.TH "Act.Cost" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Act.Cost
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBcost\fP"
.br
.ti -1c
.RI "Act\&.CostType \fBtype\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB660\fP of file \fBAct\&.2\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int Act\&.Cost\&.cost"

.PP
Definition at line \fB663\fP of file \fBAct\&.2\&.cs\fP\&.
.SS "Act\&.CostType Act\&.Cost\&.type"

.PP
Definition at line \fB666\fP of file \fBAct\&.2\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
