.TH "ActionHint" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ActionHint
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBEMono\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBRefresh\fP ()"
.br
.ti -1c
.RI "void \fBAddToggle\fP (string lang, bool on, Action< bool > action)"
.br
.ti -1c
.RI "void \fBUpdateText\fP ()"
.br
.ti -1c
.RI "void \fBShow\fP (string lang, bool icon=true)"
.br
.ti -1c
.RI "void \fBSetText\fP (string s, bool anime=false)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Transform \fBextra\fP"
.br
.ti -1c
.RI "LayoutGroup \fBlayoutDynamic\fP"
.br
.ti -1c
.RI "UIText \fBtextTitle\fP"
.br
.ti -1c
.RI "UIText \fBtextDetail\fP"
.br
.ti -1c
.RI "UIButton \fBbuttonPick\fP"
.br
.ti -1c
.RI "UIButton \fBbuttonSavePartialMap\fP"
.br
.ti -1c
.RI "UIButton \fBbuttonDeletePartialMap\fP"
.br
.ti -1c
.RI "UISelectableGroup \fBgroupRadio\fP"
.br
.ti -1c
.RI "UISelectableGroup \fBgroupToggle\fP"
.br
.ti -1c
.RI "Anime \fBanimePop\fP"
.br
.ti -1c
.RI "Image \fBiconNerun\fP"
.br
.ti -1c
.RI "CanvasGroup \fBcg\fP"
.br
.ti -1c
.RI "bool \fBdynamic\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBActionMode\fP \fBmode\fP\fR [get]\fP"
.br
.in -1c

Properties inherited from \fBEMono\fP
.in +1c
.ti -1c
.RI "static \fBGame\fP \fBgame\fP\fR [get]\fP"
.br
.ti -1c
.RI "static bool \fBAdvMode\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBPlayer\fP \fBplayer\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBChara\fP \fBpc\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBUI\fP \fBui\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBMap\fP \fB_map\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBZone\fP \fB_zone\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranchOrHomeBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFaction\fP \fBHome\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBScene\fP \fBscene\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBBaseGameScreen\fP \fBscreen\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameSetting\fP \fBsetting\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameData\fP \fBgamedata\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBColorProfile\fP \fBColors\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBWorld\fP \fBworld\fP\fR [get]\fP"
.br
.ti -1c
.RI "static SoundManager \fBSound\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBsources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBeditorSources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBCoreDebug\fP \fBdebug\fP\fR [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Static Public Member Functions inherited from \fBEMono\fP
.in +1c
.ti -1c
.RI "static int \fBrnd\fP (int a)"
.br
.in -1c

Static Public Attributes inherited from \fBEMono\fP
.in +1c
.ti -1c
.RI "static \fBCore\fP \fBcore\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB6\fP of file \fBActionHint\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void ActionHint\&.AddToggle (string lang, bool on, Action< bool > action)"

.PP
Definition at line \fB98\fP of file \fBActionHint\&.cs\fP\&.
.SS "void ActionHint\&.Refresh ()"

.PP
Definition at line \fB36\fP of file \fBActionHint\&.cs\fP\&.
.SS "void ActionHint\&.SetText (string s, bool anime = \fRfalse\fP)"

.PP
Definition at line \fB133\fP of file \fBActionHint\&.cs\fP\&.
.SS "void ActionHint\&.Show (string lang, bool icon = \fRtrue\fP)"

.PP
Definition at line \fB120\fP of file \fBActionHint\&.cs\fP\&.
.SS "void ActionHint\&.UpdateText ()"

.PP
Definition at line \fB107\fP of file \fBActionHint\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "Anime ActionHint\&.animePop"

.PP
Definition at line \fB172\fP of file \fBActionHint\&.cs\fP\&.
.SS "UIButton ActionHint\&.buttonDeletePartialMap"

.PP
Definition at line \fB163\fP of file \fBActionHint\&.cs\fP\&.
.SS "UIButton ActionHint\&.buttonPick"

.PP
Definition at line \fB157\fP of file \fBActionHint\&.cs\fP\&.
.SS "UIButton ActionHint\&.buttonSavePartialMap"

.PP
Definition at line \fB160\fP of file \fBActionHint\&.cs\fP\&.
.SS "CanvasGroup ActionHint\&.cg"

.PP
Definition at line \fB178\fP of file \fBActionHint\&.cs\fP\&.
.SS "bool ActionHint\&.dynamic"

.PP
Definition at line \fB182\fP of file \fBActionHint\&.cs\fP\&.
.SS "Transform ActionHint\&.extra"

.PP
Definition at line \fB145\fP of file \fBActionHint\&.cs\fP\&.
.SS "UISelectableGroup ActionHint\&.groupRadio"

.PP
Definition at line \fB166\fP of file \fBActionHint\&.cs\fP\&.
.SS "UISelectableGroup ActionHint\&.groupToggle"

.PP
Definition at line \fB169\fP of file \fBActionHint\&.cs\fP\&.
.SS "Image ActionHint\&.iconNerun"

.PP
Definition at line \fB175\fP of file \fBActionHint\&.cs\fP\&.
.SS "LayoutGroup ActionHint\&.layoutDynamic"

.PP
Definition at line \fB148\fP of file \fBActionHint\&.cs\fP\&.
.SS "UIText ActionHint\&.textDetail"

.PP
Definition at line \fB154\fP of file \fBActionHint\&.cs\fP\&.
.SS "UIText ActionHint\&.textTitle"

.PP
Definition at line \fB151\fP of file \fBActionHint\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "\fBActionMode\fP ActionHint\&.mode\fR [get]\fP"

.PP
Definition at line \fB10\fP of file \fBActionHint\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
