.TH "ActionMode" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ActionMode
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBEClass\fP\&.
.PP
Inherited by \fBAM_BaseGameMode\fP, \fBAM_BaseTileSelect\fP, \fBAM_MiniGame\fP, \fBAM_NewZone\fP, and \fBAM_NoMap\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual int \fBTopHeight\fP (\fBPoint\fP p)"
.br
.ti -1c
.RI "virtual void \fBSEExecuteSummary\fP ()"
.br
.ti -1c
.RI "virtual bool \fBHighlightWall\fP (\fBPoint\fP p)"
.br
.ti -1c
.RI "virtual void \fBOnClickSubMenu\fP (int a)"
.br
.ti -1c
.RI "virtual string \fBOnSetSubMenuButton\fP (int a, UIButton b)"
.br
.ti -1c
.RI "virtual bool \fBIsRoofEditMode\fP (\fBCard\fP c=null)"
.br
.ti -1c
.RI "virtual bool \fBIsFillMode\fP ()"
.br
.ti -1c
.RI "virtual int \fBGetDefaultTile\fP (\fBPoint\fP p)"
.br
.ti -1c
.RI "virtual void \fBOnShowExtraHint\fP (UINote n)"
.br
.ti -1c
.RI "void \fBActivate\fP (bool toggle=true, bool forceActivate=false)"
.br
.ti -1c
.RI "virtual void \fBOnActivate\fP ()"
.br
.ti -1c
.RI "unsafe void \fBRefreshTexts\fP ()"
.br
.ti -1c
.RI "virtual string \fBGetSimpleText\fP (\fBCard\fP c)"
.br
.ti -1c
.RI "void \fBClearSimpleTexts\fP ()"
.br
.ti -1c
.RI "void \fBDeactivate\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnDeactivate\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnCancel\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnBeforeUpdate\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnAfterUpdate\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnUpdateCursor\fP ()"
.br
.ti -1c
.RI "void \fBOnRotate\fP ()"
.br
.ti -1c
.RI "void \fBSetCursorOnMap\fP (CursorInfo cursor)"
.br
.ti -1c
.RI "void \fBUpdateInput\fP ()"
.br
.ti -1c
.RI "void \fBInputMovement\fP ()"
.br
.ti -1c
.RI "virtual void \fBInputWheel\fP (int wheel)"
.br
.ti -1c
.RI "virtual void \fBOnUpdateInput\fP ()"
.br
.ti -1c
.RI "void \fBDoFunc\fP (CoreConfig\&.GameFuncBuild func)"
.br
.ti -1c
.RI "void \fBDoFunc\fP (CoreConfig\&.GameFunc func)"
.br
.ti -1c
.RI "virtual void \fBOnScroll\fP ()"
.br
.ti -1c
.RI "void \fBTryRightClickCloseWidget\fP ()"
.br
.ti -1c
.RI "bool \fBTryShowWidgetMenu\fP ()"
.br
.ti -1c
.RI "HitResult \fB_HitTest\fP (\fBPoint\fP point, \fBPoint\fP start)"
.br
.ti -1c
.RI "virtual HitResult \fBHitTest\fP (\fBPoint\fP point, \fBPoint\fP start)"
.br
.ti -1c
.RI "virtual void \fBOnSelectStart\fP (\fBPoint\fP point)"
.br
.ti -1c
.RI "virtual void \fBOnSelectEnd\fP (bool cancel)"
.br
.ti -1c
.RI "virtual \fBMeshPass\fP \fBGetGuidePass\fP (\fBPoint\fP point)"
.br
.ti -1c
.RI "virtual unsafe void \fBOnRenderTile\fP (\fBPoint\fP point, HitResult result, int dir)"
.br
.ti -1c
.RI "unsafe void \fBOnRenderTileFloor\fP (\fBPoint\fP point, HitResult result)"
.br
.ti -1c
.RI "virtual bool \fBCanProcessTiles\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnBeforeProcessTiles\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnProcessTiles\fP (\fBPoint\fP point, int dir)"
.br
.ti -1c
.RI "virtual void \fBOnAfterProcessTiles\fP (\fBPoint\fP start, \fBPoint\fP end)"
.br
.ti -1c
.RI "virtual void \fBOnFinishProcessTiles\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnRefreshSummary\fP (\fBPoint\fP point, HitResult result, \fBHitSummary\fP summary)"
.br
.ti -1c
.RI "void \fBShowLayer\fP ()"
.br
.ti -1c
.RI "virtual Layer \fBOnShowLayer\fP ()"
.br
.ti -1c
.RI "void \fBHideLayer\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnHideLayer\fP ()"
.br
.ti -1c
.RI "virtual string \fBGetHintText\fP ()"
.br
.ti -1c
.RI "virtual void \fBRotateUnderMouse\fP ()"
.br
.ti -1c
.RI "virtual ref string \fBSetMouseInfo\fP (ref string s)"
.br
.ti -1c
.RI "void \fBTogglePause\fP ()"
.br
.ti -1c
.RI "void \fBPause\fP (bool sound=false)"
.br
.ti -1c
.RI "void \fBUnPause\fP (bool sound=false)"
.br
.ti -1c
.RI "void \fBChangeGameSpeed\fP (int a, bool sound=false)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBOnGameInstantiated\fP ()"
.br
.in -1c

Static Public Member Functions inherited from \fBEClass\fP
.in +1c
.ti -1c
.RI "static int \fBrnd\fP (int a)"
.br
.ti -1c
.RI "static int \fBcurve\fP (int a, int start, int step, int rate=75)"
.br
.ti -1c
.RI "static int \fBrndHalf\fP (int a)"
.br
.ti -1c
.RI "static float \fBrndf\fP (float a)"
.br
.ti -1c
.RI "static int \fBrndSqrt\fP (int a)"
.br
.ti -1c
.RI "static void \fBWait\fP (float a, \fBCard\fP c)"
.br
.ti -1c
.RI "static void \fBWait\fP (float a, \fBPoint\fP p)"
.br
.ti -1c
.RI "static int \fBBigger\fP (int a, int b)"
.br
.ti -1c
.RI "static int \fBSmaller\fP (int a, int b)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Layer \fBlayer\fP"
.br
.ti -1c
.RI "int \fBbrushRadius\fP = 4"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static \fBActionMode\fP \fBDefaultMode\fP"
.br
.ti -1c
.RI "static \fBAM_Title\fP \fBTitle\fP = new \fBAM_Title\fP()"
.br
.ti -1c
.RI "static \fBAM_Sim\fP \fBSim\fP"
.br
.ti -1c
.RI "static \fBAM_ViewZone\fP \fBView\fP"
.br
.ti -1c
.RI "static \fBAM_Adv\fP \fBAdv\fP"
.br
.ti -1c
.RI "static \fBAM_Region\fP \fBRegion\fP"
.br
.ti -1c
.RI "static \fBAM_ADV_Target\fP \fBAdvTarget\fP"
.br
.ti -1c
.RI "static \fBAM_EloMap\fP \fBEloMap\fP"
.br
.ti -1c
.RI "static \fBAM_Inspect\fP \fBInspect\fP"
.br
.ti -1c
.RI "static \fBAM_NoMap\fP \fBNoMap\fP"
.br
.ti -1c
.RI "static \fBAM_MiniGame\fP \fBMiniGame\fP"
.br
.ti -1c
.RI "static \fBAM_NewZone\fP \fBNewZone\fP"
.br
.ti -1c
.RI "static \fBAM_Bird\fP \fBBird\fP"
.br
.ti -1c
.RI "static \fBAM_Mine\fP \fBMine\fP"
.br
.ti -1c
.RI "static \fBAM_Dig\fP \fBDig\fP"
.br
.ti -1c
.RI "static \fBAM_Harvest\fP \fBHarvest\fP"
.br
.ti -1c
.RI "static \fBAM_Cut\fP \fBCut\fP"
.br
.ti -1c
.RI "static \fBAM_StateEditor\fP \fBStateEditor\fP"
.br
.ti -1c
.RI "static \fBAM_Picker\fP \fBPicker\fP"
.br
.ti -1c
.RI "static \fBAM_Copy\fP \fBCopy\fP"
.br
.ti -1c
.RI "static \fBAM_Blueprint\fP \fBBlueprint\fP"
.br
.ti -1c
.RI "static \fBAM_Build\fP \fBBuild\fP"
.br
.ti -1c
.RI "static \fBAM_CreateArea\fP \fBCreateArea\fP"
.br
.ti -1c
.RI "static \fBAM_EditArea\fP \fBEditArea\fP"
.br
.ti -1c
.RI "static \fBAM_ExpandArea\fP \fBExpandArea\fP"
.br
.ti -1c
.RI "static \fBAM_Deconstruct\fP \fBDeconstruct\fP"
.br
.ti -1c
.RI "static \fBAM_Select\fP \fBSelect\fP"
.br
.ti -1c
.RI "static \fBAM_RemoveDesignation\fP \fBRemoveDesignation\fP"
.br
.ti -1c
.RI "static \fBAM_ViewMap\fP \fBViewMap\fP"
.br
.ti -1c
.RI "static \fBAM_Terrain\fP \fBTerrain\fP"
.br
.ti -1c
.RI "static \fBAM_Populate\fP \fBPopulate\fP"
.br
.ti -1c
.RI "static \fBAM_EditMarker\fP \fBEditMarker\fP"
.br
.ti -1c
.RI "static \fBAM_Visibility\fP \fBVisibility\fP"
.br
.ti -1c
.RI "static \fBAM_Cinema\fP \fBCinema\fP"
.br
.ti -1c
.RI "static \fBAM_Paint\fP \fBPaint\fP"
.br
.ti -1c
.RI "static \fBAM_FlagCell\fP \fBFlagCell\fP"
.br
.ti -1c
.RI "static \fBActionMode\fP \fBLastBuildMode\fP"
.br
.ti -1c
.RI "static \fBSourceMaterial\&.Row\fP \fBlastEditorMat\fP"
.br
.ti -1c
.RI "static bool \fBignoreSound\fP"
.br
.ti -1c
.RI "static float[] \fBGameSpeeds\fP"
.br
.ti -1c
.RI "static List< \fBTCSimpleText\fP > \fBsimpleTexts\fP = new List<\fBTCSimpleText\fP>()"
.br
.in -1c

Static Public Attributes inherited from \fBEClass\fP
.in +1c
.ti -1c
.RI "static \fBCore\fP \fBcore\fP"
.br
.in -1c
.SS "Static Protected Attributes"

.in +1c
.ti -1c
.RI "static Vector3 \fBmpos\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "static \fBAM_Adv\fP \fBAdvOrRegion\fP\fR [get]\fP"
.br
.ti -1c
.RI "static bool \fBIsAdv\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual float \fBgameSpeed\fP\fR [get]\fP"
.br
.ti -1c
.RI "bool \fBIsActive\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual BaseTileSelector\&.HitType \fBhitType\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual BaseTileSelector\&.SelectType \fBselectType\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual BaseTileSelector\&.BoxType \fBboxType\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBContinuousClick\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual int \fBhitW\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual int \fBhitH\fP\fR [get]\fP"
.br
.ti -1c
.RI "\fBHitSummary\fP \fBSummary\fP\fR [get]\fP"
.br
.ti -1c
.RI "bool \fBMultisize\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual string \fBid\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual CursorInfo \fBDefaultCursor\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual string \fBidHelpTopic\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual string \fBidSound\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBenableMouseInfo\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBhideBalloon\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual string \fBtextHintTitle\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBAllowAutoClick\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBShowActionHint\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBShowMouseoverTarget\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual AreaHighlightMode \fBAreaHihlight\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBCanSelectTile\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBCanTargetOutsideBounds\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBShouldPauseGame\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBFixFocus\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBHideSubWidgets\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBIsBuildMode\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBShowBuildWidgets\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual BuildMenu\&.Mode \fBbuildMenuMode\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBShouldHideBuildMenu\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBCanTargetFog\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual int \fBCostMoney\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBAllowBuildModeShortcuts\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBAllowMiddleClickFunc\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBAllowHotbar\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBAllowGeneralInput\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBShowMaskedThings\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual int \fBSelectorHeight\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBAllowWheelZoom\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual float \fBTargetZoom\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual BaseTileMap\&.CardIconMode \fBcardIconMode\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual \fBBaseGameScreen\fP \fBTargetGameScreen\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBIsNoMap\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBUseSubMenu\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBUseSubMenuSlider\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBSubMenuAsGroup\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual int \fBSubMenuModeIndex\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBShowExtraHint\fP\fR [get]\fP"
.br
.ti -1c
.RI "\fBBaseTileSelector\fP \fBtileSelector\fP\fR [get]\fP"
.br
.in -1c

Properties inherited from \fBEClass\fP
.in +1c
.ti -1c
.RI "static \fBGame\fP \fBgame\fP\fR [get]\fP"
.br
.ti -1c
.RI "static bool \fBAdvMode\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBPlayer\fP \fBplayer\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBChara\fP \fBpc\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBUI\fP \fBui\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBMap\fP \fB_map\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBZone\fP \fB_zone\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranchOrHomeBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFaction\fP \fBHome\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFaction\fP \fBWilds\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBScene\fP \fBscene\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBBaseGameScreen\fP \fBscreen\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameSetting\fP \fBsetting\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameData\fP \fBgamedata\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBColorProfile\fP \fBColors\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBWorld\fP \fBworld\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBsources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBeditorSources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static SoundManager \fBSound\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBCoreDebug\fP \fBdebug\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB7\fP of file \fBActionMode\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "HitResult ActionMode\&._HitTest (\fBPoint\fP point, \fBPoint\fP start)"

.PP
Definition at line \fB1492\fP of file \fBActionMode\&.cs\fP\&.
.SS "void ActionMode\&.Activate (bool toggle = \fRtrue\fP, bool forceActivate = \fRfalse\fP)"

.PP
Definition at line \fB630\fP of file \fBActionMode\&.cs\fP\&.
.SS "virtual bool ActionMode\&.CanProcessTiles ()\fR [virtual]\fP"

.PP
Definition at line \fB1586\fP of file \fBActionMode\&.cs\fP\&.
.SS "void ActionMode\&.ChangeGameSpeed (int a, bool sound = \fRfalse\fP)"

.PP
Definition at line \fB1778\fP of file \fBActionMode\&.cs\fP\&.
.SS "void ActionMode\&.ClearSimpleTexts ()"

.PP
Definition at line \fB806\fP of file \fBActionMode\&.cs\fP\&.
.SS "void ActionMode\&.Deactivate ()"

.PP
Definition at line \fB819\fP of file \fBActionMode\&.cs\fP\&.
.SS "void ActionMode\&.DoFunc (CoreConfig\&.GameFunc func)"

.PP
Definition at line \fB1362\fP of file \fBActionMode\&.cs\fP\&.
.SS "void ActionMode\&.DoFunc (CoreConfig\&.GameFuncBuild func)"

.PP
Definition at line \fB1323\fP of file \fBActionMode\&.cs\fP\&.
.SS "virtual int ActionMode\&.GetDefaultTile (\fBPoint\fP p)\fR [virtual]\fP"

.PP
Definition at line \fB590\fP of file \fBActionMode\&.cs\fP\&.
.SS "virtual \fBMeshPass\fP ActionMode\&.GetGuidePass (\fBPoint\fP point)\fR [virtual]\fP"

.PP
Definition at line \fB1526\fP of file \fBActionMode\&.cs\fP\&.
.SS "virtual string ActionMode\&.GetHintText ()\fR [virtual]\fP"

.PP
Definition at line \fB1661\fP of file \fBActionMode\&.cs\fP\&.
.SS "virtual string ActionMode\&.GetSimpleText (\fBCard\fP c)\fR [virtual]\fP"

.PP
Definition at line \fB796\fP of file \fBActionMode\&.cs\fP\&.
.SS "void ActionMode\&.HideLayer ()"

.PP
Definition at line \fB1647\fP of file \fBActionMode\&.cs\fP\&.
.SS "virtual bool ActionMode\&.HighlightWall (\fBPoint\fP p)\fR [virtual]\fP"

.PP
Definition at line \fB551\fP of file \fBActionMode\&.cs\fP\&.
.SS "virtual HitResult ActionMode\&.HitTest (\fBPoint\fP point, \fBPoint\fP start)\fR [virtual]\fP"

.PP
Definition at line \fB1510\fP of file \fBActionMode\&.cs\fP\&.
.SS "void ActionMode\&.InputMovement ()"

.PP
Definition at line \fB1221\fP of file \fBActionMode\&.cs\fP\&.
.SS "virtual void ActionMode\&.InputWheel (int wheel)\fR [virtual]\fP"

.PP
Definition at line \fB1309\fP of file \fBActionMode\&.cs\fP\&.
.SS "virtual bool ActionMode\&.IsFillMode ()\fR [virtual]\fP"

.PP
Definition at line \fB584\fP of file \fBActionMode\&.cs\fP\&.
.SS "virtual bool ActionMode\&.IsRoofEditMode (\fBCard\fP c = \fRnull\fP)\fR [virtual]\fP"

.PP
Definition at line \fB578\fP of file \fBActionMode\&.cs\fP\&.
.SS "virtual void ActionMode\&.OnActivate ()\fR [virtual]\fP"

.PP
Definition at line \fB705\fP of file \fBActionMode\&.cs\fP\&.
.SS "virtual void ActionMode\&.OnAfterProcessTiles (\fBPoint\fP start, \fBPoint\fP end)\fR [virtual]\fP"

.PP
Definition at line \fB1602\fP of file \fBActionMode\&.cs\fP\&.
.SS "virtual void ActionMode\&.OnAfterUpdate ()\fR [virtual]\fP"

.PP
Definition at line \fB845\fP of file \fBActionMode\&.cs\fP\&.
.SS "virtual void ActionMode\&.OnBeforeProcessTiles ()\fR [virtual]\fP"

.PP
Definition at line \fB1592\fP of file \fBActionMode\&.cs\fP\&.
.SS "virtual void ActionMode\&.OnBeforeUpdate ()\fR [virtual]\fP"

.PP
Definition at line \fB840\fP of file \fBActionMode\&.cs\fP\&.
.SS "virtual void ActionMode\&.OnCancel ()\fR [virtual]\fP"

.PP
Definition at line \fB830\fP of file \fBActionMode\&.cs\fP\&.
.SS "virtual void ActionMode\&.OnClickSubMenu (int a)\fR [virtual]\fP"

.PP
Definition at line \fB567\fP of file \fBActionMode\&.cs\fP\&.
.SS "virtual void ActionMode\&.OnDeactivate ()\fR [virtual]\fP"

.PP
Definition at line \fB825\fP of file \fBActionMode\&.cs\fP\&.
.SS "virtual void ActionMode\&.OnFinishProcessTiles ()\fR [virtual]\fP"

.PP
Definition at line \fB1607\fP of file \fBActionMode\&.cs\fP\&.
.SS "static void ActionMode\&.OnGameInstantiated ()\fR [static]\fP"

.PP
Definition at line \fB34\fP of file \fBActionMode\&.cs\fP\&.
.SS "virtual void ActionMode\&.OnHideLayer ()\fR [virtual]\fP"

.PP
Definition at line \fB1656\fP of file \fBActionMode\&.cs\fP\&.
.SS "virtual void ActionMode\&.OnProcessTiles (\fBPoint\fP point, int dir)\fR [virtual]\fP"

.PP
Definition at line \fB1597\fP of file \fBActionMode\&.cs\fP\&.
.SS "virtual void ActionMode\&.OnRefreshSummary (\fBPoint\fP point, HitResult result, \fBHitSummary\fP summary)\fR [virtual]\fP"

.PP
Definition at line \fB1612\fP of file \fBActionMode\&.cs\fP\&.
.SS "virtual unsafe void ActionMode\&.OnRenderTile (\fBPoint\fP point, HitResult result, int dir)\fR [virtual]\fP"

.PP
Definition at line \fB1536\fP of file \fBActionMode\&.cs\fP\&.
.SS "unsafe void ActionMode\&.OnRenderTileFloor (\fBPoint\fP point, HitResult result)"

.PP
Definition at line \fB1565\fP of file \fBActionMode\&.cs\fP\&.
.SS "void ActionMode\&.OnRotate ()"

.PP
Definition at line \fB857\fP of file \fBActionMode\&.cs\fP\&.
.SS "virtual void ActionMode\&.OnScroll ()\fR [virtual]\fP"

.PP
Definition at line \fB1460\fP of file \fBActionMode\&.cs\fP\&.
.SS "virtual void ActionMode\&.OnSelectEnd (bool cancel)\fR [virtual]\fP"

.PP
Definition at line \fB1521\fP of file \fBActionMode\&.cs\fP\&.
.SS "virtual void ActionMode\&.OnSelectStart (\fBPoint\fP point)\fR [virtual]\fP"

.PP
Definition at line \fB1516\fP of file \fBActionMode\&.cs\fP\&.
.SS "virtual string ActionMode\&.OnSetSubMenuButton (int a, UIButton b)\fR [virtual]\fP"

.PP
Definition at line \fB572\fP of file \fBActionMode\&.cs\fP\&.
.SS "virtual void ActionMode\&.OnShowExtraHint (UINote n)\fR [virtual]\fP"

.PP
Definition at line \fB606\fP of file \fBActionMode\&.cs\fP\&.
.SS "virtual Layer ActionMode\&.OnShowLayer ()\fR [virtual]\fP"

.PP
Definition at line \fB1641\fP of file \fBActionMode\&.cs\fP\&.
.SS "virtual void ActionMode\&.OnUpdateCursor ()\fR [virtual]\fP"

.PP
Definition at line \fB850\fP of file \fBActionMode\&.cs\fP\&.
.SS "virtual void ActionMode\&.OnUpdateInput ()\fR [virtual]\fP"

.PP
Definition at line \fB1318\fP of file \fBActionMode\&.cs\fP\&.
.SS "void ActionMode\&.Pause (bool sound = \fRfalse\fP)"

.PP
Definition at line \fB1766\fP of file \fBActionMode\&.cs\fP\&.
.SS "unsafe void ActionMode\&.RefreshTexts ()"

.PP
Definition at line \fB710\fP of file \fBActionMode\&.cs\fP\&.
.SS "virtual void ActionMode\&.RotateUnderMouse ()\fR [virtual]\fP"

.PP
Definition at line \fB1708\fP of file \fBActionMode\&.cs\fP\&.
.SS "virtual void ActionMode\&.SEExecuteSummary ()\fR [virtual]\fP"

.PP
Definition at line \fB515\fP of file \fBActionMode\&.cs\fP\&.
.SS "void ActionMode\&.SetCursorOnMap (CursorInfo cursor)"

.PP
Definition at line \fB863\fP of file \fBActionMode\&.cs\fP\&.
.SS "virtual ref string ActionMode\&.SetMouseInfo (ref string s)\fR [virtual]\fP"

.PP
Definition at line \fB1734\fP of file \fBActionMode\&.cs\fP\&.
.SS "void ActionMode\&.ShowLayer ()"

.PP
Definition at line \fB1622\fP of file \fBActionMode\&.cs\fP\&.
.SS "void ActionMode\&.TogglePause ()"

.PP
Definition at line \fB1740\fP of file \fBActionMode\&.cs\fP\&.
.SS "virtual int ActionMode\&.TopHeight (\fBPoint\fP p)\fR [virtual]\fP"

.PP
Definition at line \fB469\fP of file \fBActionMode\&.cs\fP\&.
.SS "void ActionMode\&.TryRightClickCloseWidget ()"

.PP
Definition at line \fB1465\fP of file \fBActionMode\&.cs\fP\&.
.SS "bool ActionMode\&.TryShowWidgetMenu ()"

.PP
Definition at line \fB1475\fP of file \fBActionMode\&.cs\fP\&.
.SS "void ActionMode\&.UnPause (bool sound = \fRfalse\fP)"

.PP
Definition at line \fB1772\fP of file \fBActionMode\&.cs\fP\&.
.SS "void ActionMode\&.UpdateInput ()"

.PP
Definition at line \fB869\fP of file \fBActionMode\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBAM_Adv\fP ActionMode\&.Adv\fR [static]\fP"

.PP
Definition at line \fB1809\fP of file \fBActionMode\&.cs\fP\&.
.SS "\fBAM_ADV_Target\fP ActionMode\&.AdvTarget\fR [static]\fP"

.PP
Definition at line \fB1815\fP of file \fBActionMode\&.cs\fP\&.
.SS "\fBAM_Bird\fP ActionMode\&.Bird\fR [static]\fP"

.PP
Definition at line \fB1833\fP of file \fBActionMode\&.cs\fP\&.
.SS "\fBAM_Blueprint\fP ActionMode\&.Blueprint\fR [static]\fP"

.PP
Definition at line \fB1857\fP of file \fBActionMode\&.cs\fP\&.
.SS "int ActionMode\&.brushRadius = 4"

.PP
Definition at line \fB1941\fP of file \fBActionMode\&.cs\fP\&.
.SS "\fBAM_Build\fP ActionMode\&.Build\fR [static]\fP"

.PP
Definition at line \fB1860\fP of file \fBActionMode\&.cs\fP\&.
.SS "\fBAM_Cinema\fP ActionMode\&.Cinema\fR [static]\fP"

.PP
Definition at line \fB1896\fP of file \fBActionMode\&.cs\fP\&.
.SS "\fBAM_Copy\fP ActionMode\&.Copy\fR [static]\fP"

.PP
Definition at line \fB1854\fP of file \fBActionMode\&.cs\fP\&.
.SS "\fBAM_CreateArea\fP ActionMode\&.CreateArea\fR [static]\fP"

.PP
Definition at line \fB1863\fP of file \fBActionMode\&.cs\fP\&.
.SS "\fBAM_Cut\fP ActionMode\&.Cut\fR [static]\fP"

.PP
Definition at line \fB1845\fP of file \fBActionMode\&.cs\fP\&.
.SS "\fBAM_Deconstruct\fP ActionMode\&.Deconstruct\fR [static]\fP"

.PP
Definition at line \fB1872\fP of file \fBActionMode\&.cs\fP\&.
.SS "\fBActionMode\fP ActionMode\&.DefaultMode\fR [static]\fP"

.PP
Definition at line \fB1797\fP of file \fBActionMode\&.cs\fP\&.
.SS "\fBAM_Dig\fP ActionMode\&.Dig\fR [static]\fP"

.PP
Definition at line \fB1839\fP of file \fBActionMode\&.cs\fP\&.
.SS "\fBAM_EditArea\fP ActionMode\&.EditArea\fR [static]\fP"

.PP
Definition at line \fB1866\fP of file \fBActionMode\&.cs\fP\&.
.SS "\fBAM_EditMarker\fP ActionMode\&.EditMarker\fR [static]\fP"

.PP
Definition at line \fB1890\fP of file \fBActionMode\&.cs\fP\&.
.SS "\fBAM_EloMap\fP ActionMode\&.EloMap\fR [static]\fP"

.PP
Definition at line \fB1818\fP of file \fBActionMode\&.cs\fP\&.
.SS "\fBAM_ExpandArea\fP ActionMode\&.ExpandArea\fR [static]\fP"

.PP
Definition at line \fB1869\fP of file \fBActionMode\&.cs\fP\&.
.SS "\fBAM_FlagCell\fP ActionMode\&.FlagCell\fR [static]\fP"

.PP
Definition at line \fB1902\fP of file \fBActionMode\&.cs\fP\&.
.SS "float [] ActionMode\&.GameSpeeds\fR [static]\fP"
\fBInitial value:\fP
.nf
= new float[]
    {
        0f,
        1f,
        2f,
        5f
    }
.PP
.fi

.PP
Definition at line \fB1926\fP of file \fBActionMode\&.cs\fP\&.
.SS "\fBAM_Harvest\fP ActionMode\&.Harvest\fR [static]\fP"

.PP
Definition at line \fB1842\fP of file \fBActionMode\&.cs\fP\&.
.SS "bool ActionMode\&.ignoreSound\fR [static]\fP"

.PP
Definition at line \fB1911\fP of file \fBActionMode\&.cs\fP\&.
.SS "\fBAM_Inspect\fP ActionMode\&.Inspect\fR [static]\fP"

.PP
Definition at line \fB1821\fP of file \fBActionMode\&.cs\fP\&.
.SS "\fBActionMode\fP ActionMode\&.LastBuildMode\fR [static]\fP"

.PP
Definition at line \fB1905\fP of file \fBActionMode\&.cs\fP\&.
.SS "\fBSourceMaterial\&.Row\fP ActionMode\&.lastEditorMat\fR [static]\fP"

.PP
Definition at line \fB1908\fP of file \fBActionMode\&.cs\fP\&.
.SS "Layer ActionMode\&.layer"

.PP
Definition at line \fB1938\fP of file \fBActionMode\&.cs\fP\&.
.SS "\fBAM_Mine\fP ActionMode\&.Mine\fR [static]\fP"

.PP
Definition at line \fB1836\fP of file \fBActionMode\&.cs\fP\&.
.SS "\fBAM_MiniGame\fP ActionMode\&.MiniGame\fR [static]\fP"

.PP
Definition at line \fB1827\fP of file \fBActionMode\&.cs\fP\&.
.SS "Vector3 ActionMode\&.mpos\fR [static]\fP, \fR [protected]\fP"

.PP
Definition at line \fB1923\fP of file \fBActionMode\&.cs\fP\&.
.SS "\fBAM_NewZone\fP ActionMode\&.NewZone\fR [static]\fP"

.PP
Definition at line \fB1830\fP of file \fBActionMode\&.cs\fP\&.
.SS "\fBAM_NoMap\fP ActionMode\&.NoMap\fR [static]\fP"

.PP
Definition at line \fB1824\fP of file \fBActionMode\&.cs\fP\&.
.SS "\fBAM_Paint\fP ActionMode\&.Paint\fR [static]\fP"

.PP
Definition at line \fB1899\fP of file \fBActionMode\&.cs\fP\&.
.SS "\fBAM_Picker\fP ActionMode\&.Picker\fR [static]\fP"

.PP
Definition at line \fB1851\fP of file \fBActionMode\&.cs\fP\&.
.SS "\fBAM_Populate\fP ActionMode\&.Populate\fR [static]\fP"

.PP
Definition at line \fB1887\fP of file \fBActionMode\&.cs\fP\&.
.SS "\fBAM_Region\fP ActionMode\&.Region\fR [static]\fP"

.PP
Definition at line \fB1812\fP of file \fBActionMode\&.cs\fP\&.
.SS "\fBAM_RemoveDesignation\fP ActionMode\&.RemoveDesignation\fR [static]\fP"

.PP
Definition at line \fB1878\fP of file \fBActionMode\&.cs\fP\&.
.SS "\fBAM_Select\fP ActionMode\&.Select\fR [static]\fP"

.PP
Definition at line \fB1875\fP of file \fBActionMode\&.cs\fP\&.
.SS "\fBAM_Sim\fP ActionMode\&.Sim\fR [static]\fP"

.PP
Definition at line \fB1803\fP of file \fBActionMode\&.cs\fP\&.
.SS "List<\fBTCSimpleText\fP> ActionMode\&.simpleTexts = new List<\fBTCSimpleText\fP>()\fR [static]\fP"

.PP
Definition at line \fB1935\fP of file \fBActionMode\&.cs\fP\&.
.SS "\fBAM_StateEditor\fP ActionMode\&.StateEditor\fR [static]\fP"

.PP
Definition at line \fB1848\fP of file \fBActionMode\&.cs\fP\&.
.SS "\fBAM_Terrain\fP ActionMode\&.Terrain\fR [static]\fP"

.PP
Definition at line \fB1884\fP of file \fBActionMode\&.cs\fP\&.
.SS "\fBAM_Title\fP ActionMode\&.Title = new \fBAM_Title\fP()\fR [static]\fP"

.PP
Definition at line \fB1800\fP of file \fBActionMode\&.cs\fP\&.
.SS "\fBAM_ViewZone\fP ActionMode\&.View\fR [static]\fP"

.PP
Definition at line \fB1806\fP of file \fBActionMode\&.cs\fP\&.
.SS "\fBAM_ViewMap\fP ActionMode\&.ViewMap\fR [static]\fP"

.PP
Definition at line \fB1881\fP of file \fBActionMode\&.cs\fP\&.
.SS "\fBAM_Visibility\fP ActionMode\&.Visibility\fR [static]\fP"

.PP
Definition at line \fB1893\fP of file \fBActionMode\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "\fBAM_Adv\fP ActionMode\&.AdvOrRegion\fR [static]\fP, \fR [get]\fP"

.PP
Definition at line \fB11\fP of file \fBActionMode\&.cs\fP\&.
.SS "virtual bool ActionMode\&.AllowAutoClick\fR [get]\fP"

.PP
Definition at line \fB246\fP of file \fBActionMode\&.cs\fP\&.
.SS "virtual bool ActionMode\&.AllowBuildModeShortcuts\fR [get]\fP"

.PP
Definition at line \fB400\fP of file \fBActionMode\&.cs\fP\&.
.SS "virtual bool ActionMode\&.AllowGeneralInput\fR [get]\fP"

.PP
Definition at line \fB430\fP of file \fBActionMode\&.cs\fP\&.
.SS "virtual bool ActionMode\&.AllowHotbar\fR [get]\fP"

.PP
Definition at line \fB420\fP of file \fBActionMode\&.cs\fP\&.
.SS "virtual bool ActionMode\&.AllowMiddleClickFunc\fR [get]\fP"

.PP
Definition at line \fB410\fP of file \fBActionMode\&.cs\fP\&.
.SS "virtual bool ActionMode\&.AllowWheelZoom\fR [get]\fP"

.PP
Definition at line \fB460\fP of file \fBActionMode\&.cs\fP\&.
.SS "virtual AreaHighlightMode ActionMode\&.AreaHihlight\fR [get]\fP"

.PP
Definition at line \fB276\fP of file \fBActionMode\&.cs\fP\&.
.SS "virtual BaseTileSelector\&.BoxType ActionMode\&.boxType\fR [get]\fP"

.PP
Definition at line \fB116\fP of file \fBActionMode\&.cs\fP\&.
.SS "virtual BuildMenu\&.Mode ActionMode\&.buildMenuMode\fR [get]\fP"

.PP
Definition at line \fB356\fP of file \fBActionMode\&.cs\fP\&.
.SS "virtual bool ActionMode\&.CanSelectTile\fR [get]\fP"

.PP
Definition at line \fB286\fP of file \fBActionMode\&.cs\fP\&.
.SS "virtual bool ActionMode\&.CanTargetFog\fR [get]\fP"

.PP
Definition at line \fB380\fP of file \fBActionMode\&.cs\fP\&.
.SS "virtual bool ActionMode\&.CanTargetOutsideBounds\fR [get]\fP"

.PP
Definition at line \fB296\fP of file \fBActionMode\&.cs\fP\&.
.SS "virtual BaseTileMap\&.CardIconMode ActionMode\&.cardIconMode\fR [get]\fP"

.PP
Definition at line \fB486\fP of file \fBActionMode\&.cs\fP\&.
.SS "virtual bool ActionMode\&.ContinuousClick\fR [get]\fP"

.PP
Definition at line \fB126\fP of file \fBActionMode\&.cs\fP\&.
.SS "virtual int ActionMode\&.CostMoney\fR [get]\fP"

.PP
Definition at line \fB390\fP of file \fBActionMode\&.cs\fP\&.
.SS "virtual CursorInfo ActionMode\&.DefaultCursor\fR [get]\fP"

.PP
Definition at line \fB186\fP of file \fBActionMode\&.cs\fP\&.
.SS "virtual bool ActionMode\&.enableMouseInfo\fR [get]\fP"

.PP
Definition at line \fB216\fP of file \fBActionMode\&.cs\fP\&.
.SS "virtual bool ActionMode\&.FixFocus\fR [get]\fP"

.PP
Definition at line \fB316\fP of file \fBActionMode\&.cs\fP\&.
.SS "virtual float ActionMode\&.gameSpeed\fR [get]\fP"

.PP
Definition at line \fB76\fP of file \fBActionMode\&.cs\fP\&.
.SS "virtual bool ActionMode\&.hideBalloon\fR [get]\fP"

.PP
Definition at line \fB226\fP of file \fBActionMode\&.cs\fP\&.
.SS "virtual bool ActionMode\&.HideSubWidgets\fR [get]\fP"

.PP
Definition at line \fB326\fP of file \fBActionMode\&.cs\fP\&.
.SS "virtual int ActionMode\&.hitH\fR [get]\fP"

.PP
Definition at line \fB146\fP of file \fBActionMode\&.cs\fP\&.
.SS "virtual BaseTileSelector\&.HitType ActionMode\&.hitType\fR [get]\fP"

.PP
Definition at line \fB96\fP of file \fBActionMode\&.cs\fP\&.
.SS "virtual int ActionMode\&.hitW\fR [get]\fP"

.PP
Definition at line \fB136\fP of file \fBActionMode\&.cs\fP\&.
.SS "virtual string ActionMode\&.id\fR [get]\fP"

.PP
Definition at line \fB176\fP of file \fBActionMode\&.cs\fP\&.
.SS "virtual string ActionMode\&.idHelpTopic\fR [get]\fP"

.PP
Definition at line \fB196\fP of file \fBActionMode\&.cs\fP\&.
.SS "virtual string ActionMode\&.idSound\fR [get]\fP"

.PP
Definition at line \fB206\fP of file \fBActionMode\&.cs\fP\&.
.SS "bool ActionMode\&.IsActive\fR [get]\fP"

.PP
Definition at line \fB86\fP of file \fBActionMode\&.cs\fP\&.
.SS "bool ActionMode\&.IsAdv\fR [static]\fP, \fR [get]\fP"

.PP
Definition at line \fB25\fP of file \fBActionMode\&.cs\fP\&.
.SS "virtual bool ActionMode\&.IsBuildMode\fR [get]\fP"

.PP
Definition at line \fB336\fP of file \fBActionMode\&.cs\fP\&.
.SS "virtual bool ActionMode\&.IsNoMap\fR [get]\fP"

.PP
Definition at line \fB506\fP of file \fBActionMode\&.cs\fP\&.
.SS "bool ActionMode\&.Multisize\fR [get]\fP"

.PP
Definition at line \fB166\fP of file \fBActionMode\&.cs\fP\&.
.SS "virtual int ActionMode\&.SelectorHeight\fR [get]\fP"

.PP
Definition at line \fB450\fP of file \fBActionMode\&.cs\fP\&.
.SS "virtual BaseTileSelector\&.SelectType ActionMode\&.selectType\fR [get]\fP"

.PP
Definition at line \fB106\fP of file \fBActionMode\&.cs\fP\&.
.SS "virtual bool ActionMode\&.ShouldHideBuildMenu\fR [get]\fP"

.PP
Definition at line \fB370\fP of file \fBActionMode\&.cs\fP\&.
.SS "virtual bool ActionMode\&.ShouldPauseGame\fR [get]\fP"

.PP
Definition at line \fB306\fP of file \fBActionMode\&.cs\fP\&.
.SS "virtual bool ActionMode\&.ShowActionHint\fR [get]\fP"

.PP
Definition at line \fB256\fP of file \fBActionMode\&.cs\fP\&.
.SS "virtual bool ActionMode\&.ShowBuildWidgets\fR [get]\fP"

.PP
Definition at line \fB346\fP of file \fBActionMode\&.cs\fP\&.
.SS "virtual bool ActionMode\&.ShowExtraHint\fR [get]\fP"

.PP
Definition at line \fB597\fP of file \fBActionMode\&.cs\fP\&.
.SS "virtual bool ActionMode\&.ShowMaskedThings\fR [get]\fP"

.PP
Definition at line \fB440\fP of file \fBActionMode\&.cs\fP\&.
.SS "virtual bool ActionMode\&.ShowMouseoverTarget\fR [get]\fP"

.PP
Definition at line \fB266\fP of file \fBActionMode\&.cs\fP\&.
.SS "virtual bool ActionMode\&.SubMenuAsGroup\fR [get]\fP"

.PP
Definition at line \fB542\fP of file \fBActionMode\&.cs\fP\&.
.SS "virtual int ActionMode\&.SubMenuModeIndex\fR [get]\fP"

.PP
Definition at line \fB558\fP of file \fBActionMode\&.cs\fP\&.
.SS "\fBHitSummary\fP ActionMode\&.Summary\fR [get]\fP"

.PP
Definition at line \fB156\fP of file \fBActionMode\&.cs\fP\&.
.SS "virtual \fBBaseGameScreen\fP ActionMode\&.TargetGameScreen\fR [get]\fP"

.PP
Definition at line \fB496\fP of file \fBActionMode\&.cs\fP\&.
.SS "virtual float ActionMode\&.TargetZoom\fR [get]\fP"

.PP
Definition at line \fB476\fP of file \fBActionMode\&.cs\fP\&.
.SS "virtual string ActionMode\&.textHintTitle\fR [get]\fP"

.PP
Definition at line \fB236\fP of file \fBActionMode\&.cs\fP\&.
.SS "\fBBaseTileSelector\fP ActionMode\&.tileSelector\fR [get]\fP"

.PP
Definition at line \fB621\fP of file \fBActionMode\&.cs\fP\&.
.SS "virtual bool ActionMode\&.UseSubMenu\fR [get]\fP"

.PP
Definition at line \fB522\fP of file \fBActionMode\&.cs\fP\&.
.SS "virtual bool ActionMode\&.UseSubMenuSlider\fR [get]\fP"

.PP
Definition at line \fB532\fP of file \fBActionMode\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
