.TH "ActList.Item" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ActList.Item
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBAct\fP \fBact\fP"
.br
.ti -1c
.RI "int \fBchance\fP"
.br
.ti -1c
.RI "bool \fBpt\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB11\fP of file \fBActList\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBAct\fP ActList\&.Item\&.act"

.PP
Definition at line \fB14\fP of file \fBActList\&.cs\fP\&.
.SS "int ActList\&.Item\&.chance"

.PP
Definition at line \fB17\fP of file \fBActList\&.cs\fP\&.
.SS "bool ActList\&.Item\&.pt"

.PP
Definition at line \fB20\fP of file \fBActList\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
