.TH "ActPlan" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ActPlan
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBEClass\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBItem\fP"
.br
.ti -1c
.RI "class \fBList\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "string \fBGetText\fP (bool showName)"
.br
.ti -1c
.RI "Func< bool > \fBGetAction\fP ()"
.br
.ti -1c
.RI "void \fBShowContextMenu\fP ()"
.br
.ti -1c
.RI "bool \fBTrySetAct\fP (string lang, Func< bool > onPerform, \fBCard\fP tc, CursorInfo cursor=null, int dist=1, bool isHostileAct=false, bool localAct=true, bool canRepeat=false)"
.br
.ti -1c
.RI "bool \fBTrySetAct\fP (string lang, Func< bool > onPerform, CursorInfo cursor=null, int dist=1)"
.br
.ti -1c
.RI "bool \fBTrySetAct\fP (\fBAct\fP _act, \fBCard\fP _tc=null)"
.br
.ti -1c
.RI "void \fBClear\fP ()"
.br
.ti -1c
.RI "void \fBUpdate\fP (\fBPointTarget\fP target)"
.br
.ti -1c
.RI "void \fB_Update\fP (\fBPointTarget\fP target)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBPoint\fP \fBpos\fP = new \fBPoint\fP()"
.br
.ti -1c
.RI "ActInput \fBinput\fP"
.br
.ti -1c
.RI "bool \fBperformed\fP"
.br
.ti -1c
.RI "bool \fBaltAction\fP"
.br
.ti -1c
.RI "bool \fBignoreAdddCondition\fP"
.br
.ti -1c
.RI "\fBActPlan\&.List\fP \fBlist\fP = new \fBActPlan\&.List\fP()"
.br
.ti -1c
.RI "int \fBdist\fP"
.br
.ti -1c
.RI "\fBThing\fP \fBtool\fP"
.br
.ti -1c
.RI "\fBList\fP< \fBThing\fP > \fBlistPick\fP = new \fBList\fP<\fBThing\fP>()"
.br
.ti -1c
.RI "\fBAct\fP \fBlastAct\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static bool \fBwarning\fP"
.br
.in -1c

Static Public Attributes inherited from \fBEClass\fP
.in +1c
.ti -1c
.RI "static \fBCore\fP \fBcore\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "bool \fBIsSelf\fP\fR [get]\fP"
.br
.ti -1c
.RI "bool \fBIsSelfOrNeighbor\fP\fR [get]\fP"
.br
.ti -1c
.RI "bool \fBIsNeighborBlocked\fP\fR [get]\fP"
.br
.ti -1c
.RI "bool \fBcanRepeat\fP\fR [get]\fP"
.br
.ti -1c
.RI "\fBChara\fP \fBcc\fP\fR [get]\fP"
.br
.ti -1c
.RI "CursorInfo \fBCursorIcon\fP\fR [get]\fP"
.br
.ti -1c
.RI "bool \fBWillEndTurn\fP\fR [get]\fP"
.br
.ti -1c
.RI "bool \fBHideRightInfo\fP\fR [get]\fP"
.br
.ti -1c
.RI "bool \fBHasAct\fP\fR [get]\fP"
.br
.ti -1c
.RI "bool \fBShowAct\fP\fR [get]\fP"
.br
.ti -1c
.RI "bool \fBHasMultipleTargets\fP\fR [get]\fP"
.br
.in -1c

Properties inherited from \fBEClass\fP
.in +1c
.ti -1c
.RI "static \fBGame\fP \fBgame\fP\fR [get]\fP"
.br
.ti -1c
.RI "static bool \fBAdvMode\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBPlayer\fP \fBplayer\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBChara\fP \fBpc\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBUI\fP \fBui\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBMap\fP \fB_map\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBZone\fP \fB_zone\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranchOrHomeBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFaction\fP \fBHome\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFaction\fP \fBWilds\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBScene\fP \fBscene\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBBaseGameScreen\fP \fBscreen\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameSetting\fP \fBsetting\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameData\fP \fBgamedata\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBColorProfile\fP \fBColors\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBWorld\fP \fBworld\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBsources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBeditorSources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static SoundManager \fBSound\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBCoreDebug\fP \fBdebug\fP\fR [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Static Public Member Functions inherited from \fBEClass\fP
.in +1c
.ti -1c
.RI "static int \fBrnd\fP (int a)"
.br
.ti -1c
.RI "static int \fBcurve\fP (int a, int start, int step, int rate=75)"
.br
.ti -1c
.RI "static int \fBrndHalf\fP (int a)"
.br
.ti -1c
.RI "static float \fBrndf\fP (float a)"
.br
.ti -1c
.RI "static int \fBrndSqrt\fP (int a)"
.br
.ti -1c
.RI "static void \fBWait\fP (float a, \fBCard\fP c)"
.br
.ti -1c
.RI "static void \fBWait\fP (float a, \fBPoint\fP p)"
.br
.ti -1c
.RI "static int \fBBigger\fP (int a, int b)"
.br
.ti -1c
.RI "static int \fBSmaller\fP (int a, int b)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB8\fP of file \fBActPlan\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void ActPlan\&._Update (\fBPointTarget\fP target)"

.PP
Definition at line \fB290\fP of file \fBActPlan\&.cs\fP\&.
.SS "void ActPlan\&.Clear ()"

.PP
Definition at line \fB248\fP of file \fBActPlan\&.cs\fP\&.
.SS "Func< bool > ActPlan\&.GetAction ()"

.PP
Definition at line \fB143\fP of file \fBActPlan\&.cs\fP\&.
.SS "string ActPlan\&.GetText (bool showName)"

.PP
Definition at line \fB61\fP of file \fBActPlan\&.cs\fP\&.
.SS "void ActPlan\&.ShowContextMenu ()"

.PP
Definition at line \fB175\fP of file \fBActPlan\&.cs\fP\&.
.SS "bool ActPlan\&.TrySetAct (\fBAct\fP _act, \fBCard\fP _tc = \fRnull\fP)"

.PP
Definition at line \fB232\fP of file \fBActPlan\&.cs\fP\&.
.SS "bool ActPlan\&.TrySetAct (string lang, Func< bool > onPerform, \fBCard\fP tc, CursorInfo cursor = \fRnull\fP, int dist = \fR1\fP, bool isHostileAct = \fRfalse\fP, bool localAct = \fRtrue\fP, bool canRepeat = \fRfalse\fP)"

.PP
Definition at line \fB207\fP of file \fBActPlan\&.cs\fP\&.
.SS "bool ActPlan\&.TrySetAct (string lang, Func< bool > onPerform, CursorInfo cursor = \fRnull\fP, int dist = \fR1\fP)"

.PP
Definition at line \fB221\fP of file \fBActPlan\&.cs\fP\&.
.SS "void ActPlan\&.Update (\fBPointTarget\fP target)"

.PP
Definition at line \fB255\fP of file \fBActPlan\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "bool ActPlan\&.altAction"

.PP
Definition at line \fB779\fP of file \fBActPlan\&.cs\fP\&.
.SS "int ActPlan\&.dist"

.PP
Definition at line \fB794\fP of file \fBActPlan\&.cs\fP\&.
.SS "bool ActPlan\&.ignoreAdddCondition"

.PP
Definition at line \fB782\fP of file \fBActPlan\&.cs\fP\&.
.SS "ActInput ActPlan\&.input"

.PP
Definition at line \fB773\fP of file \fBActPlan\&.cs\fP\&.
.SS "\fBAct\fP ActPlan\&.lastAct"

.PP
Definition at line \fB803\fP of file \fBActPlan\&.cs\fP\&.
.SS "\fBActPlan\&.List\fP ActPlan\&.list = new \fBActPlan\&.List\fP()"

.PP
Definition at line \fB791\fP of file \fBActPlan\&.cs\fP\&.
.SS "\fBList\fP<\fBThing\fP> ActPlan\&.listPick = new \fBList\fP<\fBThing\fP>()"

.PP
Definition at line \fB800\fP of file \fBActPlan\&.cs\fP\&.
.SS "bool ActPlan\&.performed"

.PP
Definition at line \fB776\fP of file \fBActPlan\&.cs\fP\&.
.SS "\fBPoint\fP ActPlan\&.pos = new \fBPoint\fP()"

.PP
Definition at line \fB770\fP of file \fBActPlan\&.cs\fP\&.
.SS "\fBThing\fP ActPlan\&.tool"

.PP
Definition at line \fB797\fP of file \fBActPlan\&.cs\fP\&.
.SS "bool ActPlan\&.warning\fR [static]\fP"

.PP
Definition at line \fB767\fP of file \fBActPlan\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "bool ActPlan\&.canRepeat\fR [get]\fP"

.PP
Definition at line \fB42\fP of file \fBActPlan\&.cs\fP\&.
.SS "\fBChara\fP ActPlan\&.cc\fR [get]\fP"

.PP
Definition at line \fB52\fP of file \fBActPlan\&.cs\fP\&.
.SS "CursorInfo ActPlan\&.CursorIcon\fR [get]\fP"

.PP
Definition at line \fB76\fP of file \fBActPlan\&.cs\fP\&.
.SS "bool ActPlan\&.HasAct\fR [get]\fP"

.PP
Definition at line \fB114\fP of file \fBActPlan\&.cs\fP\&.
.SS "bool ActPlan\&.HasMultipleTargets\fR [get]\fP"

.PP
Definition at line \fB134\fP of file \fBActPlan\&.cs\fP\&.
.SS "bool ActPlan\&.HideRightInfo\fR [get]\fP"

.PP
Definition at line \fB104\fP of file \fBActPlan\&.cs\fP\&.
.SS "bool ActPlan\&.IsNeighborBlocked\fR [get]\fP"

.PP
Definition at line \fB32\fP of file \fBActPlan\&.cs\fP\&.
.SS "bool ActPlan\&.IsSelf\fR [get]\fP"

.PP
Definition at line \fB12\fP of file \fBActPlan\&.cs\fP\&.
.SS "bool ActPlan\&.IsSelfOrNeighbor\fR [get]\fP"

.PP
Definition at line \fB22\fP of file \fBActPlan\&.cs\fP\&.
.SS "bool ActPlan\&.ShowAct\fR [get]\fP"

.PP
Definition at line \fB124\fP of file \fBActPlan\&.cs\fP\&.
.SS "bool ActPlan\&.WillEndTurn\fR [get]\fP"

.PP
Definition at line \fB94\fP of file \fBActPlan\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
