.TH "ActPlan.List" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ActPlan.List
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBAdd\fP (\fBAct\fP a, string s='')"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB806\fP of file \fBActPlan\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void ActPlan\&.List\&.Add (\fBAct\fP a, string s = \fR''\fP)"

.PP
Definition at line \fB809\fP of file \fBActPlan\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
