.TH "ActPlan.Item" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ActPlan.Item
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "string \fBGetText\fP (bool showName)"
.br
.ti -1c
.RI "string \fBGetTextContext\fP (bool showName)"
.br
.ti -1c
.RI "bool \fBPerform\fP (bool repeated=false)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBAct\fP \fBact\fP"
.br
.ti -1c
.RI "\fBCard\fP \fBtc\fP"
.br
.ti -1c
.RI "\fBPoint\fP \fBpos\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBChara\fP \fBcc\fP\fR [get]\fP"
.br
.ti -1c
.RI "bool \fBHideHint\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB819\fP of file \fBActPlan\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "string ActPlan\&.Item\&.GetText (bool showName)"

.PP
Definition at line \fB842\fP of file \fBActPlan\&.cs\fP\&.
.SS "string ActPlan\&.Item\&.GetTextContext (bool showName)"

.PP
Definition at line \fB848\fP of file \fBActPlan\&.cs\fP\&.
.SS "bool ActPlan\&.Item\&.Perform (bool repeated = \fRfalse\fP)"

.PP
Definition at line \fB854\fP of file \fBActPlan\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBAct\fP ActPlan\&.Item\&.act"

.PP
Definition at line \fB942\fP of file \fBActPlan\&.cs\fP\&.
.SS "\fBPoint\fP ActPlan\&.Item\&.pos"

.PP
Definition at line \fB948\fP of file \fBActPlan\&.cs\fP\&.
.SS "\fBCard\fP ActPlan\&.Item\&.tc"

.PP
Definition at line \fB945\fP of file \fBActPlan\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "\fBChara\fP ActPlan\&.Item\&.cc\fR [get]\fP"

.PP
Definition at line \fB823\fP of file \fBActPlan\&.cs\fP\&.
.SS "bool ActPlan\&.Item\&.HideHint\fR [get]\fP"

.PP
Definition at line \fB833\fP of file \fBActPlan\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
