.TH "ActRef" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ActRef
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBAct\fP \fBact\fP"
.br
.ti -1c
.RI "string \fBaliasEle\fP"
.br
.ti -1c
.RI "string \fBn1\fP"
.br
.ti -1c
.RI "\fBThing\fP \fBrefThing\fP"
.br
.ti -1c
.RI "\fBChara\fP \fBorigin\fP"
.br
.ti -1c
.RI "bool \fBisPerfume\fP"
.br
.ti -1c
.RI "bool \fBnoFriendlyFire\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBidEle\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB4\fP of file \fBActRef\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBAct\fP ActRef\&.act"

.PP
Definition at line \fB17\fP of file \fBActRef\&.cs\fP\&.
.SS "string ActRef\&.aliasEle"

.PP
Definition at line \fB20\fP of file \fBActRef\&.cs\fP\&.
.SS "bool ActRef\&.isPerfume"

.PP
Definition at line \fB32\fP of file \fBActRef\&.cs\fP\&.
.SS "string ActRef\&.n1"

.PP
Definition at line \fB23\fP of file \fBActRef\&.cs\fP\&.
.SS "bool ActRef\&.noFriendlyFire"

.PP
Definition at line \fB35\fP of file \fBActRef\&.cs\fP\&.
.SS "\fBChara\fP ActRef\&.origin"

.PP
Definition at line \fB29\fP of file \fBActRef\&.cs\fP\&.
.SS "\fBThing\fP ActRef\&.refThing"

.PP
Definition at line \fB26\fP of file \fBActRef\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "int ActRef\&.idEle\fR [get]\fP"

.PP
Definition at line \fB8\fP of file \fBActRef\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
