.TH "Algorithms.PriorityQueueB< T >" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Algorithms.PriorityQueueB< T >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBAlgorithms\&.IPriorityQueue< T >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPriorityQueueB\fP (IComparer< T > comparer)"
.br
.ti -1c
.RI "\fBPriorityQueueB\fP (IComparer< T > comparer, int capacity)"
.br
.ti -1c
.RI "int \fBPush\fP (T item)"
.br
.ti -1c
.RI "T \fBPop\fP ()"
.br
.ti -1c
.RI "void \fBUpdate\fP (int i)"
.br
.ti -1c
.RI "T \fBPeek\fP ()"
.br
.ti -1c
.RI "void \fBClear\fP ()"
.br
.ti -1c
.RI "void \fBRemoveLocation\fP (T item)"
.br
.in -1c

Public Member Functions inherited from \fBAlgorithms\&.IPriorityQueue< T >\fP
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBSwitchElements\fP (int i, int j)"
.br
.ti -1c
.RI "virtual int \fBOnCompare\fP (int i, int j)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "List< T > \fBInnerList\fP = new List<T>()"
.br
.ti -1c
.RI "IComparer< T > \fBmComparer\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBCount\fP\fR [get]\fP"
.br
.ti -1c
.RI "T \fBthis[int index]\fP\fR [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB8\fP of file \fBPriorityQueueB\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBAlgorithms\&.PriorityQueueB\fP< T >\&.\fBPriorityQueueB\fP ()"

.PP
Definition at line \fB11\fP of file \fBPriorityQueueB\&.cs\fP\&.
.SS "\fBAlgorithms\&.PriorityQueueB\fP< T >\&.\fBPriorityQueueB\fP (IComparer< T > comparer)"

.PP
Definition at line \fB17\fP of file \fBPriorityQueueB\&.cs\fP\&.
.SS "\fBAlgorithms\&.PriorityQueueB\fP< T >\&.\fBPriorityQueueB\fP (IComparer< T > comparer, int capacity)"

.PP
Definition at line \fB23\fP of file \fBPriorityQueueB\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void \fBAlgorithms\&.PriorityQueueB\fP< T >\&.Clear ()"

.PP
Definition at line \fB140\fP of file \fBPriorityQueueB\&.cs\fP\&.
.SS "virtual int \fBAlgorithms\&.PriorityQueueB\fP< T >\&.OnCompare (int i, int j)\fR [protected]\fP, \fR [virtual]\fP"

.PP
Definition at line \fB38\fP of file \fBPriorityQueueB\&.cs\fP\&.
.SS "T \fBAlgorithms\&.PriorityQueueB\fP< T >\&.Peek ()"

.PP
Implements \fBAlgorithms\&.IPriorityQueue< T >\fP\&.
.PP
Definition at line \fB130\fP of file \fBPriorityQueueB\&.cs\fP\&.
.SS "T \fBAlgorithms\&.PriorityQueueB\fP< T >\&.Pop ()"

.PP
Implements \fBAlgorithms\&.IPriorityQueue< T >\fP\&.
.PP
Definition at line \fB62\fP of file \fBPriorityQueueB\&.cs\fP\&.
.SS "int \fBAlgorithms\&.PriorityQueueB\fP< T >\&.Push (T item)"

.PP
Implements \fBAlgorithms\&.IPriorityQueue< T >\fP\&.
.PP
Definition at line \fB44\fP of file \fBPriorityQueueB\&.cs\fP\&.
.SS "void \fBAlgorithms\&.PriorityQueueB\fP< T >\&.RemoveLocation (T item)"

.PP
Definition at line \fB156\fP of file \fBPriorityQueueB\&.cs\fP\&.
.SS "void \fBAlgorithms\&.PriorityQueueB\fP< T >\&.SwitchElements (int i, int j)\fR [protected]\fP"

.PP
Definition at line \fB30\fP of file \fBPriorityQueueB\&.cs\fP\&.
.SS "void \fBAlgorithms\&.PriorityQueueB\fP< T >\&.Update (int i)"

.PP
Implements \fBAlgorithms\&.IPriorityQueue< T >\fP\&.
.PP
Definition at line \fB91\fP of file \fBPriorityQueueB\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "List<T> \fBAlgorithms\&.PriorityQueueB\fP< T >\&.InnerList = new List<T>()\fR [protected]\fP"

.PP
Definition at line \fB187\fP of file \fBPriorityQueueB\&.cs\fP\&.
.SS "IComparer<T> \fBAlgorithms\&.PriorityQueueB\fP< T >\&.mComparer\fR [protected]\fP"

.PP
Definition at line \fB190\fP of file \fBPriorityQueueB\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "int \fBAlgorithms\&.PriorityQueueB\fP< T >\&.Count\fR [get]\fP"

.PP
Definition at line \fB147\fP of file \fBPriorityQueueB\&.cs\fP\&.
.SS "T \fBAlgorithms\&.PriorityQueueB\fP< T >\&.this[int index]\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB173\fP of file \fBPriorityQueueB\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
