.TH "Algorithms.PathFinderNode" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Algorithms.PathFinderNode
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBG\fP"
.br
.ti -1c
.RI "int \fBX\fP"
.br
.ti -1c
.RI "int \fBZ\fP"
.br
.ti -1c
.RI "int \fBPX\fP"
.br
.ti -1c
.RI "int \fBPZ\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB6\fP of file \fBPathFinderNode\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int Algorithms\&.PathFinderNode\&.G"

.PP
Definition at line \fB9\fP of file \fBPathFinderNode\&.cs\fP\&.
.SS "int Algorithms\&.PathFinderNode\&.PX"

.PP
Definition at line \fB18\fP of file \fBPathFinderNode\&.cs\fP\&.
.SS "int Algorithms\&.PathFinderNode\&.PZ"

.PP
Definition at line \fB21\fP of file \fBPathFinderNode\&.cs\fP\&.
.SS "int Algorithms\&.PathFinderNode\&.X"

.PP
Definition at line \fB12\fP of file \fBPathFinderNode\&.cs\fP\&.
.SS "int Algorithms\&.PathFinderNode\&.Z"

.PP
Definition at line \fB15\fP of file \fBPathFinderNode\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
