.TH "Algorithms" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Algorithms
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAuthorAttribute\fP"
.br
.ti -1c
.RI "interface \fBIPriorityQueue\fP"
.br
.ti -1c
.RI "class \fBPathFinder\fP"
.br
.ti -1c
.RI "struct \fBPathFinderNode\fP"
.br
.ti -1c
.RI "class \fBPriorityQueueB\fP"
.br
.ti -1c
.RI "class \fBWeightCell\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBHeuristicFormula\fP { \fBManhattan\fP = 1, \fBMaxDXDY\fP, \fBDiagonalShortCut\fP, \fBEuclidean\fP, \fBEuclideanNoSQR\fP }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum Algorithms\&.HeuristicFormula"

.PP
Definition at line \fB6\fP of file \fBHeuristicFormula\&.cs\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
