.TH "Algorithms.PathFinder" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Algorithms.PathFinder
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBIPathfinder\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBComparePFNodeMatrix\fP"
.br
.ti -1c
.RI "struct \fBPathFinderNodeFast\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "static unsafe bool \fBZeroMemory\fP (byte *destination, int length)"
.br
.ti -1c
.RI "void \fBInit\fP (\fBIPathfindGrid\fP _grid, \fBWeightCell\fP[,] _weightMap, int size)"
.br
.ti -1c
.RI "void \fBFindPath\fP (\fBPathProgress\fP path)"
.br
.in -1c

Public Member Functions inherited from \fBIPathfinder\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBdebug\fP"
.br
.ti -1c
.RI "bool \fBDiagonals\fP"
.br
.ti -1c
.RI "bool \fBPunishChangeDirection\fP"
.br
.ti -1c
.RI "float \fBHeavyDiagonals\fP = 1f"
.br
.ti -1c
.RI "bool \fBTieBreaker\fP"
.br
.ti -1c
.RI "HeuristicFormula \fBmFormula\fP = HeuristicFormula\&.Manhattan"
.br
.ti -1c
.RI "int \fBtotal\fP"
.br
.ti -1c
.RI "\fBWeightCell\fP[,] \fBweightMap\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB10\fP of file \fBPathFinder\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Algorithms\&.PathFinder\&.FindPath (\fBPathProgress\fP path)"

.PP
Implements \fBIPathfinder\fP\&.
.PP
Definition at line \fB32\fP of file \fBPathFinder\&.cs\fP\&.
.SS "void Algorithms\&.PathFinder\&.Init (\fBIPathfindGrid\fP _grid, \fBWeightCell\fP _weightMap[,], int size)"

.PP
Implements \fBIPathfinder\fP\&.
.PP
Definition at line \fB17\fP of file \fBPathFinder\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "bool Algorithms\&.PathFinder\&.debug"

.PP
Definition at line \fB268\fP of file \fBPathFinder\&.cs\fP\&.
.SS "bool Algorithms\&.PathFinder\&.Diagonals"

.PP
Definition at line \fB271\fP of file \fBPathFinder\&.cs\fP\&.
.SS "float Algorithms\&.PathFinder\&.HeavyDiagonals = 1f"

.PP
Definition at line \fB277\fP of file \fBPathFinder\&.cs\fP\&.
.SS "HeuristicFormula Algorithms\&.PathFinder\&.mFormula = HeuristicFormula\&.Manhattan"

.PP
Definition at line \fB283\fP of file \fBPathFinder\&.cs\fP\&.
.SS "bool Algorithms\&.PathFinder\&.PunishChangeDirection"

.PP
Definition at line \fB274\fP of file \fBPathFinder\&.cs\fP\&.
.SS "bool Algorithms\&.PathFinder\&.TieBreaker"

.PP
Definition at line \fB280\fP of file \fBPathFinder\&.cs\fP\&.
.SS "int Algorithms\&.PathFinder\&.total"

.PP
Definition at line \fB320\fP of file \fBPathFinder\&.cs\fP\&.
.SS "\fBWeightCell\fP [,] Algorithms\&.PathFinder\&.weightMap"

.PP
Definition at line \fB408\fP of file \fBPathFinder\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
