.TH "Algorithms.IPriorityQueue< T >" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Algorithms.IPriorityQueue< T >
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBAlgorithms\&.PriorityQueueB< T >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "int \fBPush\fP (T item)"
.br
.ti -1c
.RI "T \fBPop\fP ()"
.br
.ti -1c
.RI "T \fBPeek\fP ()"
.br
.ti -1c
.RI "void \fBUpdate\fP (int i)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB7\fP of file \fBIPriorityQueue\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
