.TH "AM_Adv.PressedAction" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AM_Adv.PressedAction
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBInit\fP (Vector3 _axis)"
.br
.ti -1c
.RI "void \fBInit\fP (ButtonState _button=null)"
.br
.ti -1c
.RI "void \fBSetAction\fP (Func< bool > _action=null, bool _canTurbo=true, bool _willEndTurn=true, bool _waitForTurn=true)"
.br
.ti -1c
.RI "void \fBSetPlan\fP (\fBActPlan\fP _plan)"
.br
.ti -1c
.RI "bool \fBIsPressing\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "ButtonState \fBbutton\fP"
.br
.ti -1c
.RI "bool \fBcanTurbo\fP"
.br
.ti -1c
.RI "bool \fBwillEndTurn\fP"
.br
.ti -1c
.RI "bool \fBwaitForTurn\fP"
.br
.ti -1c
.RI "bool \fBhideRightInfo\fP"
.br
.ti -1c
.RI "bool \fBrepeat\fP"
.br
.ti -1c
.RI "bool \fBignoreCount\fP"
.br
.ti -1c
.RI "Func< bool > \fBaction\fP"
.br
.ti -1c
.RI "\fBAct\fP \fBact\fP"
.br
.ti -1c
.RI "\fBActPlan\fP \fBplan\fP"
.br
.ti -1c
.RI "float \fBtimer\fP"
.br
.ti -1c
.RI "float \fBtimerRepeat\fP"
.br
.ti -1c
.RI "Vector2 \fBaxis\fP"
.br
.ti -1c
.RI "int \fBcount\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB1354\fP of file \fBAM_Adv\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void AM_Adv\&.PressedAction\&.Init (ButtonState _button = \fRnull\fP)"

.PP
Definition at line \fB1367\fP of file \fBAM_Adv\&.cs\fP\&.
.SS "void AM_Adv\&.PressedAction\&.Init (Vector3 _axis)"

.PP
Definition at line \fB1357\fP of file \fBAM_Adv\&.cs\fP\&.
.SS "bool AM_Adv\&.PressedAction\&.IsPressing ()"

.PP
Definition at line \fB1405\fP of file \fBAM_Adv\&.cs\fP\&.
.SS "void AM_Adv\&.PressedAction\&.SetAction (Func< bool > _action = \fRnull\fP, bool _canTurbo = \fRtrue\fP, bool _willEndTurn = \fRtrue\fP, bool _waitForTurn = \fRtrue\fP)"

.PP
Definition at line \fB1377\fP of file \fBAM_Adv\&.cs\fP\&.
.SS "void AM_Adv\&.PressedAction\&.SetPlan (\fBActPlan\fP _plan)"

.PP
Definition at line \fB1391\fP of file \fBAM_Adv\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBAct\fP AM_Adv\&.PressedAction\&.act"

.PP
Definition at line \fB1439\fP of file \fBAM_Adv\&.cs\fP\&.
.SS "Func<bool> AM_Adv\&.PressedAction\&.action"

.PP
Definition at line \fB1436\fP of file \fBAM_Adv\&.cs\fP\&.
.SS "Vector2 AM_Adv\&.PressedAction\&.axis"

.PP
Definition at line \fB1451\fP of file \fBAM_Adv\&.cs\fP\&.
.SS "ButtonState AM_Adv\&.PressedAction\&.button"

.PP
Definition at line \fB1415\fP of file \fBAM_Adv\&.cs\fP\&.
.SS "bool AM_Adv\&.PressedAction\&.canTurbo"

.PP
Definition at line \fB1418\fP of file \fBAM_Adv\&.cs\fP\&.
.SS "int AM_Adv\&.PressedAction\&.count"

.PP
Definition at line \fB1454\fP of file \fBAM_Adv\&.cs\fP\&.
.SS "bool AM_Adv\&.PressedAction\&.hideRightInfo"

.PP
Definition at line \fB1427\fP of file \fBAM_Adv\&.cs\fP\&.
.SS "bool AM_Adv\&.PressedAction\&.ignoreCount"

.PP
Definition at line \fB1433\fP of file \fBAM_Adv\&.cs\fP\&.
.SS "\fBActPlan\fP AM_Adv\&.PressedAction\&.plan"

.PP
Definition at line \fB1442\fP of file \fBAM_Adv\&.cs\fP\&.
.SS "bool AM_Adv\&.PressedAction\&.repeat"

.PP
Definition at line \fB1430\fP of file \fBAM_Adv\&.cs\fP\&.
.SS "float AM_Adv\&.PressedAction\&.timer"

.PP
Definition at line \fB1445\fP of file \fBAM_Adv\&.cs\fP\&.
.SS "float AM_Adv\&.PressedAction\&.timerRepeat"

.PP
Definition at line \fB1448\fP of file \fBAM_Adv\&.cs\fP\&.
.SS "bool AM_Adv\&.PressedAction\&.waitForTurn"

.PP
Definition at line \fB1424\fP of file \fBAM_Adv\&.cs\fP\&.
.SS "bool AM_Adv\&.PressedAction\&.willEndTurn"

.PP
Definition at line \fB1421\fP of file \fBAM_Adv\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
