.TH "AM_Dig" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AM_Dig
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBAM_Designation< TaskDig >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override bool \fBForcedInstaComplete\fP (\fBTaskDig\fP t)"
.br
.ti -1c
.RI "override void \fBOnUpdateCursor\fP ()"
.br
.ti -1c
.RI "void \fBActivate\fP (TaskDig\&.Mode _mode)"
.br
.ti -1c
.RI "override void \fBOnActivate\fP ()"
.br
.ti -1c
.RI "override void \fBOnSelectStart\fP (\fBPoint\fP point)"
.br
.ti -1c
.RI "override void \fBOnSelectEnd\fP (bool cancel)"
.br
.ti -1c
.RI "override void \fBOnCreateMold\fP (bool processing=false)"
.br
.in -1c

Public Member Functions inherited from \fBAM_Designation< TaskDig >\fP
.in +1c
.ti -1c
.RI "virtual bool \fBCanInstaComplete\fP (T t)"
.br
.ti -1c
.RI "virtual bool \fBForcedInstaComplete\fP (T t)"
.br
.ti -1c
.RI "virtual HitResult \fBHitResultOnDesignation\fP (\fBPoint\fP p)"
.br
.ti -1c
.RI "override void \fBOnActivate\fP ()"
.br
.ti -1c
.RI "void \fBCreateNewMold\fP (bool processing=false)"
.br
.ti -1c
.RI "override HitResult \fBHitTest\fP (\fBPoint\fP point, \fBPoint\fP start)"
.br
.ti -1c
.RI "override bool \fBCanProcessTiles\fP ()"
.br
.ti -1c
.RI "override void \fBOnBeforeProcessTiles\fP ()"
.br
.ti -1c
.RI "override void \fBOnProcessTiles\fP (\fBPoint\fP point, int dir)"
.br
.ti -1c
.RI "override void \fBOnAfterProcessTiles\fP (\fBPoint\fP start, \fBPoint\fP end)"
.br
.ti -1c
.RI "override void \fBOnRefreshSummary\fP (\fBPoint\fP point, HitResult result, \fBHitSummary\fP summary)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "TaskDig\&.Mode \fBmode\fP"
.br
.ti -1c
.RI "int \fBramp\fP = 3"
.br
.in -1c

Public Attributes inherited from \fBAM_Designation< TaskDig >\fP
.in +1c
.ti -1c
.RI "\fBTaskList\fP< T > \fBlist\fP"
.br
.ti -1c
.RI "T \fBmold\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override int \fBCostMoney\fP\fR [get]\fP"
.br
.ti -1c
.RI "override string \fBid\fP\fR [get]\fP"
.br
.ti -1c
.RI "override bool \fBAllowAutoClick\fP\fR [get]\fP"
.br
.in -1c

Properties inherited from \fBAM_Designation< TaskDig >\fP
.in +1c
.ti -1c
.RI "override string \fBidSound\fP\fR [get]\fP"
.br
.ti -1c
.RI "override bool \fBIsBuildMode\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB4\fP of file \fBAM_Dig\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void AM_Dig\&.Activate (TaskDig\&.Mode _mode)"

.PP
Definition at line \fB49\fP of file \fBAM_Dig\&.cs\fP\&.
.SS "override bool AM_Dig\&.ForcedInstaComplete (\fBTaskDig\fP t)"

.PP
Definition at line \fB37\fP of file \fBAM_Dig\&.cs\fP\&.
.SS "override void AM_Dig\&.OnActivate ()"

.PP
Definition at line \fB58\fP of file \fBAM_Dig\&.cs\fP\&.
.SS "override void AM_Dig\&.OnCreateMold (bool processing = \fRfalse\fP)\fR [virtual]\fP"

.PP
Reimplemented from \fBAM_Designation< TaskDig >\fP\&.
.PP
Definition at line \fB77\fP of file \fBAM_Dig\&.cs\fP\&.
.SS "override void AM_Dig\&.OnSelectEnd (bool cancel)"

.PP
Definition at line \fB71\fP of file \fBAM_Dig\&.cs\fP\&.
.SS "override void AM_Dig\&.OnSelectStart (\fBPoint\fP point)"

.PP
Definition at line \fB65\fP of file \fBAM_Dig\&.cs\fP\&.
.SS "override void AM_Dig\&.OnUpdateCursor ()"

.PP
Definition at line \fB43\fP of file \fBAM_Dig\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "TaskDig\&.Mode AM_Dig\&.mode"

.PP
Definition at line \fB84\fP of file \fBAM_Dig\&.cs\fP\&.
.SS "int AM_Dig\&.ramp = 3"

.PP
Definition at line \fB87\fP of file \fBAM_Dig\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "override bool AM_Dig\&.AllowAutoClick\fR [get]\fP"

.PP
Definition at line \fB28\fP of file \fBAM_Dig\&.cs\fP\&.
.SS "override int AM_Dig\&.CostMoney\fR [get]\fP"

.PP
Definition at line \fB8\fP of file \fBAM_Dig\&.cs\fP\&.
.SS "override string AM_Dig\&.id\fR [get]\fP"

.PP
Definition at line \fB18\fP of file \fBAM_Dig\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
