.TH "AM_Harvest" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AM_Harvest
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBAM_Designation< TaskHarvest >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnActivate\fP ()"
.br
.in -1c

Public Member Functions inherited from \fBAM_Designation< TaskHarvest >\fP
.in +1c
.ti -1c
.RI "virtual bool \fBCanInstaComplete\fP (T t)"
.br
.ti -1c
.RI "virtual bool \fBForcedInstaComplete\fP (T t)"
.br
.ti -1c
.RI "virtual HitResult \fBHitResultOnDesignation\fP (\fBPoint\fP p)"
.br
.ti -1c
.RI "override void \fBOnActivate\fP ()"
.br
.ti -1c
.RI "void \fBCreateNewMold\fP (bool processing=false)"
.br
.ti -1c
.RI "virtual void \fBOnCreateMold\fP (bool processing=false)"
.br
.ti -1c
.RI "override HitResult \fBHitTest\fP (\fBPoint\fP point, \fBPoint\fP start)"
.br
.ti -1c
.RI "override bool \fBCanProcessTiles\fP ()"
.br
.ti -1c
.RI "override void \fBOnBeforeProcessTiles\fP ()"
.br
.ti -1c
.RI "override void \fBOnProcessTiles\fP (\fBPoint\fP point, int dir)"
.br
.ti -1c
.RI "override void \fBOnAfterProcessTiles\fP (\fBPoint\fP start, \fBPoint\fP end)"
.br
.ti -1c
.RI "override void \fBOnRefreshSummary\fP (\fBPoint\fP point, HitResult result, \fBHitSummary\fP summary)"
.br
.in -1c
.SS "Additional Inherited Members"


Public Attributes inherited from \fBAM_Designation< TaskHarvest >\fP
.in +1c
.ti -1c
.RI "\fBTaskList\fP< T > \fBlist\fP"
.br
.ti -1c
.RI "T \fBmold\fP"
.br
.in -1c

Properties inherited from \fBAM_Designation< TaskHarvest >\fP
.in +1c
.ti -1c
.RI "override string \fBidSound\fP\fR [get]\fP"
.br
.ti -1c
.RI "override bool \fBIsBuildMode\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB4\fP of file \fBAM_Harvest\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void AM_Harvest\&.OnActivate ()"

.PP
Definition at line \fB7\fP of file \fBAM_Harvest\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
