.TH "AM_Title" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AM_Title
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBAM_NoMap\fP\&.
.SS "Additional Inherited Members"


Public Member Functions inherited from \fBAM_NoMap\fP
.in +1c
.ti -1c
.RI "override void \fBOnActivate\fP ()"
.br
.ti -1c
.RI "override void \fBOnDeactivate\fP ()"
.br
.in -1c

Public Member Functions inherited from \fBActionMode\fP
.in +1c
.ti -1c
.RI "virtual int \fBTopHeight\fP (\fBPoint\fP p)"
.br
.ti -1c
.RI "virtual void \fBSEExecuteSummary\fP ()"
.br
.ti -1c
.RI "virtual bool \fBHighlightWall\fP (\fBPoint\fP p)"
.br
.ti -1c
.RI "virtual void \fBOnClickSubMenu\fP (int a)"
.br
.ti -1c
.RI "virtual string \fBOnSetSubMenuButton\fP (int a, UIButton b)"
.br
.ti -1c
.RI "virtual bool \fBIsRoofEditMode\fP (\fBCard\fP c=null)"
.br
.ti -1c
.RI "virtual bool \fBIsFillMode\fP ()"
.br
.ti -1c
.RI "virtual int \fBGetDefaultTile\fP (\fBPoint\fP p)"
.br
.ti -1c
.RI "virtual void \fBOnShowExtraHint\fP (UINote n)"
.br
.ti -1c
.RI "void \fBActivate\fP (bool toggle=true, bool forceActivate=false)"
.br
.ti -1c
.RI "unsafe void \fBRefreshTexts\fP ()"
.br
.ti -1c
.RI "virtual string \fBGetSimpleText\fP (\fBCard\fP c)"
.br
.ti -1c
.RI "void \fBClearSimpleTexts\fP ()"
.br
.ti -1c
.RI "void \fBDeactivate\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnCancel\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnBeforeUpdate\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnAfterUpdate\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnUpdateCursor\fP ()"
.br
.ti -1c
.RI "void \fBOnRotate\fP ()"
.br
.ti -1c
.RI "void \fBSetCursorOnMap\fP (CursorInfo cursor)"
.br
.ti -1c
.RI "void \fBUpdateInput\fP ()"
.br
.ti -1c
.RI "void \fBInputMovement\fP ()"
.br
.ti -1c
.RI "virtual void \fBInputWheel\fP (int wheel)"
.br
.ti -1c
.RI "virtual void \fBOnUpdateInput\fP ()"
.br
.ti -1c
.RI "void \fBDoFunc\fP (CoreConfig\&.GameFuncBuild func)"
.br
.ti -1c
.RI "void \fBDoFunc\fP (CoreConfig\&.GameFunc func)"
.br
.ti -1c
.RI "virtual void \fBOnScroll\fP ()"
.br
.ti -1c
.RI "void \fBTryRightClickCloseWidget\fP ()"
.br
.ti -1c
.RI "bool \fBTryShowWidgetMenu\fP ()"
.br
.ti -1c
.RI "HitResult \fB_HitTest\fP (\fBPoint\fP point, \fBPoint\fP start)"
.br
.ti -1c
.RI "virtual HitResult \fBHitTest\fP (\fBPoint\fP point, \fBPoint\fP start)"
.br
.ti -1c
.RI "virtual void \fBOnSelectStart\fP (\fBPoint\fP point)"
.br
.ti -1c
.RI "virtual void \fBOnSelectEnd\fP (bool cancel)"
.br
.ti -1c
.RI "virtual \fBMeshPass\fP \fBGetGuidePass\fP (\fBPoint\fP point)"
.br
.ti -1c
.RI "virtual unsafe void \fBOnRenderTile\fP (\fBPoint\fP point, HitResult result, int dir)"
.br
.ti -1c
.RI "unsafe void \fBOnRenderTileFloor\fP (\fBPoint\fP point, HitResult result)"
.br
.ti -1c
.RI "virtual bool \fBCanProcessTiles\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnBeforeProcessTiles\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnProcessTiles\fP (\fBPoint\fP point, int dir)"
.br
.ti -1c
.RI "virtual void \fBOnAfterProcessTiles\fP (\fBPoint\fP start, \fBPoint\fP end)"
.br
.ti -1c
.RI "virtual void \fBOnFinishProcessTiles\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnRefreshSummary\fP (\fBPoint\fP point, HitResult result, \fBHitSummary\fP summary)"
.br
.ti -1c
.RI "void \fBShowLayer\fP ()"
.br
.ti -1c
.RI "virtual Layer \fBOnShowLayer\fP ()"
.br
.ti -1c
.RI "void \fBHideLayer\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnHideLayer\fP ()"
.br
.ti -1c
.RI "virtual string \fBGetHintText\fP ()"
.br
.ti -1c
.RI "virtual void \fBRotateUnderMouse\fP ()"
.br
.ti -1c
.RI "virtual ref string \fBSetMouseInfo\fP (ref string s)"
.br
.ti -1c
.RI "void \fBTogglePause\fP ()"
.br
.ti -1c
.RI "void \fBPause\fP (bool sound=false)"
.br
.ti -1c
.RI "void \fBUnPause\fP (bool sound=false)"
.br
.ti -1c
.RI "void \fBChangeGameSpeed\fP (int a, bool sound=false)"
.br
.in -1c

Static Public Member Functions inherited from \fBActionMode\fP
.in +1c
.ti -1c
.RI "static void \fBOnGameInstantiated\fP ()"
.br
.in -1c

Static Public Member Functions inherited from \fBEClass\fP
.in +1c
.ti -1c
.RI "static int \fBrnd\fP (int a)"
.br
.ti -1c
.RI "static int \fBcurve\fP (int a, int start, int step, int rate=75)"
.br
.ti -1c
.RI "static int \fBrndHalf\fP (int a)"
.br
.ti -1c
.RI "static float \fBrndf\fP (float a)"
.br
.ti -1c
.RI "static int \fBrndSqrt\fP (int a)"
.br
.ti -1c
.RI "static void \fBWait\fP (float a, \fBCard\fP c)"
.br
.ti -1c
.RI "static void \fBWait\fP (float a, \fBPoint\fP p)"
.br
.ti -1c
.RI "static int \fBBigger\fP (int a, int b)"
.br
.ti -1c
.RI "static int \fBSmaller\fP (int a, int b)"
.br
.in -1c

Public Attributes inherited from \fBActionMode\fP
.in +1c
.ti -1c
.RI "Layer \fBlayer\fP"
.br
.ti -1c
.RI "int \fBbrushRadius\fP = 4"
.br
.in -1c

Static Public Attributes inherited from \fBActionMode\fP
.in +1c
.ti -1c
.RI "static \fBActionMode\fP \fBDefaultMode\fP"
.br
.ti -1c
.RI "static \fBAM_Title\fP \fBTitle\fP = new \fBAM_Title\fP()"
.br
.ti -1c
.RI "static \fBAM_Sim\fP \fBSim\fP"
.br
.ti -1c
.RI "static \fBAM_ViewZone\fP \fBView\fP"
.br
.ti -1c
.RI "static \fBAM_Adv\fP \fBAdv\fP"
.br
.ti -1c
.RI "static \fBAM_Region\fP \fBRegion\fP"
.br
.ti -1c
.RI "static \fBAM_ADV_Target\fP \fBAdvTarget\fP"
.br
.ti -1c
.RI "static \fBAM_EloMap\fP \fBEloMap\fP"
.br
.ti -1c
.RI "static \fBAM_Inspect\fP \fBInspect\fP"
.br
.ti -1c
.RI "static \fBAM_NoMap\fP \fBNoMap\fP"
.br
.ti -1c
.RI "static \fBAM_MiniGame\fP \fBMiniGame\fP"
.br
.ti -1c
.RI "static \fBAM_NewZone\fP \fBNewZone\fP"
.br
.ti -1c
.RI "static \fBAM_Bird\fP \fBBird\fP"
.br
.ti -1c
.RI "static \fBAM_Mine\fP \fBMine\fP"
.br
.ti -1c
.RI "static \fBAM_Dig\fP \fBDig\fP"
.br
.ti -1c
.RI "static \fBAM_Harvest\fP \fBHarvest\fP"
.br
.ti -1c
.RI "static \fBAM_Cut\fP \fBCut\fP"
.br
.ti -1c
.RI "static \fBAM_StateEditor\fP \fBStateEditor\fP"
.br
.ti -1c
.RI "static \fBAM_Picker\fP \fBPicker\fP"
.br
.ti -1c
.RI "static \fBAM_Copy\fP \fBCopy\fP"
.br
.ti -1c
.RI "static \fBAM_Blueprint\fP \fBBlueprint\fP"
.br
.ti -1c
.RI "static \fBAM_Build\fP \fBBuild\fP"
.br
.ti -1c
.RI "static \fBAM_CreateArea\fP \fBCreateArea\fP"
.br
.ti -1c
.RI "static \fBAM_EditArea\fP \fBEditArea\fP"
.br
.ti -1c
.RI "static \fBAM_ExpandArea\fP \fBExpandArea\fP"
.br
.ti -1c
.RI "static \fBAM_Deconstruct\fP \fBDeconstruct\fP"
.br
.ti -1c
.RI "static \fBAM_Select\fP \fBSelect\fP"
.br
.ti -1c
.RI "static \fBAM_RemoveDesignation\fP \fBRemoveDesignation\fP"
.br
.ti -1c
.RI "static \fBAM_ViewMap\fP \fBViewMap\fP"
.br
.ti -1c
.RI "static \fBAM_Terrain\fP \fBTerrain\fP"
.br
.ti -1c
.RI "static \fBAM_Populate\fP \fBPopulate\fP"
.br
.ti -1c
.RI "static \fBAM_EditMarker\fP \fBEditMarker\fP"
.br
.ti -1c
.RI "static \fBAM_Visibility\fP \fBVisibility\fP"
.br
.ti -1c
.RI "static \fBAM_Cinema\fP \fBCinema\fP"
.br
.ti -1c
.RI "static \fBAM_Paint\fP \fBPaint\fP"
.br
.ti -1c
.RI "static \fBAM_FlagCell\fP \fBFlagCell\fP"
.br
.ti -1c
.RI "static \fBActionMode\fP \fBLastBuildMode\fP"
.br
.ti -1c
.RI "static \fBSourceMaterial\&.Row\fP \fBlastEditorMat\fP"
.br
.ti -1c
.RI "static bool \fBignoreSound\fP"
.br
.ti -1c
.RI "static float[] \fBGameSpeeds\fP"
.br
.ti -1c
.RI "static List< \fBTCSimpleText\fP > \fBsimpleTexts\fP = new List<\fBTCSimpleText\fP>()"
.br
.in -1c

Static Public Attributes inherited from \fBEClass\fP
.in +1c
.ti -1c
.RI "static \fBCore\fP \fBcore\fP"
.br
.in -1c

Static Protected Attributes inherited from \fBActionMode\fP
.in +1c
.ti -1c
.RI "static Vector3 \fBmpos\fP"
.br
.in -1c

Properties inherited from \fBAM_NoMap\fP
.in +1c
.ti -1c
.RI "override bool \fBShowActionHint\fP\fR [get]\fP"
.br
.ti -1c
.RI "override bool \fBAllowHotbar\fP\fR [get]\fP"
.br
.ti -1c
.RI "override bool \fBAllowGeneralInput\fP\fR [get]\fP"
.br
.ti -1c
.RI "override bool \fBIsNoMap\fP\fR [get]\fP"
.br
.ti -1c
.RI "override \fBBaseGameScreen\fP \fBTargetGameScreen\fP\fR [get]\fP"
.br
.in -1c

Properties inherited from \fBActionMode\fP
.in +1c
.ti -1c
.RI "static \fBAM_Adv\fP \fBAdvOrRegion\fP\fR [get]\fP"
.br
.ti -1c
.RI "static bool \fBIsAdv\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual float \fBgameSpeed\fP\fR [get]\fP"
.br
.ti -1c
.RI "bool \fBIsActive\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual BaseTileSelector\&.HitType \fBhitType\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual BaseTileSelector\&.SelectType \fBselectType\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual BaseTileSelector\&.BoxType \fBboxType\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBContinuousClick\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual int \fBhitW\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual int \fBhitH\fP\fR [get]\fP"
.br
.ti -1c
.RI "\fBHitSummary\fP \fBSummary\fP\fR [get]\fP"
.br
.ti -1c
.RI "bool \fBMultisize\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual string \fBid\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual CursorInfo \fBDefaultCursor\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual string \fBidHelpTopic\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual string \fBidSound\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBenableMouseInfo\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBhideBalloon\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual string \fBtextHintTitle\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBAllowAutoClick\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBShowActionHint\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBShowMouseoverTarget\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual AreaHighlightMode \fBAreaHihlight\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBCanSelectTile\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBCanTargetOutsideBounds\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBShouldPauseGame\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBFixFocus\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBHideSubWidgets\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBIsBuildMode\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBShowBuildWidgets\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual BuildMenu\&.Mode \fBbuildMenuMode\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBShouldHideBuildMenu\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBCanTargetFog\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual int \fBCostMoney\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBAllowBuildModeShortcuts\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBAllowMiddleClickFunc\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBAllowHotbar\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBAllowGeneralInput\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBShowMaskedThings\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual int \fBSelectorHeight\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBAllowWheelZoom\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual float \fBTargetZoom\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual BaseTileMap\&.CardIconMode \fBcardIconMode\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual \fBBaseGameScreen\fP \fBTargetGameScreen\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBIsNoMap\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBUseSubMenu\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBUseSubMenuSlider\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBSubMenuAsGroup\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual int \fBSubMenuModeIndex\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBShowExtraHint\fP\fR [get]\fP"
.br
.ti -1c
.RI "\fBBaseTileSelector\fP \fBtileSelector\fP\fR [get]\fP"
.br
.in -1c

Properties inherited from \fBEClass\fP
.in +1c
.ti -1c
.RI "static \fBGame\fP \fBgame\fP\fR [get]\fP"
.br
.ti -1c
.RI "static bool \fBAdvMode\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBPlayer\fP \fBplayer\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBChara\fP \fBpc\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBUI\fP \fBui\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBMap\fP \fB_map\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBZone\fP \fB_zone\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranchOrHomeBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFaction\fP \fBHome\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFaction\fP \fBWilds\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBScene\fP \fBscene\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBBaseGameScreen\fP \fBscreen\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameSetting\fP \fBsetting\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameData\fP \fBgamedata\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBColorProfile\fP \fBColors\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBWorld\fP \fBworld\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBsources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBeditorSources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static SoundManager \fBSound\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBCoreDebug\fP \fBdebug\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB4\fP of file \fBAM_Title\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
