.TH "AnimationFrame" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AnimationFrame
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Vector3[] \fBmainHand\fP"
.br
.ti -1c
.RI "Vector3[] \fBoffHand\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB6\fP of file \fBAnimationFrame\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "Vector3 [] AnimationFrame\&.mainHand"

.PP
Definition at line \fB9\fP of file \fBAnimationFrame\&.cs\fP\&.
.SS "Vector3 [] AnimationFrame\&.offHand"

.PP
Definition at line \fB12\fP of file \fBAnimationFrame\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
