.TH "AreaTypeWork" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AreaTypeWork
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBAreaType\fP\&.
.PP
Inherited by \fBAreaTypeWorkplace\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "override bool \fBIsWork\fP\fR [get]\fP"
.br
.ti -1c
.RI "override bool \fBCanAssign\fP\fR [get]\fP"
.br
.ti -1c
.RI "override bool \fBIsPublicArea\fP\fR [get]\fP"
.br
.in -1c

Properties inherited from \fBAreaType\fP
.in +1c
.ti -1c
.RI "virtual bool \fBCanAssign\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBIsWork\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBIsPublicArea\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBIsPrison\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual string \fBRandomNameGroup\fP\fR [get]\fP"
.br
.ti -1c
.RI "string \fBlangHeader\fP\fR [get]\fP"
.br
.ti -1c
.RI "\fBSourceArea\&.Row\fP \fBsource\fP\fR [get]\fP"
.br
.in -1c

Properties inherited from \fBEClass\fP
.in +1c
.ti -1c
.RI "static \fBGame\fP \fBgame\fP\fR [get]\fP"
.br
.ti -1c
.RI "static bool \fBAdvMode\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBPlayer\fP \fBplayer\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBChara\fP \fBpc\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBUI\fP \fBui\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBMap\fP \fB_map\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBZone\fP \fB_zone\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranchOrHomeBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFaction\fP \fBHome\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFaction\fP \fBWilds\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBScene\fP \fBscene\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBBaseGameScreen\fP \fBscreen\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameSetting\fP \fBsetting\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameData\fP \fBgamedata\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBColorProfile\fP \fBColors\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBWorld\fP \fBworld\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBsources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBeditorSources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static SoundManager \fBSound\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBCoreDebug\fP \fBdebug\fP\fR [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Public Member Functions inherited from \fBAreaType\fP
.in +1c
.ti -1c
.RI "virtual \fBAIAct\fP \fBGetAI\fP ()"
.br
.ti -1c
.RI "virtual int \fBGetEfficiency\fP ()"
.br
.in -1c

Static Public Member Functions inherited from \fBEClass\fP
.in +1c
.ti -1c
.RI "static int \fBrnd\fP (int a)"
.br
.ti -1c
.RI "static int \fBcurve\fP (int a, int start, int step, int rate=75)"
.br
.ti -1c
.RI "static int \fBrndHalf\fP (int a)"
.br
.ti -1c
.RI "static float \fBrndf\fP (float a)"
.br
.ti -1c
.RI "static int \fBrndSqrt\fP (int a)"
.br
.ti -1c
.RI "static void \fBWait\fP (float a, \fBCard\fP c)"
.br
.ti -1c
.RI "static void \fBWait\fP (float a, \fBPoint\fP p)"
.br
.ti -1c
.RI "static int \fBBigger\fP (int a, int b)"
.br
.ti -1c
.RI "static int \fBSmaller\fP (int a, int b)"
.br
.in -1c

Public Attributes inherited from \fBAreaType\fP
.in +1c
.ti -1c
.RI "HashSet< int > \fBuidCharas\fP = new HashSet<int>()"
.br
.ti -1c
.RI "string \fBid\fP = 'Public'"
.br
.ti -1c
.RI "\fBBaseArea\fP \fBowner\fP"
.br
.ti -1c
.RI "\fBSourceArea\&.Row\fP \fB_source\fP"
.br
.in -1c

Static Public Attributes inherited from \fBEClass\fP
.in +1c
.ti -1c
.RI "static \fBCore\fP \fBcore\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB4\fP of file \fBAreaTypeWork\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "override bool AreaTypeWork\&.CanAssign\fR [get]\fP"

.PP
Definition at line \fB18\fP of file \fBAreaTypeWork\&.cs\fP\&.
.SS "override bool AreaTypeWork\&.IsPublicArea\fR [get]\fP"

.PP
Definition at line \fB28\fP of file \fBAreaTypeWork\&.cs\fP\&.
.SS "override bool AreaTypeWork\&.IsWork\fR [get]\fP"

.PP
Definition at line \fB8\fP of file \fBAreaTypeWork\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
