.TH "Assets.Resources.Scene.Profile.Global.SceneGlobalProfile" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Assets.Resources.Scene.Profile.Global.SceneGlobalProfile
.SH SYNOPSIS
.br
.PP
.PP
Inherits ScriptableObject\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBfovPower\fP"
.br
.ti -1c
.RI "float \fBfovModNonGradient\fP"
.br
.ti -1c
.RI "float \fBplayerLightPowerLimit\fP"
.br
.ti -1c
.RI "AnimationCurve \fBlightLookupCurve\fP"
.br
.ti -1c
.RI "AnimationCurve \fBsnowLimit\fP"
.br
.ti -1c
.RI "AnimationCurve \fBroofLightLimitMod\fP"
.br
.ti -1c
.RI "float \fBmodSublight1\fP"
.br
.ti -1c
.RI "float \fBmodSublight2\fP"
.br
.ti -1c
.RI "float \fBedgeLight\fP"
.br
.ti -1c
.RI "float \fBsnowLight\fP"
.br
.ti -1c
.RI "float \fBsnowColor\fP"
.br
.ti -1c
.RI "float \fBsnowColor2\fP"
.br
.ti -1c
.RI "float \fBsnowBrightness\fP"
.br
.ti -1c
.RI "Vector3Int \fBsnowRGB\fP"
.br
.ti -1c
.RI "bool \fBlimitGradient\fP"
.br
.ti -1c
.RI "int \fBtestFovRange\fP"
.br
.ti -1c
.RI "float \fBtestFovPower\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB7\fP of file \fBSceneGlobalProfile\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "float Assets\&.Resources\&.Scene\&.Profile\&.Global\&.SceneGlobalProfile\&.edgeLight"

.PP
Definition at line \fB34\fP of file \fBSceneGlobalProfile\&.cs\fP\&.
.SS "float Assets\&.Resources\&.Scene\&.Profile\&.Global\&.SceneGlobalProfile\&.fovModNonGradient"

.PP
Definition at line \fB13\fP of file \fBSceneGlobalProfile\&.cs\fP\&.
.SS "float Assets\&.Resources\&.Scene\&.Profile\&.Global\&.SceneGlobalProfile\&.fovPower"

.PP
Definition at line \fB10\fP of file \fBSceneGlobalProfile\&.cs\fP\&.
.SS "AnimationCurve Assets\&.Resources\&.Scene\&.Profile\&.Global\&.SceneGlobalProfile\&.lightLookupCurve"

.PP
Definition at line \fB19\fP of file \fBSceneGlobalProfile\&.cs\fP\&.
.SS "bool Assets\&.Resources\&.Scene\&.Profile\&.Global\&.SceneGlobalProfile\&.limitGradient"

.PP
Definition at line \fB52\fP of file \fBSceneGlobalProfile\&.cs\fP\&.
.SS "float Assets\&.Resources\&.Scene\&.Profile\&.Global\&.SceneGlobalProfile\&.modSublight1"

.PP
Definition at line \fB28\fP of file \fBSceneGlobalProfile\&.cs\fP\&.
.SS "float Assets\&.Resources\&.Scene\&.Profile\&.Global\&.SceneGlobalProfile\&.modSublight2"

.PP
Definition at line \fB31\fP of file \fBSceneGlobalProfile\&.cs\fP\&.
.SS "float Assets\&.Resources\&.Scene\&.Profile\&.Global\&.SceneGlobalProfile\&.playerLightPowerLimit"

.PP
Definition at line \fB16\fP of file \fBSceneGlobalProfile\&.cs\fP\&.
.SS "AnimationCurve Assets\&.Resources\&.Scene\&.Profile\&.Global\&.SceneGlobalProfile\&.roofLightLimitMod"

.PP
Definition at line \fB25\fP of file \fBSceneGlobalProfile\&.cs\fP\&.
.SS "float Assets\&.Resources\&.Scene\&.Profile\&.Global\&.SceneGlobalProfile\&.snowBrightness"

.PP
Definition at line \fB46\fP of file \fBSceneGlobalProfile\&.cs\fP\&.
.SS "float Assets\&.Resources\&.Scene\&.Profile\&.Global\&.SceneGlobalProfile\&.snowColor"

.PP
Definition at line \fB40\fP of file \fBSceneGlobalProfile\&.cs\fP\&.
.SS "float Assets\&.Resources\&.Scene\&.Profile\&.Global\&.SceneGlobalProfile\&.snowColor2"

.PP
Definition at line \fB43\fP of file \fBSceneGlobalProfile\&.cs\fP\&.
.SS "float Assets\&.Resources\&.Scene\&.Profile\&.Global\&.SceneGlobalProfile\&.snowLight"

.PP
Definition at line \fB37\fP of file \fBSceneGlobalProfile\&.cs\fP\&.
.SS "AnimationCurve Assets\&.Resources\&.Scene\&.Profile\&.Global\&.SceneGlobalProfile\&.snowLimit"

.PP
Definition at line \fB22\fP of file \fBSceneGlobalProfile\&.cs\fP\&.
.SS "Vector3Int Assets\&.Resources\&.Scene\&.Profile\&.Global\&.SceneGlobalProfile\&.snowRGB"

.PP
Definition at line \fB49\fP of file \fBSceneGlobalProfile\&.cs\fP\&.
.SS "float Assets\&.Resources\&.Scene\&.Profile\&.Global\&.SceneGlobalProfile\&.testFovPower"

.PP
Definition at line \fB59\fP of file \fBSceneGlobalProfile\&.cs\fP\&.
.SS "int Assets\&.Resources\&.Scene\&.Profile\&.Global\&.SceneGlobalProfile\&.testFovRange"

.PP
Definition at line \fB56\fP of file \fBSceneGlobalProfile\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
