.TH "Assets.Resources.Scene.Profile.Global" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Assets.Resources.Scene.Profile.Global
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSceneGlobalProfile\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
