.TH "BackerContentInspector.ContentCard" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BackerContentInspector.ContentCard
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBBackerContentInspector\&.Content\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBApply\fP ()"
.br
.ti -1c
.RI "override void \fBRemove\fP ()"
.br
.in -1c

Public Member Functions inherited from \fBBackerContentInspector\&.Content\fP
.in +1c
.ti -1c
.RI "virtual void \fBOnValidate\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBCard\fP \fBc\fP"
.br
.in -1c

Public Attributes inherited from \fBBackerContentInspector\&.Content\fP
.in +1c
.ti -1c
.RI "int \fBid\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override string \fBname\fP\fR [get]\fP"
.br
.in -1c

Properties inherited from \fBBackerContentInspector\&.Content\fP
.in +1c
.ti -1c
.RI "virtual string \fBname\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB93\fP of file \fBBackerContentInspector\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void BackerContentInspector\&.ContentCard\&.Apply ()\fR [virtual]\fP"

.PP
Reimplemented from \fBBackerContentInspector\&.Content\fP\&.
.PP
Definition at line \fB106\fP of file \fBBackerContentInspector\&.cs\fP\&.
.SS "override void BackerContentInspector\&.ContentCard\&.Remove ()\fR [virtual]\fP"

.PP
Reimplemented from \fBBackerContentInspector\&.Content\fP\&.
.PP
Definition at line \fB112\fP of file \fBBackerContentInspector\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBCard\fP BackerContentInspector\&.ContentCard\&.c"

.PP
Definition at line \fB118\fP of file \fBBackerContentInspector\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "override string BackerContentInspector\&.ContentCard\&.name\fR [get]\fP"

.PP
Definition at line \fB97\fP of file \fBBackerContentInspector\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
