.TH "BackerContentInspector.Content" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BackerContentInspector.Content
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBBackerContentInspector\&.ContentCard\fP, and \fBBackerContentInspector\&.ContentObj\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBOnValidate\fP ()"
.br
.ti -1c
.RI "virtual void \fBApply\fP ()"
.br
.ti -1c
.RI "virtual void \fBRemove\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBid\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "virtual string \fBname\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB32\fP of file \fBBackerContentInspector\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual void BackerContentInspector\&.Content\&.Apply ()\fR [virtual]\fP"

.PP
Definition at line \fB50\fP of file \fBBackerContentInspector\&.cs\fP\&.
.SS "virtual void BackerContentInspector\&.Content\&.OnValidate ()\fR [virtual]\fP"

.PP
Definition at line \fB45\fP of file \fBBackerContentInspector\&.cs\fP\&.
.SS "virtual void BackerContentInspector\&.Content\&.Remove ()\fR [virtual]\fP"

.PP
Definition at line \fB55\fP of file \fBBackerContentInspector\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int BackerContentInspector\&.Content\&.id"

.PP
Definition at line \fB60\fP of file \fBBackerContentInspector\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "virtual string BackerContentInspector\&.Content\&.name\fR [get]\fP"

.PP
Definition at line \fB36\fP of file \fBBackerContentInspector\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
