.TH "BackerContent" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BackerContent
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBEClass\fP\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static string \fBConvertName\fP (string s)"
.br
.ti -1c
.RI "static void \fBGakiConvert\fP (ref string text)"
.br
.in -1c

Static Public Member Functions inherited from \fBEClass\fP
.in +1c
.ti -1c
.RI "static int \fBrnd\fP (int a)"
.br
.ti -1c
.RI "static int \fBcurve\fP (int a, int start, int step, int rate=75)"
.br
.ti -1c
.RI "static int \fBrndHalf\fP (int a)"
.br
.ti -1c
.RI "static float \fBrndf\fP (float a)"
.br
.ti -1c
.RI "static int \fBrndSqrt\fP (int a)"
.br
.ti -1c
.RI "static void \fBWait\fP (float a, \fBCard\fP c)"
.br
.ti -1c
.RI "static void \fBWait\fP (float a, \fBPoint\fP p)"
.br
.ti -1c
.RI "static int \fBBigger\fP (int a, int b)"
.br
.ti -1c
.RI "static int \fBSmaller\fP (int a, int b)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static int \fBindexTree\fP"
.br
.ti -1c
.RI "static int \fBindexRemain\fP"
.br
.ti -1c
.RI "static int \fBindexLantern\fP"
.br
.ti -1c
.RI "static int \fBindexSnail\fP"
.br
.ti -1c
.RI "static int \fBindexFollower\fP"
.br
.ti -1c
.RI "static int \fBindexSister\fP"
.br
.in -1c

Static Public Attributes inherited from \fBEClass\fP
.in +1c
.ti -1c
.RI "static \fBCore\fP \fBcore\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Properties inherited from \fBEClass\fP
.in +1c
.ti -1c
.RI "static \fBGame\fP \fBgame\fP\fR [get]\fP"
.br
.ti -1c
.RI "static bool \fBAdvMode\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBPlayer\fP \fBplayer\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBChara\fP \fBpc\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBUI\fP \fBui\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBMap\fP \fB_map\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBZone\fP \fB_zone\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranchOrHomeBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFaction\fP \fBHome\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFaction\fP \fBWilds\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBScene\fP \fBscene\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBBaseGameScreen\fP \fBscreen\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameSetting\fP \fBsetting\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameData\fP \fBgamedata\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBColorProfile\fP \fBColors\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBWorld\fP \fBworld\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBsources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBeditorSources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static SoundManager \fBSound\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBCoreDebug\fP \fBdebug\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB4\fP of file \fBBackerContent\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "static string BackerContent\&.ConvertName (string s)\fR [static]\fP"

.PP
Definition at line \fB7\fP of file \fBBackerContent\&.cs\fP\&.
.SS "static void BackerContent\&.GakiConvert (ref string text)\fR [static]\fP"

.PP
Definition at line \fB13\fP of file \fBBackerContent\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int BackerContent\&.indexFollower\fR [static]\fP"

.PP
Definition at line \fB36\fP of file \fBBackerContent\&.cs\fP\&.
.SS "int BackerContent\&.indexLantern\fR [static]\fP"

.PP
Definition at line \fB30\fP of file \fBBackerContent\&.cs\fP\&.
.SS "int BackerContent\&.indexRemain\fR [static]\fP"

.PP
Definition at line \fB27\fP of file \fBBackerContent\&.cs\fP\&.
.SS "int BackerContent\&.indexSister\fR [static]\fP"

.PP
Definition at line \fB39\fP of file \fBBackerContent\&.cs\fP\&.
.SS "int BackerContent\&.indexSnail\fR [static]\fP"

.PP
Definition at line \fB33\fP of file \fBBackerContent\&.cs\fP\&.
.SS "int BackerContent\&.indexTree\fR [static]\fP"

.PP
Definition at line \fB24\fP of file \fBBackerContent\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
