.TH "BaseInspectPos" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BaseInspectPos
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBIInspect\fP\&.
.PP
Inherited by \fBBlockInfo\fP, and \fBObjInfo\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBOnInspect\fP ()"
.br
.ti -1c
.RI "virtual void \fBWriteNote\fP (UINote n, Action< UINote > onWriteNote=null, IInspect\&.NoteMode mode=IInspect\&.NoteMode\&.Default, \fBRecipe\fP recipe=null)"
.br
.in -1c

Public Member Functions inherited from \fBIInspect\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBPoint\fP \fBpos\fP = new \fBPoint\fP()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBPoint\fP \fBInspectPoint\fP\fR [get]\fP"
.br
.ti -1c
.RI "unsafe Vector3 \fBInspectPosition\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBCanInspect\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual string \fBInspectName\fP\fR [get]\fP"
.br
.in -1c

Properties inherited from \fBIInspect\fP
.SS "Additional Inherited Members"


Public Types inherited from \fBIInspect\fP
.in +1c
.ti -1c
.RI "enum \fBNoteMode\fP { \fBDefault\fP, \fBRecipe\fP, \fBProduct\fP, \fBInfo\fP }"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB5\fP of file \fBBaseInspectPos\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void BaseInspectPos\&.OnInspect ()"

.PP
Implements \fBIInspect\fP\&.
.PP
Definition at line \fB8\fP of file \fBBaseInspectPos\&.cs\fP\&.
.SS "virtual void BaseInspectPos\&.WriteNote (UINote n, Action< UINote > onWriteNote = \fRnull\fP, IInspect\&.NoteMode mode = \fRIInspect::NoteMode::Default\fP, \fBRecipe\fP recipe = \fRnull\fP)\fR [virtual]\fP"

.PP
Implements \fBIInspect\fP\&.
.PP
Definition at line \fB53\fP of file \fBBaseInspectPos\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBPoint\fP BaseInspectPos\&.pos = new \fBPoint\fP()"

.PP
Definition at line \fB58\fP of file \fBBaseInspectPos\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "virtual bool BaseInspectPos\&.CanInspect\fR [get]\fP"

.PP
Implements \fBIInspect\fP\&.
.PP
Definition at line \fB34\fP of file \fBBaseInspectPos\&.cs\fP\&.
.SS "virtual string BaseInspectPos\&.InspectName\fR [get]\fP"

.PP
Implements \fBIInspect\fP\&.
.PP
Definition at line \fB44\fP of file \fBBaseInspectPos\&.cs\fP\&.
.SS "\fBPoint\fP BaseInspectPos\&.InspectPoint\fR [get]\fP"

.PP
Implements \fBIInspect\fP\&.
.PP
Definition at line \fB14\fP of file \fBBaseInspectPos\&.cs\fP\&.
.SS "unsafe Vector3 BaseInspectPos\&.InspectPosition\fR [get]\fP"

.PP
Implements \fBIInspect\fP\&.
.PP
Definition at line \fB24\fP of file \fBBaseInspectPos\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
