.TH "BaseGameScreen.FocusOption" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BaseGameScreen.FocusOption
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBPoint\fP \fBpos\fP"
.br
.ti -1c
.RI "float \fBspeed\fP = 2f"
.br
.ti -1c
.RI "bool \fBlinear\fP = true"
.br
.ti -1c
.RI "bool \fBplayer\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB1041\fP of file \fBBaseGameScreen\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "bool BaseGameScreen\&.FocusOption\&.linear = true"

.PP
Definition at line \fB1050\fP of file \fBBaseGameScreen\&.cs\fP\&.
.SS "bool BaseGameScreen\&.FocusOption\&.player"

.PP
Definition at line \fB1053\fP of file \fBBaseGameScreen\&.cs\fP\&.
.SS "\fBPoint\fP BaseGameScreen\&.FocusOption\&.pos"

.PP
Definition at line \fB1044\fP of file \fBBaseGameScreen\&.cs\fP\&.
.SS "float BaseGameScreen\&.FocusOption\&.speed = 2f"

.PP
Definition at line \fB1047\fP of file \fBBaseGameScreen\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
