.TH "BaseGameScreen" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BaseGameScreen
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBEMono\fP\&.
.PP
Inherited by \fBGameScreen\fP, \fBGameScreenElona\fP, and \fBGameScreenNoMap\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFocusOption\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBActivate\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnActivate\fP ()"
.br
.ti -1c
.RI "void \fBDeactivate\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnDeactivate\fP ()"
.br
.ti -1c
.RI "virtual void \fBSetUnitSize\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnEndPlayerTurn\fP ()"
.br
.ti -1c
.RI "unsafe void \fBDraw\fP ()"
.br
.ti -1c
.RI "void \fBUpdateShaders\fP (float time=0f)"
.br
.ti -1c
.RI "virtual void \fBOnChangeHour\fP ()"
.br
.ti -1c
.RI "virtual unsafe void \fBRefreshPosition\fP ()"
.br
.ti -1c
.RI "void \fBRefreshAll\fP ()"
.br
.ti -1c
.RI "void \fBRefreshScreenSize\fP ()"
.br
.ti -1c
.RI "\fBPoint\fP \fBGetRandomPoint\fP ()"
.br
.ti -1c
.RI "void \fBRefreshSky\fP ()"
.br
.ti -1c
.RI "virtual void \fBRefreshWeather\fP ()"
.br
.ti -1c
.RI "void \fBRefreshGrading\fP ()"
.br
.ti -1c
.RI "void \fBRefreshTilt\fP ()"
.br
.ti -1c
.RI "void \fBScrollMouse\fP (float x, float y)"
.br
.ti -1c
.RI "void \fBScrollAxis\fP (Vector3 axis, bool direct=false)"
.br
.ti -1c
.RI "void \fBFocus\fP (\fBInt3\fP ints)"
.br
.ti -1c
.RI "void \fBFocus\fP (int x, int y)"
.br
.ti -1c
.RI "void \fBFocus\fP (\fBCard\fP c)"
.br
.ti -1c
.RI "void \fBFocusCenter\fP ()"
.br
.ti -1c
.RI "unsafe void \fBFocus\fP (\fBPoint\fP pos)"
.br
.ti -1c
.RI "void \fBFocusPC\fP ()"
.br
.ti -1c
.RI "void \fBFocusImmediate\fP (\fBPoint\fP pos)"
.br
.ti -1c
.RI "void \fBSnapScreen\fP (ref Vector3 v, float zoom)"
.br
.ti -1c
.RI "void \fBSetZoom\fP (float z)"
.br
.ti -1c
.RI "void \fBSetTargetZoomIndex\fP (int index)"
.br
.ti -1c
.RI "void \fBModTargetZoomIndex\fP (int a)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBSharpenAmount\fP"
.br
.ti -1c
.RI "float \fBcamSpeed2\fP"
.br
.ti -1c
.RI "float \fBheightLight\fP"
.br
.ti -1c
.RI "float \fBpushbackSpeed\fP"
.br
.ti -1c
.RI "Vector2 \fBsnapSize\fP"
.br
.ti -1c
.RI "Vector2 \fBtileSize\fP"
.br
.ti -1c
.RI "Vector2 \fBtileAlign\fP"
.br
.ti -1c
.RI "Vector2 \fBtileWorldSize\fP"
.br
.ti -1c
.RI "Vector2 \fBtileViewSize\fP"
.br
.ti -1c
.RI "Vector3 \fBtileWeight\fP"
.br
.ti -1c
.RI "Vector3 \fBfocusFix\fP"
.br
.ti -1c
.RI "Vector3 \fBtileOffsetHeight\fP"
.br
.ti -1c
.RI "Vector3 \fBtileWeightHeight\fP"
.br
.ti -1c
.RI "Vector3 \fBplaneAngle\fP"
.br
.ti -1c
.RI "Vector3 \fBplaneSpeed\fP"
.br
.ti -1c
.RI "Vector2 \fBpaddings\fP"
.br
.ti -1c
.RI "Vector2 \fBpaddingOffset\fP"
.br
.ti -1c
.RI "Vector3 \fBlastPos\fP"
.br
.ti -1c
.RI "Rect \fBmapLimit\fP"
.br
.ti -1c
.RI "float \fBZoom\fP"
.br
.ti -1c
.RI "float \fBnextMove\fP"
.br
.ti -1c
.RI "float \fBfocusSpeed\fP"
.br
.ti -1c
.RI "float \fBfocusSpeedSlow\fP"
.br
.ti -1c
.RI "float \fBfocusSpeedSlow2\fP"
.br
.ti -1c
.RI "int \fBwidth\fP"
.br
.ti -1c
.RI "int \fBheight\fP"
.br
.ti -1c
.RI "int \fBscrollX\fP"
.br
.ti -1c
.RI "int \fBscrollY\fP"
.br
.ti -1c
.RI "int \fBmoonLevel\fP"
.br
.ti -1c
.RI "\fBBaseTileMap\fP \fBtileMap\fP"
.br
.ti -1c
.RI "\fBBaseTileSelector\fP \fBtileSelector\fP"
.br
.ti -1c
.RI "\fBScreenGuide\fP \fBguide\fP"
.br
.ti -1c
.RI "Grid \fBgrid\fP"
.br
.ti -1c
.RI "MeshRenderer \fBoverlayShadow\fP"
.br
.ti -1c
.RI "\fBPCOrbit\fP \fBpcOrbit\fP"
.br
.ti -1c
.RI "float \fBforcePrecision\fP"
.br
.ti -1c
.RI "bool \fBisCameraMoving\fP"
.br
.ti -1c
.RI "\fBBaseGameScreen\&.FocusOption\fP \fBfocusOption\fP"
.br
.ti -1c
.RI "Vector3? \fBfocusPos\fP"
.br
.ti -1c
.RI "Vector3 \fBposition\fP"
.br
.ti -1c
.RI "float \fBscreenFixX\fP"
.br
.ti -1c
.RI "float \fBscreenFixX2\fP"
.br
.ti -1c
.RI "float \fBscreenFixX3\fP"
.br
.ti -1c
.RI "float \fBscreenFixX4\fP"
.br
.ti -1c
.RI "float \fBscreenFixY\fP"
.br
.ti -1c
.RI "float \fBscreenFixY2\fP"
.br
.ti -1c
.RI "float \fBscreenFixY3\fP"
.br
.ti -1c
.RI "float \fBscreenFixY4\fP"
.br
.ti -1c
.RI "bool \fBinstantFocus\fP"
.br
.ti -1c
.RI "int \fBtargetZoomIndex\fP"
.br
.ti -1c
.RI "float \fBtargetZoom\fP = 0\&.5f"
.br
.ti -1c
.RI "float \fBzoomTimer\fP"
.br
.ti -1c
.RI "Vector3 \fBzoomPos\fP"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "Vector3 \fBcamPos\fP"
.br
.ti -1c
.RI "Vector3 \fBpushBack\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "bool \fBfixFocus\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual float \fBTargetZoom\fP\fR [get]\fP"
.br
.ti -1c
.RI "\fBCameraSupport\fP \fBcamSupport\fP\fR [get]\fP"
.br
.ti -1c
.RI "Transform \fBtransFocus\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual float \fBSkyRate\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual float \fBViewHeight\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBIsGameScreen\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBIsLocalMap\fP\fR [get]\fP"
.br
.in -1c

Properties inherited from \fBEMono\fP
.in +1c
.ti -1c
.RI "static \fBGame\fP \fBgame\fP\fR [get]\fP"
.br
.ti -1c
.RI "static bool \fBAdvMode\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBPlayer\fP \fBplayer\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBChara\fP \fBpc\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBUI\fP \fBui\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBMap\fP \fB_map\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBZone\fP \fB_zone\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranchOrHomeBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFaction\fP \fBHome\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBScene\fP \fBscene\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBBaseGameScreen\fP \fBscreen\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameSetting\fP \fBsetting\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameData\fP \fBgamedata\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBColorProfile\fP \fBColors\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBWorld\fP \fBworld\fP\fR [get]\fP"
.br
.ti -1c
.RI "static SoundManager \fBSound\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBsources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBeditorSources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBCoreDebug\fP \fBdebug\fP\fR [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Static Public Member Functions inherited from \fBEMono\fP
.in +1c
.ti -1c
.RI "static int \fBrnd\fP (int a)"
.br
.in -1c

Static Public Attributes inherited from \fBEMono\fP
.in +1c
.ti -1c
.RI "static \fBCore\fP \fBcore\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB5\fP of file \fBBaseGameScreen\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void BaseGameScreen\&.Activate ()"

.PP
Definition at line \fB89\fP of file \fBBaseGameScreen\&.cs\fP\&.
.SS "void BaseGameScreen\&.Deactivate ()"

.PP
Definition at line \fB145\fP of file \fBBaseGameScreen\&.cs\fP\&.
.SS "unsafe void BaseGameScreen\&.Draw ()"

.PP
Definition at line \fB168\fP of file \fBBaseGameScreen\&.cs\fP\&.
.SS "void BaseGameScreen\&.Focus (\fBCard\fP c)"

.PP
Definition at line \fB661\fP of file \fBBaseGameScreen\&.cs\fP\&.
.SS "void BaseGameScreen\&.Focus (int x, int y)"

.PP
Definition at line \fB647\fP of file \fBBaseGameScreen\&.cs\fP\&.
.SS "void BaseGameScreen\&.Focus (\fBInt3\fP ints)"

.PP
Definition at line \fB641\fP of file \fBBaseGameScreen\&.cs\fP\&.
.SS "unsafe void BaseGameScreen\&.Focus (\fBPoint\fP pos)"

.PP
Definition at line \fB678\fP of file \fBBaseGameScreen\&.cs\fP\&.
.SS "void BaseGameScreen\&.FocusCenter ()"

.PP
Definition at line \fB671\fP of file \fBBaseGameScreen\&.cs\fP\&.
.SS "void BaseGameScreen\&.FocusImmediate (\fBPoint\fP pos)"

.PP
Definition at line \fB693\fP of file \fBBaseGameScreen\&.cs\fP\&.
.SS "void BaseGameScreen\&.FocusPC ()"

.PP
Definition at line \fB684\fP of file \fBBaseGameScreen\&.cs\fP\&.
.SS "\fBPoint\fP BaseGameScreen\&.GetRandomPoint ()"

.PP
Definition at line \fB474\fP of file \fBBaseGameScreen\&.cs\fP\&.
.SS "void BaseGameScreen\&.ModTargetZoomIndex (int a)"

.PP
Definition at line \fB782\fP of file \fBBaseGameScreen\&.cs\fP\&.
.SS "virtual void BaseGameScreen\&.OnActivate ()\fR [virtual]\fP"

.PP
Definition at line \fB140\fP of file \fBBaseGameScreen\&.cs\fP\&.
.SS "virtual void BaseGameScreen\&.OnChangeHour ()\fR [virtual]\fP"

.PP
Definition at line \fB306\fP of file \fBBaseGameScreen\&.cs\fP\&.
.SS "virtual void BaseGameScreen\&.OnDeactivate ()\fR [virtual]\fP"

.PP
Definition at line \fB153\fP of file \fBBaseGameScreen\&.cs\fP\&.
.SS "virtual void BaseGameScreen\&.OnEndPlayerTurn ()\fR [virtual]\fP"

.PP
Definition at line \fB163\fP of file \fBBaseGameScreen\&.cs\fP\&.
.SS "void BaseGameScreen\&.RefreshAll ()"

.PP
Definition at line \fB423\fP of file \fBBaseGameScreen\&.cs\fP\&.
.SS "void BaseGameScreen\&.RefreshGrading ()"

.PP
Definition at line \fB581\fP of file \fBBaseGameScreen\&.cs\fP\&.
.SS "virtual unsafe void BaseGameScreen\&.RefreshPosition ()\fR [virtual]\fP"

.PP
Definition at line \fB311\fP of file \fBBaseGameScreen\&.cs\fP\&.
.SS "void BaseGameScreen\&.RefreshScreenSize ()"

.PP
Definition at line \fB444\fP of file \fBBaseGameScreen\&.cs\fP\&.
.SS "void BaseGameScreen\&.RefreshSky ()"

.PP
Definition at line \fB484\fP of file \fBBaseGameScreen\&.cs\fP\&.
.SS "void BaseGameScreen\&.RefreshTilt ()"

.PP
Definition at line \fB612\fP of file \fBBaseGameScreen\&.cs\fP\&.
.SS "virtual void BaseGameScreen\&.RefreshWeather ()\fR [virtual]\fP"

.PP
Definition at line \fB504\fP of file \fBBaseGameScreen\&.cs\fP\&.
.SS "void BaseGameScreen\&.ScrollAxis (Vector3 axis, bool direct = \fRfalse\fP)"

.PP
Definition at line \fB630\fP of file \fBBaseGameScreen\&.cs\fP\&.
.SS "void BaseGameScreen\&.ScrollMouse (float x, float y)"

.PP
Definition at line \fB619\fP of file \fBBaseGameScreen\&.cs\fP\&.
.SS "void BaseGameScreen\&.SetTargetZoomIndex (int index)"

.PP
Definition at line \fB770\fP of file \fBBaseGameScreen\&.cs\fP\&.
.SS "virtual void BaseGameScreen\&.SetUnitSize ()\fR [virtual]\fP"

.PP
Definition at line \fB158\fP of file \fBBaseGameScreen\&.cs\fP\&.
.SS "void BaseGameScreen\&.SetZoom (float z)"

.PP
Definition at line \fB761\fP of file \fBBaseGameScreen\&.cs\fP\&.
.SS "void BaseGameScreen\&.SnapScreen (ref Vector3 v, float zoom)"

.PP
Definition at line \fB703\fP of file \fBBaseGameScreen\&.cs\fP\&.
.SS "void BaseGameScreen\&.UpdateShaders (float time = \fR0f\fP)"

.PP
Definition at line \fB247\fP of file \fBBaseGameScreen\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "Vector3 BaseGameScreen\&.camPos\fR [protected]\fP"

.PP
Definition at line \fB989\fP of file \fBBaseGameScreen\&.cs\fP\&.
.SS "float BaseGameScreen\&.camSpeed2"

.PP
Definition at line \fB862\fP of file \fBBaseGameScreen\&.cs\fP\&.
.SS "Vector3 BaseGameScreen\&.focusFix"

.PP
Definition at line \fB889\fP of file \fBBaseGameScreen\&.cs\fP\&.
.SS "\fBBaseGameScreen\&.FocusOption\fP BaseGameScreen\&.focusOption"

.PP
Definition at line \fB978\fP of file \fBBaseGameScreen\&.cs\fP\&.
.SS "Vector3? BaseGameScreen\&.focusPos"

.PP
Definition at line \fB982\fP of file \fBBaseGameScreen\&.cs\fP\&.
.SS "float BaseGameScreen\&.focusSpeed"

.PP
Definition at line \fB925\fP of file \fBBaseGameScreen\&.cs\fP\&.
.SS "float BaseGameScreen\&.focusSpeedSlow"

.PP
Definition at line \fB929\fP of file \fBBaseGameScreen\&.cs\fP\&.
.SS "float BaseGameScreen\&.focusSpeedSlow2"

.PP
Definition at line \fB933\fP of file \fBBaseGameScreen\&.cs\fP\&.
.SS "float BaseGameScreen\&.forcePrecision"

.PP
Definition at line \fB970\fP of file \fBBaseGameScreen\&.cs\fP\&.
.SS "Grid BaseGameScreen\&.grid"

.PP
Definition at line \fB960\fP of file \fBBaseGameScreen\&.cs\fP\&.
.SS "\fBScreenGuide\fP BaseGameScreen\&.guide"

.PP
Definition at line \fB957\fP of file \fBBaseGameScreen\&.cs\fP\&.
.SS "int BaseGameScreen\&.height"

.PP
Definition at line \fB939\fP of file \fBBaseGameScreen\&.cs\fP\&.
.SS "float BaseGameScreen\&.heightLight"

.PP
Definition at line \fB865\fP of file \fBBaseGameScreen\&.cs\fP\&.
.SS "bool BaseGameScreen\&.instantFocus"

.PP
Definition at line \fB1026\fP of file \fBBaseGameScreen\&.cs\fP\&.
.SS "bool BaseGameScreen\&.isCameraMoving"

.PP
Definition at line \fB974\fP of file \fBBaseGameScreen\&.cs\fP\&.
.SS "Vector3 BaseGameScreen\&.lastPos"

.PP
Definition at line \fB910\fP of file \fBBaseGameScreen\&.cs\fP\&.
.SS "Rect BaseGameScreen\&.mapLimit"

.PP
Definition at line \fB913\fP of file \fBBaseGameScreen\&.cs\fP\&.
.SS "int BaseGameScreen\&.moonLevel"

.PP
Definition at line \fB948\fP of file \fBBaseGameScreen\&.cs\fP\&.
.SS "float BaseGameScreen\&.nextMove"

.PP
Definition at line \fB921\fP of file \fBBaseGameScreen\&.cs\fP\&.
.SS "MeshRenderer BaseGameScreen\&.overlayShadow"

.PP
Definition at line \fB963\fP of file \fBBaseGameScreen\&.cs\fP\&.
.SS "Vector2 BaseGameScreen\&.paddingOffset"

.PP
Definition at line \fB907\fP of file \fBBaseGameScreen\&.cs\fP\&.
.SS "Vector2 BaseGameScreen\&.paddings"

.PP
Definition at line \fB904\fP of file \fBBaseGameScreen\&.cs\fP\&.
.SS "\fBPCOrbit\fP BaseGameScreen\&.pcOrbit"

.PP
Definition at line \fB966\fP of file \fBBaseGameScreen\&.cs\fP\&.
.SS "Vector3 BaseGameScreen\&.planeAngle"

.PP
Definition at line \fB898\fP of file \fBBaseGameScreen\&.cs\fP\&.
.SS "Vector3 BaseGameScreen\&.planeSpeed"

.PP
Definition at line \fB901\fP of file \fBBaseGameScreen\&.cs\fP\&.
.SS "Vector3 BaseGameScreen\&.position"

.PP
Definition at line \fB986\fP of file \fBBaseGameScreen\&.cs\fP\&.
.SS "Vector3 BaseGameScreen\&.pushBack\fR [protected]\fP"

.PP
Definition at line \fB992\fP of file \fBBaseGameScreen\&.cs\fP\&.
.SS "float BaseGameScreen\&.pushbackSpeed"

.PP
Definition at line \fB868\fP of file \fBBaseGameScreen\&.cs\fP\&.
.SS "float BaseGameScreen\&.screenFixX"

.PP
Definition at line \fB995\fP of file \fBBaseGameScreen\&.cs\fP\&.
.SS "float BaseGameScreen\&.screenFixX2"

.PP
Definition at line \fB998\fP of file \fBBaseGameScreen\&.cs\fP\&.
.SS "float BaseGameScreen\&.screenFixX3"

.PP
Definition at line \fB1001\fP of file \fBBaseGameScreen\&.cs\fP\&.
.SS "float BaseGameScreen\&.screenFixX4"

.PP
Definition at line \fB1004\fP of file \fBBaseGameScreen\&.cs\fP\&.
.SS "float BaseGameScreen\&.screenFixY"

.PP
Definition at line \fB1007\fP of file \fBBaseGameScreen\&.cs\fP\&.
.SS "float BaseGameScreen\&.screenFixY2"

.PP
Definition at line \fB1010\fP of file \fBBaseGameScreen\&.cs\fP\&.
.SS "float BaseGameScreen\&.screenFixY3"

.PP
Definition at line \fB1013\fP of file \fBBaseGameScreen\&.cs\fP\&.
.SS "float BaseGameScreen\&.screenFixY4"

.PP
Definition at line \fB1016\fP of file \fBBaseGameScreen\&.cs\fP\&.
.SS "int BaseGameScreen\&.scrollX"

.PP
Definition at line \fB942\fP of file \fBBaseGameScreen\&.cs\fP\&.
.SS "int BaseGameScreen\&.scrollY"

.PP
Definition at line \fB945\fP of file \fBBaseGameScreen\&.cs\fP\&.
.SS "float BaseGameScreen\&.SharpenAmount"

.PP
Definition at line \fB859\fP of file \fBBaseGameScreen\&.cs\fP\&.
.SS "Vector2 BaseGameScreen\&.snapSize"

.PP
Definition at line \fB871\fP of file \fBBaseGameScreen\&.cs\fP\&.
.SS "float BaseGameScreen\&.targetZoom = 0\&.5f"

.PP
Definition at line \fB1032\fP of file \fBBaseGameScreen\&.cs\fP\&.
.SS "int BaseGameScreen\&.targetZoomIndex"

.PP
Definition at line \fB1029\fP of file \fBBaseGameScreen\&.cs\fP\&.
.SS "Vector2 BaseGameScreen\&.tileAlign"

.PP
Definition at line \fB877\fP of file \fBBaseGameScreen\&.cs\fP\&.
.SS "\fBBaseTileMap\fP BaseGameScreen\&.tileMap"

.PP
Definition at line \fB951\fP of file \fBBaseGameScreen\&.cs\fP\&.
.SS "Vector3 BaseGameScreen\&.tileOffsetHeight"

.PP
Definition at line \fB892\fP of file \fBBaseGameScreen\&.cs\fP\&.
.SS "\fBBaseTileSelector\fP BaseGameScreen\&.tileSelector"

.PP
Definition at line \fB954\fP of file \fBBaseGameScreen\&.cs\fP\&.
.SS "Vector2 BaseGameScreen\&.tileSize"

.PP
Definition at line \fB874\fP of file \fBBaseGameScreen\&.cs\fP\&.
.SS "Vector2 BaseGameScreen\&.tileViewSize"

.PP
Definition at line \fB883\fP of file \fBBaseGameScreen\&.cs\fP\&.
.SS "Vector3 BaseGameScreen\&.tileWeight"

.PP
Definition at line \fB886\fP of file \fBBaseGameScreen\&.cs\fP\&.
.SS "Vector3 BaseGameScreen\&.tileWeightHeight"

.PP
Definition at line \fB895\fP of file \fBBaseGameScreen\&.cs\fP\&.
.SS "Vector2 BaseGameScreen\&.tileWorldSize"

.PP
Definition at line \fB880\fP of file \fBBaseGameScreen\&.cs\fP\&.
.SS "int BaseGameScreen\&.width"

.PP
Definition at line \fB936\fP of file \fBBaseGameScreen\&.cs\fP\&.
.SS "float BaseGameScreen\&.Zoom"

.PP
Definition at line \fB917\fP of file \fBBaseGameScreen\&.cs\fP\&.
.SS "Vector3 BaseGameScreen\&.zoomPos"

.PP
Definition at line \fB1038\fP of file \fBBaseGameScreen\&.cs\fP\&.
.SS "float BaseGameScreen\&.zoomTimer"

.PP
Definition at line \fB1035\fP of file \fBBaseGameScreen\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "\fBCameraSupport\fP BaseGameScreen\&.camSupport\fR [get]\fP, \fR [protected]\fP"

.PP
Definition at line \fB30\fP of file \fBBaseGameScreen\&.cs\fP\&.
.SS "bool BaseGameScreen\&.fixFocus\fR [get]\fP"

.PP
Definition at line \fB9\fP of file \fBBaseGameScreen\&.cs\fP\&.
.SS "virtual bool BaseGameScreen\&.IsGameScreen\fR [get]\fP"

.PP
Definition at line \fB70\fP of file \fBBaseGameScreen\&.cs\fP\&.
.SS "virtual bool BaseGameScreen\&.IsLocalMap\fR [get]\fP"

.PP
Definition at line \fB80\fP of file \fBBaseGameScreen\&.cs\fP\&.
.SS "virtual float BaseGameScreen\&.SkyRate\fR [get]\fP"

.PP
Definition at line \fB50\fP of file \fBBaseGameScreen\&.cs\fP\&.
.SS "virtual float BaseGameScreen\&.TargetZoom\fR [get]\fP"

.PP
Definition at line \fB20\fP of file \fBBaseGameScreen\&.cs\fP\&.
.SS "Transform BaseGameScreen\&.transFocus\fR [get]\fP, \fR [protected]\fP"

.PP
Definition at line \fB40\fP of file \fBBaseGameScreen\&.cs\fP\&.
.SS "virtual float BaseGameScreen\&.ViewHeight\fR [get]\fP"

.PP
Definition at line \fB60\fP of file \fBBaseGameScreen\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
