.TH "Biography" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Biography
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBEClass\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "string \fBTextAge\fP (\fBChara\fP c)"
.br
.ti -1c
.RI "void \fBGenerate\fP (\fBChara\fP c)"
.br
.ti -1c
.RI "void \fBRerollBio\fP (\fBChara\fP c, int ageIndex=0, bool keepParent=false)"
.br
.ti -1c
.RI "void \fBGenerateBirthday\fP (\fBChara\fP c, int ageIndex=0)"
.br
.ti -1c
.RI "void \fBGenerateAppearance\fP (\fBChara\fP c)"
.br
.ti -1c
.RI "void \fBGenerateDad\fP ()"
.br
.ti -1c
.RI "void \fBGenerateMom\fP ()"
.br
.ti -1c
.RI "void \fBSetGender\fP (int g)"
.br
.ti -1c
.RI "void \fBSetPortrait\fP (\fBChara\fP c)"
.br
.ti -1c
.RI "string \fBTextBio\fP (\fBChara\fP c)"
.br
.ti -1c
.RI "string \fBTextBio2\fP (\fBChara\fP c)"
.br
.ti -1c
.RI "string \fBTextBirthDate\fP (\fBChara\fP c, bool _age=false)"
.br
.ti -1c
.RI "string \fBTextAppearance\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int[] \fBints\fP = new int[20]"
.br
.ti -1c
.RI "string[] \fBstrs\fP = new string[3]"
.br
.ti -1c
.RI "int[] \fBpersonalities\fP = new int[5]"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static string[] \fBidFemale\fP"
.br
.in -1c

Static Public Attributes inherited from \fBEClass\fP
.in +1c
.ti -1c
.RI "static \fBCore\fP \fBcore\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBidLike\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "int \fBgender\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "int \fBweight\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "int \fBheight\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "int \fBbirthDay\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "int \fBbirthMonth\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "int \fBbirthYear\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "int \fBidHome\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "int \fBidDad\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "int \fBidMom\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "int \fBidLoc\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "int \fBidAdvDad\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "int \fBidAdvMom\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "int \fBidHobby\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "int \fBstability\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "int \fBlaw\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "int \fBaffection\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "int \fBdominance\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "int \fBextroversion\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "int \fBidInterest\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "string \fBnameHome\fP\fR [get]\fP"
.br
.ti -1c
.RI "string \fBnameLoc\fP\fR [get]\fP"
.br
.ti -1c
.RI "string \fBnameDad\fP\fR [get]\fP"
.br
.ti -1c
.RI "string \fBnameMom\fP\fR [get]\fP"
.br
.ti -1c
.RI "string \fBnameBirthplace\fP\fR [get]\fP"
.br
.ti -1c
.RI "int \fBage\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "int \fBageOriginal\fP\fR [get]\fP"
.br
.ti -1c
.RI "bool \fBIsUnderAge\fP\fR [get]\fP"
.br
.in -1c

Properties inherited from \fBEClass\fP
.in +1c
.ti -1c
.RI "static \fBGame\fP \fBgame\fP\fR [get]\fP"
.br
.ti -1c
.RI "static bool \fBAdvMode\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBPlayer\fP \fBplayer\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBChara\fP \fBpc\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBUI\fP \fBui\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBMap\fP \fB_map\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBZone\fP \fB_zone\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranchOrHomeBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFaction\fP \fBHome\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFaction\fP \fBWilds\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBScene\fP \fBscene\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBBaseGameScreen\fP \fBscreen\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameSetting\fP \fBsetting\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameData\fP \fBgamedata\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBColorProfile\fP \fBColors\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBWorld\fP \fBworld\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBsources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBeditorSources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static SoundManager \fBSound\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBCoreDebug\fP \fBdebug\fP\fR [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Static Public Member Functions inherited from \fBEClass\fP
.in +1c
.ti -1c
.RI "static int \fBrnd\fP (int a)"
.br
.ti -1c
.RI "static int \fBcurve\fP (int a, int start, int step, int rate=75)"
.br
.ti -1c
.RI "static int \fBrndHalf\fP (int a)"
.br
.ti -1c
.RI "static float \fBrndf\fP (float a)"
.br
.ti -1c
.RI "static int \fBrndSqrt\fP (int a)"
.br
.ti -1c
.RI "static void \fBWait\fP (float a, \fBCard\fP c)"
.br
.ti -1c
.RI "static void \fBWait\fP (float a, \fBPoint\fP p)"
.br
.ti -1c
.RI "static int \fBBigger\fP (int a, int b)"
.br
.ti -1c
.RI "static int \fBSmaller\fP (int a, int b)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB5\fP of file \fBBiography\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Biography\&.Generate (\fBChara\fP c)"

.PP
Definition at line \fB411\fP of file \fBBiography\&.cs\fP\&.
.SS "void Biography\&.GenerateAppearance (\fBChara\fP c)"

.PP
Definition at line \fB514\fP of file \fBBiography\&.cs\fP\&.
.SS "void Biography\&.GenerateBirthday (\fBChara\fP c, int ageIndex = \fR0\fP)"

.PP
Definition at line \fB495\fP of file \fBBiography\&.cs\fP\&.
.SS "void Biography\&.GenerateDad ()"

.PP
Definition at line \fB522\fP of file \fBBiography\&.cs\fP\&.
.SS "void Biography\&.GenerateMom ()"

.PP
Definition at line \fB529\fP of file \fBBiography\&.cs\fP\&.
.SS "void Biography\&.RerollBio (\fBChara\fP c, int ageIndex = \fR0\fP, bool keepParent = \fRfalse\fP)"

.PP
Definition at line \fB481\fP of file \fBBiography\&.cs\fP\&.
.SS "void Biography\&.SetGender (int g)"

.PP
Definition at line \fB560\fP of file \fBBiography\&.cs\fP\&.
.SS "void Biography\&.SetPortrait (\fBChara\fP c)"

.PP
Definition at line \fB570\fP of file \fBBiography\&.cs\fP\&.
.SS "string Biography\&.TextAge (\fBChara\fP c)"

.PP
Definition at line \fB393\fP of file \fBBiography\&.cs\fP\&.
.SS "string Biography\&.TextAppearance ()"

.PP
Definition at line \fB606\fP of file \fBBiography\&.cs\fP\&.
.SS "string Biography\&.TextBio (\fBChara\fP c)"

.PP
Definition at line \fB581\fP of file \fBBiography\&.cs\fP\&.
.SS "string Biography\&.TextBio2 (\fBChara\fP c)"

.PP
Definition at line \fB594\fP of file \fBBiography\&.cs\fP\&.
.SS "string Biography\&.TextBirthDate (\fBChara\fP c, bool _age = \fRfalse\fP)"

.PP
Definition at line \fB600\fP of file \fBBiography\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "string [] Biography\&.idFemale\fR [static]\fP"
\fBInitial value:\fP
.nf
= new string[]
    {
        "shojo",
        "sister",
        "sister_cat",
        "younglady",
        "sister_undead"
    }
.PP
.fi

.PP
Definition at line \fB612\fP of file \fBBiography\&.cs\fP\&.
.SS "int [] Biography\&.ints = new int[20]"

.PP
Definition at line \fB623\fP of file \fBBiography\&.cs\fP\&.
.SS "int [] Biography\&.personalities = new int[5]"

.PP
Definition at line \fB630\fP of file \fBBiography\&.cs\fP\&.
.SS "string [] Biography\&.strs = new string[3]"

.PP
Definition at line \fB627\fP of file \fBBiography\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "int Biography\&.affection\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB250\fP of file \fBBiography\&.cs\fP\&.
.SS "int Biography\&.age\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB360\fP of file \fBBiography\&.cs\fP\&.
.SS "int Biography\&.ageOriginal\fR [get]\fP"

.PP
Definition at line \fB374\fP of file \fBBiography\&.cs\fP\&.
.SS "int Biography\&.birthDay\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB70\fP of file \fBBiography\&.cs\fP\&.
.SS "int Biography\&.birthMonth\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB85\fP of file \fBBiography\&.cs\fP\&.
.SS "int Biography\&.birthYear\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB100\fP of file \fBBiography\&.cs\fP\&.
.SS "int Biography\&.dominance\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB265\fP of file \fBBiography\&.cs\fP\&.
.SS "int Biography\&.extroversion\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB280\fP of file \fBBiography\&.cs\fP\&.
.SS "int Biography\&.gender\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB25\fP of file \fBBiography\&.cs\fP\&.
.SS "int Biography\&.height\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB55\fP of file \fBBiography\&.cs\fP\&.
.SS "int Biography\&.idAdvDad\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB175\fP of file \fBBiography\&.cs\fP\&.
.SS "int Biography\&.idAdvMom\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB190\fP of file \fBBiography\&.cs\fP\&.
.SS "int Biography\&.idDad\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB130\fP of file \fBBiography\&.cs\fP\&.
.SS "int Biography\&.idHobby\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB205\fP of file \fBBiography\&.cs\fP\&.
.SS "int Biography\&.idHome\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB115\fP of file \fBBiography\&.cs\fP\&.
.SS "int Biography\&.idInterest\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB295\fP of file \fBBiography\&.cs\fP\&.
.SS "string Biography\&.idLike\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB10\fP of file \fBBiography\&.cs\fP\&.
.SS "int Biography\&.idLoc\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB160\fP of file \fBBiography\&.cs\fP\&.
.SS "int Biography\&.idMom\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB145\fP of file \fBBiography\&.cs\fP\&.
.SS "bool Biography\&.IsUnderAge\fR [get]\fP"

.PP
Definition at line \fB384\fP of file \fBBiography\&.cs\fP\&.
.SS "int Biography\&.law\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB235\fP of file \fBBiography\&.cs\fP\&.
.SS "string Biography\&.nameBirthplace\fR [get]\fP"

.PP
Definition at line \fB349\fP of file \fBBiography\&.cs\fP\&.
.SS "string Biography\&.nameDad\fR [get]\fP"

.PP
Definition at line \fB329\fP of file \fBBiography\&.cs\fP\&.
.SS "string Biography\&.nameHome\fR [get]\fP"

.PP
Definition at line \fB309\fP of file \fBBiography\&.cs\fP\&.
.SS "string Biography\&.nameLoc\fR [get]\fP"

.PP
Definition at line \fB319\fP of file \fBBiography\&.cs\fP\&.
.SS "string Biography\&.nameMom\fR [get]\fP"

.PP
Definition at line \fB339\fP of file \fBBiography\&.cs\fP\&.
.SS "int Biography\&.stability\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB220\fP of file \fBBiography\&.cs\fP\&.
.SS "int Biography\&.weight\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB40\fP of file \fBBiography\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
