.TH "BiomeProfile.TileFloor" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BiomeProfile.TileFloor
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBBiomeProfile\&.Tile\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fB_id\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "string \fB_idSub\fP\fR [get, set]\fP"
.br
.in -1c

Properties inherited from \fBBiomeProfile\&.Tile\fP
.in +1c
.ti -1c
.RI "string \fB_mat\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "string \fB_matSub\fP\fR [get, set]\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Public Types inherited from \fBBiomeProfile\&.BaseTile\fP
.in +1c
.ti -1c
.RI "enum \fBSubType\fP { \fBNone\fP, \fBRnd5\fP = 10, \fBRnd10\fP, \fBRnd20\fP, \fBPattern\fP = 20 }"
.br
.ti -1c
.RI "enum \fBDirType\fP { \fBRandom8\fP, \fBRandomSqrt8\fP, \fBRandomSqrtSqrt8\fP }"
.br
.in -1c

Public Member Functions inherited from \fBBiomeProfile\&.Tile\fP
.in +1c
.ti -1c
.RI "int \fBGetDir\fP ()"
.br
.in -1c

Public Attributes inherited from \fBBiomeProfile\&.Tile\fP
.in +1c
.ti -1c
.RI "int \fBid\fP"
.br
.ti -1c
.RI "int \fBmat\fP"
.br
.ti -1c
.RI "int \fBidSub\fP"
.br
.ti -1c
.RI "int \fBmatSub\fP"
.br
.ti -1c
.RI "BiomeProfile\&.BaseTile\&.SubType \fBsubType\fP"
.br
.ti -1c
.RI "BiomeProfile\&.BaseTile\&.DirType \fBdirType\fP"
.br
.in -1c

Protected Member Functions inherited from \fBBiomeProfile\&.BaseTile\fP
.in +1c
.ti -1c
.RI "string \fB_GetThing\fP (string id)"
.br
.ti -1c
.RI "void \fB_SetThing\fP (ref string id, string value)"
.br
.ti -1c
.RI "IEnumerable< string > \fBThingRows\fP ()"
.br
.ti -1c
.RI "string \fB_GetObj\fP (int id)"
.br
.ti -1c
.RI "void \fB_SetObj\fP (ref int id, string value)"
.br
.ti -1c
.RI "IEnumerable< string > \fBObjRows\fP ()"
.br
.ti -1c
.RI "string \fB_GetFloor\fP (int id)"
.br
.ti -1c
.RI "void \fB_SetFloor\fP (ref int id, string value)"
.br
.ti -1c
.RI "IEnumerable< string > \fBFloorRows\fP ()"
.br
.ti -1c
.RI "string \fB_GetBlock\fP (int id)"
.br
.ti -1c
.RI "void \fB_SetBlock\fP (ref int id, string value)"
.br
.ti -1c
.RI "IEnumerable< string > \fBBlockRows\fP ()"
.br
.ti -1c
.RI "string \fB_GetMat\fP (int id)"
.br
.ti -1c
.RI "void \fB_SetMat\fP (ref int id, string value)"
.br
.ti -1c
.RI "IEnumerable< string > \fBMatRows\fP ()"
.br
.ti -1c
.RI "string \fB_GetSpawnList\fP (string id)"
.br
.ti -1c
.RI "void \fB_SetSpawnList\fP (ref string id, string value)"
.br
.ti -1c
.RI "IEnumerable< string > \fB_SpawnList\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB503\fP of file \fBBiomeProfile\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "string BiomeProfile\&.TileFloor\&._id\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB508\fP of file \fBBiomeProfile\&.cs\fP\&.
.SS "string BiomeProfile\&.TileFloor\&._idSub\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB523\fP of file \fBBiomeProfile\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
