.TH "BiomeProfile.Style" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BiomeProfile.Style
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBBiomeProfile\&.BaseTile\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "string \fBGetIdLight\fP (bool wall)"
.br
.ti -1c
.RI "string \fBGetIdStairs\fP (bool upstairs)"
.br
.ti -1c
.RI "string \fBGetIdDoor\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBdoorChance\fP = 0\&.9f"
.br
.ti -1c
.RI "BiomeProfile\&.DoorStyle \fBdoorStyle\fP"
.br
.ti -1c
.RI "int \fBmatDoor\fP"
.br
.ti -1c
.RI "BiomeProfile\&.StairsStyle \fBstairsStyle\fP"
.br
.ti -1c
.RI "int \fBmatStairs\fP"
.br
.ti -1c
.RI "List< \fBBiomeProfile\&.Cluster\&.ItemThing\fP > \fBlights\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fB_matDoor\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "string \fB_matStairs\fP\fR [get, set]\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Public Types inherited from \fBBiomeProfile\&.BaseTile\fP
.in +1c
.ti -1c
.RI "enum \fBSubType\fP { \fBNone\fP, \fBRnd5\fP = 10, \fBRnd10\fP, \fBRnd20\fP, \fBPattern\fP = 20 }"
.br
.ti -1c
.RI "enum \fBDirType\fP { \fBRandom8\fP, \fBRandomSqrt8\fP, \fBRandomSqrtSqrt8\fP }"
.br
.in -1c

Protected Member Functions inherited from \fBBiomeProfile\&.BaseTile\fP
.in +1c
.ti -1c
.RI "string \fB_GetThing\fP (string id)"
.br
.ti -1c
.RI "void \fB_SetThing\fP (ref string id, string value)"
.br
.ti -1c
.RI "IEnumerable< string > \fBThingRows\fP ()"
.br
.ti -1c
.RI "string \fB_GetObj\fP (int id)"
.br
.ti -1c
.RI "void \fB_SetObj\fP (ref int id, string value)"
.br
.ti -1c
.RI "IEnumerable< string > \fBObjRows\fP ()"
.br
.ti -1c
.RI "string \fB_GetFloor\fP (int id)"
.br
.ti -1c
.RI "void \fB_SetFloor\fP (ref int id, string value)"
.br
.ti -1c
.RI "IEnumerable< string > \fBFloorRows\fP ()"
.br
.ti -1c
.RI "string \fB_GetBlock\fP (int id)"
.br
.ti -1c
.RI "void \fB_SetBlock\fP (ref int id, string value)"
.br
.ti -1c
.RI "IEnumerable< string > \fBBlockRows\fP ()"
.br
.ti -1c
.RI "string \fB_GetMat\fP (int id)"
.br
.ti -1c
.RI "void \fB_SetMat\fP (ref int id, string value)"
.br
.ti -1c
.RI "IEnumerable< string > \fBMatRows\fP ()"
.br
.ti -1c
.RI "string \fB_GetSpawnList\fP (string id)"
.br
.ti -1c
.RI "void \fB_SetSpawnList\fP (ref string id, string value)"
.br
.ti -1c
.RI "IEnumerable< string > \fB_SpawnList\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB584\fP of file \fBBiomeProfile\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "string BiomeProfile\&.Style\&.GetIdDoor ()"

.PP
Definition at line \fB669\fP of file \fBBiomeProfile\&.cs\fP\&.
.SS "string BiomeProfile\&.Style\&.GetIdLight (bool wall)"

.PP
Definition at line \fB617\fP of file \fBBiomeProfile\&.cs\fP\&.
.SS "string BiomeProfile\&.Style\&.GetIdStairs (bool upstairs)"

.PP
Definition at line \fB637\fP of file \fBBiomeProfile\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "float BiomeProfile\&.Style\&.doorChance = 0\&.9f"

.PP
Definition at line \fB687\fP of file \fBBiomeProfile\&.cs\fP\&.
.SS "BiomeProfile\&.DoorStyle BiomeProfile\&.Style\&.doorStyle"

.PP
Definition at line \fB690\fP of file \fBBiomeProfile\&.cs\fP\&.
.SS "List<\fBBiomeProfile\&.Cluster\&.ItemThing\fP> BiomeProfile\&.Style\&.lights"

.PP
Definition at line \fB704\fP of file \fBBiomeProfile\&.cs\fP\&.
.SS "int BiomeProfile\&.Style\&.matDoor"

.PP
Definition at line \fB694\fP of file \fBBiomeProfile\&.cs\fP\&.
.SS "int BiomeProfile\&.Style\&.matStairs"

.PP
Definition at line \fB701\fP of file \fBBiomeProfile\&.cs\fP\&.
.SS "BiomeProfile\&.StairsStyle BiomeProfile\&.Style\&.stairsStyle"

.PP
Definition at line \fB697\fP of file \fBBiomeProfile\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "string BiomeProfile\&.Style\&._matDoor\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB589\fP of file \fBBiomeProfile\&.cs\fP\&.
.SS "string BiomeProfile\&.Style\&._matStairs\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB604\fP of file \fBBiomeProfile\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
