.TH "BiomeProfile.Cluster.BaseItem" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BiomeProfile.Cluster.BaseItem
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBBiomeProfile\&.BaseTile\fP\&.
.PP
Inherited by \fBBiomeProfile\&.Cluster\&.Item\fP, and \fBBiomeProfile\&.Cluster\&.ItemThing\fP\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBchance\fP = 1f"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "virtual bool \fBIsSpawnOnBlock\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBIsSpawnOnWater\fP\fR [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Public Types inherited from \fBBiomeProfile\&.BaseTile\fP
.in +1c
.ti -1c
.RI "enum \fBSubType\fP { \fBNone\fP, \fBRnd5\fP = 10, \fBRnd10\fP, \fBRnd20\fP, \fBPattern\fP = 20 }"
.br
.ti -1c
.RI "enum \fBDirType\fP { \fBRandom8\fP, \fBRandomSqrt8\fP, \fBRandomSqrtSqrt8\fP }"
.br
.in -1c

Protected Member Functions inherited from \fBBiomeProfile\&.BaseTile\fP
.in +1c
.ti -1c
.RI "string \fB_GetThing\fP (string id)"
.br
.ti -1c
.RI "void \fB_SetThing\fP (ref string id, string value)"
.br
.ti -1c
.RI "IEnumerable< string > \fBThingRows\fP ()"
.br
.ti -1c
.RI "string \fB_GetObj\fP (int id)"
.br
.ti -1c
.RI "void \fB_SetObj\fP (ref int id, string value)"
.br
.ti -1c
.RI "IEnumerable< string > \fBObjRows\fP ()"
.br
.ti -1c
.RI "string \fB_GetFloor\fP (int id)"
.br
.ti -1c
.RI "void \fB_SetFloor\fP (ref int id, string value)"
.br
.ti -1c
.RI "IEnumerable< string > \fBFloorRows\fP ()"
.br
.ti -1c
.RI "string \fB_GetBlock\fP (int id)"
.br
.ti -1c
.RI "void \fB_SetBlock\fP (ref int id, string value)"
.br
.ti -1c
.RI "IEnumerable< string > \fBBlockRows\fP ()"
.br
.ti -1c
.RI "string \fB_GetMat\fP (int id)"
.br
.ti -1c
.RI "void \fB_SetMat\fP (ref int id, string value)"
.br
.ti -1c
.RI "IEnumerable< string > \fBMatRows\fP ()"
.br
.ti -1c
.RI "string \fB_GetSpawnList\fP (string id)"
.br
.ti -1c
.RI "void \fB_SetSpawnList\fP (ref string id, string value)"
.br
.ti -1c
.RI "IEnumerable< string > \fB_SpawnList\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB821\fP of file \fBBiomeProfile\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "float BiomeProfile\&.Cluster\&.BaseItem\&.chance = 1f"

.PP
Definition at line \fB844\fP of file \fBBiomeProfile\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "virtual bool BiomeProfile\&.Cluster\&.BaseItem\&.IsSpawnOnBlock\fR [get]\fP"

.PP
Definition at line \fB825\fP of file \fBBiomeProfile\&.cs\fP\&.
.SS "virtual bool BiomeProfile\&.Cluster\&.BaseItem\&.IsSpawnOnWater\fR [get]\fP"

.PP
Definition at line \fB835\fP of file \fBBiomeProfile\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
