.TH "BiomeProfile.ClusterObj" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BiomeProfile.ClusterObj
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBBiomeProfile\&.Cluster\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override bool \fBTryCreate\fP (\fBPoint\fP p)"
.br
.in -1c

Public Member Functions inherited from \fBBiomeProfile\&.Cluster\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "List< \fBBiomeProfile\&.Cluster\&.Item\fP > \fBitems\fP"
.br
.in -1c

Public Attributes inherited from \fBBiomeProfile\&.Cluster\fP
.in +1c
.ti -1c
.RI "BiomeProfile\&.Cluster\&.Type \fBtype\fP"
.br
.ti -1c
.RI "float \fBdensity\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Public Types inherited from \fBBiomeProfile\&.Cluster\fP
.in +1c
.ti -1c
.RI "enum \fBType\fP { \fBScatter\fP, \fBScatterExterior\fP, \fBScatterInterior\fP, \fBScatterNonObstacle\fP, \fBByWall\fP = 10 }"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB916\fP of file \fBBiomeProfile\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override bool BiomeProfile\&.ClusterObj\&.TryCreate (\fBPoint\fP p)\fR [virtual]\fP"

.PP
Reimplemented from \fBBiomeProfile\&.Cluster\fP\&.
.PP
Definition at line \fB919\fP of file \fBBiomeProfile\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "List<\fBBiomeProfile\&.Cluster\&.Item\fP> BiomeProfile\&.ClusterObj\&.items"

.PP
Definition at line \fB948\fP of file \fBBiomeProfile\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
