.TH "BiomeProfile" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BiomeProfile
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBEScriptable\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBaseTile\fP"
.br
.ti -1c
.RI "class \fBCluster\fP"
.br
.ti -1c
.RI "class \fBClusterObj\fP"
.br
.ti -1c
.RI "class \fBClusters\fP"
.br
.ti -1c
.RI "class \fBClusterThing\fP"
.br
.ti -1c
.RI "class \fBSpawnList\fP"
.br
.ti -1c
.RI "class \fBSpawnListChara\fP"
.br
.ti -1c
.RI "class \fBSpawnListThing\fP"
.br
.ti -1c
.RI "class \fBSpawns\fP"
.br
.ti -1c
.RI "class \fBStyle\fP"
.br
.ti -1c
.RI "class \fBTile\fP"
.br
.ti -1c
.RI "class \fBTileBlock\fP"
.br
.ti -1c
.RI "class \fBTileFloor\fP"
.br
.ti -1c
.RI "class \fBTileGroup\fP"
.br
.in -1c
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBDoorStyle\fP { \fBsimpleWood\fP, \fBFirmWood\fP, \fBStone\fP, \fBJail\fP, \fBRune\fP }"
.br
.ti -1c
.RI "enum \fBStairsStyle\fP { \fBSoil\fP, \fBWood\fP, \fBStone\fP, \fBRock\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBPopulate\fP (\fBPoint\fP point, bool interior=false)"
.br
.ti -1c
.RI "void \fBReset\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBInit\fP ()"
.br
.in -1c

Static Public Member Functions inherited from \fBEScriptable\fP
.in +1c
.ti -1c
.RI "static int \fBrnd\fP (int a)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "NoiseLayer \fBlayerBlock\fP"
.br
.ti -1c
.RI "BiomeID \fBid\fP"
.br
.ti -1c
.RI "Color \fBcolor\fP"
.br
.ti -1c
.RI "\fBFowProfile\fP \fBfowProfile\fP"
.br
.ti -1c
.RI "\fBBiomeProfile\&.TileGroup\fP \fB_exterior\fP"
.br
.ti -1c
.RI "\fBBiomeProfile\&.TileGroup\fP \fB_interior\fP"
.br
.ti -1c
.RI "\fBBiomeProfile\&.Style\fP \fBstyle\fP"
.br
.ti -1c
.RI "\fBBiomeProfile\&.Spawns\fP \fBspawn\fP"
.br
.ti -1c
.RI "\fBBiomeProfile\&.Clusters\fP \fBcluster\fP"
.br
.ti -1c
.RI "string \fBtags\fP"
.br
.ti -1c
.RI "int \fBfloor_height\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static bool \fBforceInitialize\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBBiomeProfile\&.TileGroup\fP \fBexterior\fP\fR [get]\fP"
.br
.ti -1c
.RI "\fBBiomeProfile\&.TileGroup\fP \fBinterior\fP\fR [get]\fP"
.br
.ti -1c
.RI "\fBSourceMaterial\&.Row\fP \fBMatFloor\fP\fR [get]\fP"
.br
.ti -1c
.RI "\fBSourceMaterial\&.Row\fP \fBMatSub\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB8\fP of file \fBBiomeProfile\&.cs\fP\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "enum BiomeProfile\&.DoorStyle"

.PP
Definition at line \fB189\fP of file \fBBiomeProfile\&.cs\fP\&.
.SS "enum BiomeProfile\&.StairsStyle"

.PP
Definition at line \fB204\fP of file \fBBiomeProfile\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "static void BiomeProfile\&.Init ()\fR [static]\fP"

.PP
Definition at line \fB123\fP of file \fBBiomeProfile\&.cs\fP\&.
.SS "void BiomeProfile\&.Populate (\fBPoint\fP point, bool interior = \fRfalse\fP)"

.PP
Definition at line \fB65\fP of file \fBBiomeProfile\&.cs\fP\&.
.SS "void BiomeProfile\&.Reset ()"

.PP
Definition at line \fB138\fP of file \fBBiomeProfile\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBBiomeProfile\&.TileGroup\fP BiomeProfile\&._exterior"

.PP
Definition at line \fB160\fP of file \fBBiomeProfile\&.cs\fP\&.
.SS "\fBBiomeProfile\&.TileGroup\fP BiomeProfile\&._interior"

.PP
Definition at line \fB163\fP of file \fBBiomeProfile\&.cs\fP\&.
.SS "\fBBiomeProfile\&.Clusters\fP BiomeProfile\&.cluster"

.PP
Definition at line \fB172\fP of file \fBBiomeProfile\&.cs\fP\&.
.SS "Color BiomeProfile\&.color"

.PP
Definition at line \fB154\fP of file \fBBiomeProfile\&.cs\fP\&.
.SS "int BiomeProfile\&.floor_height"

.PP
Definition at line \fB178\fP of file \fBBiomeProfile\&.cs\fP\&.
.SS "bool BiomeProfile\&.forceInitialize\fR [static]\fP"

.PP
Definition at line \fB145\fP of file \fBBiomeProfile\&.cs\fP\&.
.SS "\fBFowProfile\fP BiomeProfile\&.fowProfile"

.PP
Definition at line \fB157\fP of file \fBBiomeProfile\&.cs\fP\&.
.SS "BiomeID BiomeProfile\&.id"

.PP
Definition at line \fB151\fP of file \fBBiomeProfile\&.cs\fP\&.
.SS "NoiseLayer BiomeProfile\&.layerBlock"

.PP
Definition at line \fB148\fP of file \fBBiomeProfile\&.cs\fP\&.
.SS "\fBBiomeProfile\&.Spawns\fP BiomeProfile\&.spawn"

.PP
Definition at line \fB169\fP of file \fBBiomeProfile\&.cs\fP\&.
.SS "\fBBiomeProfile\&.Style\fP BiomeProfile\&.style"

.PP
Definition at line \fB166\fP of file \fBBiomeProfile\&.cs\fP\&.
.SS "string BiomeProfile\&.tags"

.PP
Definition at line \fB175\fP of file \fBBiomeProfile\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "\fBBiomeProfile\&.TileGroup\fP BiomeProfile\&.exterior\fR [get]\fP"

.PP
Definition at line \fB12\fP of file \fBBiomeProfile\&.cs\fP\&.
.SS "\fBBiomeProfile\&.TileGroup\fP BiomeProfile\&.interior\fR [get]\fP"

.PP
Definition at line \fB22\fP of file \fBBiomeProfile\&.cs\fP\&.
.SS "\fBSourceMaterial\&.Row\fP BiomeProfile\&.MatFloor\fR [get]\fP"

.PP
Definition at line \fB36\fP of file \fBBiomeProfile\&.cs\fP\&.
.SS "\fBSourceMaterial\&.Row\fP BiomeProfile\&.MatSub\fR [get]\fP"

.PP
Definition at line \fB51\fP of file \fBBiomeProfile\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
