.TH "BiomeProfile.TileGroup" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BiomeProfile.TileGroup
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBBiomeProfile\&.TileFloor\fP \fBfloor\fP"
.br
.ti -1c
.RI "\fBBiomeProfile\&.TileBlock\fP \fBblock\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB573\fP of file \fBBiomeProfile\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBBiomeProfile\&.TileBlock\fP BiomeProfile\&.TileGroup\&.block"

.PP
Definition at line \fB579\fP of file \fBBiomeProfile\&.cs\fP\&.
.SS "\fBBiomeProfile\&.TileFloor\fP BiomeProfile\&.TileGroup\&.floor"

.PP
Definition at line \fB576\fP of file \fBBiomeProfile\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
