.TH "BiomeProfile.Clusters" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BiomeProfile.Clusters
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "List< \fBBiomeProfile\&.ClusterObj\fP > \fBobj\fP"
.br
.ti -1c
.RI "List< \fBBiomeProfile\&.ClusterThing\fP > \fBthing\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB779\fP of file \fBBiomeProfile\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "List<\fBBiomeProfile\&.ClusterObj\fP> BiomeProfile\&.Clusters\&.obj"

.PP
Definition at line \fB782\fP of file \fBBiomeProfile\&.cs\fP\&.
.SS "List<\fBBiomeProfile\&.ClusterThing\fP> BiomeProfile\&.Clusters\&.thing"

.PP
Definition at line \fB785\fP of file \fBBiomeProfile\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
