.TH "BiomeProfile.BaseTile" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BiomeProfile.BaseTile
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBBiomeProfile\&.Cluster\&.BaseItem\fP, \fBBiomeProfile\&.SpawnList\fP, \fBBiomeProfile\&.Style\fP, and \fBBiomeProfile\&.Tile\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBSubType\fP { \fBNone\fP, \fBRnd5\fP = 10, \fBRnd10\fP, \fBRnd20\fP, \fBPattern\fP = 20 }"
.br
.ti -1c
.RI "enum \fBDirType\fP { \fBRandom8\fP, \fBRandomSqrt8\fP, \fBRandomSqrtSqrt8\fP }"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "string \fB_GetThing\fP (string id)"
.br
.ti -1c
.RI "void \fB_SetThing\fP (ref string id, string value)"
.br
.ti -1c
.RI "IEnumerable< string > \fBThingRows\fP ()"
.br
.ti -1c
.RI "string \fB_GetObj\fP (int id)"
.br
.ti -1c
.RI "void \fB_SetObj\fP (ref int id, string value)"
.br
.ti -1c
.RI "IEnumerable< string > \fBObjRows\fP ()"
.br
.ti -1c
.RI "string \fB_GetFloor\fP (int id)"
.br
.ti -1c
.RI "void \fB_SetFloor\fP (ref int id, string value)"
.br
.ti -1c
.RI "IEnumerable< string > \fBFloorRows\fP ()"
.br
.ti -1c
.RI "string \fB_GetBlock\fP (int id)"
.br
.ti -1c
.RI "void \fB_SetBlock\fP (ref int id, string value)"
.br
.ti -1c
.RI "IEnumerable< string > \fBBlockRows\fP ()"
.br
.ti -1c
.RI "string \fB_GetMat\fP (int id)"
.br
.ti -1c
.RI "void \fB_SetMat\fP (ref int id, string value)"
.br
.ti -1c
.RI "IEnumerable< string > \fBMatRows\fP ()"
.br
.ti -1c
.RI "string \fB_GetSpawnList\fP (string id)"
.br
.ti -1c
.RI "void \fB_SetSpawnList\fP (ref string id, string value)"
.br
.ti -1c
.RI "IEnumerable< string > \fB_SpawnList\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB217\fP of file \fBBiomeProfile\&.cs\fP\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "enum BiomeProfile\&.BaseTile\&.DirType"

.PP
Definition at line \fB417\fP of file \fBBiomeProfile\&.cs\fP\&.
.SS "enum BiomeProfile\&.BaseTile\&.SubType"

.PP
Definition at line \fB402\fP of file \fBBiomeProfile\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "string BiomeProfile\&.BaseTile\&._GetBlock (int id)\fR [protected]\fP"

.PP
Definition at line \fB309\fP of file \fBBiomeProfile\&.cs\fP\&.
.SS "string BiomeProfile\&.BaseTile\&._GetFloor (int id)\fR [protected]\fP"

.PP
Definition at line \fB278\fP of file \fBBiomeProfile\&.cs\fP\&.
.SS "string BiomeProfile\&.BaseTile\&._GetMat (int id)\fR [protected]\fP"

.PP
Definition at line \fB340\fP of file \fBBiomeProfile\&.cs\fP\&.
.SS "string BiomeProfile\&.BaseTile\&._GetObj (int id)\fR [protected]\fP"

.PP
Definition at line \fB247\fP of file \fBBiomeProfile\&.cs\fP\&.
.SS "string BiomeProfile\&.BaseTile\&._GetSpawnList (string id)\fR [protected]\fP"

.PP
Definition at line \fB375\fP of file \fBBiomeProfile\&.cs\fP\&.
.SS "string BiomeProfile\&.BaseTile\&._GetThing (string id)\fR [protected]\fP"

.PP
Definition at line \fB220\fP of file \fBBiomeProfile\&.cs\fP\&.
.SS "void BiomeProfile\&.BaseTile\&._SetBlock (ref int id, string value)\fR [protected]\fP"

.PP
Definition at line \fB328\fP of file \fBBiomeProfile\&.cs\fP\&.
.SS "void BiomeProfile\&.BaseTile\&._SetFloor (ref int id, string value)\fR [protected]\fP"

.PP
Definition at line \fB297\fP of file \fBBiomeProfile\&.cs\fP\&.
.SS "void BiomeProfile\&.BaseTile\&._SetMat (ref int id, string value)\fR [protected]\fP"

.PP
Definition at line \fB363\fP of file \fBBiomeProfile\&.cs\fP\&.
.SS "void BiomeProfile\&.BaseTile\&._SetObj (ref int id, string value)\fR [protected]\fP"

.PP
Definition at line \fB266\fP of file \fBBiomeProfile\&.cs\fP\&.
.SS "void BiomeProfile\&.BaseTile\&._SetSpawnList (ref string id, string value)\fR [protected]\fP"

.PP
Definition at line \fB390\fP of file \fBBiomeProfile\&.cs\fP\&.
.SS "void BiomeProfile\&.BaseTile\&._SetThing (ref string id, string value)\fR [protected]\fP"

.PP
Definition at line \fB235\fP of file \fBBiomeProfile\&.cs\fP\&.
.SS "IEnumerable< string > BiomeProfile\&.BaseTile\&._SpawnList ()\fR [protected]\fP"

.PP
Definition at line \fB396\fP of file \fBBiomeProfile\&.cs\fP\&.
.SS "IEnumerable< string > BiomeProfile\&.BaseTile\&.BlockRows ()\fR [protected]\fP"

.PP
Definition at line \fB334\fP of file \fBBiomeProfile\&.cs\fP\&.
.SS "IEnumerable< string > BiomeProfile\&.BaseTile\&.FloorRows ()\fR [protected]\fP"

.PP
Definition at line \fB303\fP of file \fBBiomeProfile\&.cs\fP\&.
.SS "IEnumerable< string > BiomeProfile\&.BaseTile\&.MatRows ()\fR [protected]\fP"

.PP
Definition at line \fB369\fP of file \fBBiomeProfile\&.cs\fP\&.
.SS "IEnumerable< string > BiomeProfile\&.BaseTile\&.ObjRows ()\fR [protected]\fP"

.PP
Definition at line \fB272\fP of file \fBBiomeProfile\&.cs\fP\&.
.SS "IEnumerable< string > BiomeProfile\&.BaseTile\&.ThingRows ()\fR [protected]\fP"

.PP
Definition at line \fB241\fP of file \fBBiomeProfile\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
