.TH "BiomeProfile.Cluster" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BiomeProfile.Cluster
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBBiomeProfile\&.ClusterObj\fP, and \fBBiomeProfile\&.ClusterThing\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBaseItem\fP"
.br
.ti -1c
.RI "class \fBItem\fP"
.br
.ti -1c
.RI "class \fBItemThing\fP"
.br
.in -1c
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBType\fP { \fBScatter\fP, \fBScatterExterior\fP, \fBScatterInterior\fP, \fBScatterNonObstacle\fP, \fBByWall\fP = 10 }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual bool \fBTryCreate\fP (\fBPoint\fP p)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "BiomeProfile\&.Cluster\&.Type \fBtype\fP"
.br
.ti -1c
.RI "float \fBdensity\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB790\fP of file \fBBiomeProfile\&.cs\fP\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "enum BiomeProfile\&.Cluster\&.Type"

.PP
Definition at line \fB805\fP of file \fBBiomeProfile\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual bool BiomeProfile\&.Cluster\&.TryCreate (\fBPoint\fP p)\fR [virtual]\fP"

.PP
Definition at line \fB793\fP of file \fBBiomeProfile\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "float BiomeProfile\&.Cluster\&.density"

.PP
Definition at line \fB802\fP of file \fBBiomeProfile\&.cs\fP\&.
.SS "BiomeProfile\&.Cluster\&.Type BiomeProfile\&.Cluster\&.type"

.PP
Definition at line \fB799\fP of file \fBBiomeProfile\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
