.TH "BiomeProfile.Spawns" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BiomeProfile.Spawns
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "string \fBGetRandomCharaId\fP ()"
.br
.ti -1c
.RI "string \fBGetRandomThingId\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "List< \fBBiomeProfile\&.SpawnListChara\fP > \fBchara\fP"
.br
.ti -1c
.RI "List< \fBBiomeProfile\&.SpawnListThing\fP > \fBthing\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB709\fP of file \fBBiomeProfile\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "string BiomeProfile\&.Spawns\&.GetRandomCharaId ()"

.PP
Definition at line \fB712\fP of file \fBBiomeProfile\&.cs\fP\&.
.SS "string BiomeProfile\&.Spawns\&.GetRandomThingId ()"

.PP
Definition at line \fB722\fP of file \fBBiomeProfile\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "List<\fBBiomeProfile\&.SpawnListChara\fP> BiomeProfile\&.Spawns\&.chara"

.PP
Definition at line \fB732\fP of file \fBBiomeProfile\&.cs\fP\&.
.SS "List<\fBBiomeProfile\&.SpawnListThing\fP> BiomeProfile\&.Spawns\&.thing"

.PP
Definition at line \fB735\fP of file \fBBiomeProfile\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
