.TH "BLOCK" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BLOCK
.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "const int \fBraw\fP = 1"
.br
.ti -1c
.RI "const int \fBfence\fP = 2"
.br
.ti -1c
.RI "const int \fBramp\fP = 3"
.br
.ti -1c
.RI "const int \fBstairs\fP = 4"
.br
.ti -1c
.RI "const int \fBhalfblock_raw\fP = 5"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB4\fP of file \fBBLOCK\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "const int BLOCK\&.fence = 2\fR [static]\fP"

.PP
Definition at line \fB10\fP of file \fBBLOCK\&.cs\fP\&.
.SS "const int BLOCK\&.halfblock_raw = 5\fR [static]\fP"

.PP
Definition at line \fB19\fP of file \fBBLOCK\&.cs\fP\&.
.SS "const int BLOCK\&.ramp = 3\fR [static]\fP"

.PP
Definition at line \fB13\fP of file \fBBLOCK\&.cs\fP\&.
.SS "const int BLOCK\&.raw = 1\fR [static]\fP"

.PP
Definition at line \fB7\fP of file \fBBLOCK\&.cs\fP\&.
.SS "const int BLOCK\&.stairs = 4\fR [static]\fP"

.PP
Definition at line \fB16\fP of file \fBBLOCK\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
