.TH "BlockInfo" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BlockInfo
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBBaseInspectPos\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBWriteNote\fP (UINote n, Action< UINote > onWriteNote=null, IInspect\&.NoteMode mode=IInspect\&.NoteMode\&.Default, \fBRecipe\fP recipe=null)"
.br
.in -1c

Public Member Functions inherited from \fBBaseInspectPos\fP
.in +1c
.ti -1c
.RI "void \fBOnInspect\fP ()"
.br
.in -1c

Public Member Functions inherited from \fBIInspect\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBBlockInfo\fP \fBGetTemp\fP (\fBPoint\fP _pos)"
.br
.ti -1c
.RI "static \fBBlockInfo\fP \fBGetTempList\fP (\fBPoint\fP _pos)"
.br
.ti -1c
.RI "static bool \fB_CanInspect\fP (\fBPoint\fP pos)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static \fBBlockInfo\fP \fBTemp\fP = new \fBBlockInfo\fP()"
.br
.ti -1c
.RI "static \fBBlockInfo\fP \fBTempList\fP = new \fBBlockInfo\fP()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBSourceBlock\&.Row\fP \fBsource\fP\fR [get]\fP"
.br
.ti -1c
.RI "override bool \fBCanInspect\fP\fR [get]\fP"
.br
.ti -1c
.RI "override string \fBInspectName\fP\fR [get]\fP"
.br
.in -1c

Properties inherited from \fBBaseInspectPos\fP
.in +1c
.ti -1c
.RI "\fBPoint\fP \fBInspectPoint\fP\fR [get]\fP"
.br
.ti -1c
.RI "unsafe Vector3 \fBInspectPosition\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBCanInspect\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual string \fBInspectName\fP\fR [get]\fP"
.br
.in -1c

Properties inherited from \fBIInspect\fP
.SS "Additional Inherited Members"


Public Types inherited from \fBIInspect\fP
.in +1c
.ti -1c
.RI "enum \fBNoteMode\fP { \fBDefault\fP, \fBRecipe\fP, \fBProduct\fP, \fBInfo\fP }"
.br
.in -1c

Public Attributes inherited from \fBBaseInspectPos\fP
.in +1c
.ti -1c
.RI "\fBPoint\fP \fBpos\fP = new \fBPoint\fP()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB4\fP of file \fBBlockInfo\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "static bool BlockInfo\&._CanInspect (\fBPoint\fP pos)\fR [static]\fP"

.PP
Definition at line \fB35\fP of file \fBBlockInfo\&.cs\fP\&.
.SS "static \fBBlockInfo\fP BlockInfo\&.GetTemp (\fBPoint\fP _pos)\fR [static]\fP"

.PP
Definition at line \fB7\fP of file \fBBlockInfo\&.cs\fP\&.
.SS "static \fBBlockInfo\fP BlockInfo\&.GetTempList (\fBPoint\fP _pos)\fR [static]\fP"

.PP
Definition at line \fB14\fP of file \fBBlockInfo\&.cs\fP\&.
.SS "override void BlockInfo\&.WriteNote (UINote n, Action< UINote > onWriteNote = \fRnull\fP, IInspect\&.NoteMode mode = \fRIInspect::NoteMode::Default\fP, \fBRecipe\fP recipe = \fRnull\fP)\fR [virtual]\fP"

.PP
Reimplemented from \fBBaseInspectPos\fP\&.
.PP
Definition at line \fB61\fP of file \fBBlockInfo\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBBlockInfo\fP BlockInfo\&.Temp = new \fBBlockInfo\fP()\fR [static]\fP"

.PP
Definition at line \fB71\fP of file \fBBlockInfo\&.cs\fP\&.
.SS "\fBBlockInfo\fP BlockInfo\&.TempList = new \fBBlockInfo\fP()\fR [static]\fP"

.PP
Definition at line \fB74\fP of file \fBBlockInfo\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "override bool BlockInfo\&.CanInspect\fR [get]\fP"

.PP
Implements \fBIInspect\fP\&.
.PP
Definition at line \fB42\fP of file \fBBlockInfo\&.cs\fP\&.
.SS "override string BlockInfo\&.InspectName\fR [get]\fP"

.PP
Implements \fBIInspect\fP\&.
.PP
Definition at line \fB52\fP of file \fBBlockInfo\&.cs\fP\&.
.SS "\fBSourceBlock\&.Row\fP BlockInfo\&.source\fR [get]\fP"

.PP
Definition at line \fB26\fP of file \fBBlockInfo\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
