.TH "ButtonGridExt" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ButtonGridExt
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBRefresh\fP (\fBCard\fP c)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Image \fBimageBar\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB6\fP of file \fBButtonGridExt\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void ButtonGridExt\&.Refresh (\fBCard\fP c)"

.PP
Definition at line \fB9\fP of file \fBButtonGridExt\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "Image ButtonGridExt\&.imageBar"

.PP
Definition at line \fB17\fP of file \fBButtonGridExt\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
