.TH "ButtonAbility" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ButtonAbility
.SH SYNOPSIS
.br
.PP
.PP
Inherits UIButton, and \fBIMouseHint\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetAct\fP (\fBChara\fP _chara, \fBElement\fP e)"
.br
.ti -1c
.RI "void \fBOnDrag\fP (PointerEventData data)"
.br
.ti -1c
.RI "override void \fBOnPointerUp\fP (PointerEventData eventData)"
.br
.ti -1c
.RI "void \fBUse\fP ()"
.br
.ti -1c
.RI "void \fBHoldAbility\fP ()"
.br
.ti -1c
.RI "bool \fBCanAutoUse\fP (\fBAct\fP _act)"
.br
.ti -1c
.RI "bool \fBShowMouseHintLeft\fP ()"
.br
.ti -1c
.RI "string \fBGetTextMouseHintLeft\fP ()"
.br
.ti -1c
.RI "bool \fBShowMouseHintRight\fP ()"
.br
.ti -1c
.RI "string \fBGetTextMouseHintRight\fP ()"
.br
.ti -1c
.RI "override bool \fBCanMiddleClick\fP ()"
.br
.ti -1c
.RI "override void \fBOnMiddleClick\fP ()"
.br
.ti -1c
.RI "void \fBToggleFav\fP ()"
.br
.ti -1c
.RI "void \fBRefreshFavIcon\fP ()"
.br
.in -1c

Public Member Functions inherited from \fBIMouseHint\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBTryUse\fP (\fBAct\fP act, \fBCard\fP tg=null, \fBPoint\fP pos=null, \fBCard\fP catalyst=null, bool first=true, bool mouse=true)"
.br
.ti -1c
.RI "static bool \fBSpecialHoldAction\fP (\fBAct\fP act)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBSourceElement\&.Row\fP \fBsource\fP"
.br
.ti -1c
.RI "IDragParent \fBdragParent\fP"
.br
.ti -1c
.RI "UIText \fBtextStock\fP"
.br
.ti -1c
.RI "Image \fBimageType\fP"
.br
.ti -1c
.RI "Image \fBimageFav\fP"
.br
.ti -1c
.RI "Transform \fBattach\fP"
.br
.ti -1c
.RI "Transform \fBtransFav\fP"
.br
.ti -1c
.RI "\fBChara\fP \fBchara\fP"
.br
.ti -1c
.RI "\fBAct\fP \fBact\fP"
.br
.ti -1c
.RI "bool \fBdragged\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static float \fBhotkeyTimer\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB7\fP of file \fBButtonAbility\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "bool ButtonAbility\&.CanAutoUse (\fBAct\fP _act)"

.PP
Definition at line \fB226\fP of file \fBButtonAbility\&.cs\fP\&.
.SS "override bool ButtonAbility\&.CanMiddleClick ()"

.PP
Definition at line \fB256\fP of file \fBButtonAbility\&.cs\fP\&.
.SS "string ButtonAbility\&.GetTextMouseHintLeft ()"

.PP
Implements \fBIMouseHint\fP\&.
.PP
Definition at line \fB238\fP of file \fBButtonAbility\&.cs\fP\&.
.SS "string ButtonAbility\&.GetTextMouseHintRight ()"

.PP
Implements \fBIMouseHint\fP\&.
.PP
Definition at line \fB250\fP of file \fBButtonAbility\&.cs\fP\&.
.SS "void ButtonAbility\&.HoldAbility ()"

.PP
Definition at line \fB219\fP of file \fBButtonAbility\&.cs\fP\&.
.SS "void ButtonAbility\&.OnDrag (PointerEventData data)"

.PP
Definition at line \fB52\fP of file \fBButtonAbility\&.cs\fP\&.
.SS "override void ButtonAbility\&.OnMiddleClick ()"

.PP
Definition at line \fB262\fP of file \fBButtonAbility\&.cs\fP\&.
.SS "override void ButtonAbility\&.OnPointerUp (PointerEventData eventData)"

.PP
Definition at line \fB73\fP of file \fBButtonAbility\&.cs\fP\&.
.SS "void ButtonAbility\&.RefreshFavIcon ()"

.PP
Definition at line \fB296\fP of file \fBButtonAbility\&.cs\fP\&.
.SS "void ButtonAbility\&.SetAct (\fBChara\fP _chara, \fBElement\fP e)"

.PP
Definition at line \fB10\fP of file \fBButtonAbility\&.cs\fP\&.
.SS "bool ButtonAbility\&.ShowMouseHintLeft ()"

.PP
Implements \fBIMouseHint\fP\&.
.PP
Definition at line \fB232\fP of file \fBButtonAbility\&.cs\fP\&.
.SS "bool ButtonAbility\&.ShowMouseHintRight ()"

.PP
Implements \fBIMouseHint\fP\&.
.PP
Definition at line \fB244\fP of file \fBButtonAbility\&.cs\fP\&.
.SS "static bool ButtonAbility\&.SpecialHoldAction (\fBAct\fP act)\fR [static]\fP"

.PP
Definition at line \fB168\fP of file \fBButtonAbility\&.cs\fP\&.
.SS "void ButtonAbility\&.ToggleFav ()"

.PP
Definition at line \fB279\fP of file \fBButtonAbility\&.cs\fP\&.
.SS "static bool ButtonAbility\&.TryUse (\fBAct\fP act, \fBCard\fP tg = \fRnull\fP, \fBPoint\fP pos = \fRnull\fP, \fBCard\fP catalyst = \fRnull\fP, bool first = \fRtrue\fP, bool mouse = \fRtrue\fP)\fR [static]\fP"

.PP
Definition at line \fB107\fP of file \fBButtonAbility\&.cs\fP\&.
.SS "void ButtonAbility\&.Use ()"

.PP
Definition at line \fB85\fP of file \fBButtonAbility\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBAct\fP ButtonAbility\&.act"

.PP
Definition at line \fB327\fP of file \fBButtonAbility\&.cs\fP\&.
.SS "Transform ButtonAbility\&.attach"

.PP
Definition at line \fB318\fP of file \fBButtonAbility\&.cs\fP\&.
.SS "\fBChara\fP ButtonAbility\&.chara"

.PP
Definition at line \fB324\fP of file \fBButtonAbility\&.cs\fP\&.
.SS "bool ButtonAbility\&.dragged"

.PP
Definition at line \fB331\fP of file \fBButtonAbility\&.cs\fP\&.
.SS "IDragParent ButtonAbility\&.dragParent"

.PP
Definition at line \fB306\fP of file \fBButtonAbility\&.cs\fP\&.
.SS "float ButtonAbility\&.hotkeyTimer\fR [static]\fP"

.PP
Definition at line \fB334\fP of file \fBButtonAbility\&.cs\fP\&.
.SS "Image ButtonAbility\&.imageFav"

.PP
Definition at line \fB315\fP of file \fBButtonAbility\&.cs\fP\&.
.SS "Image ButtonAbility\&.imageType"

.PP
Definition at line \fB312\fP of file \fBButtonAbility\&.cs\fP\&.
.SS "\fBSourceElement\&.Row\fP ButtonAbility\&.source"

.PP
Definition at line \fB303\fP of file \fBButtonAbility\&.cs\fP\&.
.SS "UIText ButtonAbility\&.textStock"

.PP
Definition at line \fB309\fP of file \fBButtonAbility\&.cs\fP\&.
.SS "Transform ButtonAbility\&.transFav"

.PP
Definition at line \fB321\fP of file \fBButtonAbility\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
