.TH "ButtonResourceTrack" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ButtonResourceTrack
.SH SYNOPSIS
.br
.PP
.PP
Inherits UIButton\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetProp\fP (string id)"
.br
.ti -1c
.RI "void \fBSetCat\fP (string id)"
.br
.ti -1c
.RI "void \fBRefresh\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBPropSet\fP \fBprop\fP"
.br
.ti -1c
.RI "\fBPropSetCategory\fP \fBcat\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBUIResourceTrack\fP \fBtrack\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB5\fP of file \fBButtonResourceTrack\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void ButtonResourceTrack\&.Refresh ()"

.PP
Definition at line \fB51\fP of file \fBButtonResourceTrack\&.cs\fP\&.
.SS "void ButtonResourceTrack\&.SetCat (string id)"

.PP
Definition at line \fB36\fP of file \fBButtonResourceTrack\&.cs\fP\&.
.SS "void ButtonResourceTrack\&.SetProp (string id)"

.PP
Definition at line \fB18\fP of file \fBButtonResourceTrack\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBPropSetCategory\fP ButtonResourceTrack\&.cat"

.PP
Definition at line \fB66\fP of file \fBButtonResourceTrack\&.cs\fP\&.
.SS "\fBPropSet\fP ButtonResourceTrack\&.prop"

.PP
Definition at line \fB63\fP of file \fBButtonResourceTrack\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "\fBUIResourceTrack\fP ButtonResourceTrack\&.track\fR [get]\fP"

.PP
Definition at line \fB9\fP of file \fBButtonResourceTrack\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
