.TH "ButtonRoster" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ButtonRoster
.SH SYNOPSIS
.br
.PP
.PP
Inherits UIButton\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetChara\fP (\fBChara\fP c)"
.br
.ti -1c
.RI "void \fBRefresh\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBChara\fP \fBchara\fP"
.br
.ti -1c
.RI "float \fBiconPivot\fP"
.br
.ti -1c
.RI "Image \fBbarMood\fP"
.br
.ti -1c
.RI "UIText \fBtextName\fP"
.br
.ti -1c
.RI "RectTransform \fBrect\fP"
.br
.ti -1c
.RI "\fBPortrait\fP \fBportrait\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBWidgetRoster\fP \fBroster\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB6\fP of file \fBButtonRoster\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void ButtonRoster\&.Refresh ()"

.PP
Definition at line \fB32\fP of file \fBButtonRoster\&.cs\fP\&.
.SS "void ButtonRoster\&.SetChara (\fBChara\fP c)"

.PP
Definition at line \fB19\fP of file \fBButtonRoster\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "Image ButtonRoster\&.barMood"

.PP
Definition at line \fB65\fP of file \fBButtonRoster\&.cs\fP\&.
.SS "\fBChara\fP ButtonRoster\&.chara"

.PP
Definition at line \fB56\fP of file \fBButtonRoster\&.cs\fP\&.
.SS "float ButtonRoster\&.iconPivot"

.PP
Definition at line \fB59\fP of file \fBButtonRoster\&.cs\fP\&.
.SS "\fBPortrait\fP ButtonRoster\&.portrait"

.PP
Definition at line \fB74\fP of file \fBButtonRoster\&.cs\fP\&.
.SS "RectTransform ButtonRoster\&.rect"

.PP
Definition at line \fB71\fP of file \fBButtonRoster\&.cs\fP\&.
.SS "UIText ButtonRoster\&.textName"

.PP
Definition at line \fB68\fP of file \fBButtonRoster\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "\fBWidgetRoster\fP ButtonRoster\&.roster\fR [get]\fP"

.PP
Definition at line \fB10\fP of file \fBButtonRoster\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
