.TH "ButtonChara" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ButtonChara
.SH SYNOPSIS
.br
.PP
.PP
Inherits UIButton\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBMode\fP { \fBDefault\fP, \fBHire\fP, \fBJournal\fP, \fBEmbark\fP, \fBRanking\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetChara\fP (\fBChara\fP c, ButtonChara\&.Mode m)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBPortrait\fP \fBportrait\fP"
.br
.ti -1c
.RI "UIText \fBtextName\fP"
.br
.ti -1c
.RI "UIText \fBtextAlias\fP"
.br
.ti -1c
.RI "UIText \fBtextBio\fP"
.br
.ti -1c
.RI "UIText \fBtextWork\fP"
.br
.ti -1c
.RI "UIText \fBtextHobby\fP"
.br
.ti -1c
.RI "UIText \fBtextLifeStyle\fP"
.br
.ti -1c
.RI "new UIItem \fBitem\fP"
.br
.ti -1c
.RI "LayoutGroup \fBlayoutTag\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB5\fP of file \fBButtonChara\&.cs\fP\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "enum ButtonChara\&.Mode"

.PP
Definition at line \fB72\fP of file \fBButtonChara\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void ButtonChara\&.SetChara (\fBChara\fP c, ButtonChara\&.Mode m)"

.PP
Definition at line \fB8\fP of file \fBButtonChara\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "new UIItem ButtonChara\&.item"

.PP
Definition at line \fB66\fP of file \fBButtonChara\&.cs\fP\&.
.SS "LayoutGroup ButtonChara\&.layoutTag"

.PP
Definition at line \fB69\fP of file \fBButtonChara\&.cs\fP\&.
.SS "\fBPortrait\fP ButtonChara\&.portrait"

.PP
Definition at line \fB45\fP of file \fBButtonChara\&.cs\fP\&.
.SS "UIText ButtonChara\&.textAlias"

.PP
Definition at line \fB51\fP of file \fBButtonChara\&.cs\fP\&.
.SS "UIText ButtonChara\&.textBio"

.PP
Definition at line \fB54\fP of file \fBButtonChara\&.cs\fP\&.
.SS "UIText ButtonChara\&.textHobby"

.PP
Definition at line \fB60\fP of file \fBButtonChara\&.cs\fP\&.
.SS "UIText ButtonChara\&.textLifeStyle"

.PP
Definition at line \fB63\fP of file \fBButtonChara\&.cs\fP\&.
.SS "UIText ButtonChara\&.textName"

.PP
Definition at line \fB48\fP of file \fBButtonChara\&.cs\fP\&.
.SS "UIText ButtonChara\&.textWork"

.PP
Definition at line \fB57\fP of file \fBButtonChara\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
