.TH "ButtonElement" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ButtonElement
.SH SYNOPSIS
.br
.PP
.PP
Inherits UIButton\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBMode\fP { \fBSkill\fP, \fBAttribute\fP, \fBTech\fP, \fBFeat\fP, \fBEnchant\fP, \fBPolicy\fP, \fBOnlyValue\fP, \fBFeatPurchase\fP, \fBLandFeat\fP, \fBFeatMini\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetElement\fP (\fBElement\fP _e, \fBElementContainer\fP _owner, ButtonElement\&.Mode _mode=ButtonElement\&.Mode\&.Skill)"
.br
.ti -1c
.RI "void \fBRefresh\fP ()"
.br
.ti -1c
.RI "void \fBSetGrid\fP (\fBElement\fP e, \fBChara\fP c)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Image \fBimagePotential\fP"
.br
.ti -1c
.RI "GameObject \fBgoExp\fP"
.br
.ti -1c
.RI "\fBElement\fP \fBe\fP"
.br
.ti -1c
.RI "\fBElementContainer\fP \fBowner\fP"
.br
.ti -1c
.RI "UIButton \fBbuttonUpgrade\fP"
.br
.ti -1c
.RI "UIItem \fBmoldItemResist\fP"
.br
.ti -1c
.RI "LayoutGroup \fBlayout\fP"
.br
.ti -1c
.RI "ButtonElement\&.Mode \fBmode\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB6\fP of file \fBButtonElement\&.cs\fP\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "enum ButtonElement\&.Mode"

.PP
Definition at line \fB231\fP of file \fBButtonElement\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void ButtonElement\&.Refresh ()"

.PP
Definition at line \fB18\fP of file \fBButtonElement\&.cs\fP\&.
.SS "void ButtonElement\&.SetElement (\fBElement\fP _e, \fBElementContainer\fP _owner, ButtonElement\&.Mode _mode = \fRButtonElement::Mode::Skill\fP)"

.PP
Definition at line \fB9\fP of file \fBButtonElement\&.cs\fP\&.
.SS "void ButtonElement\&.SetGrid (\fBElement\fP e, \fBChara\fP c)"

.PP
Definition at line \fB134\fP of file \fBButtonElement\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "UIButton ButtonElement\&.buttonUpgrade"

.PP
Definition at line \fB219\fP of file \fBButtonElement\&.cs\fP\&.
.SS "\fBElement\fP ButtonElement\&.e"

.PP
Definition at line \fB213\fP of file \fBButtonElement\&.cs\fP\&.
.SS "GameObject ButtonElement\&.goExp"

.PP
Definition at line \fB210\fP of file \fBButtonElement\&.cs\fP\&.
.SS "Image ButtonElement\&.imagePotential"

.PP
Definition at line \fB207\fP of file \fBButtonElement\&.cs\fP\&.
.SS "LayoutGroup ButtonElement\&.layout"

.PP
Definition at line \fB225\fP of file \fBButtonElement\&.cs\fP\&.
.SS "ButtonElement\&.Mode ButtonElement\&.mode"

.PP
Definition at line \fB228\fP of file \fBButtonElement\&.cs\fP\&.
.SS "UIItem ButtonElement\&.moldItemResist"

.PP
Definition at line \fB222\fP of file \fBButtonElement\&.cs\fP\&.
.SS "\fBElementContainer\fP ButtonElement\&.owner"

.PP
Definition at line \fB216\fP of file \fBButtonElement\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
