.TH "ButtonGridDrag" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ButtonGridDrag
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBButtonGrid\fP, IDragHandler, and IEventSystemHandler\&.
.PP
Inherited by \fBButtonHotItem\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBSetDragParent\fP (IDragParent p)"
.br
.ti -1c
.RI "void \fBOnDrag\fP (PointerEventData data)"
.br
.ti -1c
.RI "override void \fBOnPointerUp\fP (PointerEventData eventData)"
.br
.in -1c

Public Member Functions inherited from \fBButtonGrid\fP
.in +1c
.ti -1c
.RI "override string \fBToString\fP ()"
.br
.ti -1c
.RI "T \fBAttach< T >\fP (string id, bool rightAttach=true)"
.br
.ti -1c
.RI "Transform \fBAttach\fP (string id, bool rightAttach=true)"
.br
.ti -1c
.RI "void \fBDettach\fP (string id)"
.br
.ti -1c
.RI "void \fBReset\fP ()"
.br
.ti -1c
.RI "void \fBSetBodySlot\fP (\fBBodySlot\fP b, \fBInvOwner\fP owner)"
.br
.ti -1c
.RI "void \fBRedraw\fP ()"
.br
.ti -1c
.RI "void \fBSetCardGrid\fP (\fBCard\fP c, \fBInvOwner\fP owner=null)"
.br
.ti -1c
.RI "void \fBSetCard\fP (\fBCard\fP c, ButtonGrid\&.Mode mode=ButtonGrid\&.Mode\&.Default, Action< UINote > onWriteNote=null)"
.br
.ti -1c
.RI "void \fBSetArea\fP (\fBArea\fP a)"
.br
.ti -1c
.RI "void \fBSetItem\fP (\fBGridItem\fP i)"
.br
.ti -1c
.RI "void \fBSetObject\fP (object o)"
.br
.ti -1c
.RI "void \fBSetDummy\fP ()"
.br
.ti -1c
.RI "void \fBSetIngredient\fP (\fBRecipe\fP r, \fBRecipe\&.Ingredient\fP _ing)"
.br
.ti -1c
.RI "void \fBSetIngredient\fP (\fBRecipe\fP r, \fBThing\fP t)"
.br
.ti -1c
.RI "void \fBSetRecipeVariation\fP (\fBUIRecipeInfo\&.RecipeVariation\fP a)"
.br
.ti -1c
.RI "void \fBSetRecipe\fP ()"
.br
.ti -1c
.RI "void \fBSetRecipe\fP (\fBArea\fP a)"
.br
.ti -1c
.RI "void \fBSetRecipe\fP (\fBRecipe\fP r)"
.br
.ti -1c
.RI "void \fBRefreshCraftable\fP ()"
.br
.ti -1c
.RI "void \fBSetCraftRecipe\fP (\fBRecipe\fP r, ButtonGrid\&.Mode mode, bool tooltip=false)"
.br
.ti -1c
.RI "void \fBWriteReqMat\fP (UINote n, \fBRecipe\fP r)"
.br
.ti -1c
.RI "bool \fBShowMouseHintLeft\fP ()"
.br
.ti -1c
.RI "string \fBGetTextMouseHintLeft\fP ()"
.br
.ti -1c
.RI "bool \fBShowMouseHintRight\fP ()"
.br
.ti -1c
.RI "string \fBGetTextMouseHintRight\fP ()"
.br
.ti -1c
.RI "\fBRenderRow\fP \fBGetRenderRow\fP ()"
.br
.ti -1c
.RI "void \fBOnRefreshPref\fP ()"
.br
.ti -1c
.RI "override bool \fBCanMiddleClick\fP ()"
.br
.ti -1c
.RI "override void \fBOnMiddleClick\fP ()"
.br
.in -1c

Public Member Functions inherited from \fBIMouseHint\fP

Public Member Functions inherited from \fBIPrefImage\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "IDragParent \fBdragParent\fP"
.br
.ti -1c
.RI "bool \fBdragged\fP"
.br
.in -1c

Public Attributes inherited from \fBButtonGrid\fP
.in +1c
.ti -1c
.RI "\fBArea\fP \fBarea\fP"
.br
.ti -1c
.RI "\fBRecipe\fP \fBrecipe\fP"
.br
.ti -1c
.RI "\fBRecipe\&.Ingredient\fP \fBing\fP"
.br
.ti -1c
.RI "\fBCard\fP \fBcard\fP"
.br
.ti -1c
.RI "int \fBindex\fP"
.br
.ti -1c
.RI "\fBInvOwner\fP \fBinvOwner\fP"
.br
.ti -1c
.RI "bool \fBkeepBg\fP"
.br
.ti -1c
.RI "List< Transform > \fBlistAttach\fP = new List<Transform>()"
.br
.in -1c
.SS "Additional Inherited Members"


Public Types inherited from \fBButtonGrid\fP
.in +1c
.ti -1c
.RI "enum \fBMode\fP { \fBDefault\fP, \fBGrid\fP, \fBIngredient\fP, \fBRecipe\fP, \fBRecipeGrid\fP, \fBSearch\fP }"
.br
.in -1c

Protected Member Functions inherited from \fBButtonGrid\fP
.in +1c
.ti -1c
.RI "override void \fBOnDestroy\fP ()"
.br
.in -1c

Properties inherited from \fBButtonGrid\fP
.in +1c
.ti -1c
.RI "\fBColorProfile\fP \fBColors\fP\fR [get]\fP"
.br
.ti -1c
.RI "\fBCard\fP \fBCard\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual float \fBextFixY\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB5\fP of file \fBButtonGridDrag\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void ButtonGridDrag\&.OnDrag (PointerEventData data)"

.PP
Definition at line \fB14\fP of file \fBButtonGridDrag\&.cs\fP\&.
.SS "override void ButtonGridDrag\&.OnPointerUp (PointerEventData eventData)"

.PP
Definition at line \fB40\fP of file \fBButtonGridDrag\&.cs\fP\&.
.SS "override void ButtonGridDrag\&.SetDragParent (IDragParent p)\fR [virtual]\fP"

.PP
Reimplemented from \fBButtonGrid\fP\&.
.PP
Definition at line \fB8\fP of file \fBButtonGridDrag\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "bool ButtonGridDrag\&.dragged"

.PP
Definition at line \fB57\fP of file \fBButtonGridDrag\&.cs\fP\&.
.SS "IDragParent ButtonGridDrag\&.dragParent"

.PP
Definition at line \fB53\fP of file \fBButtonGridDrag\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
