.TH "CameraSupport" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CameraSupport
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBDivider\fP { \fBNone\fP, \fBFloor\fP, \fBRound\fP, \fBCeil\fP, \fBOdd\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBResizeCameraToPixelPerfect\fP ()"
.br
.ti -1c
.RI "void \fBOnChangeResolution\fP ()"
.br
.ti -1c
.RI "float \fBGetOrthoSize\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Camera \fBcam\fP"
.br
.ti -1c
.RI "Vector3 \fBrenderPos\fP"
.br
.ti -1c
.RI "\fBGameScreen\fP \fBscreen\fP"
.br
.ti -1c
.RI "ScreenGrading \fBgrading\fP"
.br
.ti -1c
.RI "Upscaler \fBupscaler\fP"
.br
.ti -1c
.RI "CameraSupport\&.Divider \fBdivier\fP"
.br
.ti -1c
.RI "bool \fBsnap\fP"
.br
.ti -1c
.RI "float \fBPixelsPerUnit\fP = 100f"
.br
.ti -1c
.RI "TiltShift \fBtiltShift\fP"
.br
.ti -1c
.RI "BloomOptimized \fBbloom\fP"
.br
.ti -1c
.RI "Beautify \fBbeautify\fP"
.br
.ti -1c
.RI "Kuwahara \fBkuwahara\fP"
.br
.ti -1c
.RI "GaussianBlur \fBblur\fP"
.br
.ti -1c
.RI "float \fBZoom\fP = 1f"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB8\fP of file \fBCameraSupport\&.cs\fP\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "enum CameraSupport\&.Divider"

.PP
Definition at line \fB90\fP of file \fBCameraSupport\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "float CameraSupport\&.GetOrthoSize ()"

.PP
Definition at line \fB22\fP of file \fBCameraSupport\&.cs\fP\&.
.SS "void CameraSupport\&.OnChangeResolution ()"

.PP
Definition at line \fB17\fP of file \fBCameraSupport\&.cs\fP\&.
.SS "void CameraSupport\&.ResizeCameraToPixelPerfect ()"

.PP
Definition at line \fB11\fP of file \fBCameraSupport\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "Beautify CameraSupport\&.beautify"

.PP
Definition at line \fB77\fP of file \fBCameraSupport\&.cs\fP\&.
.SS "BloomOptimized CameraSupport\&.bloom"

.PP
Definition at line \fB74\fP of file \fBCameraSupport\&.cs\fP\&.
.SS "GaussianBlur CameraSupport\&.blur"

.PP
Definition at line \fB83\fP of file \fBCameraSupport\&.cs\fP\&.
.SS "Camera CameraSupport\&.cam"

.PP
Definition at line \fB47\fP of file \fBCameraSupport\&.cs\fP\&.
.SS "CameraSupport\&.Divider CameraSupport\&.divier"

.PP
Definition at line \fB62\fP of file \fBCameraSupport\&.cs\fP\&.
.SS "ScreenGrading CameraSupport\&.grading"

.PP
Definition at line \fB56\fP of file \fBCameraSupport\&.cs\fP\&.
.SS "Kuwahara CameraSupport\&.kuwahara"

.PP
Definition at line \fB80\fP of file \fBCameraSupport\&.cs\fP\&.
.SS "float CameraSupport\&.PixelsPerUnit = 100f"

.PP
Definition at line \fB68\fP of file \fBCameraSupport\&.cs\fP\&.
.SS "Vector3 CameraSupport\&.renderPos"

.PP
Definition at line \fB50\fP of file \fBCameraSupport\&.cs\fP\&.
.SS "\fBGameScreen\fP CameraSupport\&.screen"

.PP
Definition at line \fB53\fP of file \fBCameraSupport\&.cs\fP\&.
.SS "bool CameraSupport\&.snap"

.PP
Definition at line \fB65\fP of file \fBCameraSupport\&.cs\fP\&.
.SS "TiltShift CameraSupport\&.tiltShift"

.PP
Definition at line \fB71\fP of file \fBCameraSupport\&.cs\fP\&.
.SS "Upscaler CameraSupport\&.upscaler"

.PP
Definition at line \fB59\fP of file \fBCameraSupport\&.cs\fP\&.
.SS "float CameraSupport\&.Zoom = 1f"

.PP
Definition at line \fB87\fP of file \fBCameraSupport\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
