.TH "CardBlueprint" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CardBlueprint
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBCardBlueprint\fP \fBChara\fP (int lv, Rarity rarity=Rarity\&.Normal)"
.br
.ti -1c
.RI "static void \fBSet\fP (\fBCardBlueprint\fP _bp)"
.br
.ti -1c
.RI "static void \fBSetNormalRarity\fP (bool fixedMat=false)"
.br
.ti -1c
.RI "static void \fBSetRarity\fP (Rarity q=Rarity\&.Normal)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBlv\fP = \-999"
.br
.ti -1c
.RI "int \fBqualityBonus\fP"
.br
.ti -1c
.RI "string \fBidRace\fP"
.br
.ti -1c
.RI "string \fBidJob\fP"
.br
.ti -1c
.RI "string \fBidEle\fP"
.br
.ti -1c
.RI "Rarity \fBrarity\fP = Rarity\&.Random"
.br
.ti -1c
.RI "BlessedState? \fBblesstedState\fP"
.br
.ti -1c
.RI "bool \fBfixedMat\fP"
.br
.ti -1c
.RI "bool \fBtryLevelMatTier\fP"
.br
.ti -1c
.RI "bool \fBfixedQuality\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static \fBCardBlueprint\fP \fBcurrent\fP"
.br
.ti -1c
.RI "static \fBCardBlueprint\fP \fB_Default\fP = new \fBCardBlueprint\fP()"
.br
.ti -1c
.RI "static \fBCardBlueprint\fP \fBCharaGenEQ\fP"
.br
.ti -1c
.RI "static \fBCardBlueprint\fP \fBDebugEQ\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB4\fP of file \fBCardBlueprint\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "static \fBCardBlueprint\fP CardBlueprint\&.Chara (int lv, Rarity rarity = \fRRarity::Normal\fP)\fR [static]\fP"

.PP
Definition at line \fB7\fP of file \fBCardBlueprint\&.cs\fP\&.
.SS "static void CardBlueprint\&.Set (\fBCardBlueprint\fP _bp)\fR [static]\fP"

.PP
Definition at line \fB17\fP of file \fBCardBlueprint\&.cs\fP\&.
.SS "static void CardBlueprint\&.SetNormalRarity (bool fixedMat = \fRfalse\fP)\fR [static]\fP"

.PP
Definition at line \fB23\fP of file \fBCardBlueprint\&.cs\fP\&.
.SS "static void CardBlueprint\&.SetRarity (Rarity q = \fRRarity::Normal\fP)\fR [static]\fP"

.PP
Definition at line \fB33\fP of file \fBCardBlueprint\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBCardBlueprint\fP CardBlueprint\&._Default = new \fBCardBlueprint\fP()\fR [static]\fP"

.PP
Definition at line \fB75\fP of file \fBCardBlueprint\&.cs\fP\&.
.SS "BlessedState? CardBlueprint\&.blesstedState"

.PP
Definition at line \fB60\fP of file \fBCardBlueprint\&.cs\fP\&.
.SS "\fBCardBlueprint\fP CardBlueprint\&.CharaGenEQ\fR [static]\fP"
\fBInitial value:\fP
.nf
= new CardBlueprint
    {
        tryLevelMatTier = true
    }
.PP
.fi

.PP
Definition at line \fB78\fP of file \fBCardBlueprint\&.cs\fP\&.
.SS "\fBCardBlueprint\fP CardBlueprint\&.current\fR [static]\fP"

.PP
Definition at line \fB72\fP of file \fBCardBlueprint\&.cs\fP\&.
.SS "\fBCardBlueprint\fP CardBlueprint\&.DebugEQ\fR [static]\fP"
\fBInitial value:\fP
.nf
= new CardBlueprint
    {
        rarity = Rarity\&.Legendary
    }
.PP
.fi

.PP
Definition at line \fB84\fP of file \fBCardBlueprint\&.cs\fP\&.
.SS "bool CardBlueprint\&.fixedMat"

.PP
Definition at line \fB63\fP of file \fBCardBlueprint\&.cs\fP\&.
.SS "bool CardBlueprint\&.fixedQuality"

.PP
Definition at line \fB69\fP of file \fBCardBlueprint\&.cs\fP\&.
.SS "string CardBlueprint\&.idEle"

.PP
Definition at line \fB54\fP of file \fBCardBlueprint\&.cs\fP\&.
.SS "string CardBlueprint\&.idJob"

.PP
Definition at line \fB51\fP of file \fBCardBlueprint\&.cs\fP\&.
.SS "string CardBlueprint\&.idRace"

.PP
Definition at line \fB48\fP of file \fBCardBlueprint\&.cs\fP\&.
.SS "int CardBlueprint\&.lv = \-999"

.PP
Definition at line \fB42\fP of file \fBCardBlueprint\&.cs\fP\&.
.SS "int CardBlueprint\&.qualityBonus"

.PP
Definition at line \fB45\fP of file \fBCardBlueprint\&.cs\fP\&.
.SS "Rarity CardBlueprint\&.rarity = Rarity\&.Random"

.PP
Definition at line \fB57\fP of file \fBCardBlueprint\&.cs\fP\&.
.SS "bool CardBlueprint\&.tryLevelMatTier"

.PP
Definition at line \fB66\fP of file \fBCardBlueprint\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
