.TH "CardInspector" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CardInspector
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBEMono\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetCard\fP (\fBCard\fP c, bool select=true)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBCard\fP \fBcard\fP"
.br
.ti -1c
.RI "List< EditorTag > \fBtags\fP = new List<EditorTag>()"
.br
.ti -1c
.RI "string \fBtraitVals\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static \fBCardInspector\fP \fBInstance\fP"
.br
.in -1c

Static Public Attributes inherited from \fBEMono\fP
.in +1c
.ti -1c
.RI "static \fBCore\fP \fBcore\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "IEnumerable< string > \fB_SpawnList\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBInfo\fP\fR [get]\fP"
.br
.ti -1c
.RI "string \fBidEditor\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "string \fBtrait\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "string \fBBGM\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "bool \fBIsTape\fP\fR [get]\fP"
.br
.ti -1c
.RI "string \fBspawnList\fP\fR [get, set]\fP"
.br
.in -1c

Properties inherited from \fBEMono\fP
.in +1c
.ti -1c
.RI "static \fBGame\fP \fBgame\fP\fR [get]\fP"
.br
.ti -1c
.RI "static bool \fBAdvMode\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBPlayer\fP \fBplayer\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBChara\fP \fBpc\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBUI\fP \fBui\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBMap\fP \fB_map\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBZone\fP \fB_zone\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranchOrHomeBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFaction\fP \fBHome\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBScene\fP \fBscene\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBBaseGameScreen\fP \fBscreen\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameSetting\fP \fBsetting\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameData\fP \fBgamedata\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBColorProfile\fP \fBColors\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBWorld\fP \fBworld\fP\fR [get]\fP"
.br
.ti -1c
.RI "static SoundManager \fBSound\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBsources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBeditorSources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBCoreDebug\fP \fBdebug\fP\fR [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Static Public Member Functions inherited from \fBEMono\fP
.in +1c
.ti -1c
.RI "static int \fBrnd\fP (int a)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB8\fP of file \fBCardInspector\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "IEnumerable< string > CardInspector\&._SpawnList ()\fR [protected]\fP"

.PP
Definition at line \fB168\fP of file \fBCardInspector\&.cs\fP\&.
.SS "void CardInspector\&.SetCard (\fBCard\fP c, bool select = \fRtrue\fP)"

.PP
Definition at line \fB180\fP of file \fBCardInspector\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBCard\fP CardInspector\&.card"

.PP
Definition at line \fB226\fP of file \fBCardInspector\&.cs\fP\&.
.SS "\fBCardInspector\fP CardInspector\&.Instance\fR [static]\fP"

.PP
Definition at line \fB223\fP of file \fBCardInspector\&.cs\fP\&.
.SS "List<EditorTag> CardInspector\&.tags = new List<EditorTag>()"

.PP
Definition at line \fB229\fP of file \fBCardInspector\&.cs\fP\&.
.SS "string CardInspector\&.traitVals"

.PP
Definition at line \fB232\fP of file \fBCardInspector\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "string CardInspector\&.BGM\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB73\fP of file \fBCardInspector\&.cs\fP\&.
.SS "string CardInspector\&.idEditor\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB27\fP of file \fBCardInspector\&.cs\fP\&.
.SS "string CardInspector\&.Info\fR [get]\fP"

.PP
Definition at line \fB12\fP of file \fBCardInspector\&.cs\fP\&.
.SS "bool CardInspector\&.IsTape\fR [get]\fP"

.PP
Definition at line \fB110\fP of file \fBCardInspector\&.cs\fP\&.
.SS "string CardInspector\&.spawnList\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB143\fP of file \fBCardInspector\&.cs\fP\&.
.SS "string CardInspector\&.trait\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB50\fP of file \fBCardInspector\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
