.TH "CardFilter.FilterCategory" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CardFilter.FilterCategory
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBexclude\fP"
.br
.ti -1c
.RI "\fBSourceCategory\&.Row\fP \fBrow\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB186\fP of file \fBCardFilter\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "bool CardFilter\&.FilterCategory\&.exclude"

.PP
Definition at line \fB189\fP of file \fBCardFilter\&.cs\fP\&.
.SS "\fBSourceCategory\&.Row\fP CardFilter\&.FilterCategory\&.row"

.PP
Definition at line \fB192\fP of file \fBCardFilter\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
