.TH "CellEffect" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CellEffect
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBEClass\fP\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int[] \fBints\fP = new int[8]"
.br
.ti -1c
.RI "string[] \fBstrs\fP = new string[1]"
.br
.ti -1c
.RI "\fBSourceCellEffect\&.Row\fP \fB_source\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBid\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "int \fBamount\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "EffectId \fBidEffect\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "int \fBpower\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "int \fBcolor\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "bool \fBisHostileAct\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "bool \fBisBlessed\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "bool \fBisCursed\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "int \fBidEle\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "string \fBn1\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "\fBSourceCellEffect\&.Row\fP \fBsource\fP\fR [get]\fP"
.br
.ti -1c
.RI "bool \fBIsFire\fP\fR [get]\fP"
.br
.ti -1c
.RI "bool \fBIsLiquid\fP\fR [get]\fP"
.br
.ti -1c
.RI "int \fBFireAmount\fP\fR [get]\fP"
.br
.ti -1c
.RI "int \fBLiquidAmount\fP\fR [get]\fP"
.br
.ti -1c
.RI "bool \fBWillFade\fP\fR [get]\fP"
.br
.in -1c

Properties inherited from \fBEClass\fP
.in +1c
.ti -1c
.RI "static \fBGame\fP \fBgame\fP\fR [get]\fP"
.br
.ti -1c
.RI "static bool \fBAdvMode\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBPlayer\fP \fBplayer\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBChara\fP \fBpc\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBUI\fP \fBui\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBMap\fP \fB_map\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBZone\fP \fB_zone\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranchOrHomeBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFaction\fP \fBHome\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFaction\fP \fBWilds\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBScene\fP \fBscene\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBBaseGameScreen\fP \fBscreen\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameSetting\fP \fBsetting\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameData\fP \fBgamedata\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBColorProfile\fP \fBColors\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBWorld\fP \fBworld\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBsources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBeditorSources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static SoundManager \fBSound\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBCoreDebug\fP \fBdebug\fP\fR [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Static Public Member Functions inherited from \fBEClass\fP
.in +1c
.ti -1c
.RI "static int \fBrnd\fP (int a)"
.br
.ti -1c
.RI "static int \fBcurve\fP (int a, int start, int step, int rate=75)"
.br
.ti -1c
.RI "static int \fBrndHalf\fP (int a)"
.br
.ti -1c
.RI "static float \fBrndf\fP (float a)"
.br
.ti -1c
.RI "static int \fBrndSqrt\fP (int a)"
.br
.ti -1c
.RI "static void \fBWait\fP (float a, \fBCard\fP c)"
.br
.ti -1c
.RI "static void \fBWait\fP (float a, \fBPoint\fP p)"
.br
.ti -1c
.RI "static int \fBBigger\fP (int a, int b)"
.br
.ti -1c
.RI "static int \fBSmaller\fP (int a, int b)"
.br
.in -1c

Static Public Attributes inherited from \fBEClass\fP
.in +1c
.ti -1c
.RI "static \fBCore\fP \fBcore\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB5\fP of file \fBCellEffect\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBSourceCellEffect\&.Row\fP CellEffect\&._source"

.PP
Definition at line \fB239\fP of file \fBCellEffect\&.cs\fP\&.
.SS "int [] CellEffect\&.ints = new int[8]"

.PP
Definition at line \fB232\fP of file \fBCellEffect\&.cs\fP\&.
.SS "string [] CellEffect\&.strs = new string[1]"

.PP
Definition at line \fB236\fP of file \fBCellEffect\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "int CellEffect\&.amount\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB25\fP of file \fBCellEffect\&.cs\fP\&.
.SS "int CellEffect\&.color\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB70\fP of file \fBCellEffect\&.cs\fP\&.
.SS "int CellEffect\&.FireAmount\fR [get]\fP"

.PP
Definition at line \fB194\fP of file \fBCellEffect\&.cs\fP\&.
.SS "int CellEffect\&.id\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB10\fP of file \fBCellEffect\&.cs\fP\&.
.SS "EffectId CellEffect\&.idEffect\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB40\fP of file \fBCellEffect\&.cs\fP\&.
.SS "int CellEffect\&.idEle\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB130\fP of file \fBCellEffect\&.cs\fP\&.
.SS "bool CellEffect\&.isBlessed\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB100\fP of file \fBCellEffect\&.cs\fP\&.
.SS "bool CellEffect\&.isCursed\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB115\fP of file \fBCellEffect\&.cs\fP\&.
.SS "bool CellEffect\&.IsFire\fR [get]\fP"

.PP
Definition at line \fB174\fP of file \fBCellEffect\&.cs\fP\&.
.SS "bool CellEffect\&.isHostileAct\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB85\fP of file \fBCellEffect\&.cs\fP\&.
.SS "bool CellEffect\&.IsLiquid\fR [get]\fP"

.PP
Definition at line \fB184\fP of file \fBCellEffect\&.cs\fP\&.
.SS "int CellEffect\&.LiquidAmount\fR [get]\fP"

.PP
Definition at line \fB208\fP of file \fBCellEffect\&.cs\fP\&.
.SS "string CellEffect\&.n1\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB145\fP of file \fBCellEffect\&.cs\fP\&.
.SS "int CellEffect\&.power\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB55\fP of file \fBCellEffect\&.cs\fP\&.
.SS "\fBSourceCellEffect\&.Row\fP CellEffect\&.source\fR [get]\fP"

.PP
Definition at line \fB159\fP of file \fBCellEffect\&.cs\fP\&.
.SS "bool CellEffect\&.WillFade\fR [get]\fP"

.PP
Definition at line \fB222\fP of file \fBCellEffect\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
