.TH "CellDetail" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CellDetail
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBTryDespawn\fP ()"
.br
.ti -1c
.RI "void \fBMoveThingToBottom\fP (\fBThing\fP t)"
.br
.ti -1c
.RI "void \fBMoveThingToTop\fP (\fBThing\fP t)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBCellDetail\fP \fBSpawn\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "List< \fBThing\fP > \fBthings\fP = new List<\fBThing\fP>(1)"
.br
.ti -1c
.RI "List< \fBChara\fP > \fBcharas\fP = new List<\fBChara\fP>(1)"
.br
.ti -1c
.RI "\fBArea\fP \fBarea\fP"
.br
.ti -1c
.RI "\fBFootmark\fP \fBfootmark\fP"
.br
.ti -1c
.RI "\fBTaskDesignation\fP \fBdesignation\fP"
.br
.ti -1c
.RI "\fBTransAnime\fP \fBanime\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static int \fBcount\fP"
.br
.ti -1c
.RI "static \fBMap\fP \fBmap\fP"
.br
.ti -1c
.RI "static Stack< \fBCellDetail\fP > \fBcache\fP = new Stack<\fBCellDetail\fP>()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "static \fBCellDetail\fP \fBEmpty\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB5\fP of file \fBCellDetail\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void CellDetail\&.MoveThingToBottom (\fBThing\fP t)"

.PP
Definition at line \fB40\fP of file \fBCellDetail\&.cs\fP\&.
.SS "void CellDetail\&.MoveThingToTop (\fBThing\fP t)"

.PP
Definition at line \fB57\fP of file \fBCellDetail\&.cs\fP\&.
.SS "static \fBCellDetail\fP CellDetail\&.Spawn ()\fR [static]\fP"

.PP
Definition at line \fB18\fP of file \fBCellDetail\&.cs\fP\&.
.SS "bool CellDetail\&.TryDespawn ()"

.PP
Definition at line \fB29\fP of file \fBCellDetail\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBTransAnime\fP CellDetail\&.anime"

.PP
Definition at line \fB104\fP of file \fBCellDetail\&.cs\fP\&.
.SS "\fBArea\fP CellDetail\&.area"

.PP
Definition at line \fB95\fP of file \fBCellDetail\&.cs\fP\&.
.SS "Stack<\fBCellDetail\fP> CellDetail\&.cache = new Stack<\fBCellDetail\fP>()\fR [static]\fP"

.PP
Definition at line \fB86\fP of file \fBCellDetail\&.cs\fP\&.
.SS "List<\fBChara\fP> CellDetail\&.charas = new List<\fBChara\fP>(1)"

.PP
Definition at line \fB92\fP of file \fBCellDetail\&.cs\fP\&.
.SS "int CellDetail\&.count\fR [static]\fP"

.PP
Definition at line \fB80\fP of file \fBCellDetail\&.cs\fP\&.
.SS "\fBTaskDesignation\fP CellDetail\&.designation"

.PP
Definition at line \fB101\fP of file \fBCellDetail\&.cs\fP\&.
.SS "\fBFootmark\fP CellDetail\&.footmark"

.PP
Definition at line \fB98\fP of file \fBCellDetail\&.cs\fP\&.
.SS "\fBMap\fP CellDetail\&.map\fR [static]\fP"

.PP
Definition at line \fB83\fP of file \fBCellDetail\&.cs\fP\&.
.SS "List<\fBThing\fP> CellDetail\&.things = new List<\fBThing\fP>(1)"

.PP
Definition at line \fB89\fP of file \fBCellDetail\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "\fBCellDetail\fP CellDetail\&.Empty\fR [static]\fP, \fR [get]\fP"

.PP
Definition at line \fB9\fP of file \fBCellDetail\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
