.TH "CharaFilter" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CharaFilter
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCardFilter\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override bool \fBContainsTag\fP (\fBCardRow\fP source, string str)"
.br
.in -1c

Public Member Functions inherited from \fBCardFilter\fP
.in +1c
.ti -1c
.RI "override string \fBToString\fP ()"
.br
.ti -1c
.RI "void \fBInit\fP ()"
.br
.ti -1c
.RI "bool \fBPass\fP (\fBCardRow\fP source)"
.br
.ti -1c
.RI "void \fBBuildList\fP (List< \fBCardFilter\&.FilterItem\fP > list, string[] strs)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Func< \fBSourceChara\&.Row\fP, bool > \fBShouldPass\fP"
.br
.in -1c

Public Attributes inherited from \fBCardFilter\fP
.in +1c
.ti -1c
.RI "string \fBid\fP"
.br
.ti -1c
.RI "string[] \fBstrTag\fP"
.br
.ti -1c
.RI "string[] \fBstrFilter\fP"
.br
.ti -1c
.RI "string[] \fBfilterCategory\fP"
.br
.ti -1c
.RI "string[] \fBidCard\fP"
.br
.ti -1c
.RI "List< \fBCardFilter\&.FilterItem\fP > \fBtags\fP = new List<\fBCardFilter\&.FilterItem\fP>()"
.br
.ti -1c
.RI "List< \fBCardFilter\&.FilterItem\fP > \fBfilters\fP = new List<\fBCardFilter\&.FilterItem\fP>()"
.br
.ti -1c
.RI "List< \fBCardFilter\&.FilterCategory\fP > \fBcategories\fP = new List<\fBCardFilter\&.FilterCategory\fP>()"
.br
.ti -1c
.RI "List< \fBSourceCategory\&.Row\fP > \fBcategoriesInclude\fP = new List<\fBSourceCategory\&.Row\fP>()"
.br
.ti -1c
.RI "bool \fBisChara\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override bool \fB_ShouldPass\fP (\fBCardRow\fP source)"
.br
.in -1c

Protected Member Functions inherited from \fBCardFilter\fP
.SS "Additional Inherited Members"


Public Types inherited from \fBCardFilter\fP
.in +1c
.ti -1c
.RI "enum \fBFilterMode\fP { \fBNone\fP, \fBExclude\fP, \fBMatch\fP, \fBEquipped\fP }"
.br
.in -1c

Static Public Member Functions inherited from \fBCardFilter\fP
.in +1c
.ti -1c
.RI "static \fBCardFilter\&.FilterItem\fP \fBGetFilterItem\fP (string text)"
.br
.in -1c

Static Public Member Functions inherited from \fBEClass\fP
.in +1c
.ti -1c
.RI "static int \fBrnd\fP (int a)"
.br
.ti -1c
.RI "static int \fBcurve\fP (int a, int start, int step, int rate=75)"
.br
.ti -1c
.RI "static int \fBrndHalf\fP (int a)"
.br
.ti -1c
.RI "static float \fBrndf\fP (float a)"
.br
.ti -1c
.RI "static int \fBrndSqrt\fP (int a)"
.br
.ti -1c
.RI "static void \fBWait\fP (float a, \fBCard\fP c)"
.br
.ti -1c
.RI "static void \fBWait\fP (float a, \fBPoint\fP p)"
.br
.ti -1c
.RI "static int \fBBigger\fP (int a, int b)"
.br
.ti -1c
.RI "static int \fBSmaller\fP (int a, int b)"
.br
.in -1c

Static Public Attributes inherited from \fBEClass\fP
.in +1c
.ti -1c
.RI "static \fBCore\fP \fBcore\fP"
.br
.in -1c

Properties inherited from \fBEClass\fP
.in +1c
.ti -1c
.RI "static \fBGame\fP \fBgame\fP\fR [get]\fP"
.br
.ti -1c
.RI "static bool \fBAdvMode\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBPlayer\fP \fBplayer\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBChara\fP \fBpc\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBUI\fP \fBui\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBMap\fP \fB_map\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBZone\fP \fB_zone\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranchOrHomeBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFaction\fP \fBHome\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFaction\fP \fBWilds\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBScene\fP \fBscene\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBBaseGameScreen\fP \fBscreen\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameSetting\fP \fBsetting\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameData\fP \fBgamedata\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBColorProfile\fP \fBColors\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBWorld\fP \fBworld\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBsources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBeditorSources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static SoundManager \fBSound\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBCoreDebug\fP \fBdebug\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB4\fP of file \fBCharaFilter\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CharaFilter\&.CharaFilter ()"

.PP
Definition at line \fB7\fP of file \fBCharaFilter\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override bool CharaFilter\&._ShouldPass (\fBCardRow\fP source)\fR [protected]\fP, \fR [virtual]\fP"

.PP
Reimplemented from \fBCardFilter\fP\&.
.PP
Definition at line \fB13\fP of file \fBCharaFilter\&.cs\fP\&.
.SS "override bool CharaFilter\&.ContainsTag (\fBCardRow\fP source, string str)\fR [virtual]\fP"

.PP
Reimplemented from \fBCardFilter\fP\&.
.PP
Definition at line \fB19\fP of file \fBCharaFilter\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "Func<\fBSourceChara\&.Row\fP, bool> CharaFilter\&.ShouldPass"

.PP
Definition at line \fB26\fP of file \fBCharaFilter\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
