.TH "CharaActorPCC" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CharaActorPCC
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCharaActor\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnSetOwner\fP ()"
.br
.ti -1c
.RI "override void \fBNextFrame\fP ()"
.br
.ti -1c
.RI "override void \fBIdleFrame\fP ()"
.br
.ti -1c
.RI "override int \fBGetFrame\fP ()"
.br
.ti -1c
.RI "override void \fBNextDir\fP ()"
.br
.ti -1c
.RI "override void \fBKill\fP ()"
.br
.ti -1c
.RI "override void \fBOnRender\fP (\fBRenderParam\fP p)"
.br
.ti -1c
.RI "override void \fBRefreshSprite\fP ()"
.br
.in -1c

Public Member Functions inherited from \fBCharaActor\fP
.in +1c
.ti -1c
.RI "void \fBSetOwnerAsChara\fP ()"
.br
.in -1c

Public Member Functions inherited from \fBCardActor\fP
.in +1c
.ti -1c
.RI "void \fBSetOwner\fP (\fBCard\fP t)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "PCC \fBpcc\fP"
.br
.ti -1c
.RI "SpriteProvider \fBprovider\fP = new SpriteProvider()"
.br
.in -1c

Public Attributes inherited from \fBCharaActor\fP
.in +1c
.ti -1c
.RI "new \fBChara\fP \fBowner\fP"
.br
.in -1c

Public Attributes inherited from \fBCardActor\fP
.in +1c
.ti -1c
.RI "\fBCard\fP \fBowner\fP"
.br
.ti -1c
.RI "SpriteRenderer \fBsr\fP"
.br
.ti -1c
.RI "SpriteRenderer \fBsr2\fP"
.br
.ti -1c
.RI "SpriteReplacerAnimation \fBsrAnime\fP"
.br
.ti -1c
.RI "MaterialPropertyBlock \fBmpb\fP"
.br
.ti -1c
.RI "MaterialPropertyBlock \fBmpb2\fP"
.br
.ti -1c
.RI "CardActor\&.Type \fBtype\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static Vector3 \fBV2\fP = new Vector3(2f, 2f, 1f)"
.br
.in -1c

Static Public Attributes inherited from \fBEMono\fP
.in +1c
.ti -1c
.RI "static \fBCore\fP \fBcore\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override bool \fBisPCC\fP\fR [get]\fP"
.br
.ti -1c
.RI "override int \fBcurrentDir\fP\fR [get]\fP"
.br
.in -1c

Properties inherited from \fBCardActor\fP
.in +1c
.ti -1c
.RI "virtual bool \fBisPCC\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual int \fBcurrentDir\fP\fR [get]\fP"
.br
.in -1c

Properties inherited from \fBEMono\fP
.in +1c
.ti -1c
.RI "static \fBGame\fP \fBgame\fP\fR [get]\fP"
.br
.ti -1c
.RI "static bool \fBAdvMode\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBPlayer\fP \fBplayer\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBChara\fP \fBpc\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBUI\fP \fBui\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBMap\fP \fB_map\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBZone\fP \fB_zone\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranchOrHomeBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFaction\fP \fBHome\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBScene\fP \fBscene\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBBaseGameScreen\fP \fBscreen\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameSetting\fP \fBsetting\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameData\fP \fBgamedata\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBColorProfile\fP \fBColors\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBWorld\fP \fBworld\fP\fR [get]\fP"
.br
.ti -1c
.RI "static SoundManager \fBSound\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBsources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBeditorSources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBCoreDebug\fP \fBdebug\fP\fR [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Public Types inherited from \fBCardActor\fP
.in +1c
.ti -1c
.RI "enum \fBType\fP { \fBDefault\fP, \fBBoat\fP, \fBCanvas\fP, \fBMultiSprite\fP }"
.br
.in -1c

Static Public Member Functions inherited from \fBEMono\fP
.in +1c
.ti -1c
.RI "static int \fBrnd\fP (int a)"
.br
.in -1c

Static Protected Attributes inherited from \fBCardActor\fP
.in +1c
.ti -1c
.RI "static Vector3 \fBtempV\fP"
.br
.ti -1c
.RI "static Vector3 \fBtempV2\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB5\fP of file \fBCharaActorPCC\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override int CharaActorPCC\&.GetFrame ()\fR [virtual]\fP"

.PP
Reimplemented from \fBCardActor\fP\&.
.PP
Definition at line \fB65\fP of file \fBCharaActorPCC\&.cs\fP\&.
.SS "override void CharaActorPCC\&.IdleFrame ()\fR [virtual]\fP"

.PP
Reimplemented from \fBCardActor\fP\&.
.PP
Definition at line \fB56\fP of file \fBCharaActorPCC\&.cs\fP\&.
.SS "override void CharaActorPCC\&.Kill ()\fR [virtual]\fP"

.PP
Reimplemented from \fBCardActor\fP\&.
.PP
Definition at line \fB81\fP of file \fBCharaActorPCC\&.cs\fP\&.
.SS "override void CharaActorPCC\&.NextDir ()\fR [virtual]\fP"

.PP
Reimplemented from \fBCardActor\fP\&.
.PP
Definition at line \fB71\fP of file \fBCharaActorPCC\&.cs\fP\&.
.SS "override void CharaActorPCC\&.NextFrame ()\fR [virtual]\fP"

.PP
Reimplemented from \fBCharaActor\fP\&.
.PP
Definition at line \fB45\fP of file \fBCharaActorPCC\&.cs\fP\&.
.SS "override void CharaActorPCC\&.OnRender (\fBRenderParam\fP p)\fR [virtual]\fP"

.PP
Reimplemented from \fBCardActor\fP\&.
.PP
Definition at line \fB89\fP of file \fBCharaActorPCC\&.cs\fP\&.
.SS "override void CharaActorPCC\&.OnSetOwner ()\fR [virtual]\fP"

.PP
Reimplemented from \fBCharaActor\fP\&.
.PP
Definition at line \fB28\fP of file \fBCharaActorPCC\&.cs\fP\&.
.SS "override void CharaActorPCC\&.RefreshSprite ()\fR [virtual]\fP"

.PP
Reimplemented from \fBCharaActor\fP\&.
.PP
Definition at line \fB205\fP of file \fBCharaActorPCC\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "PCC CharaActorPCC\&.pcc"

.PP
Definition at line \fB217\fP of file \fBCharaActorPCC\&.cs\fP\&.
.SS "SpriteProvider CharaActorPCC\&.provider = new SpriteProvider()"

.PP
Definition at line \fB220\fP of file \fBCharaActorPCC\&.cs\fP\&.
.SS "Vector3 CharaActorPCC\&.V2 = new Vector3(2f, 2f, 1f)\fR [static]\fP"

.PP
Definition at line \fB226\fP of file \fBCharaActorPCC\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "override int CharaActorPCC\&.currentDir\fR [get]\fP"

.PP
Definition at line \fB19\fP of file \fBCharaActorPCC\&.cs\fP\&.
.SS "override bool CharaActorPCC\&.isPCC\fR [get]\fP"

.PP
Definition at line \fB9\fP of file \fBCharaActorPCC\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
