.TH "CINT" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CINT
.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "const int \fBweight\fP = 1"
.br
.ti -1c
.RI "const int \fBIDTState\fP = 2"
.br
.ti -1c
.RI "const int \fBdyeMat\fP = 3"
.br
.ti -1c
.RI "const int \fBvisitorState\fP = 4"
.br
.ti -1c
.RI "const int \fBlightColor\fP = 5"
.br
.ti -1c
.RI "const int \fBequippedSlot\fP = 6"
.br
.ti -1c
.RI "const int \fBcharges\fP = 7"
.br
.ti -1c
.RI "const int \fBcontainerSize\fP = 8"
.br
.ti -1c
.RI "const int \fBbedType\fP = 9"
.br
.ti -1c
.RI "const int \fBuidZone\fP = 10"
.br
.ti -1c
.RI "const int \fBuidRefCard\fP = 11"
.br
.ti -1c
.RI "const int \fBoriginalHostility\fP = 12"
.br
.ti -1c
.RI "const int \fBvomit\fP = 13"
.br
.ti -1c
.RI "const int \fBdiceDim\fP = 14"
.br
.ti -1c
.RI "const int \fBindexContainerIcon\fP = 15"
.br
.ti -1c
.RI "const int \fBidMainElement\fP = 16"
.br
.ti -1c
.RI "const int \fBsummonDuration\fP = 17"
.br
.ti -1c
.RI "const int \fBisHiredByGold\fP = 18"
.br
.ti -1c
.RI "const int \fBprice\fP = 21"
.br
.ti -1c
.RI "const int \fBdateStockExpire\fP = 22"
.br
.ti -1c
.RI "const int \fBbill\fP = 23"
.br
.ti -1c
.RI "const int \fBzonePrefix\fP = 24"
.br
.ti -1c
.RI "const int \fBzoneLv\fP = 25"
.br
.ti -1c
.RI "const int \fBwellPollution\fP = 26"
.br
.ti -1c
.RI "const int \fBammo\fP = 27"
.br
.ti -1c
.RI "const int \fBinvest\fP = 28"
.br
.ti -1c
.RI "const int \fBprice_add\fP = 29"
.br
.ti -1c
.RI "const int \fBdateSteal\fP = 30"
.br
.ti -1c
.RI "const int \fBdateCannibalEnd\fP = 31"
.br
.ti -1c
.RI "const int \fBdateLastSeen\fP = 32"
.br
.ti -1c
.RI "const int \fBseed\fP = 33"
.br
.ti -1c
.RI "const int \fBdateNews\fP = 33"
.br
.ti -1c
.RI "const int \fBdateGuestArrived\fP = 34"
.br
.ti -1c
.RI "const int \fBtaxExtra\fP = 35"
.br
.ti -1c
.RI "const int \fBdateLivestock\fP = 36"
.br
.ti -1c
.RI "const int \fBlockLv\fP = 50"
.br
.ti -1c
.RI "const int \fBdateNextExpedition\fP = 51"
.br
.ti -1c
.RI "const int \fBidBacker\fP = 52"
.br
.ti -1c
.RI "const int \fBrescue\fP = 53"
.br
.ti -1c
.RI "const int \fBuidMaster\fP = 54"
.br
.ti -1c
.RI "const int \fBuidLastEnemy\fP = 55"
.br
.ti -1c
.RI "const int \fBIsPC\fP = 56"
.br
.ti -1c
.RI "const int \fBdaysWithGod\fP = 57"
.br
.ti -1c
.RI "const int \fBdateLayHandDay\fP = 58"
.br
.ti -1c
.RI "const int \fBdateBout\fP = 59"
.br
.ti -1c
.RI "const int \fBdisarmFail\fP = 60"
.br
.ti -1c
.RI "const int \fBminionType\fP = 61"
.br
.ti -1c
.RI "const int \fBfur\fP = 62"
.br
.ti -1c
.RI "const int \fBlockType\fP = 63"
.br
.ti -1c
.RI "const int \fBrevealLock\fP = 64"
.br
.ti -1c
.RI "const int \fBbossType\fP = 65"
.br
.ti -1c
.RI "const int \fBfiamaPet\fP = 100"
.br
.ti -1c
.RI "const int \fBnoRestock\fP = 101"
.br
.ti -1c
.RI "const int \fBuidPackageZone\fP = 102"
.br
.ti -1c
.RI "const int \fBwasInPcParty\fP = 103"
.br
.ti -1c
.RI "const int \fBmapPos\fP = 104"
.br
.ti -1c
.RI "const int \fBcolorHair\fP = 105"
.br
.ti -1c
.RI "const int \fBmute\fP = 106"
.br
.ti -1c
.RI "const int \fBnumLicked\fP = 107"
.br
.ti -1c
.RI "const int \fBinsult\fP = 108"
.br
.ti -1c
.RI "const int \fBisImportant\fP = 109"
.br
.ti -1c
.RI "const int \fBnumBeaten\fP = 111"
.br
.ti -1c
.RI "const int \fBsisterEaten\fP = 112"
.br
.ti -1c
.RI "const int \fBdisableSharedEquip\fP = 113"
.br
.ti -1c
.RI "const int \fBallowance\fP = 114"
.br
.ti -1c
.RI "const int \fBisHarvestQuestCrop\fP = 115"
.br
.ti -1c
.RI "const int \fBisStolenFromPC\fP = 116"
.br
.ti -1c
.RI "const int \fBisTrained\fP = 120"
.br
.ti -1c
.RI "const int \fBisPrayed\fP = 121"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB4\fP of file \fBCINT\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "const int CINT\&.allowance = 114\fR [static]\fP"

.PP
Definition at line \fB199\fP of file \fBCINT\&.cs\fP\&.
.SS "const int CINT\&.ammo = 27\fR [static]\fP"

.PP
Definition at line \fB79\fP of file \fBCINT\&.cs\fP\&.
.SS "const int CINT\&.bedType = 9\fR [static]\fP"

.PP
Definition at line \fB31\fP of file \fBCINT\&.cs\fP\&.
.SS "const int CINT\&.bill = 23\fR [static]\fP"

.PP
Definition at line \fB67\fP of file \fBCINT\&.cs\fP\&.
.SS "const int CINT\&.bossType = 65\fR [static]\fP"

.PP
Definition at line \fB157\fP of file \fBCINT\&.cs\fP\&.
.SS "const int CINT\&.charges = 7\fR [static]\fP"

.PP
Definition at line \fB25\fP of file \fBCINT\&.cs\fP\&.
.SS "const int CINT\&.colorHair = 105\fR [static]\fP"

.PP
Definition at line \fB175\fP of file \fBCINT\&.cs\fP\&.
.SS "const int CINT\&.containerSize = 8\fR [static]\fP"

.PP
Definition at line \fB28\fP of file \fBCINT\&.cs\fP\&.
.SS "const int CINT\&.dateBout = 59\fR [static]\fP"

.PP
Definition at line \fB139\fP of file \fBCINT\&.cs\fP\&.
.SS "const int CINT\&.dateCannibalEnd = 31\fR [static]\fP"

.PP
Definition at line \fB91\fP of file \fBCINT\&.cs\fP\&.
.SS "const int CINT\&.dateGuestArrived = 34\fR [static]\fP"

.PP
Definition at line \fB103\fP of file \fBCINT\&.cs\fP\&.
.SS "const int CINT\&.dateLastSeen = 32\fR [static]\fP"

.PP
Definition at line \fB94\fP of file \fBCINT\&.cs\fP\&.
.SS "const int CINT\&.dateLayHandDay = 58\fR [static]\fP"

.PP
Definition at line \fB136\fP of file \fBCINT\&.cs\fP\&.
.SS "const int CINT\&.dateLivestock = 36\fR [static]\fP"

.PP
Definition at line \fB109\fP of file \fBCINT\&.cs\fP\&.
.SS "const int CINT\&.dateNews = 33\fR [static]\fP"

.PP
Definition at line \fB100\fP of file \fBCINT\&.cs\fP\&.
.SS "const int CINT\&.dateNextExpedition = 51\fR [static]\fP"

.PP
Definition at line \fB115\fP of file \fBCINT\&.cs\fP\&.
.SS "const int CINT\&.dateSteal = 30\fR [static]\fP"

.PP
Definition at line \fB88\fP of file \fBCINT\&.cs\fP\&.
.SS "const int CINT\&.dateStockExpire = 22\fR [static]\fP"

.PP
Definition at line \fB64\fP of file \fBCINT\&.cs\fP\&.
.SS "const int CINT\&.daysWithGod = 57\fR [static]\fP"

.PP
Definition at line \fB133\fP of file \fBCINT\&.cs\fP\&.
.SS "const int CINT\&.diceDim = 14\fR [static]\fP"

.PP
Definition at line \fB46\fP of file \fBCINT\&.cs\fP\&.
.SS "const int CINT\&.disableSharedEquip = 113\fR [static]\fP"

.PP
Definition at line \fB196\fP of file \fBCINT\&.cs\fP\&.
.SS "const int CINT\&.disarmFail = 60\fR [static]\fP"

.PP
Definition at line \fB142\fP of file \fBCINT\&.cs\fP\&.
.SS "const int CINT\&.dyeMat = 3\fR [static]\fP"

.PP
Definition at line \fB13\fP of file \fBCINT\&.cs\fP\&.
.SS "const int CINT\&.equippedSlot = 6\fR [static]\fP"

.PP
Definition at line \fB22\fP of file \fBCINT\&.cs\fP\&.
.SS "const int CINT\&.fiamaPet = 100\fR [static]\fP"

.PP
Definition at line \fB160\fP of file \fBCINT\&.cs\fP\&.
.SS "const int CINT\&.fur = 62\fR [static]\fP"

.PP
Definition at line \fB148\fP of file \fBCINT\&.cs\fP\&.
.SS "const int CINT\&.idBacker = 52\fR [static]\fP"

.PP
Definition at line \fB118\fP of file \fBCINT\&.cs\fP\&.
.SS "const int CINT\&.idMainElement = 16\fR [static]\fP"

.PP
Definition at line \fB52\fP of file \fBCINT\&.cs\fP\&.
.SS "const int CINT\&.IDTState = 2\fR [static]\fP"

.PP
Definition at line \fB10\fP of file \fBCINT\&.cs\fP\&.
.SS "const int CINT\&.indexContainerIcon = 15\fR [static]\fP"

.PP
Definition at line \fB49\fP of file \fBCINT\&.cs\fP\&.
.SS "const int CINT\&.insult = 108\fR [static]\fP"

.PP
Definition at line \fB184\fP of file \fBCINT\&.cs\fP\&.
.SS "const int CINT\&.invest = 28\fR [static]\fP"

.PP
Definition at line \fB82\fP of file \fBCINT\&.cs\fP\&.
.SS "const int CINT\&.isHarvestQuestCrop = 115\fR [static]\fP"

.PP
Definition at line \fB202\fP of file \fBCINT\&.cs\fP\&.
.SS "const int CINT\&.isHiredByGold = 18\fR [static]\fP"

.PP
Definition at line \fB58\fP of file \fBCINT\&.cs\fP\&.
.SS "const int CINT\&.isImportant = 109\fR [static]\fP"

.PP
Definition at line \fB187\fP of file \fBCINT\&.cs\fP\&.
.SS "const int CINT\&.IsPC = 56\fR [static]\fP"

.PP
Definition at line \fB130\fP of file \fBCINT\&.cs\fP\&.
.SS "const int CINT\&.isPrayed = 121\fR [static]\fP"

.PP
Definition at line \fB211\fP of file \fBCINT\&.cs\fP\&.
.SS "const int CINT\&.isStolenFromPC = 116\fR [static]\fP"

.PP
Definition at line \fB205\fP of file \fBCINT\&.cs\fP\&.
.SS "const int CINT\&.isTrained = 120\fR [static]\fP"

.PP
Definition at line \fB208\fP of file \fBCINT\&.cs\fP\&.
.SS "const int CINT\&.lightColor = 5\fR [static]\fP"

.PP
Definition at line \fB19\fP of file \fBCINT\&.cs\fP\&.
.SS "const int CINT\&.lockLv = 50\fR [static]\fP"

.PP
Definition at line \fB112\fP of file \fBCINT\&.cs\fP\&.
.SS "const int CINT\&.lockType = 63\fR [static]\fP"

.PP
Definition at line \fB151\fP of file \fBCINT\&.cs\fP\&.
.SS "const int CINT\&.mapPos = 104\fR [static]\fP"

.PP
Definition at line \fB172\fP of file \fBCINT\&.cs\fP\&.
.SS "const int CINT\&.minionType = 61\fR [static]\fP"

.PP
Definition at line \fB145\fP of file \fBCINT\&.cs\fP\&.
.SS "const int CINT\&.mute = 106\fR [static]\fP"

.PP
Definition at line \fB178\fP of file \fBCINT\&.cs\fP\&.
.SS "const int CINT\&.noRestock = 101\fR [static]\fP"

.PP
Definition at line \fB163\fP of file \fBCINT\&.cs\fP\&.
.SS "const int CINT\&.numBeaten = 111\fR [static]\fP"

.PP
Definition at line \fB190\fP of file \fBCINT\&.cs\fP\&.
.SS "const int CINT\&.numLicked = 107\fR [static]\fP"

.PP
Definition at line \fB181\fP of file \fBCINT\&.cs\fP\&.
.SS "const int CINT\&.originalHostility = 12\fR [static]\fP"

.PP
Definition at line \fB40\fP of file \fBCINT\&.cs\fP\&.
.SS "const int CINT\&.price = 21\fR [static]\fP"

.PP
Definition at line \fB61\fP of file \fBCINT\&.cs\fP\&.
.SS "const int CINT\&.price_add = 29\fR [static]\fP"

.PP
Definition at line \fB85\fP of file \fBCINT\&.cs\fP\&.
.SS "const int CINT\&.rescue = 53\fR [static]\fP"

.PP
Definition at line \fB121\fP of file \fBCINT\&.cs\fP\&.
.SS "const int CINT\&.revealLock = 64\fR [static]\fP"

.PP
Definition at line \fB154\fP of file \fBCINT\&.cs\fP\&.
.SS "const int CINT\&.seed = 33\fR [static]\fP"

.PP
Definition at line \fB97\fP of file \fBCINT\&.cs\fP\&.
.SS "const int CINT\&.sisterEaten = 112\fR [static]\fP"

.PP
Definition at line \fB193\fP of file \fBCINT\&.cs\fP\&.
.SS "const int CINT\&.summonDuration = 17\fR [static]\fP"

.PP
Definition at line \fB55\fP of file \fBCINT\&.cs\fP\&.
.SS "const int CINT\&.taxExtra = 35\fR [static]\fP"

.PP
Definition at line \fB106\fP of file \fBCINT\&.cs\fP\&.
.SS "const int CINT\&.uidLastEnemy = 55\fR [static]\fP"

.PP
Definition at line \fB127\fP of file \fBCINT\&.cs\fP\&.
.SS "const int CINT\&.uidMaster = 54\fR [static]\fP"

.PP
Definition at line \fB124\fP of file \fBCINT\&.cs\fP\&.
.SS "const int CINT\&.uidPackageZone = 102\fR [static]\fP"

.PP
Definition at line \fB166\fP of file \fBCINT\&.cs\fP\&.
.SS "const int CINT\&.uidRefCard = 11\fR [static]\fP"

.PP
Definition at line \fB37\fP of file \fBCINT\&.cs\fP\&.
.SS "const int CINT\&.uidZone = 10\fR [static]\fP"

.PP
Definition at line \fB34\fP of file \fBCINT\&.cs\fP\&.
.SS "const int CINT\&.visitorState = 4\fR [static]\fP"

.PP
Definition at line \fB16\fP of file \fBCINT\&.cs\fP\&.
.SS "const int CINT\&.vomit = 13\fR [static]\fP"

.PP
Definition at line \fB43\fP of file \fBCINT\&.cs\fP\&.
.SS "const int CINT\&.wasInPcParty = 103\fR [static]\fP"

.PP
Definition at line \fB169\fP of file \fBCINT\&.cs\fP\&.
.SS "const int CINT\&.weight = 1\fR [static]\fP"

.PP
Definition at line \fB7\fP of file \fBCINT\&.cs\fP\&.
.SS "const int CINT\&.wellPollution = 26\fR [static]\fP"

.PP
Definition at line \fB76\fP of file \fBCINT\&.cs\fP\&.
.SS "const int CINT\&.zoneLv = 25\fR [static]\fP"

.PP
Definition at line \fB73\fP of file \fBCINT\&.cs\fP\&.
.SS "const int CINT\&.zonePrefix = 24\fR [static]\fP"

.PP
Definition at line \fB70\fP of file \fBCINT\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
