.TH "COBJ" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
COBJ
.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "const int \fBhouseBoardData\fP = 1"
.br
.ti -1c
.RI "const int \fBwindowSaveData\fP = 2"
.br
.ti -1c
.RI "const int \fBroomPlateData\fP = 3"
.br
.ti -1c
.RI "const int \fBtextureData\fP = 4"
.br
.ti -1c
.RI "const int \fBslaverData\fP = 5"
.br
.ti -1c
.RI "const int \fBuniqueData\fP = 6"
.br
.ti -1c
.RI "const int \fBeffectData\fP = 7"
.br
.ti -1c
.RI "const int \fBchara\fP = 8"
.br
.ti -1c
.RI "const int \fBammoData\fP = 9"
.br
.ti -1c
.RI "const int \fBcopyContainer\fP = 10"
.br
.ti -1c
.RI "const int \fBcharaUpgrade\fP = 11"
.br
.ti -1c
.RI "const int \fBcontainerUpgrade\fP = 12"
.br
.ti -1c
.RI "const int \fBcharaList\fP = 13"
.br
.ti -1c
.RI "const int \fBdna\fP = 14"
.br
.ti -1c
.RI "const int \fBcharaGenes\fP = 15"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB4\fP of file \fBCOBJ\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "const int COBJ\&.ammoData = 9\fR [static]\fP"

.PP
Definition at line \fB31\fP of file \fBCOBJ\&.cs\fP\&.
.SS "const int COBJ\&.chara = 8\fR [static]\fP"

.PP
Definition at line \fB28\fP of file \fBCOBJ\&.cs\fP\&.
.SS "const int COBJ\&.charaGenes = 15\fR [static]\fP"

.PP
Definition at line \fB49\fP of file \fBCOBJ\&.cs\fP\&.
.SS "const int COBJ\&.charaList = 13\fR [static]\fP"

.PP
Definition at line \fB43\fP of file \fBCOBJ\&.cs\fP\&.
.SS "const int COBJ\&.charaUpgrade = 11\fR [static]\fP"

.PP
Definition at line \fB37\fP of file \fBCOBJ\&.cs\fP\&.
.SS "const int COBJ\&.containerUpgrade = 12\fR [static]\fP"

.PP
Definition at line \fB40\fP of file \fBCOBJ\&.cs\fP\&.
.SS "const int COBJ\&.copyContainer = 10\fR [static]\fP"

.PP
Definition at line \fB34\fP of file \fBCOBJ\&.cs\fP\&.
.SS "const int COBJ\&.dna = 14\fR [static]\fP"

.PP
Definition at line \fB46\fP of file \fBCOBJ\&.cs\fP\&.
.SS "const int COBJ\&.effectData = 7\fR [static]\fP"

.PP
Definition at line \fB25\fP of file \fBCOBJ\&.cs\fP\&.
.SS "const int COBJ\&.houseBoardData = 1\fR [static]\fP"

.PP
Definition at line \fB7\fP of file \fBCOBJ\&.cs\fP\&.
.SS "const int COBJ\&.roomPlateData = 3\fR [static]\fP"

.PP
Definition at line \fB13\fP of file \fBCOBJ\&.cs\fP\&.
.SS "const int COBJ\&.slaverData = 5\fR [static]\fP"

.PP
Definition at line \fB19\fP of file \fBCOBJ\&.cs\fP\&.
.SS "const int COBJ\&.textureData = 4\fR [static]\fP"

.PP
Definition at line \fB16\fP of file \fBCOBJ\&.cs\fP\&.
.SS "const int COBJ\&.uniqueData = 6\fR [static]\fP"

.PP
Definition at line \fB22\fP of file \fBCOBJ\&.cs\fP\&.
.SS "const int COBJ\&.windowSaveData = 2\fR [static]\fP"

.PP
Definition at line \fB10\fP of file \fBCOBJ\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
