.TH "ColorProfile.PCLights" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ColorProfile.PCLights
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "LightData \fBtorch\fP"
.br
.ti -1c
.RI "LightData \fBcateye\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB272\fP of file \fBColorProfile\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "LightData ColorProfile\&.PCLights\&.cateye"

.PP
Definition at line \fB278\fP of file \fBColorProfile\&.cs\fP\&.
.SS "LightData ColorProfile\&.PCLights\&.torch"

.PP
Definition at line \fB275\fP of file \fBColorProfile\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
