.TH "ColorProfile" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ColorProfile
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBEScriptable\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBlockColors\fP"
.br
.ti -1c
.RI "class \fBPCLights\fP"
.br
.ti -1c
.RI "class \fBRarityColors\fP"
.br
.ti -1c
.RI "class \fBTextColors\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBInit\fP ()"
.br
.ti -1c
.RI "Color \fBGetRarityColor\fP (int r, bool light=false)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "UD_String_MatData \fBmatColors\fP"
.br
.ti -1c
.RI "UD_String_LightData \fBlightColors\fP"
.br
.ti -1c
.RI "UD_String_Color \fBelementColors\fP"
.br
.ti -1c
.RI "\fBColorProfile\&.RarityColors\fP \fBrarityColors\fP"
.br
.ti -1c
.RI "\fBColorProfile\&.BlockColors\fP \fBblockColors\fP"
.br
.ti -1c
.RI "\fBColorProfile\&.TextColors\fP \fBtextColors\fP"
.br
.ti -1c
.RI "Gradient \fBgradientLVComparison\fP"
.br
.ti -1c
.RI "\fBColorProfile\&.PCLights\fP \fBpcLights\fP"
.br
.ti -1c
.RI "Color \fBcolorIngCost\fP"
.br
.ti -1c
.RI "Color \fBcolorIngPredict\fP"
.br
.ti -1c
.RI "Color \fBcolorIngReq\fP"
.br
.ti -1c
.RI "Color \fBcolorNew\fP"
.br
.ti -1c
.RI "Color \fBcolorAct\fP"
.br
.ti -1c
.RI "Color \fBcolorActWarnning\fP"
.br
.ti -1c
.RI "Color \fBcolorActCriticalWarning\fP"
.br
.ti -1c
.RI "Color \fBcolorHostileAct\fP"
.br
.ti -1c
.RI "Color \fBcolorFriend\fP"
.br
.ti -1c
.RI "Color \fBcolorHostile\fP"
.br
.ti -1c
.RI "Color \fBcolorBuff\fP"
.br
.ti -1c
.RI "Color \fBcolorDebuff\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "SkinColorProfile \fBSkin\fP\fR [get]\fP"
.br
.ti -1c
.RI "SkinColorProfile \fBDark\fP\fR [get]\fP"
.br
.ti -1c
.RI "SkinColorProfile \fBLight\fP\fR [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Static Public Member Functions inherited from \fBEScriptable\fP
.in +1c
.ti -1c
.RI "static int \fBrnd\fP (int a)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB5\fP of file \fBColorProfile\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "Color ColorProfile\&.GetRarityColor (int r, bool light = \fRfalse\fP)"

.PP
Definition at line \fB44\fP of file \fBColorProfile\&.cs\fP\&.
.SS "void ColorProfile\&.Init ()"

.PP
Definition at line \fB38\fP of file \fBColorProfile\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBColorProfile\&.BlockColors\fP ColorProfile\&.blockColors"

.PP
Definition at line \fB93\fP of file \fBColorProfile\&.cs\fP\&.
.SS "Color ColorProfile\&.colorAct"

.PP
Definition at line \fB117\fP of file \fBColorProfile\&.cs\fP\&.
.SS "Color ColorProfile\&.colorActCriticalWarning"

.PP
Definition at line \fB123\fP of file \fBColorProfile\&.cs\fP\&.
.SS "Color ColorProfile\&.colorActWarnning"

.PP
Definition at line \fB120\fP of file \fBColorProfile\&.cs\fP\&.
.SS "Color ColorProfile\&.colorBuff"

.PP
Definition at line \fB135\fP of file \fBColorProfile\&.cs\fP\&.
.SS "Color ColorProfile\&.colorDebuff"

.PP
Definition at line \fB138\fP of file \fBColorProfile\&.cs\fP\&.
.SS "Color ColorProfile\&.colorFriend"

.PP
Definition at line \fB129\fP of file \fBColorProfile\&.cs\fP\&.
.SS "Color ColorProfile\&.colorHostile"

.PP
Definition at line \fB132\fP of file \fBColorProfile\&.cs\fP\&.
.SS "Color ColorProfile\&.colorHostileAct"

.PP
Definition at line \fB126\fP of file \fBColorProfile\&.cs\fP\&.
.SS "Color ColorProfile\&.colorIngCost"

.PP
Definition at line \fB105\fP of file \fBColorProfile\&.cs\fP\&.
.SS "Color ColorProfile\&.colorIngPredict"

.PP
Definition at line \fB108\fP of file \fBColorProfile\&.cs\fP\&.
.SS "Color ColorProfile\&.colorIngReq"

.PP
Definition at line \fB111\fP of file \fBColorProfile\&.cs\fP\&.
.SS "Color ColorProfile\&.colorNew"

.PP
Definition at line \fB114\fP of file \fBColorProfile\&.cs\fP\&.
.SS "UD_String_Color ColorProfile\&.elementColors"

.PP
Definition at line \fB87\fP of file \fBColorProfile\&.cs\fP\&.
.SS "Gradient ColorProfile\&.gradientLVComparison"

.PP
Definition at line \fB99\fP of file \fBColorProfile\&.cs\fP\&.
.SS "UD_String_LightData ColorProfile\&.lightColors"

.PP
Definition at line \fB84\fP of file \fBColorProfile\&.cs\fP\&.
.SS "UD_String_MatData ColorProfile\&.matColors"

.PP
Definition at line \fB81\fP of file \fBColorProfile\&.cs\fP\&.
.SS "\fBColorProfile\&.PCLights\fP ColorProfile\&.pcLights"

.PP
Definition at line \fB102\fP of file \fBColorProfile\&.cs\fP\&.
.SS "\fBColorProfile\&.RarityColors\fP ColorProfile\&.rarityColors"

.PP
Definition at line \fB90\fP of file \fBColorProfile\&.cs\fP\&.
.SS "\fBColorProfile\&.TextColors\fP ColorProfile\&.textColors"

.PP
Definition at line \fB96\fP of file \fBColorProfile\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "SkinColorProfile ColorProfile\&.Dark\fR [get]\fP"

.PP
Definition at line \fB19\fP of file \fBColorProfile\&.cs\fP\&.
.SS "SkinColorProfile ColorProfile\&.Light\fR [get]\fP"

.PP
Definition at line \fB29\fP of file \fBColorProfile\&.cs\fP\&.
.SS "SkinColorProfile ColorProfile\&.Skin\fR [get]\fP"

.PP
Definition at line \fB9\fP of file \fBColorProfile\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
