.TH "ColorProfile.TextColors" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ColorProfile.TextColors
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Color \fBdamage\fP"
.br
.ti -1c
.RI "Color \fBdamagePC\fP"
.br
.ti -1c
.RI "Color \fBdamagePCParty\fP"
.br
.ti -1c
.RI "Color \fBdamageMana\fP"
.br
.ti -1c
.RI "Color \fBdamageStamina\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB252\fP of file \fBColorProfile\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "Color ColorProfile\&.TextColors\&.damage"

.PP
Definition at line \fB255\fP of file \fBColorProfile\&.cs\fP\&.
.SS "Color ColorProfile\&.TextColors\&.damageMana"

.PP
Definition at line \fB264\fP of file \fBColorProfile\&.cs\fP\&.
.SS "Color ColorProfile\&.TextColors\&.damagePC"

.PP
Definition at line \fB258\fP of file \fBColorProfile\&.cs\fP\&.
.SS "Color ColorProfile\&.TextColors\&.damagePCParty"

.PP
Definition at line \fB261\fP of file \fBColorProfile\&.cs\fP\&.
.SS "Color ColorProfile\&.TextColors\&.damageStamina"

.PP
Definition at line \fB267\fP of file \fBColorProfile\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
