.TH "ColorProfile.RarityColors" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ColorProfile.RarityColors
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Color \fBcolorC\fP"
.br
.ti -1c
.RI "Color \fBcolorR\fP"
.br
.ti -1c
.RI "Color \fBcolorSR\fP"
.br
.ti -1c
.RI "Color \fBcolorSSR\fP"
.br
.ti -1c
.RI "Color \fBcolorLE\fP"
.br
.ti -1c
.RI "float \fBlightMod\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB142\fP of file \fBColorProfile\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "Color ColorProfile\&.RarityColors\&.colorC"

.PP
Definition at line \fB145\fP of file \fBColorProfile\&.cs\fP\&.
.SS "Color ColorProfile\&.RarityColors\&.colorLE"

.PP
Definition at line \fB157\fP of file \fBColorProfile\&.cs\fP\&.
.SS "Color ColorProfile\&.RarityColors\&.colorR"

.PP
Definition at line \fB148\fP of file \fBColorProfile\&.cs\fP\&.
.SS "Color ColorProfile\&.RarityColors\&.colorSR"

.PP
Definition at line \fB151\fP of file \fBColorProfile\&.cs\fP\&.
.SS "Color ColorProfile\&.RarityColors\&.colorSSR"

.PP
Definition at line \fB154\fP of file \fBColorProfile\&.cs\fP\&.
.SS "float ColorProfile\&.RarityColors\&.lightMod"

.PP
Definition at line \fB160\fP of file \fBColorProfile\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
