.TH "ColorProfile.BlockColors" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ColorProfile.BlockColors
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBInit\fP ()"
.br
.ti -1c
.RI "int \fBGetColor\fP (ref Color c)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Color \fB_valid\fP"
.br
.ti -1c
.RI "Color \fB_warning\fP"
.br
.ti -1c
.RI "Color \fB_active\fP"
.br
.ti -1c
.RI "Color \fB_inactive\fP"
.br
.ti -1c
.RI "Color \fB_activeOpacity\fP"
.br
.ti -1c
.RI "Color \fB_inactiveOpacity\fP"
.br
.ti -1c
.RI "Color \fB_passive\fP"
.br
.ti -1c
.RI "Color \fB_mapHighlight\fP"
.br
.ti -1c
.RI "int \fBValid\fP"
.br
.ti -1c
.RI "int \fBWarning\fP"
.br
.ti -1c
.RI "int \fBInactive\fP"
.br
.ti -1c
.RI "int \fBActive\fP"
.br
.ti -1c
.RI "int \fBActiveOpacity\fP"
.br
.ti -1c
.RI "int \fBInactiveOpacity\fP"
.br
.ti -1c
.RI "int \fBPassive\fP"
.br
.ti -1c
.RI "int \fBMapHighlight\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "const int \fBDefColor\fP = 104025"
.br
.ti -1c
.RI "const int \fBDefColorInactive\fP = \-1214986"
.br
.ti -1c
.RI "const int \fBDefColorActive\fP = \-1173751"
.br
.ti -1c
.RI "const int \fBDefColorValid\fP = \-2747875"
.br
.ti -1c
.RI "const int \fBDefColorWarning\fP = \-2828814"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB165\fP of file \fBColorProfile\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "int ColorProfile\&.BlockColors\&.GetColor (ref Color c)"

.PP
Definition at line \fB181\fP of file \fBColorProfile\&.cs\fP\&.
.SS "void ColorProfile\&.BlockColors\&.Init ()"

.PP
Definition at line \fB168\fP of file \fBColorProfile\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "Color ColorProfile\&.BlockColors\&._active"

.PP
Definition at line \fB208\fP of file \fBColorProfile\&.cs\fP\&.
.SS "Color ColorProfile\&.BlockColors\&._activeOpacity"

.PP
Definition at line \fB214\fP of file \fBColorProfile\&.cs\fP\&.
.SS "Color ColorProfile\&.BlockColors\&._inactive"

.PP
Definition at line \fB211\fP of file \fBColorProfile\&.cs\fP\&.
.SS "Color ColorProfile\&.BlockColors\&._inactiveOpacity"

.PP
Definition at line \fB217\fP of file \fBColorProfile\&.cs\fP\&.
.SS "Color ColorProfile\&.BlockColors\&._mapHighlight"

.PP
Definition at line \fB223\fP of file \fBColorProfile\&.cs\fP\&.
.SS "Color ColorProfile\&.BlockColors\&._passive"

.PP
Definition at line \fB220\fP of file \fBColorProfile\&.cs\fP\&.
.SS "Color ColorProfile\&.BlockColors\&._valid"

.PP
Definition at line \fB202\fP of file \fBColorProfile\&.cs\fP\&.
.SS "Color ColorProfile\&.BlockColors\&._warning"

.PP
Definition at line \fB205\fP of file \fBColorProfile\&.cs\fP\&.
.SS "int ColorProfile\&.BlockColors\&.Active"

.PP
Definition at line \fB235\fP of file \fBColorProfile\&.cs\fP\&.
.SS "int ColorProfile\&.BlockColors\&.ActiveOpacity"

.PP
Definition at line \fB238\fP of file \fBColorProfile\&.cs\fP\&.
.SS "const int ColorProfile\&.BlockColors\&.DefColor = 104025\fR [static]\fP"

.PP
Definition at line \fB187\fP of file \fBColorProfile\&.cs\fP\&.
.SS "const int ColorProfile\&.BlockColors\&.DefColorActive = \-1173751\fR [static]\fP"

.PP
Definition at line \fB193\fP of file \fBColorProfile\&.cs\fP\&.
.SS "const int ColorProfile\&.BlockColors\&.DefColorInactive = \-1214986\fR [static]\fP"

.PP
Definition at line \fB190\fP of file \fBColorProfile\&.cs\fP\&.
.SS "const int ColorProfile\&.BlockColors\&.DefColorValid = \-2747875\fR [static]\fP"

.PP
Definition at line \fB196\fP of file \fBColorProfile\&.cs\fP\&.
.SS "const int ColorProfile\&.BlockColors\&.DefColorWarning = \-2828814\fR [static]\fP"

.PP
Definition at line \fB199\fP of file \fBColorProfile\&.cs\fP\&.
.SS "int ColorProfile\&.BlockColors\&.Inactive"

.PP
Definition at line \fB232\fP of file \fBColorProfile\&.cs\fP\&.
.SS "int ColorProfile\&.BlockColors\&.InactiveOpacity"

.PP
Definition at line \fB241\fP of file \fBColorProfile\&.cs\fP\&.
.SS "int ColorProfile\&.BlockColors\&.MapHighlight"

.PP
Definition at line \fB247\fP of file \fBColorProfile\&.cs\fP\&.
.SS "int ColorProfile\&.BlockColors\&.Passive"

.PP
Definition at line \fB244\fP of file \fBColorProfile\&.cs\fP\&.
.SS "int ColorProfile\&.BlockColors\&.Valid"

.PP
Definition at line \fB226\fP of file \fBColorProfile\&.cs\fP\&.
.SS "int ColorProfile\&.BlockColors\&.Warning"

.PP
Definition at line \fB229\fP of file \fBColorProfile\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
