.TH "ConGravity" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ConGravity
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBBaseDebuff\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnRefresh\fP ()"
.br
.ti -1c
.RI "override int \fBGetPhase\fP ()"
.br
.in -1c

Public Member Functions inherited from \fBBaseDebuff\fP
.in +1c
.ti -1c
.RI "override \fBBaseNotification\fP \fBCreateNotification\fP ()"
.br
.in -1c

Public Member Functions inherited from \fBCondition\fP
.in +1c
.ti -1c
.RI "override \fBBaseNotification\fP \fBCreateNotification\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnStacked\fP (int p)"
.br
.ti -1c
.RI "\fBCondition\fP \fBSetPerfume\fP (int duration=3)"
.br
.ti -1c
.RI "override void \fBTick\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnCalculateFov\fP (\fBFov\fP fov, ref int radius, ref float power)"
.br
.ti -1c
.RI "virtual void \fBOnCreateFov\fP (\fBFov\fP fov)"
.br
.ti -1c
.RI "override void \fBOnValueChanged\fP ()"
.br
.ti -1c
.RI "void \fBKill\fP (bool silent=false)"
.br
.in -1c

Public Member Functions inherited from \fBBaseCondition\fP
.in +1c
.ti -1c
.RI "virtual bool \fBCanStack\fP (\fBCondition\fP c)"
.br
.ti -1c
.RI "virtual bool \fBTryMove\fP (\fBPoint\fP p)"
.br
.ti -1c
.RI "void \fBSetElement\fP (int id)"
.br
.ti -1c
.RI "void \fBSetRefVal\fP (int a, int b)"
.br
.ti -1c
.RI "virtual Color \fBGetSpriteColor\fP ()"
.br
.ti -1c
.RI "override string \fBToString\fP ()"
.br
.ti -1c
.RI "override string \fBGetText\fP ()"
.br
.ti -1c
.RI "override int \fBGetValue\fP ()"
.br
.ti -1c
.RI "override Color \fBGetColor\fP (Gradient g)"
.br
.ti -1c
.RI "virtual void \fBSetOwner\fP (\fBChara\fP _owner, bool onDeserialize=false)"
.br
.ti -1c
.RI "\fBSourceElement\&.Row\fP \fBGetElementSource\fP (int i)"
.br
.ti -1c
.RI "void \fBStart\fP ()"
.br
.ti -1c
.RI "bool \fBTryNullify\fP (\fBCondition\fP c)"
.br
.ti -1c
.RI "virtual void \fBOnBeforeStart\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnStart\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnStartOrStack\fP ()"
.br
.ti -1c
.RI "virtual void \fBPlayEffect\fP ()"
.br
.ti -1c
.RI "virtual void \fBPlayEndEffect\fP ()"
.br
.ti -1c
.RI "void \fBSetPhase\fP ()"
.br
.ti -1c
.RI "bool \fBIsNullPhase\fP ()"
.br
.ti -1c
.RI "void \fBPhaseMsg\fP (bool inc)"
.br
.ti -1c
.RI "override string \fBGetPhaseStr\fP ()"
.br
.ti -1c
.RI "void \fBMod\fP (int a, bool force=false)"
.br
.ti -1c
.RI "virtual void \fBOnChangePhase\fP (int lastPhase, int newPhase)"
.br
.ti -1c
.RI "virtual void \fBOnRemoved\fP ()"
.br
.ti -1c
.RI "virtual int \fBEvaluatePower\fP (int p)"
.br
.ti -1c
.RI "virtual int \fBEvaluateTurn\fP (int p)"
.br
.ti -1c
.RI "\fBElement\fP \fBGetDefenseAttribute\fP (\fBChara\fP c=null)"
.br
.ti -1c
.RI "override void \fB_WriteNote\fP (UINote n, bool asChild=false)"
.br
.ti -1c
.RI "virtual void \fBOnWriteNote\fP (List< string > list)"
.br
.ti -1c
.RI "virtual \fBRendererReplacer\fP \fBGetRendererReplacer\fP ()"
.br
.in -1c

Public Member Functions inherited from \fBBaseStats\fP
.in +1c
.ti -1c
.RI "virtual Color \fBGetColor\fP (SkinColorProfile c)"
.br
.ti -1c
.RI "Color \fBGetColor\fP ()"
.br
.ti -1c
.RI "virtual Sprite \fBGetSprite\fP ()"
.br
.ti -1c
.RI "virtual void \fBSetText\fP (UIText t, SkinColorProfile cols=null)"
.br
.ti -1c
.RI "void \fBPopText\fP ()"
.br
.ti -1c
.RI "virtual void \fBWriteNote\fP (UINote n, Action< UINote > onWriteNote=null)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override bool \fBShouldRefresh\fP\fR [get]\fP"
.br
.in -1c

Properties inherited from \fBBaseDebuff\fP
.in +1c
.ti -1c
.RI "override bool \fBWillOverride\fP\fR [get]\fP"
.br
.in -1c

Properties inherited from \fBCondition\fP
.in +1c
.ti -1c
.RI "virtual bool \fBIsKilled\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual string \fBTextDuration\fP\fR [get]\fP"
.br
.in -1c

Properties inherited from \fBBaseCondition\fP
.in +1c
.ti -1c
.RI "int \fBvalue\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "int \fBpower\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "int \fBrefVal\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "int \fBrefVal2\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "bool \fBgivenByPcParty\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "bool \fBisPerfume\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "override \fBChara\fP \fBOwner\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual string \fBName\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBIsToggle\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBWillOverride\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBAllowMultipleInstance\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBConsumeTurn\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBPreventRegen\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBShouldRefresh\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBCancelAI\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBTimeBased\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBSyncRide\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual int \fBGainResistFactor\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual int \fBP2\fP\fR [get]\fP"
.br
.ti -1c
.RI "\fBSourceElement\&.Row\fP \fBsourceElement\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBIsElemental\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual string \fBRefString1\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBCanManualRemove\fP\fR [get]\fP"
.br
.in -1c

Properties inherited from \fBBaseStats\fP
.in +1c
.ti -1c
.RI "\fBSourceStat\&.Row\fP \fBsource\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual Emo2 \fBEmoIcon\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual ConditionType \fBType\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual string \fBidSprite\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBShowInWidget\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual \fBChara\fP \fBOwner\fP\fR [get]\fP"
.br
.in -1c

Properties inherited from \fBEClass\fP
.in +1c
.ti -1c
.RI "static \fBGame\fP \fBgame\fP\fR [get]\fP"
.br
.ti -1c
.RI "static bool \fBAdvMode\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBPlayer\fP \fBplayer\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBChara\fP \fBpc\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBUI\fP \fBui\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBMap\fP \fB_map\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBZone\fP \fB_zone\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranchOrHomeBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFaction\fP \fBHome\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFaction\fP \fBWilds\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBScene\fP \fBscene\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBBaseGameScreen\fP \fBscreen\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameSetting\fP \fBsetting\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameData\fP \fBgamedata\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBColorProfile\fP \fBColors\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBWorld\fP \fBworld\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBsources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBeditorSources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static SoundManager \fBSound\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBCoreDebug\fP \fBdebug\fP\fR [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Static Public Member Functions inherited from \fBCondition\fP
.in +1c
.ti -1c
.RI "static T \fBCreate< T >\fP (int power=100, Action< T > onCreate=null)"
.br
.ti -1c
.RI "static \fBCondition\fP \fBCreate\fP (string alias, int power=100, Action< \fBCondition\fP > onCreate=null)"
.br
.in -1c

Static Public Member Functions inherited from \fBEClass\fP
.in +1c
.ti -1c
.RI "static int \fBrnd\fP (int a)"
.br
.ti -1c
.RI "static int \fBcurve\fP (int a, int start, int step, int rate=75)"
.br
.ti -1c
.RI "static int \fBrndHalf\fP (int a)"
.br
.ti -1c
.RI "static float \fBrndf\fP (float a)"
.br
.ti -1c
.RI "static int \fBrndSqrt\fP (int a)"
.br
.ti -1c
.RI "static void \fBWait\fP (float a, \fBCard\fP c)"
.br
.ti -1c
.RI "static void \fBWait\fP (float a, \fBPoint\fP p)"
.br
.ti -1c
.RI "static int \fBBigger\fP (int a, int b)"
.br
.ti -1c
.RI "static int \fBSmaller\fP (int a, int b)"
.br
.in -1c

Public Attributes inherited from \fBBaseCondition\fP
.in +1c
.ti -1c
.RI "int[] \fB_ints\fP = new int[5]"
.br
.ti -1c
.RI "int \fBphase\fP = \-1"
.br
.ti -1c
.RI "\fBElementContainer\fP \fBelements\fP"
.br
.ti -1c
.RI "\fBChara\fP \fBowner\fP"
.br
.in -1c

Public Attributes inherited from \fBBaseStats\fP
.in +1c
.ti -1c
.RI "int \fBid\fP"
.br
.ti -1c
.RI "\fBSourceStat\&.Row\fP \fB_source\fP"
.br
.in -1c

Static Public Attributes inherited from \fBCondition\fP
.in +1c
.ti -1c
.RI "static bool \fBignoreEffect\fP"
.br
.in -1c

Static Public Attributes inherited from \fBBaseStats\fP
.in +1c
.ti -1c
.RI "static \fBChara\fP \fBCC\fP"
.br
.in -1c

Static Public Attributes inherited from \fBEClass\fP
.in +1c
.ti -1c
.RI "static \fBCore\fP \fBcore\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB4\fP of file \fBConGravity\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override int ConGravity\&.GetPhase ()\fR [virtual]\fP"

.PP
Reimplemented from \fBBaseDebuff\fP\&.
.PP
Definition at line \fB27\fP of file \fBConGravity\&.cs\fP\&.
.SS "override void ConGravity\&.OnRefresh ()\fR [virtual]\fP"

.PP
Reimplemented from \fBBaseCondition\fP\&.
.PP
Definition at line \fB17\fP of file \fBConGravity\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "override bool ConGravity\&.ShouldRefresh\fR [get]\fP"

.PP
Definition at line \fB8\fP of file \fBConGravity\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
