.TH "ContentPopulation.Topic" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ContentPopulation.Topic
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBheader\fP"
.br
.ti -1c
.RI "List< \fBChara\fP > \fBlist\fP = new List<\fBChara\fP>()"
.br
.ti -1c
.RI "int \fBcolor\fP"
.br
.ti -1c
.RI "int \fBsortVal\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB166\fP of file \fBContentPopulation\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int ContentPopulation\&.Topic\&.color"

.PP
Definition at line \fB175\fP of file \fBContentPopulation\&.cs\fP\&.
.SS "string ContentPopulation\&.Topic\&.header"

.PP
Definition at line \fB169\fP of file \fBContentPopulation\&.cs\fP\&.
.SS "List<\fBChara\fP> ContentPopulation\&.Topic\&.list = new List<\fBChara\fP>()"

.PP
Definition at line \fB172\fP of file \fBContentPopulation\&.cs\fP\&.
.SS "int ContentPopulation\&.Topic\&.sortVal"

.PP
Definition at line \fB178\fP of file \fBContentPopulation\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
