.TH "ContentConfigGeneral" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ContentConfigGeneral
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBContentConfig\fP\&.
.SS "Additional Inherited Members"


Public Member Functions inherited from \fBContentConfig\fP
.in +1c
.ti -1c
.RI "void \fBSetSlider\fP (Slider slider, float value, Func< float, string > action)"
.br
.in -1c

Properties inherited from \fBContentConfig\fP
.in +1c
.ti -1c
.RI "\fBCoreConfig\fP \fBconfig\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB4\fP of file \fBContentConfigGeneral\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
