.TH "ContentGallery" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ContentGallery
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBEContent\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPage\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnSwitchContent\fP (int idTab)"
.br
.ti -1c
.RI "void \fBRefresh\fP ()"
.br
.ti -1c
.RI "void \fBOnClickHelp\fP ()"
.br
.ti -1c
.RI "void \fBToggleMode\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Transform \fBtransBig\fP"
.br
.ti -1c
.RI "Image \fBimageBig\fP"
.br
.ti -1c
.RI "UIBook \fBbook\fP"
.br
.ti -1c
.RI "UIText \fBtextCollected\fP"
.br
.ti -1c
.RI "GridLayoutGroup[] \fBgrids\fP"
.br
.ti -1c
.RI "Vector2[] \fBgridSize\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static int \fBlastPage\fP"
.br
.ti -1c
.RI "static bool \fBlistMode\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB8\fP of file \fBContentGallery\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void ContentGallery\&.OnClickHelp ()"

.PP
Definition at line \fB60\fP of file \fBContentGallery\&.cs\fP\&.
.SS "override void ContentGallery\&.OnSwitchContent (int idTab)"

.PP
Definition at line \fB11\fP of file \fBContentGallery\&.cs\fP\&.
.SS "void ContentGallery\&.Refresh ()"

.PP
Definition at line \fB30\fP of file \fBContentGallery\&.cs\fP\&.
.SS "void ContentGallery\&.ToggleMode ()"

.PP
Definition at line \fB66\fP of file \fBContentGallery\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "UIBook ContentGallery\&.book"

.PP
Definition at line \fB93\fP of file \fBContentGallery\&.cs\fP\&.
.SS "GridLayoutGroup [] ContentGallery\&.grids"

.PP
Definition at line \fB99\fP of file \fBContentGallery\&.cs\fP\&.
.SS "Vector2 [] ContentGallery\&.gridSize"

.PP
Definition at line \fB102\fP of file \fBContentGallery\&.cs\fP\&.
.SS "Image ContentGallery\&.imageBig"

.PP
Definition at line \fB90\fP of file \fBContentGallery\&.cs\fP\&.
.SS "int ContentGallery\&.lastPage\fR [static]\fP"

.PP
Definition at line \fB81\fP of file \fBContentGallery\&.cs\fP\&.
.SS "bool ContentGallery\&.listMode\fR [static]\fP"

.PP
Definition at line \fB84\fP of file \fBContentGallery\&.cs\fP\&.
.SS "UIText ContentGallery\&.textCollected"

.PP
Definition at line \fB96\fP of file \fBContentGallery\&.cs\fP\&.
.SS "Transform ContentGallery\&.transBig"

.PP
Definition at line \fB87\fP of file \fBContentGallery\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
