.TH "ContentConfigGame" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ContentConfigGame
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBContentConfig\fP\&.
.PP
Inherited by \fBContentConfigInput\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnInstantiate\fP ()"
.br
.ti -1c
.RI "void \fBSetGroup\fP (UISelectableGroup group, int value, UnityAction< int > action)"
.br
.in -1c

Public Member Functions inherited from \fBContentConfig\fP
.in +1c
.ti -1c
.RI "void \fBSetSlider\fP (Slider slider, float value, Func< float, string > action)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "UIButton \fBtoggleFogBounds\fP"
.br
.ti -1c
.RI "UIButton \fBtoggleOffhand\fP"
.br
.ti -1c
.RI "UIButton \fBtoggleShowInvBG\fP"
.br
.ti -1c
.RI "UIButton \fBtoggleConfirmGive\fP"
.br
.ti -1c
.RI "UIButton \fBtoggleWarnCrime\fP"
.br
.ti -1c
.RI "UIButton \fBtoggleWarnMana\fP"
.br
.ti -1c
.RI "UIButton \fBtoggleWarnDisassemble\fP"
.br
.ti -1c
.RI "UIButton \fBtoggleHoldMiddle\fP"
.br
.ti -1c
.RI "UIButton \fBtoggleHoldDoubleClick\fP"
.br
.ti -1c
.RI "UIButton \fBtoggleConfirmExit\fP"
.br
.ti -1c
.RI "UIButton \fBtoggleUseAbilityOnHotkey\fP"
.br
.ti -1c
.RI "UIButton \fBtoggleHideWeapon\fP"
.br
.ti -1c
.RI "UIButton \fBtoggleNetSend\fP"
.br
.ti -1c
.RI "UIButton \fBtoggleNet\fP"
.br
.ti -1c
.RI "UIButton \fBtoggleDisableAutoStairs\fP"
.br
.ti -1c
.RI "UIButton \fBtoggleSmoothPick\fP"
.br
.ti -1c
.RI "UIButton \fBtoggleMarkStack\fP"
.br
.ti -1c
.RI "UIButton \fBtoggleRefIcon\fP"
.br
.ti -1c
.RI "UIButton \fBtoggleBackupOnFirstSave\fP"
.br
.ti -1c
.RI "UIButton \fBtoggleShippingResult\fP"
.br
.ti -1c
.RI "UIButton \fBtoggleShiftToUseNegativeAbility\fP"
.br
.ti -1c
.RI "UISelectableGroup \fBgroupBackerFilter\fP"
.br
.ti -1c
.RI "UISelectableGroup \fBgroupBorder\fP"
.br
.ti -1c
.RI "UISelectableGroup \fBgroupRide\fP"
.br
.ti -1c
.RI "Slider \fBsliderWait\fP"
.br
.ti -1c
.RI "UIButton \fBtoggleWaitOnDebuff\fP"
.br
.ti -1c
.RI "UIButton \fBtoggleWaitOnRange\fP"
.br
.ti -1c
.RI "UIButton \fBtoggleWaitOnMelee\fP"
.br
.ti -1c
.RI "UIButton \fBtoggleTutorial\fP"
.br
.ti -1c
.RI "UIButton \fBtoggleAdvanceMenu\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Properties inherited from \fBContentConfig\fP
.in +1c
.ti -1c
.RI "\fBCoreConfig\fP \fBconfig\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB6\fP of file \fBContentConfigGame\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void ContentConfigGame\&.OnInstantiate ()"

.PP
Definition at line \fB9\fP of file \fBContentConfigGame\&.cs\fP\&.
.SS "void ContentConfigGame\&.SetGroup (UISelectableGroup group, int value, UnityAction< int > action)"

.PP
Definition at line \fB131\fP of file \fBContentConfigGame\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "UISelectableGroup ContentConfigGame\&.groupBackerFilter"

.PP
Definition at line \fB200\fP of file \fBContentConfigGame\&.cs\fP\&.
.SS "UISelectableGroup ContentConfigGame\&.groupBorder"

.PP
Definition at line \fB203\fP of file \fBContentConfigGame\&.cs\fP\&.
.SS "UISelectableGroup ContentConfigGame\&.groupRide"

.PP
Definition at line \fB206\fP of file \fBContentConfigGame\&.cs\fP\&.
.SS "Slider ContentConfigGame\&.sliderWait"

.PP
Definition at line \fB209\fP of file \fBContentConfigGame\&.cs\fP\&.
.SS "UIButton ContentConfigGame\&.toggleAdvanceMenu"

.PP
Definition at line \fB224\fP of file \fBContentConfigGame\&.cs\fP\&.
.SS "UIButton ContentConfigGame\&.toggleBackupOnFirstSave"

.PP
Definition at line \fB191\fP of file \fBContentConfigGame\&.cs\fP\&.
.SS "UIButton ContentConfigGame\&.toggleConfirmExit"

.PP
Definition at line \fB164\fP of file \fBContentConfigGame\&.cs\fP\&.
.SS "UIButton ContentConfigGame\&.toggleConfirmGive"

.PP
Definition at line \fB146\fP of file \fBContentConfigGame\&.cs\fP\&.
.SS "UIButton ContentConfigGame\&.toggleDisableAutoStairs"

.PP
Definition at line \fB179\fP of file \fBContentConfigGame\&.cs\fP\&.
.SS "UIButton ContentConfigGame\&.toggleFogBounds"

.PP
Definition at line \fB137\fP of file \fBContentConfigGame\&.cs\fP\&.
.SS "UIButton ContentConfigGame\&.toggleHideWeapon"

.PP
Definition at line \fB170\fP of file \fBContentConfigGame\&.cs\fP\&.
.SS "UIButton ContentConfigGame\&.toggleHoldDoubleClick"

.PP
Definition at line \fB161\fP of file \fBContentConfigGame\&.cs\fP\&.
.SS "UIButton ContentConfigGame\&.toggleHoldMiddle"

.PP
Definition at line \fB158\fP of file \fBContentConfigGame\&.cs\fP\&.
.SS "UIButton ContentConfigGame\&.toggleMarkStack"

.PP
Definition at line \fB185\fP of file \fBContentConfigGame\&.cs\fP\&.
.SS "UIButton ContentConfigGame\&.toggleNet"

.PP
Definition at line \fB176\fP of file \fBContentConfigGame\&.cs\fP\&.
.SS "UIButton ContentConfigGame\&.toggleNetSend"

.PP
Definition at line \fB173\fP of file \fBContentConfigGame\&.cs\fP\&.
.SS "UIButton ContentConfigGame\&.toggleOffhand"

.PP
Definition at line \fB140\fP of file \fBContentConfigGame\&.cs\fP\&.
.SS "UIButton ContentConfigGame\&.toggleRefIcon"

.PP
Definition at line \fB188\fP of file \fBContentConfigGame\&.cs\fP\&.
.SS "UIButton ContentConfigGame\&.toggleShiftToUseNegativeAbility"

.PP
Definition at line \fB197\fP of file \fBContentConfigGame\&.cs\fP\&.
.SS "UIButton ContentConfigGame\&.toggleShippingResult"

.PP
Definition at line \fB194\fP of file \fBContentConfigGame\&.cs\fP\&.
.SS "UIButton ContentConfigGame\&.toggleShowInvBG"

.PP
Definition at line \fB143\fP of file \fBContentConfigGame\&.cs\fP\&.
.SS "UIButton ContentConfigGame\&.toggleSmoothPick"

.PP
Definition at line \fB182\fP of file \fBContentConfigGame\&.cs\fP\&.
.SS "UIButton ContentConfigGame\&.toggleTutorial"

.PP
Definition at line \fB221\fP of file \fBContentConfigGame\&.cs\fP\&.
.SS "UIButton ContentConfigGame\&.toggleUseAbilityOnHotkey"

.PP
Definition at line \fB167\fP of file \fBContentConfigGame\&.cs\fP\&.
.SS "UIButton ContentConfigGame\&.toggleWaitOnDebuff"

.PP
Definition at line \fB212\fP of file \fBContentConfigGame\&.cs\fP\&.
.SS "UIButton ContentConfigGame\&.toggleWaitOnMelee"

.PP
Definition at line \fB218\fP of file \fBContentConfigGame\&.cs\fP\&.
.SS "UIButton ContentConfigGame\&.toggleWaitOnRange"

.PP
Definition at line \fB215\fP of file \fBContentConfigGame\&.cs\fP\&.
.SS "UIButton ContentConfigGame\&.toggleWarnCrime"

.PP
Definition at line \fB149\fP of file \fBContentConfigGame\&.cs\fP\&.
.SS "UIButton ContentConfigGame\&.toggleWarnDisassemble"

.PP
Definition at line \fB155\fP of file \fBContentConfigGame\&.cs\fP\&.
.SS "UIButton ContentConfigGame\&.toggleWarnMana"

.PP
Definition at line \fB152\fP of file \fBContentConfigGame\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
