.TH "ContentHallOfFame" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ContentHallOfFame
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBEContent\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnSwitchContent\fP (int idTab)"
.br
.ti -1c
.RI "void \fBRefresh\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "UIText \fBtextElapsedTime\fP"
.br
.ti -1c
.RI "UIText \fBtextGamneTime\fP"
.br
.ti -1c
.RI "UIText \fBtextKilled\fP"
.br
.ti -1c
.RI "UIText \fBtextMined\fP"
.br
.ti -1c
.RI "UIText \fBtextTax\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB4\fP of file \fBContentHallOfFame\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void ContentHallOfFame\&.OnSwitchContent (int idTab)"

.PP
Definition at line \fB19\fP of file \fBContentHallOfFame\&.cs\fP\&.
.SS "void ContentHallOfFame\&.Refresh ()"

.PP
Definition at line \fB28\fP of file \fBContentHallOfFame\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "UIText ContentHallOfFame\&.textElapsedTime"

.PP
Definition at line \fB38\fP of file \fBContentHallOfFame\&.cs\fP\&.
.SS "UIText ContentHallOfFame\&.textGamneTime"

.PP
Definition at line \fB41\fP of file \fBContentHallOfFame\&.cs\fP\&.
.SS "UIText ContentHallOfFame\&.textKilled"

.PP
Definition at line \fB44\fP of file \fBContentHallOfFame\&.cs\fP\&.
.SS "UIText ContentHallOfFame\&.textMined"

.PP
Definition at line \fB47\fP of file \fBContentHallOfFame\&.cs\fP\&.
.SS "UIText ContentHallOfFame\&.textTax"

.PP
Definition at line \fB50\fP of file \fBContentHallOfFame\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
