.TH "ContentConfigInput" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ContentConfigInput
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBContentConfigGame\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnInstantiate\fP ()"
.br
.in -1c

Public Member Functions inherited from \fBContentConfigGame\fP
.in +1c
.ti -1c
.RI "override void \fBOnInstantiate\fP ()"
.br
.ti -1c
.RI "void \fBSetGroup\fP (UISelectableGroup group, int value, UnityAction< int > action)"
.br
.in -1c

Public Member Functions inherited from \fBContentConfig\fP
.in +1c
.ti -1c
.RI "void \fBSetSlider\fP (Slider slider, float value, Func< float, string > action)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "UIList \fBlistMovement\fP"
.br
.ti -1c
.RI "UIList \fBlistGeneral\fP"
.br
.ti -1c
.RI "UIList \fBlistMenu\fP"
.br
.ti -1c
.RI "UIList \fBlistEtc\fP"
.br
.ti -1c
.RI "UIList \fBlistAdvanced\fP"
.br
.ti -1c
.RI "UIButton \fBtoggleAutorun\fP"
.br
.ti -1c
.RI "UIButton \fBtoggleAltKeyAxis\fP"
.br
.ti -1c
.RI "UIButton \fBtoggleKeepRunning\fP"
.br
.ti -1c
.RI "UIButton \fBtoggleRightClickExitBuildMode\fP"
.br
.ti -1c
.RI "UIButton \fBtoggleIgnoreNPCs\fP"
.br
.ti -1c
.RI "UIButton \fBtoggleAltExamine\fP"
.br
.ti -1c
.RI "UIButton \fBtoggleZoomToMouse\fP"
.br
.ti -1c
.RI "UIButton \fBtoggleZoomMin\fP"
.br
.ti -1c
.RI "UIButton \fBtoggleZoomMax\fP"
.br
.ti -1c
.RI "UIButton \fBtoggleSmoothFollow\fP"
.br
.ti -1c
.RI "UIButton \fBtoggleSmoothMove\fP"
.br
.ti -1c
.RI "Slider \fBsliderKeyboardScroll\fP"
.br
.ti -1c
.RI "Slider \fBsliderDragScroll\fP"
.br
.ti -1c
.RI "Slider \fBsliderEdgeScroll\fP"
.br
.ti -1c
.RI "Slider \fBsliderRunDistance\fP"
.br
.ti -1c
.RI "Slider \fBsliderMoveFrame\fP"
.br
.ti -1c
.RI "UIButton \fBtoggleEdge\fP"
.br
.ti -1c
.RI "UIButton \fBtoggleInvertX\fP"
.br
.ti -1c
.RI "UIButton \fBtoggleInvertY\fP"
.br
.ti -1c
.RI "UIButton \fBtoggleLinearZoom\fP"
.br
.ti -1c
.RI "UIDropdown \fBddMiddleClick\fP"
.br
.ti -1c
.RI "UIDropdown \fBddMiddleClickLong\fP"
.br
.ti -1c
.RI "UIDropdown \fBddMouse3Click\fP"
.br
.ti -1c
.RI "UIDropdown \fBddMouse3Long\fP"
.br
.ti -1c
.RI "UIDropdown \fBddMouse4Click\fP"
.br
.ti -1c
.RI "UIDropdown \fBddMouse4Long\fP"
.br
.ti -1c
.RI "UIDropdown \fBb_ddMiddleClick\fP"
.br
.ti -1c
.RI "UIDropdown \fBb_ddMiddleClickLong\fP"
.br
.ti -1c
.RI "UIDropdown \fBb_ddMouse3Click\fP"
.br
.ti -1c
.RI "UIDropdown \fBb_ddMouse3Long\fP"
.br
.ti -1c
.RI "UIDropdown \fBb_ddMouse4Click\fP"
.br
.ti -1c
.RI "UIDropdown \fBb_ddMouse4Long\fP"
.br
.in -1c

Public Attributes inherited from \fBContentConfigGame\fP
.in +1c
.ti -1c
.RI "UIButton \fBtoggleFogBounds\fP"
.br
.ti -1c
.RI "UIButton \fBtoggleOffhand\fP"
.br
.ti -1c
.RI "UIButton \fBtoggleShowInvBG\fP"
.br
.ti -1c
.RI "UIButton \fBtoggleConfirmGive\fP"
.br
.ti -1c
.RI "UIButton \fBtoggleWarnCrime\fP"
.br
.ti -1c
.RI "UIButton \fBtoggleWarnMana\fP"
.br
.ti -1c
.RI "UIButton \fBtoggleWarnDisassemble\fP"
.br
.ti -1c
.RI "UIButton \fBtoggleHoldMiddle\fP"
.br
.ti -1c
.RI "UIButton \fBtoggleHoldDoubleClick\fP"
.br
.ti -1c
.RI "UIButton \fBtoggleConfirmExit\fP"
.br
.ti -1c
.RI "UIButton \fBtoggleUseAbilityOnHotkey\fP"
.br
.ti -1c
.RI "UIButton \fBtoggleHideWeapon\fP"
.br
.ti -1c
.RI "UIButton \fBtoggleNetSend\fP"
.br
.ti -1c
.RI "UIButton \fBtoggleNet\fP"
.br
.ti -1c
.RI "UIButton \fBtoggleDisableAutoStairs\fP"
.br
.ti -1c
.RI "UIButton \fBtoggleSmoothPick\fP"
.br
.ti -1c
.RI "UIButton \fBtoggleMarkStack\fP"
.br
.ti -1c
.RI "UIButton \fBtoggleRefIcon\fP"
.br
.ti -1c
.RI "UIButton \fBtoggleBackupOnFirstSave\fP"
.br
.ti -1c
.RI "UIButton \fBtoggleShippingResult\fP"
.br
.ti -1c
.RI "UIButton \fBtoggleShiftToUseNegativeAbility\fP"
.br
.ti -1c
.RI "UISelectableGroup \fBgroupBackerFilter\fP"
.br
.ti -1c
.RI "UISelectableGroup \fBgroupBorder\fP"
.br
.ti -1c
.RI "UISelectableGroup \fBgroupRide\fP"
.br
.ti -1c
.RI "Slider \fBsliderWait\fP"
.br
.ti -1c
.RI "UIButton \fBtoggleWaitOnDebuff\fP"
.br
.ti -1c
.RI "UIButton \fBtoggleWaitOnRange\fP"
.br
.ti -1c
.RI "UIButton \fBtoggleWaitOnMelee\fP"
.br
.ti -1c
.RI "UIButton \fBtoggleTutorial\fP"
.br
.ti -1c
.RI "UIButton \fBtoggleAdvanceMenu\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Properties inherited from \fBContentConfig\fP
.in +1c
.ti -1c
.RI "\fBCoreConfig\fP \fBconfig\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB7\fP of file \fBContentConfigInput\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void ContentConfigInput\&.OnInstantiate ()"

.PP
Definition at line \fB10\fP of file \fBContentConfigInput\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "UIDropdown ContentConfigInput\&.b_ddMiddleClick"

.PP
Definition at line \fB350\fP of file \fBContentConfigInput\&.cs\fP\&.
.SS "UIDropdown ContentConfigInput\&.b_ddMiddleClickLong"

.PP
Definition at line \fB353\fP of file \fBContentConfigInput\&.cs\fP\&.
.SS "UIDropdown ContentConfigInput\&.b_ddMouse3Click"

.PP
Definition at line \fB356\fP of file \fBContentConfigInput\&.cs\fP\&.
.SS "UIDropdown ContentConfigInput\&.b_ddMouse3Long"

.PP
Definition at line \fB359\fP of file \fBContentConfigInput\&.cs\fP\&.
.SS "UIDropdown ContentConfigInput\&.b_ddMouse4Click"

.PP
Definition at line \fB362\fP of file \fBContentConfigInput\&.cs\fP\&.
.SS "UIDropdown ContentConfigInput\&.b_ddMouse4Long"

.PP
Definition at line \fB365\fP of file \fBContentConfigInput\&.cs\fP\&.
.SS "UIDropdown ContentConfigInput\&.ddMiddleClick"

.PP
Definition at line \fB332\fP of file \fBContentConfigInput\&.cs\fP\&.
.SS "UIDropdown ContentConfigInput\&.ddMiddleClickLong"

.PP
Definition at line \fB335\fP of file \fBContentConfigInput\&.cs\fP\&.
.SS "UIDropdown ContentConfigInput\&.ddMouse3Click"

.PP
Definition at line \fB338\fP of file \fBContentConfigInput\&.cs\fP\&.
.SS "UIDropdown ContentConfigInput\&.ddMouse3Long"

.PP
Definition at line \fB341\fP of file \fBContentConfigInput\&.cs\fP\&.
.SS "UIDropdown ContentConfigInput\&.ddMouse4Click"

.PP
Definition at line \fB344\fP of file \fBContentConfigInput\&.cs\fP\&.
.SS "UIDropdown ContentConfigInput\&.ddMouse4Long"

.PP
Definition at line \fB347\fP of file \fBContentConfigInput\&.cs\fP\&.
.SS "UIList ContentConfigInput\&.listAdvanced"

.PP
Definition at line \fB269\fP of file \fBContentConfigInput\&.cs\fP\&.
.SS "UIList ContentConfigInput\&.listEtc"

.PP
Definition at line \fB266\fP of file \fBContentConfigInput\&.cs\fP\&.
.SS "UIList ContentConfigInput\&.listGeneral"

.PP
Definition at line \fB260\fP of file \fBContentConfigInput\&.cs\fP\&.
.SS "UIList ContentConfigInput\&.listMenu"

.PP
Definition at line \fB263\fP of file \fBContentConfigInput\&.cs\fP\&.
.SS "UIList ContentConfigInput\&.listMovement"

.PP
Definition at line \fB257\fP of file \fBContentConfigInput\&.cs\fP\&.
.SS "Slider ContentConfigInput\&.sliderDragScroll"

.PP
Definition at line \fB308\fP of file \fBContentConfigInput\&.cs\fP\&.
.SS "Slider ContentConfigInput\&.sliderEdgeScroll"

.PP
Definition at line \fB311\fP of file \fBContentConfigInput\&.cs\fP\&.
.SS "Slider ContentConfigInput\&.sliderKeyboardScroll"

.PP
Definition at line \fB305\fP of file \fBContentConfigInput\&.cs\fP\&.
.SS "Slider ContentConfigInput\&.sliderMoveFrame"

.PP
Definition at line \fB317\fP of file \fBContentConfigInput\&.cs\fP\&.
.SS "Slider ContentConfigInput\&.sliderRunDistance"

.PP
Definition at line \fB314\fP of file \fBContentConfigInput\&.cs\fP\&.
.SS "UIButton ContentConfigInput\&.toggleAltExamine"

.PP
Definition at line \fB287\fP of file \fBContentConfigInput\&.cs\fP\&.
.SS "UIButton ContentConfigInput\&.toggleAltKeyAxis"

.PP
Definition at line \fB275\fP of file \fBContentConfigInput\&.cs\fP\&.
.SS "UIButton ContentConfigInput\&.toggleAutorun"

.PP
Definition at line \fB272\fP of file \fBContentConfigInput\&.cs\fP\&.
.SS "UIButton ContentConfigInput\&.toggleEdge"

.PP
Definition at line \fB320\fP of file \fBContentConfigInput\&.cs\fP\&.
.SS "UIButton ContentConfigInput\&.toggleIgnoreNPCs"

.PP
Definition at line \fB284\fP of file \fBContentConfigInput\&.cs\fP\&.
.SS "UIButton ContentConfigInput\&.toggleInvertX"

.PP
Definition at line \fB323\fP of file \fBContentConfigInput\&.cs\fP\&.
.SS "UIButton ContentConfigInput\&.toggleInvertY"

.PP
Definition at line \fB326\fP of file \fBContentConfigInput\&.cs\fP\&.
.SS "UIButton ContentConfigInput\&.toggleKeepRunning"

.PP
Definition at line \fB278\fP of file \fBContentConfigInput\&.cs\fP\&.
.SS "UIButton ContentConfigInput\&.toggleLinearZoom"

.PP
Definition at line \fB329\fP of file \fBContentConfigInput\&.cs\fP\&.
.SS "UIButton ContentConfigInput\&.toggleRightClickExitBuildMode"

.PP
Definition at line \fB281\fP of file \fBContentConfigInput\&.cs\fP\&.
.SS "UIButton ContentConfigInput\&.toggleSmoothFollow"

.PP
Definition at line \fB299\fP of file \fBContentConfigInput\&.cs\fP\&.
.SS "UIButton ContentConfigInput\&.toggleSmoothMove"

.PP
Definition at line \fB302\fP of file \fBContentConfigInput\&.cs\fP\&.
.SS "UIButton ContentConfigInput\&.toggleZoomMax"

.PP
Definition at line \fB296\fP of file \fBContentConfigInput\&.cs\fP\&.
.SS "UIButton ContentConfigInput\&.toggleZoomMin"

.PP
Definition at line \fB293\fP of file \fBContentConfigInput\&.cs\fP\&.
.SS "UIButton ContentConfigInput\&.toggleZoomToMouse"

.PP
Definition at line \fB290\fP of file \fBContentConfigInput\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
