.TH "ContentRanking" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ContentRanking
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBEContent\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnSwitchContent\fP (int idTab)"
.br
.ti -1c
.RI "void \fBSwitchRanking\fP (string id)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "UIList \fBlist\fP"
.br
.ti -1c
.RI "UIText \fBtextTitle\fP"
.br
.ti -1c
.RI "UIText \fBtextFactionName\fP"
.br
.ti -1c
.RI "Sprite[] \fBspriteTrophies\fP"
.br
.ti -1c
.RI "GameObject \fBcomingSoon\fP"
.br
.ti -1c
.RI "GameObject \fBwet\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB5\fP of file \fBContentRanking\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void ContentRanking\&.OnSwitchContent (int idTab)"

.PP
Definition at line \fB8\fP of file \fBContentRanking\&.cs\fP\&.
.SS "void ContentRanking\&.SwitchRanking (string id)"

.PP
Definition at line \fB14\fP of file \fBContentRanking\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "GameObject ContentRanking\&.comingSoon"

.PP
Definition at line \fB124\fP of file \fBContentRanking\&.cs\fP\&.
.SS "UIList ContentRanking\&.list"

.PP
Definition at line \fB112\fP of file \fBContentRanking\&.cs\fP\&.
.SS "Sprite [] ContentRanking\&.spriteTrophies"

.PP
Definition at line \fB121\fP of file \fBContentRanking\&.cs\fP\&.
.SS "UIText ContentRanking\&.textFactionName"

.PP
Definition at line \fB118\fP of file \fBContentRanking\&.cs\fP\&.
.SS "UIText ContentRanking\&.textTitle"

.PP
Definition at line \fB115\fP of file \fBContentRanking\&.cs\fP\&.
.SS "GameObject ContentRanking\&.wet"

.PP
Definition at line \fB127\fP of file \fBContentRanking\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
