.TH "ContentPolicy" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ContentPolicy
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBEContent\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnSwitchContent\fP (int idTab)"
.br
.ti -1c
.RI "void \fBRefreshPolicy\fP ()"
.br
.ti -1c
.RI "void \fBRefreshPolicyList\fP (UIList list, string cat, string plan)"
.br
.ti -1c
.RI "void \fBRefreshPolicyIcons\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "UIList \fBlistPolicyLaw\fP"
.br
.ti -1c
.RI "UIList \fBlistPolicyEconomy\fP"
.br
.ti -1c
.RI "UIList \fBlistPolicyLife\fP"
.br
.ti -1c
.RI "UIList \fBlistUtility\fP"
.br
.ti -1c
.RI "Material \fBmatGrayscale\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB8\fP of file \fBContentPolicy\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void ContentPolicy\&.OnSwitchContent (int idTab)"

.PP
Definition at line \fB11\fP of file \fBContentPolicy\&.cs\fP\&.
.SS "void ContentPolicy\&.RefreshPolicy ()"

.PP
Definition at line \fB18\fP of file \fBContentPolicy\&.cs\fP\&.
.SS "void ContentPolicy\&.RefreshPolicyIcons ()"

.PP
Definition at line \fB101\fP of file \fBContentPolicy\&.cs\fP\&.
.SS "void ContentPolicy\&.RefreshPolicyList (UIList list, string cat, string plan)"

.PP
Definition at line \fB31\fP of file \fBContentPolicy\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "UIList ContentPolicy\&.listPolicyEconomy"

.PP
Definition at line \fB134\fP of file \fBContentPolicy\&.cs\fP\&.
.SS "UIList ContentPolicy\&.listPolicyLaw"

.PP
Definition at line \fB131\fP of file \fBContentPolicy\&.cs\fP\&.
.SS "UIList ContentPolicy\&.listPolicyLife"

.PP
Definition at line \fB137\fP of file \fBContentPolicy\&.cs\fP\&.
.SS "UIList ContentPolicy\&.listUtility"

.PP
Definition at line \fB140\fP of file \fBContentPolicy\&.cs\fP\&.
.SS "Material ContentPolicy\&.matGrayscale"

.PP
Definition at line \fB143\fP of file \fBContentPolicy\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
