.TH "ContentConfigOther" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ContentConfigOther
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBContentConfig\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnInstantiate\fP ()"
.br
.ti -1c
.RI "void \fBOpenLog\fP ()"
.br
.ti -1c
.RI "void \fBOoenConfigFolder\fP ()"
.br
.ti -1c
.RI "void \fBOpenPackage\fP ()"
.br
.ti -1c
.RI "void \fBOpenUser\fP ()"
.br
.ti -1c
.RI "void \fBResetWindows\fP ()"
.br
.ti -1c
.RI "void \fBOpenBackerCodeInput\fP ()"
.br
.ti -1c
.RI "void \fBRefreshRewardCode\fP ()"
.br
.in -1c

Public Member Functions inherited from \fBContentConfig\fP
.in +1c
.ti -1c
.RI "void \fBSetSlider\fP (Slider slider, float value, Func< float, string > action)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "UIButton \fBtoggleSyncMod\fP"
.br
.ti -1c
.RI "UIButton \fBtoggleNoCensor\fP"
.br
.ti -1c
.RI "UIButton \fBtoggleRunBackground\fP"
.br
.ti -1c
.RI "UIButton \fBtoggleTest\fP"
.br
.ti -1c
.RI "UIButton \fBtoggleAltInv\fP"
.br
.ti -1c
.RI "UIButton \fBtoggleAltAbility\fP"
.br
.ti -1c
.RI "UIButton \fBbuttonBackerCode\fP"
.br
.ti -1c
.RI "UIDropdown \fBddSnap\fP"
.br
.ti -1c
.RI "UIDropdown \fBddDivider\fP"
.br
.ti -1c
.RI "Slider \fBsliderMissClick\fP"
.br
.ti -1c
.RI "Slider \fBsliderBGMInterval\fP"
.br
.ti -1c
.RI "UIText \fBtextBackerCode\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Properties inherited from \fBContentConfig\fP
.in +1c
.ti -1c
.RI "\fBCoreConfig\fP \fBconfig\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB5\fP of file \fBContentConfigOther\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void ContentConfigOther\&.OnInstantiate ()"

.PP
Definition at line \fB8\fP of file \fBContentConfigOther\&.cs\fP\&.
.SS "void ContentConfigOther\&.OoenConfigFolder ()"

.PP
Definition at line \fB71\fP of file \fBContentConfigOther\&.cs\fP\&.
.SS "void ContentConfigOther\&.OpenBackerCodeInput ()"

.PP
Definition at line \fB98\fP of file \fBContentConfigOther\&.cs\fP\&.
.SS "void ContentConfigOther\&.OpenLog ()"

.PP
Definition at line \fB65\fP of file \fBContentConfigOther\&.cs\fP\&.
.SS "void ContentConfigOther\&.OpenPackage ()"

.PP
Definition at line \fB77\fP of file \fBContentConfigOther\&.cs\fP\&.
.SS "void ContentConfigOther\&.OpenUser ()"

.PP
Definition at line \fB83\fP of file \fBContentConfigOther\&.cs\fP\&.
.SS "void ContentConfigOther\&.RefreshRewardCode ()"

.PP
Definition at line \fB119\fP of file \fBContentConfigOther\&.cs\fP\&.
.SS "void ContentConfigOther\&.ResetWindows ()"

.PP
Definition at line \fB89\fP of file \fBContentConfigOther\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "UIButton ContentConfigOther\&.buttonBackerCode"

.PP
Definition at line \fB147\fP of file \fBContentConfigOther\&.cs\fP\&.
.SS "UIDropdown ContentConfigOther\&.ddDivider"

.PP
Definition at line \fB153\fP of file \fBContentConfigOther\&.cs\fP\&.
.SS "UIDropdown ContentConfigOther\&.ddSnap"

.PP
Definition at line \fB150\fP of file \fBContentConfigOther\&.cs\fP\&.
.SS "Slider ContentConfigOther\&.sliderBGMInterval"

.PP
Definition at line \fB159\fP of file \fBContentConfigOther\&.cs\fP\&.
.SS "Slider ContentConfigOther\&.sliderMissClick"

.PP
Definition at line \fB156\fP of file \fBContentConfigOther\&.cs\fP\&.
.SS "UIText ContentConfigOther\&.textBackerCode"

.PP
Definition at line \fB162\fP of file \fBContentConfigOther\&.cs\fP\&.
.SS "UIButton ContentConfigOther\&.toggleAltAbility"

.PP
Definition at line \fB144\fP of file \fBContentConfigOther\&.cs\fP\&.
.SS "UIButton ContentConfigOther\&.toggleAltInv"

.PP
Definition at line \fB141\fP of file \fBContentConfigOther\&.cs\fP\&.
.SS "UIButton ContentConfigOther\&.toggleNoCensor"

.PP
Definition at line \fB132\fP of file \fBContentConfigOther\&.cs\fP\&.
.SS "UIButton ContentConfigOther\&.toggleRunBackground"

.PP
Definition at line \fB135\fP of file \fBContentConfigOther\&.cs\fP\&.
.SS "UIButton ContentConfigOther\&.toggleSyncMod"

.PP
Definition at line \fB129\fP of file \fBContentConfigOther\&.cs\fP\&.
.SS "UIButton ContentConfigOther\&.toggleTest"

.PP
Definition at line \fB138\fP of file \fBContentConfigOther\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
