.TH "ContentTactics" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ContentTactics
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBContentConfig\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnInstantiate\fP ()"
.br
.ti -1c
.RI "void \fBRefresh\fP ()"
.br
.in -1c

Public Member Functions inherited from \fBContentConfig\fP
.in +1c
.ti -1c
.RI "void \fBSetSlider\fP (Slider slider, float value, Func< float, string > action)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "UIButton \fBtoggleFollowDist\fP"
.br
.ti -1c
.RI "UIButton \fBtoggleDontWander\fP"
.br
.ti -1c
.RI "UIButton \fBtoggleAbortOnAllyDying\fP"
.br
.ti -1c
.RI "UIButton \fBtoggleAbortOnAllyDead\fP"
.br
.ti -1c
.RI "UIButton \fBtoggleAbortOnKill\fP"
.br
.ti -1c
.RI "UIButton \fBtoggleOnEnemyDead\fP"
.br
.ti -1c
.RI "UIButton \fBtoggleOnHalfHP\fP"
.br
.ti -1c
.RI "UIButton \fBtoggleBUseHotbar\fP"
.br
.ti -1c
.RI "UIButton \fBtoggleBUseFav\fP"
.br
.ti -1c
.RI "UIButton \fBtoggleBUseInventory\fP"
.br
.ti -1c
.RI "UIButton \fBtoggleBTurbo\fP"
.br
.ti -1c
.RI "UIButton \fBtoggleBCastParty\fP"
.br
.ti -1c
.RI "UIButton \fBtoggleBDontChangeTarget\fP"
.br
.ti -1c
.RI "UIButton \fBtoggleBDontAutoAttackNeutral\fP"
.br
.ti -1c
.RI "UIButton \fBtoggleBDontChase\fP"
.br
.ti -1c
.RI "UIButton \fBtoggleDetail\fP"
.br
.ti -1c
.RI "UIButton \fBtogglePrefKeepPlaying\fP"
.br
.ti -1c
.RI "UIButton \fBtogglePickFish\fP"
.br
.ti -1c
.RI "UIDropdown \fBddTactics\fP"
.br
.ti -1c
.RI "Transform \fBtransDetail\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Properties inherited from \fBContentConfig\fP
.in +1c
.ti -1c
.RI "\fBCoreConfig\fP \fBconfig\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB7\fP of file \fBContentTactics\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void ContentTactics\&.OnInstantiate ()"

.PP
Definition at line \fB10\fP of file \fBContentTactics\&.cs\fP\&.
.SS "void ContentTactics\&.Refresh ()"

.PP
Definition at line \fB16\fP of file \fBContentTactics\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "UIDropdown ContentTactics\&.ddTactics"

.PP
Definition at line \fB161\fP of file \fBContentTactics\&.cs\fP\&.
.SS "UIButton ContentTactics\&.toggleAbortOnAllyDead"

.PP
Definition at line \fB116\fP of file \fBContentTactics\&.cs\fP\&.
.SS "UIButton ContentTactics\&.toggleAbortOnAllyDying"

.PP
Definition at line \fB113\fP of file \fBContentTactics\&.cs\fP\&.
.SS "UIButton ContentTactics\&.toggleAbortOnKill"

.PP
Definition at line \fB119\fP of file \fBContentTactics\&.cs\fP\&.
.SS "UIButton ContentTactics\&.toggleBCastParty"

.PP
Definition at line \fB140\fP of file \fBContentTactics\&.cs\fP\&.
.SS "UIButton ContentTactics\&.toggleBDontAutoAttackNeutral"

.PP
Definition at line \fB146\fP of file \fBContentTactics\&.cs\fP\&.
.SS "UIButton ContentTactics\&.toggleBDontChangeTarget"

.PP
Definition at line \fB143\fP of file \fBContentTactics\&.cs\fP\&.
.SS "UIButton ContentTactics\&.toggleBDontChase"

.PP
Definition at line \fB149\fP of file \fBContentTactics\&.cs\fP\&.
.SS "UIButton ContentTactics\&.toggleBTurbo"

.PP
Definition at line \fB137\fP of file \fBContentTactics\&.cs\fP\&.
.SS "UIButton ContentTactics\&.toggleBUseFav"

.PP
Definition at line \fB131\fP of file \fBContentTactics\&.cs\fP\&.
.SS "UIButton ContentTactics\&.toggleBUseHotbar"

.PP
Definition at line \fB128\fP of file \fBContentTactics\&.cs\fP\&.
.SS "UIButton ContentTactics\&.toggleBUseInventory"

.PP
Definition at line \fB134\fP of file \fBContentTactics\&.cs\fP\&.
.SS "UIButton ContentTactics\&.toggleDetail"

.PP
Definition at line \fB152\fP of file \fBContentTactics\&.cs\fP\&.
.SS "UIButton ContentTactics\&.toggleDontWander"

.PP
Definition at line \fB110\fP of file \fBContentTactics\&.cs\fP\&.
.SS "UIButton ContentTactics\&.toggleFollowDist"

.PP
Definition at line \fB107\fP of file \fBContentTactics\&.cs\fP\&.
.SS "UIButton ContentTactics\&.toggleOnEnemyDead"

.PP
Definition at line \fB122\fP of file \fBContentTactics\&.cs\fP\&.
.SS "UIButton ContentTactics\&.toggleOnHalfHP"

.PP
Definition at line \fB125\fP of file \fBContentTactics\&.cs\fP\&.
.SS "UIButton ContentTactics\&.togglePickFish"

.PP
Definition at line \fB158\fP of file \fBContentTactics\&.cs\fP\&.
.SS "UIButton ContentTactics\&.togglePrefKeepPlaying"

.PP
Definition at line \fB155\fP of file \fBContentTactics\&.cs\fP\&.
.SS "Transform ContentTactics\&.transDetail"

.PP
Definition at line \fB164\fP of file \fBContentTactics\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
