.TH "ContentHomeRanking" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ContentHomeRanking
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBEContent\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnSwitchContent\fP (int idTab)"
.br
.ti -1c
.RI "void \fBRefresh\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "UIDynamicList \fBlistRanking\fP"
.br
.ti -1c
.RI "Color[] \fBcolors\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB6\fP of file \fBContentHomeRanking\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void ContentHomeRanking\&.OnSwitchContent (int idTab)"

.PP
Definition at line \fB9\fP of file \fBContentHomeRanking\&.cs\fP\&.
.SS "void ContentHomeRanking\&.Refresh ()"

.PP
Definition at line \fB15\fP of file \fBContentHomeRanking\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "Color [] ContentHomeRanking\&.colors"

.PP
Definition at line \fB66\fP of file \fBContentHomeRanking\&.cs\fP\&.
.SS "UIDynamicList ContentHomeRanking\&.listRanking"

.PP
Definition at line \fB63\fP of file \fBContentHomeRanking\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
