.TH "ContentTop" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ContentTop
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBEContent\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnSwitchContent\fP (int idTab)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "UIText \fBtextHomeName\fP"
.br
.ti -1c
.RI "UIList \fBlist1\fP"
.br
.ti -1c
.RI "UIList \fBlist2\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB4\fP of file \fBContentTop\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void ContentTop\&.OnSwitchContent (int idTab)"

.PP
Definition at line \fB7\fP of file \fBContentTop\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "UIList ContentTop\&.list1"

.PP
Definition at line \fB31\fP of file \fBContentTop\&.cs\fP\&.
.SS "UIList ContentTop\&.list2"

.PP
Definition at line \fB34\fP of file \fBContentTop\&.cs\fP\&.
.SS "UIText ContentTop\&.textHomeName"

.PP
Definition at line \fB28\fP of file \fBContentTop\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
