.TH "ContentConfig" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ContentConfig
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBEContent\fP\&.
.PP
Inherited by \fBContentConfigGame\fP, \fBContentConfigGeneral\fP, \fBContentConfigOther\fP, \fBContentConfigTest\fP, and \fBContentTactics\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetSlider\fP (Slider slider, float value, Func< float, string > action)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBCoreConfig\fP \fBconfig\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB5\fP of file \fBContentConfig\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void ContentConfig\&.SetSlider (Slider slider, float value, Func< float, string > action)"

.PP
Definition at line \fB18\fP of file \fBContentConfig\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "\fBCoreConfig\fP ContentConfig\&.config\fR [get]\fP"

.PP
Definition at line \fB9\fP of file \fBContentConfig\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
