.TH "ContentCodex" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ContentCodex
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBEContent\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnSwitchContent\fP (int idTab)"
.br
.ti -1c
.RI "void \fBRefreshList\fP ()"
.br
.ti -1c
.RI "void \fBRefreshInfo\fP ()"
.br
.ti -1c
.RI "void \fBOnClickAddCards\fP ()"
.br
.ti -1c
.RI "void \fBOnClickGetCard\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBCollect\fP (\fBThing\fP t)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "UIDynamicList \fBlist\fP"
.br
.ti -1c
.RI "UIText \fBtextName\fP"
.br
.ti -1c
.RI "UIText \fBtextOwn\fP"
.br
.ti -1c
.RI "UIText \fBtextValue\fP"
.br
.ti -1c
.RI "UIText \fBtextKills\fP"
.br
.ti -1c
.RI "UIText \fBtextWeakspot\fP"
.br
.ti -1c
.RI "UIText \fBtextSpawns\fP"
.br
.ti -1c
.RI "UIText \fBtextBonus\fP"
.br
.ti -1c
.RI "UINote \fBnote\fP"
.br
.ti -1c
.RI "\fBCodexCreature\fP \fBcurrentCodex\fP"
.br
.ti -1c
.RI "Transform \fBtransInfo\fP"
.br
.ti -1c
.RI "UIButton \fBbuttonTake\fP"
.br
.ti -1c
.RI "UIButton \fBbuttonAddCards\fP"
.br
.ti -1c
.RI "UIButton \fBbuttonToggleCollect\fP"
.br
.ti -1c
.RI "Vector2 \fBpivot\fP"
.br
.ti -1c
.RI "Vector2 \fBlocalPos\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB6\fP of file \fBContentCodex\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "static void ContentCodex\&.Collect (\fBThing\fP t)\fR [static]\fP"

.PP
Definition at line \fB142\fP of file \fBContentCodex\&.cs\fP\&.
.SS "void ContentCodex\&.OnClickAddCards ()"

.PP
Definition at line \fB117\fP of file \fBContentCodex\&.cs\fP\&.
.SS "void ContentCodex\&.OnClickGetCard ()"

.PP
Definition at line \fB151\fP of file \fBContentCodex\&.cs\fP\&.
.SS "override void ContentCodex\&.OnSwitchContent (int idTab)"

.PP
Definition at line \fB9\fP of file \fBContentCodex\&.cs\fP\&.
.SS "void ContentCodex\&.RefreshInfo ()"

.PP
Definition at line \fB82\fP of file \fBContentCodex\&.cs\fP\&.
.SS "void ContentCodex\&.RefreshList ()"

.PP
Definition at line \fB28\fP of file \fBContentCodex\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "UIButton ContentCodex\&.buttonAddCards"

.PP
Definition at line \fB206\fP of file \fBContentCodex\&.cs\fP\&.
.SS "UIButton ContentCodex\&.buttonTake"

.PP
Definition at line \fB203\fP of file \fBContentCodex\&.cs\fP\&.
.SS "UIButton ContentCodex\&.buttonToggleCollect"

.PP
Definition at line \fB209\fP of file \fBContentCodex\&.cs\fP\&.
.SS "\fBCodexCreature\fP ContentCodex\&.currentCodex"

.PP
Definition at line \fB197\fP of file \fBContentCodex\&.cs\fP\&.
.SS "UIDynamicList ContentCodex\&.list"

.PP
Definition at line \fB170\fP of file \fBContentCodex\&.cs\fP\&.
.SS "Vector2 ContentCodex\&.localPos"

.PP
Definition at line \fB215\fP of file \fBContentCodex\&.cs\fP\&.
.SS "UINote ContentCodex\&.note"

.PP
Definition at line \fB194\fP of file \fBContentCodex\&.cs\fP\&.
.SS "Vector2 ContentCodex\&.pivot"

.PP
Definition at line \fB212\fP of file \fBContentCodex\&.cs\fP\&.
.SS "UIText ContentCodex\&.textBonus"

.PP
Definition at line \fB191\fP of file \fBContentCodex\&.cs\fP\&.
.SS "UIText ContentCodex\&.textKills"

.PP
Definition at line \fB182\fP of file \fBContentCodex\&.cs\fP\&.
.SS "UIText ContentCodex\&.textName"

.PP
Definition at line \fB173\fP of file \fBContentCodex\&.cs\fP\&.
.SS "UIText ContentCodex\&.textOwn"

.PP
Definition at line \fB176\fP of file \fBContentCodex\&.cs\fP\&.
.SS "UIText ContentCodex\&.textSpawns"

.PP
Definition at line \fB188\fP of file \fBContentCodex\&.cs\fP\&.
.SS "UIText ContentCodex\&.textValue"

.PP
Definition at line \fB179\fP of file \fBContentCodex\&.cs\fP\&.
.SS "UIText ContentCodex\&.textWeakspot"

.PP
Definition at line \fB185\fP of file \fBContentCodex\&.cs\fP\&.
.SS "Transform ContentCodex\&.transInfo"

.PP
Definition at line \fB200\fP of file \fBContentCodex\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
