.TH "ContentChronicle" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ContentChronicle
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBEContent\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnSwitchContent\fP (int idTab)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "UIList \fBlist\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB4\fP of file \fBContentChronicle\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void ContentChronicle\&.OnSwitchContent (int idTab)"

.PP
Definition at line \fB7\fP of file \fBContentChronicle\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "UIList ContentChronicle\&.list"

.PP
Definition at line \fB30\fP of file \fBContentChronicle\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
