.TH "ContentFaction" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ContentFaction
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBEContent\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnSwitchContent\fP (int idTab)"
.br
.ti -1c
.RI "void \fBRefreshFactions\fP (bool religion)"
.br
.ti -1c
.RI "void \fBRefreshZones\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "UIList \fBlistFaction\fP"
.br
.ti -1c
.RI "\fBUIFactionInfo\fP \fBinfo\fP"
.br
.ti -1c
.RI "Sprite \fBspriteFaction\fP"
.br
.ti -1c
.RI "Sprite \fBspriteFaith\fP"
.br
.ti -1c
.RI "UIText \fBtextHeader\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB6\fP of file \fBContentFaction\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void ContentFaction\&.OnSwitchContent (int idTab)"

.PP
Definition at line \fB9\fP of file \fBContentFaction\&.cs\fP\&.
.SS "void ContentFaction\&.RefreshFactions (bool religion)"

.PP
Definition at line \fB24\fP of file \fBContentFaction\&.cs\fP\&.
.SS "void ContentFaction\&.RefreshZones ()"

.PP
Definition at line \fB84\fP of file \fBContentFaction\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBUIFactionInfo\fP ContentFaction\&.info"

.PP
Definition at line \fB123\fP of file \fBContentFaction\&.cs\fP\&.
.SS "UIList ContentFaction\&.listFaction"

.PP
Definition at line \fB120\fP of file \fBContentFaction\&.cs\fP\&.
.SS "Sprite ContentFaction\&.spriteFaction"

.PP
Definition at line \fB126\fP of file \fBContentFaction\&.cs\fP\&.
.SS "Sprite ContentFaction\&.spriteFaith"

.PP
Definition at line \fB129\fP of file \fBContentFaction\&.cs\fP\&.
.SS "UIText ContentFaction\&.textHeader"

.PP
Definition at line \fB132\fP of file \fBContentFaction\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
