.TH "ContentGallery.Page.Item" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ContentGallery.Page.Item
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBid\fP"
.br
.ti -1c
.RI "Sprite \fBsprite\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB132\fP of file \fBContentGallery\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int ContentGallery\&.Page\&.Item\&.id"

.PP
Definition at line \fB135\fP of file \fBContentGallery\&.cs\fP\&.
.SS "Sprite ContentGallery\&.Page\&.Item\&.sprite"

.PP
Definition at line \fB138\fP of file \fBContentGallery\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
