.TH "ContentConfigTest" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ContentConfigTest
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBContentConfig\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnInstantiate\fP ()"
.br
.in -1c

Public Member Functions inherited from \fBContentConfig\fP
.in +1c
.ti -1c
.RI "void \fBSetSlider\fP (Slider slider, float value, Func< float, string > action)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "UIDropdown \fBddSkin\fP"
.br
.ti -1c
.RI "UIButtonLR \fBbuttonAnimeFrame\fP"
.br
.ti -1c
.RI "UIButtonLR \fBbuttonAnimeFramePCC\fP"
.br
.ti -1c
.RI "UIButton \fBtoggleAlwaysRun\fP"
.br
.ti -1c
.RI "UIButton \fBtoggleShowNumber\fP"
.br
.ti -1c
.RI "UIButton \fBtoggleAAPortrait\fP"
.br
.ti -1c
.RI "UIButton \fBtoggleExTurn\fP"
.br
.ti -1c
.RI "UIButton \fBtoggleBloom2\fP"
.br
.ti -1c
.RI "UIButton \fBtoggleExtraRace\fP"
.br
.ti -1c
.RI "UIButton \fBtoggleSeal\fP"
.br
.ti -1c
.RI "UIButton \fBtoggleExtraCancelMove\fP"
.br
.ti -1c
.RI "UIButton \fBtoggleBlockOnItem\fP"
.br
.ti -1c
.RI "UIButton \fBtoggleAlwaysFixCamera\fP"
.br
.ti -1c
.RI "UIButton \fBtoggleIgnoreBackerFlag\fP"
.br
.ti -1c
.RI "UIButton \fBtoggleRefIcon\fP"
.br
.ti -1c
.RI "Slider \fBsliderBrightness\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Properties inherited from \fBContentConfig\fP
.in +1c
.ti -1c
.RI "\fBCoreConfig\fP \fBconfig\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB6\fP of file \fBContentConfigTest\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void ContentConfigTest\&.OnInstantiate ()"

.PP
Definition at line \fB9\fP of file \fBContentConfigTest\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "UIButtonLR ContentConfigTest\&.buttonAnimeFrame"

.PP
Definition at line \fB107\fP of file \fBContentConfigTest\&.cs\fP\&.
.SS "UIButtonLR ContentConfigTest\&.buttonAnimeFramePCC"

.PP
Definition at line \fB110\fP of file \fBContentConfigTest\&.cs\fP\&.
.SS "UIDropdown ContentConfigTest\&.ddSkin"

.PP
Definition at line \fB104\fP of file \fBContentConfigTest\&.cs\fP\&.
.SS "Slider ContentConfigTest\&.sliderBrightness"

.PP
Definition at line \fB149\fP of file \fBContentConfigTest\&.cs\fP\&.
.SS "UIButton ContentConfigTest\&.toggleAAPortrait"

.PP
Definition at line \fB119\fP of file \fBContentConfigTest\&.cs\fP\&.
.SS "UIButton ContentConfigTest\&.toggleAlwaysFixCamera"

.PP
Definition at line \fB140\fP of file \fBContentConfigTest\&.cs\fP\&.
.SS "UIButton ContentConfigTest\&.toggleAlwaysRun"

.PP
Definition at line \fB113\fP of file \fBContentConfigTest\&.cs\fP\&.
.SS "UIButton ContentConfigTest\&.toggleBlockOnItem"

.PP
Definition at line \fB137\fP of file \fBContentConfigTest\&.cs\fP\&.
.SS "UIButton ContentConfigTest\&.toggleBloom2"

.PP
Definition at line \fB125\fP of file \fBContentConfigTest\&.cs\fP\&.
.SS "UIButton ContentConfigTest\&.toggleExtraCancelMove"

.PP
Definition at line \fB134\fP of file \fBContentConfigTest\&.cs\fP\&.
.SS "UIButton ContentConfigTest\&.toggleExtraRace"

.PP
Definition at line \fB128\fP of file \fBContentConfigTest\&.cs\fP\&.
.SS "UIButton ContentConfigTest\&.toggleExTurn"

.PP
Definition at line \fB122\fP of file \fBContentConfigTest\&.cs\fP\&.
.SS "UIButton ContentConfigTest\&.toggleIgnoreBackerFlag"

.PP
Definition at line \fB143\fP of file \fBContentConfigTest\&.cs\fP\&.
.SS "UIButton ContentConfigTest\&.toggleRefIcon"

.PP
Definition at line \fB146\fP of file \fBContentConfigTest\&.cs\fP\&.
.SS "UIButton ContentConfigTest\&.toggleSeal"

.PP
Definition at line \fB131\fP of file \fBContentConfigTest\&.cs\fP\&.
.SS "UIButton ContentConfigTest\&.toggleShowNumber"

.PP
Definition at line \fB116\fP of file \fBContentConfigTest\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
