.TH "ContentGallery.Page" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ContentGallery.Page
.SH SYNOPSIS
.br
.PP
.PP
Inherits UIBook\&.Page\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBItem\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBBuildNote\fP (UINote n, string idTopic)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "List< string > \fBids\fP = new List<string>()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB108\fP of file \fBContentGallery\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void ContentGallery\&.Page\&.BuildNote (UINote n, string idTopic)"

.PP
Definition at line \fB111\fP of file \fBContentGallery\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "List<string> ContentGallery\&.Page\&.ids = new List<string>()"

.PP
Definition at line \fB129\fP of file \fBContentGallery\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
