.TH "ContentHomeLog" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ContentHomeLog
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBEContent\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnSwitchContent\fP (int idTab)"
.br
.ti -1c
.RI "void \fBRefreshLog\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "UIList \fBlistLog\fP"
.br
.ti -1c
.RI "\fBItemStatistics\fP \fBstat\fP"
.br
.ti -1c
.RI "\fBItemStatistics\fP \fBstatLast\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB4\fP of file \fBContentHomeLog\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void ContentHomeLog\&.OnSwitchContent (int idTab)"

.PP
Definition at line \fB7\fP of file \fBContentHomeLog\&.cs\fP\&.
.SS "void ContentHomeLog\&.RefreshLog ()"

.PP
Definition at line \fB14\fP of file \fBContentHomeLog\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "UIList ContentHomeLog\&.listLog"

.PP
Definition at line \fB48\fP of file \fBContentHomeLog\&.cs\fP\&.
.SS "\fBItemStatistics\fP ContentHomeLog\&.stat"

.PP
Definition at line \fB51\fP of file \fBContentHomeLog\&.cs\fP\&.
.SS "\fBItemStatistics\fP ContentHomeLog\&.statLast"

.PP
Definition at line \fB54\fP of file \fBContentHomeLog\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
