.TH "ContentKeyItem" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ContentKeyItem
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBEContent\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnSwitchContent\fP (int idTab)"
.br
.ti -1c
.RI "void \fBSelectItem\fP (\fBSourceKeyItem\&.Row\fP q)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "UIList \fBlist\fP"
.br
.ti -1c
.RI "UIText \fBtextClient\fP"
.br
.ti -1c
.RI "UIText \fBtextTitle\fP"
.br
.ti -1c
.RI "UIText \fBtextDetail\fP"
.br
.ti -1c
.RI "Image \fBimageItem\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB6\fP of file \fBContentKeyItem\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void ContentKeyItem\&.OnSwitchContent (int idTab)"

.PP
Definition at line \fB9\fP of file \fBContentKeyItem\&.cs\fP\&.
.SS "void ContentKeyItem\&.SelectItem (\fBSourceKeyItem\&.Row\fP q)"

.PP
Definition at line \fB40\fP of file \fBContentKeyItem\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "Image ContentKeyItem\&.imageItem"

.PP
Definition at line \fB68\fP of file \fBContentKeyItem\&.cs\fP\&.
.SS "UIList ContentKeyItem\&.list"

.PP
Definition at line \fB56\fP of file \fBContentKeyItem\&.cs\fP\&.
.SS "UIText ContentKeyItem\&.textClient"

.PP
Definition at line \fB59\fP of file \fBContentKeyItem\&.cs\fP\&.
.SS "UIText ContentKeyItem\&.textDetail"

.PP
Definition at line \fB65\fP of file \fBContentKeyItem\&.cs\fP\&.
.SS "UIText ContentKeyItem\&.textTitle"

.PP
Definition at line \fB62\fP of file \fBContentKeyItem\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
