.TH "ContentQuest" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ContentQuest
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBEContent\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnSwitchContent\fP (int idTab)"
.br
.ti -1c
.RI "void \fBRefreshTrackButtons\fP ()"
.br
.ti -1c
.RI "void \fBSelectQuest\fP (\fBQuest\fP q)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "UIList \fBlist\fP"
.br
.ti -1c
.RI "UIText \fBtextClient\fP"
.br
.ti -1c
.RI "UIText \fBtextTitle\fP"
.br
.ti -1c
.RI "UIText \fBtextDetail\fP"
.br
.ti -1c
.RI "UIText \fBtextHours\fP"
.br
.ti -1c
.RI "UIText \fBtextNote\fP"
.br
.ti -1c
.RI "UIText \fBtextReward\fP"
.br
.ti -1c
.RI "UIText \fBtextZone\fP"
.br
.ti -1c
.RI "\fBPortrait\fP \fBportrait\fP"
.br
.ti -1c
.RI "UIButton \fBbuttonAbandon\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB6\fP of file \fBContentQuest\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void ContentQuest\&.OnSwitchContent (int idTab)"

.PP
Definition at line \fB9\fP of file \fBContentQuest\&.cs\fP\&.
.SS "void ContentQuest\&.RefreshTrackButtons ()"

.PP
Definition at line \fB78\fP of file \fBContentQuest\&.cs\fP\&.
.SS "void ContentQuest\&.SelectQuest (\fBQuest\fP q)"

.PP
Definition at line \fB88\fP of file \fBContentQuest\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "UIButton ContentQuest\&.buttonAbandon"

.PP
Definition at line \fB171\fP of file \fBContentQuest\&.cs\fP\&.
.SS "UIList ContentQuest\&.list"

.PP
Definition at line \fB144\fP of file \fBContentQuest\&.cs\fP\&.
.SS "\fBPortrait\fP ContentQuest\&.portrait"

.PP
Definition at line \fB168\fP of file \fBContentQuest\&.cs\fP\&.
.SS "UIText ContentQuest\&.textClient"

.PP
Definition at line \fB147\fP of file \fBContentQuest\&.cs\fP\&.
.SS "UIText ContentQuest\&.textDetail"

.PP
Definition at line \fB153\fP of file \fBContentQuest\&.cs\fP\&.
.SS "UIText ContentQuest\&.textHours"

.PP
Definition at line \fB156\fP of file \fBContentQuest\&.cs\fP\&.
.SS "UIText ContentQuest\&.textNote"

.PP
Definition at line \fB159\fP of file \fBContentQuest\&.cs\fP\&.
.SS "UIText ContentQuest\&.textReward"

.PP
Definition at line \fB162\fP of file \fBContentQuest\&.cs\fP\&.
.SS "UIText ContentQuest\&.textTitle"

.PP
Definition at line \fB150\fP of file \fBContentQuest\&.cs\fP\&.
.SS "UIText ContentQuest\&.textZone"

.PP
Definition at line \fB165\fP of file \fBContentQuest\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
