.TH "CoreConfig" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CoreConfig
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBEClass\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBackerContentConfig\fP"
.br
.ti -1c
.RI "class \fBCameraConfig\fP"
.br
.ti -1c
.RI "class \fBCustomFont\fP"
.br
.ti -1c
.RI "class \fBFix\fP"
.br
.ti -1c
.RI "class \fBFontSetting\fP"
.br
.ti -1c
.RI "class \fBGameConfig\fP"
.br
.ti -1c
.RI "class \fBGraphicSetting\fP"
.br
.ti -1c
.RI "class \fBInputSetting\fP"
.br
.ti -1c
.RI "class \fBNetSetting\fP"
.br
.ti -1c
.RI "class \fBOtherSetting\fP"
.br
.ti -1c
.RI "class \fBSoundSetting\fP"
.br
.ti -1c
.RI "class \fBTest\fP"
.br
.ti -1c
.RI "class \fBUISetting\fP"
.br
.in -1c
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBGameFunc\fP { \fBNone\fP, \fBToggleZoom\fP, \fBShowInv\fP, \fBShowChara\fP, \fBShowAbility\fP, \fBToggleBuild\fP, \fBShowJournal\fP, \fBEmuShift\fP, \fBEmuAlt\fP, \fBAllAction\fP, \fBToggleNoRoof\fP, \fBOpenAllyInv\fP, \fBTalk\fP, \fBEmptyHand\fP, \fBFire\fP }"
.br
.ti -1c
.RI "enum \fBGameFuncBuild\fP { \fBNone\fP, \fBExitBuildMode\fP, \fBRotate\fP, \fBToggleFreepos\fP, \fBSnapFreepos\fP, \fBToggleRoof\fP, \fBToggleSlope\fP, \fBToggleWall\fP, \fBTogglePicker\fP, \fBToggleBuildLight\fP }"
.br
.ti -1c
.RI "enum \fBScreenSnapType\fP { \fBNone\fP, \fBDefault\fP, \fBFloor\fP, \fBCeil\fP, \fBHack3\fP, \fBHack4\fP, \fBHack5\fP, \fBHack6\fP, \fBHack7\fP, \fBHack8\fP, \fBHack9\fP, \fBGrid\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBOnInit\fP ()"
.br
.ti -1c
.RI "bool \fBHasBackerRewardCode\fP ()"
.br
.ti -1c
.RI "void \fBOnReset\fP ()"
.br
.ti -1c
.RI "void \fBSetLang\fP (string id)"
.br
.ti -1c
.RI "void \fBSave\fP ()"
.br
.ti -1c
.RI "void \fBOnChangeResolution\fP ()"
.br
.ti -1c
.RI "void \fBApplyFPS\fP (bool force=false)"
.br
.ti -1c
.RI "void \fBApply\fP ()"
.br
.ti -1c
.RI "void \fBApplyResolution\fP (bool force=false)"
.br
.ti -1c
.RI "void \fBApplyScale\fP ()"
.br
.ti -1c
.RI "void \fBApplyHUD\fP ()"
.br
.ti -1c
.RI "void \fBApplyZoom\fP (float a)"
.br
.ti -1c
.RI "\fBPostEffectProfile\fP \fBGetPostEffectProfile\fP (bool replaceWorld=false)"
.br
.ti -1c
.RI "void \fBApplyGrading\fP ()"
.br
.ti -1c
.RI "void \fBRefreshUIBrightness\fP ()"
.br
.ti -1c
.RI "void \fBApplyVolume\fP ()"
.br
.ti -1c
.RI "void \fBSetBGMInterval\fP ()"
.br
.ti -1c
.RI "void \fBSetVolume\fP (string id, float v)"
.br
.ti -1c
.RI "void \fBOnSetLang\fP ()"
.br
.ti -1c
.RI "void \fBApplyFont\fP ()"
.br
.ti -1c
.RI "void \fBApplySkin\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBExist\fP ()"
.br
.ti -1c
.RI "static \fBCoreConfig\fP \fBTryLoadConfig\fP ()"
.br
.ti -1c
.RI "static bool \fBIsCompatible\fP (global::Version v)"
.br
.ti -1c
.RI "static void \fBInit\fP ()"
.br
.ti -1c
.RI "static void \fBReset\fP ()"
.br
.ti -1c
.RI "static void \fBResetGeneral\fP ()"
.br
.ti -1c
.RI "static void \fBResetGraphics\fP ()"
.br
.ti -1c
.RI "static void \fBResetGame\fP ()"
.br
.ti -1c
.RI "static void \fBResetInput\fP ()"
.br
.ti -1c
.RI "static void \fBResetOther\fP ()"
.br
.ti -1c
.RI "static void \fBResetTest\fP ()"
.br
.in -1c

Static Public Member Functions inherited from \fBEClass\fP
.in +1c
.ti -1c
.RI "static int \fBrnd\fP (int a)"
.br
.ti -1c
.RI "static int \fBcurve\fP (int a, int start, int step, int rate=75)"
.br
.ti -1c
.RI "static int \fBrndHalf\fP (int a)"
.br
.ti -1c
.RI "static float \fBrndf\fP (float a)"
.br
.ti -1c
.RI "static int \fBrndSqrt\fP (int a)"
.br
.ti -1c
.RI "static void \fBWait\fP (float a, \fBCard\fP c)"
.br
.ti -1c
.RI "static void \fBWait\fP (float a, \fBPoint\fP p)"
.br
.ti -1c
.RI "static int \fBBigger\fP (int a, int b)"
.br
.ti -1c
.RI "static int \fBSmaller\fP (int a, int b)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "global::Version \fBversion\fP"
.br
.ti -1c
.RI "string \fBlang\fP = 'JP'"
.br
.ti -1c
.RI "string \fBnameReport\fP"
.br
.ti -1c
.RI "string \fBemailReport\fP"
.br
.ti -1c
.RI "string \fBrewardCode\fP"
.br
.ti -1c
.RI "bool \fBcompressSave\fP"
.br
.ti -1c
.RI "new \fBCoreConfig\&.UISetting\fP \fBui\fP"
.br
.ti -1c
.RI "\fBCoreConfig\&.SoundSetting\fP \fBsound\fP"
.br
.ti -1c
.RI "\fBCoreConfig\&.FontSetting\fP \fBfont\fP"
.br
.ti -1c
.RI "\fBCoreConfig\&.GraphicSetting\fP \fBgraphic\fP"
.br
.ti -1c
.RI "new \fBCoreConfig\&.GameConfig\fP \fBgame\fP"
.br
.ti -1c
.RI "\fBCoreConfig\&.NetSetting\fP \fBnet\fP"
.br
.ti -1c
.RI "\fBCoreConfig\&.BackerContentConfig\fP \fBbacker\fP"
.br
.ti -1c
.RI "\fBCoreConfig\&.InputSetting\fP \fBinput\fP"
.br
.ti -1c
.RI "\fBCoreConfig\&.CameraConfig\fP \fBcamera\fP"
.br
.ti -1c
.RI "\fBCoreConfig\&.OtherSetting\fP \fBother\fP"
.br
.ti -1c
.RI "\fBCoreConfig\&.Fix\fP \fBfix\fP"
.br
.ti -1c
.RI "\fBCoreConfig\&.Test\fP \fBtest\fP"
.br
.ti -1c
.RI "List< FontSource > \fBcustomFonts\fP"
.br
.ti -1c
.RI "HashSet< string > \fBhelpFlags\fP = new HashSet<string>()"
.br
.ti -1c
.RI "int[] \fBcolors\fP = new int[10]"
.br
.ti -1c
.RI "bool \fBignoreApply\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "static string \fBpath\fP\fR [get]\fP"
.br
.ti -1c
.RI "static int \fBZoomStep\fP\fR [get]\fP"
.br
.ti -1c
.RI "\fBCameraSupport\fP \fBcamSupport\fP\fR [get]\fP"
.br
.in -1c

Properties inherited from \fBEClass\fP
.in +1c
.ti -1c
.RI "static \fBGame\fP \fBgame\fP\fR [get]\fP"
.br
.ti -1c
.RI "static bool \fBAdvMode\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBPlayer\fP \fBplayer\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBChara\fP \fBpc\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBUI\fP \fBui\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBMap\fP \fB_map\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBZone\fP \fB_zone\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranchOrHomeBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFaction\fP \fBHome\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFaction\fP \fBWilds\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBScene\fP \fBscene\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBBaseGameScreen\fP \fBscreen\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameSetting\fP \fBsetting\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameData\fP \fBgamedata\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBColorProfile\fP \fBColors\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBWorld\fP \fBworld\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBsources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBeditorSources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static SoundManager \fBSound\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBCoreDebug\fP \fBdebug\fP\fR [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Static Public Attributes inherited from \fBEClass\fP
.in +1c
.ti -1c
.RI "static \fBCore\fP \fBcore\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB12\fP of file \fBCoreConfig\&.cs\fP\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "enum CoreConfig\&.GameFunc"

.PP
Definition at line \fB518\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "enum CoreConfig\&.GameFuncBuild"

.PP
Definition at line \fB553\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "enum CoreConfig\&.ScreenSnapType"

.PP
Definition at line \fB578\fP of file \fBCoreConfig\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void CoreConfig\&.Apply ()"

.PP
Definition at line \fB255\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "void CoreConfig\&.ApplyFont ()"

.PP
Definition at line \fB429\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "void CoreConfig\&.ApplyFPS (bool force = \fRfalse\fP)"

.PP
Definition at line \fB236\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "void CoreConfig\&.ApplyGrading ()"

.PP
Definition at line \fB354\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "void CoreConfig\&.ApplyHUD ()"

.PP
Definition at line \fB330\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "void CoreConfig\&.ApplyResolution (bool force = \fRfalse\fP)"

.PP
Definition at line \fB294\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "void CoreConfig\&.ApplyScale ()"

.PP
Definition at line \fB308\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "void CoreConfig\&.ApplySkin ()"

.PP
Definition at line \fB435\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "void CoreConfig\&.ApplyVolume ()"

.PP
Definition at line \fB396\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "void CoreConfig\&.ApplyZoom (float a)"

.PP
Definition at line \fB335\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "static bool CoreConfig\&.Exist ()\fR [static]\fP"

.PP
Definition at line \fB50\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "\fBPostEffectProfile\fP CoreConfig\&.GetPostEffectProfile (bool replaceWorld = \fRfalse\fP)"

.PP
Definition at line \fB343\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "bool CoreConfig\&.HasBackerRewardCode ()"

.PP
Definition at line \fB133\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "static void CoreConfig\&.Init ()\fR [static]\fP"

.PP
Definition at line \fB98\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "static bool CoreConfig\&.IsCompatible (global\&.Version v)\fR [static]\fP"

.PP
Definition at line \fB92\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "void CoreConfig\&.OnChangeResolution ()"

.PP
Definition at line \fB230\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "void CoreConfig\&.OnInit ()"

.PP
Definition at line \fB122\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "void CoreConfig\&.OnReset ()"

.PP
Definition at line \fB206\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "void CoreConfig\&.OnSetLang ()"

.PP
Definition at line \fB422\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "void CoreConfig\&.RefreshUIBrightness ()"

.PP
Definition at line \fB375\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "static void CoreConfig\&.Reset ()\fR [static]\fP"

.PP
Definition at line \fB139\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "static void CoreConfig\&.ResetGame ()\fR [static]\fP"

.PP
Definition at line \fB170\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "static void CoreConfig\&.ResetGeneral ()\fR [static]\fP"

.PP
Definition at line \fB150\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "static void CoreConfig\&.ResetGraphics ()\fR [static]\fP"

.PP
Definition at line \fB161\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "static void CoreConfig\&.ResetInput ()\fR [static]\fP"

.PP
Definition at line \fB180\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "static void CoreConfig\&.ResetOther ()\fR [static]\fP"

.PP
Definition at line \fB189\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "static void CoreConfig\&.ResetTest ()\fR [static]\fP"

.PP
Definition at line \fB198\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "void CoreConfig\&.Save ()"

.PP
Definition at line \fB221\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "void CoreConfig\&.SetBGMInterval ()"

.PP
Definition at line \fB407\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "void CoreConfig\&.SetLang (string id)"

.PP
Definition at line \fB215\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "void CoreConfig\&.SetVolume (string id, float v)"

.PP
Definition at line \fB416\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "static \fBCoreConfig\fP CoreConfig\&.TryLoadConfig ()\fR [static]\fP"

.PP
Definition at line \fB56\fP of file \fBCoreConfig\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBCoreConfig\&.BackerContentConfig\fP CoreConfig\&.backer"

.PP
Definition at line \fB478\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "\fBCoreConfig\&.CameraConfig\fP CoreConfig\&.camera"

.PP
Definition at line \fB484\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "int [] CoreConfig\&.colors = new int[10]"

.PP
Definition at line \fB502\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "bool CoreConfig\&.compressSave"

.PP
Definition at line \fB457\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "List<FontSource> CoreConfig\&.customFonts"

.PP
Definition at line \fB496\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "string CoreConfig\&.emailReport"

.PP
Definition at line \fB451\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "\fBCoreConfig\&.Fix\fP CoreConfig\&.fix"

.PP
Definition at line \fB490\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "\fBCoreConfig\&.FontSetting\fP CoreConfig\&.font"

.PP
Definition at line \fB466\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "new \fBCoreConfig\&.GameConfig\fP CoreConfig\&.game"

.PP
Definition at line \fB472\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "\fBCoreConfig\&.GraphicSetting\fP CoreConfig\&.graphic"

.PP
Definition at line \fB469\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "HashSet<string> CoreConfig\&.helpFlags = new HashSet<string>()"

.PP
Definition at line \fB499\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "bool CoreConfig\&.ignoreApply"

.PP
Definition at line \fB506\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "\fBCoreConfig\&.InputSetting\fP CoreConfig\&.input"

.PP
Definition at line \fB481\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "string CoreConfig\&.lang = 'JP'"

.PP
Definition at line \fB445\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "string CoreConfig\&.nameReport"

.PP
Definition at line \fB448\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "\fBCoreConfig\&.NetSetting\fP CoreConfig\&.net"

.PP
Definition at line \fB475\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "\fBCoreConfig\&.OtherSetting\fP CoreConfig\&.other"

.PP
Definition at line \fB487\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "string CoreConfig\&.rewardCode"

.PP
Definition at line \fB454\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "\fBCoreConfig\&.SoundSetting\fP CoreConfig\&.sound"

.PP
Definition at line \fB463\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "\fBCoreConfig\&.Test\fP CoreConfig\&.test"

.PP
Definition at line \fB493\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "new \fBCoreConfig\&.UISetting\fP CoreConfig\&.ui"

.PP
Definition at line \fB460\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "global\&.Version CoreConfig\&.version"

.PP
Definition at line \fB442\fP of file \fBCoreConfig\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "\fBCameraSupport\fP CoreConfig\&.camSupport\fR [get]\fP"

.PP
Definition at line \fB41\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "string CoreConfig\&.path\fR [static]\fP, \fR [get]\fP"

.PP
Definition at line \fB16\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "int CoreConfig\&.ZoomStep\fR [static]\fP, \fR [get]\fP"

.PP
Definition at line \fB26\fP of file \fBCoreConfig\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
