.TH "CoreConfig.OtherSetting" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CoreConfig.OtherSetting
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBantiMissClick\fP = 2"
.br
.ti -1c
.RI "float \fBbgmInterval\fP = 1f"
.br
.ti -1c
.RI "bool \fBnoCensor\fP"
.br
.ti -1c
.RI "bool \fBrunBackground\fP"
.br
.ti -1c
.RI "bool \fBshowTestOptions\fP"
.br
.ti -1c
.RI "bool \fBsyncMods\fP"
.br
.ti -1c
.RI "string \fBidMainWidgetTheme\fP"
.br
.ti -1c
.RI "string \fBidSubWidgetTheme\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB1213\fP of file \fBCoreConfig\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int CoreConfig\&.OtherSetting\&.antiMissClick = 2"

.PP
Definition at line \fB1216\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "float CoreConfig\&.OtherSetting\&.bgmInterval = 1f"

.PP
Definition at line \fB1219\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "string CoreConfig\&.OtherSetting\&.idMainWidgetTheme"

.PP
Definition at line \fB1234\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "string CoreConfig\&.OtherSetting\&.idSubWidgetTheme"

.PP
Definition at line \fB1237\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "bool CoreConfig\&.OtherSetting\&.noCensor"

.PP
Definition at line \fB1222\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "bool CoreConfig\&.OtherSetting\&.runBackground"

.PP
Definition at line \fB1225\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "bool CoreConfig\&.OtherSetting\&.showTestOptions"

.PP
Definition at line \fB1228\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "bool CoreConfig\&.OtherSetting\&.syncMods"

.PP
Definition at line \fB1231\fP of file \fBCoreConfig\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
