.TH "CoreConfig.Test" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CoreConfig.Test
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBidSkin\fP"
.br
.ti -1c
.RI "int \fBanimeFramePCC\fP"
.br
.ti -1c
.RI "int \fBanimeFrame\fP"
.br
.ti -1c
.RI "bool \fBshowNumbers\fP"
.br
.ti -1c
.RI "bool \fBaaPortrait\fP"
.br
.ti -1c
.RI "bool \fBextraTurnaround\fP"
.br
.ti -1c
.RI "bool \fBbloom2\fP"
.br
.ti -1c
.RI "bool \fBextraRace\fP"
.br
.ti -1c
.RI "bool \fBunsealWidgets\fP"
.br
.ti -1c
.RI "bool \fBextraMoveCancel\fP"
.br
.ti -1c
.RI "bool \fBshowNetError\fP"
.br
.ti -1c
.RI "bool \fBalwaysRun\fP"
.br
.ti -1c
.RI "bool \fBallowBlockOnItem\fP"
.br
.ti -1c
.RI "bool \fBalwaysFixCamera\fP"
.br
.ti -1c
.RI "bool \fBignoreBackerDestoryFlag\fP"
.br
.ti -1c
.RI "bool \fBshowRefIcon\fP"
.br
.ti -1c
.RI "bool \fBshowTrait\fP"
.br
.ti -1c
.RI "float \fBbrightnessNight\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB1242\fP of file \fBCoreConfig\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "bool CoreConfig\&.Test\&.aaPortrait"

.PP
Definition at line \fB1257\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "bool CoreConfig\&.Test\&.allowBlockOnItem"

.PP
Definition at line \fB1281\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "bool CoreConfig\&.Test\&.alwaysFixCamera"

.PP
Definition at line \fB1284\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "bool CoreConfig\&.Test\&.alwaysRun"

.PP
Definition at line \fB1278\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "int CoreConfig\&.Test\&.animeFrame"

.PP
Definition at line \fB1251\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "int CoreConfig\&.Test\&.animeFramePCC"

.PP
Definition at line \fB1248\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "bool CoreConfig\&.Test\&.bloom2"

.PP
Definition at line \fB1263\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "float CoreConfig\&.Test\&.brightnessNight"

.PP
Definition at line \fB1296\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "bool CoreConfig\&.Test\&.extraMoveCancel"

.PP
Definition at line \fB1272\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "bool CoreConfig\&.Test\&.extraRace"

.PP
Definition at line \fB1266\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "bool CoreConfig\&.Test\&.extraTurnaround"

.PP
Definition at line \fB1260\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "int CoreConfig\&.Test\&.idSkin"

.PP
Definition at line \fB1245\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "bool CoreConfig\&.Test\&.ignoreBackerDestoryFlag"

.PP
Definition at line \fB1287\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "bool CoreConfig\&.Test\&.showNetError"

.PP
Definition at line \fB1275\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "bool CoreConfig\&.Test\&.showNumbers"

.PP
Definition at line \fB1254\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "bool CoreConfig\&.Test\&.showRefIcon"

.PP
Definition at line \fB1290\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "bool CoreConfig\&.Test\&.showTrait"

.PP
Definition at line \fB1293\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "bool CoreConfig\&.Test\&.unsealWidgets"

.PP
Definition at line \fB1269\fP of file \fBCoreConfig\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
