.TH "CoreConfig.GraphicSetting" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CoreConfig.GraphicSetting
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBidPostProfile\fP"
.br
.ti -1c
.RI "bool \fBfullScreen\fP"
.br
.ti -1c
.RI "bool \fBpixelperfectUI\fP"
.br
.ti -1c
.RI "bool \fBalwaysClearCamera\fP"
.br
.ti -1c
.RI "bool \fBvsync\fP"
.br
.ti -1c
.RI "bool \fBkuwahara\fP"
.br
.ti -1c
.RI "bool \fBdrawAllyLight\fP"
.br
.ti -1c
.RI "bool \fBhdr\fP"
.br
.ti -1c
.RI "bool \fBfixedResolution\fP"
.br
.ti -1c
.RI "bool \fBcloud\fP"
.br
.ti -1c
.RI "bool \fBfirefly\fP"
.br
.ti -1c
.RI "bool \fBbloom\fP"
.br
.ti -1c
.RI "bool \fBgradientWater\fP"
.br
.ti -1c
.RI "bool \fBgodray\fP"
.br
.ti -1c
.RI "bool \fBenhanceRain\fP"
.br
.ti -1c
.RI "bool \fBblizzard\fP"
.br
.ti -1c
.RI "bool \fBdisableShake\fP"
.br
.ti -1c
.RI "int \fBfps\fP"
.br
.ti -1c
.RI "int \fBfireflyCount\fP = 150"
.br
.ti -1c
.RI "int \fBstarCount\fP = 200"
.br
.ti -1c
.RI "int \fBsharpen\fP"
.br
.ti -1c
.RI "int \fBsharpen2\fP"
.br
.ti -1c
.RI "int \fBblur\fP"
.br
.ti -1c
.RI "int \fBspriteFrameMode\fP"
.br
.ti -1c
.RI "int \fBw\fP = 1280"
.br
.ti -1c
.RI "int \fBh\fP = 768"
.br
.ti -1c
.RI "float \fBbrightness\fP"
.br
.ti -1c
.RI "float \fBcontrast\fP"
.br
.ti -1c
.RI "float \fBsaturation\fP"
.br
.ti -1c
.RI "float \fBvibrance\fP"
.br
.ti -1c
.RI "float \fBgradientWaterLevel\fP = 0\&.2f"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB892\fP of file \fBCoreConfig\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "bool CoreConfig\&.GraphicSetting\&.alwaysClearCamera"

.PP
Definition at line \fB904\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "bool CoreConfig\&.GraphicSetting\&.blizzard"

.PP
Definition at line \fB940\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "bool CoreConfig\&.GraphicSetting\&.bloom"

.PP
Definition at line \fB928\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "int CoreConfig\&.GraphicSetting\&.blur"

.PP
Definition at line \fB961\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "float CoreConfig\&.GraphicSetting\&.brightness"

.PP
Definition at line \fB973\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "bool CoreConfig\&.GraphicSetting\&.cloud"

.PP
Definition at line \fB922\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "float CoreConfig\&.GraphicSetting\&.contrast"

.PP
Definition at line \fB976\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "bool CoreConfig\&.GraphicSetting\&.disableShake"

.PP
Definition at line \fB943\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "bool CoreConfig\&.GraphicSetting\&.drawAllyLight"

.PP
Definition at line \fB913\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "bool CoreConfig\&.GraphicSetting\&.enhanceRain"

.PP
Definition at line \fB937\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "bool CoreConfig\&.GraphicSetting\&.firefly"

.PP
Definition at line \fB925\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "int CoreConfig\&.GraphicSetting\&.fireflyCount = 150"

.PP
Definition at line \fB949\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "bool CoreConfig\&.GraphicSetting\&.fixedResolution"

.PP
Definition at line \fB919\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "int CoreConfig\&.GraphicSetting\&.fps"

.PP
Definition at line \fB946\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "bool CoreConfig\&.GraphicSetting\&.fullScreen"

.PP
Definition at line \fB898\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "bool CoreConfig\&.GraphicSetting\&.godray"

.PP
Definition at line \fB934\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "bool CoreConfig\&.GraphicSetting\&.gradientWater"

.PP
Definition at line \fB931\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "float CoreConfig\&.GraphicSetting\&.gradientWaterLevel = 0\&.2f"

.PP
Definition at line \fB985\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "int CoreConfig\&.GraphicSetting\&.h = 768"

.PP
Definition at line \fB970\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "bool CoreConfig\&.GraphicSetting\&.hdr"

.PP
Definition at line \fB916\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "string CoreConfig\&.GraphicSetting\&.idPostProfile"

.PP
Definition at line \fB895\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "bool CoreConfig\&.GraphicSetting\&.kuwahara"

.PP
Definition at line \fB910\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "bool CoreConfig\&.GraphicSetting\&.pixelperfectUI"

.PP
Definition at line \fB901\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "float CoreConfig\&.GraphicSetting\&.saturation"

.PP
Definition at line \fB979\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "int CoreConfig\&.GraphicSetting\&.sharpen"

.PP
Definition at line \fB955\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "int CoreConfig\&.GraphicSetting\&.sharpen2"

.PP
Definition at line \fB958\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "int CoreConfig\&.GraphicSetting\&.spriteFrameMode"

.PP
Definition at line \fB964\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "int CoreConfig\&.GraphicSetting\&.starCount = 200"

.PP
Definition at line \fB952\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "float CoreConfig\&.GraphicSetting\&.vibrance"

.PP
Definition at line \fB982\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "bool CoreConfig\&.GraphicSetting\&.vsync"

.PP
Definition at line \fB907\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "int CoreConfig\&.GraphicSetting\&.w = 1280"

.PP
Definition at line \fB967\fP of file \fBCoreConfig\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
