.TH "CoreRef" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CoreRef
.SH SYNOPSIS
.br
.PP
.PP
Inherits ScriptableObject\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBiomes\fP"
.br
.ti -1c
.RI "class \fBButtonAssets\fP"
.br
.ti -1c
.RI "class \fBCrawlers\fP"
.br
.ti -1c
.RI "class \fBDefaultRoof\fP"
.br
.ti -1c
.RI "class \fBIcons\fP"
.br
.ti -1c
.RI "class \fBInventoryStyle\fP"
.br
.ti -1c
.RI "class \fBOrbitIcons\fP"
.br
.ti -1c
.RI "class \fBPopperSprites\fP"
.br
.ti -1c
.RI "class \fBRects\fP"
.br
.ti -1c
.RI "class \fBRenderers\fP"
.br
.ti -1c
.RI "class \fBStateIcons\fP"
.br
.ti -1c
.RI "class \fBTCs\fP"
.br
.ti -1c
.RI "class \fBTextureDatas\fP"
.br
.ti -1c
.RI "class \fBUDIconWeather\fP"
.br
.ti -1c
.RI "class \fBUDInvStyle\fP"
.br
.ti -1c
.RI "class \fBUDInvTab\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBInit\fP ()"
.br
.ti -1c
.RI "void \fBRefreshBGM\fP ()"
.br
.ti -1c
.RI "void \fBRebuildBGMList\fP ()"
.br
.ti -1c
.RI "void \fBRebuildSketchList\fP ()"
.br
.ti -1c
.RI "void \fBRebuildBiomeList\fP ()"
.br
.ti -1c
.RI "void \fBRebuildFireworks\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static string \fBGetArtDir\fP (int a)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBCoreRef\&.Biomes\fP \fBbiomes\fP"
.br
.ti -1c
.RI "\fBCoreRef\&.Crawlers\fP \fBcrawlers\fP"
.br
.ti -1c
.RI "\fBCoreRef\&.StateIcons\fP \fBstateIcons\fP"
.br
.ti -1c
.RI "\fBCoreRef\&.OrbitIcons\fP \fBorbitIcons\fP"
.br
.ti -1c
.RI "\fBCoreRef\&.ButtonAssets\fP \fBbuttonAssets\fP"
.br
.ti -1c
.RI "\fBCoreRef\&.PopperSprites\fP \fBpopperSprites\fP"
.br
.ti -1c
.RI "\fBCoreRef\&.TCs\fP \fBtcs\fP"
.br
.ti -1c
.RI "\fBCoreRef\&.Icons\fP \fBicons\fP"
.br
.ti -1c
.RI "\fBCoreRef\&.Renderers\fP \fBrenderers\fP"
.br
.ti -1c
.RI "\fBCoreRef\&.TextureDatas\fP \fBtextureData\fP"
.br
.ti -1c
.RI "\fBCoreRef\&.Rects\fP \fBrects\fP"
.br
.ti -1c
.RI "List< \fBEffect\fP > \fBfireworks\fP"
.br
.ti -1c
.RI "List< Sprite > \fBspritesCorner\fP"
.br
.ti -1c
.RI "List< Sprite > \fBicon_HotItem\fP"
.br
.ti -1c
.RI "List< SpriteAsset > \fBbg_msg\fP"
.br
.ti -1c
.RI "List< Sprite > \fBspritesHighlight\fP"
.br
.ti -1c
.RI "List< Sprite > \fBspritesHighlightSpeed\fP"
.br
.ti -1c
.RI "List< Sprite > \fBspritesPotential\fP"
.br
.ti -1c
.RI "List< Sprite > \fBspritesEmo\fP"
.br
.ti -1c
.RI "List< Sprite > \fBspritesContainerIcon\fP"
.br
.ti -1c
.RI "List< BGMData > \fBbgms\fP"
.br
.ti -1c
.RI "List< \fBCoreRef\&.DefaultRoof\fP > \fBdefaultRoofs\fP"
.br
.ti -1c
.RI "Dictionary< int, BGMData > \fBdictBGM\fP"
.br
.ti -1c
.RI "\fBCoreRef\&.UDInvStyle\fP \fBinvStyle\fP"
.br
.ti -1c
.RI "Sprite \fBspriteRecipe\fP"
.br
.ti -1c
.RI "Sprite \fBspriteNull\fP"
.br
.ti -1c
.RI "Sprite \fBspriteArea\fP"
.br
.ti -1c
.RI "Sprite \fBspriteNoIng\fP"
.br
.ti -1c
.RI "Sprite \fBspriteButtonGrid\fP"
.br
.ti -1c
.RI "Sprite \fBspriteButtonGridBad\fP"
.br
.ti -1c
.RI "Sprite \fBspriteThingActor\fP"
.br
.ti -1c
.RI "Sprite \fBspriteDefaultCondition\fP"
.br
.ti -1c
.RI "Material \fBmatUIObj\fP"
.br
.ti -1c
.RI "Material \fBmatUIPortraitChara\fP"
.br
.ti -1c
.RI "MsgColors \fBmsgColors\fP"
.br
.ti -1c
.RI "GameObject \fBdebugText\fP"
.br
.ti -1c
.RI "UD_Int_String \fBdictSketches\fP"
.br
.ti -1c
.RI "float \fBtestColor\fP"
.br
.ti -1c
.RI "float \fBtestColor2\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static string[] \fBArtDirs\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB7\fP of file \fBCoreRef\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "static string CoreRef\&.GetArtDir (int a)\fR [static]\fP"

.PP
Definition at line \fB77\fP of file \fBCoreRef\&.cs\fP\&.
.SS "void CoreRef\&.Init ()"

.PP
Definition at line \fB10\fP of file \fBCoreRef\&.cs\fP\&.
.SS "void CoreRef\&.RebuildBGMList ()"

.PP
Definition at line \fB32\fP of file \fBCoreRef\&.cs\fP\&.
.SS "void CoreRef\&.RebuildBiomeList ()"

.PP
Definition at line \fB83\fP of file \fBCoreRef\&.cs\fP\&.
.SS "void CoreRef\&.RebuildFireworks ()"

.PP
Definition at line \fB96\fP of file \fBCoreRef\&.cs\fP\&.
.SS "void CoreRef\&.RebuildSketchList ()"

.PP
Definition at line \fB61\fP of file \fBCoreRef\&.cs\fP\&.
.SS "void CoreRef\&.RefreshBGM ()"

.PP
Definition at line \fB20\fP of file \fBCoreRef\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "string [] CoreRef\&.ArtDirs\fR [static]\fP"
\fBInitial value:\fP
.nf
= new string[]
    {
        "000\-099",
        "100\-199 Elin",
        "200\-299 Elin Chara",
        "300\-399 Ylva Illust",
        "400\-499 Ylva Other",
        "500\-599 Ylva Wall",
        "600\-699 Kickstarter",
        "700\-799 Goods",
        "800\-899 Etc",
        "900\-999 MT"
    }
.PP
.fi

.PP
Definition at line \fB226\fP of file \fBCoreRef\&.cs\fP\&.
.SS "List<SpriteAsset> CoreRef\&.bg_msg"

.PP
Definition at line \fB151\fP of file \fBCoreRef\&.cs\fP\&.
.SS "List<BGMData> CoreRef\&.bgms"

.PP
Definition at line \fB169\fP of file \fBCoreRef\&.cs\fP\&.
.SS "\fBCoreRef\&.Biomes\fP CoreRef\&.biomes"

.PP
Definition at line \fB109\fP of file \fBCoreRef\&.cs\fP\&.
.SS "\fBCoreRef\&.ButtonAssets\fP CoreRef\&.buttonAssets"

.PP
Definition at line \fB121\fP of file \fBCoreRef\&.cs\fP\&.
.SS "\fBCoreRef\&.Crawlers\fP CoreRef\&.crawlers"

.PP
Definition at line \fB112\fP of file \fBCoreRef\&.cs\fP\&.
.SS "GameObject CoreRef\&.debugText"

.PP
Definition at line \fB214\fP of file \fBCoreRef\&.cs\fP\&.
.SS "List<\fBCoreRef\&.DefaultRoof\fP> CoreRef\&.defaultRoofs"

.PP
Definition at line \fB172\fP of file \fBCoreRef\&.cs\fP\&.
.SS "Dictionary<int, BGMData> CoreRef\&.dictBGM"

.PP
Definition at line \fB175\fP of file \fBCoreRef\&.cs\fP\&.
.SS "UD_Int_String CoreRef\&.dictSketches"

.PP
Definition at line \fB217\fP of file \fBCoreRef\&.cs\fP\&.
.SS "List<\fBEffect\fP> CoreRef\&.fireworks"

.PP
Definition at line \fB142\fP of file \fBCoreRef\&.cs\fP\&.
.SS "List<Sprite> CoreRef\&.icon_HotItem"

.PP
Definition at line \fB148\fP of file \fBCoreRef\&.cs\fP\&.
.SS "\fBCoreRef\&.Icons\fP CoreRef\&.icons"

.PP
Definition at line \fB130\fP of file \fBCoreRef\&.cs\fP\&.
.SS "\fBCoreRef\&.UDInvStyle\fP CoreRef\&.invStyle"

.PP
Definition at line \fB178\fP of file \fBCoreRef\&.cs\fP\&.
.SS "Material CoreRef\&.matUIObj"

.PP
Definition at line \fB205\fP of file \fBCoreRef\&.cs\fP\&.
.SS "Material CoreRef\&.matUIPortraitChara"

.PP
Definition at line \fB208\fP of file \fBCoreRef\&.cs\fP\&.
.SS "MsgColors CoreRef\&.msgColors"

.PP
Definition at line \fB211\fP of file \fBCoreRef\&.cs\fP\&.
.SS "\fBCoreRef\&.OrbitIcons\fP CoreRef\&.orbitIcons"

.PP
Definition at line \fB118\fP of file \fBCoreRef\&.cs\fP\&.
.SS "\fBCoreRef\&.PopperSprites\fP CoreRef\&.popperSprites"

.PP
Definition at line \fB124\fP of file \fBCoreRef\&.cs\fP\&.
.SS "\fBCoreRef\&.Rects\fP CoreRef\&.rects"

.PP
Definition at line \fB139\fP of file \fBCoreRef\&.cs\fP\&.
.SS "\fBCoreRef\&.Renderers\fP CoreRef\&.renderers"

.PP
Definition at line \fB133\fP of file \fBCoreRef\&.cs\fP\&.
.SS "Sprite CoreRef\&.spriteArea"

.PP
Definition at line \fB187\fP of file \fBCoreRef\&.cs\fP\&.
.SS "Sprite CoreRef\&.spriteButtonGrid"

.PP
Definition at line \fB193\fP of file \fBCoreRef\&.cs\fP\&.
.SS "Sprite CoreRef\&.spriteButtonGridBad"

.PP
Definition at line \fB196\fP of file \fBCoreRef\&.cs\fP\&.
.SS "Sprite CoreRef\&.spriteDefaultCondition"

.PP
Definition at line \fB202\fP of file \fBCoreRef\&.cs\fP\&.
.SS "Sprite CoreRef\&.spriteNoIng"

.PP
Definition at line \fB190\fP of file \fBCoreRef\&.cs\fP\&.
.SS "Sprite CoreRef\&.spriteNull"

.PP
Definition at line \fB184\fP of file \fBCoreRef\&.cs\fP\&.
.SS "Sprite CoreRef\&.spriteRecipe"

.PP
Definition at line \fB181\fP of file \fBCoreRef\&.cs\fP\&.
.SS "List<Sprite> CoreRef\&.spritesContainerIcon"

.PP
Definition at line \fB166\fP of file \fBCoreRef\&.cs\fP\&.
.SS "List<Sprite> CoreRef\&.spritesCorner"

.PP
Definition at line \fB145\fP of file \fBCoreRef\&.cs\fP\&.
.SS "List<Sprite> CoreRef\&.spritesEmo"

.PP
Definition at line \fB163\fP of file \fBCoreRef\&.cs\fP\&.
.SS "List<Sprite> CoreRef\&.spritesHighlight"

.PP
Definition at line \fB154\fP of file \fBCoreRef\&.cs\fP\&.
.SS "List<Sprite> CoreRef\&.spritesHighlightSpeed"

.PP
Definition at line \fB157\fP of file \fBCoreRef\&.cs\fP\&.
.SS "List<Sprite> CoreRef\&.spritesPotential"

.PP
Definition at line \fB160\fP of file \fBCoreRef\&.cs\fP\&.
.SS "Sprite CoreRef\&.spriteThingActor"

.PP
Definition at line \fB199\fP of file \fBCoreRef\&.cs\fP\&.
.SS "\fBCoreRef\&.StateIcons\fP CoreRef\&.stateIcons"

.PP
Definition at line \fB115\fP of file \fBCoreRef\&.cs\fP\&.
.SS "\fBCoreRef\&.TCs\fP CoreRef\&.tcs"

.PP
Definition at line \fB127\fP of file \fBCoreRef\&.cs\fP\&.
.SS "float CoreRef\&.testColor"

.PP
Definition at line \fB220\fP of file \fBCoreRef\&.cs\fP\&.
.SS "float CoreRef\&.testColor2"

.PP
Definition at line \fB223\fP of file \fBCoreRef\&.cs\fP\&.
.SS "\fBCoreRef\&.TextureDatas\fP CoreRef\&.textureData"

.PP
Definition at line \fB136\fP of file \fBCoreRef\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
