.TH "CoreDebug.MatColorTest" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CoreDebug.MatColorTest
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBUpdate\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBenable\fP"
.br
.ti -1c
.RI "Color \fBcolor\fP"
.br
.ti -1c
.RI "int \fBmatColor\fP"
.br
.ti -1c
.RI "\fBColorProfile\fP \fBprofile\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB2511\fP of file \fBCoreDebug\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void CoreDebug\&.MatColorTest\&.Update ()"

.PP
Definition at line \fB2514\fP of file \fBCoreDebug\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "Color CoreDebug\&.MatColorTest\&.color"

.PP
Definition at line \fB2531\fP of file \fBCoreDebug\&.cs\fP\&.
.SS "bool CoreDebug\&.MatColorTest\&.enable"

.PP
Definition at line \fB2528\fP of file \fBCoreDebug\&.cs\fP\&.
.SS "int CoreDebug\&.MatColorTest\&.matColor"

.PP
Definition at line \fB2534\fP of file \fBCoreDebug\&.cs\fP\&.
.SS "\fBColorProfile\fP CoreDebug\&.MatColorTest\&.profile"

.PP
Definition at line \fB2537\fP of file \fBCoreDebug\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
