.TH "CoreRef.OrbitIcons" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CoreRef.OrbitIcons
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Sprite \fBDefault\fP"
.br
.ti -1c
.RI "Sprite \fBSearch\fP"
.br
.ti -1c
.RI "Sprite \fBHostile\fP"
.br
.ti -1c
.RI "Sprite \fBGuest\fP"
.br
.ti -1c
.RI "Sprite \fBhealthCritical\fP"
.br
.ti -1c
.RI "Sprite \fBhealthDanger\fP"
.br
.ti -1c
.RI "Sprite \fBhealthLow\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB437\fP of file \fBCoreRef\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "Sprite CoreRef\&.OrbitIcons\&.Default"

.PP
Definition at line \fB440\fP of file \fBCoreRef\&.cs\fP\&.
.SS "Sprite CoreRef\&.OrbitIcons\&.Guest"

.PP
Definition at line \fB449\fP of file \fBCoreRef\&.cs\fP\&.
.SS "Sprite CoreRef\&.OrbitIcons\&.healthCritical"

.PP
Definition at line \fB452\fP of file \fBCoreRef\&.cs\fP\&.
.SS "Sprite CoreRef\&.OrbitIcons\&.healthDanger"

.PP
Definition at line \fB455\fP of file \fBCoreRef\&.cs\fP\&.
.SS "Sprite CoreRef\&.OrbitIcons\&.healthLow"

.PP
Definition at line \fB458\fP of file \fBCoreRef\&.cs\fP\&.
.SS "Sprite CoreRef\&.OrbitIcons\&.Hostile"

.PP
Definition at line \fB446\fP of file \fBCoreRef\&.cs\fP\&.
.SS "Sprite CoreRef\&.OrbitIcons\&.Search"

.PP
Definition at line \fB443\fP of file \fBCoreRef\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
