.TH "CoreConfig.SoundSetting" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CoreConfig.SoundSetting
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBvolumeMaster\fP"
.br
.ti -1c
.RI "float \fBvolumeBGM\fP"
.br
.ti -1c
.RI "float \fBvolumeSFX\fP"
.br
.ti -1c
.RI "float \fBvolumeAMB\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB875\fP of file \fBCoreConfig\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "float CoreConfig\&.SoundSetting\&.volumeAMB"

.PP
Definition at line \fB887\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "float CoreConfig\&.SoundSetting\&.volumeBGM"

.PP
Definition at line \fB881\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "float CoreConfig\&.SoundSetting\&.volumeMaster"

.PP
Definition at line \fB878\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "float CoreConfig\&.SoundSetting\&.volumeSFX"

.PP
Definition at line \fB884\fP of file \fBCoreConfig\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
