.TH "CoreRef.TCs" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CoreRef.TCs
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBTCText\fP \fBtext\fP"
.br
.ti -1c
.RI "\fBTCCensored\fP \fBcensored\fP"
.br
.ti -1c
.RI "\fBTCState\fP \fBstate\fP"
.br
.ti -1c
.RI "\fBTCSimpleText\fP \fBsimpleText\fP"
.br
.ti -1c
.RI "\fBTCSimpleText\fP \fBsimpleTextIcon\fP"
.br
.ti -1c
.RI "Sprite \fBspriteVisited\fP"
.br
.ti -1c
.RI "Sprite \fBspriteConquer\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB494\fP of file \fBCoreRef\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBTCCensored\fP CoreRef\&.TCs\&.censored"

.PP
Definition at line \fB500\fP of file \fBCoreRef\&.cs\fP\&.
.SS "\fBTCSimpleText\fP CoreRef\&.TCs\&.simpleText"

.PP
Definition at line \fB506\fP of file \fBCoreRef\&.cs\fP\&.
.SS "\fBTCSimpleText\fP CoreRef\&.TCs\&.simpleTextIcon"

.PP
Definition at line \fB509\fP of file \fBCoreRef\&.cs\fP\&.
.SS "Sprite CoreRef\&.TCs\&.spriteConquer"

.PP
Definition at line \fB515\fP of file \fBCoreRef\&.cs\fP\&.
.SS "Sprite CoreRef\&.TCs\&.spriteVisited"

.PP
Definition at line \fB512\fP of file \fBCoreRef\&.cs\fP\&.
.SS "\fBTCState\fP CoreRef\&.TCs\&.state"

.PP
Definition at line \fB503\fP of file \fBCoreRef\&.cs\fP\&.
.SS "\fBTCText\fP CoreRef\&.TCs\&.text"

.PP
Definition at line \fB497\fP of file \fBCoreRef\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
