.TH "CoreRef.StateIcons" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CoreRef.StateIcons
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBMultiSprite\fP \fBcombat\fP"
.br
.ti -1c
.RI "\fBMultiSprite\fP \fBsleep\fP"
.br
.ti -1c
.RI "\fBMultiSprite\fP \fBgather\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB415\fP of file \fBCoreRef\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBMultiSprite\fP CoreRef\&.StateIcons\&.combat"

.PP
Definition at line \fB418\fP of file \fBCoreRef\&.cs\fP\&.
.SS "\fBMultiSprite\fP CoreRef\&.StateIcons\&.gather"

.PP
Definition at line \fB424\fP of file \fBCoreRef\&.cs\fP\&.
.SS "\fBMultiSprite\fP CoreRef\&.StateIcons\&.sleep"

.PP
Definition at line \fB421\fP of file \fBCoreRef\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
