.TH "CoreConfig.GameConfig" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CoreConfig.GameConfig
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBautopause\fP"
.br
.ti -1c
.RI "bool \fBshowQuickMenuHint\fP"
.br
.ti -1c
.RI "bool \fBdontRenderOutsideMap\fP"
.br
.ti -1c
.RI "bool \fBfreePos\fP"
.br
.ti -1c
.RI "bool \fBshowOffhand\fP"
.br
.ti -1c
.RI "bool \fBconfirmGive\fP"
.br
.ti -1c
.RI "bool \fBconfirmMapExit\fP"
.br
.ti -1c
.RI "bool \fBholdMiddleButtonToHold\fP"
.br
.ti -1c
.RI "bool \fBdoubleClickToHold\fP"
.br
.ti -1c
.RI "bool \fBuseAbilityOnHotkey\fP"
.br
.ti -1c
.RI "float \fBrunDistance\fP"
.br
.ti -1c
.RI "float \fBangleMargin\fP"
.br
.ti -1c
.RI "int \fBnewlineCount\fP"
.br
.ti -1c
.RI "int \fBshowBorder\fP"
.br
.ti -1c
.RI "int \fBshowRide\fP"
.br
.ti -1c
.RI "int \fBwaiter\fP"
.br
.ti -1c
.RI "bool \fBaltUI\fP"
.br
.ti -1c
.RI "bool \fBaltInv\fP"
.br
.ti -1c
.RI "bool \fBaltAbility\fP"
.br
.ti -1c
.RI "bool \fBaltCraft\fP"
.br
.ti -1c
.RI "bool \fBautoSave\fP"
.br
.ti -1c
.RI "bool \fBalwaysUpdateRecipe\fP"
.br
.ti -1c
.RI "bool \fBshowInvBG\fP"
.br
.ti -1c
.RI "bool \fBuseGrid\fP"
.br
.ti -1c
.RI "bool \fBrightScroll\fP"
.br
.ti -1c
.RI "bool \fBtutorial\fP"
.br
.ti -1c
.RI "bool \fBadvancedMenu\fP"
.br
.ti -1c
.RI "bool \fBwarnCrime\fP"
.br
.ti -1c
.RI "bool \fBwarnMana\fP"
.br
.ti -1c
.RI "bool \fBwarnDisassemble\fP"
.br
.ti -1c
.RI "bool \fBhideWeapons\fP"
.br
.ti -1c
.RI "bool \fBbackupOnSave\fP"
.br
.ti -1c
.RI "bool \fBbackupOnFirstSave\fP"
.br
.ti -1c
.RI "bool \fBdisableAutoStairs\fP"
.br
.ti -1c
.RI "bool \fBsmoothPick\fP"
.br
.ti -1c
.RI "bool \fBmarkStack\fP"
.br
.ti -1c
.RI "bool \fBwaitOnRange\fP"
.br
.ti -1c
.RI "bool \fBwaitOnDebuff\fP"
.br
.ti -1c
.RI "bool \fBwaitOnMelee\fP"
.br
.ti -1c
.RI "bool \fBhighlightEnemy\fP"
.br
.ti -1c
.RI "bool \fBshowShippingResult\fP"
.br
.ti -1c
.RI "bool \fBshiftToUseNegativeAbilityOnSelf\fP"
.br
.ti -1c
.RI "bool \fBignoreWarnCrime\fP"
.br
.ti -1c
.RI "bool \fBignoreWarnMana\fP"
.br
.ti -1c
.RI "bool \fBignoreWarnDisassemble\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB664\fP of file \fBCoreConfig\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "bool CoreConfig\&.GameConfig\&.advancedMenu"

.PP
Definition at line \fB745\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "bool CoreConfig\&.GameConfig\&.altAbility"

.PP
Definition at line \fB721\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "bool CoreConfig\&.GameConfig\&.altCraft"

.PP
Definition at line \fB724\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "bool CoreConfig\&.GameConfig\&.altInv"

.PP
Definition at line \fB718\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "bool CoreConfig\&.GameConfig\&.altUI"

.PP
Definition at line \fB715\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "bool CoreConfig\&.GameConfig\&.alwaysUpdateRecipe"

.PP
Definition at line \fB730\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "float CoreConfig\&.GameConfig\&.angleMargin"

.PP
Definition at line \fB700\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "bool CoreConfig\&.GameConfig\&.autopause"

.PP
Definition at line \fB667\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "bool CoreConfig\&.GameConfig\&.autoSave"

.PP
Definition at line \fB727\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "bool CoreConfig\&.GameConfig\&.backupOnFirstSave"

.PP
Definition at line \fB763\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "bool CoreConfig\&.GameConfig\&.backupOnSave"

.PP
Definition at line \fB760\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "bool CoreConfig\&.GameConfig\&.confirmGive"

.PP
Definition at line \fB682\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "bool CoreConfig\&.GameConfig\&.confirmMapExit"

.PP
Definition at line \fB685\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "bool CoreConfig\&.GameConfig\&.disableAutoStairs"

.PP
Definition at line \fB766\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "bool CoreConfig\&.GameConfig\&.dontRenderOutsideMap"

.PP
Definition at line \fB673\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "bool CoreConfig\&.GameConfig\&.doubleClickToHold"

.PP
Definition at line \fB691\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "bool CoreConfig\&.GameConfig\&.freePos"

.PP
Definition at line \fB676\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "bool CoreConfig\&.GameConfig\&.hideWeapons"

.PP
Definition at line \fB757\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "bool CoreConfig\&.GameConfig\&.highlightEnemy"

.PP
Definition at line \fB784\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "bool CoreConfig\&.GameConfig\&.holdMiddleButtonToHold"

.PP
Definition at line \fB688\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "bool CoreConfig\&.GameConfig\&.ignoreWarnCrime"

.PP
Definition at line \fB795\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "bool CoreConfig\&.GameConfig\&.ignoreWarnDisassemble"

.PP
Definition at line \fB805\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "bool CoreConfig\&.GameConfig\&.ignoreWarnMana"

.PP
Definition at line \fB800\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "bool CoreConfig\&.GameConfig\&.markStack"

.PP
Definition at line \fB772\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "int CoreConfig\&.GameConfig\&.newlineCount"

.PP
Definition at line \fB703\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "bool CoreConfig\&.GameConfig\&.rightScroll"

.PP
Definition at line \fB739\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "float CoreConfig\&.GameConfig\&.runDistance"

.PP
Definition at line \fB697\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "bool CoreConfig\&.GameConfig\&.shiftToUseNegativeAbilityOnSelf"

.PP
Definition at line \fB790\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "int CoreConfig\&.GameConfig\&.showBorder"

.PP
Definition at line \fB706\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "bool CoreConfig\&.GameConfig\&.showInvBG"

.PP
Definition at line \fB733\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "bool CoreConfig\&.GameConfig\&.showOffhand"

.PP
Definition at line \fB679\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "bool CoreConfig\&.GameConfig\&.showQuickMenuHint"

.PP
Definition at line \fB670\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "int CoreConfig\&.GameConfig\&.showRide"

.PP
Definition at line \fB709\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "bool CoreConfig\&.GameConfig\&.showShippingResult"

.PP
Definition at line \fB787\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "bool CoreConfig\&.GameConfig\&.smoothPick"

.PP
Definition at line \fB769\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "bool CoreConfig\&.GameConfig\&.tutorial"

.PP
Definition at line \fB742\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "bool CoreConfig\&.GameConfig\&.useAbilityOnHotkey"

.PP
Definition at line \fB694\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "bool CoreConfig\&.GameConfig\&.useGrid"

.PP
Definition at line \fB736\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "int CoreConfig\&.GameConfig\&.waiter"

.PP
Definition at line \fB712\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "bool CoreConfig\&.GameConfig\&.waitOnDebuff"

.PP
Definition at line \fB778\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "bool CoreConfig\&.GameConfig\&.waitOnMelee"

.PP
Definition at line \fB781\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "bool CoreConfig\&.GameConfig\&.waitOnRange"

.PP
Definition at line \fB775\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "bool CoreConfig\&.GameConfig\&.warnCrime"

.PP
Definition at line \fB748\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "bool CoreConfig\&.GameConfig\&.warnDisassemble"

.PP
Definition at line \fB754\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "bool CoreConfig\&.GameConfig\&.warnMana"

.PP
Definition at line \fB751\fP of file \fBCoreConfig\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
