.TH "CoreConfig.BackerContentConfig" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CoreConfig.BackerContentConfig
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBShow\fP (int id)"
.br
.ti -1c
.RI "bool \fBShow\fP (\fBSourceBacker\&.Row\fP row)"
.br
.ti -1c
.RI "bool \fBShow\fP (string s)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBfilter\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "bool \fBFilterAll\fP\fR [get]\fP"
.br
.ti -1c
.RI "bool \fBFilterLang\fP\fR [get]\fP"
.br
.ti -1c
.RI "bool \fBFilterNone\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB1119\fP of file \fBCoreConfig\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "bool CoreConfig\&.BackerContentConfig\&.Show (int id)"

.PP
Definition at line \fB1152\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "bool CoreConfig\&.BackerContentConfig\&.Show (\fBSourceBacker\&.Row\fP row)"

.PP
Definition at line \fB1158\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "bool CoreConfig\&.BackerContentConfig\&.Show (string s)"

.PP
Definition at line \fB1182\fP of file \fBCoreConfig\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int CoreConfig\&.BackerContentConfig\&.filter"

.PP
Definition at line \fB1208\fP of file \fBCoreConfig\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "bool CoreConfig\&.BackerContentConfig\&.FilterAll\fR [get]\fP"

.PP
Definition at line \fB1123\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "bool CoreConfig\&.BackerContentConfig\&.FilterLang\fR [get]\fP"

.PP
Definition at line \fB1133\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "bool CoreConfig\&.BackerContentConfig\&.FilterNone\fR [get]\fP"

.PP
Definition at line \fB1143\fP of file \fBCoreConfig\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
