.TH "CoreRef.UDInvStyle" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CoreRef.UDInvStyle
.SH SYNOPSIS
.br
.PP
.PP
Inherits UDictionary< string, CoreRef\&.InventoryStyle >\&.
.SH "Detailed Description"
.PP 
Definition at line \fB254\fP of file \fBCoreRef\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
