.TH "Core" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Core
.SH SYNOPSIS
.br
.PP
.PP
Inherits BaseCore\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBStartCase\fP ()"
.br
.ti -1c
.RI "void \fBUpdate\fP ()"
.br
.ti -1c
.RI "void \fBOnApplicationFocus\fP (bool focus)"
.br
.ti -1c
.RI "void \fBOnApplicationQuit\fP ()"
.br
.ti -1c
.RI "void \fBResetRuntime\fP ()"
.br
.ti -1c
.RI "void \fBInit\fP ()"
.br
.ti -1c
.RI "void \fBQuit\fP ()"
.br
.ti -1c
.RI "override void \fBConsumeInput\fP ()"
.br
.ti -1c
.RI "void \fBSetReferences\fP ()"
.br
.ti -1c
.RI "void \fBSetReleaseMode\fP (ReleaseMode m)"
.br
.ti -1c
.RI "void \fBOnChangeResolution\fP ()"
.br
.ti -1c
.RI "void \fBHalt\fP ()"
.br
.ti -1c
.RI "override void \fBFreezeScreen\fP (float duration)"
.br
.ti -1c
.RI "override void \fBUnfreezeScreen\fP ()"
.br
.ti -1c
.RI "override void \fBRebuildBGMList\fP ()"
.br
.ti -1c
.RI "override void \fBStopEventSystem\fP (Component c, Action action, float duration=0\&.12f)"
.br
.ti -1c
.RI "override void \fBStopEventSystem\fP (float duration=0\&.2f)"
.br
.ti -1c
.RI "void \fBSetLang\fP (string langCode, bool force=false)"
.br
.ti -1c
.RI "void \fBApplySkins\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBCore\fP \fBSetCurrent\fP (\fBCore\fP _current=null)"
.br
.ti -1c
.RI "static \fBCore\fP \fBGetCurrent\fP ()"
.br
.ti -1c
.RI "static int[] \fBParseElements\fP (string str)"
.br
.ti -1c
.RI "static int \fBGetElement\fP (string id)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBCoreDebug\fP \fBdebug\fP"
.br
.ti -1c
.RI "\fBSourceManager\fP \fBsources\fP"
.br
.ti -1c
.RI "\fBPathManager\fP \fBpathManager\fP"
.br
.ti -1c
.RI "\fBEffectManager\fP \fBeffects\fP"
.br
.ti -1c
.RI "\fBModManager\fP \fBmods\fP = new \fBModManager\fP()"
.br
.ti -1c
.RI "PCCManager \fBpccs\fP"
.br
.ti -1c
.RI "SkinManager \fBskins\fP"
.br
.ti -1c
.RI "\fBTextureManager\fP \fBtextures\fP = new \fBTextureManager\fP()"
.br
.ti -1c
.RI "\fBGameSetting\fP \fBgameSetting\fP"
.br
.ti -1c
.RI "\fBGameData\fP \fBgamedata\fP"
.br
.ti -1c
.RI "\fBCoreRef\fP \fBrefs\fP"
.br
.ti -1c
.RI "\fBColorProfile\fP \fBColors\fP"
.br
.ti -1c
.RI "Material \fBmatUI\fP"
.br
.ti -1c
.RI "\fBSteam\fP \fBsteam\fP"
.br
.ti -1c
.RI "bool \fBuseUImat\fP"
.br
.ti -1c
.RI "bool \fBtrial\fP"
.br
.ti -1c
.RI "\fBUI\fP \fBui\fP"
.br
.ti -1c
.RI "\fBScene\fP \fBscene\fP"
.br
.ti -1c
.RI "\fBBaseGameScreen\fP \fBscreen\fP"
.br
.ti -1c
.RI "\fBCoreConfig\fP \fBconfig\fP"
.br
.ti -1c
.RI "\fBGame\fP \fBgame\fP"
.br
.ti -1c
.RI "bool \fBinitialized\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static new \fBCore\fP \fBInstance\fP"
.br
.ti -1c
.RI "static float \fBdelta\fP"
.br
.ti -1c
.RI "static float \fBavgDelta\fP"
.br
.ti -1c
.RI "static float \fBgameDelta\fP"
.br
.ti -1c
.RI "static float \fBgameDeltaNoPause\fP"
.br
.ti -1c
.RI "static bool \fBspiked\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBAwake\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "bool \fBIsGameStarted\fP\fR [get]\fP"
.br
.ti -1c
.RI "override float \fBuiScale\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB14\fP of file \fBCore\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Core\&.ApplySkins ()"

.PP
Definition at line \fB691\fP of file \fBCore\&.cs\fP\&.
.SS "override void Core\&.Awake ()\fR [protected]\fP"

.PP
Definition at line \fB37\fP of file \fBCore\&.cs\fP\&.
.SS "override void Core\&.ConsumeInput ()"

.PP
Definition at line \fB492\fP of file \fBCore\&.cs\fP\&.
.SS "override void Core\&.FreezeScreen (float duration)"

.PP
Definition at line \fB592\fP of file \fBCore\&.cs\fP\&.
.SS "static \fBCore\fP Core\&.GetCurrent ()\fR [static]\fP"

.PP
Definition at line \fB514\fP of file \fBCore\&.cs\fP\&.
.SS "static int Core\&.GetElement (string id)\fR [static]\fP"

.PP
Definition at line \fB670\fP of file \fBCore\&.cs\fP\&.
.SS "void Core\&.Halt ()"

.PP
Definition at line \fB587\fP of file \fBCore\&.cs\fP\&.
.SS "void Core\&.Init ()"

.PP
Definition at line \fB443\fP of file \fBCore\&.cs\fP\&.
.SS "void Core\&.OnApplicationFocus (bool focus)"

.PP
Definition at line \fB338\fP of file \fBCore\&.cs\fP\&.
.SS "void Core\&.OnApplicationQuit ()"

.PP
Definition at line \fB384\fP of file \fBCore\&.cs\fP\&.
.SS "void Core\&.OnChangeResolution ()"

.PP
Definition at line \fB569\fP of file \fBCore\&.cs\fP\&.
.SS "static int[] Core\&.ParseElements (string str)\fR [static]\fP"

.PP
Definition at line \fB652\fP of file \fBCore\&.cs\fP\&.
.SS "void Core\&.Quit ()"

.PP
Definition at line \fB485\fP of file \fBCore\&.cs\fP\&.
.SS "override void Core\&.RebuildBGMList ()"

.PP
Definition at line \fB604\fP of file \fBCore\&.cs\fP\&.
.SS "void Core\&.ResetRuntime ()"

.PP
Definition at line \fB430\fP of file \fBCore\&.cs\fP\&.
.SS "static \fBCore\fP Core\&.SetCurrent (\fBCore\fP _current = \fRnull\fP)\fR [static]\fP"

.PP
Definition at line \fB498\fP of file \fBCore\&.cs\fP\&.
.SS "void Core\&.SetLang (string langCode, bool force = \fRfalse\fP)"

.PP
Definition at line \fB633\fP of file \fBCore\&.cs\fP\&.
.SS "void Core\&.SetReferences ()"

.PP
Definition at line \fB520\fP of file \fBCore\&.cs\fP\&.
.SS "void Core\&.SetReleaseMode (ReleaseMode m)"

.PP
Definition at line \fB534\fP of file \fBCore\&.cs\fP\&.
.SS "void Core\&.StartCase ()"

.PP
Definition at line \fB167\fP of file \fBCore\&.cs\fP\&.
.SS "override void Core\&.StopEventSystem (Component c, Action action, float duration = \fR0::12f\fP)"

.PP
Definition at line \fB610\fP of file \fBCore\&.cs\fP\&.
.SS "override void Core\&.StopEventSystem (float duration = \fR0::2f\fP)"

.PP
Definition at line \fB623\fP of file \fBCore\&.cs\fP\&.
.SS "override void Core\&.UnfreezeScreen ()"

.PP
Definition at line \fB598\fP of file \fBCore\&.cs\fP\&.
.SS "void Core\&.Update ()"

.PP
Definition at line \fB236\fP of file \fBCore\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "float Core\&.avgDelta\fR [static]\fP"

.PP
Definition at line \fB707\fP of file \fBCore\&.cs\fP\&.
.SS "\fBColorProfile\fP Core\&.Colors"

.PP
Definition at line \fB755\fP of file \fBCore\&.cs\fP\&.
.SS "\fBCoreConfig\fP Core\&.config"

.PP
Definition at line \fB780\fP of file \fBCore\&.cs\fP\&.
.SS "\fBCoreDebug\fP Core\&.debug"

.PP
Definition at line \fB722\fP of file \fBCore\&.cs\fP\&.
.SS "float Core\&.delta\fR [static]\fP"

.PP
Definition at line \fB704\fP of file \fBCore\&.cs\fP\&.
.SS "\fBEffectManager\fP Core\&.effects"

.PP
Definition at line \fB731\fP of file \fBCore\&.cs\fP\&.
.SS "\fBGame\fP Core\&.game"

.PP
Definition at line \fB783\fP of file \fBCore\&.cs\fP\&.
.SS "\fBGameData\fP Core\&.gamedata"

.PP
Definition at line \fB749\fP of file \fBCore\&.cs\fP\&.
.SS "float Core\&.gameDelta\fR [static]\fP"

.PP
Definition at line \fB710\fP of file \fBCore\&.cs\fP\&.
.SS "float Core\&.gameDeltaNoPause\fR [static]\fP"

.PP
Definition at line \fB713\fP of file \fBCore\&.cs\fP\&.
.SS "\fBGameSetting\fP Core\&.gameSetting"

.PP
Definition at line \fB746\fP of file \fBCore\&.cs\fP\&.
.SS "bool Core\&.initialized"

.PP
Definition at line \fB787\fP of file \fBCore\&.cs\fP\&.
.SS "new \fBCore\fP Core\&.Instance\fR [static]\fP"

.PP
Definition at line \fB701\fP of file \fBCore\&.cs\fP\&.
.SS "Material Core\&.matUI"

.PP
Definition at line \fB758\fP of file \fBCore\&.cs\fP\&.
.SS "\fBModManager\fP Core\&.mods = new \fBModManager\fP()"

.PP
Definition at line \fB734\fP of file \fBCore\&.cs\fP\&.
.SS "\fBPathManager\fP Core\&.pathManager"

.PP
Definition at line \fB728\fP of file \fBCore\&.cs\fP\&.
.SS "PCCManager Core\&.pccs"

.PP
Definition at line \fB737\fP of file \fBCore\&.cs\fP\&.
.SS "\fBCoreRef\fP Core\&.refs"

.PP
Definition at line \fB752\fP of file \fBCore\&.cs\fP\&.
.SS "\fBScene\fP Core\&.scene"

.PP
Definition at line \fB773\fP of file \fBCore\&.cs\fP\&.
.SS "\fBBaseGameScreen\fP Core\&.screen"

.PP
Definition at line \fB776\fP of file \fBCore\&.cs\fP\&.
.SS "SkinManager Core\&.skins"

.PP
Definition at line \fB740\fP of file \fBCore\&.cs\fP\&.
.SS "\fBSourceManager\fP Core\&.sources"

.PP
Definition at line \fB725\fP of file \fBCore\&.cs\fP\&.
.SS "bool Core\&.spiked\fR [static]\fP"

.PP
Definition at line \fB716\fP of file \fBCore\&.cs\fP\&.
.SS "\fBSteam\fP Core\&.steam"

.PP
Definition at line \fB761\fP of file \fBCore\&.cs\fP\&.
.SS "\fBTextureManager\fP Core\&.textures = new \fBTextureManager\fP()"

.PP
Definition at line \fB743\fP of file \fBCore\&.cs\fP\&.
.SS "bool Core\&.trial"

.PP
Definition at line \fB767\fP of file \fBCore\&.cs\fP\&.
.SS "\fBUI\fP Core\&.ui"

.PP
Definition at line \fB770\fP of file \fBCore\&.cs\fP\&.
.SS "bool Core\&.useUImat"

.PP
Definition at line \fB764\fP of file \fBCore\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "bool Core\&.IsGameStarted\fR [get]\fP"

.PP
Definition at line \fB18\fP of file \fBCore\&.cs\fP\&.
.SS "override float Core\&.uiScale\fR [get]\fP"

.PP
Definition at line \fB28\fP of file \fBCore\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
