.TH "CoreConfig.Fix" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CoreConfig.Fix
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "CameraSupport\&.Divider \fBdivider\fP"
.br
.ti -1c
.RI "CoreConfig\&.ScreenSnapType \fBsnapType\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB1301\fP of file \fBCoreConfig\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "CameraSupport\&.Divider CoreConfig\&.Fix\&.divider"

.PP
Definition at line \fB1304\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "CoreConfig\&.ScreenSnapType CoreConfig\&.Fix\&.snapType"

.PP
Definition at line \fB1307\fP of file \fBCoreConfig\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
