.TH "CoreConfig.FontSetting" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CoreConfig.FontSetting
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "SkinManager\&.FontSaveData \fBfontUI\fP"
.br
.ti -1c
.RI "SkinManager\&.FontSaveData \fBfontChatbox\fP"
.br
.ti -1c
.RI "SkinManager\&.FontSaveData \fBfontBalloon\fP"
.br
.ti -1c
.RI "SkinManager\&.FontSaveData \fBfontDialog\fP"
.br
.ti -1c
.RI "SkinManager\&.FontSaveData \fBfontWidget\fP"
.br
.ti -1c
.RI "SkinManager\&.FontSaveData \fBfontNews\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB1068\fP of file \fBCoreConfig\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "SkinManager\&.FontSaveData CoreConfig\&.FontSetting\&.fontBalloon"

.PP
Definition at line \fB1077\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "SkinManager\&.FontSaveData CoreConfig\&.FontSetting\&.fontChatbox"

.PP
Definition at line \fB1074\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "SkinManager\&.FontSaveData CoreConfig\&.FontSetting\&.fontDialog"

.PP
Definition at line \fB1080\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "SkinManager\&.FontSaveData CoreConfig\&.FontSetting\&.fontNews"

.PP
Definition at line \fB1086\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "SkinManager\&.FontSaveData CoreConfig\&.FontSetting\&.fontUI"

.PP
Definition at line \fB1071\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "SkinManager\&.FontSaveData CoreConfig\&.FontSetting\&.fontWidget"

.PP
Definition at line \fB1083\fP of file \fBCoreConfig\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
