.TH "CoreConfig.CustomFont" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CoreConfig.CustomFont
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBid\fP"
.br
.ti -1c
.RI "string \fBname\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB1091\fP of file \fBCoreConfig\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "string CoreConfig\&.CustomFont\&.id"

.PP
Definition at line \fB1094\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "string CoreConfig\&.CustomFont\&.name"

.PP
Definition at line \fB1097\fP of file \fBCoreConfig\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
