.TH "CoreRef.Icons" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CoreRef.Icons
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Sprite \fBsuspend\fP"
.br
.ti -1c
.RI "Sprite \fBresume\fP"
.br
.ti -1c
.RI "Sprite \fBdelete\fP"
.br
.ti -1c
.RI "Sprite \fBgo\fP"
.br
.ti -1c
.RI "Sprite \fBtalk\fP"
.br
.ti -1c
.RI "Sprite \fBcaste\fP"
.br
.ti -1c
.RI "Sprite \fBhome\fP"
.br
.ti -1c
.RI "Sprite \fBwork\fP"
.br
.ti -1c
.RI "Sprite \fBuniformM\fP"
.br
.ti -1c
.RI "Sprite \fBuniformF\fP"
.br
.ti -1c
.RI "Sprite \fBinspect\fP"
.br
.ti -1c
.RI "Sprite \fBup\fP"
.br
.ti -1c
.RI "Sprite \fBdown\fP"
.br
.ti -1c
.RI "Sprite \fBtrash\fP"
.br
.ti -1c
.RI "Sprite \fBtrans\fP"
.br
.ti -1c
.RI "Sprite \fBnoHotItem\fP"
.br
.ti -1c
.RI "Sprite \fBdefaultHotItem\fP"
.br
.ti -1c
.RI "Sprite \fBdefaultAbility\fP"
.br
.ti -1c
.RI "Sprite \fBtargetSelf\fP"
.br
.ti -1c
.RI "Sprite \fBtargetAny\fP"
.br
.ti -1c
.RI "Sprite \fBmana\fP"
.br
.ti -1c
.RI "Sprite \fBstamina\fP"
.br
.ti -1c
.RI "Sprite \fBshared\fP"
.br
.ti -1c
.RI "Sprite \fBpersonal\fP"
.br
.ti -1c
.RI "\fBCoreRef\&.UDInvTab\fP \fBinvTab\fP"
.br
.ti -1c
.RI "\fBCoreRef\&.UDIconWeather\fP \fBweather\fP"
.br
.ti -1c
.RI "List< Sprite > \fBquality\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB286\fP of file \fBCoreRef\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "Sprite CoreRef\&.Icons\&.caste"

.PP
Definition at line \fB304\fP of file \fBCoreRef\&.cs\fP\&.
.SS "Sprite CoreRef\&.Icons\&.defaultAbility"

.PP
Definition at line \fB340\fP of file \fBCoreRef\&.cs\fP\&.
.SS "Sprite CoreRef\&.Icons\&.defaultHotItem"

.PP
Definition at line \fB337\fP of file \fBCoreRef\&.cs\fP\&.
.SS "Sprite CoreRef\&.Icons\&.delete"

.PP
Definition at line \fB295\fP of file \fBCoreRef\&.cs\fP\&.
.SS "Sprite CoreRef\&.Icons\&.down"

.PP
Definition at line \fB325\fP of file \fBCoreRef\&.cs\fP\&.
.SS "Sprite CoreRef\&.Icons\&.go"

.PP
Definition at line \fB298\fP of file \fBCoreRef\&.cs\fP\&.
.SS "Sprite CoreRef\&.Icons\&.home"

.PP
Definition at line \fB307\fP of file \fBCoreRef\&.cs\fP\&.
.SS "Sprite CoreRef\&.Icons\&.inspect"

.PP
Definition at line \fB319\fP of file \fBCoreRef\&.cs\fP\&.
.SS "\fBCoreRef\&.UDInvTab\fP CoreRef\&.Icons\&.invTab"

.PP
Definition at line \fB361\fP of file \fBCoreRef\&.cs\fP\&.
.SS "Sprite CoreRef\&.Icons\&.mana"

.PP
Definition at line \fB349\fP of file \fBCoreRef\&.cs\fP\&.
.SS "Sprite CoreRef\&.Icons\&.noHotItem"

.PP
Definition at line \fB334\fP of file \fBCoreRef\&.cs\fP\&.
.SS "Sprite CoreRef\&.Icons\&.personal"

.PP
Definition at line \fB358\fP of file \fBCoreRef\&.cs\fP\&.
.SS "List<Sprite> CoreRef\&.Icons\&.quality"

.PP
Definition at line \fB367\fP of file \fBCoreRef\&.cs\fP\&.
.SS "Sprite CoreRef\&.Icons\&.resume"

.PP
Definition at line \fB292\fP of file \fBCoreRef\&.cs\fP\&.
.SS "Sprite CoreRef\&.Icons\&.shared"

.PP
Definition at line \fB355\fP of file \fBCoreRef\&.cs\fP\&.
.SS "Sprite CoreRef\&.Icons\&.stamina"

.PP
Definition at line \fB352\fP of file \fBCoreRef\&.cs\fP\&.
.SS "Sprite CoreRef\&.Icons\&.suspend"

.PP
Definition at line \fB289\fP of file \fBCoreRef\&.cs\fP\&.
.SS "Sprite CoreRef\&.Icons\&.talk"

.PP
Definition at line \fB301\fP of file \fBCoreRef\&.cs\fP\&.
.SS "Sprite CoreRef\&.Icons\&.targetAny"

.PP
Definition at line \fB346\fP of file \fBCoreRef\&.cs\fP\&.
.SS "Sprite CoreRef\&.Icons\&.targetSelf"

.PP
Definition at line \fB343\fP of file \fBCoreRef\&.cs\fP\&.
.SS "Sprite CoreRef\&.Icons\&.trans"

.PP
Definition at line \fB331\fP of file \fBCoreRef\&.cs\fP\&.
.SS "Sprite CoreRef\&.Icons\&.trash"

.PP
Definition at line \fB328\fP of file \fBCoreRef\&.cs\fP\&.
.SS "Sprite CoreRef\&.Icons\&.uniformF"

.PP
Definition at line \fB316\fP of file \fBCoreRef\&.cs\fP\&.
.SS "Sprite CoreRef\&.Icons\&.uniformM"

.PP
Definition at line \fB313\fP of file \fBCoreRef\&.cs\fP\&.
.SS "Sprite CoreRef\&.Icons\&.up"

.PP
Definition at line \fB322\fP of file \fBCoreRef\&.cs\fP\&.
.SS "\fBCoreRef\&.UDIconWeather\fP CoreRef\&.Icons\&.weather"

.PP
Definition at line \fB364\fP of file \fBCoreRef\&.cs\fP\&.
.SS "Sprite CoreRef\&.Icons\&.work"

.PP
Definition at line \fB310\fP of file \fBCoreRef\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
