.TH "CoreConfig.UISetting" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CoreConfig.UISetting
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBdefaultTheme\fP"
.br
.ti -1c
.RI "bool \fBopenLastTab\fP"
.br
.ti -1c
.RI "bool \fBrightClickClose\fP"
.br
.ti -1c
.RI "bool \fBblur\fP"
.br
.ti -1c
.RI "bool \fBcornerHoard\fP"
.br
.ti -1c
.RI "bool \fBanimeWindow\fP"
.br
.ti -1c
.RI "bool \fBautoscale\fP"
.br
.ti -1c
.RI "bool \fBdynamicBrightness\fP"
.br
.ti -1c
.RI "bool \fBsecureMinWidth\fP"
.br
.ti -1c
.RI "bool \fBautoFocusWindow\fP"
.br
.ti -1c
.RI "bool \fBshowFloatButtons\fP"
.br
.ti -1c
.RI "bool \fBballoonBG\fP"
.br
.ti -1c
.RI "float \fBscrollSens\fP"
.br
.ti -1c
.RI "float \fBbaseScrollSens\fP"
.br
.ti -1c
.RI "float \fBblurSize\fP"
.br
.ti -1c
.RI "float \fBdynamicBrightnessMod\fP"
.br
.ti -1c
.RI "int \fBmouseDragMargin\fP"
.br
.ti -1c
.RI "int \fBscale\fP"
.br
.ti -1c
.RI "int \fBbrightness\fP"
.br
.ti -1c
.RI "int \fBcontrast\fP"
.br
.ti -1c
.RI "int \fBoutlineAlpha\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "float \fBScrollSensitivity\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB990\fP of file \fBCoreConfig\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "bool CoreConfig\&.UISetting\&.animeWindow"

.PP
Definition at line \fB1018\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "bool CoreConfig\&.UISetting\&.autoFocusWindow"

.PP
Definition at line \fB1030\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "bool CoreConfig\&.UISetting\&.autoscale"

.PP
Definition at line \fB1021\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "bool CoreConfig\&.UISetting\&.balloonBG"

.PP
Definition at line \fB1036\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "float CoreConfig\&.UISetting\&.baseScrollSens"

.PP
Definition at line \fB1042\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "bool CoreConfig\&.UISetting\&.blur"

.PP
Definition at line \fB1012\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "float CoreConfig\&.UISetting\&.blurSize"

.PP
Definition at line \fB1045\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "int CoreConfig\&.UISetting\&.brightness"

.PP
Definition at line \fB1057\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "int CoreConfig\&.UISetting\&.contrast"

.PP
Definition at line \fB1060\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "bool CoreConfig\&.UISetting\&.cornerHoard"

.PP
Definition at line \fB1015\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "string CoreConfig\&.UISetting\&.defaultTheme"

.PP
Definition at line \fB1003\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "bool CoreConfig\&.UISetting\&.dynamicBrightness"

.PP
Definition at line \fB1024\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "float CoreConfig\&.UISetting\&.dynamicBrightnessMod"

.PP
Definition at line \fB1048\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "int CoreConfig\&.UISetting\&.mouseDragMargin"

.PP
Definition at line \fB1051\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "bool CoreConfig\&.UISetting\&.openLastTab"

.PP
Definition at line \fB1006\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "int CoreConfig\&.UISetting\&.outlineAlpha"

.PP
Definition at line \fB1063\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "bool CoreConfig\&.UISetting\&.rightClickClose"

.PP
Definition at line \fB1009\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "int CoreConfig\&.UISetting\&.scale"

.PP
Definition at line \fB1054\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "float CoreConfig\&.UISetting\&.scrollSens"

.PP
Definition at line \fB1039\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "bool CoreConfig\&.UISetting\&.secureMinWidth"

.PP
Definition at line \fB1027\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "bool CoreConfig\&.UISetting\&.showFloatButtons"

.PP
Definition at line \fB1033\fP of file \fBCoreConfig\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "float CoreConfig\&.UISetting\&.ScrollSensitivity\fR [get]\fP"

.PP
Definition at line \fB994\fP of file \fBCoreConfig\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
