.TH "CoreRef.Biomes" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CoreRef.Biomes
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBUD_Biome\fP \fBdict\fP"
.br
.ti -1c
.RI "\fBBiomeProfile\fP \fBPlain\fP"
.br
.ti -1c
.RI "\fBBiomeProfile\fP \fBSand\fP"
.br
.ti -1c
.RI "\fBBiomeProfile\fP \fBWater\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB372\fP of file \fBCoreRef\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBUD_Biome\fP CoreRef\&.Biomes\&.dict"

.PP
Definition at line \fB375\fP of file \fBCoreRef\&.cs\fP\&.
.SS "\fBBiomeProfile\fP CoreRef\&.Biomes\&.Plain"

.PP
Definition at line \fB378\fP of file \fBCoreRef\&.cs\fP\&.
.SS "\fBBiomeProfile\fP CoreRef\&.Biomes\&.Sand"

.PP
Definition at line \fB381\fP of file \fBCoreRef\&.cs\fP\&.
.SS "\fBBiomeProfile\fP CoreRef\&.Biomes\&.Water"

.PP
Definition at line \fB384\fP of file \fBCoreRef\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
