.TH "CoreRef.InventoryStyle" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CoreRef.InventoryStyle
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Sprite \fBbg\fP"
.br
.ti -1c
.RI "Vector2 \fBsizeDelta\fP"
.br
.ti -1c
.RI "Vector2 \fBgridSize\fP"
.br
.ti -1c
.RI "Vector2 \fBsizeContainer\fP"
.br
.ti -1c
.RI "Vector2 \fBposFix\fP"
.br
.ti -1c
.RI "Color \fBgridColor\fP"
.br
.ti -1c
.RI "SoundData \fBsound\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB260\fP of file \fBCoreRef\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "Sprite CoreRef\&.InventoryStyle\&.bg"

.PP
Definition at line \fB263\fP of file \fBCoreRef\&.cs\fP\&.
.SS "Color CoreRef\&.InventoryStyle\&.gridColor"

.PP
Definition at line \fB278\fP of file \fBCoreRef\&.cs\fP\&.
.SS "Vector2 CoreRef\&.InventoryStyle\&.gridSize"

.PP
Definition at line \fB269\fP of file \fBCoreRef\&.cs\fP\&.
.SS "Vector2 CoreRef\&.InventoryStyle\&.posFix"

.PP
Definition at line \fB275\fP of file \fBCoreRef\&.cs\fP\&.
.SS "Vector2 CoreRef\&.InventoryStyle\&.sizeContainer"

.PP
Definition at line \fB272\fP of file \fBCoreRef\&.cs\fP\&.
.SS "Vector2 CoreRef\&.InventoryStyle\&.sizeDelta"

.PP
Definition at line \fB266\fP of file \fBCoreRef\&.cs\fP\&.
.SS "SoundData CoreRef\&.InventoryStyle\&.sound"

.PP
Definition at line \fB281\fP of file \fBCoreRef\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
