.TH "CoreRef.ButtonAssets" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CoreRef.ButtonAssets
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Sprite \fBbgDefault\fP"
.br
.ti -1c
.RI "Sprite \fBbgNew\fP"
.br
.ti -1c
.RI "Sprite \fBbgSuperior\fP"
.br
.ti -1c
.RI "Sprite \fBbgLegendary\fP"
.br
.ti -1c
.RI "Sprite \fBbgMythical\fP"
.br
.ti -1c
.RI "Sprite \fBbgArtifact\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB471\fP of file \fBCoreRef\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "Sprite CoreRef\&.ButtonAssets\&.bgArtifact"

.PP
Definition at line \fB489\fP of file \fBCoreRef\&.cs\fP\&.
.SS "Sprite CoreRef\&.ButtonAssets\&.bgDefault"

.PP
Definition at line \fB474\fP of file \fBCoreRef\&.cs\fP\&.
.SS "Sprite CoreRef\&.ButtonAssets\&.bgLegendary"

.PP
Definition at line \fB483\fP of file \fBCoreRef\&.cs\fP\&.
.SS "Sprite CoreRef\&.ButtonAssets\&.bgMythical"

.PP
Definition at line \fB486\fP of file \fBCoreRef\&.cs\fP\&.
.SS "Sprite CoreRef\&.ButtonAssets\&.bgNew"

.PP
Definition at line \fB477\fP of file \fBCoreRef\&.cs\fP\&.
.SS "Sprite CoreRef\&.ButtonAssets\&.bgSuperior"

.PP
Definition at line \fB480\fP of file \fBCoreRef\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
