.TH "CoreConfig.NetSetting" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CoreConfig.NetSetting
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBenable\fP"
.br
.ti -1c
.RI "bool \fBsendEvent\fP"
.br
.ti -1c
.RI "bool \fBreceiveRealtime\fP"
.br
.ti -1c
.RI "bool \fBpassword\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB1102\fP of file \fBCoreConfig\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "bool CoreConfig\&.NetSetting\&.enable"

.PP
Definition at line \fB1105\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "bool CoreConfig\&.NetSetting\&.password"

.PP
Definition at line \fB1114\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "bool CoreConfig\&.NetSetting\&.receiveRealtime"

.PP
Definition at line \fB1111\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "bool CoreConfig\&.NetSetting\&.sendEvent"

.PP
Definition at line \fB1108\fP of file \fBCoreConfig\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
