.TH "CoreConfig.CameraConfig" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CoreConfig.CameraConfig
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBinvertX\fP"
.br
.ti -1c
.RI "bool \fBinvertY\fP"
.br
.ti -1c
.RI "bool \fBedgeScroll\fP"
.br
.ti -1c
.RI "bool \fBzoomToMouse\fP"
.br
.ti -1c
.RI "bool \fBextendZoomMin\fP"
.br
.ti -1c
.RI "bool \fBextendZoomMax\fP"
.br
.ti -1c
.RI "bool \fBlinearZoom\fP"
.br
.ti -1c
.RI "bool \fBsmoothFollow\fP"
.br
.ti -1c
.RI "bool \fBsmoothMove\fP"
.br
.ti -1c
.RI "float \fBsenseKeyboard\fP"
.br
.ti -1c
.RI "float \fBsensEdge\fP"
.br
.ti -1c
.RI "float \fBsensDrag\fP"
.br
.ti -1c
.RI "float \fBmomentum\fP"
.br
.ti -1c
.RI "float \fBzoomSpeed\fP"
.br
.ti -1c
.RI "int \fBdefaultZoom\fP"
.br
.ti -1c
.RI "int \fBmoveframe\fP"
.br
.ti -1c
.RI "float[] \fBzooms\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB608\fP of file \fBCoreConfig\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int CoreConfig\&.CameraConfig\&.defaultZoom"

.PP
Definition at line \fB653\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "bool CoreConfig\&.CameraConfig\&.edgeScroll"

.PP
Definition at line \fB617\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "bool CoreConfig\&.CameraConfig\&.extendZoomMax"

.PP
Definition at line \fB626\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "bool CoreConfig\&.CameraConfig\&.extendZoomMin"

.PP
Definition at line \fB623\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "bool CoreConfig\&.CameraConfig\&.invertX"

.PP
Definition at line \fB611\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "bool CoreConfig\&.CameraConfig\&.invertY"

.PP
Definition at line \fB614\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "bool CoreConfig\&.CameraConfig\&.linearZoom"

.PP
Definition at line \fB629\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "float CoreConfig\&.CameraConfig\&.momentum"

.PP
Definition at line \fB647\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "int CoreConfig\&.CameraConfig\&.moveframe"

.PP
Definition at line \fB656\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "float CoreConfig\&.CameraConfig\&.sensDrag"

.PP
Definition at line \fB644\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "float CoreConfig\&.CameraConfig\&.sensEdge"

.PP
Definition at line \fB641\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "float CoreConfig\&.CameraConfig\&.senseKeyboard"

.PP
Definition at line \fB638\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "bool CoreConfig\&.CameraConfig\&.smoothFollow"

.PP
Definition at line \fB632\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "bool CoreConfig\&.CameraConfig\&.smoothMove"

.PP
Definition at line \fB635\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "float [] CoreConfig\&.CameraConfig\&.zooms"

.PP
Definition at line \fB659\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "float CoreConfig\&.CameraConfig\&.zoomSpeed"

.PP
Definition at line \fB650\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "bool CoreConfig\&.CameraConfig\&.zoomToMouse"

.PP
Definition at line \fB620\fP of file \fBCoreConfig\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
