.TH "CoreRef.Renderers" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CoreRef.Renderers
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBRenderData\fP \fBpcc\fP"
.br
.ti -1c
.RI "\fBRenderData\fP \fBpcc_L\fP"
.br
.ti -1c
.RI "\fBRenderData\fP \fBobj_wheat\fP"
.br
.ti -1c
.RI "\fBRenderData\fP \fBobjS_flat\fP"
.br
.ti -1c
.RI "\fBRenderData\fP \fBobjL_harvest\fP"
.br
.ti -1c
.RI "\fBRenderData\fP \fBobj_paint\fP"
.br
.ti -1c
.RI "\fBRenderData\fP \fBobjs_shrine\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB579\fP of file \fBCoreRef\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBRenderData\fP CoreRef\&.Renderers\&.obj_paint"

.PP
Definition at line \fB597\fP of file \fBCoreRef\&.cs\fP\&.
.SS "\fBRenderData\fP CoreRef\&.Renderers\&.obj_wheat"

.PP
Definition at line \fB588\fP of file \fBCoreRef\&.cs\fP\&.
.SS "\fBRenderData\fP CoreRef\&.Renderers\&.objL_harvest"

.PP
Definition at line \fB594\fP of file \fBCoreRef\&.cs\fP\&.
.SS "\fBRenderData\fP CoreRef\&.Renderers\&.objS_flat"

.PP
Definition at line \fB591\fP of file \fBCoreRef\&.cs\fP\&.
.SS "\fBRenderData\fP CoreRef\&.Renderers\&.objs_shrine"

.PP
Definition at line \fB600\fP of file \fBCoreRef\&.cs\fP\&.
.SS "\fBRenderData\fP CoreRef\&.Renderers\&.pcc"

.PP
Definition at line \fB582\fP of file \fBCoreRef\&.cs\fP\&.
.SS "\fBRenderData\fP CoreRef\&.Renderers\&.pcc_L"

.PP
Definition at line \fB585\fP of file \fBCoreRef\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
