.TH "CoreRef.TextureDatas" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CoreRef.TextureDatas
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBTextureData\fP \fBblock\fP"
.br
.ti -1c
.RI "\fBTextureData\fP \fBblock_snow\fP"
.br
.ti -1c
.RI "\fBTextureData\fP \fBfloor\fP"
.br
.ti -1c
.RI "\fBTextureData\fP \fBfloor_snow\fP"
.br
.ti -1c
.RI "\fBTextureData\fP \fBobjs\fP"
.br
.ti -1c
.RI "\fBTextureData\fP \fBobjs_snow\fP"
.br
.ti -1c
.RI "\fBTextureData\fP \fBobjs_S\fP"
.br
.ti -1c
.RI "\fBTextureData\fP \fBobjs_S_snow\fP"
.br
.ti -1c
.RI "\fBTextureData\fP \fBobjs_L\fP"
.br
.ti -1c
.RI "\fBTextureData\fP \fBobjs_L_snow\fP"
.br
.ti -1c
.RI "\fBTextureData\fP \fBobjs_C\fP"
.br
.ti -1c
.RI "\fBTextureData\fP \fBobjs_CLL\fP"
.br
.ti -1c
.RI "\fBTextureData\fP \fBshadows\fP"
.br
.ti -1c
.RI "\fBTextureData\fP \fBfov\fP"
.br
.ti -1c
.RI "\fBTextureData\fP \fBworld\fP"
.br
.ti -1c
.RI "\fBTextureData\fP \fBroofs\fP"
.br
.ti -1c
.RI "\fBTextureData\fP \fBobjs_SS\fP"
.br
.ti -1c
.RI "\fBTextureData\fP \fBbird\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB520\fP of file \fBCoreRef\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBTextureData\fP CoreRef\&.TextureDatas\&.bird"

.PP
Definition at line \fB574\fP of file \fBCoreRef\&.cs\fP\&.
.SS "\fBTextureData\fP CoreRef\&.TextureDatas\&.block"

.PP
Definition at line \fB523\fP of file \fBCoreRef\&.cs\fP\&.
.SS "\fBTextureData\fP CoreRef\&.TextureDatas\&.block_snow"

.PP
Definition at line \fB526\fP of file \fBCoreRef\&.cs\fP\&.
.SS "\fBTextureData\fP CoreRef\&.TextureDatas\&.floor"

.PP
Definition at line \fB529\fP of file \fBCoreRef\&.cs\fP\&.
.SS "\fBTextureData\fP CoreRef\&.TextureDatas\&.floor_snow"

.PP
Definition at line \fB532\fP of file \fBCoreRef\&.cs\fP\&.
.SS "\fBTextureData\fP CoreRef\&.TextureDatas\&.fov"

.PP
Definition at line \fB562\fP of file \fBCoreRef\&.cs\fP\&.
.SS "\fBTextureData\fP CoreRef\&.TextureDatas\&.objs"

.PP
Definition at line \fB535\fP of file \fBCoreRef\&.cs\fP\&.
.SS "\fBTextureData\fP CoreRef\&.TextureDatas\&.objs_C"

.PP
Definition at line \fB553\fP of file \fBCoreRef\&.cs\fP\&.
.SS "\fBTextureData\fP CoreRef\&.TextureDatas\&.objs_CLL"

.PP
Definition at line \fB556\fP of file \fBCoreRef\&.cs\fP\&.
.SS "\fBTextureData\fP CoreRef\&.TextureDatas\&.objs_L"

.PP
Definition at line \fB547\fP of file \fBCoreRef\&.cs\fP\&.
.SS "\fBTextureData\fP CoreRef\&.TextureDatas\&.objs_L_snow"

.PP
Definition at line \fB550\fP of file \fBCoreRef\&.cs\fP\&.
.SS "\fBTextureData\fP CoreRef\&.TextureDatas\&.objs_S"

.PP
Definition at line \fB541\fP of file \fBCoreRef\&.cs\fP\&.
.SS "\fBTextureData\fP CoreRef\&.TextureDatas\&.objs_S_snow"

.PP
Definition at line \fB544\fP of file \fBCoreRef\&.cs\fP\&.
.SS "\fBTextureData\fP CoreRef\&.TextureDatas\&.objs_snow"

.PP
Definition at line \fB538\fP of file \fBCoreRef\&.cs\fP\&.
.SS "\fBTextureData\fP CoreRef\&.TextureDatas\&.objs_SS"

.PP
Definition at line \fB571\fP of file \fBCoreRef\&.cs\fP\&.
.SS "\fBTextureData\fP CoreRef\&.TextureDatas\&.roofs"

.PP
Definition at line \fB568\fP of file \fBCoreRef\&.cs\fP\&.
.SS "\fBTextureData\fP CoreRef\&.TextureDatas\&.shadows"

.PP
Definition at line \fB559\fP of file \fBCoreRef\&.cs\fP\&.
.SS "\fBTextureData\fP CoreRef\&.TextureDatas\&.world"

.PP
Definition at line \fB565\fP of file \fBCoreRef\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
