.TH "CoreDebug.DebugCommand" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CoreDebug.DebugCommand
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Action \fBaction\fP"
.br
.ti -1c
.RI "int \fBcat\fP"
.br
.ti -1c
.RI "string \fBname\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB2541\fP of file \fBCoreDebug\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "Action CoreDebug\&.DebugCommand\&.action"

.PP
Definition at line \fB2544\fP of file \fBCoreDebug\&.cs\fP\&.
.SS "int CoreDebug\&.DebugCommand\&.cat"

.PP
Definition at line \fB2547\fP of file \fBCoreDebug\&.cs\fP\&.
.SS "string CoreDebug\&.DebugCommand\&.name"

.PP
Definition at line \fB2550\fP of file \fBCoreDebug\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
