.TH "CoreDebug" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CoreDebug
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBEScriptable\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDebugCommand\fP"
.br
.ti -1c
.RI "class \fBMatColorTest\fP"
.br
.ti -1c
.RI "class \fBStartSetting\fP"
.br
.in -1c
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBDebugHotkey\fP { \fBNone\fP, \fBBlock\fP, \fBItem\fP, \fBDecal\fP, \fBAct\fP, \fBTest\fP, \fBAnime\fP }"
.br
.ti -1c
.RI "enum \fBStartLoadout\fP { \fBNew\fP, \fBAllItem\fP, \fBFewItem\fP }"
.br
.ti -1c
.RI "enum \fBStartParty\fP { \fBNone\fP, \fBFarris\fP, \fBFull\fP }"
.br
.ti -1c
.RI "enum \fBStartScene\fP { \fBTitle\fP, \fBZone\fP, \fBHome\fP, \fBHome_Cave\fP, \fBStory_Test\fP, \fBMeetFarris\fP, \fBNymelleBoss\fP, \fBAfterNymelle\fP, \fBMelilith\fP, \fBTefra\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBInit\fP ()"
.br
.ti -1c
.RI "void \fBQuickStart\fP ()"
.br
.ti -1c
.RI "void \fBOnLoad\fP ()"
.br
.ti -1c
.RI "void \fBAddAllRecipes\fP ()"
.br
.ti -1c
.RI "void \fBSetStartStockpile\fP (\fBThing\fP container, int num=100)"
.br
.ti -1c
.RI "\fBThing\fP \fBGetOrCreateDebugContainer\fP ()"
.br
.ti -1c
.RI "\fBThing\fP \fBGetDebugContainer\fP ()"
.br
.ti -1c
.RI "void \fBEnableDebugResource\fP ()"
.br
.ti -1c
.RI "void \fBSpawnCheatContainer\fP ()"
.br
.ti -1c
.RI "void \fBUpdateAlways\fP ()"
.br
.ti -1c
.RI "void \fBValidateData\fP ()"
.br
.ti -1c
.RI "void \fBUpdateInput\fP ()"
.br
.ti -1c
.RI "void \fBInitDebugCommands\fP ()"
.br
.ti -1c
.RI "void \fBTest_Grow\fP ()"
.br
.ti -1c
.RI "void \fBTest_GodTalk\fP ()"
.br
.ti -1c
.RI "void \fBCOM_Teleport\fP ()"
.br
.ti -1c
.RI "void \fBCOM_PlayStartDrama\fP ()"
.br
.ti -1c
.RI "void \fBTest_Filter\fP ()"
.br
.ti -1c
.RI "void \fBLOG_Spatials\fP ()"
.br
.ti -1c
.RI "void \fBTest_SiegeGuard\fP ()"
.br
.ti -1c
.RI "void \fBTest_Siege\fP ()"
.br
.ti -1c
.RI "void \fBCOM_MaxConstruction\fP ()"
.br
.ti -1c
.RI "void \fBLog\fP (object o)"
.br
.ti -1c
.RI "void \fBNextBGM\fP ()"
.br
.ti -1c
.RI "void \fBToggleRevealMap\fP ()"
.br
.ti -1c
.RI "void \fBLoadBroadcast\fP ()"
.br
.ti -1c
.RI "void \fBBroadcastNext\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBCheatEnabled\fP ()"
.br
.ti -1c
.RI "static string \fBCheat\fP ()"
.br
.ti -1c
.RI "static string \fBFix_RemoveDuplicateUnique\fP ()"
.br
.ti -1c
.RI "static string \fBFix_EtherDisease\fP ()"
.br
.ti -1c
.RI "static string \fBListChara\fP ()"
.br
.ti -1c
.RI "static string \fBListThing\fP ()"
.br
.ti -1c
.RI "static string \fBSetElement\fP (string alias, int value, int potential=100)"
.br
.ti -1c
.RI "static string \fBSpawn\fP (string id, int num=1)"
.br
.ti -1c
.RI "static string \fBTestSpawn\fP (int lv, int num)"
.br
.ti -1c
.RI "static string \fBResetPetUpgrades\fP ()"
.br
.ti -1c
.RI "static string \fBGodMode\fP ()"
.br
.ti -1c
.RI "static string \fBModFame\fP (int amount)"
.br
.ti -1c
.RI "static string \fBModKarma\fP (int amount)"
.br
.ti -1c
.RI "static string \fBModContribution\fP (int amount)"
.br
.ti -1c
.RI "static string \fBFlyMode\fP ()"
.br
.ti -1c
.RI "static string \fBChangeRace\fP (string id='?')"
.br
.ti -1c
.RI "static string \fBChangeJob\fP (string id='?')"
.br
.ti -1c
.RI "static string \fBFirstAdventurer\fP ()"
.br
.ti -1c
.RI "static string \fBAllRecipe\fP (bool forget=false)"
.br
.ti -1c
.RI "static string \fBLastWish\fP (string name)"
.br
.ti -1c
.RI "static string \fBClearLastWishFlag\fP ()"
.br
.ti -1c
.RI "static string \fBResource\fP ()"
.br
.in -1c

Static Public Member Functions inherited from \fBEScriptable\fP
.in +1c
.ti -1c
.RI "static int \fBrnd\fP (int a)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "CoreDebug\&.StartScene \fBstartScene\fP"
.br
.ti -1c
.RI "CoreDebug\&.StartLoadout \fBstartLoadout\fP"
.br
.ti -1c
.RI "CoreDebug\&.StartParty \fBstartParty\fP"
.br
.ti -1c
.RI "int \fBstartHour\fP"
.br
.ti -1c
.RI "\fBCoreDebug\&.StartSetting\fP \fBstartSetting\fP"
.br
.ti -1c
.RI "string \fBstartZone\fP"
.br
.ti -1c
.RI "bool \fBshowSceneSelector\fP"
.br
.ti -1c
.RI "bool \fBskipModSync\fP"
.br
.ti -1c
.RI "Lang\&.LangCode \fBlangCode\fP"
.br
.ti -1c
.RI "bool \fBignorePool\fP"
.br
.ti -1c
.RI "bool \fBresetPlayerConfig\fP"
.br
.ti -1c
.RI "bool \fBdontUseThread\fP"
.br
.ti -1c
.RI "bool \fBuseNewConfig\fP"
.br
.ti -1c
.RI "bool \fBignoreAutoSave\fP"
.br
.ti -1c
.RI "bool \fBalwaysResetWindow\fP"
.br
.ti -1c
.RI "bool \fBvalidateData\fP"
.br
.ti -1c
.RI "bool \fBdontCompressSave\fP"
.br
.ti -1c
.RI "bool \fBskipMod\fP"
.br
.ti -1c
.RI "string \fBcommand\fP"
.br
.ti -1c
.RI "bool \fBdebugInput\fP"
.br
.ti -1c
.RI "bool \fBkeypadDebug\fP"
.br
.ti -1c
.RI "CoreDebug\&.DebugHotkey \fBdebugHotkeys\fP"
.br
.ti -1c
.RI "int \fBadvanceMin\fP"
.br
.ti -1c
.RI "bool \fBtestLOS\fP"
.br
.ti -1c
.RI "bool \fBtestLOS2\fP"
.br
.ti -1c
.RI "bool \fBdebugProps\fP"
.br
.ti -1c
.RI "bool \fBrevealMap\fP"
.br
.ti -1c
.RI "bool \fBdebugHoard\fP"
.br
.ti -1c
.RI "bool \fBrevealInner\fP"
.br
.ti -1c
.RI "bool \fBignorePopup\fP"
.br
.ti -1c
.RI "bool \fBskipEvent\fP"
.br
.ti -1c
.RI "bool \fBskipNerun\fP"
.br
.ti -1c
.RI "bool \fBshowTone\fP"
.br
.ti -1c
.RI "bool \fBshowExtra\fP"
.br
.ti -1c
.RI "bool \fBtest\fP"
.br
.ti -1c
.RI "bool \fBgodMode\fP"
.br
.ti -1c
.RI "bool \fBrandomResource\fP"
.br
.ti -1c
.RI "bool \fBdebugScatter\fP"
.br
.ti -1c
.RI "bool \fB_godBuild\fP"
.br
.ti -1c
.RI "bool \fBgodCraft\fP"
.br
.ti -1c
.RI "bool \fBgodFood\fP"
.br
.ti -1c
.RI "bool \fBignoreBuildRule\fP"
.br
.ti -1c
.RI "bool \fBignoreWeight\fP"
.br
.ti -1c
.RI "bool \fBautoIdentify\fP"
.br
.ti -1c
.RI "bool \fBallAbility\fP"
.br
.ti -1c
.RI "bool \fBallSkill\fP"
.br
.ti -1c
.RI "bool \fBallHomeSkill\fP"
.br
.ti -1c
.RI "bool \fBallArt\fP"
.br
.ti -1c
.RI "bool \fBallBGM\fP"
.br
.ti -1c
.RI "bool \fBignoreEncounter\fP"
.br
.ti -1c
.RI "bool \fBreturnAnywhere\fP"
.br
.ti -1c
.RI "bool \fBinstaReturn\fP"
.br
.ti -1c
.RI "bool \fBtravelAnywhere\fP"
.br
.ti -1c
.RI "bool \fBhidePCItemsInBuild\fP"
.br
.ti -1c
.RI "bool \fBautoAdvanceQuest\fP"
.br
.ti -1c
.RI "bool \fBenableMapPieceEditor\fP"
.br
.ti -1c
.RI "bool \fBtestThingQuality\fP"
.br
.ti -1c
.RI "int \fBnumResource\fP"
.br
.ti -1c
.RI "bool \fBunlimitedInterest\fP"
.br
.ti -1c
.RI "bool \fBinviteAnytime\fP"
.br
.ti -1c
.RI "bool \fBmarryAnytime\fP"
.br
.ti -1c
.RI "bool \fBshowFav\fP"
.br
.ti -1c
.RI "bool \fBalwaysFavFood\fP"
.br
.ti -1c
.RI "bool \fBmaxQuests\fP"
.br
.ti -1c
.RI "bool \fBallRecipe\fP"
.br
.ti -1c
.RI "bool \fBallMenu\fP"
.br
.ti -1c
.RI "bool \fBallPolicy\fP"
.br
.ti -1c
.RI "bool \fBallStory\fP"
.br
.ti -1c
.RI "bool \fBskipInitialQuest\fP"
.br
.ti -1c
.RI "bool \fBlogAdv\fP"
.br
.ti -1c
.RI "bool \fBlogCombat\fP"
.br
.ti -1c
.RI "bool \fBlogDice\fP"
.br
.ti -1c
.RI "bool \fBvalidatePref\fP"
.br
.ti -1c
.RI "int \fBparam1\fP"
.br
.ti -1c
.RI "int \fBparam2\fP"
.br
.ti -1c
.RI "\fBCoreDebug\&.MatColorTest\fP \fBmatColorTest\fP"
.br
.ti -1c
.RI "bool \fBboradcast\fP"
.br
.ti -1c
.RI "bool \fBtestFixedColor\fP"
.br
.ti -1c
.RI "Color32 \fBfixedColor\fP"
.br
.ti -1c
.RI "List< \fBCoreDebug\&.DebugCommand\fP > \fBcommands\fP = new List<\fBCoreDebug\&.DebugCommand\fP>()"
.br
.ti -1c
.RI "bool \fBenable\fP"
.br
.ti -1c
.RI "\fBFov\fP \fBfov\fP = new \fBFov\fP()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "bool \fBgodBuild\fP\fR [get]\fP"
.br
.ti -1c
.RI "static string \fBEnableCheat\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB11\fP of file \fBCoreDebug\&.cs\fP\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "enum CoreDebug\&.DebugHotkey"

.PP
Definition at line \fB2444\fP of file \fBCoreDebug\&.cs\fP\&.
.SS "enum CoreDebug\&.StartLoadout"

.PP
Definition at line \fB2463\fP of file \fBCoreDebug\&.cs\fP\&.
.SS "enum CoreDebug\&.StartParty"

.PP
Definition at line \fB2474\fP of file \fBCoreDebug\&.cs\fP\&.
.SS "enum CoreDebug\&.StartScene"

.PP
Definition at line \fB2485\fP of file \fBCoreDebug\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void CoreDebug\&.AddAllRecipes ()"

.PP
Definition at line \fB384\fP of file \fBCoreDebug\&.cs\fP\&.
.SS "static string CoreDebug\&.AllRecipe (bool forget = \fRfalse\fP)\fR [static]\fP"

.PP
Definition at line \fB1942\fP of file \fBCoreDebug\&.cs\fP\&.
.SS "void CoreDebug\&.BroadcastNext ()"

.PP
Definition at line \fB2053\fP of file \fBCoreDebug\&.cs\fP\&.
.SS "static string CoreDebug\&.ChangeJob (string id = \fR'?'\fP)\fR [static]\fP"

.PP
Definition at line \fB1864\fP of file \fBCoreDebug\&.cs\fP\&.
.SS "static string CoreDebug\&.ChangeRace (string id = \fR'?'\fP)\fR [static]\fP"

.PP
Definition at line \fB1815\fP of file \fBCoreDebug\&.cs\fP\&.
.SS "static string CoreDebug\&.Cheat ()\fR [static]\fP"

.PP
Definition at line \fB1589\fP of file \fBCoreDebug\&.cs\fP\&.
.SS "static bool CoreDebug\&.CheatEnabled ()\fR [static]\fP"

.PP
Definition at line \fB1572\fP of file \fBCoreDebug\&.cs\fP\&.
.SS "static string CoreDebug\&.ClearLastWishFlag ()\fR [static]\fP"

.PP
Definition at line \fB1996\fP of file \fBCoreDebug\&.cs\fP\&.
.SS "void CoreDebug\&.COM_MaxConstruction ()"

.PP
Definition at line \fB1562\fP of file \fBCoreDebug\&.cs\fP\&.
.SS "void CoreDebug\&.COM_PlayStartDrama ()"

.PP
Definition at line \fB1502\fP of file \fBCoreDebug\&.cs\fP\&.
.SS "void CoreDebug\&.COM_Teleport ()"

.PP
Definition at line \fB1486\fP of file \fBCoreDebug\&.cs\fP\&.
.SS "void CoreDebug\&.EnableDebugResource ()"

.PP
Definition at line \fB457\fP of file \fBCoreDebug\&.cs\fP\&.
.SS "static string CoreDebug\&.FirstAdventurer ()\fR [static]\fP"

.PP
Definition at line \fB1889\fP of file \fBCoreDebug\&.cs\fP\&.
.SS "static string CoreDebug\&.Fix_EtherDisease ()\fR [static]\fP"

.PP
Definition at line \fB1618\fP of file \fBCoreDebug\&.cs\fP\&.
.SS "static string CoreDebug\&.Fix_RemoveDuplicateUnique ()\fR [static]\fP"

.PP
Definition at line \fB1597\fP of file \fBCoreDebug\&.cs\fP\&.
.SS "static string CoreDebug\&.FlyMode ()\fR [static]\fP"

.PP
Definition at line \fB1807\fP of file \fBCoreDebug\&.cs\fP\&.
.SS "\fBThing\fP CoreDebug\&.GetDebugContainer ()"

.PP
Definition at line \fB444\fP of file \fBCoreDebug\&.cs\fP\&.
.SS "\fBThing\fP CoreDebug\&.GetOrCreateDebugContainer ()"

.PP
Definition at line \fB426\fP of file \fBCoreDebug\&.cs\fP\&.
.SS "static string CoreDebug\&.GodMode ()\fR [static]\fP"

.PP
Definition at line \fB1754\fP of file \fBCoreDebug\&.cs\fP\&.
.SS "void CoreDebug\&.Init ()"

.PP
Definition at line \fB36\fP of file \fBCoreDebug\&.cs\fP\&.
.SS "void CoreDebug\&.InitDebugCommands ()"

.PP
Definition at line \fB1149\fP of file \fBCoreDebug\&.cs\fP\&.
.SS "static string CoreDebug\&.LastWish (string name)\fR [static]\fP"

.PP
Definition at line \fB1961\fP of file \fBCoreDebug\&.cs\fP\&.
.SS "static string CoreDebug\&.ListChara ()\fR [static]\fP"

.PP
Definition at line \fB1652\fP of file \fBCoreDebug\&.cs\fP\&.
.SS "static string CoreDebug\&.ListThing ()\fR [static]\fP"

.PP
Definition at line \fB1664\fP of file \fBCoreDebug\&.cs\fP\&.
.SS "void CoreDebug\&.LoadBroadcast ()"

.PP
Definition at line \fB2046\fP of file \fBCoreDebug\&.cs\fP\&.
.SS "void CoreDebug\&.Log (object o)"

.PP
Definition at line \fB2019\fP of file \fBCoreDebug\&.cs\fP\&.
.SS "void CoreDebug\&.LOG_Spatials ()"

.PP
Definition at line \fB1522\fP of file \fBCoreDebug\&.cs\fP\&.
.SS "static string CoreDebug\&.ModContribution (int amount)\fR [static]\fP"

.PP
Definition at line \fB1791\fP of file \fBCoreDebug\&.cs\fP\&.
.SS "static string CoreDebug\&.ModFame (int amount)\fR [static]\fP"

.PP
Definition at line \fB1767\fP of file \fBCoreDebug\&.cs\fP\&.
.SS "static string CoreDebug\&.ModKarma (int amount)\fR [static]\fP"

.PP
Definition at line \fB1779\fP of file \fBCoreDebug\&.cs\fP\&.
.SS "void CoreDebug\&.NextBGM ()"

.PP
Definition at line \fB2025\fP of file \fBCoreDebug\&.cs\fP\&.
.SS "void CoreDebug\&.OnLoad ()"

.PP
Definition at line \fB375\fP of file \fBCoreDebug\&.cs\fP\&.
.SS "void CoreDebug\&.QuickStart ()"

.PP
Definition at line \fB43\fP of file \fBCoreDebug\&.cs\fP\&.
.SS "static string CoreDebug\&.ResetPetUpgrades ()\fR [static]\fP"

.PP
Definition at line \fB1740\fP of file \fBCoreDebug\&.cs\fP\&.
.SS "static string CoreDebug\&.Resource ()\fR [static]\fP"

.PP
Definition at line \fB2008\fP of file \fBCoreDebug\&.cs\fP\&.
.SS "static string CoreDebug\&.SetElement (string alias, int value, int potential = \fR100\fP)\fR [static]\fP"

.PP
Definition at line \fB1676\fP of file \fBCoreDebug\&.cs\fP\&.
.SS "void CoreDebug\&.SetStartStockpile (\fBThing\fP container, int num = \fR100\fP)"

.PP
Definition at line \fB396\fP of file \fBCoreDebug\&.cs\fP\&.
.SS "static string CoreDebug\&.Spawn (string id, int num = \fR1\fP)\fR [static]\fP"

.PP
Definition at line \fB1693\fP of file \fBCoreDebug\&.cs\fP\&.
.SS "void CoreDebug\&.SpawnCheatContainer ()"

.PP
Definition at line \fB472\fP of file \fBCoreDebug\&.cs\fP\&.
.SS "void CoreDebug\&.Test_Filter ()"

.PP
Definition at line \fB1511\fP of file \fBCoreDebug\&.cs\fP\&.
.SS "void CoreDebug\&.Test_GodTalk ()"

.PP
Definition at line \fB1477\fP of file \fBCoreDebug\&.cs\fP\&.
.SS "void CoreDebug\&.Test_Grow ()"

.PP
Definition at line \fB1457\fP of file \fBCoreDebug\&.cs\fP\&.
.SS "void CoreDebug\&.Test_Siege ()"

.PP
Definition at line \fB1551\fP of file \fBCoreDebug\&.cs\fP\&.
.SS "void CoreDebug\&.Test_SiegeGuard ()"

.PP
Definition at line \fB1540\fP of file \fBCoreDebug\&.cs\fP\&.
.SS "static string CoreDebug\&.TestSpawn (int lv, int num)\fR [static]\fP"

.PP
Definition at line \fB1716\fP of file \fBCoreDebug\&.cs\fP\&.
.SS "void CoreDebug\&.ToggleRevealMap ()"

.PP
Definition at line \fB2035\fP of file \fBCoreDebug\&.cs\fP\&.
.SS "void CoreDebug\&.UpdateAlways ()"

.PP
Definition at line \fB477\fP of file \fBCoreDebug\&.cs\fP\&.
.SS "void CoreDebug\&.UpdateInput ()"

.PP
Definition at line \fB540\fP of file \fBCoreDebug\&.cs\fP\&.
.SS "void CoreDebug\&.ValidateData ()"

.PP
Definition at line \fB528\fP of file \fBCoreDebug\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "bool CoreDebug\&._godBuild"

.PP
Definition at line \fB2237\fP of file \fBCoreDebug\&.cs\fP\&.
.SS "int CoreDebug\&.advanceMin"

.PP
Definition at line \fB2188\fP of file \fBCoreDebug\&.cs\fP\&.
.SS "bool CoreDebug\&.allAbility"

.PP
Definition at line \fB2255\fP of file \fBCoreDebug\&.cs\fP\&.
.SS "bool CoreDebug\&.allArt"

.PP
Definition at line \fB2264\fP of file \fBCoreDebug\&.cs\fP\&.
.SS "bool CoreDebug\&.allBGM"

.PP
Definition at line \fB2267\fP of file \fBCoreDebug\&.cs\fP\&.
.SS "bool CoreDebug\&.allHomeSkill"

.PP
Definition at line \fB2261\fP of file \fBCoreDebug\&.cs\fP\&.
.SS "bool CoreDebug\&.allMenu"

.PP
Definition at line \fB2320\fP of file \fBCoreDebug\&.cs\fP\&.
.SS "bool CoreDebug\&.allPolicy"

.PP
Definition at line \fB2323\fP of file \fBCoreDebug\&.cs\fP\&.
.SS "bool CoreDebug\&.allRecipe"

.PP
Definition at line \fB2317\fP of file \fBCoreDebug\&.cs\fP\&.
.SS "bool CoreDebug\&.allSkill"

.PP
Definition at line \fB2258\fP of file \fBCoreDebug\&.cs\fP\&.
.SS "bool CoreDebug\&.allStory"

.PP
Definition at line \fB2326\fP of file \fBCoreDebug\&.cs\fP\&.
.SS "bool CoreDebug\&.alwaysFavFood"

.PP
Definition at line \fB2310\fP of file \fBCoreDebug\&.cs\fP\&.
.SS "bool CoreDebug\&.alwaysResetWindow"

.PP
Definition at line \fB2162\fP of file \fBCoreDebug\&.cs\fP\&.
.SS "bool CoreDebug\&.autoAdvanceQuest"

.PP
Definition at line \fB2285\fP of file \fBCoreDebug\&.cs\fP\&.
.SS "bool CoreDebug\&.autoIdentify"

.PP
Definition at line \fB2252\fP of file \fBCoreDebug\&.cs\fP\&.
.SS "bool CoreDebug\&.boradcast"

.PP
Definition at line \fB2358\fP of file \fBCoreDebug\&.cs\fP\&.
.SS "string CoreDebug\&.command"

.PP
Definition at line \fB2174\fP of file \fBCoreDebug\&.cs\fP\&.
.SS "List<\fBCoreDebug\&.DebugCommand\fP> CoreDebug\&.commands = new List<\fBCoreDebug\&.DebugCommand\fP>()"

.PP
Definition at line \fB2401\fP of file \fBCoreDebug\&.cs\fP\&.
.SS "bool CoreDebug\&.debugHoard"

.PP
Definition at line \fB2203\fP of file \fBCoreDebug\&.cs\fP\&.
.SS "CoreDebug\&.DebugHotkey CoreDebug\&.debugHotkeys"

.PP
Definition at line \fB2184\fP of file \fBCoreDebug\&.cs\fP\&.
.SS "bool CoreDebug\&.debugInput"

.PP
Definition at line \fB2178\fP of file \fBCoreDebug\&.cs\fP\&.
.SS "bool CoreDebug\&.debugProps"

.PP
Definition at line \fB2197\fP of file \fBCoreDebug\&.cs\fP\&.
.SS "bool CoreDebug\&.debugScatter"

.PP
Definition at line \fB2234\fP of file \fBCoreDebug\&.cs\fP\&.
.SS "bool CoreDebug\&.dontCompressSave"

.PP
Definition at line \fB2168\fP of file \fBCoreDebug\&.cs\fP\&.
.SS "bool CoreDebug\&.dontUseThread"

.PP
Definition at line \fB2153\fP of file \fBCoreDebug\&.cs\fP\&.
.SS "bool CoreDebug\&.enable"

.PP
Definition at line \fB2405\fP of file \fBCoreDebug\&.cs\fP\&.
.SS "bool CoreDebug\&.enableMapPieceEditor"

.PP
Definition at line \fB2288\fP of file \fBCoreDebug\&.cs\fP\&.
.SS "Color32 CoreDebug\&.fixedColor"

.PP
Definition at line \fB2364\fP of file \fBCoreDebug\&.cs\fP\&.
.SS "\fBFov\fP CoreDebug\&.fov = new \fBFov\fP()"

.PP
Definition at line \fB2408\fP of file \fBCoreDebug\&.cs\fP\&.
.SS "bool CoreDebug\&.godCraft"

.PP
Definition at line \fB2240\fP of file \fBCoreDebug\&.cs\fP\&.
.SS "bool CoreDebug\&.godFood"

.PP
Definition at line \fB2243\fP of file \fBCoreDebug\&.cs\fP\&.
.SS "bool CoreDebug\&.godMode"

.PP
Definition at line \fB2228\fP of file \fBCoreDebug\&.cs\fP\&.
.SS "bool CoreDebug\&.hidePCItemsInBuild"

.PP
Definition at line \fB2282\fP of file \fBCoreDebug\&.cs\fP\&.
.SS "bool CoreDebug\&.ignoreAutoSave"

.PP
Definition at line \fB2159\fP of file \fBCoreDebug\&.cs\fP\&.
.SS "bool CoreDebug\&.ignoreBuildRule"

.PP
Definition at line \fB2246\fP of file \fBCoreDebug\&.cs\fP\&.
.SS "bool CoreDebug\&.ignoreEncounter"

.PP
Definition at line \fB2270\fP of file \fBCoreDebug\&.cs\fP\&.
.SS "bool CoreDebug\&.ignorePool"

.PP
Definition at line \fB2146\fP of file \fBCoreDebug\&.cs\fP\&.
.SS "bool CoreDebug\&.ignorePopup"

.PP
Definition at line \fB2209\fP of file \fBCoreDebug\&.cs\fP\&.
.SS "bool CoreDebug\&.ignoreWeight"

.PP
Definition at line \fB2249\fP of file \fBCoreDebug\&.cs\fP\&.
.SS "bool CoreDebug\&.instaReturn"

.PP
Definition at line \fB2276\fP of file \fBCoreDebug\&.cs\fP\&.
.SS "bool CoreDebug\&.inviteAnytime"

.PP
Definition at line \fB2301\fP of file \fBCoreDebug\&.cs\fP\&.
.SS "bool CoreDebug\&.keypadDebug"

.PP
Definition at line \fB2181\fP of file \fBCoreDebug\&.cs\fP\&.
.SS "Lang\&.LangCode CoreDebug\&.langCode"

.PP
Definition at line \fB2142\fP of file \fBCoreDebug\&.cs\fP\&.
.SS "bool CoreDebug\&.logAdv"

.PP
Definition at line \fB2333\fP of file \fBCoreDebug\&.cs\fP\&.
.SS "bool CoreDebug\&.logCombat"

.PP
Definition at line \fB2337\fP of file \fBCoreDebug\&.cs\fP\&.
.SS "bool CoreDebug\&.logDice"

.PP
Definition at line \fB2340\fP of file \fBCoreDebug\&.cs\fP\&.
.SS "bool CoreDebug\&.marryAnytime"

.PP
Definition at line \fB2304\fP of file \fBCoreDebug\&.cs\fP\&.
.SS "\fBCoreDebug\&.MatColorTest\fP CoreDebug\&.matColorTest"

.PP
Definition at line \fB2355\fP of file \fBCoreDebug\&.cs\fP\&.
.SS "bool CoreDebug\&.maxQuests"

.PP
Definition at line \fB2313\fP of file \fBCoreDebug\&.cs\fP\&.
.SS "int CoreDebug\&.numResource"

.PP
Definition at line \fB2294\fP of file \fBCoreDebug\&.cs\fP\&.
.SS "int CoreDebug\&.param1"

.PP
Definition at line \fB2348\fP of file \fBCoreDebug\&.cs\fP\&.
.SS "int CoreDebug\&.param2"

.PP
Definition at line \fB2352\fP of file \fBCoreDebug\&.cs\fP\&.
.SS "bool CoreDebug\&.randomResource"

.PP
Definition at line \fB2231\fP of file \fBCoreDebug\&.cs\fP\&.
.SS "bool CoreDebug\&.resetPlayerConfig"

.PP
Definition at line \fB2150\fP of file \fBCoreDebug\&.cs\fP\&.
.SS "bool CoreDebug\&.returnAnywhere"

.PP
Definition at line \fB2273\fP of file \fBCoreDebug\&.cs\fP\&.
.SS "bool CoreDebug\&.revealInner"

.PP
Definition at line \fB2206\fP of file \fBCoreDebug\&.cs\fP\&.
.SS "bool CoreDebug\&.revealMap"

.PP
Definition at line \fB2200\fP of file \fBCoreDebug\&.cs\fP\&.
.SS "bool CoreDebug\&.showExtra"

.PP
Definition at line \fB2221\fP of file \fBCoreDebug\&.cs\fP\&.
.SS "bool CoreDebug\&.showFav"

.PP
Definition at line \fB2307\fP of file \fBCoreDebug\&.cs\fP\&.
.SS "bool CoreDebug\&.showSceneSelector"

.PP
Definition at line \fB2135\fP of file \fBCoreDebug\&.cs\fP\&.
.SS "bool CoreDebug\&.showTone"

.PP
Definition at line \fB2218\fP of file \fBCoreDebug\&.cs\fP\&.
.SS "bool CoreDebug\&.skipEvent"

.PP
Definition at line \fB2212\fP of file \fBCoreDebug\&.cs\fP\&.
.SS "bool CoreDebug\&.skipInitialQuest"

.PP
Definition at line \fB2329\fP of file \fBCoreDebug\&.cs\fP\&.
.SS "bool CoreDebug\&.skipMod"

.PP
Definition at line \fB2171\fP of file \fBCoreDebug\&.cs\fP\&.
.SS "bool CoreDebug\&.skipModSync"

.PP
Definition at line \fB2139\fP of file \fBCoreDebug\&.cs\fP\&.
.SS "bool CoreDebug\&.skipNerun"

.PP
Definition at line \fB2215\fP of file \fBCoreDebug\&.cs\fP\&.
.SS "int CoreDebug\&.startHour"

.PP
Definition at line \fB2125\fP of file \fBCoreDebug\&.cs\fP\&.
.SS "CoreDebug\&.StartLoadout CoreDebug\&.startLoadout"

.PP
Definition at line \fB2119\fP of file \fBCoreDebug\&.cs\fP\&.
.SS "CoreDebug\&.StartParty CoreDebug\&.startParty"

.PP
Definition at line \fB2122\fP of file \fBCoreDebug\&.cs\fP\&.
.SS "CoreDebug\&.StartScene CoreDebug\&.startScene"

.PP
Definition at line \fB2116\fP of file \fBCoreDebug\&.cs\fP\&.
.SS "\fBCoreDebug\&.StartSetting\fP CoreDebug\&.startSetting"

.PP
Definition at line \fB2128\fP of file \fBCoreDebug\&.cs\fP\&.
.SS "string CoreDebug\&.startZone"

.PP
Definition at line \fB2131\fP of file \fBCoreDebug\&.cs\fP\&.
.SS "bool CoreDebug\&.test"

.PP
Definition at line \fB2224\fP of file \fBCoreDebug\&.cs\fP\&.
.SS "bool CoreDebug\&.testFixedColor"

.PP
Definition at line \fB2361\fP of file \fBCoreDebug\&.cs\fP\&.
.SS "bool CoreDebug\&.testLOS"

.PP
Definition at line \fB2191\fP of file \fBCoreDebug\&.cs\fP\&.
.SS "bool CoreDebug\&.testLOS2"

.PP
Definition at line \fB2194\fP of file \fBCoreDebug\&.cs\fP\&.
.SS "bool CoreDebug\&.testThingQuality"

.PP
Definition at line \fB2291\fP of file \fBCoreDebug\&.cs\fP\&.
.SS "bool CoreDebug\&.travelAnywhere"

.PP
Definition at line \fB2279\fP of file \fBCoreDebug\&.cs\fP\&.
.SS "bool CoreDebug\&.unlimitedInterest"

.PP
Definition at line \fB2298\fP of file \fBCoreDebug\&.cs\fP\&.
.SS "bool CoreDebug\&.useNewConfig"

.PP
Definition at line \fB2156\fP of file \fBCoreDebug\&.cs\fP\&.
.SS "bool CoreDebug\&.validateData"

.PP
Definition at line \fB2165\fP of file \fBCoreDebug\&.cs\fP\&.
.SS "bool CoreDebug\&.validatePref"

.PP
Definition at line \fB2344\fP of file \fBCoreDebug\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "string CoreDebug\&.EnableCheat\fR [static]\fP, \fR [get]\fP"

.PP
Definition at line \fB1579\fP of file \fBCoreDebug\&.cs\fP\&.
.SS "bool CoreDebug\&.godBuild\fR [get]\fP"

.PP
Definition at line \fB15\fP of file \fBCoreDebug\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
