.TH "CoreRef.UDIconWeather" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CoreRef.UDIconWeather
.SH SYNOPSIS
.br
.PP
.PP
Inherits UDictionary< Weather\&.Condition, Sprite >\&.
.SH "Detailed Description"
.PP 
Definition at line \fB242\fP of file \fBCoreRef\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
