.TH "CoreRef.Rects" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CoreRef.Rects
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "RectData \fBbottomRight\fP"
.br
.ti -1c
.RI "RectData \fBinv\fP"
.br
.ti -1c
.RI "RectData \fBinvFloat\fP"
.br
.ti -1c
.RI "RectData \fBinvCenter\fP"
.br
.ti -1c
.RI "RectData \fBcenter\fP"
.br
.ti -1c
.RI "RectData \fBcenterFloat\fP"
.br
.ti -1c
.RI "RectData \fBabilityDebug\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB389\fP of file \fBCoreRef\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "RectData CoreRef\&.Rects\&.abilityDebug"

.PP
Definition at line \fB410\fP of file \fBCoreRef\&.cs\fP\&.
.SS "RectData CoreRef\&.Rects\&.bottomRight"

.PP
Definition at line \fB392\fP of file \fBCoreRef\&.cs\fP\&.
.SS "RectData CoreRef\&.Rects\&.center"

.PP
Definition at line \fB404\fP of file \fBCoreRef\&.cs\fP\&.
.SS "RectData CoreRef\&.Rects\&.centerFloat"

.PP
Definition at line \fB407\fP of file \fBCoreRef\&.cs\fP\&.
.SS "RectData CoreRef\&.Rects\&.inv"

.PP
Definition at line \fB395\fP of file \fBCoreRef\&.cs\fP\&.
.SS "RectData CoreRef\&.Rects\&.invCenter"

.PP
Definition at line \fB401\fP of file \fBCoreRef\&.cs\fP\&.
.SS "RectData CoreRef\&.Rects\&.invFloat"

.PP
Definition at line \fB398\fP of file \fBCoreRef\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
