.TH "CoreConfig.InputSetting" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CoreConfig.InputSetting
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBautorun\fP"
.br
.ti -1c
.RI "bool \fBautowalk\fP"
.br
.ti -1c
.RI "bool \fBaltKeyAxis\fP"
.br
.ti -1c
.RI "bool \fBkeepRunning\fP"
.br
.ti -1c
.RI "bool \fBrightClickExitBuildMode\fP"
.br
.ti -1c
.RI "bool \fBignoreNPCs\fP"
.br
.ti -1c
.RI "bool \fBaltExamine\fP"
.br
.ti -1c
.RI "CoreConfig\&.GameFunc \fBmiddleClick\fP"
.br
.ti -1c
.RI "CoreConfig\&.GameFunc \fBmiddlePressLong\fP"
.br
.ti -1c
.RI "CoreConfig\&.GameFunc \fBmouse3Click\fP"
.br
.ti -1c
.RI "CoreConfig\&.GameFunc \fBmouse3PressLong\fP"
.br
.ti -1c
.RI "CoreConfig\&.GameFunc \fBmouse4Click\fP"
.br
.ti -1c
.RI "CoreConfig\&.GameFunc \fBmouse4PressLong\fP"
.br
.ti -1c
.RI "CoreConfig\&.GameFuncBuild \fBb_middleClick\fP"
.br
.ti -1c
.RI "CoreConfig\&.GameFuncBuild \fBb_middlePressLong\fP"
.br
.ti -1c
.RI "CoreConfig\&.GameFuncBuild \fBb_mouse3Click\fP"
.br
.ti -1c
.RI "CoreConfig\&.GameFuncBuild \fBb_mouse3PressLong\fP"
.br
.ti -1c
.RI "CoreConfig\&.GameFuncBuild \fBb_mouse4Click\fP"
.br
.ti -1c
.RI "CoreConfig\&.GameFuncBuild \fBb_mouse4PressLong\fP"
.br
.ti -1c
.RI "EInput\&.KeyMapManager \fBkeys\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB810\fP of file \fBCoreConfig\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "bool CoreConfig\&.InputSetting\&.altExamine"

.PP
Definition at line \fB831\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "bool CoreConfig\&.InputSetting\&.altKeyAxis"

.PP
Definition at line \fB819\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "bool CoreConfig\&.InputSetting\&.autorun"

.PP
Definition at line \fB813\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "bool CoreConfig\&.InputSetting\&.autowalk"

.PP
Definition at line \fB816\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "CoreConfig\&.GameFuncBuild CoreConfig\&.InputSetting\&.b_middleClick"

.PP
Definition at line \fB852\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "CoreConfig\&.GameFuncBuild CoreConfig\&.InputSetting\&.b_middlePressLong"

.PP
Definition at line \fB855\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "CoreConfig\&.GameFuncBuild CoreConfig\&.InputSetting\&.b_mouse3Click"

.PP
Definition at line \fB858\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "CoreConfig\&.GameFuncBuild CoreConfig\&.InputSetting\&.b_mouse3PressLong"

.PP
Definition at line \fB861\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "CoreConfig\&.GameFuncBuild CoreConfig\&.InputSetting\&.b_mouse4Click"

.PP
Definition at line \fB864\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "CoreConfig\&.GameFuncBuild CoreConfig\&.InputSetting\&.b_mouse4PressLong"

.PP
Definition at line \fB867\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "bool CoreConfig\&.InputSetting\&.ignoreNPCs"

.PP
Definition at line \fB828\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "bool CoreConfig\&.InputSetting\&.keepRunning"

.PP
Definition at line \fB822\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "EInput\&.KeyMapManager CoreConfig\&.InputSetting\&.keys"

.PP
Definition at line \fB870\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "CoreConfig\&.GameFunc CoreConfig\&.InputSetting\&.middleClick"

.PP
Definition at line \fB834\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "CoreConfig\&.GameFunc CoreConfig\&.InputSetting\&.middlePressLong"

.PP
Definition at line \fB837\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "CoreConfig\&.GameFunc CoreConfig\&.InputSetting\&.mouse3Click"

.PP
Definition at line \fB840\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "CoreConfig\&.GameFunc CoreConfig\&.InputSetting\&.mouse3PressLong"

.PP
Definition at line \fB843\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "CoreConfig\&.GameFunc CoreConfig\&.InputSetting\&.mouse4Click"

.PP
Definition at line \fB846\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "CoreConfig\&.GameFunc CoreConfig\&.InputSetting\&.mouse4PressLong"

.PP
Definition at line \fB849\fP of file \fBCoreConfig\&.cs\fP\&.
.SS "bool CoreConfig\&.InputSetting\&.rightClickExitBuildMode"

.PP
Definition at line \fB825\fP of file \fBCoreConfig\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
