.TH "Crawler" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Crawler
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBEScriptable\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMember\fP"
.br
.ti -1c
.RI "class \fBResult\fP"
.br
.in -1c
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBMoveType\fP { \fBSurface\fP, \fBBlock\fP }"
.br
.ti -1c
.RI "enum \fBStartType\fP { \fBSurface\fP, \fBBlock\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBCrawlUntil\fP (\fBMap\fP map, Func< \fBPoint\fP > onStart, int tries, Func< \fBCrawler\&.Result\fP, bool > canComplete, Action onFail=null)"
.br
.ti -1c
.RI "void \fBCrawl\fP (\fBMap\fP map)"
.br
.ti -1c
.RI "\fBCrawler\&.Result\fP \fBCrawl\fP (\fBMap\fP map, \fBPoint\fP _start, Action< \fBPoint\fP > onNewVisit=null)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBCrawler\fP \fBCreate\fP (string id)"
.br
.in -1c

Static Public Member Functions inherited from \fBEScriptable\fP
.in +1c
.ti -1c
.RI "static int \fBrnd\fP (int a)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBlife\fP"
.br
.ti -1c
.RI "int \fBmember\fP"
.br
.ti -1c
.RI "int \fBradius\fP"
.br
.ti -1c
.RI "int \fBrepeat\fP"
.br
.ti -1c
.RI "bool \fBstickToStartBiome\fP"
.br
.ti -1c
.RI "bool \fBskipBorder\fP"
.br
.ti -1c
.RI "Crawler\&.StartType \fBstartType\fP"
.br
.ti -1c
.RI "Crawler\&.MoveType \fBmoveType\fP"
.br
.ti -1c
.RI "int \fBSize\fP"
.br
.ti -1c
.RI "List< \fBCrawler\&.Member\fP > \fBmembers\fP = new List<\fBCrawler\&.Member\fP>()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static int[,] \fBmapping\fP = new int[0, 0]"
.br
.ti -1c
.RI "static int \fBsync\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB6\fP of file \fBCrawler\&.cs\fP\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "enum Crawler\&.MoveType"

.PP
Definition at line \fB219\fP of file \fBCrawler\&.cs\fP\&.
.SS "enum Crawler\&.StartType"

.PP
Definition at line \fB228\fP of file \fBCrawler\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Crawler\&.Crawl (\fBMap\fP map)"

.PP
Definition at line \fB62\fP of file \fBCrawler\&.cs\fP\&.
.SS "\fBCrawler\&.Result\fP Crawler\&.Crawl (\fBMap\fP map, \fBPoint\fP _start, Action< \fBPoint\fP > onNewVisit = \fRnull\fP)"

.PP
Definition at line \fB76\fP of file \fBCrawler\&.cs\fP\&.
.SS "bool Crawler\&.CrawlUntil (\fBMap\fP map, Func< \fBPoint\fP > onStart, int tries, Func< \fBCrawler\&.Result\fP, bool > canComplete, Action onFail = \fRnull\fP)"

.PP
Definition at line \fB9\fP of file \fBCrawler\&.cs\fP\&.
.SS "static \fBCrawler\fP Crawler\&.Create (string id)\fR [static]\fP"

.PP
Definition at line \fB158\fP of file \fBCrawler\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int Crawler\&.life"

.PP
Definition at line \fB170\fP of file \fBCrawler\&.cs\fP\&.
.SS "int [,] Crawler\&.mapping = new int[0, 0]\fR [static]\fP"

.PP
Definition at line \fB164\fP of file \fBCrawler\&.cs\fP\&.
.SS "int Crawler\&.member"

.PP
Definition at line \fB173\fP of file \fBCrawler\&.cs\fP\&.
.SS "List<\fBCrawler\&.Member\fP> Crawler\&.members = new List<\fBCrawler\&.Member\fP>()"

.PP
Definition at line \fB199\fP of file \fBCrawler\&.cs\fP\&.
.SS "Crawler\&.MoveType Crawler\&.moveType"

.PP
Definition at line \fB191\fP of file \fBCrawler\&.cs\fP\&.
.SS "int Crawler\&.radius"

.PP
Definition at line \fB176\fP of file \fBCrawler\&.cs\fP\&.
.SS "int Crawler\&.repeat"

.PP
Definition at line \fB179\fP of file \fBCrawler\&.cs\fP\&.
.SS "int Crawler\&.Size"

.PP
Definition at line \fB195\fP of file \fBCrawler\&.cs\fP\&.
.SS "bool Crawler\&.skipBorder"

.PP
Definition at line \fB185\fP of file \fBCrawler\&.cs\fP\&.
.SS "Crawler\&.StartType Crawler\&.startType"

.PP
Definition at line \fB188\fP of file \fBCrawler\&.cs\fP\&.
.SS "bool Crawler\&.stickToStartBiome"

.PP
Definition at line \fB182\fP of file \fBCrawler\&.cs\fP\&.
.SS "int Crawler\&.sync\fR [static]\fP"

.PP
Definition at line \fB167\fP of file \fBCrawler\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
