.TH "Crawler.Member" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Crawler.Member
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBPoint\fP \fBpos\fP = new \fBPoint\fP()"
.br
.ti -1c
.RI "int \fBlife\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB202\fP of file \fBCrawler\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int Crawler\&.Member\&.life"

.PP
Definition at line \fB208\fP of file \fBCrawler\&.cs\fP\&.
.SS "\fBPoint\fP Crawler\&.Member\&.pos = new \fBPoint\fP()"

.PP
Definition at line \fB205\fP of file \fBCrawler\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
