.TH "CSTR" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CSTR
.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "const int \fBaltName\fP = 1"
.br
.ti -1c
.RI "const int \fBaltName2\fP = 2"
.br
.ti -1c
.RI "const int \fBidRace\fP = 3"
.br
.ti -1c
.RI "const int \fBidJob\fP = 4"
.br
.ti -1c
.RI "const int \fBidRefCard\fP = 5"
.br
.ti -1c
.RI "const int \fBidRefCard2\fP = 6"
.br
.ti -1c
.RI "const int \fBidRefName\fP = 7"
.br
.ti -1c
.RI "const int \fBcolor\fP = 8"
.br
.ti -1c
.RI "const int \fBidPortrait\fP = 9"
.br
.ti -1c
.RI "const int \fBrefText\fP = 10"
.br
.ti -1c
.RI "const int \fBidCat\fP = 11"
.br
.ti -1c
.RI "const int \fBcontext\fP = 20"
.br
.ti -1c
.RI "const int \fBidTalk\fP = 21"
.br
.ti -1c
.RI "const int \fBidTone\fP = 22"
.br
.ti -1c
.RI "const int \fBidPortraitBG\fP = 23"
.br
.ti -1c
.RI "const int \fBidPortraitFrame\fP = 24"
.br
.ti -1c
.RI "const int \fBeditorTraitVal\fP = 25"
.br
.ti -1c
.RI "const int \fBidDeity\fP = 26"
.br
.ti -1c
.RI "const int \fBidEditor\fP = 27"
.br
.ti -1c
.RI "const int \fBeditorTags\fP = 28"
.br
.ti -1c
.RI "const int \fBidTrait\fP = 29"
.br
.ti -1c
.RI "const int \fBidSourceZone\fP = 30"
.br
.ti -1c
.RI "const int \fBidTeleport\fP = 31"
.br
.ti -1c
.RI "const int \fBidAbility\fP = 50"
.br
.ti -1c
.RI "const int \fBnote\fP = 51"
.br
.ti -1c
.RI "const int \fBidActorEx\fP = 52"
.br
.ti -1c
.RI "const int \fBidBook\fP = 53"
.br
.ti -1c
.RI "const int \fBidPath\fP = 54"
.br
.ti -1c
.RI "const int \fBidRidePCC\fP = 55"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB4\fP of file \fBCSTR\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "const int CSTR\&.altName = 1\fR [static]\fP"

.PP
Definition at line \fB7\fP of file \fBCSTR\&.cs\fP\&.
.SS "const int CSTR\&.altName2 = 2\fR [static]\fP"

.PP
Definition at line \fB10\fP of file \fBCSTR\&.cs\fP\&.
.SS "const int CSTR\&.color = 8\fR [static]\fP"

.PP
Definition at line \fB28\fP of file \fBCSTR\&.cs\fP\&.
.SS "const int CSTR\&.context = 20\fR [static]\fP"

.PP
Definition at line \fB40\fP of file \fBCSTR\&.cs\fP\&.
.SS "const int CSTR\&.editorTags = 28\fR [static]\fP"

.PP
Definition at line \fB64\fP of file \fBCSTR\&.cs\fP\&.
.SS "const int CSTR\&.editorTraitVal = 25\fR [static]\fP"

.PP
Definition at line \fB55\fP of file \fBCSTR\&.cs\fP\&.
.SS "const int CSTR\&.idAbility = 50\fR [static]\fP"

.PP
Definition at line \fB76\fP of file \fBCSTR\&.cs\fP\&.
.SS "const int CSTR\&.idActorEx = 52\fR [static]\fP"

.PP
Definition at line \fB82\fP of file \fBCSTR\&.cs\fP\&.
.SS "const int CSTR\&.idBook = 53\fR [static]\fP"

.PP
Definition at line \fB85\fP of file \fBCSTR\&.cs\fP\&.
.SS "const int CSTR\&.idCat = 11\fR [static]\fP"

.PP
Definition at line \fB37\fP of file \fBCSTR\&.cs\fP\&.
.SS "const int CSTR\&.idDeity = 26\fR [static]\fP"

.PP
Definition at line \fB58\fP of file \fBCSTR\&.cs\fP\&.
.SS "const int CSTR\&.idEditor = 27\fR [static]\fP"

.PP
Definition at line \fB61\fP of file \fBCSTR\&.cs\fP\&.
.SS "const int CSTR\&.idJob = 4\fR [static]\fP"

.PP
Definition at line \fB16\fP of file \fBCSTR\&.cs\fP\&.
.SS "const int CSTR\&.idPath = 54\fR [static]\fP"

.PP
Definition at line \fB88\fP of file \fBCSTR\&.cs\fP\&.
.SS "const int CSTR\&.idPortrait = 9\fR [static]\fP"

.PP
Definition at line \fB31\fP of file \fBCSTR\&.cs\fP\&.
.SS "const int CSTR\&.idPortraitBG = 23\fR [static]\fP"

.PP
Definition at line \fB49\fP of file \fBCSTR\&.cs\fP\&.
.SS "const int CSTR\&.idPortraitFrame = 24\fR [static]\fP"

.PP
Definition at line \fB52\fP of file \fBCSTR\&.cs\fP\&.
.SS "const int CSTR\&.idRace = 3\fR [static]\fP"

.PP
Definition at line \fB13\fP of file \fBCSTR\&.cs\fP\&.
.SS "const int CSTR\&.idRefCard = 5\fR [static]\fP"

.PP
Definition at line \fB19\fP of file \fBCSTR\&.cs\fP\&.
.SS "const int CSTR\&.idRefCard2 = 6\fR [static]\fP"

.PP
Definition at line \fB22\fP of file \fBCSTR\&.cs\fP\&.
.SS "const int CSTR\&.idRefName = 7\fR [static]\fP"

.PP
Definition at line \fB25\fP of file \fBCSTR\&.cs\fP\&.
.SS "const int CSTR\&.idRidePCC = 55\fR [static]\fP"

.PP
Definition at line \fB91\fP of file \fBCSTR\&.cs\fP\&.
.SS "const int CSTR\&.idSourceZone = 30\fR [static]\fP"

.PP
Definition at line \fB70\fP of file \fBCSTR\&.cs\fP\&.
.SS "const int CSTR\&.idTalk = 21\fR [static]\fP"

.PP
Definition at line \fB43\fP of file \fBCSTR\&.cs\fP\&.
.SS "const int CSTR\&.idTeleport = 31\fR [static]\fP"

.PP
Definition at line \fB73\fP of file \fBCSTR\&.cs\fP\&.
.SS "const int CSTR\&.idTone = 22\fR [static]\fP"

.PP
Definition at line \fB46\fP of file \fBCSTR\&.cs\fP\&.
.SS "const int CSTR\&.idTrait = 29\fR [static]\fP"

.PP
Definition at line \fB67\fP of file \fBCSTR\&.cs\fP\&.
.SS "const int CSTR\&.note = 51\fR [static]\fP"

.PP
Definition at line \fB79\fP of file \fBCSTR\&.cs\fP\&.
.SS "const int CSTR\&.refText = 10\fR [static]\fP"

.PP
Definition at line \fB34\fP of file \fBCSTR\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
