.TH "Currency" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Currency
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static string \fBToID\fP (CurrencyType currency)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB4\fP of file \fBCurrency\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "static string Currency\&.ToID (CurrencyType currency)\fR [static]\fP"

.PP
Definition at line \fB7\fP of file \fBCurrency\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
