.TH "DayData" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DayData
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBLuck\fP { \fBBest\fP, \fBGreat\fP, \fBGood\fP, \fBAverage\fP, \fBBad\fP, \fBAwful\fP }"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "DayData\&.Luck \fBluck\fP = DayData\&.Luck\&.Awful"
.br
.ti -1c
.RI "int \fBseed\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static int[] \fBLuckRange\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB4\fP of file \fBDayData\&.cs\fP\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "enum DayData\&.Luck"

.PP
Definition at line \fB24\fP of file \fBDayData\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "DayData\&.Luck DayData\&.luck = DayData\&.Luck\&.Awful"

.PP
Definition at line \fB18\fP of file \fBDayData\&.cs\fP\&.
.SS "int [] DayData\&.LuckRange\fR [static]\fP"
\fBInitial value:\fP
.nf
= new int[]
    {
        95,
        80,
        60,
        30,
        10,
        0
    }
.PP
.fi

.PP
Definition at line \fB7\fP of file \fBDayData\&.cs\fP\&.
.SS "int DayData\&.seed"

.PP
Definition at line \fB21\fP of file \fBDayData\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
