.TH "DialogDrama" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DialogDrama
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBEMono\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual UIButton \fBAddChoice\fP (\fBDramaChoice\fP choice, string text, Action func=null, bool deactivateOnChoice=true)"
.br
.ti -1c
.RI "void \fBClearChoice\fP ()"
.br
.ti -1c
.RI "virtual void \fBSetText\fP (string detail='', bool center=false)"
.br
.ti -1c
.RI "void \fBDeactivate\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Text \fBtextName\fP"
.br
.ti -1c
.RI "Text \fBtextBio\fP"
.br
.ti -1c
.RI "Text \fBtextAffinity\fP"
.br
.ti -1c
.RI "Text \fBtextNoInterest\fP"
.br
.ti -1c
.RI "Text \fBtextFav\fP"
.br
.ti -1c
.RI "Text \fBtextRank\fP"
.br
.ti -1c
.RI "GameObject \fBtransInterest\fP"
.br
.ti -1c
.RI "GameObject \fBtransAffinity\fP"
.br
.ti -1c
.RI "GameObject \fBtransFav\fP"
.br
.ti -1c
.RI "GameObject \fBtransRank\fP"
.br
.ti -1c
.RI "UIText \fBtextMain\fP"
.br
.ti -1c
.RI "HyphenationJpn \fBhypen\fP"
.br
.ti -1c
.RI "Transform \fBtransChoices\fP"
.br
.ti -1c
.RI "GameObject \fBiconNext\fP"
.br
.ti -1c
.RI "GameObject \fBgoAffinity\fP"
.br
.ti -1c
.RI "\fBPortrait\fP \fBportrait\fP"
.br
.ti -1c
.RI "LayoutGroup \fBlayoutInterest\fP"
.br
.ti -1c
.RI "Transform \fBmoldInterest\fP"
.br
.ti -1c
.RI "Font \fBfontRune\fP"
.br
.ti -1c
.RI "Glitch \fBglitch\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Static Public Member Functions inherited from \fBEMono\fP
.in +1c
.ti -1c
.RI "static int \fBrnd\fP (int a)"
.br
.in -1c

Static Public Attributes inherited from \fBEMono\fP
.in +1c
.ti -1c
.RI "static \fBCore\fP \fBcore\fP"
.br
.in -1c

Properties inherited from \fBEMono\fP
.in +1c
.ti -1c
.RI "static \fBGame\fP \fBgame\fP\fR [get]\fP"
.br
.ti -1c
.RI "static bool \fBAdvMode\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBPlayer\fP \fBplayer\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBChara\fP \fBpc\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBUI\fP \fBui\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBMap\fP \fB_map\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBZone\fP \fB_zone\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranchOrHomeBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFaction\fP \fBHome\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBScene\fP \fBscene\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBBaseGameScreen\fP \fBscreen\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameSetting\fP \fBsetting\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameData\fP \fBgamedata\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBColorProfile\fP \fBColors\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBWorld\fP \fBworld\fP\fR [get]\fP"
.br
.ti -1c
.RI "static SoundManager \fBSound\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBsources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBeditorSources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBCoreDebug\fP \fBdebug\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB8\fP of file \fBDialogDrama\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual UIButton DialogDrama\&.AddChoice (\fBDramaChoice\fP choice, string text, Action func = \fRnull\fP, bool deactivateOnChoice = \fRtrue\fP)\fR [virtual]\fP"

.PP
Definition at line \fB17\fP of file \fBDialogDrama\&.cs\fP\&.
.SS "void DialogDrama\&.ClearChoice ()"

.PP
Definition at line \fB42\fP of file \fBDialogDrama\&.cs\fP\&.
.SS "void DialogDrama\&.Deactivate ()"

.PP
Definition at line \fB67\fP of file \fBDialogDrama\&.cs\fP\&.
.SS "virtual void DialogDrama\&.SetText (string detail = \fR''\fP, bool center = \fRfalse\fP)\fR [virtual]\fP"

.PP
Definition at line \fB49\fP of file \fBDialogDrama\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "Font DialogDrama\&.fontRune"

.PP
Definition at line \fB130\fP of file \fBDialogDrama\&.cs\fP\&.
.SS "Glitch DialogDrama\&.glitch"

.PP
Definition at line \fB133\fP of file \fBDialogDrama\&.cs\fP\&.
.SS "GameObject DialogDrama\&.goAffinity"

.PP
Definition at line \fB118\fP of file \fBDialogDrama\&.cs\fP\&.
.SS "HyphenationJpn DialogDrama\&.hypen"

.PP
Definition at line \fB106\fP of file \fBDialogDrama\&.cs\fP\&.
.SS "GameObject DialogDrama\&.iconNext"

.PP
Definition at line \fB115\fP of file \fBDialogDrama\&.cs\fP\&.
.SS "LayoutGroup DialogDrama\&.layoutInterest"

.PP
Definition at line \fB124\fP of file \fBDialogDrama\&.cs\fP\&.
.SS "Transform DialogDrama\&.moldInterest"

.PP
Definition at line \fB127\fP of file \fBDialogDrama\&.cs\fP\&.
.SS "\fBPortrait\fP DialogDrama\&.portrait"

.PP
Definition at line \fB121\fP of file \fBDialogDrama\&.cs\fP\&.
.SS "Text DialogDrama\&.textAffinity"

.PP
Definition at line \fB79\fP of file \fBDialogDrama\&.cs\fP\&.
.SS "Text DialogDrama\&.textBio"

.PP
Definition at line \fB76\fP of file \fBDialogDrama\&.cs\fP\&.
.SS "Text DialogDrama\&.textFav"

.PP
Definition at line \fB85\fP of file \fBDialogDrama\&.cs\fP\&.
.SS "UIText DialogDrama\&.textMain"

.PP
Definition at line \fB103\fP of file \fBDialogDrama\&.cs\fP\&.
.SS "Text DialogDrama\&.textName"

.PP
Definition at line \fB73\fP of file \fBDialogDrama\&.cs\fP\&.
.SS "Text DialogDrama\&.textNoInterest"

.PP
Definition at line \fB82\fP of file \fBDialogDrama\&.cs\fP\&.
.SS "Text DialogDrama\&.textRank"

.PP
Definition at line \fB88\fP of file \fBDialogDrama\&.cs\fP\&.
.SS "GameObject DialogDrama\&.transAffinity"

.PP
Definition at line \fB94\fP of file \fBDialogDrama\&.cs\fP\&.
.SS "Transform DialogDrama\&.transChoices"

.PP
Definition at line \fB109\fP of file \fBDialogDrama\&.cs\fP\&.
.SS "GameObject DialogDrama\&.transFav"

.PP
Definition at line \fB97\fP of file \fBDialogDrama\&.cs\fP\&.
.SS "GameObject DialogDrama\&.transInterest"

.PP
Definition at line \fB91\fP of file \fBDialogDrama\&.cs\fP\&.
.SS "GameObject DialogDrama\&.transRank"

.PP
Definition at line \fB100\fP of file \fBDialogDrama\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
