.TH "Dice" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Dice
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDice\fP (int _num=0, int _sides=0, int _bonus=0, \fBCard\fP _card=null)"
.br
.ti -1c
.RI "int \fBRoll\fP ()"
.br
.ti -1c
.RI "int \fBRollMax\fP ()"
.br
.ti -1c
.RI "override string \fBToString\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static int \fBRoll\fP (int num, int sides, int bonus=0, \fBCard\fP card=null)"
.br
.ti -1c
.RI "static int \fBRollMax\fP (int num, int sides, int bonus=0)"
.br
.ti -1c
.RI "static int \fBrnd\fP (int a)"
.br
.ti -1c
.RI "static \fBDice\fP \fBParse\fP (string raw)"
.br
.ti -1c
.RI "static \fBDice\fP \fBCreate\fP (\fBElement\fP ele, \fBCard\fP c)"
.br
.ti -1c
.RI "static \fBDice\fP \fBCreate\fP (string id, int power, \fBCard\fP c=null, \fBAct\fP act=null)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBnum\fP"
.br
.ti -1c
.RI "int \fBsides\fP"
.br
.ti -1c
.RI "int \fBbonus\fP"
.br
.ti -1c
.RI "\fBCard\fP \fBcard\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static \fBDice\fP \fBNull\fP = new \fBDice\fP(0, 0, 0, null)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB6\fP of file \fBDice\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Dice\&.Dice (int _num = \fR0\fP, int _sides = \fR0\fP, int _bonus = \fR0\fP, \fBCard\fP _card = \fRnull\fP)"

.PP
Definition at line \fB48\fP of file \fBDice\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "static \fBDice\fP Dice\&.Create (\fBElement\fP ele, \fBCard\fP c)\fR [static]\fP"

.PP
Definition at line \fB93\fP of file \fBDice\&.cs\fP\&.
.SS "static \fBDice\fP Dice\&.Create (string id, int power, \fBCard\fP c = \fRnull\fP, \fBAct\fP act = \fRnull\fP)\fR [static]\fP"

.PP
Definition at line \fB121\fP of file \fBDice\&.cs\fP\&.
.SS "static \fBDice\fP Dice\&.Parse (string raw)\fR [static]\fP"

.PP
Definition at line \fB57\fP of file \fBDice\&.cs\fP\&.
.SS "static int Dice\&.rnd (int a)\fR [static]\fP"

.PP
Definition at line \fB42\fP of file \fBDice\&.cs\fP\&.
.SS "int Dice\&.Roll ()"

.PP
Definition at line \fB75\fP of file \fBDice\&.cs\fP\&.
.SS "static int Dice\&.Roll (int num, int sides, int bonus = \fR0\fP, \fBCard\fP card = \fRnull\fP)\fR [static]\fP"

.PP
Definition at line \fB9\fP of file \fBDice\&.cs\fP\&.
.SS "int Dice\&.RollMax ()"

.PP
Definition at line \fB81\fP of file \fBDice\&.cs\fP\&.
.SS "static int Dice\&.RollMax (int num, int sides, int bonus = \fR0\fP)\fR [static]\fP"

.PP
Definition at line \fB36\fP of file \fBDice\&.cs\fP\&.
.SS "override string Dice\&.ToString ()"

.PP
Definition at line \fB87\fP of file \fBDice\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int Dice\&.bonus"

.PP
Definition at line \fB171\fP of file \fBDice\&.cs\fP\&.
.SS "\fBCard\fP Dice\&.card"

.PP
Definition at line \fB174\fP of file \fBDice\&.cs\fP\&.
.SS "\fBDice\fP Dice\&.Null = new \fBDice\fP(0, 0, 0, null)\fR [static]\fP"

.PP
Definition at line \fB162\fP of file \fBDice\&.cs\fP\&.
.SS "int Dice\&.num"

.PP
Definition at line \fB165\fP of file \fBDice\&.cs\fP\&.
.SS "int Dice\&.sides"

.PP
Definition at line \fB168\fP of file \fBDice\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
