.TH "DNA" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DNA
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBEClass\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBType\fP { \fBInferior\fP, \fBDefault\fP = 3, \fBSuperior\fP = 5, \fBBrain\fP = 8 }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBApply\fP (\fBChara\fP c)"
.br
.ti -1c
.RI "void \fBApply\fP (\fBChara\fP c, bool reverse)"
.br
.ti -1c
.RI "void \fBGenerateWithGene\fP (DNA\&.Type _type, \fBCard\fP gene, \fBChara\fP model=null)"
.br
.ti -1c
.RI "void \fBGenerate\fP (DNA\&.Type _type, \fBChara\fP model=null)"
.br
.ti -1c
.RI "void \fBCalcCost\fP ()"
.br
.ti -1c
.RI "string \fBGetMaterialId\fP (DNA\&.Type type)"
.br
.ti -1c
.RI "int \fBGetDurationHour\fP ()"
.br
.ti -1c
.RI "DNA\&.Type \fBGetRandomType\fP ()"
.br
.ti -1c
.RI "string \fBGetText\fP ()"
.br
.ti -1c
.RI "void \fBWriteNote\fP (UINote n)"
.br
.ti -1c
.RI "\fBElement\fP \fBGetInvalidFeat\fP (\fBChara\fP c)"
.br
.ti -1c
.RI "\fBElement\fP \fBGetInvalidAction\fP (\fBChara\fP c)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBThing\fP \fBGenerateGene\fP (\fBChara\fP c, DNA\&.Type? type=null)"
.br
.ti -1c
.RI "static \fBThing\fP \fBGenerateGene\fP (\fBCardRow\fP r, DNA\&.Type? type=null, int lv=\-1, int seed=\-1)"
.br
.ti -1c
.RI "static DNA\&.Type \fBGetType\fP (string idMat)"
.br
.in -1c

Static Public Member Functions inherited from \fBEClass\fP
.in +1c
.ti -1c
.RI "static int \fBrnd\fP (int a)"
.br
.ti -1c
.RI "static int \fBcurve\fP (int a, int start, int step, int rate=75)"
.br
.ti -1c
.RI "static int \fBrndHalf\fP (int a)"
.br
.ti -1c
.RI "static float \fBrndf\fP (float a)"
.br
.ti -1c
.RI "static int \fBrndSqrt\fP (int a)"
.br
.ti -1c
.RI "static void \fBWait\fP (float a, \fBCard\fP c)"
.br
.ti -1c
.RI "static void \fBWait\fP (float a, \fBPoint\fP p)"
.br
.ti -1c
.RI "static int \fBBigger\fP (int a, int b)"
.br
.ti -1c
.RI "static int \fBSmaller\fP (int a, int b)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBid\fP"
.br
.ti -1c
.RI "int[] \fBints\fP = new int[4]"
.br
.ti -1c
.RI "List< int > \fBvals\fP = new List<int>()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "DNA\&.Type \fBtype\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "int \fBcost\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "int \fBlv\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "int \fBseed\fP\fR [get, set]\fP"
.br
.in -1c

Properties inherited from \fBEClass\fP
.in +1c
.ti -1c
.RI "static \fBGame\fP \fBgame\fP\fR [get]\fP"
.br
.ti -1c
.RI "static bool \fBAdvMode\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBPlayer\fP \fBplayer\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBChara\fP \fBpc\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBUI\fP \fBui\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBMap\fP \fB_map\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBZone\fP \fB_zone\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranchOrHomeBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFaction\fP \fBHome\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFaction\fP \fBWilds\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBScene\fP \fBscene\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBBaseGameScreen\fP \fBscreen\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameSetting\fP \fBsetting\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameData\fP \fBgamedata\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBColorProfile\fP \fBColors\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBWorld\fP \fBworld\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBsources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBeditorSources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static SoundManager \fBSound\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBCoreDebug\fP \fBdebug\fP\fR [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Static Public Attributes inherited from \fBEClass\fP
.in +1c
.ti -1c
.RI "static \fBCore\fP \fBcore\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB8\fP of file \fBDNA\&.cs\fP\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "enum DNA\&.Type"

.PP
Definition at line \fB647\fP of file \fBDNA\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void DNA\&.Apply (\fBChara\fP c)"

.PP
Definition at line \fB103\fP of file \fBDNA\&.cs\fP\&.
.SS "void DNA\&.Apply (\fBChara\fP c, bool reverse)"

.PP
Definition at line \fB121\fP of file \fBDNA\&.cs\fP\&.
.SS "void DNA\&.CalcCost ()"

.PP
Definition at line \fB267\fP of file \fBDNA\&.cs\fP\&.
.SS "void DNA\&.Generate (DNA\&.Type _type, \fBChara\fP model = \fRnull\fP)"

.PP
Definition at line \fB187\fP of file \fBDNA\&.cs\fP\&.
.SS "static \fBThing\fP DNA\&.GenerateGene (\fBCardRow\fP r, DNA\&.Type? type = \fRnull\fP, int lv = \fR\-1\fP, int seed = \fR\-1\fP)\fR [static]\fP"

.PP
Definition at line \fB87\fP of file \fBDNA\&.cs\fP\&.
.SS "static \fBThing\fP DNA\&.GenerateGene (\fBChara\fP c, DNA\&.Type? type = \fRnull\fP)\fR [static]\fP"

.PP
Definition at line \fB71\fP of file \fBDNA\&.cs\fP\&.
.SS "void DNA\&.GenerateWithGene (DNA\&.Type _type, \fBCard\fP gene, \fBChara\fP model = \fRnull\fP)"

.PP
Definition at line \fB179\fP of file \fBDNA\&.cs\fP\&.
.SS "int DNA\&.GetDurationHour ()"

.PP
Definition at line \fB312\fP of file \fBDNA\&.cs\fP\&.
.SS "\fBElement\fP DNA\&.GetInvalidAction (\fBChara\fP c)"

.PP
Definition at line \fB440\fP of file \fBDNA\&.cs\fP\&.
.SS "\fBElement\fP DNA\&.GetInvalidFeat (\fBChara\fP c)"

.PP
Definition at line \fB426\fP of file \fBDNA\&.cs\fP\&.
.SS "string DNA\&.GetMaterialId (DNA\&.Type type)"

.PP
Definition at line \fB294\fP of file \fBDNA\&.cs\fP\&.
.SS "DNA\&.Type DNA\&.GetRandomType ()"

.PP
Definition at line \fB318\fP of file \fBDNA\&.cs\fP\&.
.SS "string DNA\&.GetText ()"

.PP
Definition at line \fB332\fP of file \fBDNA\&.cs\fP\&.
.SS "static DNA\&.Type DNA\&.GetType (string idMat)\fR [static]\fP"

.PP
Definition at line \fB276\fP of file \fBDNA\&.cs\fP\&.
.SS "void DNA\&.WriteNote (UINote n)"

.PP
Definition at line \fB340\fP of file \fBDNA\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "string DNA\&.id"

.PP
Definition at line \fB636\fP of file \fBDNA\&.cs\fP\&.
.SS "int [] DNA\&.ints = new int[4]"

.PP
Definition at line \fB640\fP of file \fBDNA\&.cs\fP\&.
.SS "List<int> DNA\&.vals = new List<int>()"

.PP
Definition at line \fB644\fP of file \fBDNA\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "int DNA\&.cost\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB28\fP of file \fBDNA\&.cs\fP\&.
.SS "int DNA\&.lv\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB43\fP of file \fBDNA\&.cs\fP\&.
.SS "int DNA\&.seed\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB58\fP of file \fBDNA\&.cs\fP\&.
.SS "DNA\&.Type DNA\&.type\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB13\fP of file \fBDNA\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
