.TH "DragItemCard.DragInfo" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DragItemCard.DragInfo
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDragInfo\fP (\fBButtonGrid\fP b)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBButtonGrid\fP \fBbutton\fP"
.br
.ti -1c
.RI "\fBBodySlot\fP \fBequippedSlot\fP"
.br
.ti -1c
.RI "int \fBinvX\fP"
.br
.ti -1c
.RI "int \fBinvY\fP"
.br
.ti -1c
.RI "\fBThing\fP \fBthing\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "List< \fBThing\fP > \fBgrid\fP\fR [get]\fP"
.br
.ti -1c
.RI "\fBInvOwner\fP \fBinvOwner\fP\fR [get]\fP"
.br
.ti -1c
.RI "\fBCard\fP \fBcontainer\fP\fR [get]\fP"
.br
.ti -1c
.RI "BaseList \fBlist\fP\fR [get]\fP"
.br
.ti -1c
.RI "ContainerType \fBContainerType\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB71\fP of file \fBDragItemCard\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "DragItemCard\&.DragInfo\&.DragInfo (\fBButtonGrid\fP b)"

.PP
Definition at line \fB74\fP of file \fBDragItemCard\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBButtonGrid\fP DragItemCard\&.DragInfo\&.button"

.PP
Definition at line \fB149\fP of file \fBDragItemCard\&.cs\fP\&.
.SS "\fBBodySlot\fP DragItemCard\&.DragInfo\&.equippedSlot"

.PP
Definition at line \fB152\fP of file \fBDragItemCard\&.cs\fP\&.
.SS "int DragItemCard\&.DragInfo\&.invX"

.PP
Definition at line \fB155\fP of file \fBDragItemCard\&.cs\fP\&.
.SS "int DragItemCard\&.DragInfo\&.invY"

.PP
Definition at line \fB158\fP of file \fBDragItemCard\&.cs\fP\&.
.SS "\fBThing\fP DragItemCard\&.DragInfo\&.thing"

.PP
Definition at line \fB161\fP of file \fBDragItemCard\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "\fBCard\fP DragItemCard\&.DragInfo\&.container\fR [get]\fP"

.PP
Definition at line \fB120\fP of file \fBDragItemCard\&.cs\fP\&.
.SS "ContainerType DragItemCard\&.DragInfo\&.ContainerType\fR [get]\fP"

.PP
Definition at line \fB140\fP of file \fBDragItemCard\&.cs\fP\&.
.SS "List<\fBThing\fP> DragItemCard\&.DragInfo\&.grid\fR [get]\fP"

.PP
Definition at line \fB100\fP of file \fBDragItemCard\&.cs\fP\&.
.SS "\fBInvOwner\fP DragItemCard\&.DragInfo\&.invOwner\fR [get]\fP"

.PP
Definition at line \fB110\fP of file \fBDragItemCard\&.cs\fP\&.
.SS "BaseList DragItemCard\&.DragInfo\&.list\fR [get]\fP"

.PP
Definition at line \fB130\fP of file \fBDragItemCard\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
