.TH "DramaManager" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DramaManager
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBEMono\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDramaSequence\fP \fBPlay\fP (\fBDramaSetup\fP setup)"
.br
.ti -1c
.RI "\fBDramaSequence\fP \fBLoad\fP ()"
.br
.ti -1c
.RI "void \fBAddCustomEvents\fP (string idCustom='Resident')"
.br
.ti -1c
.RI "unsafe void \fBParseLine\fP (Dictionary< string, string > item)"
.br
.ti -1c
.RI "\fBDramaActor\fP \fBGetActor\fP (string id)"
.br
.ti -1c
.RI "\fBDramaEvent\fP \fBAddEvent\fP (\fBDramaEvent\fP e)"
.br
.ti -1c
.RI "\fBDramaEventMethod\fP \fBAddEvent\fP (Action func, float duration=0f, bool halt=false)"
.br
.ti -1c
.RI "\fBDramaEventMethod\fP \fBAddEvent\fP (Action func, Func< string > funcJump)"
.br
.ti -1c
.RI "\fBDramaEvent\fP \fBCustomEvent\fP (Action func, string step=null, float duration=0f, bool halt=false)"
.br
.ti -1c
.RI "void \fBSetDialog\fP (string id='Default')"
.br
.ti -1c
.RI "bool \fBCheckIF\fP (string IF)"
.br
.ti -1c
.RI "void \fBShow\fP ()"
.br
.ti -1c
.RI "void \fBHide\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBLayerDrama\fP \fBlayer\fP"
.br
.ti -1c
.RI "CanvasGroup \fBcg\fP"
.br
.ti -1c
.RI "CanvasGroup \fBcgCover\fP"
.br
.ti -1c
.RI "UIDynamicList \fBlistCredit\fP"
.br
.ti -1c
.RI "Transform \fBactorPos\fP"
.br
.ti -1c
.RI "Transform \fBendroll\fP"
.br
.ti -1c
.RI "\fBDramaActor\fP \fBmoldActor\fP"
.br
.ti -1c
.RI "\fBDramaSequence\fP \fBsequence\fP"
.br
.ti -1c
.RI "\fBDramaOutcome\fP \fBoutcome\fP"
.br
.ti -1c
.RI "\fBDialogDrama\fP \fBdialog\fP"
.br
.ti -1c
.RI "\fBDramaSetup\fP \fBsetup\fP"
.br
.ti -1c
.RI "GameObject \fBgoSkip\fP"
.br
.ti -1c
.RI "Image \fBimageBG\fP"
.br
.ti -1c
.RI "Image \fBimageCover\fP"
.br
.ti -1c
.RI "Font[] \fBfonts\fP"
.br
.ti -1c
.RI "\fBPerson\fP \fBtg\fP"
.br
.ti -1c
.RI "bool \fBbgmChanged\fP"
.br
.ti -1c
.RI "List< \fBDramaChoice\fP > \fB_choices\fP = new List<\fBDramaChoice\fP>()"
.br
.ti -1c
.RI "Dictionary< string, string > \fBcustomTalkTopics\fP = new Dictionary<string, string>()"
.br
.ti -1c
.RI "Dictionary< string, string > \fBdictLocalize\fP = new Dictionary<string, string>()"
.br
.ti -1c
.RI "float \fBcreditSpeed\fP"
.br
.ti -1c
.RI "\fBDramaEventTalk\fP \fBlastTalk\fP"
.br
.ti -1c
.RI "bool \fBenableTone\fP"
.br
.ti -1c
.RI "bool \fBcustomEventsAdded\fP"
.br
.ti -1c
.RI "bool \fBidDefaultPassed\fP"
.br
.ti -1c
.RI "int \fBcountLine\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static \fBChara\fP \fBTG\fP"
.br
.ti -1c
.RI "static Dictionary< string, ExcelData > \fBdictCache\fP = new Dictionary<string, ExcelData>()"
.br
.in -1c

Static Public Attributes inherited from \fBEMono\fP
.in +1c
.ti -1c
.RI "static \fBCore\fP \fBcore\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBDramaActor\fP \fBtgActor\fP\fR [get]\fP"
.br
.in -1c

Properties inherited from \fBEMono\fP
.in +1c
.ti -1c
.RI "static \fBGame\fP \fBgame\fP\fR [get]\fP"
.br
.ti -1c
.RI "static bool \fBAdvMode\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBPlayer\fP \fBplayer\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBChara\fP \fBpc\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBUI\fP \fBui\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBMap\fP \fB_map\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBZone\fP \fB_zone\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranchOrHomeBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFaction\fP \fBHome\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBScene\fP \fBscene\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBBaseGameScreen\fP \fBscreen\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameSetting\fP \fBsetting\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameData\fP \fBgamedata\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBColorProfile\fP \fBColors\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBWorld\fP \fBworld\fP\fR [get]\fP"
.br
.ti -1c
.RI "static SoundManager \fBSound\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBsources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBeditorSources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBCoreDebug\fP \fBdebug\fP\fR [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Static Public Member Functions inherited from \fBEMono\fP
.in +1c
.ti -1c
.RI "static int \fBrnd\fP (int a)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB11\fP of file \fBDramaManager\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void DramaManager\&.AddCustomEvents (string idCustom = \fR'Resident'\fP)"

.PP
Definition at line \fB107\fP of file \fBDramaManager\&.cs\fP\&.
.SS "\fBDramaEventMethod\fP DramaManager\&.AddEvent (Action func, float duration = \fR0f\fP, bool halt = \fRfalse\fP)"

.PP
Definition at line \fB1644\fP of file \fBDramaManager\&.cs\fP\&.
.SS "\fBDramaEventMethod\fP DramaManager\&.AddEvent (Action func, Func< string > funcJump)"

.PP
Definition at line \fB1650\fP of file \fBDramaManager\&.cs\fP\&.
.SS "\fBDramaEvent\fP DramaManager\&.AddEvent (\fBDramaEvent\fP e)"

.PP
Definition at line \fB1638\fP of file \fBDramaManager\&.cs\fP\&.
.SS "bool DramaManager\&.CheckIF (string IF)"

.PP
Definition at line \fB1687\fP of file \fBDramaManager\&.cs\fP\&.
.SS "\fBDramaEvent\fP DramaManager\&.CustomEvent (Action func, string step = \fRnull\fP, float duration = \fR0f\fP, bool halt = \fRfalse\fP)"

.PP
Definition at line \fB1659\fP of file \fBDramaManager\&.cs\fP\&.
.SS "\fBDramaActor\fP DramaManager\&.GetActor (string id)"

.PP
Definition at line \fB1622\fP of file \fBDramaManager\&.cs\fP\&.
.SS "void DramaManager\&.Hide ()"

.PP
Definition at line \fB1960\fP of file \fBDramaManager\&.cs\fP\&.
.SS "\fBDramaSequence\fP DramaManager\&.Load ()"

.PP
Definition at line \fB51\fP of file \fBDramaManager\&.cs\fP\&.
.SS "unsafe void DramaManager\&.ParseLine (Dictionary< string, string > item)"

.PP
Definition at line \fB143\fP of file \fBDramaManager\&.cs\fP\&.
.SS "\fBDramaSequence\fP DramaManager\&.Play (\fBDramaSetup\fP setup)"

.PP
Definition at line \fB24\fP of file \fBDramaManager\&.cs\fP\&.
.SS "void DramaManager\&.SetDialog (string id = \fR'Default'\fP)"

.PP
Definition at line \fB1670\fP of file \fBDramaManager\&.cs\fP\&.
.SS "void DramaManager\&.Show ()"

.PP
Definition at line \fB1951\fP of file \fBDramaManager\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "List<\fBDramaChoice\fP> DramaManager\&._choices = new List<\fBDramaChoice\fP>()"

.PP
Definition at line \fB2023\fP of file \fBDramaManager\&.cs\fP\&.
.SS "Transform DramaManager\&.actorPos"

.PP
Definition at line \fB1981\fP of file \fBDramaManager\&.cs\fP\&.
.SS "bool DramaManager\&.bgmChanged"

.PP
Definition at line \fB2017\fP of file \fBDramaManager\&.cs\fP\&.
.SS "CanvasGroup DramaManager\&.cg"

.PP
Definition at line \fB1972\fP of file \fBDramaManager\&.cs\fP\&.
.SS "CanvasGroup DramaManager\&.cgCover"

.PP
Definition at line \fB1975\fP of file \fBDramaManager\&.cs\fP\&.
.SS "int DramaManager\&.countLine"

.PP
Definition at line \fB2053\fP of file \fBDramaManager\&.cs\fP\&.
.SS "float DramaManager\&.creditSpeed"

.PP
Definition at line \fB2032\fP of file \fBDramaManager\&.cs\fP\&.
.SS "bool DramaManager\&.customEventsAdded"

.PP
Definition at line \fB2047\fP of file \fBDramaManager\&.cs\fP\&.
.SS "Dictionary<string, string> DramaManager\&.customTalkTopics = new Dictionary<string, string>()"

.PP
Definition at line \fB2026\fP of file \fBDramaManager\&.cs\fP\&.
.SS "\fBDialogDrama\fP DramaManager\&.dialog"

.PP
Definition at line \fB1996\fP of file \fBDramaManager\&.cs\fP\&.
.SS "Dictionary<string, ExcelData> DramaManager\&.dictCache = new Dictionary<string, ExcelData>()\fR [static]\fP"

.PP
Definition at line \fB2062\fP of file \fBDramaManager\&.cs\fP\&.
.SS "Dictionary<string, string> DramaManager\&.dictLocalize = new Dictionary<string, string>()"

.PP
Definition at line \fB2029\fP of file \fBDramaManager\&.cs\fP\&.
.SS "bool DramaManager\&.enableTone"

.PP
Definition at line \fB2044\fP of file \fBDramaManager\&.cs\fP\&.
.SS "Transform DramaManager\&.endroll"

.PP
Definition at line \fB1984\fP of file \fBDramaManager\&.cs\fP\&.
.SS "Font [] DramaManager\&.fonts"

.PP
Definition at line \fB2011\fP of file \fBDramaManager\&.cs\fP\&.
.SS "GameObject DramaManager\&.goSkip"

.PP
Definition at line \fB2002\fP of file \fBDramaManager\&.cs\fP\&.
.SS "bool DramaManager\&.idDefaultPassed"

.PP
Definition at line \fB2050\fP of file \fBDramaManager\&.cs\fP\&.
.SS "Image DramaManager\&.imageBG"

.PP
Definition at line \fB2005\fP of file \fBDramaManager\&.cs\fP\&.
.SS "Image DramaManager\&.imageCover"

.PP
Definition at line \fB2008\fP of file \fBDramaManager\&.cs\fP\&.
.SS "\fBDramaEventTalk\fP DramaManager\&.lastTalk"

.PP
Definition at line \fB2041\fP of file \fBDramaManager\&.cs\fP\&.
.SS "\fBLayerDrama\fP DramaManager\&.layer"

.PP
Definition at line \fB1969\fP of file \fBDramaManager\&.cs\fP\&.
.SS "UIDynamicList DramaManager\&.listCredit"

.PP
Definition at line \fB1978\fP of file \fBDramaManager\&.cs\fP\&.
.SS "\fBDramaActor\fP DramaManager\&.moldActor"

.PP
Definition at line \fB1987\fP of file \fBDramaManager\&.cs\fP\&.
.SS "\fBDramaOutcome\fP DramaManager\&.outcome"

.PP
Definition at line \fB1993\fP of file \fBDramaManager\&.cs\fP\&.
.SS "\fBDramaSequence\fP DramaManager\&.sequence"

.PP
Definition at line \fB1990\fP of file \fBDramaManager\&.cs\fP\&.
.SS "\fBDramaSetup\fP DramaManager\&.setup"

.PP
Definition at line \fB1999\fP of file \fBDramaManager\&.cs\fP\&.
.SS "\fBChara\fP DramaManager\&.TG\fR [static]\fP"

.PP
Definition at line \fB1966\fP of file \fBDramaManager\&.cs\fP\&.
.SS "\fBPerson\fP DramaManager\&.tg"

.PP
Definition at line \fB2014\fP of file \fBDramaManager\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "\fBDramaActor\fP DramaManager\&.tgActor\fR [get]\fP"

.PP
Definition at line \fB1629\fP of file \fBDramaManager\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
