.TH "DramaSequence" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DramaSequence
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBEClass\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBTemplate\fP { \fBDefault\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBClear\fP ()"
.br
.ti -1c
.RI "\fBDramaActor\fP \fBGetActor\fP (string id)"
.br
.ti -1c
.RI "T \fBGetEvent< T >\fP (string idStep)"
.br
.ti -1c
.RI "\fBDramaActor\fP \fBAddActor\fP (string id, \fBPerson\fP person)"
.br
.ti -1c
.RI "void \fBAddStep\fP (string id)"
.br
.ti -1c
.RI "\fBDramaEvent\fP \fBAddEvent\fP (\fBDramaEvent\fP e)"
.br
.ti -1c
.RI "void \fBPlayNext\fP ()"
.br
.ti -1c
.RI "void \fBPlay\fP (string id)"
.br
.ti -1c
.RI "void \fBPlay\fP (int eventID=0)"
.br
.ti -1c
.RI "void \fBExit\fP ()"
.br
.ti -1c
.RI "void \fBOnUpdate\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBid\fP"
.br
.ti -1c
.RI "\fBDramaManager\fP \fBmanager\fP"
.br
.ti -1c
.RI "Dictionary< string, int > \fBsteps\fP = new Dictionary<string, int>()"
.br
.ti -1c
.RI "Dictionary< string, \fBDramaActor\fP > \fBactors\fP = new Dictionary<string, \fBDramaActor\fP>()"
.br
.ti -1c
.RI "List< \fBDramaEvent\fP > \fBevents\fP = new List<\fBDramaEvent\fP>()"
.br
.ti -1c
.RI "bool \fBisLoop\fP"
.br
.ti -1c
.RI "bool \fBcanCancel\fP = true"
.br
.ti -1c
.RI "bool \fBisExited\fP"
.br
.ti -1c
.RI "bool \fBfullPortrait\fP"
.br
.ti -1c
.RI "\fBDramaEventTalk\fP \fBfirstTalk\fP"
.br
.ti -1c
.RI "List< \fBDramaEvent\fP > \fBtempEvents\fP = new List<\fBDramaEvent\fP>()"
.br
.ti -1c
.RI "string \fBmessage\fP = ''"
.br
.ti -1c
.RI "string \fBskipJump\fP"
.br
.ti -1c
.RI "string \fBlastStep\fP"
.br
.ti -1c
.RI "string \fBlastlastStep\fP"
.br
.ti -1c
.RI "\fBDramaSetup\fP \fBsetup\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBDialogDrama\fP \fBdialog\fP\fR [get]\fP"
.br
.in -1c

Properties inherited from \fBEClass\fP
.in +1c
.ti -1c
.RI "static \fBGame\fP \fBgame\fP\fR [get]\fP"
.br
.ti -1c
.RI "static bool \fBAdvMode\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBPlayer\fP \fBplayer\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBChara\fP \fBpc\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBUI\fP \fBui\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBMap\fP \fB_map\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBZone\fP \fB_zone\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranchOrHomeBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFaction\fP \fBHome\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFaction\fP \fBWilds\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBScene\fP \fBscene\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBBaseGameScreen\fP \fBscreen\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameSetting\fP \fBsetting\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameData\fP \fBgamedata\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBColorProfile\fP \fBColors\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBWorld\fP \fBworld\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBsources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBeditorSources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static SoundManager \fBSound\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBCoreDebug\fP \fBdebug\fP\fR [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Static Public Member Functions inherited from \fBEClass\fP
.in +1c
.ti -1c
.RI "static int \fBrnd\fP (int a)"
.br
.ti -1c
.RI "static int \fBcurve\fP (int a, int start, int step, int rate=75)"
.br
.ti -1c
.RI "static int \fBrndHalf\fP (int a)"
.br
.ti -1c
.RI "static float \fBrndf\fP (float a)"
.br
.ti -1c
.RI "static int \fBrndSqrt\fP (int a)"
.br
.ti -1c
.RI "static void \fBWait\fP (float a, \fBCard\fP c)"
.br
.ti -1c
.RI "static void \fBWait\fP (float a, \fBPoint\fP p)"
.br
.ti -1c
.RI "static int \fBBigger\fP (int a, int b)"
.br
.ti -1c
.RI "static int \fBSmaller\fP (int a, int b)"
.br
.in -1c

Static Public Attributes inherited from \fBEClass\fP
.in +1c
.ti -1c
.RI "static \fBCore\fP \fBcore\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB6\fP of file \fBDramaSequence\&.cs\fP\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "enum DramaSequence\&.Template"

.PP
Definition at line \fB249\fP of file \fBDramaSequence\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBDramaActor\fP DramaSequence\&.AddActor (string id, \fBPerson\fP person)"

.PP
Definition at line \fB59\fP of file \fBDramaSequence\&.cs\fP\&.
.SS "\fBDramaEvent\fP DramaSequence\&.AddEvent (\fBDramaEvent\fP e)"

.PP
Definition at line \fB83\fP of file \fBDramaSequence\&.cs\fP\&.
.SS "void DramaSequence\&.AddStep (string id)"

.PP
Definition at line \fB72\fP of file \fBDramaSequence\&.cs\fP\&.
.SS "void DramaSequence\&.Clear ()"

.PP
Definition at line \fB19\fP of file \fBDramaSequence\&.cs\fP\&.
.SS "void DramaSequence\&.Exit ()"

.PP
Definition at line \fB151\fP of file \fBDramaSequence\&.cs\fP\&.
.SS "\fBDramaActor\fP DramaSequence\&.GetActor (string id)"

.PP
Definition at line \fB28\fP of file \fBDramaSequence\&.cs\fP\&.
.SS "T DramaSequence\&.GetEvent< T > (string idStep)"

.PP
\fBType Constraints\fP
.TP
\fIT\fP : \fI\fBDramaEvent\fP\fP
.PP
Definition at line \fB46\fP of file \fBDramaSequence\&.cs\fP\&.
.SS "void DramaSequence\&.OnUpdate ()"

.PP
Definition at line \fB159\fP of file \fBDramaSequence\&.cs\fP\&.
.SS "void DramaSequence\&.Play (int eventID = \fR0\fP)"

.PP
Definition at line \fB115\fP of file \fBDramaSequence\&.cs\fP\&.
.SS "void DramaSequence\&.Play (string id)"

.PP
Definition at line \fB101\fP of file \fBDramaSequence\&.cs\fP\&.
.SS "void DramaSequence\&.PlayNext ()"

.PP
Definition at line \fB95\fP of file \fBDramaSequence\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "Dictionary<string, \fBDramaActor\fP> DramaSequence\&.actors = new Dictionary<string, \fBDramaActor\fP>()"

.PP
Definition at line \fB204\fP of file \fBDramaSequence\&.cs\fP\&.
.SS "bool DramaSequence\&.canCancel = true"

.PP
Definition at line \fB213\fP of file \fBDramaSequence\&.cs\fP\&.
.SS "List<\fBDramaEvent\fP> DramaSequence\&.events = new List<\fBDramaEvent\fP>()"

.PP
Definition at line \fB207\fP of file \fBDramaSequence\&.cs\fP\&.
.SS "\fBDramaEventTalk\fP DramaSequence\&.firstTalk"

.PP
Definition at line \fB222\fP of file \fBDramaSequence\&.cs\fP\&.
.SS "bool DramaSequence\&.fullPortrait"

.PP
Definition at line \fB219\fP of file \fBDramaSequence\&.cs\fP\&.
.SS "string DramaSequence\&.id"

.PP
Definition at line \fB195\fP of file \fBDramaSequence\&.cs\fP\&.
.SS "bool DramaSequence\&.isExited"

.PP
Definition at line \fB216\fP of file \fBDramaSequence\&.cs\fP\&.
.SS "bool DramaSequence\&.isLoop"

.PP
Definition at line \fB210\fP of file \fBDramaSequence\&.cs\fP\&.
.SS "string DramaSequence\&.lastlastStep"

.PP
Definition at line \fB240\fP of file \fBDramaSequence\&.cs\fP\&.
.SS "string DramaSequence\&.lastStep"

.PP
Definition at line \fB237\fP of file \fBDramaSequence\&.cs\fP\&.
.SS "\fBDramaManager\fP DramaSequence\&.manager"

.PP
Definition at line \fB198\fP of file \fBDramaSequence\&.cs\fP\&.
.SS "string DramaSequence\&.message = ''"

.PP
Definition at line \fB231\fP of file \fBDramaSequence\&.cs\fP\&.
.SS "\fBDramaSetup\fP DramaSequence\&.setup"

.PP
Definition at line \fB243\fP of file \fBDramaSequence\&.cs\fP\&.
.SS "string DramaSequence\&.skipJump"

.PP
Definition at line \fB234\fP of file \fBDramaSequence\&.cs\fP\&.
.SS "Dictionary<string, int> DramaSequence\&.steps = new Dictionary<string, int>()"

.PP
Definition at line \fB201\fP of file \fBDramaSequence\&.cs\fP\&.
.SS "List<\fBDramaEvent\fP> DramaSequence\&.tempEvents = new List<\fBDramaEvent\fP>()"

.PP
Definition at line \fB225\fP of file \fBDramaSequence\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "\fBDialogDrama\fP DramaSequence\&.dialog\fR [get]\fP"

.PP
Definition at line \fB10\fP of file \fBDramaSequence\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
