.TH "DramaChoice" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DramaChoice
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDramaChoice\fP (string text, string idJump, string idAction='', string CHECK='', string IF='')"
.br
.ti -1c
.RI "\fBDramaChoice\fP \fBDisableSound\fP ()"
.br
.ti -1c
.RI "\fBDramaChoice\fP \fBSetOnTooltip\fP (Action< UITooltip > action)"
.br
.ti -1c
.RI "\fBDramaChoice\fP \fBSetOnClick\fP (Action action)"
.br
.ti -1c
.RI "\fBDramaChoice\fP \fBSetCondition\fP (Func< bool > condition)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBindex\fP"
.br
.ti -1c
.RI "string \fBtext\fP"
.br
.ti -1c
.RI "string \fBidJump\fP"
.br
.ti -1c
.RI "string \fBidAction\fP"
.br
.ti -1c
.RI "string \fBCHECK\fP"
.br
.ti -1c
.RI "string \fBIF\fP"
.br
.ti -1c
.RI "bool \fBsound\fP = true"
.br
.ti -1c
.RI "bool \fBforceHighlight\fP"
.br
.ti -1c
.RI "Action \fBonClick\fP"
.br
.ti -1c
.RI "Action \fBonJump\fP"
.br
.ti -1c
.RI "Action< UITooltip > \fBonTooltip\fP"
.br
.ti -1c
.RI "Func< bool > \fBactiveCondition\fP"
.br
.ti -1c
.RI "\fBCheck\fP \fBcheck\fP"
.br
.ti -1c
.RI "UIButton \fBbutton\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static \fBDramaChoice\fP \fBlastChoice\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB4\fP of file \fBDramaChoice\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "DramaChoice\&.DramaChoice (string text, string idJump, string idAction = \fR''\fP, string CHECK = \fR''\fP, string IF = \fR''\fP)"

.PP
Definition at line \fB7\fP of file \fBDramaChoice\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBDramaChoice\fP DramaChoice\&.DisableSound ()"

.PP
Definition at line \fB17\fP of file \fBDramaChoice\&.cs\fP\&.
.SS "\fBDramaChoice\fP DramaChoice\&.SetCondition (Func< bool > condition)"

.PP
Definition at line \fB38\fP of file \fBDramaChoice\&.cs\fP\&.
.SS "\fBDramaChoice\fP DramaChoice\&.SetOnClick (Action action)"

.PP
Definition at line \fB31\fP of file \fBDramaChoice\&.cs\fP\&.
.SS "\fBDramaChoice\fP DramaChoice\&.SetOnTooltip (Action< UITooltip > action)"

.PP
Definition at line \fB24\fP of file \fBDramaChoice\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "Func<bool> DramaChoice\&.activeCondition"

.PP
Definition at line \fB81\fP of file \fBDramaChoice\&.cs\fP\&.
.SS "UIButton DramaChoice\&.button"

.PP
Definition at line \fB87\fP of file \fBDramaChoice\&.cs\fP\&.
.SS "string DramaChoice\&.CHECK"

.PP
Definition at line \fB60\fP of file \fBDramaChoice\&.cs\fP\&.
.SS "\fBCheck\fP DramaChoice\&.check"

.PP
Definition at line \fB84\fP of file \fBDramaChoice\&.cs\fP\&.
.SS "bool DramaChoice\&.forceHighlight"

.PP
Definition at line \fB69\fP of file \fBDramaChoice\&.cs\fP\&.
.SS "string DramaChoice\&.idAction"

.PP
Definition at line \fB57\fP of file \fBDramaChoice\&.cs\fP\&.
.SS "string DramaChoice\&.idJump"

.PP
Definition at line \fB54\fP of file \fBDramaChoice\&.cs\fP\&.
.SS "string DramaChoice\&.IF"

.PP
Definition at line \fB63\fP of file \fBDramaChoice\&.cs\fP\&.
.SS "int DramaChoice\&.index"

.PP
Definition at line \fB48\fP of file \fBDramaChoice\&.cs\fP\&.
.SS "\fBDramaChoice\fP DramaChoice\&.lastChoice\fR [static]\fP"

.PP
Definition at line \fB45\fP of file \fBDramaChoice\&.cs\fP\&.
.SS "Action DramaChoice\&.onClick"

.PP
Definition at line \fB72\fP of file \fBDramaChoice\&.cs\fP\&.
.SS "Action DramaChoice\&.onJump"

.PP
Definition at line \fB75\fP of file \fBDramaChoice\&.cs\fP\&.
.SS "Action<UITooltip> DramaChoice\&.onTooltip"

.PP
Definition at line \fB78\fP of file \fBDramaChoice\&.cs\fP\&.
.SS "bool DramaChoice\&.sound = true"

.PP
Definition at line \fB66\fP of file \fBDramaChoice\&.cs\fP\&.
.SS "string DramaChoice\&.text"

.PP
Definition at line \fB51\fP of file \fBDramaChoice\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
