.TH "DramaActor" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DramaActor
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBEMono\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBInit\fP (\fBDramaSequence\fP _sequence, string _id, \fBPerson\fP _owner)"
.br
.ti -1c
.RI "void \fBTalk\fP (string text, List< \fBDramaChoice\fP > choices, bool center, bool unknown)"
.br
.ti -1c
.RI "string \fBConvertAdv\fP (string text)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBid\fP"
.br
.ti -1c
.RI "\fBPerson\fP \fBowner\fP"
.br
.ti -1c
.RI "\fBDramaSequence\fP \fBsequence\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static bool \fBuseGlitch\fP"
.br
.in -1c

Static Public Attributes inherited from \fBEMono\fP
.in +1c
.ti -1c
.RI "static \fBCore\fP \fBcore\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBDialogDrama\fP \fBdialog\fP\fR [get]\fP"
.br
.in -1c

Properties inherited from \fBEMono\fP
.in +1c
.ti -1c
.RI "static \fBGame\fP \fBgame\fP\fR [get]\fP"
.br
.ti -1c
.RI "static bool \fBAdvMode\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBPlayer\fP \fBplayer\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBChara\fP \fBpc\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBUI\fP \fBui\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBMap\fP \fB_map\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBZone\fP \fB_zone\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranchOrHomeBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFaction\fP \fBHome\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBScene\fP \fBscene\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBBaseGameScreen\fP \fBscreen\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameSetting\fP \fBsetting\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameData\fP \fBgamedata\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBColorProfile\fP \fBColors\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBWorld\fP \fBworld\fP\fR [get]\fP"
.br
.ti -1c
.RI "static SoundManager \fBSound\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBsources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBeditorSources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBCoreDebug\fP \fBdebug\fP\fR [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Static Public Member Functions inherited from \fBEMono\fP
.in +1c
.ti -1c
.RI "static int \fBrnd\fP (int a)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB7\fP of file \fBDramaActor\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "string DramaActor\&.ConvertAdv (string text)"

.PP
Definition at line \fB231\fP of file \fBDramaActor\&.cs\fP\&.
.SS "void DramaActor\&.Init (\fBDramaSequence\fP _sequence, string _id, \fBPerson\fP _owner)"

.PP
Definition at line \fB20\fP of file \fBDramaActor\&.cs\fP\&.
.SS "void DramaActor\&.Talk (string text, List< \fBDramaChoice\fP > choices, bool center, bool unknown)"

.PP
Definition at line \fB29\fP of file \fBDramaActor\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "string DramaActor\&.id"

.PP
Definition at line \fB249\fP of file \fBDramaActor\&.cs\fP\&.
.SS "\fBPerson\fP DramaActor\&.owner"

.PP
Definition at line \fB252\fP of file \fBDramaActor\&.cs\fP\&.
.SS "\fBDramaSequence\fP DramaActor\&.sequence"

.PP
Definition at line \fB255\fP of file \fBDramaActor\&.cs\fP\&.
.SS "bool DramaActor\&.useGlitch\fR [static]\fP"

.PP
Definition at line \fB246\fP of file \fBDramaActor\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "\fBDialogDrama\fP DramaActor\&.dialog\fR [get]\fP"

.PP
Definition at line \fB11\fP of file \fBDramaActor\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
