.TH "DramaOutcome" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DramaOutcome
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBEMono\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBStartNewGame\fP ()"
.br
.ti -1c
.RI "void \fBStartNewGame2\fP ()"
.br
.ti -1c
.RI "void \fBPutOutFire\fP ()"
.br
.ti -1c
.RI "void \fBOnClaimLand\fP ()"
.br
.ti -1c
.RI "void \fBAddMaid\fP ()"
.br
.ti -1c
.RI "void \fBQuestSharedContainer_Drop1\fP ()"
.br
.ti -1c
.RI "void \fBQuestShippingChest_Drop1\fP ()"
.br
.ti -1c
.RI "void \fBQuestExploration_Drop1\fP ()"
.br
.ti -1c
.RI "void \fBQuestExploration_MeetFarris\fP ()"
.br
.ti -1c
.RI "void \fBQuestExploration_MeetFarris2\fP ()"
.br
.ti -1c
.RI "void \fBQuestExploration_AfterCrystal\fP ()"
.br
.ti -1c
.RI "void \fBQuestExploration_AfterComplete\fP ()"
.br
.ti -1c
.RI "void \fBQuestCraft_Drop1\fP ()"
.br
.ti -1c
.RI "void \fBQuestDefense_0\fP ()"
.br
.ti -1c
.RI "void \fBQuestVernis_DropRecipe\fP ()"
.br
.ti -1c
.RI "void \fBQuestDefense_1\fP ()"
.br
.ti -1c
.RI "void \fBQuestDefense_2\fP ()"
.br
.ti -1c
.RI "void \fBQuestDebt_reward\fP ()"
.br
.ti -1c
.RI "void \fBTutorial1\fP ()"
.br
.ti -1c
.RI "void \fBWelcomeMsg\fP ()"
.br
.ti -1c
.RI "void \fBchara_hired\fP ()"
.br
.ti -1c
.RI "void \fBchara_hired_ticket\fP ()"
.br
.ti -1c
.RI "void \fBnerun_gift\fP ()"
.br
.ti -1c
.RI "void \fBnerun_gift2\fP ()"
.br
.ti -1c
.RI "void \fBnerun_gift3\fP ()"
.br
.ti -1c
.RI "void \fBfiama_gold\fP ()"
.br
.ti -1c
.RI "void \fBfiama_pet1\fP ()"
.br
.ti -1c
.RI "void \fBfiama_pet2\fP ()"
.br
.ti -1c
.RI "void \fBfiama_pet3\fP ()"
.br
.ti -1c
.RI "void \fBfiama_pet4\fP ()"
.br
.ti -1c
.RI "void \fBfiama_starter_gift\fP ()"
.br
.ti -1c
.RI "void \fBrevive_pet\fP ()"
.br
.ti -1c
.RI "void \fBmelilith_friend\fP ()"
.br
.ti -1c
.RI "void \fBsister_friend\fP ()"
.br
.ti -1c
.RI "void \fBsister_change\fP ()"
.br
.ti -1c
.RI "void \fBget_scratch\fP ()"
.br
.ti -1c
.RI "void \fBpoppy_found\fP ()"
.br
.ti -1c
.RI "void \fBevent_swordkeeper\fP ()"
.br
.ti -1c
.RI "void \fBguild_trial\fP ()"
.br
.ti -1c
.RI "void \fBguild_join\fP ()"
.br
.ti -1c
.RI "void \fBguild_mageTrial\fP ()"
.br
.ti -1c
.RI "void \fBguild_promote\fP ()"
.br
.ti -1c
.RI "bool \fBcheck_sketch\fP ()"
.br
.ti -1c
.RI "int \fBGetFelmeraRewardIndex\fP ()"
.br
.ti -1c
.RI "bool \fBcheck_sketch2\fP ()"
.br
.ti -1c
.RI "List< \fBThing\fP > \fBListFelmeraBarter\fP ()"
.br
.ti -1c
.RI "void \fBgive_sketch_reward\fP ()"
.br
.ti -1c
.RI "void \fBgive_sketch_special\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBIf\fP (\fBDramaChoice\fP item, \fBChara\fP c)"
.br
.in -1c

Static Public Member Functions inherited from \fBEMono\fP
.in +1c
.ti -1c
.RI "static int \fBrnd\fP (int a)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBDramaManager\fP \fBmanager\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static string \fBidJump\fP"
.br
.in -1c

Static Public Attributes inherited from \fBEMono\fP
.in +1c
.ti -1c
.RI "static \fBCore\fP \fBcore\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBDramaSequence\fP \fBsequence\fP\fR [get]\fP"
.br
.ti -1c
.RI "\fBPerson\fP \fBtg\fP\fR [get]\fP"
.br
.ti -1c
.RI "\fBChara\fP \fBcc\fP\fR [get]\fP"
.br
.in -1c

Properties inherited from \fBEMono\fP
.in +1c
.ti -1c
.RI "static \fBGame\fP \fBgame\fP\fR [get]\fP"
.br
.ti -1c
.RI "static bool \fBAdvMode\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBPlayer\fP \fBplayer\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBChara\fP \fBpc\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBUI\fP \fBui\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBMap\fP \fB_map\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBZone\fP \fB_zone\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranchOrHomeBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFaction\fP \fBHome\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBScene\fP \fBscene\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBBaseGameScreen\fP \fBscreen\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameSetting\fP \fBsetting\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameData\fP \fBgamedata\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBColorProfile\fP \fBColors\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBWorld\fP \fBworld\fP\fR [get]\fP"
.br
.ti -1c
.RI "static SoundManager \fBSound\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBsources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBeditorSources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBCoreDebug\fP \fBdebug\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB6\fP of file \fBDramaOutcome\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void DramaOutcome\&.AddMaid ()"

.PP
Definition at line \fB86\fP of file \fBDramaOutcome\&.cs\fP\&.
.SS "void DramaOutcome\&.chara_hired ()"

.PP
Definition at line \fB220\fP of file \fBDramaOutcome\&.cs\fP\&.
.SS "void DramaOutcome\&.chara_hired_ticket ()"

.PP
Definition at line \fB232\fP of file \fBDramaOutcome\&.cs\fP\&.
.SS "bool DramaOutcome\&.check_sketch ()"

.PP
Definition at line \fB477\fP of file \fBDramaOutcome\&.cs\fP\&.
.SS "bool DramaOutcome\&.check_sketch2 ()"

.PP
Definition at line \fB530\fP of file \fBDramaOutcome\&.cs\fP\&.
.SS "void DramaOutcome\&.event_swordkeeper ()"

.PP
Definition at line \fB417\fP of file \fBDramaOutcome\&.cs\fP\&.
.SS "void DramaOutcome\&.fiama_gold ()"

.PP
Definition at line \fB272\fP of file \fBDramaOutcome\&.cs\fP\&.
.SS "void DramaOutcome\&.fiama_pet1 ()"

.PP
Definition at line \fB282\fP of file \fBDramaOutcome\&.cs\fP\&.
.SS "void DramaOutcome\&.fiama_pet2 ()"

.PP
Definition at line \fB289\fP of file \fBDramaOutcome\&.cs\fP\&.
.SS "void DramaOutcome\&.fiama_pet3 ()"

.PP
Definition at line \fB296\fP of file \fBDramaOutcome\&.cs\fP\&.
.SS "void DramaOutcome\&.fiama_pet4 ()"

.PP
Definition at line \fB303\fP of file \fBDramaOutcome\&.cs\fP\&.
.SS "void DramaOutcome\&.fiama_starter_gift ()"

.PP
Definition at line \fB318\fP of file \fBDramaOutcome\&.cs\fP\&.
.SS "void DramaOutcome\&.get_scratch ()"

.PP
Definition at line \fB397\fP of file \fBDramaOutcome\&.cs\fP\&.
.SS "int DramaOutcome\&.GetFelmeraRewardIndex ()"

.PP
Definition at line \fB510\fP of file \fBDramaOutcome\&.cs\fP\&.
.SS "void DramaOutcome\&.give_sketch_reward ()"

.PP
Definition at line \fB550\fP of file \fBDramaOutcome\&.cs\fP\&.
.SS "void DramaOutcome\&.give_sketch_special ()"

.PP
Definition at line \fB563\fP of file \fBDramaOutcome\&.cs\fP\&.
.SS "void DramaOutcome\&.guild_join ()"

.PP
Definition at line \fB441\fP of file \fBDramaOutcome\&.cs\fP\&.
.SS "void DramaOutcome\&.guild_mageTrial ()"

.PP
Definition at line \fB454\fP of file \fBDramaOutcome\&.cs\fP\&.
.SS "void DramaOutcome\&.guild_promote ()"

.PP
Definition at line \fB465\fP of file \fBDramaOutcome\&.cs\fP\&.
.SS "void DramaOutcome\&.guild_trial ()"

.PP
Definition at line \fB430\fP of file \fBDramaOutcome\&.cs\fP\&.
.SS "static bool DramaOutcome\&.If (\fBDramaChoice\fP item, \fBChara\fP c)\fR [static]\fP"

.PP
Definition at line \fB423\fP of file \fBDramaOutcome\&.cs\fP\&.
.SS "List< \fBThing\fP > DramaOutcome\&.ListFelmeraBarter ()"

.PP
Definition at line \fB536\fP of file \fBDramaOutcome\&.cs\fP\&.
.SS "void DramaOutcome\&.melilith_friend ()"

.PP
Definition at line \fB371\fP of file \fBDramaOutcome\&.cs\fP\&.
.SS "void DramaOutcome\&.nerun_gift ()"

.PP
Definition at line \fB241\fP of file \fBDramaOutcome\&.cs\fP\&.
.SS "void DramaOutcome\&.nerun_gift2 ()"

.PP
Definition at line \fB250\fP of file \fBDramaOutcome\&.cs\fP\&.
.SS "void DramaOutcome\&.nerun_gift3 ()"

.PP
Definition at line \fB259\fP of file \fBDramaOutcome\&.cs\fP\&.
.SS "void DramaOutcome\&.OnClaimLand ()"

.PP
Definition at line \fB75\fP of file \fBDramaOutcome\&.cs\fP\&.
.SS "void DramaOutcome\&.poppy_found ()"

.PP
Definition at line \fB404\fP of file \fBDramaOutcome\&.cs\fP\&.
.SS "void DramaOutcome\&.PutOutFire ()"

.PP
Definition at line \fB66\fP of file \fBDramaOutcome\&.cs\fP\&.
.SS "void DramaOutcome\&.QuestCraft_Drop1 ()"

.PP
Definition at line \fB160\fP of file \fBDramaOutcome\&.cs\fP\&.
.SS "void DramaOutcome\&.QuestDebt_reward ()"

.PP
Definition at line \fB199\fP of file \fBDramaOutcome\&.cs\fP\&.
.SS "void DramaOutcome\&.QuestDefense_0 ()"

.PP
Definition at line \fB166\fP of file \fBDramaOutcome\&.cs\fP\&.
.SS "void DramaOutcome\&.QuestDefense_1 ()"

.PP
Definition at line \fB182\fP of file \fBDramaOutcome\&.cs\fP\&.
.SS "void DramaOutcome\&.QuestDefense_2 ()"

.PP
Definition at line \fB194\fP of file \fBDramaOutcome\&.cs\fP\&.
.SS "void DramaOutcome\&.QuestExploration_AfterComplete ()"

.PP
Definition at line \fB148\fP of file \fBDramaOutcome\&.cs\fP\&.
.SS "void DramaOutcome\&.QuestExploration_AfterCrystal ()"

.PP
Definition at line \fB133\fP of file \fBDramaOutcome\&.cs\fP\&.
.SS "void DramaOutcome\&.QuestExploration_Drop1 ()"

.PP
Definition at line \fB103\fP of file \fBDramaOutcome\&.cs\fP\&.
.SS "void DramaOutcome\&.QuestExploration_MeetFarris ()"

.PP
Definition at line \fB110\fP of file \fBDramaOutcome\&.cs\fP\&.
.SS "void DramaOutcome\&.QuestExploration_MeetFarris2 ()"

.PP
Definition at line \fB121\fP of file \fBDramaOutcome\&.cs\fP\&.
.SS "void DramaOutcome\&.QuestSharedContainer_Drop1 ()"

.PP
Definition at line \fB91\fP of file \fBDramaOutcome\&.cs\fP\&.
.SS "void DramaOutcome\&.QuestShippingChest_Drop1 ()"

.PP
Definition at line \fB97\fP of file \fBDramaOutcome\&.cs\fP\&.
.SS "void DramaOutcome\&.QuestVernis_DropRecipe ()"

.PP
Definition at line \fB176\fP of file \fBDramaOutcome\&.cs\fP\&.
.SS "void DramaOutcome\&.revive_pet ()"

.PP
Definition at line \fB358\fP of file \fBDramaOutcome\&.cs\fP\&.
.SS "void DramaOutcome\&.sister_change ()"

.PP
Definition at line \fB391\fP of file \fBDramaOutcome\&.cs\fP\&.
.SS "void DramaOutcome\&.sister_friend ()"

.PP
Definition at line \fB380\fP of file \fBDramaOutcome\&.cs\fP\&.
.SS "void DramaOutcome\&.StartNewGame ()"

.PP
Definition at line \fB39\fP of file \fBDramaOutcome\&.cs\fP\&.
.SS "void DramaOutcome\&.StartNewGame2 ()"

.PP
Definition at line \fB49\fP of file \fBDramaOutcome\&.cs\fP\&.
.SS "void DramaOutcome\&.Tutorial1 ()"

.PP
Definition at line \fB205\fP of file \fBDramaOutcome\&.cs\fP\&.
.SS "void DramaOutcome\&.WelcomeMsg ()"

.PP
Definition at line \fB215\fP of file \fBDramaOutcome\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "string DramaOutcome\&.idJump\fR [static]\fP"

.PP
Definition at line \fB578\fP of file \fBDramaOutcome\&.cs\fP\&.
.SS "\fBDramaManager\fP DramaOutcome\&.manager"

.PP
Definition at line \fB581\fP of file \fBDramaOutcome\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "\fBChara\fP DramaOutcome\&.cc\fR [get]\fP"

.PP
Definition at line \fB30\fP of file \fBDramaOutcome\&.cs\fP\&.
.SS "\fBDramaSequence\fP DramaOutcome\&.sequence\fR [get]\fP"

.PP
Definition at line \fB10\fP of file \fBDramaOutcome\&.cs\fP\&.
.SS "\fBPerson\fP DramaOutcome\&.tg\fR [get]\fP"

.PP
Definition at line \fB20\fP of file \fBDramaOutcome\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
