.TH "DramaSetup" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DramaSetup
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBsheet\fP"
.br
.ti -1c
.RI "string \fBstep\fP"
.br
.ti -1c
.RI "string \fBbook\fP"
.br
.ti -1c
.RI "string \fBtextData\fP"
.br
.ti -1c
.RI "string \fBforceJump\fP"
.br
.ti -1c
.RI "string \fBtag\fP"
.br
.ti -1c
.RI "\fBCard\fP \fBref1\fP"
.br
.ti -1c
.RI "\fBPerson\fP \fBperson\fP"
.br
.ti -1c
.RI "Action \fBonComplete\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB4\fP of file \fBDramaSetup\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "string DramaSetup\&.book"

.PP
Definition at line \fB13\fP of file \fBDramaSetup\&.cs\fP\&.
.SS "string DramaSetup\&.forceJump"

.PP
Definition at line \fB19\fP of file \fBDramaSetup\&.cs\fP\&.
.SS "Action DramaSetup\&.onComplete"

.PP
Definition at line \fB31\fP of file \fBDramaSetup\&.cs\fP\&.
.SS "\fBPerson\fP DramaSetup\&.person"

.PP
Definition at line \fB28\fP of file \fBDramaSetup\&.cs\fP\&.
.SS "\fBCard\fP DramaSetup\&.ref1"

.PP
Definition at line \fB25\fP of file \fBDramaSetup\&.cs\fP\&.
.SS "string DramaSetup\&.sheet"

.PP
Definition at line \fB7\fP of file \fBDramaSetup\&.cs\fP\&.
.SS "string DramaSetup\&.step"

.PP
Definition at line \fB10\fP of file \fBDramaSetup\&.cs\fP\&.
.SS "string DramaSetup\&.tag"

.PP
Definition at line \fB22\fP of file \fBDramaSetup\&.cs\fP\&.
.SS "string DramaSetup\&.textData"

.PP
Definition at line \fB16\fP of file \fBDramaSetup\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
