.TH "DropdownRecipe" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DropdownRecipe
.SH SYNOPSIS
.br
.PP
.PP
Inherits UIDropdown\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBRefreshLabel\fP ()"
.br
.ti -1c
.RI "string \fBGetLabel\fP (\fBThing\fP t, bool showColor)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBRecipe\fP \fBrecipe\fP"
.br
.ti -1c
.RI "UIText \fBtextLabel\fP"
.br
.ti -1c
.RI "UIText \fBorgLabel\fP"
.br
.ti -1c
.RI "\fBRecipe\&.Ingredient\fP \fBingredient\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static Color \fBcolorCost\fP"
.br
.ti -1c
.RI "static Color \fBcolorPredict\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB5\fP of file \fBDropdownRecipe\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "string DropdownRecipe\&.GetLabel (\fBThing\fP t, bool showColor)"

.PP
Definition at line \fB14\fP of file \fBDropdownRecipe\&.cs\fP\&.
.SS "void DropdownRecipe\&.RefreshLabel ()"

.PP
Definition at line \fB8\fP of file \fBDropdownRecipe\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "Color DropdownRecipe\&.colorCost\fR [static]\fP"

.PP
Definition at line \fB47\fP of file \fBDropdownRecipe\&.cs\fP\&.
.SS "Color DropdownRecipe\&.colorPredict\fR [static]\fP"

.PP
Definition at line \fB50\fP of file \fBDropdownRecipe\&.cs\fP\&.
.SS "\fBRecipe\&.Ingredient\fP DropdownRecipe\&.ingredient"

.PP
Definition at line \fB62\fP of file \fBDropdownRecipe\&.cs\fP\&.
.SS "UIText DropdownRecipe\&.orgLabel"

.PP
Definition at line \fB59\fP of file \fBDropdownRecipe\&.cs\fP\&.
.SS "\fBRecipe\fP DropdownRecipe\&.recipe"

.PP
Definition at line \fB53\fP of file \fBDropdownRecipe\&.cs\fP\&.
.SS "UIText DropdownRecipe\&.textLabel"

.PP
Definition at line \fB56\fP of file \fBDropdownRecipe\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
