.TH "EffectText" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EffectText
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBEffect\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEffectText\fP \fBPlay\fP (Vector3 _pos, string text, float _duration=0f)"
.br
.ti -1c
.RI "\fBEffectText\fP \fBSetColor\fP (Color c)"
.br
.ti -1c
.RI "\fBEffectText\fP \fBSetSize\fP (float a)"
.br
.ti -1c
.RI "void \fBLateUpdate\fP ()"
.br
.in -1c

Public Member Functions inherited from \fBEffect\fP
.in +1c
.ti -1c
.RI "void \fBPlay\fP (float delay, \fBPoint\fP from, float fixY=0f, \fBPoint\fP to=null, Sprite sprite=null)"
.br
.ti -1c
.RI "unsafe \fBEffect\fP \fBPlay\fP (\fBPoint\fP from, float fixY=0f, \fBPoint\fP to=null, Sprite sprite=null)"
.br
.ti -1c
.RI "unsafe \fBEffect\fP \fB_Play\fP (\fBPoint\fP from, Vector3 fromV, float fixY=0f, \fBPoint\fP to=null, Sprite sprite=null)"
.br
.ti -1c
.RI "\fBEffect\fP \fBPlay\fP (Vector3 v)"
.br
.ti -1c
.RI "\fBEffect\fP \fBFlip\fP (bool x=false, bool y=false)"
.br
.ti -1c
.RI "\fBEffect\fP \fBSetStartDelay\fP (float a)"
.br
.ti -1c
.RI "virtual void \fBOnPlay\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnUpdate\fP ()"
.br
.ti -1c
.RI "void \fBKill\fP ()"
.br
.ti -1c
.RI "void \fBOnDisable\fP ()"
.br
.ti -1c
.RI "void \fBOnDestroy\fP ()"
.br
.ti -1c
.RI "\fBEffect\fP \fBEmit\fP (int num)"
.br
.ti -1c
.RI "\fBEffect\fP \fBSetParticleColor\fP (Color c)"
.br
.ti -1c
.RI "\fBEffect\fP \fBSetParticleColor\fP (Color color, bool changeMaterial=false, string idCol='_Color')"
.br
.ti -1c
.RI "\fBEffect\fP \fBSetScale\fP (float a)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Text \fBtextMain\fP"
.br
.ti -1c
.RI "RectTransform \fBrect\fP"
.br
.ti -1c
.RI "RectTransform \fBbody\fP"
.br
.ti -1c
.RI "bool \fBaddBrackets\fP"
.br
.ti -1c
.RI "Vector3 \fBpos\fP"
.br
.in -1c

Public Attributes inherited from \fBEffect\fP
.in +1c
.ti -1c
.RI "Effect\&.Type \fBtype\fP"
.br
.ti -1c
.RI "float \fBduration\fP = 1f"
.br
.ti -1c
.RI "float \fBspeed\fP"
.br
.ti -1c
.RI "float \fBstartDelay\fP"
.br
.ti -1c
.RI "bool \fBlookAtTarget\fP"
.br
.ti -1c
.RI "bool \fBrotate\fP"
.br
.ti -1c
.RI "bool \fBpool\fP"
.br
.ti -1c
.RI "SpriteRenderer \fBsr\fP"
.br
.ti -1c
.RI "ParticleSystem[] \fBsystems\fP"
.br
.ti -1c
.RI "Vector3[] \fBdirs\fP"
.br
.ti -1c
.RI "Ease \fBease\fP"
.br
.ti -1c
.RI "Vector3 \fBposFix\fP"
.br
.ti -1c
.RI "Vector3 \fBrandomRange\fP"
.br
.ti -1c
.RI "Tween \fBmoveTween\fP"
.br
.ti -1c
.RI "Sprite[] \fBsprites\fP"
.br
.ti -1c
.RI "bool \fBrandomFlip\fP"
.br
.ti -1c
.RI "bool \fBrandomSpeed\fP"
.br
.ti -1c
.RI "bool \fBtest\fP"
.br
.ti -1c
.RI "bool \fBsetColor\fP = true"
.br
.ti -1c
.RI "Action \fBonComplete\fP"
.br
.ti -1c
.RI "int \fBspriteIndex\fP"
.br
.ti -1c
.RI "float \fBtimer\fP"
.br
.ti -1c
.RI "Vector3 \fBfromV\fP"
.br
.ti -1c
.RI "Vector3 \fBdestV\fP"
.br
.ti -1c
.RI "bool \fBpooled\fP"
.br
.ti -1c
.RI "Transform \fBpoolParent\fP"
.br
.ti -1c
.RI "List< Material > \fBmaterialsToDestroy\fP"
.br
.ti -1c
.RI "\fBPoint\fP \fBdestPos\fP"
.br
.ti -1c
.RI "Tween \fBkillTimer\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static RectTransform \fBtransRoot\fP"
.br
.in -1c

Static Public Attributes inherited from \fBEMono\fP
.in +1c
.ti -1c
.RI "static \fBCore\fP \fBcore\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Public Types inherited from \fBEffect\fP
.in +1c
.ti -1c
.RI "enum \fBType\fP { \fBDefault\fP, \fBFirework\fP }"
.br
.in -1c

Static Public Member Functions inherited from \fBEffect\fP
.in +1c
.ti -1c
.RI "static \fBEffect\fP \fBGet\fP (\fBEffect\fP original)"
.br
.ti -1c
.RI "static \fBEffect\fP \fBGet\fP (string id)"
.br
.ti -1c
.RI "static T \fBGet< T >\fP (string id)"
.br
.in -1c

Static Public Member Functions inherited from \fBEMono\fP
.in +1c
.ti -1c
.RI "static int \fBrnd\fP (int a)"
.br
.in -1c

Protected Member Functions inherited from \fBEffect\fP
.in +1c
.ti -1c
.RI "void \fBActivate\fP ()"
.br
.in -1c

Protected Attributes inherited from \fBEffect\fP
.in +1c
.ti -1c
.RI "bool \fBkilled\fP"
.br
.in -1c

Properties inherited from \fBEffect\fP
.in +1c
.ti -1c
.RI "static \fBEffectManager\fP \fBmanager\fP\fR [get]\fP"
.br
.in -1c

Properties inherited from \fBEMono\fP
.in +1c
.ti -1c
.RI "static \fBGame\fP \fBgame\fP\fR [get]\fP"
.br
.ti -1c
.RI "static bool \fBAdvMode\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBPlayer\fP \fBplayer\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBChara\fP \fBpc\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBUI\fP \fBui\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBMap\fP \fB_map\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBZone\fP \fB_zone\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranchOrHomeBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFaction\fP \fBHome\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBScene\fP \fBscene\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBBaseGameScreen\fP \fBscreen\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameSetting\fP \fBsetting\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameData\fP \fBgamedata\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBColorProfile\fP \fBColors\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBWorld\fP \fBworld\fP\fR [get]\fP"
.br
.ti -1c
.RI "static SoundManager \fBSound\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBsources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBeditorSources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBCoreDebug\fP \fBdebug\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB6\fP of file \fBEffectText\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void EffectText\&.LateUpdate ()"

.PP
Definition at line \fB37\fP of file \fBEffectText\&.cs\fP\&.
.SS "\fBEffectText\fP EffectText\&.Play (Vector3 _pos, string text, float _duration = \fR0f\fP)"

.PP
Definition at line \fB9\fP of file \fBEffectText\&.cs\fP\&.
.SS "\fBEffectText\fP EffectText\&.SetColor (Color c)"

.PP
Definition at line \fB23\fP of file \fBEffectText\&.cs\fP\&.
.SS "\fBEffectText\fP EffectText\&.SetSize (float a)"

.PP
Definition at line \fB30\fP of file \fBEffectText\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "bool EffectText\&.addBrackets"

.PP
Definition at line \fB55\fP of file \fBEffectText\&.cs\fP\&.
.SS "RectTransform EffectText\&.body"

.PP
Definition at line \fB52\fP of file \fBEffectText\&.cs\fP\&.
.SS "Vector3 EffectText\&.pos"

.PP
Definition at line \fB59\fP of file \fBEffectText\&.cs\fP\&.
.SS "RectTransform EffectText\&.rect"

.PP
Definition at line \fB49\fP of file \fBEffectText\&.cs\fP\&.
.SS "Text EffectText\&.textMain"

.PP
Definition at line \fB46\fP of file \fBEffectText\&.cs\fP\&.
.SS "RectTransform EffectText\&.transRoot\fR [static]\fP"

.PP
Definition at line \fB43\fP of file \fBEffectText\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
