.TH "EffectManager.EffectList" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EffectManager.EffectList
.SH SYNOPSIS
.br
.PP
.PP
Inherits DynamicAsset< Effect >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEffect\fP \fBGet\fP (string id)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB49\fP of file \fBEffectManager\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBEffect\fP EffectManager\&.EffectList\&.Get (string id)"

.PP
Definition at line \fB52\fP of file \fBEffectManager\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
