.TH "EGraphic" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EGraphic
.SH SYNOPSIS
.br
.PP
.PP
Inherits Graphic\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Texture2D \fBtexture\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override Texture \fBmainTexture\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB8\fP of file \fBEGraphic\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "Texture2D EGraphic\&.texture"

.PP
Definition at line \fB21\fP of file \fBEGraphic\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "override Texture EGraphic\&.mainTexture\fR [get]\fP"

.PP
Definition at line \fB12\fP of file \fBEGraphic\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
