.TH "ElementRef" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ElementRef
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Color \fBcolorSprite\fP"
.br
.ti -1c
.RI "Color \fBcolorTrail\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB6\fP of file \fBElementRef\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "Color ElementRef\&.colorSprite"

.PP
Definition at line \fB9\fP of file \fBElementRef\&.cs\fP\&.
.SS "Color ElementRef\&.colorTrail"

.PP
Definition at line \fB12\fP of file \fBElementRef\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
