.TH "ElementOrigin" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ElementOrigin
.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "const int \fBDEFAULT\fP = 0"
.br
.ti -1c
.RI "const int \fBTEMP\fP = 0"
.br
.ti -1c
.RI "const int \fBRACE\fP = 1"
.br
.ti -1c
.RI "const int \fBJOB\fP = 2"
.br
.ti -1c
.RI "const int \fBORIGINAL\fP = 3"
.br
.ti -1c
.RI "const int \fBLINK\fP = 4"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB4\fP of file \fBElementOrigin\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "const int ElementOrigin\&.DEFAULT = 0\fR [static]\fP"

.PP
Definition at line \fB7\fP of file \fBElementOrigin\&.cs\fP\&.
.SS "const int ElementOrigin\&.JOB = 2\fR [static]\fP"

.PP
Definition at line \fB16\fP of file \fBElementOrigin\&.cs\fP\&.
.SS "const int ElementOrigin\&.LINK = 4\fR [static]\fP"

.PP
Definition at line \fB22\fP of file \fBElementOrigin\&.cs\fP\&.
.SS "const int ElementOrigin\&.ORIGINAL = 3\fR [static]\fP"

.PP
Definition at line \fB19\fP of file \fBElementOrigin\&.cs\fP\&.
.SS "const int ElementOrigin\&.RACE = 1\fR [static]\fP"

.PP
Definition at line \fB13\fP of file \fBElementOrigin\&.cs\fP\&.
.SS "const int ElementOrigin\&.TEMP = 0\fR [static]\fP"

.PP
Definition at line \fB10\fP of file \fBElementOrigin\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
