.TH "EloMap.TileInfo" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EloMap.TileInfo
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Sprite \fBsprite\fP"
.br
.ti -1c
.RI "bool \fBblocked\fP"
.br
.ti -1c
.RI "bool \fBisRoad\fP"
.br
.ti -1c
.RI "bool \fBroadLeft\fP"
.br
.ti -1c
.RI "bool \fBroadRight\fP"
.br
.ti -1c
.RI "bool \fBroadUp\fP"
.br
.ti -1c
.RI "bool \fBroadDown\fP"
.br
.ti -1c
.RI "bool \fBrock\fP"
.br
.ti -1c
.RI "bool \fBsea\fP"
.br
.ti -1c
.RI "bool \fBshore\fP"
.br
.ti -1c
.RI "\fBSourceGlobalTile\&.Row\fP \fBsource\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "bool \fBIsSnow\fP\fR [get]\fP"
.br
.ti -1c
.RI "string \fBidSurface\fP\fR [get]\fP"
.br
.ti -1c
.RI "string \fBidZoneProfile\fP\fR [get]\fP"
.br
.ti -1c
.RI "string \fBname\fP\fR [get]\fP"
.br
.ti -1c
.RI "bool \fBCanEmbark\fP\fR [get]\fP"
.br
.ti -1c
.RI "bool \fBIsBridge\fP\fR [get]\fP"
.br
.ti -1c
.RI "bool \fBIsNeighborRoad\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB483\fP of file \fBEloMap\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "bool EloMap\&.TileInfo\&.blocked"

.PP
Definition at line \fB560\fP of file \fBEloMap\&.cs\fP\&.
.SS "bool EloMap\&.TileInfo\&.isRoad"

.PP
Definition at line \fB563\fP of file \fBEloMap\&.cs\fP\&.
.SS "bool EloMap\&.TileInfo\&.roadDown"

.PP
Definition at line \fB575\fP of file \fBEloMap\&.cs\fP\&.
.SS "bool EloMap\&.TileInfo\&.roadLeft"

.PP
Definition at line \fB566\fP of file \fBEloMap\&.cs\fP\&.
.SS "bool EloMap\&.TileInfo\&.roadRight"

.PP
Definition at line \fB569\fP of file \fBEloMap\&.cs\fP\&.
.SS "bool EloMap\&.TileInfo\&.roadUp"

.PP
Definition at line \fB572\fP of file \fBEloMap\&.cs\fP\&.
.SS "bool EloMap\&.TileInfo\&.rock"

.PP
Definition at line \fB578\fP of file \fBEloMap\&.cs\fP\&.
.SS "bool EloMap\&.TileInfo\&.sea"

.PP
Definition at line \fB581\fP of file \fBEloMap\&.cs\fP\&.
.SS "bool EloMap\&.TileInfo\&.shore"

.PP
Definition at line \fB584\fP of file \fBEloMap\&.cs\fP\&.
.SS "\fBSourceGlobalTile\&.Row\fP EloMap\&.TileInfo\&.source"

.PP
Definition at line \fB587\fP of file \fBEloMap\&.cs\fP\&.
.SS "Sprite EloMap\&.TileInfo\&.sprite"

.PP
Definition at line \fB557\fP of file \fBEloMap\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "bool EloMap\&.TileInfo\&.CanEmbark\fR [get]\fP"

.PP
Definition at line \fB528\fP of file \fBEloMap\&.cs\fP\&.
.SS "string EloMap\&.TileInfo\&.idSurface\fR [get]\fP"

.PP
Definition at line \fB497\fP of file \fBEloMap\&.cs\fP\&.
.SS "string EloMap\&.TileInfo\&.idZoneProfile\fR [get]\fP"

.PP
Definition at line \fB508\fP of file \fBEloMap\&.cs\fP\&.
.SS "bool EloMap\&.TileInfo\&.IsBridge\fR [get]\fP"

.PP
Definition at line \fB538\fP of file \fBEloMap\&.cs\fP\&.
.SS "bool EloMap\&.TileInfo\&.IsNeighborRoad\fR [get]\fP"

.PP
Definition at line \fB548\fP of file \fBEloMap\&.cs\fP\&.
.SS "bool EloMap\&.TileInfo\&.IsSnow\fR [get]\fP"

.PP
Definition at line \fB487\fP of file \fBEloMap\&.cs\fP\&.
.SS "string EloMap\&.TileInfo\&.name\fR [get]\fP"

.PP
Definition at line \fB518\fP of file \fBEloMap\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
