.TH "EloMap" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EloMap
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBEClass\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCell\fP"
.br
.ti -1c
.RI "class \fBTileInfo\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBInit\fP (\fBEloMapActor\fP _actor)"
.br
.ti -1c
.RI "void \fBSetZone\fP (int gx, int gy, \fBZone\fP z, bool updateMesh=false)"
.br
.ti -1c
.RI "\fBEloMap\&.Cell\fP \fBGetCell\fP (\fBPoint\fP pos)"
.br
.ti -1c
.RI "\fBEloMap\&.Cell\fP \fBGetCell\fP (int gx, int gy)"
.br
.ti -1c
.RI "\fBEloMap\&.TileInfo\fP \fBGetTileInfo\fP (int gx, int gy)"
.br
.ti -1c
.RI "List< \fBSourceGlobalTile\&.Row\fP > \fBGetSources\fP (int gx, int gy)"
.br
.ti -1c
.RI "bool \fBCanBuildSite\fP (int gx, int gy, int radius=0, ElomapSiteType type=ElomapSiteType\&.Nefia)"
.br
.ti -1c
.RI "bool \fBIsSnow\fP (int gx, int gy)"
.br
.ti -1c
.RI "\fBZone\fP \fBGetZone\fP (\fBPoint\fP p)"
.br
.ti -1c
.RI "\fBZone\fP \fBGetZone\fP (int gx, int gy)"
.br
.ti -1c
.RI "int \fBGetRoadDist\fP (int gx, int gy)"
.br
.ti -1c
.RI "void \fBAddLight\fP (int gx, int gy, string id='elolight')"
.br
.ti -1c
.RI "void \fBRemoveLight\fP (int gx, int gy)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int[,] \fB_ints\fP"
.br
.ti -1c
.RI "\fBEloMap\&.Cell\fP[,] \fBcells\fP"
.br
.ti -1c
.RI "TilemapGroup \fBgroup\fP"
.br
.ti -1c
.RI "STETilemap \fBfogmap\fP"
.br
.ti -1c
.RI "STETilemap \fBseaMap\fP"
.br
.ti -1c
.RI "STETilemap \fBobjScatterMap\fP"
.br
.ti -1c
.RI "STETilemap \fBobjmap\fP"
.br
.ti -1c
.RI "STETilemap \fBextramap\fP"
.br
.ti -1c
.RI "STETilemap \fBcloudmap\fP"
.br
.ti -1c
.RI "int \fBw\fP"
.br
.ti -1c
.RI "int \fBh\fP"
.br
.ti -1c
.RI "int \fBminX\fP"
.br
.ti -1c
.RI "int \fBminY\fP"
.br
.ti -1c
.RI "bool \fBinitialized\fP"
.br
.ti -1c
.RI "\fBEloMapActor\fP \fBactor\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBRegion\fP \fBregion\fP\fR [get]\fP"
.br
.ti -1c
.RI "string \fBidMap\fP\fR [get]\fP"
.br
.in -1c

Properties inherited from \fBEClass\fP
.in +1c
.ti -1c
.RI "static \fBGame\fP \fBgame\fP\fR [get]\fP"
.br
.ti -1c
.RI "static bool \fBAdvMode\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBPlayer\fP \fBplayer\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBChara\fP \fBpc\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBUI\fP \fBui\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBMap\fP \fB_map\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBZone\fP \fB_zone\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranchOrHomeBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFaction\fP \fBHome\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFaction\fP \fBWilds\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBScene\fP \fBscene\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBBaseGameScreen\fP \fBscreen\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameSetting\fP \fBsetting\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameData\fP \fBgamedata\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBColorProfile\fP \fBColors\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBWorld\fP \fBworld\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBsources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBeditorSources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static SoundManager \fBSound\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBCoreDebug\fP \fBdebug\fP\fR [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Static Public Member Functions inherited from \fBEClass\fP
.in +1c
.ti -1c
.RI "static int \fBrnd\fP (int a)"
.br
.ti -1c
.RI "static int \fBcurve\fP (int a, int start, int step, int rate=75)"
.br
.ti -1c
.RI "static int \fBrndHalf\fP (int a)"
.br
.ti -1c
.RI "static float \fBrndf\fP (float a)"
.br
.ti -1c
.RI "static int \fBrndSqrt\fP (int a)"
.br
.ti -1c
.RI "static void \fBWait\fP (float a, \fBCard\fP c)"
.br
.ti -1c
.RI "static void \fBWait\fP (float a, \fBPoint\fP p)"
.br
.ti -1c
.RI "static int \fBBigger\fP (int a, int b)"
.br
.ti -1c
.RI "static int \fBSmaller\fP (int a, int b)"
.br
.in -1c

Static Public Attributes inherited from \fBEClass\fP
.in +1c
.ti -1c
.RI "static \fBCore\fP \fBcore\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB9\fP of file \fBEloMap\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void EloMap\&.AddLight (int gx, int gy, string id = \fR'elolight'\fP)"

.PP
Definition at line \fB382\fP of file \fBEloMap\&.cs\fP\&.
.SS "bool EloMap\&.CanBuildSite (int gx, int gy, int radius = \fR0\fP, ElomapSiteType type = \fRElomapSiteType::Nefia\fP)"

.PP
Definition at line \fB289\fP of file \fBEloMap\&.cs\fP\&.
.SS "\fBEloMap\&.Cell\fP EloMap\&.GetCell (int gx, int gy)"

.PP
Definition at line \fB193\fP of file \fBEloMap\&.cs\fP\&.
.SS "\fBEloMap\&.Cell\fP EloMap\&.GetCell (\fBPoint\fP pos)"

.PP
Definition at line \fB187\fP of file \fBEloMap\&.cs\fP\&.
.SS "int EloMap\&.GetRoadDist (int gx, int gy)"

.PP
Definition at line \fB350\fP of file \fBEloMap\&.cs\fP\&.
.SS "List< \fBSourceGlobalTile\&.Row\fP > EloMap\&.GetSources (int gx, int gy)"

.PP
Definition at line \fB271\fP of file \fBEloMap\&.cs\fP\&.
.SS "\fBEloMap\&.TileInfo\fP EloMap\&.GetTileInfo (int gx, int gy)"

.PP
Definition at line \fB203\fP of file \fBEloMap\&.cs\fP\&.
.SS "\fBZone\fP EloMap\&.GetZone (int gx, int gy)"

.PP
Definition at line \fB332\fP of file \fBEloMap\&.cs\fP\&.
.SS "\fBZone\fP EloMap\&.GetZone (\fBPoint\fP p)"

.PP
Definition at line \fB326\fP of file \fBEloMap\&.cs\fP\&.
.SS "void EloMap\&.Init (\fBEloMapActor\fP _actor)"

.PP
Definition at line \fB68\fP of file \fBEloMap\&.cs\fP\&.
.SS "bool EloMap\&.IsSnow (int gx, int gy)"

.PP
Definition at line \fB315\fP of file \fBEloMap\&.cs\fP\&.
.SS "void EloMap\&.RemoveLight (int gx, int gy)"

.PP
Definition at line \fB396\fP of file \fBEloMap\&.cs\fP\&.
.SS "void EloMap\&.SetZone (int gx, int gy, \fBZone\fP z, bool updateMesh = \fRfalse\fP)"

.PP
Definition at line \fB146\fP of file \fBEloMap\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int [,] EloMap\&._ints"

.PP
Definition at line \fB411\fP of file \fBEloMap\&.cs\fP\&.
.SS "\fBEloMapActor\fP EloMap\&.actor"

.PP
Definition at line \fB453\fP of file \fBEloMap\&.cs\fP\&.
.SS "\fBEloMap\&.Cell\fP [,] EloMap\&.cells"

.PP
Definition at line \fB414\fP of file \fBEloMap\&.cs\fP\&.
.SS "STETilemap EloMap\&.cloudmap"

.PP
Definition at line \fB435\fP of file \fBEloMap\&.cs\fP\&.
.SS "STETilemap EloMap\&.extramap"

.PP
Definition at line \fB432\fP of file \fBEloMap\&.cs\fP\&.
.SS "STETilemap EloMap\&.fogmap"

.PP
Definition at line \fB420\fP of file \fBEloMap\&.cs\fP\&.
.SS "TilemapGroup EloMap\&.group"

.PP
Definition at line \fB417\fP of file \fBEloMap\&.cs\fP\&.
.SS "int EloMap\&.h"

.PP
Definition at line \fB441\fP of file \fBEloMap\&.cs\fP\&.
.SS "bool EloMap\&.initialized"

.PP
Definition at line \fB450\fP of file \fBEloMap\&.cs\fP\&.
.SS "int EloMap\&.minX"

.PP
Definition at line \fB444\fP of file \fBEloMap\&.cs\fP\&.
.SS "int EloMap\&.minY"

.PP
Definition at line \fB447\fP of file \fBEloMap\&.cs\fP\&.
.SS "STETilemap EloMap\&.objmap"

.PP
Definition at line \fB429\fP of file \fBEloMap\&.cs\fP\&.
.SS "STETilemap EloMap\&.objScatterMap"

.PP
Definition at line \fB426\fP of file \fBEloMap\&.cs\fP\&.
.SS "STETilemap EloMap\&.seaMap"

.PP
Definition at line \fB423\fP of file \fBEloMap\&.cs\fP\&.
.SS "int EloMap\&.w"

.PP
Definition at line \fB438\fP of file \fBEloMap\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "string EloMap\&.idMap\fR [get]\fP"

.PP
Definition at line \fB23\fP of file \fBEloMap\&.cs\fP\&.
.SS "\fBRegion\fP EloMap\&.region\fR [get]\fP"

.PP
Definition at line \fB13\fP of file \fBEloMap\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
