.TH "EloMap.Cell" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EloMap.Cell
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCell\fP (int i)"
.br
.ti -1c
.RI "int \fBGetInt\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBZone\fP \fBzone\fP"
.br
.ti -1c
.RI "int \fBobj\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB456\fP of file \fBEloMap\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "EloMap\&.Cell\&.Cell ()"

.PP
Definition at line \fB459\fP of file \fBEloMap\&.cs\fP\&.
.SS "EloMap\&.Cell\&.Cell (int i)"

.PP
Definition at line \fB464\fP of file \fBEloMap\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "int EloMap\&.Cell\&.GetInt ()"

.PP
Definition at line \fB470\fP of file \fBEloMap\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int EloMap\&.Cell\&.obj"

.PP
Definition at line \fB479\fP of file \fBEloMap\&.cs\fP\&.
.SS "\fBZone\fP EloMap\&.Cell\&.zone"

.PP
Definition at line \fB476\fP of file \fBEloMap\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
