.TH "EloMapActor" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EloMapActor
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBEMono\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBInitialize\fP (\fBEloMap\fP _elomap)"
.br
.ti -1c
.RI "void \fBOnActivate\fP ()"
.br
.ti -1c
.RI "void \fBOnDeactivate\fP ()"
.br
.ti -1c
.RI "void \fBOnChangeHour\fP ()"
.br
.ti -1c
.RI "\fBEloMap\fP \fBGetEloMap\fP ()"
.br
.ti -1c
.RI "void \fBOnKillGame\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBEloMap\fP \fBelomap\fP"
.br
.ti -1c
.RI "Transform \fBtransMap\fP"
.br
.ti -1c
.RI "Transform \fBtransLight\fP"
.br
.ti -1c
.RI "Transform \fBmoldLight\fP"
.br
.ti -1c
.RI "Tileset \fBtileset\fP"
.br
.ti -1c
.RI "\fBEloMapTileSelector\fP \fBselector\fP"
.br
.ti -1c
.RI "List< \fBEloMapLight\fP > \fBlights\fP = new List<\fBEloMapLight\fP>()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "bool \fBIsActive\fP\fR [get]\fP"
.br
.in -1c

Properties inherited from \fBEMono\fP
.in +1c
.ti -1c
.RI "static \fBGame\fP \fBgame\fP\fR [get]\fP"
.br
.ti -1c
.RI "static bool \fBAdvMode\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBPlayer\fP \fBplayer\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBChara\fP \fBpc\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBUI\fP \fBui\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBMap\fP \fB_map\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBZone\fP \fB_zone\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranchOrHomeBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFaction\fP \fBHome\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBScene\fP \fBscene\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBBaseGameScreen\fP \fBscreen\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameSetting\fP \fBsetting\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameData\fP \fBgamedata\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBColorProfile\fP \fBColors\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBWorld\fP \fBworld\fP\fR [get]\fP"
.br
.ti -1c
.RI "static SoundManager \fBSound\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBsources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBeditorSources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBCoreDebug\fP \fBdebug\fP\fR [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Static Public Member Functions inherited from \fBEMono\fP
.in +1c
.ti -1c
.RI "static int \fBrnd\fP (int a)"
.br
.in -1c

Static Public Attributes inherited from \fBEMono\fP
.in +1c
.ti -1c
.RI "static \fBCore\fP \fBcore\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB7\fP of file \fBEloMapActor\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBEloMap\fP EloMapActor\&.GetEloMap ()"

.PP
Definition at line \fB84\fP of file \fBEloMapActor\&.cs\fP\&.
.SS "void EloMapActor\&.Initialize (\fBEloMap\fP _elomap)"

.PP
Definition at line \fB26\fP of file \fBEloMapActor\&.cs\fP\&.
.SS "void EloMapActor\&.OnActivate ()"

.PP
Definition at line \fB47\fP of file \fBEloMapActor\&.cs\fP\&.
.SS "void EloMapActor\&.OnChangeHour ()"

.PP
Definition at line \fB72\fP of file \fBEloMapActor\&.cs\fP\&.
.SS "void EloMapActor\&.OnDeactivate ()"

.PP
Definition at line \fB59\fP of file \fBEloMapActor\&.cs\fP\&.
.SS "void EloMapActor\&.OnKillGame ()"

.PP
Definition at line \fB91\fP of file \fBEloMapActor\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBEloMap\fP EloMapActor\&.elomap"

.PP
Definition at line \fB108\fP of file \fBEloMapActor\&.cs\fP\&.
.SS "List<\fBEloMapLight\fP> EloMapActor\&.lights = new List<\fBEloMapLight\fP>()"

.PP
Definition at line \fB126\fP of file \fBEloMapActor\&.cs\fP\&.
.SS "Transform EloMapActor\&.moldLight"

.PP
Definition at line \fB117\fP of file \fBEloMapActor\&.cs\fP\&.
.SS "\fBEloMapTileSelector\fP EloMapActor\&.selector"

.PP
Definition at line \fB123\fP of file \fBEloMapActor\&.cs\fP\&.
.SS "Tileset EloMapActor\&.tileset"

.PP
Definition at line \fB120\fP of file \fBEloMapActor\&.cs\fP\&.
.SS "Transform EloMapActor\&.transLight"

.PP
Definition at line \fB114\fP of file \fBEloMapActor\&.cs\fP\&.
.SS "Transform EloMapActor\&.transMap"

.PP
Definition at line \fB111\fP of file \fBEloMapActor\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "bool EloMapActor\&.IsActive\fR [get]\fP"

.PP
Definition at line \fB11\fP of file \fBEloMapActor\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
