.TH "ENC" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ENC
.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "const int \fBliving\fP = 653"
.br
.ti -1c
.RI "const int \fBeco\fP = 652"
.br
.ti -1c
.RI "const int \fBr_PV\fP = 651"
.br
.ti -1c
.RI "const int \fBr_DV\fP = 650"
.br
.ti -1c
.RI "const int \fBmod_scatter\fP = 607"
.br
.ti -1c
.RI "const int \fBmod_precision\fP = 605"
.br
.ti -1c
.RI "const int \fBmod_drill\fP = 606"
.br
.ti -1c
.RI "const int \fBr_life\fP = 640"
.br
.ti -1c
.RI "const int \fBnoDamage\fP = 654"
.br
.ti -1c
.RI "const int \fBr_mana\fP = 641"
.br
.ti -1c
.RI "const int \fBonlyPet\fP = 655"
.br
.ti -1c
.RI "const int \fBconvertImpact\fP = 865"
.br
.ti -1c
.RI "const int \fBabsorbHP\fP = 660"
.br
.ti -1c
.RI "const int \fBabsorbMP\fP = 661"
.br
.ti -1c
.RI "const int \fBabsorbSP\fP = 662"
.br
.ti -1c
.RI "const int \fBeheluck\fP = 663"
.br
.ti -1c
.RI "const int \fBboostMachine\fP = 664"
.br
.ti -1c
.RI "const int \fBplanter\fP = 665"
.br
.ti -1c
.RI "const int \fBmeleeDistance\fP = 666"
.br
.ti -1c
.RI "const int \fBmod_ammo_recover\fP = 604"
.br
.ti -1c
.RI "const int \fBconvertFire\fP = 850"
.br
.ti -1c
.RI "const int \fBconvertCold\fP = 851"
.br
.ti -1c
.RI "const int \fBconvertLightning\fP = 852"
.br
.ti -1c
.RI "const int \fBpermaCurse\fP = 656"
.br
.ti -1c
.RI "const int \fBmod_ammo_knockback\fP = 603"
.br
.ti -1c
.RI "const int \fBsustain_MAG\fP = 446"
.br
.ti -1c
.RI "const int \fBmod_reload\fP = 601"
.br
.ti -1c
.RI "const int \fBallNeckHunt\fP = 428"
.br
.ti -1c
.RI "const int \fBnegateNeckHunt\fP = 427"
.br
.ti -1c
.RI "const int \fBnegateSteal\fP = 426"
.br
.ti -1c
.RI "const int \fBnegateConfusion\fP = 425"
.br
.ti -1c
.RI "const int \fBnegateSleep\fP = 424"
.br
.ti -1c
.RI "const int \fBmod_rapid\fP = 602"
.br
.ti -1c
.RI "const int \fBnegateParalysis\fP = 422"
.br
.ti -1c
.RI "const int \fBnegateBlind\fP = 421"
.br
.ti -1c
.RI "const int \fBnegatePoison\fP = 420"
.br
.ti -1c
.RI "const int \fBseeInvisible\fP = 416"
.br
.ti -1c
.RI "const int \fBinvisibility\fP = 415"
.br
.ti -1c
.RI "const int \fBencSpell\fP = 411"
.br
.ti -1c
.RI "const int \fBthrowReturn\fP = 410"
.br
.ti -1c
.RI "const int \fBcorruption\fP = 409"
.br
.ti -1c
.RI "const int \fBresWeather\fP = 408"
.br
.ti -1c
.RI "const int \fBtravelSpeed\fP = 407"
.br
.ti -1c
.RI "const int \fBresMutation\fP = 406"
.br
.ti -1c
.RI "const int \fBslowDecay\fP = 405"
.br
.ti -1c
.RI "const int \fBweightMod\fP = 404"
.br
.ti -1c
.RI "const int \fBexpMod\fP = 403"
.br
.ti -1c
.RI "const int \fBsearchRange\fP = 402"
.br
.ti -1c
.RI "const int \fBlevitation\fP = 401"
.br
.ti -1c
.RI "const int \fBnegateTeleport\fP = 400"
.br
.ti -1c
.RI "const int \fBsustain_STR\fP = 440"
.br
.ti -1c
.RI "const int \fBsustain_END\fP = 441"
.br
.ti -1c
.RI "const int \fBnegateFear\fP = 423"
.br
.ti -1c
.RI "const int \fBstrongStomach\fP = 480"
.br
.ti -1c
.RI "const int \fBmod_ammo\fP = 600"
.br
.ti -1c
.RI "const int \fBoptimizeMana\fP = 483"
.br
.ti -1c
.RI "const int \fBforce_weapon\fP = 482"
.br
.ti -1c
.RI "const int \fBrevealFaith\fP = 481"
.br
.ti -1c
.RI "const int \fBbane_all\fP = 468"
.br
.ti -1c
.RI "const int \fBbane_fish\fP = 467"
.br
.ti -1c
.RI "const int \fBbane_god\fP = 466"
.br
.ti -1c
.RI "const int \fBbane_machine\fP = 465"
.br
.ti -1c
.RI "const int \fBbane_man\fP = 464"
.br
.ti -1c
.RI "const int \fBbane_animal\fP = 463"
.br
.ti -1c
.RI "const int \fBbane_undead\fP = 461"
.br
.ti -1c
.RI "const int \fBbane_fairy\fP = 462"
.br
.ti -1c
.RI "const int \fBsustain_CHA\fP = 447"
.br
.ti -1c
.RI "const int \fBsustain_WIL\fP = 445"
.br
.ti -1c
.RI "const int \fBsustain_LER\fP = 444"
.br
.ti -1c
.RI "const int \fBsustain_PER\fP = 443"
.br
.ti -1c
.RI "const int \fBsustain_DEX\fP = 442"
.br
.ti -1c
.RI "const int \fBbane_dragon\fP = 460"
.br
.ti -1c
.RI "static readonly int[] \fBIDS\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB4\fP of file \fBENC\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "const int ENC\&.absorbHP = 660\fR [static]\fP"

.PP
Definition at line \fB43\fP of file \fBENC\&.cs\fP\&.
.SS "const int ENC\&.absorbMP = 661\fR [static]\fP"

.PP
Definition at line \fB46\fP of file \fBENC\&.cs\fP\&.
.SS "const int ENC\&.absorbSP = 662\fR [static]\fP"

.PP
Definition at line \fB49\fP of file \fBENC\&.cs\fP\&.
.SS "const int ENC\&.allNeckHunt = 428\fR [static]\fP"

.PP
Definition at line \fB88\fP of file \fBENC\&.cs\fP\&.
.SS "const int ENC\&.bane_all = 468\fR [static]\fP"

.PP
Definition at line \fB181\fP of file \fBENC\&.cs\fP\&.
.SS "const int ENC\&.bane_animal = 463\fR [static]\fP"

.PP
Definition at line \fB196\fP of file \fBENC\&.cs\fP\&.
.SS "const int ENC\&.bane_dragon = 460\fR [static]\fP"

.PP
Definition at line \fB220\fP of file \fBENC\&.cs\fP\&.
.SS "const int ENC\&.bane_fairy = 462\fR [static]\fP"

.PP
Definition at line \fB202\fP of file \fBENC\&.cs\fP\&.
.SS "const int ENC\&.bane_fish = 467\fR [static]\fP"

.PP
Definition at line \fB184\fP of file \fBENC\&.cs\fP\&.
.SS "const int ENC\&.bane_god = 466\fR [static]\fP"

.PP
Definition at line \fB187\fP of file \fBENC\&.cs\fP\&.
.SS "const int ENC\&.bane_machine = 465\fR [static]\fP"

.PP
Definition at line \fB190\fP of file \fBENC\&.cs\fP\&.
.SS "const int ENC\&.bane_man = 464\fR [static]\fP"

.PP
Definition at line \fB193\fP of file \fBENC\&.cs\fP\&.
.SS "const int ENC\&.bane_undead = 461\fR [static]\fP"

.PP
Definition at line \fB199\fP of file \fBENC\&.cs\fP\&.
.SS "const int ENC\&.boostMachine = 664\fR [static]\fP"

.PP
Definition at line \fB55\fP of file \fBENC\&.cs\fP\&.
.SS "const int ENC\&.convertCold = 851\fR [static]\fP"

.PP
Definition at line \fB70\fP of file \fBENC\&.cs\fP\&.
.SS "const int ENC\&.convertFire = 850\fR [static]\fP"

.PP
Definition at line \fB67\fP of file \fBENC\&.cs\fP\&.
.SS "const int ENC\&.convertImpact = 865\fR [static]\fP"

.PP
Definition at line \fB40\fP of file \fBENC\&.cs\fP\&.
.SS "const int ENC\&.convertLightning = 852\fR [static]\fP"

.PP
Definition at line \fB73\fP of file \fBENC\&.cs\fP\&.
.SS "const int ENC\&.corruption = 409\fR [static]\fP"

.PP
Definition at line \fB127\fP of file \fBENC\&.cs\fP\&.
.SS "const int ENC\&.eco = 652\fR [static]\fP"

.PP
Definition at line \fB10\fP of file \fBENC\&.cs\fP\&.
.SS "const int ENC\&.eheluck = 663\fR [static]\fP"

.PP
Definition at line \fB52\fP of file \fBENC\&.cs\fP\&.
.SS "const int ENC\&.encSpell = 411\fR [static]\fP"

.PP
Definition at line \fB121\fP of file \fBENC\&.cs\fP\&.
.SS "const int ENC\&.expMod = 403\fR [static]\fP"

.PP
Definition at line \fB145\fP of file \fBENC\&.cs\fP\&.
.SS "const int ENC\&.force_weapon = 482\fR [static]\fP"

.PP
Definition at line \fB175\fP of file \fBENC\&.cs\fP\&.
.SS "readonly int [] ENC\&.IDS\fR [static]\fP"

.PP
Definition at line \fB223\fP of file \fBENC\&.cs\fP\&.
.SS "const int ENC\&.invisibility = 415\fR [static]\fP"

.PP
Definition at line \fB118\fP of file \fBENC\&.cs\fP\&.
.SS "const int ENC\&.levitation = 401\fR [static]\fP"

.PP
Definition at line \fB151\fP of file \fBENC\&.cs\fP\&.
.SS "const int ENC\&.living = 653\fR [static]\fP"

.PP
Definition at line \fB7\fP of file \fBENC\&.cs\fP\&.
.SS "const int ENC\&.meleeDistance = 666\fR [static]\fP"

.PP
Definition at line \fB61\fP of file \fBENC\&.cs\fP\&.
.SS "const int ENC\&.mod_ammo = 600\fR [static]\fP"

.PP
Definition at line \fB169\fP of file \fBENC\&.cs\fP\&.
.SS "const int ENC\&.mod_ammo_knockback = 603\fR [static]\fP"

.PP
Definition at line \fB79\fP of file \fBENC\&.cs\fP\&.
.SS "const int ENC\&.mod_ammo_recover = 604\fR [static]\fP"

.PP
Definition at line \fB64\fP of file \fBENC\&.cs\fP\&.
.SS "const int ENC\&.mod_drill = 606\fR [static]\fP"

.PP
Definition at line \fB25\fP of file \fBENC\&.cs\fP\&.
.SS "const int ENC\&.mod_precision = 605\fR [static]\fP"

.PP
Definition at line \fB22\fP of file \fBENC\&.cs\fP\&.
.SS "const int ENC\&.mod_rapid = 602\fR [static]\fP"

.PP
Definition at line \fB103\fP of file \fBENC\&.cs\fP\&.
.SS "const int ENC\&.mod_reload = 601\fR [static]\fP"

.PP
Definition at line \fB85\fP of file \fBENC\&.cs\fP\&.
.SS "const int ENC\&.mod_scatter = 607\fR [static]\fP"

.PP
Definition at line \fB19\fP of file \fBENC\&.cs\fP\&.
.SS "const int ENC\&.negateBlind = 421\fR [static]\fP"

.PP
Definition at line \fB109\fP of file \fBENC\&.cs\fP\&.
.SS "const int ENC\&.negateConfusion = 425\fR [static]\fP"

.PP
Definition at line \fB97\fP of file \fBENC\&.cs\fP\&.
.SS "const int ENC\&.negateFear = 423\fR [static]\fP"

.PP
Definition at line \fB163\fP of file \fBENC\&.cs\fP\&.
.SS "const int ENC\&.negateNeckHunt = 427\fR [static]\fP"

.PP
Definition at line \fB91\fP of file \fBENC\&.cs\fP\&.
.SS "const int ENC\&.negateParalysis = 422\fR [static]\fP"

.PP
Definition at line \fB106\fP of file \fBENC\&.cs\fP\&.
.SS "const int ENC\&.negatePoison = 420\fR [static]\fP"

.PP
Definition at line \fB112\fP of file \fBENC\&.cs\fP\&.
.SS "const int ENC\&.negateSleep = 424\fR [static]\fP"

.PP
Definition at line \fB100\fP of file \fBENC\&.cs\fP\&.
.SS "const int ENC\&.negateSteal = 426\fR [static]\fP"

.PP
Definition at line \fB94\fP of file \fBENC\&.cs\fP\&.
.SS "const int ENC\&.negateTeleport = 400\fR [static]\fP"

.PP
Definition at line \fB154\fP of file \fBENC\&.cs\fP\&.
.SS "const int ENC\&.noDamage = 654\fR [static]\fP"

.PP
Definition at line \fB31\fP of file \fBENC\&.cs\fP\&.
.SS "const int ENC\&.onlyPet = 655\fR [static]\fP"

.PP
Definition at line \fB37\fP of file \fBENC\&.cs\fP\&.
.SS "const int ENC\&.optimizeMana = 483\fR [static]\fP"

.PP
Definition at line \fB172\fP of file \fBENC\&.cs\fP\&.
.SS "const int ENC\&.permaCurse = 656\fR [static]\fP"

.PP
Definition at line \fB76\fP of file \fBENC\&.cs\fP\&.
.SS "const int ENC\&.planter = 665\fR [static]\fP"

.PP
Definition at line \fB58\fP of file \fBENC\&.cs\fP\&.
.SS "const int ENC\&.r_DV = 650\fR [static]\fP"

.PP
Definition at line \fB16\fP of file \fBENC\&.cs\fP\&.
.SS "const int ENC\&.r_life = 640\fR [static]\fP"

.PP
Definition at line \fB28\fP of file \fBENC\&.cs\fP\&.
.SS "const int ENC\&.r_mana = 641\fR [static]\fP"

.PP
Definition at line \fB34\fP of file \fBENC\&.cs\fP\&.
.SS "const int ENC\&.r_PV = 651\fR [static]\fP"

.PP
Definition at line \fB13\fP of file \fBENC\&.cs\fP\&.
.SS "const int ENC\&.resMutation = 406\fR [static]\fP"

.PP
Definition at line \fB136\fP of file \fBENC\&.cs\fP\&.
.SS "const int ENC\&.resWeather = 408\fR [static]\fP"

.PP
Definition at line \fB130\fP of file \fBENC\&.cs\fP\&.
.SS "const int ENC\&.revealFaith = 481\fR [static]\fP"

.PP
Definition at line \fB178\fP of file \fBENC\&.cs\fP\&.
.SS "const int ENC\&.searchRange = 402\fR [static]\fP"

.PP
Definition at line \fB148\fP of file \fBENC\&.cs\fP\&.
.SS "const int ENC\&.seeInvisible = 416\fR [static]\fP"

.PP
Definition at line \fB115\fP of file \fBENC\&.cs\fP\&.
.SS "const int ENC\&.slowDecay = 405\fR [static]\fP"

.PP
Definition at line \fB139\fP of file \fBENC\&.cs\fP\&.
.SS "const int ENC\&.strongStomach = 480\fR [static]\fP"

.PP
Definition at line \fB166\fP of file \fBENC\&.cs\fP\&.
.SS "const int ENC\&.sustain_CHA = 447\fR [static]\fP"

.PP
Definition at line \fB205\fP of file \fBENC\&.cs\fP\&.
.SS "const int ENC\&.sustain_DEX = 442\fR [static]\fP"

.PP
Definition at line \fB217\fP of file \fBENC\&.cs\fP\&.
.SS "const int ENC\&.sustain_END = 441\fR [static]\fP"

.PP
Definition at line \fB160\fP of file \fBENC\&.cs\fP\&.
.SS "const int ENC\&.sustain_LER = 444\fR [static]\fP"

.PP
Definition at line \fB211\fP of file \fBENC\&.cs\fP\&.
.SS "const int ENC\&.sustain_MAG = 446\fR [static]\fP"

.PP
Definition at line \fB82\fP of file \fBENC\&.cs\fP\&.
.SS "const int ENC\&.sustain_PER = 443\fR [static]\fP"

.PP
Definition at line \fB214\fP of file \fBENC\&.cs\fP\&.
.SS "const int ENC\&.sustain_STR = 440\fR [static]\fP"

.PP
Definition at line \fB157\fP of file \fBENC\&.cs\fP\&.
.SS "const int ENC\&.sustain_WIL = 445\fR [static]\fP"

.PP
Definition at line \fB208\fP of file \fBENC\&.cs\fP\&.
.SS "const int ENC\&.throwReturn = 410\fR [static]\fP"

.PP
Definition at line \fB124\fP of file \fBENC\&.cs\fP\&.
.SS "const int ENC\&.travelSpeed = 407\fR [static]\fP"

.PP
Definition at line \fB133\fP of file \fBENC\&.cs\fP\&.
.SS "const int ENC\&.weightMod = 404\fR [static]\fP"

.PP
Definition at line \fB142\fP of file \fBENC\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
