.TH "EScriptable" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EScriptable
.SH SYNOPSIS
.br
.PP
.PP
Inherits ScriptableObject\&.
.PP
Inherited by \fBBiomeProfile\fP, \fBColorProfile\fP, \fBCoreDebug\fP, \fBCrawler\fP, \fBGameData\fP, \fBLiquidProfile\fP, \fBMapPiece\fP, \fBPostEffectProfile\fP, \fBRefractionProfile\fP, \fBRenderData\fP, \fBSceneTemplate\fP, \fBShadowData\fP, \fBSourceAsset\fP, \fBTextureData\fP, and \fBZoneProfile\fP\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static int \fBrnd\fP (int a)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB5\fP of file \fBEScriptable\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "static int EScriptable\&.rnd (int a)\fR [static]\fP"

.PP
Definition at line \fB8\fP of file \fBEScriptable\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
