.TH "Faction" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Faction
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBEClass\fP\&.
.PP
Inherited by \fBGuild\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBInit\fP ()"
.br
.ti -1c
.RI "void \fBOnLoad\fP ()"
.br
.ti -1c
.RI "float \fBGetHappiness\fP ()"
.br
.ti -1c
.RI "Sprite \fBGetSprite\fP ()"
.br
.ti -1c
.RI "int \fBCountTax\fP ()"
.br
.ti -1c
.RI "List< \fBFactionBranch\fP > \fBGetChildren\fP ()"
.br
.ti -1c
.RI "int \fBCountWealth\fP ()"
.br
.ti -1c
.RI "int \fBCountTerritories\fP ()"
.br
.ti -1c
.RI "int \fBCountMembers\fP ()"
.br
.ti -1c
.RI "Hostility \fBGetHostility\fP ()"
.br
.ti -1c
.RI "void \fBModRelation\fP (int a)"
.br
.ti -1c
.RI "bool \fBHasMember\fP (string id, bool includeReserve=true)"
.br
.ti -1c
.RI "void \fBAddContribution\fP (int a)"
.br
.ti -1c
.RI "void \fBAddReserve\fP (\fBChara\fP c)"
.br
.ti -1c
.RI "void \fBRemoveReserve\fP (\fBChara\fP c)"
.br
.ti -1c
.RI "void \fBOnAdvanceDay\fP ()"
.br
.ti -1c
.RI "void \fBOnAdvanceMonth\fP ()"
.br
.ti -1c
.RI "void \fBTryPayBill\fP (\fBThing\fP bill)"
.br
.ti -1c
.RI "\fBFactionBranch\fP \fBFindBranch\fP (\fBChara\fP c)"
.br
.ti -1c
.RI "void \fBAddGlobalPolicy\fP (int id)"
.br
.ti -1c
.RI "bool \fBIsGlobalPolicyActive\fP (int id)"
.br
.ti -1c
.RI "void \fBSetGlobalPolicyActive\fP (int id, bool active)"
.br
.ti -1c
.RI "int \fBGetResidentTax\fP ()"
.br
.ti -1c
.RI "int \fBGetRankIncome\fP ()"
.br
.ti -1c
.RI "int \fBGetFactionSalary\fP ()"
.br
.ti -1c
.RI "int \fBGetTotalTax\fP (bool evasion)"
.br
.ti -1c
.RI "int \fBGetBaseTax\fP (bool evasion)"
.br
.ti -1c
.RI "int \fBGetFameTax\fP (bool evasion)"
.br
.ti -1c
.RI "int \fBEvadeTax\fP (int v, bool evasion)"
.br
.ti -1c
.RI "void \fBSetTaxTooltip\fP (UINote n)"
.br
.ti -1c
.RI "int \fBCountTaxFreeLand\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBFaction\fP \fBCreate\fP (\fBSourceFaction\&.Row\fP r)"
.br
.in -1c

Static Public Member Functions inherited from \fBEClass\fP
.in +1c
.ti -1c
.RI "static int \fBrnd\fP (int a)"
.br
.ti -1c
.RI "static int \fBcurve\fP (int a, int start, int step, int rate=75)"
.br
.ti -1c
.RI "static int \fBrndHalf\fP (int a)"
.br
.ti -1c
.RI "static float \fBrndf\fP (float a)"
.br
.ti -1c
.RI "static int \fBrndSqrt\fP (int a)"
.br
.ti -1c
.RI "static void \fBWait\fP (float a, \fBCard\fP c)"
.br
.ti -1c
.RI "static void \fBWait\fP (float a, \fBPoint\fP p)"
.br
.ti -1c
.RI "static int \fBBigger\fP (int a, int b)"
.br
.ti -1c
.RI "static int \fBSmaller\fP (int a, int b)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBFactionRelation\fP \fBrelation\fP = new \fBFactionRelation\fP()"
.br
.ti -1c
.RI "int \fBmaxReserve\fP = 3"
.br
.ti -1c
.RI "string \fBid\fP"
.br
.ti -1c
.RI "string \fBuid\fP"
.br
.ti -1c
.RI "string \fBname\fP"
.br
.ti -1c
.RI "List< \fBHireInfo\fP > \fBlistReserve\fP = new List<\fBHireInfo\fP>()"
.br
.ti -1c
.RI "\fBElementContainerZone\fP \fBelements\fP = new \fBElementContainerZone\fP()"
.br
.ti -1c
.RI "HashSet< int > \fBglobalPolicies\fP = new HashSet<int>()"
.br
.ti -1c
.RI "\fBElementContainerFaction\fP \fBcharaElements\fP = new \fBElementContainerFaction\fP()"
.br
.ti -1c
.RI "\fBSourceFaction\&.Row\fP \fB_source\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBName\fP\fR [get]\fP"
.br
.ti -1c
.RI "\fBSourceFaction\&.Row\fP \fBsource\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual string \fBTextType\fP\fR [get]\fP"
.br
.in -1c

Properties inherited from \fBEClass\fP
.in +1c
.ti -1c
.RI "static \fBGame\fP \fBgame\fP\fR [get]\fP"
.br
.ti -1c
.RI "static bool \fBAdvMode\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBPlayer\fP \fBplayer\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBChara\fP \fBpc\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBUI\fP \fBui\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBMap\fP \fB_map\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBZone\fP \fB_zone\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranchOrHomeBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFaction\fP \fBHome\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFaction\fP \fBWilds\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBScene\fP \fBscene\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBBaseGameScreen\fP \fBscreen\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameSetting\fP \fBsetting\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameData\fP \fBgamedata\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBColorProfile\fP \fBColors\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBWorld\fP \fBworld\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBsources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBeditorSources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static SoundManager \fBSound\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBCoreDebug\fP \fBdebug\fP\fR [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Static Public Attributes inherited from \fBEClass\fP
.in +1c
.ti -1c
.RI "static \fBCore\fP \fBcore\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB7\fP of file \fBFaction\&.2\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Faction\&.AddContribution (int a)"

.PP
Definition at line \fB200\fP of file \fBFaction\&.2\&.cs\fP\&.
.SS "void Faction\&.AddGlobalPolicy (int id)"

.PP
Definition at line \fB315\fP of file \fBFaction\&.2\&.cs\fP\&.
.SS "void Faction\&.AddReserve (\fBChara\fP c)"

.PP
Definition at line \fB211\fP of file \fBFaction\&.2\&.cs\fP\&.
.SS "int Faction\&.CountMembers ()"

.PP
Definition at line \fB133\fP of file \fBFaction\&.2\&.cs\fP\&.
.SS "int Faction\&.CountTax ()"

.PP
Definition at line \fB81\fP of file \fBFaction\&.2\&.cs\fP\&.
.SS "int Faction\&.CountTaxFreeLand ()"

.PP
Definition at line \fB437\fP of file \fBFaction\&.2\&.cs\fP\&.
.SS "int Faction\&.CountTerritories ()"

.PP
Definition at line \fB116\fP of file \fBFaction\&.2\&.cs\fP\&.
.SS "int Faction\&.CountWealth ()"

.PP
Definition at line \fB101\fP of file \fBFaction\&.2\&.cs\fP\&.
.SS "static \fBFaction\fP Faction\&.Create (\fBSourceFaction\&.Row\fP r)\fR [static]\fP"

.PP
Definition at line \fB45\fP of file \fBFaction\&.2\&.cs\fP\&.
.SS "int Faction\&.EvadeTax (int v, bool evasion)"

.PP
Definition at line \fB413\fP of file \fBFaction\&.2\&.cs\fP\&.
.SS "\fBFactionBranch\fP Faction\&.FindBranch (\fBChara\fP c)"

.PP
Definition at line \fB302\fP of file \fBFaction\&.2\&.cs\fP\&.
.SS "int Faction\&.GetBaseTax (bool evasion)"

.PP
Definition at line \fB398\fP of file \fBFaction\&.2\&.cs\fP\&.
.SS "List< \fBFactionBranch\fP > Faction\&.GetChildren ()"

.PP
Definition at line \fB87\fP of file \fBFaction\&.2\&.cs\fP\&.
.SS "int Faction\&.GetFactionSalary ()"

.PP
Definition at line \fB377\fP of file \fBFaction\&.2\&.cs\fP\&.
.SS "int Faction\&.GetFameTax (bool evasion)"

.PP
Definition at line \fB406\fP of file \fBFaction\&.2\&.cs\fP\&.
.SS "float Faction\&.GetHappiness ()"

.PP
Definition at line \fB69\fP of file \fBFaction\&.2\&.cs\fP\&.
.SS "Hostility Faction\&.GetHostility ()"

.PP
Definition at line \fB150\fP of file \fBFaction\&.2\&.cs\fP\&.
.SS "int Faction\&.GetRankIncome ()"

.PP
Definition at line \fB362\fP of file \fBFaction\&.2\&.cs\fP\&.
.SS "int Faction\&.GetResidentTax ()"

.PP
Definition at line \fB347\fP of file \fBFaction\&.2\&.cs\fP\&.
.SS "Sprite Faction\&.GetSprite ()"

.PP
Definition at line \fB75\fP of file \fBFaction\&.2\&.cs\fP\&.
.SS "int Faction\&.GetTotalTax (bool evasion)"

.PP
Definition at line \fB392\fP of file \fBFaction\&.2\&.cs\fP\&.
.SS "bool Faction\&.HasMember (string id, bool includeReserve = \fRtrue\fP)"

.PP
Definition at line \fB174\fP of file \fBFaction\&.2\&.cs\fP\&.
.SS "void Faction\&.Init ()"

.PP
Definition at line \fB54\fP of file \fBFaction\&.2\&.cs\fP\&.
.SS "bool Faction\&.IsGlobalPolicyActive (int id)"

.PP
Definition at line \fB321\fP of file \fBFaction\&.2\&.cs\fP\&.
.SS "void Faction\&.ModRelation (int a)"

.PP
Definition at line \fB168\fP of file \fBFaction\&.2\&.cs\fP\&.
.SS "void Faction\&.OnAdvanceDay ()"

.PP
Definition at line \fB250\fP of file \fBFaction\&.2\&.cs\fP\&.
.SS "void Faction\&.OnAdvanceMonth ()"

.PP
Definition at line \fB259\fP of file \fBFaction\&.2\&.cs\fP\&.
.SS "void Faction\&.OnLoad ()"

.PP
Definition at line \fB63\fP of file \fBFaction\&.2\&.cs\fP\&.
.SS "void Faction\&.RemoveReserve (\fBChara\fP c)"

.PP
Definition at line \fB238\fP of file \fBFaction\&.2\&.cs\fP\&.
.SS "void Faction\&.SetGlobalPolicyActive (int id, bool active)"

.PP
Definition at line \fB338\fP of file \fBFaction\&.2\&.cs\fP\&.
.SS "void Faction\&.SetTaxTooltip (UINote n)"

.PP
Definition at line \fB428\fP of file \fBFaction\&.2\&.cs\fP\&.
.SS "void Faction\&.TryPayBill (\fBThing\fP bill)"

.PP
Definition at line \fB291\fP of file \fBFaction\&.2\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBSourceFaction\&.Row\fP Faction\&._source"

.PP
Definition at line \fB489\fP of file \fBFaction\&.2\&.cs\fP\&.
.SS "\fBElementContainerFaction\fP Faction\&.charaElements = new \fBElementContainerFaction\fP()"

.PP
Definition at line \fB486\fP of file \fBFaction\&.2\&.cs\fP\&.
.SS "\fBElementContainerZone\fP Faction\&.elements = new \fBElementContainerZone\fP()"

.PP
Definition at line \fB479\fP of file \fBFaction\&.2\&.cs\fP\&.
.SS "HashSet<int> Faction\&.globalPolicies = new HashSet<int>()"

.PP
Definition at line \fB483\fP of file \fBFaction\&.2\&.cs\fP\&.
.SS "string Faction\&.id"

.PP
Definition at line \fB463\fP of file \fBFaction\&.2\&.cs\fP\&.
.SS "List<\fBHireInfo\fP> Faction\&.listReserve = new List<\fBHireInfo\fP>()"

.PP
Definition at line \fB475\fP of file \fBFaction\&.2\&.cs\fP\&.
.SS "int Faction\&.maxReserve = 3"

.PP
Definition at line \fB459\fP of file \fBFaction\&.2\&.cs\fP\&.
.SS "string Faction\&.name"

.PP
Definition at line \fB471\fP of file \fBFaction\&.2\&.cs\fP\&.
.SS "\fBFactionRelation\fP Faction\&.relation = new \fBFactionRelation\fP()"

.PP
Definition at line \fB455\fP of file \fBFaction\&.2\&.cs\fP\&.
.SS "string Faction\&.uid"

.PP
Definition at line \fB467\fP of file \fBFaction\&.2\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "string Faction\&.Name\fR [get]\fP"

.PP
Definition at line \fB11\fP of file \fBFaction\&.2\&.cs\fP\&.
.SS "\fBSourceFaction\&.Row\fP Faction\&.source\fR [get]\fP"

.PP
Definition at line \fB21\fP of file \fBFaction\&.2\&.cs\fP\&.
.SS "virtual string Faction\&.TextType\fR [get]\fP"

.PP
Definition at line \fB36\fP of file \fBFaction\&.2\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
