.TH "FactionManager" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FactionManager
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBEClass\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBAssignUID\fP (\fBFaction\fP s)"
.br
.ti -1c
.RI "void \fBOnCreateGame\fP ()"
.br
.ti -1c
.RI "void \fBOnLoad\fP ()"
.br
.ti -1c
.RI "T \fBFind< T >\fP (string id)"
.br
.ti -1c
.RI "\fBFaction\fP \fBFind\fP (string id)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Dictionary< string, \fBFaction\fP > \fBdictAll\fP = new Dictionary<string, \fBFaction\fP>()"
.br
.ti -1c
.RI "new \fBFaction\fP \fBHome\fP"
.br
.ti -1c
.RI "new \fBFaction\fP \fBWilds\fP"
.br
.ti -1c
.RI "\fBGuildFighter\fP \fBFighter\fP"
.br
.ti -1c
.RI "\fBGuildMage\fP \fBMage\fP"
.br
.ti -1c
.RI "\fBGuildThief\fP \fBThief\fP"
.br
.ti -1c
.RI "\fBGuildMerchant\fP \fBMerchant\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Static Public Member Functions inherited from \fBEClass\fP
.in +1c
.ti -1c
.RI "static int \fBrnd\fP (int a)"
.br
.ti -1c
.RI "static int \fBcurve\fP (int a, int start, int step, int rate=75)"
.br
.ti -1c
.RI "static int \fBrndHalf\fP (int a)"
.br
.ti -1c
.RI "static float \fBrndf\fP (float a)"
.br
.ti -1c
.RI "static int \fBrndSqrt\fP (int a)"
.br
.ti -1c
.RI "static void \fBWait\fP (float a, \fBCard\fP c)"
.br
.ti -1c
.RI "static void \fBWait\fP (float a, \fBPoint\fP p)"
.br
.ti -1c
.RI "static int \fBBigger\fP (int a, int b)"
.br
.ti -1c
.RI "static int \fBSmaller\fP (int a, int b)"
.br
.in -1c

Static Public Attributes inherited from \fBEClass\fP
.in +1c
.ti -1c
.RI "static \fBCore\fP \fBcore\fP"
.br
.in -1c

Properties inherited from \fBEClass\fP
.in +1c
.ti -1c
.RI "static \fBGame\fP \fBgame\fP\fR [get]\fP"
.br
.ti -1c
.RI "static bool \fBAdvMode\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBPlayer\fP \fBplayer\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBChara\fP \fBpc\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBUI\fP \fBui\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBMap\fP \fB_map\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBZone\fP \fB_zone\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranchOrHomeBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFaction\fP \fBHome\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFaction\fP \fBWilds\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBScene\fP \fBscene\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBBaseGameScreen\fP \fBscreen\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameSetting\fP \fBsetting\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameData\fP \fBgamedata\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBColorProfile\fP \fBColors\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBWorld\fP \fBworld\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBsources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBeditorSources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static SoundManager \fBSound\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBCoreDebug\fP \fBdebug\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB7\fP of file \fBFactionManager\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void FactionManager\&.AssignUID (\fBFaction\fP s)"

.PP
Definition at line \fB10\fP of file \fBFactionManager\&.cs\fP\&.
.SS "\fBFaction\fP FactionManager\&.Find (string id)"

.PP
Definition at line \fB53\fP of file \fBFactionManager\&.cs\fP\&.
.SS "T FactionManager\&.Find< T > (string id)"

.PP
\fBType Constraints\fP
.TP
\fIT\fP : \fI\fBFaction\fP\fP
.PP
Definition at line \fB47\fP of file \fBFactionManager\&.cs\fP\&.
.SS "void FactionManager\&.OnCreateGame ()"

.PP
Definition at line \fB22\fP of file \fBFactionManager\&.cs\fP\&.
.SS "void FactionManager\&.OnLoad ()"

.PP
Definition at line \fB38\fP of file \fBFactionManager\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "Dictionary<string, \fBFaction\fP> FactionManager\&.dictAll = new Dictionary<string, \fBFaction\fP>()"

.PP
Definition at line \fB67\fP of file \fBFactionManager\&.cs\fP\&.
.SS "\fBGuildFighter\fP FactionManager\&.Fighter"

.PP
Definition at line \fB79\fP of file \fBFactionManager\&.cs\fP\&.
.SS "new \fBFaction\fP FactionManager\&.Home"

.PP
Definition at line \fB71\fP of file \fBFactionManager\&.cs\fP\&.
.SS "\fBGuildMage\fP FactionManager\&.Mage"

.PP
Definition at line \fB83\fP of file \fBFactionManager\&.cs\fP\&.
.SS "\fBGuildMerchant\fP FactionManager\&.Merchant"

.PP
Definition at line \fB91\fP of file \fBFactionManager\&.cs\fP\&.
.SS "\fBGuildThief\fP FactionManager\&.Thief"

.PP
Definition at line \fB87\fP of file \fBFactionManager\&.cs\fP\&.
.SS "new \fBFaction\fP FactionManager\&.Wilds"

.PP
Definition at line \fB75\fP of file \fBFactionManager\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
