.TH "FactionBranch" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FactionBranch
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBEClass\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBStatistics\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "int \fBGetNextExp\fP (int _lv=\-1)"
.br
.ti -1c
.RI "int \fBEvalue\fP (int ele)"
.br
.ti -1c
.RI "int \fBGetProductBonus\fP (\fBChara\fP c)"
.br
.ti -1c
.RI "void \fBRefreshEfficiency\fP ()"
.br
.ti -1c
.RI "void \fBAbandon\fP ()"
.br
.ti -1c
.RI "void \fBOnCreate\fP (\fBZone\fP zone)"
.br
.ti -1c
.RI "void \fBSetOwner\fP (\fBZone\fP zone)"
.br
.ti -1c
.RI "void \fBOnActivateZone\fP ()"
.br
.ti -1c
.RI "void \fBOnAfterSimulate\fP ()"
.br
.ti -1c
.RI "void \fBOnUnloadMap\fP ()"
.br
.ti -1c
.RI "void \fBOnSimulateHour\fP (\fBVirtualDate\fP date)"
.br
.ti -1c
.RI "void \fBAutoClean\fP ()"
.br
.ti -1c
.RI "void \fBOnSimulateDay\fP (\fBVirtualDate\fP date)"
.br
.ti -1c
.RI "void \fBOnAdvanceDay\fP ()"
.br
.ti -1c
.RI "void \fBOnSimulateMonth\fP (\fBVirtualDate\fP date)"
.br
.ti -1c
.RI "void \fBGenerateGarbage\fP (\fBVirtualDate\fP date)"
.br
.ti -1c
.RI "bool \fBTryTrash\fP (\fBThing\fP t)"
.br
.ti -1c
.RI "void \fBReceivePackages\fP (\fBVirtualDate\fP date)"
.br
.ti -1c
.RI "void \fBDailyOutcome\fP (\fBVirtualDate\fP date)"
.br
.ti -1c
.RI "void \fBPutInMailBox\fP (\fBThing\fP t, bool outside=false, bool install=true)"
.br
.ti -1c
.RI "\fBThing\fP \fBGetMailBox\fP ()"
.br
.ti -1c
.RI "\fBPoint\fP \fBGetMailBoxPos\fP ()"
.br
.ti -1c
.RI "int \fBGetResidentTax\fP ()"
.br
.ti -1c
.RI "void \fBCalcInnIncome\fP ()"
.br
.ti -1c
.RI "void \fBCalcTourismIncome\fP ()"
.br
.ti -1c
.RI "void \fBGetDailyIncome\fP ()"
.br
.ti -1c
.RI "\fBThing\fP \fBGetMeal\fP (\fBChara\fP c)"
.br
.ti -1c
.RI "void \fBOnClaimZone\fP ()"
.br
.ti -1c
.RI "void \fBOnUnclaimZone\fP ()"
.br
.ti -1c
.RI "void \fBValidateUpgradePolicies\fP ()"
.br
.ti -1c
.RI "void \fBUpgrade\fP ()"
.br
.ti -1c
.RI "bool \fBCanUpgrade\fP ()"
.br
.ti -1c
.RI "int \fBGetUpgradeCost\fP ()"
.br
.ti -1c
.RI "void \fBModExp\fP (int a)"
.br
.ti -1c
.RI "string \fBGetHearthHint\fP (int a)"
.br
.ti -1c
.RI "void \fBAddFeat\fP (int ele, int v)"
.br
.ti -1c
.RI "void \fBAddMemeber\fP (\fBChara\fP c)"
.br
.ti -1c
.RI "void \fBChangeMemberType\fP (\fBChara\fP c, FactionMemberType type)"
.br
.ti -1c
.RI "void \fBBanishMember\fP (\fBChara\fP c, bool sell=false)"
.br
.ti -1c
.RI "void \fBRemoveMemeber\fP (\fBChara\fP c)"
.br
.ti -1c
.RI "int \fBGetHappiness\fP (FactionMemberType type)"
.br
.ti -1c
.RI "bool \fBIsAllDead\fP ()"
.br
.ti -1c
.RI "void \fBRecruit\fP (\fBChara\fP c)"
.br
.ti -1c
.RI "\fBChara\fP \fBGetMaid\fP ()"
.br
.ti -1c
.RI "string \fBGetRandomName\fP ()"
.br
.ti -1c
.RI "int \fBCountMembers\fP (FactionMemberType type, bool onlyAlive=false)"
.br
.ti -1c
.RI "int \fBCountGuests\fP ()"
.br
.ti -1c
.RI "int \fBCountWealthyGuests\fP ()"
.br
.ti -1c
.RI "void \fBUpdateReqruits\fP (bool clear=false)"
.br
.ti -1c
.RI "void \fBAddRecruit\fP (\fBChara\fP c)"
.br
.ti -1c
.RI "void \fBRemoveRecruit\fP (\fBChara\fP c)"
.br
.ti -1c
.RI "int \fBCountNewRecruits\fP ()"
.br
.ti -1c
.RI "void \fBClearNewRecruits\fP ()"
.br
.ti -1c
.RI "bool \fBIsRecruit\fP (\fBChara\fP c)"
.br
.ti -1c
.RI "int \fBCountPasture\fP ()"
.br
.ti -1c
.RI "int \fBGetPastureCost\fP ()"
.br
.ti -1c
.RI "int \fBGetCivility\fP ()"
.br
.ti -1c
.RI "float \fBGetHearthIncome\fP ()"
.br
.ti -1c
.RI "float \fBGetHearthIncome\fP (string id)"
.br
.ti -1c
.RI "int \fBGetTechUpgradeCost\fP (\fBElement\fP e)"
.br
.ti -1c
.RI "string \fBLog\fP (string idLang, string ref1=null, string ref2=null, string ref3=null, string ref4=null)"
.br
.ti -1c
.RI "string \fBLog\fP (string idLang, \fBCard\fP c1, \fBCard\fP c2, string ref1=null, string ref2=null)"
.br
.ti -1c
.RI "string \fBLog\fP (string idLang, \fBCard\fP c1, string ref1=null, string ref2=null, string ref3=null)"
.br
.ti -1c
.RI "string \fBLogRaw\fP (string text, string col=null)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBlv\fP = 1"
.br
.ti -1c
.RI "int \fBrank\fP"
.br
.ti -1c
.RI "int \fBexp\fP"
.br
.ti -1c
.RI "int \fBseedPlan\fP"
.br
.ti -1c
.RI "int \fBtemper\fP"
.br
.ti -1c
.RI "int \fBuidMaid\fP"
.br
.ti -1c
.RI "int \fBlastUpdateReqruit\fP"
.br
.ti -1c
.RI "int \fBincomeShop\fP"
.br
.ti -1c
.RI "\fBGStability\fP \fBstability\fP"
.br
.ti -1c
.RI "\fBHomeResourceManager\fP \fBresources\fP = new \fBHomeResourceManager\fP()"
.br
.ti -1c
.RI "\fBResearchManager\fP \fBresearches\fP = new \fBResearchManager\fP()"
.br
.ti -1c
.RI "\fBPolicyManager\fP \fBpolicies\fP = new \fBPolicyManager\fP()"
.br
.ti -1c
.RI "\fBHappinessManager\fP \fBhappiness\fP = new \fBHappinessManager\fP()"
.br
.ti -1c
.RI "\fBMeetingManager\fP \fBmeetings\fP = new \fBMeetingManager\fP()"
.br
.ti -1c
.RI "\fBThing\fP \fBstash\fP"
.br
.ti -1c
.RI "\fBMsgLog\fP \fBlog\fP"
.br
.ti -1c
.RI "\fBReligion\fP \fBfaith\fP"
.br
.ti -1c
.RI "\fBExpeditionManager\fP \fBexpeditions\fP = new \fBExpeditionManager\fP()"
.br
.ti -1c
.RI "List< \fBHireInfo\fP > \fBlistRecruit\fP = new List<\fBHireInfo\fP>()"
.br
.ti -1c
.RI "int \fBdateFound\fP"
.br
.ti -1c
.RI "int \fBtourism\fP"
.br
.ti -1c
.RI "\fBFactionBranch\&.Statistics\fP \fBstatistics\fP = new \fBFactionBranch\&.Statistics\fP()"
.br
.ti -1c
.RI "\fBFactionBranch\&.Statistics\fP \fBlastStatistics\fP = new \fBFactionBranch\&.Statistics\fP()"
.br
.ti -1c
.RI "\fBZone\fP \fBowner\fP"
.br
.ti -1c
.RI "int \fBincomeInn\fP"
.br
.ti -1c
.RI "int \fBincomeTourism\fP"
.br
.ti -1c
.RI "int \fBefficiency\fP = 100"
.br
.ti -1c
.RI "List< \fBChara\fP > \fBmembers\fP = new List<\fBChara\fP>()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBMoney\fP\fR [get]\fP"
.br
.ti -1c
.RI "int \fBWorth\fP\fR [get]\fP"
.br
.ti -1c
.RI "int \fBNumHeirloom\fP\fR [get]\fP"
.br
.ti -1c
.RI "int \fBMaxAP\fP\fR [get]\fP"
.br
.ti -1c
.RI "int \fBMaxPopulation\fP\fR [get]\fP"
.br
.ti -1c
.RI "int \fBMaxSoil\fP\fR [get]\fP"
.br
.ti -1c
.RI "int \fBContentLV\fP\fR [get]\fP"
.br
.ti -1c
.RI "int \fBDangerLV\fP\fR [get]\fP"
.br
.ti -1c
.RI "bool \fBHasNetwork\fP\fR [get]\fP"
.br
.ti -1c
.RI "bool \fBIsTaxFree\fP\fR [get]\fP"
.br
.ti -1c
.RI "string \fBRankText\fP\fR [get]\fP"
.br
.ti -1c
.RI "string \fBTextLv\fP\fR [get]\fP"
.br
.ti -1c
.RI "bool \fBIsStartBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "\fBElementContainerZone\fP \fBelements\fP\fR [get]\fP"
.br
.ti -1c
.RI "int \fBMaxLv\fP\fR [get]\fP"
.br
.in -1c

Properties inherited from \fBEClass\fP
.in +1c
.ti -1c
.RI "static \fBGame\fP \fBgame\fP\fR [get]\fP"
.br
.ti -1c
.RI "static bool \fBAdvMode\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBPlayer\fP \fBplayer\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBChara\fP \fBpc\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBUI\fP \fBui\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBMap\fP \fB_map\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBZone\fP \fB_zone\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranchOrHomeBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFaction\fP \fBHome\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFaction\fP \fBWilds\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBScene\fP \fBscene\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBBaseGameScreen\fP \fBscreen\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameSetting\fP \fBsetting\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameData\fP \fBgamedata\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBColorProfile\fP \fBColors\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBWorld\fP \fBworld\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBsources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBeditorSources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static SoundManager \fBSound\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBCoreDebug\fP \fBdebug\fP\fR [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Static Public Member Functions inherited from \fBEClass\fP
.in +1c
.ti -1c
.RI "static int \fBrnd\fP (int a)"
.br
.ti -1c
.RI "static int \fBcurve\fP (int a, int start, int step, int rate=75)"
.br
.ti -1c
.RI "static int \fBrndHalf\fP (int a)"
.br
.ti -1c
.RI "static float \fBrndf\fP (float a)"
.br
.ti -1c
.RI "static int \fBrndSqrt\fP (int a)"
.br
.ti -1c
.RI "static void \fBWait\fP (float a, \fBCard\fP c)"
.br
.ti -1c
.RI "static void \fBWait\fP (float a, \fBPoint\fP p)"
.br
.ti -1c
.RI "static int \fBBigger\fP (int a, int b)"
.br
.ti -1c
.RI "static int \fBSmaller\fP (int a, int b)"
.br
.in -1c

Static Public Attributes inherited from \fBEClass\fP
.in +1c
.ti -1c
.RI "static \fBCore\fP \fBcore\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB9\fP of file \fBFactionBranch\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void FactionBranch\&.Abandon ()"

.PP
Definition at line \fB199\fP of file \fBFactionBranch\&.cs\fP\&.
.SS "void FactionBranch\&.AddFeat (int ele, int v)"

.PP
Definition at line \fB1143\fP of file \fBFactionBranch\&.cs\fP\&.
.SS "void FactionBranch\&.AddMemeber (\fBChara\fP c)"

.PP
Definition at line \fB1150\fP of file \fBFactionBranch\&.cs\fP\&.
.SS "void FactionBranch\&.AddRecruit (\fBChara\fP c)"

.PP
Definition at line \fB1426\fP of file \fBFactionBranch\&.cs\fP\&.
.SS "void FactionBranch\&.AutoClean ()"

.PP
Definition at line \fB445\fP of file \fBFactionBranch\&.cs\fP\&.
.SS "void FactionBranch\&.BanishMember (\fBChara\fP c, bool sell = \fRfalse\fP)"

.PP
Definition at line \fB1192\fP of file \fBFactionBranch\&.cs\fP\&.
.SS "void FactionBranch\&.CalcInnIncome ()"

.PP
Definition at line \fB818\fP of file \fBFactionBranch\&.cs\fP\&.
.SS "void FactionBranch\&.CalcTourismIncome ()"

.PP
Definition at line \fB860\fP of file \fBFactionBranch\&.cs\fP\&.
.SS "bool FactionBranch\&.CanUpgrade ()"

.PP
Definition at line \fB1088\fP of file \fBFactionBranch\&.cs\fP\&.
.SS "void FactionBranch\&.ChangeMemberType (\fBChara\fP c, FactionMemberType type)"

.PP
Definition at line \fB1183\fP of file \fBFactionBranch\&.cs\fP\&.
.SS "void FactionBranch\&.ClearNewRecruits ()"

.PP
Definition at line \fB1467\fP of file \fBFactionBranch\&.cs\fP\&.
.SS "int FactionBranch\&.CountGuests ()"

.PP
Definition at line \fB1335\fP of file \fBFactionBranch\&.cs\fP\&.
.SS "int FactionBranch\&.CountMembers (FactionMemberType type, bool onlyAlive = \fRfalse\fP)"

.PP
Definition at line \fB1321\fP of file \fBFactionBranch\&.cs\fP\&.
.SS "int FactionBranch\&.CountNewRecruits ()"

.PP
Definition at line \fB1450\fP of file \fBFactionBranch\&.cs\fP\&.
.SS "int FactionBranch\&.CountPasture ()"

.PP
Definition at line \fB1492\fP of file \fBFactionBranch\&.cs\fP\&.
.SS "int FactionBranch\&.CountWealthyGuests ()"

.PP
Definition at line \fB1352\fP of file \fBFactionBranch\&.cs\fP\&.
.SS "void FactionBranch\&.DailyOutcome (\fBVirtualDate\fP date)"

.PP
Definition at line \fB618\fP of file \fBFactionBranch\&.cs\fP\&.
.SS "int FactionBranch\&.Evalue (int ele)"

.PP
Definition at line \fB22\fP of file \fBFactionBranch\&.cs\fP\&.
.SS "void FactionBranch\&.GenerateGarbage (\fBVirtualDate\fP date)"

.PP
Definition at line \fB526\fP of file \fBFactionBranch\&.cs\fP\&.
.SS "int FactionBranch\&.GetCivility ()"

.PP
Definition at line \fB1504\fP of file \fBFactionBranch\&.cs\fP\&.
.SS "void FactionBranch\&.GetDailyIncome ()"

.PP
Definition at line \fB877\fP of file \fBFactionBranch\&.cs\fP\&.
.SS "int FactionBranch\&.GetHappiness (FactionMemberType type)"

.PP
Definition at line \fB1251\fP of file \fBFactionBranch\&.cs\fP\&.
.SS "string FactionBranch\&.GetHearthHint (int a)"

.PP
Definition at line \fB1124\fP of file \fBFactionBranch\&.cs\fP\&.
.SS "float FactionBranch\&.GetHearthIncome ()"

.PP
Definition at line \fB1519\fP of file \fBFactionBranch\&.cs\fP\&.
.SS "float FactionBranch\&.GetHearthIncome (string id)"

.PP
Definition at line \fB1533\fP of file \fBFactionBranch\&.cs\fP\&.
.SS "\fBChara\fP FactionBranch\&.GetMaid ()"

.PP
Definition at line \fB1298\fP of file \fBFactionBranch\&.cs\fP\&.
.SS "\fBThing\fP FactionBranch\&.GetMailBox ()"

.PP
Definition at line \fB751\fP of file \fBFactionBranch\&.cs\fP\&.
.SS "\fBPoint\fP FactionBranch\&.GetMailBoxPos ()"

.PP
Definition at line \fB757\fP of file \fBFactionBranch\&.cs\fP\&.
.SS "\fBThing\fP FactionBranch\&.GetMeal (\fBChara\fP c)"

.PP
Definition at line \fB885\fP of file \fBFactionBranch\&.cs\fP\&.
.SS "int FactionBranch\&.GetNextExp (int _lv = \fR\-1\fP)"

.PP
Definition at line \fB12\fP of file \fBFactionBranch\&.cs\fP\&.
.SS "int FactionBranch\&.GetPastureCost ()"

.PP
Definition at line \fB1498\fP of file \fBFactionBranch\&.cs\fP\&.
.SS "int FactionBranch\&.GetProductBonus (\fBChara\fP c)"

.PP
Definition at line \fB137\fP of file \fBFactionBranch\&.cs\fP\&.
.SS "string FactionBranch\&.GetRandomName ()"

.PP
Definition at line \fB1311\fP of file \fBFactionBranch\&.cs\fP\&.
.SS "int FactionBranch\&.GetResidentTax ()"

.PP
Definition at line \fB772\fP of file \fBFactionBranch\&.cs\fP\&.
.SS "int FactionBranch\&.GetTechUpgradeCost (\fBElement\fP e)"

.PP
Definition at line \fB1547\fP of file \fBFactionBranch\&.cs\fP\&.
.SS "int FactionBranch\&.GetUpgradeCost ()"

.PP
Definition at line \fB1094\fP of file \fBFactionBranch\&.cs\fP\&.
.SS "bool FactionBranch\&.IsAllDead ()"

.PP
Definition at line \fB1266\fP of file \fBFactionBranch\&.cs\fP\&.
.SS "bool FactionBranch\&.IsRecruit (\fBChara\fP c)"

.PP
Definition at line \fB1476\fP of file \fBFactionBranch\&.cs\fP\&.
.SS "string FactionBranch\&.Log (string idLang, \fBCard\fP c1, \fBCard\fP c2, string ref1 = \fRnull\fP, string ref2 = \fRnull\fP)"

.PP
Definition at line \fB1566\fP of file \fBFactionBranch\&.cs\fP\&.
.SS "string FactionBranch\&.Log (string idLang, \fBCard\fP c1, string ref1 = \fRnull\fP, string ref2 = \fRnull\fP, string ref3 = \fRnull\fP)"

.PP
Definition at line \fB1573\fP of file \fBFactionBranch\&.cs\fP\&.
.SS "string FactionBranch\&.Log (string idLang, string ref1 = \fRnull\fP, string ref2 = \fRnull\fP, string ref3 = \fRnull\fP, string ref4 = \fRnull\fP)"

.PP
Definition at line \fB1559\fP of file \fBFactionBranch\&.cs\fP\&.
.SS "string FactionBranch\&.LogRaw (string text, string col = \fRnull\fP)"

.PP
Definition at line \fB1580\fP of file \fBFactionBranch\&.cs\fP\&.
.SS "void FactionBranch\&.ModExp (int a)"

.PP
Definition at line \fB1100\fP of file \fBFactionBranch\&.cs\fP\&.
.SS "void FactionBranch\&.OnActivateZone ()"

.PP
Definition at line \fB243\fP of file \fBFactionBranch\&.cs\fP\&.
.SS "void FactionBranch\&.OnAdvanceDay ()"

.PP
Definition at line \fB498\fP of file \fBFactionBranch\&.cs\fP\&.
.SS "void FactionBranch\&.OnAfterSimulate ()"

.PP
Definition at line \fB259\fP of file \fBFactionBranch\&.cs\fP\&.
.SS "void FactionBranch\&.OnClaimZone ()"

.PP
Definition at line \fB896\fP of file \fBFactionBranch\&.cs\fP\&.
.SS "void FactionBranch\&.OnCreate (\fBZone\fP zone)"

.PP
Definition at line \fB204\fP of file \fBFactionBranch\&.cs\fP\&.
.SS "void FactionBranch\&.OnSimulateDay (\fBVirtualDate\fP date)"

.PP
Definition at line \fB470\fP of file \fBFactionBranch\&.cs\fP\&.
.SS "void FactionBranch\&.OnSimulateHour (\fBVirtualDate\fP date)"

.PP
Definition at line \fB273\fP of file \fBFactionBranch\&.cs\fP\&.
.SS "void FactionBranch\&.OnSimulateMonth (\fBVirtualDate\fP date)"

.PP
Definition at line \fB519\fP of file \fBFactionBranch\&.cs\fP\&.
.SS "void FactionBranch\&.OnUnclaimZone ()"

.PP
Definition at line \fB962\fP of file \fBFactionBranch\&.cs\fP\&.
.SS "void FactionBranch\&.OnUnloadMap ()"

.PP
Definition at line \fB268\fP of file \fBFactionBranch\&.cs\fP\&.
.SS "void FactionBranch\&.PutInMailBox (\fBThing\fP t, bool outside = \fRfalse\fP, bool install = \fRtrue\fP)"

.PP
Definition at line \fB731\fP of file \fBFactionBranch\&.cs\fP\&.
.SS "void FactionBranch\&.ReceivePackages (\fBVirtualDate\fP date)"

.PP
Definition at line \fB586\fP of file \fBFactionBranch\&.cs\fP\&.
.SS "void FactionBranch\&.Recruit (\fBChara\fP c)"

.PP
Definition at line \fB1282\fP of file \fBFactionBranch\&.cs\fP\&.
.SS "void FactionBranch\&.RefreshEfficiency ()"

.PP
Definition at line \fB147\fP of file \fBFactionBranch\&.cs\fP\&.
.SS "void FactionBranch\&.RemoveMemeber (\fBChara\fP c)"

.PP
Definition at line \fB1233\fP of file \fBFactionBranch\&.cs\fP\&.
.SS "void FactionBranch\&.RemoveRecruit (\fBChara\fP c)"

.PP
Definition at line \fB1438\fP of file \fBFactionBranch\&.cs\fP\&.
.SS "void FactionBranch\&.SetOwner (\fBZone\fP zone)"

.PP
Definition at line \fB214\fP of file \fBFactionBranch\&.cs\fP\&.
.SS "bool FactionBranch\&.TryTrash (\fBThing\fP t)"

.PP
Definition at line \fB562\fP of file \fBFactionBranch\&.cs\fP\&.
.SS "void FactionBranch\&.UpdateReqruits (bool clear = \fRfalse\fP)"

.PP
Definition at line \fB1366\fP of file \fBFactionBranch\&.cs\fP\&.
.SS "void FactionBranch\&.Upgrade ()"

.PP
Definition at line \fB1001\fP of file \fBFactionBranch\&.cs\fP\&.
.SS "void FactionBranch\&.ValidateUpgradePolicies ()"

.PP
Definition at line \fB967\fP of file \fBFactionBranch\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int FactionBranch\&.dateFound"

.PP
Definition at line \fB1764\fP of file \fBFactionBranch\&.cs\fP\&.
.SS "int FactionBranch\&.efficiency = 100"

.PP
Definition at line \fB1788\fP of file \fBFactionBranch\&.cs\fP\&.
.SS "int FactionBranch\&.exp"

.PP
Definition at line \fB1690\fP of file \fBFactionBranch\&.cs\fP\&.
.SS "\fBExpeditionManager\fP FactionBranch\&.expeditions = new \fBExpeditionManager\fP()"

.PP
Definition at line \fB1756\fP of file \fBFactionBranch\&.cs\fP\&.
.SS "\fBReligion\fP FactionBranch\&.faith"

.PP
Definition at line \fB1752\fP of file \fBFactionBranch\&.cs\fP\&.
.SS "\fBHappinessManager\fP FactionBranch\&.happiness = new \fBHappinessManager\fP()"

.PP
Definition at line \fB1733\fP of file \fBFactionBranch\&.cs\fP\&.
.SS "int FactionBranch\&.incomeInn"

.PP
Definition at line \fB1782\fP of file \fBFactionBranch\&.cs\fP\&.
.SS "int FactionBranch\&.incomeShop"

.PP
Definition at line \fB1710\fP of file \fBFactionBranch\&.cs\fP\&.
.SS "int FactionBranch\&.incomeTourism"

.PP
Definition at line \fB1785\fP of file \fBFactionBranch\&.cs\fP\&.
.SS "\fBFactionBranch\&.Statistics\fP FactionBranch\&.lastStatistics = new \fBFactionBranch\&.Statistics\fP()"

.PP
Definition at line \fB1776\fP of file \fBFactionBranch\&.cs\fP\&.
.SS "int FactionBranch\&.lastUpdateReqruit"

.PP
Definition at line \fB1706\fP of file \fBFactionBranch\&.cs\fP\&.
.SS "List<\fBHireInfo\fP> FactionBranch\&.listRecruit = new List<\fBHireInfo\fP>()"

.PP
Definition at line \fB1760\fP of file \fBFactionBranch\&.cs\fP\&.
.SS "\fBMsgLog\fP FactionBranch\&.log"
\fBInitial value:\fP
.nf
= new MsgLog
    {
        id = "log"
    }
.PP
.fi

.PP
Definition at line \fB1745\fP of file \fBFactionBranch\&.cs\fP\&.
.SS "int FactionBranch\&.lv = 1"

.PP
Definition at line \fB1682\fP of file \fBFactionBranch\&.cs\fP\&.
.SS "\fBMeetingManager\fP FactionBranch\&.meetings = new \fBMeetingManager\fP()"

.PP
Definition at line \fB1737\fP of file \fBFactionBranch\&.cs\fP\&.
.SS "List<\fBChara\fP> FactionBranch\&.members = new List<\fBChara\fP>()"

.PP
Definition at line \fB1791\fP of file \fBFactionBranch\&.cs\fP\&.
.SS "\fBZone\fP FactionBranch\&.owner"

.PP
Definition at line \fB1779\fP of file \fBFactionBranch\&.cs\fP\&.
.SS "\fBPolicyManager\fP FactionBranch\&.policies = new \fBPolicyManager\fP()"

.PP
Definition at line \fB1729\fP of file \fBFactionBranch\&.cs\fP\&.
.SS "int FactionBranch\&.rank"

.PP
Definition at line \fB1686\fP of file \fBFactionBranch\&.cs\fP\&.
.SS "\fBResearchManager\fP FactionBranch\&.researches = new \fBResearchManager\fP()"

.PP
Definition at line \fB1725\fP of file \fBFactionBranch\&.cs\fP\&.
.SS "\fBHomeResourceManager\fP FactionBranch\&.resources = new \fBHomeResourceManager\fP()"

.PP
Definition at line \fB1721\fP of file \fBFactionBranch\&.cs\fP\&.
.SS "int FactionBranch\&.seedPlan"

.PP
Definition at line \fB1694\fP of file \fBFactionBranch\&.cs\fP\&.
.SS "\fBGStability\fP FactionBranch\&.stability"
\fBInitial value:\fP
.nf
= new GStability
    {
        value = 1
    }
.PP
.fi

.PP
Definition at line \fB1714\fP of file \fBFactionBranch\&.cs\fP\&.
.SS "\fBThing\fP FactionBranch\&.stash"

.PP
Definition at line \fB1741\fP of file \fBFactionBranch\&.cs\fP\&.
.SS "\fBFactionBranch\&.Statistics\fP FactionBranch\&.statistics = new \fBFactionBranch\&.Statistics\fP()"

.PP
Definition at line \fB1772\fP of file \fBFactionBranch\&.cs\fP\&.
.SS "int FactionBranch\&.temper"

.PP
Definition at line \fB1698\fP of file \fBFactionBranch\&.cs\fP\&.
.SS "int FactionBranch\&.tourism"

.PP
Definition at line \fB1768\fP of file \fBFactionBranch\&.cs\fP\&.
.SS "int FactionBranch\&.uidMaid"

.PP
Definition at line \fB1702\fP of file \fBFactionBranch\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "int FactionBranch\&.ContentLV\fR [get]\fP"

.PP
Definition at line \fB98\fP of file \fBFactionBranch\&.cs\fP\&.
.SS "int FactionBranch\&.DangerLV\fR [get]\fP"

.PP
Definition at line \fB108\fP of file \fBFactionBranch\&.cs\fP\&.
.SS "\fBElementContainerZone\fP FactionBranch\&.elements\fR [get]\fP"

.PP
Definition at line \fB190\fP of file \fBFactionBranch\&.cs\fP\&.
.SS "bool FactionBranch\&.HasNetwork\fR [get]\fP"

.PP
Definition at line \fB118\fP of file \fBFactionBranch\&.cs\fP\&.
.SS "bool FactionBranch\&.IsStartBranch\fR [get]\fP"

.PP
Definition at line \fB180\fP of file \fBFactionBranch\&.cs\fP\&.
.SS "bool FactionBranch\&.IsTaxFree\fR [get]\fP"

.PP
Definition at line \fB128\fP of file \fBFactionBranch\&.cs\fP\&.
.SS "int FactionBranch\&.MaxAP\fR [get]\fP"

.PP
Definition at line \fB68\fP of file \fBFactionBranch\&.cs\fP\&.
.SS "int FactionBranch\&.MaxLv\fR [get]\fP"

.PP
Definition at line \fB1079\fP of file \fBFactionBranch\&.cs\fP\&.
.SS "int FactionBranch\&.MaxPopulation\fR [get]\fP"

.PP
Definition at line \fB78\fP of file \fBFactionBranch\&.cs\fP\&.
.SS "int FactionBranch\&.MaxSoil\fR [get]\fP"

.PP
Definition at line \fB88\fP of file \fBFactionBranch\&.cs\fP\&.
.SS "int FactionBranch\&.Money\fR [get]\fP"

.PP
Definition at line \fB38\fP of file \fBFactionBranch\&.cs\fP\&.
.SS "int FactionBranch\&.NumHeirloom\fR [get]\fP"

.PP
Definition at line \fB58\fP of file \fBFactionBranch\&.cs\fP\&.
.SS "string FactionBranch\&.RankText\fR [get]\fP"

.PP
Definition at line \fB160\fP of file \fBFactionBranch\&.cs\fP\&.
.SS "string FactionBranch\&.TextLv\fR [get]\fP"

.PP
Definition at line \fB170\fP of file \fBFactionBranch\&.cs\fP\&.
.SS "int FactionBranch\&.Worth\fR [get]\fP"

.PP
Definition at line \fB48\fP of file \fBFactionBranch\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
