.TH "FLOOR" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FLOOR
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBEClass\fP\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBIsTatami\fP (int id)"
.br
.in -1c

Static Public Member Functions inherited from \fBEClass\fP
.in +1c
.ti -1c
.RI "static int \fBrnd\fP (int a)"
.br
.ti -1c
.RI "static int \fBcurve\fP (int a, int start, int step, int rate=75)"
.br
.ti -1c
.RI "static int \fBrndHalf\fP (int a)"
.br
.ti -1c
.RI "static float \fBrndf\fP (float a)"
.br
.ti -1c
.RI "static int \fBrndSqrt\fP (int a)"
.br
.ti -1c
.RI "static void \fBWait\fP (float a, \fBCard\fP c)"
.br
.ti -1c
.RI "static void \fBWait\fP (float a, \fBPoint\fP p)"
.br
.ti -1c
.RI "static int \fBBigger\fP (int a, int b)"
.br
.ti -1c
.RI "static int \fBSmaller\fP (int a, int b)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "const int \fBTileWidth\fP = 32"
.br
.ti -1c
.RI "const int \fBfloor_raw\fP = 40"
.br
.ti -1c
.RI "const int \fBfield\fP = 4"
.br
.ti -1c
.RI "const int \fBfloor_rock\fP = 6"
.br
.ti -1c
.RI "const int \fBfloor_wood\fP = 21"
.br
.ti -1c
.RI "const int \fBfloor_water\fP = 43"
.br
.ti -1c
.RI "const int \fBfloor_water_shallow\fP = 44"
.br
.ti -1c
.RI "const int \fBfloor_deck\fP = 57"
.br
.ti -1c
.RI "const int \fBfloor_sand\fP = 33"
.br
.ti -1c
.RI "const int \fBfloor_snow\fP = 39"
.br
.ti -1c
.RI "const int \fBfloor_ice\fP = 38"
.br
.ti -1c
.RI "const int \fBfloor_snow2\fP = 56"
.br
.ti -1c
.RI "const int \fBsky\fP = 90"
.br
.ti -1c
.RI "const int \fBfloor_shore\fP = 33"
.br
.ti -1c
.RI "static \fBSourceFloor\&.Row\fP \fBsourceSnow\fP = EClass\&.sources\&.floors\&.rows[39]"
.br
.ti -1c
.RI "static \fBSourceFloor\&.Row\fP \fBsourceSnow2\fP = EClass\&.sources\&.floors\&.rows[56]"
.br
.ti -1c
.RI "static \fBSourceFloor\&.Row\fP \fBsourceIce\fP = EClass\&.sources\&.floors\&.rows[38]"
.br
.ti -1c
.RI "static \fBSourceFloor\&.Row\fP \fBsourceWood\fP = EClass\&.sources\&.floors\&.rows[21]"
.br
.in -1c

Static Public Attributes inherited from \fBEClass\fP
.in +1c
.ti -1c
.RI "static \fBCore\fP \fBcore\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Properties inherited from \fBEClass\fP
.in +1c
.ti -1c
.RI "static \fBGame\fP \fBgame\fP\fR [get]\fP"
.br
.ti -1c
.RI "static bool \fBAdvMode\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBPlayer\fP \fBplayer\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBChara\fP \fBpc\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBUI\fP \fBui\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBMap\fP \fB_map\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBZone\fP \fB_zone\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranchOrHomeBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFaction\fP \fBHome\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFaction\fP \fBWilds\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBScene\fP \fBscene\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBBaseGameScreen\fP \fBscreen\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameSetting\fP \fBsetting\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameData\fP \fBgamedata\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBColorProfile\fP \fBColors\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBWorld\fP \fBworld\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBsources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBeditorSources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static SoundManager \fBSound\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBCoreDebug\fP \fBdebug\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB4\fP of file \fBFLOOR\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "static bool FLOOR\&.IsTatami (int id)\fR [static]\fP"

.PP
Definition at line \fB7\fP of file \fBFLOOR\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "const int FLOOR\&.field = 4\fR [static]\fP"

.PP
Definition at line \fB19\fP of file \fBFLOOR\&.cs\fP\&.
.SS "const int FLOOR\&.floor_deck = 57\fR [static]\fP"

.PP
Definition at line \fB34\fP of file \fBFLOOR\&.cs\fP\&.
.SS "const int FLOOR\&.floor_ice = 38\fR [static]\fP"

.PP
Definition at line \fB43\fP of file \fBFLOOR\&.cs\fP\&.
.SS "const int FLOOR\&.floor_raw = 40\fR [static]\fP"

.PP
Definition at line \fB16\fP of file \fBFLOOR\&.cs\fP\&.
.SS "const int FLOOR\&.floor_rock = 6\fR [static]\fP"

.PP
Definition at line \fB22\fP of file \fBFLOOR\&.cs\fP\&.
.SS "const int FLOOR\&.floor_sand = 33\fR [static]\fP"

.PP
Definition at line \fB37\fP of file \fBFLOOR\&.cs\fP\&.
.SS "const int FLOOR\&.floor_shore = 33\fR [static]\fP"

.PP
Definition at line \fB52\fP of file \fBFLOOR\&.cs\fP\&.
.SS "const int FLOOR\&.floor_snow = 39\fR [static]\fP"

.PP
Definition at line \fB40\fP of file \fBFLOOR\&.cs\fP\&.
.SS "const int FLOOR\&.floor_snow2 = 56\fR [static]\fP"

.PP
Definition at line \fB46\fP of file \fBFLOOR\&.cs\fP\&.
.SS "const int FLOOR\&.floor_water = 43\fR [static]\fP"

.PP
Definition at line \fB28\fP of file \fBFLOOR\&.cs\fP\&.
.SS "const int FLOOR\&.floor_water_shallow = 44\fR [static]\fP"

.PP
Definition at line \fB31\fP of file \fBFLOOR\&.cs\fP\&.
.SS "const int FLOOR\&.floor_wood = 21\fR [static]\fP"

.PP
Definition at line \fB25\fP of file \fBFLOOR\&.cs\fP\&.
.SS "const int FLOOR\&.sky = 90\fR [static]\fP"

.PP
Definition at line \fB49\fP of file \fBFLOOR\&.cs\fP\&.
.SS "\fBSourceFloor\&.Row\fP FLOOR\&.sourceIce = EClass\&.sources\&.floors\&.rows[38]\fR [static]\fP"

.PP
Definition at line \fB61\fP of file \fBFLOOR\&.cs\fP\&.
.SS "\fBSourceFloor\&.Row\fP FLOOR\&.sourceSnow = EClass\&.sources\&.floors\&.rows[39]\fR [static]\fP"

.PP
Definition at line \fB55\fP of file \fBFLOOR\&.cs\fP\&.
.SS "\fBSourceFloor\&.Row\fP FLOOR\&.sourceSnow2 = EClass\&.sources\&.floors\&.rows[56]\fR [static]\fP"

.PP
Definition at line \fB58\fP of file \fBFLOOR\&.cs\fP\&.
.SS "\fBSourceFloor\&.Row\fP FLOOR\&.sourceWood = EClass\&.sources\&.floors\&.rows[21]\fR [static]\fP"

.PP
Definition at line \fB64\fP of file \fBFLOOR\&.cs\fP\&.
.SS "const int FLOOR\&.TileWidth = 32\fR [static]\fP"

.PP
Definition at line \fB13\fP of file \fBFLOOR\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
