.TH "Footmark" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Footmark
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBPoint\fP \fBpos\fP = new \fBPoint\fP()"
.br
.ti -1c
.RI "int \fBremaining\fP"
.br
.ti -1c
.RI "int \fBtile\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB4\fP of file \fBFootmark\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBPoint\fP Footmark\&.pos = new \fBPoint\fP()"

.PP
Definition at line \fB7\fP of file \fBFootmark\&.cs\fP\&.
.SS "int Footmark\&.remaining"

.PP
Definition at line \fB10\fP of file \fBFootmark\&.cs\fP\&.
.SS "int Footmark\&.tile"

.PP
Definition at line \fB13\fP of file \fBFootmark\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
