.TH "GameSetting.UISetting" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GameSetting.UISetting
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "List< \fBWidget\&.Meta\fP > \fBwidgetMetas\fP"
.br
.ti -1c
.RI "List< Vector2 > \fBiconSizes\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB118\fP of file \fBGameSetting\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "List<Vector2> GameSetting\&.UISetting\&.iconSizes"

.PP
Definition at line \fB124\fP of file \fBGameSetting\&.cs\fP\&.
.SS "List<\fBWidget\&.Meta\fP> GameSetting\&.UISetting\&.widgetMetas"

.PP
Definition at line \fB121\fP of file \fBGameSetting\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
