.TH "GameSetting.RenderSetting.MapBGSetting" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GameSetting.RenderSetting.MapBGSetting
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Material \fBmat\fP"
.br
.ti -1c
.RI "bool \fBskyBox\fP"
.br
.ti -1c
.RI "bool \fBwall\fP"
.br
.ti -1c
.RI "bool \fBplane\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB381\fP of file \fBGameSetting\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "Material GameSetting\&.RenderSetting\&.MapBGSetting\&.mat"

.PP
Definition at line \fB384\fP of file \fBGameSetting\&.cs\fP\&.
.SS "bool GameSetting\&.RenderSetting\&.MapBGSetting\&.plane"

.PP
Definition at line \fB393\fP of file \fBGameSetting\&.cs\fP\&.
.SS "bool GameSetting\&.RenderSetting\&.MapBGSetting\&.skyBox"

.PP
Definition at line \fB387\fP of file \fBGameSetting\&.cs\fP\&.
.SS "bool GameSetting\&.RenderSetting\&.MapBGSetting\&.wall"

.PP
Definition at line \fB390\fP of file \fBGameSetting\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
