.TH "GameSetting.GenSetting" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GameSetting.GenSetting
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBdefaultBlockHeight\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB467\fP of file \fBGameSetting\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "float GameSetting\&.GenSetting\&.defaultBlockHeight"

.PP
Definition at line \fB470\fP of file \fBGameSetting\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
