.TH "GameSetting.RenderSetting" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GameSetting.RenderSetting
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBActorSetting\fP"
.br
.ti -1c
.RI "class \fBAnimeSetting\fP"
.br
.ti -1c
.RI "class \fBMapBGSetting\fP"
.br
.ti -1c
.RI "class \fBTCSetting\fP"
.br
.ti -1c
.RI "class \fBUD_FogSetting\fP"
.br
.ti -1c
.RI "class \fBUD_MapBGSetting\fP"
.br
.ti -1c
.RI "class \fBZSetting\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBGameSetting\&.RenderSetting\&.ZSetting\fP \fBzSetting\fP"
.br
.ti -1c
.RI "\fBGameSetting\&.RenderSetting\&.TCSetting\fP \fBtc\fP"
.br
.ti -1c
.RI "\fBGameSetting\&.RenderSetting\&.AnimeSetting\fP \fBanime\fP"
.br
.ti -1c
.RI "\fBGameSetting\&.RenderSetting\&.ActorSetting\fP \fBactor\fP"
.br
.ti -1c
.RI "Vector3[] \fBcharaPos\fP"
.br
.ti -1c
.RI "Vector3[] \fBheldPos\fP"
.br
.ti -1c
.RI "Vector3[] \fBheldPosChara\fP"
.br
.ti -1c
.RI "Vector3[] \fBheldPosChara2\fP"
.br
.ti -1c
.RI "Vector3[] \fBmainHandPos\fP"
.br
.ti -1c
.RI "Vector3[] \fBoffHandPos\fP"
.br
.ti -1c
.RI "Vector3[] \fBhatPos\fP"
.br
.ti -1c
.RI "Vector3[] \fBridePos\fP"
.br
.ti -1c
.RI "Vector3 \fBposShackle\fP"
.br
.ti -1c
.RI "Vector3 \fBposGallows\fP"
.br
.ti -1c
.RI "\fBGameSetting\&.TransData\fP[] \fBdead\fP"
.br
.ti -1c
.RI "Vector3[] \fBrampFix\fP"
.br
.ti -1c
.RI "Vector3 \fBvFix\fP"
.br
.ti -1c
.RI "Vector3 \fBpccScale\fP"
.br
.ti -1c
.RI "Vector3 \fBwaterFix\fP"
.br
.ti -1c
.RI "float \fBthingZ\fP"
.br
.ti -1c
.RI "float \fBlaydownZ\fP"
.br
.ti -1c
.RI "float \fBcharaZ\fP"
.br
.ti -1c
.RI "float \fBshadowAngle\fP"
.br
.ti -1c
.RI "float \fBtileMarkerZ\fP"
.br
.ti -1c
.RI "float \fBtileMarkerZFloor\fP"
.br
.ti -1c
.RI "float \fBcrateHeight\fP"
.br
.ti -1c
.RI "float \fBhangedObjFixZ\fP"
.br
.ti -1c
.RI "Vector3 \fBshadowScale\fP"
.br
.ti -1c
.RI "Vector3 \fBshadowOffset\fP"
.br
.ti -1c
.RI "Vector3 \fBpeakFix\fP"
.br
.ti -1c
.RI "Vector3 \fBpeakFixBlock\fP"
.br
.ti -1c
.RI "float \fBroomHeightMod\fP"
.br
.ti -1c
.RI "float \fBdefCharaHeight\fP"
.br
.ti -1c
.RI "float \fBalphaHair\fP"
.br
.ti -1c
.RI "float \fBshadowStrength\fP"
.br
.ti -1c
.RI "Vector2 \fBfreePosFix\fP"
.br
.ti -1c
.RI "\fBAnimationFrame\fP[] \fBanimeWalk\fP"
.br
.ti -1c
.RI "UD_String_PaintPosition \fBpaintPos\fP"
.br
.ti -1c
.RI "\fBGameSetting\&.RenderSetting\&.UD_MapBGSetting\fP \fBbgs\fP"
.br
.ti -1c
.RI "\fBGameSetting\&.RenderSetting\&.UD_FogSetting\fP \fBfogs\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB129\fP of file \fBGameSetting\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBGameSetting\&.RenderSetting\&.ActorSetting\fP GameSetting\&.RenderSetting\&.actor"

.PP
Definition at line \fB141\fP of file \fBGameSetting\&.cs\fP\&.
.SS "float GameSetting\&.RenderSetting\&.alphaHair"

.PP
Definition at line \fB231\fP of file \fBGameSetting\&.cs\fP\&.
.SS "\fBGameSetting\&.RenderSetting\&.AnimeSetting\fP GameSetting\&.RenderSetting\&.anime"

.PP
Definition at line \fB138\fP of file \fBGameSetting\&.cs\fP\&.
.SS "\fBAnimationFrame\fP [] GameSetting\&.RenderSetting\&.animeWalk"

.PP
Definition at line \fB240\fP of file \fBGameSetting\&.cs\fP\&.
.SS "\fBGameSetting\&.RenderSetting\&.UD_MapBGSetting\fP GameSetting\&.RenderSetting\&.bgs"

.PP
Definition at line \fB246\fP of file \fBGameSetting\&.cs\fP\&.
.SS "Vector3 [] GameSetting\&.RenderSetting\&.charaPos"

.PP
Definition at line \fB144\fP of file \fBGameSetting\&.cs\fP\&.
.SS "float GameSetting\&.RenderSetting\&.charaZ"

.PP
Definition at line \fB195\fP of file \fBGameSetting\&.cs\fP\&.
.SS "float GameSetting\&.RenderSetting\&.crateHeight"

.PP
Definition at line \fB207\fP of file \fBGameSetting\&.cs\fP\&.
.SS "\fBGameSetting\&.TransData\fP [] GameSetting\&.RenderSetting\&.dead"

.PP
Definition at line \fB174\fP of file \fBGameSetting\&.cs\fP\&.
.SS "float GameSetting\&.RenderSetting\&.defCharaHeight"

.PP
Definition at line \fB228\fP of file \fBGameSetting\&.cs\fP\&.
.SS "\fBGameSetting\&.RenderSetting\&.UD_FogSetting\fP GameSetting\&.RenderSetting\&.fogs"

.PP
Definition at line \fB249\fP of file \fBGameSetting\&.cs\fP\&.
.SS "Vector2 GameSetting\&.RenderSetting\&.freePosFix"

.PP
Definition at line \fB237\fP of file \fBGameSetting\&.cs\fP\&.
.SS "float GameSetting\&.RenderSetting\&.hangedObjFixZ"

.PP
Definition at line \fB210\fP of file \fBGameSetting\&.cs\fP\&.
.SS "Vector3 [] GameSetting\&.RenderSetting\&.hatPos"

.PP
Definition at line \fB162\fP of file \fBGameSetting\&.cs\fP\&.
.SS "Vector3 [] GameSetting\&.RenderSetting\&.heldPos"

.PP
Definition at line \fB147\fP of file \fBGameSetting\&.cs\fP\&.
.SS "Vector3 [] GameSetting\&.RenderSetting\&.heldPosChara"

.PP
Definition at line \fB150\fP of file \fBGameSetting\&.cs\fP\&.
.SS "Vector3 [] GameSetting\&.RenderSetting\&.heldPosChara2"

.PP
Definition at line \fB153\fP of file \fBGameSetting\&.cs\fP\&.
.SS "float GameSetting\&.RenderSetting\&.laydownZ"

.PP
Definition at line \fB192\fP of file \fBGameSetting\&.cs\fP\&.
.SS "Vector3 [] GameSetting\&.RenderSetting\&.mainHandPos"

.PP
Definition at line \fB156\fP of file \fBGameSetting\&.cs\fP\&.
.SS "Vector3 [] GameSetting\&.RenderSetting\&.offHandPos"

.PP
Definition at line \fB159\fP of file \fBGameSetting\&.cs\fP\&.
.SS "UD_String_PaintPosition GameSetting\&.RenderSetting\&.paintPos"

.PP
Definition at line \fB243\fP of file \fBGameSetting\&.cs\fP\&.
.SS "Vector3 GameSetting\&.RenderSetting\&.pccScale"

.PP
Definition at line \fB183\fP of file \fBGameSetting\&.cs\fP\&.
.SS "Vector3 GameSetting\&.RenderSetting\&.peakFix"

.PP
Definition at line \fB219\fP of file \fBGameSetting\&.cs\fP\&.
.SS "Vector3 GameSetting\&.RenderSetting\&.peakFixBlock"

.PP
Definition at line \fB222\fP of file \fBGameSetting\&.cs\fP\&.
.SS "Vector3 GameSetting\&.RenderSetting\&.posGallows"

.PP
Definition at line \fB171\fP of file \fBGameSetting\&.cs\fP\&.
.SS "Vector3 GameSetting\&.RenderSetting\&.posShackle"

.PP
Definition at line \fB168\fP of file \fBGameSetting\&.cs\fP\&.
.SS "Vector3 [] GameSetting\&.RenderSetting\&.rampFix"

.PP
Definition at line \fB177\fP of file \fBGameSetting\&.cs\fP\&.
.SS "Vector3 [] GameSetting\&.RenderSetting\&.ridePos"

.PP
Definition at line \fB165\fP of file \fBGameSetting\&.cs\fP\&.
.SS "float GameSetting\&.RenderSetting\&.roomHeightMod"

.PP
Definition at line \fB225\fP of file \fBGameSetting\&.cs\fP\&.
.SS "float GameSetting\&.RenderSetting\&.shadowAngle"

.PP
Definition at line \fB198\fP of file \fBGameSetting\&.cs\fP\&.
.SS "Vector3 GameSetting\&.RenderSetting\&.shadowOffset"

.PP
Definition at line \fB216\fP of file \fBGameSetting\&.cs\fP\&.
.SS "Vector3 GameSetting\&.RenderSetting\&.shadowScale"

.PP
Definition at line \fB213\fP of file \fBGameSetting\&.cs\fP\&.
.SS "float GameSetting\&.RenderSetting\&.shadowStrength"

.PP
Definition at line \fB234\fP of file \fBGameSetting\&.cs\fP\&.
.SS "\fBGameSetting\&.RenderSetting\&.TCSetting\fP GameSetting\&.RenderSetting\&.tc"

.PP
Definition at line \fB135\fP of file \fBGameSetting\&.cs\fP\&.
.SS "float GameSetting\&.RenderSetting\&.thingZ"

.PP
Definition at line \fB189\fP of file \fBGameSetting\&.cs\fP\&.
.SS "float GameSetting\&.RenderSetting\&.tileMarkerZ"

.PP
Definition at line \fB201\fP of file \fBGameSetting\&.cs\fP\&.
.SS "float GameSetting\&.RenderSetting\&.tileMarkerZFloor"

.PP
Definition at line \fB204\fP of file \fBGameSetting\&.cs\fP\&.
.SS "Vector3 GameSetting\&.RenderSetting\&.vFix"

.PP
Definition at line \fB180\fP of file \fBGameSetting\&.cs\fP\&.
.SS "Vector3 GameSetting\&.RenderSetting\&.waterFix"

.PP
Definition at line \fB186\fP of file \fBGameSetting\&.cs\fP\&.
.SS "\fBGameSetting\&.RenderSetting\&.ZSetting\fP GameSetting\&.RenderSetting\&.zSetting"

.PP
Definition at line \fB132\fP of file \fBGameSetting\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
