.TH "GameSetting.RenderSetting.UD_MapBGSetting" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GameSetting.RenderSetting.UD_MapBGSetting
.SH SYNOPSIS
.br
.PP
.PP
Inherits UDictionary< MapBG, GameSetting\&.RenderSetting\&.MapBGSetting >\&.
.SH "Detailed Description"
.PP 
Definition at line \fB398\fP of file \fBGameSetting\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
