.TH "GameSetting.RenderSetting.TCSetting" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GameSetting.RenderSetting.TCSetting
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Vector3 \fBtextPos\fP"
.br
.ti -1c
.RI "Vector3 \fBtextPosDead\fP"
.br
.ti -1c
.RI "Vector3 \fBstatePos\fP"
.br
.ti -1c
.RI "Vector3 \fBcensorPos\fP"
.br
.ti -1c
.RI "Vector3 \fBsimpleTextPos\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB353\fP of file \fBGameSetting\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "Vector3 GameSetting\&.RenderSetting\&.TCSetting\&.censorPos"

.PP
Definition at line \fB365\fP of file \fBGameSetting\&.cs\fP\&.
.SS "Vector3 GameSetting\&.RenderSetting\&.TCSetting\&.simpleTextPos"

.PP
Definition at line \fB368\fP of file \fBGameSetting\&.cs\fP\&.
.SS "Vector3 GameSetting\&.RenderSetting\&.TCSetting\&.statePos"

.PP
Definition at line \fB362\fP of file \fBGameSetting\&.cs\fP\&.
.SS "Vector3 GameSetting\&.RenderSetting\&.TCSetting\&.textPos"

.PP
Definition at line \fB356\fP of file \fBGameSetting\&.cs\fP\&.
.SS "Vector3 GameSetting\&.RenderSetting\&.TCSetting\&.textPosDead"

.PP
Definition at line \fB359\fP of file \fBGameSetting\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
