.TH "GameSetting.TransData" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GameSetting.TransData
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Vector3 \fBscale\fP"
.br
.ti -1c
.RI "Vector3 \fBeuler\fP"
.br
.ti -1c
.RI "Vector3 \fBpos\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB96\fP of file \fBGameSetting\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "Vector3 GameSetting\&.TransData\&.euler"

.PP
Definition at line \fB102\fP of file \fBGameSetting\&.cs\fP\&.
.SS "Vector3 GameSetting\&.TransData\&.pos"

.PP
Definition at line \fB105\fP of file \fBGameSetting\&.cs\fP\&.
.SS "Vector3 GameSetting\&.TransData\&.scale"

.PP
Definition at line \fB99\fP of file \fBGameSetting\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
