.TH "GameUpdater" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GameUpdater
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBEClass\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAreaUpdater\fP"
.br
.ti -1c
.RI "class \fBCharaUpdater\fP"
.br
.ti -1c
.RI "class \fBConditionUpdater\fP"
.br
.ti -1c
.RI "class \fBFastSurfaceUpdater\fP"
.br
.ti -1c
.RI "class \fBFireUpdater\fP"
.br
.ti -1c
.RI "class \fBLogicUpdater\fP"
.br
.ti -1c
.RI "class \fBSensorUpdater\fP"
.br
.ti -1c
.RI "class \fBSurfaceUpdater\fP"
.br
.ti -1c
.RI "class \fBThingUpdater\fP"
.br
.ti -1c
.RI "class \fBUpdater\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBReset\fP ()"
.br
.ti -1c
.RI "unsafe void \fBUpdate100ms\fP ()"
.br
.ti -1c
.RI "void \fBFixedUpdate\fP ()"
.br
.ti -1c
.RI "void \fBUpdate\fP ()"
.br
.ti -1c
.RI "string \fBGetText\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBGameUpdater\&.AreaUpdater\fP \fBarea\fP"
.br
.ti -1c
.RI "\fBGameUpdater\&.SurfaceUpdater\fP \fBsurface\fP"
.br
.ti -1c
.RI "\fBGameUpdater\&.FastSurfaceUpdater\fP \fBsurfaceFast\fP"
.br
.ti -1c
.RI "\fBGameUpdater\&.FireUpdater\fP \fBfire\fP"
.br
.ti -1c
.RI "\fBGameUpdater\&.CharaUpdater\fP \fBchara\fP"
.br
.ti -1c
.RI "\fBGameUpdater\&.ConditionUpdater\fP \fBcondition\fP"
.br
.ti -1c
.RI "\fBGameUpdater\&.ThingUpdater\fP \fBthing\fP"
.br
.ti -1c
.RI "\fBGameUpdater\&.SensorUpdater\fP \fBsensor\fP"
.br
.ti -1c
.RI "\fBRecipeUpdater\fP \fBrecipe\fP = new \fBRecipeUpdater\fP()"
.br
.ti -1c
.RI "\fBGameUpdater\&.Updater\fP[] \fBall\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static float \fBdelta\fP"
.br
.in -1c

Static Public Attributes inherited from \fBEClass\fP
.in +1c
.ti -1c
.RI "static \fBCore\fP \fBcore\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Static Public Member Functions inherited from \fBEClass\fP
.in +1c
.ti -1c
.RI "static int \fBrnd\fP (int a)"
.br
.ti -1c
.RI "static int \fBcurve\fP (int a, int start, int step, int rate=75)"
.br
.ti -1c
.RI "static int \fBrndHalf\fP (int a)"
.br
.ti -1c
.RI "static float \fBrndf\fP (float a)"
.br
.ti -1c
.RI "static int \fBrndSqrt\fP (int a)"
.br
.ti -1c
.RI "static void \fBWait\fP (float a, \fBCard\fP c)"
.br
.ti -1c
.RI "static void \fBWait\fP (float a, \fBPoint\fP p)"
.br
.ti -1c
.RI "static int \fBBigger\fP (int a, int b)"
.br
.ti -1c
.RI "static int \fBSmaller\fP (int a, int b)"
.br
.in -1c

Properties inherited from \fBEClass\fP
.in +1c
.ti -1c
.RI "static \fBGame\fP \fBgame\fP\fR [get]\fP"
.br
.ti -1c
.RI "static bool \fBAdvMode\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBPlayer\fP \fBplayer\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBChara\fP \fBpc\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBUI\fP \fBui\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBMap\fP \fB_map\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBZone\fP \fB_zone\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranchOrHomeBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFaction\fP \fBHome\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFaction\fP \fBWilds\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBScene\fP \fBscene\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBBaseGameScreen\fP \fBscreen\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameSetting\fP \fBsetting\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameData\fP \fBgamedata\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBColorProfile\fP \fBColors\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBWorld\fP \fBworld\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBsources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBeditorSources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static SoundManager \fBSound\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBCoreDebug\fP \fBdebug\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB7\fP of file \fBGameUpdater\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void GameUpdater\&.FixedUpdate ()"

.PP
Definition at line \fB89\fP of file \fBGameUpdater\&.cs\fP\&.
.SS "string GameUpdater\&.GetText ()"

.PP
Definition at line \fB218\fP of file \fBGameUpdater\&.cs\fP\&.
.SS "void GameUpdater\&.Reset ()"

.PP
Definition at line \fB10\fP of file \fBGameUpdater\&.cs\fP\&.
.SS "void GameUpdater\&.Update ()"

.PP
Definition at line \fB122\fP of file \fBGameUpdater\&.cs\fP\&.
.SS "unsafe void GameUpdater\&.Update100ms ()"

.PP
Definition at line \fB23\fP of file \fBGameUpdater\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBGameUpdater\&.Updater\fP [] GameUpdater\&.all"

.PP
Definition at line \fB274\fP of file \fBGameUpdater\&.cs\fP\&.
.SS "\fBGameUpdater\&.AreaUpdater\fP GameUpdater\&.area"

.PP
Definition at line \fB247\fP of file \fBGameUpdater\&.cs\fP\&.
.SS "\fBGameUpdater\&.CharaUpdater\fP GameUpdater\&.chara"

.PP
Definition at line \fB259\fP of file \fBGameUpdater\&.cs\fP\&.
.SS "\fBGameUpdater\&.ConditionUpdater\fP GameUpdater\&.condition"

.PP
Definition at line \fB262\fP of file \fBGameUpdater\&.cs\fP\&.
.SS "float GameUpdater\&.delta\fR [static]\fP"

.PP
Definition at line \fB244\fP of file \fBGameUpdater\&.cs\fP\&.
.SS "\fBGameUpdater\&.FireUpdater\fP GameUpdater\&.fire"

.PP
Definition at line \fB256\fP of file \fBGameUpdater\&.cs\fP\&.
.SS "\fBRecipeUpdater\fP GameUpdater\&.recipe = new \fBRecipeUpdater\fP()"

.PP
Definition at line \fB271\fP of file \fBGameUpdater\&.cs\fP\&.
.SS "\fBGameUpdater\&.SensorUpdater\fP GameUpdater\&.sensor"

.PP
Definition at line \fB268\fP of file \fBGameUpdater\&.cs\fP\&.
.SS "\fBGameUpdater\&.SurfaceUpdater\fP GameUpdater\&.surface"

.PP
Definition at line \fB250\fP of file \fBGameUpdater\&.cs\fP\&.
.SS "\fBGameUpdater\&.FastSurfaceUpdater\fP GameUpdater\&.surfaceFast"

.PP
Definition at line \fB253\fP of file \fBGameUpdater\&.cs\fP\&.
.SS "\fBGameUpdater\&.ThingUpdater\fP GameUpdater\&.thing"

.PP
Definition at line \fB265\fP of file \fBGameUpdater\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
