.TH "GameSetting.RenderSetting.UD_FogSetting" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GameSetting.RenderSetting.UD_FogSetting
.SH SYNOPSIS
.br
.PP
.PP
Inherits UDictionary< FogType, ScreenGradingProfile\&.Fog >\&.
.SH "Detailed Description"
.PP 
Definition at line \fB404\fP of file \fBGameSetting\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
