.TH "GameSetting.BalanceSetting" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GameSetting.BalanceSetting
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBdateRevive\fP"
.br
.ti -1c
.RI "int \fBdateRegenerateZone\fP"
.br
.ti -1c
.RI "int \fBdateExpireRandomMap\fP"
.br
.ti -1c
.RI "int \fBnumAdv\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB439\fP of file \fBGameSetting\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int GameSetting\&.BalanceSetting\&.dateExpireRandomMap"

.PP
Definition at line \fB448\fP of file \fBGameSetting\&.cs\fP\&.
.SS "int GameSetting\&.BalanceSetting\&.dateRegenerateZone"

.PP
Definition at line \fB445\fP of file \fBGameSetting\&.cs\fP\&.
.SS "int GameSetting\&.BalanceSetting\&.dateRevive"

.PP
Definition at line \fB442\fP of file \fBGameSetting\&.cs\fP\&.
.SS "int GameSetting\&.BalanceSetting\&.numAdv"

.PP
Definition at line \fB451\fP of file \fBGameSetting\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
