.TH "GameSetting.StartSetting" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GameSetting.StartSetting
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "List< \fBPrologue\fP > \fBprologues\fP"
.br
.ti -1c
.RI "List< \fBGameDifficulty\fP > \fBdifficulties\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB428\fP of file \fBGameSetting\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "List<\fBGameDifficulty\fP> GameSetting\&.StartSetting\&.difficulties"

.PP
Definition at line \fB434\fP of file \fBGameSetting\&.cs\fP\&.
.SS "List<\fBPrologue\fP> GameSetting\&.StartSetting\&.prologues"

.PP
Definition at line \fB431\fP of file \fBGameSetting\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
