.TH "Game" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Game
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBEClass\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBConfig\fP"
.br
.ti -1c
.RI "class \fBFlags\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBOnUpdate\fP ()"
.br
.ti -1c
.RI "void \fBOnLoad\fP ()"
.br
.ti -1c
.RI "void \fBOnGameInstantiated\fP ()"
.br
.ti -1c
.RI "void \fB_Create\fP ()"
.br
.ti -1c
.RI "void \fBStartNewGame\fP ()"
.br
.ti -1c
.RI "void \fBAddAdventurers\fP ()"
.br
.ti -1c
.RI "void \fBGotoTitle\fP (bool showDialog=true)"
.br
.ti -1c
.RI "void \fBQuit\fP ()"
.br
.ti -1c
.RI "void \fBSave\fP (bool isAutoSave=false, Action onComplete=null, bool silent=false)"
.br
.ti -1c
.RI "void \fBOnBeforeSave\fP ()"
.br
.ti -1c
.RI "void \fBKill\fP ()"
.br
.ti -1c
.RI "void \fBPause\fP (Action onUnpause=null)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static new void \fBWait\fP (float a, \fBPoint\fP p)"
.br
.ti -1c
.RI "static new void \fBWait\fP (float a, \fBCard\fP c)"
.br
.ti -1c
.RI "static void \fBWait\fP (float a)"
.br
.ti -1c
.RI "static void \fBLoad\fP (string slot)"
.br
.ti -1c
.RI "static void \fBCreate\fP (string _id=null)"
.br
.ti -1c
.RI "static void \fBOnBeforeInstantiate\fP ()"
.br
.in -1c

Static Public Member Functions inherited from \fBEClass\fP
.in +1c
.ti -1c
.RI "static int \fBrnd\fP (int a)"
.br
.ti -1c
.RI "static int \fBcurve\fP (int a, int start, int step, int rate=75)"
.br
.ti -1c
.RI "static int \fBrndHalf\fP (int a)"
.br
.ti -1c
.RI "static float \fBrndf\fP (float a)"
.br
.ti -1c
.RI "static int \fBrndSqrt\fP (int a)"
.br
.ti -1c
.RI "static void \fBWait\fP (float a, \fBCard\fP c)"
.br
.ti -1c
.RI "static void \fBWait\fP (float a, \fBPoint\fP p)"
.br
.ti -1c
.RI "static int \fBBigger\fP (int a, int b)"
.br
.ti -1c
.RI "static int \fBSmaller\fP (int a, int b)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBSpatialManager\fP \fBspatials\fP = new \fBSpatialManager\fP()"
.br
.ti -1c
.RI "\fBCardManager\fP \fBcards\fP = new \fBCardManager\fP()"
.br
.ti -1c
.RI "\fBReligionManager\fP \fBreligions\fP = new \fBReligionManager\fP()"
.br
.ti -1c
.RI "\fBFactionManager\fP \fBfactions\fP = new \fBFactionManager\fP()"
.br
.ti -1c
.RI "\fBDomainManager\fP \fBdomains\fP = new \fBDomainManager\fP()"
.br
.ti -1c
.RI "global::Version \fBversion\fP"
.br
.ti -1c
.RI "\fBPartyManager\fP \fBparties\fP = new \fBPartyManager\fP()"
.br
.ti -1c
.RI "new \fBWorld\fP \fBworld\fP"
.br
.ti -1c
.RI "new \fBPlayer\fP \fBplayer\fP = new \fBPlayer\fP()"
.br
.ti -1c
.RI "\fBQuestManager\fP \fBquests\fP = new \fBQuestManager\fP()"
.br
.ti -1c
.RI "\fBRelationManager\fP \fBrelations\fP = new \fBRelationManager\fP()"
.br
.ti -1c
.RI "\fBMsgLog\fP \fBlog\fP"
.br
.ti -1c
.RI "PCCUniformManager \fBuniforms\fP = new PCCUniformManager()"
.br
.ti -1c
.RI "\fBTeleportManager\fP \fBteleports\fP = new \fBTeleportManager\fP()"
.br
.ti -1c
.RI "int \fBseed\fP"
.br
.ti -1c
.RI "int \fBidPrologue\fP"
.br
.ti -1c
.RI "int \fBidDifficulty\fP"
.br
.ti -1c
.RI "int \fBdateScratch\fP"
.br
.ti -1c
.RI "\fBGame\&.Flags\fP \fBflags\fP = new \fBGame\&.Flags\fP()"
.br
.ti -1c
.RI "\fBGame\&.Config\fP \fBconfig\fP = new \fBGame\&.Config\fP()"
.br
.ti -1c
.RI "List< \fBThing\fP > \fBlostThings\fP = new List<\fBThing\fP>()"
.br
.ti -1c
.RI "int \fBgameSpeedIndex\fP = 1"
.br
.ti -1c
.RI "int \fBlastGameSpeedIndex\fP = 1"
.br
.ti -1c
.RI "int \fBsessionMin\fP"
.br
.ti -1c
.RI "int \fBcountLoadedMaps\fP"
.br
.ti -1c
.RI "int \fBsaveCount\fP"
.br
.ti -1c
.RI "float \fBtimeSinceStart\fP"
.br
.ti -1c
.RI "bool \fBisLoading\fP"
.br
.ti -1c
.RI "bool \fBisKilling\fP"
.br
.ti -1c
.RI "\fBGameBlueprint\fP \fBbp\fP"
.br
.ti -1c
.RI "\fBGameUpdater\fP \fBupdater\fP = new \fBGameUpdater\fP()"
.br
.ti -1c
.RI "\fBZone\fP \fBactiveZone\fP"
.br
.ti -1c
.RI "\fBZone\fP \fBlastActiveZone\fP"
.br
.ti -1c
.RI "Dictionary< string, \fBIGlobalValue\fP > \fBreferenceMap\fP = new Dictionary<string, \fBIGlobalValue\fP>()"
.br
.ti -1c
.RI "HashSet< Texture2D > \fBloadedTextures\fP = new HashSet<Texture2D>()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static \fBGame\fP \fBInstance\fP"
.br
.ti -1c
.RI "static float \fBwaitTimer\fP"
.br
.ti -1c
.RI "static string \fBid\fP"
.br
.ti -1c
.RI "static bool \fBisPaused\fP"
.br
.in -1c

Static Public Attributes inherited from \fBEClass\fP
.in +1c
.ti -1c
.RI "static \fBCore\fP \fBcore\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "static bool \fBIsWaiting\fP\fR [get]\fP"
.br
.ti -1c
.RI "\fBPrologue\fP \fBPrologue\fP\fR [get]\fP"
.br
.ti -1c
.RI "\fBGameDifficulty\fP \fBDifficulty\fP\fR [get]\fP"
.br
.ti -1c
.RI "bool \fBUseGrid\fP\fR [get]\fP"
.br
.ti -1c
.RI "bool \fBaltUI\fP\fR [get]\fP"
.br
.ti -1c
.RI "bool \fBaltInv\fP\fR [get]\fP"
.br
.ti -1c
.RI "bool \fBaltCraft\fP\fR [get]\fP"
.br
.ti -1c
.RI "bool \fBaltAbility\fP\fR [get]\fP"
.br
.ti -1c
.RI "\fBZone\fP \fBStartZone\fP\fR [get]\fP"
.br
.in -1c

Properties inherited from \fBEClass\fP
.in +1c
.ti -1c
.RI "static \fBGame\fP \fBgame\fP\fR [get]\fP"
.br
.ti -1c
.RI "static bool \fBAdvMode\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBPlayer\fP \fBplayer\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBChara\fP \fBpc\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBUI\fP \fBui\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBMap\fP \fB_map\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBZone\fP \fB_zone\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranchOrHomeBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFaction\fP \fBHome\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFaction\fP \fBWilds\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBScene\fP \fBscene\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBBaseGameScreen\fP \fBscreen\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameSetting\fP \fBsetting\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameData\fP \fBgamedata\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBColorProfile\fP \fBColors\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBWorld\fP \fBworld\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBsources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBeditorSources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static SoundManager \fBSound\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBCoreDebug\fP \fBdebug\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB9\fP of file \fBGame\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Game\&._Create ()"

.PP
Definition at line \fB409\fP of file \fBGame\&.cs\fP\&.
.SS "void Game\&.AddAdventurers ()"

.PP
Definition at line \fB568\fP of file \fBGame\&.cs\fP\&.
.SS "static void Game\&.Create (string _id = \fRnull\fP)\fR [static]\fP"

.PP
Definition at line \fB365\fP of file \fBGame\&.cs\fP\&.
.SS "void Game\&.GotoTitle (bool showDialog = \fRtrue\fP)"

.PP
Definition at line \fB606\fP of file \fBGame\&.cs\fP\&.
.SS "void Game\&.Kill ()"

.PP
Definition at line \fB697\fP of file \fBGame\&.cs\fP\&.
.SS "static void Game\&.Load (string slot)\fR [static]\fP"

.PP
Definition at line \fB140\fP of file \fBGame\&.cs\fP\&.
.SS "static void Game\&.OnBeforeInstantiate ()\fR [static]\fP"

.PP
Definition at line \fB376\fP of file \fBGame\&.cs\fP\&.
.SS "void Game\&.OnBeforeSave ()"

.PP
Definition at line \fB682\fP of file \fBGame\&.cs\fP\&.
.SS "void Game\&.OnGameInstantiated ()"

.PP
Definition at line \fB382\fP of file \fBGame\&.cs\fP\&.
.SS "void Game\&.OnLoad ()"

.PP
Definition at line \fB170\fP of file \fBGame\&.cs\fP\&.
.SS "void Game\&.OnUpdate ()"

.PP
Definition at line \fB127\fP of file \fBGame\&.cs\fP\&.
.SS "void Game\&.Pause (Action onUnpause = \fRnull\fP)"

.PP
Definition at line \fB720\fP of file \fBGame\&.cs\fP\&.
.SS "void Game\&.Quit ()"

.PP
Definition at line \fB623\fP of file \fBGame\&.cs\fP\&.
.SS "void Game\&.Save (bool isAutoSave = \fRfalse\fP, Action onComplete = \fRnull\fP, bool silent = \fRfalse\fP)"

.PP
Definition at line \fB635\fP of file \fBGame\&.cs\fP\&.
.SS "void Game\&.StartNewGame ()"

.PP
Definition at line \fB439\fP of file \fBGame\&.cs\fP\&.
.SS "static void Game\&.Wait (float a)\fR [static]\fP"

.PP
Definition at line \fB41\fP of file \fBGame\&.cs\fP\&.
.SS "static new void Game\&.Wait (float a, \fBCard\fP c)\fR [static]\fP"

.PP
Definition at line \fB31\fP of file \fBGame\&.cs\fP\&.
.SS "static new void Game\&.Wait (float a, \fBPoint\fP p)\fR [static]\fP"

.PP
Definition at line \fB22\fP of file \fBGame\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBZone\fP Game\&.activeZone"

.PP
Definition at line \fB895\fP of file \fBGame\&.cs\fP\&.
.SS "\fBGameBlueprint\fP Game\&.bp"

.PP
Definition at line \fB889\fP of file \fBGame\&.cs\fP\&.
.SS "\fBCardManager\fP Game\&.cards = new \fBCardManager\fP()"

.PP
Definition at line \fB783\fP of file \fBGame\&.cs\fP\&.
.SS "\fBGame\&.Config\fP Game\&.config = new \fBGame\&.Config\fP()"

.PP
Definition at line \fB858\fP of file \fBGame\&.cs\fP\&.
.SS "int Game\&.countLoadedMaps"

.PP
Definition at line \fB874\fP of file \fBGame\&.cs\fP\&.
.SS "int Game\&.dateScratch"

.PP
Definition at line \fB850\fP of file \fBGame\&.cs\fP\&.
.SS "\fBDomainManager\fP Game\&.domains = new \fBDomainManager\fP()"

.PP
Definition at line \fB795\fP of file \fBGame\&.cs\fP\&.
.SS "\fBFactionManager\fP Game\&.factions = new \fBFactionManager\fP()"

.PP
Definition at line \fB791\fP of file \fBGame\&.cs\fP\&.
.SS "\fBGame\&.Flags\fP Game\&.flags = new \fBGame\&.Flags\fP()"

.PP
Definition at line \fB854\fP of file \fBGame\&.cs\fP\&.
.SS "int Game\&.gameSpeedIndex = 1"

.PP
Definition at line \fB865\fP of file \fBGame\&.cs\fP\&.
.SS "string Game\&.id\fR [static]\fP"

.PP
Definition at line \fB772\fP of file \fBGame\&.cs\fP\&.
.SS "int Game\&.idDifficulty"

.PP
Definition at line \fB846\fP of file \fBGame\&.cs\fP\&.
.SS "int Game\&.idPrologue"

.PP
Definition at line \fB842\fP of file \fBGame\&.cs\fP\&.
.SS "\fBGame\fP Game\&.Instance\fR [static]\fP"

.PP
Definition at line \fB766\fP of file \fBGame\&.cs\fP\&.
.SS "bool Game\&.isKilling"

.PP
Definition at line \fB886\fP of file \fBGame\&.cs\fP\&.
.SS "bool Game\&.isLoading"

.PP
Definition at line \fB883\fP of file \fBGame\&.cs\fP\&.
.SS "bool Game\&.isPaused\fR [static]\fP"

.PP
Definition at line \fB775\fP of file \fBGame\&.cs\fP\&.
.SS "\fBZone\fP Game\&.lastActiveZone"

.PP
Definition at line \fB898\fP of file \fBGame\&.cs\fP\&.
.SS "int Game\&.lastGameSpeedIndex = 1"

.PP
Definition at line \fB868\fP of file \fBGame\&.cs\fP\&.
.SS "HashSet<Texture2D> Game\&.loadedTextures = new HashSet<Texture2D>()"

.PP
Definition at line \fB904\fP of file \fBGame\&.cs\fP\&.
.SS "\fBMsgLog\fP Game\&.log"
\fBInitial value:\fP
.nf
= new MsgLog
    {
        id = "log"
    }
.PP
.fi

.PP
Definition at line \fB823\fP of file \fBGame\&.cs\fP\&.
.SS "List<\fBThing\fP> Game\&.lostThings = new List<\fBThing\fP>()"

.PP
Definition at line \fB862\fP of file \fBGame\&.cs\fP\&.
.SS "\fBPartyManager\fP Game\&.parties = new \fBPartyManager\fP()"

.PP
Definition at line \fB803\fP of file \fBGame\&.cs\fP\&.
.SS "new \fBPlayer\fP Game\&.player = new \fBPlayer\fP()"

.PP
Definition at line \fB811\fP of file \fBGame\&.cs\fP\&.
.SS "\fBQuestManager\fP Game\&.quests = new \fBQuestManager\fP()"

.PP
Definition at line \fB815\fP of file \fBGame\&.cs\fP\&.
.SS "Dictionary<string, \fBIGlobalValue\fP> Game\&.referenceMap = new Dictionary<string, \fBIGlobalValue\fP>()"

.PP
Definition at line \fB901\fP of file \fBGame\&.cs\fP\&.
.SS "\fBRelationManager\fP Game\&.relations = new \fBRelationManager\fP()"

.PP
Definition at line \fB819\fP of file \fBGame\&.cs\fP\&.
.SS "\fBReligionManager\fP Game\&.religions = new \fBReligionManager\fP()"

.PP
Definition at line \fB787\fP of file \fBGame\&.cs\fP\&.
.SS "int Game\&.saveCount"

.PP
Definition at line \fB877\fP of file \fBGame\&.cs\fP\&.
.SS "int Game\&.seed"

.PP
Definition at line \fB838\fP of file \fBGame\&.cs\fP\&.
.SS "int Game\&.sessionMin"

.PP
Definition at line \fB871\fP of file \fBGame\&.cs\fP\&.
.SS "\fBSpatialManager\fP Game\&.spatials = new \fBSpatialManager\fP()"

.PP
Definition at line \fB779\fP of file \fBGame\&.cs\fP\&.
.SS "\fBTeleportManager\fP Game\&.teleports = new \fBTeleportManager\fP()"

.PP
Definition at line \fB834\fP of file \fBGame\&.cs\fP\&.
.SS "float Game\&.timeSinceStart"

.PP
Definition at line \fB880\fP of file \fBGame\&.cs\fP\&.
.SS "PCCUniformManager Game\&.uniforms = new PCCUniformManager()"

.PP
Definition at line \fB830\fP of file \fBGame\&.cs\fP\&.
.SS "\fBGameUpdater\fP Game\&.updater = new \fBGameUpdater\fP()"

.PP
Definition at line \fB892\fP of file \fBGame\&.cs\fP\&.
.SS "global\&.Version Game\&.version"

.PP
Definition at line \fB799\fP of file \fBGame\&.cs\fP\&.
.SS "float Game\&.waitTimer\fR [static]\fP"

.PP
Definition at line \fB769\fP of file \fBGame\&.cs\fP\&.
.SS "new \fBWorld\fP Game\&.world"

.PP
Definition at line \fB807\fP of file \fBGame\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "bool Game\&.altAbility\fR [get]\fP"

.PP
Definition at line \fB108\fP of file \fBGame\&.cs\fP\&.
.SS "bool Game\&.altCraft\fR [get]\fP"

.PP
Definition at line \fB98\fP of file \fBGame\&.cs\fP\&.
.SS "bool Game\&.altInv\fR [get]\fP"

.PP
Definition at line \fB88\fP of file \fBGame\&.cs\fP\&.
.SS "bool Game\&.altUI\fR [get]\fP"

.PP
Definition at line \fB78\fP of file \fBGame\&.cs\fP\&.
.SS "\fBGameDifficulty\fP Game\&.Difficulty\fR [get]\fP"

.PP
Definition at line \fB58\fP of file \fBGame\&.cs\fP\&.
.SS "bool Game\&.IsWaiting\fR [static]\fP, \fR [get]\fP"

.PP
Definition at line \fB13\fP of file \fBGame\&.cs\fP\&.
.SS "\fBPrologue\fP Game\&.Prologue\fR [get]\fP"

.PP
Definition at line \fB48\fP of file \fBGame\&.cs\fP\&.
.SS "\fBZone\fP Game\&.StartZone\fR [get]\fP"

.PP
Definition at line \fB118\fP of file \fBGame\&.cs\fP\&.
.SS "bool Game\&.UseGrid\fR [get]\fP"

.PP
Definition at line \fB68\fP of file \fBGame\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
