.TH "GameData" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GameData
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBEScriptable\fP\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "List< \fBAffinity\fP > \fBaffinities\fP"
.br
.ti -1c
.RI "List< \fBShrineData\fP > \fBshrines\fP"
.br
.ti -1c
.RI "List< \fBGodStatueData\fP > \fBgodStatues\fP"
.br
.ti -1c
.RI "List< \fBGuildRankData\fP > \fBguildRanks\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Static Public Member Functions inherited from \fBEScriptable\fP
.in +1c
.ti -1c
.RI "static int \fBrnd\fP (int a)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB5\fP of file \fBGameData\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "List<\fBAffinity\fP> GameData\&.affinities"

.PP
Definition at line \fB8\fP of file \fBGameData\&.cs\fP\&.
.SS "List<\fBGodStatueData\fP> GameData\&.godStatues"

.PP
Definition at line \fB14\fP of file \fBGameData\&.cs\fP\&.
.SS "List<\fBGuildRankData\fP> GameData\&.guildRanks"

.PP
Definition at line \fB17\fP of file \fBGameData\&.cs\fP\&.
.SS "List<\fBShrineData\fP> GameData\&.shrines"

.PP
Definition at line \fB11\fP of file \fBGameData\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
