.TH "GameSetting" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GameSetting
.SH SYNOPSIS
.br
.PP
.PP
Inherits ScriptableObject\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAudioSetting\fP"
.br
.ti -1c
.RI "class \fBBalanceSetting\fP"
.br
.ti -1c
.RI "class \fBEffectData\fP"
.br
.ti -1c
.RI "class \fBEffectSetting\fP"
.br
.ti -1c
.RI "class \fBGenSetting\fP"
.br
.ti -1c
.RI "class \fBPassSetting\fP"
.br
.ti -1c
.RI "class \fBRenderSetting\fP"
.br
.ti -1c
.RI "class \fBStartSetting\fP"
.br
.ti -1c
.RI "class \fBTransData\fP"
.br
.ti -1c
.RI "class \fBUISetting\fP"
.br
.ti -1c
.RI "class \fBWeatherSetting\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBApplyConfig\fP ()"
.br
.ti -1c
.RI "void \fBCopyColors\fP ()"
.br
.ti -1c
.RI "void \fBInit\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBGameSetting\&.AudioSetting\fP \fBaudio\fP"
.br
.ti -1c
.RI "\fBGameSetting\&.EffectSetting\fP \fBeffect\fP"
.br
.ti -1c
.RI "\fBGameSetting\&.RenderSetting\fP \fBrender\fP"
.br
.ti -1c
.RI "\fBGameSetting\&.PassSetting\fP \fBpass\fP"
.br
.ti -1c
.RI "\fBGameSetting\&.StartSetting\fP \fBstart\fP"
.br
.ti -1c
.RI "\fBGameSetting\&.UISetting\fP \fBui\fP"
.br
.ti -1c
.RI "\fBGameSetting\&.BalanceSetting\fP \fBbalance\fP"
.br
.ti -1c
.RI "\fBGameSetting\&.GenSetting\fP \fBgen\fP"
.br
.ti -1c
.RI "\fBGameSetting\&.WeatherSetting\fP \fBweather\fP"
.br
.ti -1c
.RI "\fBUD_String_ElementRef\fP \fBelements\fP"
.br
.ti -1c
.RI "int \fBminsPerRegionMove\fP"
.br
.ti -1c
.RI "float \fBsecsPerHour\fP"
.br
.ti -1c
.RI "float \fBdayRatioMod\fP"
.br
.ti -1c
.RI "float \fBfovPower\fP"
.br
.ti -1c
.RI "float \fBfovPowerChara\fP"
.br
.ti -1c
.RI "float \fBdefaultActPace\fP"
.br
.ti -1c
.RI "float \fBdefaultTurbo\fP"
.br
.ti -1c
.RI "int \fBmaxGenHeight\fP"
.br
.ti -1c
.RI "bool \fBtoolConsumeHP\fP"
.br
.ti -1c
.RI "int \fBdefaultMapSize\fP"
.br
.ti -1c
.RI "\fBCoreConfig\fP \fBconfig\fP"
.br
.ti -1c
.RI "Dictionary< string, Vector3 > \fBdictEquipOffsets\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB6\fP of file \fBGameSetting\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void GameSetting\&.ApplyConfig ()"

.PP
Definition at line \fB9\fP of file \fBGameSetting\&.cs\fP\&.
.SS "void GameSetting\&.CopyColors ()"

.PP
Definition at line \fB16\fP of file \fBGameSetting\&.cs\fP\&.
.SS "void GameSetting\&.Init ()"

.PP
Definition at line \fB22\fP of file \fBGameSetting\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBGameSetting\&.AudioSetting\fP GameSetting\&.audio"

.PP
Definition at line \fB28\fP of file \fBGameSetting\&.cs\fP\&.
.SS "\fBGameSetting\&.BalanceSetting\fP GameSetting\&.balance"

.PP
Definition at line \fB46\fP of file \fBGameSetting\&.cs\fP\&.
.SS "\fBCoreConfig\fP GameSetting\&.config"

.PP
Definition at line \fB88\fP of file \fBGameSetting\&.cs\fP\&.
.SS "float GameSetting\&.dayRatioMod"

.PP
Definition at line \fB64\fP of file \fBGameSetting\&.cs\fP\&.
.SS "float GameSetting\&.defaultActPace"

.PP
Definition at line \fB73\fP of file \fBGameSetting\&.cs\fP\&.
.SS "int GameSetting\&.defaultMapSize"

.PP
Definition at line \fB85\fP of file \fBGameSetting\&.cs\fP\&.
.SS "float GameSetting\&.defaultTurbo"

.PP
Definition at line \fB76\fP of file \fBGameSetting\&.cs\fP\&.
.SS "Dictionary<string, Vector3> GameSetting\&.dictEquipOffsets"

.PP
Definition at line \fB92\fP of file \fBGameSetting\&.cs\fP\&.
.SS "\fBGameSetting\&.EffectSetting\fP GameSetting\&.effect"

.PP
Definition at line \fB31\fP of file \fBGameSetting\&.cs\fP\&.
.SS "\fBUD_String_ElementRef\fP GameSetting\&.elements"

.PP
Definition at line \fB55\fP of file \fBGameSetting\&.cs\fP\&.
.SS "float GameSetting\&.fovPower"

.PP
Definition at line \fB67\fP of file \fBGameSetting\&.cs\fP\&.
.SS "float GameSetting\&.fovPowerChara"

.PP
Definition at line \fB70\fP of file \fBGameSetting\&.cs\fP\&.
.SS "\fBGameSetting\&.GenSetting\fP GameSetting\&.gen"

.PP
Definition at line \fB49\fP of file \fBGameSetting\&.cs\fP\&.
.SS "int GameSetting\&.maxGenHeight"

.PP
Definition at line \fB79\fP of file \fBGameSetting\&.cs\fP\&.
.SS "int GameSetting\&.minsPerRegionMove"

.PP
Definition at line \fB58\fP of file \fBGameSetting\&.cs\fP\&.
.SS "\fBGameSetting\&.PassSetting\fP GameSetting\&.pass"

.PP
Definition at line \fB37\fP of file \fBGameSetting\&.cs\fP\&.
.SS "\fBGameSetting\&.RenderSetting\fP GameSetting\&.render"

.PP
Definition at line \fB34\fP of file \fBGameSetting\&.cs\fP\&.
.SS "float GameSetting\&.secsPerHour"

.PP
Definition at line \fB61\fP of file \fBGameSetting\&.cs\fP\&.
.SS "\fBGameSetting\&.StartSetting\fP GameSetting\&.start"

.PP
Definition at line \fB40\fP of file \fBGameSetting\&.cs\fP\&.
.SS "bool GameSetting\&.toolConsumeHP"

.PP
Definition at line \fB82\fP of file \fBGameSetting\&.cs\fP\&.
.SS "\fBGameSetting\&.UISetting\fP GameSetting\&.ui"

.PP
Definition at line \fB43\fP of file \fBGameSetting\&.cs\fP\&.
.SS "\fBGameSetting\&.WeatherSetting\fP GameSetting\&.weather"

.PP
Definition at line \fB52\fP of file \fBGameSetting\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
