.TH "GameUpdater.Updater" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GameUpdater.Updater
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBEClass\fP\&.
.PP
Inherited by \fBGameUpdater\&.AreaUpdater\fP, \fBGameUpdater\&.CharaUpdater\fP, \fBGameUpdater\&.LogicUpdater\fP, \fBGameUpdater\&.SensorUpdater\fP, \fBGameUpdater\&.SurfaceUpdater\fP, and \fBGameUpdater\&.ThingUpdater\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBFixedUpdate\fP ()"
.br
.ti -1c
.RI "void \fBSetUpdatesPerFrame\fP (int _maxcount, float _duration)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBindex\fP"
.br
.ti -1c
.RI "int \fBupdatesPerFrame\fP"
.br
.ti -1c
.RI "int \fBmaxCount\fP"
.br
.ti -1c
.RI "float \fBduration\fP = 1f"
.br
.ti -1c
.RI "float \fB_updatesPerFrame\fP"
.br
.ti -1c
.RI "\fBPoint\fP \fBpos\fP = new \fBPoint\fP()"
.br
.in -1c
.SS "Additional Inherited Members"


Static Public Member Functions inherited from \fBEClass\fP
.in +1c
.ti -1c
.RI "static int \fBrnd\fP (int a)"
.br
.ti -1c
.RI "static int \fBcurve\fP (int a, int start, int step, int rate=75)"
.br
.ti -1c
.RI "static int \fBrndHalf\fP (int a)"
.br
.ti -1c
.RI "static float \fBrndf\fP (float a)"
.br
.ti -1c
.RI "static int \fBrndSqrt\fP (int a)"
.br
.ti -1c
.RI "static void \fBWait\fP (float a, \fBCard\fP c)"
.br
.ti -1c
.RI "static void \fBWait\fP (float a, \fBPoint\fP p)"
.br
.ti -1c
.RI "static int \fBBigger\fP (int a, int b)"
.br
.ti -1c
.RI "static int \fBSmaller\fP (int a, int b)"
.br
.in -1c

Static Public Attributes inherited from \fBEClass\fP
.in +1c
.ti -1c
.RI "static \fBCore\fP \fBcore\fP"
.br
.in -1c

Properties inherited from \fBEClass\fP
.in +1c
.ti -1c
.RI "static \fBGame\fP \fBgame\fP\fR [get]\fP"
.br
.ti -1c
.RI "static bool \fBAdvMode\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBPlayer\fP \fBplayer\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBChara\fP \fBpc\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBUI\fP \fBui\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBMap\fP \fB_map\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBZone\fP \fB_zone\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranchOrHomeBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFaction\fP \fBHome\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFaction\fP \fBWilds\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBScene\fP \fBscene\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBBaseGameScreen\fP \fBscreen\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameSetting\fP \fBsetting\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameData\fP \fBgamedata\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBColorProfile\fP \fBColors\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBWorld\fP \fBworld\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBsources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBeditorSources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static SoundManager \fBSound\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBCoreDebug\fP \fBdebug\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB289\fP of file \fBGameUpdater\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual void GameUpdater\&.Updater\&.FixedUpdate ()\fR [virtual]\fP"

.PP
Definition at line \fB292\fP of file \fBGameUpdater\&.cs\fP\&.
.SS "void GameUpdater\&.Updater\&.SetUpdatesPerFrame (int _maxcount, float _duration)"

.PP
Definition at line \fB297\fP of file \fBGameUpdater\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "float GameUpdater\&.Updater\&._updatesPerFrame"

.PP
Definition at line \fB324\fP of file \fBGameUpdater\&.cs\fP\&.
.SS "float GameUpdater\&.Updater\&.duration = 1f"

.PP
Definition at line \fB321\fP of file \fBGameUpdater\&.cs\fP\&.
.SS "int GameUpdater\&.Updater\&.index"

.PP
Definition at line \fB312\fP of file \fBGameUpdater\&.cs\fP\&.
.SS "int GameUpdater\&.Updater\&.maxCount"

.PP
Definition at line \fB318\fP of file \fBGameUpdater\&.cs\fP\&.
.SS "\fBPoint\fP GameUpdater\&.Updater\&.pos = new \fBPoint\fP()"

.PP
Definition at line \fB327\fP of file \fBGameUpdater\&.cs\fP\&.
.SS "int GameUpdater\&.Updater\&.updatesPerFrame"

.PP
Definition at line \fB315\fP of file \fBGameUpdater\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
