.TH "GameSetting.RenderSetting.ActorSetting" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GameSetting.RenderSetting.ActorSetting
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Vector2 \fBpccExtent\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB373\fP of file \fBGameSetting\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "Vector2 GameSetting\&.RenderSetting\&.ActorSetting\&.pccExtent"

.PP
Definition at line \fB376\fP of file \fBGameSetting\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
