.TH "GameSetting.EffectData" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GameSetting.EffectData
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBnum\fP"
.br
.ti -1c
.RI "float \fBdelay\fP"
.br
.ti -1c
.RI "string \fBidEffect\fP"
.br
.ti -1c
.RI "string \fBidSound\fP"
.br
.ti -1c
.RI "Sprite \fBsprite\fP"
.br
.ti -1c
.RI "bool \fBeject\fP"
.br
.ti -1c
.RI "Vector2 \fBfirePos\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB483\fP of file \fBGameSetting\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "float GameSetting\&.EffectData\&.delay"

.PP
Definition at line \fB489\fP of file \fBGameSetting\&.cs\fP\&.
.SS "bool GameSetting\&.EffectData\&.eject"

.PP
Definition at line \fB501\fP of file \fBGameSetting\&.cs\fP\&.
.SS "Vector2 GameSetting\&.EffectData\&.firePos"

.PP
Definition at line \fB504\fP of file \fBGameSetting\&.cs\fP\&.
.SS "string GameSetting\&.EffectData\&.idEffect"

.PP
Definition at line \fB492\fP of file \fBGameSetting\&.cs\fP\&.
.SS "string GameSetting\&.EffectData\&.idSound"

.PP
Definition at line \fB495\fP of file \fBGameSetting\&.cs\fP\&.
.SS "int GameSetting\&.EffectData\&.num"

.PP
Definition at line \fB486\fP of file \fBGameSetting\&.cs\fP\&.
.SS "Sprite GameSetting\&.EffectData\&.sprite"

.PP
Definition at line \fB498\fP of file \fBGameSetting\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
