.TH "GameSetting.WeatherSetting" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GameSetting.WeatherSetting
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBsplashCount\fP"
.br
.ti -1c
.RI "float \fBthunerInterval\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB456\fP of file \fBGameSetting\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int GameSetting\&.WeatherSetting\&.splashCount"

.PP
Definition at line \fB459\fP of file \fBGameSetting\&.cs\fP\&.
.SS "float GameSetting\&.WeatherSetting\&.thunerInterval"

.PP
Definition at line \fB462\fP of file \fBGameSetting\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
