.TH "GameSetting.PassSetting" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GameSetting.PassSetting
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBSubPassData\fP \fBsubDfault\fP"
.br
.ti -1c
.RI "\fBSubPassData\fP \fBsubDead\fP"
.br
.ti -1c
.RI "\fBSubPassData\fP \fBsubDeadPCC\fP"
.br
.ti -1c
.RI "\fBSubPassData\fP \fBsubCrate\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB411\fP of file \fBGameSetting\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBSubPassData\fP GameSetting\&.PassSetting\&.subCrate"

.PP
Definition at line \fB423\fP of file \fBGameSetting\&.cs\fP\&.
.SS "\fBSubPassData\fP GameSetting\&.PassSetting\&.subDead"

.PP
Definition at line \fB417\fP of file \fBGameSetting\&.cs\fP\&.
.SS "\fBSubPassData\fP GameSetting\&.PassSetting\&.subDeadPCC"

.PP
Definition at line \fB420\fP of file \fBGameSetting\&.cs\fP\&.
.SS "\fBSubPassData\fP GameSetting\&.PassSetting\&.subDfault"

.PP
Definition at line \fB414\fP of file \fBGameSetting\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
