.TH "GameSetting.RenderSetting.AnimeSetting" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GameSetting.RenderSetting.AnimeSetting
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int[] \fBanimeStep\fP"
.br
.ti -1c
.RI "int[] \fBanimeStepPC\fP"
.br
.ti -1c
.RI "float \fBidleTime\fP"
.br
.ti -1c
.RI "float \fBfixedMove\fP"
.br
.ti -1c
.RI "float \fBanimeExtraTime\fP"
.br
.ti -1c
.RI "float \fBanimeExtraTimeParty\fP"
.br
.ti -1c
.RI "float \fBnextFrameInterval\fP"
.br
.ti -1c
.RI "float \fBslowSpeed\fP"
.br
.ti -1c
.RI "float \fBhopStrength\fP"
.br
.ti -1c
.RI "float \fBfix1\fP"
.br
.ti -1c
.RI "float \fBfix2\fP"
.br
.ti -1c
.RI "float \fBfix3\fP"
.br
.ti -1c
.RI "float \fBfix4\fP"
.br
.ti -1c
.RI "float \fBdestRadius\fP"
.br
.ti -1c
.RI "float \fBdiagonalSpeed\fP"
.br
.ti -1c
.RI "float \fBmaxProgressMod\fP"
.br
.ti -1c
.RI "float \fBregionSpeed\fP"
.br
.ti -1c
.RI "int \fBheightLimit\fP = 80"
.br
.ti -1c
.RI "AnimationCurve \fBhop\fP"
.br
.ti -1c
.RI "AnimationCurve \fBhopHuman\fP"
.br
.ti -1c
.RI "AnimationCurve \fBgradientZForward\fP"
.br
.ti -1c
.RI "AnimationCurve \fBgradientZBack\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB282\fP of file \fBGameSetting\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "float GameSetting\&.RenderSetting\&.AnimeSetting\&.animeExtraTime"

.PP
Definition at line \fB297\fP of file \fBGameSetting\&.cs\fP\&.
.SS "float GameSetting\&.RenderSetting\&.AnimeSetting\&.animeExtraTimeParty"

.PP
Definition at line \fB300\fP of file \fBGameSetting\&.cs\fP\&.
.SS "int [] GameSetting\&.RenderSetting\&.AnimeSetting\&.animeStep"

.PP
Definition at line \fB285\fP of file \fBGameSetting\&.cs\fP\&.
.SS "int [] GameSetting\&.RenderSetting\&.AnimeSetting\&.animeStepPC"

.PP
Definition at line \fB288\fP of file \fBGameSetting\&.cs\fP\&.
.SS "float GameSetting\&.RenderSetting\&.AnimeSetting\&.destRadius"

.PP
Definition at line \fB324\fP of file \fBGameSetting\&.cs\fP\&.
.SS "float GameSetting\&.RenderSetting\&.AnimeSetting\&.diagonalSpeed"

.PP
Definition at line \fB327\fP of file \fBGameSetting\&.cs\fP\&.
.SS "float GameSetting\&.RenderSetting\&.AnimeSetting\&.fix1"

.PP
Definition at line \fB312\fP of file \fBGameSetting\&.cs\fP\&.
.SS "float GameSetting\&.RenderSetting\&.AnimeSetting\&.fix2"

.PP
Definition at line \fB315\fP of file \fBGameSetting\&.cs\fP\&.
.SS "float GameSetting\&.RenderSetting\&.AnimeSetting\&.fix3"

.PP
Definition at line \fB318\fP of file \fBGameSetting\&.cs\fP\&.
.SS "float GameSetting\&.RenderSetting\&.AnimeSetting\&.fix4"

.PP
Definition at line \fB321\fP of file \fBGameSetting\&.cs\fP\&.
.SS "float GameSetting\&.RenderSetting\&.AnimeSetting\&.fixedMove"

.PP
Definition at line \fB294\fP of file \fBGameSetting\&.cs\fP\&.
.SS "AnimationCurve GameSetting\&.RenderSetting\&.AnimeSetting\&.gradientZBack"

.PP
Definition at line \fB348\fP of file \fBGameSetting\&.cs\fP\&.
.SS "AnimationCurve GameSetting\&.RenderSetting\&.AnimeSetting\&.gradientZForward"

.PP
Definition at line \fB345\fP of file \fBGameSetting\&.cs\fP\&.
.SS "int GameSetting\&.RenderSetting\&.AnimeSetting\&.heightLimit = 80"

.PP
Definition at line \fB336\fP of file \fBGameSetting\&.cs\fP\&.
.SS "AnimationCurve GameSetting\&.RenderSetting\&.AnimeSetting\&.hop"

.PP
Definition at line \fB339\fP of file \fBGameSetting\&.cs\fP\&.
.SS "AnimationCurve GameSetting\&.RenderSetting\&.AnimeSetting\&.hopHuman"

.PP
Definition at line \fB342\fP of file \fBGameSetting\&.cs\fP\&.
.SS "float GameSetting\&.RenderSetting\&.AnimeSetting\&.hopStrength"

.PP
Definition at line \fB309\fP of file \fBGameSetting\&.cs\fP\&.
.SS "float GameSetting\&.RenderSetting\&.AnimeSetting\&.idleTime"

.PP
Definition at line \fB291\fP of file \fBGameSetting\&.cs\fP\&.
.SS "float GameSetting\&.RenderSetting\&.AnimeSetting\&.maxProgressMod"

.PP
Definition at line \fB330\fP of file \fBGameSetting\&.cs\fP\&.
.SS "float GameSetting\&.RenderSetting\&.AnimeSetting\&.nextFrameInterval"

.PP
Definition at line \fB303\fP of file \fBGameSetting\&.cs\fP\&.
.SS "float GameSetting\&.RenderSetting\&.AnimeSetting\&.regionSpeed"

.PP
Definition at line \fB333\fP of file \fBGameSetting\&.cs\fP\&.
.SS "float GameSetting\&.RenderSetting\&.AnimeSetting\&.slowSpeed"

.PP
Definition at line \fB306\fP of file \fBGameSetting\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
