.TH "GameSetting.EffectSetting" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GameSetting.EffectSetting
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBUD_String_EffectData\fP \fBguns\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB475\fP of file \fBGameSetting\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBUD_String_EffectData\fP GameSetting\&.EffectSetting\&.guns"

.PP
Definition at line \fB478\fP of file \fBGameSetting\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
