.TH "GoalCombat.ItemAbility" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GoalCombat.ItemAbility
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBAct\fP \fBact\fP"
.br
.ti -1c
.RI "int \fBpriority\fP"
.br
.ti -1c
.RI "int \fBpriorityMod\fP"
.br
.ti -1c
.RI "int \fBchance\fP"
.br
.ti -1c
.RI "\fBChara\fP \fBtg\fP"
.br
.ti -1c
.RI "bool \fBpt\fP"
.br
.ti -1c
.RI "bool \fBaiPt\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB1093\fP of file \fBGoalCombat\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBAct\fP GoalCombat\&.ItemAbility\&.act"

.PP
Definition at line \fB1096\fP of file \fBGoalCombat\&.cs\fP\&.
.SS "bool GoalCombat\&.ItemAbility\&.aiPt"

.PP
Definition at line \fB1114\fP of file \fBGoalCombat\&.cs\fP\&.
.SS "int GoalCombat\&.ItemAbility\&.chance"

.PP
Definition at line \fB1105\fP of file \fBGoalCombat\&.cs\fP\&.
.SS "int GoalCombat\&.ItemAbility\&.priority"

.PP
Definition at line \fB1099\fP of file \fBGoalCombat\&.cs\fP\&.
.SS "int GoalCombat\&.ItemAbility\&.priorityMod"

.PP
Definition at line \fB1102\fP of file \fBGoalCombat\&.cs\fP\&.
.SS "bool GoalCombat\&.ItemAbility\&.pt"

.PP
Definition at line \fB1111\fP of file \fBGoalCombat\&.cs\fP\&.
.SS "\fBChara\fP GoalCombat\&.ItemAbility\&.tg"

.PP
Definition at line \fB1108\fP of file \fBGoalCombat\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
