.TH "GrowSystem.Stage" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GrowSystem.Stage
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetTile\fP (int _tile)"
.br
.ti -1c
.RI "void \fBSetTile\fP (int tileIdx, params int[] _tiles)"
.br
.ti -1c
.RI "int \fBConvert\fP (int tile)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int[] \fBtiles\fP"
.br
.ti -1c
.RI "int \fBidx\fP"
.br
.ti -1c
.RI "int \fBtileEx\fP"
.br
.ti -1c
.RI "\fBRenderData\fP \fBrenderData\fP"
.br
.ti -1c
.RI "bool \fBharvest\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB868\fP of file \fBGrowSystem\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "int GrowSystem\&.Stage\&.Convert (int tile)"

.PP
Definition at line \fB887\fP of file \fBGrowSystem\&.cs\fP\&.
.SS "void GrowSystem\&.Stage\&.SetTile (int _tile)"

.PP
Definition at line \fB871\fP of file \fBGrowSystem\&.cs\fP\&.
.SS "void GrowSystem\&.Stage\&.SetTile (int tileIdx, params int[] _tiles)"

.PP
Definition at line \fB877\fP of file \fBGrowSystem\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "bool GrowSystem\&.Stage\&.harvest"

.PP
Definition at line \fB905\fP of file \fBGrowSystem\&.cs\fP\&.
.SS "int GrowSystem\&.Stage\&.idx"

.PP
Definition at line \fB896\fP of file \fBGrowSystem\&.cs\fP\&.
.SS "\fBRenderData\fP GrowSystem\&.Stage\&.renderData"

.PP
Definition at line \fB902\fP of file \fBGrowSystem\&.cs\fP\&.
.SS "int GrowSystem\&.Stage\&.tileEx"

.PP
Definition at line \fB899\fP of file \fBGrowSystem\&.cs\fP\&.
.SS "int [] GrowSystem\&.Stage\&.tiles"

.PP
Definition at line \fB893\fP of file \fBGrowSystem\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
