.TH "HoardActor.BG" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HoardActor.BG
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Sprite \fBsprite\fP"
.br
.ti -1c
.RI "float \fBreflection\fP"
.br
.ti -1c
.RI "float \fBshadow\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB829\fP of file \fBHoardActor\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "float HoardActor\&.BG\&.reflection"

.PP
Definition at line \fB835\fP of file \fBHoardActor\&.cs\fP\&.
.SS "float HoardActor\&.BG\&.shadow"

.PP
Definition at line \fB838\fP of file \fBHoardActor\&.cs\fP\&.
.SS "Sprite HoardActor\&.BG\&.sprite"

.PP
Definition at line \fB832\fP of file \fBHoardActor\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
