.TH "HomeResource.CostList" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HomeResource.CostList
.SH SYNOPSIS
.br
.PP
.PP
Inherits List< HomeResource\&.Cost >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "string \fBGetText\fP ()"
.br
.ti -1c
.RI "bool \fBCanPay\fP ()"
.br
.ti -1c
.RI "void \fBPay\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB39\fP of file \fBHomeResource\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "bool HomeResource\&.CostList\&.CanPay ()"

.PP
Definition at line \fB57\fP of file \fBHomeResource\&.cs\fP\&.
.SS "string HomeResource\&.CostList\&.GetText ()"

.PP
Definition at line \fB42\fP of file \fBHomeResource\&.cs\fP\&.
.SS "void HomeResource\&.CostList\&.Pay ()"

.PP
Definition at line \fB70\fP of file \fBHomeResource\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
