.TH "HomeResource.Cost" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HomeResource.Cost
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCost\fP (\fBHomeResource\fP _resource, int _cost)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBcost\fP"
.br
.ti -1c
.RI "\fBHomeResource\fP \fBresource\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB80\fP of file \fBHomeResource\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "HomeResource\&.Cost\&.Cost (\fBHomeResource\fP _resource, int _cost)"

.PP
Definition at line \fB83\fP of file \fBHomeResource\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int HomeResource\&.Cost\&.cost"

.PP
Definition at line \fB90\fP of file \fBHomeResource\&.cs\fP\&.
.SS "\fBHomeResource\fP HomeResource\&.Cost\&.resource"

.PP
Definition at line \fB93\fP of file \fBHomeResource\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
