.TH "HotAction" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HotAction
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBHotItem\fP\&.
.PP
Inherited by \fBHotItemActionAudoDump\fP, \fBHotItemActionSleep\fP, \fBHotItemEQSet\fP, \fBHotItemFocusPos\fP, and \fBHotItemLayout\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnClick\fP (\fBButtonHotItem\fP b, \fBHotbar\fP h)"
.br
.ti -1c
.RI "virtual void \fBPerform\fP ()"
.br
.ti -1c
.RI "override void \fBOnShowContextMenu\fP (UIContextMenu m)"
.br
.in -1c

Public Member Functions inherited from \fBHotItem\fP
.in +1c
.ti -1c
.RI "string \fBTextHotkey\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnRightClick\fP (\fBButtonHotItem\fP b)"
.br
.ti -1c
.RI "virtual bool \fBCanAutoFire\fP (\fBChara\fP tg)"
.br
.ti -1c
.RI "virtual void \fBOnSetCurrentItem\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnUnsetCurrentItem\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnUnselect\fP ()"
.br
.ti -1c
.RI "virtual void \fBSetImage\fP (Image icon)"
.br
.ti -1c
.RI "virtual bool \fBTrySetAct\fP (\fBActPlan\fP p)"
.br
.ti -1c
.RI "virtual void \fBOnMarkMapHighlights\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnRenderTile\fP (\fBPoint\fP point, HitResult result, int dir)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fB_bgColor\fP"
.br
.ti -1c
.RI "string \fBtext\fP"
.br
.in -1c

Public Attributes inherited from \fBHotItem\fP
.in +1c
.ti -1c
.RI "\fBButtonHotItem\fP \fBbutton\fP"
.br
.ti -1c
.RI "\fBHotbar\fP \fBhotbar\fP"
.br
.ti -1c
.RI "bool \fBdisabled\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "Color \fBbgColor\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "override Color \fBSpriteColor\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual string \fBId\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBCanChangeIconColor\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBCanName\fP\fR [get]\fP"
.br
.ti -1c
.RI "override string \fBName\fP\fR [get]\fP"
.br
.ti -1c
.RI "override string \fBpathSprite\fP\fR [get]\fP"
.br
.in -1c

Properties inherited from \fBHotItem\fP
.in +1c
.ti -1c
.RI "override Sprite \fBSpriteHighlight\fP\fR [get]\fP"
.br
.ti -1c
.RI "override bool \fBIsSelectable\fP\fR [get]\fP"
.br
.ti -1c
.RI "override string \fBTextTip\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual \fBThing\fP \fBRenderThing\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual \fBThing\fP \fBThing\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual \fBThing\fP \fBTool\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBIsTool\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBLookAtMouse\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBIsGameAction\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBUseUIObjMaterial\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB6\fP of file \fBHotAction\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void HotAction\&.OnClick (\fBButtonHotItem\fP b, \fBHotbar\fP h)\fR [virtual]\fP"

.PP
Reimplemented from \fBHotItem\fP\&.
.PP
Definition at line \fB88\fP of file \fBHotAction\&.cs\fP\&.
.SS "override void HotAction\&.OnShowContextMenu (UIContextMenu m)"

.PP
Definition at line \fB104\fP of file \fBHotAction\&.cs\fP\&.
.SS "virtual void HotAction\&.Perform ()\fR [virtual]\fP"

.PP
Definition at line \fB99\fP of file \fBHotAction\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int HotAction\&._bgColor"

.PP
Definition at line \fB139\fP of file \fBHotAction\&.cs\fP\&.
.SS "string HotAction\&.text"

.PP
Definition at line \fB143\fP of file \fBHotAction\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "Color HotAction\&.bgColor\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB11\fP of file \fBHotAction\&.cs\fP\&.
.SS "virtual bool HotAction\&.CanChangeIconColor\fR [get]\fP"

.PP
Definition at line \fB49\fP of file \fBHotAction\&.cs\fP\&.
.SS "virtual bool HotAction\&.CanName\fR [get]\fP"

.PP
Definition at line \fB59\fP of file \fBHotAction\&.cs\fP\&.
.SS "virtual string HotAction\&.Id\fR [get]\fP"

.PP
Definition at line \fB39\fP of file \fBHotAction\&.cs\fP\&.
.SS "override string HotAction\&.Name\fR [get]\fP"

.PP
Definition at line \fB69\fP of file \fBHotAction\&.cs\fP\&.
.SS "override string HotAction\&.pathSprite\fR [get]\fP"

.PP
Definition at line \fB79\fP of file \fBHotAction\&.cs\fP\&.
.SS "override Color HotAction\&.SpriteColor\fR [get]\fP"

.PP
Definition at line \fB25\fP of file \fBHotAction\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
