.TH "HotItemNoItem" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HotItemNoItem
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBHotItemGameAction\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override Sprite \fBGetSprite\fP ()"
.br
.ti -1c
.RI "override bool \fBTrySetAct\fP (\fBActPlan\fP p)"
.br
.in -1c

Public Member Functions inherited from \fBHotItemGameAction\fP
.in +1c
.ti -1c
.RI "override void \fBOnClick\fP (\fBButtonHotItem\fP b, \fBHotbar\fP h)"
.br
.ti -1c
.RI "override void \fBOnRightClick\fP (\fBButtonHotItem\fP b)"
.br
.ti -1c
.RI "override void \fBOnMarkMapHighlights\fP ()"
.br
.in -1c

Public Member Functions inherited from \fBHotItem\fP
.in +1c
.ti -1c
.RI "string \fBTextHotkey\fP ()"
.br
.ti -1c
.RI "virtual bool \fBCanAutoFire\fP (\fBChara\fP tg)"
.br
.ti -1c
.RI "virtual void \fBOnSetCurrentItem\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnUnsetCurrentItem\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnUnselect\fP ()"
.br
.ti -1c
.RI "virtual void \fBSetImage\fP (Image icon)"
.br
.ti -1c
.RI "virtual void \fBOnRenderTile\fP (\fBPoint\fP point, HitResult result, int dir)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fB_TrySetAct\fP (\fBActPlan\fP p)"
.br
.in -1c
.SS "Additional Inherited Members"


Public Attributes inherited from \fBHotItem\fP
.in +1c
.ti -1c
.RI "\fBButtonHotItem\fP \fBbutton\fP"
.br
.ti -1c
.RI "\fBHotbar\fP \fBhotbar\fP"
.br
.ti -1c
.RI "bool \fBdisabled\fP"
.br
.in -1c

Properties inherited from \fBHotItemGameAction\fP
.in +1c
.ti -1c
.RI "virtual \fBAct\fP \fBact\fP\fR [get]\fP"
.br
.ti -1c
.RI "override bool \fBIsGameAction\fP\fR [get]\fP"
.br
.in -1c

Properties inherited from \fBHotItem\fP
.in +1c
.ti -1c
.RI "override Sprite \fBSpriteHighlight\fP\fR [get]\fP"
.br
.ti -1c
.RI "override bool \fBIsSelectable\fP\fR [get]\fP"
.br
.ti -1c
.RI "override string \fBTextTip\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual \fBThing\fP \fBRenderThing\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual \fBThing\fP \fBThing\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual \fBThing\fP \fBTool\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBIsTool\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBLookAtMouse\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBIsGameAction\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBUseUIObjMaterial\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB5\fP of file \fBHotItemNoItem\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "static bool HotItemNoItem\&._TrySetAct (\fBActPlan\fP p)\fR [static]\fP"

.PP
Definition at line \fB14\fP of file \fBHotItemNoItem\&.cs\fP\&.
.SS "override Sprite HotItemNoItem\&.GetSprite ()"

.PP
Definition at line \fB8\fP of file \fBHotItemNoItem\&.cs\fP\&.
.SS "override bool HotItemNoItem\&.TrySetAct (\fBActPlan\fP p)\fR [virtual]\fP"

.PP
Reimplemented from \fBHotItem\fP\&.
.PP
Definition at line \fB83\fP of file \fBHotItemNoItem\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
