.TH "HotItemHeld" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HotItemHeld
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBHotItemThing\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHotItemHeld\fP (\fBThing\fP t)"
.br
.ti -1c
.RI "override void \fBOnSetCurrentItem\fP ()"
.br
.ti -1c
.RI "override void \fBOnUnselect\fP ()"
.br
.ti -1c
.RI "\fBAct\fP \fBGetAct\fP ()"
.br
.ti -1c
.RI "\fBAct\fP \fBGetSelfAct\fP ()"
.br
.ti -1c
.RI "override bool \fBTrySetAct\fP (\fBActPlan\fP p)"
.br
.ti -1c
.RI "bool \fBTrySetToolAct\fP (\fBActPlan\fP p)"
.br
.ti -1c
.RI "unsafe override void \fBOnRenderTile\fP (\fBPoint\fP point, HitResult result, int dir)"
.br
.in -1c

Public Member Functions inherited from \fBHotItemThing\fP
.in +1c
.ti -1c
.RI "override Sprite \fBGetSprite\fP ()"
.br
.ti -1c
.RI "override void \fBSetImage\fP (Image icon)"
.br
.ti -1c
.RI "override void \fBSetSubText\fP (UIText t)"
.br
.in -1c

Public Member Functions inherited from \fBHotItemGameAction\fP
.in +1c
.ti -1c
.RI "override void \fBOnClick\fP (\fBButtonHotItem\fP b, \fBHotbar\fP h)"
.br
.ti -1c
.RI "override void \fBOnRightClick\fP (\fBButtonHotItem\fP b)"
.br
.ti -1c
.RI "override void \fBOnMarkMapHighlights\fP ()"
.br
.in -1c

Public Member Functions inherited from \fBHotItem\fP
.in +1c
.ti -1c
.RI "string \fBTextHotkey\fP ()"
.br
.ti -1c
.RI "virtual bool \fBCanAutoFire\fP (\fBChara\fP tg)"
.br
.ti -1c
.RI "virtual void \fBOnUnsetCurrentItem\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBCanChangeHeightByWheel\fP ()"
.br
.ti -1c
.RI "static bool \fBCanRotate\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static \fBThing\fP \fBlastHeld\fP"
.br
.ti -1c
.RI "static \fBTaskBuild\fP \fBtaskBuild\fP"
.br
.ti -1c
.RI "static \fBRecipe\fP \fBrecipe\fP"
.br
.ti -1c
.RI "static bool \fBdisableTool\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override \fBAct\fP \fBact\fP\fR [get]\fP"
.br
.in -1c

Properties inherited from \fBHotItemThing\fP
.in +1c
.ti -1c
.RI "override \fBAct\fP \fBact\fP\fR [get]\fP"
.br
.ti -1c
.RI "override string \fBName\fP\fR [get]\fP"
.br
.ti -1c
.RI "override bool \fBIsSelectable\fP\fR [get]\fP"
.br
.ti -1c
.RI "override \fBThing\fP \fBThing\fP\fR [get]\fP"
.br
.ti -1c
.RI "override bool \fBUseUIObjMaterial\fP\fR [get]\fP"
.br
.in -1c

Properties inherited from \fBHotItemGameAction\fP
.in +1c
.ti -1c
.RI "virtual \fBAct\fP \fBact\fP\fR [get]\fP"
.br
.ti -1c
.RI "override bool \fBIsGameAction\fP\fR [get]\fP"
.br
.in -1c

Properties inherited from \fBHotItem\fP
.in +1c
.ti -1c
.RI "override Sprite \fBSpriteHighlight\fP\fR [get]\fP"
.br
.ti -1c
.RI "override bool \fBIsSelectable\fP\fR [get]\fP"
.br
.ti -1c
.RI "override string \fBTextTip\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual \fBThing\fP \fBRenderThing\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual \fBThing\fP \fBThing\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual \fBThing\fP \fBTool\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBIsTool\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBLookAtMouse\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBIsGameAction\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBUseUIObjMaterial\fP\fR [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Public Attributes inherited from \fBHotItemThing\fP
.in +1c
.ti -1c
.RI "\fBThing\fP \fBthing\fP"
.br
.ti -1c
.RI "bool \fBlost\fP"
.br
.ti -1c
.RI "\fBAct\fP \fB_act\fP"
.br
.in -1c

Public Attributes inherited from \fBHotItem\fP
.in +1c
.ti -1c
.RI "\fBButtonHotItem\fP \fBbutton\fP"
.br
.ti -1c
.RI "\fBHotbar\fP \fBhotbar\fP"
.br
.ti -1c
.RI "bool \fBdisabled\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB5\fP of file \fBHotItemHeld\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "HotItemHeld\&.HotItemHeld ()"

.PP
Definition at line \fB30\fP of file \fBHotItemHeld\&.cs\fP\&.
.SS "HotItemHeld\&.HotItemHeld (\fBThing\fP t)"

.PP
Definition at line \fB35\fP of file \fBHotItemHeld\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "static bool HotItemHeld\&.CanChangeHeightByWheel ()\fR [static]\fP"

.PP
Definition at line \fB8\fP of file \fBHotItemHeld\&.cs\fP\&.
.SS "static bool HotItemHeld\&.CanRotate ()\fR [static]\fP"

.PP
Definition at line \fB14\fP of file \fBHotItemHeld\&.cs\fP\&.
.SS "\fBAct\fP HotItemHeld\&.GetAct ()"

.PP
Definition at line \fB79\fP of file \fBHotItemHeld\&.cs\fP\&.
.SS "\fBAct\fP HotItemHeld\&.GetSelfAct ()"

.PP
Definition at line \fB124\fP of file \fBHotItemHeld\&.cs\fP\&.
.SS "unsafe override void HotItemHeld\&.OnRenderTile (\fBPoint\fP point, HitResult result, int dir)\fR [virtual]\fP"

.PP
Reimplemented from \fBHotItem\fP\&.
.PP
Definition at line \fB397\fP of file \fBHotItemHeld\&.cs\fP\&.
.SS "override void HotItemHeld\&.OnSetCurrentItem ()\fR [virtual]\fP"

.PP
Reimplemented from \fBHotItem\fP\&.
.PP
Definition at line \fB41\fP of file \fBHotItemHeld\&.cs\fP\&.
.SS "override void HotItemHeld\&.OnUnselect ()\fR [virtual]\fP"

.PP
Reimplemented from \fBHotItem\fP\&.
.PP
Definition at line \fB68\fP of file \fBHotItemHeld\&.cs\fP\&.
.SS "override bool HotItemHeld\&.TrySetAct (\fBActPlan\fP p)\fR [virtual]\fP"

.PP
Reimplemented from \fBHotItem\fP\&.
.PP
Definition at line \fB155\fP of file \fBHotItemHeld\&.cs\fP\&.
.SS "bool HotItemHeld\&.TrySetToolAct (\fBActPlan\fP p)"

.PP
Definition at line \fB274\fP of file \fBHotItemHeld\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "bool HotItemHeld\&.disableTool\fR [static]\fP"

.PP
Definition at line \fB445\fP of file \fBHotItemHeld\&.cs\fP\&.
.SS "\fBThing\fP HotItemHeld\&.lastHeld\fR [static]\fP"

.PP
Definition at line \fB436\fP of file \fBHotItemHeld\&.cs\fP\&.
.SS "\fBRecipe\fP HotItemHeld\&.recipe\fR [static]\fP"

.PP
Definition at line \fB442\fP of file \fBHotItemHeld\&.cs\fP\&.
.SS "\fBTaskBuild\fP HotItemHeld\&.taskBuild\fR [static]\fP"

.PP
Definition at line \fB439\fP of file \fBHotItemHeld\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "override \fBAct\fP HotItemHeld\&.act\fR [get]\fP"

.PP
Definition at line \fB21\fP of file \fBHotItemHeld\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
