.TH "HotItemLayout.Layout" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HotItemLayout.Layout
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Dictionary< string, Window\&.SaveData > \fBdataWindow\fP = new Dictionary<string, Window\&.SaveData>()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB61\fP of file \fBHotItemLayout\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "Dictionary<string, Window\&.SaveData> HotItemLayout\&.Layout\&.dataWindow = new Dictionary<string, Window\&.SaveData>()"

.PP
Definition at line \fB65\fP of file \fBHotItemLayout\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
