.TH "HotItemToggleVisible" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HotItemToggleVisible
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBHotItemIcon\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override bool \fBShouldHighlight\fP ()"
.br
.ti -1c
.RI "override Sprite \fBGetSprite\fP (bool highlight)"
.br
.ti -1c
.RI "override void \fBOnHover\fP (UIButton b)"
.br
.ti -1c
.RI "override void \fBOnClick\fP (\fBButtonHotItem\fP b, \fBHotbar\fP h)"
.br
.in -1c

Public Member Functions inherited from \fBHotItemIcon\fP
.in +1c
.ti -1c
.RI "override Sprite \fBGetSprite\fP ()"
.br
.in -1c

Public Member Functions inherited from \fBHotItem\fP
.in +1c
.ti -1c
.RI "string \fBTextHotkey\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnRightClick\fP (\fBButtonHotItem\fP b)"
.br
.ti -1c
.RI "virtual bool \fBCanAutoFire\fP (\fBChara\fP tg)"
.br
.ti -1c
.RI "virtual void \fBOnSetCurrentItem\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnUnsetCurrentItem\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnUnselect\fP ()"
.br
.ti -1c
.RI "virtual void \fBSetImage\fP (Image icon)"
.br
.ti -1c
.RI "virtual bool \fBTrySetAct\fP (\fBActPlan\fP p)"
.br
.ti -1c
.RI "virtual void \fBOnMarkMapHighlights\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnRenderTile\fP (\fBPoint\fP point, HitResult result, int dir)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBsticky\fP"
.br
.in -1c

Public Attributes inherited from \fBHotItem\fP
.in +1c
.ti -1c
.RI "\fBButtonHotItem\fP \fBbutton\fP"
.br
.ti -1c
.RI "\fBHotbar\fP \fBhotbar\fP"
.br
.ti -1c
.RI "bool \fBdisabled\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override string \fBName\fP\fR [get]\fP"
.br
.ti -1c
.RI "override string \fBTextTip\fP\fR [get]\fP"
.br
.ti -1c
.RI "override bool \fBKeepVisibleWhenHighlighted\fP\fR [get]\fP"
.br
.ti -1c
.RI "override bool \fBUseIconForHighlight\fP\fR [get]\fP"
.br
.in -1c

Properties inherited from \fBHotItemIcon\fP
.in +1c
.ti -1c
.RI "virtual int \fBdefaultIcon\fP\fR [get]\fP"
.br
.in -1c

Properties inherited from \fBHotItem\fP
.in +1c
.ti -1c
.RI "override Sprite \fBSpriteHighlight\fP\fR [get]\fP"
.br
.ti -1c
.RI "override bool \fBIsSelectable\fP\fR [get]\fP"
.br
.ti -1c
.RI "override string \fBTextTip\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual \fBThing\fP \fBRenderThing\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual \fBThing\fP \fBThing\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual \fBThing\fP \fBTool\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBIsTool\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBLookAtMouse\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBIsGameAction\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBUseUIObjMaterial\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB5\fP of file \fBHotItemToggleVisible\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override Sprite HotItemToggleVisible\&.GetSprite (bool highlight)"

.PP
Definition at line \fB54\fP of file \fBHotItemToggleVisible\&.cs\fP\&.
.SS "override void HotItemToggleVisible\&.OnClick (\fBButtonHotItem\fP b, \fBHotbar\fP h)\fR [virtual]\fP"

.PP
Reimplemented from \fBHotItem\fP\&.
.PP
Definition at line \fB74\fP of file \fBHotItemToggleVisible\&.cs\fP\&.
.SS "override void HotItemToggleVisible\&.OnHover (UIButton b)"

.PP
Definition at line \fB64\fP of file \fBHotItemToggleVisible\&.cs\fP\&.
.SS "override bool HotItemToggleVisible\&.ShouldHighlight ()"

.PP
Definition at line \fB38\fP of file \fBHotItemToggleVisible\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "bool HotItemToggleVisible\&.sticky"

.PP
Definition at line \fB95\fP of file \fBHotItemToggleVisible\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "override bool HotItemToggleVisible\&.KeepVisibleWhenHighlighted\fR [get]\fP"

.PP
Definition at line \fB29\fP of file \fBHotItemToggleVisible\&.cs\fP\&.
.SS "override string HotItemToggleVisible\&.Name\fR [get]\fP"

.PP
Definition at line \fB9\fP of file \fBHotItemToggleVisible\&.cs\fP\&.
.SS "override string HotItemToggleVisible\&.TextTip\fR [get]\fP"

.PP
Definition at line \fB19\fP of file \fBHotItemToggleVisible\&.cs\fP\&.
.SS "override bool HotItemToggleVisible\&.UseIconForHighlight\fR [get]\fP"

.PP
Definition at line \fB45\fP of file \fBHotItemToggleVisible\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
