.TH "HotItemContext" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HotItemContext
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBHotItem\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnHover\fP (UIButton b)"
.br
.ti -1c
.RI "override void \fBOnClick\fP (UIButton b)"
.br
.ti -1c
.RI "override void \fBOnShowContextMenu\fP (UIContextMenu m)"
.br
.in -1c

Public Member Functions inherited from \fBHotItem\fP
.in +1c
.ti -1c
.RI "string \fBTextHotkey\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnClick\fP (\fBButtonHotItem\fP b, \fBHotbar\fP h)"
.br
.ti -1c
.RI "virtual void \fBOnRightClick\fP (\fBButtonHotItem\fP b)"
.br
.ti -1c
.RI "virtual bool \fBCanAutoFire\fP (\fBChara\fP tg)"
.br
.ti -1c
.RI "virtual void \fBOnSetCurrentItem\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnUnsetCurrentItem\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnUnselect\fP ()"
.br
.ti -1c
.RI "virtual void \fBSetImage\fP (Image icon)"
.br
.ti -1c
.RI "virtual bool \fBTrySetAct\fP (\fBActPlan\fP p)"
.br
.ti -1c
.RI "virtual void \fBOnMarkMapHighlights\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnRenderTile\fP (\fBPoint\fP point, HitResult result, int dir)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBShow\fP (string id, Vector3 pos)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBid\fP"
.br
.ti -1c
.RI "bool \fBautoExpand\fP"
.br
.in -1c

Public Attributes inherited from \fBHotItem\fP
.in +1c
.ti -1c
.RI "\fBButtonHotItem\fP \fBbutton\fP"
.br
.ti -1c
.RI "\fBHotbar\fP \fBhotbar\fP"
.br
.ti -1c
.RI "bool \fBdisabled\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override string \fBName\fP\fR [get]\fP"
.br
.ti -1c
.RI "override string \fBTextTip\fP\fR [get]\fP"
.br
.ti -1c
.RI "override string \fBpathSprite\fP\fR [get]\fP"
.br
.ti -1c
.RI "override Selectable\&.Transition \fBTransition\fP\fR [get]\fP"
.br
.ti -1c
.RI "bool \fBAutoExpand\fP\fR [get]\fP"
.br
.in -1c

Properties inherited from \fBHotItem\fP
.in +1c
.ti -1c
.RI "override Sprite \fBSpriteHighlight\fP\fR [get]\fP"
.br
.ti -1c
.RI "override bool \fBIsSelectable\fP\fR [get]\fP"
.br
.ti -1c
.RI "override string \fBTextTip\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual \fBThing\fP \fBRenderThing\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual \fBThing\fP \fBThing\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual \fBThing\fP \fBTool\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBIsTool\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBLookAtMouse\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBIsGameAction\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBUseUIObjMaterial\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB8\fP of file \fBHotItemContext\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void HotItemContext\&.OnClick (UIButton b)"

.PP
Definition at line \fB79\fP of file \fBHotItemContext\&.cs\fP\&.
.SS "override void HotItemContext\&.OnHover (UIButton b)"

.PP
Definition at line \fB69\fP of file \fBHotItemContext\&.cs\fP\&.
.SS "override void HotItemContext\&.OnShowContextMenu (UIContextMenu m)"

.PP
Definition at line \fB89\fP of file \fBHotItemContext\&.cs\fP\&.
.SS "static void HotItemContext\&.Show (string id, Vector3 pos)\fR [static]\fP"

.PP
Definition at line \fB98\fP of file \fBHotItemContext\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "bool HotItemContext\&.autoExpand"

.PP
Definition at line \fB314\fP of file \fBHotItemContext\&.cs\fP\&.
.SS "string HotItemContext\&.id"

.PP
Definition at line \fB310\fP of file \fBHotItemContext\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "bool HotItemContext\&.AutoExpand\fR [get]\fP"

.PP
Definition at line \fB60\fP of file \fBHotItemContext\&.cs\fP\&.
.SS "override string HotItemContext\&.Name\fR [get]\fP"

.PP
Definition at line \fB12\fP of file \fBHotItemContext\&.cs\fP\&.
.SS "override string HotItemContext\&.pathSprite\fR [get]\fP"

.PP
Definition at line \fB32\fP of file \fBHotItemContext\&.cs\fP\&.
.SS "override string HotItemContext\&.TextTip\fR [get]\fP"

.PP
Definition at line \fB22\fP of file \fBHotItemContext\&.cs\fP\&.
.SS "override Selectable\&.Transition HotItemContext\&.Transition\fR [get]\fP"

.PP
Definition at line \fB46\fP of file \fBHotItemContext\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
