.TH "HotItemEQSet.Item" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HotItemEQSet.Item
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBCard\fP \fBcontainer\fP"
.br
.ti -1c
.RI "int \fBinvX\fP"
.br
.ti -1c
.RI "int \fBinvY\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB139\fP of file \fBHotItemEQSet\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBCard\fP HotItemEQSet\&.Item\&.container"

.PP
Definition at line \fB142\fP of file \fBHotItemEQSet\&.cs\fP\&.
.SS "int HotItemEQSet\&.Item\&.invX"

.PP
Definition at line \fB145\fP of file \fBHotItemEQSet\&.cs\fP\&.
.SS "int HotItemEQSet\&.Item\&.invY"

.PP
Definition at line \fB148\fP of file \fBHotItemEQSet\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
