.TH "HotItemToggleWidget" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HotItemToggleWidget
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBHotItemIcon\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnClick\fP (UIButton b)"
.br
.in -1c

Public Member Functions inherited from \fBHotItemIcon\fP
.in +1c
.ti -1c
.RI "override Sprite \fBGetSprite\fP ()"
.br
.in -1c

Public Member Functions inherited from \fBHotItem\fP
.in +1c
.ti -1c
.RI "string \fBTextHotkey\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnClick\fP (\fBButtonHotItem\fP b, \fBHotbar\fP h)"
.br
.ti -1c
.RI "virtual void \fBOnRightClick\fP (\fBButtonHotItem\fP b)"
.br
.ti -1c
.RI "virtual bool \fBCanAutoFire\fP (\fBChara\fP tg)"
.br
.ti -1c
.RI "virtual void \fBOnSetCurrentItem\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnUnsetCurrentItem\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnUnselect\fP ()"
.br
.ti -1c
.RI "virtual void \fBSetImage\fP (Image icon)"
.br
.ti -1c
.RI "virtual bool \fBTrySetAct\fP (\fBActPlan\fP p)"
.br
.ti -1c
.RI "virtual void \fBOnMarkMapHighlights\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnRenderTile\fP (\fBPoint\fP point, HitResult result, int dir)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override int \fBdefaultIcon\fP\fR [get]\fP"
.br
.ti -1c
.RI "override string \fBName\fP\fR [get]\fP"
.br
.in -1c

Properties inherited from \fBHotItemIcon\fP
.in +1c
.ti -1c
.RI "virtual int \fBdefaultIcon\fP\fR [get]\fP"
.br
.in -1c

Properties inherited from \fBHotItem\fP
.in +1c
.ti -1c
.RI "override Sprite \fBSpriteHighlight\fP\fR [get]\fP"
.br
.ti -1c
.RI "override bool \fBIsSelectable\fP\fR [get]\fP"
.br
.ti -1c
.RI "override string \fBTextTip\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual \fBThing\fP \fBRenderThing\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual \fBThing\fP \fBThing\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual \fBThing\fP \fBTool\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBIsTool\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBLookAtMouse\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBIsGameAction\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBUseUIObjMaterial\fP\fR [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Public Attributes inherited from \fBHotItem\fP
.in +1c
.ti -1c
.RI "\fBButtonHotItem\fP \fBbutton\fP"
.br
.ti -1c
.RI "\fBHotbar\fP \fBhotbar\fP"
.br
.ti -1c
.RI "bool \fBdisabled\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB4\fP of file \fBHotItemToggleWidget\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void HotItemToggleWidget\&.OnClick (UIButton b)"

.PP
Definition at line \fB27\fP of file \fBHotItemToggleWidget\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "override int HotItemToggleWidget\&.defaultIcon\fR [get]\fP"

.PP
Definition at line \fB8\fP of file \fBHotItemToggleWidget\&.cs\fP\&.
.SS "override string HotItemToggleWidget\&.Name\fR [get]\fP"

.PP
Definition at line \fB18\fP of file \fBHotItemToggleWidget\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
