.TH "HotItemWidget" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HotItemWidget
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBHotItem\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnClick\fP (\fBButtonHotItem\fP b, \fBHotbar\fP h)"
.br
.in -1c

Public Member Functions inherited from \fBHotItem\fP
.in +1c
.ti -1c
.RI "string \fBTextHotkey\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnRightClick\fP (\fBButtonHotItem\fP b)"
.br
.ti -1c
.RI "virtual bool \fBCanAutoFire\fP (\fBChara\fP tg)"
.br
.ti -1c
.RI "virtual void \fBOnSetCurrentItem\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnUnsetCurrentItem\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnUnselect\fP ()"
.br
.ti -1c
.RI "virtual void \fBSetImage\fP (Image icon)"
.br
.ti -1c
.RI "virtual bool \fBTrySetAct\fP (\fBActPlan\fP p)"
.br
.ti -1c
.RI "virtual void \fBOnMarkMapHighlights\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnRenderTile\fP (\fBPoint\fP point, HitResult result, int dir)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBid\fP"
.br
.in -1c

Public Attributes inherited from \fBHotItem\fP
.in +1c
.ti -1c
.RI "\fBButtonHotItem\fP \fBbutton\fP"
.br
.ti -1c
.RI "\fBHotbar\fP \fBhotbar\fP"
.br
.ti -1c
.RI "bool \fBdisabled\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override string \fBName\fP\fR [get]\fP"
.br
.ti -1c
.RI "override string \fBpathSprite\fP\fR [get]\fP"
.br
.in -1c

Properties inherited from \fBHotItem\fP
.in +1c
.ti -1c
.RI "override Sprite \fBSpriteHighlight\fP\fR [get]\fP"
.br
.ti -1c
.RI "override bool \fBIsSelectable\fP\fR [get]\fP"
.br
.ti -1c
.RI "override string \fBTextTip\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual \fBThing\fP \fBRenderThing\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual \fBThing\fP \fBThing\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual \fBThing\fP \fBTool\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBIsTool\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBLookAtMouse\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBIsGameAction\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBUseUIObjMaterial\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB5\fP of file \fBHotItemWidget\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void HotItemWidget\&.OnClick (\fBButtonHotItem\fP b, \fBHotbar\fP h)\fR [virtual]\fP"

.PP
Reimplemented from \fBHotItem\fP\&.
.PP
Definition at line \fB28\fP of file \fBHotItemWidget\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "string HotItemWidget\&.id"

.PP
Definition at line \fB57\fP of file \fBHotItemWidget\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "override string HotItemWidget\&.Name\fR [get]\fP"

.PP
Definition at line \fB9\fP of file \fBHotItemWidget\&.cs\fP\&.
.SS "override string HotItemWidget\&.pathSprite\fR [get]\fP"

.PP
Definition at line \fB19\fP of file \fBHotItemWidget\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
