.TH "HS_ParticleEndSound" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HS_ParticleEndSound
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPool\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "GameObject \fBSpawnFromPool\fP (string tag, Vector3 position)"
.br
.ti -1c
.RI "void \fBLateUpdate\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBpoolReturnTimer\fP = 1\&.5f"
.br
.ti -1c
.RI "float \fBexplosionMinVolume\fP = 0\&.3f"
.br
.ti -1c
.RI "float \fBexplosionMaxVolume\fP = 0\&.7f"
.br
.ti -1c
.RI "float \fBexplosionPitchMin\fP = 0\&.75f"
.br
.ti -1c
.RI "float \fBexplosionPitchMax\fP = 1\&.25f"
.br
.ti -1c
.RI "float \fBshootMinVolume\fP = 0\&.05f"
.br
.ti -1c
.RI "float \fBshootMaxVolume\fP = 0\&.1f"
.br
.ti -1c
.RI "float \fBshootPitchMin\fP = 0\&.75f"
.br
.ti -1c
.RI "float \fBshootPitchMax\fP = 1\&.25f"
.br
.ti -1c
.RI "AudioClip[] \fBaudioExplosion\fP"
.br
.ti -1c
.RI "AudioClip[] \fBaudioShot\fP"
.br
.ti -1c
.RI "List< \fBHS_ParticleEndSound\&.Pool\fP > \fBpools\fP"
.br
.ti -1c
.RI "Dictionary< string, \fBQueue\fP< GameObject > > \fBpoolDictionary\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static \fBHS_ParticleEndSound\fP \fBSharedInstance\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB7\fP of file \fBHS_ParticleEndSound\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void HS_ParticleEndSound\&.LateUpdate ()"

.PP
Definition at line \fB60\fP of file \fBHS_ParticleEndSound\&.cs\fP\&.
.SS "GameObject HS_ParticleEndSound\&.SpawnFromPool (string tag, Vector3 position)"

.PP
Definition at line \fB44\fP of file \fBHS_ParticleEndSound\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "AudioClip [] HS_ParticleEndSound\&.audioExplosion"

.PP
Definition at line \fB121\fP of file \fBHS_ParticleEndSound\&.cs\fP\&.
.SS "AudioClip [] HS_ParticleEndSound\&.audioShot"

.PP
Definition at line \fB124\fP of file \fBHS_ParticleEndSound\&.cs\fP\&.
.SS "float HS_ParticleEndSound\&.explosionMaxVolume = 0\&.7f"

.PP
Definition at line \fB100\fP of file \fBHS_ParticleEndSound\&.cs\fP\&.
.SS "float HS_ParticleEndSound\&.explosionMinVolume = 0\&.3f"

.PP
Definition at line \fB97\fP of file \fBHS_ParticleEndSound\&.cs\fP\&.
.SS "float HS_ParticleEndSound\&.explosionPitchMax = 1\&.25f"

.PP
Definition at line \fB106\fP of file \fBHS_ParticleEndSound\&.cs\fP\&.
.SS "float HS_ParticleEndSound\&.explosionPitchMin = 0\&.75f"

.PP
Definition at line \fB103\fP of file \fBHS_ParticleEndSound\&.cs\fP\&.
.SS "Dictionary<string, \fBQueue\fP<GameObject> > HS_ParticleEndSound\&.poolDictionary"

.PP
Definition at line \fB133\fP of file \fBHS_ParticleEndSound\&.cs\fP\&.
.SS "float HS_ParticleEndSound\&.poolReturnTimer = 1\&.5f"

.PP
Definition at line \fB94\fP of file \fBHS_ParticleEndSound\&.cs\fP\&.
.SS "List<\fBHS_ParticleEndSound\&.Pool\fP> HS_ParticleEndSound\&.pools"

.PP
Definition at line \fB130\fP of file \fBHS_ParticleEndSound\&.cs\fP\&.
.SS "\fBHS_ParticleEndSound\fP HS_ParticleEndSound\&.SharedInstance\fR [static]\fP"

.PP
Definition at line \fB127\fP of file \fBHS_ParticleEndSound\&.cs\fP\&.
.SS "float HS_ParticleEndSound\&.shootMaxVolume = 0\&.1f"

.PP
Definition at line \fB112\fP of file \fBHS_ParticleEndSound\&.cs\fP\&.
.SS "float HS_ParticleEndSound\&.shootMinVolume = 0\&.05f"

.PP
Definition at line \fB109\fP of file \fBHS_ParticleEndSound\&.cs\fP\&.
.SS "float HS_ParticleEndSound\&.shootPitchMax = 1\&.25f"

.PP
Definition at line \fB118\fP of file \fBHS_ParticleEndSound\&.cs\fP\&.
.SS "float HS_ParticleEndSound\&.shootPitchMin = 0\&.75f"

.PP
Definition at line \fB115\fP of file \fBHS_ParticleEndSound\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
