.TH "HUD" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HUD
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBEClass\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBHideMouseInfo\fP ()"
.br
.ti -1c
.RI "void \fBSetDragImage\fP (Image i, string text=null, UIText uiText=null)"
.br
.ti -1c
.RI "void \fBSetDragText\fP (string text=null, string text2=null)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBActionHint\fP \fBhint\fP"
.br
.ti -1c
.RI "Transform \fBframe\fP"
.br
.ti -1c
.RI "\fBUIHangIcon\fP \fBhangCorner\fP"
.br
.ti -1c
.RI "Image \fBimageDrag\fP"
.br
.ti -1c
.RI "Image \fBimageCover\fP"
.br
.ti -1c
.RI "CanvasGroup \fBcgDrag\fP"
.br
.ti -1c
.RI "UIText \fBtextDrag\fP"
.br
.ti -1c
.RI "UIText \fBtextDrag2\fP"
.br
.ti -1c
.RI "UIText \fBtextMouseHintRight\fP"
.br
.ti -1c
.RI "UIText \fBtextMouseHintLeft\fP"
.br
.ti -1c
.RI "Vector3 \fBimageDragFix\fP"
.br
.ti -1c
.RI "Vector3 \fBimageDragFix2\fP"
.br
.ti -1c
.RI "Vector3 \fBtextMouseHintFix\fP"
.br
.ti -1c
.RI "Vector3 \fBtextMouseHintFixLeft\fP"
.br
.ti -1c
.RI "int \fBmarginImageDrag\fP"
.br
.ti -1c
.RI "Image \fBimageRight\fP"
.br
.ti -1c
.RI "UIText \fBtextRight\fP"
.br
.ti -1c
.RI "UIText \fBtextLeft\fP"
.br
.ti -1c
.RI "UIText \fBtextMiddle\fP"
.br
.ti -1c
.RI "UIText \fBtextWheel\fP"
.br
.ti -1c
.RI "Transform \fBtransRight\fP"
.br
.ti -1c
.RI "Vector2 \fBrightTextPos\fP"
.br
.ti -1c
.RI "Vector2 \fBleftTextPos\fP"
.br
.ti -1c
.RI "Vector2 \fBwheelTextPos\fP"
.br
.ti -1c
.RI "Vector2 \fBwheelTextPos2\fP"
.br
.ti -1c
.RI "Vector3 \fBtransRightPos\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Static Public Member Functions inherited from \fBEClass\fP
.in +1c
.ti -1c
.RI "static int \fBrnd\fP (int a)"
.br
.ti -1c
.RI "static int \fBcurve\fP (int a, int start, int step, int rate=75)"
.br
.ti -1c
.RI "static int \fBrndHalf\fP (int a)"
.br
.ti -1c
.RI "static float \fBrndf\fP (float a)"
.br
.ti -1c
.RI "static int \fBrndSqrt\fP (int a)"
.br
.ti -1c
.RI "static void \fBWait\fP (float a, \fBCard\fP c)"
.br
.ti -1c
.RI "static void \fBWait\fP (float a, \fBPoint\fP p)"
.br
.ti -1c
.RI "static int \fBBigger\fP (int a, int b)"
.br
.ti -1c
.RI "static int \fBSmaller\fP (int a, int b)"
.br
.in -1c

Static Public Attributes inherited from \fBEClass\fP
.in +1c
.ti -1c
.RI "static \fBCore\fP \fBcore\fP"
.br
.in -1c

Properties inherited from \fBEClass\fP
.in +1c
.ti -1c
.RI "static \fBGame\fP \fBgame\fP\fR [get]\fP"
.br
.ti -1c
.RI "static bool \fBAdvMode\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBPlayer\fP \fBplayer\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBChara\fP \fBpc\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBUI\fP \fBui\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBMap\fP \fB_map\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBZone\fP \fB_zone\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranchOrHomeBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFaction\fP \fBHome\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFaction\fP \fBWilds\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBScene\fP \fBscene\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBBaseGameScreen\fP \fBscreen\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameSetting\fP \fBsetting\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameData\fP \fBgamedata\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBColorProfile\fP \fBColors\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBWorld\fP \fBworld\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBsources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBeditorSources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static SoundManager \fBSound\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBCoreDebug\fP \fBdebug\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB7\fP of file \fBHUD\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void HUD\&.HideMouseInfo ()"

.PP
Definition at line \fB10\fP of file \fBHUD\&.cs\fP\&.
.SS "void HUD\&.SetDragImage (Image i, string text = \fRnull\fP, UIText uiText = \fRnull\fP)"

.PP
Definition at line \fB16\fP of file \fBHUD\&.cs\fP\&.
.SS "void HUD\&.SetDragText (string text = \fRnull\fP, string text2 = \fRnull\fP)"

.PP
Definition at line \fB51\fP of file \fBHUD\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "CanvasGroup HUD\&.cgDrag"

.PP
Definition at line \fB81\fP of file \fBHUD\&.cs\fP\&.
.SS "Transform HUD\&.frame"

.PP
Definition at line \fB69\fP of file \fBHUD\&.cs\fP\&.
.SS "\fBUIHangIcon\fP HUD\&.hangCorner"

.PP
Definition at line \fB72\fP of file \fBHUD\&.cs\fP\&.
.SS "\fBActionHint\fP HUD\&.hint"

.PP
Definition at line \fB66\fP of file \fBHUD\&.cs\fP\&.
.SS "Image HUD\&.imageCover"

.PP
Definition at line \fB78\fP of file \fBHUD\&.cs\fP\&.
.SS "Image HUD\&.imageDrag"

.PP
Definition at line \fB75\fP of file \fBHUD\&.cs\fP\&.
.SS "Vector3 HUD\&.imageDragFix"

.PP
Definition at line \fB96\fP of file \fBHUD\&.cs\fP\&.
.SS "Vector3 HUD\&.imageDragFix2"

.PP
Definition at line \fB99\fP of file \fBHUD\&.cs\fP\&.
.SS "Image HUD\&.imageRight"

.PP
Definition at line \fB111\fP of file \fBHUD\&.cs\fP\&.
.SS "Vector2 HUD\&.leftTextPos"

.PP
Definition at line \fB132\fP of file \fBHUD\&.cs\fP\&.
.SS "int HUD\&.marginImageDrag"

.PP
Definition at line \fB108\fP of file \fBHUD\&.cs\fP\&.
.SS "Vector2 HUD\&.rightTextPos"

.PP
Definition at line \fB129\fP of file \fBHUD\&.cs\fP\&.
.SS "UIText HUD\&.textDrag"

.PP
Definition at line \fB84\fP of file \fBHUD\&.cs\fP\&.
.SS "UIText HUD\&.textDrag2"

.PP
Definition at line \fB87\fP of file \fBHUD\&.cs\fP\&.
.SS "UIText HUD\&.textLeft"

.PP
Definition at line \fB117\fP of file \fBHUD\&.cs\fP\&.
.SS "UIText HUD\&.textMiddle"

.PP
Definition at line \fB120\fP of file \fBHUD\&.cs\fP\&.
.SS "Vector3 HUD\&.textMouseHintFix"

.PP
Definition at line \fB102\fP of file \fBHUD\&.cs\fP\&.
.SS "Vector3 HUD\&.textMouseHintFixLeft"

.PP
Definition at line \fB105\fP of file \fBHUD\&.cs\fP\&.
.SS "UIText HUD\&.textMouseHintLeft"

.PP
Definition at line \fB93\fP of file \fBHUD\&.cs\fP\&.
.SS "UIText HUD\&.textMouseHintRight"

.PP
Definition at line \fB90\fP of file \fBHUD\&.cs\fP\&.
.SS "UIText HUD\&.textRight"

.PP
Definition at line \fB114\fP of file \fBHUD\&.cs\fP\&.
.SS "UIText HUD\&.textWheel"

.PP
Definition at line \fB123\fP of file \fBHUD\&.cs\fP\&.
.SS "Transform HUD\&.transRight"

.PP
Definition at line \fB126\fP of file \fBHUD\&.cs\fP\&.
.SS "Vector3 HUD\&.transRightPos"

.PP
Definition at line \fB141\fP of file \fBHUD\&.cs\fP\&.
.SS "Vector2 HUD\&.wheelTextPos"

.PP
Definition at line \fB135\fP of file \fBHUD\&.cs\fP\&.
.SS "Vector2 HUD\&.wheelTextPos2"

.PP
Definition at line \fB138\fP of file \fBHUD\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
