.TH "IGlobalValue" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IGlobalValue
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBCard\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "string \fBReferenceId\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB4\fP of file \fBIGlobalValue\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
