.TH "IInspect" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IInspect
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBBaseArea\fP, \fBBaseInspectPos\fP, \fBCard\fP, \fBEloPos\fP, \fBTaskPoint\fP, and \fBZone\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBNoteMode\fP { \fBDefault\fP, \fBRecipe\fP, \fBProduct\fP, \fBInfo\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBWriteNote\fP (UINote n, Action< UINote > onWriteNote=null, IInspect\&.NoteMode mode=IInspect\&.NoteMode\&.Default, \fBRecipe\fP recipe=null)"
.br
.ti -1c
.RI "void \fBOnInspect\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "bool \fBCanInspect\fP\fR [get]\fP"
.br
.ti -1c
.RI "string \fBInspectName\fP\fR [get]\fP"
.br
.ti -1c
.RI "\fBPoint\fP \fBInspectPoint\fP\fR [get]\fP"
.br
.ti -1c
.RI "Vector3 \fBInspectPosition\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB5\fP of file \fBIInspect\&.cs\fP\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "enum IInspect\&.NoteMode"

.PP
Definition at line \fB30\fP of file \fBIInspect\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "bool IInspect\&.CanInspect\fR [get]\fP"

.PP
Definition at line \fB9\fP of file \fBIInspect\&.cs\fP\&.
.SS "string IInspect\&.InspectName\fR [get]\fP"

.PP
Definition at line \fB13\fP of file \fBIInspect\&.cs\fP\&.
.SS "\fBPoint\fP IInspect\&.InspectPoint\fR [get]\fP"

.PP
Definition at line \fB17\fP of file \fBIInspect\&.cs\fP\&.
.SS "Vector3 IInspect\&.InspectPosition\fR [get]\fP"

.PP
Definition at line \fB21\fP of file \fBIInspect\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
