.TH "InspectGroup< T >.Item" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
InspectGroup< T >.Item
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBtext\fP"
.br
.ti -1c
.RI "string \fBidSprite\fP"
.br
.ti -1c
.RI "Action< \fBIInspect\fP > \fBaction\fP"
.br
.ti -1c
.RI "int \fBpriority\fP"
.br
.ti -1c
.RI "bool \fBauto\fP"
.br
.ti -1c
.RI "bool \fBsound\fP"
.br
.ti -1c
.RI "bool \fBmulti\fP"
.br
.ti -1c
.RI "Func< string > \fBtextFunc\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB118\fP of file \fBInspectGroup\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "Action<\fBIInspect\fP> \fBInspectGroup\fP< T >\&.Item\&.action"

.PP
Definition at line \fB127\fP of file \fBInspectGroup\&.cs\fP\&.
.SS "bool \fBInspectGroup\fP< T >\&.Item\&.auto"

.PP
Definition at line \fB133\fP of file \fBInspectGroup\&.cs\fP\&.
.SS "string \fBInspectGroup\fP< T >\&.Item\&.idSprite"

.PP
Definition at line \fB124\fP of file \fBInspectGroup\&.cs\fP\&.
.SS "bool \fBInspectGroup\fP< T >\&.Item\&.multi"

.PP
Definition at line \fB139\fP of file \fBInspectGroup\&.cs\fP\&.
.SS "int \fBInspectGroup\fP< T >\&.Item\&.priority"

.PP
Definition at line \fB130\fP of file \fBInspectGroup\&.cs\fP\&.
.SS "bool \fBInspectGroup\fP< T >\&.Item\&.sound"

.PP
Definition at line \fB136\fP of file \fBInspectGroup\&.cs\fP\&.
.SS "string \fBInspectGroup\fP< T >\&.Item\&.text"

.PP
Definition at line \fB121\fP of file \fBInspectGroup\&.cs\fP\&.
.SS "Func<string> \fBInspectGroup\fP< T >\&.Item\&.textFunc"

.PP
Definition at line \fB142\fP of file \fBInspectGroup\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
