.TH "Int3" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Int3
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBInt3\fP (int _x, int _y, int _z)"
.br
.ti -1c
.RI "\fBInt3\fP (float _x, float _y, float _z)"
.br
.ti -1c
.RI "void \fBSet\fP (int _x, int _y, int _z)"
.br
.ti -1c
.RI "void \fBSet\fP (float _x, float _y, float _z)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int[] \fBi\fP = new int[3]"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBx\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "int \fBy\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "int \fBz\fP\fR [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB4\fP of file \fBInt3\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Int3\&.Int3 ()"

.PP
Definition at line \fB52\fP of file \fBInt3\&.cs\fP\&.
.SS "Int3\&.Int3 (int _x, int _y, int _z)"

.PP
Definition at line \fB57\fP of file \fBInt3\&.cs\fP\&.
.SS "Int3\&.Int3 (float _x, float _y, float _z)"

.PP
Definition at line \fB63\fP of file \fBInt3\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Int3\&.Set (float _x, float _y, float _z)"

.PP
Definition at line \fB77\fP of file \fBInt3\&.cs\fP\&.
.SS "void Int3\&.Set (int _x, int _y, int _z)"

.PP
Definition at line \fB69\fP of file \fBInt3\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int [] Int3\&.i = new int[3]"

.PP
Definition at line \fB85\fP of file \fBInt3\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "int Int3\&.x\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB9\fP of file \fBInt3\&.cs\fP\&.
.SS "int Int3\&.y\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB24\fP of file \fBInt3\&.cs\fP\&.
.SS "int Int3\&.z\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB39\fP of file \fBInt3\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
