.TH "InvOwner.Interaction" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
InvOwner.Interaction
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBname\fP"
.br
.ti -1c
.RI "Action \fBaction\fP"
.br
.ti -1c
.RI "int \fBpriority\fP"
.br
.ti -1c
.RI "bool \fBrepeatable\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB1927\fP of file \fBInvOwner\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "Action InvOwner\&.Interaction\&.action"

.PP
Definition at line \fB1933\fP of file \fBInvOwner\&.cs\fP\&.
.SS "string InvOwner\&.Interaction\&.name"

.PP
Definition at line \fB1930\fP of file \fBInvOwner\&.cs\fP\&.
.SS "int InvOwner\&.Interaction\&.priority"

.PP
Definition at line \fB1936\fP of file \fBInvOwner\&.cs\fP\&.
.SS "bool InvOwner\&.Interaction\&.repeatable"

.PP
Definition at line \fB1939\fP of file \fBInvOwner\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
