.TH "InvOwner.ErrorMessage" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
InvOwner.ErrorMessage
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSet\fP (string _lang, \fBCard\fP c=null, string _sound='beep_small')"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBsound\fP = 'beep_small'"
.br
.ti -1c
.RI "string \fBlang\fP = ''"
.br
.ti -1c
.RI "\fBCard\fP \fBcard\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB1445\fP of file \fBInvOwner\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void InvOwner\&.ErrorMessage\&.Set (string _lang, \fBCard\fP c = \fRnull\fP, string _sound = \fR'beep_small'\fP)"

.PP
Definition at line \fB1448\fP of file \fBInvOwner\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBCard\fP InvOwner\&.ErrorMessage\&.card"

.PP
Definition at line \fB1465\fP of file \fBInvOwner\&.cs\fP\&.
.SS "string InvOwner\&.ErrorMessage\&.lang = ''"

.PP
Definition at line \fB1462\fP of file \fBInvOwner\&.cs\fP\&.
.SS "string InvOwner\&.ErrorMessage\&.sound = 'beep_small'"

.PP
Definition at line \fB1459\fP of file \fBInvOwner\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
