.TH "InvOwner.Transaction" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
InvOwner.Transaction
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTransaction\fP (\fBDragItemCard\&.DragInfo\fP from, \fBUIInventory\fP destUIInv, int num=1)"
.br
.ti -1c
.RI "\fBTransaction\fP (\fBDragItemCard\&.DragInfo\fP from, \fBDragItemCard\&.DragInfo\fP to, int num=1)"
.br
.ti -1c
.RI "\fBTransaction\fP (\fBButtonGrid\fP button, int num=1, \fBInvOwner\fP owner=null)"
.br
.ti -1c
.RI "bool \fBProcess\fP (bool startTransaction=false)"
.br
.ti -1c
.RI "int \fBGetPrice\fP ()"
.br
.ti -1c
.RI "bool \fBIsValid\fP ()"
.br
.ti -1c
.RI "string \fBGetTextDetail\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBThing\fP \fBthing\fP"
.br
.ti -1c
.RI "\fBButtonGrid\fP \fBbutton\fP"
.br
.ti -1c
.RI "int \fBnum\fP = 1"
.br
.ti -1c
.RI "\fBDragItemCard\&.DragInfo\fP \fBfrom\fP"
.br
.ti -1c
.RI "\fBDragItemCard\&.DragInfo\fP \fBto\fP"
.br
.ti -1c
.RI "\fBUIInventory\fP \fBdestUIInv\fP"
.br
.ti -1c
.RI "\fBInvOwner\fP \fBinv\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static \fBInvOwner\&.ErrorMessage\fP \fBerror\fP = new \fBInvOwner\&.ErrorMessage\fP()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBInvOwner\fP \fBdestInv\fP\fR [get]\fP"
.br
.ti -1c
.RI "bool \fBsell\fP\fR [get]\fP"
.br
.ti -1c
.RI "string \fBIDCurrency\fP\fR [get]\fP"
.br
.ti -1c
.RI "CurrencyType \fBcurrency\fP\fR [get]\fP"
.br
.ti -1c
.RI "bool \fBFreeTrade\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB1479\fP of file \fBInvOwner\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "InvOwner\&.Transaction\&.Transaction (\fBDragItemCard\&.DragInfo\fP from, \fBUIInventory\fP destUIInv, int num = \fR1\fP)"

.PP
Definition at line \fB1544\fP of file \fBInvOwner\&.cs\fP\&.
.SS "InvOwner\&.Transaction\&.Transaction (\fBDragItemCard\&.DragInfo\fP from, \fBDragItemCard\&.DragInfo\fP to, int num = \fR1\fP)"

.PP
Definition at line \fB1555\fP of file \fBInvOwner\&.cs\fP\&.
.SS "InvOwner\&.Transaction\&.Transaction (\fBButtonGrid\fP button, int num = \fR1\fP, \fBInvOwner\fP owner = \fRnull\fP)"

.PP
Definition at line \fB1566\fP of file \fBInvOwner\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "int InvOwner\&.Transaction\&.GetPrice ()"

.PP
Definition at line \fB1791\fP of file \fBInvOwner\&.cs\fP\&.
.SS "string InvOwner\&.Transaction\&.GetTextDetail ()"

.PP
Definition at line \fB1892\fP of file \fBInvOwner\&.cs\fP\&.
.SS "bool InvOwner\&.Transaction\&.IsValid ()"

.PP
Definition at line \fB1801\fP of file \fBInvOwner\&.cs\fP\&.
.SS "bool InvOwner\&.Transaction\&.Process (bool startTransaction = \fRfalse\fP)"

.PP
Definition at line \fB1575\fP of file \fBInvOwner\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBButtonGrid\fP InvOwner\&.Transaction\&.button"

.PP
Definition at line \fB1908\fP of file \fBInvOwner\&.cs\fP\&.
.SS "\fBUIInventory\fP InvOwner\&.Transaction\&.destUIInv"

.PP
Definition at line \fB1920\fP of file \fBInvOwner\&.cs\fP\&.
.SS "\fBInvOwner\&.ErrorMessage\fP InvOwner\&.Transaction\&.error = new \fBInvOwner\&.ErrorMessage\fP()\fR [static]\fP"

.PP
Definition at line \fB1902\fP of file \fBInvOwner\&.cs\fP\&.
.SS "\fBDragItemCard\&.DragInfo\fP InvOwner\&.Transaction\&.from"

.PP
Definition at line \fB1914\fP of file \fBInvOwner\&.cs\fP\&.
.SS "\fBInvOwner\fP InvOwner\&.Transaction\&.inv"

.PP
Definition at line \fB1923\fP of file \fBInvOwner\&.cs\fP\&.
.SS "int InvOwner\&.Transaction\&.num = 1"

.PP
Definition at line \fB1911\fP of file \fBInvOwner\&.cs\fP\&.
.SS "\fBThing\fP InvOwner\&.Transaction\&.thing"

.PP
Definition at line \fB1905\fP of file \fBInvOwner\&.cs\fP\&.
.SS "\fBDragItemCard\&.DragInfo\fP InvOwner\&.Transaction\&.to"

.PP
Definition at line \fB1917\fP of file \fBInvOwner\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "CurrencyType InvOwner\&.Transaction\&.currency\fR [get]\fP"

.PP
Definition at line \fB1525\fP of file \fBInvOwner\&.cs\fP\&.
.SS "\fBInvOwner\fP InvOwner\&.Transaction\&.destInv\fR [get]\fP"

.PP
Definition at line \fB1483\fP of file \fBInvOwner\&.cs\fP\&.
.SS "bool InvOwner\&.Transaction\&.FreeTrade\fR [get]\fP"

.PP
Definition at line \fB1535\fP of file \fBInvOwner\&.cs\fP\&.
.SS "string InvOwner\&.Transaction\&.IDCurrency\fR [get]\fP"

.PP
Definition at line \fB1515\fP of file \fBInvOwner\&.cs\fP\&.
.SS "bool InvOwner\&.Transaction\&.sell\fR [get]\fP"

.PP
Definition at line \fB1505\fP of file \fBInvOwner\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
