.TH "InvOwner.ListInteraction" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
InvOwner.ListInteraction
.SH SYNOPSIS
.br
.PP
.PP
Inherits List< InvOwner\&.Interaction >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBInvOwner\&.Interaction\fP \fBAdd\fP (string s, int priority, Action action)"
.br
.ti -1c
.RI "bool \fBContains\fP (string s)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB1943\fP of file \fBInvOwner\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBInvOwner\&.Interaction\fP InvOwner\&.ListInteraction\&.Add (string s, int priority, Action action)"

.PP
Definition at line \fB1946\fP of file \fBInvOwner\&.cs\fP\&.
.SS "bool InvOwner\&.ListInteraction\&.Contains (string s)"

.PP
Definition at line \fB1959\fP of file \fBInvOwner\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
