.TH "IPathfinder" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IPathfinder
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBAlgorithms\&.PathFinder\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBFindPath\fP (\fBPathProgress\fP progress)"
.br
.ti -1c
.RI "void \fBInit\fP (\fBIPathfindGrid\fP _grid, \fBWeightCell\fP[,] _weightMap, int size)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB5\fP of file \fBIPathfinder\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
