.TH "IPathfindWalker" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IPathfindWalker
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBChara\fP\&.
.SH "Detailed Description"
.PP 
Definition at line \fB4\fP of file \fBIPathfindWalker\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
