.TH "IRenderer" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IRenderer
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBRenderData\fP, and \fBRenderObject\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBRenderToRenderCam\fP (\fBRenderParam\fP p)"
.br
.ti -1c
.RI "void \fBDraw\fP (\fBRenderParam\fP p)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB4\fP of file \fBIRenderer\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
