.TH "IRenderSource" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IRenderSource
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBCard\fP, and \fBRenderRow\fP\&.
.SH "Detailed Description"
.PP 
Definition at line \fB4\fP of file \fBIRenderSource\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
