.TH "ISyncScreen" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ISyncScreen
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBRenderObject\fP, and \fBTaskDesignation\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBOnEnterScreen\fP ()"
.br
.ti -1c
.RI "void \fBOnLeaveScreen\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "long \fBSync\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB4\fP of file \fBISyncScreen\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "long ISyncScreen\&.Sync\fR [get]\fP"

.PP
Definition at line \fB8\fP of file \fBISyncScreen\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
