.TH "ItemGeneral" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ItemGeneral
.SH SYNOPSIS
.br
.PP
.PP
Inherits UIItem, and \fBIPrefImage\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetChara\fP (\fBChara\fP c)"
.br
.ti -1c
.RI "\fBRenderRow\fP \fBGetRenderRow\fP ()"
.br
.ti -1c
.RI "void \fBOnRefreshPref\fP ()"
.br
.ti -1c
.RI "void \fBClear\fP ()"
.br
.ti -1c
.RI "UIButton \fBAddSubButton\fP (Sprite sprite, Action action, string lang=null, Action< UITooltip > onTooltip=null)"
.br
.ti -1c
.RI "void \fBSetMainText\fP (string lang, Sprite sprite=null, bool disableMask=true)"
.br
.ti -1c
.RI "UIButton \fBSetSubText\fP (string lang, int x, FontColor c=FontColor\&.Default, TextAnchor align=TextAnchor\&.MiddleLeft)"
.br
.ti -1c
.RI "UIButton \fBSetSubText2\fP (string lang, FontColor c=FontColor\&.Default, TextAnchor align=TextAnchor\&.MiddleRight)"
.br
.ti -1c
.RI "T \fBAddPrefab< T >\fP (string id)"
.br
.ti -1c
.RI "void \fBSetSound\fP (SoundData data=null)"
.br
.ti -1c
.RI "void \fBDisableIcon\fP ()"
.br
.ti -1c
.RI "void \fBDisableMask\fP ()"
.br
.ti -1c
.RI "void \fBBuild\fP ()"
.br
.in -1c

Public Member Functions inherited from \fBIPrefImage\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "LayoutGroup \fBlayout\fP"
.br
.ti -1c
.RI "int \fBpaddingSubText\fP = 50"
.br
.ti -1c
.RI "\fBCard\fP \fBcard\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB6\fP of file \fBItemGeneral\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "T ItemGeneral\&.AddPrefab< T > (string id)"

.PP
\fBType Constraints\fP
.TP
\fIT\fP : \fIComponent\fP
.PP
Definition at line \fB128\fP of file \fBItemGeneral\&.cs\fP\&.
.SS "UIButton ItemGeneral\&.AddSubButton (Sprite sprite, Action action, string lang = \fRnull\fP, Action< UITooltip > onTooltip = \fRnull\fP)"

.PP
Definition at line \fB62\fP of file \fBItemGeneral\&.cs\fP\&.
.SS "void ItemGeneral\&.Build ()"

.PP
Definition at line \fB157\fP of file \fBItemGeneral\&.cs\fP\&.
.SS "void ItemGeneral\&.Clear ()"

.PP
Definition at line \fB46\fP of file \fBItemGeneral\&.cs\fP\&.
.SS "void ItemGeneral\&.DisableIcon ()"

.PP
Definition at line \fB140\fP of file \fBItemGeneral\&.cs\fP\&.
.SS "void ItemGeneral\&.DisableMask ()"

.PP
Definition at line \fB151\fP of file \fBItemGeneral\&.cs\fP\&.
.SS "\fBRenderRow\fP ItemGeneral\&.GetRenderRow ()"

.PP
Implements \fBIPrefImage\fP\&.
.PP
Definition at line \fB26\fP of file \fBItemGeneral\&.cs\fP\&.
.SS "void ItemGeneral\&.OnRefreshPref ()"

.PP
Implements \fBIPrefImage\fP\&.
.PP
Definition at line \fB37\fP of file \fBItemGeneral\&.cs\fP\&.
.SS "void ItemGeneral\&.SetChara (\fBChara\fP c)"

.PP
Definition at line \fB9\fP of file \fBItemGeneral\&.cs\fP\&.
.SS "void ItemGeneral\&.SetMainText (string lang, Sprite sprite = \fRnull\fP, bool disableMask = \fRtrue\fP)"

.PP
Definition at line \fB88\fP of file \fBItemGeneral\&.cs\fP\&.
.SS "void ItemGeneral\&.SetSound (SoundData data = \fRnull\fP)"

.PP
Definition at line \fB134\fP of file \fBItemGeneral\&.cs\fP\&.
.SS "UIButton ItemGeneral\&.SetSubText (string lang, int x, FontColor c = \fRFontColor::Default\fP, TextAnchor align = \fRTextAnchor::MiddleLeft\fP)"

.PP
Definition at line \fB108\fP of file \fBItemGeneral\&.cs\fP\&.
.SS "UIButton ItemGeneral\&.SetSubText2 (string lang, FontColor c = \fRFontColor::Default\fP, TextAnchor align = \fRTextAnchor::MiddleRight\fP)"

.PP
Definition at line \fB119\fP of file \fBItemGeneral\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBCard\fP ItemGeneral\&.card"

.PP
Definition at line \fB182\fP of file \fBItemGeneral\&.cs\fP\&.
.SS "LayoutGroup ItemGeneral\&.layout"

.PP
Definition at line \fB176\fP of file \fBItemGeneral\&.cs\fP\&.
.SS "int ItemGeneral\&.paddingSubText = 50"

.PP
Definition at line \fB179\fP of file \fBItemGeneral\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
