.TH "ItemCulture" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ItemCulture
.SH SYNOPSIS
.br
.PP
.PP
Inherits UIItem\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBRefresh\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBid\fP"
.br
.ti -1c
.RI "UIText \fBtextLv\fP"
.br
.ti -1c
.RI "UIText \fBtextSkills\fP"
.br
.ti -1c
.RI "UIText \fBtextInvest\fP"
.br
.ti -1c
.RI "UIText \fBtextHearth\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB5\fP of file \fBItemCulture\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void ItemCulture\&.Refresh ()"

.PP
Definition at line \fB8\fP of file \fBItemCulture\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "string ItemCulture\&.id"

.PP
Definition at line \fB48\fP of file \fBItemCulture\&.cs\fP\&.
.SS "UIText ItemCulture\&.textHearth"

.PP
Definition at line \fB60\fP of file \fBItemCulture\&.cs\fP\&.
.SS "UIText ItemCulture\&.textInvest"

.PP
Definition at line \fB57\fP of file \fBItemCulture\&.cs\fP\&.
.SS "UIText ItemCulture\&.textLv"

.PP
Definition at line \fB51\fP of file \fBItemCulture\&.cs\fP\&.
.SS "UIText ItemCulture\&.textSkills"

.PP
Definition at line \fB54\fP of file \fBItemCulture\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
