.TH "ItemGachaResult" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ItemGachaResult
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBEMono\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetChara\fP (\fBChara\fP c, \fBLayerGachaResult\fP _layer)"
.br
.ti -1c
.RI "int \fBGetMedal\fP ()"
.br
.ti -1c
.RI "void \fBConfirm\fP (bool add)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "UIButton \fBbuttonGet\fP"
.br
.ti -1c
.RI "UIButton \fBbuttonDump\fP"
.br
.ti -1c
.RI "\fBPortrait\fP \fBportrait\fP"
.br
.ti -1c
.RI "\fBChara\fP \fBchara\fP"
.br
.ti -1c
.RI "UIText \fBtextName\fP"
.br
.ti -1c
.RI "UIText \fBtextBio\fP"
.br
.ti -1c
.RI "UIText \fBtextJob\fP"
.br
.ti -1c
.RI "UIText \fBtextDetail\fP"
.br
.ti -1c
.RI "UIText \fBtextResult\fP"
.br
.ti -1c
.RI "UIText \fBtextHobby\fP"
.br
.ti -1c
.RI "UIText \fBtextWork\fP"
.br
.ti -1c
.RI "UIText \fBtextLifeStyle\fP"
.br
.ti -1c
.RI "\fBLayerGachaResult\fP \fBlayer\fP"
.br
.ti -1c
.RI "LayoutGroup \fBlayoutTag\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Static Public Member Functions inherited from \fBEMono\fP
.in +1c
.ti -1c
.RI "static int \fBrnd\fP (int a)"
.br
.in -1c

Static Public Attributes inherited from \fBEMono\fP
.in +1c
.ti -1c
.RI "static \fBCore\fP \fBcore\fP"
.br
.in -1c

Properties inherited from \fBEMono\fP
.in +1c
.ti -1c
.RI "static \fBGame\fP \fBgame\fP\fR [get]\fP"
.br
.ti -1c
.RI "static bool \fBAdvMode\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBPlayer\fP \fBplayer\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBChara\fP \fBpc\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBUI\fP \fBui\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBMap\fP \fB_map\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBZone\fP \fB_zone\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranchOrHomeBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFaction\fP \fBHome\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBScene\fP \fBscene\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBBaseGameScreen\fP \fBscreen\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameSetting\fP \fBsetting\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameData\fP \fBgamedata\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBColorProfile\fP \fBColors\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBWorld\fP \fBworld\fP\fR [get]\fP"
.br
.ti -1c
.RI "static SoundManager \fBSound\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBsources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBeditorSources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBCoreDebug\fP \fBdebug\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB7\fP of file \fBItemGachaResult\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void ItemGachaResult\&.Confirm (bool add)"

.PP
Definition at line \fB62\fP of file \fBItemGachaResult\&.cs\fP\&.
.SS "int ItemGachaResult\&.GetMedal ()"

.PP
Definition at line \fB56\fP of file \fBItemGachaResult\&.cs\fP\&.
.SS "void ItemGachaResult\&.SetChara (\fBChara\fP c, \fBLayerGachaResult\fP _layer)"

.PP
Definition at line \fB10\fP of file \fBItemGachaResult\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "UIButton ItemGachaResult\&.buttonDump"

.PP
Definition at line \fB88\fP of file \fBItemGachaResult\&.cs\fP\&.
.SS "UIButton ItemGachaResult\&.buttonGet"

.PP
Definition at line \fB85\fP of file \fBItemGachaResult\&.cs\fP\&.
.SS "\fBChara\fP ItemGachaResult\&.chara"

.PP
Definition at line \fB94\fP of file \fBItemGachaResult\&.cs\fP\&.
.SS "\fBLayerGachaResult\fP ItemGachaResult\&.layer"

.PP
Definition at line \fB121\fP of file \fBItemGachaResult\&.cs\fP\&.
.SS "LayoutGroup ItemGachaResult\&.layoutTag"

.PP
Definition at line \fB124\fP of file \fBItemGachaResult\&.cs\fP\&.
.SS "\fBPortrait\fP ItemGachaResult\&.portrait"

.PP
Definition at line \fB91\fP of file \fBItemGachaResult\&.cs\fP\&.
.SS "UIText ItemGachaResult\&.textBio"

.PP
Definition at line \fB100\fP of file \fBItemGachaResult\&.cs\fP\&.
.SS "UIText ItemGachaResult\&.textDetail"

.PP
Definition at line \fB106\fP of file \fBItemGachaResult\&.cs\fP\&.
.SS "UIText ItemGachaResult\&.textHobby"

.PP
Definition at line \fB112\fP of file \fBItemGachaResult\&.cs\fP\&.
.SS "UIText ItemGachaResult\&.textJob"

.PP
Definition at line \fB103\fP of file \fBItemGachaResult\&.cs\fP\&.
.SS "UIText ItemGachaResult\&.textLifeStyle"

.PP
Definition at line \fB118\fP of file \fBItemGachaResult\&.cs\fP\&.
.SS "UIText ItemGachaResult\&.textName"

.PP
Definition at line \fB97\fP of file \fBItemGachaResult\&.cs\fP\&.
.SS "UIText ItemGachaResult\&.textResult"

.PP
Definition at line \fB109\fP of file \fBItemGachaResult\&.cs\fP\&.
.SS "UIText ItemGachaResult\&.textWork"

.PP
Definition at line \fB115\fP of file \fBItemGachaResult\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
