.TH "ItemMod" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ItemMod
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBEMono\fP\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "UIButton \fBbuttonActivate\fP"
.br
.ti -1c
.RI "UIButton \fBbuttonBG\fP"
.br
.ti -1c
.RI "UIButton \fBbuttonLock\fP"
.br
.ti -1c
.RI "UIButton \fBbuttonUp\fP"
.br
.ti -1c
.RI "UIButton \fBbuttonDown\fP"
.br
.ti -1c
.RI "UIButton \fBbuttonToggle\fP"
.br
.ti -1c
.RI "Image \fBimageActive\fP"
.br
.ti -1c
.RI "Image \fBimageLock\fP"
.br
.ti -1c
.RI "\fBWidget\&.Config\fP \fBconfig\fP"
.br
.ti -1c
.RI "BaseModPackage \fBpackage\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Static Public Member Functions inherited from \fBEMono\fP
.in +1c
.ti -1c
.RI "static int \fBrnd\fP (int a)"
.br
.in -1c

Static Public Attributes inherited from \fBEMono\fP
.in +1c
.ti -1c
.RI "static \fBCore\fP \fBcore\fP"
.br
.in -1c

Properties inherited from \fBEMono\fP
.in +1c
.ti -1c
.RI "static \fBGame\fP \fBgame\fP\fR [get]\fP"
.br
.ti -1c
.RI "static bool \fBAdvMode\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBPlayer\fP \fBplayer\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBChara\fP \fBpc\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBUI\fP \fBui\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBMap\fP \fB_map\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBZone\fP \fB_zone\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranchOrHomeBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFaction\fP \fBHome\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBScene\fP \fBscene\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBBaseGameScreen\fP \fBscreen\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameSetting\fP \fBsetting\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameData\fP \fBgamedata\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBColorProfile\fP \fBColors\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBWorld\fP \fBworld\fP\fR [get]\fP"
.br
.ti -1c
.RI "static SoundManager \fBSound\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBsources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBeditorSources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBCoreDebug\fP \fBdebug\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB5\fP of file \fBItemMod\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "UIButton ItemMod\&.buttonActivate"

.PP
Definition at line \fB8\fP of file \fBItemMod\&.cs\fP\&.
.SS "UIButton ItemMod\&.buttonBG"

.PP
Definition at line \fB11\fP of file \fBItemMod\&.cs\fP\&.
.SS "UIButton ItemMod\&.buttonDown"

.PP
Definition at line \fB20\fP of file \fBItemMod\&.cs\fP\&.
.SS "UIButton ItemMod\&.buttonLock"

.PP
Definition at line \fB14\fP of file \fBItemMod\&.cs\fP\&.
.SS "UIButton ItemMod\&.buttonToggle"

.PP
Definition at line \fB23\fP of file \fBItemMod\&.cs\fP\&.
.SS "UIButton ItemMod\&.buttonUp"

.PP
Definition at line \fB17\fP of file \fBItemMod\&.cs\fP\&.
.SS "\fBWidget\&.Config\fP ItemMod\&.config"

.PP
Definition at line \fB32\fP of file \fBItemMod\&.cs\fP\&.
.SS "Image ItemMod\&.imageActive"

.PP
Definition at line \fB26\fP of file \fBItemMod\&.cs\fP\&.
.SS "Image ItemMod\&.imageLock"

.PP
Definition at line \fB29\fP of file \fBItemMod\&.cs\fP\&.
.SS "BaseModPackage ItemMod\&.package"

.PP
Definition at line \fB35\fP of file \fBItemMod\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
