.TH "ItemResearch" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ItemResearch
.SH SYNOPSIS
.br
.PP
.PP
Inherits UIItem\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetPlan\fP (\fBResearchPlan\fP p, UIList list, \fBFactionBranch\fP branch, \fBLayerTech\fP layer)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Image \fBimageExp\fP"
.br
.ti -1c
.RI "Image \fBgoFocus\fP"
.br
.ti -1c
.RI "\fBResearchPlan\fP \fBplan\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB5\fP of file \fBItemResearch\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void ItemResearch\&.SetPlan (\fBResearchPlan\fP p, UIList list, \fBFactionBranch\fP branch, \fBLayerTech\fP layer)"

.PP
Definition at line \fB8\fP of file \fBItemResearch\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "Image ItemResearch\&.goFocus"

.PP
Definition at line \fB55\fP of file \fBItemResearch\&.cs\fP\&.
.SS "Image ItemResearch\&.imageExp"

.PP
Definition at line \fB52\fP of file \fBItemResearch\&.cs\fP\&.
.SS "\fBResearchPlan\fP ItemResearch\&.plan"

.PP
Definition at line \fB58\fP of file \fBItemResearch\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
