.TH "KnowledgeList< T >" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KnowledgeList< T >
.SH SYNOPSIS
.br
.PP
.PP
Inherits HashSet< string >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "new void \fBAdd\fP (string id)"
.br
.ti -1c
.RI "void \fBAdd\fP (T k)"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBType Constraints\fP
.TP
\fIT\fP : \fI\fBKnowledge\fP\fP
.PP
Definition at line \fB5\fP of file \fBKnowledgeList\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "new void \fBKnowledgeList\fP< T >\&.Add (string id)"

.PP
Definition at line \fB8\fP of file \fBKnowledgeList\&.cs\fP\&.
.SS "void \fBKnowledgeList\fP< T >\&.Add (T k)"

.PP
Definition at line \fB13\fP of file \fBKnowledgeList\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
