.TH "LayerPeople" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LayerPeople
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBELayer\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBMode\fP { \fBDefault\fP, \fBSelect\fP, \fBDouble\fP, \fBHire\fP }"
.br
.ti -1c
.RI "enum \fBShowMode\fP { \fBJob\fP, \fBRace\fP, \fBWork\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override bool \fBHeaderIsListOf\fP (int id)"
.br
.ti -1c
.RI "override void \fBOnInit\fP ()"
.br
.ti -1c
.RI "\fBLayerPeople\fP \fBSetOnConfirm\fP (Action _onConfirm)"
.br
.ti -1c
.RI "void \fBConfirm\fP ()"
.br
.ti -1c
.RI "override void \fBOnKill\fP ()"
.br
.ti -1c
.RI "override void \fBOnSwitchContent\fP (Window window)"
.br
.in -1c

Public Member Functions inherited from \fBELayer\fP
.in +1c
.ti -1c
.RI "override void \fBOnBeforeAddLayer\fP ()"
.br
.ti -1c
.RI "void \fBInitInspector\fP ()"
.br
.ti -1c
.RI "override void \fBInit\fP ()"
.br
.ti -1c
.RI "override void \fBOnAfterAddLayer\fP ()"
.br
.ti -1c
.RI "void \fBTryShowHelp\fP ()"
.br
.ti -1c
.RI "void \fBAddLayerToUI\fP (string id)"
.br
.ti -1c
.RI "void \fBTryShowHint\fP (string _langHint=null)"
.br
.ti -1c
.RI "void \fBTalkHomeMemeber\fP (string id)"
.br
.ti -1c
.RI "void \fBTalkMaid\fP (string id)"
.br
.ti -1c
.RI "override void \fBOnRightClick\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBLayerPeople\fP \fBCreate\fP (LayerPeople\&.Mode mode)"
.br
.ti -1c
.RI "static \fBLayerPeople\fP \fBCreate< T >\fP (string langHint=null, \fBChara\fP owner=null)"
.br
.ti -1c
.RI "static \fBLayerPeople\fP \fBCreateReserve\fP ()"
.br
.ti -1c
.RI "static \fBLayerPeople\fP \fBCreateGraze\fP (\fBAreaType\fP areaType)"
.br
.ti -1c
.RI "static \fBLayerPeople\fP \fBCreateSelectEmbarkMembers\fP (List< \fBChara\fP > settlers)"
.br
.ti -1c
.RI "static \fBLayerPeople\fP \fBCreate\fP (\fBBaseListPeople\fP list)"
.br
.ti -1c
.RI "static \fBLayerPeople\fP \fBCreateSelect\fP (string langHeader, string langHint, Action< UIList > onList, Action< \fBChara\fP > onClick, Func< \fBChara\fP, string > _onShowSubText=null)"
.br
.in -1c

Static Public Member Functions inherited from \fBELayer\fP
.in +1c
.ti -1c
.RI "static int \fBrnd\fP (int a)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "LayerPeople\&.ShowMode \fBshowMode\fP"
.br
.ti -1c
.RI "LayoutGroup \fBlayoutMenu\fP"
.br
.ti -1c
.RI "Action \fBonConfirm\fP"
.br
.ti -1c
.RI "\fBUIMultiList\fP \fBmulti\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static \fBChara\fP \fBslaveToBuy\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Protected Member Functions inherited from \fBELayer\fP
.in +1c
.ti -1c
.RI "override void \fB_Close\fP ()"
.br
.ti -1c
.RI "override void \fBKill\fP ()"
.br
.in -1c

Properties inherited from \fBELayer\fP
.in +1c
.ti -1c
.RI "static \fBCore\fP \fBcore\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGame\fP \fBgame\fP\fR [get]\fP"
.br
.ti -1c
.RI "static bool \fBAdvMode\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBPlayer\fP \fBplayer\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBChara\fP \fBpc\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFaction\fP \fBHome\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBUI\fP \fBui\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBMap\fP \fB_map\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBZone\fP \fB_zone\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBScene\fP \fBscene\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBBaseGameScreen\fP \fBscreen\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBCoreConfig\fP \fBconfig\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameSetting\fP \fBsetting\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBColorProfile\fP \fBColors\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBsources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBWorld\fP \fBworld\fP\fR [get]\fP"
.br
.ti -1c
.RI "static SoundManager \fBSound\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBCoreDebug\fP \fBdebug\fP\fR [get]\fP"
.br
.ti -1c
.RI "bool \fBIsFloat\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual string \fBIdHelp\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB6\fP of file \fBLayerPeople\&.cs\fP\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "enum LayerPeople\&.Mode"

.PP
Definition at line \fB183\fP of file \fBLayerPeople\&.cs\fP\&.
.SS "enum LayerPeople\&.ShowMode"

.PP
Definition at line \fB196\fP of file \fBLayerPeople\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void LayerPeople\&.Confirm ()"

.PP
Definition at line \fB49\fP of file \fBLayerPeople\&.cs\fP\&.
.SS "static \fBLayerPeople\fP LayerPeople\&.Create (\fBBaseListPeople\fP list)\fR [static]\fP"

.PP
Definition at line \fB144\fP of file \fBLayerPeople\&.cs\fP\&.
.SS "static \fBLayerPeople\fP LayerPeople\&.Create (LayerPeople\&.Mode mode)\fR [static]\fP"

.PP
Definition at line \fB78\fP of file \fBLayerPeople\&.cs\fP\&.
.SS "static \fBLayerPeople\fP LayerPeople\&.Create< T > (string langHint = \fRnull\fP, \fBChara\fP owner = \fRnull\fP)\fR [static]\fP"

.PP
\fBType Constraints\fP
.TP
\fIT\fP : \fI\fBBaseListPeople\fP\fP
.PP
Definition at line \fB89\fP of file \fBLayerPeople\&.cs\fP\&.
.SS "static \fBLayerPeople\fP LayerPeople\&.CreateGraze (\fBAreaType\fP areaType)\fR [static]\fP"

.PP
Definition at line \fB113\fP of file \fBLayerPeople\&.cs\fP\&.
.SS "static \fBLayerPeople\fP LayerPeople\&.CreateReserve ()\fR [static]\fP"

.PP
Definition at line \fB100\fP of file \fBLayerPeople\&.cs\fP\&.
.SS "static \fBLayerPeople\fP LayerPeople\&.CreateSelect (string langHeader, string langHint, Action< UIList > onList, Action< \fBChara\fP > onClick, Func< \fBChara\fP, string > _onShowSubText = \fRnull\fP)\fR [static]\fP"

.PP
Definition at line \fB152\fP of file \fBLayerPeople\&.cs\fP\&.
.SS "static \fBLayerPeople\fP LayerPeople\&.CreateSelectEmbarkMembers (List< \fBChara\fP > settlers)\fR [static]\fP"

.PP
Definition at line \fB119\fP of file \fBLayerPeople\&.cs\fP\&.
.SS "override bool LayerPeople\&.HeaderIsListOf (int id)"

.PP
Definition at line \fB9\fP of file \fBLayerPeople\&.cs\fP\&.
.SS "override void LayerPeople\&.OnInit ()"

.PP
Definition at line \fB15\fP of file \fBLayerPeople\&.cs\fP\&.
.SS "override void LayerPeople\&.OnKill ()"

.PP
Definition at line \fB59\fP of file \fBLayerPeople\&.cs\fP\&.
.SS "override void LayerPeople\&.OnSwitchContent (Window window)"

.PP
Definition at line \fB67\fP of file \fBLayerPeople\&.cs\fP\&.
.SS "\fBLayerPeople\fP LayerPeople\&.SetOnConfirm (Action _onConfirm)"

.PP
Definition at line \fB42\fP of file \fBLayerPeople\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "LayoutGroup LayerPeople\&.layoutMenu"

.PP
Definition at line \fB174\fP of file \fBLayerPeople\&.cs\fP\&.
.SS "\fBUIMultiList\fP LayerPeople\&.multi"

.PP
Definition at line \fB180\fP of file \fBLayerPeople\&.cs\fP\&.
.SS "Action LayerPeople\&.onConfirm"

.PP
Definition at line \fB177\fP of file \fBLayerPeople\&.cs\fP\&.
.SS "LayerPeople\&.ShowMode LayerPeople\&.showMode"

.PP
Definition at line \fB171\fP of file \fBLayerPeople\&.cs\fP\&.
.SS "\fBChara\fP LayerPeople\&.slaveToBuy\fR [static]\fP"

.PP
Definition at line \fB168\fP of file \fBLayerPeople\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
