.TH "LayerTitle.TitleType" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LayerTitle.TitleType
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Color \fBlight\fP"
.br
.ti -1c
.RI "Color \fBfog\fP"
.br
.ti -1c
.RI "Sprite \fBbg\fP"
.br
.ti -1c
.RI "BGMData \fBbgm\fP"
.br
.ti -1c
.RI "BGMData \fBbgmTitle\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB215\fP of file \fBLayerTitle\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "Sprite LayerTitle\&.TitleType\&.bg"

.PP
Definition at line \fB224\fP of file \fBLayerTitle\&.cs\fP\&.
.SS "BGMData LayerTitle\&.TitleType\&.bgm"

.PP
Definition at line \fB227\fP of file \fBLayerTitle\&.cs\fP\&.
.SS "BGMData LayerTitle\&.TitleType\&.bgmTitle"

.PP
Definition at line \fB230\fP of file \fBLayerTitle\&.cs\fP\&.
.SS "Color LayerTitle\&.TitleType\&.fog"

.PP
Definition at line \fB221\fP of file \fBLayerTitle\&.cs\fP\&.
.SS "Color LayerTitle\&.TitleType\&.light"

.PP
Definition at line \fB218\fP of file \fBLayerTitle\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
