.TH "LayerConfig" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LayerConfig
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBELayer\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override string \fBGetTextHeader\fP (Window window)"
.br
.ti -1c
.RI "override void \fBOnBeforeAddLayer\fP ()"
.br
.ti -1c
.RI "override void \fBOnInit\fP ()"
.br
.ti -1c
.RI "override void \fBOnSwitchContent\fP (Window window)"
.br
.ti -1c
.RI "void \fBValidateResolution\fP ()"
.br
.ti -1c
.RI "override void \fBOnKill\fP ()"
.br
.ti -1c
.RI "void \fBRefresh\fP ()"
.br
.ti -1c
.RI "void \fBSetFont\fP (SkinManager\&.FontSaveData data, UIItem item, string lang)"
.br
.ti -1c
.RI "void \fBApplyFont\fP ()"
.br
.ti -1c
.RI "void \fBSetSlider\fP (Slider slider, float value, Func< float, string > action, bool notify=false)"
.br
.ti -1c
.RI "void \fBSetGroup\fP (UISelectableGroup group, int value, UnityAction< int > action)"
.br
.in -1c

Public Member Functions inherited from \fBELayer\fP
.in +1c
.ti -1c
.RI "override void \fBOnBeforeAddLayer\fP ()"
.br
.ti -1c
.RI "void \fBInitInspector\fP ()"
.br
.ti -1c
.RI "override void \fBInit\fP ()"
.br
.ti -1c
.RI "override void \fBOnAfterAddLayer\fP ()"
.br
.ti -1c
.RI "void \fBTryShowHelp\fP ()"
.br
.ti -1c
.RI "void \fBAddLayerToUI\fP (string id)"
.br
.ti -1c
.RI "void \fBTryShowHint\fP (string _langHint=null)"
.br
.ti -1c
.RI "void \fBTalkHomeMemeber\fP (string id)"
.br
.ti -1c
.RI "void \fBTalkMaid\fP (string id)"
.br
.ti -1c
.RI "override void \fBOnRightClick\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Slider \fBsliderMaster\fP"
.br
.ti -1c
.RI "Slider \fBsliderBGM\fP"
.br
.ti -1c
.RI "Slider \fBsliderSFX\fP"
.br
.ti -1c
.RI "Slider \fBsliderAMB\fP"
.br
.ti -1c
.RI "Slider \fBsliderBrightness\fP"
.br
.ti -1c
.RI "Slider \fBsliderContrast\fP"
.br
.ti -1c
.RI "Slider \fBsliderSaturation\fP"
.br
.ti -1c
.RI "Slider \fBsliderVibrance\fP"
.br
.ti -1c
.RI "Slider \fBsliderScrollSense\fP"
.br
.ti -1c
.RI "Slider \fBsliderScale\fP"
.br
.ti -1c
.RI "Slider \fBsliderSharpen\fP"
.br
.ti -1c
.RI "Slider \fBsliderSharpen2\fP"
.br
.ti -1c
.RI "Slider \fBsliderBlur\fP"
.br
.ti -1c
.RI "UISelectableGroup \fBgroupVSync\fP"
.br
.ti -1c
.RI "UISelectableGroup \fBgroupLang\fP"
.br
.ti -1c
.RI "UIButton \fBtoggleVsync\fP"
.br
.ti -1c
.RI "UIButton \fBtoggleFixedResolution\fP"
.br
.ti -1c
.RI "UIButton \fBtoggleOpenLastTab\fP"
.br
.ti -1c
.RI "UIButton \fBtoggleRightClickClose\fP"
.br
.ti -1c
.RI "UIButton \fBtoggleFullscreen\fP"
.br
.ti -1c
.RI "UIButton \fBtogglePixelPerfectUI\fP"
.br
.ti -1c
.RI "UIButton \fBtoggleBloom\fP"
.br
.ti -1c
.RI "UIButton \fBtoggleHDR\fP"
.br
.ti -1c
.RI "UIButton \fBtoggleBlur\fP"
.br
.ti -1c
.RI "UIButton \fBtoggleAutoscale\fP"
.br
.ti -1c
.RI "UIButton \fBtoggleDynamicBrightness\fP"
.br
.ti -1c
.RI "UIButton \fBtoggleKuwahara\fP"
.br
.ti -1c
.RI "UIButton \fBtoggleBlizzard\fP"
.br
.ti -1c
.RI "UIButton \fBtoggleDisableShake\fP"
.br
.ti -1c
.RI "UIButton \fBtoggleFirefly\fP"
.br
.ti -1c
.RI "UIButton \fBtoggleSecureWidth\fP"
.br
.ti -1c
.RI "UIButton \fBtoggleGradientWater\fP"
.br
.ti -1c
.RI "UIButton \fBtoggleGodray\fP"
.br
.ti -1c
.RI "UIButton \fBtoggleShowFloatButtons\fP"
.br
.ti -1c
.RI "UIButton \fBtoggleAllyLight\fP"
.br
.ti -1c
.RI "UIButton \fBtoggleBalloon\fP"
.br
.ti -1c
.RI "UIItem \fBfontUI\fP"
.br
.ti -1c
.RI "UIItem \fBfontChatbox\fP"
.br
.ti -1c
.RI "UIItem \fBfontBalloon\fP"
.br
.ti -1c
.RI "UIItem \fBfontDialog\fP"
.br
.ti -1c
.RI "UIItem \fBfontWidget\fP"
.br
.ti -1c
.RI "UIItem \fBfontNews\fP"
.br
.ti -1c
.RI "UIDropdown \fBddPostEffect\fP"
.br
.ti -1c
.RI "UIButton \fBbuttonReset\fP"
.br
.ti -1c
.RI "Slider \fBsliderUIBrightness\fP"
.br
.ti -1c
.RI "Slider \fBsliderUIContrast\fP"
.br
.ti -1c
.RI "Slider \fBsliderBalloon\fP"
.br
.ti -1c
.RI "LayoutGroup \fBlayoutLanguage\fP"
.br
.ti -1c
.RI "UIButton \fBmoldLanguage\fP"
.br
.ti -1c
.RI "UIButton \fBbuttonApplyScreenSize\fP"
.br
.ti -1c
.RI "InputField \fBinputW\fP"
.br
.ti -1c
.RI "InputField \fBinputH\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Static Public Member Functions inherited from \fBELayer\fP
.in +1c
.ti -1c
.RI "static int \fBrnd\fP (int a)"
.br
.in -1c

Protected Member Functions inherited from \fBELayer\fP
.in +1c
.ti -1c
.RI "override void \fB_Close\fP ()"
.br
.ti -1c
.RI "override void \fBKill\fP ()"
.br
.in -1c

Properties inherited from \fBELayer\fP
.in +1c
.ti -1c
.RI "static \fBCore\fP \fBcore\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGame\fP \fBgame\fP\fR [get]\fP"
.br
.ti -1c
.RI "static bool \fBAdvMode\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBPlayer\fP \fBplayer\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBChara\fP \fBpc\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFaction\fP \fBHome\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBUI\fP \fBui\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBMap\fP \fB_map\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBZone\fP \fB_zone\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBScene\fP \fBscene\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBBaseGameScreen\fP \fBscreen\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBCoreConfig\fP \fBconfig\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameSetting\fP \fBsetting\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBColorProfile\fP \fBColors\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBsources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBWorld\fP \fBworld\fP\fR [get]\fP"
.br
.ti -1c
.RI "static SoundManager \fBSound\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBCoreDebug\fP \fBdebug\fP\fR [get]\fP"
.br
.ti -1c
.RI "bool \fBIsFloat\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual string \fBIdHelp\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB9\fP of file \fBLayerConfig\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void LayerConfig\&.ApplyFont ()"

.PP
Definition at line \fB436\fP of file \fBLayerConfig\&.cs\fP\&.
.SS "override string LayerConfig\&.GetTextHeader (Window window)"

.PP
Definition at line \fB12\fP of file \fBLayerConfig\&.cs\fP\&.
.SS "override void LayerConfig\&.OnBeforeAddLayer ()"

.PP
Definition at line \fB18\fP of file \fBLayerConfig\&.cs\fP\&.
.SS "override void LayerConfig\&.OnInit ()"

.PP
Definition at line \fB24\fP of file \fBLayerConfig\&.cs\fP\&.
.SS "override void LayerConfig\&.OnKill ()"

.PP
Definition at line \fB116\fP of file \fBLayerConfig\&.cs\fP\&.
.SS "override void LayerConfig\&.OnSwitchContent (Window window)"

.PP
Definition at line \fB88\fP of file \fBLayerConfig\&.cs\fP\&.
.SS "void LayerConfig\&.Refresh ()"

.PP
Definition at line \fB125\fP of file \fBLayerConfig\&.cs\fP\&.
.SS "void LayerConfig\&.SetFont (SkinManager\&.FontSaveData data, UIItem item, string lang)"

.PP
Definition at line \fB394\fP of file \fBLayerConfig\&.cs\fP\&.
.SS "void LayerConfig\&.SetGroup (UISelectableGroup group, int value, UnityAction< int > action)"

.PP
Definition at line \fB462\fP of file \fBLayerConfig\&.cs\fP\&.
.SS "void LayerConfig\&.SetSlider (Slider slider, float value, Func< float, string > action, bool notify = \fRfalse\fP)"

.PP
Definition at line \fB443\fP of file \fBLayerConfig\&.cs\fP\&.
.SS "void LayerConfig\&.ValidateResolution ()"

.PP
Definition at line \fB105\fP of file \fBLayerConfig\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "UIButton LayerConfig\&.buttonApplyScreenSize"

.PP
Definition at line \fB615\fP of file \fBLayerConfig\&.cs\fP\&.
.SS "UIButton LayerConfig\&.buttonReset"

.PP
Definition at line \fB597\fP of file \fBLayerConfig\&.cs\fP\&.
.SS "UIDropdown LayerConfig\&.ddPostEffect"

.PP
Definition at line \fB594\fP of file \fBLayerConfig\&.cs\fP\&.
.SS "UIItem LayerConfig\&.fontBalloon"

.PP
Definition at line \fB582\fP of file \fBLayerConfig\&.cs\fP\&.
.SS "UIItem LayerConfig\&.fontChatbox"

.PP
Definition at line \fB579\fP of file \fBLayerConfig\&.cs\fP\&.
.SS "UIItem LayerConfig\&.fontDialog"

.PP
Definition at line \fB585\fP of file \fBLayerConfig\&.cs\fP\&.
.SS "UIItem LayerConfig\&.fontNews"

.PP
Definition at line \fB591\fP of file \fBLayerConfig\&.cs\fP\&.
.SS "UIItem LayerConfig\&.fontUI"

.PP
Definition at line \fB576\fP of file \fBLayerConfig\&.cs\fP\&.
.SS "UIItem LayerConfig\&.fontWidget"

.PP
Definition at line \fB588\fP of file \fBLayerConfig\&.cs\fP\&.
.SS "UISelectableGroup LayerConfig\&.groupLang"

.PP
Definition at line \fB510\fP of file \fBLayerConfig\&.cs\fP\&.
.SS "UISelectableGroup LayerConfig\&.groupVSync"

.PP
Definition at line \fB507\fP of file \fBLayerConfig\&.cs\fP\&.
.SS "InputField LayerConfig\&.inputH"

.PP
Definition at line \fB621\fP of file \fBLayerConfig\&.cs\fP\&.
.SS "InputField LayerConfig\&.inputW"

.PP
Definition at line \fB618\fP of file \fBLayerConfig\&.cs\fP\&.
.SS "LayoutGroup LayerConfig\&.layoutLanguage"

.PP
Definition at line \fB609\fP of file \fBLayerConfig\&.cs\fP\&.
.SS "UIButton LayerConfig\&.moldLanguage"

.PP
Definition at line \fB612\fP of file \fBLayerConfig\&.cs\fP\&.
.SS "Slider LayerConfig\&.sliderAMB"

.PP
Definition at line \fB477\fP of file \fBLayerConfig\&.cs\fP\&.
.SS "Slider LayerConfig\&.sliderBalloon"

.PP
Definition at line \fB606\fP of file \fBLayerConfig\&.cs\fP\&.
.SS "Slider LayerConfig\&.sliderBGM"

.PP
Definition at line \fB471\fP of file \fBLayerConfig\&.cs\fP\&.
.SS "Slider LayerConfig\&.sliderBlur"

.PP
Definition at line \fB504\fP of file \fBLayerConfig\&.cs\fP\&.
.SS "Slider LayerConfig\&.sliderBrightness"

.PP
Definition at line \fB480\fP of file \fBLayerConfig\&.cs\fP\&.
.SS "Slider LayerConfig\&.sliderContrast"

.PP
Definition at line \fB483\fP of file \fBLayerConfig\&.cs\fP\&.
.SS "Slider LayerConfig\&.sliderMaster"

.PP
Definition at line \fB468\fP of file \fBLayerConfig\&.cs\fP\&.
.SS "Slider LayerConfig\&.sliderSaturation"

.PP
Definition at line \fB486\fP of file \fBLayerConfig\&.cs\fP\&.
.SS "Slider LayerConfig\&.sliderScale"

.PP
Definition at line \fB495\fP of file \fBLayerConfig\&.cs\fP\&.
.SS "Slider LayerConfig\&.sliderScrollSense"

.PP
Definition at line \fB492\fP of file \fBLayerConfig\&.cs\fP\&.
.SS "Slider LayerConfig\&.sliderSFX"

.PP
Definition at line \fB474\fP of file \fBLayerConfig\&.cs\fP\&.
.SS "Slider LayerConfig\&.sliderSharpen"

.PP
Definition at line \fB498\fP of file \fBLayerConfig\&.cs\fP\&.
.SS "Slider LayerConfig\&.sliderSharpen2"

.PP
Definition at line \fB501\fP of file \fBLayerConfig\&.cs\fP\&.
.SS "Slider LayerConfig\&.sliderUIBrightness"

.PP
Definition at line \fB600\fP of file \fBLayerConfig\&.cs\fP\&.
.SS "Slider LayerConfig\&.sliderUIContrast"

.PP
Definition at line \fB603\fP of file \fBLayerConfig\&.cs\fP\&.
.SS "Slider LayerConfig\&.sliderVibrance"

.PP
Definition at line \fB489\fP of file \fBLayerConfig\&.cs\fP\&.
.SS "UIButton LayerConfig\&.toggleAllyLight"

.PP
Definition at line \fB570\fP of file \fBLayerConfig\&.cs\fP\&.
.SS "UIButton LayerConfig\&.toggleAutoscale"

.PP
Definition at line \fB540\fP of file \fBLayerConfig\&.cs\fP\&.
.SS "UIButton LayerConfig\&.toggleBalloon"

.PP
Definition at line \fB573\fP of file \fBLayerConfig\&.cs\fP\&.
.SS "UIButton LayerConfig\&.toggleBlizzard"

.PP
Definition at line \fB549\fP of file \fBLayerConfig\&.cs\fP\&.
.SS "UIButton LayerConfig\&.toggleBloom"

.PP
Definition at line \fB531\fP of file \fBLayerConfig\&.cs\fP\&.
.SS "UIButton LayerConfig\&.toggleBlur"

.PP
Definition at line \fB537\fP of file \fBLayerConfig\&.cs\fP\&.
.SS "UIButton LayerConfig\&.toggleDisableShake"

.PP
Definition at line \fB552\fP of file \fBLayerConfig\&.cs\fP\&.
.SS "UIButton LayerConfig\&.toggleDynamicBrightness"

.PP
Definition at line \fB543\fP of file \fBLayerConfig\&.cs\fP\&.
.SS "UIButton LayerConfig\&.toggleFirefly"

.PP
Definition at line \fB555\fP of file \fBLayerConfig\&.cs\fP\&.
.SS "UIButton LayerConfig\&.toggleFixedResolution"

.PP
Definition at line \fB516\fP of file \fBLayerConfig\&.cs\fP\&.
.SS "UIButton LayerConfig\&.toggleFullscreen"

.PP
Definition at line \fB525\fP of file \fBLayerConfig\&.cs\fP\&.
.SS "UIButton LayerConfig\&.toggleGodray"

.PP
Definition at line \fB564\fP of file \fBLayerConfig\&.cs\fP\&.
.SS "UIButton LayerConfig\&.toggleGradientWater"

.PP
Definition at line \fB561\fP of file \fBLayerConfig\&.cs\fP\&.
.SS "UIButton LayerConfig\&.toggleHDR"

.PP
Definition at line \fB534\fP of file \fBLayerConfig\&.cs\fP\&.
.SS "UIButton LayerConfig\&.toggleKuwahara"

.PP
Definition at line \fB546\fP of file \fBLayerConfig\&.cs\fP\&.
.SS "UIButton LayerConfig\&.toggleOpenLastTab"

.PP
Definition at line \fB519\fP of file \fBLayerConfig\&.cs\fP\&.
.SS "UIButton LayerConfig\&.togglePixelPerfectUI"

.PP
Definition at line \fB528\fP of file \fBLayerConfig\&.cs\fP\&.
.SS "UIButton LayerConfig\&.toggleRightClickClose"

.PP
Definition at line \fB522\fP of file \fBLayerConfig\&.cs\fP\&.
.SS "UIButton LayerConfig\&.toggleSecureWidth"

.PP
Definition at line \fB558\fP of file \fBLayerConfig\&.cs\fP\&.
.SS "UIButton LayerConfig\&.toggleShowFloatButtons"

.PP
Definition at line \fB567\fP of file \fBLayerConfig\&.cs\fP\&.
.SS "UIButton LayerConfig\&.toggleVsync"

.PP
Definition at line \fB513\fP of file \fBLayerConfig\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
