.TH "LayerAbility" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LayerAbility
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBELayer\fP, and IDragParent\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBConfig\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnInit\fP ()"
.br
.ti -1c
.RI "void \fBRefreshConfig\fP ()"
.br
.ti -1c
.RI "override void \fBOnSwitchContent\fP (Window window)"
.br
.ti -1c
.RI "override void \fBOnUpdateInput\fP ()"
.br
.ti -1c
.RI "void \fBSelectGroup\fP (string id)"
.br
.ti -1c
.RI "void \fB_Redraw\fP ()"
.br
.ti -1c
.RI "void \fBOnStartDrag\fP (UIButton b)"
.br
.ti -1c
.RI "void \fBOnDrag\fP (UIButton b)"
.br
.ti -1c
.RI "void \fBOnEndDrag\fP (UIButton b, bool cancel=false)"
.br
.ti -1c
.RI "void \fBOnDisable\fP ()"
.br
.in -1c

Public Member Functions inherited from \fBELayer\fP
.in +1c
.ti -1c
.RI "override void \fBOnBeforeAddLayer\fP ()"
.br
.ti -1c
.RI "void \fBInitInspector\fP ()"
.br
.ti -1c
.RI "override void \fBInit\fP ()"
.br
.ti -1c
.RI "override void \fBOnAfterAddLayer\fP ()"
.br
.ti -1c
.RI "void \fBTryShowHelp\fP ()"
.br
.ti -1c
.RI "void \fBAddLayerToUI\fP (string id)"
.br
.ti -1c
.RI "void \fBTryShowHint\fP (string _langHint=null)"
.br
.ti -1c
.RI "void \fBTalkHomeMemeber\fP (string id)"
.br
.ti -1c
.RI "void \fBTalkMaid\fP (string id)"
.br
.ti -1c
.RI "override void \fBOnRightClick\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBSetDirty\fP (\fBElement\fP a)"
.br
.ti -1c
.RI "static void \fBClearHotElement\fP ()"
.br
.ti -1c
.RI "static void \fBRedraw\fP ()"
.br
.in -1c

Static Public Member Functions inherited from \fBELayer\fP
.in +1c
.ti -1c
.RI "static int \fBrnd\fP (int a)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "UIDynamicList \fBlist\fP"
.br
.ti -1c
.RI "\fBChara\fP \fBchara\fP"
.br
.ti -1c
.RI "Transform \fBheaderRow\fP"
.br
.ti -1c
.RI "string[] \fBidGroup\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static \fBLayerAbility\fP \fBInstance\fP"
.br
.ti -1c
.RI "static \fBButtonAbility\fP \fBhotElement\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "new \fBLayerAbility\&.Config\fP \fBconfig\fP\fR [get]\fP"
.br
.in -1c

Properties inherited from \fBELayer\fP
.in +1c
.ti -1c
.RI "static \fBCore\fP \fBcore\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGame\fP \fBgame\fP\fR [get]\fP"
.br
.ti -1c
.RI "static bool \fBAdvMode\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBPlayer\fP \fBplayer\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBChara\fP \fBpc\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFaction\fP \fBHome\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBUI\fP \fBui\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBMap\fP \fB_map\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBZone\fP \fB_zone\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBScene\fP \fBscene\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBBaseGameScreen\fP \fBscreen\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBCoreConfig\fP \fBconfig\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameSetting\fP \fBsetting\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBColorProfile\fP \fBColors\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBsources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBWorld\fP \fBworld\fP\fR [get]\fP"
.br
.ti -1c
.RI "static SoundManager \fBSound\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBCoreDebug\fP \fBdebug\fP\fR [get]\fP"
.br
.ti -1c
.RI "bool \fBIsFloat\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual string \fBIdHelp\fP\fR [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Protected Member Functions inherited from \fBELayer\fP
.in +1c
.ti -1c
.RI "override void \fB_Close\fP ()"
.br
.ti -1c
.RI "override void \fBKill\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB6\fP of file \fBLayerAbility\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void LayerAbility\&._Redraw ()"

.PP
Definition at line \fB217\fP of file \fBLayerAbility\&.cs\fP\&.
.SS "static void LayerAbility\&.ClearHotElement ()\fR [static]\fP"

.PP
Definition at line \fB142\fP of file \fBLayerAbility\&.cs\fP\&.
.SS "void LayerAbility\&.OnDisable ()"

.PP
Definition at line \fB260\fP of file \fBLayerAbility\&.cs\fP\&.
.SS "void LayerAbility\&.OnDrag (UIButton b)"

.PP
Definition at line \fB229\fP of file \fBLayerAbility\&.cs\fP\&.
.SS "void LayerAbility\&.OnEndDrag (UIButton b, bool cancel = \fRfalse\fP)"

.PP
Definition at line \fB246\fP of file \fBLayerAbility\&.cs\fP\&.
.SS "override void LayerAbility\&.OnInit ()"

.PP
Definition at line \fB19\fP of file \fBLayerAbility\&.cs\fP\&.
.SS "void LayerAbility\&.OnStartDrag (UIButton b)"

.PP
Definition at line \fB223\fP of file \fBLayerAbility\&.cs\fP\&.
.SS "override void LayerAbility\&.OnSwitchContent (Window window)"

.PP
Definition at line \fB119\fP of file \fBLayerAbility\&.cs\fP\&.
.SS "override void LayerAbility\&.OnUpdateInput ()"

.PP
Definition at line \fB126\fP of file \fBLayerAbility\&.cs\fP\&.
.SS "static void LayerAbility\&.Redraw ()\fR [static]\fP"

.PP
Definition at line \fB208\fP of file \fBLayerAbility\&.cs\fP\&.
.SS "void LayerAbility\&.RefreshConfig ()"

.PP
Definition at line \fB74\fP of file \fBLayerAbility\&.cs\fP\&.
.SS "void LayerAbility\&.SelectGroup (string id)"

.PP
Definition at line \fB156\fP of file \fBLayerAbility\&.cs\fP\&.
.SS "static void LayerAbility\&.SetDirty (\fBElement\fP a)\fR [static]\fP"

.PP
Definition at line \fB87\fP of file \fBLayerAbility\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBChara\fP LayerAbility\&.chara"

.PP
Definition at line \fB277\fP of file \fBLayerAbility\&.cs\fP\&.
.SS "Transform LayerAbility\&.headerRow"

.PP
Definition at line \fB280\fP of file \fBLayerAbility\&.cs\fP\&.
.SS "\fBButtonAbility\fP LayerAbility\&.hotElement\fR [static]\fP"

.PP
Definition at line \fB271\fP of file \fBLayerAbility\&.cs\fP\&.
.SS "string [] LayerAbility\&.idGroup"
\fBInitial value:\fP
.nf
= new string[]
    {
        "all",
        "attack",
        "defense",
        "util",
        "ability",
        "favAbility"
    }
.PP
.fi

.PP
Definition at line \fB284\fP of file \fBLayerAbility\&.cs\fP\&.
.SS "\fBLayerAbility\fP LayerAbility\&.Instance\fR [static]\fP"

.PP
Definition at line \fB268\fP of file \fBLayerAbility\&.cs\fP\&.
.SS "UIDynamicList LayerAbility\&.list"

.PP
Definition at line \fB274\fP of file \fBLayerAbility\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "new \fBLayerAbility\&.Config\fP LayerAbility\&.config\fR [get]\fP"

.PP
Definition at line \fB10\fP of file \fBLayerAbility\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
