.TH "LayerList" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LayerList
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBELayer\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCustomItem\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnInit\fP ()"
.br
.ti -1c
.RI "override void \fBOnUpdateInput\fP ()"
.br
.ti -1c
.RI "\fBLayerList\fP \fBSetMold\fP (int index)"
.br
.ti -1c
.RI "\fBLayerList\fP \fBSetSize\fP (float w=450f, float h=\-1f)"
.br
.ti -1c
.RI "\fBLayerList\fP \fBSetPivot\fP (float x, float y=\-1f)"
.br
.ti -1c
.RI "void \fBRefreshSize\fP ()"
.br
.ti -1c
.RI "\fBLayerList\fP \fBSetList< TValue >\fP (ICollection< TValue > items, Func< TValue, string > getString, Action< int, string > onSelect, bool autoClose=true)"
.br
.ti -1c
.RI "\fBLayerList\fP \fBSetStringList\fP (Func< ICollection< string > > getList, Action< int, string > onSelect, bool autoClose=true)"
.br
.ti -1c
.RI "\fBLayerList\fP \fBSetList2< TValue >\fP (ICollection< TValue > _list, Func< TValue, string > getText, Action< TValue, \fBItemGeneral\fP > onClick, Action< TValue, \fBItemGeneral\fP > onInstantiate, bool autoClose=true)"
.br
.ti -1c
.RI "\fBLayerList\fP \fBSetListCheck< TValue >\fP (ICollection< TValue > _list, Func< TValue, string > getText, Action< TValue, \fBItemGeneral\fP > onClick, Action< List< UIList\&.ButtonPair > > onValidate)"
.br
.ti -1c
.RI "\fBLayerList\fP \fBEnableReroll\fP ()"
.br
.ti -1c
.RI "\fBLayerList\fP \fBManualList\fP (Action< UIList, \fBLayerList\fP > onInit)"
.br
.ti -1c
.RI "\fBLayerList\fP \fBSetHeader\fP (string lang)"
.br
.ti -1c
.RI "\fBLayerList\fP \fBSetNoSound\fP ()"
.br
.ti -1c
.RI "void \fBSetHighlightTarget\fP (UIButton _target)"
.br
.ti -1c
.RI "override void \fBOnKill\fP ()"
.br
.ti -1c
.RI "void \fBAdd\fP (string lang, Action< int > action)"
.br
.ti -1c
.RI "void \fBShow\fP (bool autoClose=true)"
.br
.in -1c

Public Member Functions inherited from \fBELayer\fP
.in +1c
.ti -1c
.RI "override void \fBOnBeforeAddLayer\fP ()"
.br
.ti -1c
.RI "void \fBInitInspector\fP ()"
.br
.ti -1c
.RI "override void \fBInit\fP ()"
.br
.ti -1c
.RI "override void \fBOnAfterAddLayer\fP ()"
.br
.ti -1c
.RI "void \fBTryShowHelp\fP ()"
.br
.ti -1c
.RI "void \fBAddLayerToUI\fP (string id)"
.br
.ti -1c
.RI "void \fBTryShowHint\fP (string _langHint=null)"
.br
.ti -1c
.RI "void \fBTalkHomeMemeber\fP (string id)"
.br
.ti -1c
.RI "void \fBTalkMaid\fP (string id)"
.br
.ti -1c
.RI "override void \fBOnRightClick\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "UIList \fBlist\fP"
.br
.ti -1c
.RI "UIButton \fBbuttonReroll\fP"
.br
.ti -1c
.RI "UIButton \fBhighlightTarget\fP"
.br
.ti -1c
.RI "UIItem \fBmoldItemCheck\fP"
.br
.ti -1c
.RI "Transform \fBmoldItemGeneral\fP"
.br
.ti -1c
.RI "Transform \fBmoldItemDetail\fP"
.br
.ti -1c
.RI "bool \fBuseItem\fP"
.br
.ti -1c
.RI "bool \fBautoX\fP"
.br
.ti -1c
.RI "bool \fBautoY\fP"
.br
.ti -1c
.RI "bool \fBnoSound\fP"
.br
.ti -1c
.RI "UIScrollView \fBscroll\fP"
.br
.ti -1c
.RI "Vector2 \fBsizeMin\fP"
.br
.ti -1c
.RI "Vector2 \fBsizeMax\fP"
.br
.ti -1c
.RI "Vector2 \fBpaddings\fP"
.br
.ti -1c
.RI "List< \fBLayerList\&.CustomItem\fP > \fBcustomItems\fP = new List<\fBLayerList\&.CustomItem\fP>()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBAwake\fP ()"
.br
.in -1c

Protected Member Functions inherited from \fBELayer\fP
.in +1c
.ti -1c
.RI "override void \fB_Close\fP ()"
.br
.ti -1c
.RI "override void \fBKill\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"


Static Public Member Functions inherited from \fBELayer\fP
.in +1c
.ti -1c
.RI "static int \fBrnd\fP (int a)"
.br
.in -1c

Properties inherited from \fBELayer\fP
.in +1c
.ti -1c
.RI "static \fBCore\fP \fBcore\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGame\fP \fBgame\fP\fR [get]\fP"
.br
.ti -1c
.RI "static bool \fBAdvMode\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBPlayer\fP \fBplayer\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBChara\fP \fBpc\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFaction\fP \fBHome\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBUI\fP \fBui\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBMap\fP \fB_map\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBZone\fP \fB_zone\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBScene\fP \fBscene\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBBaseGameScreen\fP \fBscreen\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBCoreConfig\fP \fBconfig\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameSetting\fP \fBsetting\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBColorProfile\fP \fBColors\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBsources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBWorld\fP \fBworld\fP\fR [get]\fP"
.br
.ti -1c
.RI "static SoundManager \fBSound\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBCoreDebug\fP \fBdebug\fP\fR [get]\fP"
.br
.ti -1c
.RI "bool \fBIsFloat\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual string \fBIdHelp\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB7\fP of file \fBLayerList\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void LayerList\&.Add (string lang, Action< int > action)"

.PP
Definition at line \fB316\fP of file \fBLayerList\&.cs\fP\&.
.SS "override void LayerList\&.Awake ()\fR [protected]\fP"

.PP
Definition at line \fB10\fP of file \fBLayerList\&.cs\fP\&.
.SS "\fBLayerList\fP LayerList\&.EnableReroll ()"

.PP
Definition at line \fB229\fP of file \fBLayerList\&.cs\fP\&.
.SS "\fBLayerList\fP LayerList\&.ManualList (Action< UIList, \fBLayerList\fP > onInit)"

.PP
Definition at line \fB243\fP of file \fBLayerList\&.cs\fP\&.
.SS "override void LayerList\&.OnInit ()"

.PP
Definition at line \fB20\fP of file \fBLayerList\&.cs\fP\&.
.SS "override void LayerList\&.OnKill ()"

.PP
Definition at line \fB293\fP of file \fBLayerList\&.cs\fP\&.
.SS "override void LayerList\&.OnUpdateInput ()"

.PP
Definition at line \fB30\fP of file \fBLayerList\&.cs\fP\&.
.SS "void LayerList\&.RefreshSize ()"

.PP
Definition at line \fB87\fP of file \fBLayerList\&.cs\fP\&.
.SS "\fBLayerList\fP LayerList\&.SetHeader (string lang)"

.PP
Definition at line \fB254\fP of file \fBLayerList\&.cs\fP\&.
.SS "void LayerList\&.SetHighlightTarget (UIButton _target)"

.PP
Definition at line \fB268\fP of file \fBLayerList\&.cs\fP\&.
.SS "\fBLayerList\fP LayerList\&.SetList2< TValue > (ICollection< TValue > _list, Func< TValue, string > getText, Action< TValue, \fBItemGeneral\fP > onClick, Action< TValue, \fBItemGeneral\fP > onInstantiate, bool autoClose = \fRtrue\fP)"

.PP
Definition at line \fB154\fP of file \fBLayerList\&.cs\fP\&.
.SS "\fBLayerList\fP LayerList\&.SetList< TValue > (ICollection< TValue > items, Func< TValue, string > getString, Action< int, string > onSelect, bool autoClose = \fRtrue\fP)"

.PP
Definition at line \fB106\fP of file \fBLayerList\&.cs\fP\&.
.SS "\fBLayerList\fP LayerList\&.SetListCheck< TValue > (ICollection< TValue > _list, Func< TValue, string > getText, Action< TValue, \fBItemGeneral\fP > onClick, Action< List< UIList\&.ButtonPair > > onValidate)"

.PP
Definition at line \fB188\fP of file \fBLayerList\&.cs\fP\&.
.SS "\fBLayerList\fP LayerList\&.SetMold (int index)"

.PP
Definition at line \fB47\fP of file \fBLayerList\&.cs\fP\&.
.SS "\fBLayerList\fP LayerList\&.SetNoSound ()"

.PP
Definition at line \fB261\fP of file \fBLayerList\&.cs\fP\&.
.SS "\fBLayerList\fP LayerList\&.SetPivot (float x, float y = \fR\-1f\fP)"

.PP
Definition at line \fB80\fP of file \fBLayerList\&.cs\fP\&.
.SS "\fBLayerList\fP LayerList\&.SetSize (float w = \fR450f\fP, float h = \fR\-1f\fP)"

.PP
Definition at line \fB64\fP of file \fBLayerList\&.cs\fP\&.
.SS "\fBLayerList\fP LayerList\&.SetStringList (Func< ICollection< string > > getList, Action< int, string > onSelect, bool autoClose = \fRtrue\fP)"

.PP
Definition at line \fB118\fP of file \fBLayerList\&.cs\fP\&.
.SS "void LayerList\&.Show (bool autoClose = \fRtrue\fP)"

.PP
Definition at line \fB331\fP of file \fBLayerList\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "bool LayerList\&.autoX"

.PP
Definition at line \fB388\fP of file \fBLayerList\&.cs\fP\&.
.SS "bool LayerList\&.autoY"

.PP
Definition at line \fB391\fP of file \fBLayerList\&.cs\fP\&.
.SS "UIButton LayerList\&.buttonReroll"

.PP
Definition at line \fB370\fP of file \fBLayerList\&.cs\fP\&.
.SS "List<\fBLayerList\&.CustomItem\fP> LayerList\&.customItems = new List<\fBLayerList\&.CustomItem\fP>()"

.PP
Definition at line \fB412\fP of file \fBLayerList\&.cs\fP\&.
.SS "UIButton LayerList\&.highlightTarget"

.PP
Definition at line \fB373\fP of file \fBLayerList\&.cs\fP\&.
.SS "UIList LayerList\&.list"

.PP
Definition at line \fB367\fP of file \fBLayerList\&.cs\fP\&.
.SS "UIItem LayerList\&.moldItemCheck"

.PP
Definition at line \fB376\fP of file \fBLayerList\&.cs\fP\&.
.SS "Transform LayerList\&.moldItemDetail"

.PP
Definition at line \fB382\fP of file \fBLayerList\&.cs\fP\&.
.SS "Transform LayerList\&.moldItemGeneral"

.PP
Definition at line \fB379\fP of file \fBLayerList\&.cs\fP\&.
.SS "bool LayerList\&.noSound"

.PP
Definition at line \fB394\fP of file \fBLayerList\&.cs\fP\&.
.SS "Vector2 LayerList\&.paddings"

.PP
Definition at line \fB406\fP of file \fBLayerList\&.cs\fP\&.
.SS "UIScrollView LayerList\&.scroll"

.PP
Definition at line \fB397\fP of file \fBLayerList\&.cs\fP\&.
.SS "Vector2 LayerList\&.sizeMax"

.PP
Definition at line \fB403\fP of file \fBLayerList\&.cs\fP\&.
.SS "Vector2 LayerList\&.sizeMin"

.PP
Definition at line \fB400\fP of file \fBLayerList\&.cs\fP\&.
.SS "bool LayerList\&.useItem"

.PP
Definition at line \fB385\fP of file \fBLayerList\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
