.TH "LayerList.CustomItem" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LayerList.CustomItem
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBlang\fP"
.br
.ti -1c
.RI "Action< int > \fBaction\fP"
.br
.ti -1c
.RI "int \fBid\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB415\fP of file \fBLayerList\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "Action<int> LayerList\&.CustomItem\&.action"

.PP
Definition at line \fB421\fP of file \fBLayerList\&.cs\fP\&.
.SS "int LayerList\&.CustomItem\&.id"

.PP
Definition at line \fB424\fP of file \fBLayerList\&.cs\fP\&.
.SS "string LayerList\&.CustomItem\&.lang"

.PP
Definition at line \fB418\fP of file \fBLayerList\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
