.TH "LayerEditPlaylist" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LayerEditPlaylist
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBELayer\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBListBGM\fP"
.br
.in -1c
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBMode\fP { \fBPlaylist\fP, \fBLotBGM\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnInit\fP ()"
.br
.ti -1c
.RI "void \fBActivate\fP (\fBTraitJukeBox\fP _box)"
.br
.ti -1c
.RI "void \fBActivate\fP (\fBTraitHouseBoard\fP _board)"
.br
.ti -1c
.RI "void \fBActivate\fP (LayerEditPlaylist\&.Mode _mode=LayerEditPlaylist\&.Mode\&.Playlist)"
.br
.ti -1c
.RI "void \fBRefresh\fP ()"
.br
.ti -1c
.RI "void \fBTogglePL\fP ()"
.br
.ti -1c
.RI "override void \fBOnKill\fP ()"
.br
.ti -1c
.RI "override void \fBOnSwitchContent\fP (Window window)"
.br
.in -1c

Public Member Functions inherited from \fBELayer\fP
.in +1c
.ti -1c
.RI "override void \fBOnBeforeAddLayer\fP ()"
.br
.ti -1c
.RI "void \fBInitInspector\fP ()"
.br
.ti -1c
.RI "override void \fBInit\fP ()"
.br
.ti -1c
.RI "override void \fBOnAfterAddLayer\fP ()"
.br
.ti -1c
.RI "void \fBTryShowHelp\fP ()"
.br
.ti -1c
.RI "void \fBAddLayerToUI\fP (string id)"
.br
.ti -1c
.RI "void \fBTryShowHint\fP (string _langHint=null)"
.br
.ti -1c
.RI "void \fBTalkHomeMemeber\fP (string id)"
.br
.ti -1c
.RI "void \fBTalkMaid\fP (string id)"
.br
.ti -1c
.RI "override void \fBOnRightClick\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "List< BGMData > \fBitemsDay\fP = new List<BGMData>()"
.br
.ti -1c
.RI "List< BGMData > \fBitemsNight\fP = new List<BGMData>()"
.br
.ti -1c
.RI "\fBUIMultiList\fP \fBmulti\fP"
.br
.ti -1c
.RI "bool \fBday\fP"
.br
.ti -1c
.RI "bool \fBkeepPlaying\fP"
.br
.ti -1c
.RI "bool \fBsingle\fP"
.br
.ti -1c
.RI "bool \fBdayNight\fP"
.br
.ti -1c
.RI "LayerEditPlaylist\&.Mode \fBmode\fP"
.br
.ti -1c
.RI "\fBTraitHouseBoard\fP \fBboard\fP"
.br
.ti -1c
.RI "\fBTraitJukeBox\fP \fBjukebox\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "Dictionary< int, BGMData > \fBbgms\fP\fR [get]\fP"
.br
.in -1c

Properties inherited from \fBELayer\fP
.in +1c
.ti -1c
.RI "static \fBCore\fP \fBcore\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGame\fP \fBgame\fP\fR [get]\fP"
.br
.ti -1c
.RI "static bool \fBAdvMode\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBPlayer\fP \fBplayer\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBChara\fP \fBpc\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFaction\fP \fBHome\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBUI\fP \fBui\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBMap\fP \fB_map\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBZone\fP \fB_zone\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBScene\fP \fBscene\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBBaseGameScreen\fP \fBscreen\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBCoreConfig\fP \fBconfig\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameSetting\fP \fBsetting\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBColorProfile\fP \fBColors\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBsources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBWorld\fP \fBworld\fP\fR [get]\fP"
.br
.ti -1c
.RI "static SoundManager \fBSound\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBCoreDebug\fP \fBdebug\fP\fR [get]\fP"
.br
.ti -1c
.RI "bool \fBIsFloat\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual string \fBIdHelp\fP\fR [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Static Public Member Functions inherited from \fBELayer\fP
.in +1c
.ti -1c
.RI "static int \fBrnd\fP (int a)"
.br
.in -1c

Protected Member Functions inherited from \fBELayer\fP
.in +1c
.ti -1c
.RI "override void \fB_Close\fP ()"
.br
.ti -1c
.RI "override void \fBKill\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB7\fP of file \fBLayerEditPlaylist\&.cs\fP\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "enum LayerEditPlaylist\&.Mode"

.PP
Definition at line \fB220\fP of file \fBLayerEditPlaylist\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void LayerEditPlaylist\&.Activate (LayerEditPlaylist\&.Mode _mode = \fRLayerEditPlaylist::Mode::Playlist\fP)"

.PP
Definition at line \fB41\fP of file \fBLayerEditPlaylist\&.cs\fP\&.
.SS "void LayerEditPlaylist\&.Activate (\fBTraitHouseBoard\fP _board)"

.PP
Definition at line \fB33\fP of file \fBLayerEditPlaylist\&.cs\fP\&.
.SS "void LayerEditPlaylist\&.Activate (\fBTraitJukeBox\fP _box)"

.PP
Definition at line \fB25\fP of file \fBLayerEditPlaylist\&.cs\fP\&.
.SS "override void LayerEditPlaylist\&.OnInit ()"

.PP
Definition at line \fB20\fP of file \fBLayerEditPlaylist\&.cs\fP\&.
.SS "override void LayerEditPlaylist\&.OnKill ()"

.PP
Definition at line \fB152\fP of file \fBLayerEditPlaylist\&.cs\fP\&.
.SS "override void LayerEditPlaylist\&.OnSwitchContent (Window window)"

.PP
Definition at line \fB181\fP of file \fBLayerEditPlaylist\&.cs\fP\&.
.SS "void LayerEditPlaylist\&.Refresh ()"

.PP
Definition at line \fB83\fP of file \fBLayerEditPlaylist\&.cs\fP\&.
.SS "void LayerEditPlaylist\&.TogglePL ()"

.PP
Definition at line \fB143\fP of file \fBLayerEditPlaylist\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBTraitHouseBoard\fP LayerEditPlaylist\&.board"

.PP
Definition at line \fB214\fP of file \fBLayerEditPlaylist\&.cs\fP\&.
.SS "bool LayerEditPlaylist\&.day"

.PP
Definition at line \fB199\fP of file \fBLayerEditPlaylist\&.cs\fP\&.
.SS "bool LayerEditPlaylist\&.dayNight"

.PP
Definition at line \fB208\fP of file \fBLayerEditPlaylist\&.cs\fP\&.
.SS "List<BGMData> LayerEditPlaylist\&.itemsDay = new List<BGMData>()"

.PP
Definition at line \fB190\fP of file \fBLayerEditPlaylist\&.cs\fP\&.
.SS "List<BGMData> LayerEditPlaylist\&.itemsNight = new List<BGMData>()"

.PP
Definition at line \fB193\fP of file \fBLayerEditPlaylist\&.cs\fP\&.
.SS "\fBTraitJukeBox\fP LayerEditPlaylist\&.jukebox"

.PP
Definition at line \fB217\fP of file \fBLayerEditPlaylist\&.cs\fP\&.
.SS "bool LayerEditPlaylist\&.keepPlaying"

.PP
Definition at line \fB202\fP of file \fBLayerEditPlaylist\&.cs\fP\&.
.SS "LayerEditPlaylist\&.Mode LayerEditPlaylist\&.mode"

.PP
Definition at line \fB211\fP of file \fBLayerEditPlaylist\&.cs\fP\&.
.SS "\fBUIMultiList\fP LayerEditPlaylist\&.multi"

.PP
Definition at line \fB196\fP of file \fBLayerEditPlaylist\&.cs\fP\&.
.SS "bool LayerEditPlaylist\&.single"

.PP
Definition at line \fB205\fP of file \fBLayerEditPlaylist\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "Dictionary<int, BGMData> LayerEditPlaylist\&.bgms\fR [get]\fP"

.PP
Definition at line \fB11\fP of file \fBLayerEditPlaylist\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
