.TH "LayerGachaResult.Data" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LayerGachaResult.Data
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBSourceChara\&.Row\fP \fBrow\fP"
.br
.ti -1c
.RI "int \fBweight\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB154\fP of file \fBLayerGachaResult\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBSourceChara\&.Row\fP LayerGachaResult\&.Data\&.row"

.PP
Definition at line \fB157\fP of file \fBLayerGachaResult\&.cs\fP\&.
.SS "int LayerGachaResult\&.Data\&.weight"

.PP
Definition at line \fB160\fP of file \fBLayerGachaResult\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
