.TH "LayerRegisterHotbar" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LayerRegisterHotbar
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBELayer\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetItem\fP (\fBSourceElement\&.Row\fP act)"
.br
.ti -1c
.RI "\fBLayerRegisterHotbar\fP \fBSetItem\fP (\fBThing\fP t)"
.br
.ti -1c
.RI "void \fBSetItem\fP (\fBChara\fP c)"
.br
.ti -1c
.RI "\fBLayerRegisterHotbar\fP \fBSetItem\fP (\fBHotItem\fP item)"
.br
.ti -1c
.RI "void \fBShow\fP ()"
.br
.ti -1c
.RI "\fBButtonHotItem\fP \fBGetButton\fP ()"
.br
.ti -1c
.RI "bool \fBOnEndDrag\fP ()"
.br
.ti -1c
.RI "override void \fBOnKill\fP ()"
.br
.in -1c

Public Member Functions inherited from \fBELayer\fP
.in +1c
.ti -1c
.RI "override void \fBOnBeforeAddLayer\fP ()"
.br
.ti -1c
.RI "void \fBInitInspector\fP ()"
.br
.ti -1c
.RI "override void \fBInit\fP ()"
.br
.ti -1c
.RI "override void \fBOnAfterAddLayer\fP ()"
.br
.ti -1c
.RI "void \fBTryShowHelp\fP ()"
.br
.ti -1c
.RI "void \fBAddLayerToUI\fP (string id)"
.br
.ti -1c
.RI "void \fBTryShowHint\fP (string _langHint=null)"
.br
.ti -1c
.RI "void \fBTalkHomeMemeber\fP (string id)"
.br
.ti -1c
.RI "void \fBTalkMaid\fP (string id)"
.br
.ti -1c
.RI "override void \fBOnRightClick\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Image \fBmoldCover\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Static Public Member Functions inherited from \fBELayer\fP
.in +1c
.ti -1c
.RI "static int \fBrnd\fP (int a)"
.br
.in -1c

Protected Member Functions inherited from \fBELayer\fP
.in +1c
.ti -1c
.RI "override void \fB_Close\fP ()"
.br
.ti -1c
.RI "override void \fBKill\fP ()"
.br
.in -1c

Properties inherited from \fBELayer\fP
.in +1c
.ti -1c
.RI "static \fBCore\fP \fBcore\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGame\fP \fBgame\fP\fR [get]\fP"
.br
.ti -1c
.RI "static bool \fBAdvMode\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBPlayer\fP \fBplayer\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBChara\fP \fBpc\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFaction\fP \fBHome\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBUI\fP \fBui\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBMap\fP \fB_map\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBZone\fP \fB_zone\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBScene\fP \fBscene\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBBaseGameScreen\fP \fBscreen\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBCoreConfig\fP \fBconfig\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameSetting\fP \fBsetting\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBColorProfile\fP \fBColors\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBsources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBWorld\fP \fBworld\fP\fR [get]\fP"
.br
.ti -1c
.RI "static SoundManager \fBSound\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBCoreDebug\fP \fBdebug\fP\fR [get]\fP"
.br
.ti -1c
.RI "bool \fBIsFloat\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual string \fBIdHelp\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB7\fP of file \fBLayerRegisterHotbar\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBButtonHotItem\fP LayerRegisterHotbar\&.GetButton ()"

.PP
Definition at line \fB61\fP of file \fBLayerRegisterHotbar\&.cs\fP\&.
.SS "bool LayerRegisterHotbar\&.OnEndDrag ()"

.PP
Definition at line \fB77\fP of file \fBLayerRegisterHotbar\&.cs\fP\&.
.SS "override void LayerRegisterHotbar\&.OnKill ()"

.PP
Definition at line \fB89\fP of file \fBLayerRegisterHotbar\&.cs\fP\&.
.SS "void LayerRegisterHotbar\&.SetItem (\fBChara\fP c)"

.PP
Definition at line \fB25\fP of file \fBLayerRegisterHotbar\&.cs\fP\&.
.SS "\fBLayerRegisterHotbar\fP LayerRegisterHotbar\&.SetItem (\fBHotItem\fP item)"

.PP
Definition at line \fB34\fP of file \fBLayerRegisterHotbar\&.cs\fP\&.
.SS "void LayerRegisterHotbar\&.SetItem (\fBSourceElement\&.Row\fP act)"

.PP
Definition at line \fB10\fP of file \fBLayerRegisterHotbar\&.cs\fP\&.
.SS "\fBLayerRegisterHotbar\fP LayerRegisterHotbar\&.SetItem (\fBThing\fP t)"

.PP
Definition at line \fB19\fP of file \fBLayerRegisterHotbar\&.cs\fP\&.
.SS "void LayerRegisterHotbar\&.Show ()"

.PP
Definition at line \fB42\fP of file \fBLayerRegisterHotbar\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "Image LayerRegisterHotbar\&.moldCover"

.PP
Definition at line \fB104\fP of file \fBLayerRegisterHotbar\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
