.TH "LayerProgress" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LayerProgress
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBELayer\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBInit\fP (string hint)"
.br
.ti -1c
.RI "void \fBUpdate\fP ()"
.br
.in -1c

Public Member Functions inherited from \fBELayer\fP
.in +1c
.ti -1c
.RI "override void \fBOnBeforeAddLayer\fP ()"
.br
.ti -1c
.RI "void \fBInitInspector\fP ()"
.br
.ti -1c
.RI "override void \fBInit\fP ()"
.br
.ti -1c
.RI "override void \fBOnAfterAddLayer\fP ()"
.br
.ti -1c
.RI "void \fBTryShowHelp\fP ()"
.br
.ti -1c
.RI "void \fBAddLayerToUI\fP (string id)"
.br
.ti -1c
.RI "void \fBTryShowHint\fP (string _langHint=null)"
.br
.ti -1c
.RI "void \fBTalkHomeMemeber\fP (string id)"
.br
.ti -1c
.RI "void \fBTalkMaid\fP (string id)"
.br
.ti -1c
.RI "override void \fBOnRightClick\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBLayerProgress\fP \fBStartAsync\fP (string text, UniTask< bool > task, Action onCancel=null)"
.br
.ti -1c
.RI "static \fBLayerProgress\fP \fBStart\fP (string text, Action onComplete=null)"
.br
.ti -1c
.RI "static void \fBStart\fP (string text, Action thread, Action onComplete)"
.br
.in -1c

Static Public Member Functions inherited from \fBELayer\fP
.in +1c
.ti -1c
.RI "static int \fBrnd\fP (int a)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBspeed\fP"
.br
.ti -1c
.RI "float \fBminTime\fP"
.br
.ti -1c
.RI "float \fBendTime\fP"
.br
.ti -1c
.RI "float \fBminProgress\fP"
.br
.ti -1c
.RI "Slider \fBbar\fP"
.br
.ti -1c
.RI "Text \fBtext\fP"
.br
.ti -1c
.RI "Action \fBonComplete\fP"
.br
.ti -1c
.RI "Func< bool > \fBfuncComplete\fP"
.br
.ti -1c
.RI "UniTask< bool > \fBunitask\fP"
.br
.ti -1c
.RI "Action \fBonCancel\fP"
.br
.ti -1c
.RI "bool \fBuseUnitask\fP"
.br
.ti -1c
.RI "CanvasGroup \fBcg\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static bool \fBcompleted\fP"
.br
.ti -1c
.RI "static bool \fBisActive\fP"
.br
.ti -1c
.RI "static float \fBprogress\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Protected Member Functions inherited from \fBELayer\fP
.in +1c
.ti -1c
.RI "override void \fB_Close\fP ()"
.br
.ti -1c
.RI "override void \fBKill\fP ()"
.br
.in -1c

Properties inherited from \fBELayer\fP
.in +1c
.ti -1c
.RI "static \fBCore\fP \fBcore\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGame\fP \fBgame\fP\fR [get]\fP"
.br
.ti -1c
.RI "static bool \fBAdvMode\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBPlayer\fP \fBplayer\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBChara\fP \fBpc\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFaction\fP \fBHome\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBUI\fP \fBui\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBMap\fP \fB_map\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBZone\fP \fB_zone\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBScene\fP \fBscene\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBBaseGameScreen\fP \fBscreen\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBCoreConfig\fP \fBconfig\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameSetting\fP \fBsetting\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBColorProfile\fP \fBColors\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBsources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBWorld\fP \fBworld\fP\fR [get]\fP"
.br
.ti -1c
.RI "static SoundManager \fBSound\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBCoreDebug\fP \fBdebug\fP\fR [get]\fP"
.br
.ti -1c
.RI "bool \fBIsFloat\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual string \fBIdHelp\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB11\fP of file \fBLayerProgress\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void LayerProgress\&.Init (string hint)"

.PP
Definition at line \fB14\fP of file \fBLayerProgress\&.cs\fP\&.
.SS "static \fBLayerProgress\fP LayerProgress\&.Start (string text, Action onComplete = \fRnull\fP)\fR [static]\fP"

.PP
Definition at line \fB75\fP of file \fBLayerProgress\&.cs\fP\&.
.SS "static void LayerProgress\&.Start (string text, Action thread, Action onComplete)\fR [static]\fP"

.PP
Definition at line \fB84\fP of file \fBLayerProgress\&.cs\fP\&.
.SS "static \fBLayerProgress\fP LayerProgress\&.StartAsync (string text, UniTask< bool > task, Action onCancel = \fRnull\fP)\fR [static]\fP"

.PP
Definition at line \fB64\fP of file \fBLayerProgress\&.cs\fP\&.
.SS "void LayerProgress\&.Update ()"

.PP
Definition at line \fB25\fP of file \fBLayerProgress\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "Slider LayerProgress\&.bar"

.PP
Definition at line \fB124\fP of file \fBLayerProgress\&.cs\fP\&.
.SS "CanvasGroup LayerProgress\&.cg"

.PP
Definition at line \fB145\fP of file \fBLayerProgress\&.cs\fP\&.
.SS "bool LayerProgress\&.completed\fR [static]\fP"

.PP
Definition at line \fB103\fP of file \fBLayerProgress\&.cs\fP\&.
.SS "float LayerProgress\&.endTime"

.PP
Definition at line \fB118\fP of file \fBLayerProgress\&.cs\fP\&.
.SS "Func<bool> LayerProgress\&.funcComplete"

.PP
Definition at line \fB133\fP of file \fBLayerProgress\&.cs\fP\&.
.SS "bool LayerProgress\&.isActive\fR [static]\fP"

.PP
Definition at line \fB106\fP of file \fBLayerProgress\&.cs\fP\&.
.SS "float LayerProgress\&.minProgress"

.PP
Definition at line \fB121\fP of file \fBLayerProgress\&.cs\fP\&.
.SS "float LayerProgress\&.minTime"

.PP
Definition at line \fB115\fP of file \fBLayerProgress\&.cs\fP\&.
.SS "Action LayerProgress\&.onCancel"

.PP
Definition at line \fB139\fP of file \fBLayerProgress\&.cs\fP\&.
.SS "Action LayerProgress\&.onComplete"

.PP
Definition at line \fB130\fP of file \fBLayerProgress\&.cs\fP\&.
.SS "float LayerProgress\&.progress\fR [static]\fP"

.PP
Definition at line \fB109\fP of file \fBLayerProgress\&.cs\fP\&.
.SS "float LayerProgress\&.speed"

.PP
Definition at line \fB112\fP of file \fBLayerProgress\&.cs\fP\&.
.SS "Text LayerProgress\&.text"

.PP
Definition at line \fB127\fP of file \fBLayerProgress\&.cs\fP\&.
.SS "UniTask<bool> LayerProgress\&.unitask"

.PP
Definition at line \fB136\fP of file \fBLayerProgress\&.cs\fP\&.
.SS "bool LayerProgress\&.useUnitask"

.PP
Definition at line \fB142\fP of file \fBLayerProgress\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
