.TH "LayerNewspaper" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LayerNewspaper
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBELayer\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnInit\fP ()"
.br
.ti -1c
.RI "void \fBOnClickPage\fP ()"
.br
.ti -1c
.RI "void \fBRefreshPage\fP ()"
.br
.ti -1c
.RI "void \fBRefreshNews\fP ()"
.br
.ti -1c
.RI "void \fBRefreshAD\fP ()"
.br
.ti -1c
.RI "void \fBRefreshChat\fP ()"
.br
.ti -1c
.RI "void \fBRefreshVote\fP ()"
.br
.ti -1c
.RI "void \fBRefreshWeather\fP ()"
.br
.in -1c

Public Member Functions inherited from \fBELayer\fP
.in +1c
.ti -1c
.RI "override void \fBOnBeforeAddLayer\fP ()"
.br
.ti -1c
.RI "void \fBInitInspector\fP ()"
.br
.ti -1c
.RI "override void \fBInit\fP ()"
.br
.ti -1c
.RI "override void \fBOnAfterAddLayer\fP ()"
.br
.ti -1c
.RI "void \fBTryShowHelp\fP ()"
.br
.ti -1c
.RI "void \fBAddLayerToUI\fP (string id)"
.br
.ti -1c
.RI "void \fBTryShowHint\fP (string _langHint=null)"
.br
.ti -1c
.RI "void \fBTalkHomeMemeber\fP (string id)"
.br
.ti -1c
.RI "void \fBTalkMaid\fP (string id)"
.br
.ti -1c
.RI "override void \fBOnRightClick\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "UIText \fBtextDate\fP"
.br
.ti -1c
.RI "UIText \fBtextFortune\fP"
.br
.ti -1c
.RI "UIText \fBtextVote\fP"
.br
.ti -1c
.RI "UIText \fBtextVoteRemaining\fP"
.br
.ti -1c
.RI "UIList \fBlistChat\fP"
.br
.ti -1c
.RI "UIList \fBlistWeather\fP"
.br
.ti -1c
.RI "UIList \fBlistVote\fP"
.br
.ti -1c
.RI "UIList \fBlistNews\fP"
.br
.ti -1c
.RI "Image \fBimageHeadline\fP"
.br
.ti -1c
.RI "Image \fBimageAdRight\fP"
.br
.ti -1c
.RI "Image \fBmoldAdBottom\fP"
.br
.ti -1c
.RI "List< Sprite > \fBspritesAd\fP"
.br
.ti -1c
.RI "List< Sprite > \fBspritesSmallAd\fP"
.br
.ti -1c
.RI "List< Sprite > \fBspritesHeadline\fP"
.br
.ti -1c
.RI "LayoutGroup \fBlayoutAdBottom\fP"
.br
.ti -1c
.RI "LayoutGroup \fBlayoutPortrait\fP"
.br
.ti -1c
.RI "\fBPortrait\fP \fBmoldPortrait\fP"
.br
.ti -1c
.RI "List< string > \fBdesiredNews\fP"
.br
.ti -1c
.RI "UIButton \fBbuttonPage\fP"
.br
.ti -1c
.RI "GameObject \fBgoTop\fP"
.br
.ti -1c
.RI "GameObject \fBgoBack\fP"
.br
.ti -1c
.RI "bool \fBtopPage\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBDayData\fP \fBdata\fP\fR [get]\fP"
.br
.in -1c

Properties inherited from \fBELayer\fP
.in +1c
.ti -1c
.RI "static \fBCore\fP \fBcore\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGame\fP \fBgame\fP\fR [get]\fP"
.br
.ti -1c
.RI "static bool \fBAdvMode\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBPlayer\fP \fBplayer\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBChara\fP \fBpc\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFaction\fP \fBHome\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBUI\fP \fBui\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBMap\fP \fB_map\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBZone\fP \fB_zone\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBScene\fP \fBscene\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBBaseGameScreen\fP \fBscreen\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBCoreConfig\fP \fBconfig\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameSetting\fP \fBsetting\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBColorProfile\fP \fBColors\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBsources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBWorld\fP \fBworld\fP\fR [get]\fP"
.br
.ti -1c
.RI "static SoundManager \fBSound\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBCoreDebug\fP \fBdebug\fP\fR [get]\fP"
.br
.ti -1c
.RI "bool \fBIsFloat\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual string \fBIdHelp\fP\fR [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Static Public Member Functions inherited from \fBELayer\fP
.in +1c
.ti -1c
.RI "static int \fBrnd\fP (int a)"
.br
.in -1c

Protected Member Functions inherited from \fBELayer\fP
.in +1c
.ti -1c
.RI "override void \fB_Close\fP ()"
.br
.ti -1c
.RI "override void \fBKill\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB9\fP of file \fBLayerNewspaper\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void LayerNewspaper\&.OnClickPage ()"

.PP
Definition at line \fB47\fP of file \fBLayerNewspaper\&.cs\fP\&.
.SS "override void LayerNewspaper\&.OnInit ()"

.PP
Definition at line \fB22\fP of file \fBLayerNewspaper\&.cs\fP\&.
.SS "void LayerNewspaper\&.RefreshAD ()"

.PP
Definition at line \fB73\fP of file \fBLayerNewspaper\&.cs\fP\&.
.SS "void LayerNewspaper\&.RefreshChat ()"

.PP
Definition at line \fB95\fP of file \fBLayerNewspaper\&.cs\fP\&.
.SS "void LayerNewspaper\&.RefreshNews ()"

.PP
Definition at line \fB63\fP of file \fBLayerNewspaper\&.cs\fP\&.
.SS "void LayerNewspaper\&.RefreshPage ()"

.PP
Definition at line \fB56\fP of file \fBLayerNewspaper\&.cs\fP\&.
.SS "void LayerNewspaper\&.RefreshVote ()"

.PP
Definition at line \fB105\fP of file \fBLayerNewspaper\&.cs\fP\&.
.SS "void LayerNewspaper\&.RefreshWeather ()"

.PP
Definition at line \fB115\fP of file \fBLayerNewspaper\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "UIButton LayerNewspaper\&.buttonPage"

.PP
Definition at line \fB208\fP of file \fBLayerNewspaper\&.cs\fP\&.
.SS "List<string> LayerNewspaper\&.desiredNews"

.PP
Definition at line \fB205\fP of file \fBLayerNewspaper\&.cs\fP\&.
.SS "GameObject LayerNewspaper\&.goBack"

.PP
Definition at line \fB214\fP of file \fBLayerNewspaper\&.cs\fP\&.
.SS "GameObject LayerNewspaper\&.goTop"

.PP
Definition at line \fB211\fP of file \fBLayerNewspaper\&.cs\fP\&.
.SS "Image LayerNewspaper\&.imageAdRight"

.PP
Definition at line \fB181\fP of file \fBLayerNewspaper\&.cs\fP\&.
.SS "Image LayerNewspaper\&.imageHeadline"

.PP
Definition at line \fB178\fP of file \fBLayerNewspaper\&.cs\fP\&.
.SS "LayoutGroup LayerNewspaper\&.layoutAdBottom"

.PP
Definition at line \fB196\fP of file \fBLayerNewspaper\&.cs\fP\&.
.SS "LayoutGroup LayerNewspaper\&.layoutPortrait"

.PP
Definition at line \fB199\fP of file \fBLayerNewspaper\&.cs\fP\&.
.SS "UIList LayerNewspaper\&.listChat"

.PP
Definition at line \fB166\fP of file \fBLayerNewspaper\&.cs\fP\&.
.SS "UIList LayerNewspaper\&.listNews"

.PP
Definition at line \fB175\fP of file \fBLayerNewspaper\&.cs\fP\&.
.SS "UIList LayerNewspaper\&.listVote"

.PP
Definition at line \fB172\fP of file \fBLayerNewspaper\&.cs\fP\&.
.SS "UIList LayerNewspaper\&.listWeather"

.PP
Definition at line \fB169\fP of file \fBLayerNewspaper\&.cs\fP\&.
.SS "Image LayerNewspaper\&.moldAdBottom"

.PP
Definition at line \fB184\fP of file \fBLayerNewspaper\&.cs\fP\&.
.SS "\fBPortrait\fP LayerNewspaper\&.moldPortrait"

.PP
Definition at line \fB202\fP of file \fBLayerNewspaper\&.cs\fP\&.
.SS "List<Sprite> LayerNewspaper\&.spritesAd"

.PP
Definition at line \fB187\fP of file \fBLayerNewspaper\&.cs\fP\&.
.SS "List<Sprite> LayerNewspaper\&.spritesHeadline"

.PP
Definition at line \fB193\fP of file \fBLayerNewspaper\&.cs\fP\&.
.SS "List<Sprite> LayerNewspaper\&.spritesSmallAd"

.PP
Definition at line \fB190\fP of file \fBLayerNewspaper\&.cs\fP\&.
.SS "UIText LayerNewspaper\&.textDate"

.PP
Definition at line \fB154\fP of file \fBLayerNewspaper\&.cs\fP\&.
.SS "UIText LayerNewspaper\&.textFortune"

.PP
Definition at line \fB157\fP of file \fBLayerNewspaper\&.cs\fP\&.
.SS "UIText LayerNewspaper\&.textVote"

.PP
Definition at line \fB160\fP of file \fBLayerNewspaper\&.cs\fP\&.
.SS "UIText LayerNewspaper\&.textVoteRemaining"

.PP
Definition at line \fB163\fP of file \fBLayerNewspaper\&.cs\fP\&.
.SS "bool LayerNewspaper\&.topPage"

.PP
Definition at line \fB217\fP of file \fBLayerNewspaper\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "\fBDayData\fP LayerNewspaper\&.data\fR [get]\fP"

.PP
Definition at line \fB13\fP of file \fBLayerNewspaper\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
