.TH "LayerInteraction.Page" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LayerInteraction.Page
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLayerInteraction\&.Item\fP \fBAdd\fP (object target, string text, string idSprite, Action action, int priority=0, bool auto=false)"
.br
.ti -1c
.RI "\fBLayerInteraction\&.Item\fP \fBAdd\fP (object target, string text, Func< bool > valueFunc, Action< bool > action)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "UIButton \fBbutton\fP"
.br
.ti -1c
.RI "\fBArea\fP \fBarea\fP"
.br
.ti -1c
.RI "List< \fBLayerInteraction\&.Item\fP > \fBitems\fP = new List<\fBLayerInteraction\&.Item\fP>()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB270\fP of file \fBLayerInteraction\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBLayerInteraction\&.Item\fP LayerInteraction\&.Page\&.Add (object target, string text, Func< bool > valueFunc, Action< bool > action)"

.PP
Definition at line \fB289\fP of file \fBLayerInteraction\&.cs\fP\&.
.SS "\fBLayerInteraction\&.Item\fP LayerInteraction\&.Page\&.Add (object target, string text, string idSprite, Action action, int priority = \fR0\fP, bool auto = \fRfalse\fP)"

.PP
Definition at line \fB273\fP of file \fBLayerInteraction\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBArea\fP LayerInteraction\&.Page\&.area"

.PP
Definition at line \fB311\fP of file \fBLayerInteraction\&.cs\fP\&.
.SS "UIButton LayerInteraction\&.Page\&.button"

.PP
Definition at line \fB308\fP of file \fBLayerInteraction\&.cs\fP\&.
.SS "List<\fBLayerInteraction\&.Item\fP> LayerInteraction\&.Page\&.items = new List<\fBLayerInteraction\&.Item\fP>()"

.PP
Definition at line \fB314\fP of file \fBLayerInteraction\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
