.TH "LayerDrama" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LayerDrama
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBELayer\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnInit\fP ()"
.br
.ti -1c
.RI "override void \fBOnUpdateInput\fP ()"
.br
.ti -1c
.RI "override void \fBOnKill\fP ()"
.br
.in -1c

Public Member Functions inherited from \fBELayer\fP
.in +1c
.ti -1c
.RI "override void \fBOnBeforeAddLayer\fP ()"
.br
.ti -1c
.RI "void \fBInitInspector\fP ()"
.br
.ti -1c
.RI "override void \fBInit\fP ()"
.br
.ti -1c
.RI "override void \fBOnAfterAddLayer\fP ()"
.br
.ti -1c
.RI "void \fBTryShowHelp\fP ()"
.br
.ti -1c
.RI "void \fBAddLayerToUI\fP (string id)"
.br
.ti -1c
.RI "void \fBTryShowHint\fP (string _langHint=null)"
.br
.ti -1c
.RI "void \fBTalkHomeMemeber\fP (string id)"
.br
.ti -1c
.RI "void \fBTalkMaid\fP (string id)"
.br
.ti -1c
.RI "override void \fBOnRightClick\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBIsActive\fP ()"
.br
.ti -1c
.RI "static \fBLayerDrama\fP \fBActivateMain\fP (string idSheet, string idStep=null, \fBChara\fP target=null, \fBCard\fP ref1=null, string tag='')"
.br
.ti -1c
.RI "static \fBLayerDrama\fP \fBActivate\fP (string book, string idSheet, string idStep, \fBChara\fP target=null, \fBCard\fP ref1=null, string tag='')"
.br
.ti -1c
.RI "static \fBLayerDrama\fP \fBActivateNerun\fP (string idText)"
.br
.in -1c

Static Public Member Functions inherited from \fBELayer\fP
.in +1c
.ti -1c
.RI "static int \fBrnd\fP (int a)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBDramaManager\fP \fBdrama\fP"
.br
.ti -1c
.RI "CanvasGroup \fBcg\fP"
.br
.ti -1c
.RI "\fBDramaSetup\fP \fBsetup\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static \fBQuest\fP \fBcurrentQuest\fP"
.br
.ti -1c
.RI "static \fBReligion\fP \fBcurrentReligion\fP"
.br
.ti -1c
.RI "static bool \fBkeepBGM\fP"
.br
.ti -1c
.RI "static bool \fBhaltPlaylist\fP"
.br
.ti -1c
.RI "static bool \fBmaxBGMVolume\fP"
.br
.ti -1c
.RI "static string \fBforceJump\fP"
.br
.ti -1c
.RI "static \fBLayerDrama\fP \fBInstance\fP"
.br
.ti -1c
.RI "static \fBCard\fP \fBalwaysVisible\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Protected Member Functions inherited from \fBELayer\fP
.in +1c
.ti -1c
.RI "override void \fB_Close\fP ()"
.br
.ti -1c
.RI "override void \fBKill\fP ()"
.br
.in -1c

Properties inherited from \fBELayer\fP
.in +1c
.ti -1c
.RI "static \fBCore\fP \fBcore\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGame\fP \fBgame\fP\fR [get]\fP"
.br
.ti -1c
.RI "static bool \fBAdvMode\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBPlayer\fP \fBplayer\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBChara\fP \fBpc\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFaction\fP \fBHome\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBUI\fP \fBui\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBMap\fP \fB_map\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBZone\fP \fB_zone\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBScene\fP \fBscene\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBBaseGameScreen\fP \fBscreen\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBCoreConfig\fP \fBconfig\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameSetting\fP \fBsetting\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBColorProfile\fP \fBColors\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBsources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBWorld\fP \fBworld\fP\fR [get]\fP"
.br
.ti -1c
.RI "static SoundManager \fBSound\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBCoreDebug\fP \fBdebug\fP\fR [get]\fP"
.br
.ti -1c
.RI "bool \fBIsFloat\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual string \fBIdHelp\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB5\fP of file \fBLayerDrama\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "static \fBLayerDrama\fP LayerDrama\&.Activate (string book, string idSheet, string idStep, \fBChara\fP target = \fRnull\fP, \fBCard\fP ref1 = \fRnull\fP, string tag = \fR''\fP)\fR [static]\fP"

.PP
Definition at line \fB42\fP of file \fBLayerDrama\&.cs\fP\&.
.SS "static \fBLayerDrama\fP LayerDrama\&.ActivateMain (string idSheet, string idStep = \fRnull\fP, \fBChara\fP target = \fRnull\fP, \fBCard\fP ref1 = \fRnull\fP, string tag = \fR''\fP)\fR [static]\fP"

.PP
Definition at line \fB36\fP of file \fBLayerDrama\&.cs\fP\&.
.SS "static \fBLayerDrama\fP LayerDrama\&.ActivateNerun (string idText)\fR [static]\fP"

.PP
Definition at line \fB65\fP of file \fBLayerDrama\&.cs\fP\&.
.SS "static bool LayerDrama\&.IsActive ()\fR [static]\fP"

.PP
Definition at line \fB8\fP of file \fBLayerDrama\&.cs\fP\&.
.SS "override void LayerDrama\&.OnInit ()"

.PP
Definition at line \fB14\fP of file \fBLayerDrama\&.cs\fP\&.
.SS "override void LayerDrama\&.OnKill ()"

.PP
Definition at line \fB93\fP of file \fBLayerDrama\&.cs\fP\&.
.SS "override void LayerDrama\&.OnUpdateInput ()"

.PP
Definition at line \fB87\fP of file \fBLayerDrama\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBCard\fP LayerDrama\&.alwaysVisible\fR [static]\fP"

.PP
Definition at line \fB129\fP of file \fBLayerDrama\&.cs\fP\&.
.SS "CanvasGroup LayerDrama\&.cg"

.PP
Definition at line \fB135\fP of file \fBLayerDrama\&.cs\fP\&.
.SS "\fBQuest\fP LayerDrama\&.currentQuest\fR [static]\fP"

.PP
Definition at line \fB108\fP of file \fBLayerDrama\&.cs\fP\&.
.SS "\fBReligion\fP LayerDrama\&.currentReligion\fR [static]\fP"

.PP
Definition at line \fB111\fP of file \fBLayerDrama\&.cs\fP\&.
.SS "\fBDramaManager\fP LayerDrama\&.drama"

.PP
Definition at line \fB132\fP of file \fBLayerDrama\&.cs\fP\&.
.SS "string LayerDrama\&.forceJump\fR [static]\fP"

.PP
Definition at line \fB123\fP of file \fBLayerDrama\&.cs\fP\&.
.SS "bool LayerDrama\&.haltPlaylist\fR [static]\fP"

.PP
Definition at line \fB117\fP of file \fBLayerDrama\&.cs\fP\&.
.SS "\fBLayerDrama\fP LayerDrama\&.Instance\fR [static]\fP"

.PP
Definition at line \fB126\fP of file \fBLayerDrama\&.cs\fP\&.
.SS "bool LayerDrama\&.keepBGM\fR [static]\fP"

.PP
Definition at line \fB114\fP of file \fBLayerDrama\&.cs\fP\&.
.SS "bool LayerDrama\&.maxBGMVolume\fR [static]\fP"

.PP
Definition at line \fB120\fP of file \fBLayerDrama\&.cs\fP\&.
.SS "\fBDramaSetup\fP LayerDrama\&.setup"

.PP
Definition at line \fB138\fP of file \fBLayerDrama\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
