.TH "LayerTitle" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LayerTitle
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBELayer\fP, IChangeLanguage, and IChangeResolution\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTitleType\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnInit\fP ()"
.br
.ti -1c
.RI "void \fBRefresh\fP ()"
.br
.ti -1c
.RI "void \fBOnClickStart\fP ()"
.br
.ti -1c
.RI "void \fBOnChangeResolution\fP ()"
.br
.ti -1c
.RI "void \fBOnClickContinue\fP ()"
.br
.ti -1c
.RI "void \fBOnClickConfig\fP ()"
.br
.ti -1c
.RI "void \fBOnClickMod\fP ()"
.br
.ti -1c
.RI "void \fBOnClickCredit\fP ()"
.br
.ti -1c
.RI "void \fBOnClickAnnounce\fP ()"
.br
.ti -1c
.RI "void \fBOnClickAbout\fP ()"
.br
.ti -1c
.RI "void \fBOnClickFeedback\fP ()"
.br
.ti -1c
.RI "void \fBOnClickExit\fP ()"
.br
.ti -1c
.RI "override void \fBOnKill\fP ()"
.br
.ti -1c
.RI "void \fBOnChangeLanguage\fP ()"
.br
.in -1c

Public Member Functions inherited from \fBELayer\fP
.in +1c
.ti -1c
.RI "override void \fBOnBeforeAddLayer\fP ()"
.br
.ti -1c
.RI "void \fBInitInspector\fP ()"
.br
.ti -1c
.RI "override void \fBInit\fP ()"
.br
.ti -1c
.RI "override void \fBOnAfterAddLayer\fP ()"
.br
.ti -1c
.RI "void \fBTryShowHelp\fP ()"
.br
.ti -1c
.RI "void \fBAddLayerToUI\fP (string id)"
.br
.ti -1c
.RI "void \fBTryShowHint\fP (string _langHint=null)"
.br
.ti -1c
.RI "void \fBTalkHomeMemeber\fP (string id)"
.br
.ti -1c
.RI "void \fBTalkMaid\fP (string id)"
.br
.ti -1c
.RI "override void \fBOnRightClick\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBKillActor\fP ()"
.br
.in -1c

Static Public Member Functions inherited from \fBELayer\fP
.in +1c
.ti -1c
.RI "static int \fBrnd\fP (int a)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBLayerTitle\&.TitleType\fP[] \fBtypes\fP"
.br
.ti -1c
.RI "\fBLayerEditBio\fP \fBembark\fP"
.br
.ti -1c
.RI "UIText \fBtextVersion\fP"
.br
.ti -1c
.RI "UIText \fBtextIntro\fP"
.br
.ti -1c
.RI "Transform \fBtransBook\fP"
.br
.ti -1c
.RI "CanvasGroup \fBcgBook\fP"
.br
.ti -1c
.RI "CanvasGroup \fBcgBG\fP"
.br
.ti -1c
.RI "float \fBspeed\fP"
.br
.ti -1c
.RI "GraphicRaycaster \fBray\fP"
.br
.ti -1c
.RI "Transform \fBtitleActor\fP"
.br
.ti -1c
.RI "Image \fBuiLight\fP"
.br
.ti -1c
.RI "RawImage \fBimageFog\fP"
.br
.ti -1c
.RI "RawImage \fBimageBG\fP"
.br
.ti -1c
.RI "bool \fBtoggle\fP"
.br
.ti -1c
.RI "bool \fBaltTitle\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static \fBLayerTitle\fP \fBInstance\fP"
.br
.ti -1c
.RI "static \fBEmbarkActor\fP \fBactor\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBLayerTitle\&.TitleType\fP \fBCurrentTitle\fP\fR [get]\fP"
.br
.in -1c

Properties inherited from \fBELayer\fP
.in +1c
.ti -1c
.RI "static \fBCore\fP \fBcore\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGame\fP \fBgame\fP\fR [get]\fP"
.br
.ti -1c
.RI "static bool \fBAdvMode\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBPlayer\fP \fBplayer\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBChara\fP \fBpc\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFaction\fP \fBHome\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBUI\fP \fBui\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBMap\fP \fB_map\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBZone\fP \fB_zone\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBScene\fP \fBscene\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBBaseGameScreen\fP \fBscreen\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBCoreConfig\fP \fBconfig\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameSetting\fP \fBsetting\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBColorProfile\fP \fBColors\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBsources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBWorld\fP \fBworld\fP\fR [get]\fP"
.br
.ti -1c
.RI "static SoundManager \fBSound\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBCoreDebug\fP \fBdebug\fP\fR [get]\fP"
.br
.ti -1c
.RI "bool \fBIsFloat\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual string \fBIdHelp\fP\fR [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Protected Member Functions inherited from \fBELayer\fP
.in +1c
.ti -1c
.RI "override void \fB_Close\fP ()"
.br
.ti -1c
.RI "override void \fBKill\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB6\fP of file \fBLayerTitle\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "static void LayerTitle\&.KillActor ()\fR [static]\fP"

.PP
Definition at line \fB154\fP of file \fBLayerTitle\&.cs\fP\&.
.SS "void LayerTitle\&.OnChangeLanguage ()"

.PP
Definition at line \fB148\fP of file \fBLayerTitle\&.cs\fP\&.
.SS "void LayerTitle\&.OnChangeResolution ()"

.PP
Definition at line \fB47\fP of file \fBLayerTitle\&.cs\fP\&.
.SS "void LayerTitle\&.OnClickAbout ()"

.PP
Definition at line \fB83\fP of file \fBLayerTitle\&.cs\fP\&.
.SS "void LayerTitle\&.OnClickAnnounce ()"

.PP
Definition at line \fB77\fP of file \fBLayerTitle\&.cs\fP\&.
.SS "void LayerTitle\&.OnClickConfig ()"

.PP
Definition at line \fB59\fP of file \fBLayerTitle\&.cs\fP\&.
.SS "void LayerTitle\&.OnClickContinue ()"

.PP
Definition at line \fB53\fP of file \fBLayerTitle\&.cs\fP\&.
.SS "void LayerTitle\&.OnClickCredit ()"

.PP
Definition at line \fB71\fP of file \fBLayerTitle\&.cs\fP\&.
.SS "void LayerTitle\&.OnClickExit ()"

.PP
Definition at line \fB95\fP of file \fBLayerTitle\&.cs\fP\&.
.SS "void LayerTitle\&.OnClickFeedback ()"

.PP
Definition at line \fB89\fP of file \fBLayerTitle\&.cs\fP\&.
.SS "void LayerTitle\&.OnClickMod ()"

.PP
Definition at line \fB65\fP of file \fBLayerTitle\&.cs\fP\&.
.SS "void LayerTitle\&.OnClickStart ()"

.PP
Definition at line \fB40\fP of file \fBLayerTitle\&.cs\fP\&.
.SS "override void LayerTitle\&.OnInit ()"

.PP
Definition at line \fB19\fP of file \fBLayerTitle\&.cs\fP\&.
.SS "override void LayerTitle\&.OnKill ()"

.PP
Definition at line \fB111\fP of file \fBLayerTitle\&.cs\fP\&.
.SS "void LayerTitle\&.Refresh ()"

.PP
Definition at line \fB31\fP of file \fBLayerTitle\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBEmbarkActor\fP LayerTitle\&.actor\fR [static]\fP"

.PP
Definition at line \fB169\fP of file \fBLayerTitle\&.cs\fP\&.
.SS "bool LayerTitle\&.altTitle"

.PP
Definition at line \fB211\fP of file \fBLayerTitle\&.cs\fP\&.
.SS "CanvasGroup LayerTitle\&.cgBG"

.PP
Definition at line \fB187\fP of file \fBLayerTitle\&.cs\fP\&.
.SS "CanvasGroup LayerTitle\&.cgBook"

.PP
Definition at line \fB184\fP of file \fBLayerTitle\&.cs\fP\&.
.SS "\fBLayerEditBio\fP LayerTitle\&.embark"

.PP
Definition at line \fB172\fP of file \fBLayerTitle\&.cs\fP\&.
.SS "RawImage LayerTitle\&.imageBG"

.PP
Definition at line \fB205\fP of file \fBLayerTitle\&.cs\fP\&.
.SS "RawImage LayerTitle\&.imageFog"

.PP
Definition at line \fB202\fP of file \fBLayerTitle\&.cs\fP\&.
.SS "\fBLayerTitle\fP LayerTitle\&.Instance\fR [static]\fP"

.PP
Definition at line \fB166\fP of file \fBLayerTitle\&.cs\fP\&.
.SS "GraphicRaycaster LayerTitle\&.ray"

.PP
Definition at line \fB193\fP of file \fBLayerTitle\&.cs\fP\&.
.SS "float LayerTitle\&.speed"

.PP
Definition at line \fB190\fP of file \fBLayerTitle\&.cs\fP\&.
.SS "UIText LayerTitle\&.textIntro"

.PP
Definition at line \fB178\fP of file \fBLayerTitle\&.cs\fP\&.
.SS "UIText LayerTitle\&.textVersion"

.PP
Definition at line \fB175\fP of file \fBLayerTitle\&.cs\fP\&.
.SS "Transform LayerTitle\&.titleActor"

.PP
Definition at line \fB196\fP of file \fBLayerTitle\&.cs\fP\&.
.SS "bool LayerTitle\&.toggle"

.PP
Definition at line \fB208\fP of file \fBLayerTitle\&.cs\fP\&.
.SS "Transform LayerTitle\&.transBook"

.PP
Definition at line \fB181\fP of file \fBLayerTitle\&.cs\fP\&.
.SS "\fBLayerTitle\&.TitleType\fP [] LayerTitle\&.types"

.PP
Definition at line \fB163\fP of file \fBLayerTitle\&.cs\fP\&.
.SS "Image LayerTitle\&.uiLight"

.PP
Definition at line \fB199\fP of file \fBLayerTitle\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "\fBLayerTitle\&.TitleType\fP LayerTitle\&.CurrentTitle\fR [get]\fP"

.PP
Definition at line \fB10\fP of file \fBLayerTitle\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
