.TH "LayerInteraction.Item" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LayerInteraction.Item
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "object \fBtarget\fP"
.br
.ti -1c
.RI "string \fBtext\fP"
.br
.ti -1c
.RI "string \fBidSprite\fP"
.br
.ti -1c
.RI "Action \fBaction\fP"
.br
.ti -1c
.RI "int \fBpriority\fP"
.br
.ti -1c
.RI "bool \fBauto\fP"
.br
.ti -1c
.RI "bool \fBreload\fP"
.br
.ti -1c
.RI "Func< string > \fBtextFunc\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "bool \fBIsArea\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB318\fP of file \fBLayerInteraction\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "Action LayerInteraction\&.Item\&.action"

.PP
Definition at line \fB340\fP of file \fBLayerInteraction\&.cs\fP\&.
.SS "bool LayerInteraction\&.Item\&.auto"

.PP
Definition at line \fB346\fP of file \fBLayerInteraction\&.cs\fP\&.
.SS "string LayerInteraction\&.Item\&.idSprite"

.PP
Definition at line \fB337\fP of file \fBLayerInteraction\&.cs\fP\&.
.SS "int LayerInteraction\&.Item\&.priority"

.PP
Definition at line \fB343\fP of file \fBLayerInteraction\&.cs\fP\&.
.SS "bool LayerInteraction\&.Item\&.reload"

.PP
Definition at line \fB349\fP of file \fBLayerInteraction\&.cs\fP\&.
.SS "object LayerInteraction\&.Item\&.target"

.PP
Definition at line \fB331\fP of file \fBLayerInteraction\&.cs\fP\&.
.SS "string LayerInteraction\&.Item\&.text"

.PP
Definition at line \fB334\fP of file \fBLayerInteraction\&.cs\fP\&.
.SS "Func<string> LayerInteraction\&.Item\&.textFunc"

.PP
Definition at line \fB352\fP of file \fBLayerInteraction\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "bool LayerInteraction\&.Item\&.IsArea\fR [get]\fP"

.PP
Definition at line \fB322\fP of file \fBLayerInteraction\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
