.TH "LayerAbility.Config" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LayerAbility.Config
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBautoHideBG\fP"
.br
.ti -1c
.RI "bool \fBhideDepletedSpell\fP"
.br
.ti -1c
.RI "int \fBbgAlpha\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB296\fP of file \fBLayerAbility\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "bool LayerAbility\&.Config\&.autoHideBG"

.PP
Definition at line \fB299\fP of file \fBLayerAbility\&.cs\fP\&.
.SS "int LayerAbility\&.Config\&.bgAlpha"

.PP
Definition at line \fB305\fP of file \fBLayerAbility\&.cs\fP\&.
.SS "bool LayerAbility\&.Config\&.hideDepletedSpell"

.PP
Definition at line \fB302\fP of file \fBLayerAbility\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
