.TH "LayerTextureViewer" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LayerTextureViewer
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBELayer\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnInit\fP ()"
.br
.ti -1c
.RI "override void \fBOnSwitchContent\fP (Window window)"
.br
.ti -1c
.RI "void \fBRefreshPage\fP ()"
.br
.ti -1c
.RI "void \fBSetPos\fP (Component r, int x, int y, float size=0f, Vector2 posFix=default(Vector2))"
.br
.in -1c

Public Member Functions inherited from \fBELayer\fP
.in +1c
.ti -1c
.RI "override void \fBOnBeforeAddLayer\fP ()"
.br
.ti -1c
.RI "void \fBInitInspector\fP ()"
.br
.ti -1c
.RI "override void \fBInit\fP ()"
.br
.ti -1c
.RI "override void \fBOnAfterAddLayer\fP ()"
.br
.ti -1c
.RI "void \fBTryShowHelp\fP ()"
.br
.ti -1c
.RI "void \fBAddLayerToUI\fP (string id)"
.br
.ti -1c
.RI "void \fBTryShowHint\fP (string _langHint=null)"
.br
.ti -1c
.RI "void \fBTalkHomeMemeber\fP (string id)"
.br
.ti -1c
.RI "void \fBTalkMaid\fP (string id)"
.br
.ti -1c
.RI "override void \fBOnRightClick\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "RawImage \fBimageTex\fP"
.br
.ti -1c
.RI "Image \fBhighlight\fP"
.br
.ti -1c
.RI "Image \fBmoldMarker\fP"
.br
.ti -1c
.RI "\fBTextureData\fP \fBdata\fP"
.br
.ti -1c
.RI "UIScrollView \fBview\fP"
.br
.ti -1c
.RI "Scrollbar \fBscrollbarH\fP"
.br
.ti -1c
.RI "Scrollbar \fBscrollvarV\fP"
.br
.ti -1c
.RI "UIText \fBtextHint\fP"
.br
.ti -1c
.RI "Transform \fBtransMask\fP"
.br
.ti -1c
.RI "float \fBscale\fP"
.br
.ti -1c
.RI "float \fBhighlightSize\fP"
.br
.ti -1c
.RI "List< Image > \fBmarkers\fP = new List<Image>()"
.br
.ti -1c
.RI "Vector2 \fBmarkerFix\fP"
.br
.ti -1c
.RI "Color \fBcolorUser\fP"
.br
.ti -1c
.RI "Color \fBcolorMod\fP"
.br
.ti -1c
.RI "Color \fBcolorLocal\fP"
.br
.ti -1c
.RI "int \fBsizeX\fP"
.br
.ti -1c
.RI "int \fBsizeY\fP"
.br
.ti -1c
.RI "bool \fBfixZoom\fP"
.br
.ti -1c
.RI "bool \fBsnow\fP"
.br
.ti -1c
.RI "Vector2 \fBtest\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Static Public Member Functions inherited from \fBELayer\fP
.in +1c
.ti -1c
.RI "static int \fBrnd\fP (int a)"
.br
.in -1c

Protected Member Functions inherited from \fBELayer\fP
.in +1c
.ti -1c
.RI "override void \fB_Close\fP ()"
.br
.ti -1c
.RI "override void \fBKill\fP ()"
.br
.in -1c

Properties inherited from \fBELayer\fP
.in +1c
.ti -1c
.RI "static \fBCore\fP \fBcore\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGame\fP \fBgame\fP\fR [get]\fP"
.br
.ti -1c
.RI "static bool \fBAdvMode\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBPlayer\fP \fBplayer\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBChara\fP \fBpc\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFaction\fP \fBHome\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBUI\fP \fBui\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBMap\fP \fB_map\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBZone\fP \fB_zone\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBScene\fP \fBscene\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBBaseGameScreen\fP \fBscreen\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBCoreConfig\fP \fBconfig\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameSetting\fP \fBsetting\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBColorProfile\fP \fBColors\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBsources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBWorld\fP \fBworld\fP\fR [get]\fP"
.br
.ti -1c
.RI "static SoundManager \fBSound\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBCoreDebug\fP \fBdebug\fP\fR [get]\fP"
.br
.ti -1c
.RI "bool \fBIsFloat\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual string \fBIdHelp\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB7\fP of file \fBLayerTextureViewer\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void LayerTextureViewer\&.OnInit ()"

.PP
Definition at line \fB10\fP of file \fBLayerTextureViewer\&.cs\fP\&.
.SS "override void LayerTextureViewer\&.OnSwitchContent (Window window)"

.PP
Definition at line \fB26\fP of file \fBLayerTextureViewer\&.cs\fP\&.
.SS "void LayerTextureViewer\&.RefreshPage ()"

.PP
Definition at line \fB35\fP of file \fBLayerTextureViewer\&.cs\fP\&.
.SS "void LayerTextureViewer\&.SetPos (Component r, int x, int y, float size = \fR0f\fP, Vector2 posFix = \fRdefault(Vector2)\fP)"

.PP
Definition at line \fB71\fP of file \fBLayerTextureViewer\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "Color LayerTextureViewer\&.colorLocal"

.PP
Definition at line \fB211\fP of file \fBLayerTextureViewer\&.cs\fP\&.
.SS "Color LayerTextureViewer\&.colorMod"

.PP
Definition at line \fB208\fP of file \fBLayerTextureViewer\&.cs\fP\&.
.SS "Color LayerTextureViewer\&.colorUser"

.PP
Definition at line \fB205\fP of file \fBLayerTextureViewer\&.cs\fP\&.
.SS "\fBTextureData\fP LayerTextureViewer\&.data"

.PP
Definition at line \fB175\fP of file \fBLayerTextureViewer\&.cs\fP\&.
.SS "bool LayerTextureViewer\&.fixZoom"

.PP
Definition at line \fB220\fP of file \fBLayerTextureViewer\&.cs\fP\&.
.SS "Image LayerTextureViewer\&.highlight"

.PP
Definition at line \fB169\fP of file \fBLayerTextureViewer\&.cs\fP\&.
.SS "float LayerTextureViewer\&.highlightSize"

.PP
Definition at line \fB196\fP of file \fBLayerTextureViewer\&.cs\fP\&.
.SS "RawImage LayerTextureViewer\&.imageTex"

.PP
Definition at line \fB166\fP of file \fBLayerTextureViewer\&.cs\fP\&.
.SS "Vector2 LayerTextureViewer\&.markerFix"

.PP
Definition at line \fB202\fP of file \fBLayerTextureViewer\&.cs\fP\&.
.SS "List<Image> LayerTextureViewer\&.markers = new List<Image>()"

.PP
Definition at line \fB199\fP of file \fBLayerTextureViewer\&.cs\fP\&.
.SS "Image LayerTextureViewer\&.moldMarker"

.PP
Definition at line \fB172\fP of file \fBLayerTextureViewer\&.cs\fP\&.
.SS "float LayerTextureViewer\&.scale"

.PP
Definition at line \fB193\fP of file \fBLayerTextureViewer\&.cs\fP\&.
.SS "Scrollbar LayerTextureViewer\&.scrollbarH"

.PP
Definition at line \fB181\fP of file \fBLayerTextureViewer\&.cs\fP\&.
.SS "Scrollbar LayerTextureViewer\&.scrollvarV"

.PP
Definition at line \fB184\fP of file \fBLayerTextureViewer\&.cs\fP\&.
.SS "int LayerTextureViewer\&.sizeX"

.PP
Definition at line \fB214\fP of file \fBLayerTextureViewer\&.cs\fP\&.
.SS "int LayerTextureViewer\&.sizeY"

.PP
Definition at line \fB217\fP of file \fBLayerTextureViewer\&.cs\fP\&.
.SS "bool LayerTextureViewer\&.snow"

.PP
Definition at line \fB223\fP of file \fBLayerTextureViewer\&.cs\fP\&.
.SS "Vector2 LayerTextureViewer\&.test"

.PP
Definition at line \fB226\fP of file \fBLayerTextureViewer\&.cs\fP\&.
.SS "UIText LayerTextureViewer\&.textHint"

.PP
Definition at line \fB187\fP of file \fBLayerTextureViewer\&.cs\fP\&.
.SS "Transform LayerTextureViewer\&.transMask"

.PP
Definition at line \fB190\fP of file \fBLayerTextureViewer\&.cs\fP\&.
.SS "UIScrollView LayerTextureViewer\&.view"

.PP
Definition at line \fB178\fP of file \fBLayerTextureViewer\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
