.TH "LayerLoadGame" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LayerLoadGame
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBELayer\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnAfterInit\fP ()"
.br
.ti -1c
.RI "void \fBRefreshList\fP ()"
.br
.ti -1c
.RI "void \fBRefreshInfo\fP (\fBGameIndex\fP i)"
.br
.in -1c

Public Member Functions inherited from \fBELayer\fP
.in +1c
.ti -1c
.RI "override void \fBOnBeforeAddLayer\fP ()"
.br
.ti -1c
.RI "void \fBInitInspector\fP ()"
.br
.ti -1c
.RI "override void \fBInit\fP ()"
.br
.ti -1c
.RI "override void \fBOnAfterAddLayer\fP ()"
.br
.ti -1c
.RI "void \fBTryShowHelp\fP ()"
.br
.ti -1c
.RI "void \fBAddLayerToUI\fP (string id)"
.br
.ti -1c
.RI "void \fBTryShowHint\fP (string _langHint=null)"
.br
.ti -1c
.RI "void \fBTalkHomeMemeber\fP (string id)"
.br
.ti -1c
.RI "void \fBTalkMaid\fP (string id)"
.br
.ti -1c
.RI "override void \fBOnRightClick\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "UIList \fBlist\fP"
.br
.ti -1c
.RI "GameObject \fBgoInfo\fP"
.br
.ti -1c
.RI "GameObject \fBgoNoInfo\fP"
.br
.ti -1c
.RI "UINote \fBnote\fP"
.br
.ti -1c
.RI "UIButton \fBbuttonLoad\fP"
.br
.ti -1c
.RI "UIButton \fBbuttonDelete\fP"
.br
.ti -1c
.RI "UIButton \fBbuttonBackup\fP"
.br
.ti -1c
.RI "List< \fBGameIndex\fP > \fBworlds\fP"
.br
.ti -1c
.RI "\fBPortrait\fP \fBportrait\fP"
.br
.ti -1c
.RI "UIText \fBtextAka\fP"
.br
.ti -1c
.RI "UIText \fBtextName\fP"
.br
.ti -1c
.RI "UIText \fBtextInfo\fP"
.br
.ti -1c
.RI "UIText \fBtextRace\fP"
.br
.ti -1c
.RI "UIText \fBtextJob\fP"
.br
.ti -1c
.RI "UIText \fBtextDeepest\fP"
.br
.ti -1c
.RI "UIText \fBtextDays\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Static Public Member Functions inherited from \fBELayer\fP
.in +1c
.ti -1c
.RI "static int \fBrnd\fP (int a)"
.br
.in -1c

Protected Member Functions inherited from \fBELayer\fP
.in +1c
.ti -1c
.RI "override void \fB_Close\fP ()"
.br
.ti -1c
.RI "override void \fBKill\fP ()"
.br
.in -1c

Properties inherited from \fBELayer\fP
.in +1c
.ti -1c
.RI "static \fBCore\fP \fBcore\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGame\fP \fBgame\fP\fR [get]\fP"
.br
.ti -1c
.RI "static bool \fBAdvMode\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBPlayer\fP \fBplayer\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBChara\fP \fBpc\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFaction\fP \fBHome\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBUI\fP \fBui\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBMap\fP \fB_map\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBZone\fP \fB_zone\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBScene\fP \fBscene\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBBaseGameScreen\fP \fBscreen\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBCoreConfig\fP \fBconfig\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameSetting\fP \fBsetting\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBColorProfile\fP \fBColors\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBsources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBWorld\fP \fBworld\fP\fR [get]\fP"
.br
.ti -1c
.RI "static SoundManager \fBSound\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBCoreDebug\fP \fBdebug\fP\fR [get]\fP"
.br
.ti -1c
.RI "bool \fBIsFloat\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual string \fBIdHelp\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB6\fP of file \fBLayerLoadGame\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void LayerLoadGame\&.OnAfterInit ()"

.PP
Definition at line \fB9\fP of file \fBLayerLoadGame\&.cs\fP\&.
.SS "void LayerLoadGame\&.RefreshInfo (\fBGameIndex\fP i)"

.PP
Definition at line \fB61\fP of file \fBLayerLoadGame\&.cs\fP\&.
.SS "void LayerLoadGame\&.RefreshList ()"

.PP
Definition at line \fB15\fP of file \fBLayerLoadGame\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "UIButton LayerLoadGame\&.buttonBackup"

.PP
Definition at line \fB154\fP of file \fBLayerLoadGame\&.cs\fP\&.
.SS "UIButton LayerLoadGame\&.buttonDelete"

.PP
Definition at line \fB151\fP of file \fBLayerLoadGame\&.cs\fP\&.
.SS "UIButton LayerLoadGame\&.buttonLoad"

.PP
Definition at line \fB148\fP of file \fBLayerLoadGame\&.cs\fP\&.
.SS "GameObject LayerLoadGame\&.goInfo"

.PP
Definition at line \fB139\fP of file \fBLayerLoadGame\&.cs\fP\&.
.SS "GameObject LayerLoadGame\&.goNoInfo"

.PP
Definition at line \fB142\fP of file \fBLayerLoadGame\&.cs\fP\&.
.SS "UIList LayerLoadGame\&.list"

.PP
Definition at line \fB136\fP of file \fBLayerLoadGame\&.cs\fP\&.
.SS "UINote LayerLoadGame\&.note"

.PP
Definition at line \fB145\fP of file \fBLayerLoadGame\&.cs\fP\&.
.SS "\fBPortrait\fP LayerLoadGame\&.portrait"

.PP
Definition at line \fB160\fP of file \fBLayerLoadGame\&.cs\fP\&.
.SS "UIText LayerLoadGame\&.textAka"

.PP
Definition at line \fB163\fP of file \fBLayerLoadGame\&.cs\fP\&.
.SS "UIText LayerLoadGame\&.textDays"

.PP
Definition at line \fB181\fP of file \fBLayerLoadGame\&.cs\fP\&.
.SS "UIText LayerLoadGame\&.textDeepest"

.PP
Definition at line \fB178\fP of file \fBLayerLoadGame\&.cs\fP\&.
.SS "UIText LayerLoadGame\&.textInfo"

.PP
Definition at line \fB169\fP of file \fBLayerLoadGame\&.cs\fP\&.
.SS "UIText LayerLoadGame\&.textJob"

.PP
Definition at line \fB175\fP of file \fBLayerLoadGame\&.cs\fP\&.
.SS "UIText LayerLoadGame\&.textName"

.PP
Definition at line \fB166\fP of file \fBLayerLoadGame\&.cs\fP\&.
.SS "UIText LayerLoadGame\&.textRace"

.PP
Definition at line \fB172\fP of file \fBLayerLoadGame\&.cs\fP\&.
.SS "List<\fBGameIndex\fP> LayerLoadGame\&.worlds"

.PP
Definition at line \fB157\fP of file \fBLayerLoadGame\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
