.TH "LayerInspect.MenuItem" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LayerInspect.MenuItem
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBid\fP"
.br
.ti -1c
.RI "string \fBtext\fP"
.br
.ti -1c
.RI "UnityAction \fBaction\fP"
.br
.ti -1c
.RI "\fBCard\fP \fBcard\fP"
.br
.ti -1c
.RI "\fBRenderRow\fP \fBrenderRow\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB185\fP of file \fBLayerInspect\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "UnityAction LayerInspect\&.MenuItem\&.action"

.PP
Definition at line \fB194\fP of file \fBLayerInspect\&.cs\fP\&.
.SS "\fBCard\fP LayerInspect\&.MenuItem\&.card"

.PP
Definition at line \fB197\fP of file \fBLayerInspect\&.cs\fP\&.
.SS "string LayerInspect\&.MenuItem\&.id"

.PP
Definition at line \fB188\fP of file \fBLayerInspect\&.cs\fP\&.
.SS "\fBRenderRow\fP LayerInspect\&.MenuItem\&.renderRow"

.PP
Definition at line \fB200\fP of file \fBLayerInspect\&.cs\fP\&.
.SS "string LayerInspect\&.MenuItem\&.text"

.PP
Definition at line \fB191\fP of file \fBLayerInspect\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
