.TH "LayerCraft" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LayerCraft
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLayerBaseCraft\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBRefreshCurrentGrid\fP ()"
.br
.ti -1c
.RI "override void \fBClearButtons\fP ()"
.br
.ti -1c
.RI "override string \fBGetTextHeader\fP (Window window)"
.br
.ti -1c
.RI "override void \fBOnAfterInit\fP ()"
.br
.ti -1c
.RI "override void \fBOnKill\fP ()"
.br
.ti -1c
.RI "void \fBSetFactory\fP (\fBThing\fP t)"
.br
.ti -1c
.RI "void \fBOnClickCraft\fP ()"
.br
.ti -1c
.RI "override List< \fBThing\fP > \fBGetTargets\fP ()"
.br
.ti -1c
.RI "override int \fBGetReqIngredient\fP (int index)"
.br
.ti -1c
.RI "override void \fBOnEndCraft\fP ()"
.br
.ti -1c
.RI "void \fBOnCompleteCraft\fP ()"
.br
.ti -1c
.RI "void \fBWaitUntilIdle\fP ()"
.br
.ti -1c
.RI "void \fBRefreshInfo\fP ()"
.br
.ti -1c
.RI "void \fBRefreshCategory\fP (string cat)"
.br
.ti -1c
.RI "void \fBOnChangeIngredient\fP ()"
.br
.ti -1c
.RI "void \fBRefreshRecipe\fP (bool first)"
.br
.ti -1c
.RI "void \fBRefreshInputNum\fP ()"
.br
.ti -1c
.RI "void \fBRefreshProduct\fP ()"
.br
.ti -1c
.RI "bool \fBIsQualityMet\fP ()"
.br
.ti -1c
.RI "void \fBRefreshQuality\fP ()"
.br
.ti -1c
.RI "void \fBOnClickExamine\fP ()"
.br
.in -1c

Public Member Functions inherited from \fBLayerBaseCraft\fP

Public Member Functions inherited from \fBELayer\fP
.in +1c
.ti -1c
.RI "override void \fBOnBeforeAddLayer\fP ()"
.br
.ti -1c
.RI "void \fBInitInspector\fP ()"
.br
.ti -1c
.RI "override void \fBInit\fP ()"
.br
.ti -1c
.RI "override void \fBOnAfterAddLayer\fP ()"
.br
.ti -1c
.RI "void \fBTryShowHelp\fP ()"
.br
.ti -1c
.RI "void \fBAddLayerToUI\fP (string id)"
.br
.ti -1c
.RI "void \fBTryShowHint\fP (string _langHint=null)"
.br
.ti -1c
.RI "void \fBTalkHomeMemeber\fP (string id)"
.br
.ti -1c
.RI "void \fBTalkMaid\fP (string id)"
.br
.ti -1c
.RI "override void \fBOnRightClick\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "UIDynamicList \fBlist\fP"
.br
.ti -1c
.RI "\fBUIRecipeInfo\fP \fBinfo1\fP"
.br
.ti -1c
.RI "\fBUIRecipeInfo\fP \fBinfo2\fP"
.br
.ti -1c
.RI "Vector3 \fBposInfo\fP"
.br
.ti -1c
.RI "\fBThing\fP \fBfactory\fP"
.br
.ti -1c
.RI "\fBThing\fP \fBproduct\fP"
.br
.ti -1c
.RI "\fBRecipe\fP \fBrecipe\fP"
.br
.ti -1c
.RI "UIButton \fBtoggleRepeat\fP"
.br
.ti -1c
.RI "UIButton \fBtoggleCraftTo\fP"
.br
.ti -1c
.RI "UIInputText \fBinputNum\fP"
.br
.ti -1c
.RI "UIInputText \fBmoldInputNum\fP"
.br
.ti -1c
.RI "List< \fBRecipeSource\fP > \fBnewRecipes\fP = new List<\fBRecipeSource\fP>()"
.br
.ti -1c
.RI "Window \fBwindowList\fP"
.br
.ti -1c
.RI "bool \fBshowInfo\fP"
.br
.ti -1c
.RI "UIButton \fBbuttonRefuel\fP"
.br
.ti -1c
.RI "UIButton \fBbuttonAutoRefuel\fP"
.br
.ti -1c
.RI "Transform \fBtransFuel\fP"
.br
.ti -1c
.RI "UIText \fBtextFuel\fP"
.br
.ti -1c
.RI "UIText \fBtextQualityInvalid\fP"
.br
.ti -1c
.RI "UIText \fBtextQualityValid\fP"
.br
.ti -1c
.RI "Image \fBimageQualityReq\fP"
.br
.ti -1c
.RI "Image \fBimageQualityCurrent\fP"
.br
.ti -1c
.RI "float \fBwaitComplete\fP"
.br
.ti -1c
.RI "float \fBqualityBarWidth\fP"
.br
.ti -1c
.RI "\fBButtonGrid\fP \fBlastB\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static \fBLayerCraft\fP \fBInstance\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Static Public Member Functions inherited from \fBELayer\fP
.in +1c
.ti -1c
.RI "static int \fBrnd\fP (int a)"
.br
.in -1c

Protected Member Functions inherited from \fBELayer\fP
.in +1c
.ti -1c
.RI "override void \fB_Close\fP ()"
.br
.ti -1c
.RI "override void \fBKill\fP ()"
.br
.in -1c

Properties inherited from \fBLayerBaseCraft\fP
.in +1c
.ti -1c
.RI "virtual bool \fBCanCancelAI\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBRepeatAI\fP\fR [get]\fP"
.br
.in -1c

Properties inherited from \fBELayer\fP
.in +1c
.ti -1c
.RI "static \fBCore\fP \fBcore\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGame\fP \fBgame\fP\fR [get]\fP"
.br
.ti -1c
.RI "static bool \fBAdvMode\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBPlayer\fP \fBplayer\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBChara\fP \fBpc\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFaction\fP \fBHome\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBUI\fP \fBui\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBMap\fP \fB_map\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBZone\fP \fB_zone\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBScene\fP \fBscene\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBBaseGameScreen\fP \fBscreen\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBCoreConfig\fP \fBconfig\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameSetting\fP \fBsetting\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBColorProfile\fP \fBColors\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBsources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBWorld\fP \fBworld\fP\fR [get]\fP"
.br
.ti -1c
.RI "static SoundManager \fBSound\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBCoreDebug\fP \fBdebug\fP\fR [get]\fP"
.br
.ti -1c
.RI "bool \fBIsFloat\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual string \fBIdHelp\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB8\fP of file \fBLayerCraft\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void LayerCraft\&.ClearButtons ()\fR [virtual]\fP"

.PP
Reimplemented from \fBLayerBaseCraft\fP\&.
.PP
Definition at line \fB17\fP of file \fBLayerCraft\&.cs\fP\&.
.SS "override int LayerCraft\&.GetReqIngredient (int index)\fR [virtual]\fP"

.PP
Reimplemented from \fBLayerBaseCraft\fP\&.
.PP
Definition at line \fB165\fP of file \fBLayerCraft\&.cs\fP\&.
.SS "override List< \fBThing\fP > LayerCraft\&.GetTargets ()\fR [virtual]\fP"

.PP
Reimplemented from \fBLayerBaseCraft\fP\&.
.PP
Definition at line \fB151\fP of file \fBLayerCraft\&.cs\fP\&.
.SS "override string LayerCraft\&.GetTextHeader (Window window)"

.PP
Definition at line \fB23\fP of file \fBLayerCraft\&.cs\fP\&.
.SS "bool LayerCraft\&.IsQualityMet ()"

.PP
Definition at line \fB416\fP of file \fBLayerCraft\&.cs\fP\&.
.SS "override void LayerCraft\&.OnAfterInit ()"

.PP
Definition at line \fB29\fP of file \fBLayerCraft\&.cs\fP\&.
.SS "void LayerCraft\&.OnChangeIngredient ()"

.PP
Definition at line \fB333\fP of file \fBLayerCraft\&.cs\fP\&.
.SS "void LayerCraft\&.OnClickCraft ()"

.PP
Definition at line \fB89\fP of file \fBLayerCraft\&.cs\fP\&.
.SS "void LayerCraft\&.OnClickExamine ()"

.PP
Definition at line \fB427\fP of file \fBLayerCraft\&.cs\fP\&.
.SS "void LayerCraft\&.OnCompleteCraft ()"

.PP
Definition at line \fB177\fP of file \fBLayerCraft\&.cs\fP\&.
.SS "override void LayerCraft\&.OnEndCraft ()\fR [virtual]\fP"

.PP
Reimplemented from \fBLayerBaseCraft\fP\&.
.PP
Definition at line \fB171\fP of file \fBLayerCraft\&.cs\fP\&.
.SS "override void LayerCraft\&.OnKill ()"

.PP
Definition at line \fB37\fP of file \fBLayerCraft\&.cs\fP\&.
.SS "void LayerCraft\&.RefreshCategory (string cat)"

.PP
Definition at line \fB243\fP of file \fBLayerCraft\&.cs\fP\&.
.SS "override void LayerCraft\&.RefreshCurrentGrid ()\fR [virtual]\fP"

.PP
Reimplemented from \fBLayerBaseCraft\fP\&.
.PP
Definition at line \fB11\fP of file \fBLayerCraft\&.cs\fP\&.
.SS "void LayerCraft\&.RefreshInfo ()"

.PP
Definition at line \fB228\fP of file \fBLayerCraft\&.cs\fP\&.
.SS "void LayerCraft\&.RefreshInputNum ()"

.PP
Definition at line \fB362\fP of file \fBLayerCraft\&.cs\fP\&.
.SS "void LayerCraft\&.RefreshProduct ()"

.PP
Definition at line \fB373\fP of file \fBLayerCraft\&.cs\fP\&.
.SS "void LayerCraft\&.RefreshQuality ()"

.PP
Definition at line \fB422\fP of file \fBLayerCraft\&.cs\fP\&.
.SS "void LayerCraft\&.RefreshRecipe (bool first)"

.PP
Definition at line \fB339\fP of file \fBLayerCraft\&.cs\fP\&.
.SS "void LayerCraft\&.SetFactory (\fBThing\fP t)"

.PP
Definition at line \fB50\fP of file \fBLayerCraft\&.cs\fP\&.
.SS "void LayerCraft\&.WaitUntilIdle ()"

.PP
Definition at line \fB197\fP of file \fBLayerCraft\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "UIButton LayerCraft\&.buttonAutoRefuel"

.PP
Definition at line \fB487\fP of file \fBLayerCraft\&.cs\fP\&.
.SS "UIButton LayerCraft\&.buttonRefuel"

.PP
Definition at line \fB484\fP of file \fBLayerCraft\&.cs\fP\&.
.SS "\fBThing\fP LayerCraft\&.factory"

.PP
Definition at line \fB448\fP of file \fBLayerCraft\&.cs\fP\&.
.SS "Image LayerCraft\&.imageQualityCurrent"

.PP
Definition at line \fB505\fP of file \fBLayerCraft\&.cs\fP\&.
.SS "Image LayerCraft\&.imageQualityReq"

.PP
Definition at line \fB502\fP of file \fBLayerCraft\&.cs\fP\&.
.SS "\fBUIRecipeInfo\fP LayerCraft\&.info1"

.PP
Definition at line \fB439\fP of file \fBLayerCraft\&.cs\fP\&.
.SS "\fBUIRecipeInfo\fP LayerCraft\&.info2"

.PP
Definition at line \fB442\fP of file \fBLayerCraft\&.cs\fP\&.
.SS "UIInputText LayerCraft\&.inputNum"

.PP
Definition at line \fB463\fP of file \fBLayerCraft\&.cs\fP\&.
.SS "\fBLayerCraft\fP LayerCraft\&.Instance\fR [static]\fP"

.PP
Definition at line \fB433\fP of file \fBLayerCraft\&.cs\fP\&.
.SS "\fBButtonGrid\fP LayerCraft\&.lastB"

.PP
Definition at line \fB517\fP of file \fBLayerCraft\&.cs\fP\&.
.SS "UIDynamicList LayerCraft\&.list"

.PP
Definition at line \fB436\fP of file \fBLayerCraft\&.cs\fP\&.
.SS "UIInputText LayerCraft\&.moldInputNum"

.PP
Definition at line \fB466\fP of file \fBLayerCraft\&.cs\fP\&.
.SS "List<\fBRecipeSource\fP> LayerCraft\&.newRecipes = new List<\fBRecipeSource\fP>()"

.PP
Definition at line \fB469\fP of file \fBLayerCraft\&.cs\fP\&.
.SS "Vector3 LayerCraft\&.posInfo"

.PP
Definition at line \fB445\fP of file \fBLayerCraft\&.cs\fP\&.
.SS "\fBThing\fP LayerCraft\&.product"

.PP
Definition at line \fB451\fP of file \fBLayerCraft\&.cs\fP\&.
.SS "float LayerCraft\&.qualityBarWidth"

.PP
Definition at line \fB511\fP of file \fBLayerCraft\&.cs\fP\&.
.SS "\fBRecipe\fP LayerCraft\&.recipe"

.PP
Definition at line \fB454\fP of file \fBLayerCraft\&.cs\fP\&.
.SS "bool LayerCraft\&.showInfo"

.PP
Definition at line \fB475\fP of file \fBLayerCraft\&.cs\fP\&.
.SS "UIText LayerCraft\&.textFuel"

.PP
Definition at line \fB493\fP of file \fBLayerCraft\&.cs\fP\&.
.SS "UIText LayerCraft\&.textQualityInvalid"

.PP
Definition at line \fB496\fP of file \fBLayerCraft\&.cs\fP\&.
.SS "UIText LayerCraft\&.textQualityValid"

.PP
Definition at line \fB499\fP of file \fBLayerCraft\&.cs\fP\&.
.SS "UIButton LayerCraft\&.toggleCraftTo"

.PP
Definition at line \fB460\fP of file \fBLayerCraft\&.cs\fP\&.
.SS "UIButton LayerCraft\&.toggleRepeat"

.PP
Definition at line \fB457\fP of file \fBLayerCraft\&.cs\fP\&.
.SS "Transform LayerCraft\&.transFuel"

.PP
Definition at line \fB490\fP of file \fBLayerCraft\&.cs\fP\&.
.SS "float LayerCraft\&.waitComplete"

.PP
Definition at line \fB508\fP of file \fBLayerCraft\&.cs\fP\&.
.SS "Window LayerCraft\&.windowList"

.PP
Definition at line \fB472\fP of file \fBLayerCraft\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
