.TH "LayerFaith" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LayerFaith
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBELayer\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSlot\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBActivate\fP (\fBReligion\fP r, Action< \fBReligion\fP > _onWorship)"
.br
.ti -1c
.RI "void \fBMove\fP (int a)"
.br
.ti -1c
.RI "void \fBRefreshSlots\fP ()"
.br
.ti -1c
.RI "void \fBAddReligion\fP (\fBReligion\fP r)"
.br
.in -1c

Public Member Functions inherited from \fBELayer\fP
.in +1c
.ti -1c
.RI "override void \fBOnBeforeAddLayer\fP ()"
.br
.ti -1c
.RI "void \fBInitInspector\fP ()"
.br
.ti -1c
.RI "override void \fBInit\fP ()"
.br
.ti -1c
.RI "override void \fBOnAfterAddLayer\fP ()"
.br
.ti -1c
.RI "void \fBTryShowHelp\fP ()"
.br
.ti -1c
.RI "void \fBAddLayerToUI\fP (string id)"
.br
.ti -1c
.RI "void \fBTryShowHint\fP (string _langHint=null)"
.br
.ti -1c
.RI "void \fBTalkHomeMemeber\fP (string id)"
.br
.ti -1c
.RI "void \fBTalkMaid\fP (string id)"
.br
.ti -1c
.RI "override void \fBOnRightClick\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Vector2 \fBstartPos\fP"
.br
.ti -1c
.RI "float \fBtime\fP"
.br
.ti -1c
.RI "float \fBbgAlpha\fP"
.br
.ti -1c
.RI "float \fBstartDelay\fP"
.br
.ti -1c
.RI "\fBLayerFaith\&.Slot\fP \fBslotVoid\fP"
.br
.ti -1c
.RI "List< \fBLayerFaith\&.Slot\fP > \fBslots\fP"
.br
.ti -1c
.RI "UIItem \fBmoldItem\fP"
.br
.ti -1c
.RI "LayoutGroup \fBlayout\fP"
.br
.ti -1c
.RI "Action< \fBReligion\fP > \fBonWorship\fP"
.br
.ti -1c
.RI "bool \fBisBranchFaith\fP"
.br
.ti -1c
.RI "int \fBindex\fP"
.br
.ti -1c
.RI "List< UIItem > \fBitems\fP = new List<UIItem>()"
.br
.ti -1c
.RI "List< UIItem > \fBorders\fP = new List<UIItem>()"
.br
.in -1c
.SS "Additional Inherited Members"


Static Public Member Functions inherited from \fBELayer\fP
.in +1c
.ti -1c
.RI "static int \fBrnd\fP (int a)"
.br
.in -1c

Protected Member Functions inherited from \fBELayer\fP
.in +1c
.ti -1c
.RI "override void \fB_Close\fP ()"
.br
.ti -1c
.RI "override void \fBKill\fP ()"
.br
.in -1c

Properties inherited from \fBELayer\fP
.in +1c
.ti -1c
.RI "static \fBCore\fP \fBcore\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGame\fP \fBgame\fP\fR [get]\fP"
.br
.ti -1c
.RI "static bool \fBAdvMode\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBPlayer\fP \fBplayer\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBChara\fP \fBpc\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFaction\fP \fBHome\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBUI\fP \fBui\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBMap\fP \fB_map\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBZone\fP \fB_zone\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBScene\fP \fBscene\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBBaseGameScreen\fP \fBscreen\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBCoreConfig\fP \fBconfig\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameSetting\fP \fBsetting\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBColorProfile\fP \fBColors\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBsources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBWorld\fP \fBworld\fP\fR [get]\fP"
.br
.ti -1c
.RI "static SoundManager \fBSound\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBCoreDebug\fP \fBdebug\fP\fR [get]\fP"
.br
.ti -1c
.RI "bool \fBIsFloat\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual string \fBIdHelp\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB10\fP of file \fBLayerFaith\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void LayerFaith\&.Activate (\fBReligion\fP r, Action< \fBReligion\fP > _onWorship)"

.PP
Definition at line \fB13\fP of file \fBLayerFaith\&.cs\fP\&.
.SS "void LayerFaith\&.AddReligion (\fBReligion\fP r)"

.PP
Definition at line \fB126\fP of file \fBLayerFaith\&.cs\fP\&.
.SS "void LayerFaith\&.Move (int a)"

.PP
Definition at line \fB45\fP of file \fBLayerFaith\&.cs\fP\&.
.SS "void LayerFaith\&.RefreshSlots ()"

.PP
Definition at line \fB61\fP of file \fBLayerFaith\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "float LayerFaith\&.bgAlpha"

.PP
Definition at line \fB148\fP of file \fBLayerFaith\&.cs\fP\&.
.SS "int LayerFaith\&.index"

.PP
Definition at line \fB174\fP of file \fBLayerFaith\&.cs\fP\&.
.SS "bool LayerFaith\&.isBranchFaith"

.PP
Definition at line \fB170\fP of file \fBLayerFaith\&.cs\fP\&.
.SS "List<UIItem> LayerFaith\&.items = new List<UIItem>()"

.PP
Definition at line \fB178\fP of file \fBLayerFaith\&.cs\fP\&.
.SS "LayoutGroup LayerFaith\&.layout"

.PP
Definition at line \fB163\fP of file \fBLayerFaith\&.cs\fP\&.
.SS "UIItem LayerFaith\&.moldItem"

.PP
Definition at line \fB160\fP of file \fBLayerFaith\&.cs\fP\&.
.SS "Action<\fBReligion\fP> LayerFaith\&.onWorship"

.PP
Definition at line \fB166\fP of file \fBLayerFaith\&.cs\fP\&.
.SS "List<UIItem> LayerFaith\&.orders = new List<UIItem>()"

.PP
Definition at line \fB182\fP of file \fBLayerFaith\&.cs\fP\&.
.SS "List<\fBLayerFaith\&.Slot\fP> LayerFaith\&.slots"

.PP
Definition at line \fB157\fP of file \fBLayerFaith\&.cs\fP\&.
.SS "\fBLayerFaith\&.Slot\fP LayerFaith\&.slotVoid"

.PP
Definition at line \fB154\fP of file \fBLayerFaith\&.cs\fP\&.
.SS "float LayerFaith\&.startDelay"

.PP
Definition at line \fB151\fP of file \fBLayerFaith\&.cs\fP\&.
.SS "Vector2 LayerFaith\&.startPos"

.PP
Definition at line \fB142\fP of file \fBLayerFaith\&.cs\fP\&.
.SS "float LayerFaith\&.time"

.PP
Definition at line \fB145\fP of file \fBLayerFaith\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
