.TH "LayerQuestBoard" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LayerQuestBoard
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBELayer\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnInit\fP ()"
.br
.ti -1c
.RI "override void \fBOnSwitchContent\fP (Window window)"
.br
.ti -1c
.RI "void \fBRefreshQuest\fP ()"
.br
.ti -1c
.RI "void \fBRefreshHire\fP ()"
.br
.ti -1c
.RI "void \fBRefreshRanking\fP ()"
.br
.ti -1c
.RI "override void \fBOnKill\fP ()"
.br
.in -1c

Public Member Functions inherited from \fBELayer\fP
.in +1c
.ti -1c
.RI "override void \fBOnBeforeAddLayer\fP ()"
.br
.ti -1c
.RI "void \fBInitInspector\fP ()"
.br
.ti -1c
.RI "override void \fBInit\fP ()"
.br
.ti -1c
.RI "override void \fBOnAfterAddLayer\fP ()"
.br
.ti -1c
.RI "void \fBTryShowHelp\fP ()"
.br
.ti -1c
.RI "void \fBAddLayerToUI\fP (string id)"
.br
.ti -1c
.RI "void \fBTryShowHint\fP (string _langHint=null)"
.br
.ti -1c
.RI "void \fBTalkHomeMemeber\fP (string id)"
.br
.ti -1c
.RI "void \fBTalkMaid\fP (string id)"
.br
.ti -1c
.RI "override void \fBOnRightClick\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "UIList \fBlist\fP"
.br
.ti -1c
.RI "UIList \fBlistHire\fP"
.br
.ti -1c
.RI "UIDynamicList \fBlistRanking\fP"
.br
.ti -1c
.RI "UIText \fBtextClient\fP"
.br
.ti -1c
.RI "UIText \fBtextTitle\fP"
.br
.ti -1c
.RI "UIText \fBtextDetail\fP"
.br
.ti -1c
.RI "UIText \fBtextHours\fP"
.br
.ti -1c
.RI "UIText \fBtextNote\fP"
.br
.ti -1c
.RI "UIText \fBtextReward\fP"
.br
.ti -1c
.RI "UIText \fBtextQuestLimit\fP"
.br
.ti -1c
.RI "\fBPortrait\fP \fBportrait\fP"
.br
.ti -1c
.RI "UIButton \fBbuttonTalk\fP"
.br
.ti -1c
.RI "\fBUICurrency\fP \fBuiCurrency\fP"
.br
.ti -1c
.RI "Gradient \fBgradientRank\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Static Public Member Functions inherited from \fBELayer\fP
.in +1c
.ti -1c
.RI "static int \fBrnd\fP (int a)"
.br
.in -1c

Protected Member Functions inherited from \fBELayer\fP
.in +1c
.ti -1c
.RI "override void \fB_Close\fP ()"
.br
.ti -1c
.RI "override void \fBKill\fP ()"
.br
.in -1c

Properties inherited from \fBELayer\fP
.in +1c
.ti -1c
.RI "static \fBCore\fP \fBcore\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGame\fP \fBgame\fP\fR [get]\fP"
.br
.ti -1c
.RI "static bool \fBAdvMode\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBPlayer\fP \fBplayer\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBChara\fP \fBpc\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFaction\fP \fBHome\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBUI\fP \fBui\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBMap\fP \fB_map\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBZone\fP \fB_zone\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBScene\fP \fBscene\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBBaseGameScreen\fP \fBscreen\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBCoreConfig\fP \fBconfig\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameSetting\fP \fBsetting\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBColorProfile\fP \fBColors\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBsources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBWorld\fP \fBworld\fP\fR [get]\fP"
.br
.ti -1c
.RI "static SoundManager \fBSound\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBCoreDebug\fP \fBdebug\fP\fR [get]\fP"
.br
.ti -1c
.RI "bool \fBIsFloat\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual string \fBIdHelp\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB7\fP of file \fBLayerQuestBoard\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void LayerQuestBoard\&.OnInit ()"

.PP
Definition at line \fB10\fP of file \fBLayerQuestBoard\&.cs\fP\&.
.SS "override void LayerQuestBoard\&.OnKill ()"

.PP
Definition at line \fB193\fP of file \fBLayerQuestBoard\&.cs\fP\&.
.SS "override void LayerQuestBoard\&.OnSwitchContent (Window window)"

.PP
Definition at line \fB20\fP of file \fBLayerQuestBoard\&.cs\fP\&.
.SS "void LayerQuestBoard\&.RefreshHire ()"

.PP
Definition at line \fB92\fP of file \fBLayerQuestBoard\&.cs\fP\&.
.SS "void LayerQuestBoard\&.RefreshQuest ()"

.PP
Definition at line \fB57\fP of file \fBLayerQuestBoard\&.cs\fP\&.
.SS "void LayerQuestBoard\&.RefreshRanking ()"

.PP
Definition at line \fB152\fP of file \fBLayerQuestBoard\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "UIButton LayerQuestBoard\&.buttonTalk"

.PP
Definition at line \fB242\fP of file \fBLayerQuestBoard\&.cs\fP\&.
.SS "Gradient LayerQuestBoard\&.gradientRank"

.PP
Definition at line \fB248\fP of file \fBLayerQuestBoard\&.cs\fP\&.
.SS "UIList LayerQuestBoard\&.list"

.PP
Definition at line \fB209\fP of file \fBLayerQuestBoard\&.cs\fP\&.
.SS "UIList LayerQuestBoard\&.listHire"

.PP
Definition at line \fB212\fP of file \fBLayerQuestBoard\&.cs\fP\&.
.SS "UIDynamicList LayerQuestBoard\&.listRanking"

.PP
Definition at line \fB215\fP of file \fBLayerQuestBoard\&.cs\fP\&.
.SS "\fBPortrait\fP LayerQuestBoard\&.portrait"

.PP
Definition at line \fB239\fP of file \fBLayerQuestBoard\&.cs\fP\&.
.SS "UIText LayerQuestBoard\&.textClient"

.PP
Definition at line \fB218\fP of file \fBLayerQuestBoard\&.cs\fP\&.
.SS "UIText LayerQuestBoard\&.textDetail"

.PP
Definition at line \fB224\fP of file \fBLayerQuestBoard\&.cs\fP\&.
.SS "UIText LayerQuestBoard\&.textHours"

.PP
Definition at line \fB227\fP of file \fBLayerQuestBoard\&.cs\fP\&.
.SS "UIText LayerQuestBoard\&.textNote"

.PP
Definition at line \fB230\fP of file \fBLayerQuestBoard\&.cs\fP\&.
.SS "UIText LayerQuestBoard\&.textQuestLimit"

.PP
Definition at line \fB236\fP of file \fBLayerQuestBoard\&.cs\fP\&.
.SS "UIText LayerQuestBoard\&.textReward"

.PP
Definition at line \fB233\fP of file \fBLayerQuestBoard\&.cs\fP\&.
.SS "UIText LayerQuestBoard\&.textTitle"

.PP
Definition at line \fB221\fP of file \fBLayerQuestBoard\&.cs\fP\&.
.SS "\fBUICurrency\fP LayerQuestBoard\&.uiCurrency"

.PP
Definition at line \fB245\fP of file \fBLayerQuestBoard\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
