.TH "LayerFeedback" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LayerFeedback
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBELayer\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnInit\fP ()"
.br
.ti -1c
.RI "void \fBValidate\fP ()"
.br
.ti -1c
.RI "void \fBCollectFiles\fP ()"
.br
.ti -1c
.RI "void \fBOnCancel\fP ()"
.br
.ti -1c
.RI "void \fBOnSubmit\fP ()"
.br
.ti -1c
.RI "string \fBGetSystemText\fP ()"
.br
.in -1c

Public Member Functions inherited from \fBELayer\fP
.in +1c
.ti -1c
.RI "override void \fBOnBeforeAddLayer\fP ()"
.br
.ti -1c
.RI "void \fBInitInspector\fP ()"
.br
.ti -1c
.RI "override void \fBInit\fP ()"
.br
.ti -1c
.RI "override void \fBOnAfterAddLayer\fP ()"
.br
.ti -1c
.RI "void \fBTryShowHelp\fP ()"
.br
.ti -1c
.RI "void \fBAddLayerToUI\fP (string id)"
.br
.ti -1c
.RI "void \fBTryShowHint\fP (string _langHint=null)"
.br
.ti -1c
.RI "void \fBTalkHomeMemeber\fP (string id)"
.br
.ti -1c
.RI "void \fBTalkMaid\fP (string id)"
.br
.ti -1c
.RI "override void \fBOnRightClick\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "UIText \fBtextProgress\fP"
.br
.ti -1c
.RI "InputField \fBinputVersion\fP"
.br
.ti -1c
.RI "InputField \fBinputName\fP"
.br
.ti -1c
.RI "InputField \fBinputEmail\fP"
.br
.ti -1c
.RI "InputField \fBinputLang\fP"
.br
.ti -1c
.RI "InputField \fBinputSummary\fP"
.br
.ti -1c
.RI "InputField \fBinputDetail\fP"
.br
.ti -1c
.RI "FeedbackForm \fBform\fP"
.br
.ti -1c
.RI "DebugLogCollector \fBcollector\fP"
.br
.ti -1c
.RI "Transform \fBtransUpload\fP"
.br
.ti -1c
.RI "UIDropdown \fBddSave\fP"
.br
.ti -1c
.RI "Toggle \fBtoggleSave\fP"
.br
.ti -1c
.RI "Toggle \fBtoggleScreenshot\fP"
.br
.ti -1c
.RI "\fBGameIndex\fP \fBsaveIndex\fP"
.br
.ti -1c
.RI "CanvasGroup \fBcgForm\fP"
.br
.ti -1c
.RI "CategoryDropdown \fBcategory\fP"
.br
.ti -1c
.RI "Button \fBbuttonSubmit\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static string \fBlastSummary\fP = ''"
.br
.ti -1c
.RI "static string \fBlastDetail\fP = ''"
.br
.in -1c
.SS "Additional Inherited Members"


Static Public Member Functions inherited from \fBELayer\fP
.in +1c
.ti -1c
.RI "static int \fBrnd\fP (int a)"
.br
.in -1c

Protected Member Functions inherited from \fBELayer\fP
.in +1c
.ti -1c
.RI "override void \fB_Close\fP ()"
.br
.ti -1c
.RI "override void \fBKill\fP ()"
.br
.in -1c

Properties inherited from \fBELayer\fP
.in +1c
.ti -1c
.RI "static \fBCore\fP \fBcore\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGame\fP \fBgame\fP\fR [get]\fP"
.br
.ti -1c
.RI "static bool \fBAdvMode\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBPlayer\fP \fBplayer\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBChara\fP \fBpc\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFaction\fP \fBHome\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBUI\fP \fBui\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBMap\fP \fB_map\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBZone\fP \fB_zone\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBScene\fP \fBscene\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBBaseGameScreen\fP \fBscreen\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBCoreConfig\fP \fBconfig\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameSetting\fP \fBsetting\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBColorProfile\fP \fBColors\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBsources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBWorld\fP \fBworld\fP\fR [get]\fP"
.br
.ti -1c
.RI "static SoundManager \fBSound\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBCoreDebug\fP \fBdebug\fP\fR [get]\fP"
.br
.ti -1c
.RI "bool \fBIsFloat\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual string \fBIdHelp\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB12\fP of file \fBLayerFeedback\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void LayerFeedback\&.CollectFiles ()"

.PP
Definition at line \fB96\fP of file \fBLayerFeedback\&.cs\fP\&.
.SS "string LayerFeedback\&.GetSystemText ()"

.PP
Definition at line \fB155\fP of file \fBLayerFeedback\&.cs\fP\&.
.SS "void LayerFeedback\&.OnCancel ()"

.PP
Definition at line \fB127\fP of file \fBLayerFeedback\&.cs\fP\&.
.SS "override void LayerFeedback\&.OnInit ()"

.PP
Definition at line \fB15\fP of file \fBLayerFeedback\&.cs\fP\&.
.SS "void LayerFeedback\&.OnSubmit ()"

.PP
Definition at line \fB136\fP of file \fBLayerFeedback\&.cs\fP\&.
.SS "void LayerFeedback\&.Validate ()"

.PP
Definition at line \fB81\fP of file \fBLayerFeedback\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "Button LayerFeedback\&.buttonSubmit"

.PP
Definition at line \fB234\fP of file \fBLayerFeedback\&.cs\fP\&.
.SS "CategoryDropdown LayerFeedback\&.category"

.PP
Definition at line \fB231\fP of file \fBLayerFeedback\&.cs\fP\&.
.SS "CanvasGroup LayerFeedback\&.cgForm"

.PP
Definition at line \fB228\fP of file \fBLayerFeedback\&.cs\fP\&.
.SS "DebugLogCollector LayerFeedback\&.collector"

.PP
Definition at line \fB210\fP of file \fBLayerFeedback\&.cs\fP\&.
.SS "UIDropdown LayerFeedback\&.ddSave"

.PP
Definition at line \fB216\fP of file \fBLayerFeedback\&.cs\fP\&.
.SS "FeedbackForm LayerFeedback\&.form"

.PP
Definition at line \fB207\fP of file \fBLayerFeedback\&.cs\fP\&.
.SS "InputField LayerFeedback\&.inputDetail"

.PP
Definition at line \fB204\fP of file \fBLayerFeedback\&.cs\fP\&.
.SS "InputField LayerFeedback\&.inputEmail"

.PP
Definition at line \fB195\fP of file \fBLayerFeedback\&.cs\fP\&.
.SS "InputField LayerFeedback\&.inputLang"

.PP
Definition at line \fB198\fP of file \fBLayerFeedback\&.cs\fP\&.
.SS "InputField LayerFeedback\&.inputName"

.PP
Definition at line \fB192\fP of file \fBLayerFeedback\&.cs\fP\&.
.SS "InputField LayerFeedback\&.inputSummary"

.PP
Definition at line \fB201\fP of file \fBLayerFeedback\&.cs\fP\&.
.SS "InputField LayerFeedback\&.inputVersion"

.PP
Definition at line \fB189\fP of file \fBLayerFeedback\&.cs\fP\&.
.SS "string LayerFeedback\&.lastDetail = ''\fR [static]\fP"

.PP
Definition at line \fB183\fP of file \fBLayerFeedback\&.cs\fP\&.
.SS "string LayerFeedback\&.lastSummary = ''\fR [static]\fP"

.PP
Definition at line \fB180\fP of file \fBLayerFeedback\&.cs\fP\&.
.SS "\fBGameIndex\fP LayerFeedback\&.saveIndex"

.PP
Definition at line \fB225\fP of file \fBLayerFeedback\&.cs\fP\&.
.SS "UIText LayerFeedback\&.textProgress"

.PP
Definition at line \fB186\fP of file \fBLayerFeedback\&.cs\fP\&.
.SS "Toggle LayerFeedback\&.toggleSave"

.PP
Definition at line \fB219\fP of file \fBLayerFeedback\&.cs\fP\&.
.SS "Toggle LayerFeedback\&.toggleScreenshot"

.PP
Definition at line \fB222\fP of file \fBLayerFeedback\&.cs\fP\&.
.SS "Transform LayerFeedback\&.transUpload"

.PP
Definition at line \fB213\fP of file \fBLayerFeedback\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
