.TH "LayerHoard" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LayerHoard
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBELayer\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnAfterInit\fP ()"
.br
.ti -1c
.RI "void \fBReset\fP ()"
.br
.ti -1c
.RI "override void \fBOnKill\fP ()"
.br
.ti -1c
.RI "void \fBAddRandom\fP ()"
.br
.ti -1c
.RI "void \fBGenerate\fP ()"
.br
.ti -1c
.RI "void \fBOnClickClear\fP ()"
.br
.ti -1c
.RI "void \fBOnClickNextMode\fP ()"
.br
.ti -1c
.RI "void \fBOnClickConfig\fP ()"
.br
.in -1c

Public Member Functions inherited from \fBELayer\fP
.in +1c
.ti -1c
.RI "override void \fBOnBeforeAddLayer\fP ()"
.br
.ti -1c
.RI "void \fBInitInspector\fP ()"
.br
.ti -1c
.RI "override void \fBInit\fP ()"
.br
.ti -1c
.RI "override void \fBOnAfterAddLayer\fP ()"
.br
.ti -1c
.RI "void \fBTryShowHelp\fP ()"
.br
.ti -1c
.RI "void \fBAddLayerToUI\fP (string id)"
.br
.ti -1c
.RI "void \fBTryShowHint\fP (string _langHint=null)"
.br
.ti -1c
.RI "void \fBTalkHomeMemeber\fP (string id)"
.br
.ti -1c
.RI "void \fBTalkMaid\fP (string id)"
.br
.ti -1c
.RI "override void \fBOnRightClick\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBHoardActor\fP \fBactor\fP"
.br
.ti -1c
.RI "bool \fBautoList\fP"
.br
.ti -1c
.RI "int \fBautoNum\fP"
.br
.ti -1c
.RI "float \fBidleTimer\fP"
.br
.ti -1c
.RI "float \fBfadeSpeed\fP"
.br
.ti -1c
.RI "CanvasGroup \fBcg\fP"
.br
.ti -1c
.RI "UIText \fBtextMode\fP"
.br
.ti -1c
.RI "UIText \fBtextScore\fP"
.br
.ti -1c
.RI "UIText \fBtextTime\fP"
.br
.ti -1c
.RI "UIButton[] \fBdebugButtons\fP"
.br
.ti -1c
.RI "LayoutGroup \fBlayoutMenu\fP"
.br
.ti -1c
.RI "int \fBv\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBHoard\fP \fBhoard\fP\fR [get]\fP"
.br
.in -1c

Properties inherited from \fBELayer\fP
.in +1c
.ti -1c
.RI "static \fBCore\fP \fBcore\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGame\fP \fBgame\fP\fR [get]\fP"
.br
.ti -1c
.RI "static bool \fBAdvMode\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBPlayer\fP \fBplayer\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBChara\fP \fBpc\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFaction\fP \fBHome\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBUI\fP \fBui\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBMap\fP \fB_map\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBZone\fP \fB_zone\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBScene\fP \fBscene\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBBaseGameScreen\fP \fBscreen\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBCoreConfig\fP \fBconfig\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameSetting\fP \fBsetting\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBColorProfile\fP \fBColors\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBsources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBWorld\fP \fBworld\fP\fR [get]\fP"
.br
.ti -1c
.RI "static SoundManager \fBSound\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBCoreDebug\fP \fBdebug\fP\fR [get]\fP"
.br
.ti -1c
.RI "bool \fBIsFloat\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual string \fBIdHelp\fP\fR [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Static Public Member Functions inherited from \fBELayer\fP
.in +1c
.ti -1c
.RI "static int \fBrnd\fP (int a)"
.br
.in -1c

Protected Member Functions inherited from \fBELayer\fP
.in +1c
.ti -1c
.RI "override void \fB_Close\fP ()"
.br
.ti -1c
.RI "override void \fBKill\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB7\fP of file \fBLayerHoard\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void LayerHoard\&.AddRandom ()"

.PP
Definition at line \fB143\fP of file \fBLayerHoard\&.cs\fP\&.
.SS "void LayerHoard\&.Generate ()"

.PP
Definition at line \fB157\fP of file \fBLayerHoard\&.cs\fP\&.
.SS "override void LayerHoard\&.OnAfterInit ()"

.PP
Definition at line \fB20\fP of file \fBLayerHoard\&.cs\fP\&.
.SS "void LayerHoard\&.OnClickClear ()"

.PP
Definition at line \fB172\fP of file \fBLayerHoard\&.cs\fP\&.
.SS "void LayerHoard\&.OnClickConfig ()"

.PP
Definition at line \fB188\fP of file \fBLayerHoard\&.cs\fP\&.
.SS "void LayerHoard\&.OnClickNextMode ()"

.PP
Definition at line \fB180\fP of file \fBLayerHoard\&.cs\fP\&.
.SS "override void LayerHoard\&.OnKill ()"

.PP
Definition at line \fB57\fP of file \fBLayerHoard\&.cs\fP\&.
.SS "void LayerHoard\&.Reset ()"

.PP
Definition at line \fB50\fP of file \fBLayerHoard\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBHoardActor\fP LayerHoard\&.actor"

.PP
Definition at line \fB227\fP of file \fBLayerHoard\&.cs\fP\&.
.SS "bool LayerHoard\&.autoList"

.PP
Definition at line \fB230\fP of file \fBLayerHoard\&.cs\fP\&.
.SS "int LayerHoard\&.autoNum"

.PP
Definition at line \fB233\fP of file \fBLayerHoard\&.cs\fP\&.
.SS "CanvasGroup LayerHoard\&.cg"

.PP
Definition at line \fB242\fP of file \fBLayerHoard\&.cs\fP\&.
.SS "UIButton [] LayerHoard\&.debugButtons"

.PP
Definition at line \fB254\fP of file \fBLayerHoard\&.cs\fP\&.
.SS "float LayerHoard\&.fadeSpeed"

.PP
Definition at line \fB239\fP of file \fBLayerHoard\&.cs\fP\&.
.SS "float LayerHoard\&.idleTimer"

.PP
Definition at line \fB236\fP of file \fBLayerHoard\&.cs\fP\&.
.SS "LayoutGroup LayerHoard\&.layoutMenu"

.PP
Definition at line \fB257\fP of file \fBLayerHoard\&.cs\fP\&.
.SS "UIText LayerHoard\&.textMode"

.PP
Definition at line \fB245\fP of file \fBLayerHoard\&.cs\fP\&.
.SS "UIText LayerHoard\&.textScore"

.PP
Definition at line \fB248\fP of file \fBLayerHoard\&.cs\fP\&.
.SS "UIText LayerHoard\&.textTime"

.PP
Definition at line \fB251\fP of file \fBLayerHoard\&.cs\fP\&.
.SS "int LayerHoard\&.v"

.PP
Definition at line \fB263\fP of file \fBLayerHoard\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "\fBHoard\fP LayerHoard\&.hoard\fR [get]\fP"

.PP
Definition at line \fB11\fP of file \fBLayerHoard\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
