.TH "LightControl" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LightControl
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBenableLight\fP = true"
.br
.ti -1c
.RI "bool \fBenableHaze\fP = true"
.br
.ti -1c
.RI "float \fBlightRange\fP = 300f"
.br
.ti -1c
.RI "float \fBlightIntensity\fP = 1f"
.br
.ti -1c
.RI "float \fBhazeLevel\fP = 120f"
.br
.ti -1c
.RI "Light \fBparticleLight\fP"
.br
.ti -1c
.RI "GameObject \fBHaze\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB6\fP of file \fBLightControl\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "bool LightControl\&.enableHaze = true"

.PP
Definition at line \fB36\fP of file \fBLightControl\&.cs\fP\&.
.SS "bool LightControl\&.enableLight = true"

.PP
Definition at line \fB33\fP of file \fBLightControl\&.cs\fP\&.
.SS "GameObject LightControl\&.Haze"

.PP
Definition at line \fB54\fP of file \fBLightControl\&.cs\fP\&.
.SS "float LightControl\&.hazeLevel = 120f"

.PP
Definition at line \fB46\fP of file \fBLightControl\&.cs\fP\&.
.SS "float LightControl\&.lightIntensity = 1f"

.PP
Definition at line \fB42\fP of file \fBLightControl\&.cs\fP\&.
.SS "float LightControl\&.lightRange = 300f"

.PP
Definition at line \fB39\fP of file \fBLightControl\&.cs\fP\&.
.SS "Light LightControl\&.particleLight"

.PP
Definition at line \fB50\fP of file \fBLightControl\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
