.TH "LiquidProfile" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LiquidProfile
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBEScriptable\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBApply\fP (Color? previewColor=null)"
.br
.ti -1c
.RI "void \fBApplyColor\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBLiquidProfile\fP \fBGet\fP (string id)"
.br
.ti -1c
.RI "static void \fBApply\fP (string id)"
.br
.in -1c

Static Public Member Functions inherited from \fBEScriptable\fP
.in +1c
.ti -1c
.RI "static int \fBrnd\fP (int a)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Color \fBmodColor\fP"
.br
.ti -1c
.RI "float \fBtransparency\fP"
.br
.ti -1c
.RI "Texture2D \fBsurface\fP"
.br
.ti -1c
.RI "Vector4 \fBsurfaceAnime\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB6\fP of file \fBLiquidProfile\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void LiquidProfile\&.Apply (Color? previewColor = \fRnull\fP)"

.PP
Definition at line \fB21\fP of file \fBLiquidProfile\&.cs\fP\&.
.SS "static void LiquidProfile\&.Apply (string id)\fR [static]\fP"

.PP
Definition at line \fB15\fP of file \fBLiquidProfile\&.cs\fP\&.
.SS "void LiquidProfile\&.ApplyColor ()"

.PP
Definition at line \fB33\fP of file \fBLiquidProfile\&.cs\fP\&.
.SS "static \fBLiquidProfile\fP LiquidProfile\&.Get (string id)\fR [static]\fP"

.PP
Definition at line \fB9\fP of file \fBLiquidProfile\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "Color LiquidProfile\&.modColor"

.PP
Definition at line \fB61\fP of file \fBLiquidProfile\&.cs\fP\&.
.SS "Texture2D LiquidProfile\&.surface"

.PP
Definition at line \fB67\fP of file \fBLiquidProfile\&.cs\fP\&.
.SS "Vector4 LiquidProfile\&.surfaceAnime"

.PP
Definition at line \fB70\fP of file \fBLiquidProfile\&.cs\fP\&.
.SS "float LiquidProfile\&.transparency"

.PP
Definition at line \fB64\fP of file \fBLiquidProfile\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
