.TH "Lot" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Lot
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBEClass\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetBaseRoom\fP (\fBRoom\fP r)"
.br
.ti -1c
.RI "void \fBRefreshData\fP (\fBTraitHouseBoard\&.Data\fP data)"
.br
.ti -1c
.RI "void \fBAddConnectedRooms\fP (\fBRoom\fP r2)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBid\fP"
.br
.ti -1c
.RI "int \fBheight\fP = 2"
.br
.ti -1c
.RI "int \fBidRoofStyle\fP"
.br
.ti -1c
.RI "int \fBidBGM\fP"
.br
.ti -1c
.RI "int \fBheightFix\fP"
.br
.ti -1c
.RI "int \fBidRoofTile\fP"
.br
.ti -1c
.RI "int \fBidBlock\fP"
.br
.ti -1c
.RI "int \fBidRamp\fP"
.br
.ti -1c
.RI "int \fBidDeco\fP"
.br
.ti -1c
.RI "int \fBidDeco2\fP"
.br
.ti -1c
.RI "int \fBcolRoof\fP"
.br
.ti -1c
.RI "int \fBcolBlock\fP"
.br
.ti -1c
.RI "int \fBcolDeco\fP"
.br
.ti -1c
.RI "int \fBcolDeco2\fP"
.br
.ti -1c
.RI "int \fBdecoFix\fP"
.br
.ti -1c
.RI "int \fBdecoFix2\fP"
.br
.ti -1c
.RI "bool \fBreverse\fP"
.br
.ti -1c
.RI "bool \fBsnow\fP"
.br
.ti -1c
.RI "bool \fBaltRoof\fP"
.br
.ti -1c
.RI "bool \fBfullblock\fP"
.br
.ti -1c
.RI "int \fBx\fP"
.br
.ti -1c
.RI "int \fBz\fP"
.br
.ti -1c
.RI "int \fBmx\fP"
.br
.ti -1c
.RI "int \fBmz\fP"
.br
.ti -1c
.RI "int \fBmh\fP"
.br
.ti -1c
.RI "bool \fBsync\fP"
.br
.ti -1c
.RI "bool \fBdirty\fP"
.br
.ti -1c
.RI "float \fBrealHeight\fP"
.br
.ti -1c
.RI "float \fBlight\fP"
.br
.ti -1c
.RI "\fBPoint\fP \fBpointMinX\fP"
.br
.ti -1c
.RI "\fBPoint\fP \fBpointMaxX\fP"
.br
.ti -1c
.RI "\fBTraitHouseBoard\fP \fBboard\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static \fBLot\fP \fBVoid\fP = new \fBLot\fP()"
.br
.ti -1c
.RI "static Dictionary< int, int > \fBroofCount\fP = new Dictionary<int, int>()"
.br
.in -1c

Static Public Attributes inherited from \fBEClass\fP
.in +1c
.ti -1c
.RI "static \fBCore\fP \fBcore\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Static Public Member Functions inherited from \fBEClass\fP
.in +1c
.ti -1c
.RI "static int \fBrnd\fP (int a)"
.br
.ti -1c
.RI "static int \fBcurve\fP (int a, int start, int step, int rate=75)"
.br
.ti -1c
.RI "static int \fBrndHalf\fP (int a)"
.br
.ti -1c
.RI "static float \fBrndf\fP (float a)"
.br
.ti -1c
.RI "static int \fBrndSqrt\fP (int a)"
.br
.ti -1c
.RI "static void \fBWait\fP (float a, \fBCard\fP c)"
.br
.ti -1c
.RI "static void \fBWait\fP (float a, \fBPoint\fP p)"
.br
.ti -1c
.RI "static int \fBBigger\fP (int a, int b)"
.br
.ti -1c
.RI "static int \fBSmaller\fP (int a, int b)"
.br
.in -1c

Properties inherited from \fBEClass\fP
.in +1c
.ti -1c
.RI "static \fBGame\fP \fBgame\fP\fR [get]\fP"
.br
.ti -1c
.RI "static bool \fBAdvMode\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBPlayer\fP \fBplayer\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBChara\fP \fBpc\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBUI\fP \fBui\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBMap\fP \fB_map\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBZone\fP \fB_zone\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranchOrHomeBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFaction\fP \fBHome\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFaction\fP \fBWilds\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBScene\fP \fBscene\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBBaseGameScreen\fP \fBscreen\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameSetting\fP \fBsetting\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameData\fP \fBgamedata\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBColorProfile\fP \fBColors\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBWorld\fP \fBworld\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBsources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBeditorSources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static SoundManager \fBSound\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBCoreDebug\fP \fBdebug\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB6\fP of file \fBLot\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Lot\&.AddConnectedRooms (\fBRoom\fP r2)"

.PP
Definition at line \fB187\fP of file \fBLot\&.cs\fP\&.
.SS "void Lot\&.RefreshData (\fBTraitHouseBoard\&.Data\fP data)"

.PP
Definition at line \fB143\fP of file \fBLot\&.cs\fP\&.
.SS "void Lot\&.SetBaseRoom (\fBRoom\fP r)"

.PP
Definition at line \fB9\fP of file \fBLot\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "bool Lot\&.altRoof"

.PP
Definition at line \fB319\fP of file \fBLot\&.cs\fP\&.
.SS "\fBTraitHouseBoard\fP Lot\&.board"

.PP
Definition at line \fB370\fP of file \fBLot\&.cs\fP\&.
.SS "int Lot\&.colBlock"

.PP
Definition at line \fB298\fP of file \fBLot\&.cs\fP\&.
.SS "int Lot\&.colDeco"

.PP
Definition at line \fB301\fP of file \fBLot\&.cs\fP\&.
.SS "int Lot\&.colDeco2"

.PP
Definition at line \fB304\fP of file \fBLot\&.cs\fP\&.
.SS "int Lot\&.colRoof"

.PP
Definition at line \fB295\fP of file \fBLot\&.cs\fP\&.
.SS "int Lot\&.decoFix"

.PP
Definition at line \fB307\fP of file \fBLot\&.cs\fP\&.
.SS "int Lot\&.decoFix2"

.PP
Definition at line \fB310\fP of file \fBLot\&.cs\fP\&.
.SS "bool Lot\&.dirty"

.PP
Definition at line \fB343\fP of file \fBLot\&.cs\fP\&.
.SS "bool Lot\&.fullblock"

.PP
Definition at line \fB322\fP of file \fBLot\&.cs\fP\&.
.SS "int Lot\&.height = 2"

.PP
Definition at line \fB268\fP of file \fBLot\&.cs\fP\&.
.SS "int Lot\&.heightFix"

.PP
Definition at line \fB277\fP of file \fBLot\&.cs\fP\&.
.SS "int Lot\&.id"

.PP
Definition at line \fB265\fP of file \fBLot\&.cs\fP\&.
.SS "int Lot\&.idBGM"

.PP
Definition at line \fB274\fP of file \fBLot\&.cs\fP\&.
.SS "int Lot\&.idBlock"

.PP
Definition at line \fB283\fP of file \fBLot\&.cs\fP\&.
.SS "int Lot\&.idDeco"

.PP
Definition at line \fB289\fP of file \fBLot\&.cs\fP\&.
.SS "int Lot\&.idDeco2"

.PP
Definition at line \fB292\fP of file \fBLot\&.cs\fP\&.
.SS "int Lot\&.idRamp"

.PP
Definition at line \fB286\fP of file \fBLot\&.cs\fP\&.
.SS "int Lot\&.idRoofStyle"

.PP
Definition at line \fB271\fP of file \fBLot\&.cs\fP\&.
.SS "int Lot\&.idRoofTile"

.PP
Definition at line \fB280\fP of file \fBLot\&.cs\fP\&.
.SS "float Lot\&.light"

.PP
Definition at line \fB349\fP of file \fBLot\&.cs\fP\&.
.SS "int Lot\&.mh"

.PP
Definition at line \fB337\fP of file \fBLot\&.cs\fP\&.
.SS "int Lot\&.mx"

.PP
Definition at line \fB331\fP of file \fBLot\&.cs\fP\&.
.SS "int Lot\&.mz"

.PP
Definition at line \fB334\fP of file \fBLot\&.cs\fP\&.
.SS "\fBPoint\fP Lot\&.pointMaxX"

.PP
Definition at line \fB355\fP of file \fBLot\&.cs\fP\&.
.SS "\fBPoint\fP Lot\&.pointMinX"

.PP
Definition at line \fB352\fP of file \fBLot\&.cs\fP\&.
.SS "float Lot\&.realHeight"

.PP
Definition at line \fB346\fP of file \fBLot\&.cs\fP\&.
.SS "bool Lot\&.reverse"

.PP
Definition at line \fB313\fP of file \fBLot\&.cs\fP\&.
.SS "Dictionary<int, int> Lot\&.roofCount = new Dictionary<int, int>()\fR [static]\fP"

.PP
Definition at line \fB262\fP of file \fBLot\&.cs\fP\&.
.SS "bool Lot\&.snow"

.PP
Definition at line \fB316\fP of file \fBLot\&.cs\fP\&.
.SS "bool Lot\&.sync"

.PP
Definition at line \fB340\fP of file \fBLot\&.cs\fP\&.
.SS "\fBLot\fP Lot\&.Void = new \fBLot\fP()\fR [static]\fP"

.PP
Definition at line \fB259\fP of file \fBLot\&.cs\fP\&.
.SS "int Lot\&.x"

.PP
Definition at line \fB325\fP of file \fBLot\&.cs\fP\&.
.SS "int Lot\&.z"

.PP
Definition at line \fB328\fP of file \fBLot\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
