.TH "MapBounds" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MapBounds
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBEClass\fP\&.
.PP
Inherited by \fBMap\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetBounds\fP (int _x, int _z, int _maxX, int _maxZ)"
.br
.ti -1c
.RI "bool \fBContains\fP (int dx, int dz)"
.br
.ti -1c
.RI "bool \fBContains\fP (\fBPoint\fP p)"
.br
.ti -1c
.RI "\fBPoint\fP \fBGetCenterPos\fP ()"
.br
.ti -1c
.RI "\fBPoint\fP \fBGetRandomTopPos\fP ()"
.br
.ti -1c
.RI "\fBPoint\fP \fBGetRandomRightPos\fP ()"
.br
.ti -1c
.RI "\fBPoint\fP \fBGetRandomBottomPos\fP ()"
.br
.ti -1c
.RI "\fBPoint\fP \fBGetRandomLeftPos\fP ()"
.br
.ti -1c
.RI "\fBPoint\fP \fBGetTopPos\fP (float rate=\-1f)"
.br
.ti -1c
.RI "\fBPoint\fP \fBGetRightPos\fP (float rate=\-1f)"
.br
.ti -1c
.RI "\fBPoint\fP \fBGetBottomPos\fP (float rate=\-1f)"
.br
.ti -1c
.RI "\fBPoint\fP \fBGetLeftPos\fP (float rate=\-1f)"
.br
.ti -1c
.RI "\fBPoint\fP \fBGetRandomPoint\fP ()"
.br
.ti -1c
.RI "\fBPoint\fP \fBGetSpawnPos\fP (int x, int z, int maxX, int maxZ)"
.br
.ti -1c
.RI "bool \fBCanExpand\fP (int a)"
.br
.ti -1c
.RI "void \fBExpand\fP (int a)"
.br
.ti -1c
.RI "\fBPoint\fP \fBGetSurface\fP (int x, int z, bool walkable=true)"
.br
.ti -1c
.RI "\fBPoint\fP \fBGetRandomSurface\fP (int x, int z, int radius, bool walkable=true, bool allowWater=false)"
.br
.ti -1c
.RI "\fBPoint\fP \fBGetRandomSurface\fP (bool centered=false, bool walkable=true, bool allowWater=false)"
.br
.ti -1c
.RI "\fBPoint\fP \fBGetRandomSpawnPos\fP ()"
.br
.ti -1c
.RI "\fBPoint\fP \fBGetRandomEdge\fP (int r=3)"
.br
.ti -1c
.RI "\fBPoint\fP \fBGetRandomSpace\fP (int width, int height, int tries=100)"
.br
.ti -1c
.RI "void \fBForeachCell\fP (Action< \fBCell\fP > action)"
.br
.ti -1c
.RI "void \fBForeachPoint\fP (Action< \fBPoint\fP > action)"
.br
.ti -1c
.RI "void \fBForeachXYZ\fP (Action< int, int > action)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBx\fP"
.br
.ti -1c
.RI "int \fBz\fP"
.br
.ti -1c
.RI "int \fBmaxX\fP"
.br
.ti -1c
.RI "int \fBmaxZ\fP"
.br
.ti -1c
.RI "int \fBSize\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBCenterX\fP\fR [get]\fP"
.br
.ti -1c
.RI "int \fBCenterZ\fP\fR [get]\fP"
.br
.ti -1c
.RI "int \fBWidth\fP\fR [get]\fP"
.br
.ti -1c
.RI "int \fBHeight\fP\fR [get]\fP"
.br
.in -1c

Properties inherited from \fBEClass\fP
.in +1c
.ti -1c
.RI "static \fBGame\fP \fBgame\fP\fR [get]\fP"
.br
.ti -1c
.RI "static bool \fBAdvMode\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBPlayer\fP \fBplayer\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBChara\fP \fBpc\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBUI\fP \fBui\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBMap\fP \fB_map\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBZone\fP \fB_zone\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranchOrHomeBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFaction\fP \fBHome\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFaction\fP \fBWilds\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBScene\fP \fBscene\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBBaseGameScreen\fP \fBscreen\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameSetting\fP \fBsetting\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameData\fP \fBgamedata\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBColorProfile\fP \fBColors\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBWorld\fP \fBworld\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBsources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBeditorSources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static SoundManager \fBSound\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBCoreDebug\fP \fBdebug\fP\fR [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Static Public Member Functions inherited from \fBEClass\fP
.in +1c
.ti -1c
.RI "static int \fBrnd\fP (int a)"
.br
.ti -1c
.RI "static int \fBcurve\fP (int a, int start, int step, int rate=75)"
.br
.ti -1c
.RI "static int \fBrndHalf\fP (int a)"
.br
.ti -1c
.RI "static float \fBrndf\fP (float a)"
.br
.ti -1c
.RI "static int \fBrndSqrt\fP (int a)"
.br
.ti -1c
.RI "static void \fBWait\fP (float a, \fBCard\fP c)"
.br
.ti -1c
.RI "static void \fBWait\fP (float a, \fBPoint\fP p)"
.br
.ti -1c
.RI "static int \fBBigger\fP (int a, int b)"
.br
.ti -1c
.RI "static int \fBSmaller\fP (int a, int b)"
.br
.in -1c

Static Public Attributes inherited from \fBEClass\fP
.in +1c
.ti -1c
.RI "static \fBCore\fP \fBcore\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB6\fP of file \fBMapBounds\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "bool MapBounds\&.CanExpand (int a)"

.PP
Definition at line \fB167\fP of file \fBMapBounds\&.cs\fP\&.
.SS "bool MapBounds\&.Contains (int dx, int dz)"

.PP
Definition at line \fB58\fP of file \fBMapBounds\&.cs\fP\&.
.SS "bool MapBounds\&.Contains (\fBPoint\fP p)"

.PP
Definition at line \fB64\fP of file \fBMapBounds\&.cs\fP\&.
.SS "void MapBounds\&.Expand (int a)"

.PP
Definition at line \fB173\fP of file \fBMapBounds\&.cs\fP\&.
.SS "void MapBounds\&.ForeachCell (Action< \fBCell\fP > action)"

.PP
Definition at line \fB312\fP of file \fBMapBounds\&.cs\fP\&.
.SS "void MapBounds\&.ForeachPoint (Action< \fBPoint\fP > action)"

.PP
Definition at line \fB325\fP of file \fBMapBounds\&.cs\fP\&.
.SS "void MapBounds\&.ForeachXYZ (Action< int, int > action)"

.PP
Definition at line \fB338\fP of file \fBMapBounds\&.cs\fP\&.
.SS "\fBPoint\fP MapBounds\&.GetBottomPos (float rate = \fR\-1f\fP)"

.PP
Definition at line \fB112\fP of file \fBMapBounds\&.cs\fP\&.
.SS "\fBPoint\fP MapBounds\&.GetCenterPos ()"

.PP
Definition at line \fB70\fP of file \fBMapBounds\&.cs\fP\&.
.SS "\fBPoint\fP MapBounds\&.GetLeftPos (float rate = \fR\-1f\fP)"

.PP
Definition at line \fB118\fP of file \fBMapBounds\&.cs\fP\&.
.SS "\fBPoint\fP MapBounds\&.GetRandomBottomPos ()"

.PP
Definition at line \fB88\fP of file \fBMapBounds\&.cs\fP\&.
.SS "\fBPoint\fP MapBounds\&.GetRandomEdge (int r = \fR3\fP)"

.PP
Definition at line \fB252\fP of file \fBMapBounds\&.cs\fP\&.
.SS "\fBPoint\fP MapBounds\&.GetRandomLeftPos ()"

.PP
Definition at line \fB94\fP of file \fBMapBounds\&.cs\fP\&.
.SS "\fBPoint\fP MapBounds\&.GetRandomPoint ()"

.PP
Definition at line \fB124\fP of file \fBMapBounds\&.cs\fP\&.
.SS "\fBPoint\fP MapBounds\&.GetRandomRightPos ()"

.PP
Definition at line \fB82\fP of file \fBMapBounds\&.cs\fP\&.
.SS "\fBPoint\fP MapBounds\&.GetRandomSpace (int width, int height, int tries = \fR100\fP)"

.PP
Definition at line \fB278\fP of file \fBMapBounds\&.cs\fP\&.
.SS "\fBPoint\fP MapBounds\&.GetRandomSpawnPos ()"

.PP
Definition at line \fB238\fP of file \fBMapBounds\&.cs\fP\&.
.SS "\fBPoint\fP MapBounds\&.GetRandomSurface (bool centered = \fRfalse\fP, bool walkable = \fRtrue\fP, bool allowWater = \fRfalse\fP)"

.PP
Definition at line \fB224\fP of file \fBMapBounds\&.cs\fP\&.
.SS "\fBPoint\fP MapBounds\&.GetRandomSurface (int x, int z, int radius, bool walkable = \fRtrue\fP, bool allowWater = \fRfalse\fP)"

.PP
Definition at line \fB210\fP of file \fBMapBounds\&.cs\fP\&.
.SS "\fBPoint\fP MapBounds\&.GetRandomTopPos ()"

.PP
Definition at line \fB76\fP of file \fBMapBounds\&.cs\fP\&.
.SS "\fBPoint\fP MapBounds\&.GetRightPos (float rate = \fR\-1f\fP)"

.PP
Definition at line \fB106\fP of file \fBMapBounds\&.cs\fP\&.
.SS "\fBPoint\fP MapBounds\&.GetSpawnPos (int x, int z, int maxX, int maxZ)"

.PP
Definition at line \fB130\fP of file \fBMapBounds\&.cs\fP\&.
.SS "\fBPoint\fP MapBounds\&.GetSurface (int x, int z, bool walkable = \fRtrue\fP)"

.PP
Definition at line \fB198\fP of file \fBMapBounds\&.cs\fP\&.
.SS "\fBPoint\fP MapBounds\&.GetTopPos (float rate = \fR\-1f\fP)"

.PP
Definition at line \fB100\fP of file \fBMapBounds\&.cs\fP\&.
.SS "void MapBounds\&.SetBounds (int _x, int _z, int _maxX, int _maxZ)"

.PP
Definition at line \fB49\fP of file \fBMapBounds\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int MapBounds\&.maxX"

.PP
Definition at line \fB359\fP of file \fBMapBounds\&.cs\fP\&.
.SS "int MapBounds\&.maxZ"

.PP
Definition at line \fB363\fP of file \fBMapBounds\&.cs\fP\&.
.SS "int MapBounds\&.Size"

.PP
Definition at line \fB367\fP of file \fBMapBounds\&.cs\fP\&.
.SS "int MapBounds\&.x"

.PP
Definition at line \fB351\fP of file \fBMapBounds\&.cs\fP\&.
.SS "int MapBounds\&.z"

.PP
Definition at line \fB355\fP of file \fBMapBounds\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "int MapBounds\&.CenterX\fR [get]\fP"

.PP
Definition at line \fB10\fP of file \fBMapBounds\&.cs\fP\&.
.SS "int MapBounds\&.CenterZ\fR [get]\fP"

.PP
Definition at line \fB20\fP of file \fBMapBounds\&.cs\fP\&.
.SS "int MapBounds\&.Height\fR [get]\fP"

.PP
Definition at line \fB40\fP of file \fBMapBounds\&.cs\fP\&.
.SS "int MapBounds\&.Width\fR [get]\fP"

.PP
Definition at line \fB30\fP of file \fBMapBounds\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
