.TH "MapGenVariation" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MapGenVariation
.SH SYNOPSIS
.br
.PP
.PP
Inherits ScriptableObject\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "string \fBGetText\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "NoiseLayer \fBlayerHeight\fP"
.br
.ti -1c
.RI "NoiseLayer \fBlayerRiver\fP"
.br
.ti -1c
.RI "NoiseLayer \fBlayerStratum\fP"
.br
.ti -1c
.RI "NoiseLayer \fBlayerBiome\fP"
.br
.ti -1c
.RI "\fBBiomeProfile\fP[] \fBbiomeProfiles\fP"
.br
.ti -1c
.RI "\fBBiomeProfile\fP \fBbiomeShore\fP"
.br
.ti -1c
.RI "\fBBiomeProfile\fP \fBbiomeWater\fP"
.br
.ti -1c
.RI "float \fBmaxWaterRatio\fP"
.br
.ti -1c
.RI "bool \fBembark\fP = true"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB6\fP of file \fBMapGenVariation\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "string MapGenVariation\&.GetText ()"

.PP
Definition at line \fB9\fP of file \fBMapGenVariation\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBBiomeProfile\fP [] MapGenVariation\&.biomeProfiles"

.PP
Definition at line \fB27\fP of file \fBMapGenVariation\&.cs\fP\&.
.SS "\fBBiomeProfile\fP MapGenVariation\&.biomeShore"

.PP
Definition at line \fB30\fP of file \fBMapGenVariation\&.cs\fP\&.
.SS "\fBBiomeProfile\fP MapGenVariation\&.biomeWater"

.PP
Definition at line \fB33\fP of file \fBMapGenVariation\&.cs\fP\&.
.SS "bool MapGenVariation\&.embark = true"

.PP
Definition at line \fB39\fP of file \fBMapGenVariation\&.cs\fP\&.
.SS "NoiseLayer MapGenVariation\&.layerBiome"

.PP
Definition at line \fB24\fP of file \fBMapGenVariation\&.cs\fP\&.
.SS "NoiseLayer MapGenVariation\&.layerHeight"

.PP
Definition at line \fB15\fP of file \fBMapGenVariation\&.cs\fP\&.
.SS "NoiseLayer MapGenVariation\&.layerRiver"

.PP
Definition at line \fB18\fP of file \fBMapGenVariation\&.cs\fP\&.
.SS "NoiseLayer MapGenVariation\&.layerStratum"

.PP
Definition at line \fB21\fP of file \fBMapGenVariation\&.cs\fP\&.
.SS "float MapGenVariation\&.maxWaterRatio"

.PP
Definition at line \fB36\fP of file \fBMapGenVariation\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
