.TH "MapHeight" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MapHeight
.SH SYNOPSIS
.br
.PP
.PP
Inherits ScriptableObject\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBheightMod\fP"
.br
.ti -1c
.RI "int \fBbaseHeight\fP"
.br
.ti -1c
.RI "int \fBstep\fP"
.br
.ti -1c
.RI "bool \fBsmoothDownhill\fP"
.br
.ti -1c
.RI "bool \fBmod1\fP"
.br
.ti -1c
.RI "bool \fBmod2\fP"
.br
.ti -1c
.RI "bool \fBmod3\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB5\fP of file \fBMapHeight\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int MapHeight\&.baseHeight"

.PP
Definition at line \fB11\fP of file \fBMapHeight\&.cs\fP\&.
.SS "int MapHeight\&.heightMod"

.PP
Definition at line \fB8\fP of file \fBMapHeight\&.cs\fP\&.
.SS "bool MapHeight\&.mod1"

.PP
Definition at line \fB20\fP of file \fBMapHeight\&.cs\fP\&.
.SS "bool MapHeight\&.mod2"

.PP
Definition at line \fB23\fP of file \fBMapHeight\&.cs\fP\&.
.SS "bool MapHeight\&.mod3"

.PP
Definition at line \fB26\fP of file \fBMapHeight\&.cs\fP\&.
.SS "bool MapHeight\&.smoothDownhill"

.PP
Definition at line \fB17\fP of file \fBMapHeight\&.cs\fP\&.
.SS "int MapHeight\&.step"

.PP
Definition at line \fB14\fP of file \fBMapHeight\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
