.TH "MapPiece.MapPath" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MapPiece.MapPath
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBpath\fP"
.br
.ti -1c
.RI "string \fBtag\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB127\fP of file \fBMapPiece\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "string MapPiece\&.MapPath\&.path"

.PP
Definition at line \fB130\fP of file \fBMapPiece\&.cs\fP\&.
.SS "string MapPiece\&.MapPath\&.tag"

.PP
Definition at line \fB133\fP of file \fBMapPiece\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
