.TH "MapPiece" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MapPiece
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBEScriptable\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBItem\fP"
.br
.ti -1c
.RI "class \fBMapPath\fP"
.br
.in -1c
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBType\fP { \fBAny\fP, \fBDeco\fP, \fBTreasure\fP, \fBTrap\fP, \fBConcert\fP, \fBFarm\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPartialMap\fP \fBGetMap\fP (MapPiece\&.Type type, string tag, float ruin)"
.br
.ti -1c
.RI "void \fBInit\fP ()"
.br
.ti -1c
.RI "void \fBReset\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "List< \fBMapPiece\&.Item\fP > \fBitems\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static bool \fBinitialized\fP"
.br
.ti -1c
.RI "static Dictionary< string, \fBPartialMap\fP > \fBCacheMap\fP = new Dictionary<string, \fBPartialMap\fP>()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "static \fBMapPiece\fP \fBInstance\fP\fR [get]\fP"
.br
.ti -1c
.RI "static bool \fBIsEditor\fP\fR [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Static Public Member Functions inherited from \fBEScriptable\fP
.in +1c
.ti -1c
.RI "static int \fBrnd\fP (int a)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB7\fP of file \fBMapPiece\&.cs\fP\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "enum MapPiece\&.Type"

.PP
Definition at line \fB137\fP of file \fBMapPiece\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBPartialMap\fP MapPiece\&.GetMap (MapPiece\&.Type type, string tag, float ruin)"

.PP
Definition at line \fB35\fP of file \fBMapPiece\&.cs\fP\&.
.SS "void MapPiece\&.Init ()"

.PP
Definition at line \fB82\fP of file \fBMapPiece\&.cs\fP\&.
.SS "void MapPiece\&.Reset ()"

.PP
Definition at line \fB109\fP of file \fBMapPiece\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "Dictionary<string, \fBPartialMap\fP> MapPiece\&.CacheMap = new Dictionary<string, \fBPartialMap\fP>()\fR [static]\fP"

.PP
Definition at line \fB124\fP of file \fBMapPiece\&.cs\fP\&.
.SS "bool MapPiece\&.initialized\fR [static]\fP"

.PP
Definition at line \fB118\fP of file \fBMapPiece\&.cs\fP\&.
.SS "List<\fBMapPiece\&.Item\fP> MapPiece\&.items"

.PP
Definition at line \fB121\fP of file \fBMapPiece\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "\fBMapPiece\fP MapPiece\&.Instance\fR [static]\fP, \fR [get]\fP"

.PP
Definition at line \fB11\fP of file \fBMapPiece\&.cs\fP\&.
.SS "bool MapPiece\&.IsEditor\fR [static]\fP, \fR [get]\fP"

.PP
Definition at line \fB26\fP of file \fBMapPiece\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
