.TH "MATERIAL" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MATERIAL
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBEClass\fP\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBSourceMaterial\&.Row\fP \fBGetRandomMaterial\fP (int lv, string group=null, bool tryLevelMatTier=false)"
.br
.ti -1c
.RI "static \fBSourceMaterial\&.Row\fP \fBGetRandomMaterialFromCategory\fP (int lv, string cat, \fBSourceMaterial\&.Row\fP fallback)"
.br
.ti -1c
.RI "static \fBSourceMaterial\&.Row\fP \fBGetRandomMaterialFromCategory\fP (int lv, string[] cat, \fBSourceMaterial\&.Row\fP fallback)"
.br
.in -1c

Static Public Member Functions inherited from \fBEClass\fP
.in +1c
.ti -1c
.RI "static int \fBrnd\fP (int a)"
.br
.ti -1c
.RI "static int \fBcurve\fP (int a, int start, int step, int rate=75)"
.br
.ti -1c
.RI "static int \fBrndHalf\fP (int a)"
.br
.ti -1c
.RI "static float \fBrndf\fP (float a)"
.br
.ti -1c
.RI "static int \fBrndSqrt\fP (int a)"
.br
.ti -1c
.RI "static void \fBWait\fP (float a, \fBCard\fP c)"
.br
.ti -1c
.RI "static void \fBWait\fP (float a, \fBPoint\fP p)"
.br
.ti -1c
.RI "static int \fBBigger\fP (int a, int b)"
.br
.ti -1c
.RI "static int \fBSmaller\fP (int a, int b)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "const byte \fBoak\fP = 1"
.br
.ti -1c
.RI "const byte \fBgranite\fP = 3"
.br
.ti -1c
.RI "const byte \fBmud\fP = 4"
.br
.ti -1c
.RI "const byte \fBsand\fP = 8"
.br
.ti -1c
.RI "const byte \fBsoil\fP = 45"
.br
.ti -1c
.RI "const byte \fBsnow\fP = 48"
.br
.ti -1c
.RI "const byte \fBwater\fP = 66"
.br
.ti -1c
.RI "const byte \fBwater_fresh\fP = 67"
.br
.ti -1c
.RI "const byte \fBice\fP = 61"
.br
.ti -1c
.RI "const byte \fBgold\fP = 12"
.br
.ti -1c
.RI "const byte \fBwater_sea\fP = 88"
.br
.ti -1c
.RI "const byte \fBprocess\fP = 94"
.br
.ti -1c
.RI "const byte \fBsand_sea\fP = 97"
.br
.ti -1c
.RI "static \fBSourceMaterial\&.Row\fP \fBsourceSnow\fP = EClass\&.sources\&.materials\&.rows[48]"
.br
.ti -1c
.RI "static \fBSourceMaterial\&.Row\fP \fBsourceIce\fP = EClass\&.sources\&.materials\&.rows[61]"
.br
.ti -1c
.RI "static \fBSourceMaterial\&.Row\fP \fBsourceGold\fP = EClass\&.sources\&.materials\&.rows[12]"
.br
.ti -1c
.RI "static \fBSourceMaterial\&.Row\fP \fBsourceOak\fP = EClass\&.sources\&.materials\&.rows[1]"
.br
.in -1c

Static Public Attributes inherited from \fBEClass\fP
.in +1c
.ti -1c
.RI "static \fBCore\fP \fBcore\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "static \fBSourceMaterial\&.Row\fP \fBsourceWaterSea\fP\fR [get]\fP"
.br
.in -1c

Properties inherited from \fBEClass\fP
.in +1c
.ti -1c
.RI "static \fBGame\fP \fBgame\fP\fR [get]\fP"
.br
.ti -1c
.RI "static bool \fBAdvMode\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBPlayer\fP \fBplayer\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBChara\fP \fBpc\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBUI\fP \fBui\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBMap\fP \fB_map\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBZone\fP \fB_zone\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranchOrHomeBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFaction\fP \fBHome\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFaction\fP \fBWilds\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBScene\fP \fBscene\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBBaseGameScreen\fP \fBscreen\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameSetting\fP \fBsetting\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameData\fP \fBgamedata\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBColorProfile\fP \fBColors\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBWorld\fP \fBworld\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBsources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBeditorSources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static SoundManager \fBSound\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBCoreDebug\fP \fBdebug\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB7\fP of file \fBMATERIAL\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "static \fBSourceMaterial\&.Row\fP MATERIAL\&.GetRandomMaterial (int lv, string group = \fRnull\fP, bool tryLevelMatTier = \fRfalse\fP)\fR [static]\fP"

.PP
Definition at line \fB20\fP of file \fBMATERIAL\&.cs\fP\&.
.SS "static \fBSourceMaterial\&.Row\fP MATERIAL\&.GetRandomMaterialFromCategory (int lv, string cat, \fBSourceMaterial\&.Row\fP fallback)\fR [static]\fP"

.PP
Definition at line \fB70\fP of file \fBMATERIAL\&.cs\fP\&.
.SS "static \fBSourceMaterial\&.Row\fP MATERIAL\&.GetRandomMaterialFromCategory (int lv, string[] cat, \fBSourceMaterial\&.Row\fP fallback)\fR [static]\fP"

.PP
Definition at line \fB79\fP of file \fBMATERIAL\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "const byte MATERIAL\&.gold = 12\fR [static]\fP"

.PP
Definition at line \fB122\fP of file \fBMATERIAL\&.cs\fP\&.
.SS "const byte MATERIAL\&.granite = 3\fR [static]\fP"

.PP
Definition at line \fB98\fP of file \fBMATERIAL\&.cs\fP\&.
.SS "const byte MATERIAL\&.ice = 61\fR [static]\fP"

.PP
Definition at line \fB119\fP of file \fBMATERIAL\&.cs\fP\&.
.SS "const byte MATERIAL\&.mud = 4\fR [static]\fP"

.PP
Definition at line \fB101\fP of file \fBMATERIAL\&.cs\fP\&.
.SS "const byte MATERIAL\&.oak = 1\fR [static]\fP"

.PP
Definition at line \fB95\fP of file \fBMATERIAL\&.cs\fP\&.
.SS "const byte MATERIAL\&.process = 94\fR [static]\fP"

.PP
Definition at line \fB128\fP of file \fBMATERIAL\&.cs\fP\&.
.SS "const byte MATERIAL\&.sand = 8\fR [static]\fP"

.PP
Definition at line \fB104\fP of file \fBMATERIAL\&.cs\fP\&.
.SS "const byte MATERIAL\&.sand_sea = 97\fR [static]\fP"

.PP
Definition at line \fB131\fP of file \fBMATERIAL\&.cs\fP\&.
.SS "const byte MATERIAL\&.snow = 48\fR [static]\fP"

.PP
Definition at line \fB110\fP of file \fBMATERIAL\&.cs\fP\&.
.SS "const byte MATERIAL\&.soil = 45\fR [static]\fP"

.PP
Definition at line \fB107\fP of file \fBMATERIAL\&.cs\fP\&.
.SS "\fBSourceMaterial\&.Row\fP MATERIAL\&.sourceGold = EClass\&.sources\&.materials\&.rows[12]\fR [static]\fP"

.PP
Definition at line \fB140\fP of file \fBMATERIAL\&.cs\fP\&.
.SS "\fBSourceMaterial\&.Row\fP MATERIAL\&.sourceIce = EClass\&.sources\&.materials\&.rows[61]\fR [static]\fP"

.PP
Definition at line \fB137\fP of file \fBMATERIAL\&.cs\fP\&.
.SS "\fBSourceMaterial\&.Row\fP MATERIAL\&.sourceOak = EClass\&.sources\&.materials\&.rows[1]\fR [static]\fP"

.PP
Definition at line \fB143\fP of file \fBMATERIAL\&.cs\fP\&.
.SS "\fBSourceMaterial\&.Row\fP MATERIAL\&.sourceSnow = EClass\&.sources\&.materials\&.rows[48]\fR [static]\fP"

.PP
Definition at line \fB134\fP of file \fBMATERIAL\&.cs\fP\&.
.SS "const byte MATERIAL\&.water = 66\fR [static]\fP"

.PP
Definition at line \fB113\fP of file \fBMATERIAL\&.cs\fP\&.
.SS "const byte MATERIAL\&.water_fresh = 67\fR [static]\fP"

.PP
Definition at line \fB116\fP of file \fBMATERIAL\&.cs\fP\&.
.SS "const byte MATERIAL\&.water_sea = 88\fR [static]\fP"

.PP
Definition at line \fB125\fP of file \fBMATERIAL\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "\fBSourceMaterial\&.Row\fP MATERIAL\&.sourceWaterSea\fR [static]\fP, \fR [get]\fP"

.PP
Definition at line \fB11\fP of file \fBMATERIAL\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
