.TH "MeshPass" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MeshPass
.SH SYNOPSIS
.br
.PP
.PP
Inherits ScriptableObject\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBInit\fP ()"
.br
.ti -1c
.RI "unsafe void \fBAdd\fP (\fBPoint\fP point, float tile=0f, float color=0f)"
.br
.ti -1c
.RI "void \fBAdd\fP (ref Vector3 v, float tile=0f, float color=0f)"
.br
.ti -1c
.RI "void \fBAdd\fP (float x, float y, float z, float tile=0f, float color=0f)"
.br
.ti -1c
.RI "void \fBAddWithScale\fP (float x, float y, float z, int tile, float scale)"
.br
.ti -1c
.RI "void \fBAddShadow\fP (\fBMeshPassParam\fP p, ref Vector3 fix)"
.br
.ti -1c
.RI "void \fBAddShadow\fP (float x, float y, float z, \fBShadowData\&.Item\fP s, \fBSourcePref\fP pref, int dir=0, bool snow=false)"
.br
.ti -1c
.RI "void \fBAddWithRotation\fP (float x, float y, float z, float sx, float sy, int tile, float angle, bool flip)"
.br
.ti -1c
.RI "void \fBAdd\fP (\fBMeshPassParam\fP p)"
.br
.ti -1c
.RI "void \fBAdd\fP (float x, float y, float z, float tile, float color, float matColor=0f)"
.br
.ti -1c
.RI "void \fBAdd\fP (\fBMeshPassParam\fP p, float tile, float color, float matColor=0f)"
.br
.ti -1c
.RI "void \fBDraw\fP ()"
.br
.ti -1c
.RI "void \fBDrawEmpty\fP ()"
.br
.ti -1c
.RI "void \fBNextBatch\fP ()"
.br
.ti -1c
.RI "override string \fBToString\fP ()"
.br
.ti -1c
.RI "void \fBRefresh\fP ()"
.br
.ti -1c
.RI "void \fBOnValidate\fP ()"
.br
.ti -1c
.RI "void \fB_Refresh\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBMeshPass\fP \fBsubPass\fP"
.br
.ti -1c
.RI "\fBMeshPass\fP \fBsnowPass\fP"
.br
.ti -1c
.RI "\fBMeshPass\fP \fBshadowPass\fP"
.br
.ti -1c
.RI "Material \fBmat\fP"
.br
.ti -1c
.RI "Mesh \fBmesh\fP"
.br
.ti -1c
.RI "\fBProceduralMesh\fP \fBpmesh\fP"
.br
.ti -1c
.RI "Sprite \fBsprite\fP"
.br
.ti -1c
.RI "bool \fBsetTile\fP"
.br
.ti -1c
.RI "bool \fBsetColor\fP"
.br
.ti -1c
.RI "bool \fBsetMatColor\fP"
.br
.ti -1c
.RI "bool \fBsetExtra\fP"
.br
.ti -1c
.RI "int \fBrenderQueue\fP"
.br
.ti -1c
.RI "\fBMeshPassParam\fP \fB_p\fP = new \fBMeshPassParam\fP()"
.br
.ti -1c
.RI "FilterMode \fBfilter\fP"
.br
.ti -1c
.RI "int \fBlastCount\fP"
.br
.ti -1c
.RI "int \fBlastBatchCount\fP"
.br
.ti -1c
.RI "bool \fBhaveSubPass\fP"
.br
.ti -1c
.RI "bool \fBhaveShadowPass\fP"
.br
.ti -1c
.RI "bool \fBhaveSnowPass\fP"
.br
.ti -1c
.RI "int \fBidx\fP"
.br
.ti -1c
.RI "int \fBbatchIdx\fP"
.br
.ti -1c
.RI "int \fBbatchSize\fP = 1023"
.br
.ti -1c
.RI "List< \fBMeshBatch\fP > \fBbatches\fP = new List<\fBMeshBatch\fP>()"
.br
.ti -1c
.RI "Texture \fBpreserveTex\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "const int \fBTokenLiquid\fP = 10000"
.br
.ti -1c
.RI "const int \fBTokenLowWall\fP = 1000000"
.br
.ti -1c
.RI "const int \fBTokenLowWallDefault\fP = 3000000"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "float \fBmeshX\fP\fR [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB8\fP of file \fBMeshPass\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void MeshPass\&._Refresh ()"

.PP
Definition at line \fB412\fP of file \fBMeshPass\&.cs\fP\&.
.SS "void MeshPass\&.Add (float x, float y, float z, float tile, float color, float matColor = \fR0f\fP)"

.PP
Definition at line \fB228\fP of file \fBMeshPass\&.cs\fP\&.
.SS "void MeshPass\&.Add (float x, float y, float z, float tile = \fR0f\fP, float color = \fR0f\fP)"

.PP
Definition at line \fB75\fP of file \fBMeshPass\&.cs\fP\&.
.SS "void MeshPass\&.Add (\fBMeshPassParam\fP p)"

.PP
Definition at line \fB202\fP of file \fBMeshPass\&.cs\fP\&.
.SS "void MeshPass\&.Add (\fBMeshPassParam\fP p, float tile, float color, float matColor = \fR0f\fP)"

.PP
Definition at line \fB251\fP of file \fBMeshPass\&.cs\fP\&.
.SS "unsafe void MeshPass\&.Add (\fBPoint\fP point, float tile = \fR0f\fP, float color = \fR0f\fP)"

.PP
Definition at line \fB36\fP of file \fBMeshPass\&.cs\fP\&.
.SS "void MeshPass\&.Add (ref Vector3 v, float tile = \fR0f\fP, float color = \fR0f\fP)"

.PP
Definition at line \fB56\fP of file \fBMeshPass\&.cs\fP\&.
.SS "void MeshPass\&.AddShadow (float x, float y, float z, \fBShadowData\&.Item\fP s, \fBSourcePref\fP pref, int dir = \fR0\fP, bool snow = \fRfalse\fP)"

.PP
Definition at line \fB132\fP of file \fBMeshPass\&.cs\fP\&.
.SS "void MeshPass\&.AddShadow (\fBMeshPassParam\fP p, ref Vector3 fix)"

.PP
Definition at line \fB113\fP of file \fBMeshPass\&.cs\fP\&.
.SS "void MeshPass\&.AddWithRotation (float x, float y, float z, float sx, float sy, int tile, float angle, bool flip)"

.PP
Definition at line \fB173\fP of file \fBMeshPass\&.cs\fP\&.
.SS "void MeshPass\&.AddWithScale (float x, float y, float z, int tile, float scale)"

.PP
Definition at line \fB94\fP of file \fBMeshPass\&.cs\fP\&.
.SS "void MeshPass\&.Draw ()"

.PP
Definition at line \fB274\fP of file \fBMeshPass\&.cs\fP\&.
.SS "void MeshPass\&.DrawEmpty ()"

.PP
Definition at line \fB337\fP of file \fBMeshPass\&.cs\fP\&.
.SS "void MeshPass\&.Init ()"

.PP
Definition at line \fB11\fP of file \fBMeshPass\&.cs\fP\&.
.SS "void MeshPass\&.NextBatch ()"

.PP
Definition at line \fB343\fP of file \fBMeshPass\&.cs\fP\&.
.SS "void MeshPass\&.OnValidate ()"

.PP
Definition at line \fB406\fP of file \fBMeshPass\&.cs\fP\&.
.SS "void MeshPass\&.Refresh ()"

.PP
Definition at line \fB375\fP of file \fBMeshPass\&.cs\fP\&.
.SS "override string MeshPass\&.ToString ()"

.PP
Definition at line \fB369\fP of file \fBMeshPass\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBMeshPassParam\fP MeshPass\&._p = new \fBMeshPassParam\fP()"

.PP
Definition at line \fB488\fP of file \fBMeshPass\&.cs\fP\&.
.SS "List<\fBMeshBatch\fP> MeshPass\&.batches = new List<\fBMeshBatch\fP>()"

.PP
Definition at line \fB525\fP of file \fBMeshPass\&.cs\fP\&.
.SS "int MeshPass\&.batchIdx"

.PP
Definition at line \fB517\fP of file \fBMeshPass\&.cs\fP\&.
.SS "int MeshPass\&.batchSize = 1023"

.PP
Definition at line \fB521\fP of file \fBMeshPass\&.cs\fP\&.
.SS "FilterMode MeshPass\&.filter"

.PP
Definition at line \fB491\fP of file \fBMeshPass\&.cs\fP\&.
.SS "bool MeshPass\&.haveShadowPass"

.PP
Definition at line \fB505\fP of file \fBMeshPass\&.cs\fP\&.
.SS "bool MeshPass\&.haveSnowPass"

.PP
Definition at line \fB509\fP of file \fBMeshPass\&.cs\fP\&.
.SS "bool MeshPass\&.haveSubPass"

.PP
Definition at line \fB501\fP of file \fBMeshPass\&.cs\fP\&.
.SS "int MeshPass\&.idx"

.PP
Definition at line \fB513\fP of file \fBMeshPass\&.cs\fP\&.
.SS "int MeshPass\&.lastBatchCount"

.PP
Definition at line \fB497\fP of file \fBMeshPass\&.cs\fP\&.
.SS "int MeshPass\&.lastCount"

.PP
Definition at line \fB494\fP of file \fBMeshPass\&.cs\fP\&.
.SS "Material MeshPass\&.mat"

.PP
Definition at line \fB461\fP of file \fBMeshPass\&.cs\fP\&.
.SS "Mesh MeshPass\&.mesh"

.PP
Definition at line \fB464\fP of file \fBMeshPass\&.cs\fP\&.
.SS "\fBProceduralMesh\fP MeshPass\&.pmesh"

.PP
Definition at line \fB467\fP of file \fBMeshPass\&.cs\fP\&.
.SS "Texture MeshPass\&.preserveTex"

.PP
Definition at line \fB537\fP of file \fBMeshPass\&.cs\fP\&.
.SS "int MeshPass\&.renderQueue"

.PP
Definition at line \fB485\fP of file \fBMeshPass\&.cs\fP\&.
.SS "bool MeshPass\&.setColor"

.PP
Definition at line \fB476\fP of file \fBMeshPass\&.cs\fP\&.
.SS "bool MeshPass\&.setExtra"

.PP
Definition at line \fB482\fP of file \fBMeshPass\&.cs\fP\&.
.SS "bool MeshPass\&.setMatColor"

.PP
Definition at line \fB479\fP of file \fBMeshPass\&.cs\fP\&.
.SS "bool MeshPass\&.setTile"

.PP
Definition at line \fB473\fP of file \fBMeshPass\&.cs\fP\&.
.SS "\fBMeshPass\fP MeshPass\&.shadowPass"

.PP
Definition at line \fB458\fP of file \fBMeshPass\&.cs\fP\&.
.SS "\fBMeshPass\fP MeshPass\&.snowPass"

.PP
Definition at line \fB455\fP of file \fBMeshPass\&.cs\fP\&.
.SS "Sprite MeshPass\&.sprite"

.PP
Definition at line \fB470\fP of file \fBMeshPass\&.cs\fP\&.
.SS "\fBMeshPass\fP MeshPass\&.subPass"

.PP
Definition at line \fB452\fP of file \fBMeshPass\&.cs\fP\&.
.SS "const int MeshPass\&.TokenLiquid = 10000\fR [static]\fP"

.PP
Definition at line \fB443\fP of file \fBMeshPass\&.cs\fP\&.
.SS "const int MeshPass\&.TokenLowWall = 1000000\fR [static]\fP"

.PP
Definition at line \fB446\fP of file \fBMeshPass\&.cs\fP\&.
.SS "const int MeshPass\&.TokenLowWallDefault = 3000000\fR [static]\fP"

.PP
Definition at line \fB449\fP of file \fBMeshPass\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "float MeshPass\&.meshX\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB393\fP of file \fBMeshPass\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
