.TH "MeshBatch" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MeshBatch
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMeshBatch\fP (\fBMeshPass\fP pass)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Matrix4x4[] \fBmatrices\fP"
.br
.ti -1c
.RI "float[] \fBtiles\fP"
.br
.ti -1c
.RI "float[] \fBcolors\fP"
.br
.ti -1c
.RI "float[] \fBmatColors\fP"
.br
.ti -1c
.RI "float[] \fBextras\fP"
.br
.ti -1c
.RI "MaterialPropertyBlock \fBmpb\fP"
.br
.ti -1c
.RI "Material \fBmat\fP"
.br
.ti -1c
.RI "int \fBsize\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB5\fP of file \fBMeshBatch\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MeshBatch\&.MeshBatch (\fBMeshPass\fP pass)"

.PP
Definition at line \fB8\fP of file \fBMeshBatch\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "float [] MeshBatch\&.colors"

.PP
Definition at line \fB48\fP of file \fBMeshBatch\&.cs\fP\&.
.SS "float [] MeshBatch\&.extras"

.PP
Definition at line \fB54\fP of file \fBMeshBatch\&.cs\fP\&.
.SS "Material MeshBatch\&.mat"

.PP
Definition at line \fB60\fP of file \fBMeshBatch\&.cs\fP\&.
.SS "float [] MeshBatch\&.matColors"

.PP
Definition at line \fB51\fP of file \fBMeshBatch\&.cs\fP\&.
.SS "Matrix4x4 [] MeshBatch\&.matrices"

.PP
Definition at line \fB42\fP of file \fBMeshBatch\&.cs\fP\&.
.SS "MaterialPropertyBlock MeshBatch\&.mpb"

.PP
Definition at line \fB57\fP of file \fBMeshBatch\&.cs\fP\&.
.SS "int MeshBatch\&.size"

.PP
Definition at line \fB63\fP of file \fBMeshBatch\&.cs\fP\&.
.SS "float [] MeshBatch\&.tiles"

.PP
Definition at line \fB45\fP of file \fBMeshBatch\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
