.TH "MiniGame.Balance" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MiniGame.Balance
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBlastCoin\fP"
.br
.ti -1c
.RI "int \fBchangeCoin\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB179\fP of file \fBMiniGame\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int MiniGame\&.Balance\&.changeCoin"

.PP
Definition at line \fB185\fP of file \fBMiniGame\&.cs\fP\&.
.SS "int MiniGame\&.Balance\&.lastCoin"

.PP
Definition at line \fB182\fP of file \fBMiniGame\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
