.TH "MiniGame_Blackjack" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MiniGame_Blackjack
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBModMinigame< Blackjack >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override bool \fBCanExit\fP ()"
.br
.ti -1c
.RI "override void \fBOnActivate\fP ()"
.br
.ti -1c
.RI "override void \fBOnDeactivate\fP ()"
.br
.in -1c

Public Member Functions inherited from \fBModMinigame< Blackjack >\fP
.in +1c
.ti -1c
.RI "void \fBLoad\fP ()"
.br
.ti -1c
.RI "void \fBKill\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Blackjack \fBprefab\fP"
.br
.in -1c

Public Attributes inherited from \fBModMinigame< Blackjack >\fP
.in +1c
.ti -1c
.RI "T \fBgame\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override string \fBid\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB6\fP of file \fBMiniGame_Blackjack\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override bool MiniGame_Blackjack\&.CanExit ()"

.PP
Definition at line \fB19\fP of file \fBMiniGame_Blackjack\&.cs\fP\&.
.SS "override void MiniGame_Blackjack\&.OnActivate ()"

.PP
Definition at line \fB25\fP of file \fBMiniGame_Blackjack\&.cs\fP\&.
.SS "override void MiniGame_Blackjack\&.OnDeactivate ()"

.PP
Definition at line \fB58\fP of file \fBMiniGame_Blackjack\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "Blackjack MiniGame_Blackjack\&.prefab"

.PP
Definition at line \fB69\fP of file \fBMiniGame_Blackjack\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "override string MiniGame_Blackjack\&.id\fR [get]\fP"

.PP
Definition at line \fB10\fP of file \fBMiniGame_Blackjack\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
