.TH "MiniGame" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MiniGame
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBModMinigame< T >\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBalance\fP"
.br
.in -1c
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBType\fP { \fBSlot\fP, \fBBlackjack\fP, \fBScratch\fP, \fBBasket\fP, \fBCoinDrop\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBOnActivate\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnDeactivate\fP ()"
.br
.ti -1c
.RI "void \fBDeactivate\fP ()"
.br
.ti -1c
.RI "void \fBSetAudioMixer\fP (GameObject go)"
.br
.ti -1c
.RI "void \fBSay\fP (string lang)"
.br
.ti -1c
.RI "virtual bool \fBCanExit\fP ()"
.br
.ti -1c
.RI "void \fBExit\fP ()"
.br
.ti -1c
.RI "bool \fBOnPlay\fP (int a)"
.br
.ti -1c
.RI "void \fBGetSlotReward\fP (string id, int pay=1, int bet=1)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBRegisterMiniGame\fP (string id, \fBMiniGame\fP g, string _path)"
.br
.ti -1c
.RI "static void \fBActivate\fP (MiniGame\&.Type type)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBMiniGame\&.Balance\fP \fBbalance\fP = new \fBMiniGame\&.Balance\fP()"
.br
.ti -1c
.RI "GameObject \fBgo\fP"
.br
.ti -1c
.RI "AssetBundle \fBasset\fP"
.br
.ti -1c
.RI "string \fBpath\fP"
.br
.ti -1c
.RI "bool \fBisActive\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static Dictionary< string, \fBMiniGame\fP > \fBminigames\fP = new Dictionary<string, \fBMiniGame\fP>()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "virtual string \fBid\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB7\fP of file \fBMiniGame\&.cs\fP\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "enum MiniGame\&.Type"

.PP
Definition at line \fB189\fP of file \fBMiniGame\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "static void MiniGame\&.Activate (MiniGame\&.Type type)\fR [static]\fP"

.PP
Definition at line \fB18\fP of file \fBMiniGame\&.cs\fP\&.
.SS "virtual bool MiniGame\&.CanExit ()\fR [virtual]\fP"

.PP
Definition at line \fB100\fP of file \fBMiniGame\&.cs\fP\&.
.SS "void MiniGame\&.Deactivate ()"

.PP
Definition at line \fB66\fP of file \fBMiniGame\&.cs\fP\&.
.SS "void MiniGame\&.Exit ()"

.PP
Definition at line \fB106\fP of file \fBMiniGame\&.cs\fP\&.
.SS "void MiniGame\&.GetSlotReward (string id, int pay = \fR1\fP, int bet = \fR1\fP)"

.PP
Definition at line \fB141\fP of file \fBMiniGame\&.cs\fP\&.
.SS "virtual void MiniGame\&.OnActivate ()\fR [virtual]\fP"

.PP
Definition at line \fB56\fP of file \fBMiniGame\&.cs\fP\&.
.SS "virtual void MiniGame\&.OnDeactivate ()\fR [virtual]\fP"

.PP
Definition at line \fB61\fP of file \fBMiniGame\&.cs\fP\&.
.SS "bool MiniGame\&.OnPlay (int a)"

.PP
Definition at line \fB117\fP of file \fBMiniGame\&.cs\fP\&.
.SS "static void MiniGame\&.RegisterMiniGame (string id, \fBMiniGame\fP g, string _path)\fR [static]\fP"

.PP
Definition at line \fB10\fP of file \fBMiniGame\&.cs\fP\&.
.SS "void MiniGame\&.Say (string lang)"

.PP
Definition at line \fB94\fP of file \fBMiniGame\&.cs\fP\&.
.SS "void MiniGame\&.SetAudioMixer (GameObject go)"

.PP
Definition at line \fB84\fP of file \fBMiniGame\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "AssetBundle MiniGame\&.asset"

.PP
Definition at line \fB170\fP of file \fBMiniGame\&.cs\fP\&.
.SS "\fBMiniGame\&.Balance\fP MiniGame\&.balance = new \fBMiniGame\&.Balance\fP()"

.PP
Definition at line \fB164\fP of file \fBMiniGame\&.cs\fP\&.
.SS "GameObject MiniGame\&.go"

.PP
Definition at line \fB167\fP of file \fBMiniGame\&.cs\fP\&.
.SS "bool MiniGame\&.isActive"

.PP
Definition at line \fB176\fP of file \fBMiniGame\&.cs\fP\&.
.SS "Dictionary<string, \fBMiniGame\fP> MiniGame\&.minigames = new Dictionary<string, \fBMiniGame\fP>()\fR [static]\fP"

.PP
Definition at line \fB161\fP of file \fBMiniGame\&.cs\fP\&.
.SS "string MiniGame\&.path"

.PP
Definition at line \fB173\fP of file \fBMiniGame\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "virtual string MiniGame\&.id\fR [get]\fP"

.PP
Definition at line \fB47\fP of file \fBMiniGame\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
