.TH "MiniGame_Basket" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MiniGame_Basket
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBModMinigame< Shooter >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnActivate\fP ()"
.br
.ti -1c
.RI "override void \fBOnDeactivate\fP ()"
.br
.in -1c

Public Member Functions inherited from \fBModMinigame< Shooter >\fP
.in +1c
.ti -1c
.RI "void \fBLoad\fP ()"
.br
.ti -1c
.RI "void \fBKill\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Shooter \fBprefab\fP"
.br
.in -1c

Public Attributes inherited from \fBModMinigame< Shooter >\fP
.in +1c
.ti -1c
.RI "T \fBgame\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override string \fBid\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB5\fP of file \fBMiniGame_Basket\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void MiniGame_Basket\&.OnActivate ()"

.PP
Definition at line \fB18\fP of file \fBMiniGame_Basket\&.cs\fP\&.
.SS "override void MiniGame_Basket\&.OnDeactivate ()"

.PP
Definition at line \fB50\fP of file \fBMiniGame_Basket\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "Shooter MiniGame_Basket\&.prefab"

.PP
Definition at line \fB57\fP of file \fBMiniGame_Basket\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "override string MiniGame_Basket\&.id\fR [get]\fP"

.PP
Definition at line \fB9\fP of file \fBMiniGame_Basket\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
