.TH "ModManager.SheetIndex" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ModManager.SheetIndex
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBdest\fP"
.br
.ti -1c
.RI "int \fBold\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB834\fP of file \fBModManager\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int ModManager\&.SheetIndex\&.dest"

.PP
Definition at line \fB837\fP of file \fBModManager\&.cs\fP\&.
.SS "int ModManager\&.SheetIndex\&.old"

.PP
Definition at line \fB840\fP of file \fBModManager\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
