.TH "ModMinigame< T >" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ModMinigame< T >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMiniGame\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBLoad\fP ()"
.br
.ti -1c
.RI "void \fBKill\fP ()"
.br
.in -1c

Public Member Functions inherited from \fBMiniGame\fP
.in +1c
.ti -1c
.RI "virtual void \fBOnActivate\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnDeactivate\fP ()"
.br
.ti -1c
.RI "void \fBDeactivate\fP ()"
.br
.ti -1c
.RI "void \fBSetAudioMixer\fP (GameObject go)"
.br
.ti -1c
.RI "void \fBSay\fP (string lang)"
.br
.ti -1c
.RI "virtual bool \fBCanExit\fP ()"
.br
.ti -1c
.RI "void \fBExit\fP ()"
.br
.ti -1c
.RI "bool \fBOnPlay\fP (int a)"
.br
.ti -1c
.RI "void \fBGetSlotReward\fP (string id, int pay=1, int bet=1)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "T \fBgame\fP"
.br
.in -1c

Public Attributes inherited from \fBMiniGame\fP
.in +1c
.ti -1c
.RI "\fBMiniGame\&.Balance\fP \fBbalance\fP = new \fBMiniGame\&.Balance\fP()"
.br
.ti -1c
.RI "GameObject \fBgo\fP"
.br
.ti -1c
.RI "AssetBundle \fBasset\fP"
.br
.ti -1c
.RI "string \fBpath\fP"
.br
.ti -1c
.RI "bool \fBisActive\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Public Types inherited from \fBMiniGame\fP
.in +1c
.ti -1c
.RI "enum \fBType\fP { \fBSlot\fP, \fBBlackjack\fP, \fBScratch\fP, \fBBasket\fP, \fBCoinDrop\fP }"
.br
.in -1c

Static Public Member Functions inherited from \fBMiniGame\fP
.in +1c
.ti -1c
.RI "static void \fBRegisterMiniGame\fP (string id, \fBMiniGame\fP g, string _path)"
.br
.ti -1c
.RI "static void \fBActivate\fP (MiniGame\&.Type type)"
.br
.in -1c

Static Public Attributes inherited from \fBMiniGame\fP
.in +1c
.ti -1c
.RI "static Dictionary< string, \fBMiniGame\fP > \fBminigames\fP = new Dictionary<string, \fBMiniGame\fP>()"
.br
.in -1c

Properties inherited from \fBMiniGame\fP
.in +1c
.ti -1c
.RI "virtual string \fBid\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBType Constraints\fP
.TP
\fIT\fP : \fIComponent\fP
.PP
Definition at line \fB5\fP of file \fBModMinigame\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void \fBModMinigame\fP< T >\&.Kill ()"

.PP
Definition at line \fB25\fP of file \fBModMinigame\&.cs\fP\&.
.SS "void \fBModMinigame\fP< T >\&.Load ()"

.PP
Definition at line \fB8\fP of file \fBModMinigame\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "T \fBModMinigame\fP< T >\&.game"

.PP
Definition at line \fB36\fP of file \fBModMinigame\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
