.TH "ModManager" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ModManager
.SH SYNOPSIS
.br
.PP
.PP
Inherits BaseModManager\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBSheetIndex\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "IniData \fBGetElinIni\fP ()"
.br
.ti -1c
.RI "override void \fBInit\fP (string path, string defaultPackage='_Elona')"
.br
.ti -1c
.RI "IEnumerator \fBRefreshMods\fP (Action onComplete, bool syncMods)"
.br
.ti -1c
.RI "void \fBSaveLoadOrder\fP ()"
.br
.ti -1c
.RI "void \fBLoadLoadOrder\fP ()"
.br
.ti -1c
.RI "\fBModPackage\fP \fBAddPackage\fP (DirectoryInfo dir, bool isInPackages=false)"
.br
.ti -1c
.RI "\fBModPackage\fP \fBAddWorkshopPackage\fP (WorkshopItem item, bool isInPackages=false)"
.br
.ti -1c
.RI "override void \fBParseExtra\fP (DirectoryInfo dir, BaseModPackage package)"
.br
.ti -1c
.RI "void \fBUpdateDialogs\fP (DirectoryInfo dir, string dirTemp)"
.br
.ti -1c
.RI "void \fBUpdateTalks\fP (DirectoryInfo dir, string dirTemp)"
.br
.ti -1c
.RI "void \fBUpdateExcelBook\fP (FileInfo f, string dirTemp, bool updateOnlyText)"
.br
.ti -1c
.RI "int \fBUpdateExcelSheet\fP (ISheet destSheet, ISheet oldSheet, bool updateOnlytext)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "List< FileInfo > \fBreplaceFiles\fP = new List<FileInfo>()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static readonly string \fBPasswordChar\fP = '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ'"
.br
.ti -1c
.RI "static List< object > \fBListPluginObject\fP = new List<object>()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "static List< string > \fBListChainLoad\fP\fR [get]\fP"
.br
.ti -1c
.RI "static DirectoryInfo \fBDirWorkshop\fP\fR [get]\fP"
.br
.ti -1c
.RI "static bool \fBIsInitialized\fP\fR [get]\fP"
.br
.ti -1c
.RI "static string \fBPathIni\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB19\fP of file \fBModManager\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBModPackage\fP ModManager\&.AddPackage (DirectoryInfo dir, bool isInPackages = \fRfalse\fP)"

.PP
Definition at line \fB339\fP of file \fBModManager\&.cs\fP\&.
.SS "\fBModPackage\fP ModManager\&.AddWorkshopPackage (WorkshopItem item, bool isInPackages = \fRfalse\fP)"

.PP
Definition at line \fB354\fP of file \fBModManager\&.cs\fP\&.
.SS "IniData ModManager\&.GetElinIni ()"

.PP
Definition at line \fB62\fP of file \fBModManager\&.cs\fP\&.
.SS "override void ModManager\&.Init (string path, string defaultPackage = \fR'_Elona'\fP)"

.PP
Definition at line \fB84\fP of file \fBModManager\&.cs\fP\&.
.SS "void ModManager\&.LoadLoadOrder ()"

.PP
Definition at line \fB308\fP of file \fBModManager\&.cs\fP\&.
.SS "override void ModManager\&.ParseExtra (DirectoryInfo dir, BaseModPackage package)"

.PP
Definition at line \fB376\fP of file \fBModManager\&.cs\fP\&.
.SS "IEnumerator ModManager\&.RefreshMods (Action onComplete, bool syncMods)"

.PP
Definition at line \fB133\fP of file \fBModManager\&.cs\fP\&.
.SS "void ModManager\&.SaveLoadOrder ()"

.PP
Definition at line \fB293\fP of file \fBModManager\&.cs\fP\&.
.SS "void ModManager\&.UpdateDialogs (DirectoryInfo dir, string dirTemp)"

.PP
Definition at line \fB540\fP of file \fBModManager\&.cs\fP\&.
.SS "void ModManager\&.UpdateExcelBook (FileInfo f, string dirTemp, bool updateOnlyText)"

.PP
Definition at line \fB568\fP of file \fBModManager\&.cs\fP\&.
.SS "int ModManager\&.UpdateExcelSheet (ISheet destSheet, ISheet oldSheet, bool updateOnlytext)"

.PP
Definition at line \fB620\fP of file \fBModManager\&.cs\fP\&.
.SS "void ModManager\&.UpdateTalks (DirectoryInfo dir, string dirTemp)"

.PP
Definition at line \fB556\fP of file \fBModManager\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "List<object> ModManager\&.ListPluginObject = new List<object>()\fR [static]\fP"

.PP
Definition at line \fB828\fP of file \fBModManager\&.cs\fP\&.
.SS "readonly string ModManager\&.PasswordChar = '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ'\fR [static]\fP"

.PP
Definition at line \fB825\fP of file \fBModManager\&.cs\fP\&.
.SS "List<FileInfo> ModManager\&.replaceFiles = new List<FileInfo>()"

.PP
Definition at line \fB831\fP of file \fBModManager\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "DirectoryInfo ModManager\&.DirWorkshop\fR [static]\fP, \fR [get]\fP"

.PP
Definition at line \fB33\fP of file \fBModManager\&.cs\fP\&.
.SS "bool ModManager\&.IsInitialized\fR [static]\fP, \fR [get]\fP"

.PP
Definition at line \fB43\fP of file \fBModManager\&.cs\fP\&.
.SS "List<string> ModManager\&.ListChainLoad\fR [static]\fP, \fR [get]\fP"

.PP
Definition at line \fB23\fP of file \fBModManager\&.cs\fP\&.
.SS "string ModManager\&.PathIni\fR [static]\fP, \fR [get]\fP"

.PP
Definition at line \fB53\fP of file \fBModManager\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
