.TH "ModPackage" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ModPackage
.SH SYNOPSIS
.br
.PP
.PP
Inherits BaseModPackage\&.
.SH "Detailed Description"
.PP 
Definition at line \fB4\fP of file \fBModPackage\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
