.TH "MultiSprite" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MultiSprite
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Sprite[] \fBframes\fP"
.br
.ti -1c
.RI "float \fBinterval\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB6\fP of file \fBMultiSprite\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "Sprite [] MultiSprite\&.frames"

.PP
Definition at line \fB9\fP of file \fBMultiSprite\&.cs\fP\&.
.SS "float MultiSprite\&.interval"

.PP
Definition at line \fB12\fP of file \fBMultiSprite\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
