.TH "Net" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Net
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBChatLog\fP"
.br
.ti -1c
.RI "class \fBDownloadCahce\fP"
.br
.ti -1c
.RI "class \fBDownloadMeta\fP"
.br
.ti -1c
.RI "class \fBVoteLog\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBShowVote\fP (string logs)"
.br
.ti -1c
.RI "void \fBShowChat\fP (string logs)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static UniTask< bool > \fBUploadFile\fP (string id, string password, string name, string title, string path, string idLang)"
.br
.ti -1c
.RI "static UniTask< FileInfo > \fBDownloadFile\fP (\fBNet\&.DownloadMeta\fP item, string path, string idLang)"
.br
.ti -1c
.RI "static UniTask< List< \fBNet\&.DownloadMeta\fP > > \fBGetFileList\fP (string idLang)"
.br
.ti -1c
.RI "static UniTask< bool > \fBSendVote\fP (int id, string idLang)"
.br
.ti -1c
.RI "static UniTask< List< \fBNet\&.VoteLog\fP > > \fBGetVote\fP (string idLang)"
.br
.ti -1c
.RI "static UniTask< bool > \fBSendChat\fP (string name, string msg, ChatCategory cat, string idLang)"
.br
.ti -1c
.RI "static UniTask< List< \fBNet\&.ChatLog\fP > > \fBGetChat\fP (ChatCategory cat, string idLang)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "List< \fBNet\&.ChatLog\fP > \fBchatList\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static bool \fBisUploading\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "static bool \fBShowNetError\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB11\fP of file \fBNet\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "static UniTask< FileInfo > Net\&.DownloadFile (\fBNet\&.DownloadMeta\fP item, string path, string idLang)\fR [static]\fP"

.PP
Definition at line \fB60\fP of file \fBNet\&.cs\fP\&.
.SS "static UniTask< List< \fBNet\&.ChatLog\fP > > Net\&.GetChat (ChatCategory cat, string idLang)\fR [static]\fP"

.PP
Definition at line \fB121\fP of file \fBNet\&.cs\fP\&.
.SS "static UniTask< List< \fBNet\&.DownloadMeta\fP > > Net\&.GetFileList (string idLang)\fR [static]\fP"

.PP
Definition at line \fB73\fP of file \fBNet\&.cs\fP\&.
.SS "static UniTask< List< \fBNet\&.VoteLog\fP > > Net\&.GetVote (string idLang)\fR [static]\fP"

.PP
Definition at line \fB96\fP of file \fBNet\&.cs\fP\&.
.SS "static UniTask< bool > Net\&.SendChat (string name, string msg, ChatCategory cat, string idLang)\fR [static]\fP"

.PP
Definition at line \fB107\fP of file \fBNet\&.cs\fP\&.
.SS "static UniTask< bool > Net\&.SendVote (int id, string idLang)\fR [static]\fP"

.PP
Definition at line \fB84\fP of file \fBNet\&.cs\fP\&.
.SS "void Net\&.ShowChat (string logs)"

.PP
Definition at line \fB34\fP of file \fBNet\&.cs\fP\&.
.SS "void Net\&.ShowVote (string logs)"

.PP
Definition at line \fB24\fP of file \fBNet\&.cs\fP\&.
.SS "static UniTask< bool > Net\&.UploadFile (string id, string password, string name, string title, string path, string idLang)\fR [static]\fP"

.PP
Definition at line \fB44\fP of file \fBNet\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "List<\fBNet\&.ChatLog\fP> Net\&.chatList"

.PP
Definition at line \fB132\fP of file \fBNet\&.cs\fP\&.
.SS "bool Net\&.isUploading\fR [static]\fP"

.PP
Definition at line \fB147\fP of file \fBNet\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "bool Net\&.ShowNetError\fR [static]\fP, \fR [get]\fP"

.PP
Definition at line \fB15\fP of file \fBNet\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
