.TH "Net.DownloadMeta" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Net.DownloadMeta
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBIsValidVersion\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBname\fP"
.br
.ti -1c
.RI "string \fBtitle\fP"
.br
.ti -1c
.RI "string \fBid\fP"
.br
.ti -1c
.RI "string \fBpath\fP"
.br
.ti -1c
.RI "string \fBdate\fP"
.br
.ti -1c
.RI "int \fBversion\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB176\fP of file \fBNet\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "bool Net\&.DownloadMeta\&.IsValidVersion ()"

.PP
Definition at line \fB179\fP of file \fBNet\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "string Net\&.DownloadMeta\&.date"

.PP
Definition at line \fB197\fP of file \fBNet\&.cs\fP\&.
.SS "string Net\&.DownloadMeta\&.id"

.PP
Definition at line \fB191\fP of file \fBNet\&.cs\fP\&.
.SS "string Net\&.DownloadMeta\&.name"

.PP
Definition at line \fB185\fP of file \fBNet\&.cs\fP\&.
.SS "string Net\&.DownloadMeta\&.path"

.PP
Definition at line \fB194\fP of file \fBNet\&.cs\fP\&.
.SS "string Net\&.DownloadMeta\&.title"

.PP
Definition at line \fB188\fP of file \fBNet\&.cs\fP\&.
.SS "int Net\&.DownloadMeta\&.version"

.PP
Definition at line \fB200\fP of file \fBNet\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
