.TH "Net.VoteLog" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Net.VoteLog
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBname\fP"
.br
.ti -1c
.RI "int \fBcount\fP"
.br
.ti -1c
.RI "int \fBindex\fP"
.br
.ti -1c
.RI "int \fBtime\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB160\fP of file \fBNet\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int Net\&.VoteLog\&.count"

.PP
Definition at line \fB166\fP of file \fBNet\&.cs\fP\&.
.SS "int Net\&.VoteLog\&.index"

.PP
Definition at line \fB169\fP of file \fBNet\&.cs\fP\&.
.SS "string Net\&.VoteLog\&.name"

.PP
Definition at line \fB163\fP of file \fBNet\&.cs\fP\&.
.SS "int Net\&.VoteLog\&.time"

.PP
Definition at line \fB172\fP of file \fBNet\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
