.TH "Net.DownloadCahce" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Net.DownloadCahce
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Dictionary< string, string > \fBitems\fP = new Dictionary<string, string>()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB204\fP of file \fBNet\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "Dictionary<string, string> Net\&.DownloadCahce\&.items = new Dictionary<string, string>()"

.PP
Definition at line \fB207\fP of file \fBNet\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
