.TH "NoticeManager" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NoticeManager
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBNotice\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBRefresh\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "List< \fBNoticeManager\&.Notice\fP > \fBlist\fP = new List<\fBNoticeManager\&.Notice\fP>()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB5\fP of file \fBNoticeManager\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void NoticeManager\&.Refresh ()"

.PP
Definition at line \fB8\fP of file \fBNoticeManager\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "List<\fBNoticeManager\&.Notice\fP> NoticeManager\&.list = new List<\fBNoticeManager\&.Notice\fP>()"

.PP
Definition at line \fB21\fP of file \fBNoticeManager\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
