.TH "PathProgress" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PathProgress
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBState\fP { \fBIdle\fP, \fBSearching\fP, \fBPathReady\fP, \fBFail\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBIsDestinationReached\fP (\fBPoint\fP pos)"
.br
.ti -1c
.RI "void \fBRequestPath\fP (\fBPoint\fP _startPoint, \fBPoint\fP _destPoint, int _destDist, bool _ignoreConnection, int _searchLimit=\-1)"
.br
.ti -1c
.RI "void \fBRequestPathImmediate\fP (\fBPoint\fP _startPoint, \fBPoint\fP _destPoint, int _destDist, bool _ignoreConnection, int _searchLimit=\-1)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBIPathfindWalker\fP \fBwalker\fP"
.br
.ti -1c
.RI "List< \fBPathFinderNode\fP > \fBnodes\fP = new List<\fBPathFinderNode\fP>()"
.br
.ti -1c
.RI "\fBPoint\fP \fBstartPoint\fP = new \fBPoint\fP()"
.br
.ti -1c
.RI "\fBPoint\fP \fBdestPoint\fP = new \fBPoint\fP()"
.br
.ti -1c
.RI "int \fBnodeIndex\fP"
.br
.ti -1c
.RI "PathProgress\&.State \fBstate\fP"
.br
.ti -1c
.RI "int \fBdestDist\fP"
.br
.ti -1c
.RI "int \fBsearchLimit\fP"
.br
.ti -1c
.RI "bool \fBignoreConnection\fP"
.br
.ti -1c
.RI "PathManager\&.MoveType \fBmoveType\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "bool \fBHasPath\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB6\fP of file \fBPathProgress\&.cs\fP\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "enum PathProgress\&.State"

.PP
Definition at line \fB91\fP of file \fBPathProgress\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "bool PathProgress\&.IsDestinationReached (\fBPoint\fP pos)"

.PP
Definition at line \fB19\fP of file \fBPathProgress\&.cs\fP\&.
.SS "void PathProgress\&.RequestPath (\fBPoint\fP _startPoint, \fBPoint\fP _destPoint, int _destDist, bool _ignoreConnection, int _searchLimit = \fR\-1\fP)"

.PP
Definition at line \fB25\fP of file \fBPathProgress\&.cs\fP\&.
.SS "void PathProgress\&.RequestPathImmediate (\fBPoint\fP _startPoint, \fBPoint\fP _destPoint, int _destDist, bool _ignoreConnection, int _searchLimit = \fR\-1\fP)"

.PP
Definition at line \fB43\fP of file \fBPathProgress\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int PathProgress\&.destDist"

.PP
Definition at line \fB79\fP of file \fBPathProgress\&.cs\fP\&.
.SS "\fBPoint\fP PathProgress\&.destPoint = new \fBPoint\fP()"

.PP
Definition at line \fB70\fP of file \fBPathProgress\&.cs\fP\&.
.SS "bool PathProgress\&.ignoreConnection"

.PP
Definition at line \fB85\fP of file \fBPathProgress\&.cs\fP\&.
.SS "PathManager\&.MoveType PathProgress\&.moveType"

.PP
Definition at line \fB88\fP of file \fBPathProgress\&.cs\fP\&.
.SS "int PathProgress\&.nodeIndex"

.PP
Definition at line \fB73\fP of file \fBPathProgress\&.cs\fP\&.
.SS "List<\fBPathFinderNode\fP> PathProgress\&.nodes = new List<\fBPathFinderNode\fP>()"

.PP
Definition at line \fB64\fP of file \fBPathProgress\&.cs\fP\&.
.SS "int PathProgress\&.searchLimit"

.PP
Definition at line \fB82\fP of file \fBPathProgress\&.cs\fP\&.
.SS "\fBPoint\fP PathProgress\&.startPoint = new \fBPoint\fP()"

.PP
Definition at line \fB67\fP of file \fBPathProgress\&.cs\fP\&.
.SS "PathProgress\&.State PathProgress\&.state"

.PP
Definition at line \fB76\fP of file \fBPathProgress\&.cs\fP\&.
.SS "\fBIPathfindWalker\fP PathProgress\&.walker"

.PP
Definition at line \fB61\fP of file \fBPathProgress\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "bool PathProgress\&.HasPath\fR [get]\fP"

.PP
Definition at line \fB10\fP of file \fBPathProgress\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
