.TH "PathManager" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PathManager
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBMoveType\fP { \fBDefault\fP, \fBCombat\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBRequestPath\fP (\fBPathProgress\fP progress)"
.br
.ti -1c
.RI "void \fBRequestPathImmediate\fP (\fBPathProgress\fP progress)"
.br
.ti -1c
.RI "bool \fBIsPathClear\fP (\fBPoint\fP origin, \fBPoint\fP dest, \fBIPathfindWalker\fP walker, int radius)"
.br
.ti -1c
.RI "\fBPathProgress\fP \fBRequestPathImmediate\fP (\fBPoint\fP origin, \fBPoint\fP dest, \fBIPathfindWalker\fP walker, PathManager\&.MoveType moveType=PathManager\&.MoveType\&.Default, int searchLimit=\-1, int destDist=0)"
.br
.ti -1c
.RI "\fBPoint\fP \fBGetFirstStep\fP (\fBPoint\fP origin, \fBPoint\fP _dest, \fBIPathfindWalker\fP walker, int maxDist=20, PathManager\&.MoveType moveType=PathManager\&.MoveType\&.Default)"
.br
.ti -1c
.RI "\fBPoint\fP \fB_GetFirstStep\fP (\fBPoint\fP origin, \fBPoint\fP dest, \fBIPathfindWalker\fP walker, int maxDist=20, PathManager\&.MoveType moveType=PathManager\&.MoveType\&.Default)"
.br
.ti -1c
.RI "void \fBOnGridModified\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBPathFinder\fP \fB_pathfinder\fP"
.br
.ti -1c
.RI "int \fBsearchLimit\fP = 1000000"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static int \fBrequestCount\fP"
.br
.ti -1c
.RI "static \fBPathManager\fP \fBInstance\fP"
.br
.ti -1c
.RI "static \fBPathProgress\fP \fBtempProgress\fP = new \fBPathProgress\fP()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBIPathfinder\fP \fBpathfinder\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB8\fP of file \fBPathManager\&.cs\fP\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "enum PathManager\&.MoveType"

.PP
Definition at line \fB131\fP of file \fBPathManager\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBPoint\fP PathManager\&._GetFirstStep (\fBPoint\fP origin, \fBPoint\fP dest, \fBIPathfindWalker\fP walker, int maxDist = \fR20\fP, PathManager\&.MoveType moveType = \fRPathManager::MoveType::Default\fP)"

.PP
Definition at line \fB75\fP of file \fBPathManager\&.cs\fP\&.
.SS "\fBPoint\fP PathManager\&.GetFirstStep (\fBPoint\fP origin, \fBPoint\fP _dest, \fBIPathfindWalker\fP walker, int maxDist = \fR20\fP, PathManager\&.MoveType moveType = \fRPathManager::MoveType::Default\fP)"

.PP
Definition at line \fB63\fP of file \fBPathManager\&.cs\fP\&.
.SS "bool PathManager\&.IsPathClear (\fBPoint\fP origin, \fBPoint\fP dest, \fBIPathfindWalker\fP walker, int radius)"

.PP
Definition at line \fB45\fP of file \fBPathManager\&.cs\fP\&.
.SS "void PathManager\&.OnGridModified ()"

.PP
Definition at line \fB111\fP of file \fBPathManager\&.cs\fP\&.
.SS "void PathManager\&.RequestPath (\fBPathProgress\fP progress)"

.PP
Definition at line \fB27\fP of file \fBPathManager\&.cs\fP\&.
.SS "void PathManager\&.RequestPathImmediate (\fBPathProgress\fP progress)"

.PP
Definition at line \fB38\fP of file \fBPathManager\&.cs\fP\&.
.SS "\fBPathProgress\fP PathManager\&.RequestPathImmediate (\fBPoint\fP origin, \fBPoint\fP dest, \fBIPathfindWalker\fP walker, PathManager\&.MoveType moveType = \fRPathManager::MoveType::Default\fP, int searchLimit = \fR\-1\fP, int destDist = \fR0\fP)"

.PP
Definition at line \fB54\fP of file \fBPathManager\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBPathFinder\fP PathManager\&._pathfinder"

.PP
Definition at line \fB125\fP of file \fBPathManager\&.cs\fP\&.
.SS "\fBPathManager\fP PathManager\&.Instance\fR [static]\fP"

.PP
Definition at line \fB119\fP of file \fBPathManager\&.cs\fP\&.
.SS "int PathManager\&.requestCount\fR [static]\fP"

.PP
Definition at line \fB116\fP of file \fBPathManager\&.cs\fP\&.
.SS "int PathManager\&.searchLimit = 1000000"

.PP
Definition at line \fB128\fP of file \fBPathManager\&.cs\fP\&.
.SS "\fBPathProgress\fP PathManager\&.tempProgress = new \fBPathProgress\fP()\fR [static]\fP"

.PP
Definition at line \fB122\fP of file \fBPathManager\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "\fBIPathfinder\fP PathManager\&.pathfinder\fR [get]\fP"

.PP
Definition at line \fB12\fP of file \fBPathManager\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
