.TH "Person" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Person
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBEClass\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPerson\fP (string _id, \fBChara\fP c=null)"
.br
.ti -1c
.RI "\fBPerson\fP (\fBReligion\fP r)"
.br
.ti -1c
.RI "\fBPerson\fP (\fBChara\fP c)"
.br
.ti -1c
.RI "void \fBSetChara\fP (\fBChara\fP c)"
.br
.ti -1c
.RI "string \fBApplyTone\fP (string text)"
.br
.ti -1c
.RI "string \fBGetDramaTitle\fP ()"
.br
.ti -1c
.RI "void \fBSetImage\fP (Image image)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBname\fP"
.br
.ti -1c
.RI "string \fBidPortrait\fP"
.br
.ti -1c
.RI "string \fBid\fP"
.br
.ti -1c
.RI "string \fBtones\fP"
.br
.ti -1c
.RI "int \fBuidChara\fP"
.br
.ti -1c
.RI "int \fBgender\fP"
.br
.ti -1c
.RI "SerializableColor \fBcolorHair\fP"
.br
.ti -1c
.RI "\fBRefChara\fP \fBrefChara\fP = new \fBRefChara\fP()"
.br
.ti -1c
.RI "\fBChara\fP \fB_tempChara\fP"
.br
.ti -1c
.RI "string \fBtempName\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBSourcePerson\&.Row\fP \fBsource\fP\fR [get]\fP"
.br
.ti -1c
.RI "\fBChara\fP \fBchara\fP\fR [get]\fP"
.br
.ti -1c
.RI "bool \fBhasChara\fP\fR [get]\fP"
.br
.ti -1c
.RI "bool \fBHumanSpeak\fP\fR [get]\fP"
.br
.ti -1c
.RI "string \fBName\fP\fR [get]\fP"
.br
.ti -1c
.RI "string \fBNameBraced\fP\fR [get]\fP"
.br
.ti -1c
.RI "string \fBAka\fP\fR [get]\fP"
.br
.in -1c

Properties inherited from \fBEClass\fP
.in +1c
.ti -1c
.RI "static \fBGame\fP \fBgame\fP\fR [get]\fP"
.br
.ti -1c
.RI "static bool \fBAdvMode\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBPlayer\fP \fBplayer\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBChara\fP \fBpc\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBUI\fP \fBui\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBMap\fP \fB_map\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBZone\fP \fB_zone\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranchOrHomeBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFaction\fP \fBHome\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFaction\fP \fBWilds\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBScene\fP \fBscene\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBBaseGameScreen\fP \fBscreen\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameSetting\fP \fBsetting\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameData\fP \fBgamedata\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBColorProfile\fP \fBColors\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBWorld\fP \fBworld\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBsources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBeditorSources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static SoundManager \fBSound\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBCoreDebug\fP \fBdebug\fP\fR [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Static Public Member Functions inherited from \fBEClass\fP
.in +1c
.ti -1c
.RI "static int \fBrnd\fP (int a)"
.br
.ti -1c
.RI "static int \fBcurve\fP (int a, int start, int step, int rate=75)"
.br
.ti -1c
.RI "static int \fBrndHalf\fP (int a)"
.br
.ti -1c
.RI "static float \fBrndf\fP (float a)"
.br
.ti -1c
.RI "static int \fBrndSqrt\fP (int a)"
.br
.ti -1c
.RI "static void \fBWait\fP (float a, \fBCard\fP c)"
.br
.ti -1c
.RI "static void \fBWait\fP (float a, \fBPoint\fP p)"
.br
.ti -1c
.RI "static int \fBBigger\fP (int a, int b)"
.br
.ti -1c
.RI "static int \fBSmaller\fP (int a, int b)"
.br
.in -1c

Static Public Attributes inherited from \fBEClass\fP
.in +1c
.ti -1c
.RI "static \fBCore\fP \fBcore\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB7\fP of file \fBPerson\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Person\&.Person ()"

.PP
Definition at line \fB105\fP of file \fBPerson\&.cs\fP\&.
.SS "Person\&.Person (string _id, \fBChara\fP c = \fRnull\fP)"

.PP
Definition at line \fB110\fP of file \fBPerson\&.cs\fP\&.
.SS "Person\&.Person (\fBReligion\fP r)"

.PP
Definition at line \fB117\fP of file \fBPerson\&.cs\fP\&.
.SS "Person\&.Person (\fBChara\fP c)"

.PP
Definition at line \fB129\fP of file \fBPerson\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "string Person\&.ApplyTone (string text)"

.PP
Definition at line \fB150\fP of file \fBPerson\&.cs\fP\&.
.SS "string Person\&.GetDramaTitle ()"

.PP
Definition at line \fB157\fP of file \fBPerson\&.cs\fP\&.
.SS "void Person\&.SetChara (\fBChara\fP c)"

.PP
Definition at line \fB135\fP of file \fBPerson\&.cs\fP\&.
.SS "void Person\&.SetImage (Image image)"

.PP
Definition at line \fB203\fP of file \fBPerson\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBChara\fP Person\&._tempChara"

.PP
Definition at line \fB251\fP of file \fBPerson\&.cs\fP\&.
.SS "SerializableColor Person\&.colorHair"

.PP
Definition at line \fB245\fP of file \fBPerson\&.cs\fP\&.
.SS "int Person\&.gender"

.PP
Definition at line \fB241\fP of file \fBPerson\&.cs\fP\&.
.SS "string Person\&.id"

.PP
Definition at line \fB229\fP of file \fBPerson\&.cs\fP\&.
.SS "string Person\&.idPortrait"

.PP
Definition at line \fB225\fP of file \fBPerson\&.cs\fP\&.
.SS "string Person\&.name"

.PP
Definition at line \fB221\fP of file \fBPerson\&.cs\fP\&.
.SS "\fBRefChara\fP Person\&.refChara = new \fBRefChara\fP()"

.PP
Definition at line \fB248\fP of file \fBPerson\&.cs\fP\&.
.SS "string Person\&.tempName"

.PP
Definition at line \fB254\fP of file \fBPerson\&.cs\fP\&.
.SS "string Person\&.tones"

.PP
Definition at line \fB233\fP of file \fBPerson\&.cs\fP\&.
.SS "int Person\&.uidChara"

.PP
Definition at line \fB237\fP of file \fBPerson\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "string Person\&.Aka\fR [get]\fP"

.PP
Definition at line \fB89\fP of file \fBPerson\&.cs\fP\&.
.SS "\fBChara\fP Person\&.chara\fR [get]\fP"

.PP
Definition at line \fB21\fP of file \fBPerson\&.cs\fP\&.
.SS "bool Person\&.hasChara\fR [get]\fP"

.PP
Definition at line \fB31\fP of file \fBPerson\&.cs\fP\&.
.SS "bool Person\&.HumanSpeak\fR [get]\fP"

.PP
Definition at line \fB41\fP of file \fBPerson\&.cs\fP\&.
.SS "string Person\&.Name\fR [get]\fP"

.PP
Definition at line \fB51\fP of file \fBPerson\&.cs\fP\&.
.SS "string Person\&.NameBraced\fR [get]\fP"

.PP
Definition at line \fB70\fP of file \fBPerson\&.cs\fP\&.
.SS "\fBSourcePerson\&.Row\fP Person\&.source\fR [get]\fP"

.PP
Definition at line \fB11\fP of file \fBPerson\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
