.TH "Player.Flags" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Player.Flags
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBEClass\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBOnCreateGame\fP ()"
.br
.ti -1c
.RI "void \fBOnEnableDebug\fP ()"
.br
.ti -1c
.RI "void \fBOnBuild\fP (\fBRecipe\fP r)"
.br
.ti -1c
.RI "bool \fBIsStoryPlayed\fP (int flag)"
.br
.ti -1c
.RI "int \fBGetStoryRowID\fP (string idBook, string idStep)"
.br
.ti -1c
.RI "Dictionary< string, string > \fBGetStoryRow\fP (string idBook, int id)"
.br
.ti -1c
.RI "ExcelData \fBGetStoryExcelData\fP (string idBook)"
.br
.ti -1c
.RI "bool \fBPlayStory\fP (string idBook, int id, bool fromBook=false)"
.br
.ti -1c
.RI "bool \fBPlayStory\fP (int id, bool fromBook=false)"
.br
.ti -1c
.RI "void \fBAddStory\fP (int id)"
.br
.ti -1c
.RI "void \fBOnEnterZone\fP ()"
.br
.ti -1c
.RI "void \fBOnLeaveZone\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int[] \fBints\fP = new int[50]"
.br
.ti -1c
.RI "List< int > \fBplayedStories\fP = new List<int>()"
.br
.ti -1c
.RI "List< int > \fBavailableStories\fP = new List<int>()"
.br
.ti -1c
.RI "HashSet< int > \fBpleaseDontTouch\fP = new HashSet<int>()"
.br
.ti -1c
.RI "List< string > \fBreservedTutorial\fP = new List<string>()"
.br
.ti -1c
.RI "BitArray32 \fBbits\fP"
.br
.ti -1c
.RI "Dictionary< string, ExcelData > \fBstoryExcel\fP = new Dictionary<string, ExcelData>()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "const int \fBMonoDeparture\fP = 100"
.br
.in -1c

Static Public Attributes inherited from \fBEClass\fP
.in +1c
.ti -1c
.RI "static \fBCore\fP \fBcore\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "bool \fBgotClickReward\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "bool \fBwelcome\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "bool \fBfiamaStoryBookGiven\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "bool \fBfiamaFirstDream\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "bool \fBhelpHighlightDisabled\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "bool \fBpickedMelilithTreasure\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "bool \fBisShoesOff\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "bool \fBbackpackHighlightDisabled\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "bool \fBabilityHighlightDisabled\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "bool \fBelinGift\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "bool \fBgotMelilithCurse\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "bool \fBcanComupWithFoodRecipe\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "bool \fBKilledBossInVoid\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "bool \fBstatueShipped\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "bool \fBlittle_saved\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "bool \fBlittle_killed\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "bool \fBgotEtherDisease\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "bool \fBloytelEscaped\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "bool \fBmagicChestSent\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "int \fBstart\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "int \fBbuild\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "int \fBmain\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "int \fBstoryFiama\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "int \fBlutz\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "int \fBdaysAfterQuestExploration\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "int \fBlandDeedBought\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "int \fBloytelMartLv\fP\fR [get, set]\fP"
.br
.in -1c

Properties inherited from \fBEClass\fP
.in +1c
.ti -1c
.RI "static \fBGame\fP \fBgame\fP\fR [get]\fP"
.br
.ti -1c
.RI "static bool \fBAdvMode\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBPlayer\fP \fBplayer\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBChara\fP \fBpc\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBUI\fP \fBui\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBMap\fP \fB_map\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBZone\fP \fB_zone\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranchOrHomeBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFaction\fP \fBHome\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFaction\fP \fBWilds\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBScene\fP \fBscene\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBBaseGameScreen\fP \fBscreen\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameSetting\fP \fBsetting\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameData\fP \fBgamedata\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBColorProfile\fP \fBColors\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBWorld\fP \fBworld\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBsources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBeditorSources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static SoundManager \fBSound\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBCoreDebug\fP \fBdebug\fP\fR [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Static Public Member Functions inherited from \fBEClass\fP
.in +1c
.ti -1c
.RI "static int \fBrnd\fP (int a)"
.br
.ti -1c
.RI "static int \fBcurve\fP (int a, int start, int step, int rate=75)"
.br
.ti -1c
.RI "static int \fBrndHalf\fP (int a)"
.br
.ti -1c
.RI "static float \fBrndf\fP (float a)"
.br
.ti -1c
.RI "static int \fBrndSqrt\fP (int a)"
.br
.ti -1c
.RI "static void \fBWait\fP (float a, \fBCard\fP c)"
.br
.ti -1c
.RI "static void \fBWait\fP (float a, \fBPoint\fP p)"
.br
.ti -1c
.RI "static int \fBBigger\fP (int a, int b)"
.br
.ti -1c
.RI "static int \fBSmaller\fP (int a, int b)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB1994\fP of file \fBPlayer\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Player\&.Flags\&.AddStory (int id)"

.PP
Definition at line \fB2504\fP of file \fBPlayer\&.cs\fP\&.
.SS "ExcelData Player\&.Flags\&.GetStoryExcelData (string idBook)"

.PP
Definition at line \fB2467\fP of file \fBPlayer\&.cs\fP\&.
.SS "Dictionary< string, string > Player\&.Flags\&.GetStoryRow (string idBook, int id)"

.PP
Definition at line \fB2454\fP of file \fBPlayer\&.cs\fP\&.
.SS "int Player\&.Flags\&.GetStoryRowID (string idBook, string idStep)"

.PP
Definition at line \fB2441\fP of file \fBPlayer\&.cs\fP\&.
.SS "bool Player\&.Flags\&.IsStoryPlayed (int flag)"

.PP
Definition at line \fB2435\fP of file \fBPlayer\&.cs\fP\&.
.SS "void Player\&.Flags\&.OnBuild (\fBRecipe\fP r)"

.PP
Definition at line \fB2426\fP of file \fBPlayer\&.cs\fP\&.
.SS "void Player\&.Flags\&.OnCreateGame ()"

.PP
Definition at line \fB2416\fP of file \fBPlayer\&.cs\fP\&.
.SS "void Player\&.Flags\&.OnEnableDebug ()"

.PP
Definition at line \fB2421\fP of file \fBPlayer\&.cs\fP\&.
.SS "void Player\&.Flags\&.OnEnterZone ()"

.PP
Definition at line \fB2515\fP of file \fBPlayer\&.cs\fP\&.
.SS "void Player\&.Flags\&.OnLeaveZone ()"

.PP
Definition at line \fB2544\fP of file \fBPlayer\&.cs\fP\&.
.SS "bool Player\&.Flags\&.PlayStory (int id, bool fromBook = \fRfalse\fP)"

.PP
Definition at line \fB2498\fP of file \fBPlayer\&.cs\fP\&.
.SS "bool Player\&.Flags\&.PlayStory (string idBook, int id, bool fromBook = \fRfalse\fP)"

.PP
Definition at line \fB2481\fP of file \fBPlayer\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "List<int> Player\&.Flags\&.availableStories = new List<int>()"

.PP
Definition at line \fB2565\fP of file \fBPlayer\&.cs\fP\&.
.SS "BitArray32 Player\&.Flags\&.bits"

.PP
Definition at line \fB2576\fP of file \fBPlayer\&.cs\fP\&.
.SS "int [] Player\&.Flags\&.ints = new int[50]"

.PP
Definition at line \fB2557\fP of file \fBPlayer\&.cs\fP\&.
.SS "const int Player\&.Flags\&.MonoDeparture = 100\fR [static]\fP"

.PP
Definition at line \fB2553\fP of file \fBPlayer\&.cs\fP\&.
.SS "List<int> Player\&.Flags\&.playedStories = new List<int>()"

.PP
Definition at line \fB2561\fP of file \fBPlayer\&.cs\fP\&.
.SS "HashSet<int> Player\&.Flags\&.pleaseDontTouch = new HashSet<int>()"

.PP
Definition at line \fB2569\fP of file \fBPlayer\&.cs\fP\&.
.SS "List<string> Player\&.Flags\&.reservedTutorial = new List<string>()"

.PP
Definition at line \fB2573\fP of file \fBPlayer\&.cs\fP\&.
.SS "Dictionary<string, ExcelData> Player\&.Flags\&.storyExcel = new Dictionary<string, ExcelData>()"

.PP
Definition at line \fB2579\fP of file \fBPlayer\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "bool Player\&.Flags\&.abilityHighlightDisabled\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB2119\fP of file \fBPlayer\&.cs\fP\&.
.SS "bool Player\&.Flags\&.backpackHighlightDisabled\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB2104\fP of file \fBPlayer\&.cs\fP\&.
.SS "int Player\&.Flags\&.build\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB2299\fP of file \fBPlayer\&.cs\fP\&.
.SS "bool Player\&.Flags\&.canComupWithFoodRecipe\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB2164\fP of file \fBPlayer\&.cs\fP\&.
.SS "int Player\&.Flags\&.daysAfterQuestExploration\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB2359\fP of file \fBPlayer\&.cs\fP\&.
.SS "bool Player\&.Flags\&.elinGift\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB2134\fP of file \fBPlayer\&.cs\fP\&.
.SS "bool Player\&.Flags\&.fiamaFirstDream\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB2044\fP of file \fBPlayer\&.cs\fP\&.
.SS "bool Player\&.Flags\&.fiamaStoryBookGiven\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB2029\fP of file \fBPlayer\&.cs\fP\&.
.SS "bool Player\&.Flags\&.gotClickReward\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB1999\fP of file \fBPlayer\&.cs\fP\&.
.SS "bool Player\&.Flags\&.gotEtherDisease\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB2239\fP of file \fBPlayer\&.cs\fP\&.
.SS "bool Player\&.Flags\&.gotMelilithCurse\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB2149\fP of file \fBPlayer\&.cs\fP\&.
.SS "bool Player\&.Flags\&.helpHighlightDisabled\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB2059\fP of file \fBPlayer\&.cs\fP\&.
.SS "bool Player\&.Flags\&.isShoesOff\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB2089\fP of file \fBPlayer\&.cs\fP\&.
.SS "bool Player\&.Flags\&.KilledBossInVoid\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB2179\fP of file \fBPlayer\&.cs\fP\&.
.SS "int Player\&.Flags\&.landDeedBought\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB2374\fP of file \fBPlayer\&.cs\fP\&.
.SS "bool Player\&.Flags\&.little_killed\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB2224\fP of file \fBPlayer\&.cs\fP\&.
.SS "bool Player\&.Flags\&.little_saved\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB2209\fP of file \fBPlayer\&.cs\fP\&.
.SS "bool Player\&.Flags\&.loytelEscaped\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB2254\fP of file \fBPlayer\&.cs\fP\&.
.SS "int Player\&.Flags\&.loytelMartLv\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB2389\fP of file \fBPlayer\&.cs\fP\&.
.SS "int Player\&.Flags\&.lutz\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB2344\fP of file \fBPlayer\&.cs\fP\&.
.SS "bool Player\&.Flags\&.magicChestSent\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB2269\fP of file \fBPlayer\&.cs\fP\&.
.SS "int Player\&.Flags\&.main\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB2314\fP of file \fBPlayer\&.cs\fP\&.
.SS "bool Player\&.Flags\&.pickedMelilithTreasure\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB2074\fP of file \fBPlayer\&.cs\fP\&.
.SS "int Player\&.Flags\&.start\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB2284\fP of file \fBPlayer\&.cs\fP\&.
.SS "bool Player\&.Flags\&.statueShipped\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB2194\fP of file \fBPlayer\&.cs\fP\&.
.SS "int Player\&.Flags\&.storyFiama\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB2329\fP of file \fBPlayer\&.cs\fP\&.
.SS "bool Player\&.Flags\&.welcome\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB2014\fP of file \fBPlayer\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
