.TH "Player.Pref" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Player.Pref
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBlastBuildCategory\fP"
.br
.ti -1c
.RI "string \fBlastBuildRecipe\fP"
.br
.ti -1c
.RI "int \fBlastIdTabAbility\fP"
.br
.ti -1c
.RI "bool \fBlayerInventory\fP"
.br
.ti -1c
.RI "bool \fBlayerAbility\fP"
.br
.ti -1c
.RI "bool \fBlayerCraft\fP"
.br
.ti -1c
.RI "bool \fBsort_ascending\fP"
.br
.ti -1c
.RI "bool \fBsort_ascending_shop\fP"
.br
.ti -1c
.RI "UIList\&.SortMode \fBsortResources\fP"
.br
.ti -1c
.RI "UIList\&.SortMode \fBsortPeople\fP"
.br
.ti -1c
.RI "UIList\&.SortMode \fBsortResearch\fP = UIList\&.SortMode\&.ByCategory"
.br
.ti -1c
.RI "UIList\&.SortMode \fBsortInv\fP = UIList\&.SortMode\&.ByCategory"
.br
.ti -1c
.RI "UIList\&.SortMode \fBsortInvShop\fP = UIList\&.SortMode\&.ByValue"
.br
.ti -1c
.RI "UIList\&.SortMode \fBsortAbility\fP = UIList\&.SortMode\&.ByID"
.br
.ti -1c
.RI "LayerPeople\&.ShowMode \fBmodePoeple\fP"
.br
.ti -1c
.RI "UIInventory\&.InteractMode \fBinteractMode\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB1836\fP of file \fBPlayer\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "UIInventory\&.InteractMode Player\&.Pref\&.interactMode"

.PP
Definition at line \fB1886\fP of file \fBPlayer\&.cs\fP\&.
.SS "string Player\&.Pref\&.lastBuildCategory"

.PP
Definition at line \fB1840\fP of file \fBPlayer\&.cs\fP\&.
.SS "string Player\&.Pref\&.lastBuildRecipe"

.PP
Definition at line \fB1844\fP of file \fBPlayer\&.cs\fP\&.
.SS "int Player\&.Pref\&.lastIdTabAbility"

.PP
Definition at line \fB1847\fP of file \fBPlayer\&.cs\fP\&.
.SS "bool Player\&.Pref\&.layerAbility"

.PP
Definition at line \fB1853\fP of file \fBPlayer\&.cs\fP\&.
.SS "bool Player\&.Pref\&.layerCraft"

.PP
Definition at line \fB1856\fP of file \fBPlayer\&.cs\fP\&.
.SS "bool Player\&.Pref\&.layerInventory"

.PP
Definition at line \fB1850\fP of file \fBPlayer\&.cs\fP\&.
.SS "LayerPeople\&.ShowMode Player\&.Pref\&.modePoeple"

.PP
Definition at line \fB1883\fP of file \fBPlayer\&.cs\fP\&.
.SS "bool Player\&.Pref\&.sort_ascending"

.PP
Definition at line \fB1859\fP of file \fBPlayer\&.cs\fP\&.
.SS "bool Player\&.Pref\&.sort_ascending_shop"

.PP
Definition at line \fB1862\fP of file \fBPlayer\&.cs\fP\&.
.SS "UIList\&.SortMode Player\&.Pref\&.sortAbility = UIList\&.SortMode\&.ByID"

.PP
Definition at line \fB1880\fP of file \fBPlayer\&.cs\fP\&.
.SS "UIList\&.SortMode Player\&.Pref\&.sortInv = UIList\&.SortMode\&.ByCategory"

.PP
Definition at line \fB1874\fP of file \fBPlayer\&.cs\fP\&.
.SS "UIList\&.SortMode Player\&.Pref\&.sortInvShop = UIList\&.SortMode\&.ByValue"

.PP
Definition at line \fB1877\fP of file \fBPlayer\&.cs\fP\&.
.SS "UIList\&.SortMode Player\&.Pref\&.sortPeople"

.PP
Definition at line \fB1868\fP of file \fBPlayer\&.cs\fP\&.
.SS "UIList\&.SortMode Player\&.Pref\&.sortResearch = UIList\&.SortMode\&.ByCategory"

.PP
Definition at line \fB1871\fP of file \fBPlayer\&.cs\fP\&.
.SS "UIList\&.SortMode Player\&.Pref\&.sortResources"

.PP
Definition at line \fB1865\fP of file \fBPlayer\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
