.TH "PlayingSong" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PlayingSong
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBid\fP"
.br
.ti -1c
.RI "string \fBidTool\fP"
.br
.ti -1c
.RI "int \fBindex\fP"
.br
.ti -1c
.RI "int \fBmistakes\fP"
.br
.ti -1c
.RI "BGMData \fBbgm\fP"
.br
.ti -1c
.RI "SoundSource \fBsource\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB4\fP of file \fBPlayingSong\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "BGMData PlayingSong\&.bgm"

.PP
Definition at line \fB19\fP of file \fBPlayingSong\&.cs\fP\&.
.SS "string PlayingSong\&.id"

.PP
Definition at line \fB7\fP of file \fBPlayingSong\&.cs\fP\&.
.SS "string PlayingSong\&.idTool"

.PP
Definition at line \fB10\fP of file \fBPlayingSong\&.cs\fP\&.
.SS "int PlayingSong\&.index"

.PP
Definition at line \fB13\fP of file \fBPlayingSong\&.cs\fP\&.
.SS "int PlayingSong\&.mistakes"

.PP
Definition at line \fB16\fP of file \fBPlayingSong\&.cs\fP\&.
.SS "SoundSource PlayingSong\&.source"

.PP
Definition at line \fB22\fP of file \fBPlayingSong\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
