.TH "Player.Stats" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Player.Stats
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "int \fBGetShippingBonus\fP (int _a)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBtimeElapsed\fP"
.br
.ti -1c
.RI "int \fBkumi\fP"
.br
.ti -1c
.RI "int \fBmins\fP"
.br
.ti -1c
.RI "int \fBdays\fP"
.br
.ti -1c
.RI "int \fBmonths\fP"
.br
.ti -1c
.RI "int \fBsieges\fP"
.br
.ti -1c
.RI "int \fBturns\fP"
.br
.ti -1c
.RI "int \fBkills\fP"
.br
.ti -1c
.RI "int \fBtaxBills\fP"
.br
.ti -1c
.RI "int \fBtaxBillsPaid\fP"
.br
.ti -1c
.RI "int \fBdigs\fP"
.br
.ti -1c
.RI "int \fBshipNum\fP"
.br
.ti -1c
.RI "int \fBshipMoney\fP"
.br
.ti -1c
.RI "int \fBslept\fP"
.br
.ti -1c
.RI "int \fBdeath\fP"
.br
.ti -1c
.RI "int \fBallyDeath\fP"
.br
.ti -1c
.RI "int \fBdeepest\fP"
.br
.ti -1c
.RI "int \fBgambleChest\fP"
.br
.ti -1c
.RI "int \fBgambleChestOpen\fP"
.br
.ti -1c
.RI "int \fBlastShippingExp\fP"
.br
.ti -1c
.RI "int \fBlastShippingExpMax\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB1890\fP of file \fBPlayer\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "int Player\&.Stats\&.GetShippingBonus (int _a)"

.PP
Definition at line \fB1893\fP of file \fBPlayer\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int Player\&.Stats\&.allyDeath"

.PP
Definition at line \fB1973\fP of file \fBPlayer\&.cs\fP\&.
.SS "int Player\&.Stats\&.days"

.PP
Definition at line \fB1937\fP of file \fBPlayer\&.cs\fP\&.
.SS "int Player\&.Stats\&.death"

.PP
Definition at line \fB1970\fP of file \fBPlayer\&.cs\fP\&.
.SS "int Player\&.Stats\&.deepest"

.PP
Definition at line \fB1976\fP of file \fBPlayer\&.cs\fP\&.
.SS "int Player\&.Stats\&.digs"

.PP
Definition at line \fB1958\fP of file \fBPlayer\&.cs\fP\&.
.SS "int Player\&.Stats\&.gambleChest"

.PP
Definition at line \fB1979\fP of file \fBPlayer\&.cs\fP\&.
.SS "int Player\&.Stats\&.gambleChestOpen"

.PP
Definition at line \fB1982\fP of file \fBPlayer\&.cs\fP\&.
.SS "int Player\&.Stats\&.kills"

.PP
Definition at line \fB1949\fP of file \fBPlayer\&.cs\fP\&.
.SS "int Player\&.Stats\&.kumi"

.PP
Definition at line \fB1931\fP of file \fBPlayer\&.cs\fP\&.
.SS "int Player\&.Stats\&.lastShippingExp"

.PP
Definition at line \fB1986\fP of file \fBPlayer\&.cs\fP\&.
.SS "int Player\&.Stats\&.lastShippingExpMax"

.PP
Definition at line \fB1990\fP of file \fBPlayer\&.cs\fP\&.
.SS "int Player\&.Stats\&.mins"

.PP
Definition at line \fB1934\fP of file \fBPlayer\&.cs\fP\&.
.SS "int Player\&.Stats\&.months"

.PP
Definition at line \fB1940\fP of file \fBPlayer\&.cs\fP\&.
.SS "int Player\&.Stats\&.shipMoney"

.PP
Definition at line \fB1964\fP of file \fBPlayer\&.cs\fP\&.
.SS "int Player\&.Stats\&.shipNum"

.PP
Definition at line \fB1961\fP of file \fBPlayer\&.cs\fP\&.
.SS "int Player\&.Stats\&.sieges"

.PP
Definition at line \fB1943\fP of file \fBPlayer\&.cs\fP\&.
.SS "int Player\&.Stats\&.slept"

.PP
Definition at line \fB1967\fP of file \fBPlayer\&.cs\fP\&.
.SS "int Player\&.Stats\&.taxBills"

.PP
Definition at line \fB1952\fP of file \fBPlayer\&.cs\fP\&.
.SS "int Player\&.Stats\&.taxBillsPaid"

.PP
Definition at line \fB1955\fP of file \fBPlayer\&.cs\fP\&.
.SS "double Player\&.Stats\&.timeElapsed"

.PP
Definition at line \fB1928\fP of file \fBPlayer\&.cs\fP\&.
.SS "int Player\&.Stats\&.turns"

.PP
Definition at line \fB1946\fP of file \fBPlayer\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
