.TH "POIMap.Cell" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
POIMap.Cell
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPoint\fP \fBGetCenter\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBx\fP"
.br
.ti -1c
.RI "int \fBz\fP"
.br
.ti -1c
.RI "bool \fBoccupied\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB134\fP of file \fBPOIMap\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBPoint\fP POIMap\&.Cell\&.GetCenter ()"

.PP
Definition at line \fB137\fP of file \fBPOIMap\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "bool POIMap\&.Cell\&.occupied"

.PP
Definition at line \fB149\fP of file \fBPOIMap\&.cs\fP\&.
.SS "int POIMap\&.Cell\&.x"

.PP
Definition at line \fB143\fP of file \fBPOIMap\&.cs\fP\&.
.SS "int POIMap\&.Cell\&.z"

.PP
Definition at line \fB146\fP of file \fBPOIMap\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
