.TH "POIMap" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
POIMap
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCell\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBInit\fP (int _mapSize, int _cellSize)"
.br
.ti -1c
.RI "void \fBReset\fP ()"
.br
.ti -1c
.RI "\fBPoint\fP \fBGetCenterOfEmptyCell\fP (int tries=100)"
.br
.ti -1c
.RI "\fBPOIMap\&.Cell\fP \fBGetCenterCell\fP (int radius=1)"
.br
.ti -1c
.RI "\fBPOIMap\&.Cell\fP \fBGetEmptyCell\fP ()"
.br
.ti -1c
.RI "void \fBForeachCenterOfEmptyCell\fP (Action< \fBPoint\fP > action)"
.br
.ti -1c
.RI "void \fBOccyupyPOI\fP (\fBPoint\fP p, int radius=0)"
.br
.ti -1c
.RI "void \fBOccyupyPOI\fP (int _x, int _z, int radius)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBPOIMap\&.Cell\fP[,] \fBcells\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static int \fBcellSize\fP"
.br
.ti -1c
.RI "static int \fBmapSize\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBlength\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB4\fP of file \fBPOIMap\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void POIMap\&.ForeachCenterOfEmptyCell (Action< \fBPoint\fP > action)"

.PP
Definition at line \fB80\fP of file \fBPOIMap\&.cs\fP\&.
.SS "\fBPOIMap\&.Cell\fP POIMap\&.GetCenterCell (int radius = \fR1\fP)"

.PP
Definition at line \fB58\fP of file \fBPOIMap\&.cs\fP\&.
.SS "\fBPoint\fP POIMap\&.GetCenterOfEmptyCell (int tries = \fR100\fP)"

.PP
Definition at line \fB42\fP of file \fBPOIMap\&.cs\fP\&.
.SS "\fBPOIMap\&.Cell\fP POIMap\&.GetEmptyCell ()"

.PP
Definition at line \fB64\fP of file \fBPOIMap\&.cs\fP\&.
.SS "void POIMap\&.Init (int _mapSize, int _cellSize)"

.PP
Definition at line \fB17\fP of file \fBPOIMap\&.cs\fP\&.
.SS "void POIMap\&.OccyupyPOI (int _x, int _z, int radius)"

.PP
Definition at line \fB101\fP of file \fBPOIMap\&.cs\fP\&.
.SS "void POIMap\&.OccyupyPOI (\fBPoint\fP p, int radius = \fR0\fP)"

.PP
Definition at line \fB95\fP of file \fBPOIMap\&.cs\fP\&.
.SS "void POIMap\&.Reset ()"

.PP
Definition at line \fB26\fP of file \fBPOIMap\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBPOIMap\&.Cell\fP [,] POIMap\&.cells"

.PP
Definition at line \fB131\fP of file \fBPOIMap\&.cs\fP\&.
.SS "int POIMap\&.cellSize\fR [static]\fP"

.PP
Definition at line \fB125\fP of file \fBPOIMap\&.cs\fP\&.
.SS "int POIMap\&.mapSize\fR [static]\fP"

.PP
Definition at line \fB128\fP of file \fBPOIMap\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "int POIMap\&.length\fR [get]\fP"

.PP
Definition at line \fB8\fP of file \fBPOIMap\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
