.TH "PointTarget" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PointTarget
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBEClass\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBUpdate\fP (\fBPoint\fP _pos)"
.br
.ti -1c
.RI "bool \fBShouldIgnore\fP (\fBCard\fP c)"
.br
.ti -1c
.RI "void \fBCycleTarget\fP (int a)"
.br
.ti -1c
.RI "bool \fBCanCycle\fP ()"
.br
.ti -1c
.RI "void \fBClear\fP ()"
.br
.ti -1c
.RI "void \fBCheckLastTarget\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBCard\fP \fBcard\fP"
.br
.ti -1c
.RI "\fBArea\fP \fBarea\fP"
.br
.ti -1c
.RI "\fBObjInfo\fP \fBobj\fP"
.br
.ti -1c
.RI "\fBBlockInfo\fP \fBblock\fP"
.br
.ti -1c
.RI "\fBTaskPoint\fP \fBtask\fP"
.br
.ti -1c
.RI "\fBIInspect\fP \fBtarget\fP"
.br
.ti -1c
.RI "\fBIInspect\fP \fBlastTarget\fP"
.br
.ti -1c
.RI "bool \fBhasTargetChanged\fP"
.br
.ti -1c
.RI "bool \fBhasValidTarget\fP"
.br
.ti -1c
.RI "bool \fBdrawHighlight\fP"
.br
.ti -1c
.RI "bool \fBmouse\fP = true"
.br
.ti -1c
.RI "bool \fBhasInteraction\fP"
.br
.ti -1c
.RI "bool \fBisValid\fP"
.br
.ti -1c
.RI "\fBPoint\fP \fBpos\fP = new \fBPoint\fP()"
.br
.ti -1c
.RI "\fBPoint\fP \fBlastPos\fP = new \fBPoint\fP()"
.br
.ti -1c
.RI "int \fBindex\fP"
.br
.ti -1c
.RI "List< \fBCard\fP > \fBcards\fP = new List<\fBCard\fP>()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBChara\fP \fBTargetChara\fP\fR [get]\fP"
.br
.in -1c

Properties inherited from \fBEClass\fP
.in +1c
.ti -1c
.RI "static \fBGame\fP \fBgame\fP\fR [get]\fP"
.br
.ti -1c
.RI "static bool \fBAdvMode\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBPlayer\fP \fBplayer\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBChara\fP \fBpc\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBUI\fP \fBui\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBMap\fP \fB_map\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBZone\fP \fB_zone\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranchOrHomeBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFaction\fP \fBHome\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFaction\fP \fBWilds\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBScene\fP \fBscene\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBBaseGameScreen\fP \fBscreen\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameSetting\fP \fBsetting\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameData\fP \fBgamedata\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBColorProfile\fP \fBColors\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBWorld\fP \fBworld\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBsources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBeditorSources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static SoundManager \fBSound\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBCoreDebug\fP \fBdebug\fP\fR [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Static Public Member Functions inherited from \fBEClass\fP
.in +1c
.ti -1c
.RI "static int \fBrnd\fP (int a)"
.br
.ti -1c
.RI "static int \fBcurve\fP (int a, int start, int step, int rate=75)"
.br
.ti -1c
.RI "static int \fBrndHalf\fP (int a)"
.br
.ti -1c
.RI "static float \fBrndf\fP (float a)"
.br
.ti -1c
.RI "static int \fBrndSqrt\fP (int a)"
.br
.ti -1c
.RI "static void \fBWait\fP (float a, \fBCard\fP c)"
.br
.ti -1c
.RI "static void \fBWait\fP (float a, \fBPoint\fP p)"
.br
.ti -1c
.RI "static int \fBBigger\fP (int a, int b)"
.br
.ti -1c
.RI "static int \fBSmaller\fP (int a, int b)"
.br
.in -1c

Static Public Attributes inherited from \fBEClass\fP
.in +1c
.ti -1c
.RI "static \fBCore\fP \fBcore\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB6\fP of file \fBPointTarget\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "bool PointTarget\&.CanCycle ()"

.PP
Definition at line \fB192\fP of file \fBPointTarget\&.cs\fP\&.
.SS "void PointTarget\&.CheckLastTarget ()"

.PP
Definition at line \fB208\fP of file \fBPointTarget\&.cs\fP\&.
.SS "void PointTarget\&.Clear ()"

.PP
Definition at line \fB198\fP of file \fBPointTarget\&.cs\fP\&.
.SS "void PointTarget\&.CycleTarget (int a)"

.PP
Definition at line \fB180\fP of file \fBPointTarget\&.cs\fP\&.
.SS "bool PointTarget\&.ShouldIgnore (\fBCard\fP c)"

.PP
Definition at line \fB119\fP of file \fBPointTarget\&.cs\fP\&.
.SS "void PointTarget\&.Update (\fBPoint\fP _pos)"

.PP
Definition at line \fB23\fP of file \fBPointTarget\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBArea\fP PointTarget\&.area"

.PP
Definition at line \fB220\fP of file \fBPointTarget\&.cs\fP\&.
.SS "\fBBlockInfo\fP PointTarget\&.block"

.PP
Definition at line \fB226\fP of file \fBPointTarget\&.cs\fP\&.
.SS "\fBCard\fP PointTarget\&.card"

.PP
Definition at line \fB217\fP of file \fBPointTarget\&.cs\fP\&.
.SS "List<\fBCard\fP> PointTarget\&.cards = new List<\fBCard\fP>()"

.PP
Definition at line \fB265\fP of file \fBPointTarget\&.cs\fP\&.
.SS "bool PointTarget\&.drawHighlight"

.PP
Definition at line \fB244\fP of file \fBPointTarget\&.cs\fP\&.
.SS "bool PointTarget\&.hasInteraction"

.PP
Definition at line \fB250\fP of file \fBPointTarget\&.cs\fP\&.
.SS "bool PointTarget\&.hasTargetChanged"

.PP
Definition at line \fB238\fP of file \fBPointTarget\&.cs\fP\&.
.SS "bool PointTarget\&.hasValidTarget"

.PP
Definition at line \fB241\fP of file \fBPointTarget\&.cs\fP\&.
.SS "int PointTarget\&.index"

.PP
Definition at line \fB262\fP of file \fBPointTarget\&.cs\fP\&.
.SS "bool PointTarget\&.isValid"

.PP
Definition at line \fB253\fP of file \fBPointTarget\&.cs\fP\&.
.SS "\fBPoint\fP PointTarget\&.lastPos = new \fBPoint\fP()"

.PP
Definition at line \fB259\fP of file \fBPointTarget\&.cs\fP\&.
.SS "\fBIInspect\fP PointTarget\&.lastTarget"

.PP
Definition at line \fB235\fP of file \fBPointTarget\&.cs\fP\&.
.SS "bool PointTarget\&.mouse = true"

.PP
Definition at line \fB247\fP of file \fBPointTarget\&.cs\fP\&.
.SS "\fBObjInfo\fP PointTarget\&.obj"

.PP
Definition at line \fB223\fP of file \fBPointTarget\&.cs\fP\&.
.SS "\fBPoint\fP PointTarget\&.pos = new \fBPoint\fP()"

.PP
Definition at line \fB256\fP of file \fBPointTarget\&.cs\fP\&.
.SS "\fBIInspect\fP PointTarget\&.target"

.PP
Definition at line \fB232\fP of file \fBPointTarget\&.cs\fP\&.
.SS "\fBTaskPoint\fP PointTarget\&.task"

.PP
Definition at line \fB229\fP of file \fBPointTarget\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "\fBChara\fP PointTarget\&.TargetChara\fR [get]\fP"

.PP
Definition at line \fB10\fP of file \fBPointTarget\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
