.TH "Portrait" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Portrait
.SH SYNOPSIS
.br
.PP
.PP
Inherits UIButton\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetPerson\fP (\fBPerson\fP p)"
.br
.ti -1c
.RI "void \fBSetChara\fP (\fBChara\fP c, PCCData pccData=null)"
.br
.ti -1c
.RI "void \fBSetPortrait\fP (string id, Color colorOverlay=default(Color))"
.br
.ti -1c
.RI "void \fBSetPortrait\fP (bool isPortrait, Sprite spritePortrait, Sprite spriteOverlay=null, Color colorOverlay=default(Color), Sprite spriteFull=null)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static List< ModItem< Sprite > > \fBListPlayerPortraits\fP (int gender, bool nullPortrait=false)"
.br
.ti -1c
.RI "static List< ModItem< Sprite > > \fBListPortraits\fP (string idDict)"
.br
.ti -1c
.RI "static List< ModItem< Sprite > > \fBListPortraits\fP (int gender, string cat)"
.br
.ti -1c
.RI "static string \fBGetRandomPortrait\fP (string idDict)"
.br
.ti -1c
.RI "static string \fBGetRandomPortrait\fP (int gender, string cat)"
.br
.ti -1c
.RI "static bool \fBExists\fP (string id)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Image \fBportrait\fP"
.br
.ti -1c
.RI "Image \fBoverlay\fP"
.br
.ti -1c
.RI "Image \fBimageChara\fP"
.br
.ti -1c
.RI "Image \fBimageFaith\fP"
.br
.ti -1c
.RI "Image \fBimageFull\fP"
.br
.ti -1c
.RI "Image \fBimageFrame\fP"
.br
.ti -1c
.RI "Sprite \fBspriteNoPortrait\fP"
.br
.ti -1c
.RI "bool \fBenableFull\fP = true"
.br
.ti -1c
.RI "bool \fBhideIfNoPortrait\fP"
.br
.ti -1c
.RI "bool \fBfixSpritePos\fP = true"
.br
.ti -1c
.RI "bool \fBshowPortrait\fP = true"
.br
.ti -1c
.RI "float \fBcharaScale\fP = 1f"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static ModItemList< Sprite > \fBmodPortraitBGFs\fP = new ModItemList<Sprite>(3)"
.br
.ti -1c
.RI "static ModItemList< Sprite > \fBmodPortraitBGs\fP = new ModItemList<Sprite>(3)"
.br
.ti -1c
.RI "static ModItemList< Sprite > \fBmodPortraits\fP = new ModItemList<Sprite>(3)"
.br
.ti -1c
.RI "static ModItemList< Sprite > \fBmodOverlays\fP = new ModItemList<Sprite>(3)"
.br
.ti -1c
.RI "static ModItemList< Sprite > \fBmodFull\fP = new ModItemList<Sprite>(3)"
.br
.ti -1c
.RI "static Dictionary< string, List< ModItem< Sprite > > > \fBdictList\fP = new Dictionary<string, List<ModItem<Sprite>>>()"
.br
.ti -1c
.RI "static HashSet< string > \fBallIds\fP = new HashSet<string>()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB9\fP of file \fBPortrait\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "static bool Portrait\&.Exists (string id)\fR [static]\fP"

.PP
Definition at line \fB83\fP of file \fBPortrait\&.cs\fP\&.
.SS "static string Portrait\&.GetRandomPortrait (int gender, string cat)\fR [static]\fP"

.PP
Definition at line \fB77\fP of file \fBPortrait\&.cs\fP\&.
.SS "static string Portrait\&.GetRandomPortrait (string idDict)\fR [static]\fP"

.PP
Definition at line \fB71\fP of file \fBPortrait\&.cs\fP\&.
.SS "static List< ModItem< Sprite > > Portrait\&.ListPlayerPortraits (int gender, bool nullPortrait = \fRfalse\fP)\fR [static]\fP"

.PP
Definition at line \fB12\fP of file \fBPortrait\&.cs\fP\&.
.SS "static List< ModItem< Sprite > > Portrait\&.ListPortraits (int gender, string cat)\fR [static]\fP"

.PP
Definition at line \fB42\fP of file \fBPortrait\&.cs\fP\&.
.SS "static List< ModItem< Sprite > > Portrait\&.ListPortraits (string idDict)\fR [static]\fP"

.PP
Definition at line \fB23\fP of file \fBPortrait\&.cs\fP\&.
.SS "void Portrait\&.SetChara (\fBChara\fP c, PCCData pccData = \fRnull\fP)"

.PP
Definition at line \fB107\fP of file \fBPortrait\&.cs\fP\&.
.SS "void Portrait\&.SetPerson (\fBPerson\fP p)"

.PP
Definition at line \fB89\fP of file \fBPortrait\&.cs\fP\&.
.SS "void Portrait\&.SetPortrait (bool isPortrait, Sprite spritePortrait, Sprite spriteOverlay = \fRnull\fP, Color colorOverlay = \fRdefault(Color)\fP, Sprite spriteFull = \fRnull\fP)"

.PP
Definition at line \fB186\fP of file \fBPortrait\&.cs\fP\&.
.SS "void Portrait\&.SetPortrait (string id, Color colorOverlay = \fRdefault(Color)\fP)"

.PP
Definition at line \fB177\fP of file \fBPortrait\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "HashSet<string> Portrait\&.allIds = new HashSet<string>()\fR [static]\fP"

.PP
Definition at line \fB255\fP of file \fBPortrait\&.cs\fP\&.
.SS "float Portrait\&.charaScale = 1f"

.PP
Definition at line \fB291\fP of file \fBPortrait\&.cs\fP\&.
.SS "Dictionary<string, List<ModItem<Sprite> > > Portrait\&.dictList = new Dictionary<string, List<ModItem<Sprite>>>()\fR [static]\fP"

.PP
Definition at line \fB252\fP of file \fBPortrait\&.cs\fP\&.
.SS "bool Portrait\&.enableFull = true"

.PP
Definition at line \fB279\fP of file \fBPortrait\&.cs\fP\&.
.SS "bool Portrait\&.fixSpritePos = true"

.PP
Definition at line \fB285\fP of file \fBPortrait\&.cs\fP\&.
.SS "bool Portrait\&.hideIfNoPortrait"

.PP
Definition at line \fB282\fP of file \fBPortrait\&.cs\fP\&.
.SS "Image Portrait\&.imageChara"

.PP
Definition at line \fB264\fP of file \fBPortrait\&.cs\fP\&.
.SS "Image Portrait\&.imageFaith"

.PP
Definition at line \fB267\fP of file \fBPortrait\&.cs\fP\&.
.SS "Image Portrait\&.imageFrame"

.PP
Definition at line \fB273\fP of file \fBPortrait\&.cs\fP\&.
.SS "Image Portrait\&.imageFull"

.PP
Definition at line \fB270\fP of file \fBPortrait\&.cs\fP\&.
.SS "ModItemList<Sprite> Portrait\&.modFull = new ModItemList<Sprite>(3)\fR [static]\fP"

.PP
Definition at line \fB249\fP of file \fBPortrait\&.cs\fP\&.
.SS "ModItemList<Sprite> Portrait\&.modOverlays = new ModItemList<Sprite>(3)\fR [static]\fP"

.PP
Definition at line \fB246\fP of file \fBPortrait\&.cs\fP\&.
.SS "ModItemList<Sprite> Portrait\&.modPortraitBGFs = new ModItemList<Sprite>(3)\fR [static]\fP"

.PP
Definition at line \fB237\fP of file \fBPortrait\&.cs\fP\&.
.SS "ModItemList<Sprite> Portrait\&.modPortraitBGs = new ModItemList<Sprite>(3)\fR [static]\fP"

.PP
Definition at line \fB240\fP of file \fBPortrait\&.cs\fP\&.
.SS "ModItemList<Sprite> Portrait\&.modPortraits = new ModItemList<Sprite>(3)\fR [static]\fP"

.PP
Definition at line \fB243\fP of file \fBPortrait\&.cs\fP\&.
.SS "Image Portrait\&.overlay"

.PP
Definition at line \fB261\fP of file \fBPortrait\&.cs\fP\&.
.SS "Image Portrait\&.portrait"

.PP
Definition at line \fB258\fP of file \fBPortrait\&.cs\fP\&.
.SS "bool Portrait\&.showPortrait = true"

.PP
Definition at line \fB288\fP of file \fBPortrait\&.cs\fP\&.
.SS "Sprite Portrait\&.spriteNoPortrait"

.PP
Definition at line \fB276\fP of file \fBPortrait\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
