.TH "PostEffectProfile" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PostEffectProfile
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBEScriptable\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBOnChangeProfile\fP ()"
.br
.ti -1c
.RI "void \fBApply\fP (Camera cam)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBBrightness\fP"
.br
.ti -1c
.RI "float \fBSaturation\fP"
.br
.ti -1c
.RI "float \fBContrast\fP"
.br
.ti -1c
.RI "int \fBsharpen\fP = 20"
.br
.ti -1c
.RI "int \fBsharpen2\fP = 80"
.br
.ti -1c
.RI "int \fBblur\fP"
.br
.ti -1c
.RI "bool \fBenableAA\fP"
.br
.ti -1c
.RI "bool \fBenableCharaAA\fP"
.br
.ti -1c
.RI "bool \fBdisable\fP"
.br
.ti -1c
.RI "bool \fBkuwahara\fP"
.br
.ti -1c
.RI "AAMode \fBaaMode\fP"
.br
.ti -1c
.RI "float \fBoffsetScale\fP"
.br
.ti -1c
.RI "float \fBblurRadius\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Static Public Member Functions inherited from \fBEScriptable\fP
.in +1c
.ti -1c
.RI "static int \fBrnd\fP (int a)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB6\fP of file \fBPostEffectProfile\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void PostEffectProfile\&.Apply (Camera cam)"

.PP
Definition at line \fB28\fP of file \fBPostEffectProfile\&.cs\fP\&.
.SS "void PostEffectProfile\&.OnChangeProfile ()"

.PP
Definition at line \fB18\fP of file \fBPostEffectProfile\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "AAMode PostEffectProfile\&.aaMode"

.PP
Definition at line \fB79\fP of file \fBPostEffectProfile\&.cs\fP\&.
.SS "int PostEffectProfile\&.blur"

.PP
Definition at line \fB64\fP of file \fBPostEffectProfile\&.cs\fP\&.
.SS "float PostEffectProfile\&.blurRadius"

.PP
Definition at line \fB85\fP of file \fBPostEffectProfile\&.cs\fP\&.
.SS "float PostEffectProfile\&.Brightness"

.PP
Definition at line \fB49\fP of file \fBPostEffectProfile\&.cs\fP\&.
.SS "float PostEffectProfile\&.Contrast"

.PP
Definition at line \fB55\fP of file \fBPostEffectProfile\&.cs\fP\&.
.SS "bool PostEffectProfile\&.disable"

.PP
Definition at line \fB73\fP of file \fBPostEffectProfile\&.cs\fP\&.
.SS "bool PostEffectProfile\&.enableAA"

.PP
Definition at line \fB67\fP of file \fBPostEffectProfile\&.cs\fP\&.
.SS "bool PostEffectProfile\&.enableCharaAA"

.PP
Definition at line \fB70\fP of file \fBPostEffectProfile\&.cs\fP\&.
.SS "bool PostEffectProfile\&.kuwahara"

.PP
Definition at line \fB76\fP of file \fBPostEffectProfile\&.cs\fP\&.
.SS "float PostEffectProfile\&.offsetScale"

.PP
Definition at line \fB82\fP of file \fBPostEffectProfile\&.cs\fP\&.
.SS "float PostEffectProfile\&.Saturation"

.PP
Definition at line \fB52\fP of file \fBPostEffectProfile\&.cs\fP\&.
.SS "int PostEffectProfile\&.sharpen = 20"

.PP
Definition at line \fB58\fP of file \fBPostEffectProfile\&.cs\fP\&.
.SS "int PostEffectProfile\&.sharpen2 = 80"

.PP
Definition at line \fB61\fP of file \fBPostEffectProfile\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
