.TH "ProceduralMesh" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ProceduralMesh
.SH SYNOPSIS
.br
.PP
.PP
Inherits ScriptableObject\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "Mesh \fBGetMesh\fP ()"
.br
.ti -1c
.RI "void \fBCreate\fP ()"
.br
.ti -1c
.RI "void \fBAddTriangles\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Vector2 \fBtiling\fP = Vector2\&.one"
.br
.ti -1c
.RI "float \fBUVPadding\fP = 0\&.02f"
.br
.ti -1c
.RI "Vector3 \fBpos\fP = new Vector3(0f, 0f, \-1f)"
.br
.ti -1c
.RI "Vector3 \fBoffset\fP"
.br
.ti -1c
.RI "Vector3 \fBsize\fP = Vector3\&.one"
.br
.ti -1c
.RI "bool \fBtop\fP"
.br
.ti -1c
.RI "bool \fBcalculateNormal\fP = true"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB6\fP of file \fBProceduralMesh\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void ProceduralMesh\&.AddTriangles ()"

.PP
Definition at line \fB60\fP of file \fBProceduralMesh\&.cs\fP\&.
.SS "void ProceduralMesh\&.Create ()"

.PP
Definition at line \fB19\fP of file \fBProceduralMesh\&.cs\fP\&.
.SS "Mesh ProceduralMesh\&.GetMesh ()"

.PP
Definition at line \fB9\fP of file \fBProceduralMesh\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "bool ProceduralMesh\&.calculateNormal = true"

.PP
Definition at line \fB108\fP of file \fBProceduralMesh\&.cs\fP\&.
.SS "Vector3 ProceduralMesh\&.offset"

.PP
Definition at line \fB99\fP of file \fBProceduralMesh\&.cs\fP\&.
.SS "Vector3 ProceduralMesh\&.pos = new Vector3(0f, 0f, \-1f)"

.PP
Definition at line \fB96\fP of file \fBProceduralMesh\&.cs\fP\&.
.SS "Vector3 ProceduralMesh\&.size = Vector3\&.one"

.PP
Definition at line \fB102\fP of file \fBProceduralMesh\&.cs\fP\&.
.SS "Vector2 ProceduralMesh\&.tiling = Vector2\&.one"

.PP
Definition at line \fB90\fP of file \fBProceduralMesh\&.cs\fP\&.
.SS "bool ProceduralMesh\&.top"

.PP
Definition at line \fB105\fP of file \fBProceduralMesh\&.cs\fP\&.
.SS "float ProceduralMesh\&.UVPadding = 0\&.02f"

.PP
Definition at line \fB93\fP of file \fBProceduralMesh\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
