.TH "Prologue" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Prologue
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBidStartZone\fP"
.br
.ti -1c
.RI "int \fBstartX\fP"
.br
.ti -1c
.RI "int \fBstartZ\fP"
.br
.ti -1c
.RI "int \fByear\fP"
.br
.ti -1c
.RI "int \fBmonth\fP"
.br
.ti -1c
.RI "int \fBday\fP"
.br
.ti -1c
.RI "int \fBhour\fP"
.br
.ti -1c
.RI "Vector2Int \fBposAsh\fP"
.br
.ti -1c
.RI "Vector2Int \fBposFiama\fP"
.br
.ti -1c
.RI "Vector2Int \fBposPunk\fP"
.br
.ti -1c
.RI "Weather\&.Condition \fBweather\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB6\fP of file \fBPrologue\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int Prologue\&.day"

.PP
Definition at line \fB24\fP of file \fBPrologue\&.cs\fP\&.
.SS "int Prologue\&.hour"

.PP
Definition at line \fB27\fP of file \fBPrologue\&.cs\fP\&.
.SS "string Prologue\&.idStartZone"

.PP
Definition at line \fB9\fP of file \fBPrologue\&.cs\fP\&.
.SS "int Prologue\&.month"

.PP
Definition at line \fB21\fP of file \fBPrologue\&.cs\fP\&.
.SS "Vector2Int Prologue\&.posAsh"

.PP
Definition at line \fB30\fP of file \fBPrologue\&.cs\fP\&.
.SS "Vector2Int Prologue\&.posFiama"

.PP
Definition at line \fB33\fP of file \fBPrologue\&.cs\fP\&.
.SS "Vector2Int Prologue\&.posPunk"

.PP
Definition at line \fB36\fP of file \fBPrologue\&.cs\fP\&.
.SS "int Prologue\&.startX"

.PP
Definition at line \fB12\fP of file \fBPrologue\&.cs\fP\&.
.SS "int Prologue\&.startZ"

.PP
Definition at line \fB15\fP of file \fBPrologue\&.cs\fP\&.
.SS "Weather\&.Condition Prologue\&.weather"

.PP
Definition at line \fB39\fP of file \fBPrologue\&.cs\fP\&.
.SS "int Prologue\&.year"

.PP
Definition at line \fB18\fP of file \fBPrologue\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
