.TH "PropSet" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PropSet
.SH SYNOPSIS
.br
.PP
.PP
Inherits Dictionary< int, Card >\&.
.PP
Inherited by \fBPropSetCategory\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBAdd\fP (\fBCard\fP c)"
.br
.ti -1c
.RI "void \fBRemove\fP (\fBCard\fP c)"
.br
.ti -1c
.RI "bool \fBContains\fP (\fBCard\fP c)"
.br
.ti -1c
.RI "virtual void \fBModNum\fP (int a)"
.br
.ti -1c
.RI "void \fBOnChangeNum\fP (int a)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBnum\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB5\fP of file \fBPropSet\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void PropSet\&.Add (\fBCard\fP c)"

.PP
Definition at line \fB8\fP of file \fBPropSet\&.cs\fP\&.
.SS "bool PropSet\&.Contains (\fBCard\fP c)"

.PP
Definition at line \fB22\fP of file \fBPropSet\&.cs\fP\&.
.SS "virtual void PropSet\&.ModNum (int a)\fR [virtual]\fP"

.PP
Definition at line \fB28\fP of file \fBPropSet\&.cs\fP\&.
.SS "void PropSet\&.OnChangeNum (int a)"

.PP
Definition at line \fB34\fP of file \fBPropSet\&.cs\fP\&.
.SS "void PropSet\&.Remove (\fBCard\fP c)"

.PP
Definition at line \fB15\fP of file \fBPropSet\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int PropSet\&.num"

.PP
Definition at line \fB40\fP of file \fBPropSet\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
