.TH "QuestFiamaLock" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QuestFiamaLock
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBQuestProgression\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override bool \fBCanUpdateOnTalk\fP (\fBChara\fP c)"
.br
.ti -1c
.RI "override void \fBOnStart\fP ()"
.br
.in -1c

Public Member Functions inherited from \fBQuestProgression\fP
.in +1c
.ti -1c
.RI "override string \fBGetDetail\fP (bool onJournal=false)"
.br
.in -1c

Public Member Functions inherited from \fBQuestSequence\fP
.in +1c
.ti -1c
.RI "override string \fBGetTitle\fP ()"
.br
.ti -1c
.RI "override void \fBOnCompleteTask\fP ()"
.br
.in -1c

Public Member Functions inherited from \fBQuest\fP
.in +1c
.ti -1c
.RI "virtual \fBThing\fP \fBGetDestThing\fP ()"
.br
.ti -1c
.RI "virtual int \fBGetExtraMoney\fP ()"
.br
.ti -1c
.RI "virtual int \fBGetRewardPlat\fP (int money)"
.br
.ti -1c
.RI "override bool \fBEquals\fP (object obj)"
.br
.ti -1c
.RI "virtual bool \fBIsVisibleOnQuestBoard\fP ()"
.br
.ti -1c
.RI "virtual bool \fBCanStartQuest\fP ()"
.br
.ti -1c
.RI "virtual \fBZone\fP \fBCreateInstanceZone\fP (\fBChara\fP c)"
.br
.ti -1c
.RI "virtual bool \fBUpdateOnTalk\fP ()"
.br
.ti -1c
.RI "void \fBInit\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnInit\fP ()"
.br
.ti -1c
.RI "\fBQuest\fP \fBSetClient\fP (\fBChara\fP c, bool assignQuest=true)"
.br
.ti -1c
.RI "void \fBSetTask\fP (\fBQuestTask\fP _task)"
.br
.ti -1c
.RI "void \fBStart\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnEnterZone\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnClickQuest\fP ()"
.br
.ti -1c
.RI "void \fBFail\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnFail\fP ()"
.br
.ti -1c
.RI "virtual void \fBShowCompleteText\fP ()"
.br
.ti -1c
.RI "void \fBComplete\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnBeforeComplete\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnDropReward\fP ()"
.br
.ti -1c
.RI "\fBThing\fP \fBDropReward\fP (string id)"
.br
.ti -1c
.RI "\fBThing\fP \fBDropReward\fP (\fBThing\fP t)"
.br
.ti -1c
.RI "virtual void \fBOnComplete\fP ()"
.br
.ti -1c
.RI "void \fBCompleteTask\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnGiveItem\fP (\fBChara\fP c, \fBThing\fP t)"
.br
.ti -1c
.RI "virtual void \fBOnKillChara\fP (\fBChara\fP c)"
.br
.ti -1c
.RI "virtual void \fBOnModKarma\fP (int a)"
.br
.ti -1c
.RI "void \fBNextPhase\fP ()"
.br
.ti -1c
.RI "void \fBChangePhase\fP (int a)"
.br
.ti -1c
.RI "virtual void \fBOnChangePhase\fP (int a)"
.br
.ti -1c
.RI "string \fBParse\fP (string s)"
.br
.ti -1c
.RI "virtual string \fBGetTrackerText\fP ()"
.br
.ti -1c
.RI "virtual string \fBGetDetailText\fP (bool onJournal=false)"
.br
.ti -1c
.RI "virtual string \fBGetTextProgress\fP ()"
.br
.ti -1c
.RI "string \fBGetRewardText\fP ()"
.br
.ti -1c
.RI "virtual string \fBGetTalkProgress\fP ()"
.br
.ti -1c
.RI "virtual string \fBGetTalkComplete\fP ()"
.br
.ti -1c
.RI "void \fBUpdateJournal\fP ()"
.br
.ti -1c
.RI "virtual bool \fBIsDeliverTarget\fP (\fBChara\fP c)"
.br
.ti -1c
.RI "virtual bool \fBCanDeliverToClient\fP (\fBChara\fP c)"
.br
.ti -1c
.RI "virtual bool \fBCanDeliverToBox\fP (\fBThing\fP t)"
.br
.ti -1c
.RI "virtual bool \fBDeliver\fP (\fBChara\fP c, \fBThing\fP t=null)"
.br
.in -1c
.SS "Additional Inherited Members"


Public Types inherited from \fBQuest\fP
.in +1c
.ti -1c
.RI "enum \fBDifficultyType\fP { \fBDefault\fP, \fBDeliver\fP, \fBSupply\fP, \fBEscort\fP, \fBBulk\fP, \fBMeal\fP, \fBFarm\fP, \fBMusic\fP }"
.br
.ti -1c
.RI "enum \fBSubReward\fP { \fBplat\fP, \fBgacha_coin\fP, \fBmoney2\fP, \fBticket_furniture\fP }"
.br
.in -1c

Static Public Member Functions inherited from \fBQuest\fP
.in +1c
.ti -1c
.RI "static \fBQuest\fP \fBCreate\fP (string _id, string _idPerson=null, \fBChara\fP c=null)"
.br
.ti -1c
.RI "static List< \fBZone\fP > \fBListDeliver\fP ()"
.br
.in -1c

Static Public Member Functions inherited from \fBEClass\fP
.in +1c
.ti -1c
.RI "static int \fBrnd\fP (int a)"
.br
.ti -1c
.RI "static int \fBcurve\fP (int a, int start, int step, int rate=75)"
.br
.ti -1c
.RI "static int \fBrndHalf\fP (int a)"
.br
.ti -1c
.RI "static float \fBrndf\fP (float a)"
.br
.ti -1c
.RI "static int \fBrndSqrt\fP (int a)"
.br
.ti -1c
.RI "static void \fBWait\fP (float a, \fBCard\fP c)"
.br
.ti -1c
.RI "static void \fBWait\fP (float a, \fBPoint\fP p)"
.br
.ti -1c
.RI "static int \fBBigger\fP (int a, int b)"
.br
.ti -1c
.RI "static int \fBSmaller\fP (int a, int b)"
.br
.in -1c

Public Attributes inherited from \fBQuest\fP
.in +1c
.ti -1c
.RI "string \fBid\fP"
.br
.ti -1c
.RI "int \fBuid\fP"
.br
.ti -1c
.RI "int \fBuidClientZone\fP"
.br
.ti -1c
.RI "int \fBphase\fP"
.br
.ti -1c
.RI "int \fBlv\fP"
.br
.ti -1c
.RI "int \fBdeadline\fP"
.br
.ti -1c
.RI "int \fBdifficulty\fP"
.br
.ti -1c
.RI "int \fBrewardMoney\fP"
.br
.ti -1c
.RI "int \fBbonusMoney\fP"
.br
.ti -1c
.RI "int \fBstartDate\fP"
.br
.ti -1c
.RI "int \fBdangerLv\fP"
.br
.ti -1c
.RI "bool \fBisNew\fP"
.br
.ti -1c
.RI "bool \fBisComplete\fP"
.br
.ti -1c
.RI "bool \fBtrack\fP"
.br
.ti -1c
.RI "\fBPerson\fP \fBperson\fP"
.br
.ti -1c
.RI "\fBQuestTask\fP \fBtask\fP"
.br
.ti -1c
.RI "\fBRefChara\fP \fBrefChara\fP = new \fBRefChara\fP()"
.br
.in -1c

Static Public Attributes inherited from \fBQuest\fP
.in +1c
.ti -1c
.RI "const int \fBPhaseComplete\fP = 999"
.br
.in -1c

Static Public Attributes inherited from \fBEClass\fP
.in +1c
.ti -1c
.RI "static \fBCore\fP \fBcore\fP"
.br
.in -1c

Properties inherited from \fBQuestProgression\fP
.in +1c
.ti -1c
.RI "override string \fBTitlePrefix\fP\fR [get]\fP"
.br
.in -1c

Properties inherited from \fBQuestSequence\fP
.in +1c
.ti -1c
.RI "\fBSourceQuest\&.Row\fP \fBoriginalSource\fP\fR [get]\fP"
.br
.ti -1c
.RI "override string \fBidSource\fP\fR [get]\fP"
.br
.in -1c

Properties inherited from \fBQuest\fP
.in +1c
.ti -1c
.RI "\fBZone\fP \fBClientZone\fP\fR [get]\fP"
.br
.ti -1c
.RI "\fBChara\fP \fBchara\fP\fR [get]\fP"
.br
.ti -1c
.RI "\fBSourceQuest\&.Row\fP \fBsource\fP\fR [get]\fP"
.br
.ti -1c
.RI "bool \fBConfetti\fP\fR [get]\fP"
.br
.ti -1c
.RI "bool \fBIsExpired\fP\fR [get]\fP"
.br
.ti -1c
.RI "int \fBHours\fP\fR [get]\fP"
.br
.ti -1c
.RI "string \fBTextDeadline\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBHasDLC\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual string \fBidSource\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual string \fBRewardSuffix\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBFameContent\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual string \fBTextExtra\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual int \fBDangerLv\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual int \fBAffinityGain\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual int \fBBaseMoney\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual int \fBKarmaOnFail\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBCanAbandon\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual int \fBFameOnComplete\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual int \fBRangeDeadLine\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBUseInstanceZone\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBForbidTeleport\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBRequireClientInSameZone\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual Quest\&.DifficultyType \fBdifficultyType\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual \fBChara\fP \fBDestChara\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual string \fBRefDrama1\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual string \fBRefDrama2\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual string \fBRefDrama3\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual string \fBRefDrama4\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual string \fBTitlePrefix\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBCanAutoAdvance\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBIsRandomQuest\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual string \fBNameDeliver\fP\fR [get]\fP"
.br
.in -1c

Properties inherited from \fBEClass\fP
.in +1c
.ti -1c
.RI "static \fBGame\fP \fBgame\fP\fR [get]\fP"
.br
.ti -1c
.RI "static bool \fBAdvMode\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBPlayer\fP \fBplayer\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBChara\fP \fBpc\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBUI\fP \fBui\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBMap\fP \fB_map\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBZone\fP \fB_zone\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranchOrHomeBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFaction\fP \fBHome\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFaction\fP \fBWilds\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBScene\fP \fBscene\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBBaseGameScreen\fP \fBscreen\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameSetting\fP \fBsetting\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameData\fP \fBgamedata\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBColorProfile\fP \fBColors\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBWorld\fP \fBworld\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBsources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBeditorSources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static SoundManager \fBSound\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBCoreDebug\fP \fBdebug\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB4\fP of file \fBQuestFiamaLock\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override bool QuestFiamaLock\&.CanUpdateOnTalk (\fBChara\fP c)\fR [virtual]\fP"

.PP
Reimplemented from \fBQuest\fP\&.
.PP
Definition at line \fB7\fP of file \fBQuestFiamaLock\&.cs\fP\&.
.SS "override void QuestFiamaLock\&.OnStart ()\fR [virtual]\fP"

.PP
Reimplemented from \fBQuest\fP\&.
.PP
Definition at line \fB13\fP of file \fBQuestFiamaLock\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
