.TH "QuestCraft.Req" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QuestCraft.Req
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBReq\fP (string id, int n)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBidThing\fP"
.br
.ti -1c
.RI "int \fBnum\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB185\fP of file \fBQuestCraft\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "QuestCraft\&.Req\&.Req ()"

.PP
Definition at line \fB188\fP of file \fBQuestCraft\&.cs\fP\&.
.SS "QuestCraft\&.Req\&.Req (string id, int n)"

.PP
Definition at line \fB193\fP of file \fBQuestCraft\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "string QuestCraft\&.Req\&.idThing"

.PP
Definition at line \fB201\fP of file \fBQuestCraft\&.cs\fP\&.
.SS "int QuestCraft\&.Req\&.num"

.PP
Definition at line \fB205\fP of file \fBQuestCraft\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
