.TH "QuestTaskHunt" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QuestTaskHunt
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBQuestTask\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBType\fP { \fBDefault\fP, \fBRace\fP }"
.br
.ti -1c
.RI "enum \fBSetup\fP { \fBRandom\fP, \fBFighterGuild\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override bool \fBIsComplete\fP ()"
.br
.ti -1c
.RI "override void \fBOnInit\fP ()"
.br
.ti -1c
.RI "override void \fBOnKillChara\fP (\fBChara\fP c)"
.br
.ti -1c
.RI "override string \fBGetTextProgress\fP ()"
.br
.ti -1c
.RI "override void \fBOnGetDetail\fP (ref string detail, bool onJournal)"
.br
.in -1c

Public Member Functions inherited from \fBQuestTask\fP
.in +1c
.ti -1c
.RI "void \fBSetOwner\fP (\fBQuest\fP quest)"
.br
.ti -1c
.RI "virtual void \fBOnStart\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnGiveItem\fP (\fBChara\fP c, \fBThing\fP t)"
.br
.ti -1c
.RI "virtual void \fBOnModKarma\fP (int a)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static List< \fBSourceChara\&.Row\fP > \fBListTargets\fP (string idRace)"
.br
.in -1c

Static Public Member Functions inherited from \fBEClass\fP
.in +1c
.ti -1c
.RI "static int \fBrnd\fP (int a)"
.br
.ti -1c
.RI "static int \fBcurve\fP (int a, int start, int step, int rate=75)"
.br
.ti -1c
.RI "static int \fBrndHalf\fP (int a)"
.br
.ti -1c
.RI "static float \fBrndf\fP (float a)"
.br
.ti -1c
.RI "static int \fBrndSqrt\fP (int a)"
.br
.ti -1c
.RI "static void \fBWait\fP (float a, \fBCard\fP c)"
.br
.ti -1c
.RI "static void \fBWait\fP (float a, \fBPoint\fP p)"
.br
.ti -1c
.RI "static int \fBBigger\fP (int a, int b)"
.br
.ti -1c
.RI "static int \fBSmaller\fP (int a, int b)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBnumHunted\fP"
.br
.ti -1c
.RI "int \fBnumRequired\fP"
.br
.ti -1c
.RI "string \fBidRace\fP"
.br
.ti -1c
.RI "QuestTaskHunt\&.Type \fBtype\fP"
.br
.ti -1c
.RI "QuestTaskHunt\&.Setup \fBsetup\fP"
.br
.in -1c

Public Attributes inherited from \fBQuestTask\fP
.in +1c
.ti -1c
.RI "\fBQuest\fP \fBowner\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBSourceRace\&.Row\fP \fBRace\fP\fR [get]\fP"
.br
.ti -1c
.RI "override string \fBRefDrama2\fP\fR [get]\fP"
.br
.ti -1c
.RI "override string \fBRefDrama3\fP\fR [get]\fP"
.br
.in -1c

Properties inherited from \fBQuestTask\fP
.in +1c
.ti -1c
.RI "virtual string \fBRefDrama1\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual string \fBRefDrama2\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual string \fBRefDrama3\fP\fR [get]\fP"
.br
.in -1c

Properties inherited from \fBEClass\fP
.in +1c
.ti -1c
.RI "static \fBGame\fP \fBgame\fP\fR [get]\fP"
.br
.ti -1c
.RI "static bool \fBAdvMode\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBPlayer\fP \fBplayer\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBChara\fP \fBpc\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBUI\fP \fBui\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBMap\fP \fB_map\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBZone\fP \fB_zone\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranchOrHomeBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFaction\fP \fBHome\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFaction\fP \fBWilds\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBScene\fP \fBscene\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBBaseGameScreen\fP \fBscreen\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameSetting\fP \fBsetting\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameData\fP \fBgamedata\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBColorProfile\fP \fBColors\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBWorld\fP \fBworld\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBsources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBeditorSources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static SoundManager \fBSound\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBCoreDebug\fP \fBdebug\fP\fR [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Static Public Attributes inherited from \fBEClass\fP
.in +1c
.ti -1c
.RI "static \fBCore\fP \fBcore\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB7\fP of file \fBQuestTaskHunt\&.cs\fP\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "enum QuestTaskHunt\&.Setup"

.PP
Definition at line \fB204\fP of file \fBQuestTaskHunt\&.cs\fP\&.
.SS "enum QuestTaskHunt\&.Type"

.PP
Definition at line \fB195\fP of file \fBQuestTaskHunt\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override string QuestTaskHunt\&.GetTextProgress ()\fR [virtual]\fP"

.PP
Reimplemented from \fBQuestTask\fP\&.
.PP
Definition at line \fB114\fP of file \fBQuestTaskHunt\&.cs\fP\&.
.SS "override bool QuestTaskHunt\&.IsComplete ()\fR [virtual]\fP"

.PP
Reimplemented from \fBQuestTask\fP\&.
.PP
Definition at line \fB44\fP of file \fBQuestTaskHunt\&.cs\fP\&.
.SS "static List< \fBSourceChara\&.Row\fP > QuestTaskHunt\&.ListTargets (string idRace)\fR [static]\fP"

.PP
Definition at line \fB50\fP of file \fBQuestTaskHunt\&.cs\fP\&.
.SS "override void QuestTaskHunt\&.OnGetDetail (ref string detail, bool onJournal)\fR [virtual]\fP"

.PP
Reimplemented from \fBQuestTask\fP\&.
.PP
Definition at line \fB124\fP of file \fBQuestTaskHunt\&.cs\fP\&.
.SS "override void QuestTaskHunt\&.OnInit ()\fR [virtual]\fP"

.PP
Reimplemented from \fBQuestTask\fP\&.
.PP
Definition at line \fB64\fP of file \fBQuestTaskHunt\&.cs\fP\&.
.SS "override void QuestTaskHunt\&.OnKillChara (\fBChara\fP c)\fR [virtual]\fP"

.PP
Reimplemented from \fBQuestTask\fP\&.
.PP
Definition at line \fB90\fP of file \fBQuestTaskHunt\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "string QuestTaskHunt\&.idRace"

.PP
Definition at line \fB185\fP of file \fBQuestTaskHunt\&.cs\fP\&.
.SS "int QuestTaskHunt\&.numHunted"

.PP
Definition at line \fB177\fP of file \fBQuestTaskHunt\&.cs\fP\&.
.SS "int QuestTaskHunt\&.numRequired"

.PP
Definition at line \fB181\fP of file \fBQuestTaskHunt\&.cs\fP\&.
.SS "QuestTaskHunt\&.Setup QuestTaskHunt\&.setup"

.PP
Definition at line \fB192\fP of file \fBQuestTaskHunt\&.cs\fP\&.
.SS "QuestTaskHunt\&.Type QuestTaskHunt\&.type"

.PP
Definition at line \fB189\fP of file \fBQuestTaskHunt\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "\fBSourceRace\&.Row\fP QuestTaskHunt\&.Race\fR [get]\fP"

.PP
Definition at line \fB11\fP of file \fBQuestTaskHunt\&.cs\fP\&.
.SS "override string QuestTaskHunt\&.RefDrama2\fR [get]\fP"

.PP
Definition at line \fB21\fP of file \fBQuestTaskHunt\&.cs\fP\&.
.SS "override string QuestTaskHunt\&.RefDrama3\fR [get]\fP"

.PP
Definition at line \fB35\fP of file \fBQuestTaskHunt\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
