.TH "QuestTaskFlyer" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QuestTaskFlyer
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBQuestTask\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override bool \fBIsComplete\fP ()"
.br
.ti -1c
.RI "override void \fBOnGiveItem\fP (\fBChara\fP c, \fBThing\fP t)"
.br
.ti -1c
.RI "override void \fBOnInit\fP ()"
.br
.ti -1c
.RI "override string \fBGetTextProgress\fP ()"
.br
.in -1c

Public Member Functions inherited from \fBQuestTask\fP
.in +1c
.ti -1c
.RI "void \fBSetOwner\fP (\fBQuest\fP quest)"
.br
.ti -1c
.RI "virtual void \fBOnStart\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnKillChara\fP (\fBChara\fP c)"
.br
.ti -1c
.RI "virtual void \fBOnModKarma\fP (int a)"
.br
.ti -1c
.RI "virtual void \fBOnGetDetail\fP (ref string detail, bool onJournal)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBnum\fP"
.br
.ti -1c
.RI "int \fBnumRequired\fP"
.br
.in -1c

Public Attributes inherited from \fBQuestTask\fP
.in +1c
.ti -1c
.RI "\fBQuest\fP \fBowner\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override string \fBRefDrama2\fP\fR [get]\fP"
.br
.ti -1c
.RI "override string \fBRefDrama3\fP\fR [get]\fP"
.br
.in -1c

Properties inherited from \fBQuestTask\fP
.in +1c
.ti -1c
.RI "virtual string \fBRefDrama1\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual string \fBRefDrama2\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual string \fBRefDrama3\fP\fR [get]\fP"
.br
.in -1c

Properties inherited from \fBEClass\fP
.in +1c
.ti -1c
.RI "static \fBGame\fP \fBgame\fP\fR [get]\fP"
.br
.ti -1c
.RI "static bool \fBAdvMode\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBPlayer\fP \fBplayer\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBChara\fP \fBpc\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBUI\fP \fBui\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBMap\fP \fB_map\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBZone\fP \fB_zone\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranchOrHomeBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFaction\fP \fBHome\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFaction\fP \fBWilds\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBScene\fP \fBscene\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBBaseGameScreen\fP \fBscreen\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameSetting\fP \fBsetting\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameData\fP \fBgamedata\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBColorProfile\fP \fBColors\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBWorld\fP \fBworld\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBsources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBeditorSources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static SoundManager \fBSound\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBCoreDebug\fP \fBdebug\fP\fR [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Static Public Member Functions inherited from \fBEClass\fP
.in +1c
.ti -1c
.RI "static int \fBrnd\fP (int a)"
.br
.ti -1c
.RI "static int \fBcurve\fP (int a, int start, int step, int rate=75)"
.br
.ti -1c
.RI "static int \fBrndHalf\fP (int a)"
.br
.ti -1c
.RI "static float \fBrndf\fP (float a)"
.br
.ti -1c
.RI "static int \fBrndSqrt\fP (int a)"
.br
.ti -1c
.RI "static void \fBWait\fP (float a, \fBCard\fP c)"
.br
.ti -1c
.RI "static void \fBWait\fP (float a, \fBPoint\fP p)"
.br
.ti -1c
.RI "static int \fBBigger\fP (int a, int b)"
.br
.ti -1c
.RI "static int \fBSmaller\fP (int a, int b)"
.br
.in -1c

Static Public Attributes inherited from \fBEClass\fP
.in +1c
.ti -1c
.RI "static \fBCore\fP \fBcore\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB5\fP of file \fBQuestTaskFlyer\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override string QuestTaskFlyer\&.GetTextProgress ()\fR [virtual]\fP"

.PP
Reimplemented from \fBQuestTask\fP\&.
.PP
Definition at line \fB49\fP of file \fBQuestTaskFlyer\&.cs\fP\&.
.SS "override bool QuestTaskFlyer\&.IsComplete ()\fR [virtual]\fP"

.PP
Reimplemented from \fBQuestTask\fP\&.
.PP
Definition at line \fB28\fP of file \fBQuestTaskFlyer\&.cs\fP\&.
.SS "override void QuestTaskFlyer\&.OnGiveItem (\fBChara\fP c, \fBThing\fP t)\fR [virtual]\fP"

.PP
Reimplemented from \fBQuestTask\fP\&.
.PP
Definition at line \fB34\fP of file \fBQuestTaskFlyer\&.cs\fP\&.
.SS "override void QuestTaskFlyer\&.OnInit ()\fR [virtual]\fP"

.PP
Reimplemented from \fBQuestTask\fP\&.
.PP
Definition at line \fB43\fP of file \fBQuestTaskFlyer\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int QuestTaskFlyer\&.num"

.PP
Definition at line \fB56\fP of file \fBQuestTaskFlyer\&.cs\fP\&.
.SS "int QuestTaskFlyer\&.numRequired"

.PP
Definition at line \fB60\fP of file \fBQuestTaskFlyer\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "override string QuestTaskFlyer\&.RefDrama2\fR [get]\fP"

.PP
Definition at line \fB9\fP of file \fBQuestTaskFlyer\&.cs\fP\&.
.SS "override string QuestTaskFlyer\&.RefDrama3\fR [get]\fP"

.PP
Definition at line \fB19\fP of file \fBQuestTaskFlyer\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
