.TH "Queue" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Queue
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBAIAct\fP \fBinteraction\fP"
.br
.ti -1c
.RI "UIButton \fBbutton\fP"
.br
.ti -1c
.RI "bool \fBremoved\fP"
.br
.ti -1c
.RI "bool \fBpinned\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "bool \fBCanCancel\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB4\fP of file \fBQueue\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "UIButton Queue\&.button"

.PP
Definition at line \fB20\fP of file \fBQueue\&.cs\fP\&.
.SS "\fBAIAct\fP Queue\&.interaction"

.PP
Definition at line \fB17\fP of file \fBQueue\&.cs\fP\&.
.SS "bool Queue\&.pinned"

.PP
Definition at line \fB26\fP of file \fBQueue\&.cs\fP\&.
.SS "bool Queue\&.removed"

.PP
Definition at line \fB23\fP of file \fBQueue\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "bool Queue\&.CanCancel\fR [get]\fP"

.PP
Definition at line \fB8\fP of file \fBQueue\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
