.TH "QueueManager" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QueueManager
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBEClass\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBOnSetGoal\fP (\fBAIAct\fP newGoal)"
.br
.ti -1c
.RI "\fBAIAct\fP \fBPop\fP ()"
.br
.ti -1c
.RI "\fBQueue\fP \fBManualAdd\fP (\fBAIAct\fP interaction)"
.br
.ti -1c
.RI "\fBQueue\fP \fBAdd\fP (\fBAIAct\fP interaction, bool insert=false)"
.br
.ti -1c
.RI "void \fBRemove\fP (\fBQueue\fP q)"
.br
.ti -1c
.RI "void \fBCancel\fP (\fBQueue\fP q)"
.br
.ti -1c
.RI "void \fBSetOwner\fP (\fBChara\fP _owner)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBChara\fP \fBowner\fP"
.br
.ti -1c
.RI "List< \fBQueue\fP > \fBlist\fP = new List<\fBQueue\fP>()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBUIQueue\fP \fBuiq\fP\fR [get]\fP"
.br
.ti -1c
.RI "\fBQueue\fP \fBcurrentQueue\fP\fR [get]\fP"
.br
.in -1c

Properties inherited from \fBEClass\fP
.in +1c
.ti -1c
.RI "static \fBGame\fP \fBgame\fP\fR [get]\fP"
.br
.ti -1c
.RI "static bool \fBAdvMode\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBPlayer\fP \fBplayer\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBChara\fP \fBpc\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBUI\fP \fBui\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBMap\fP \fB_map\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBZone\fP \fB_zone\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranchOrHomeBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFaction\fP \fBHome\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFaction\fP \fBWilds\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBScene\fP \fBscene\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBBaseGameScreen\fP \fBscreen\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameSetting\fP \fBsetting\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameData\fP \fBgamedata\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBColorProfile\fP \fBColors\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBWorld\fP \fBworld\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBsources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBeditorSources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static SoundManager \fBSound\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBCoreDebug\fP \fBdebug\fP\fR [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Static Public Member Functions inherited from \fBEClass\fP
.in +1c
.ti -1c
.RI "static int \fBrnd\fP (int a)"
.br
.ti -1c
.RI "static int \fBcurve\fP (int a, int start, int step, int rate=75)"
.br
.ti -1c
.RI "static int \fBrndHalf\fP (int a)"
.br
.ti -1c
.RI "static float \fBrndf\fP (float a)"
.br
.ti -1c
.RI "static int \fBrndSqrt\fP (int a)"
.br
.ti -1c
.RI "static void \fBWait\fP (float a, \fBCard\fP c)"
.br
.ti -1c
.RI "static void \fBWait\fP (float a, \fBPoint\fP p)"
.br
.ti -1c
.RI "static int \fBBigger\fP (int a, int b)"
.br
.ti -1c
.RI "static int \fBSmaller\fP (int a, int b)"
.br
.in -1c

Static Public Attributes inherited from \fBEClass\fP
.in +1c
.ti -1c
.RI "static \fBCore\fP \fBcore\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB5\fP of file \fBQueueManager\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBQueue\fP QueueManager\&.Add (\fBAIAct\fP interaction, bool insert = \fRfalse\fP)"

.PP
Definition at line \fB49\fP of file \fBQueueManager\&.cs\fP\&.
.SS "void QueueManager\&.Cancel (\fBQueue\fP q)"

.PP
Definition at line \fB82\fP of file \fBQueueManager\&.cs\fP\&.
.SS "\fBQueue\fP QueueManager\&.ManualAdd (\fBAIAct\fP interaction)"

.PP
Definition at line \fB43\fP of file \fBQueueManager\&.cs\fP\&.
.SS "void QueueManager\&.OnSetGoal (\fBAIAct\fP newGoal)"

.PP
Definition at line \fB32\fP of file \fBQueueManager\&.cs\fP\&.
.SS "\fBAIAct\fP QueueManager\&.Pop ()"

.PP
Definition at line \fB37\fP of file \fBQueueManager\&.cs\fP\&.
.SS "void QueueManager\&.Remove (\fBQueue\fP q)"

.PP
Definition at line \fB71\fP of file \fBQueueManager\&.cs\fP\&.
.SS "void QueueManager\&.SetOwner (\fBChara\fP _owner)"

.PP
Definition at line \fB93\fP of file \fBQueueManager\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "List<\fBQueue\fP> QueueManager\&.list = new List<\fBQueue\fP>()"

.PP
Definition at line \fB107\fP of file \fBQueueManager\&.cs\fP\&.
.SS "\fBChara\fP QueueManager\&.owner"

.PP
Definition at line \fB104\fP of file \fBQueueManager\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "\fBQueue\fP QueueManager\&.currentQueue\fR [get]\fP"

.PP
Definition at line \fB19\fP of file \fBQueueManager\&.cs\fP\&.
.SS "\fBUIQueue\fP QueueManager\&.uiq\fR [get]\fP"

.PP
Definition at line \fB9\fP of file \fBQueueManager\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
