.TH "RandomPositionMover" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RandomPositionMover
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBpickerInterval\fP"
.br
.ti -1c
.RI "float \fBradius\fP"
.br
.ti -1c
.RI "GameObject \fBplayer\fP"
.br
.ti -1c
.RI "Vector2 \fBrandomPointInCircle\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB5\fP of file \fBRandomPositionMover\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "float RandomPositionMover\&.pickerInterval"

.PP
Definition at line \fB32\fP of file \fBRandomPositionMover\&.cs\fP\&.
.SS "GameObject RandomPositionMover\&.player"

.PP
Definition at line \fB38\fP of file \fBRandomPositionMover\&.cs\fP\&.
.SS "float RandomPositionMover\&.radius"

.PP
Definition at line \fB35\fP of file \fBRandomPositionMover\&.cs\fP\&.
.SS "Vector2 RandomPositionMover\&.randomPointInCircle"

.PP
Definition at line \fB41\fP of file \fBRandomPositionMover\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
