.TH "RecipeUpdater" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RecipeUpdater
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBEClass\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBMode\fP { \fBPassive\fP, \fBImmediate\fP, \fBValidate\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBBuild\fP (\fBPoint\fP _p, RecipeUpdater\&.Mode _mode=RecipeUpdater\&.Mode\&.Passive)"
.br
.ti -1c
.RI "void \fBFixedUpdate\fP ()"
.br
.ti -1c
.RI "IEnumerable \fBRunRecipe\fP ()"
.br
.ti -1c
.RI "IEnumerable \fBRunDisassemble\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "IEnumerator \fBEnumerator\fP"
.br
.ti -1c
.RI "\fBPoint\fP \fBpos\fP = new \fBPoint\fP()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static List< \fBThing\fP > \fBlistD\fP = new List<\fBThing\fP>()"
.br
.ti -1c
.RI "static List< \fBThing\fP > \fBlastListD\fP = new List<\fBThing\fP>()"
.br
.ti -1c
.RI "static HashSet< \fBRecipe\fP > \fBrecipes\fP = new HashSet<\fBRecipe\fP>()"
.br
.ti -1c
.RI "static HashSet< \fBRecipe\fP > \fBlastRecipes\fP = new HashSet<\fBRecipe\fP>()"
.br
.ti -1c
.RI "static HashSet< string > \fBfactories\fP = new HashSet<string>()"
.br
.ti -1c
.RI "static RecipeUpdater\&.Mode \fBmode\fP"
.br
.ti -1c
.RI "static int \fBsync\fP"
.br
.ti -1c
.RI "static bool \fBdirty\fP"
.br
.in -1c

Static Public Attributes inherited from \fBEClass\fP
.in +1c
.ti -1c
.RI "static \fBCore\fP \fBcore\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Static Public Member Functions inherited from \fBEClass\fP
.in +1c
.ti -1c
.RI "static int \fBrnd\fP (int a)"
.br
.ti -1c
.RI "static int \fBcurve\fP (int a, int start, int step, int rate=75)"
.br
.ti -1c
.RI "static int \fBrndHalf\fP (int a)"
.br
.ti -1c
.RI "static float \fBrndf\fP (float a)"
.br
.ti -1c
.RI "static int \fBrndSqrt\fP (int a)"
.br
.ti -1c
.RI "static void \fBWait\fP (float a, \fBCard\fP c)"
.br
.ti -1c
.RI "static void \fBWait\fP (float a, \fBPoint\fP p)"
.br
.ti -1c
.RI "static int \fBBigger\fP (int a, int b)"
.br
.ti -1c
.RI "static int \fBSmaller\fP (int a, int b)"
.br
.in -1c

Properties inherited from \fBEClass\fP
.in +1c
.ti -1c
.RI "static \fBGame\fP \fBgame\fP\fR [get]\fP"
.br
.ti -1c
.RI "static bool \fBAdvMode\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBPlayer\fP \fBplayer\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBChara\fP \fBpc\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBUI\fP \fBui\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBMap\fP \fB_map\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBZone\fP \fB_zone\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranchOrHomeBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFaction\fP \fBHome\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFaction\fP \fBWilds\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBScene\fP \fBscene\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBBaseGameScreen\fP \fBscreen\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameSetting\fP \fBsetting\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameData\fP \fBgamedata\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBColorProfile\fP \fBColors\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBWorld\fP \fBworld\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBsources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBeditorSources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static SoundManager \fBSound\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBCoreDebug\fP \fBdebug\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB7\fP of file \fBRecipeUpdater\&.cs\fP\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "enum RecipeUpdater\&.Mode"

.PP
Definition at line \fB251\fP of file \fBRecipeUpdater\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void RecipeUpdater\&.Build (\fBPoint\fP _p, RecipeUpdater\&.Mode _mode = \fRRecipeUpdater::Mode::Passive\fP)"

.PP
Definition at line \fB10\fP of file \fBRecipeUpdater\&.cs\fP\&.
.SS "void RecipeUpdater\&.FixedUpdate ()"

.PP
Definition at line \fB34\fP of file \fBRecipeUpdater\&.cs\fP\&.
.SS "IEnumerable RecipeUpdater\&.RunDisassemble ()"

.PP
Definition at line \fB186\fP of file \fBRecipeUpdater\&.cs\fP\&.
.SS "IEnumerable RecipeUpdater\&.RunRecipe ()"

.PP
Definition at line \fB47\fP of file \fBRecipeUpdater\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "bool RecipeUpdater\&.dirty\fR [static]\fP"

.PP
Definition at line \fB248\fP of file \fBRecipeUpdater\&.cs\fP\&.
.SS "IEnumerator RecipeUpdater\&.Enumerator"

.PP
Definition at line \fB221\fP of file \fBRecipeUpdater\&.cs\fP\&.
.SS "HashSet<string> RecipeUpdater\&.factories = new HashSet<string>()\fR [static]\fP"

.PP
Definition at line \fB239\fP of file \fBRecipeUpdater\&.cs\fP\&.
.SS "List<\fBThing\fP> RecipeUpdater\&.lastListD = new List<\fBThing\fP>()\fR [static]\fP"

.PP
Definition at line \fB230\fP of file \fBRecipeUpdater\&.cs\fP\&.
.SS "HashSet<\fBRecipe\fP> RecipeUpdater\&.lastRecipes = new HashSet<\fBRecipe\fP>()\fR [static]\fP"

.PP
Definition at line \fB236\fP of file \fBRecipeUpdater\&.cs\fP\&.
.SS "List<\fBThing\fP> RecipeUpdater\&.listD = new List<\fBThing\fP>()\fR [static]\fP"

.PP
Definition at line \fB227\fP of file \fBRecipeUpdater\&.cs\fP\&.
.SS "RecipeUpdater\&.Mode RecipeUpdater\&.mode\fR [static]\fP"

.PP
Definition at line \fB242\fP of file \fBRecipeUpdater\&.cs\fP\&.
.SS "\fBPoint\fP RecipeUpdater\&.pos = new \fBPoint\fP()"

.PP
Definition at line \fB224\fP of file \fBRecipeUpdater\&.cs\fP\&.
.SS "HashSet<\fBRecipe\fP> RecipeUpdater\&.recipes = new HashSet<\fBRecipe\fP>()\fR [static]\fP"

.PP
Definition at line \fB233\fP of file \fBRecipeUpdater\&.cs\fP\&.
.SS "int RecipeUpdater\&.sync\fR [static]\fP"

.PP
Definition at line \fB245\fP of file \fBRecipeUpdater\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
