.TH "RefractionProfile" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RefractionProfile
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBEScriptable\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBApply\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBRefractionProfile\fP \fBGet\fP (string id)"
.br
.ti -1c
.RI "static void \fBApply\fP (string id)"
.br
.in -1c

Static Public Member Functions inherited from \fBEScriptable\fP
.in +1c
.ti -1c
.RI "static int \fBrnd\fP (int a)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Texture2D \fBtex\fP"
.br
.ti -1c
.RI "float \fBtransparency\fP"
.br
.ti -1c
.RI "Vector4 \fBgrabAnime\fP"
.br
.ti -1c
.RI "Vector4 \fBgrabPos\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB6\fP of file \fBRefractionProfile\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void RefractionProfile\&.Apply ()"

.PP
Definition at line \fB21\fP of file \fBRefractionProfile\&.cs\fP\&.
.SS "static void RefractionProfile\&.Apply (string id)\fR [static]\fP"

.PP
Definition at line \fB15\fP of file \fBRefractionProfile\&.cs\fP\&.
.SS "static \fBRefractionProfile\fP RefractionProfile\&.Get (string id)\fR [static]\fP"

.PP
Definition at line \fB9\fP of file \fBRefractionProfile\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "Vector4 RefractionProfile\&.grabAnime"

.PP
Definition at line \fB45\fP of file \fBRefractionProfile\&.cs\fP\&.
.SS "Vector4 RefractionProfile\&.grabPos"

.PP
Definition at line \fB48\fP of file \fBRefractionProfile\&.cs\fP\&.
.SS "Texture2D RefractionProfile\&.tex"

.PP
Definition at line \fB39\fP of file \fBRefractionProfile\&.cs\fP\&.
.SS "float RefractionProfile\&.transparency"

.PP
Definition at line \fB42\fP of file \fBRefractionProfile\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
