.TH "ReligionManager" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ReligionManager
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBEClass\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetOwner\fP ()"
.br
.ti -1c
.RI "void \fBOnCreateGame\fP ()"
.br
.ti -1c
.RI "void \fBOnLoad\fP ()"
.br
.ti -1c
.RI "\fBReligion\fP \fBFind\fP (string id)"
.br
.ti -1c
.RI "\fBReligion\fP \fBGetRandomReligion\fP (bool onlyJoinable=true, bool includeMinor=false)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Dictionary< string, \fBReligion\fP > \fBdictAll\fP = new Dictionary<string, \fBReligion\fP>()"
.br
.ti -1c
.RI "List< \fBReligion\fP > \fBlist\fP = new List<\fBReligion\fP>()"
.br
.ti -1c
.RI "\fBReligionEyth\fP \fBEyth\fP = new \fBReligionEyth\fP()"
.br
.ti -1c
.RI "\fBReligionWind\fP \fBWind\fP = new \fBReligionWind\fP()"
.br
.ti -1c
.RI "\fBReligionEarth\fP \fBEarth\fP = new \fBReligionEarth\fP()"
.br
.ti -1c
.RI "\fBReligionHealing\fP \fBHealing\fP = new \fBReligionHealing\fP()"
.br
.ti -1c
.RI "\fBReligionLuck\fP \fBLuck\fP = new \fBReligionLuck\fP()"
.br
.ti -1c
.RI "\fBReligionMachine\fP \fBMachine\fP = new \fBReligionMachine\fP()"
.br
.ti -1c
.RI "\fBReligionElement\fP \fBElement\fP = new \fBReligionElement\fP()"
.br
.ti -1c
.RI "\fBReligionHarvest\fP \fBHarvest\fP = new \fBReligionHarvest\fP()"
.br
.ti -1c
.RI "\fBReligionOblivion\fP \fBOblivion\fP = new \fBReligionOblivion\fP()"
.br
.ti -1c
.RI "\fBReligionHarmony\fP \fBHarmony\fP = new \fBReligionHarmony\fP()"
.br
.ti -1c
.RI "\fBReligionTrickery\fP \fBTrickery\fP = new \fBReligionTrickery\fP()"
.br
.ti -1c
.RI "\fBReligionMoonShadow\fP \fBMoonShadow\fP = new \fBReligionMoonShadow\fP()"
.br
.ti -1c
.RI "\fBReligionStrife\fP \fBStrife\fP = new \fBReligionStrife\fP()"
.br
.in -1c
.SS "Additional Inherited Members"


Static Public Member Functions inherited from \fBEClass\fP
.in +1c
.ti -1c
.RI "static int \fBrnd\fP (int a)"
.br
.ti -1c
.RI "static int \fBcurve\fP (int a, int start, int step, int rate=75)"
.br
.ti -1c
.RI "static int \fBrndHalf\fP (int a)"
.br
.ti -1c
.RI "static float \fBrndf\fP (float a)"
.br
.ti -1c
.RI "static int \fBrndSqrt\fP (int a)"
.br
.ti -1c
.RI "static void \fBWait\fP (float a, \fBCard\fP c)"
.br
.ti -1c
.RI "static void \fBWait\fP (float a, \fBPoint\fP p)"
.br
.ti -1c
.RI "static int \fBBigger\fP (int a, int b)"
.br
.ti -1c
.RI "static int \fBSmaller\fP (int a, int b)"
.br
.in -1c

Static Public Attributes inherited from \fBEClass\fP
.in +1c
.ti -1c
.RI "static \fBCore\fP \fBcore\fP"
.br
.in -1c

Properties inherited from \fBEClass\fP
.in +1c
.ti -1c
.RI "static \fBGame\fP \fBgame\fP\fR [get]\fP"
.br
.ti -1c
.RI "static bool \fBAdvMode\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBPlayer\fP \fBplayer\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBChara\fP \fBpc\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBUI\fP \fBui\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBMap\fP \fB_map\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBZone\fP \fB_zone\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranchOrHomeBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFaction\fP \fBHome\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFaction\fP \fBWilds\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBScene\fP \fBscene\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBBaseGameScreen\fP \fBscreen\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameSetting\fP \fBsetting\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameData\fP \fBgamedata\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBColorProfile\fP \fBColors\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBWorld\fP \fBworld\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBsources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBeditorSources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static SoundManager \fBSound\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBCoreDebug\fP \fBdebug\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB7\fP of file \fBReligionManager\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBReligion\fP ReligionManager\&.Find (string id)"

.PP
Definition at line \fB55\fP of file \fBReligionManager\&.cs\fP\&.
.SS "\fBReligion\fP ReligionManager\&.GetRandomReligion (bool onlyJoinable = \fRtrue\fP, bool includeMinor = \fRfalse\fP)"

.PP
Definition at line \fB68\fP of file \fBReligionManager\&.cs\fP\&.
.SS "void ReligionManager\&.OnCreateGame ()"

.PP
Definition at line \fB35\fP of file \fBReligionManager\&.cs\fP\&.
.SS "void ReligionManager\&.OnLoad ()"

.PP
Definition at line \fB45\fP of file \fBReligionManager\&.cs\fP\&.
.SS "void ReligionManager\&.SetOwner ()"

.PP
Definition at line \fB10\fP of file \fBReligionManager\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "Dictionary<string, \fBReligion\fP> ReligionManager\&.dictAll = new Dictionary<string, \fBReligion\fP>()"

.PP
Definition at line \fB76\fP of file \fBReligionManager\&.cs\fP\&.
.SS "\fBReligionEarth\fP ReligionManager\&.Earth = new \fBReligionEarth\fP()"

.PP
Definition at line \fB91\fP of file \fBReligionManager\&.cs\fP\&.
.SS "\fBReligionElement\fP ReligionManager\&.Element = new \fBReligionElement\fP()"

.PP
Definition at line \fB107\fP of file \fBReligionManager\&.cs\fP\&.
.SS "\fBReligionEyth\fP ReligionManager\&.Eyth = new \fBReligionEyth\fP()"

.PP
Definition at line \fB83\fP of file \fBReligionManager\&.cs\fP\&.
.SS "\fBReligionHarmony\fP ReligionManager\&.Harmony = new \fBReligionHarmony\fP()"

.PP
Definition at line \fB119\fP of file \fBReligionManager\&.cs\fP\&.
.SS "\fBReligionHarvest\fP ReligionManager\&.Harvest = new \fBReligionHarvest\fP()"

.PP
Definition at line \fB111\fP of file \fBReligionManager\&.cs\fP\&.
.SS "\fBReligionHealing\fP ReligionManager\&.Healing = new \fBReligionHealing\fP()"

.PP
Definition at line \fB95\fP of file \fBReligionManager\&.cs\fP\&.
.SS "List<\fBReligion\fP> ReligionManager\&.list = new List<\fBReligion\fP>()"

.PP
Definition at line \fB79\fP of file \fBReligionManager\&.cs\fP\&.
.SS "\fBReligionLuck\fP ReligionManager\&.Luck = new \fBReligionLuck\fP()"

.PP
Definition at line \fB99\fP of file \fBReligionManager\&.cs\fP\&.
.SS "\fBReligionMachine\fP ReligionManager\&.Machine = new \fBReligionMachine\fP()"

.PP
Definition at line \fB103\fP of file \fBReligionManager\&.cs\fP\&.
.SS "\fBReligionMoonShadow\fP ReligionManager\&.MoonShadow = new \fBReligionMoonShadow\fP()"

.PP
Definition at line \fB127\fP of file \fBReligionManager\&.cs\fP\&.
.SS "\fBReligionOblivion\fP ReligionManager\&.Oblivion = new \fBReligionOblivion\fP()"

.PP
Definition at line \fB115\fP of file \fBReligionManager\&.cs\fP\&.
.SS "\fBReligionStrife\fP ReligionManager\&.Strife = new \fBReligionStrife\fP()"

.PP
Definition at line \fB131\fP of file \fBReligionManager\&.cs\fP\&.
.SS "\fBReligionTrickery\fP ReligionManager\&.Trickery = new \fBReligionTrickery\fP()"

.PP
Definition at line \fB123\fP of file \fBReligionManager\&.cs\fP\&.
.SS "\fBReligionWind\fP ReligionManager\&.Wind = new \fBReligionWind\fP()"

.PP
Definition at line \fB87\fP of file \fBReligionManager\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
