.TH "RenderParam" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RenderParam
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMeshPassParam\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRenderParam\fP (\fBRenderParam\fP p)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBliquidLv\fP"
.br
.ti -1c
.RI "int \fBtile2\fP"
.br
.ti -1c
.RI "int \fBhalfBlockColor\fP"
.br
.ti -1c
.RI "int \fBdir\fP"
.br
.ti -1c
.RI "\fBCell\fP \fBcell\fP"
.br
.ti -1c
.RI "\fBSourceMaterial\&.Row\fP \fBmat\fP"
.br
.ti -1c
.RI "Vector3 \fBv\fP"
.br
.ti -1c
.RI "float \fBshadowFix\fP"
.br
.in -1c

Public Attributes inherited from \fBMeshPassParam\fP
.in +1c
.ti -1c
.RI "float \fBx\fP"
.br
.ti -1c
.RI "float \fBy\fP"
.br
.ti -1c
.RI "float \fBz\fP"
.br
.ti -1c
.RI "float \fBcolor\fP"
.br
.ti -1c
.RI "float \fBtile\fP"
.br
.ti -1c
.RI "float \fBmatColor\fP"
.br
.ti -1c
.RI "float \fBliquid\fP"
.br
.ti -1c
.RI "bool \fBsnow\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static \fBRenderParam\fP \fBshared\fP = new \fBRenderParam\fP()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "Vector3 \fBNewVector3\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB5\fP of file \fBRenderParam\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "RenderParam\&.RenderParam ()"

.PP
Definition at line \fB18\fP of file \fBRenderParam\&.cs\fP\&.
.SS "RenderParam\&.RenderParam (\fBRenderParam\fP p)"

.PP
Definition at line \fB23\fP of file \fBRenderParam\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBCell\fP RenderParam\&.cell"

.PP
Definition at line \fB60\fP of file \fBRenderParam\&.cs\fP\&.
.SS "int RenderParam\&.dir"

.PP
Definition at line \fB57\fP of file \fBRenderParam\&.cs\fP\&.
.SS "int RenderParam\&.halfBlockColor"

.PP
Definition at line \fB54\fP of file \fBRenderParam\&.cs\fP\&.
.SS "int RenderParam\&.liquidLv"

.PP
Definition at line \fB48\fP of file \fBRenderParam\&.cs\fP\&.
.SS "\fBSourceMaterial\&.Row\fP RenderParam\&.mat"

.PP
Definition at line \fB63\fP of file \fBRenderParam\&.cs\fP\&.
.SS "float RenderParam\&.shadowFix"

.PP
Definition at line \fB69\fP of file \fBRenderParam\&.cs\fP\&.
.SS "\fBRenderParam\fP RenderParam\&.shared = new \fBRenderParam\fP()\fR [static]\fP"

.PP
Definition at line \fB45\fP of file \fBRenderParam\&.cs\fP\&.
.SS "int RenderParam\&.tile2"

.PP
Definition at line \fB51\fP of file \fBRenderParam\&.cs\fP\&.
.SS "Vector3 RenderParam\&.v"

.PP
Definition at line \fB66\fP of file \fBRenderParam\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "Vector3 RenderParam\&.NewVector3\fR [get]\fP"

.PP
Definition at line \fB9\fP of file \fBRenderParam\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
