.TH "RenderDataEffect" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RenderDataEffect
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBRenderData\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "new void \fBDraw\fP (\fBRenderParam\fP p, int tile=0)"
.br
.in -1c

Public Member Functions inherited from \fBRenderData\fP
.in +1c
.ti -1c
.RI "virtual \fBCardActor\fP \fBCreateActor\fP ()"
.br
.ti -1c
.RI "void \fBInit\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnInit\fP ()"
.br
.ti -1c
.RI "int \fBConvertTile\fP (int tile)"
.br
.ti -1c
.RI "void \fBRenderToRenderCam\fP (\fBRenderParam\fP p)"
.br
.ti -1c
.RI "void \fBDraw\fP (\fBRenderParam\fP p, int tile)"
.br
.ti -1c
.RI "virtual void \fBDraw\fP (\fBRenderParam\fP p)"
.br
.ti -1c
.RI "void \fBDrawRepeatTo\fP (\fBRenderParam\fP p, float maxY, float height, ref Vector3 peakFix, bool skipFirst=false, int fire=0, bool isBlock=false)"
.br
.ti -1c
.RI "void \fBDrawRepeat\fP (\fBRenderParam\fP p, int count, float size, bool skipFirst=false)"
.br
.ti -1c
.RI "virtual void \fBDrawWithRotation\fP (\fBRenderParam\fP p, float angle)"
.br
.ti -1c
.RI "virtual void \fBDrawShadow\fP (\fBRenderParam\fP p)"
.br
.in -1c

Public Member Functions inherited from \fBIRenderer\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBspeed\fP"
.br
.in -1c

Public Attributes inherited from \fBRenderData\fP
.in +1c
.ti -1c
.RI "int \fBidShadow\fP"
.br
.ti -1c
.RI "\fBMeshPass\fP \fBpass\fP"
.br
.ti -1c
.RI "Vector3 \fBoffset\fP"
.br
.ti -1c
.RI "Vector3 \fBoffsetBack\fP"
.br
.ti -1c
.RI "Vector3 \fBoffsetShadow\fP"
.br
.ti -1c
.RI "Vector3 \fBheldPos\fP"
.br
.ti -1c
.RI "Vector2 \fBimagePivot\fP = new Vector2(0\&.5f, 0\&.25f)"
.br
.ti -1c
.RI "Vector2 \fBimageScale\fP = new Vector2(1f, 1f)"
.br
.ti -1c
.RI "Vector2 \fBsize\fP"
.br
.ti -1c
.RI "bool \fBmultiSize\fP"
.br
.ti -1c
.RI "bool \fBanimate\fP"
.br
.ti -1c
.RI "bool \fBuseOffsetBack\fP"
.br
.ti -1c
.RI "bool \fBpersistActor\fP"
.br
.ti -1c
.RI "bool \fBsymmetry\fP = true"
.br
.ti -1c
.RI "float \fBhangedFixZ\fP"
.br
.ti -1c
.RI "float \fBstackZ\fP"
.br
.ti -1c
.RI "\fBSubPassData\fP \fBsubCrate\fP"
.br
.ti -1c
.RI "\fBSourcePref\fP \fBshadowPref\fP"
.br
.ti -1c
.RI "\fBRenderData\fP \fBsubData\fP"
.br
.ti -1c
.RI "bool \fBinitialized\fP"
.br
.ti -1c
.RI "bool \fBhasSubPass\fP"
.br
.ti -1c
.RI "bool \fBhasSnowPass\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Static Public Member Functions inherited from \fBEScriptable\fP
.in +1c
.ti -1c
.RI "static int \fBrnd\fP (int a)"
.br
.in -1c

Static Public Attributes inherited from \fBRenderData\fP
.in +1c
.ti -1c
.RI "const int \fBHeldLightMod\fP = 1572864"
.br
.ti -1c
.RI "static Quaternion \fBdeadRotation\fP = Quaternion\&.Euler(0f, 0f, 90f)"
.br
.ti -1c
.RI "static \fBGameSetting\&.RenderSetting\fP \fBrenderSetting\fP"
.br
.in -1c

Protected Attributes inherited from \fBRenderData\fP
.in +1c
.ti -1c
.RI "Vector3 \fB_offset\fP"
.br
.in -1c

Properties inherited from \fBRenderData\fP
.in +1c
.ti -1c
.RI "static Quaternion \fBshadowRotation\fP\fR [get]\fP"
.br
.ti -1c
.RI "static Vector3 \fBshadowScale\fP\fR [get]\fP"
.br
.ti -1c
.RI "static Vector3 \fBshadowOffset\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBSkipOnMap\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual string \fBpathSprite\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual string \fBprefabName\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBForceAltHeldPosition\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB5\fP of file \fBRenderDataEffect\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "new void RenderDataEffect\&.Draw (\fBRenderParam\fP p, int tile = \fR0\fP)"

.PP
Definition at line \fB8\fP of file \fBRenderDataEffect\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "float RenderDataEffect\&.speed"

.PP
Definition at line \fB25\fP of file \fBRenderDataEffect\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
