.TH "SceneLightProfile" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SceneLightProfile
.SH SYNOPSIS
.br
.PP
.PP
Inherits ScriptableObject\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBbaseBrightness\fP"
.br
.ti -1c
.RI "float \fBdynamicBrightnessSpeed\fP"
.br
.ti -1c
.RI "float \fBdynamicBrightnessLightBonus\fP"
.br
.ti -1c
.RI "float \fBlightMod\fP"
.br
.ti -1c
.RI "float \fBlightPowerMod\fP"
.br
.ti -1c
.RI "float \fBplayerLightMod\fP = 1f"
.br
.ti -1c
.RI "AnimationCurve \fBlightLimit\fP"
.br
.ti -1c
.RI "AnimationCurve \fBlightModCurve\fP"
.br
.ti -1c
.RI "AnimationCurve \fBlightPower\fP"
.br
.ti -1c
.RI "AnimationCurve \fBbaseBrightnessCurve\fP"
.br
.ti -1c
.RI "AnimationCurve \fBdynamicBrightnessCurve\fP"
.br
.ti -1c
.RI "AnimationCurve \fBdynamicBrightnessCurve2\fP"
.br
.ti -1c
.RI "AnimationCurve \fBnightRatioCurve\fP"
.br
.ti -1c
.RI "AnimationCurve \fBfovCurveChara\fP"
.br
.ti -1c
.RI "AnimationCurve \fBfogBrightness\fP"
.br
.ti -1c
.RI "AnimationCurve \fBvignetteCurve\fP"
.br
.ti -1c
.RI "AnimationCurve \fBbloomCurve\fP"
.br
.ti -1c
.RI "AnimationCurve \fBbloomCurve2\fP"
.br
.ti -1c
.RI "AnimationCurve \fBorbitAlphaCurve\fP"
.br
.ti -1c
.RI "AnimationCurve \fBshadowCurve\fP"
.br
.ti -1c
.RI "AnimationCurve \fBshadowCurveFloor\fP"
.br
.ti -1c
.RI "bool \fBvignette\fP"
.br
.ti -1c
.RI "Color \fBvignetteColor\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB5\fP of file \fBSceneLightProfile\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "float SceneLightProfile\&.baseBrightness"

.PP
Definition at line \fB8\fP of file \fBSceneLightProfile\&.cs\fP\&.
.SS "AnimationCurve SceneLightProfile\&.baseBrightnessCurve"

.PP
Definition at line \fB35\fP of file \fBSceneLightProfile\&.cs\fP\&.
.SS "AnimationCurve SceneLightProfile\&.bloomCurve"

.PP
Definition at line \fB56\fP of file \fBSceneLightProfile\&.cs\fP\&.
.SS "AnimationCurve SceneLightProfile\&.bloomCurve2"

.PP
Definition at line \fB59\fP of file \fBSceneLightProfile\&.cs\fP\&.
.SS "AnimationCurve SceneLightProfile\&.dynamicBrightnessCurve"

.PP
Definition at line \fB38\fP of file \fBSceneLightProfile\&.cs\fP\&.
.SS "AnimationCurve SceneLightProfile\&.dynamicBrightnessCurve2"

.PP
Definition at line \fB41\fP of file \fBSceneLightProfile\&.cs\fP\&.
.SS "float SceneLightProfile\&.dynamicBrightnessLightBonus"

.PP
Definition at line \fB14\fP of file \fBSceneLightProfile\&.cs\fP\&.
.SS "float SceneLightProfile\&.dynamicBrightnessSpeed"

.PP
Definition at line \fB11\fP of file \fBSceneLightProfile\&.cs\fP\&.
.SS "AnimationCurve SceneLightProfile\&.fogBrightness"

.PP
Definition at line \fB50\fP of file \fBSceneLightProfile\&.cs\fP\&.
.SS "AnimationCurve SceneLightProfile\&.fovCurveChara"

.PP
Definition at line \fB47\fP of file \fBSceneLightProfile\&.cs\fP\&.
.SS "AnimationCurve SceneLightProfile\&.lightLimit"

.PP
Definition at line \fB26\fP of file \fBSceneLightProfile\&.cs\fP\&.
.SS "float SceneLightProfile\&.lightMod"

.PP
Definition at line \fB17\fP of file \fBSceneLightProfile\&.cs\fP\&.
.SS "AnimationCurve SceneLightProfile\&.lightModCurve"

.PP
Definition at line \fB29\fP of file \fBSceneLightProfile\&.cs\fP\&.
.SS "AnimationCurve SceneLightProfile\&.lightPower"

.PP
Definition at line \fB32\fP of file \fBSceneLightProfile\&.cs\fP\&.
.SS "float SceneLightProfile\&.lightPowerMod"

.PP
Definition at line \fB20\fP of file \fBSceneLightProfile\&.cs\fP\&.
.SS "AnimationCurve SceneLightProfile\&.nightRatioCurve"

.PP
Definition at line \fB44\fP of file \fBSceneLightProfile\&.cs\fP\&.
.SS "AnimationCurve SceneLightProfile\&.orbitAlphaCurve"

.PP
Definition at line \fB62\fP of file \fBSceneLightProfile\&.cs\fP\&.
.SS "float SceneLightProfile\&.playerLightMod = 1f"

.PP
Definition at line \fB23\fP of file \fBSceneLightProfile\&.cs\fP\&.
.SS "AnimationCurve SceneLightProfile\&.shadowCurve"

.PP
Definition at line \fB65\fP of file \fBSceneLightProfile\&.cs\fP\&.
.SS "AnimationCurve SceneLightProfile\&.shadowCurveFloor"

.PP
Definition at line \fB68\fP of file \fBSceneLightProfile\&.cs\fP\&.
.SS "bool SceneLightProfile\&.vignette"

.PP
Definition at line \fB71\fP of file \fBSceneLightProfile\&.cs\fP\&.
.SS "Color SceneLightProfile\&.vignetteColor"

.PP
Definition at line \fB74\fP of file \fBSceneLightProfile\&.cs\fP\&.
.SS "AnimationCurve SceneLightProfile\&.vignetteCurve"

.PP
Definition at line \fB53\fP of file \fBSceneLightProfile\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
