.TH "SceneProfile" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SceneProfile
.SH SYNOPSIS
.br
.PP
.PP
Inherits ScriptableObject\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBSceneProfile\fP \fBLoad\fP (string id)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBSceneGlobalProfile\fP \fBglobal\fP"
.br
.ti -1c
.RI "OverlayProfile \fBoverlay\fP"
.br
.ti -1c
.RI "\fBSceneLightProfile\fP \fBlight\fP"
.br
.ti -1c
.RI "\fBSceneColorProfile\fP \fBcolor\fP"
.br
.ti -1c
.RI "Material \fBmatOverlay\fP"
.br
.ti -1c
.RI "Material \fBmatGrading\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB6\fP of file \fBSceneProfile\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "static \fBSceneProfile\fP SceneProfile\&.Load (string id)\fR [static]\fP"

.PP
Definition at line \fB9\fP of file \fBSceneProfile\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBSceneColorProfile\fP SceneProfile\&.color"

.PP
Definition at line \fB24\fP of file \fBSceneProfile\&.cs\fP\&.
.SS "\fBSceneGlobalProfile\fP SceneProfile\&.global"

.PP
Definition at line \fB15\fP of file \fBSceneProfile\&.cs\fP\&.
.SS "\fBSceneLightProfile\fP SceneProfile\&.light"

.PP
Definition at line \fB21\fP of file \fBSceneProfile\&.cs\fP\&.
.SS "Material SceneProfile\&.matGrading"

.PP
Definition at line \fB30\fP of file \fBSceneProfile\&.cs\fP\&.
.SS "Material SceneProfile\&.matOverlay"

.PP
Definition at line \fB27\fP of file \fBSceneProfile\&.cs\fP\&.
.SS "OverlayProfile SceneProfile\&.overlay"

.PP
Definition at line \fB18\fP of file \fBSceneProfile\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
