.TH "Scene" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Scene
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBEMono\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBMode\fP { \fBNone\fP, \fBTitle\fP, \fBStartGame\fP, \fBZone\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBInit\fP (Scene\&.Mode newMode)"
.br
.ti -1c
.RI "void \fBOnKillGame\fP ()"
.br
.ti -1c
.RI "void \fBClear\fP ()"
.br
.ti -1c
.RI "unsafe void \fBOnUpdate\fP ()"
.br
.ti -1c
.RI "void \fBOnLateUpdate\fP ()"
.br
.ti -1c
.RI "void \fBUpdateCursor\fP ()"
.br
.ti -1c
.RI "void \fBUpdateTimeRatio\fP ()"
.br
.ti -1c
.RI "void \fBOnChangeHour\fP ()"
.br
.ti -1c
.RI "void \fBRefreshBG\fP ()"
.br
.ti -1c
.RI "void \fBFocusAndPause\fP (\fBPoint\fP pos, int a)"
.br
.ti -1c
.RI "void \fBApplyZoneConfig\fP ()"
.br
.ti -1c
.RI "void \fBOnToggle\fP ()"
.br
.ti -1c
.RI "void \fBToggleShowRoof\fP ()"
.br
.ti -1c
.RI "void \fBToggleLight\fP ()"
.br
.ti -1c
.RI "void \fBToggleSnapFreePos\fP ()"
.br
.ti -1c
.RI "void \fBToggleFreePos\fP ()"
.br
.ti -1c
.RI "void \fBToggleShowWall\fP ()"
.br
.ti -1c
.RI "void \fBToggleRoof\fP ()"
.br
.ti -1c
.RI "void \fBToggleSlope\fP ()"
.br
.ti -1c
.RI "void \fBToggleTilt\fP ()"
.br
.ti -1c
.RI "void \fBToggleHighlightAct\fP ()"
.br
.ti -1c
.RI "void \fBToggleAreaHighlight\fP ()"
.br
.ti -1c
.RI "void \fBToggleBirdView\fP (bool sound=true)"
.br
.ti -1c
.RI "void \fBToggleBalloon\fP ()"
.br
.ti -1c
.RI "void \fBToggleMuteBGM\fP ()"
.br
.ti -1c
.RI "void \fBRebuildActorEx\fP ()"
.br
.ti -1c
.RI "void \fBRefreshActorEx\fP ()"
.br
.ti -1c
.RI "void \fBClearActorEx\fP ()"
.br
.ti -1c
.RI "void \fBAddActorEx\fP (\fBCard\fP c, Action< \fBActorEx\fP > onBeforeSetOwner=null)"
.br
.ti -1c
.RI "void \fBRemoveActorEx\fP (\fBCard\fP c)"
.br
.ti -1c
.RI "void \fBInitPass\fP ()"
.br
.ti -1c
.RI "void \fBDrawPass\fP ()"
.br
.ti -1c
.RI "void \fBRefreshSync\fP ()"
.br
.ti -1c
.RI "Transform \fBLoadPrefab\fP (string id)"
.br
.ti -1c
.RI "void \fBDestroyPrefabs\fP ()"
.br
.ti -1c
.RI "void \fBDestroyPrefab\fP (string id)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Vector2[] \fBtest\fP"
.br
.ti -1c
.RI "Transform \fBtransFocus\fP"
.br
.ti -1c
.RI "Transform \fBtransBlizzard\fP"
.br
.ti -1c
.RI "Transform \fBtransAudio\fP"
.br
.ti -1c
.RI "AudioListener \fBaudioListener\fP"
.br
.ti -1c
.RI "Camera \fBcam\fP"
.br
.ti -1c
.RI "Camera \fBcamTreasure\fP"
.br
.ti -1c
.RI "\fBCameraSupport\fP \fBcamSupport\fP"
.br
.ti -1c
.RI "\fBVFX\fP \fBfirefly\fP"
.br
.ti -1c
.RI "\fBVFX\fP \fBfireflyNight\fP"
.br
.ti -1c
.RI "\fBVFX\fP \fBstar\fP"
.br
.ti -1c
.RI "ParticleSystem \fBrain\fP"
.br
.ti -1c
.RI "ParticleSystem \fBsnow\fP"
.br
.ti -1c
.RI "ParticleSystem \fBether\fP"
.br
.ti -1c
.RI "ParticleSystem \fBgodray\fP"
.br
.ti -1c
.RI "ParticleSystem \fBgodrayDust\fP"
.br
.ti -1c
.RI "ParticleSystem \fBblossom\fP"
.br
.ti -1c
.RI "ParticleSystem \fBetherBlossom\fP"
.br
.ti -1c
.RI "ParticleSystem[] \fBblossoms\fP"
.br
.ti -1c
.RI "ParticleSystem[] \fBblizzards\fP"
.br
.ti -1c
.RI "FlockController \fBflock\fP"
.br
.ti -1c
.RI "MeshRenderer \fBskyBG\fP"
.br
.ti -1c
.RI "MeshRenderer \fBskyPlane\fP"
.br
.ti -1c
.RI "\fBSceneProfile\fP \fBprofile\fP"
.br
.ti -1c
.RI "CameraFilterPack_Atmosphere_Rain \fBfilterRain\fP"
.br
.ti -1c
.RI "\fBActionMode\fP \fBactionMode\fP"
.br
.ti -1c
.RI "SoundSource \fBsfxRain\fP"
.br
.ti -1c
.RI "SoundSource \fBsfxWind\fP"
.br
.ti -1c
.RI "SoundSource \fBsfxSea\fP"
.br
.ti -1c
.RI "SoundSource \fBsfxFire\fP"
.br
.ti -1c
.RI "SoundSource \fBsfxEther\fP"
.br
.ti -1c
.RI "\fBGameScreen\fP \fBscreenElin\fP"
.br
.ti -1c
.RI "\fBGameScreenElona\fP \fBscreenElona\fP"
.br
.ti -1c
.RI "\fBGameScreenNoMap\fP \fBscreenNoMap\fP"
.br
.ti -1c
.RI "PopperManager \fBpopper\fP"
.br
.ti -1c
.RI "\fBEloMapActor\fP \fBelomapActor\fP"
.br
.ti -1c
.RI "SpriteRenderer \fBsrTarget\fP"
.br
.ti -1c
.RI "Tileset \fBtileset\fP"
.br
.ti -1c
.RI "ParticleSystem \fBpsFoot\fP"
.br
.ti -1c
.RI "ParticleSystem \fBpsSmoke\fP"
.br
.ti -1c
.RI "ParticleSystem \fBpsRainSplash\fP"
.br
.ti -1c
.RI "ParticleSystem \fBpsRainSplashWater\fP"
.br
.ti -1c
.RI "\fBMeshPass\fP[] \fBpasses\fP"
.br
.ti -1c
.RI "\fBGameSetting\&.RenderSetting\&.MapBGSetting\fP \fBbg\fP"
.br
.ti -1c
.RI "Scene\&.Mode \fBmode\fP"
.br
.ti -1c
.RI "float \fBtimeRatio\fP"
.br
.ti -1c
.RI "List< GameObject > \fBloadedPrefabs\fP = new List<GameObject>()"
.br
.ti -1c
.RI "\fBPointTarget\fP \fBmouseTarget\fP = new \fBPointTarget\fP()"
.br
.ti -1c
.RI "List< \fBISyncScreen\fP > \fBsyncList\fP = new List<\fBISyncScreen\fP>()"
.br
.ti -1c
.RI "bool \fBpaused\fP"
.br
.ti -1c
.RI "long \fBsyncFrame\fP"
.br
.ti -1c
.RI "Dictionary< \fBCard\fP, \fBActorEx\fP > \fBdictActorEx\fP = new Dictionary<\fBCard\fP, \fBActorEx\fP>()"
.br
.ti -1c
.RI "bool \fBhideBalloon\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static bool \fBisAnnounced\fP"
.br
.ti -1c
.RI "static \fBPoint\fP \fBHitPoint\fP = new \fBPoint\fP()"
.br
.ti -1c
.RI "static \fBPoint\fP \fBClickPoint\fP = new \fBPoint\fP()"
.br
.ti -1c
.RI "static bool \fBskipAnime\fP"
.br
.in -1c

Static Public Attributes inherited from \fBEMono\fP
.in +1c
.ti -1c
.RI "static \fBCore\fP \fBcore\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBEloMap\fP \fBelomap\fP\fR [get]\fP"
.br
.in -1c

Properties inherited from \fBEMono\fP
.in +1c
.ti -1c
.RI "static \fBGame\fP \fBgame\fP\fR [get]\fP"
.br
.ti -1c
.RI "static bool \fBAdvMode\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBPlayer\fP \fBplayer\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBChara\fP \fBpc\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBUI\fP \fBui\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBMap\fP \fB_map\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBZone\fP \fB_zone\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranchOrHomeBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFaction\fP \fBHome\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBScene\fP \fBscene\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBBaseGameScreen\fP \fBscreen\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameSetting\fP \fBsetting\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameData\fP \fBgamedata\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBColorProfile\fP \fBColors\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBWorld\fP \fBworld\fP\fR [get]\fP"
.br
.ti -1c
.RI "static SoundManager \fBSound\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBsources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBeditorSources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBCoreDebug\fP \fBdebug\fP\fR [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Static Public Member Functions inherited from \fBEMono\fP
.in +1c
.ti -1c
.RI "static int \fBrnd\fP (int a)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB9\fP of file \fBScene\&.cs\fP\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "enum Scene\&.Mode"

.PP
Definition at line \fB1164\fP of file \fBScene\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Scene\&.AddActorEx (\fBCard\fP c, Action< \fBActorEx\fP > onBeforeSetOwner = \fRnull\fP)"

.PP
Definition at line \fB844\fP of file \fBScene\&.cs\fP\&.
.SS "void Scene\&.ApplyZoneConfig ()"

.PP
Definition at line \fB649\fP of file \fBScene\&.cs\fP\&.
.SS "void Scene\&.Clear ()"

.PP
Definition at line \fB188\fP of file \fBScene\&.cs\fP\&.
.SS "void Scene\&.ClearActorEx ()"

.PP
Definition at line \fB834\fP of file \fBScene\&.cs\fP\&.
.SS "void Scene\&.DestroyPrefab (string id)"

.PP
Definition at line \fB956\fP of file \fBScene\&.cs\fP\&.
.SS "void Scene\&.DestroyPrefabs ()"

.PP
Definition at line \fB946\fP of file \fBScene\&.cs\fP\&.
.SS "void Scene\&.DrawPass ()"

.PP
Definition at line \fB895\fP of file \fBScene\&.cs\fP\&.
.SS "void Scene\&.FocusAndPause (\fBPoint\fP pos, int a)"

.PP
Definition at line \fB636\fP of file \fBScene\&.cs\fP\&.
.SS "void Scene\&.Init (Scene\&.Mode newMode)"

.PP
Definition at line \fB28\fP of file \fBScene\&.cs\fP\&.
.SS "void Scene\&.InitPass ()"

.PP
Definition at line \fB873\fP of file \fBScene\&.cs\fP\&.
.SS "Transform Scene\&.LoadPrefab (string id)"

.PP
Definition at line \fB937\fP of file \fBScene\&.cs\fP\&.
.SS "void Scene\&.OnChangeHour ()"

.PP
Definition at line \fB599\fP of file \fBScene\&.cs\fP\&.
.SS "void Scene\&.OnKillGame ()"

.PP
Definition at line \fB175\fP of file \fBScene\&.cs\fP\&.
.SS "void Scene\&.OnLateUpdate ()"

.PP
Definition at line \fB567\fP of file \fBScene\&.cs\fP\&.
.SS "void Scene\&.OnToggle ()"

.PP
Definition at line \fB682\fP of file \fBScene\&.cs\fP\&.
.SS "unsafe void Scene\&.OnUpdate ()"

.PP
Definition at line \fB201\fP of file \fBScene\&.cs\fP\&.
.SS "void Scene\&.RebuildActorEx ()"

.PP
Definition at line \fB812\fP of file \fBScene\&.cs\fP\&.
.SS "void Scene\&.RefreshActorEx ()"

.PP
Definition at line \fB824\fP of file \fBScene\&.cs\fP\&.
.SS "void Scene\&.RefreshBG ()"

.PP
Definition at line \fB621\fP of file \fBScene\&.cs\fP\&.
.SS "void Scene\&.RefreshSync ()"

.PP
Definition at line \fB921\fP of file \fBScene\&.cs\fP\&.
.SS "void Scene\&.RemoveActorEx (\fBCard\fP c)"

.PP
Definition at line \fB861\fP of file \fBScene\&.cs\fP\&.
.SS "void Scene\&.ToggleAreaHighlight ()"

.PP
Definition at line \fB772\fP of file \fBScene\&.cs\fP\&.
.SS "void Scene\&.ToggleBalloon ()"

.PP
Definition at line \fB791\fP of file \fBScene\&.cs\fP\&.
.SS "void Scene\&.ToggleBirdView (bool sound = \fRtrue\fP)"

.PP
Definition at line \fB779\fP of file \fBScene\&.cs\fP\&.
.SS "void Scene\&.ToggleFreePos ()"

.PP
Definition at line \fB716\fP of file \fBScene\&.cs\fP\&.
.SS "void Scene\&.ToggleHighlightAct ()"

.PP
Definition at line \fB765\fP of file \fBScene\&.cs\fP\&.
.SS "void Scene\&.ToggleLight ()"

.PP
Definition at line \fB697\fP of file \fBScene\&.cs\fP\&.
.SS "void Scene\&.ToggleMuteBGM ()"

.PP
Definition at line \fB800\fP of file \fBScene\&.cs\fP\&.
.SS "void Scene\&.ToggleRoof ()"

.PP
Definition at line \fB735\fP of file \fBScene\&.cs\fP\&.
.SS "void Scene\&.ToggleShowRoof ()"

.PP
Definition at line \fB690\fP of file \fBScene\&.cs\fP\&.
.SS "void Scene\&.ToggleShowWall ()"

.PP
Definition at line \fB728\fP of file \fBScene\&.cs\fP\&.
.SS "void Scene\&.ToggleSlope ()"

.PP
Definition at line \fB742\fP of file \fBScene\&.cs\fP\&.
.SS "void Scene\&.ToggleSnapFreePos ()"

.PP
Definition at line \fB704\fP of file \fBScene\&.cs\fP\&.
.SS "void Scene\&.ToggleTilt ()"

.PP
Definition at line \fB750\fP of file \fBScene\&.cs\fP\&.
.SS "void Scene\&.UpdateCursor ()"

.PP
Definition at line \fB574\fP of file \fBScene\&.cs\fP\&.
.SS "void Scene\&.UpdateTimeRatio ()"

.PP
Definition at line \fB588\fP of file \fBScene\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBActionMode\fP Scene\&.actionMode"

.PP
Definition at line \fB1074\fP of file \fBScene\&.cs\fP\&.
.SS "AudioListener Scene\&.audioListener"

.PP
Definition at line \fB1011\fP of file \fBScene\&.cs\fP\&.
.SS "\fBGameSetting\&.RenderSetting\&.MapBGSetting\fP Scene\&.bg"

.PP
Definition at line \fB1129\fP of file \fBScene\&.cs\fP\&.
.SS "ParticleSystem [] Scene\&.blizzards"

.PP
Definition at line \fB1056\fP of file \fBScene\&.cs\fP\&.
.SS "ParticleSystem Scene\&.blossom"

.PP
Definition at line \fB1047\fP of file \fBScene\&.cs\fP\&.
.SS "ParticleSystem [] Scene\&.blossoms"

.PP
Definition at line \fB1053\fP of file \fBScene\&.cs\fP\&.
.SS "Camera Scene\&.cam"

.PP
Definition at line \fB1014\fP of file \fBScene\&.cs\fP\&.
.SS "\fBCameraSupport\fP Scene\&.camSupport"

.PP
Definition at line \fB1020\fP of file \fBScene\&.cs\fP\&.
.SS "Camera Scene\&.camTreasure"

.PP
Definition at line \fB1017\fP of file \fBScene\&.cs\fP\&.
.SS "\fBPoint\fP Scene\&.ClickPoint = new \fBPoint\fP()\fR [static]\fP"

.PP
Definition at line \fB996\fP of file \fBScene\&.cs\fP\&.
.SS "Dictionary<\fBCard\fP, \fBActorEx\fP> Scene\&.dictActorEx = new Dictionary<\fBCard\fP, \fBActorEx\fP>()"

.PP
Definition at line \fB1157\fP of file \fBScene\&.cs\fP\&.
.SS "\fBEloMapActor\fP Scene\&.elomapActor"

.PP
Definition at line \fB1104\fP of file \fBScene\&.cs\fP\&.
.SS "ParticleSystem Scene\&.ether"

.PP
Definition at line \fB1038\fP of file \fBScene\&.cs\fP\&.
.SS "ParticleSystem Scene\&.etherBlossom"

.PP
Definition at line \fB1050\fP of file \fBScene\&.cs\fP\&.
.SS "CameraFilterPack_Atmosphere_Rain Scene\&.filterRain"

.PP
Definition at line \fB1071\fP of file \fBScene\&.cs\fP\&.
.SS "\fBVFX\fP Scene\&.firefly"

.PP
Definition at line \fB1023\fP of file \fBScene\&.cs\fP\&.
.SS "\fBVFX\fP Scene\&.fireflyNight"

.PP
Definition at line \fB1026\fP of file \fBScene\&.cs\fP\&.
.SS "FlockController Scene\&.flock"

.PP
Definition at line \fB1059\fP of file \fBScene\&.cs\fP\&.
.SS "ParticleSystem Scene\&.godray"

.PP
Definition at line \fB1041\fP of file \fBScene\&.cs\fP\&.
.SS "ParticleSystem Scene\&.godrayDust"

.PP
Definition at line \fB1044\fP of file \fBScene\&.cs\fP\&.
.SS "bool Scene\&.hideBalloon"

.PP
Definition at line \fB1161\fP of file \fBScene\&.cs\fP\&.
.SS "\fBPoint\fP Scene\&.HitPoint = new \fBPoint\fP()\fR [static]\fP"

.PP
Definition at line \fB993\fP of file \fBScene\&.cs\fP\&.
.SS "bool Scene\&.isAnnounced\fR [static]\fP"

.PP
Definition at line \fB990\fP of file \fBScene\&.cs\fP\&.
.SS "List<GameObject> Scene\&.loadedPrefabs = new List<GameObject>()"

.PP
Definition at line \fB1141\fP of file \fBScene\&.cs\fP\&.
.SS "Scene\&.Mode Scene\&.mode"

.PP
Definition at line \fB1133\fP of file \fBScene\&.cs\fP\&.
.SS "\fBPointTarget\fP Scene\&.mouseTarget = new \fBPointTarget\fP()"

.PP
Definition at line \fB1144\fP of file \fBScene\&.cs\fP\&.
.SS "\fBMeshPass\fP [] Scene\&.passes"

.PP
Definition at line \fB1125\fP of file \fBScene\&.cs\fP\&.
.SS "bool Scene\&.paused"

.PP
Definition at line \fB1151\fP of file \fBScene\&.cs\fP\&.
.SS "PopperManager Scene\&.popper"

.PP
Definition at line \fB1101\fP of file \fBScene\&.cs\fP\&.
.SS "\fBSceneProfile\fP Scene\&.profile"

.PP
Definition at line \fB1068\fP of file \fBScene\&.cs\fP\&.
.SS "ParticleSystem Scene\&.psFoot"

.PP
Definition at line \fB1113\fP of file \fBScene\&.cs\fP\&.
.SS "ParticleSystem Scene\&.psRainSplash"

.PP
Definition at line \fB1119\fP of file \fBScene\&.cs\fP\&.
.SS "ParticleSystem Scene\&.psRainSplashWater"

.PP
Definition at line \fB1122\fP of file \fBScene\&.cs\fP\&.
.SS "ParticleSystem Scene\&.psSmoke"

.PP
Definition at line \fB1116\fP of file \fBScene\&.cs\fP\&.
.SS "ParticleSystem Scene\&.rain"

.PP
Definition at line \fB1032\fP of file \fBScene\&.cs\fP\&.
.SS "\fBGameScreen\fP Scene\&.screenElin"

.PP
Definition at line \fB1092\fP of file \fBScene\&.cs\fP\&.
.SS "\fBGameScreenElona\fP Scene\&.screenElona"

.PP
Definition at line \fB1095\fP of file \fBScene\&.cs\fP\&.
.SS "\fBGameScreenNoMap\fP Scene\&.screenNoMap"

.PP
Definition at line \fB1098\fP of file \fBScene\&.cs\fP\&.
.SS "SoundSource Scene\&.sfxEther"

.PP
Definition at line \fB1089\fP of file \fBScene\&.cs\fP\&.
.SS "SoundSource Scene\&.sfxFire"

.PP
Definition at line \fB1086\fP of file \fBScene\&.cs\fP\&.
.SS "SoundSource Scene\&.sfxRain"

.PP
Definition at line \fB1077\fP of file \fBScene\&.cs\fP\&.
.SS "SoundSource Scene\&.sfxSea"

.PP
Definition at line \fB1083\fP of file \fBScene\&.cs\fP\&.
.SS "SoundSource Scene\&.sfxWind"

.PP
Definition at line \fB1080\fP of file \fBScene\&.cs\fP\&.
.SS "bool Scene\&.skipAnime\fR [static]\fP"

.PP
Definition at line \fB999\fP of file \fBScene\&.cs\fP\&.
.SS "MeshRenderer Scene\&.skyBG"

.PP
Definition at line \fB1062\fP of file \fBScene\&.cs\fP\&.
.SS "MeshRenderer Scene\&.skyPlane"

.PP
Definition at line \fB1065\fP of file \fBScene\&.cs\fP\&.
.SS "ParticleSystem Scene\&.snow"

.PP
Definition at line \fB1035\fP of file \fBScene\&.cs\fP\&.
.SS "SpriteRenderer Scene\&.srTarget"

.PP
Definition at line \fB1107\fP of file \fBScene\&.cs\fP\&.
.SS "\fBVFX\fP Scene\&.star"

.PP
Definition at line \fB1029\fP of file \fBScene\&.cs\fP\&.
.SS "long Scene\&.syncFrame"

.PP
Definition at line \fB1154\fP of file \fBScene\&.cs\fP\&.
.SS "List<\fBISyncScreen\fP> Scene\&.syncList = new List<\fBISyncScreen\fP>()"

.PP
Definition at line \fB1147\fP of file \fBScene\&.cs\fP\&.
.SS "Vector2 [] Scene\&.test"

.PP
Definition at line \fB987\fP of file \fBScene\&.cs\fP\&.
.SS "Tileset Scene\&.tileset"

.PP
Definition at line \fB1110\fP of file \fBScene\&.cs\fP\&.
.SS "float Scene\&.timeRatio"

.PP
Definition at line \fB1137\fP of file \fBScene\&.cs\fP\&.
.SS "Transform Scene\&.transAudio"

.PP
Definition at line \fB1008\fP of file \fBScene\&.cs\fP\&.
.SS "Transform Scene\&.transBlizzard"

.PP
Definition at line \fB1005\fP of file \fBScene\&.cs\fP\&.
.SS "Transform Scene\&.transFocus"

.PP
Definition at line \fB1002\fP of file \fBScene\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "\fBEloMap\fP Scene\&.elomap\fR [get]\fP"

.PP
Definition at line \fB13\fP of file \fBScene\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
