.TH "Schedule" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Schedule
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBItem\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "List< \fBSchedule\&.Item\fP > \fBlist\fP = new List<\fBSchedule\&.Item\fP>()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB6\fP of file \fBSchedule\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "List<\fBSchedule\&.Item\fP> Schedule\&.list = new List<\fBSchedule\&.Item\fP>()"

.PP
Definition at line \fB10\fP of file \fBSchedule\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
