.TH "ScreenFlash" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ScreenFlash
.SH SYNOPSIS
.br
.PP
.PP
Inherits ScriptableObject\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBPlay\fP (float mtp=1f)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBReset\fP ()"
.br
.ti -1c
.RI "static void \fBPlay\fP (string id, float mtp=1f)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Color \fBcolor\fP"
.br
.ti -1c
.RI "AnimationCurve \fBease\fP"
.br
.ti -1c
.RI "float \fBduration\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static Color \fBcurrentColor\fP"
.br
.ti -1c
.RI "static Color \fBclearColor\fP = new Color(0f, 0f, 0f, 0f)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB8\fP of file \fBScreenFlash\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void ScreenFlash\&.Play (float mtp = \fR1f\fP)"

.PP
Definition at line \fB24\fP of file \fBScreenFlash\&.cs\fP\&.
.SS "static void ScreenFlash\&.Play (string id, float mtp = \fR1f\fP)\fR [static]\fP"

.PP
Definition at line \fB18\fP of file \fBScreenFlash\&.cs\fP\&.
.SS "static void ScreenFlash\&.Reset ()\fR [static]\fP"

.PP
Definition at line \fB11\fP of file \fBScreenFlash\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "Color ScreenFlash\&.clearColor = new Color(0f, 0f, 0f, 0f)\fR [static]\fP"

.PP
Definition at line \fB43\fP of file \fBScreenFlash\&.cs\fP\&.
.SS "Color ScreenFlash\&.color"

.PP
Definition at line \fB46\fP of file \fBScreenFlash\&.cs\fP\&.
.SS "Color ScreenFlash\&.currentColor\fR [static]\fP"

.PP
Definition at line \fB40\fP of file \fBScreenFlash\&.cs\fP\&.
.SS "float ScreenFlash\&.duration"

.PP
Definition at line \fB52\fP of file \fBScreenFlash\&.cs\fP\&.
.SS "AnimationCurve ScreenFlash\&.ease"

.PP
Definition at line \fB49\fP of file \fBScreenFlash\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
