.TH "SerializableDateTime" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SerializableDateTime
.SH SYNOPSIS
.br
.PP
.PP
Inherits IComparable< SerializableDateTime >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSerializableDateTime\fP (DateTime dateTime)"
.br
.ti -1c
.RI "int \fBCompareTo\fP (\fBSerializableDateTime\fP other)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "DateTime \fBm_dateTime\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "DateTime \fBDateTime\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB6\fP of file \fBSerializableDateTime\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SerializableDateTime\&.SerializableDateTime (DateTime dateTime)"

.PP
Definition at line \fB24\fP of file \fBSerializableDateTime\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "int SerializableDateTime\&.CompareTo (\fBSerializableDateTime\fP other)"

.PP
Definition at line \fB32\fP of file \fBSerializableDateTime\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "DateTime SerializableDateTime\&.m_dateTime"

.PP
Definition at line \fB49\fP of file \fBSerializableDateTime\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "DateTime SerializableDateTime\&.DateTime\fR [get]\fP"

.PP
Definition at line \fB10\fP of file \fBSerializableDateTime\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
