.TH "SerializedCards.Data" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SerializedCards.Data
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBEClass\fP\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int[] \fBints\fP = new int[30]"
.br
.ti -1c
.RI "string[] \fBstrs\fP = new string[10]"
.br
.ti -1c
.RI "Dictionary< int, object > \fBobj\fP"
.br
.ti -1c
.RI "Dictionary< int, string > \fBcstr\fP"
.br
.ti -1c
.RI "BitArray32 \fB_bits1\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBidDyeMat\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "int \fBidV\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "int \fBidMat\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "int \fBx\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "int \fBz\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "int \fBdir\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "int \fBplaceState\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "int \fBaltitude\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "int \fBfx\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "int \fBfy\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "int \fBlightColor\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "int \fBbits1\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "int \fBtile\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "int \fBrefVal\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "int \fBidSkin\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "int \fBidBacker\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "int \fBbits2\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "int \fBuidEditor\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "int \fBlv\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "int \fBelement\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "string \fBid\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "string \fBidEditor\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "string \fBidTrait\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "string \fBtags\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "string \fBidRender\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "string \fBtraitVals\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "string \fBidRefCard\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "string \fBidDeity\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "bool \fBisDead\fP\fR [get, set]\fP"
.br
.in -1c

Properties inherited from \fBEClass\fP
.in +1c
.ti -1c
.RI "static \fBGame\fP \fBgame\fP\fR [get]\fP"
.br
.ti -1c
.RI "static bool \fBAdvMode\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBPlayer\fP \fBplayer\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBChara\fP \fBpc\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBUI\fP \fBui\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBMap\fP \fB_map\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBZone\fP \fB_zone\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranchOrHomeBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFaction\fP \fBHome\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFaction\fP \fBWilds\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBScene\fP \fBscene\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBBaseGameScreen\fP \fBscreen\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameSetting\fP \fBsetting\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameData\fP \fBgamedata\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBColorProfile\fP \fBColors\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBWorld\fP \fBworld\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBsources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBeditorSources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static SoundManager \fBSound\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBCoreDebug\fP \fBdebug\fP\fR [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Static Public Member Functions inherited from \fBEClass\fP
.in +1c
.ti -1c
.RI "static int \fBrnd\fP (int a)"
.br
.ti -1c
.RI "static int \fBcurve\fP (int a, int start, int step, int rate=75)"
.br
.ti -1c
.RI "static int \fBrndHalf\fP (int a)"
.br
.ti -1c
.RI "static float \fBrndf\fP (float a)"
.br
.ti -1c
.RI "static int \fBrndSqrt\fP (int a)"
.br
.ti -1c
.RI "static void \fBWait\fP (float a, \fBCard\fP c)"
.br
.ti -1c
.RI "static void \fBWait\fP (float a, \fBPoint\fP p)"
.br
.ti -1c
.RI "static int \fBBigger\fP (int a, int b)"
.br
.ti -1c
.RI "static int \fBSmaller\fP (int a, int b)"
.br
.in -1c

Static Public Attributes inherited from \fBEClass\fP
.in +1c
.ti -1c
.RI "static \fBCore\fP \fBcore\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB405\fP of file \fBSerializedCards\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "BitArray32 SerializedCards\&.Data\&._bits1"

.PP
Definition at line \fB859\fP of file \fBSerializedCards\&.cs\fP\&.
.SS "Dictionary<int, string> SerializedCards\&.Data\&.cstr"

.PP
Definition at line \fB856\fP of file \fBSerializedCards\&.cs\fP\&.
.SS "int [] SerializedCards\&.Data\&.ints = new int[30]"

.PP
Definition at line \fB844\fP of file \fBSerializedCards\&.cs\fP\&.
.SS "Dictionary<int, object> SerializedCards\&.Data\&.obj"

.PP
Definition at line \fB852\fP of file \fBSerializedCards\&.cs\fP\&.
.SS "string [] SerializedCards\&.Data\&.strs = new string[10]"

.PP
Definition at line \fB848\fP of file \fBSerializedCards\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "int SerializedCards\&.Data\&.altitude\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB515\fP of file \fBSerializedCards\&.cs\fP\&.
.SS "int SerializedCards\&.Data\&.bits1\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB575\fP of file \fBSerializedCards\&.cs\fP\&.
.SS "int SerializedCards\&.Data\&.bits2\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB650\fP of file \fBSerializedCards\&.cs\fP\&.
.SS "int SerializedCards\&.Data\&.dir\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB485\fP of file \fBSerializedCards\&.cs\fP\&.
.SS "int SerializedCards\&.Data\&.element\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB695\fP of file \fBSerializedCards\&.cs\fP\&.
.SS "int SerializedCards\&.Data\&.fx\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB530\fP of file \fBSerializedCards\&.cs\fP\&.
.SS "int SerializedCards\&.Data\&.fy\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB545\fP of file \fBSerializedCards\&.cs\fP\&.
.SS "string SerializedCards\&.Data\&.id\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB710\fP of file \fBSerializedCards\&.cs\fP\&.
.SS "int SerializedCards\&.Data\&.idBacker\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB635\fP of file \fBSerializedCards\&.cs\fP\&.
.SS "string SerializedCards\&.Data\&.idDeity\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB815\fP of file \fBSerializedCards\&.cs\fP\&.
.SS "int SerializedCards\&.Data\&.idDyeMat\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB410\fP of file \fBSerializedCards\&.cs\fP\&.
.SS "string SerializedCards\&.Data\&.idEditor\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB725\fP of file \fBSerializedCards\&.cs\fP\&.
.SS "int SerializedCards\&.Data\&.idMat\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB440\fP of file \fBSerializedCards\&.cs\fP\&.
.SS "string SerializedCards\&.Data\&.idRefCard\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB800\fP of file \fBSerializedCards\&.cs\fP\&.
.SS "string SerializedCards\&.Data\&.idRender\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB770\fP of file \fBSerializedCards\&.cs\fP\&.
.SS "int SerializedCards\&.Data\&.idSkin\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB620\fP of file \fBSerializedCards\&.cs\fP\&.
.SS "string SerializedCards\&.Data\&.idTrait\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB740\fP of file \fBSerializedCards\&.cs\fP\&.
.SS "int SerializedCards\&.Data\&.idV\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB425\fP of file \fBSerializedCards\&.cs\fP\&.
.SS "bool SerializedCards\&.Data\&.isDead\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB830\fP of file \fBSerializedCards\&.cs\fP\&.
.SS "int SerializedCards\&.Data\&.lightColor\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB560\fP of file \fBSerializedCards\&.cs\fP\&.
.SS "int SerializedCards\&.Data\&.lv\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB680\fP of file \fBSerializedCards\&.cs\fP\&.
.SS "int SerializedCards\&.Data\&.placeState\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB500\fP of file \fBSerializedCards\&.cs\fP\&.
.SS "int SerializedCards\&.Data\&.refVal\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB605\fP of file \fBSerializedCards\&.cs\fP\&.
.SS "string SerializedCards\&.Data\&.tags\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB755\fP of file \fBSerializedCards\&.cs\fP\&.
.SS "int SerializedCards\&.Data\&.tile\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB590\fP of file \fBSerializedCards\&.cs\fP\&.
.SS "string SerializedCards\&.Data\&.traitVals\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB785\fP of file \fBSerializedCards\&.cs\fP\&.
.SS "int SerializedCards\&.Data\&.uidEditor\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB665\fP of file \fBSerializedCards\&.cs\fP\&.
.SS "int SerializedCards\&.Data\&.x\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB455\fP of file \fBSerializedCards\&.cs\fP\&.
.SS "int SerializedCards\&.Data\&.z\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB470\fP of file \fBSerializedCards\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
