.TH "ShadowData" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ShadowData
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBEScriptable\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBItem\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "List< \fBShadowData\&.Item\fP > \fBitems\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static \fBShadowData\fP \fBInstance\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Static Public Member Functions inherited from \fBEScriptable\fP
.in +1c
.ti -1c
.RI "static int \fBrnd\fP (int a)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB5\fP of file \fBShadowData\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBShadowData\fP ShadowData\&.Instance\fR [static]\fP"

.PP
Definition at line \fB8\fP of file \fBShadowData\&.cs\fP\&.
.SS "List<\fBShadowData\&.Item\fP> ShadowData\&.items"

.PP
Definition at line \fB11\fP of file \fBShadowData\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
