.TH "ShopTransaction.Item" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ShopTransaction.Item
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBThing\fP \fBthing\fP"
.br
.ti -1c
.RI "int \fBnum\fP"
.br
.ti -1c
.RI "int \fBprice\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB225\fP of file \fBShopTransaction\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int ShopTransaction\&.Item\&.num"

.PP
Definition at line \fB231\fP of file \fBShopTransaction\&.cs\fP\&.
.SS "int ShopTransaction\&.Item\&.price"

.PP
Definition at line \fB234\fP of file \fBShopTransaction\&.cs\fP\&.
.SS "\fBThing\fP ShopTransaction\&.Item\&.thing"

.PP
Definition at line \fB228\fP of file \fBShopTransaction\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
