.TH "ShopTransaction" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ShopTransaction
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBEClass\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBItem\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBLog\fP ()"
.br
.ti -1c
.RI "bool \fBHasBought\fP (\fBThing\fP t)"
.br
.ti -1c
.RI "bool \fBCanSellBack\fP (\fBThing\fP t, int num=\-1)"
.br
.ti -1c
.RI "void \fBProcess\fP (\fBThing\fP t, int n, bool sell)"
.br
.ti -1c
.RI "int \fBGetPrice\fP (\fBThing\fP t, int n, bool sell)"
.br
.ti -1c
.RI "void \fBOnEndTransaction\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBInvOwner\fP \fBtrader\fP"
.br
.ti -1c
.RI "List< \fBShopTransaction\&.Item\fP > \fBbought\fP = new List<\fBShopTransaction\&.Item\fP>()"
.br
.ti -1c
.RI "List< \fBShopTransaction\&.Item\fP > \fBsold\fP = new List<\fBShopTransaction\&.Item\fP>()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static \fBShopTransaction\fP \fBcurrent\fP"
.br
.in -1c

Static Public Attributes inherited from \fBEClass\fP
.in +1c
.ti -1c
.RI "static \fBCore\fP \fBcore\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Static Public Member Functions inherited from \fBEClass\fP
.in +1c
.ti -1c
.RI "static int \fBrnd\fP (int a)"
.br
.ti -1c
.RI "static int \fBcurve\fP (int a, int start, int step, int rate=75)"
.br
.ti -1c
.RI "static int \fBrndHalf\fP (int a)"
.br
.ti -1c
.RI "static float \fBrndf\fP (float a)"
.br
.ti -1c
.RI "static int \fBrndSqrt\fP (int a)"
.br
.ti -1c
.RI "static void \fBWait\fP (float a, \fBCard\fP c)"
.br
.ti -1c
.RI "static void \fBWait\fP (float a, \fBPoint\fP p)"
.br
.ti -1c
.RI "static int \fBBigger\fP (int a, int b)"
.br
.ti -1c
.RI "static int \fBSmaller\fP (int a, int b)"
.br
.in -1c

Properties inherited from \fBEClass\fP
.in +1c
.ti -1c
.RI "static \fBGame\fP \fBgame\fP\fR [get]\fP"
.br
.ti -1c
.RI "static bool \fBAdvMode\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBPlayer\fP \fBplayer\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBChara\fP \fBpc\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBUI\fP \fBui\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBMap\fP \fB_map\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBZone\fP \fB_zone\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranchOrHomeBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFaction\fP \fBHome\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFaction\fP \fBWilds\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBScene\fP \fBscene\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBBaseGameScreen\fP \fBscreen\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameSetting\fP \fBsetting\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameData\fP \fBgamedata\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBColorProfile\fP \fBColors\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBWorld\fP \fBworld\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBsources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBeditorSources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static SoundManager \fBSound\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBCoreDebug\fP \fBdebug\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB6\fP of file \fBShopTransaction\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "bool ShopTransaction\&.CanSellBack (\fBThing\fP t, int num = \fR\-1\fP)"

.PP
Definition at line \fB58\fP of file \fBShopTransaction\&.cs\fP\&.
.SS "int ShopTransaction\&.GetPrice (\fBThing\fP t, int n, bool sell)"

.PP
Definition at line \fB138\fP of file \fBShopTransaction\&.cs\fP\&.
.SS "bool ShopTransaction\&.HasBought (\fBThing\fP t)"

.PP
Definition at line \fB42\fP of file \fBShopTransaction\&.cs\fP\&.
.SS "void ShopTransaction\&.Log ()"

.PP
Definition at line \fB9\fP of file \fBShopTransaction\&.cs\fP\&.
.SS "void ShopTransaction\&.OnEndTransaction ()"

.PP
Definition at line \fB162\fP of file \fBShopTransaction\&.cs\fP\&.
.SS "void ShopTransaction\&.Process (\fBThing\fP t, int n, bool sell)"

.PP
Definition at line \fB75\fP of file \fBShopTransaction\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "List<\fBShopTransaction\&.Item\fP> ShopTransaction\&.bought = new List<\fBShopTransaction\&.Item\fP>()"

.PP
Definition at line \fB219\fP of file \fBShopTransaction\&.cs\fP\&.
.SS "\fBShopTransaction\fP ShopTransaction\&.current\fR [static]\fP"

.PP
Definition at line \fB213\fP of file \fBShopTransaction\&.cs\fP\&.
.SS "List<\fBShopTransaction\&.Item\fP> ShopTransaction\&.sold = new List<\fBShopTransaction\&.Item\fP>()"

.PP
Definition at line \fB222\fP of file \fBShopTransaction\&.cs\fP\&.
.SS "\fBInvOwner\fP ShopTransaction\&.trader"

.PP
Definition at line \fB216\fP of file \fBShopTransaction\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
