.TH "SkinRootRedirect" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SkinRootRedirect
.SH SYNOPSIS
.br
.PP
.PP
Inherits SkinRoot\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBidWidget\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override SkinConfig \fBConfig\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB4\fP of file \fBSkinRootRedirect\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "string SkinRootRedirect\&.idWidget"

.PP
Definition at line \fB22\fP of file \fBSkinRootRedirect\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "override SkinConfig SkinRootRedirect\&.Config\fR [get]\fP"

.PP
Definition at line \fB8\fP of file \fBSkinRootRedirect\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
