.TH "SLOT" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SLOT
.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "const int \fBback\fP = 33"
.br
.ti -1c
.RI "const int \fBarm\fP = 34"
.br
.ti -1c
.RI "const int \fBhand\fP = 35"
.br
.ti -1c
.RI "const int \fBfinger\fP = 36"
.br
.ti -1c
.RI "const int \fBwaist\fP = 37"
.br
.ti -1c
.RI "const int \fBfoot\fP = 39"
.br
.ti -1c
.RI "const int \fBtoolbelt\fP = 44"
.br
.ti -1c
.RI "const int \fBtoken\fP = 43"
.br
.ti -1c
.RI "const int \fBtool\fP = 40"
.br
.ti -1c
.RI "const int \fBammo\fP = 42"
.br
.ti -1c
.RI "const int \fBtorso\fP = 32"
.br
.ti -1c
.RI "const int \fBleg\fP = 38"
.br
.ti -1c
.RI "const int \fBneck\fP = 31"
.br
.ti -1c
.RI "const int \fBrange\fP = 41"
.br
.ti -1c
.RI "const int \fBhead\fP = 30"
.br
.ti -1c
.RI "const int \fBlightsource\fP = 45"
.br
.ti -1c
.RI "static readonly int[] \fBIDS\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB4\fP of file \fBSLOT\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "const int SLOT\&.ammo = 42\fR [static]\fP"

.PP
Definition at line \fB34\fP of file \fBSLOT\&.cs\fP\&.
.SS "const int SLOT\&.arm = 34\fR [static]\fP"

.PP
Definition at line \fB10\fP of file \fBSLOT\&.cs\fP\&.
.SS "const int SLOT\&.back = 33\fR [static]\fP"

.PP
Definition at line \fB7\fP of file \fBSLOT\&.cs\fP\&.
.SS "const int SLOT\&.finger = 36\fR [static]\fP"

.PP
Definition at line \fB16\fP of file \fBSLOT\&.cs\fP\&.
.SS "const int SLOT\&.foot = 39\fR [static]\fP"

.PP
Definition at line \fB22\fP of file \fBSLOT\&.cs\fP\&.
.SS "const int SLOT\&.hand = 35\fR [static]\fP"

.PP
Definition at line \fB13\fP of file \fBSLOT\&.cs\fP\&.
.SS "const int SLOT\&.head = 30\fR [static]\fP"

.PP
Definition at line \fB49\fP of file \fBSLOT\&.cs\fP\&.
.SS "readonly int [] SLOT\&.IDS\fR [static]\fP"
\fBInitial value:\fP
.nf
= new int[]
    {
        33,
        34,
        35,
        36,
        37,
        39,
        44,
        43,
        40,
        42,
        32,
        38,
        31,
        41,
        30,
        45
    }
.PP
.fi

.PP
Definition at line \fB55\fP of file \fBSLOT\&.cs\fP\&.
.SS "const int SLOT\&.leg = 38\fR [static]\fP"

.PP
Definition at line \fB40\fP of file \fBSLOT\&.cs\fP\&.
.SS "const int SLOT\&.lightsource = 45\fR [static]\fP"

.PP
Definition at line \fB52\fP of file \fBSLOT\&.cs\fP\&.
.SS "const int SLOT\&.neck = 31\fR [static]\fP"

.PP
Definition at line \fB43\fP of file \fBSLOT\&.cs\fP\&.
.SS "const int SLOT\&.range = 41\fR [static]\fP"

.PP
Definition at line \fB46\fP of file \fBSLOT\&.cs\fP\&.
.SS "const int SLOT\&.token = 43\fR [static]\fP"

.PP
Definition at line \fB28\fP of file \fBSLOT\&.cs\fP\&.
.SS "const int SLOT\&.tool = 40\fR [static]\fP"

.PP
Definition at line \fB31\fP of file \fBSLOT\&.cs\fP\&.
.SS "const int SLOT\&.toolbelt = 44\fR [static]\fP"

.PP
Definition at line \fB25\fP of file \fBSLOT\&.cs\fP\&.
.SS "const int SLOT\&.torso = 32\fR [static]\fP"

.PP
Definition at line \fB37\fP of file \fBSLOT\&.cs\fP\&.
.SS "const int SLOT\&.waist = 37\fR [static]\fP"

.PP
Definition at line \fB19\fP of file \fBSLOT\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
