.TH "SourceCollectible.Row" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SourceCollectible.Row
.SH SYNOPSIS
.br
.PP
.PP
Inherits SourceData\&.BaseRow\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBid\fP"
.br
.ti -1c
.RI "string \fBname_JP\fP"
.br
.ti -1c
.RI "string \fBname\fP"
.br
.ti -1c
.RI "int \fBrarity\fP"
.br
.ti -1c
.RI "string \fBprefab\fP"
.br
.ti -1c
.RI "int \fBnum\fP"
.br
.ti -1c
.RI "string \fBfilter\fP"
.br
.ti -1c
.RI "string[] \fBtag\fP"
.br
.ti -1c
.RI "string \fBsound\fP"
.br
.ti -1c
.RI "string \fBdetail_JP\fP"
.br
.ti -1c
.RI "string \fBdetail\fP"
.br
.ti -1c
.RI "string \fBname_L\fP"
.br
.ti -1c
.RI "string \fBdetail_L\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override bool \fBUseAlias\fP\fR [get]\fP"
.br
.ti -1c
.RI "override string \fBGetAlias\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB33\fP of file \fBSourceCollectible\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "string SourceCollectible\&.Row\&.detail"

.PP
Definition at line \fB86\fP of file \fBSourceCollectible\&.cs\fP\&.
.SS "string SourceCollectible\&.Row\&.detail_JP"

.PP
Definition at line \fB83\fP of file \fBSourceCollectible\&.cs\fP\&.
.SS "string SourceCollectible\&.Row\&.detail_L"

.PP
Definition at line \fB92\fP of file \fBSourceCollectible\&.cs\fP\&.
.SS "string SourceCollectible\&.Row\&.filter"

.PP
Definition at line \fB74\fP of file \fBSourceCollectible\&.cs\fP\&.
.SS "string SourceCollectible\&.Row\&.id"

.PP
Definition at line \fB56\fP of file \fBSourceCollectible\&.cs\fP\&.
.SS "string SourceCollectible\&.Row\&.name"

.PP
Definition at line \fB62\fP of file \fBSourceCollectible\&.cs\fP\&.
.SS "string SourceCollectible\&.Row\&.name_JP"

.PP
Definition at line \fB59\fP of file \fBSourceCollectible\&.cs\fP\&.
.SS "string SourceCollectible\&.Row\&.name_L"

.PP
Definition at line \fB89\fP of file \fBSourceCollectible\&.cs\fP\&.
.SS "int SourceCollectible\&.Row\&.num"

.PP
Definition at line \fB71\fP of file \fBSourceCollectible\&.cs\fP\&.
.SS "string SourceCollectible\&.Row\&.prefab"

.PP
Definition at line \fB68\fP of file \fBSourceCollectible\&.cs\fP\&.
.SS "int SourceCollectible\&.Row\&.rarity"

.PP
Definition at line \fB65\fP of file \fBSourceCollectible\&.cs\fP\&.
.SS "string SourceCollectible\&.Row\&.sound"

.PP
Definition at line \fB80\fP of file \fBSourceCollectible\&.cs\fP\&.
.SS "string [] SourceCollectible\&.Row\&.tag"

.PP
Definition at line \fB77\fP of file \fBSourceCollectible\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "override string SourceCollectible\&.Row\&.GetAlias\fR [get]\fP"

.PP
Definition at line \fB47\fP of file \fBSourceCollectible\&.cs\fP\&.
.SS "override bool SourceCollectible\&.Row\&.UseAlias\fR [get]\fP"

.PP
Definition at line \fB37\fP of file \fBSourceCollectible\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
