.TH "SourcePerson.Row" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SourcePerson.Row
.SH SYNOPSIS
.br
.PP
.PP
Inherits SourceData\&.BaseRow\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBid\fP"
.br
.ti -1c
.RI "string \fBidActor\fP"
.br
.ti -1c
.RI "string \fBname_JP\fP"
.br
.ti -1c
.RI "string \fBname\fP"
.br
.ti -1c
.RI "string \fBaka_JP\fP"
.br
.ti -1c
.RI "string \fBaka\fP"
.br
.ti -1c
.RI "string \fBportrait\fP"
.br
.ti -1c
.RI "string \fBfaction\fP"
.br
.ti -1c
.RI "int \fBLV\fP"
.br
.ti -1c
.RI "string \fBjob\fP"
.br
.ti -1c
.RI "string \fBrace\fP"
.br
.ti -1c
.RI "string \fBmaterial\fP"
.br
.ti -1c
.RI "string \fBbio\fP"
.br
.ti -1c
.RI "string \fBdetail_JP\fP"
.br
.ti -1c
.RI "string \fBdetail\fP"
.br
.ti -1c
.RI "string \fBname_L\fP"
.br
.ti -1c
.RI "string \fBdetail_L\fP"
.br
.ti -1c
.RI "string \fBaka_L\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override bool \fBUseAlias\fP\fR [get]\fP"
.br
.ti -1c
.RI "override string \fBGetAlias\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB50\fP of file \fBSourcePerson\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "string SourcePerson\&.Row\&.aka"

.PP
Definition at line \fB88\fP of file \fBSourcePerson\&.cs\fP\&.
.SS "string SourcePerson\&.Row\&.aka_JP"

.PP
Definition at line \fB85\fP of file \fBSourcePerson\&.cs\fP\&.
.SS "string SourcePerson\&.Row\&.aka_L"

.PP
Definition at line \fB124\fP of file \fBSourcePerson\&.cs\fP\&.
.SS "string SourcePerson\&.Row\&.bio"

.PP
Definition at line \fB109\fP of file \fBSourcePerson\&.cs\fP\&.
.SS "string SourcePerson\&.Row\&.detail"

.PP
Definition at line \fB115\fP of file \fBSourcePerson\&.cs\fP\&.
.SS "string SourcePerson\&.Row\&.detail_JP"

.PP
Definition at line \fB112\fP of file \fBSourcePerson\&.cs\fP\&.
.SS "string SourcePerson\&.Row\&.detail_L"

.PP
Definition at line \fB121\fP of file \fBSourcePerson\&.cs\fP\&.
.SS "string SourcePerson\&.Row\&.faction"

.PP
Definition at line \fB94\fP of file \fBSourcePerson\&.cs\fP\&.
.SS "string SourcePerson\&.Row\&.id"

.PP
Definition at line \fB73\fP of file \fBSourcePerson\&.cs\fP\&.
.SS "string SourcePerson\&.Row\&.idActor"

.PP
Definition at line \fB76\fP of file \fBSourcePerson\&.cs\fP\&.
.SS "string SourcePerson\&.Row\&.job"

.PP
Definition at line \fB100\fP of file \fBSourcePerson\&.cs\fP\&.
.SS "int SourcePerson\&.Row\&.LV"

.PP
Definition at line \fB97\fP of file \fBSourcePerson\&.cs\fP\&.
.SS "string SourcePerson\&.Row\&.material"

.PP
Definition at line \fB106\fP of file \fBSourcePerson\&.cs\fP\&.
.SS "string SourcePerson\&.Row\&.name"

.PP
Definition at line \fB82\fP of file \fBSourcePerson\&.cs\fP\&.
.SS "string SourcePerson\&.Row\&.name_JP"

.PP
Definition at line \fB79\fP of file \fBSourcePerson\&.cs\fP\&.
.SS "string SourcePerson\&.Row\&.name_L"

.PP
Definition at line \fB118\fP of file \fBSourcePerson\&.cs\fP\&.
.SS "string SourcePerson\&.Row\&.portrait"

.PP
Definition at line \fB91\fP of file \fBSourcePerson\&.cs\fP\&.
.SS "string SourcePerson\&.Row\&.race"

.PP
Definition at line \fB103\fP of file \fBSourcePerson\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "override string SourcePerson\&.Row\&.GetAlias\fR [get]\fP"

.PP
Definition at line \fB64\fP of file \fBSourcePerson\&.cs\fP\&.
.SS "override bool SourcePerson\&.Row\&.UseAlias\fR [get]\fP"

.PP
Definition at line \fB54\fP of file \fBSourcePerson\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
