.TH "SourceResearch.Row" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SourceResearch.Row
.SH SYNOPSIS
.br
.PP
.PP
Inherits SourceData\&.BaseRow\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBid\fP"
.br
.ti -1c
.RI "string \fBname_JP\fP"
.br
.ti -1c
.RI "string \fBname\fP"
.br
.ti -1c
.RI "string[] \fBresource\fP"
.br
.ti -1c
.RI "int \fBmoney\fP"
.br
.ti -1c
.RI "int \fBtech\fP"
.br
.ti -1c
.RI "string \fBreq\fP"
.br
.ti -1c
.RI "string \fBtype\fP"
.br
.ti -1c
.RI "int \fBexpMod\fP"
.br
.ti -1c
.RI "int \fBmaxLv\fP"
.br
.ti -1c
.RI "string \fBreward\fP"
.br
.ti -1c
.RI "string \fBdetail_JP\fP"
.br
.ti -1c
.RI "string \fBdetail\fP"
.br
.ti -1c
.RI "string \fBname_L\fP"
.br
.ti -1c
.RI "string \fBdetail_L\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override bool \fBUseAlias\fP\fR [get]\fP"
.br
.ti -1c
.RI "override string \fBGetAlias\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB35\fP of file \fBSourceResearch\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "string SourceResearch\&.Row\&.detail"

.PP
Definition at line \fB94\fP of file \fBSourceResearch\&.cs\fP\&.
.SS "string SourceResearch\&.Row\&.detail_JP"

.PP
Definition at line \fB91\fP of file \fBSourceResearch\&.cs\fP\&.
.SS "string SourceResearch\&.Row\&.detail_L"

.PP
Definition at line \fB100\fP of file \fBSourceResearch\&.cs\fP\&.
.SS "int SourceResearch\&.Row\&.expMod"

.PP
Definition at line \fB82\fP of file \fBSourceResearch\&.cs\fP\&.
.SS "string SourceResearch\&.Row\&.id"

.PP
Definition at line \fB58\fP of file \fBSourceResearch\&.cs\fP\&.
.SS "int SourceResearch\&.Row\&.maxLv"

.PP
Definition at line \fB85\fP of file \fBSourceResearch\&.cs\fP\&.
.SS "int SourceResearch\&.Row\&.money"

.PP
Definition at line \fB70\fP of file \fBSourceResearch\&.cs\fP\&.
.SS "string SourceResearch\&.Row\&.name"

.PP
Definition at line \fB64\fP of file \fBSourceResearch\&.cs\fP\&.
.SS "string SourceResearch\&.Row\&.name_JP"

.PP
Definition at line \fB61\fP of file \fBSourceResearch\&.cs\fP\&.
.SS "string SourceResearch\&.Row\&.name_L"

.PP
Definition at line \fB97\fP of file \fBSourceResearch\&.cs\fP\&.
.SS "string SourceResearch\&.Row\&.req"

.PP
Definition at line \fB76\fP of file \fBSourceResearch\&.cs\fP\&.
.SS "string [] SourceResearch\&.Row\&.resource"

.PP
Definition at line \fB67\fP of file \fBSourceResearch\&.cs\fP\&.
.SS "string SourceResearch\&.Row\&.reward"

.PP
Definition at line \fB88\fP of file \fBSourceResearch\&.cs\fP\&.
.SS "int SourceResearch\&.Row\&.tech"

.PP
Definition at line \fB73\fP of file \fBSourceResearch\&.cs\fP\&.
.SS "string SourceResearch\&.Row\&.type"

.PP
Definition at line \fB79\fP of file \fBSourceResearch\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "override string SourceResearch\&.Row\&.GetAlias\fR [get]\fP"

.PP
Definition at line \fB49\fP of file \fBSourceResearch\&.cs\fP\&.
.SS "override bool SourceResearch\&.Row\&.UseAlias\fR [get]\fP"

.PP
Definition at line \fB39\fP of file \fBSourceResearch\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
