.TH "SourceRace.Row" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SourceRace.Row
.SH SYNOPSIS
.br
.PP
.PP
Inherits SourceData\&.BaseRow\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBid\fP"
.br
.ti -1c
.RI "string \fBname_JP\fP"
.br
.ti -1c
.RI "string \fBname\fP"
.br
.ti -1c
.RI "int \fBplayable\fP"
.br
.ti -1c
.RI "string[] \fBtag\fP"
.br
.ti -1c
.RI "int \fBlife\fP"
.br
.ti -1c
.RI "int \fBmana\fP"
.br
.ti -1c
.RI "int \fBvigor\fP"
.br
.ti -1c
.RI "int \fBDV\fP"
.br
.ti -1c
.RI "int \fBPV\fP"
.br
.ti -1c
.RI "int \fBPDR\fP"
.br
.ti -1c
.RI "int \fBEDR\fP"
.br
.ti -1c
.RI "int \fBEP\fP"
.br
.ti -1c
.RI "int \fBSTR\fP"
.br
.ti -1c
.RI "int \fBEND\fP"
.br
.ti -1c
.RI "int \fBDEX\fP"
.br
.ti -1c
.RI "int \fBPER\fP"
.br
.ti -1c
.RI "int \fBLER\fP"
.br
.ti -1c
.RI "int \fBWIL\fP"
.br
.ti -1c
.RI "int \fBMAG\fP"
.br
.ti -1c
.RI "int \fBCHA\fP"
.br
.ti -1c
.RI "int \fBSPD\fP"
.br
.ti -1c
.RI "int \fBINT\fP"
.br
.ti -1c
.RI "int \fBmartial\fP"
.br
.ti -1c
.RI "int \fBpen\fP"
.br
.ti -1c
.RI "int[] \fBelements\fP"
.br
.ti -1c
.RI "string \fBskill\fP"
.br
.ti -1c
.RI "string \fBfigure\fP"
.br
.ti -1c
.RI "string \fBmaterial\fP"
.br
.ti -1c
.RI "string[] \fBcorpse\fP"
.br
.ti -1c
.RI "string[] \fBloot\fP"
.br
.ti -1c
.RI "int \fBblood\fP"
.br
.ti -1c
.RI "string \fBmeleeStyle\fP"
.br
.ti -1c
.RI "string \fBcastStyle\fP"
.br
.ti -1c
.RI "string[] \fBEQ\fP"
.br
.ti -1c
.RI "int \fBsex\fP"
.br
.ti -1c
.RI "int[] \fBage\fP"
.br
.ti -1c
.RI "int \fBheight\fP"
.br
.ti -1c
.RI "int \fBbreeder\fP"
.br
.ti -1c
.RI "string[] \fBfood\fP"
.br
.ti -1c
.RI "string \fBfur\fP"
.br
.ti -1c
.RI "string \fBdetail_JP\fP"
.br
.ti -1c
.RI "string \fBdetail\fP"
.br
.ti -1c
.RI "bool \fBvisibleWithTelepathy\fP"
.br
.ti -1c
.RI "Dictionary< int, int > \fBelementMap\fP"
.br
.ti -1c
.RI "string \fBname_L\fP"
.br
.ti -1c
.RI "string \fBdetail_L\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override bool \fBUseAlias\fP\fR [get]\fP"
.br
.ti -1c
.RI "override string \fBGetAlias\fP\fR [get]\fP"
.br
.ti -1c
.RI "bool \fBIsAnimal\fP\fR [get]\fP"
.br
.ti -1c
.RI "bool \fBIsHuman\fP\fR [get]\fP"
.br
.ti -1c
.RI "bool \fBIsUndead\fP\fR [get]\fP"
.br
.ti -1c
.RI "bool \fBIsMachine\fP\fR [get]\fP"
.br
.ti -1c
.RI "bool \fBIsHorror\fP\fR [get]\fP"
.br
.ti -1c
.RI "bool \fBIsFish\fP\fR [get]\fP"
.br
.ti -1c
.RI "bool \fBIsFairy\fP\fR [get]\fP"
.br
.ti -1c
.RI "bool \fBIsGod\fP\fR [get]\fP"
.br
.ti -1c
.RI "bool \fBIsDragon\fP\fR [get]\fP"
.br
.ti -1c
.RI "bool \fBIsPlant\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB117\fP of file \fBSourceRace\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int [] SourceRace\&.Row\&.age"

.PP
Definition at line \fB348\fP of file \fBSourceRace\&.cs\fP\&.
.SS "int SourceRace\&.Row\&.blood"

.PP
Definition at line \fB333\fP of file \fBSourceRace\&.cs\fP\&.
.SS "int SourceRace\&.Row\&.breeder"

.PP
Definition at line \fB354\fP of file \fBSourceRace\&.cs\fP\&.
.SS "string SourceRace\&.Row\&.castStyle"

.PP
Definition at line \fB339\fP of file \fBSourceRace\&.cs\fP\&.
.SS "int SourceRace\&.Row\&.CHA"

.PP
Definition at line \fB300\fP of file \fBSourceRace\&.cs\fP\&.
.SS "string [] SourceRace\&.Row\&.corpse"

.PP
Definition at line \fB327\fP of file \fBSourceRace\&.cs\fP\&.
.SS "string SourceRace\&.Row\&.detail"

.PP
Definition at line \fB366\fP of file \fBSourceRace\&.cs\fP\&.
.SS "string SourceRace\&.Row\&.detail_JP"

.PP
Definition at line \fB363\fP of file \fBSourceRace\&.cs\fP\&.
.SS "string SourceRace\&.Row\&.detail_L"

.PP
Definition at line \fB378\fP of file \fBSourceRace\&.cs\fP\&.
.SS "int SourceRace\&.Row\&.DEX"

.PP
Definition at line \fB285\fP of file \fBSourceRace\&.cs\fP\&.
.SS "int SourceRace\&.Row\&.DV"

.PP
Definition at line \fB264\fP of file \fBSourceRace\&.cs\fP\&.
.SS "int SourceRace\&.Row\&.EDR"

.PP
Definition at line \fB273\fP of file \fBSourceRace\&.cs\fP\&.
.SS "Dictionary<int, int> SourceRace\&.Row\&.elementMap"

.PP
Definition at line \fB372\fP of file \fBSourceRace\&.cs\fP\&.
.SS "int [] SourceRace\&.Row\&.elements"

.PP
Definition at line \fB315\fP of file \fBSourceRace\&.cs\fP\&.
.SS "int SourceRace\&.Row\&.END"

.PP
Definition at line \fB282\fP of file \fBSourceRace\&.cs\fP\&.
.SS "int SourceRace\&.Row\&.EP"

.PP
Definition at line \fB276\fP of file \fBSourceRace\&.cs\fP\&.
.SS "string [] SourceRace\&.Row\&.EQ"

.PP
Definition at line \fB342\fP of file \fBSourceRace\&.cs\fP\&.
.SS "string SourceRace\&.Row\&.figure"

.PP
Definition at line \fB321\fP of file \fBSourceRace\&.cs\fP\&.
.SS "string [] SourceRace\&.Row\&.food"

.PP
Definition at line \fB357\fP of file \fBSourceRace\&.cs\fP\&.
.SS "string SourceRace\&.Row\&.fur"

.PP
Definition at line \fB360\fP of file \fBSourceRace\&.cs\fP\&.
.SS "int SourceRace\&.Row\&.height"

.PP
Definition at line \fB351\fP of file \fBSourceRace\&.cs\fP\&.
.SS "string SourceRace\&.Row\&.id"

.PP
Definition at line \fB240\fP of file \fBSourceRace\&.cs\fP\&.
.SS "int SourceRace\&.Row\&.INT"

.PP
Definition at line \fB306\fP of file \fBSourceRace\&.cs\fP\&.
.SS "int SourceRace\&.Row\&.LER"

.PP
Definition at line \fB291\fP of file \fBSourceRace\&.cs\fP\&.
.SS "int SourceRace\&.Row\&.life"

.PP
Definition at line \fB255\fP of file \fBSourceRace\&.cs\fP\&.
.SS "string [] SourceRace\&.Row\&.loot"

.PP
Definition at line \fB330\fP of file \fBSourceRace\&.cs\fP\&.
.SS "int SourceRace\&.Row\&.MAG"

.PP
Definition at line \fB297\fP of file \fBSourceRace\&.cs\fP\&.
.SS "int SourceRace\&.Row\&.mana"

.PP
Definition at line \fB258\fP of file \fBSourceRace\&.cs\fP\&.
.SS "int SourceRace\&.Row\&.martial"

.PP
Definition at line \fB309\fP of file \fBSourceRace\&.cs\fP\&.
.SS "string SourceRace\&.Row\&.material"

.PP
Definition at line \fB324\fP of file \fBSourceRace\&.cs\fP\&.
.SS "string SourceRace\&.Row\&.meleeStyle"

.PP
Definition at line \fB336\fP of file \fBSourceRace\&.cs\fP\&.
.SS "string SourceRace\&.Row\&.name"

.PP
Definition at line \fB246\fP of file \fBSourceRace\&.cs\fP\&.
.SS "string SourceRace\&.Row\&.name_JP"

.PP
Definition at line \fB243\fP of file \fBSourceRace\&.cs\fP\&.
.SS "string SourceRace\&.Row\&.name_L"

.PP
Definition at line \fB375\fP of file \fBSourceRace\&.cs\fP\&.
.SS "int SourceRace\&.Row\&.PDR"

.PP
Definition at line \fB270\fP of file \fBSourceRace\&.cs\fP\&.
.SS "int SourceRace\&.Row\&.pen"

.PP
Definition at line \fB312\fP of file \fBSourceRace\&.cs\fP\&.
.SS "int SourceRace\&.Row\&.PER"

.PP
Definition at line \fB288\fP of file \fBSourceRace\&.cs\fP\&.
.SS "int SourceRace\&.Row\&.playable"

.PP
Definition at line \fB249\fP of file \fBSourceRace\&.cs\fP\&.
.SS "int SourceRace\&.Row\&.PV"

.PP
Definition at line \fB267\fP of file \fBSourceRace\&.cs\fP\&.
.SS "int SourceRace\&.Row\&.sex"

.PP
Definition at line \fB345\fP of file \fBSourceRace\&.cs\fP\&.
.SS "string SourceRace\&.Row\&.skill"

.PP
Definition at line \fB318\fP of file \fBSourceRace\&.cs\fP\&.
.SS "int SourceRace\&.Row\&.SPD"

.PP
Definition at line \fB303\fP of file \fBSourceRace\&.cs\fP\&.
.SS "int SourceRace\&.Row\&.STR"

.PP
Definition at line \fB279\fP of file \fBSourceRace\&.cs\fP\&.
.SS "string [] SourceRace\&.Row\&.tag"

.PP
Definition at line \fB252\fP of file \fBSourceRace\&.cs\fP\&.
.SS "int SourceRace\&.Row\&.vigor"

.PP
Definition at line \fB261\fP of file \fBSourceRace\&.cs\fP\&.
.SS "bool SourceRace\&.Row\&.visibleWithTelepathy"

.PP
Definition at line \fB369\fP of file \fBSourceRace\&.cs\fP\&.
.SS "int SourceRace\&.Row\&.WIL"

.PP
Definition at line \fB294\fP of file \fBSourceRace\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "override string SourceRace\&.Row\&.GetAlias\fR [get]\fP"

.PP
Definition at line \fB131\fP of file \fBSourceRace\&.cs\fP\&.
.SS "bool SourceRace\&.Row\&.IsAnimal\fR [get]\fP"

.PP
Definition at line \fB141\fP of file \fBSourceRace\&.cs\fP\&.
.SS "bool SourceRace\&.Row\&.IsDragon\fR [get]\fP"

.PP
Definition at line \fB221\fP of file \fBSourceRace\&.cs\fP\&.
.SS "bool SourceRace\&.Row\&.IsFairy\fR [get]\fP"

.PP
Definition at line \fB201\fP of file \fBSourceRace\&.cs\fP\&.
.SS "bool SourceRace\&.Row\&.IsFish\fR [get]\fP"

.PP
Definition at line \fB191\fP of file \fBSourceRace\&.cs\fP\&.
.SS "bool SourceRace\&.Row\&.IsGod\fR [get]\fP"

.PP
Definition at line \fB211\fP of file \fBSourceRace\&.cs\fP\&.
.SS "bool SourceRace\&.Row\&.IsHorror\fR [get]\fP"

.PP
Definition at line \fB181\fP of file \fBSourceRace\&.cs\fP\&.
.SS "bool SourceRace\&.Row\&.IsHuman\fR [get]\fP"

.PP
Definition at line \fB151\fP of file \fBSourceRace\&.cs\fP\&.
.SS "bool SourceRace\&.Row\&.IsMachine\fR [get]\fP"

.PP
Definition at line \fB171\fP of file \fBSourceRace\&.cs\fP\&.
.SS "bool SourceRace\&.Row\&.IsPlant\fR [get]\fP"

.PP
Definition at line \fB231\fP of file \fBSourceRace\&.cs\fP\&.
.SS "bool SourceRace\&.Row\&.IsUndead\fR [get]\fP"

.PP
Definition at line \fB161\fP of file \fBSourceRace\&.cs\fP\&.
.SS "override bool SourceRace\&.Row\&.UseAlias\fR [get]\fP"

.PP
Definition at line \fB121\fP of file \fBSourceRace\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
