.TH "SourceManager" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SourceManager
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBEMono\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBInitLang\fP ()"
.br
.ti -1c
.RI "void \fBOnChangeLang\fP ()"
.br
.ti -1c
.RI "void \fBInit\fP ()"
.br
.ti -1c
.RI "void \fBExportSourceTexts\fP (string path)"
.br
.ti -1c
.RI "void \fBUpdateSourceTexts\fP (string path)"
.br
.ti -1c
.RI "void \fBImportSourceTexts\fP ()"
.br
.ti -1c
.RI "void \fBValidateLang\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "LangGeneral \fBlangGeneral\fP"
.br
.ti -1c
.RI "LangList \fBlangList\fP"
.br
.ti -1c
.RI "LangGame \fBlangGame\fP"
.br
.ti -1c
.RI "LangWord \fBlangWord\fP"
.br
.ti -1c
.RI "LangNote \fBlangNote\fP"
.br
.ti -1c
.RI "\fBSourceCard\fP \fBcards\fP = new \fBSourceCard\fP()"
.br
.ti -1c
.RI "\fBSourceChara\fP \fBcharas\fP"
.br
.ti -1c
.RI "\fBSourceCharaText\fP \fBcharaText\fP"
.br
.ti -1c
.RI "\fBSourceTactics\fP \fBtactics\fP"
.br
.ti -1c
.RI "\fBSourcePerson\fP \fBpersons\fP"
.br
.ti -1c
.RI "\fBSourceThing\fP \fBthings\fP"
.br
.ti -1c
.RI "\fBSourceElement\fP \fBelements\fP"
.br
.ti -1c
.RI "\fBSourceCalc\fP \fBcalc\fP"
.br
.ti -1c
.RI "\fBSourceCheck\fP \fBchecks\fP"
.br
.ti -1c
.RI "\fBSourceRace\fP \fBraces\fP"
.br
.ti -1c
.RI "\fBSourceCategory\fP \fBcategories\fP"
.br
.ti -1c
.RI "\fBSourceMaterial\fP \fBmaterials\fP"
.br
.ti -1c
.RI "\fBSourceSpawnList\fP \fBspawnLists\fP"
.br
.ti -1c
.RI "\fBSourceBlock\fP \fBblocks\fP"
.br
.ti -1c
.RI "\fBSourceFloor\fP \fBfloors\fP"
.br
.ti -1c
.RI "\fBSourceCellEffect\fP \fBcellEffects\fP"
.br
.ti -1c
.RI "\fBSourceObj\fP \fBobjs\fP"
.br
.ti -1c
.RI "\fBSourceFaction\fP \fBfactions\fP"
.br
.ti -1c
.RI "\fBSourceReligion\fP \fBreligions\fP"
.br
.ti -1c
.RI "\fBSourceJob\fP \fBjobs\fP"
.br
.ti -1c
.RI "\fBSourceHobby\fP \fBhobbies\fP"
.br
.ti -1c
.RI "\fBSourceQuest\fP \fBquests\fP"
.br
.ti -1c
.RI "\fBSourceStat\fP \fBstats\fP"
.br
.ti -1c
.RI "\fBSourceArea\fP \fBareas\fP"
.br
.ti -1c
.RI "\fBSourceZone\fP \fBzones\fP"
.br
.ti -1c
.RI "\fBSourceZoneAffix\fP \fBzoneAffixes\fP"
.br
.ti -1c
.RI "\fBSourceResearch\fP \fBresearches\fP"
.br
.ti -1c
.RI "\fBSourceHomeResource\fP \fBhomeResources\fP"
.br
.ti -1c
.RI "\fBSourceCollectible\fP \fBcollectibles\fP"
.br
.ti -1c
.RI "\fBSourceGlobalTile\fP \fBglobalTiles\fP"
.br
.ti -1c
.RI "\fBSourceThingV\fP \fBthingV\fP"
.br
.ti -1c
.RI "\fBSourceFood\fP \fBfoods\fP"
.br
.ti -1c
.RI "\fBSourceRecipe\fP \fBrecipes\fP"
.br
.ti -1c
.RI "\fBSourceBacker\fP \fBbackers\fP"
.br
.ti -1c
.RI "\fBSourceAsset\fP \fBasset\fP"
.br
.ti -1c
.RI "\fBSourceKeyItem\fP \fBkeyItems\fP"
.br
.ti -1c
.RI "bool \fBinitialized\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "ExcelData \fBdataGodTalk\fP\fR [get]\fP"
.br
.in -1c

Properties inherited from \fBEMono\fP
.in +1c
.ti -1c
.RI "static \fBGame\fP \fBgame\fP\fR [get]\fP"
.br
.ti -1c
.RI "static bool \fBAdvMode\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBPlayer\fP \fBplayer\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBChara\fP \fBpc\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBUI\fP \fBui\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBMap\fP \fB_map\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBZone\fP \fB_zone\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranchOrHomeBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFaction\fP \fBHome\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBScene\fP \fBscene\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBBaseGameScreen\fP \fBscreen\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameSetting\fP \fBsetting\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameData\fP \fBgamedata\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBColorProfile\fP \fBColors\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBWorld\fP \fBworld\fP\fR [get]\fP"
.br
.ti -1c
.RI "static SoundManager \fBSound\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBsources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBeditorSources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBCoreDebug\fP \fBdebug\fP\fR [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Static Public Member Functions inherited from \fBEMono\fP
.in +1c
.ti -1c
.RI "static int \fBrnd\fP (int a)"
.br
.in -1c

Static Public Attributes inherited from \fBEMono\fP
.in +1c
.ti -1c
.RI "static \fBCore\fP \fBcore\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB6\fP of file \fBSourceManager\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void SourceManager\&.ExportSourceTexts (string path)"

.PP
Definition at line \fB105\fP of file \fBSourceManager\&.cs\fP\&.
.SS "void SourceManager\&.ImportSourceTexts ()"

.PP
Definition at line \fB123\fP of file \fBSourceManager\&.cs\fP\&.
.SS "void SourceManager\&.Init ()"

.PP
Definition at line \fB45\fP of file \fBSourceManager\&.cs\fP\&.
.SS "void SourceManager\&.InitLang ()"

.PP
Definition at line \fB24\fP of file \fBSourceManager\&.cs\fP\&.
.SS "void SourceManager\&.OnChangeLang ()"

.PP
Definition at line \fB39\fP of file \fBSourceManager\&.cs\fP\&.
.SS "void SourceManager\&.UpdateSourceTexts (string path)"

.PP
Definition at line \fB114\fP of file \fBSourceManager\&.cs\fP\&.
.SS "void SourceManager\&.ValidateLang ()"

.PP
Definition at line \fB139\fP of file \fBSourceManager\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBSourceArea\fP SourceManager\&.areas"

.PP
Definition at line \fB236\fP of file \fBSourceManager\&.cs\fP\&.
.SS "\fBSourceAsset\fP SourceManager\&.asset"

.PP
Definition at line \fB269\fP of file \fBSourceManager\&.cs\fP\&.
.SS "\fBSourceBacker\fP SourceManager\&.backers"

.PP
Definition at line \fB266\fP of file \fBSourceManager\&.cs\fP\&.
.SS "\fBSourceBlock\fP SourceManager\&.blocks"

.PP
Definition at line \fB206\fP of file \fBSourceManager\&.cs\fP\&.
.SS "\fBSourceCalc\fP SourceManager\&.calc"

.PP
Definition at line \fB188\fP of file \fBSourceManager\&.cs\fP\&.
.SS "\fBSourceCard\fP SourceManager\&.cards = new \fBSourceCard\fP()"

.PP
Definition at line \fB167\fP of file \fBSourceManager\&.cs\fP\&.
.SS "\fBSourceCategory\fP SourceManager\&.categories"

.PP
Definition at line \fB197\fP of file \fBSourceManager\&.cs\fP\&.
.SS "\fBSourceCellEffect\fP SourceManager\&.cellEffects"

.PP
Definition at line \fB212\fP of file \fBSourceManager\&.cs\fP\&.
.SS "\fBSourceChara\fP SourceManager\&.charas"

.PP
Definition at line \fB170\fP of file \fBSourceManager\&.cs\fP\&.
.SS "\fBSourceCharaText\fP SourceManager\&.charaText"

.PP
Definition at line \fB173\fP of file \fBSourceManager\&.cs\fP\&.
.SS "\fBSourceCheck\fP SourceManager\&.checks"

.PP
Definition at line \fB191\fP of file \fBSourceManager\&.cs\fP\&.
.SS "\fBSourceCollectible\fP SourceManager\&.collectibles"

.PP
Definition at line \fB251\fP of file \fBSourceManager\&.cs\fP\&.
.SS "\fBSourceElement\fP SourceManager\&.elements"

.PP
Definition at line \fB185\fP of file \fBSourceManager\&.cs\fP\&.
.SS "\fBSourceFaction\fP SourceManager\&.factions"

.PP
Definition at line \fB218\fP of file \fBSourceManager\&.cs\fP\&.
.SS "\fBSourceFloor\fP SourceManager\&.floors"

.PP
Definition at line \fB209\fP of file \fBSourceManager\&.cs\fP\&.
.SS "\fBSourceFood\fP SourceManager\&.foods"

.PP
Definition at line \fB260\fP of file \fBSourceManager\&.cs\fP\&.
.SS "\fBSourceGlobalTile\fP SourceManager\&.globalTiles"

.PP
Definition at line \fB254\fP of file \fBSourceManager\&.cs\fP\&.
.SS "\fBSourceHobby\fP SourceManager\&.hobbies"

.PP
Definition at line \fB227\fP of file \fBSourceManager\&.cs\fP\&.
.SS "\fBSourceHomeResource\fP SourceManager\&.homeResources"

.PP
Definition at line \fB248\fP of file \fBSourceManager\&.cs\fP\&.
.SS "bool SourceManager\&.initialized"

.PP
Definition at line \fB281\fP of file \fBSourceManager\&.cs\fP\&.
.SS "\fBSourceJob\fP SourceManager\&.jobs"

.PP
Definition at line \fB224\fP of file \fBSourceManager\&.cs\fP\&.
.SS "\fBSourceKeyItem\fP SourceManager\&.keyItems"

.PP
Definition at line \fB272\fP of file \fBSourceManager\&.cs\fP\&.
.SS "LangGame SourceManager\&.langGame"

.PP
Definition at line \fB158\fP of file \fBSourceManager\&.cs\fP\&.
.SS "LangGeneral SourceManager\&.langGeneral"

.PP
Definition at line \fB152\fP of file \fBSourceManager\&.cs\fP\&.
.SS "LangList SourceManager\&.langList"

.PP
Definition at line \fB155\fP of file \fBSourceManager\&.cs\fP\&.
.SS "LangNote SourceManager\&.langNote"

.PP
Definition at line \fB164\fP of file \fBSourceManager\&.cs\fP\&.
.SS "LangWord SourceManager\&.langWord"

.PP
Definition at line \fB161\fP of file \fBSourceManager\&.cs\fP\&.
.SS "\fBSourceMaterial\fP SourceManager\&.materials"

.PP
Definition at line \fB200\fP of file \fBSourceManager\&.cs\fP\&.
.SS "\fBSourceObj\fP SourceManager\&.objs"

.PP
Definition at line \fB215\fP of file \fBSourceManager\&.cs\fP\&.
.SS "\fBSourcePerson\fP SourceManager\&.persons"

.PP
Definition at line \fB179\fP of file \fBSourceManager\&.cs\fP\&.
.SS "\fBSourceQuest\fP SourceManager\&.quests"

.PP
Definition at line \fB230\fP of file \fBSourceManager\&.cs\fP\&.
.SS "\fBSourceRace\fP SourceManager\&.races"

.PP
Definition at line \fB194\fP of file \fBSourceManager\&.cs\fP\&.
.SS "\fBSourceRecipe\fP SourceManager\&.recipes"

.PP
Definition at line \fB263\fP of file \fBSourceManager\&.cs\fP\&.
.SS "\fBSourceReligion\fP SourceManager\&.religions"

.PP
Definition at line \fB221\fP of file \fBSourceManager\&.cs\fP\&.
.SS "\fBSourceResearch\fP SourceManager\&.researches"

.PP
Definition at line \fB245\fP of file \fBSourceManager\&.cs\fP\&.
.SS "\fBSourceSpawnList\fP SourceManager\&.spawnLists"

.PP
Definition at line \fB203\fP of file \fBSourceManager\&.cs\fP\&.
.SS "\fBSourceStat\fP SourceManager\&.stats"

.PP
Definition at line \fB233\fP of file \fBSourceManager\&.cs\fP\&.
.SS "\fBSourceTactics\fP SourceManager\&.tactics"

.PP
Definition at line \fB176\fP of file \fBSourceManager\&.cs\fP\&.
.SS "\fBSourceThing\fP SourceManager\&.things"

.PP
Definition at line \fB182\fP of file \fBSourceManager\&.cs\fP\&.
.SS "\fBSourceThingV\fP SourceManager\&.thingV"

.PP
Definition at line \fB257\fP of file \fBSourceManager\&.cs\fP\&.
.SS "\fBSourceZoneAffix\fP SourceManager\&.zoneAffixes"

.PP
Definition at line \fB242\fP of file \fBSourceManager\&.cs\fP\&.
.SS "\fBSourceZone\fP SourceManager\&.zones"

.PP
Definition at line \fB239\fP of file \fBSourceManager\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "ExcelData SourceManager\&.dataGodTalk\fR [get]\fP"

.PP
Definition at line \fB10\fP of file \fBSourceManager\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
