.TH "SourceRecipe" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SourceRecipe
.SH SYNOPSIS
.br
.PP
.PP
Inherits SourceDataInt< SourceRecipe\&.Row >\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRow\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override \fBSourceRecipe\&.Row\fP \fBCreateRow\fP ()"
.br
.ti -1c
.RI "override void \fBSetRow\fP (\fBSourceRecipe\&.Row\fP r)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB4\fP of file \fBSourceRecipe\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override \fBSourceRecipe\&.Row\fP SourceRecipe\&.CreateRow ()"

.PP
Definition at line \fB7\fP of file \fBSourceRecipe\&.cs\fP\&.
.SS "override void SourceRecipe\&.SetRow (\fBSourceRecipe\&.Row\fP r)"

.PP
Definition at line \fB26\fP of file \fBSourceRecipe\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
