.TH "SourceRace" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SourceRace
.SH SYNOPSIS
.br
.PP
.PP
Inherits SourceDataString< SourceRace\&.Row >\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRow\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override \fBSourceRace\&.Row\fP \fBCreateRow\fP ()"
.br
.ti -1c
.RI "override void \fBSetRow\fP (\fBSourceRace\&.Row\fP r)"
.br
.ti -1c
.RI "override void \fBOnInit\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB5\fP of file \fBSourceRace\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override \fBSourceRace\&.Row\fP SourceRace\&.CreateRow ()"

.PP
Definition at line \fB8\fP of file \fBSourceRace\&.cs\fP\&.
.SS "override void SourceRace\&.OnInit ()"

.PP
Definition at line \fB65\fP of file \fBSourceRace\&.cs\fP\&.
.SS "override void SourceRace\&.SetRow (\fBSourceRace\&.Row\fP r)"

.PP
Definition at line \fB59\fP of file \fBSourceRace\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
