.TH "SourceFloor" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SourceFloor
.SH SYNOPSIS
.br
.PP
.PP
Inherits SourceDataInt< SourceFloor\&.Row >\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRow\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override \fBSourceFloor\&.Row\fP \fBCreateRow\fP ()"
.br
.ti -1c
.RI "override void \fBSetRow\fP (\fBSourceFloor\&.Row\fP r)"
.br
.ti -1c
.RI "override void \fBBackupPref\fP ()"
.br
.ti -1c
.RI "override void \fBRestorePref\fP ()"
.br
.ti -1c
.RI "override void \fBValidatePref\fP ()"
.br
.ti -1c
.RI "override void \fBOnAfterImportData\fP ()"
.br
.ti -1c
.RI "override void \fBOnInit\fP ()"
.br
.ti -1c
.RI "void \fBOnAfterInit\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Dictionary< int, \fBSourceFloor\&.Row\fP > \fB_rows\fP = new Dictionary<int, \fBSourceFloor\&.Row\fP>()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static \fBRenderData\fP \fBFallbackRenderData\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB5\fP of file \fBSourceFloor\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void SourceFloor\&.BackupPref ()"

.PP
Definition at line \fB51\fP of file \fBSourceFloor\&.cs\fP\&.
.SS "override \fBSourceFloor\&.Row\fP SourceFloor\&.CreateRow ()"

.PP
Definition at line \fB8\fP of file \fBSourceFloor\&.cs\fP\&.
.SS "override void SourceFloor\&.OnAfterImportData ()"

.PP
Definition at line \fB81\fP of file \fBSourceFloor\&.cs\fP\&.
.SS "void SourceFloor\&.OnAfterInit ()"

.PP
Definition at line \fB108\fP of file \fBSourceFloor\&.cs\fP\&.
.SS "override void SourceFloor\&.OnInit ()"

.PP
Definition at line \fB97\fP of file \fBSourceFloor\&.cs\fP\&.
.SS "override void SourceFloor\&.RestorePref ()"

.PP
Definition at line \fB61\fP of file \fBSourceFloor\&.cs\fP\&.
.SS "override void SourceFloor\&.SetRow (\fBSourceFloor\&.Row\fP r)"

.PP
Definition at line \fB45\fP of file \fBSourceFloor\&.cs\fP\&.
.SS "override void SourceFloor\&.ValidatePref ()"

.PP
Definition at line \fB72\fP of file \fBSourceFloor\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "Dictionary<int, \fBSourceFloor\&.Row\fP> SourceFloor\&._rows = new Dictionary<int, \fBSourceFloor\&.Row\fP>()"

.PP
Definition at line \fB119\fP of file \fBSourceFloor\&.cs\fP\&.
.SS "\fBRenderData\fP SourceFloor\&.FallbackRenderData\fR [static]\fP"

.PP
Definition at line \fB122\fP of file \fBSourceFloor\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
