.TH "SourceChara.Row" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SourceChara.Row
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCardRow\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override string \fBGetSearchName\fP (bool jp)"
.br
.ti -1c
.RI "override void \fBSetTiles\fP ()"
.br
.ti -1c
.RI "override string \fBGetName\fP ()"
.br
.in -1c

Public Member Functions inherited from \fBCardRow\fP
.in +1c
.ti -1c
.RI "override \fBSourcePref\fP \fBGetPref\fP ()"
.br
.ti -1c
.RI "override void \fBOnImportData\fP (SourceData data)"
.br
.ti -1c
.RI "virtual string \fBGetName\fP (int i)"
.br
.ti -1c
.RI "virtual string \fBGetName\fP (\fBSourceMaterial\&.Row\fP mat, int sum)"
.br
.ti -1c
.RI "override string \fBGetEditorListName\fP ()"
.br
.ti -1c
.RI "override string \fBGetName\fP ()"
.br
.ti -1c
.RI "string \fBGetName\fP (\fBCard\fP c, bool full=false)"
.br
.in -1c

Public Member Functions inherited from \fBRenderRow\fP
.in +1c
.ti -1c
.RI "bool \fBHasTag\fP (CTAG _tag)"
.br
.ti -1c
.RI "bool \fBContainsTag\fP (string _tag)"
.br
.ti -1c
.RI "override void \fBOnImportData\fP (SourceData data)"
.br
.ti -1c
.RI "void \fBSetRenderData\fP ()"
.br
.ti -1c
.RI "int \fBConvertTile\fP (int tile)"
.br
.ti -1c
.RI "Sprite \fBGetSprite\fP (int dir=0, int skin=0, bool snow=false)"
.br
.ti -1c
.RI "void \fBSetSpriteRenderer\fP (SpriteRenderer sr, Sprite sprite=null, int matCol=0, bool setTransform=true, int dir=0)"
.br
.ti -1c
.RI "void \fBSetImage\fP (Image image, Sprite sprite=null, int matCol=0, bool setNativeSize=true, int dir=0, int idSkin=0)"
.br
.ti -1c
.RI "void \fBSetRenderParam\fP (\fBRenderParam\fP p, \fBSourceMaterial\&.Row\fP mat, int dir)"
.br
.ti -1c
.RI "virtual unsafe \fBRenderParam\fP \fBGetRenderParam\fP (\fBSourceMaterial\&.Row\fP mat, int dir, \fBPoint\fP point=null, int bridgeHeight=\-1)"
.br
.ti -1c
.RI "virtual int \fBGetTile\fP (\fBSourceMaterial\&.Row\fP mat, int dir=0)"
.br
.ti -1c
.RI "int \fBGetColorInt\fP (\fBSourceMaterial\&.Row\fP mat)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fB_id\fP"
.br
.ti -1c
.RI "string \fBaka_JP\fP"
.br
.ti -1c
.RI "string \fBaka\fP"
.br
.ti -1c
.RI "int[] \fBtiles_snow\fP"
.br
.ti -1c
.RI "string \fBhostility\fP"
.br
.ti -1c
.RI "string \fBbiome\fP"
.br
.ti -1c
.RI "string \fBrace\fP"
.br
.ti -1c
.RI "string \fBjob\fP"
.br
.ti -1c
.RI "string \fBtactics\fP"
.br
.ti -1c
.RI "string \fBaiIdle\fP"
.br
.ti -1c
.RI "int[] \fBaiParam\fP"
.br
.ti -1c
.RI "string[] \fBactCombat\fP"
.br
.ti -1c
.RI "string[] \fBmainElement\fP"
.br
.ti -1c
.RI "string \fBequip\fP"
.br
.ti -1c
.RI "string[] \fBgachaFilter\fP"
.br
.ti -1c
.RI "string \fBtone\fP"
.br
.ti -1c
.RI "string[] \fBactIdle\fP"
.br
.ti -1c
.RI "string \fBbio\fP"
.br
.ti -1c
.RI "string \fBfaith\fP"
.br
.ti -1c
.RI "string[] \fBworks\fP"
.br
.ti -1c
.RI "string[] \fBhobbies\fP"
.br
.ti -1c
.RI "string \fBidText\fP"
.br
.ti -1c
.RI "string \fBmoveAnime\fP"
.br
.ti -1c
.RI "bool \fBstaticSkin\fP"
.br
.ti -1c
.RI "int[] \fB_tiles_snow\fP"
.br
.ti -1c
.RI "\fBSourceRace\&.Row\fP \fB_race_row\fP"
.br
.ti -1c
.RI "string \fBname_L\fP"
.br
.ti -1c
.RI "string \fBdetail_L\fP"
.br
.ti -1c
.RI "string \fBaka_L\fP"
.br
.in -1c

Public Attributes inherited from \fBCardRow\fP
.in +1c
.ti -1c
.RI "string \fBid\fP"
.br
.ti -1c
.RI "string \fBidExtra\fP"
.br
.ti -1c
.RI "string \fBtierGroup\fP"
.br
.ti -1c
.RI "string \fBlightData\fP"
.br
.ti -1c
.RI "string \fB_origin\fP"
.br
.ti -1c
.RI "int \fBidShadow\fP"
.br
.ti -1c
.RI "int \fBquality\fP"
.br
.ti -1c
.RI "int[] \fBelements\fP"
.br
.ti -1c
.RI "int[] \fBshadow\fP"
.br
.ti -1c
.RI "int[] \fBsize\fP"
.br
.ti -1c
.RI "int[] \fBlight\fP"
.br
.ti -1c
.RI "string[] \fBloot\fP"
.br
.ti -1c
.RI "string[] \fBfilter\fP"
.br
.ti -1c
.RI "string[] \fBtrait\fP"
.br
.ti -1c
.RI "string[] \fBidActor\fP"
.br
.ti -1c
.RI "string[] \fBvals\fP"
.br
.ti -1c
.RI "string[] \fBname2\fP"
.br
.ti -1c
.RI "string[] \fBname2_JP\fP"
.br
.ti -1c
.RI "Dictionary< int, int > \fBelementMap\fP"
.br
.ti -1c
.RI "Sprite \fBsprite\fP"
.br
.ti -1c
.RI "\fBCardRow\fP \fBorigin\fP"
.br
.ti -1c
.RI "bool \fBisOrigin\fP"
.br
.ti -1c
.RI "bool \fBisChara\fP"
.br
.ti -1c
.RI "\fBCard\fP \fB_model\fP"
.br
.in -1c

Public Attributes inherited from \fBRenderRow\fP
.in +1c
.ti -1c
.RI "int[] \fBtiles\fP"
.br
.ti -1c
.RI "int[] \fB_tiles\fP"
.br
.ti -1c
.RI "int[] \fBskins\fP"
.br
.ti -1c
.RI "int \fBcolorMod\fP"
.br
.ti -1c
.RI "int \fBsort\fP"
.br
.ti -1c
.RI "int \fBvalue\fP"
.br
.ti -1c
.RI "int \fBLV\fP"
.br
.ti -1c
.RI "int \fBchance\fP"
.br
.ti -1c
.RI "int \fBtempChance\fP"
.br
.ti -1c
.RI "int \fBsnowTile\fP"
.br
.ti -1c
.RI "string \fBname\fP"
.br
.ti -1c
.RI "string \fBname_JP\fP"
.br
.ti -1c
.RI "string \fBdetail\fP"
.br
.ti -1c
.RI "string \fBdetail_JP\fP"
.br
.ti -1c
.RI "string \fB_idRenderData\fP"
.br
.ti -1c
.RI "string \fB_tileType\fP"
.br
.ti -1c
.RI "string \fBdefMat\fP"
.br
.ti -1c
.RI "string \fBcolorType\fP"
.br
.ti -1c
.RI "string \fBcategory\fP"
.br
.ti -1c
.RI "string \fBidSound\fP"
.br
.ti -1c
.RI "string \fBaliasPref\fP"
.br
.ti -1c
.RI "string[] \fBcomponents\fP"
.br
.ti -1c
.RI "string[] \fBfactory\fP"
.br
.ti -1c
.RI "string[] \fBrecipeKey\fP"
.br
.ti -1c
.RI "string[] \fBtag\fP"
.br
.ti -1c
.RI "int \fBW\fP = 1"
.br
.ti -1c
.RI "int \fBH\fP = 1"
.br
.ti -1c
.RI "bool \fBmultisize\fP"
.br
.ti -1c
.RI "\fBSourcePref\fP \fBpref\fP"
.br
.ti -1c
.RI "\fBRenderData\fP \fBrenderData\fP"
.br
.ti -1c
.RI "Sprite[,] \fBsprites\fP"
.br
.ti -1c
.RI "\fBTileType\fP \fBtileType\fP"
.br
.ti -1c
.RI "bool \fBuseAltColor\fP"
.br
.ti -1c
.RI "bool \fBuseRandomColor\fP"
.br
.ti -1c
.RI "bool \fBfixedMaterial\fP"
.br
.ti -1c
.RI "\fBSourceMaterial\&.Row\fP \fBDefaultMaterial\fP"
.br
.ti -1c
.RI "SpriteReplacer \fBreplacer\fP"
.br
.ti -1c
.RI "string \fB_nameSearch\fP"
.br
.ti -1c
.RI "string \fB_nameSearchJP\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override bool \fBUseAlias\fP\fR [get]\fP"
.br
.ti -1c
.RI "override string \fBGetAlias\fP\fR [get]\fP"
.br
.ti -1c
.RI "\fBSourceRace\&.Row\fP \fBrace_row\fP\fR [get]\fP"
.br
.ti -1c
.RI "override string \fBRecipeID\fP\fR [get]\fP"
.br
.in -1c

Properties inherited from \fBCardRow\fP
.in +1c
.ti -1c
.RI "\fBCard\fP \fBmodel\fP\fR [get]\fP"
.br
.ti -1c
.RI "override string \fBidRenderData\fP\fR [get]\fP"
.br
.ti -1c
.RI "override string \fBidSprite\fP\fR [get]\fP"
.br
.ti -1c
.RI "override string \fBidString\fP\fR [get]\fP"
.br
.ti -1c
.RI "override string \fBpathSprite\fP\fR [get]\fP"
.br
.in -1c

Properties inherited from \fBRenderRow\fP
.in +1c
.ti -1c
.RI "virtual string \fBidString\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual string \fBRecipeID\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual string \fBpathRenderData\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual string \fBidRenderData\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual \fBRenderData\fP \fBdefaultRenderData\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual string \fBpathSprite\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual string \fBidSprite\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual string \fBprefabName\fP\fR [get]\fP"
.br
.ti -1c
.RI "\fBSourceCategory\&.Row\fP \fBCategory\fP\fR [get]\fP"
.br
.ti -1c
.RI "string \fBRecipeCat\fP\fR [get]\fP"
.br
.ti -1c
.RI "\fBSourceManager\fP \fBsources\fP\fR [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Static Public Attributes inherited from \fBRenderRow\fP
.in +1c
.ti -1c
.RI "static Dictionary< string, \fBRenderData\fP > \fBDictRenderData\fP = new Dictionary<string, \fBRenderData\fP>()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB121\fP of file \fBSourceChara\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override string SourceChara\&.Row\&.GetName ()"

.PP
Definition at line \fB206\fP of file \fBSourceChara\&.cs\fP\&.
.SS "override string SourceChara\&.Row\&.GetSearchName (bool jp)\fR [virtual]\fP"

.PP
Reimplemented from \fBRenderRow\fP\&.
.PP
Definition at line \fB169\fP of file \fBSourceChara\&.cs\fP\&.
.SS "override void SourceChara\&.Row\&.SetTiles ()\fR [virtual]\fP"

.PP
Reimplemented from \fBRenderRow\fP\&.
.PP
Definition at line \fB187\fP of file \fBSourceChara\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int SourceChara\&.Row\&._id"

.PP
Definition at line \fB222\fP of file \fBSourceChara\&.cs\fP\&.
.SS "\fBSourceRace\&.Row\fP SourceChara\&.Row\&._race_row"

.PP
Definition at line \fB298\fP of file \fBSourceChara\&.cs\fP\&.
.SS "int [] SourceChara\&.Row\&._tiles_snow"

.PP
Definition at line \fB294\fP of file \fBSourceChara\&.cs\fP\&.
.SS "string [] SourceChara\&.Row\&.actCombat"

.PP
Definition at line \fB255\fP of file \fBSourceChara\&.cs\fP\&.
.SS "string [] SourceChara\&.Row\&.actIdle"

.PP
Definition at line \fB270\fP of file \fBSourceChara\&.cs\fP\&.
.SS "string SourceChara\&.Row\&.aiIdle"

.PP
Definition at line \fB249\fP of file \fBSourceChara\&.cs\fP\&.
.SS "int [] SourceChara\&.Row\&.aiParam"

.PP
Definition at line \fB252\fP of file \fBSourceChara\&.cs\fP\&.
.SS "string SourceChara\&.Row\&.aka"

.PP
Definition at line \fB228\fP of file \fBSourceChara\&.cs\fP\&.
.SS "string SourceChara\&.Row\&.aka_JP"

.PP
Definition at line \fB225\fP of file \fBSourceChara\&.cs\fP\&.
.SS "string SourceChara\&.Row\&.aka_L"

.PP
Definition at line \fB307\fP of file \fBSourceChara\&.cs\fP\&.
.SS "string SourceChara\&.Row\&.bio"

.PP
Definition at line \fB273\fP of file \fBSourceChara\&.cs\fP\&.
.SS "string SourceChara\&.Row\&.biome"

.PP
Definition at line \fB237\fP of file \fBSourceChara\&.cs\fP\&.
.SS "string SourceChara\&.Row\&.detail_L"

.PP
Definition at line \fB304\fP of file \fBSourceChara\&.cs\fP\&.
.SS "string SourceChara\&.Row\&.equip"

.PP
Definition at line \fB261\fP of file \fBSourceChara\&.cs\fP\&.
.SS "string SourceChara\&.Row\&.faith"

.PP
Definition at line \fB276\fP of file \fBSourceChara\&.cs\fP\&.
.SS "string [] SourceChara\&.Row\&.gachaFilter"

.PP
Definition at line \fB264\fP of file \fBSourceChara\&.cs\fP\&.
.SS "string [] SourceChara\&.Row\&.hobbies"

.PP
Definition at line \fB282\fP of file \fBSourceChara\&.cs\fP\&.
.SS "string SourceChara\&.Row\&.hostility"

.PP
Definition at line \fB234\fP of file \fBSourceChara\&.cs\fP\&.
.SS "string SourceChara\&.Row\&.idText"

.PP
Definition at line \fB285\fP of file \fBSourceChara\&.cs\fP\&.
.SS "string SourceChara\&.Row\&.job"

.PP
Definition at line \fB243\fP of file \fBSourceChara\&.cs\fP\&.
.SS "string [] SourceChara\&.Row\&.mainElement"

.PP
Definition at line \fB258\fP of file \fBSourceChara\&.cs\fP\&.
.SS "string SourceChara\&.Row\&.moveAnime"

.PP
Definition at line \fB288\fP of file \fBSourceChara\&.cs\fP\&.
.SS "string SourceChara\&.Row\&.name_L"

.PP
Definition at line \fB301\fP of file \fBSourceChara\&.cs\fP\&.
.SS "string SourceChara\&.Row\&.race"

.PP
Definition at line \fB240\fP of file \fBSourceChara\&.cs\fP\&.
.SS "bool SourceChara\&.Row\&.staticSkin"

.PP
Definition at line \fB291\fP of file \fBSourceChara\&.cs\fP\&.
.SS "string SourceChara\&.Row\&.tactics"

.PP
Definition at line \fB246\fP of file \fBSourceChara\&.cs\fP\&.
.SS "int [] SourceChara\&.Row\&.tiles_snow"

.PP
Definition at line \fB231\fP of file \fBSourceChara\&.cs\fP\&.
.SS "string SourceChara\&.Row\&.tone"

.PP
Definition at line \fB267\fP of file \fBSourceChara\&.cs\fP\&.
.SS "string [] SourceChara\&.Row\&.works"

.PP
Definition at line \fB279\fP of file \fBSourceChara\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "override string SourceChara\&.Row\&.GetAlias\fR [get]\fP"

.PP
Definition at line \fB135\fP of file \fBSourceChara\&.cs\fP\&.
.SS "\fBSourceRace\&.Row\fP SourceChara\&.Row\&.race_row\fR [get]\fP"

.PP
Definition at line \fB145\fP of file \fBSourceChara\&.cs\fP\&.
.SS "override string SourceChara\&.Row\&.RecipeID\fR [get]\fP"

.PP
Definition at line \fB160\fP of file \fBSourceChara\&.cs\fP\&.
.SS "override bool SourceChara\&.Row\&.UseAlias\fR [get]\fP"

.PP
Definition at line \fB125\fP of file \fBSourceChara\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
