.TH "SourceChara" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SourceChara
.SH SYNOPSIS
.br
.PP
.PP
Inherits SourceDataString< SourceChara\&.Row >\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRow\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override \fBSourceChara\&.Row\fP \fBCreateRow\fP ()"
.br
.ti -1c
.RI "override void \fBSetRow\fP (\fBSourceChara\&.Row\fP r)"
.br
.ti -1c
.RI "override void \fBBackupPref\fP ()"
.br
.ti -1c
.RI "override void \fBRestorePref\fP ()"
.br
.ti -1c
.RI "override void \fBValidatePref\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Dictionary< string, \fBSourceChara\&.Row\fP > \fB_rows\fP = new Dictionary<string, \fBSourceChara\&.Row\fP>()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static \fBSourceChara\&.Row\fP \fBrowDefaultPCC\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override string[] \fBImportFields\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB5\fP of file \fBSourceChara\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void SourceChara\&.BackupPref ()"

.PP
Definition at line \fB71\fP of file \fBSourceChara\&.cs\fP\&.
.SS "override \fBSourceChara\&.Row\fP SourceChara\&.CreateRow ()"

.PP
Definition at line \fB8\fP of file \fBSourceChara\&.cs\fP\&.
.SS "override void SourceChara\&.RestorePref ()"

.PP
Definition at line \fB81\fP of file \fBSourceChara\&.cs\fP\&.
.SS "override void SourceChara\&.SetRow (\fBSourceChara\&.Row\fP r)"

.PP
Definition at line \fB65\fP of file \fBSourceChara\&.cs\fP\&.
.SS "override void SourceChara\&.ValidatePref ()"

.PP
Definition at line \fB92\fP of file \fBSourceChara\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "Dictionary<string, \fBSourceChara\&.Row\fP> SourceChara\&._rows = new Dictionary<string, \fBSourceChara\&.Row\fP>()"

.PP
Definition at line \fB114\fP of file \fBSourceChara\&.cs\fP\&.
.SS "\fBSourceChara\&.Row\fP SourceChara\&.rowDefaultPCC\fR [static]\fP"

.PP
Definition at line \fB117\fP of file \fBSourceChara\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "override string [] SourceChara\&.ImportFields\fR [get]\fP"

.PP
Definition at line \fB102\fP of file \fBSourceChara\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
