.TH "SourceObj" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SourceObj
.SH SYNOPSIS
.br
.PP
.PP
Inherits SourceDataInt< SourceObj\&.Row >\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRow\fP"
.br
.ti -1c
.RI "class \fBStage\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override \fBSourceObj\&.Row\fP \fBCreateRow\fP ()"
.br
.ti -1c
.RI "override void \fBSetRow\fP (\fBSourceObj\&.Row\fP r)"
.br
.ti -1c
.RI "override void \fBBackupPref\fP ()"
.br
.ti -1c
.RI "override void \fBRestorePref\fP ()"
.br
.ti -1c
.RI "override void \fBValidatePref\fP ()"
.br
.ti -1c
.RI "string \fBGetName\fP (int id)"
.br
.ti -1c
.RI "override void \fBOnAfterImportData\fP ()"
.br
.ti -1c
.RI "override void \fBOnInit\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Dictionary< int, \fBSourceObj\&.Row\fP > \fB_rows\fP = new Dictionary<int, \fBSourceObj\&.Row\fP>()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static \fBRenderData\fP \fBFallbackRenderData\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB5\fP of file \fBSourceObj\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void SourceObj\&.BackupPref ()"

.PP
Definition at line \fB53\fP of file \fBSourceObj\&.cs\fP\&.
.SS "override \fBSourceObj\&.Row\fP SourceObj\&.CreateRow ()"

.PP
Definition at line \fB8\fP of file \fBSourceObj\&.cs\fP\&.
.SS "string SourceObj\&.GetName (int id)"

.PP
Definition at line \fB83\fP of file \fBSourceObj\&.cs\fP\&.
.SS "override void SourceObj\&.OnAfterImportData ()"

.PP
Definition at line \fB89\fP of file \fBSourceObj\&.cs\fP\&.
.SS "override void SourceObj\&.OnInit ()"

.PP
Definition at line \fB105\fP of file \fBSourceObj\&.cs\fP\&.
.SS "override void SourceObj\&.RestorePref ()"

.PP
Definition at line \fB63\fP of file \fBSourceObj\&.cs\fP\&.
.SS "override void SourceObj\&.SetRow (\fBSourceObj\&.Row\fP r)"

.PP
Definition at line \fB47\fP of file \fBSourceObj\&.cs\fP\&.
.SS "override void SourceObj\&.ValidatePref ()"

.PP
Definition at line \fB74\fP of file \fBSourceObj\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "Dictionary<int, \fBSourceObj\&.Row\fP> SourceObj\&._rows = new Dictionary<int, \fBSourceObj\&.Row\fP>()"

.PP
Definition at line \fB116\fP of file \fBSourceObj\&.cs\fP\&.
.SS "\fBRenderData\fP SourceObj\&.FallbackRenderData\fR [static]\fP"

.PP
Definition at line \fB119\fP of file \fBSourceObj\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
