.TH "SourceHomeResource" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SourceHomeResource
.SH SYNOPSIS
.br
.PP
.PP
Inherits SourceDataString< SourceHomeResource\&.Row >\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRow\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override \fBSourceHomeResource\&.Row\fP \fBCreateRow\fP ()"
.br
.ti -1c
.RI "override void \fBSetRow\fP (\fBSourceHomeResource\&.Row\fP r)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB4\fP of file \fBSourceHomeResource\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override \fBSourceHomeResource\&.Row\fP SourceHomeResource\&.CreateRow ()"

.PP
Definition at line \fB7\fP of file \fBSourceHomeResource\&.cs\fP\&.
.SS "override void SourceHomeResource\&.SetRow (\fBSourceHomeResource\&.Row\fP r)"

.PP
Definition at line \fB23\fP of file \fBSourceHomeResource\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
