.TH "SourceElement.Row" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SourceElement.Row
.SH SYNOPSIS
.br
.PP
.PP
Inherits SourceData\&.BaseRow\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override string \fBGetName\fP ()"
.br
.ti -1c
.RI "Sprite \fBGetSprite\fP ()"
.br
.ti -1c
.RI "void \fBSetImage\fP (Image image)"
.br
.ti -1c
.RI "string \fBGetAltname\fP (int i)"
.br
.ti -1c
.RI "bool \fBIsEncAppliable\fP (\fBThing\fP t, bool isMaterial)"
.br
.ti -1c
.RI "bool \fBIsEncAppliable\fP (\fBThing\fP t)"
.br
.ti -1c
.RI "bool \fBIsEncAppliable\fP (\fBSourceCategory\&.Row\fP cat)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBid\fP"
.br
.ti -1c
.RI "string \fBalias\fP"
.br
.ti -1c
.RI "string \fBname_JP\fP"
.br
.ti -1c
.RI "string \fBname\fP"
.br
.ti -1c
.RI "string \fBaltname_JP\fP"
.br
.ti -1c
.RI "string \fBaltname\fP"
.br
.ti -1c
.RI "string \fBaliasParent\fP"
.br
.ti -1c
.RI "float \fBparentFactor\fP"
.br
.ti -1c
.RI "int \fBlvFactor\fP"
.br
.ti -1c
.RI "int \fBencFactor\fP"
.br
.ti -1c
.RI "int \fBmtp\fP"
.br
.ti -1c
.RI "string \fBaliasRef\fP"
.br
.ti -1c
.RI "string \fBaliasMtp\fP"
.br
.ti -1c
.RI "int \fBsort\fP"
.br
.ti -1c
.RI "string \fBtarget\fP"
.br
.ti -1c
.RI "string[] \fBproc\fP"
.br
.ti -1c
.RI "string \fBtype\fP"
.br
.ti -1c
.RI "string \fBgroup\fP"
.br
.ti -1c
.RI "string \fBcategory\fP"
.br
.ti -1c
.RI "string \fBcategorySub\fP"
.br
.ti -1c
.RI "string[] \fBabilityType\fP"
.br
.ti -1c
.RI "string[] \fBtag\fP"
.br
.ti -1c
.RI "string \fBthing\fP"
.br
.ti -1c
.RI "int \fBeleP\fP"
.br
.ti -1c
.RI "int \fBcooldown\fP"
.br
.ti -1c
.RI "int \fBLV\fP"
.br
.ti -1c
.RI "int \fBchance\fP"
.br
.ti -1c
.RI "int \fBvalue\fP"
.br
.ti -1c
.RI "int[] \fBcost\fP"
.br
.ti -1c
.RI "int \fBcharge\fP"
.br
.ti -1c
.RI "float \fBradius\fP"
.br
.ti -1c
.RI "int \fBmax\fP"
.br
.ti -1c
.RI "string[] \fBreq\fP"
.br
.ti -1c
.RI "string \fBidTrainer\fP"
.br
.ti -1c
.RI "string \fBencSlot\fP"
.br
.ti -1c
.RI "int \fBpartySkill\fP"
.br
.ti -1c
.RI "string \fBtagTrainer\fP"
.br
.ti -1c
.RI "string \fBlevelBonus_JP\fP"
.br
.ti -1c
.RI "string \fBlevelBonus\fP"
.br
.ti -1c
.RI "string[] \fBfoodEffect\fP"
.br
.ti -1c
.RI "string[] \fBlangAct\fP"
.br
.ti -1c
.RI "string \fBdetail_JP\fP"
.br
.ti -1c
.RI "string \fBdetail\fP"
.br
.ti -1c
.RI "string \fBtextPhase_JP\fP"
.br
.ti -1c
.RI "string \fBtextPhase\fP"
.br
.ti -1c
.RI "string \fBtextExtra_JP\fP"
.br
.ti -1c
.RI "string \fBtextExtra\fP"
.br
.ti -1c
.RI "string \fBtextInc_JP\fP"
.br
.ti -1c
.RI "string \fBtextInc\fP"
.br
.ti -1c
.RI "string \fBtextDec_JP\fP"
.br
.ti -1c
.RI "string \fBtextDec\fP"
.br
.ti -1c
.RI "string[] \fBtextAlt_JP\fP"
.br
.ti -1c
.RI "string[] \fBtextAlt\fP"
.br
.ti -1c
.RI "string[] \fBadjective_JP\fP"
.br
.ti -1c
.RI "string[] \fBadjective\fP"
.br
.ti -1c
.RI "bool \fBisAttribute\fP"
.br
.ti -1c
.RI "bool \fBisPrimaryAttribute\fP"
.br
.ti -1c
.RI "bool \fBisSkill\fP"
.br
.ti -1c
.RI "bool \fBisSpell\fP"
.br
.ti -1c
.RI "int \fBidMold\fP"
.br
.ti -1c
.RI "string \fBname_L\fP"
.br
.ti -1c
.RI "string \fBaltname_L\fP"
.br
.ti -1c
.RI "string \fBdetail_L\fP"
.br
.ti -1c
.RI "string \fBtextPhase_L\fP"
.br
.ti -1c
.RI "string \fBtextExtra_L\fP"
.br
.ti -1c
.RI "string \fBtextInc_L\fP"
.br
.ti -1c
.RI "string \fBtextDec_L\fP"
.br
.ti -1c
.RI "string \fBlevelBonus_L\fP"
.br
.ti -1c
.RI "string[] \fBtextAlt_L\fP"
.br
.ti -1c
.RI "string[] \fBadjective_L\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override bool \fBUseAlias\fP\fR [get]\fP"
.br
.ti -1c
.RI "override string \fBGetAlias\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB169\fP of file \fBSourceElement\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "string SourceElement\&.Row\&.GetAltname (int i)"

.PP
Definition at line \fB225\fP of file \fBSourceElement\&.cs\fP\&.
.SS "override string SourceElement\&.Row\&.GetName ()"

.PP
Definition at line \fB192\fP of file \fBSourceElement\&.cs\fP\&.
.SS "Sprite SourceElement\&.Row\&.GetSprite ()"

.PP
Definition at line \fB202\fP of file \fBSourceElement\&.cs\fP\&.
.SS "bool SourceElement\&.Row\&.IsEncAppliable (\fBSourceCategory\&.Row\fP cat)"

.PP
Definition at line \fB267\fP of file \fBSourceElement\&.cs\fP\&.
.SS "bool SourceElement\&.Row\&.IsEncAppliable (\fBThing\fP t)"

.PP
Definition at line \fB245\fP of file \fBSourceElement\&.cs\fP\&.
.SS "bool SourceElement\&.Row\&.IsEncAppliable (\fBThing\fP t, bool isMaterial)"

.PP
Definition at line \fB231\fP of file \fBSourceElement\&.cs\fP\&.
.SS "void SourceElement\&.Row\&.SetImage (Image image)"

.PP
Definition at line \fB213\fP of file \fBSourceElement\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "string [] SourceElement\&.Row\&.abilityType"

.PP
Definition at line \fB355\fP of file \fBSourceElement\&.cs\fP\&.
.SS "string [] SourceElement\&.Row\&.adjective"

.PP
Definition at line \fB457\fP of file \fBSourceElement\&.cs\fP\&.
.SS "string [] SourceElement\&.Row\&.adjective_JP"

.PP
Definition at line \fB454\fP of file \fBSourceElement\&.cs\fP\&.
.SS "string [] SourceElement\&.Row\&.adjective_L"

.PP
Definition at line \fB506\fP of file \fBSourceElement\&.cs\fP\&.
.SS "string SourceElement\&.Row\&.alias"

.PP
Definition at line \fB298\fP of file \fBSourceElement\&.cs\fP\&.
.SS "string SourceElement\&.Row\&.aliasMtp"

.PP
Definition at line \fB331\fP of file \fBSourceElement\&.cs\fP\&.
.SS "string SourceElement\&.Row\&.aliasParent"

.PP
Definition at line \fB313\fP of file \fBSourceElement\&.cs\fP\&.
.SS "string SourceElement\&.Row\&.aliasRef"

.PP
Definition at line \fB328\fP of file \fBSourceElement\&.cs\fP\&.
.SS "string SourceElement\&.Row\&.altname"

.PP
Definition at line \fB310\fP of file \fBSourceElement\&.cs\fP\&.
.SS "string SourceElement\&.Row\&.altname_JP"

.PP
Definition at line \fB307\fP of file \fBSourceElement\&.cs\fP\&.
.SS "string SourceElement\&.Row\&.altname_L"

.PP
Definition at line \fB482\fP of file \fBSourceElement\&.cs\fP\&.
.SS "string SourceElement\&.Row\&.category"

.PP
Definition at line \fB349\fP of file \fBSourceElement\&.cs\fP\&.
.SS "string SourceElement\&.Row\&.categorySub"

.PP
Definition at line \fB352\fP of file \fBSourceElement\&.cs\fP\&.
.SS "int SourceElement\&.Row\&.chance"

.PP
Definition at line \fB373\fP of file \fBSourceElement\&.cs\fP\&.
.SS "int SourceElement\&.Row\&.charge"

.PP
Definition at line \fB382\fP of file \fBSourceElement\&.cs\fP\&.
.SS "int SourceElement\&.Row\&.cooldown"

.PP
Definition at line \fB367\fP of file \fBSourceElement\&.cs\fP\&.
.SS "int [] SourceElement\&.Row\&.cost"

.PP
Definition at line \fB379\fP of file \fBSourceElement\&.cs\fP\&.
.SS "string SourceElement\&.Row\&.detail"

.PP
Definition at line \fB421\fP of file \fBSourceElement\&.cs\fP\&.
.SS "string SourceElement\&.Row\&.detail_JP"

.PP
Definition at line \fB418\fP of file \fBSourceElement\&.cs\fP\&.
.SS "string SourceElement\&.Row\&.detail_L"

.PP
Definition at line \fB485\fP of file \fBSourceElement\&.cs\fP\&.
.SS "int SourceElement\&.Row\&.eleP"

.PP
Definition at line \fB364\fP of file \fBSourceElement\&.cs\fP\&.
.SS "int SourceElement\&.Row\&.encFactor"

.PP
Definition at line \fB322\fP of file \fBSourceElement\&.cs\fP\&.
.SS "string SourceElement\&.Row\&.encSlot"

.PP
Definition at line \fB397\fP of file \fBSourceElement\&.cs\fP\&.
.SS "string [] SourceElement\&.Row\&.foodEffect"

.PP
Definition at line \fB412\fP of file \fBSourceElement\&.cs\fP\&.
.SS "string SourceElement\&.Row\&.group"

.PP
Definition at line \fB346\fP of file \fBSourceElement\&.cs\fP\&.
.SS "int SourceElement\&.Row\&.id"

.PP
Definition at line \fB295\fP of file \fBSourceElement\&.cs\fP\&.
.SS "int SourceElement\&.Row\&.idMold"

.PP
Definition at line \fB476\fP of file \fBSourceElement\&.cs\fP\&.
.SS "string SourceElement\&.Row\&.idTrainer"

.PP
Definition at line \fB394\fP of file \fBSourceElement\&.cs\fP\&.
.SS "bool SourceElement\&.Row\&.isAttribute"

.PP
Definition at line \fB461\fP of file \fBSourceElement\&.cs\fP\&.
.SS "bool SourceElement\&.Row\&.isPrimaryAttribute"

.PP
Definition at line \fB465\fP of file \fBSourceElement\&.cs\fP\&.
.SS "bool SourceElement\&.Row\&.isSkill"

.PP
Definition at line \fB469\fP of file \fBSourceElement\&.cs\fP\&.
.SS "bool SourceElement\&.Row\&.isSpell"

.PP
Definition at line \fB473\fP of file \fBSourceElement\&.cs\fP\&.
.SS "string [] SourceElement\&.Row\&.langAct"

.PP
Definition at line \fB415\fP of file \fBSourceElement\&.cs\fP\&.
.SS "string SourceElement\&.Row\&.levelBonus"

.PP
Definition at line \fB409\fP of file \fBSourceElement\&.cs\fP\&.
.SS "string SourceElement\&.Row\&.levelBonus_JP"

.PP
Definition at line \fB406\fP of file \fBSourceElement\&.cs\fP\&.
.SS "string SourceElement\&.Row\&.levelBonus_L"

.PP
Definition at line \fB500\fP of file \fBSourceElement\&.cs\fP\&.
.SS "int SourceElement\&.Row\&.LV"

.PP
Definition at line \fB370\fP of file \fBSourceElement\&.cs\fP\&.
.SS "int SourceElement\&.Row\&.lvFactor"

.PP
Definition at line \fB319\fP of file \fBSourceElement\&.cs\fP\&.
.SS "int SourceElement\&.Row\&.max"

.PP
Definition at line \fB388\fP of file \fBSourceElement\&.cs\fP\&.
.SS "int SourceElement\&.Row\&.mtp"

.PP
Definition at line \fB325\fP of file \fBSourceElement\&.cs\fP\&.
.SS "string SourceElement\&.Row\&.name"

.PP
Definition at line \fB304\fP of file \fBSourceElement\&.cs\fP\&.
.SS "string SourceElement\&.Row\&.name_JP"

.PP
Definition at line \fB301\fP of file \fBSourceElement\&.cs\fP\&.
.SS "string SourceElement\&.Row\&.name_L"

.PP
Definition at line \fB479\fP of file \fBSourceElement\&.cs\fP\&.
.SS "float SourceElement\&.Row\&.parentFactor"

.PP
Definition at line \fB316\fP of file \fBSourceElement\&.cs\fP\&.
.SS "int SourceElement\&.Row\&.partySkill"

.PP
Definition at line \fB400\fP of file \fBSourceElement\&.cs\fP\&.
.SS "string [] SourceElement\&.Row\&.proc"

.PP
Definition at line \fB340\fP of file \fBSourceElement\&.cs\fP\&.
.SS "float SourceElement\&.Row\&.radius"

.PP
Definition at line \fB385\fP of file \fBSourceElement\&.cs\fP\&.
.SS "string [] SourceElement\&.Row\&.req"

.PP
Definition at line \fB391\fP of file \fBSourceElement\&.cs\fP\&.
.SS "int SourceElement\&.Row\&.sort"

.PP
Definition at line \fB334\fP of file \fBSourceElement\&.cs\fP\&.
.SS "string [] SourceElement\&.Row\&.tag"

.PP
Definition at line \fB358\fP of file \fBSourceElement\&.cs\fP\&.
.SS "string SourceElement\&.Row\&.tagTrainer"

.PP
Definition at line \fB403\fP of file \fBSourceElement\&.cs\fP\&.
.SS "string SourceElement\&.Row\&.target"

.PP
Definition at line \fB337\fP of file \fBSourceElement\&.cs\fP\&.
.SS "string [] SourceElement\&.Row\&.textAlt"

.PP
Definition at line \fB451\fP of file \fBSourceElement\&.cs\fP\&.
.SS "string [] SourceElement\&.Row\&.textAlt_JP"

.PP
Definition at line \fB448\fP of file \fBSourceElement\&.cs\fP\&.
.SS "string [] SourceElement\&.Row\&.textAlt_L"

.PP
Definition at line \fB503\fP of file \fBSourceElement\&.cs\fP\&.
.SS "string SourceElement\&.Row\&.textDec"

.PP
Definition at line \fB445\fP of file \fBSourceElement\&.cs\fP\&.
.SS "string SourceElement\&.Row\&.textDec_JP"

.PP
Definition at line \fB442\fP of file \fBSourceElement\&.cs\fP\&.
.SS "string SourceElement\&.Row\&.textDec_L"

.PP
Definition at line \fB497\fP of file \fBSourceElement\&.cs\fP\&.
.SS "string SourceElement\&.Row\&.textExtra"

.PP
Definition at line \fB433\fP of file \fBSourceElement\&.cs\fP\&.
.SS "string SourceElement\&.Row\&.textExtra_JP"

.PP
Definition at line \fB430\fP of file \fBSourceElement\&.cs\fP\&.
.SS "string SourceElement\&.Row\&.textExtra_L"

.PP
Definition at line \fB491\fP of file \fBSourceElement\&.cs\fP\&.
.SS "string SourceElement\&.Row\&.textInc"

.PP
Definition at line \fB439\fP of file \fBSourceElement\&.cs\fP\&.
.SS "string SourceElement\&.Row\&.textInc_JP"

.PP
Definition at line \fB436\fP of file \fBSourceElement\&.cs\fP\&.
.SS "string SourceElement\&.Row\&.textInc_L"

.PP
Definition at line \fB494\fP of file \fBSourceElement\&.cs\fP\&.
.SS "string SourceElement\&.Row\&.textPhase"

.PP
Definition at line \fB427\fP of file \fBSourceElement\&.cs\fP\&.
.SS "string SourceElement\&.Row\&.textPhase_JP"

.PP
Definition at line \fB424\fP of file \fBSourceElement\&.cs\fP\&.
.SS "string SourceElement\&.Row\&.textPhase_L"

.PP
Definition at line \fB488\fP of file \fBSourceElement\&.cs\fP\&.
.SS "string SourceElement\&.Row\&.thing"

.PP
Definition at line \fB361\fP of file \fBSourceElement\&.cs\fP\&.
.SS "string SourceElement\&.Row\&.type"

.PP
Definition at line \fB343\fP of file \fBSourceElement\&.cs\fP\&.
.SS "int SourceElement\&.Row\&.value"

.PP
Definition at line \fB376\fP of file \fBSourceElement\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "override string SourceElement\&.Row\&.GetAlias\fR [get]\fP"

.PP
Definition at line \fB183\fP of file \fBSourceElement\&.cs\fP\&.
.SS "override bool SourceElement\&.Row\&.UseAlias\fR [get]\fP"

.PP
Definition at line \fB173\fP of file \fBSourceElement\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
