.TH "SourceTactics.Row" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SourceTactics.Row
.SH SYNOPSIS
.br
.PP
.PP
Inherits SourceData\&.BaseRow\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBid\fP"
.br
.ti -1c
.RI "string \fBname_JP\fP"
.br
.ti -1c
.RI "string \fBname\fP"
.br
.ti -1c
.RI "int \fBdist\fP"
.br
.ti -1c
.RI "int \fBmove\fP"
.br
.ti -1c
.RI "int \fBmovePC\fP"
.br
.ti -1c
.RI "int \fBparty\fP"
.br
.ti -1c
.RI "int \fBtaunt\fP"
.br
.ti -1c
.RI "int \fBmelee\fP"
.br
.ti -1c
.RI "int \fBrange\fP"
.br
.ti -1c
.RI "int \fBspell\fP"
.br
.ti -1c
.RI "int \fBheal\fP"
.br
.ti -1c
.RI "int \fBsummon\fP"
.br
.ti -1c
.RI "int \fBbuff\fP"
.br
.ti -1c
.RI "int \fBdebuff\fP"
.br
.ti -1c
.RI "string[] \fBtag\fP"
.br
.ti -1c
.RI "string \fBdetail_JP\fP"
.br
.ti -1c
.RI "string \fBdetail\fP"
.br
.ti -1c
.RI "string \fBname_L\fP"
.br
.ti -1c
.RI "string \fBdetail_L\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override bool \fBUseAlias\fP\fR [get]\fP"
.br
.ti -1c
.RI "override string \fBGetAlias\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB40\fP of file \fBSourceTactics\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int SourceTactics\&.Row\&.buff"

.PP
Definition at line \fB102\fP of file \fBSourceTactics\&.cs\fP\&.
.SS "int SourceTactics\&.Row\&.debuff"

.PP
Definition at line \fB105\fP of file \fBSourceTactics\&.cs\fP\&.
.SS "string SourceTactics\&.Row\&.detail"

.PP
Definition at line \fB114\fP of file \fBSourceTactics\&.cs\fP\&.
.SS "string SourceTactics\&.Row\&.detail_JP"

.PP
Definition at line \fB111\fP of file \fBSourceTactics\&.cs\fP\&.
.SS "string SourceTactics\&.Row\&.detail_L"

.PP
Definition at line \fB120\fP of file \fBSourceTactics\&.cs\fP\&.
.SS "int SourceTactics\&.Row\&.dist"

.PP
Definition at line \fB72\fP of file \fBSourceTactics\&.cs\fP\&.
.SS "int SourceTactics\&.Row\&.heal"

.PP
Definition at line \fB96\fP of file \fBSourceTactics\&.cs\fP\&.
.SS "string SourceTactics\&.Row\&.id"

.PP
Definition at line \fB63\fP of file \fBSourceTactics\&.cs\fP\&.
.SS "int SourceTactics\&.Row\&.melee"

.PP
Definition at line \fB87\fP of file \fBSourceTactics\&.cs\fP\&.
.SS "int SourceTactics\&.Row\&.move"

.PP
Definition at line \fB75\fP of file \fBSourceTactics\&.cs\fP\&.
.SS "int SourceTactics\&.Row\&.movePC"

.PP
Definition at line \fB78\fP of file \fBSourceTactics\&.cs\fP\&.
.SS "string SourceTactics\&.Row\&.name"

.PP
Definition at line \fB69\fP of file \fBSourceTactics\&.cs\fP\&.
.SS "string SourceTactics\&.Row\&.name_JP"

.PP
Definition at line \fB66\fP of file \fBSourceTactics\&.cs\fP\&.
.SS "string SourceTactics\&.Row\&.name_L"

.PP
Definition at line \fB117\fP of file \fBSourceTactics\&.cs\fP\&.
.SS "int SourceTactics\&.Row\&.party"

.PP
Definition at line \fB81\fP of file \fBSourceTactics\&.cs\fP\&.
.SS "int SourceTactics\&.Row\&.range"

.PP
Definition at line \fB90\fP of file \fBSourceTactics\&.cs\fP\&.
.SS "int SourceTactics\&.Row\&.spell"

.PP
Definition at line \fB93\fP of file \fBSourceTactics\&.cs\fP\&.
.SS "int SourceTactics\&.Row\&.summon"

.PP
Definition at line \fB99\fP of file \fBSourceTactics\&.cs\fP\&.
.SS "string [] SourceTactics\&.Row\&.tag"

.PP
Definition at line \fB108\fP of file \fBSourceTactics\&.cs\fP\&.
.SS "int SourceTactics\&.Row\&.taunt"

.PP
Definition at line \fB84\fP of file \fBSourceTactics\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "override string SourceTactics\&.Row\&.GetAlias\fR [get]\fP"

.PP
Definition at line \fB54\fP of file \fBSourceTactics\&.cs\fP\&.
.SS "override bool SourceTactics\&.Row\&.UseAlias\fR [get]\fP"

.PP
Definition at line \fB44\fP of file \fBSourceTactics\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
