.TH "SourceArea" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SourceArea
.SH SYNOPSIS
.br
.PP
.PP
Inherits SourceDataString< SourceArea\&.Row >\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRow\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override \fBSourceArea\&.Row\fP \fBCreateRow\fP ()"
.br
.ti -1c
.RI "override void \fBSetRow\fP (\fBSourceArea\&.Row\fP r)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override string[] \fBImportFields\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB4\fP of file \fBSourceArea\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override \fBSourceArea\&.Row\fP SourceArea\&.CreateRow ()"

.PP
Definition at line \fB7\fP of file \fBSourceArea\&.cs\fP\&.
.SS "override void SourceArea\&.SetRow (\fBSourceArea\&.Row\fP r)"

.PP
Definition at line \fB23\fP of file \fBSourceArea\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "override string [] SourceArea\&.ImportFields\fR [get]\fP"

.PP
Definition at line \fB30\fP of file \fBSourceArea\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
