.TH "SourceRecipe.Row" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SourceRecipe.Row
.SH SYNOPSIS
.br
.PP
.PP
Inherits SourceData\&.BaseRow\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBid\fP"
.br
.ti -1c
.RI "string \fBfactory\fP"
.br
.ti -1c
.RI "string \fBtype\fP"
.br
.ti -1c
.RI "string \fBthing\fP"
.br
.ti -1c
.RI "string \fBnum\fP"
.br
.ti -1c
.RI "int \fBsp\fP"
.br
.ti -1c
.RI "int \fBtime\fP"
.br
.ti -1c
.RI "string[] \fBing1\fP"
.br
.ti -1c
.RI "string[] \fBing2\fP"
.br
.ti -1c
.RI "string[] \fBing3\fP"
.br
.ti -1c
.RI "string[] \fBtag\fP"
.br
.ti -1c
.RI "string \fBname_L\fP"
.br
.ti -1c
.RI "string \fBdetail_L\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override bool \fBUseAlias\fP\fR [get]\fP"
.br
.ti -1c
.RI "override string \fBGetAlias\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB33\fP of file \fBSourceRecipe\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "string SourceRecipe\&.Row\&.detail_L"

.PP
Definition at line \fB92\fP of file \fBSourceRecipe\&.cs\fP\&.
.SS "string SourceRecipe\&.Row\&.factory"

.PP
Definition at line \fB59\fP of file \fBSourceRecipe\&.cs\fP\&.
.SS "int SourceRecipe\&.Row\&.id"

.PP
Definition at line \fB56\fP of file \fBSourceRecipe\&.cs\fP\&.
.SS "string [] SourceRecipe\&.Row\&.ing1"

.PP
Definition at line \fB77\fP of file \fBSourceRecipe\&.cs\fP\&.
.SS "string [] SourceRecipe\&.Row\&.ing2"

.PP
Definition at line \fB80\fP of file \fBSourceRecipe\&.cs\fP\&.
.SS "string [] SourceRecipe\&.Row\&.ing3"

.PP
Definition at line \fB83\fP of file \fBSourceRecipe\&.cs\fP\&.
.SS "string SourceRecipe\&.Row\&.name_L"

.PP
Definition at line \fB89\fP of file \fBSourceRecipe\&.cs\fP\&.
.SS "string SourceRecipe\&.Row\&.num"

.PP
Definition at line \fB68\fP of file \fBSourceRecipe\&.cs\fP\&.
.SS "int SourceRecipe\&.Row\&.sp"

.PP
Definition at line \fB71\fP of file \fBSourceRecipe\&.cs\fP\&.
.SS "string [] SourceRecipe\&.Row\&.tag"

.PP
Definition at line \fB86\fP of file \fBSourceRecipe\&.cs\fP\&.
.SS "string SourceRecipe\&.Row\&.thing"

.PP
Definition at line \fB65\fP of file \fBSourceRecipe\&.cs\fP\&.
.SS "int SourceRecipe\&.Row\&.time"

.PP
Definition at line \fB74\fP of file \fBSourceRecipe\&.cs\fP\&.
.SS "string SourceRecipe\&.Row\&.type"

.PP
Definition at line \fB62\fP of file \fBSourceRecipe\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "override string SourceRecipe\&.Row\&.GetAlias\fR [get]\fP"

.PP
Definition at line \fB47\fP of file \fBSourceRecipe\&.cs\fP\&.
.SS "override bool SourceRecipe\&.Row\&.UseAlias\fR [get]\fP"

.PP
Definition at line \fB37\fP of file \fBSourceRecipe\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
