.TH "SourceJob.Row" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SourceJob.Row
.SH SYNOPSIS
.br
.PP
.PP
Inherits SourceData\&.BaseRow\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBWriteNote\fP (UINote n)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBid\fP"
.br
.ti -1c
.RI "string \fBname_JP\fP"
.br
.ti -1c
.RI "string \fBname\fP"
.br
.ti -1c
.RI "int \fBplayable\fP"
.br
.ti -1c
.RI "int \fBSTR\fP"
.br
.ti -1c
.RI "int \fBEND\fP"
.br
.ti -1c
.RI "int \fBDEX\fP"
.br
.ti -1c
.RI "int \fBPER\fP"
.br
.ti -1c
.RI "int \fBLER\fP"
.br
.ti -1c
.RI "int \fBWIL\fP"
.br
.ti -1c
.RI "int \fBMAG\fP"
.br
.ti -1c
.RI "int \fBCHA\fP"
.br
.ti -1c
.RI "int \fBSPD\fP"
.br
.ti -1c
.RI "int[] \fBelements\fP"
.br
.ti -1c
.RI "string[] \fBweapon\fP"
.br
.ti -1c
.RI "string \fBequip\fP"
.br
.ti -1c
.RI "int[] \fBdomain\fP"
.br
.ti -1c
.RI "string \fBdetail_JP\fP"
.br
.ti -1c
.RI "string \fBdetail\fP"
.br
.ti -1c
.RI "Dictionary< int, int > \fBelementMap\fP"
.br
.ti -1c
.RI "string \fBname_L\fP"
.br
.ti -1c
.RI "string \fBdetail_L\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override bool \fBUseAlias\fP\fR [get]\fP"
.br
.ti -1c
.RI "override string \fBGetAlias\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB60\fP of file \fBSourceJob\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void SourceJob\&.Row\&.WriteNote (UINote n)"

.PP
Definition at line \fB83\fP of file \fBSourceJob\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int SourceJob\&.Row\&.CHA"

.PP
Definition at line \fB125\fP of file \fBSourceJob\&.cs\fP\&.
.SS "string SourceJob\&.Row\&.detail"

.PP
Definition at line \fB146\fP of file \fBSourceJob\&.cs\fP\&.
.SS "string SourceJob\&.Row\&.detail_JP"

.PP
Definition at line \fB143\fP of file \fBSourceJob\&.cs\fP\&.
.SS "string SourceJob\&.Row\&.detail_L"

.PP
Definition at line \fB155\fP of file \fBSourceJob\&.cs\fP\&.
.SS "int SourceJob\&.Row\&.DEX"

.PP
Definition at line \fB110\fP of file \fBSourceJob\&.cs\fP\&.
.SS "int [] SourceJob\&.Row\&.domain"

.PP
Definition at line \fB140\fP of file \fBSourceJob\&.cs\fP\&.
.SS "Dictionary<int, int> SourceJob\&.Row\&.elementMap"

.PP
Definition at line \fB149\fP of file \fBSourceJob\&.cs\fP\&.
.SS "int [] SourceJob\&.Row\&.elements"

.PP
Definition at line \fB131\fP of file \fBSourceJob\&.cs\fP\&.
.SS "int SourceJob\&.Row\&.END"

.PP
Definition at line \fB107\fP of file \fBSourceJob\&.cs\fP\&.
.SS "string SourceJob\&.Row\&.equip"

.PP
Definition at line \fB137\fP of file \fBSourceJob\&.cs\fP\&.
.SS "string SourceJob\&.Row\&.id"

.PP
Definition at line \fB92\fP of file \fBSourceJob\&.cs\fP\&.
.SS "int SourceJob\&.Row\&.LER"

.PP
Definition at line \fB116\fP of file \fBSourceJob\&.cs\fP\&.
.SS "int SourceJob\&.Row\&.MAG"

.PP
Definition at line \fB122\fP of file \fBSourceJob\&.cs\fP\&.
.SS "string SourceJob\&.Row\&.name"

.PP
Definition at line \fB98\fP of file \fBSourceJob\&.cs\fP\&.
.SS "string SourceJob\&.Row\&.name_JP"

.PP
Definition at line \fB95\fP of file \fBSourceJob\&.cs\fP\&.
.SS "string SourceJob\&.Row\&.name_L"

.PP
Definition at line \fB152\fP of file \fBSourceJob\&.cs\fP\&.
.SS "int SourceJob\&.Row\&.PER"

.PP
Definition at line \fB113\fP of file \fBSourceJob\&.cs\fP\&.
.SS "int SourceJob\&.Row\&.playable"

.PP
Definition at line \fB101\fP of file \fBSourceJob\&.cs\fP\&.
.SS "int SourceJob\&.Row\&.SPD"

.PP
Definition at line \fB128\fP of file \fBSourceJob\&.cs\fP\&.
.SS "int SourceJob\&.Row\&.STR"

.PP
Definition at line \fB104\fP of file \fBSourceJob\&.cs\fP\&.
.SS "string [] SourceJob\&.Row\&.weapon"

.PP
Definition at line \fB134\fP of file \fBSourceJob\&.cs\fP\&.
.SS "int SourceJob\&.Row\&.WIL"

.PP
Definition at line \fB119\fP of file \fBSourceJob\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "override string SourceJob\&.Row\&.GetAlias\fR [get]\fP"

.PP
Definition at line \fB74\fP of file \fBSourceJob\&.cs\fP\&.
.SS "override bool SourceJob\&.Row\&.UseAlias\fR [get]\fP"

.PP
Definition at line \fB64\fP of file \fBSourceJob\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
