.TH "SourceStat" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SourceStat
.SH SYNOPSIS
.br
.PP
.PP
Inherits SourceDataInt< SourceStat\&.Row >\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRow\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override \fBSourceStat\&.Row\fP \fBCreateRow\fP ()"
.br
.ti -1c
.RI "override void \fBSetRow\fP (\fBSourceStat\&.Row\fP r)"
.br
.ti -1c
.RI "override void \fBOnInit\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Dictionary< string, List< \fBSourceStat\&.Row\fP > > \fBgroups\fP = new Dictionary<string, List<\fBSourceStat\&.Row\fP>>()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override string[] \fBImportFields\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB5\fP of file \fBSourceStat\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override \fBSourceStat\&.Row\fP SourceStat\&.CreateRow ()"

.PP
Definition at line \fB8\fP of file \fBSourceStat\&.cs\fP\&.
.SS "override void SourceStat\&.OnInit ()"

.PP
Definition at line \fB54\fP of file \fBSourceStat\&.cs\fP\&.
.SS "override void SourceStat\&.SetRow (\fBSourceStat\&.Row\fP r)"

.PP
Definition at line \fB48\fP of file \fBSourceStat\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "Dictionary<string, List<\fBSourceStat\&.Row\fP> > SourceStat\&.groups = new Dictionary<string, List<\fBSourceStat\&.Row\fP>>()"

.PP
Definition at line \fB83\fP of file \fBSourceStat\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "override string [] SourceStat\&.ImportFields\fR [get]\fP"

.PP
Definition at line \fB67\fP of file \fBSourceStat\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
