.TH "SourceBacker" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SourceBacker
.SH SYNOPSIS
.br
.PP
.PP
Inherits SourceDataInt< SourceBacker\&.Row >\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRow\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override \fBSourceBacker\&.Row\fP \fBCreateRow\fP ()"
.br
.ti -1c
.RI "override void \fBSetRow\fP (\fBSourceBacker\&.Row\fP r)"
.br
.ti -1c
.RI "override void \fBOnInit\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "List< \fBSourceBacker\&.Row\fP > \fBlistRemain\fP = new List<\fBSourceBacker\&.Row\fP>()"
.br
.ti -1c
.RI "List< \fBSourceBacker\&.Row\fP > \fBlistLantern\fP = new List<\fBSourceBacker\&.Row\fP>()"
.br
.ti -1c
.RI "List< \fBSourceBacker\&.Row\fP > \fBlistTree\fP = new List<\fBSourceBacker\&.Row\fP>()"
.br
.ti -1c
.RI "List< \fBSourceBacker\&.Row\fP > \fBlistPet\fP = new List<\fBSourceBacker\&.Row\fP>()"
.br
.ti -1c
.RI "List< \fBSourceBacker\&.Row\fP > \fBlistSister\fP = new List<\fBSourceBacker\&.Row\fP>()"
.br
.ti -1c
.RI "List< \fBSourceBacker\&.Row\fP > \fBlistFollower\fP = new List<\fBSourceBacker\&.Row\fP>()"
.br
.ti -1c
.RI "List< \fBSourceBacker\&.Row\fP > \fBlistSnail\fP = new List<\fBSourceBacker\&.Row\fP>()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB5\fP of file \fBSourceBacker\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override \fBSourceBacker\&.Row\fP SourceBacker\&.CreateRow ()"

.PP
Definition at line \fB8\fP of file \fBSourceBacker\&.cs\fP\&.
.SS "override void SourceBacker\&.OnInit ()"

.PP
Definition at line \fB38\fP of file \fBSourceBacker\&.cs\fP\&.
.SS "override void SourceBacker\&.SetRow (\fBSourceBacker\&.Row\fP r)"

.PP
Definition at line \fB32\fP of file \fBSourceBacker\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "List<\fBSourceBacker\&.Row\fP> SourceBacker\&.listFollower = new List<\fBSourceBacker\&.Row\fP>()"

.PP
Definition at line \fB101\fP of file \fBSourceBacker\&.cs\fP\&.
.SS "List<\fBSourceBacker\&.Row\fP> SourceBacker\&.listLantern = new List<\fBSourceBacker\&.Row\fP>()"

.PP
Definition at line \fB85\fP of file \fBSourceBacker\&.cs\fP\&.
.SS "List<\fBSourceBacker\&.Row\fP> SourceBacker\&.listPet = new List<\fBSourceBacker\&.Row\fP>()"

.PP
Definition at line \fB93\fP of file \fBSourceBacker\&.cs\fP\&.
.SS "List<\fBSourceBacker\&.Row\fP> SourceBacker\&.listRemain = new List<\fBSourceBacker\&.Row\fP>()"

.PP
Definition at line \fB81\fP of file \fBSourceBacker\&.cs\fP\&.
.SS "List<\fBSourceBacker\&.Row\fP> SourceBacker\&.listSister = new List<\fBSourceBacker\&.Row\fP>()"

.PP
Definition at line \fB97\fP of file \fBSourceBacker\&.cs\fP\&.
.SS "List<\fBSourceBacker\&.Row\fP> SourceBacker\&.listSnail = new List<\fBSourceBacker\&.Row\fP>()"

.PP
Definition at line \fB105\fP of file \fBSourceBacker\&.cs\fP\&.
.SS "List<\fBSourceBacker\&.Row\fP> SourceBacker\&.listTree = new List<\fBSourceBacker\&.Row\fP>()"

.PP
Definition at line \fB89\fP of file \fBSourceBacker\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
