.TH "SourceCharaText.Row" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SourceCharaText.Row
.SH SYNOPSIS
.br
.PP
.PP
Inherits SourceData\&.BaseRow\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBid\fP"
.br
.ti -1c
.RI "string \fBcalm_JP\fP"
.br
.ti -1c
.RI "string \fBfov_JP\fP"
.br
.ti -1c
.RI "string \fBaggro_JP\fP"
.br
.ti -1c
.RI "string \fBdead_JP\fP"
.br
.ti -1c
.RI "string \fBkill_JP\fP"
.br
.ti -1c
.RI "string \fBcalm\fP"
.br
.ti -1c
.RI "string \fBfov\fP"
.br
.ti -1c
.RI "string \fBaggro\fP"
.br
.ti -1c
.RI "string \fBdead\fP"
.br
.ti -1c
.RI "string \fBkill\fP"
.br
.ti -1c
.RI "string \fBcalm_L\fP"
.br
.ti -1c
.RI "string \fBfov_L\fP"
.br
.ti -1c
.RI "string \fBaggro_L\fP"
.br
.ti -1c
.RI "string \fBdead_L\fP"
.br
.ti -1c
.RI "string \fBkill_L\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override bool \fBUseAlias\fP\fR [get]\fP"
.br
.ti -1c
.RI "override string \fBGetAlias\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB50\fP of file \fBSourceCharaText\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "string SourceCharaText\&.Row\&.aggro"

.PP
Definition at line \fB97\fP of file \fBSourceCharaText\&.cs\fP\&.
.SS "string SourceCharaText\&.Row\&.aggro_JP"

.PP
Definition at line \fB82\fP of file \fBSourceCharaText\&.cs\fP\&.
.SS "string SourceCharaText\&.Row\&.aggro_L"

.PP
Definition at line \fB112\fP of file \fBSourceCharaText\&.cs\fP\&.
.SS "string SourceCharaText\&.Row\&.calm"

.PP
Definition at line \fB91\fP of file \fBSourceCharaText\&.cs\fP\&.
.SS "string SourceCharaText\&.Row\&.calm_JP"

.PP
Definition at line \fB76\fP of file \fBSourceCharaText\&.cs\fP\&.
.SS "string SourceCharaText\&.Row\&.calm_L"

.PP
Definition at line \fB106\fP of file \fBSourceCharaText\&.cs\fP\&.
.SS "string SourceCharaText\&.Row\&.dead"

.PP
Definition at line \fB100\fP of file \fBSourceCharaText\&.cs\fP\&.
.SS "string SourceCharaText\&.Row\&.dead_JP"

.PP
Definition at line \fB85\fP of file \fBSourceCharaText\&.cs\fP\&.
.SS "string SourceCharaText\&.Row\&.dead_L"

.PP
Definition at line \fB115\fP of file \fBSourceCharaText\&.cs\fP\&.
.SS "string SourceCharaText\&.Row\&.fov"

.PP
Definition at line \fB94\fP of file \fBSourceCharaText\&.cs\fP\&.
.SS "string SourceCharaText\&.Row\&.fov_JP"

.PP
Definition at line \fB79\fP of file \fBSourceCharaText\&.cs\fP\&.
.SS "string SourceCharaText\&.Row\&.fov_L"

.PP
Definition at line \fB109\fP of file \fBSourceCharaText\&.cs\fP\&.
.SS "string SourceCharaText\&.Row\&.id"

.PP
Definition at line \fB73\fP of file \fBSourceCharaText\&.cs\fP\&.
.SS "string SourceCharaText\&.Row\&.kill"

.PP
Definition at line \fB103\fP of file \fBSourceCharaText\&.cs\fP\&.
.SS "string SourceCharaText\&.Row\&.kill_JP"

.PP
Definition at line \fB88\fP of file \fBSourceCharaText\&.cs\fP\&.
.SS "string SourceCharaText\&.Row\&.kill_L"

.PP
Definition at line \fB118\fP of file \fBSourceCharaText\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "override string SourceCharaText\&.Row\&.GetAlias\fR [get]\fP"

.PP
Definition at line \fB64\fP of file \fBSourceCharaText\&.cs\fP\&.
.SS "override bool SourceCharaText\&.Row\&.UseAlias\fR [get]\fP"

.PP
Definition at line \fB54\fP of file \fBSourceCharaText\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
