.TH "SourceReligion.Row" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SourceReligion.Row
.SH SYNOPSIS
.br
.PP
.PP
Inherits SourceData\&.BaseRow\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBid\fP"
.br
.ti -1c
.RI "string \fBname_JP\fP"
.br
.ti -1c
.RI "string \fBname\fP"
.br
.ti -1c
.RI "string[] \fBname2_JP\fP"
.br
.ti -1c
.RI "string[] \fBname2\fP"
.br
.ti -1c
.RI "string \fBtype\fP"
.br
.ti -1c
.RI "string \fBidMaterial\fP"
.br
.ti -1c
.RI "string \fBfaith\fP"
.br
.ti -1c
.RI "string \fBdomain\fP"
.br
.ti -1c
.RI "int \fBtax\fP"
.br
.ti -1c
.RI "int \fBrelation\fP"
.br
.ti -1c
.RI "int[] \fBelements\fP"
.br
.ti -1c
.RI "string[] \fBcat_offer\fP"
.br
.ti -1c
.RI "string[] \fBrewards\fP"
.br
.ti -1c
.RI "string \fBtextType_JP\fP"
.br
.ti -1c
.RI "string \fBtextType\fP"
.br
.ti -1c
.RI "string \fBtextAvatar\fP"
.br
.ti -1c
.RI "string \fBdetail_JP\fP"
.br
.ti -1c
.RI "string \fBdetail\fP"
.br
.ti -1c
.RI "string \fBtextBenefit_JP\fP"
.br
.ti -1c
.RI "string \fBtextBenefit\fP"
.br
.ti -1c
.RI "string \fBtextPet_JP\fP"
.br
.ti -1c
.RI "string \fBtextPet\fP"
.br
.ti -1c
.RI "string \fBname_L\fP"
.br
.ti -1c
.RI "string \fBdetail_L\fP"
.br
.ti -1c
.RI "string \fBtextType_L\fP"
.br
.ti -1c
.RI "string \fBtextBenefit_L\fP"
.br
.ti -1c
.RI "string[] \fBname2_L\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override bool \fBUseAlias\fP\fR [get]\fP"
.br
.ti -1c
.RI "override string \fBGetAlias\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB60\fP of file \fBSourceReligion\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "string [] SourceReligion\&.Row\&.cat_offer"

.PP
Definition at line \fB119\fP of file \fBSourceReligion\&.cs\fP\&.
.SS "string SourceReligion\&.Row\&.detail"

.PP
Definition at line \fB137\fP of file \fBSourceReligion\&.cs\fP\&.
.SS "string SourceReligion\&.Row\&.detail_JP"

.PP
Definition at line \fB134\fP of file \fBSourceReligion\&.cs\fP\&.
.SS "string SourceReligion\&.Row\&.detail_L"

.PP
Definition at line \fB155\fP of file \fBSourceReligion\&.cs\fP\&.
.SS "string SourceReligion\&.Row\&.domain"

.PP
Definition at line \fB107\fP of file \fBSourceReligion\&.cs\fP\&.
.SS "int [] SourceReligion\&.Row\&.elements"

.PP
Definition at line \fB116\fP of file \fBSourceReligion\&.cs\fP\&.
.SS "string SourceReligion\&.Row\&.faith"

.PP
Definition at line \fB104\fP of file \fBSourceReligion\&.cs\fP\&.
.SS "string SourceReligion\&.Row\&.id"

.PP
Definition at line \fB83\fP of file \fBSourceReligion\&.cs\fP\&.
.SS "string SourceReligion\&.Row\&.idMaterial"

.PP
Definition at line \fB101\fP of file \fBSourceReligion\&.cs\fP\&.
.SS "string SourceReligion\&.Row\&.name"

.PP
Definition at line \fB89\fP of file \fBSourceReligion\&.cs\fP\&.
.SS "string [] SourceReligion\&.Row\&.name2"

.PP
Definition at line \fB95\fP of file \fBSourceReligion\&.cs\fP\&.
.SS "string [] SourceReligion\&.Row\&.name2_JP"

.PP
Definition at line \fB92\fP of file \fBSourceReligion\&.cs\fP\&.
.SS "string [] SourceReligion\&.Row\&.name2_L"

.PP
Definition at line \fB164\fP of file \fBSourceReligion\&.cs\fP\&.
.SS "string SourceReligion\&.Row\&.name_JP"

.PP
Definition at line \fB86\fP of file \fBSourceReligion\&.cs\fP\&.
.SS "string SourceReligion\&.Row\&.name_L"

.PP
Definition at line \fB152\fP of file \fBSourceReligion\&.cs\fP\&.
.SS "int SourceReligion\&.Row\&.relation"

.PP
Definition at line \fB113\fP of file \fBSourceReligion\&.cs\fP\&.
.SS "string [] SourceReligion\&.Row\&.rewards"

.PP
Definition at line \fB122\fP of file \fBSourceReligion\&.cs\fP\&.
.SS "int SourceReligion\&.Row\&.tax"

.PP
Definition at line \fB110\fP of file \fBSourceReligion\&.cs\fP\&.
.SS "string SourceReligion\&.Row\&.textAvatar"

.PP
Definition at line \fB131\fP of file \fBSourceReligion\&.cs\fP\&.
.SS "string SourceReligion\&.Row\&.textBenefit"

.PP
Definition at line \fB143\fP of file \fBSourceReligion\&.cs\fP\&.
.SS "string SourceReligion\&.Row\&.textBenefit_JP"

.PP
Definition at line \fB140\fP of file \fBSourceReligion\&.cs\fP\&.
.SS "string SourceReligion\&.Row\&.textBenefit_L"

.PP
Definition at line \fB161\fP of file \fBSourceReligion\&.cs\fP\&.
.SS "string SourceReligion\&.Row\&.textPet"

.PP
Definition at line \fB149\fP of file \fBSourceReligion\&.cs\fP\&.
.SS "string SourceReligion\&.Row\&.textPet_JP"

.PP
Definition at line \fB146\fP of file \fBSourceReligion\&.cs\fP\&.
.SS "string SourceReligion\&.Row\&.textType"

.PP
Definition at line \fB128\fP of file \fBSourceReligion\&.cs\fP\&.
.SS "string SourceReligion\&.Row\&.textType_JP"

.PP
Definition at line \fB125\fP of file \fBSourceReligion\&.cs\fP\&.
.SS "string SourceReligion\&.Row\&.textType_L"

.PP
Definition at line \fB158\fP of file \fBSourceReligion\&.cs\fP\&.
.SS "string SourceReligion\&.Row\&.type"

.PP
Definition at line \fB98\fP of file \fBSourceReligion\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "override string SourceReligion\&.Row\&.GetAlias\fR [get]\fP"

.PP
Definition at line \fB74\fP of file \fBSourceReligion\&.cs\fP\&.
.SS "override bool SourceReligion\&.Row\&.UseAlias\fR [get]\fP"

.PP
Definition at line \fB64\fP of file \fBSourceReligion\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
