.TH "SourceObj.Stage" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SourceObj.Stage
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBstep\fP"
.br
.ti -1c
.RI "int[] \fBtiles\fP"
.br
.ti -1c
.RI "string \fBidThing\fP"
.br
.ti -1c
.RI "bool \fBharvest\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB226\fP of file \fBSourceObj\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "bool SourceObj\&.Stage\&.harvest"

.PP
Definition at line \fB238\fP of file \fBSourceObj\&.cs\fP\&.
.SS "string SourceObj\&.Stage\&.idThing"

.PP
Definition at line \fB235\fP of file \fBSourceObj\&.cs\fP\&.
.SS "int SourceObj\&.Stage\&.step"

.PP
Definition at line \fB229\fP of file \fBSourceObj\&.cs\fP\&.
.SS "int [] SourceObj\&.Stage\&.tiles"

.PP
Definition at line \fB232\fP of file \fBSourceObj\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
