.TH "SourceCategory.Row" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SourceCategory.Row
.SH SYNOPSIS
.br
.PP
.PP
Inherits SourceData\&.BaseRow\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBIsChildOf\fP (string id)"
.br
.ti -1c
.RI "bool \fBIsChildOf\fP (\fBSourceCategory\&.Row\fP r)"
.br
.ti -1c
.RI "bool \fBIsChildOf\fP (int _uid)"
.br
.ti -1c
.RI "bool \fBContatin\fP (int _uid)"
.br
.ti -1c
.RI "\fBSourceCategory\&.Row\fP \fBGetRoot\fP ()"
.br
.ti -1c
.RI "\fBSourceCategory\&.Row\fP \fBGetSecondRoot\fP ()"
.br
.ti -1c
.RI "string \fBGetIdThing\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBid\fP"
.br
.ti -1c
.RI "int \fBuid\fP"
.br
.ti -1c
.RI "string \fBname_JP\fP"
.br
.ti -1c
.RI "string \fBname\fP"
.br
.ti -1c
.RI "string \fB_parent\fP"
.br
.ti -1c
.RI "string \fBrecipeCat\fP"
.br
.ti -1c
.RI "int \fBslot\fP"
.br
.ti -1c
.RI "int \fBskill\fP"
.br
.ti -1c
.RI "int \fBmaxStack\fP"
.br
.ti -1c
.RI "int \fBtileDummy\fP"
.br
.ti -1c
.RI "bool \fBinstallOne\fP"
.br
.ti -1c
.RI "int \fBignoreBless\fP"
.br
.ti -1c
.RI "string[] \fBtag\fP"
.br
.ti -1c
.RI "string \fBidThing\fP"
.br
.ti -1c
.RI "string[] \fBrecycle\fP"
.br
.ti -1c
.RI "int \fBcostSP\fP"
.br
.ti -1c
.RI "int \fBgift\fP"
.br
.ti -1c
.RI "int \fBdeliver\fP"
.br
.ti -1c
.RI "int \fBoffer\fP"
.br
.ti -1c
.RI "int \fBticket\fP"
.br
.ti -1c
.RI "int \fBsortVal\fP"
.br
.ti -1c
.RI "int \fBflag\fP"
.br
.ti -1c
.RI "\fBSourceCategory\&.Row\fP \fBparent\fP"
.br
.ti -1c
.RI "List< \fBSourceCategory\&.Row\fP > \fBchildren\fP"
.br
.ti -1c
.RI "string \fBname_L\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override bool \fBUseAlias\fP\fR [get]\fP"
.br
.ti -1c
.RI "override string \fBGetAlias\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB63\fP of file \fBSourceCategory\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "bool SourceCategory\&.Row\&.Contatin (int _uid)"

.PP
Definition at line \fB104\fP of file \fBSourceCategory\&.cs\fP\&.
.SS "string SourceCategory\&.Row\&.GetIdThing ()"

.PP
Definition at line \fB144\fP of file \fBSourceCategory\&.cs\fP\&.
.SS "\fBSourceCategory\&.Row\fP SourceCategory\&.Row\&.GetRoot ()"

.PP
Definition at line \fB124\fP of file \fBSourceCategory\&.cs\fP\&.
.SS "\fBSourceCategory\&.Row\fP SourceCategory\&.Row\&.GetSecondRoot ()"

.PP
Definition at line \fB134\fP of file \fBSourceCategory\&.cs\fP\&.
.SS "bool SourceCategory\&.Row\&.IsChildOf (int _uid)"

.PP
Definition at line \fB98\fP of file \fBSourceCategory\&.cs\fP\&.
.SS "bool SourceCategory\&.Row\&.IsChildOf (\fBSourceCategory\&.Row\fP r)"

.PP
Definition at line \fB92\fP of file \fBSourceCategory\&.cs\fP\&.
.SS "bool SourceCategory\&.Row\&.IsChildOf (string id)"

.PP
Definition at line \fB86\fP of file \fBSourceCategory\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "string SourceCategory\&.Row\&._parent"

.PP
Definition at line \fB166\fP of file \fBSourceCategory\&.cs\fP\&.
.SS "List<\fBSourceCategory\&.Row\fP> SourceCategory\&.Row\&.children"

.PP
Definition at line \fB225\fP of file \fBSourceCategory\&.cs\fP\&.
.SS "int SourceCategory\&.Row\&.costSP"

.PP
Definition at line \fB199\fP of file \fBSourceCategory\&.cs\fP\&.
.SS "int SourceCategory\&.Row\&.deliver"

.PP
Definition at line \fB205\fP of file \fBSourceCategory\&.cs\fP\&.
.SS "int SourceCategory\&.Row\&.flag"

.PP
Definition at line \fB217\fP of file \fBSourceCategory\&.cs\fP\&.
.SS "int SourceCategory\&.Row\&.gift"

.PP
Definition at line \fB202\fP of file \fBSourceCategory\&.cs\fP\&.
.SS "string SourceCategory\&.Row\&.id"

.PP
Definition at line \fB154\fP of file \fBSourceCategory\&.cs\fP\&.
.SS "string SourceCategory\&.Row\&.idThing"

.PP
Definition at line \fB193\fP of file \fBSourceCategory\&.cs\fP\&.
.SS "int SourceCategory\&.Row\&.ignoreBless"

.PP
Definition at line \fB187\fP of file \fBSourceCategory\&.cs\fP\&.
.SS "bool SourceCategory\&.Row\&.installOne"

.PP
Definition at line \fB184\fP of file \fBSourceCategory\&.cs\fP\&.
.SS "int SourceCategory\&.Row\&.maxStack"

.PP
Definition at line \fB178\fP of file \fBSourceCategory\&.cs\fP\&.
.SS "string SourceCategory\&.Row\&.name"

.PP
Definition at line \fB163\fP of file \fBSourceCategory\&.cs\fP\&.
.SS "string SourceCategory\&.Row\&.name_JP"

.PP
Definition at line \fB160\fP of file \fBSourceCategory\&.cs\fP\&.
.SS "string SourceCategory\&.Row\&.name_L"

.PP
Definition at line \fB228\fP of file \fBSourceCategory\&.cs\fP\&.
.SS "int SourceCategory\&.Row\&.offer"

.PP
Definition at line \fB208\fP of file \fBSourceCategory\&.cs\fP\&.
.SS "\fBSourceCategory\&.Row\fP SourceCategory\&.Row\&.parent"

.PP
Definition at line \fB221\fP of file \fBSourceCategory\&.cs\fP\&.
.SS "string SourceCategory\&.Row\&.recipeCat"

.PP
Definition at line \fB169\fP of file \fBSourceCategory\&.cs\fP\&.
.SS "string [] SourceCategory\&.Row\&.recycle"

.PP
Definition at line \fB196\fP of file \fBSourceCategory\&.cs\fP\&.
.SS "int SourceCategory\&.Row\&.skill"

.PP
Definition at line \fB175\fP of file \fBSourceCategory\&.cs\fP\&.
.SS "int SourceCategory\&.Row\&.slot"

.PP
Definition at line \fB172\fP of file \fBSourceCategory\&.cs\fP\&.
.SS "int SourceCategory\&.Row\&.sortVal"

.PP
Definition at line \fB214\fP of file \fBSourceCategory\&.cs\fP\&.
.SS "string [] SourceCategory\&.Row\&.tag"

.PP
Definition at line \fB190\fP of file \fBSourceCategory\&.cs\fP\&.
.SS "int SourceCategory\&.Row\&.ticket"

.PP
Definition at line \fB211\fP of file \fBSourceCategory\&.cs\fP\&.
.SS "int SourceCategory\&.Row\&.tileDummy"

.PP
Definition at line \fB181\fP of file \fBSourceCategory\&.cs\fP\&.
.SS "int SourceCategory\&.Row\&.uid"

.PP
Definition at line \fB157\fP of file \fBSourceCategory\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "override string SourceCategory\&.Row\&.GetAlias\fR [get]\fP"

.PP
Definition at line \fB77\fP of file \fBSourceCategory\&.cs\fP\&.
.SS "override bool SourceCategory\&.Row\&.UseAlias\fR [get]\fP"

.PP
Definition at line \fB67\fP of file \fBSourceCategory\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
