.TH "SourceAsset.Prefs" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SourceAsset.Prefs
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBversion\fP"
.br
.ti -1c
.RI "\fBSourceAsset\&.PrefData\fP \fBthings\fP = new \fBSourceAsset\&.PrefData\fP()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB90\fP of file \fBSourceAsset\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBSourceAsset\&.PrefData\fP SourceAsset\&.Prefs\&.things = new \fBSourceAsset\&.PrefData\fP()"

.PP
Definition at line \fB96\fP of file \fBSourceAsset\&.cs\fP\&.
.SS "int SourceAsset\&.Prefs\&.version"

.PP
Definition at line \fB93\fP of file \fBSourceAsset\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
