.TH "SourceThingV" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SourceThingV
.SH SYNOPSIS
.br
.PP
.PP
Inherits SourceDataString< SourceThingV\&.Row >\&.
.PP
Inherited by \fBSourceFood\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRow\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override \fBSourceThingV\&.Row\fP \fBCreateRow\fP ()"
.br
.ti -1c
.RI "override void \fBSetRow\fP (\fBSourceThingV\&.Row\fP r)"
.br
.ti -1c
.RI "override void \fBRestorePref\fP ()"
.br
.ti -1c
.RI "override void \fBValidatePref\fP ()"
.br
.ti -1c
.RI "override void \fBOnAfterImportData\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnImportRow\fP (\fBSourceThingV\&.Row\fP _r, \fBSourceThing\&.Row\fP c)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override string[] \fBImportFields\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB7\fP of file \fBSourceThingV\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override \fBSourceThingV\&.Row\fP SourceThingV\&.CreateRow ()"

.PP
Definition at line \fB10\fP of file \fBSourceThingV\&.cs\fP\&.
.SS "override void SourceThingV\&.OnAfterImportData ()"

.PP
Definition at line \fB86\fP of file \fBSourceThingV\&.cs\fP\&.
.SS "virtual void SourceThingV\&.OnImportRow (\fBSourceThingV\&.Row\fP _r, \fBSourceThing\&.Row\fP c)\fR [virtual]\fP"

.PP
Definition at line \fB338\fP of file \fBSourceThingV\&.cs\fP\&.
.SS "override void SourceThingV\&.RestorePref ()"

.PP
Definition at line \fB47\fP of file \fBSourceThingV\&.cs\fP\&.
.SS "override void SourceThingV\&.SetRow (\fBSourceThingV\&.Row\fP r)"

.PP
Definition at line \fB41\fP of file \fBSourceThingV\&.cs\fP\&.
.SS "override void SourceThingV\&.ValidatePref ()"

.PP
Definition at line \fB77\fP of file \fBSourceThingV\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "override string [] SourceThingV\&.ImportFields\fR [get]\fP"

.PP
Definition at line \fB344\fP of file \fBSourceThingV\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
