.TH "SourceCheck.Row" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SourceCheck.Row
.SH SYNOPSIS
.br
.PP
.PP
Inherits SourceData\&.BaseRow\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBid\fP"
.br
.ti -1c
.RI "int \fBelement\fP"
.br
.ti -1c
.RI "int \fBtargetElement\fP"
.br
.ti -1c
.RI "float \fBsubFactor\fP"
.br
.ti -1c
.RI "float \fBtargetSubFactor\fP"
.br
.ti -1c
.RI "int \fBbaseDC\fP"
.br
.ti -1c
.RI "int \fBcritRange\fP"
.br
.ti -1c
.RI "int \fBfumbleRange\fP"
.br
.ti -1c
.RI "int \fBdice\fP"
.br
.ti -1c
.RI "float \fBlvMod\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override bool \fBUseAlias\fP\fR [get]\fP"
.br
.ti -1c
.RI "override string \fBGetAlias\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB32\fP of file \fBSourceCheck\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int SourceCheck\&.Row\&.baseDC"

.PP
Definition at line \fB70\fP of file \fBSourceCheck\&.cs\fP\&.
.SS "int SourceCheck\&.Row\&.critRange"

.PP
Definition at line \fB73\fP of file \fBSourceCheck\&.cs\fP\&.
.SS "int SourceCheck\&.Row\&.dice"

.PP
Definition at line \fB79\fP of file \fBSourceCheck\&.cs\fP\&.
.SS "int SourceCheck\&.Row\&.element"

.PP
Definition at line \fB58\fP of file \fBSourceCheck\&.cs\fP\&.
.SS "int SourceCheck\&.Row\&.fumbleRange"

.PP
Definition at line \fB76\fP of file \fBSourceCheck\&.cs\fP\&.
.SS "string SourceCheck\&.Row\&.id"

.PP
Definition at line \fB55\fP of file \fBSourceCheck\&.cs\fP\&.
.SS "float SourceCheck\&.Row\&.lvMod"

.PP
Definition at line \fB82\fP of file \fBSourceCheck\&.cs\fP\&.
.SS "float SourceCheck\&.Row\&.subFactor"

.PP
Definition at line \fB64\fP of file \fBSourceCheck\&.cs\fP\&.
.SS "int SourceCheck\&.Row\&.targetElement"

.PP
Definition at line \fB61\fP of file \fBSourceCheck\&.cs\fP\&.
.SS "float SourceCheck\&.Row\&.targetSubFactor"

.PP
Definition at line \fB67\fP of file \fBSourceCheck\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "override string SourceCheck\&.Row\&.GetAlias\fR [get]\fP"

.PP
Definition at line \fB46\fP of file \fBSourceCheck\&.cs\fP\&.
.SS "override bool SourceCheck\&.Row\&.UseAlias\fR [get]\fP"

.PP
Definition at line \fB36\fP of file \fBSourceCheck\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
