.TH "SourceHobby" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SourceHobby
.SH SYNOPSIS
.br
.PP
.PP
Inherits SourceDataInt< SourceHobby\&.Row >\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRow\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override \fBSourceHobby\&.Row\fP \fBCreateRow\fP ()"
.br
.ti -1c
.RI "override void \fBSetRow\fP (\fBSourceHobby\&.Row\fP r)"
.br
.ti -1c
.RI "override void \fBOnInit\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "List< \fBSourceHobby\&.Row\fP > \fBlistHobbies\fP = new List<\fBSourceHobby\&.Row\fP>()"
.br
.ti -1c
.RI "List< \fBSourceHobby\&.Row\fP > \fBlistWorks\fP = new List<\fBSourceHobby\&.Row\fP>()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB5\fP of file \fBSourceHobby\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override \fBSourceHobby\&.Row\fP SourceHobby\&.CreateRow ()"

.PP
Definition at line \fB8\fP of file \fBSourceHobby\&.cs\fP\&.
.SS "override void SourceHobby\&.OnInit ()"

.PP
Definition at line \fB42\fP of file \fBSourceHobby\&.cs\fP\&.
.SS "override void SourceHobby\&.SetRow (\fBSourceHobby\&.Row\fP r)"

.PP
Definition at line \fB36\fP of file \fBSourceHobby\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "List<\fBSourceHobby\&.Row\fP> SourceHobby\&.listHobbies = new List<\fBSourceHobby\&.Row\fP>()"

.PP
Definition at line \fB71\fP of file \fBSourceHobby\&.cs\fP\&.
.SS "List<\fBSourceHobby\&.Row\fP> SourceHobby\&.listWorks = new List<\fBSourceHobby\&.Row\fP>()"

.PP
Definition at line \fB75\fP of file \fBSourceHobby\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
