.TH "SourceThing.Row" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SourceThing.Row
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCardRow\fP\&.
.PP
Inherited by \fBSourceThingV\&.Row\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnImportData\fP (SourceData data)"
.br
.ti -1c
.RI "override void \fBSetTiles\fP ()"
.br
.ti -1c
.RI "override string \fBGetName\fP (\fBSourceMaterial\&.Row\fP mat, int sum)"
.br
.ti -1c
.RI "override string \fBGetName\fP ()"
.br
.ti -1c
.RI "override string \fBGetSearchName\fP (bool jp)"
.br
.in -1c

Public Member Functions inherited from \fBCardRow\fP
.in +1c
.ti -1c
.RI "override \fBSourcePref\fP \fBGetPref\fP ()"
.br
.ti -1c
.RI "override void \fBOnImportData\fP (SourceData data)"
.br
.ti -1c
.RI "virtual string \fBGetName\fP (int i)"
.br
.ti -1c
.RI "override string \fBGetEditorListName\fP ()"
.br
.ti -1c
.RI "override string \fBGetName\fP ()"
.br
.ti -1c
.RI "string \fBGetName\fP (\fBCard\fP c, bool full=false)"
.br
.in -1c

Public Member Functions inherited from \fBRenderRow\fP
.in +1c
.ti -1c
.RI "bool \fBHasTag\fP (CTAG _tag)"
.br
.ti -1c
.RI "bool \fBContainsTag\fP (string _tag)"
.br
.ti -1c
.RI "override void \fBOnImportData\fP (SourceData data)"
.br
.ti -1c
.RI "void \fBSetRenderData\fP ()"
.br
.ti -1c
.RI "int \fBConvertTile\fP (int tile)"
.br
.ti -1c
.RI "Sprite \fBGetSprite\fP (int dir=0, int skin=0, bool snow=false)"
.br
.ti -1c
.RI "void \fBSetSpriteRenderer\fP (SpriteRenderer sr, Sprite sprite=null, int matCol=0, bool setTransform=true, int dir=0)"
.br
.ti -1c
.RI "void \fBSetImage\fP (Image image, Sprite sprite=null, int matCol=0, bool setNativeSize=true, int dir=0, int idSkin=0)"
.br
.ti -1c
.RI "void \fBSetRenderParam\fP (\fBRenderParam\fP p, \fBSourceMaterial\&.Row\fP mat, int dir)"
.br
.ti -1c
.RI "virtual unsafe \fBRenderParam\fP \fBGetRenderParam\fP (\fBSourceMaterial\&.Row\fP mat, int dir, \fBPoint\fP point=null, int bridgeHeight=\-1)"
.br
.ti -1c
.RI "virtual int \fBGetTile\fP (\fBSourceMaterial\&.Row\fP mat, int dir=0)"
.br
.ti -1c
.RI "int \fBGetColorInt\fP (\fBSourceMaterial\&.Row\fP mat)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBunknown_JP\fP"
.br
.ti -1c
.RI "string \fBunit_JP\fP"
.br
.ti -1c
.RI "string \fBnaming\fP"
.br
.ti -1c
.RI "string \fBunit\fP"
.br
.ti -1c
.RI "string \fBunknown\fP"
.br
.ti -1c
.RI "int[] \fBaltTiles\fP"
.br
.ti -1c
.RI "int[] \fBanime\fP"
.br
.ti -1c
.RI "string[] \fBdisassemble\fP"
.br
.ti -1c
.RI "int \fBHP\fP"
.br
.ti -1c
.RI "int \fBweight\fP"
.br
.ti -1c
.RI "int \fBelectricity\fP"
.br
.ti -1c
.RI "int \fBrange\fP"
.br
.ti -1c
.RI "string \fBattackType\fP"
.br
.ti -1c
.RI "int[] \fBoffense\fP"
.br
.ti -1c
.RI "int[] \fBsubstats\fP"
.br
.ti -1c
.RI "int[] \fBdefense\fP"
.br
.ti -1c
.RI "string \fBidToggleExtra\fP"
.br
.ti -1c
.RI "string \fBidActorEx\fP"
.br
.ti -1c
.RI "string \fBworkTag\fP"
.br
.ti -1c
.RI "string[] \fBroomName_JP\fP"
.br
.ti -1c
.RI "string[] \fBroomName\fP"
.br
.ti -1c
.RI "int[] \fB_altTiles\fP"
.br
.ti -1c
.RI "bool \fBignoreAltFix\fP"
.br
.ti -1c
.RI "string \fBname_L\fP"
.br
.ti -1c
.RI "string \fBdetail_L\fP"
.br
.ti -1c
.RI "string \fBunit_L\fP"
.br
.ti -1c
.RI "string \fBunknown_L\fP"
.br
.ti -1c
.RI "string[] \fBname2_L\fP"
.br
.ti -1c
.RI "string[] \fBroomName_L\fP"
.br
.in -1c

Public Attributes inherited from \fBCardRow\fP
.in +1c
.ti -1c
.RI "string \fBid\fP"
.br
.ti -1c
.RI "string \fBidExtra\fP"
.br
.ti -1c
.RI "string \fBtierGroup\fP"
.br
.ti -1c
.RI "string \fBlightData\fP"
.br
.ti -1c
.RI "string \fB_origin\fP"
.br
.ti -1c
.RI "int \fBidShadow\fP"
.br
.ti -1c
.RI "int \fBquality\fP"
.br
.ti -1c
.RI "int[] \fBelements\fP"
.br
.ti -1c
.RI "int[] \fBshadow\fP"
.br
.ti -1c
.RI "int[] \fBsize\fP"
.br
.ti -1c
.RI "int[] \fBlight\fP"
.br
.ti -1c
.RI "string[] \fBloot\fP"
.br
.ti -1c
.RI "string[] \fBfilter\fP"
.br
.ti -1c
.RI "string[] \fBtrait\fP"
.br
.ti -1c
.RI "string[] \fBidActor\fP"
.br
.ti -1c
.RI "string[] \fBvals\fP"
.br
.ti -1c
.RI "string[] \fBname2\fP"
.br
.ti -1c
.RI "string[] \fBname2_JP\fP"
.br
.ti -1c
.RI "Dictionary< int, int > \fBelementMap\fP"
.br
.ti -1c
.RI "Sprite \fBsprite\fP"
.br
.ti -1c
.RI "\fBCardRow\fP \fBorigin\fP"
.br
.ti -1c
.RI "bool \fBisOrigin\fP"
.br
.ti -1c
.RI "bool \fBisChara\fP"
.br
.ti -1c
.RI "\fBCard\fP \fB_model\fP"
.br
.in -1c

Public Attributes inherited from \fBRenderRow\fP
.in +1c
.ti -1c
.RI "int[] \fBtiles\fP"
.br
.ti -1c
.RI "int[] \fB_tiles\fP"
.br
.ti -1c
.RI "int[] \fBskins\fP"
.br
.ti -1c
.RI "int \fBcolorMod\fP"
.br
.ti -1c
.RI "int \fBsort\fP"
.br
.ti -1c
.RI "int \fBvalue\fP"
.br
.ti -1c
.RI "int \fBLV\fP"
.br
.ti -1c
.RI "int \fBchance\fP"
.br
.ti -1c
.RI "int \fBtempChance\fP"
.br
.ti -1c
.RI "int \fBsnowTile\fP"
.br
.ti -1c
.RI "string \fBname\fP"
.br
.ti -1c
.RI "string \fBname_JP\fP"
.br
.ti -1c
.RI "string \fBdetail\fP"
.br
.ti -1c
.RI "string \fBdetail_JP\fP"
.br
.ti -1c
.RI "string \fB_idRenderData\fP"
.br
.ti -1c
.RI "string \fB_tileType\fP"
.br
.ti -1c
.RI "string \fBdefMat\fP"
.br
.ti -1c
.RI "string \fBcolorType\fP"
.br
.ti -1c
.RI "string \fBcategory\fP"
.br
.ti -1c
.RI "string \fBidSound\fP"
.br
.ti -1c
.RI "string \fBaliasPref\fP"
.br
.ti -1c
.RI "string[] \fBcomponents\fP"
.br
.ti -1c
.RI "string[] \fBfactory\fP"
.br
.ti -1c
.RI "string[] \fBrecipeKey\fP"
.br
.ti -1c
.RI "string[] \fBtag\fP"
.br
.ti -1c
.RI "int \fBW\fP = 1"
.br
.ti -1c
.RI "int \fBH\fP = 1"
.br
.ti -1c
.RI "bool \fBmultisize\fP"
.br
.ti -1c
.RI "\fBSourcePref\fP \fBpref\fP"
.br
.ti -1c
.RI "\fBRenderData\fP \fBrenderData\fP"
.br
.ti -1c
.RI "Sprite[,] \fBsprites\fP"
.br
.ti -1c
.RI "\fBTileType\fP \fBtileType\fP"
.br
.ti -1c
.RI "bool \fBuseAltColor\fP"
.br
.ti -1c
.RI "bool \fBuseRandomColor\fP"
.br
.ti -1c
.RI "bool \fBfixedMaterial\fP"
.br
.ti -1c
.RI "\fBSourceMaterial\&.Row\fP \fBDefaultMaterial\fP"
.br
.ti -1c
.RI "SpriteReplacer \fBreplacer\fP"
.br
.ti -1c
.RI "string \fB_nameSearch\fP"
.br
.ti -1c
.RI "string \fB_nameSearchJP\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override bool \fBUseAlias\fP\fR [get]\fP"
.br
.ti -1c
.RI "override string \fBGetAlias\fP\fR [get]\fP"
.br
.ti -1c
.RI "override string \fBRecipeID\fP\fR [get]\fP"
.br
.in -1c

Properties inherited from \fBCardRow\fP
.in +1c
.ti -1c
.RI "\fBCard\fP \fBmodel\fP\fR [get]\fP"
.br
.ti -1c
.RI "override string \fBidRenderData\fP\fR [get]\fP"
.br
.ti -1c
.RI "override string \fBidSprite\fP\fR [get]\fP"
.br
.ti -1c
.RI "override string \fBidString\fP\fR [get]\fP"
.br
.ti -1c
.RI "override string \fBpathSprite\fP\fR [get]\fP"
.br
.in -1c

Properties inherited from \fBRenderRow\fP
.in +1c
.ti -1c
.RI "virtual string \fBidString\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual string \fBRecipeID\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual string \fBpathRenderData\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual string \fBidRenderData\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual \fBRenderData\fP \fBdefaultRenderData\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual string \fBpathSprite\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual string \fBidSprite\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual string \fBprefabName\fP\fR [get]\fP"
.br
.ti -1c
.RI "\fBSourceCategory\&.Row\fP \fBCategory\fP\fR [get]\fP"
.br
.ti -1c
.RI "string \fBRecipeCat\fP\fR [get]\fP"
.br
.ti -1c
.RI "\fBSourceManager\fP \fBsources\fP\fR [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Static Public Attributes inherited from \fBRenderRow\fP
.in +1c
.ti -1c
.RI "static Dictionary< string, \fBRenderData\fP > \fBDictRenderData\fP = new Dictionary<string, \fBRenderData\fP>()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB108\fP of file \fBSourceThing\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override string SourceThing\&.Row\&.GetName ()"

.PP
Definition at line \fB185\fP of file \fBSourceThing\&.cs\fP\&.
.SS "override string SourceThing\&.Row\&.GetName (\fBSourceMaterial\&.Row\fP mat, int sum)\fR [virtual]\fP"

.PP
Reimplemented from \fBCardRow\fP\&.
.PP
Definition at line \fB171\fP of file \fBSourceThing\&.cs\fP\&.
.SS "override string SourceThing\&.Row\&.GetSearchName (bool jp)\fR [virtual]\fP"

.PP
Reimplemented from \fBRenderRow\fP\&.
.PP
Definition at line \fB200\fP of file \fBSourceThing\&.cs\fP\&.
.SS "override void SourceThing\&.Row\&.OnImportData (SourceData data)"

.PP
Definition at line \fB141\fP of file \fBSourceThing\&.cs\fP\&.
.SS "override void SourceThing\&.Row\&.SetTiles ()\fR [virtual]\fP"

.PP
Reimplemented from \fBRenderRow\fP\&.
.PP
Definition at line \fB148\fP of file \fBSourceThing\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int [] SourceThing\&.Row\&._altTiles"

.PP
Definition at line \fB283\fP of file \fBSourceThing\&.cs\fP\&.
.SS "int [] SourceThing\&.Row\&.altTiles"

.PP
Definition at line \fB235\fP of file \fBSourceThing\&.cs\fP\&.
.SS "int [] SourceThing\&.Row\&.anime"

.PP
Definition at line \fB238\fP of file \fBSourceThing\&.cs\fP\&.
.SS "string SourceThing\&.Row\&.attackType"

.PP
Definition at line \fB256\fP of file \fBSourceThing\&.cs\fP\&.
.SS "int [] SourceThing\&.Row\&.defense"

.PP
Definition at line \fB265\fP of file \fBSourceThing\&.cs\fP\&.
.SS "string SourceThing\&.Row\&.detail_L"

.PP
Definition at line \fB292\fP of file \fBSourceThing\&.cs\fP\&.
.SS "string [] SourceThing\&.Row\&.disassemble"

.PP
Definition at line \fB241\fP of file \fBSourceThing\&.cs\fP\&.
.SS "int SourceThing\&.Row\&.electricity"

.PP
Definition at line \fB250\fP of file \fBSourceThing\&.cs\fP\&.
.SS "int SourceThing\&.Row\&.HP"

.PP
Definition at line \fB244\fP of file \fBSourceThing\&.cs\fP\&.
.SS "string SourceThing\&.Row\&.idActorEx"

.PP
Definition at line \fB271\fP of file \fBSourceThing\&.cs\fP\&.
.SS "string SourceThing\&.Row\&.idToggleExtra"

.PP
Definition at line \fB268\fP of file \fBSourceThing\&.cs\fP\&.
.SS "bool SourceThing\&.Row\&.ignoreAltFix"

.PP
Definition at line \fB286\fP of file \fBSourceThing\&.cs\fP\&.
.SS "string [] SourceThing\&.Row\&.name2_L"

.PP
Definition at line \fB301\fP of file \fBSourceThing\&.cs\fP\&.
.SS "string SourceThing\&.Row\&.name_L"

.PP
Definition at line \fB289\fP of file \fBSourceThing\&.cs\fP\&.
.SS "string SourceThing\&.Row\&.naming"

.PP
Definition at line \fB226\fP of file \fBSourceThing\&.cs\fP\&.
.SS "int [] SourceThing\&.Row\&.offense"

.PP
Definition at line \fB259\fP of file \fBSourceThing\&.cs\fP\&.
.SS "int SourceThing\&.Row\&.range"

.PP
Definition at line \fB253\fP of file \fBSourceThing\&.cs\fP\&.
.SS "string [] SourceThing\&.Row\&.roomName"

.PP
Definition at line \fB280\fP of file \fBSourceThing\&.cs\fP\&.
.SS "string [] SourceThing\&.Row\&.roomName_JP"

.PP
Definition at line \fB277\fP of file \fBSourceThing\&.cs\fP\&.
.SS "string [] SourceThing\&.Row\&.roomName_L"

.PP
Definition at line \fB304\fP of file \fBSourceThing\&.cs\fP\&.
.SS "int [] SourceThing\&.Row\&.substats"

.PP
Definition at line \fB262\fP of file \fBSourceThing\&.cs\fP\&.
.SS "string SourceThing\&.Row\&.unit"

.PP
Definition at line \fB229\fP of file \fBSourceThing\&.cs\fP\&.
.SS "string SourceThing\&.Row\&.unit_JP"

.PP
Definition at line \fB223\fP of file \fBSourceThing\&.cs\fP\&.
.SS "string SourceThing\&.Row\&.unit_L"

.PP
Definition at line \fB295\fP of file \fBSourceThing\&.cs\fP\&.
.SS "string SourceThing\&.Row\&.unknown"

.PP
Definition at line \fB232\fP of file \fBSourceThing\&.cs\fP\&.
.SS "string SourceThing\&.Row\&.unknown_JP"

.PP
Definition at line \fB220\fP of file \fBSourceThing\&.cs\fP\&.
.SS "string SourceThing\&.Row\&.unknown_L"

.PP
Definition at line \fB298\fP of file \fBSourceThing\&.cs\fP\&.
.SS "int SourceThing\&.Row\&.weight"

.PP
Definition at line \fB247\fP of file \fBSourceThing\&.cs\fP\&.
.SS "string SourceThing\&.Row\&.workTag"

.PP
Definition at line \fB274\fP of file \fBSourceThing\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "override string SourceThing\&.Row\&.GetAlias\fR [get]\fP"

.PP
Definition at line \fB122\fP of file \fBSourceThing\&.cs\fP\&.
.SS "override string SourceThing\&.Row\&.RecipeID\fR [get]\fP"

.PP
Definition at line \fB132\fP of file \fBSourceThing\&.cs\fP\&.
.SS "override bool SourceThing\&.Row\&.UseAlias\fR [get]\fP"

.PP
Definition at line \fB112\fP of file \fBSourceThing\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
