.TH "SourceHobby.Row" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SourceHobby.Row
.SH SYNOPSIS
.br
.PP
.PP
Inherits SourceData\&.BaseRow\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBid\fP"
.br
.ti -1c
.RI "string \fBalias\fP"
.br
.ti -1c
.RI "string \fBtype\fP"
.br
.ti -1c
.RI "string \fBname_JP\fP"
.br
.ti -1c
.RI "string \fBname\fP"
.br
.ti -1c
.RI "string \fBai\fP"
.br
.ti -1c
.RI "string \fBtalk\fP"
.br
.ti -1c
.RI "string \fBarea\fP"
.br
.ti -1c
.RI "string \fBdestTrait\fP"
.br
.ti -1c
.RI "string \fBworkTag\fP"
.br
.ti -1c
.RI "string \fBexpedition\fP"
.br
.ti -1c
.RI "int[] \fBresources\fP"
.br
.ti -1c
.RI "int \fBrandomRange\fP"
.br
.ti -1c
.RI "string[] \fBmodifiers\fP"
.br
.ti -1c
.RI "int \fBtax\fP"
.br
.ti -1c
.RI "string[] \fBthings\fP"
.br
.ti -1c
.RI "int[] \fBelements\fP"
.br
.ti -1c
.RI "string \fBskill\fP"
.br
.ti -1c
.RI "string \fBdetail_JP\fP"
.br
.ti -1c
.RI "string \fBdetail\fP"
.br
.ti -1c
.RI "string \fBname_L\fP"
.br
.ti -1c
.RI "string \fBdetail_L\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override bool \fBUseAlias\fP\fR [get]\fP"
.br
.ti -1c
.RI "override string \fBGetAlias\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB79\fP of file \fBSourceHobby\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "string SourceHobby\&.Row\&.ai"

.PP
Definition at line \fB117\fP of file \fBSourceHobby\&.cs\fP\&.
.SS "string SourceHobby\&.Row\&.alias"

.PP
Definition at line \fB105\fP of file \fBSourceHobby\&.cs\fP\&.
.SS "string SourceHobby\&.Row\&.area"

.PP
Definition at line \fB123\fP of file \fBSourceHobby\&.cs\fP\&.
.SS "string SourceHobby\&.Row\&.destTrait"

.PP
Definition at line \fB126\fP of file \fBSourceHobby\&.cs\fP\&.
.SS "string SourceHobby\&.Row\&.detail"

.PP
Definition at line \fB159\fP of file \fBSourceHobby\&.cs\fP\&.
.SS "string SourceHobby\&.Row\&.detail_JP"

.PP
Definition at line \fB156\fP of file \fBSourceHobby\&.cs\fP\&.
.SS "string SourceHobby\&.Row\&.detail_L"

.PP
Definition at line \fB165\fP of file \fBSourceHobby\&.cs\fP\&.
.SS "int [] SourceHobby\&.Row\&.elements"

.PP
Definition at line \fB150\fP of file \fBSourceHobby\&.cs\fP\&.
.SS "string SourceHobby\&.Row\&.expedition"

.PP
Definition at line \fB132\fP of file \fBSourceHobby\&.cs\fP\&.
.SS "int SourceHobby\&.Row\&.id"

.PP
Definition at line \fB102\fP of file \fBSourceHobby\&.cs\fP\&.
.SS "string [] SourceHobby\&.Row\&.modifiers"

.PP
Definition at line \fB141\fP of file \fBSourceHobby\&.cs\fP\&.
.SS "string SourceHobby\&.Row\&.name"

.PP
Definition at line \fB114\fP of file \fBSourceHobby\&.cs\fP\&.
.SS "string SourceHobby\&.Row\&.name_JP"

.PP
Definition at line \fB111\fP of file \fBSourceHobby\&.cs\fP\&.
.SS "string SourceHobby\&.Row\&.name_L"

.PP
Definition at line \fB162\fP of file \fBSourceHobby\&.cs\fP\&.
.SS "int SourceHobby\&.Row\&.randomRange"

.PP
Definition at line \fB138\fP of file \fBSourceHobby\&.cs\fP\&.
.SS "int [] SourceHobby\&.Row\&.resources"

.PP
Definition at line \fB135\fP of file \fBSourceHobby\&.cs\fP\&.
.SS "string SourceHobby\&.Row\&.skill"

.PP
Definition at line \fB153\fP of file \fBSourceHobby\&.cs\fP\&.
.SS "string SourceHobby\&.Row\&.talk"

.PP
Definition at line \fB120\fP of file \fBSourceHobby\&.cs\fP\&.
.SS "int SourceHobby\&.Row\&.tax"

.PP
Definition at line \fB144\fP of file \fBSourceHobby\&.cs\fP\&.
.SS "string [] SourceHobby\&.Row\&.things"

.PP
Definition at line \fB147\fP of file \fBSourceHobby\&.cs\fP\&.
.SS "string SourceHobby\&.Row\&.type"

.PP
Definition at line \fB108\fP of file \fBSourceHobby\&.cs\fP\&.
.SS "string SourceHobby\&.Row\&.workTag"

.PP
Definition at line \fB129\fP of file \fBSourceHobby\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "override string SourceHobby\&.Row\&.GetAlias\fR [get]\fP"

.PP
Definition at line \fB93\fP of file \fBSourceHobby\&.cs\fP\&.
.SS "override bool SourceHobby\&.Row\&.UseAlias\fR [get]\fP"

.PP
Definition at line \fB83\fP of file \fBSourceHobby\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
