.TH "SourceCalc.Row" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SourceCalc.Row
.SH SYNOPSIS
.br
.PP
.PP
Inherits SourceData\&.BaseRow\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBid\fP"
.br
.ti -1c
.RI "string \fBnum\fP"
.br
.ti -1c
.RI "string \fBsides\fP"
.br
.ti -1c
.RI "string \fBbonus\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override bool \fBUseAlias\fP\fR [get]\fP"
.br
.ti -1c
.RI "override string \fBGetAlias\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB26\fP of file \fBSourceCalc\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "string SourceCalc\&.Row\&.bonus"

.PP
Definition at line \fB58\fP of file \fBSourceCalc\&.cs\fP\&.
.SS "string SourceCalc\&.Row\&.id"

.PP
Definition at line \fB49\fP of file \fBSourceCalc\&.cs\fP\&.
.SS "string SourceCalc\&.Row\&.num"

.PP
Definition at line \fB52\fP of file \fBSourceCalc\&.cs\fP\&.
.SS "string SourceCalc\&.Row\&.sides"

.PP
Definition at line \fB55\fP of file \fBSourceCalc\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "override string SourceCalc\&.Row\&.GetAlias\fR [get]\fP"

.PP
Definition at line \fB40\fP of file \fBSourceCalc\&.cs\fP\&.
.SS "override bool SourceCalc\&.Row\&.UseAlias\fR [get]\fP"

.PP
Definition at line \fB30\fP of file \fBSourceCalc\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
