.TH "SourceArea.Row" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SourceArea.Row
.SH SYNOPSIS
.br
.PP
.PP
Inherits SourceData\&.BaseRow\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBid\fP"
.br
.ti -1c
.RI "string \fBname_JP\fP"
.br
.ti -1c
.RI "string \fBname\fP"
.br
.ti -1c
.RI "string \fBtextAssign_JP\fP"
.br
.ti -1c
.RI "string \fBtextAssign\fP"
.br
.ti -1c
.RI "string \fBdetail_JP\fP"
.br
.ti -1c
.RI "string \fBtag\fP"
.br
.ti -1c
.RI "string \fBdetail\fP"
.br
.ti -1c
.RI "string \fBname_L\fP"
.br
.ti -1c
.RI "string \fBdetail_L\fP"
.br
.ti -1c
.RI "string \fBtextAssign_L\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override bool \fBUseAlias\fP\fR [get]\fP"
.br
.ti -1c
.RI "override string \fBGetAlias\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB43\fP of file \fBSourceArea\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "string SourceArea\&.Row\&.detail"

.PP
Definition at line \fB87\fP of file \fBSourceArea\&.cs\fP\&.
.SS "string SourceArea\&.Row\&.detail_JP"

.PP
Definition at line \fB81\fP of file \fBSourceArea\&.cs\fP\&.
.SS "string SourceArea\&.Row\&.detail_L"

.PP
Definition at line \fB93\fP of file \fBSourceArea\&.cs\fP\&.
.SS "string SourceArea\&.Row\&.id"

.PP
Definition at line \fB66\fP of file \fBSourceArea\&.cs\fP\&.
.SS "string SourceArea\&.Row\&.name"

.PP
Definition at line \fB72\fP of file \fBSourceArea\&.cs\fP\&.
.SS "string SourceArea\&.Row\&.name_JP"

.PP
Definition at line \fB69\fP of file \fBSourceArea\&.cs\fP\&.
.SS "string SourceArea\&.Row\&.name_L"

.PP
Definition at line \fB90\fP of file \fBSourceArea\&.cs\fP\&.
.SS "string SourceArea\&.Row\&.tag"

.PP
Definition at line \fB84\fP of file \fBSourceArea\&.cs\fP\&.
.SS "string SourceArea\&.Row\&.textAssign"

.PP
Definition at line \fB78\fP of file \fBSourceArea\&.cs\fP\&.
.SS "string SourceArea\&.Row\&.textAssign_JP"

.PP
Definition at line \fB75\fP of file \fBSourceArea\&.cs\fP\&.
.SS "string SourceArea\&.Row\&.textAssign_L"

.PP
Definition at line \fB96\fP of file \fBSourceArea\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "override string SourceArea\&.Row\&.GetAlias\fR [get]\fP"

.PP
Definition at line \fB57\fP of file \fBSourceArea\&.cs\fP\&.
.SS "override bool SourceArea\&.Row\&.UseAlias\fR [get]\fP"

.PP
Definition at line \fB47\fP of file \fBSourceArea\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
