.TH "SourceMaterial.Tier" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SourceMaterial.Tier
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSourceMaterial\&.Row\fP \fBSelect\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBsum\fP"
.br
.ti -1c
.RI "List< \fBSourceMaterial\&.Row\fP > \fBlist\fP = new List<\fBSourceMaterial\&.Row\fP>()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB560\fP of file \fBSourceMaterial\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBSourceMaterial\&.Row\fP SourceMaterial\&.Tier\&.Select ()"

.PP
Definition at line \fB563\fP of file \fBSourceMaterial\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "List<\fBSourceMaterial\&.Row\fP> SourceMaterial\&.Tier\&.list = new List<\fBSourceMaterial\&.Row\fP>()"

.PP
Definition at line \fB582\fP of file \fBSourceMaterial\&.cs\fP\&.
.SS "int SourceMaterial\&.Tier\&.sum"

.PP
Definition at line \fB579\fP of file \fBSourceMaterial\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
