.TH "SourceCheck" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SourceCheck
.SH SYNOPSIS
.br
.PP
.PP
Inherits SourceDataString< SourceCheck\&.Row >\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRow\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override \fBSourceCheck\&.Row\fP \fBCreateRow\fP ()"
.br
.ti -1c
.RI "override void \fBSetRow\fP (\fBSourceCheck\&.Row\fP r)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB4\fP of file \fBSourceCheck\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override \fBSourceCheck\&.Row\fP SourceCheck\&.CreateRow ()"

.PP
Definition at line \fB7\fP of file \fBSourceCheck\&.cs\fP\&.
.SS "override void SourceCheck\&.SetRow (\fBSourceCheck\&.Row\fP r)"

.PP
Definition at line \fB25\fP of file \fBSourceCheck\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
