.TH "SourceObj.Row" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SourceObj.Row
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBTileRow\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnInit\fP ()"
.br
.in -1c

Public Member Functions inherited from \fBTileRow\fP
.in +1c
.ti -1c
.RI "void \fBInit\fP ()"
.br
.in -1c

Public Member Functions inherited from \fBRenderRow\fP
.in +1c
.ti -1c
.RI "bool \fBHasTag\fP (CTAG _tag)"
.br
.ti -1c
.RI "virtual string \fBGetSearchName\fP (bool jp)"
.br
.ti -1c
.RI "bool \fBContainsTag\fP (string _tag)"
.br
.ti -1c
.RI "override void \fBOnImportData\fP (SourceData data)"
.br
.ti -1c
.RI "void \fBSetRenderData\fP ()"
.br
.ti -1c
.RI "virtual void \fBSetTiles\fP ()"
.br
.ti -1c
.RI "int \fBConvertTile\fP (int tile)"
.br
.ti -1c
.RI "Sprite \fBGetSprite\fP (int dir=0, int skin=0, bool snow=false)"
.br
.ti -1c
.RI "void \fBSetSpriteRenderer\fP (SpriteRenderer sr, Sprite sprite=null, int matCol=0, bool setTransform=true, int dir=0)"
.br
.ti -1c
.RI "virtual \fBSourcePref\fP \fBGetPref\fP ()"
.br
.ti -1c
.RI "void \fBSetImage\fP (Image image, Sprite sprite=null, int matCol=0, bool setNativeSize=true, int dir=0, int idSkin=0)"
.br
.ti -1c
.RI "void \fBSetRenderParam\fP (\fBRenderParam\fP p, \fBSourceMaterial\&.Row\fP mat, int dir)"
.br
.ti -1c
.RI "virtual unsafe \fBRenderParam\fP \fBGetRenderParam\fP (\fBSourceMaterial\&.Row\fP mat, int dir, \fBPoint\fP point=null, int bridgeHeight=\-1)"
.br
.ti -1c
.RI "virtual int \fBGetTile\fP (\fBSourceMaterial\&.Row\fP mat, int dir=0)"
.br
.ti -1c
.RI "int \fBGetColorInt\fP (\fBSourceMaterial\&.Row\fP mat)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string[] \fB_growth\fP"
.br
.ti -1c
.RI "int \fBcostSoil\fP"
.br
.ti -1c
.RI "string \fBobjType\fP"
.br
.ti -1c
.RI "string[] \fBvals\fP"
.br
.ti -1c
.RI "string[] \fBreqHarvest\fP"
.br
.ti -1c
.RI "string \fBvalType\fP"
.br
.ti -1c
.RI "string \fBmatCategory\fP"
.br
.ti -1c
.RI "int \fBidRoof\fP"
.br
.ti -1c
.RI "bool \fBHasGrowth\fP"
.br
.ti -1c
.RI "bool \fBautoTile\fP"
.br
.ti -1c
.RI "\fBGrowSystem\fP \fBgrowth\fP"
.br
.ti -1c
.RI "ObjValType \fBobjValType\fP"
.br
.ti -1c
.RI "string \fBname_L\fP"
.br
.ti -1c
.RI "string \fBdetail_L\fP"
.br
.in -1c

Public Attributes inherited from \fBTileRow\fP
.in +1c
.ti -1c
.RI "bool \fBignoreSnow\fP"
.br
.ti -1c
.RI "int \fBid\fP"
.br
.ti -1c
.RI "int \fBhp\fP"
.br
.ti -1c
.RI "string \fBalias\fP"
.br
.ti -1c
.RI "string \fBsoundFoot\fP"
.br
.in -1c

Public Attributes inherited from \fBRenderRow\fP
.in +1c
.ti -1c
.RI "int[] \fBtiles\fP"
.br
.ti -1c
.RI "int[] \fB_tiles\fP"
.br
.ti -1c
.RI "int[] \fBskins\fP"
.br
.ti -1c
.RI "int \fBcolorMod\fP"
.br
.ti -1c
.RI "int \fBsort\fP"
.br
.ti -1c
.RI "int \fBvalue\fP"
.br
.ti -1c
.RI "int \fBLV\fP"
.br
.ti -1c
.RI "int \fBchance\fP"
.br
.ti -1c
.RI "int \fBtempChance\fP"
.br
.ti -1c
.RI "int \fBsnowTile\fP"
.br
.ti -1c
.RI "string \fBname\fP"
.br
.ti -1c
.RI "string \fBname_JP\fP"
.br
.ti -1c
.RI "string \fBdetail\fP"
.br
.ti -1c
.RI "string \fBdetail_JP\fP"
.br
.ti -1c
.RI "string \fB_idRenderData\fP"
.br
.ti -1c
.RI "string \fB_tileType\fP"
.br
.ti -1c
.RI "string \fBdefMat\fP"
.br
.ti -1c
.RI "string \fBcolorType\fP"
.br
.ti -1c
.RI "string \fBcategory\fP"
.br
.ti -1c
.RI "string \fBidSound\fP"
.br
.ti -1c
.RI "string \fBaliasPref\fP"
.br
.ti -1c
.RI "string[] \fBcomponents\fP"
.br
.ti -1c
.RI "string[] \fBfactory\fP"
.br
.ti -1c
.RI "string[] \fBrecipeKey\fP"
.br
.ti -1c
.RI "string[] \fBtag\fP"
.br
.ti -1c
.RI "int \fBW\fP = 1"
.br
.ti -1c
.RI "int \fBH\fP = 1"
.br
.ti -1c
.RI "bool \fBmultisize\fP"
.br
.ti -1c
.RI "\fBSourcePref\fP \fBpref\fP"
.br
.ti -1c
.RI "\fBRenderData\fP \fBrenderData\fP"
.br
.ti -1c
.RI "Sprite[,] \fBsprites\fP"
.br
.ti -1c
.RI "\fBTileType\fP \fBtileType\fP"
.br
.ti -1c
.RI "bool \fBuseAltColor\fP"
.br
.ti -1c
.RI "bool \fBuseRandomColor\fP"
.br
.ti -1c
.RI "bool \fBfixedMaterial\fP"
.br
.ti -1c
.RI "\fBSourceMaterial\&.Row\fP \fBDefaultMaterial\fP"
.br
.ti -1c
.RI "SpriteReplacer \fBreplacer\fP"
.br
.ti -1c
.RI "string \fB_nameSearch\fP"
.br
.ti -1c
.RI "string \fB_nameSearchJP\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override bool \fBUseAlias\fP\fR [get]\fP"
.br
.ti -1c
.RI "override string \fBGetAlias\fP\fR [get]\fP"
.br
.ti -1c
.RI "override string \fBRecipeID\fP\fR [get]\fP"
.br
.ti -1c
.RI "override \fBRenderData\fP \fBdefaultRenderData\fP\fR [get]\fP"
.br
.in -1c

Properties inherited from \fBRenderRow\fP
.in +1c
.ti -1c
.RI "virtual string \fBidString\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual string \fBRecipeID\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual string \fBpathRenderData\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual string \fBidRenderData\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual \fBRenderData\fP \fBdefaultRenderData\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual string \fBpathSprite\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual string \fBidSprite\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual string \fBprefabName\fP\fR [get]\fP"
.br
.ti -1c
.RI "\fBSourceCategory\&.Row\fP \fBCategory\fP\fR [get]\fP"
.br
.ti -1c
.RI "string \fBRecipeCat\fP\fR [get]\fP"
.br
.ti -1c
.RI "\fBSourceManager\fP \fBsources\fP\fR [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Static Public Attributes inherited from \fBRenderRow\fP
.in +1c
.ti -1c
.RI "static Dictionary< string, \fBRenderData\fP > \fBDictRenderData\fP = new Dictionary<string, \fBRenderData\fP>()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB123\fP of file \fBSourceObj\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void SourceObj\&.Row\&.OnInit ()\fR [virtual]\fP"

.PP
Reimplemented from \fBTileRow\fP\&.
.PP
Definition at line \fB166\fP of file \fBSourceObj\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "string [] SourceObj\&.Row\&._growth"

.PP
Definition at line \fB181\fP of file \fBSourceObj\&.cs\fP\&.
.SS "bool SourceObj\&.Row\&.autoTile"

.PP
Definition at line \fB210\fP of file \fBSourceObj\&.cs\fP\&.
.SS "int SourceObj\&.Row\&.costSoil"

.PP
Definition at line \fB184\fP of file \fBSourceObj\&.cs\fP\&.
.SS "string SourceObj\&.Row\&.detail_L"

.PP
Definition at line \fB222\fP of file \fBSourceObj\&.cs\fP\&.
.SS "\fBGrowSystem\fP SourceObj\&.Row\&.growth"

.PP
Definition at line \fB213\fP of file \fBSourceObj\&.cs\fP\&.
.SS "bool SourceObj\&.Row\&.HasGrowth"

.PP
Definition at line \fB206\fP of file \fBSourceObj\&.cs\fP\&.
.SS "int SourceObj\&.Row\&.idRoof"

.PP
Definition at line \fB202\fP of file \fBSourceObj\&.cs\fP\&.
.SS "string SourceObj\&.Row\&.matCategory"

.PP
Definition at line \fB199\fP of file \fBSourceObj\&.cs\fP\&.
.SS "string SourceObj\&.Row\&.name_L"

.PP
Definition at line \fB219\fP of file \fBSourceObj\&.cs\fP\&.
.SS "string SourceObj\&.Row\&.objType"

.PP
Definition at line \fB187\fP of file \fBSourceObj\&.cs\fP\&.
.SS "ObjValType SourceObj\&.Row\&.objValType"

.PP
Definition at line \fB216\fP of file \fBSourceObj\&.cs\fP\&.
.SS "string [] SourceObj\&.Row\&.reqHarvest"

.PP
Definition at line \fB193\fP of file \fBSourceObj\&.cs\fP\&.
.SS "string [] SourceObj\&.Row\&.vals"

.PP
Definition at line \fB190\fP of file \fBSourceObj\&.cs\fP\&.
.SS "string SourceObj\&.Row\&.valType"

.PP
Definition at line \fB196\fP of file \fBSourceObj\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "override \fBRenderData\fP SourceObj\&.Row\&.defaultRenderData\fR [get]\fP"

.PP
Definition at line \fB157\fP of file \fBSourceObj\&.cs\fP\&.
.SS "override string SourceObj\&.Row\&.GetAlias\fR [get]\fP"

.PP
Definition at line \fB137\fP of file \fBSourceObj\&.cs\fP\&.
.SS "override string SourceObj\&.Row\&.RecipeID\fR [get]\fP"

.PP
Definition at line \fB147\fP of file \fBSourceObj\&.cs\fP\&.
.SS "override bool SourceObj\&.Row\&.UseAlias\fR [get]\fP"

.PP
Definition at line \fB127\fP of file \fBSourceObj\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
