.TH "SourceZoneAffix.Row" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SourceZoneAffix.Row
.SH SYNOPSIS
.br
.PP
.PP
Inherits SourceData\&.BaseRow\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBid\fP"
.br
.ti -1c
.RI "string \fBzone\fP"
.br
.ti -1c
.RI "string \fBname_JP\fP"
.br
.ti -1c
.RI "string \fBname\fP"
.br
.ti -1c
.RI "string \fBtextAssign_JP\fP"
.br
.ti -1c
.RI "string \fBtextAssign\fP"
.br
.ti -1c
.RI "string \fBdetail_JP\fP"
.br
.ti -1c
.RI "string \fBdetail\fP"
.br
.ti -1c
.RI "string \fBname_L\fP"
.br
.ti -1c
.RI "string \fBdetail_L\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override bool \fBUseAlias\fP\fR [get]\fP"
.br
.ti -1c
.RI "override string \fBGetAlias\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB30\fP of file \fBSourceZoneAffix\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "string SourceZoneAffix\&.Row\&.detail"

.PP
Definition at line \fB74\fP of file \fBSourceZoneAffix\&.cs\fP\&.
.SS "string SourceZoneAffix\&.Row\&.detail_JP"

.PP
Definition at line \fB71\fP of file \fBSourceZoneAffix\&.cs\fP\&.
.SS "string SourceZoneAffix\&.Row\&.detail_L"

.PP
Definition at line \fB80\fP of file \fBSourceZoneAffix\&.cs\fP\&.
.SS "int SourceZoneAffix\&.Row\&.id"

.PP
Definition at line \fB53\fP of file \fBSourceZoneAffix\&.cs\fP\&.
.SS "string SourceZoneAffix\&.Row\&.name"

.PP
Definition at line \fB62\fP of file \fBSourceZoneAffix\&.cs\fP\&.
.SS "string SourceZoneAffix\&.Row\&.name_JP"

.PP
Definition at line \fB59\fP of file \fBSourceZoneAffix\&.cs\fP\&.
.SS "string SourceZoneAffix\&.Row\&.name_L"

.PP
Definition at line \fB77\fP of file \fBSourceZoneAffix\&.cs\fP\&.
.SS "string SourceZoneAffix\&.Row\&.textAssign"

.PP
Definition at line \fB68\fP of file \fBSourceZoneAffix\&.cs\fP\&.
.SS "string SourceZoneAffix\&.Row\&.textAssign_JP"

.PP
Definition at line \fB65\fP of file \fBSourceZoneAffix\&.cs\fP\&.
.SS "string SourceZoneAffix\&.Row\&.zone"

.PP
Definition at line \fB56\fP of file \fBSourceZoneAffix\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "override string SourceZoneAffix\&.Row\&.GetAlias\fR [get]\fP"

.PP
Definition at line \fB44\fP of file \fBSourceZoneAffix\&.cs\fP\&.
.SS "override bool SourceZoneAffix\&.Row\&.UseAlias\fR [get]\fP"

.PP
Definition at line \fB34\fP of file \fBSourceZoneAffix\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
