.TH "SourceAsset" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SourceAsset
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBEScriptable\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPrefData\fP"
.br
.ti -1c
.RI "class \fBPrefs\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBDoFix\fP ()"
.br
.ti -1c
.RI "void \fBSavePrefs\fP (string id='prefs')"
.br
.ti -1c
.RI "void \fBLoadPrefs\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fB_SavePrefs\fP (string id='prefs')"
.br
.ti -1c
.RI "static void \fB_LoadPrefs\fP (string id='prefs')"
.br
.in -1c

Static Public Member Functions inherited from \fBEScriptable\fP
.in +1c
.ti -1c
.RI "static int \fBrnd\fP (int a)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBidLoad\fP = 'prefs'"
.br
.ti -1c
.RI "UD_String_String \fBrenames\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "static string \fBPrefPath\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB6\fP of file \fBSourceAsset\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "static void SourceAsset\&._LoadPrefs (string id = \fR'prefs'\fP)\fR [static]\fP"

.PP
Definition at line \fB58\fP of file \fBSourceAsset\&.cs\fP\&.
.SS "static void SourceAsset\&._SavePrefs (string id = \fR'prefs'\fP)\fR [static]\fP"

.PP
Definition at line \fB30\fP of file \fBSourceAsset\&.cs\fP\&.
.SS "void SourceAsset\&.DoFix ()"

.PP
Definition at line \fB19\fP of file \fBSourceAsset\&.cs\fP\&.
.SS "void SourceAsset\&.LoadPrefs ()"

.PP
Definition at line \fB52\fP of file \fBSourceAsset\&.cs\fP\&.
.SS "void SourceAsset\&.SavePrefs (string id = \fR'prefs'\fP)"

.PP
Definition at line \fB24\fP of file \fBSourceAsset\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "string SourceAsset\&.idLoad = 'prefs'"

.PP
Definition at line \fB77\fP of file \fBSourceAsset\&.cs\fP\&.
.SS "UD_String_String SourceAsset\&.renames"

.PP
Definition at line \fB80\fP of file \fBSourceAsset\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "string SourceAsset\&.PrefPath\fR [static]\fP, \fR [get]\fP"

.PP
Definition at line \fB10\fP of file \fBSourceAsset\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
