.TH "SourceResearch" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SourceResearch
.SH SYNOPSIS
.br
.PP
.PP
Inherits SourceDataString< SourceResearch\&.Row >\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRow\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override \fBSourceResearch\&.Row\fP \fBCreateRow\fP ()"
.br
.ti -1c
.RI "override void \fBSetRow\fP (\fBSourceResearch\&.Row\fP r)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB4\fP of file \fBSourceResearch\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override \fBSourceResearch\&.Row\fP SourceResearch\&.CreateRow ()"

.PP
Definition at line \fB7\fP of file \fBSourceResearch\&.cs\fP\&.
.SS "override void SourceResearch\&.SetRow (\fBSourceResearch\&.Row\fP r)"

.PP
Definition at line \fB28\fP of file \fBSourceResearch\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
