.TH "SourceFood.Row2" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SourceFood.Row2
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSourceThingV\&.Row\fP\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBidTaste\fP"
.br
.ti -1c
.RI "int \fBTST\fP"
.br
.ti -1c
.RI "int \fBNUT\fP"
.br
.ti -1c
.RI "int \fBSTR\fP"
.br
.ti -1c
.RI "int \fBSTR2\fP"
.br
.ti -1c
.RI "int \fBEND\fP"
.br
.ti -1c
.RI "int \fBEND2\fP"
.br
.ti -1c
.RI "int \fBDEX\fP"
.br
.ti -1c
.RI "int \fBDEX2\fP"
.br
.ti -1c
.RI "int \fBPER\fP"
.br
.ti -1c
.RI "int \fBPER2\fP"
.br
.ti -1c
.RI "int \fBLER\fP"
.br
.ti -1c
.RI "int \fBLER2\fP"
.br
.ti -1c
.RI "int \fBWIL\fP"
.br
.ti -1c
.RI "int \fBWIL2\fP"
.br
.ti -1c
.RI "int \fBMAG\fP"
.br
.ti -1c
.RI "int \fBMAG2\fP"
.br
.ti -1c
.RI "int \fBCHA\fP"
.br
.ti -1c
.RI "int \fBCHA2\fP"
.br
.in -1c

Public Attributes inherited from \fBSourceThingV\&.Row\fP
.in +1c
.ti -1c
.RI "string[] \fBparse\fP"
.br
.in -1c

Public Attributes inherited from \fBSourceThing\&.Row\fP
.in +1c
.ti -1c
.RI "string \fBunknown_JP\fP"
.br
.ti -1c
.RI "string \fBunit_JP\fP"
.br
.ti -1c
.RI "string \fBnaming\fP"
.br
.ti -1c
.RI "string \fBunit\fP"
.br
.ti -1c
.RI "string \fBunknown\fP"
.br
.ti -1c
.RI "int[] \fBaltTiles\fP"
.br
.ti -1c
.RI "int[] \fBanime\fP"
.br
.ti -1c
.RI "string[] \fBdisassemble\fP"
.br
.ti -1c
.RI "int \fBHP\fP"
.br
.ti -1c
.RI "int \fBweight\fP"
.br
.ti -1c
.RI "int \fBelectricity\fP"
.br
.ti -1c
.RI "int \fBrange\fP"
.br
.ti -1c
.RI "string \fBattackType\fP"
.br
.ti -1c
.RI "int[] \fBoffense\fP"
.br
.ti -1c
.RI "int[] \fBsubstats\fP"
.br
.ti -1c
.RI "int[] \fBdefense\fP"
.br
.ti -1c
.RI "string \fBidToggleExtra\fP"
.br
.ti -1c
.RI "string \fBidActorEx\fP"
.br
.ti -1c
.RI "string \fBworkTag\fP"
.br
.ti -1c
.RI "string[] \fBroomName_JP\fP"
.br
.ti -1c
.RI "string[] \fBroomName\fP"
.br
.ti -1c
.RI "int[] \fB_altTiles\fP"
.br
.ti -1c
.RI "bool \fBignoreAltFix\fP"
.br
.ti -1c
.RI "string \fBname_L\fP"
.br
.ti -1c
.RI "string \fBdetail_L\fP"
.br
.ti -1c
.RI "string \fBunit_L\fP"
.br
.ti -1c
.RI "string \fBunknown_L\fP"
.br
.ti -1c
.RI "string[] \fBname2_L\fP"
.br
.ti -1c
.RI "string[] \fBroomName_L\fP"
.br
.in -1c

Public Attributes inherited from \fBCardRow\fP
.in +1c
.ti -1c
.RI "string \fBid\fP"
.br
.ti -1c
.RI "string \fBidExtra\fP"
.br
.ti -1c
.RI "string \fBtierGroup\fP"
.br
.ti -1c
.RI "string \fBlightData\fP"
.br
.ti -1c
.RI "string \fB_origin\fP"
.br
.ti -1c
.RI "int \fBidShadow\fP"
.br
.ti -1c
.RI "int \fBquality\fP"
.br
.ti -1c
.RI "int[] \fBelements\fP"
.br
.ti -1c
.RI "int[] \fBshadow\fP"
.br
.ti -1c
.RI "int[] \fBsize\fP"
.br
.ti -1c
.RI "int[] \fBlight\fP"
.br
.ti -1c
.RI "string[] \fBloot\fP"
.br
.ti -1c
.RI "string[] \fBfilter\fP"
.br
.ti -1c
.RI "string[] \fBtrait\fP"
.br
.ti -1c
.RI "string[] \fBidActor\fP"
.br
.ti -1c
.RI "string[] \fBvals\fP"
.br
.ti -1c
.RI "string[] \fBname2\fP"
.br
.ti -1c
.RI "string[] \fBname2_JP\fP"
.br
.ti -1c
.RI "Dictionary< int, int > \fBelementMap\fP"
.br
.ti -1c
.RI "Sprite \fBsprite\fP"
.br
.ti -1c
.RI "\fBCardRow\fP \fBorigin\fP"
.br
.ti -1c
.RI "bool \fBisOrigin\fP"
.br
.ti -1c
.RI "bool \fBisChara\fP"
.br
.ti -1c
.RI "\fBCard\fP \fB_model\fP"
.br
.in -1c

Public Attributes inherited from \fBRenderRow\fP
.in +1c
.ti -1c
.RI "int[] \fBtiles\fP"
.br
.ti -1c
.RI "int[] \fB_tiles\fP"
.br
.ti -1c
.RI "int[] \fBskins\fP"
.br
.ti -1c
.RI "int \fBcolorMod\fP"
.br
.ti -1c
.RI "int \fBsort\fP"
.br
.ti -1c
.RI "int \fBvalue\fP"
.br
.ti -1c
.RI "int \fBLV\fP"
.br
.ti -1c
.RI "int \fBchance\fP"
.br
.ti -1c
.RI "int \fBtempChance\fP"
.br
.ti -1c
.RI "int \fBsnowTile\fP"
.br
.ti -1c
.RI "string \fBname\fP"
.br
.ti -1c
.RI "string \fBname_JP\fP"
.br
.ti -1c
.RI "string \fBdetail\fP"
.br
.ti -1c
.RI "string \fBdetail_JP\fP"
.br
.ti -1c
.RI "string \fB_idRenderData\fP"
.br
.ti -1c
.RI "string \fB_tileType\fP"
.br
.ti -1c
.RI "string \fBdefMat\fP"
.br
.ti -1c
.RI "string \fBcolorType\fP"
.br
.ti -1c
.RI "string \fBcategory\fP"
.br
.ti -1c
.RI "string \fBidSound\fP"
.br
.ti -1c
.RI "string \fBaliasPref\fP"
.br
.ti -1c
.RI "string[] \fBcomponents\fP"
.br
.ti -1c
.RI "string[] \fBfactory\fP"
.br
.ti -1c
.RI "string[] \fBrecipeKey\fP"
.br
.ti -1c
.RI "string[] \fBtag\fP"
.br
.ti -1c
.RI "int \fBW\fP = 1"
.br
.ti -1c
.RI "int \fBH\fP = 1"
.br
.ti -1c
.RI "bool \fBmultisize\fP"
.br
.ti -1c
.RI "\fBSourcePref\fP \fBpref\fP"
.br
.ti -1c
.RI "\fBRenderData\fP \fBrenderData\fP"
.br
.ti -1c
.RI "Sprite[,] \fBsprites\fP"
.br
.ti -1c
.RI "\fBTileType\fP \fBtileType\fP"
.br
.ti -1c
.RI "bool \fBuseAltColor\fP"
.br
.ti -1c
.RI "bool \fBuseRandomColor\fP"
.br
.ti -1c
.RI "bool \fBfixedMaterial\fP"
.br
.ti -1c
.RI "\fBSourceMaterial\&.Row\fP \fBDefaultMaterial\fP"
.br
.ti -1c
.RI "SpriteReplacer \fBreplacer\fP"
.br
.ti -1c
.RI "string \fB_nameSearch\fP"
.br
.ti -1c
.RI "string \fB_nameSearchJP\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override bool \fBUseAlias\fP\fR [get]\fP"
.br
.ti -1c
.RI "override string \fBGetAlias\fP\fR [get]\fP"
.br
.in -1c

Properties inherited from \fBSourceThingV\&.Row\fP
.in +1c
.ti -1c
.RI "override bool \fBUseAlias\fP\fR [get]\fP"
.br
.ti -1c
.RI "override string \fBGetAlias\fP\fR [get]\fP"
.br
.in -1c

Properties inherited from \fBSourceThing\&.Row\fP
.in +1c
.ti -1c
.RI "override bool \fBUseAlias\fP\fR [get]\fP"
.br
.ti -1c
.RI "override string \fBGetAlias\fP\fR [get]\fP"
.br
.ti -1c
.RI "override string \fBRecipeID\fP\fR [get]\fP"
.br
.in -1c

Properties inherited from \fBCardRow\fP
.in +1c
.ti -1c
.RI "\fBCard\fP \fBmodel\fP\fR [get]\fP"
.br
.ti -1c
.RI "override string \fBidRenderData\fP\fR [get]\fP"
.br
.ti -1c
.RI "override string \fBidSprite\fP\fR [get]\fP"
.br
.ti -1c
.RI "override string \fBidString\fP\fR [get]\fP"
.br
.ti -1c
.RI "override string \fBpathSprite\fP\fR [get]\fP"
.br
.in -1c

Properties inherited from \fBRenderRow\fP
.in +1c
.ti -1c
.RI "virtual string \fBidString\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual string \fBRecipeID\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual string \fBpathRenderData\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual string \fBidRenderData\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual \fBRenderData\fP \fBdefaultRenderData\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual string \fBpathSprite\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual string \fBidSprite\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual string \fBprefabName\fP\fR [get]\fP"
.br
.ti -1c
.RI "\fBSourceCategory\&.Row\fP \fBCategory\fP\fR [get]\fP"
.br
.ti -1c
.RI "string \fBRecipeCat\fP\fR [get]\fP"
.br
.ti -1c
.RI "\fBSourceManager\fP \fBsources\fP\fR [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Public Member Functions inherited from \fBSourceThing\&.Row\fP
.in +1c
.ti -1c
.RI "override void \fBOnImportData\fP (SourceData data)"
.br
.ti -1c
.RI "override void \fBSetTiles\fP ()"
.br
.ti -1c
.RI "override string \fBGetName\fP (\fBSourceMaterial\&.Row\fP mat, int sum)"
.br
.ti -1c
.RI "override string \fBGetName\fP ()"
.br
.ti -1c
.RI "override string \fBGetSearchName\fP (bool jp)"
.br
.in -1c

Public Member Functions inherited from \fBCardRow\fP
.in +1c
.ti -1c
.RI "override \fBSourcePref\fP \fBGetPref\fP ()"
.br
.ti -1c
.RI "override void \fBOnImportData\fP (SourceData data)"
.br
.ti -1c
.RI "virtual string \fBGetName\fP (int i)"
.br
.ti -1c
.RI "override string \fBGetEditorListName\fP ()"
.br
.ti -1c
.RI "override string \fBGetName\fP ()"
.br
.ti -1c
.RI "string \fBGetName\fP (\fBCard\fP c, bool full=false)"
.br
.in -1c

Public Member Functions inherited from \fBRenderRow\fP
.in +1c
.ti -1c
.RI "bool \fBHasTag\fP (CTAG _tag)"
.br
.ti -1c
.RI "bool \fBContainsTag\fP (string _tag)"
.br
.ti -1c
.RI "override void \fBOnImportData\fP (SourceData data)"
.br
.ti -1c
.RI "void \fBSetRenderData\fP ()"
.br
.ti -1c
.RI "int \fBConvertTile\fP (int tile)"
.br
.ti -1c
.RI "Sprite \fBGetSprite\fP (int dir=0, int skin=0, bool snow=false)"
.br
.ti -1c
.RI "void \fBSetSpriteRenderer\fP (SpriteRenderer sr, Sprite sprite=null, int matCol=0, bool setTransform=true, int dir=0)"
.br
.ti -1c
.RI "void \fBSetImage\fP (Image image, Sprite sprite=null, int matCol=0, bool setNativeSize=true, int dir=0, int idSkin=0)"
.br
.ti -1c
.RI "void \fBSetRenderParam\fP (\fBRenderParam\fP p, \fBSourceMaterial\&.Row\fP mat, int dir)"
.br
.ti -1c
.RI "virtual unsafe \fBRenderParam\fP \fBGetRenderParam\fP (\fBSourceMaterial\&.Row\fP mat, int dir, \fBPoint\fP point=null, int bridgeHeight=\-1)"
.br
.ti -1c
.RI "virtual int \fBGetTile\fP (\fBSourceMaterial\&.Row\fP mat, int dir=0)"
.br
.ti -1c
.RI "int \fBGetColorInt\fP (\fBSourceMaterial\&.Row\fP mat)"
.br
.in -1c

Static Public Attributes inherited from \fBRenderRow\fP
.in +1c
.ti -1c
.RI "static Dictionary< string, \fBRenderData\fP > \fBDictRenderData\fP = new Dictionary<string, \fBRenderData\fP>()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB118\fP of file \fBSourceFood\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int SourceFood\&.Row2\&.CHA"

.PP
Definition at line \fB192\fP of file \fBSourceFood\&.cs\fP\&.
.SS "int SourceFood\&.Row2\&.CHA2"

.PP
Definition at line \fB195\fP of file \fBSourceFood\&.cs\fP\&.
.SS "int SourceFood\&.Row2\&.DEX"

.PP
Definition at line \fB162\fP of file \fBSourceFood\&.cs\fP\&.
.SS "int SourceFood\&.Row2\&.DEX2"

.PP
Definition at line \fB165\fP of file \fBSourceFood\&.cs\fP\&.
.SS "int SourceFood\&.Row2\&.END"

.PP
Definition at line \fB156\fP of file \fBSourceFood\&.cs\fP\&.
.SS "int SourceFood\&.Row2\&.END2"

.PP
Definition at line \fB159\fP of file \fBSourceFood\&.cs\fP\&.
.SS "string SourceFood\&.Row2\&.idTaste"

.PP
Definition at line \fB141\fP of file \fBSourceFood\&.cs\fP\&.
.SS "int SourceFood\&.Row2\&.LER"

.PP
Definition at line \fB174\fP of file \fBSourceFood\&.cs\fP\&.
.SS "int SourceFood\&.Row2\&.LER2"

.PP
Definition at line \fB177\fP of file \fBSourceFood\&.cs\fP\&.
.SS "int SourceFood\&.Row2\&.MAG"

.PP
Definition at line \fB186\fP of file \fBSourceFood\&.cs\fP\&.
.SS "int SourceFood\&.Row2\&.MAG2"

.PP
Definition at line \fB189\fP of file \fBSourceFood\&.cs\fP\&.
.SS "int SourceFood\&.Row2\&.NUT"

.PP
Definition at line \fB147\fP of file \fBSourceFood\&.cs\fP\&.
.SS "int SourceFood\&.Row2\&.PER"

.PP
Definition at line \fB168\fP of file \fBSourceFood\&.cs\fP\&.
.SS "int SourceFood\&.Row2\&.PER2"

.PP
Definition at line \fB171\fP of file \fBSourceFood\&.cs\fP\&.
.SS "int SourceFood\&.Row2\&.STR"

.PP
Definition at line \fB150\fP of file \fBSourceFood\&.cs\fP\&.
.SS "int SourceFood\&.Row2\&.STR2"

.PP
Definition at line \fB153\fP of file \fBSourceFood\&.cs\fP\&.
.SS "int SourceFood\&.Row2\&.TST"

.PP
Definition at line \fB144\fP of file \fBSourceFood\&.cs\fP\&.
.SS "int SourceFood\&.Row2\&.WIL"

.PP
Definition at line \fB180\fP of file \fBSourceFood\&.cs\fP\&.
.SS "int SourceFood\&.Row2\&.WIL2"

.PP
Definition at line \fB183\fP of file \fBSourceFood\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "override string SourceFood\&.Row2\&.GetAlias\fR [get]\fP"

.PP
Definition at line \fB132\fP of file \fBSourceFood\&.cs\fP\&.
.SS "override bool SourceFood\&.Row2\&.UseAlias\fR [get]\fP"

.PP
Definition at line \fB122\fP of file \fBSourceFood\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
