.TH "SourceMaterial.Row" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SourceMaterial.Row
.SH SYNOPSIS
.br
.PP
.PP
Inherits SourceData\&.BaseRow\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnImportData\fP (SourceData data)"
.br
.ti -1c
.RI "void \fBInit\fP ()"
.br
.ti -1c
.RI "void \fBSetTiles\fP ()"
.br
.ti -1c
.RI "void \fBAddBlood\fP (\fBPoint\fP p, int a=1)"
.br
.ti -1c
.RI "void \fBPlayHitEffect\fP (\fBPoint\fP p)"
.br
.ti -1c
.RI "Color \fBGetColor\fP ()"
.br
.ti -1c
.RI "string \fBTryGetSound\fP (string suffx, \fBRenderRow\fP c=null)"
.br
.ti -1c
.RI "string \fBGetSoundDead\fP (\fBRenderRow\fP c=null)"
.br
.ti -1c
.RI "string \fBGetSoundDrop\fP (\fBRenderRow\fP c=null)"
.br
.ti -1c
.RI "string \fBGetSoundCraft\fP (\fBRenderRow\fP c=null)"
.br
.ti -1c
.RI "string \fBGetSoundImpact\fP (\fBRenderRow\fP c=null)"
.br
.ti -1c
.RI "void \fBCreateByProduct\fP (\fBThing\fP container, int num)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBid\fP"
.br
.ti -1c
.RI "string \fBalias\fP"
.br
.ti -1c
.RI "string \fBname_JP\fP"
.br
.ti -1c
.RI "string \fBname\fP"
.br
.ti -1c
.RI "string \fBcategory\fP"
.br
.ti -1c
.RI "string[] \fBtag\fP"
.br
.ti -1c
.RI "string \fBthing\fP"
.br
.ti -1c
.RI "string[] \fBgoods\fP"
.br
.ti -1c
.RI "string[] \fBminerals\fP"
.br
.ti -1c
.RI "int \fBdecal\fP"
.br
.ti -1c
.RI "int \fBdecay\fP"
.br
.ti -1c
.RI "int \fBgrass\fP"
.br
.ti -1c
.RI "int \fBdefFloor\fP"
.br
.ti -1c
.RI "int \fBdefBlock\fP"
.br
.ti -1c
.RI "int \fBedge\fP"
.br
.ti -1c
.RI "int \fBramp\fP"
.br
.ti -1c
.RI "string \fBidSound\fP"
.br
.ti -1c
.RI "string \fBsoundFoot\fP"
.br
.ti -1c
.RI "int \fBhardness\fP"
.br
.ti -1c
.RI "string[] \fBgroups\fP"
.br
.ti -1c
.RI "int \fBtier\fP"
.br
.ti -1c
.RI "int \fBchance\fP"
.br
.ti -1c
.RI "int \fBweight\fP"
.br
.ti -1c
.RI "int \fBvalue\fP"
.br
.ti -1c
.RI "int \fBquality\fP"
.br
.ti -1c
.RI "int \fBatk\fP"
.br
.ti -1c
.RI "int \fBdmg\fP"
.br
.ti -1c
.RI "int \fBdv\fP"
.br
.ti -1c
.RI "int \fBpv\fP"
.br
.ti -1c
.RI "int \fBdice\fP"
.br
.ti -1c
.RI "string[] \fBbits\fP"
.br
.ti -1c
.RI "int[] \fBelements\fP"
.br
.ti -1c
.RI "string[] \fBaltName\fP"
.br
.ti -1c
.RI "string[] \fBaltName_JP\fP"
.br
.ti -1c
.RI "Color \fBmatColor\fP"
.br
.ti -1c
.RI "Color \fBaltColor\fP"
.br
.ti -1c
.RI "Dictionary< int, int > \fBelementMap\fP"
.br
.ti -1c
.RI "string \fBname_L\fP"
.br
.ti -1c
.RI "string \fBdetail_L\fP"
.br
.ti -1c
.RI "string[] \fBaltName_L\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static string[] \fBIDPick\fP"
.br
.ti -1c
.RI "static string[] \fBIDAxe\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override bool \fBUseAlias\fP\fR [get]\fP"
.br
.ti -1c
.RI "override string \fBGetAlias\fP\fR [get]\fP"
.br
.ti -1c
.RI "bool \fBUsePick\fP\fR [get]\fP"
.br
.ti -1c
.RI "bool \fBUseAxe\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB147\fP of file \fBSourceMaterial\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void SourceMaterial\&.Row\&.AddBlood (\fBPoint\fP p, int a = \fR1\fP)"

.PP
Definition at line \fB191\fP of file \fBSourceMaterial\&.cs\fP\&.
.SS "void SourceMaterial\&.Row\&.CreateByProduct (\fBThing\fP container, int num)"

.PP
Definition at line \fB264\fP of file \fBSourceMaterial\&.cs\fP\&.
.SS "Color SourceMaterial\&.Row\&.GetColor ()"

.PP
Definition at line \fB215\fP of file \fBSourceMaterial\&.cs\fP\&.
.SS "string SourceMaterial\&.Row\&.GetSoundCraft (\fBRenderRow\fP c = \fRnull\fP)"

.PP
Definition at line \fB244\fP of file \fBSourceMaterial\&.cs\fP\&.
.SS "string SourceMaterial\&.Row\&.GetSoundDead (\fBRenderRow\fP c = \fRnull\fP)"

.PP
Definition at line \fB232\fP of file \fBSourceMaterial\&.cs\fP\&.
.SS "string SourceMaterial\&.Row\&.GetSoundDrop (\fBRenderRow\fP c = \fRnull\fP)"

.PP
Definition at line \fB238\fP of file \fBSourceMaterial\&.cs\fP\&.
.SS "string SourceMaterial\&.Row\&.GetSoundImpact (\fBRenderRow\fP c = \fRnull\fP)"

.PP
Definition at line \fB254\fP of file \fBSourceMaterial\&.cs\fP\&.
.SS "void SourceMaterial\&.Row\&.Init ()"

.PP
Definition at line \fB177\fP of file \fBSourceMaterial\&.cs\fP\&.
.SS "override void SourceMaterial\&.Row\&.OnImportData (SourceData data)"

.PP
Definition at line \fB170\fP of file \fBSourceMaterial\&.cs\fP\&.
.SS "void SourceMaterial\&.Row\&.PlayHitEffect (\fBPoint\fP p)"

.PP
Definition at line \fB209\fP of file \fBSourceMaterial\&.cs\fP\&.
.SS "void SourceMaterial\&.Row\&.SetTiles ()"

.PP
Definition at line \fB186\fP of file \fBSourceMaterial\&.cs\fP\&.
.SS "string SourceMaterial\&.Row\&.TryGetSound (string suffx, \fBRenderRow\fP c = \fRnull\fP)"

.PP
Definition at line \fB221\fP of file \fBSourceMaterial\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "string SourceMaterial\&.Row\&.alias"

.PP
Definition at line \fB407\fP of file \fBSourceMaterial\&.cs\fP\&.
.SS "Color SourceMaterial\&.Row\&.altColor"

.PP
Definition at line \fB511\fP of file \fBSourceMaterial\&.cs\fP\&.
.SS "string [] SourceMaterial\&.Row\&.altName"

.PP
Definition at line \fB500\fP of file \fBSourceMaterial\&.cs\fP\&.
.SS "string [] SourceMaterial\&.Row\&.altName_JP"

.PP
Definition at line \fB503\fP of file \fBSourceMaterial\&.cs\fP\&.
.SS "string [] SourceMaterial\&.Row\&.altName_L"

.PP
Definition at line \fB539\fP of file \fBSourceMaterial\&.cs\fP\&.
.SS "int SourceMaterial\&.Row\&.atk"

.PP
Definition at line \fB479\fP of file \fBSourceMaterial\&.cs\fP\&.
.SS "string [] SourceMaterial\&.Row\&.bits"

.PP
Definition at line \fB494\fP of file \fBSourceMaterial\&.cs\fP\&.
.SS "string SourceMaterial\&.Row\&.category"

.PP
Definition at line \fB416\fP of file \fBSourceMaterial\&.cs\fP\&.
.SS "int SourceMaterial\&.Row\&.chance"

.PP
Definition at line \fB467\fP of file \fBSourceMaterial\&.cs\fP\&.
.SS "int SourceMaterial\&.Row\&.decal"

.PP
Definition at line \fB431\fP of file \fBSourceMaterial\&.cs\fP\&.
.SS "int SourceMaterial\&.Row\&.decay"

.PP
Definition at line \fB434\fP of file \fBSourceMaterial\&.cs\fP\&.
.SS "int SourceMaterial\&.Row\&.defBlock"

.PP
Definition at line \fB443\fP of file \fBSourceMaterial\&.cs\fP\&.
.SS "int SourceMaterial\&.Row\&.defFloor"

.PP
Definition at line \fB440\fP of file \fBSourceMaterial\&.cs\fP\&.
.SS "string SourceMaterial\&.Row\&.detail_L"

.PP
Definition at line \fB536\fP of file \fBSourceMaterial\&.cs\fP\&.
.SS "int SourceMaterial\&.Row\&.dice"

.PP
Definition at line \fB491\fP of file \fBSourceMaterial\&.cs\fP\&.
.SS "int SourceMaterial\&.Row\&.dmg"

.PP
Definition at line \fB482\fP of file \fBSourceMaterial\&.cs\fP\&.
.SS "int SourceMaterial\&.Row\&.dv"

.PP
Definition at line \fB485\fP of file \fBSourceMaterial\&.cs\fP\&.
.SS "int SourceMaterial\&.Row\&.edge"

.PP
Definition at line \fB446\fP of file \fBSourceMaterial\&.cs\fP\&.
.SS "Dictionary<int, int> SourceMaterial\&.Row\&.elementMap"

.PP
Definition at line \fB514\fP of file \fBSourceMaterial\&.cs\fP\&.
.SS "int [] SourceMaterial\&.Row\&.elements"

.PP
Definition at line \fB497\fP of file \fBSourceMaterial\&.cs\fP\&.
.SS "string [] SourceMaterial\&.Row\&.goods"

.PP
Definition at line \fB425\fP of file \fBSourceMaterial\&.cs\fP\&.
.SS "int SourceMaterial\&.Row\&.grass"

.PP
Definition at line \fB437\fP of file \fBSourceMaterial\&.cs\fP\&.
.SS "string [] SourceMaterial\&.Row\&.groups"

.PP
Definition at line \fB461\fP of file \fBSourceMaterial\&.cs\fP\&.
.SS "int SourceMaterial\&.Row\&.hardness"

.PP
Definition at line \fB458\fP of file \fBSourceMaterial\&.cs\fP\&.
.SS "int SourceMaterial\&.Row\&.id"

.PP
Definition at line \fB404\fP of file \fBSourceMaterial\&.cs\fP\&.
.SS "string [] SourceMaterial\&.Row\&.IDAxe\fR [static]\fP"
\fBInitial value:\fP
.nf
= new string[]
        {
            "wood"
        }
.PP
.fi

.PP
Definition at line \fB527\fP of file \fBSourceMaterial\&.cs\fP\&.
.SS "string [] SourceMaterial\&.Row\&.IDPick\fR [static]\fP"
\fBInitial value:\fP
.nf
= new string[]
        {
            "rock",
            "ore",
            "gem",
            "crystal",
            "bone"
        }
.PP
.fi

.PP
Definition at line \fB517\fP of file \fBSourceMaterial\&.cs\fP\&.
.SS "string SourceMaterial\&.Row\&.idSound"

.PP
Definition at line \fB452\fP of file \fBSourceMaterial\&.cs\fP\&.
.SS "Color SourceMaterial\&.Row\&.matColor"

.PP
Definition at line \fB507\fP of file \fBSourceMaterial\&.cs\fP\&.
.SS "string [] SourceMaterial\&.Row\&.minerals"

.PP
Definition at line \fB428\fP of file \fBSourceMaterial\&.cs\fP\&.
.SS "string SourceMaterial\&.Row\&.name"

.PP
Definition at line \fB413\fP of file \fBSourceMaterial\&.cs\fP\&.
.SS "string SourceMaterial\&.Row\&.name_JP"

.PP
Definition at line \fB410\fP of file \fBSourceMaterial\&.cs\fP\&.
.SS "string SourceMaterial\&.Row\&.name_L"

.PP
Definition at line \fB533\fP of file \fBSourceMaterial\&.cs\fP\&.
.SS "int SourceMaterial\&.Row\&.pv"

.PP
Definition at line \fB488\fP of file \fBSourceMaterial\&.cs\fP\&.
.SS "int SourceMaterial\&.Row\&.quality"

.PP
Definition at line \fB476\fP of file \fBSourceMaterial\&.cs\fP\&.
.SS "int SourceMaterial\&.Row\&.ramp"

.PP
Definition at line \fB449\fP of file \fBSourceMaterial\&.cs\fP\&.
.SS "string SourceMaterial\&.Row\&.soundFoot"

.PP
Definition at line \fB455\fP of file \fBSourceMaterial\&.cs\fP\&.
.SS "string [] SourceMaterial\&.Row\&.tag"

.PP
Definition at line \fB419\fP of file \fBSourceMaterial\&.cs\fP\&.
.SS "string SourceMaterial\&.Row\&.thing"

.PP
Definition at line \fB422\fP of file \fBSourceMaterial\&.cs\fP\&.
.SS "int SourceMaterial\&.Row\&.tier"

.PP
Definition at line \fB464\fP of file \fBSourceMaterial\&.cs\fP\&.
.SS "int SourceMaterial\&.Row\&.value"

.PP
Definition at line \fB473\fP of file \fBSourceMaterial\&.cs\fP\&.
.SS "int SourceMaterial\&.Row\&.weight"

.PP
Definition at line \fB470\fP of file \fBSourceMaterial\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "override string SourceMaterial\&.Row\&.GetAlias\fR [get]\fP"

.PP
Definition at line \fB161\fP of file \fBSourceMaterial\&.cs\fP\&.
.SS "override bool SourceMaterial\&.Row\&.UseAlias\fR [get]\fP"

.PP
Definition at line \fB151\fP of file \fBSourceMaterial\&.cs\fP\&.
.SS "bool SourceMaterial\&.Row\&.UseAxe\fR [get]\fP"

.PP
Definition at line \fB385\fP of file \fBSourceMaterial\&.cs\fP\&.
.SS "bool SourceMaterial\&.Row\&.UsePick\fR [get]\fP"

.PP
Definition at line \fB375\fP of file \fBSourceMaterial\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
