.TH "SourceTactics" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SourceTactics
.SH SYNOPSIS
.br
.PP
.PP
Inherits SourceDataString< SourceTactics\&.Row >\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRow\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override \fBSourceTactics\&.Row\fP \fBCreateRow\fP ()"
.br
.ti -1c
.RI "override void \fBSetRow\fP (\fBSourceTactics\&.Row\fP r)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB4\fP of file \fBSourceTactics\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override \fBSourceTactics\&.Row\fP SourceTactics\&.CreateRow ()"

.PP
Definition at line \fB7\fP of file \fBSourceTactics\&.cs\fP\&.
.SS "override void SourceTactics\&.SetRow (\fBSourceTactics\&.Row\fP r)"

.PP
Definition at line \fB33\fP of file \fBSourceTactics\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
