.TH "SourceGlobalTile" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SourceGlobalTile
.SH SYNOPSIS
.br
.PP
.PP
Inherits SourceDataInt< SourceGlobalTile\&.Row >\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRow\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override \fBSourceGlobalTile\&.Row\fP \fBCreateRow\fP ()"
.br
.ti -1c
.RI "override void \fBSetRow\fP (\fBSourceGlobalTile\&.Row\fP r)"
.br
.ti -1c
.RI "override void \fBOnInit\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Dictionary< int, \fBSourceGlobalTile\&.Row\fP > \fBtileAlias\fP = new Dictionary<int, \fBSourceGlobalTile\&.Row\fP>()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB5\fP of file \fBSourceGlobalTile\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override \fBSourceGlobalTile\&.Row\fP SourceGlobalTile\&.CreateRow ()"

.PP
Definition at line \fB8\fP of file \fBSourceGlobalTile\&.cs\fP\&.
.SS "override void SourceGlobalTile\&.OnInit ()"

.PP
Definition at line \fB36\fP of file \fBSourceGlobalTile\&.cs\fP\&.
.SS "override void SourceGlobalTile\&.SetRow (\fBSourceGlobalTile\&.Row\fP r)"

.PP
Definition at line \fB30\fP of file \fBSourceGlobalTile\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "Dictionary<int, \fBSourceGlobalTile\&.Row\fP> SourceGlobalTile\&.tileAlias = new Dictionary<int, \fBSourceGlobalTile\&.Row\fP>()"

.PP
Definition at line \fB48\fP of file \fBSourceGlobalTile\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
