.TH "SourceZoneAffix" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SourceZoneAffix
.SH SYNOPSIS
.br
.PP
.PP
Inherits SourceDataInt< SourceZoneAffix\&.Row >\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRow\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override \fBSourceZoneAffix\&.Row\fP \fBCreateRow\fP ()"
.br
.ti -1c
.RI "override void \fBSetRow\fP (\fBSourceZoneAffix\&.Row\fP r)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB4\fP of file \fBSourceZoneAffix\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override \fBSourceZoneAffix\&.Row\fP SourceZoneAffix\&.CreateRow ()"

.PP
Definition at line \fB7\fP of file \fBSourceZoneAffix\&.cs\fP\&.
.SS "override void SourceZoneAffix\&.SetRow (\fBSourceZoneAffix\&.Row\fP r)"

.PP
Definition at line \fB23\fP of file \fBSourceZoneAffix\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
