.TH "SourceMaterial" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SourceMaterial
.SH SYNOPSIS
.br
.PP
.PP
Inherits SourceDataInt< SourceMaterial\&.Row >\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRow\fP"
.br
.ti -1c
.RI "class \fBTier\fP"
.br
.ti -1c
.RI "class \fBTierList\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override \fBSourceMaterial\&.Row\fP \fBCreateRow\fP ()"
.br
.ti -1c
.RI "override void \fBSetRow\fP (\fBSourceMaterial\&.Row\fP r)"
.br
.ti -1c
.RI "override void \fBOnInit\fP ()"
.br
.ti -1c
.RI "override void \fBOnAfterImportData\fP ()"
.br
.ti -1c
.RI "void \fBOnImportRow\fP (\fBSourceMaterial\&.Row\fP r)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static Dictionary< string, \fBSourceMaterial\&.TierList\fP > \fBtierMap\fP = new Dictionary<string, \fBSourceMaterial\&.TierList\fP>()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override string[] \fBImportFields\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB7\fP of file \fBSourceMaterial\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override \fBSourceMaterial\&.Row\fP SourceMaterial\&.CreateRow ()"

.PP
Definition at line \fB10\fP of file \fBSourceMaterial\&.cs\fP\&.
.SS "override void SourceMaterial\&.OnAfterImportData ()"

.PP
Definition at line \fB103\fP of file \fBSourceMaterial\&.cs\fP\&.
.SS "void SourceMaterial\&.OnImportRow (\fBSourceMaterial\&.Row\fP r)"

.PP
Definition at line \fB109\fP of file \fBSourceMaterial\&.cs\fP\&.
.SS "override void SourceMaterial\&.OnInit ()"

.PP
Definition at line \fB58\fP of file \fBSourceMaterial\&.cs\fP\&.
.SS "override void SourceMaterial\&.SetRow (\fBSourceMaterial\&.Row\fP r)"

.PP
Definition at line \fB52\fP of file \fBSourceMaterial\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "Dictionary<string, \fBSourceMaterial\&.TierList\fP> SourceMaterial\&.tierMap = new Dictionary<string, \fBSourceMaterial\&.TierList\fP>()\fR [static]\fP"

.PP
Definition at line \fB143\fP of file \fBSourceMaterial\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "override string [] SourceMaterial\&.ImportFields\fR [get]\fP"

.PP
Definition at line \fB123\fP of file \fBSourceMaterial\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
