.TH "SourceMaterial.TierList" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SourceMaterial.TierList
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBSourceMaterial\&.Tier\fP[] \fBtiers\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB543\fP of file \fBSourceMaterial\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SourceMaterial\&.TierList\&.TierList ()"

.PP
Definition at line \fB546\fP of file \fBSourceMaterial\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBSourceMaterial\&.Tier\fP [] SourceMaterial\&.TierList\&.tiers"

.PP
Definition at line \fB556\fP of file \fBSourceMaterial\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
