.TH "SourceStat.Row" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SourceStat.Row
.SH SYNOPSIS
.br
.PP
.PP
Inherits SourceData\&.BaseRow\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBid\fP"
.br
.ti -1c
.RI "string \fBalias\fP"
.br
.ti -1c
.RI "string \fBname_JP\fP"
.br
.ti -1c
.RI "string \fBname\fP"
.br
.ti -1c
.RI "string \fBtype\fP"
.br
.ti -1c
.RI "string \fBgroup\fP"
.br
.ti -1c
.RI "string \fBcurse\fP"
.br
.ti -1c
.RI "string \fBduration\fP"
.br
.ti -1c
.RI "int \fBhexPower\fP"
.br
.ti -1c
.RI "string[] \fBnegate\fP"
.br
.ti -1c
.RI "string[] \fBdefenseAttb\fP"
.br
.ti -1c
.RI "string[] \fBresistance\fP"
.br
.ti -1c
.RI "int \fBgainRes\fP"
.br
.ti -1c
.RI "string[] \fBelements\fP"
.br
.ti -1c
.RI "string[] \fBnullify\fP"
.br
.ti -1c
.RI "string[] \fBtag\fP"
.br
.ti -1c
.RI "int[] \fBphase\fP"
.br
.ti -1c
.RI "string \fBcolors\fP"
.br
.ti -1c
.RI "string \fBelement\fP"
.br
.ti -1c
.RI "string[] \fBeffect\fP"
.br
.ti -1c
.RI "string[] \fBstrPhase_JP\fP"
.br
.ti -1c
.RI "string[] \fBstrPhase\fP"
.br
.ti -1c
.RI "string \fBtextPhase_JP\fP"
.br
.ti -1c
.RI "string \fBtextPhase\fP"
.br
.ti -1c
.RI "string \fBtextEnd_JP\fP"
.br
.ti -1c
.RI "string \fBtextEnd\fP"
.br
.ti -1c
.RI "string \fBtextPhase2_JP\fP"
.br
.ti -1c
.RI "string \fBtextPhase2\fP"
.br
.ti -1c
.RI "string \fBgradient\fP"
.br
.ti -1c
.RI "bool \fBinvert\fP"
.br
.ti -1c
.RI "string \fBdetail_JP\fP"
.br
.ti -1c
.RI "string \fBdetail\fP"
.br
.ti -1c
.RI "string \fBname_L\fP"
.br
.ti -1c
.RI "string \fBdetail_L\fP"
.br
.ti -1c
.RI "string \fBtextPhase_L\fP"
.br
.ti -1c
.RI "string \fBtextPhase2_L\fP"
.br
.ti -1c
.RI "string \fBtextEnd_L\fP"
.br
.ti -1c
.RI "string[] \fBstrPhase_L\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override bool \fBUseAlias\fP\fR [get]\fP"
.br
.ti -1c
.RI "override string \fBGetAlias\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB87\fP of file \fBSourceStat\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "string SourceStat\&.Row\&.alias"

.PP
Definition at line \fB113\fP of file \fBSourceStat\&.cs\fP\&.
.SS "string SourceStat\&.Row\&.colors"

.PP
Definition at line \fB161\fP of file \fBSourceStat\&.cs\fP\&.
.SS "string SourceStat\&.Row\&.curse"

.PP
Definition at line \fB128\fP of file \fBSourceStat\&.cs\fP\&.
.SS "string [] SourceStat\&.Row\&.defenseAttb"

.PP
Definition at line \fB140\fP of file \fBSourceStat\&.cs\fP\&.
.SS "string SourceStat\&.Row\&.detail"

.PP
Definition at line \fB203\fP of file \fBSourceStat\&.cs\fP\&.
.SS "string SourceStat\&.Row\&.detail_JP"

.PP
Definition at line \fB200\fP of file \fBSourceStat\&.cs\fP\&.
.SS "string SourceStat\&.Row\&.detail_L"

.PP
Definition at line \fB209\fP of file \fBSourceStat\&.cs\fP\&.
.SS "string SourceStat\&.Row\&.duration"

.PP
Definition at line \fB131\fP of file \fBSourceStat\&.cs\fP\&.
.SS "string [] SourceStat\&.Row\&.effect"

.PP
Definition at line \fB167\fP of file \fBSourceStat\&.cs\fP\&.
.SS "string SourceStat\&.Row\&.element"

.PP
Definition at line \fB164\fP of file \fBSourceStat\&.cs\fP\&.
.SS "string [] SourceStat\&.Row\&.elements"

.PP
Definition at line \fB149\fP of file \fBSourceStat\&.cs\fP\&.
.SS "int SourceStat\&.Row\&.gainRes"

.PP
Definition at line \fB146\fP of file \fBSourceStat\&.cs\fP\&.
.SS "string SourceStat\&.Row\&.gradient"

.PP
Definition at line \fB194\fP of file \fBSourceStat\&.cs\fP\&.
.SS "string SourceStat\&.Row\&.group"

.PP
Definition at line \fB125\fP of file \fBSourceStat\&.cs\fP\&.
.SS "int SourceStat\&.Row\&.hexPower"

.PP
Definition at line \fB134\fP of file \fBSourceStat\&.cs\fP\&.
.SS "int SourceStat\&.Row\&.id"

.PP
Definition at line \fB110\fP of file \fBSourceStat\&.cs\fP\&.
.SS "bool SourceStat\&.Row\&.invert"

.PP
Definition at line \fB197\fP of file \fBSourceStat\&.cs\fP\&.
.SS "string SourceStat\&.Row\&.name"

.PP
Definition at line \fB119\fP of file \fBSourceStat\&.cs\fP\&.
.SS "string SourceStat\&.Row\&.name_JP"

.PP
Definition at line \fB116\fP of file \fBSourceStat\&.cs\fP\&.
.SS "string SourceStat\&.Row\&.name_L"

.PP
Definition at line \fB206\fP of file \fBSourceStat\&.cs\fP\&.
.SS "string [] SourceStat\&.Row\&.negate"

.PP
Definition at line \fB137\fP of file \fBSourceStat\&.cs\fP\&.
.SS "string [] SourceStat\&.Row\&.nullify"

.PP
Definition at line \fB152\fP of file \fBSourceStat\&.cs\fP\&.
.SS "int [] SourceStat\&.Row\&.phase"

.PP
Definition at line \fB158\fP of file \fBSourceStat\&.cs\fP\&.
.SS "string [] SourceStat\&.Row\&.resistance"

.PP
Definition at line \fB143\fP of file \fBSourceStat\&.cs\fP\&.
.SS "string [] SourceStat\&.Row\&.strPhase"

.PP
Definition at line \fB173\fP of file \fBSourceStat\&.cs\fP\&.
.SS "string [] SourceStat\&.Row\&.strPhase_JP"

.PP
Definition at line \fB170\fP of file \fBSourceStat\&.cs\fP\&.
.SS "string [] SourceStat\&.Row\&.strPhase_L"

.PP
Definition at line \fB221\fP of file \fBSourceStat\&.cs\fP\&.
.SS "string [] SourceStat\&.Row\&.tag"

.PP
Definition at line \fB155\fP of file \fBSourceStat\&.cs\fP\&.
.SS "string SourceStat\&.Row\&.textEnd"

.PP
Definition at line \fB185\fP of file \fBSourceStat\&.cs\fP\&.
.SS "string SourceStat\&.Row\&.textEnd_JP"

.PP
Definition at line \fB182\fP of file \fBSourceStat\&.cs\fP\&.
.SS "string SourceStat\&.Row\&.textEnd_L"

.PP
Definition at line \fB218\fP of file \fBSourceStat\&.cs\fP\&.
.SS "string SourceStat\&.Row\&.textPhase"

.PP
Definition at line \fB179\fP of file \fBSourceStat\&.cs\fP\&.
.SS "string SourceStat\&.Row\&.textPhase2"

.PP
Definition at line \fB191\fP of file \fBSourceStat\&.cs\fP\&.
.SS "string SourceStat\&.Row\&.textPhase2_JP"

.PP
Definition at line \fB188\fP of file \fBSourceStat\&.cs\fP\&.
.SS "string SourceStat\&.Row\&.textPhase2_L"

.PP
Definition at line \fB215\fP of file \fBSourceStat\&.cs\fP\&.
.SS "string SourceStat\&.Row\&.textPhase_JP"

.PP
Definition at line \fB176\fP of file \fBSourceStat\&.cs\fP\&.
.SS "string SourceStat\&.Row\&.textPhase_L"

.PP
Definition at line \fB212\fP of file \fBSourceStat\&.cs\fP\&.
.SS "string SourceStat\&.Row\&.type"

.PP
Definition at line \fB122\fP of file \fBSourceStat\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "override string SourceStat\&.Row\&.GetAlias\fR [get]\fP"

.PP
Definition at line \fB101\fP of file \fBSourceStat\&.cs\fP\&.
.SS "override bool SourceStat\&.Row\&.UseAlias\fR [get]\fP"

.PP
Definition at line \fB91\fP of file \fBSourceStat\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
