.TH "SourceElement" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SourceElement
.SH SYNOPSIS
.br
.PP
.PP
Inherits SourceDataInt< SourceElement\&.Row >\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRow\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override \fBSourceElement\&.Row\fP \fBCreateRow\fP ()"
.br
.ti -1c
.RI "override void \fBSetRow\fP (\fBSourceElement\&.Row\fP r)"
.br
.ti -1c
.RI "override void \fBOnInit\fP ()"
.br
.ti -1c
.RI "override void \fBOnAfterImportData\fP ()"
.br
.ti -1c
.RI "void \fBAddRow\fP (\fBSourceElement\&.Row\fP ele, int id, string idOrg)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "List< \fBSourceElement\&.Row\fP > \fBhobbies\fP = new List<\fBSourceElement\&.Row\fP>()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override string[] \fBImportFields\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB8\fP of file \fBSourceElement\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void SourceElement\&.AddRow (\fBSourceElement\&.Row\fP ele, int id, string idOrg)"

.PP
Definition at line \fB123\fP of file \fBSourceElement\&.cs\fP\&.
.SS "override \fBSourceElement\&.Row\fP SourceElement\&.CreateRow ()"

.PP
Definition at line \fB11\fP of file \fBSourceElement\&.cs\fP\&.
.SS "override void SourceElement\&.OnAfterImportData ()"

.PP
Definition at line \fB96\fP of file \fBSourceElement\&.cs\fP\&.
.SS "override void SourceElement\&.OnInit ()"

.PP
Definition at line \fB80\fP of file \fBSourceElement\&.cs\fP\&.
.SS "override void SourceElement\&.SetRow (\fBSourceElement\&.Row\fP r)"

.PP
Definition at line \fB74\fP of file \fBSourceElement\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "List<\fBSourceElement\&.Row\fP> SourceElement\&.hobbies = new List<\fBSourceElement\&.Row\fP>()"

.PP
Definition at line \fB165\fP of file \fBSourceElement\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "override string [] SourceElement\&.ImportFields\fR [get]\fP"

.PP
Definition at line \fB145\fP of file \fBSourceElement\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
