.TH "SourceSupplyType.Row" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SourceSupplyType.Row
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBname_L\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB7\fP of file \fBSourceSupplyType\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "string SourceSupplyType\&.Row\&.name_L"

.PP
Definition at line \fB10\fP of file \fBSourceSupplyType\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
