.TH "SourceGlobalTile.Row" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SourceGlobalTile.Row
.SH SYNOPSIS
.br
.PP
.PP
Inherits SourceData\&.BaseRow\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBid\fP"
.br
.ti -1c
.RI "string \fBalias\fP"
.br
.ti -1c
.RI "string \fBname_JP\fP"
.br
.ti -1c
.RI "string \fBname\fP"
.br
.ti -1c
.RI "int[] \fBtiles\fP"
.br
.ti -1c
.RI "int \fBfloor\fP"
.br
.ti -1c
.RI "string \fBzoneProfile\fP"
.br
.ti -1c
.RI "string[] \fBtag\fP"
.br
.ti -1c
.RI "int \fBdangerLv\fP"
.br
.ti -1c
.RI "string[] \fBtrait\fP"
.br
.ti -1c
.RI "string \fBidBiome\fP"
.br
.ti -1c
.RI "int[] \fBattribs\fP"
.br
.ti -1c
.RI "string \fBdetail_JP\fP"
.br
.ti -1c
.RI "string \fBdetail\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override bool \fBUseAlias\fP\fR [get]\fP"
.br
.ti -1c
.RI "override string \fBGetAlias\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB52\fP of file \fBSourceGlobalTile\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "string SourceGlobalTile\&.Row\&.alias"

.PP
Definition at line \fB78\fP of file \fBSourceGlobalTile\&.cs\fP\&.
.SS "int [] SourceGlobalTile\&.Row\&.attribs"

.PP
Definition at line \fB108\fP of file \fBSourceGlobalTile\&.cs\fP\&.
.SS "int SourceGlobalTile\&.Row\&.dangerLv"

.PP
Definition at line \fB99\fP of file \fBSourceGlobalTile\&.cs\fP\&.
.SS "string SourceGlobalTile\&.Row\&.detail"

.PP
Definition at line \fB114\fP of file \fBSourceGlobalTile\&.cs\fP\&.
.SS "string SourceGlobalTile\&.Row\&.detail_JP"

.PP
Definition at line \fB111\fP of file \fBSourceGlobalTile\&.cs\fP\&.
.SS "int SourceGlobalTile\&.Row\&.floor"

.PP
Definition at line \fB90\fP of file \fBSourceGlobalTile\&.cs\fP\&.
.SS "int SourceGlobalTile\&.Row\&.id"

.PP
Definition at line \fB75\fP of file \fBSourceGlobalTile\&.cs\fP\&.
.SS "string SourceGlobalTile\&.Row\&.idBiome"

.PP
Definition at line \fB105\fP of file \fBSourceGlobalTile\&.cs\fP\&.
.SS "string SourceGlobalTile\&.Row\&.name"

.PP
Definition at line \fB84\fP of file \fBSourceGlobalTile\&.cs\fP\&.
.SS "string SourceGlobalTile\&.Row\&.name_JP"

.PP
Definition at line \fB81\fP of file \fBSourceGlobalTile\&.cs\fP\&.
.SS "string [] SourceGlobalTile\&.Row\&.tag"

.PP
Definition at line \fB96\fP of file \fBSourceGlobalTile\&.cs\fP\&.
.SS "int [] SourceGlobalTile\&.Row\&.tiles"

.PP
Definition at line \fB87\fP of file \fBSourceGlobalTile\&.cs\fP\&.
.SS "string [] SourceGlobalTile\&.Row\&.trait"

.PP
Definition at line \fB102\fP of file \fBSourceGlobalTile\&.cs\fP\&.
.SS "string SourceGlobalTile\&.Row\&.zoneProfile"

.PP
Definition at line \fB93\fP of file \fBSourceGlobalTile\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "override string SourceGlobalTile\&.Row\&.GetAlias\fR [get]\fP"

.PP
Definition at line \fB66\fP of file \fBSourceGlobalTile\&.cs\fP\&.
.SS "override bool SourceGlobalTile\&.Row\&.UseAlias\fR [get]\fP"

.PP
Definition at line \fB56\fP of file \fBSourceGlobalTile\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
