.TH "SourceKeyItem.Row" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SourceKeyItem.Row
.SH SYNOPSIS
.br
.PP
.PP
Inherits SourceData\&.BaseRow\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBid\fP"
.br
.ti -1c
.RI "string \fBalias\fP"
.br
.ti -1c
.RI "string \fBname_JP\fP"
.br
.ti -1c
.RI "string \fBname\fP"
.br
.ti -1c
.RI "string \fBdetail_JP\fP"
.br
.ti -1c
.RI "string \fBdetail\fP"
.br
.ti -1c
.RI "string \fBname_L\fP"
.br
.ti -1c
.RI "string \fBdetail_L\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override bool \fBUseAlias\fP\fR [get]\fP"
.br
.ti -1c
.RI "override string \fBGetAlias\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB28\fP of file \fBSourceKeyItem\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "string SourceKeyItem\&.Row\&.alias"

.PP
Definition at line \fB54\fP of file \fBSourceKeyItem\&.cs\fP\&.
.SS "string SourceKeyItem\&.Row\&.detail"

.PP
Definition at line \fB66\fP of file \fBSourceKeyItem\&.cs\fP\&.
.SS "string SourceKeyItem\&.Row\&.detail_JP"

.PP
Definition at line \fB63\fP of file \fBSourceKeyItem\&.cs\fP\&.
.SS "string SourceKeyItem\&.Row\&.detail_L"

.PP
Definition at line \fB72\fP of file \fBSourceKeyItem\&.cs\fP\&.
.SS "int SourceKeyItem\&.Row\&.id"

.PP
Definition at line \fB51\fP of file \fBSourceKeyItem\&.cs\fP\&.
.SS "string SourceKeyItem\&.Row\&.name"

.PP
Definition at line \fB60\fP of file \fBSourceKeyItem\&.cs\fP\&.
.SS "string SourceKeyItem\&.Row\&.name_JP"

.PP
Definition at line \fB57\fP of file \fBSourceKeyItem\&.cs\fP\&.
.SS "string SourceKeyItem\&.Row\&.name_L"

.PP
Definition at line \fB69\fP of file \fBSourceKeyItem\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "override string SourceKeyItem\&.Row\&.GetAlias\fR [get]\fP"

.PP
Definition at line \fB42\fP of file \fBSourceKeyItem\&.cs\fP\&.
.SS "override bool SourceKeyItem\&.Row\&.UseAlias\fR [get]\fP"

.PP
Definition at line \fB32\fP of file \fBSourceKeyItem\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
