.TH "SourceBacker.Row" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SourceBacker.Row
.SH SYNOPSIS
.br
.PP
.PP
Inherits SourceData\&.BaseRow\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBid\fP"
.br
.ti -1c
.RI "bool \fBvalid\fP"
.br
.ti -1c
.RI "string \fBlang\fP"
.br
.ti -1c
.RI "string \fBname\fP"
.br
.ti -1c
.RI "string \fBtext\fP"
.br
.ti -1c
.RI "int \fBtype\fP"
.br
.ti -1c
.RI "int \fBskin\fP"
.br
.ti -1c
.RI "int \fBgender\fP"
.br
.ti -1c
.RI "string \fBtree\fP"
.br
.ti -1c
.RI "string \fBdeity\fP"
.br
.ti -1c
.RI "string \fBchara\fP"
.br
.ti -1c
.RI "string \fBloot\fP"
.br
.ti -1c
.RI "int \fBisStatic\fP"
.br
.ti -1c
.RI "bool \fBdone\fP"
.br
.ti -1c
.RI "string \fBloc\fP"
.br
.ti -1c
.RI "string \fBoriginal\fP"
.br
.ti -1c
.RI "string \fBname_L\fP"
.br
.ti -1c
.RI "string \fBtext_L\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override bool \fBUseAlias\fP\fR [get]\fP"
.br
.ti -1c
.RI "override string \fBGetAlias\fP\fR [get]\fP"
.br
.ti -1c
.RI "string \fBName\fP\fR [get]\fP"
.br
.ti -1c
.RI "string \fBText\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB109\fP of file \fBSourceBacker\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "string SourceBacker\&.Row\&.chara"

.PP
Definition at line \fB186\fP of file \fBSourceBacker\&.cs\fP\&.
.SS "string SourceBacker\&.Row\&.deity"

.PP
Definition at line \fB183\fP of file \fBSourceBacker\&.cs\fP\&.
.SS "bool SourceBacker\&.Row\&.done"

.PP
Definition at line \fB195\fP of file \fBSourceBacker\&.cs\fP\&.
.SS "int SourceBacker\&.Row\&.gender"

.PP
Definition at line \fB177\fP of file \fBSourceBacker\&.cs\fP\&.
.SS "int SourceBacker\&.Row\&.id"

.PP
Definition at line \fB156\fP of file \fBSourceBacker\&.cs\fP\&.
.SS "int SourceBacker\&.Row\&.isStatic"

.PP
Definition at line \fB192\fP of file \fBSourceBacker\&.cs\fP\&.
.SS "string SourceBacker\&.Row\&.lang"

.PP
Definition at line \fB162\fP of file \fBSourceBacker\&.cs\fP\&.
.SS "string SourceBacker\&.Row\&.loc"

.PP
Definition at line \fB198\fP of file \fBSourceBacker\&.cs\fP\&.
.SS "string SourceBacker\&.Row\&.loot"

.PP
Definition at line \fB189\fP of file \fBSourceBacker\&.cs\fP\&.
.SS "string SourceBacker\&.Row\&.name"

.PP
Definition at line \fB165\fP of file \fBSourceBacker\&.cs\fP\&.
.SS "string SourceBacker\&.Row\&.name_L"

.PP
Definition at line \fB204\fP of file \fBSourceBacker\&.cs\fP\&.
.SS "string SourceBacker\&.Row\&.original"

.PP
Definition at line \fB201\fP of file \fBSourceBacker\&.cs\fP\&.
.SS "int SourceBacker\&.Row\&.skin"

.PP
Definition at line \fB174\fP of file \fBSourceBacker\&.cs\fP\&.
.SS "string SourceBacker\&.Row\&.text"

.PP
Definition at line \fB168\fP of file \fBSourceBacker\&.cs\fP\&.
.SS "string SourceBacker\&.Row\&.text_L"

.PP
Definition at line \fB207\fP of file \fBSourceBacker\&.cs\fP\&.
.SS "string SourceBacker\&.Row\&.tree"

.PP
Definition at line \fB180\fP of file \fBSourceBacker\&.cs\fP\&.
.SS "int SourceBacker\&.Row\&.type"

.PP
Definition at line \fB171\fP of file \fBSourceBacker\&.cs\fP\&.
.SS "bool SourceBacker\&.Row\&.valid"

.PP
Definition at line \fB159\fP of file \fBSourceBacker\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "override string SourceBacker\&.Row\&.GetAlias\fR [get]\fP"

.PP
Definition at line \fB123\fP of file \fBSourceBacker\&.cs\fP\&.
.SS "string SourceBacker\&.Row\&.Name\fR [get]\fP"

.PP
Definition at line \fB133\fP of file \fBSourceBacker\&.cs\fP\&.
.SS "string SourceBacker\&.Row\&.Text\fR [get]\fP"

.PP
Definition at line \fB143\fP of file \fBSourceBacker\&.cs\fP\&.
.SS "override bool SourceBacker\&.Row\&.UseAlias\fR [get]\fP"

.PP
Definition at line \fB113\fP of file \fBSourceBacker\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
