.TH "SourceZone.Row" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SourceZone.Row
.SH SYNOPSIS
.br
.PP
.PP
Inherits SourceData\&.BaseRow\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBid\fP"
.br
.ti -1c
.RI "string \fBparent\fP"
.br
.ti -1c
.RI "string \fBname_JP\fP"
.br
.ti -1c
.RI "string \fBname\fP"
.br
.ti -1c
.RI "string \fBtype\fP"
.br
.ti -1c
.RI "int \fBLV\fP"
.br
.ti -1c
.RI "int \fBchance\fP"
.br
.ti -1c
.RI "string \fBfaction\fP"
.br
.ti -1c
.RI "int \fBvalue\fP"
.br
.ti -1c
.RI "string \fBidProfile\fP"
.br
.ti -1c
.RI "string[] \fBidFile\fP"
.br
.ti -1c
.RI "string \fBidBiome\fP"
.br
.ti -1c
.RI "string \fBidGen\fP"
.br
.ti -1c
.RI "string \fBidPlaylist\fP"
.br
.ti -1c
.RI "string[] \fBtag\fP"
.br
.ti -1c
.RI "int \fBcost\fP"
.br
.ti -1c
.RI "int \fBdev\fP"
.br
.ti -1c
.RI "string \fBimage\fP"
.br
.ti -1c
.RI "int[] \fBpos\fP"
.br
.ti -1c
.RI "string[] \fBquestTag\fP"
.br
.ti -1c
.RI "string \fBtextFlavor_JP\fP"
.br
.ti -1c
.RI "string \fBtextFlavor\fP"
.br
.ti -1c
.RI "string \fBdetail_JP\fP"
.br
.ti -1c
.RI "string \fBdetail\fP"
.br
.ti -1c
.RI "string \fBname_L\fP"
.br
.ti -1c
.RI "string \fBdetail_L\fP"
.br
.ti -1c
.RI "string \fBtextFlavor_L\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override bool \fBUseAlias\fP\fR [get]\fP"
.br
.ti -1c
.RI "override string \fBGetAlias\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB59\fP of file \fBSourceZone\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int SourceZone\&.Row\&.chance"

.PP
Definition at line \fB100\fP of file \fBSourceZone\&.cs\fP\&.
.SS "int SourceZone\&.Row\&.cost"

.PP
Definition at line \fB127\fP of file \fBSourceZone\&.cs\fP\&.
.SS "string SourceZone\&.Row\&.detail"

.PP
Definition at line \fB151\fP of file \fBSourceZone\&.cs\fP\&.
.SS "string SourceZone\&.Row\&.detail_JP"

.PP
Definition at line \fB148\fP of file \fBSourceZone\&.cs\fP\&.
.SS "string SourceZone\&.Row\&.detail_L"

.PP
Definition at line \fB157\fP of file \fBSourceZone\&.cs\fP\&.
.SS "int SourceZone\&.Row\&.dev"

.PP
Definition at line \fB130\fP of file \fBSourceZone\&.cs\fP\&.
.SS "string SourceZone\&.Row\&.faction"

.PP
Definition at line \fB103\fP of file \fBSourceZone\&.cs\fP\&.
.SS "string SourceZone\&.Row\&.id"

.PP
Definition at line \fB82\fP of file \fBSourceZone\&.cs\fP\&.
.SS "string SourceZone\&.Row\&.idBiome"

.PP
Definition at line \fB115\fP of file \fBSourceZone\&.cs\fP\&.
.SS "string [] SourceZone\&.Row\&.idFile"

.PP
Definition at line \fB112\fP of file \fBSourceZone\&.cs\fP\&.
.SS "string SourceZone\&.Row\&.idGen"

.PP
Definition at line \fB118\fP of file \fBSourceZone\&.cs\fP\&.
.SS "string SourceZone\&.Row\&.idPlaylist"

.PP
Definition at line \fB121\fP of file \fBSourceZone\&.cs\fP\&.
.SS "string SourceZone\&.Row\&.idProfile"

.PP
Definition at line \fB109\fP of file \fBSourceZone\&.cs\fP\&.
.SS "string SourceZone\&.Row\&.image"

.PP
Definition at line \fB133\fP of file \fBSourceZone\&.cs\fP\&.
.SS "int SourceZone\&.Row\&.LV"

.PP
Definition at line \fB97\fP of file \fBSourceZone\&.cs\fP\&.
.SS "string SourceZone\&.Row\&.name"

.PP
Definition at line \fB91\fP of file \fBSourceZone\&.cs\fP\&.
.SS "string SourceZone\&.Row\&.name_JP"

.PP
Definition at line \fB88\fP of file \fBSourceZone\&.cs\fP\&.
.SS "string SourceZone\&.Row\&.name_L"

.PP
Definition at line \fB154\fP of file \fBSourceZone\&.cs\fP\&.
.SS "string SourceZone\&.Row\&.parent"

.PP
Definition at line \fB85\fP of file \fBSourceZone\&.cs\fP\&.
.SS "int [] SourceZone\&.Row\&.pos"

.PP
Definition at line \fB136\fP of file \fBSourceZone\&.cs\fP\&.
.SS "string [] SourceZone\&.Row\&.questTag"

.PP
Definition at line \fB139\fP of file \fBSourceZone\&.cs\fP\&.
.SS "string [] SourceZone\&.Row\&.tag"

.PP
Definition at line \fB124\fP of file \fBSourceZone\&.cs\fP\&.
.SS "string SourceZone\&.Row\&.textFlavor"

.PP
Definition at line \fB145\fP of file \fBSourceZone\&.cs\fP\&.
.SS "string SourceZone\&.Row\&.textFlavor_JP"

.PP
Definition at line \fB142\fP of file \fBSourceZone\&.cs\fP\&.
.SS "string SourceZone\&.Row\&.textFlavor_L"

.PP
Definition at line \fB160\fP of file \fBSourceZone\&.cs\fP\&.
.SS "string SourceZone\&.Row\&.type"

.PP
Definition at line \fB94\fP of file \fBSourceZone\&.cs\fP\&.
.SS "int SourceZone\&.Row\&.value"

.PP
Definition at line \fB106\fP of file \fBSourceZone\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "override string SourceZone\&.Row\&.GetAlias\fR [get]\fP"

.PP
Definition at line \fB73\fP of file \fBSourceZone\&.cs\fP\&.
.SS "override bool SourceZone\&.Row\&.UseAlias\fR [get]\fP"

.PP
Definition at line \fB63\fP of file \fBSourceZone\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
