.TH "SourceFaction.Row" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SourceFaction.Row
.SH SYNOPSIS
.br
.PP
.PP
Inherits SourceData\&.BaseRow\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBid\fP"
.br
.ti -1c
.RI "string \fBname_JP\fP"
.br
.ti -1c
.RI "string \fBname\fP"
.br
.ti -1c
.RI "string \fBtype\fP"
.br
.ti -1c
.RI "string \fBfaith\fP"
.br
.ti -1c
.RI "string \fBdomain\fP"
.br
.ti -1c
.RI "int \fBrelation\fP"
.br
.ti -1c
.RI "string \fBtextType_JP\fP"
.br
.ti -1c
.RI "string \fBtextType\fP"
.br
.ti -1c
.RI "string \fBtextAvatar\fP"
.br
.ti -1c
.RI "string \fBdetail_JP\fP"
.br
.ti -1c
.RI "string \fBdetail\fP"
.br
.ti -1c
.RI "string \fBname_L\fP"
.br
.ti -1c
.RI "string \fBdetail_L\fP"
.br
.ti -1c
.RI "string \fBtextType_L\fP"
.br
.ti -1c
.RI "string \fBtextBenefit_L\fP"
.br
.ti -1c
.RI "string \fBtextPet_L\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override bool \fBUseAlias\fP\fR [get]\fP"
.br
.ti -1c
.RI "override string \fBGetAlias\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB49\fP of file \fBSourceFaction\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "string SourceFaction\&.Row\&.detail"

.PP
Definition at line \fB105\fP of file \fBSourceFaction\&.cs\fP\&.
.SS "string SourceFaction\&.Row\&.detail_JP"

.PP
Definition at line \fB102\fP of file \fBSourceFaction\&.cs\fP\&.
.SS "string SourceFaction\&.Row\&.detail_L"

.PP
Definition at line \fB111\fP of file \fBSourceFaction\&.cs\fP\&.
.SS "string SourceFaction\&.Row\&.domain"

.PP
Definition at line \fB87\fP of file \fBSourceFaction\&.cs\fP\&.
.SS "string SourceFaction\&.Row\&.faith"

.PP
Definition at line \fB84\fP of file \fBSourceFaction\&.cs\fP\&.
.SS "string SourceFaction\&.Row\&.id"

.PP
Definition at line \fB72\fP of file \fBSourceFaction\&.cs\fP\&.
.SS "string SourceFaction\&.Row\&.name"

.PP
Definition at line \fB78\fP of file \fBSourceFaction\&.cs\fP\&.
.SS "string SourceFaction\&.Row\&.name_JP"

.PP
Definition at line \fB75\fP of file \fBSourceFaction\&.cs\fP\&.
.SS "string SourceFaction\&.Row\&.name_L"

.PP
Definition at line \fB108\fP of file \fBSourceFaction\&.cs\fP\&.
.SS "int SourceFaction\&.Row\&.relation"

.PP
Definition at line \fB90\fP of file \fBSourceFaction\&.cs\fP\&.
.SS "string SourceFaction\&.Row\&.textAvatar"

.PP
Definition at line \fB99\fP of file \fBSourceFaction\&.cs\fP\&.
.SS "string SourceFaction\&.Row\&.textBenefit_L"

.PP
Definition at line \fB117\fP of file \fBSourceFaction\&.cs\fP\&.
.SS "string SourceFaction\&.Row\&.textPet_L"

.PP
Definition at line \fB120\fP of file \fBSourceFaction\&.cs\fP\&.
.SS "string SourceFaction\&.Row\&.textType"

.PP
Definition at line \fB96\fP of file \fBSourceFaction\&.cs\fP\&.
.SS "string SourceFaction\&.Row\&.textType_JP"

.PP
Definition at line \fB93\fP of file \fBSourceFaction\&.cs\fP\&.
.SS "string SourceFaction\&.Row\&.textType_L"

.PP
Definition at line \fB114\fP of file \fBSourceFaction\&.cs\fP\&.
.SS "string SourceFaction\&.Row\&.type"

.PP
Definition at line \fB81\fP of file \fBSourceFaction\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "override string SourceFaction\&.Row\&.GetAlias\fR [get]\fP"

.PP
Definition at line \fB63\fP of file \fBSourceFaction\&.cs\fP\&.
.SS "override bool SourceFaction\&.Row\&.UseAlias\fR [get]\fP"

.PP
Definition at line \fB53\fP of file \fBSourceFaction\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
