.TH "SourceFood" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SourceFood
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSourceThingV\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRow2\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override \fBSourceThingV\&.Row\fP \fBCreateRow\fP ()"
.br
.ti -1c
.RI "override void \fBSetRow\fP (\fBSourceThingV\&.Row\fP r)"
.br
.ti -1c
.RI "override void \fBOnImportRow\fP (\fBSourceThingV\&.Row\fP _r, \fBSourceThing\&.Row\fP c)"
.br
.in -1c

Public Member Functions inherited from \fBSourceThingV\fP
.in +1c
.ti -1c
.RI "override \fBSourceThingV\&.Row\fP \fBCreateRow\fP ()"
.br
.ti -1c
.RI "override void \fBSetRow\fP (\fBSourceThingV\&.Row\fP r)"
.br
.ti -1c
.RI "override void \fBRestorePref\fP ()"
.br
.ti -1c
.RI "override void \fBValidatePref\fP ()"
.br
.ti -1c
.RI "override void \fBOnAfterImportData\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"


Properties inherited from \fBSourceThingV\fP
.in +1c
.ti -1c
.RI "override string[] \fBImportFields\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB6\fP of file \fBSourceFood\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override \fBSourceThingV\&.Row\fP SourceFood\&.CreateRow ()"

.PP
Definition at line \fB9\fP of file \fBSourceFood\&.cs\fP\&.
.SS "override void SourceFood\&.OnImportRow (\fBSourceThingV\&.Row\fP _r, \fBSourceThing\&.Row\fP c)\fR [virtual]\fP"

.PP
Reimplemented from \fBSourceThingV\fP\&.
.PP
Definition at line \fB67\fP of file \fBSourceFood\&.cs\fP\&.
.SS "override void SourceFood\&.SetRow (\fBSourceThingV\&.Row\fP r)"

.PP
Definition at line \fB61\fP of file \fBSourceFood\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
