.TH "SourceAsset.PrefData" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SourceAsset.PrefData
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Dictionary< string, \fBSourcePref\fP > \fBdict\fP = new Dictionary<string, \fBSourcePref\fP>()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB83\fP of file \fBSourceAsset\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "Dictionary<string, \fBSourcePref\fP> SourceAsset\&.PrefData\&.dict = new Dictionary<string, \fBSourcePref\fP>()"

.PP
Definition at line \fB86\fP of file \fBSourceAsset\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
