.TH "SourceThing" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SourceThing
.SH SYNOPSIS
.br
.PP
.PP
Inherits SourceDataString< SourceThing\&.Row >\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRow\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override \fBSourceThing\&.Row\fP \fBCreateRow\fP ()"
.br
.ti -1c
.RI "override void \fBSetRow\fP (\fBSourceThing\&.Row\fP r)"
.br
.ti -1c
.RI "override void \fBBackupPref\fP ()"
.br
.ti -1c
.RI "override void \fBRestorePref\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Dictionary< string, \fBSourceThing\&.Row\fP > \fB_rows\fP = new Dictionary<string, \fBSourceThing\&.Row\fP>()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override string[] \fBImportFields\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB5\fP of file \fBSourceThing\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void SourceThing\&.BackupPref ()"

.PP
Definition at line \fB73\fP of file \fBSourceThing\&.cs\fP\&.
.SS "override \fBSourceThing\&.Row\fP SourceThing\&.CreateRow ()"

.PP
Definition at line \fB8\fP of file \fBSourceThing\&.cs\fP\&.
.SS "override void SourceThing\&.RestorePref ()"

.PP
Definition at line \fB83\fP of file \fBSourceThing\&.cs\fP\&.
.SS "override void SourceThing\&.SetRow (\fBSourceThing\&.Row\fP r)"

.PP
Definition at line \fB67\fP of file \fBSourceThing\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "Dictionary<string, \fBSourceThing\&.Row\fP> SourceThing\&._rows = new Dictionary<string, \fBSourceThing\&.Row\fP>()"

.PP
Definition at line \fB104\fP of file \fBSourceThing\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "override string [] SourceThing\&.ImportFields\fR [get]\fP"

.PP
Definition at line \fB89\fP of file \fBSourceThing\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
