.TH "SpatialManager.GlobalSpatialList" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SpatialManager.GlobalSpatialList
.SH SYNOPSIS
.br
.PP
.PP
Inherits Dictionary< int, Spatial >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBAdd\fP (\fBSpatial\fP s)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB109\fP of file \fBSpatialManager\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void SpatialManager\&.GlobalSpatialList\&.Add (\fBSpatial\fP s)"

.PP
Definition at line \fB112\fP of file \fBSpatialManager\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
