.TH "SpawnList" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SpawnList
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBEClass\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSpawnList\fP (string id=null)"
.br
.ti -1c
.RI "void \fBAdd\fP (\fBCardRow\fP row)"
.br
.ti -1c
.RI "void \fBCreateMaster\fP (\fBCardFilter\fP _filter, string parent=null)"
.br
.ti -1c
.RI "\fBSpawnList\fP \fBFilter\fP (int lv, int levelRange=\-1)"
.br
.ti -1c
.RI "\fBCardRow\fP \fBSelect\fP (int lv=\-1, int levelRange=\-1)"
.br
.ti -1c
.RI "\fBCardRow\fP \fBGetRandom\fP ()"
.br
.ti -1c
.RI "\fBCardRow\fP \fBGetFirst\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBSpawnList\fP \fBGet\fP (string id, string parent=null, \fBCardFilter\fP filter=null)"
.br
.in -1c

Static Public Member Functions inherited from \fBEClass\fP
.in +1c
.ti -1c
.RI "static int \fBrnd\fP (int a)"
.br
.ti -1c
.RI "static int \fBcurve\fP (int a, int start, int step, int rate=75)"
.br
.ti -1c
.RI "static int \fBrndHalf\fP (int a)"
.br
.ti -1c
.RI "static float \fBrndf\fP (float a)"
.br
.ti -1c
.RI "static int \fBrndSqrt\fP (int a)"
.br
.ti -1c
.RI "static void \fBWait\fP (float a, \fBCard\fP c)"
.br
.ti -1c
.RI "static void \fBWait\fP (float a, \fBPoint\fP p)"
.br
.ti -1c
.RI "static int \fBBigger\fP (int a, int b)"
.br
.ti -1c
.RI "static int \fBSmaller\fP (int a, int b)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBid\fP"
.br
.ti -1c
.RI "List< \fBCardRow\fP > \fBrows\fP = new List<\fBCardRow\fP>()"
.br
.ti -1c
.RI "\fBCardFilter\fP \fBfilter\fP"
.br
.ti -1c
.RI "int \fBtotalChance\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static Dictionary< string, \fBSpawnList\fP > \fBallList\fP = new Dictionary<string, \fBSpawnList\fP>()"
.br
.ti -1c
.RI "static \fBSpawnList\fP \fBtempList\fP = new \fBSpawnList\fP(null)"
.br
.in -1c

Static Public Attributes inherited from \fBEClass\fP
.in +1c
.ti -1c
.RI "static \fBCore\fP \fBcore\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Properties inherited from \fBEClass\fP
.in +1c
.ti -1c
.RI "static \fBGame\fP \fBgame\fP\fR [get]\fP"
.br
.ti -1c
.RI "static bool \fBAdvMode\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBPlayer\fP \fBplayer\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBChara\fP \fBpc\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBUI\fP \fBui\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBMap\fP \fB_map\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBZone\fP \fB_zone\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranchOrHomeBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFaction\fP \fBHome\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFaction\fP \fBWilds\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBScene\fP \fBscene\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBBaseGameScreen\fP \fBscreen\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameSetting\fP \fBsetting\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameData\fP \fBgamedata\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBColorProfile\fP \fBColors\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBWorld\fP \fBworld\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBsources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBeditorSources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static SoundManager \fBSound\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBCoreDebug\fP \fBdebug\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB7\fP of file \fBSpawnList\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SpawnList\&.SpawnList (string id = \fRnull\fP)"

.PP
Definition at line \fB31\fP of file \fBSpawnList\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void SpawnList\&.Add (\fBCardRow\fP row)"

.PP
Definition at line \fB52\fP of file \fBSpawnList\&.cs\fP\&.
.SS "void SpawnList\&.CreateMaster (\fBCardFilter\fP _filter, string parent = \fRnull\fP)"

.PP
Definition at line \fB59\fP of file \fBSpawnList\&.cs\fP\&.
.SS "\fBSpawnList\fP SpawnList\&.Filter (int lv, int levelRange = \fR\-1\fP)"

.PP
Definition at line \fB84\fP of file \fBSpawnList\&.cs\fP\&.
.SS "static \fBSpawnList\fP SpawnList\&.Get (string id, string parent = \fRnull\fP, \fBCardFilter\fP filter = \fRnull\fP)\fR [static]\fP"

.PP
Definition at line \fB10\fP of file \fBSpawnList\&.cs\fP\&.
.SS "\fBCardRow\fP SpawnList\&.GetFirst ()"

.PP
Definition at line \fB161\fP of file \fBSpawnList\&.cs\fP\&.
.SS "\fBCardRow\fP SpawnList\&.GetRandom ()"

.PP
Definition at line \fB155\fP of file \fBSpawnList\&.cs\fP\&.
.SS "\fBCardRow\fP SpawnList\&.Select (int lv = \fR\-1\fP, int levelRange = \fR\-1\fP)"

.PP
Definition at line \fB121\fP of file \fBSpawnList\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "Dictionary<string, \fBSpawnList\fP> SpawnList\&.allList = new Dictionary<string, \fBSpawnList\fP>()\fR [static]\fP"

.PP
Definition at line \fB193\fP of file \fBSpawnList\&.cs\fP\&.
.SS "\fBCardFilter\fP SpawnList\&.filter"

.PP
Definition at line \fB205\fP of file \fBSpawnList\&.cs\fP\&.
.SS "string SpawnList\&.id"

.PP
Definition at line \fB199\fP of file \fBSpawnList\&.cs\fP\&.
.SS "List<\fBCardRow\fP> SpawnList\&.rows = new List<\fBCardRow\fP>()"

.PP
Definition at line \fB202\fP of file \fBSpawnList\&.cs\fP\&.
.SS "\fBSpawnList\fP SpawnList\&.tempList = new \fBSpawnList\fP(null)\fR [static]\fP"

.PP
Definition at line \fB196\fP of file \fBSpawnList\&.cs\fP\&.
.SS "int SpawnList\&.totalChance"

.PP
Definition at line \fB208\fP of file \fBSpawnList\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
