.TH "SpriteBasedLaser" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SpriteBasedLaser
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBPlay\fP (Vector3 to)"
.br
.ti -1c
.RI "delegate void \fBLaserHitTriggerHandler\fP (RaycastHit2D hitInfo)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Material \fBmat\fP"
.br
.ti -1c
.RI "Vector3 \fBdest\fP"
.br
.ti -1c
.RI "Vector3 \fBfixTip\fP"
.br
.ti -1c
.RI "Vector3 \fBdest2\fP"
.br
.ti -1c
.RI "Vector3 \fBfix\fP"
.br
.ti -1c
.RI "Vector3 \fBfix2\fP"
.br
.ti -1c
.RI "float \fBarcNum\fP"
.br
.ti -1c
.RI "float \fBarcNum2\fP"
.br
.ti -1c
.RI "DOTweenAnimation[] \fBanime\fP"
.br
.ti -1c
.RI "LineRenderer \fBlaserLineRendererArc\fP"
.br
.ti -1c
.RI "int \fBlaserArcSegments\fP = 20"
.br
.ti -1c
.RI "\fBRandomPositionMover\fP \fBlaserOscillationPositionerScript\fP"
.br
.ti -1c
.RI "bool \fBoscillateLaser\fP"
.br
.ti -1c
.RI "float \fBmaxLaserLength\fP = 20f"
.br
.ti -1c
.RI "float \fBoscillationSpeed\fP = 1f"
.br
.ti -1c
.RI "GameObject \fBtargetGo\fP"
.br
.ti -1c
.RI "ParticleSystem \fBhitSparkParticleSystem\fP"
.br
.ti -1c
.RI "float \fBlaserArcMax\fP"
.br
.ti -1c
.RI "float \fBmaxLaserRaycastDistance\fP"
.br
.ti -1c
.RI "bool \fBlaserRotationEnabled\fP"
.br
.ti -1c
.RI "bool \fBlerpLaserRotation\fP"
.br
.ti -1c
.RI "float \fBturningRate\fP = 3f"
.br
.ti -1c
.RI "float \fBcollisionTriggerInterval\fP = 0\&.25f"
.br
.ti -1c
.RI "LayerMask \fBmask\fP"
.br
.ti -1c
.RI "bool \fBuseArc\fP"
.br
.ti -1c
.RI "float \fBoscillationThreshold\fP = 0\&.2f"
.br
.ti -1c
.RI "Transform \fBtrail\fP"
.br
.ti -1c
.RI "GameObject \fBstartGoPiece\fP"
.br
.ti -1c
.RI "GameObject \fBmiddleGoPiece\fP"
.br
.ti -1c
.RI "GameObject \fBendGoPiece\fP"
.br
.in -1c
.SS "Events"

.in +1c
.ti -1c
.RI "SpriteBasedLaser\&.LaserHitTriggerHandler \fBOnLaserHitTriggered\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB6\fP of file \fBSpriteBasedLaser\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void SpriteBasedLaser\&.Play (Vector3 to)"

.PP
Definition at line \fB14\fP of file \fBSpriteBasedLaser\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "DOTweenAnimation [] SpriteBasedLaser\&.anime"

.PP
Definition at line \fB179\fP of file \fBSpriteBasedLaser\&.cs\fP\&.
.SS "float SpriteBasedLaser\&.arcNum"

.PP
Definition at line \fB173\fP of file \fBSpriteBasedLaser\&.cs\fP\&.
.SS "float SpriteBasedLaser\&.arcNum2"

.PP
Definition at line \fB176\fP of file \fBSpriteBasedLaser\&.cs\fP\&.
.SS "float SpriteBasedLaser\&.collisionTriggerInterval = 0\&.25f"

.PP
Definition at line \fB221\fP of file \fBSpriteBasedLaser\&.cs\fP\&.
.SS "Vector3 SpriteBasedLaser\&.dest"

.PP
Definition at line \fB158\fP of file \fBSpriteBasedLaser\&.cs\fP\&.
.SS "Vector3 SpriteBasedLaser\&.dest2"

.PP
Definition at line \fB164\fP of file \fBSpriteBasedLaser\&.cs\fP\&.
.SS "GameObject SpriteBasedLaser\&.endGoPiece"

.PP
Definition at line \fB254\fP of file \fBSpriteBasedLaser\&.cs\fP\&.
.SS "Vector3 SpriteBasedLaser\&.fix"

.PP
Definition at line \fB167\fP of file \fBSpriteBasedLaser\&.cs\fP\&.
.SS "Vector3 SpriteBasedLaser\&.fix2"

.PP
Definition at line \fB170\fP of file \fBSpriteBasedLaser\&.cs\fP\&.
.SS "Vector3 SpriteBasedLaser\&.fixTip"

.PP
Definition at line \fB161\fP of file \fBSpriteBasedLaser\&.cs\fP\&.
.SS "ParticleSystem SpriteBasedLaser\&.hitSparkParticleSystem"

.PP
Definition at line \fB203\fP of file \fBSpriteBasedLaser\&.cs\fP\&.
.SS "float SpriteBasedLaser\&.laserArcMax"

.PP
Definition at line \fB206\fP of file \fBSpriteBasedLaser\&.cs\fP\&.
.SS "int SpriteBasedLaser\&.laserArcSegments = 20"

.PP
Definition at line \fB185\fP of file \fBSpriteBasedLaser\&.cs\fP\&.
.SS "LineRenderer SpriteBasedLaser\&.laserLineRendererArc"

.PP
Definition at line \fB182\fP of file \fBSpriteBasedLaser\&.cs\fP\&.
.SS "\fBRandomPositionMover\fP SpriteBasedLaser\&.laserOscillationPositionerScript"

.PP
Definition at line \fB188\fP of file \fBSpriteBasedLaser\&.cs\fP\&.
.SS "bool SpriteBasedLaser\&.laserRotationEnabled"

.PP
Definition at line \fB212\fP of file \fBSpriteBasedLaser\&.cs\fP\&.
.SS "bool SpriteBasedLaser\&.lerpLaserRotation"

.PP
Definition at line \fB215\fP of file \fBSpriteBasedLaser\&.cs\fP\&.
.SS "LayerMask SpriteBasedLaser\&.mask"

.PP
Definition at line \fB224\fP of file \fBSpriteBasedLaser\&.cs\fP\&.
.SS "Material SpriteBasedLaser\&.mat"

.PP
Definition at line \fB155\fP of file \fBSpriteBasedLaser\&.cs\fP\&.
.SS "float SpriteBasedLaser\&.maxLaserLength = 20f"

.PP
Definition at line \fB194\fP of file \fBSpriteBasedLaser\&.cs\fP\&.
.SS "float SpriteBasedLaser\&.maxLaserRaycastDistance"

.PP
Definition at line \fB209\fP of file \fBSpriteBasedLaser\&.cs\fP\&.
.SS "GameObject SpriteBasedLaser\&.middleGoPiece"

.PP
Definition at line \fB251\fP of file \fBSpriteBasedLaser\&.cs\fP\&.
.SS "bool SpriteBasedLaser\&.oscillateLaser"

.PP
Definition at line \fB191\fP of file \fBSpriteBasedLaser\&.cs\fP\&.
.SS "float SpriteBasedLaser\&.oscillationSpeed = 1f"

.PP
Definition at line \fB197\fP of file \fBSpriteBasedLaser\&.cs\fP\&.
.SS "float SpriteBasedLaser\&.oscillationThreshold = 0\&.2f"

.PP
Definition at line \fB230\fP of file \fBSpriteBasedLaser\&.cs\fP\&.
.SS "GameObject SpriteBasedLaser\&.startGoPiece"

.PP
Definition at line \fB248\fP of file \fBSpriteBasedLaser\&.cs\fP\&.
.SS "GameObject SpriteBasedLaser\&.targetGo"

.PP
Definition at line \fB200\fP of file \fBSpriteBasedLaser\&.cs\fP\&.
.SS "Transform SpriteBasedLaser\&.trail"

.PP
Definition at line \fB245\fP of file \fBSpriteBasedLaser\&.cs\fP\&.
.SS "float SpriteBasedLaser\&.turningRate = 3f"

.PP
Definition at line \fB218\fP of file \fBSpriteBasedLaser\&.cs\fP\&.
.SS "bool SpriteBasedLaser\&.useArc"

.PP
Definition at line \fB227\fP of file \fBSpriteBasedLaser\&.cs\fP\&.
.SH "Event Documentation"
.PP 
.SS "SpriteBasedLaser\&.LaserHitTriggerHandler SpriteBasedLaser\&.OnLaserHitTriggered"

.PP
Definition at line \fB11\fP of file \fBSpriteBasedLaser\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
