.TH "Steam" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Steam
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBInit\fP ()"
.br
.ti -1c
.RI "void \fBCheckUpdate\fP ()"
.br
.ti -1c
.RI "void \fBCheckDLC\fP ()"
.br
.ti -1c
.RI "void \fBTestHasDLC\fP ()"
.br
.ti -1c
.RI "void \fBCreateUserContent\fP (BaseModPackage p)"
.br
.ti -1c
.RI "void \fBUpdateUserContent\fP (PublishedFileId_t fileId)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBHasDLC\fP (ID_DLC id)"
.br
.ti -1c
.RI "static void \fBGetAchievement\fP (ID_Achievement id)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "SteamworksBehaviour \fBsteamworks\fP"
.br
.ti -1c
.RI "UserGeneratedContentQueryManager \fBugc\fP"
.br
.ti -1c
.RI "WorkshopItem \fBtestData\fP"
.br
.ti -1c
.RI "BaseModPackage \fBcurrentPackage\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static \fBSteam\fP \fBInstance\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB10\fP of file \fBSteam\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Steam\&.CheckDLC ()"

.PP
Definition at line \fB31\fP of file \fBSteam\&.cs\fP\&.
.SS "void Steam\&.CheckUpdate ()"

.PP
Definition at line \fB26\fP of file \fBSteam\&.cs\fP\&.
.SS "void Steam\&.CreateUserContent (BaseModPackage p)"

.PP
Definition at line \fB73\fP of file \fBSteam\&.cs\fP\&.
.SS "static void Steam\&.GetAchievement (ID_Achievement id)\fR [static]\fP"

.PP
Definition at line \fB46\fP of file \fBSteam\&.cs\fP\&.
.SS "static bool Steam\&.HasDLC (ID_DLC id)\fR [static]\fP"

.PP
Definition at line \fB37\fP of file \fBSteam\&.cs\fP\&.
.SS "void Steam\&.Init ()"

.PP
Definition at line \fB19\fP of file \fBSteam\&.cs\fP\&.
.SS "void Steam\&.TestHasDLC ()"

.PP
Definition at line \fB66\fP of file \fBSteam\&.cs\fP\&.
.SS "void Steam\&.UpdateUserContent (PublishedFileId_t fileId)"

.PP
Definition at line \fB149\fP of file \fBSteam\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "BaseModPackage Steam\&.currentPackage"

.PP
Definition at line \fB191\fP of file \fBSteam\&.cs\fP\&.
.SS "\fBSteam\fP Steam\&.Instance\fR [static]\fP"

.PP
Definition at line \fB179\fP of file \fBSteam\&.cs\fP\&.
.SS "SteamworksBehaviour Steam\&.steamworks"

.PP
Definition at line \fB182\fP of file \fBSteam\&.cs\fP\&.
.SS "WorkshopItem Steam\&.testData"

.PP
Definition at line \fB188\fP of file \fBSteam\&.cs\fP\&.
.SS "UserGeneratedContentQueryManager Steam\&.ugc"

.PP
Definition at line \fB185\fP of file \fBSteam\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
