.TH "SubPassData" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SubPassData
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Vector3 \fBoffset\fP"
.br
.ti -1c
.RI "Vector3 \fBscale\fP = Vector3\&.one"
.br
.ti -1c
.RI "Quaternion \fBrotation\fP = Quaternion\&.identity"
.br
.ti -1c
.RI "bool \fBenable\fP"
.br
.ti -1c
.RI "bool \fBshadow\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static \fBSubPassData\fP \fBDefault\fP"
.br
.ti -1c
.RI "static \fBSubPassData\fP \fBCurrent\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB6\fP of file \fBSubPassData\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBSubPassData\fP SubPassData\&.Current\fR [static]\fP"

.PP
Definition at line \fB12\fP of file \fBSubPassData\&.cs\fP\&.
.SS "\fBSubPassData\fP SubPassData\&.Default\fR [static]\fP"

.PP
Definition at line \fB9\fP of file \fBSubPassData\&.cs\fP\&.
.SS "bool SubPassData\&.enable"

.PP
Definition at line \fB24\fP of file \fBSubPassData\&.cs\fP\&.
.SS "Vector3 SubPassData\&.offset"

.PP
Definition at line \fB15\fP of file \fBSubPassData\&.cs\fP\&.
.SS "Quaternion SubPassData\&.rotation = Quaternion\&.identity"

.PP
Definition at line \fB21\fP of file \fBSubPassData\&.cs\fP\&.
.SS "Vector3 SubPassData\&.scale = Vector3\&.one"

.PP
Definition at line \fB18\fP of file \fBSubPassData\&.cs\fP\&.
.SS "bool SubPassData\&.shadow"

.PP
Definition at line \fB27\fP of file \fBSubPassData\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
