.TH "TextureReplace" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TextureReplace
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBSource\fP { \fBUser\fP, \fBMod\fP, \fBLocal\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBTryRefresh\fP (bool force)"
.br
.ti -1c
.RI "void \fBLoad\fP (bool dateMatched)"
.br
.ti -1c
.RI "void \fBDestoryTex\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "DateTime \fBdate\fP"
.br
.ti -1c
.RI "Texture2D \fBtex\fP"
.br
.ti -1c
.RI "FileInfo \fBfile\fP"
.br
.ti -1c
.RI "\fBTextureData\fP \fBdata\fP"
.br
.ti -1c
.RI "int \fBindex\fP"
.br
.ti -1c
.RI "int \fBw\fP"
.br
.ti -1c
.RI "int \fBh\fP"
.br
.ti -1c
.RI "TextureReplace\&.Source \fBsource\fP"
.br
.ti -1c
.RI "\fBTextureReplace\fP \fBoriginal\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "bool \fBuser\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB6\fP of file \fBTextureReplace\&.cs\fP\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "enum TextureReplace\&.Source"

.PP
Definition at line \fB83\fP of file \fBTextureReplace\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void TextureReplace\&.DestoryTex ()"

.PP
Definition at line \fB50\fP of file \fBTextureReplace\&.cs\fP\&.
.SS "void TextureReplace\&.Load (bool dateMatched)"

.PP
Definition at line \fB35\fP of file \fBTextureReplace\&.cs\fP\&.
.SS "void TextureReplace\&.TryRefresh (bool force)"

.PP
Definition at line \fB19\fP of file \fBTextureReplace\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBTextureData\fP TextureReplace\&.data"

.PP
Definition at line \fB65\fP of file \fBTextureReplace\&.cs\fP\&.
.SS "DateTime TextureReplace\&.date"

.PP
Definition at line \fB56\fP of file \fBTextureReplace\&.cs\fP\&.
.SS "FileInfo TextureReplace\&.file"

.PP
Definition at line \fB62\fP of file \fBTextureReplace\&.cs\fP\&.
.SS "int TextureReplace\&.h"

.PP
Definition at line \fB74\fP of file \fBTextureReplace\&.cs\fP\&.
.SS "int TextureReplace\&.index"

.PP
Definition at line \fB68\fP of file \fBTextureReplace\&.cs\fP\&.
.SS "\fBTextureReplace\fP TextureReplace\&.original"

.PP
Definition at line \fB80\fP of file \fBTextureReplace\&.cs\fP\&.
.SS "TextureReplace\&.Source TextureReplace\&.source"

.PP
Definition at line \fB77\fP of file \fBTextureReplace\&.cs\fP\&.
.SS "Texture2D TextureReplace\&.tex"

.PP
Definition at line \fB59\fP of file \fBTextureReplace\&.cs\fP\&.
.SS "int TextureReplace\&.w"

.PP
Definition at line \fB71\fP of file \fBTextureReplace\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "bool TextureReplace\&.user\fR [get]\fP"

.PP
Definition at line \fB10\fP of file \fBTextureReplace\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
