.TH "TextureManager" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TextureManager
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBInit\fP ()"
.br
.ti -1c
.RI "void \fBAddBase\fP (\fBTextureData\fP data, string path, \fBMeshPass\fP pass, string texName='_MainTex')"
.br
.ti -1c
.RI "void \fBAdd\fP (\fBMeshPass\fP to, \fBTextureData\fP from, string texName='_MainTex')"
.br
.ti -1c
.RI "void \fBAddList\fP (\fBTextureData\fP data, string path)"
.br
.ti -1c
.RI "void \fBRefreshTextures\fP ()"
.br
.ti -1c
.RI "void \fBOnDropFile\fP (List< string > paths)"
.br
.ti -1c
.RI "bool \fBTryAddReplace\fP (FileInfo file, TextureReplace\&.Source source=TextureReplace\&.Source\&.Mod, bool add=true, bool refresh=false)"
.br
.ti -1c
.RI "void \fBApplyLocalReplace\fP (string path)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Dictionary< string, \fBTextureData\fP > \fBtexMap\fP = new Dictionary<string, \fBTextureData\fP>()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBpathTex\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB6\fP of file \fBTextureManager\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void TextureManager\&.Add (\fBMeshPass\fP to, \fBTextureData\fP from, string texName = \fR'_MainTex'\fP)"

.PP
Definition at line \fB83\fP of file \fBTextureManager\&.cs\fP\&.
.SS "void TextureManager\&.AddBase (\fBTextureData\fP data, string path, \fBMeshPass\fP pass, string texName = \fR'_MainTex'\fP)"

.PP
Definition at line \fB71\fP of file \fBTextureManager\&.cs\fP\&.
.SS "void TextureManager\&.AddList (\fBTextureData\fP data, string path)"

.PP
Definition at line \fB89\fP of file \fBTextureManager\&.cs\fP\&.
.SS "void TextureManager\&.ApplyLocalReplace (string path)"

.PP
Definition at line \fB177\fP of file \fBTextureManager\&.cs\fP\&.
.SS "void TextureManager\&.Init ()"

.PP
Definition at line \fB19\fP of file \fBTextureManager\&.cs\fP\&.
.SS "void TextureManager\&.OnDropFile (List< string > paths)"

.PP
Definition at line \fB109\fP of file \fBTextureManager\&.cs\fP\&.
.SS "void TextureManager\&.RefreshTextures ()"

.PP
Definition at line \fB96\fP of file \fBTextureManager\&.cs\fP\&.
.SS "bool TextureManager\&.TryAddReplace (FileInfo file, TextureReplace\&.Source source = \fRTextureReplace::Source::Mod\fP, bool add = \fRtrue\fP, bool refresh = \fRfalse\fP)"

.PP
Definition at line \fB137\fP of file \fBTextureManager\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "Dictionary<string, \fBTextureData\fP> TextureManager\&.texMap = new Dictionary<string, \fBTextureData\fP>()"

.PP
Definition at line \fB211\fP of file \fBTextureManager\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "string TextureManager\&.pathTex\fR [get]\fP"

.PP
Definition at line \fB10\fP of file \fBTextureManager\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
