.TH "TextureData" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TextureData
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBEScriptable\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDate\fP"
.br
.in -1c
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBType\fP { \fBPass\fP, \fBWorld\fP, \fBDestTex\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBTryRefresh\fP ()"
.br
.ti -1c
.RI "void \fBForceRefresh\fP ()"
.br
.ti -1c
.RI "virtual bool \fBIsValid\fP ()"
.br
.ti -1c
.RI "void \fBLoad\fP (bool dateMatched)"
.br
.ti -1c
.RI "void \fBCreateReplace\fP (int index, string path, TextureReplace\&.Source source, int sizeX, int sizeY)"
.br
.ti -1c
.RI "void \fBAddReplace\fP (\fBTextureReplace\fP r)"
.br
.ti -1c
.RI "void \fBDeleteReplace\fP (\fBTextureReplace\fP r)"
.br
.ti -1c
.RI "void \fBRemoveDeletedReplace\fP (int index)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBRefreshAll\fP ()"
.br
.in -1c

Static Public Member Functions inherited from \fBEScriptable\fP
.in +1c
.ti -1c
.RI "static int \fBrnd\fP (int a)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBid\fP"
.br
.ti -1c
.RI "TextureData\&.Type \fBtype\fP"
.br
.ti -1c
.RI "\fBTextureData\&.Date\fP \fBdate\fP"
.br
.ti -1c
.RI "Texture2D \fBtex\fP"
.br
.ti -1c
.RI "bool \fBforceRefresh\fP"
.br
.ti -1c
.RI "int \fBtileW\fP"
.br
.ti -1c
.RI "int \fBtileH\fP"
.br
.ti -1c
.RI "string \fBpath\fP"
.br
.ti -1c
.RI "string \fBtexName\fP"
.br
.ti -1c
.RI "List< \fBMeshPass\fP > \fBlistPass\fP = new List<\fBMeshPass\fP>()"
.br
.ti -1c
.RI "Dictionary< int, \fBTextureReplace\fP > \fBdictReplace\fP = new Dictionary<int, \fBTextureReplace\fP>()"
.br
.ti -1c
.RI "List< \fBTextureReplace\fP > \fBlistReplaceLocal\fP = new List<\fBTextureReplace\fP>()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB7\fP of file \fBTextureData\&.cs\fP\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "enum TextureData\&.Type"

.PP
Definition at line \fB273\fP of file \fBTextureData\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void TextureData\&.AddReplace (\fBTextureReplace\fP r)"

.PP
Definition at line \fB163\fP of file \fBTextureData\&.cs\fP\&.
.SS "void TextureData\&.CreateReplace (int index, string path, TextureReplace\&.Source source, int sizeX, int sizeY)"

.PP
Definition at line \fB143\fP of file \fBTextureData\&.cs\fP\&.
.SS "void TextureData\&.DeleteReplace (\fBTextureReplace\fP r)"

.PP
Definition at line \fB185\fP of file \fBTextureData\&.cs\fP\&.
.SS "void TextureData\&.ForceRefresh ()"

.PP
Definition at line \fB47\fP of file \fBTextureData\&.cs\fP\&.
.SS "virtual bool TextureData\&.IsValid ()\fR [virtual]\fP"

.PP
Definition at line \fB67\fP of file \fBTextureData\&.cs\fP\&.
.SS "void TextureData\&.Load (bool dateMatched)"

.PP
Definition at line \fB88\fP of file \fBTextureData\&.cs\fP\&.
.SS "static void TextureData\&.RefreshAll ()\fR [static]\fP"

.PP
Definition at line \fB54\fP of file \fBTextureData\&.cs\fP\&.
.SS "void TextureData\&.RemoveDeletedReplace (int index)"

.PP
Definition at line \fB192\fP of file \fBTextureData\&.cs\fP\&.
.SS "void TextureData\&.TryRefresh ()"

.PP
Definition at line \fB10\fP of file \fBTextureData\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBTextureData\&.Date\fP TextureData\&.date"

.PP
Definition at line \fB215\fP of file \fBTextureData\&.cs\fP\&.
.SS "Dictionary<int, \fBTextureReplace\fP> TextureData\&.dictReplace = new Dictionary<int, \fBTextureReplace\fP>()"

.PP
Definition at line \fB243\fP of file \fBTextureData\&.cs\fP\&.
.SS "bool TextureData\&.forceRefresh"

.PP
Definition at line \fB221\fP of file \fBTextureData\&.cs\fP\&.
.SS "string TextureData\&.id"

.PP
Definition at line \fB209\fP of file \fBTextureData\&.cs\fP\&.
.SS "List<\fBMeshPass\fP> TextureData\&.listPass = new List<\fBMeshPass\fP>()"

.PP
Definition at line \fB239\fP of file \fBTextureData\&.cs\fP\&.
.SS "List<\fBTextureReplace\fP> TextureData\&.listReplaceLocal = new List<\fBTextureReplace\fP>()"

.PP
Definition at line \fB247\fP of file \fBTextureData\&.cs\fP\&.
.SS "string TextureData\&.path"

.PP
Definition at line \fB231\fP of file \fBTextureData\&.cs\fP\&.
.SS "Texture2D TextureData\&.tex"

.PP
Definition at line \fB218\fP of file \fBTextureData\&.cs\fP\&.
.SS "string TextureData\&.texName"

.PP
Definition at line \fB235\fP of file \fBTextureData\&.cs\fP\&.
.SS "int TextureData\&.tileH"

.PP
Definition at line \fB227\fP of file \fBTextureData\&.cs\fP\&.
.SS "int TextureData\&.tileW"

.PP
Definition at line \fB224\fP of file \fBTextureData\&.cs\fP\&.
.SS "TextureData\&.Type TextureData\&.type"

.PP
Definition at line \fB212\fP of file \fBTextureData\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
