.TH "ThingContainer.DestData" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ThingContainer.DestData
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBCard\fP \fBcontainer\fP"
.br
.ti -1c
.RI "\fBThing\fP \fBstack\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "bool \fBIsValid\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB879\fP of file \fBThingContainer\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBCard\fP ThingContainer\&.DestData\&.container"

.PP
Definition at line \fB892\fP of file \fBThingContainer\&.cs\fP\&.
.SS "\fBThing\fP ThingContainer\&.DestData\&.stack"

.PP
Definition at line \fB895\fP of file \fBThingContainer\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "bool ThingContainer\&.DestData\&.IsValid\fR [get]\fP"

.PP
Definition at line \fB883\fP of file \fBThingContainer\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
