.TH "ThingGen" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ThingGen
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCardGen\fP\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBThing\fP \fB_Create\fP (string id, int idMat=\-1, int lv=\-1)"
.br
.ti -1c
.RI "static \fBThing\fP \fBTestCreate\fP ()"
.br
.ti -1c
.RI "static \fBThing\fP \fBCreateCurrency\fP (int a, string id='money')"
.br
.ti -1c
.RI "static \fBThing\fP \fBCreateParcel\fP (string idLang=null, params \fBThing\fP[] things)"
.br
.ti -1c
.RI "static \fBThing\fP \fBCreate\fP (string id, int idMat=\-1, int lv=\-1)"
.br
.ti -1c
.RI "static \fBThing\fP \fBCreate\fP (string id, string idMat)"
.br
.ti -1c
.RI "static \fBThing\fP \fBCreateFromFilter\fP (string id, int lv=\-1)"
.br
.ti -1c
.RI "static \fBThing\fP \fBCreateRawMaterial\fP (\fBSourceMaterial\&.Row\fP m)"
.br
.ti -1c
.RI "static \fBThing\fP \fBCreateFromCategory\fP (string idCat, int lv=\-1)"
.br
.ti -1c
.RI "static \fBThing\fP \fBCreateFromTag\fP (string idTag, int lv=\-1)"
.br
.ti -1c
.RI "static \fBThing\fP \fBCreateBill\fP (int pay, bool tax)"
.br
.ti -1c
.RI "static \fBThing\fP \fBCreateBlock\fP (int id, int idMat)"
.br
.ti -1c
.RI "static \fBThing\fP \fBCreateFloor\fP (int id, int idMat, bool platform=false)"
.br
.ti -1c
.RI "static \fBThing\fP \fBCreateObj\fP (int id, int idMat)"
.br
.ti -1c
.RI "static \fBThing\fP \fBCreateMap\fP (string idSource=null, int lv=\-1)"
.br
.ti -1c
.RI "static \fBThing\fP \fBCreatePlan\fP (int ele)"
.br
.ti -1c
.RI "static \fBThing\fP \fBCreateRecipe\fP (string id)"
.br
.ti -1c
.RI "static \fBThing\fP \fBCreateSpellbook\fP (string alias, int num=1)"
.br
.ti -1c
.RI "static \fBThing\fP \fBCreateSpellbook\fP (int ele, int num=1)"
.br
.ti -1c
.RI "static \fBThing\fP \fBCreateScroll\fP (int ele, int num=1)"
.br
.ti -1c
.RI "static \fBThing\fP \fBCreatePotion\fP (int ele, int num=1)"
.br
.ti -1c
.RI "static \fBThing\fP \fBCreatePerfume\fP (int ele, int num=1)"
.br
.ti -1c
.RI "static \fBThing\fP \fBCreateCardboardBox\fP (int uidZone=\-1)"
.br
.ti -1c
.RI "static \fBThing\fP \fBCreateTreasure\fP (string id, int lv, TreasureType type=TreasureType\&.Map)"
.br
.ti -1c
.RI "static void \fBCreateTreasureContent\fP (\fBThing\fP t, int lv, TreasureType type, bool clearContent)"
.br
.ti -1c
.RI "static void \fBTryLickChest\fP (\fBThing\fP chest)"
.br
.in -1c

Static Public Member Functions inherited from \fBEClass\fP
.in +1c
.ti -1c
.RI "static int \fBrnd\fP (int a)"
.br
.ti -1c
.RI "static int \fBcurve\fP (int a, int start, int step, int rate=75)"
.br
.ti -1c
.RI "static int \fBrndHalf\fP (int a)"
.br
.ti -1c
.RI "static float \fBrndf\fP (float a)"
.br
.ti -1c
.RI "static int \fBrndSqrt\fP (int a)"
.br
.ti -1c
.RI "static void \fBWait\fP (float a, \fBCard\fP c)"
.br
.ti -1c
.RI "static void \fBWait\fP (float a, \fBPoint\fP p)"
.br
.ti -1c
.RI "static int \fBBigger\fP (int a, int b)"
.br
.ti -1c
.RI "static int \fBSmaller\fP (int a, int b)"
.br
.in -1c
.SS "Additional Inherited Members"


Static Public Attributes inherited from \fBEClass\fP
.in +1c
.ti -1c
.RI "static \fBCore\fP \fBcore\fP"
.br
.in -1c

Properties inherited from \fBEClass\fP
.in +1c
.ti -1c
.RI "static \fBGame\fP \fBgame\fP\fR [get]\fP"
.br
.ti -1c
.RI "static bool \fBAdvMode\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBPlayer\fP \fBplayer\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBChara\fP \fBpc\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBUI\fP \fBui\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBMap\fP \fB_map\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBZone\fP \fB_zone\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranchOrHomeBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFaction\fP \fBHome\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFaction\fP \fBWilds\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBScene\fP \fBscene\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBBaseGameScreen\fP \fBscreen\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameSetting\fP \fBsetting\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameData\fP \fBgamedata\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBColorProfile\fP \fBColors\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBWorld\fP \fBworld\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBsources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBeditorSources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static SoundManager \fBSound\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBCoreDebug\fP \fBdebug\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB8\fP of file \fBThingGen\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "static \fBThing\fP ThingGen\&._Create (string id, int idMat = \fR\-1\fP, int lv = \fR\-1\fP)\fR [static]\fP"

.PP
Definition at line \fB11\fP of file \fBThingGen\&.cs\fP\&.
.SS "static \fBThing\fP ThingGen\&.Create (string id, int idMat = \fR\-1\fP, int lv = \fR\-1\fP)\fR [static]\fP"

.PP
Definition at line \fB65\fP of file \fBThingGen\&.cs\fP\&.
.SS "static \fBThing\fP ThingGen\&.Create (string id, string idMat)\fR [static]\fP"

.PP
Definition at line \fB71\fP of file \fBThingGen\&.cs\fP\&.
.SS "static \fBThing\fP ThingGen\&.CreateBill (int pay, bool tax)\fR [static]\fP"

.PP
Definition at line \fB103\fP of file \fBThingGen\&.cs\fP\&.
.SS "static \fBThing\fP ThingGen\&.CreateBlock (int id, int idMat)\fR [static]\fP"

.PP
Definition at line \fB120\fP of file \fBThingGen\&.cs\fP\&.
.SS "static \fBThing\fP ThingGen\&.CreateCardboardBox (int uidZone = \fR\-1\fP)\fR [static]\fP"

.PP
Definition at line \fB214\fP of file \fBThingGen\&.cs\fP\&.
.SS "static \fBThing\fP ThingGen\&.CreateCurrency (int a, string id = \fR'money'\fP)\fR [static]\fP"

.PP
Definition at line \fB47\fP of file \fBThingGen\&.cs\fP\&.
.SS "static \fBThing\fP ThingGen\&.CreateFloor (int id, int idMat, bool platform = \fRfalse\fP)\fR [static]\fP"

.PP
Definition at line \fB128\fP of file \fBThingGen\&.cs\fP\&.
.SS "static \fBThing\fP ThingGen\&.CreateFromCategory (string idCat, int lv = \fR\-1\fP)\fR [static]\fP"

.PP
Definition at line \fB91\fP of file \fBThingGen\&.cs\fP\&.
.SS "static \fBThing\fP ThingGen\&.CreateFromFilter (string id, int lv = \fR\-1\fP)\fR [static]\fP"

.PP
Definition at line \fB77\fP of file \fBThingGen\&.cs\fP\&.
.SS "static \fBThing\fP ThingGen\&.CreateFromTag (string idTag, int lv = \fR\-1\fP)\fR [static]\fP"

.PP
Definition at line \fB97\fP of file \fBThingGen\&.cs\fP\&.
.SS "static \fBThing\fP ThingGen\&.CreateMap (string idSource = \fRnull\fP, int lv = \fR\-1\fP)\fR [static]\fP"

.PP
Definition at line \fB146\fP of file \fBThingGen\&.cs\fP\&.
.SS "static \fBThing\fP ThingGen\&.CreateObj (int id, int idMat)\fR [static]\fP"

.PP
Definition at line \fB137\fP of file \fBThingGen\&.cs\fP\&.
.SS "static \fBThing\fP ThingGen\&.CreateParcel (string idLang = \fRnull\fP, params \fBThing\fP[] things)\fR [static]\fP"

.PP
Definition at line \fB53\fP of file \fBThingGen\&.cs\fP\&.
.SS "static \fBThing\fP ThingGen\&.CreatePerfume (int ele, int num = \fR1\fP)\fR [static]\fP"

.PP
Definition at line \fB206\fP of file \fBThingGen\&.cs\fP\&.
.SS "static \fBThing\fP ThingGen\&.CreatePlan (int ele)\fR [static]\fP"

.PP
Definition at line \fB160\fP of file \fBThingGen\&.cs\fP\&.
.SS "static \fBThing\fP ThingGen\&.CreatePotion (int ele, int num = \fR1\fP)\fR [static]\fP"

.PP
Definition at line \fB198\fP of file \fBThingGen\&.cs\fP\&.
.SS "static \fBThing\fP ThingGen\&.CreateRawMaterial (\fBSourceMaterial\&.Row\fP m)\fR [static]\fP"

.PP
Definition at line \fB83\fP of file \fBThingGen\&.cs\fP\&.
.SS "static \fBThing\fP ThingGen\&.CreateRecipe (string id)\fR [static]\fP"

.PP
Definition at line \fB168\fP of file \fBThingGen\&.cs\fP\&.
.SS "static \fBThing\fP ThingGen\&.CreateScroll (int ele, int num = \fR1\fP)\fR [static]\fP"

.PP
Definition at line \fB190\fP of file \fBThingGen\&.cs\fP\&.
.SS "static \fBThing\fP ThingGen\&.CreateSpellbook (int ele, int num = \fR1\fP)\fR [static]\fP"

.PP
Definition at line \fB182\fP of file \fBThingGen\&.cs\fP\&.
.SS "static \fBThing\fP ThingGen\&.CreateSpellbook (string alias, int num = \fR1\fP)\fR [static]\fP"

.PP
Definition at line \fB176\fP of file \fBThingGen\&.cs\fP\&.
.SS "static \fBThing\fP ThingGen\&.CreateTreasure (string id, int lv, TreasureType type = \fRTreasureType::Map\fP)\fR [static]\fP"

.PP
Definition at line \fB234\fP of file \fBThingGen\&.cs\fP\&.
.SS "static void ThingGen\&.CreateTreasureContent (\fBThing\fP t, int lv, TreasureType type, bool clearContent)\fR [static]\fP"

.PP
Definition at line \fB242\fP of file \fBThingGen\&.cs\fP\&.
.SS "static \fBThing\fP ThingGen\&.TestCreate ()\fR [static]\fP"

.PP
Definition at line \fB41\fP of file \fBThingGen\&.cs\fP\&.
.SS "static void ThingGen\&.TryLickChest (\fBThing\fP chest)\fR [static]\fP"

.PP
Definition at line \fB365\fP of file \fBThingGen\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
