.TH "TileTypeSlope" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TileTypeSlope
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBTileTypeBaseBlock\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override bool \fBCanRotate\fP (bool buildMode)"
.br
.in -1c

Public Member Functions inherited from \fBTileType\fP
.in +1c
.ti -1c
.RI "HitResult \fB_HitTest\fP (\fBPoint\fP pos, \fBCard\fP target, bool canIgnore=true)"
.br
.ti -1c
.RI "virtual int \fBGetDesiredDir\fP (\fBPoint\fP p, int d)"
.br
.ti -1c
.RI "virtual void \fBGetMountHeight\fP (ref Vector3 v, \fBPoint\fP p, int d, \fBCard\fP target=null)"
.br
.ti -1c
.RI "Vector3 \fBGetRampFix\fP (int dir)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override TileType\&.RampType \fBRamp\fP\fR [get]\fP"
.br
.ti -1c
.RI "override byte \fBslopeHeight\fP\fR [get]\fP"
.br
.ti -1c
.RI "override bool \fBFreeStyle\fP\fR [get]\fP"
.br
.ti -1c
.RI "override bool \fBCanBuiltOnBlock\fP\fR [get]\fP"
.br
.ti -1c
.RI "override bool \fBIsOccupyCell\fP\fR [get]\fP"
.br
.in -1c

Properties inherited from \fBTileTypeBaseBlock\fP
.in +1c
.ti -1c
.RI "override string \fBLangPlaceType\fP\fR [get]\fP"
.br
.ti -1c
.RI "override bool \fBCanBuiltOnWater\fP\fR [get]\fP"
.br
.in -1c

Properties inherited from \fBTileType\fP
.in +1c
.ti -1c
.RI "virtual string \fBLangPlaceType\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBCanStack\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBChangeBlockDir\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBIsSkipLowBlock\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBIsSkipFloor\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBIsUseBlockDir\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBIsFloorOrBridge\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBIsWall\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBIsFloor\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBIsBridge\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBIsWallOrFence\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBIsWallOrFullBlock\fP\fR [get]\fP"
.br
.ti -1c
.RI "bool \fBIsRamp\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual TileType\&.RampType \fBRamp\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBIsLadder\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBIsBlockPass\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBIsOccupyCell\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBIsBlockSight\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBIsOpenSight\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBIsBlockLiquid\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBIsWater\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBIsDeepWater\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBIsBlockMount\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBIsFullBlock\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBIsFence\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBIsFloodBlock\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBIsPlayFootSound\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBCanSpawnOnWater\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBIsWaterTop\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBCastShadowSelf\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBCastShadowBack\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBCastAmbientShadow\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBCastAmbientShadowBack\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBCanBuiltOnArea\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBCanBuiltOnWater\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBCanBuiltOnThing\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBCanBuiltOnBlock\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBIsDoor\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBCanBuiltOnFloor\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBCanBuiltOnBridge\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBCanInstaComplete\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual int \fBMinAltitude\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual int \fBMaxAltitude\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBAltitudeAsDir\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBUseLowWallTiles\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBUseMountHeight\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBUseHangZFix\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBUseLowBlock\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBRemoveOnFloorChange\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBAllowObj\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBAllowMultiInstall\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBFreeStyle\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual byte \fBslopeHeight\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual float \fBMountHeight\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual float \fBFloorHeight\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual float \fBRepeatSize\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual int \fBFloorAltitude\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual int \fBLiquidLV\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBAllowLitter\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBAllowBlood\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBShowPillar\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBAlwaysShowShadow\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBRepeatBlock\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBForceRpeatBlock\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBCanBeHeld\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBEditorTile\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBIsFloodDoor\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBInvisible\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBIgnoreBuildRule\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBRenderWaterBlock\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual BaseTileSelector\&.SelectType \fBSelectType\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual BaseTileSelector\&.BoxType \fBBoxType\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual BaseTileSelector\&.HitType \fBHitType\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual BlockRenderMode \fBblockRenderMode\fP\fR [get]\fP"
.br
.ti -1c
.RI "bool \fBIsMountBlock\fP\fR [get]\fP"
.br
.in -1c

Properties inherited from \fBEClass\fP
.in +1c
.ti -1c
.RI "static \fBGame\fP \fBgame\fP\fR [get]\fP"
.br
.ti -1c
.RI "static bool \fBAdvMode\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBPlayer\fP \fBplayer\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBChara\fP \fBpc\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBUI\fP \fBui\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBMap\fP \fB_map\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBZone\fP \fB_zone\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranchOrHomeBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFaction\fP \fBHome\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFaction\fP \fBWilds\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBScene\fP \fBscene\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBBaseGameScreen\fP \fBscreen\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameSetting\fP \fBsetting\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameData\fP \fBgamedata\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBColorProfile\fP \fBColors\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBWorld\fP \fBworld\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBsources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBeditorSources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static SoundManager \fBSound\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBCoreDebug\fP \fBdebug\fP\fR [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Public Types inherited from \fBTileType\fP
.in +1c
.ti -1c
.RI "enum \fBRampType\fP { \fBNone\fP, \fBFull\fP, \fBHalf\fP }"
.br
.in -1c

Static Public Member Functions inherited from \fBTileType\fP
.in +1c
.ti -1c
.RI "static void \fBInit\fP ()"
.br
.in -1c

Static Public Member Functions inherited from \fBEClass\fP
.in +1c
.ti -1c
.RI "static int \fBrnd\fP (int a)"
.br
.ti -1c
.RI "static int \fBcurve\fP (int a, int start, int step, int rate=75)"
.br
.ti -1c
.RI "static int \fBrndHalf\fP (int a)"
.br
.ti -1c
.RI "static float \fBrndf\fP (float a)"
.br
.ti -1c
.RI "static int \fBrndSqrt\fP (int a)"
.br
.ti -1c
.RI "static void \fBWait\fP (float a, \fBCard\fP c)"
.br
.ti -1c
.RI "static void \fBWait\fP (float a, \fBPoint\fP p)"
.br
.ti -1c
.RI "static int \fBBigger\fP (int a, int b)"
.br
.ti -1c
.RI "static int \fBSmaller\fP (int a, int b)"
.br
.in -1c

Static Public Attributes inherited from \fBTileType\fP
.in +1c
.ti -1c
.RI "static \fBTileTypeNone\fP \fBNone\fP = new \fBTileTypeNone\fP()"
.br
.ti -1c
.RI "static \fBTileTypeInvisibleBlock\fP \fBInvisiBlock\fP = new \fBTileTypeInvisibleBlock\fP()"
.br
.ti -1c
.RI "static \fBTileTypeBlock\fP \fBBlock\fP = new \fBTileTypeBlock\fP()"
.br
.ti -1c
.RI "static \fBTileTypeBlockShip\fP \fBBlockShip\fP = new \fBTileTypeBlockShip\fP()"
.br
.ti -1c
.RI "static \fBTileTypeSlope\fP \fBSlope\fP = new \fBTileTypeSlope\fP()"
.br
.ti -1c
.RI "static \fBTileTypeHalfBlock\fP \fBHalfBlock\fP = new \fBTileTypeHalfBlock\fP()"
.br
.ti -1c
.RI "static \fBTileTypeStairs\fP \fBStairs\fP = new \fBTileTypeStairs\fP()"
.br
.ti -1c
.RI "static \fBTileTypeStairs\fP \fBStairsHalf\fP = new \fBTileTypeStairsHalf\fP()"
.br
.ti -1c
.RI "static \fBTileTypeRooftop\fP \fBRooftop\fP = new \fBTileTypeRooftop\fP()"
.br
.ti -1c
.RI "static \fBTileTypeScaffold\fP \fBScaffold\fP = new \fBTileTypeScaffold\fP()"
.br
.ti -1c
.RI "static \fBTileTypeLadder\fP \fBLadder\fP = new \fBTileTypeLadder\fP()"
.br
.ti -1c
.RI "static \fBTileTypePillar\fP \fBPillar\fP = new \fBTileTypePillar\fP()"
.br
.ti -1c
.RI "static \fBTileTypeWaterfall\fP \fBWaterfall\fP = new \fBTileTypeWaterfall\fP()"
.br
.ti -1c
.RI "static \fBTileTypeWall\fP \fBWall\fP = new \fBTileTypeWall\fP()"
.br
.ti -1c
.RI "static \fBTileTypeWallOpen\fP \fBWallOpen\fP = new \fBTileTypeWallOpen\fP()"
.br
.ti -1c
.RI "static \fBTileTypeFence\fP \fBFence\fP = new \fBTileTypeFence\fP()"
.br
.ti -1c
.RI "static \fBTileTypeFenceClosed\fP \fBFenceClosed\fP = new \fBTileTypeFenceClosed\fP()"
.br
.ti -1c
.RI "static \fBTileTypeFloor\fP \fBFloor\fP = new \fBTileTypeFloor\fP()"
.br
.ti -1c
.RI "static \fBTileTypeFloorScaffold\fP \fBFloorScaffold\fP = new \fBTileTypeFloorScaffold\fP()"
.br
.ti -1c
.RI "static \fBTileTypeWater\fP \fBFloorWater\fP = new \fBTileTypeWater\fP()"
.br
.ti -1c
.RI "static \fBTileTypeWaterShallow\fP \fBFloorWaterShallow\fP = new \fBTileTypeWaterShallow\fP()"
.br
.ti -1c
.RI "static \fBTileTypeWaterDeep\fP \fBFloorWaterDeep\fP = new \fBTileTypeWaterDeep\fP()"
.br
.ti -1c
.RI "static \fBTileTypeBridge\fP \fBBridge\fP = new \fBTileTypeBridge\fP()"
.br
.ti -1c
.RI "static \fBTileTypeBridgeDeco\fP \fBBridgeDeco\fP = new \fBTileTypeBridgeDeco\fP()"
.br
.ti -1c
.RI "static \fBTileTypeBridgePillar\fP \fBBridgePillar\fP = new \fBTileTypeBridgePillar\fP()"
.br
.ti -1c
.RI "static \fBTileTypeSky\fP \fBSky\fP = new \fBTileTypeSky\fP()"
.br
.ti -1c
.RI "static \fBTileTypeObj\fP \fBObj\fP = new \fBTileTypeObj\fP()"
.br
.ti -1c
.RI "static \fBTileTypeObjBig\fP \fBObjBig\fP = new \fBTileTypeObjBig\fP()"
.br
.ti -1c
.RI "static \fBTileTypeObjHuge\fP \fBObjHuge\fP = new \fBTileTypeObjHuge\fP()"
.br
.ti -1c
.RI "static \fBTileTypeObjCeil\fP \fBObjCeil\fP = new \fBTileTypeObjCeil\fP()"
.br
.ti -1c
.RI "static \fBTileTypeObjFloat\fP \fBObjFloat\fP = new \fBTileTypeObjFloat\fP()"
.br
.ti -1c
.RI "static \fBTileTypeObjWater\fP \fBObjWater\fP = new \fBTileTypeObjWater\fP()"
.br
.ti -1c
.RI "static \fBTileTypeObjWaterTop\fP \fBObjWaterTop\fP = new \fBTileTypeObjWaterTop\fP()"
.br
.ti -1c
.RI "static \fBTileTypeIllumination\fP \fBIllumination\fP = new \fBTileTypeIllumination\fP()"
.br
.ti -1c
.RI "static \fBTileTypeTree\fP \fBTree\fP = new \fBTileTypeTree\fP()"
.br
.ti -1c
.RI "static \fBTileTypeDoor\fP \fBDoor\fP = new \fBTileTypeDoor\fP()"
.br
.ti -1c
.RI "static \fBTileTypeWallHang\fP \fBWallHang\fP = new \fBTileTypeWallHang\fP()"
.br
.ti -1c
.RI "static \fBTileTypeWallHangSign\fP \fBWallHangSign\fP = new \fBTileTypeWallHangSign\fP()"
.br
.ti -1c
.RI "static \fBTileTypeVine\fP \fBVine\fP = new \fBTileTypeVine\fP()"
.br
.ti -1c
.RI "static \fBTileTypeWallMount\fP \fBWallMount\fP = new \fBTileTypeWallMount\fP()"
.br
.ti -1c
.RI "static \fBTileTypePaint\fP \fBPaint\fP = new \fBTileTypePaint\fP()"
.br
.ti -1c
.RI "static \fBTileTypeWindow\fP \fBWindow\fP = new \fBTileTypeWindow\fP()"
.br
.ti -1c
.RI "static \fBTileTypeRoof\fP \fBRoof\fP = new \fBTileTypeRoof\fP()"
.br
.ti -1c
.RI "static \fBTileTypeRoad\fP \fBRoad\fP = new \fBTileTypeRoad\fP()"
.br
.ti -1c
.RI "static \fBTileTypeChasm\fP \fBChasm\fP = new \fBTileTypeChasm\fP()"
.br
.ti -1c
.RI "static \fBTileTypeBoat\fP \fBBoat\fP = new \fBTileTypeBoat\fP()"
.br
.ti -1c
.RI "static \fBTileTypeLiquid\fP \fBLiquid\fP = new \fBTileTypeLiquid\fP()"
.br
.ti -1c
.RI "static \fBTileTypeMarker\fP \fBMarker\fP = new \fBTileTypeMarker\fP()"
.br
.ti -1c
.RI "static Dictionary< string, \fBTileType\fP > \fBdict\fP = new Dictionary<string, \fBTileType\fP>()"
.br
.in -1c

Static Public Attributes inherited from \fBEClass\fP
.in +1c
.ti -1c
.RI "static \fBCore\fP \fBcore\fP"
.br
.in -1c

Protected Member Functions inherited from \fBTileType\fP
.in +1c
.ti -1c
.RI "virtual HitResult \fBHitTest\fP (\fBPoint\fP pos)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB4\fP of file \fBTileTypeSlope\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override bool TileTypeSlope\&.CanRotate (bool buildMode)\fR [virtual]\fP"

.PP
Reimplemented from \fBTileType\fP\&.
.PP
Definition at line \fB17\fP of file \fBTileTypeSlope\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "override bool TileTypeSlope\&.CanBuiltOnBlock\fR [get]\fP"

.PP
Definition at line \fB44\fP of file \fBTileTypeSlope\&.cs\fP\&.
.SS "override bool TileTypeSlope\&.FreeStyle\fR [get]\fP"

.PP
Definition at line \fB34\fP of file \fBTileTypeSlope\&.cs\fP\&.
.SS "override bool TileTypeSlope\&.IsOccupyCell\fR [get]\fP"

.PP
Definition at line \fB54\fP of file \fBTileTypeSlope\&.cs\fP\&.
.SS "override TileType\&.RampType TileTypeSlope\&.Ramp\fR [get]\fP"

.PP
Definition at line \fB8\fP of file \fBTileTypeSlope\&.cs\fP\&.
.SS "override byte TileTypeSlope\&.slopeHeight\fR [get]\fP"

.PP
Definition at line \fB24\fP of file \fBTileTypeSlope\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
