.TH "TileMap" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TileMap
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBBaseTileMap\fP\&.
.SS "Additional Inherited Members"


Public Types inherited from \fBBaseTileMap\fP
.in +1c
.ti -1c
.RI "enum \fBWallClipMode\fP { \fBByRoom\fP, \fBByLot\fP }"
.br
.ti -1c
.RI "enum \fBInnerMode\fP { \fBNone\fP, \fBInnerBlock\fP, \fBHeight\fP, \fBBuildMode\fP }"
.br
.ti -1c
.RI "enum \fBCardIconMode\fP { \fBNone\fP, \fBInspect\fP, \fBDeconstruct\fP, \fBState\fP, \fBVisibility\fP }"
.br
.ti -1c
.RI "enum \fBScreenHighlight\fP { \fBNone\fP, \fBSunMap\fP }"
.br
.in -1c

Public Member Functions inherited from \fBBaseTileMap\fP
.in +1c
.ti -1c
.RI "void \fBOnActivate\fP (\fBBaseGameScreen\fP _screen)"
.br
.ti -1c
.RI "virtual unsafe void \fBDraw\fP ()"
.br
.ti -1c
.RI "void \fBRefreshHeight\fP ()"
.br
.ti -1c
.RI "virtual void \fBDrawTile\fP ()"
.br
.ti -1c
.RI "Vector3 \fBGetThingPosition\fP (\fBCard\fP tg, \fBPoint\fP p)"
.br
.ti -1c
.RI "int \fBGetApproximateBlocklight\fP (\fBCell\fP cell)"
.br
.ti -1c
.RI "int \fBGetRoofLight\fP (\fBLot\fP lot)"
.br
.ti -1c
.RI "void \fBDrawRoof\fP (\fBLot\fP lot)"
.br
.ti -1c
.RI "void \fBSetRoofHeight\fP (\fBMeshPassParam\fP _param, \fBCell\fP _cell, int _cx, int _cz, int h=0, int altitude=0, int dirWall=\-1, bool ignoreAltitudeY=false)"
.br
.in -1c

Static Public Member Functions inherited from \fBBaseTileMap\fP
.in +1c
.ti -1c
.RI "static int \fBGetColorInt\fP (ref Color matColor, int p)"
.br
.in -1c

Static Public Member Functions inherited from \fBEMono\fP
.in +1c
.ti -1c
.RI "static int \fBrnd\fP (int a)"
.br
.in -1c

Public Attributes inherited from \fBBaseTileMap\fP
.in +1c
.ti -1c
.RI "int \fBcount\fP"
.br
.ti -1c
.RI "Collider2D \fBmouseCollider\fP"
.br
.ti -1c
.RI "Vector3 \fBcolliderFix\fP"
.br
.ti -1c
.RI "int \fBmaxColliderCheck\fP"
.br
.ti -1c
.RI "float \fBheightBlockSize\fP"
.br
.ti -1c
.RI "float \fBslopeFixZ\fP"
.br
.ti -1c
.RI "float \fBheightModDeco\fP"
.br
.ti -1c
.RI "float \fBheightLimitDeco\fP"
.br
.ti -1c
.RI "Vector3 \fBheightMod\fP"
.br
.ti -1c
.RI "Vector3 \fBugFix\fP"
.br
.ti -1c
.RI "Vector3 \fBugFixBridge\fP"
.br
.ti -1c
.RI "Vector3 \fBugFixBridgeBottom\fP"
.br
.ti -1c
.RI "Vector3 \fBugFixBridgeTop\fP"
.br
.ti -1c
.RI "Vector3 \fBheightModRoofBlock\fP"
.br
.ti -1c
.RI "float \fBrightWallShade\fP"
.br
.ti -1c
.RI "Vector3 \fBroofRampFix\fP"
.br
.ti -1c
.RI "Vector3 \fBroofFix\fP"
.br
.ti -1c
.RI "Vector3 \fBroofFix2\fP"
.br
.ti -1c
.RI "Vector3 \fBroofFix3\fP"
.br
.ti -1c
.RI "float \fBroofLightMod\fP"
.br
.ti -1c
.RI "float \fBlotLight\fP"
.br
.ti -1c
.RI "float \fBlotLight2\fP"
.br
.ti -1c
.RI "float \fBroofLightSnow\fP"
.br
.ti -1c
.RI "BaseTileMap\&.WallClipMode \fBwallClipMode\fP"
.br
.ti -1c
.RI "BaseTileMap\&.InnerMode \fBdefaultInnerMode\fP"
.br
.ti -1c
.RI "Vector3 \fBedgeBlockFix\fP"
.br
.ti -1c
.RI "Vector3 \fBbridgeFix\fP"
.br
.ti -1c
.RI "Vector3 \fBcornerWallFix\fP"
.br
.ti -1c
.RI "Vector3 \fBcornerWallFix2\fP"
.br
.ti -1c
.RI "Vector3 \fBcornerWallFix3\fP"
.br
.ti -1c
.RI "Vector3 \fBaltitudeFix\fP"
.br
.ti -1c
.RI "Vector3 \fBwaterEdgeFix\fP"
.br
.ti -1c
.RI "Vector3 \fBwaterEdgeBridgeFix\fP"
.br
.ti -1c
.RI "Vector3 \fBwaterEdgeFixShore\fP"
.br
.ti -1c
.RI "Vector3 \fBwaterEdgeFixShoreSand\fP"
.br
.ti -1c
.RI "Vector3[] \fBambientShadowFix\fP"
.br
.ti -1c
.RI "Vector3[] \fBtransitionFix\fP"
.br
.ti -1c
.RI "Vector3[] \fBwallHangFix\fP"
.br
.ti -1c
.RI "Vector3[] \fBwaterEdgeBlockFix\fP"
.br
.ti -1c
.RI "int \fBfogTile\fP"
.br
.ti -1c
.RI "float \fBfloatSpeed\fP"
.br
.ti -1c
.RI "float \fBshadowModStrength\fP"
.br
.ti -1c
.RI "int \fBmaxFloat\fP"
.br
.ti -1c
.RI "int[] \fBseaAnimeIndexes\fP"
.br
.ti -1c
.RI "NoiseLayer \fBlayerGroundLights\fP"
.br
.ti -1c
.RI "\fBMeshPass\fP \fBpassShadow\fP"
.br
.ti -1c
.RI "\fBMeshPass\fP \fBpassLiquid\fP"
.br
.ti -1c
.RI "\fBMeshPass\fP \fBpassGuideBlock\fP"
.br
.ti -1c
.RI "\fBMeshPass\fP \fBpassGuideFloor\fP"
.br
.ti -1c
.RI "\fBMeshPass\fP \fBpassArea\fP"
.br
.ti -1c
.RI "\fBMeshPass\fP \fBpassRamp\fP"
.br
.ti -1c
.RI "\fBMeshPass\fP \fBpassFloor\fP"
.br
.ti -1c
.RI "\fBMeshPass\fP \fBpassBlock\fP"
.br
.ti -1c
.RI "\fBMeshPass\fP \fBpassObjS\fP"
.br
.ti -1c
.RI "\fBMeshPass\fP \fBpassObjSS\fP"
.br
.ti -1c
.RI "\fBMeshPass\fP \fBpassObj\fP"
.br
.ti -1c
.RI "\fBMeshPass\fP \fBpassObjL\fP"
.br
.ti -1c
.RI "\fBMeshPass\fP \fBpassDecal\fP"
.br
.ti -1c
.RI "\fBMeshPass\fP \fBpassRoof\fP"
.br
.ti -1c
.RI "\fBMeshPass\fP \fBpassBlockEx\fP"
.br
.ti -1c
.RI "\fBMeshPass\fP \fBpassFloorEx\fP"
.br
.ti -1c
.RI "\fBMeshPass\fP \fBpassFloorWater\fP"
.br
.ti -1c
.RI "\fBMeshPass\fP \fBpassInner\fP"
.br
.ti -1c
.RI "\fBMeshPass\fP \fBpassFog\fP"
.br
.ti -1c
.RI "\fBMeshPass\fP \fBpassFov\fP"
.br
.ti -1c
.RI "\fBMeshPass\fP \fBpassEdge\fP"
.br
.ti -1c
.RI "\fBMeshPass\fP \fBpassAutoTile\fP"
.br
.ti -1c
.RI "\fBMeshPass\fP \fBpassAutoTileWater\fP"
.br
.ti -1c
.RI "\fBMeshPass\fP \fBpassBlockMarker\fP"
.br
.ti -1c
.RI "\fBMeshPass\fP \fBpassFloorMarker\fP"
.br
.ti -1c
.RI "\fBMeshPass\fP \fBpassWaterBlock\fP"
.br
.ti -1c
.RI "\fBMeshPass\fP \fBpassIcon\fP"
.br
.ti -1c
.RI "\fBMeshPass\fP \fBpassChara\fP"
.br
.ti -1c
.RI "\fBMeshPass\fP \fBpassCharaL\fP"
.br
.ti -1c
.RI "\fBMeshPass\fP \fBpassCharaLL\fP"
.br
.ti -1c
.RI "\fBMeshPass\fP \fBpassShore\fP"
.br
.ti -1c
.RI "\fBRenderData\fP \fBrenderFootmark\fP"
.br
.ti -1c
.RI "\fBRenderData\fP \fBrendererBlockMarker\fP"
.br
.ti -1c
.RI "\fBRenderData\fP \fBrendererFloorMarker\fP"
.br
.ti -1c
.RI "\fBRenderData\fP \fBrendererInnerBlock\fP"
.br
.ti -1c
.RI "\fBRenderData\fP \fBrendererFov\fP"
.br
.ti -1c
.RI "\fBRenderData\fP \fBrendererFov2\fP"
.br
.ti -1c
.RI "\fBRenderData\fP \fBrendererShore\fP"
.br
.ti -1c
.RI "\fBRenderData\fP \fBrenderBorder\fP"
.br
.ti -1c
.RI "\fBRenderData\fP \fBrendererFogBlockSolid\fP"
.br
.ti -1c
.RI "\fBRenderData\fP \fBrendererFogFloorSolid\fP"
.br
.ti -1c
.RI "\fBRenderData\fP \fBrendererFogRoomSolid\fP"
.br
.ti -1c
.RI "\fBRenderData\fP \fBrendererFogRoomBlockSolid\fP"
.br
.ti -1c
.RI "\fBRenderData\fP \fBrendererFogRoomWallSolid\fP"
.br
.ti -1c
.RI "\fBRenderData\fP \fBrendererWallDeco\fP"
.br
.ti -1c
.RI "\fBRenderData\fP \fBrendererWaterBlock\fP"
.br
.ti -1c
.RI "\fBRenderDataObjDummy\fP \fBrendererObjDummy\fP"
.br
.ti -1c
.RI "\fBRenderDataEffect\fP \fBrendererEffect\fP"
.br
.ti -1c
.RI "\fBPoint\fP \fBTestPoint\fP = new \fBPoint\fP()"
.br
.ti -1c
.RI "int \fBSize\fP"
.br
.ti -1c
.RI "int \fBSizeXZ\fP"
.br
.ti -1c
.RI "int \fBmx\fP"
.br
.ti -1c
.RI "int \fBmz\fP"
.br
.ti -1c
.RI "int \fBx\fP"
.br
.ti -1c
.RI "int \fBz\fP"
.br
.ti -1c
.RI "int \fBcx\fP"
.br
.ti -1c
.RI "int \fBcz\fP"
.br
.ti -1c
.RI "int \fBactiveCount\fP"
.br
.ti -1c
.RI "int \fBfloatV\fP = 1"
.br
.ti -1c
.RI "byte[] \fBgroundLights\fP"
.br
.ti -1c
.RI "bool \fBlowBlock\fP"
.br
.ti -1c
.RI "bool \fBlowObj\fP"
.br
.ti -1c
.RI "bool \fBhighlightArea\fP"
.br
.ti -1c
.RI "bool \fBsubtleHighlightArea\fP"
.br
.ti -1c
.RI "bool \fBhideRoomFog\fP"
.br
.ti -1c
.RI "bool \fBshowRoof\fP"
.br
.ti -1c
.RI "bool \fBshowFullWall\fP"
.br
.ti -1c
.RI "bool \fBhideHang\fP"
.br
.ti -1c
.RI "bool \fBusingHouseBoard\fP"
.br
.ti -1c
.RI "bool \fBnoRoofMode\fP"
.br
.ti -1c
.RI "bool \fBfogged\fP"
.br
.ti -1c
.RI "float[] \fBlightLookUp\fP"
.br
.ti -1c
.RI "float \fB_lightMod\fP"
.br
.ti -1c
.RI "float \fB_baseBrightness\fP"
.br
.ti -1c
.RI "float \fBlowblockTimer\fP"
.br
.ti -1c
.RI "float \fBheightLightMod\fP"
.br
.ti -1c
.RI "float \fB_rightWallShade\fP"
.br
.ti -1c
.RI "float \fBroofLightLimitMod\fP"
.br
.ti -1c
.RI "float \fBfloatY\fP"
.br
.ti -1c
.RI "float \fBfloorShadowStrength\fP"
.br
.ti -1c
.RI "Vector3 \fB_heightMod\fP"
.br
.ti -1c
.RI "BaseTileMap\&.ScreenHighlight \fBscreenHighlight\fP"
.br
.ti -1c
.RI "new \fBBaseGameScreen\fP \fBscreen\fP"
.br
.ti -1c
.RI "\fBRoofStyle\fP[] \fBroofStyles\fP"
.br
.in -1c

Static Public Attributes inherited from \fBBaseTileMap\fP
.in +1c
.ti -1c
.RI "static bool \fBforceShowHang\fP"
.br
.ti -1c
.RI "const int \fBDefColor\fP = 104025"
.br
.ti -1c
.RI "const int \fBBlocklightToken\fP = 262144"
.br
.ti -1c
.RI "const int \fBBlocklightMTP\fP = 50"
.br
.in -1c

Static Public Attributes inherited from \fBEMono\fP
.in +1c
.ti -1c
.RI "static \fBCore\fP \fBcore\fP"
.br
.in -1c

Protected Attributes inherited from \fBBaseTileMap\fP
.in +1c
.ti -1c
.RI "BaseTileMap\&.InnerMode \fBinnerMode\fP"
.br
.ti -1c
.RI "RaycastHit2D[] \fBrays\fP = new RaycastHit2D[1]"
.br
.ti -1c
.RI "BaseTileMap\&.CardIconMode \fBiconMode\fP"
.br
.ti -1c
.RI "bool \fBisMining\fP"
.br
.ti -1c
.RI "bool \fBbuildMode\fP"
.br
.ti -1c
.RI "bool \fBhasBridge\fP"
.br
.ti -1c
.RI "bool \fB_lowblock\fP"
.br
.ti -1c
.RI "bool \fBisIndoor\fP"
.br
.ti -1c
.RI "\fBMap\fP \fBmap\fP"
.br
.ti -1c
.RI "\fBMeshPass\fP \fBpass\fP"
.br
.ti -1c
.RI "\fBBaseTileSelector\fP \fBselector\fP"
.br
.ti -1c
.RI "\fBGameSetting\&.RenderSetting\fP \fBrenderSetting\fP"
.br
.ti -1c
.RI "\fBGameSetting\&.RenderSetting\&.ZSetting\fP \fBzSetting\fP"
.br
.ti -1c
.RI "int \fBliquidLv\fP"
.br
.ti -1c
.RI "int \fBindex\fP"
.br
.ti -1c
.RI "int \fBtotalFire\fP"
.br
.ti -1c
.RI "int \fBsnowColorToken\fP"
.br
.ti -1c
.RI "int \fBwaterAnimeIndex\fP"
.br
.ti -1c
.RI "int \fBlowWallObjAltitude\fP"
.br
.ti -1c
.RI "\fBSourceMaterial\&.Row\fP \fBmatBlock\fP"
.br
.ti -1c
.RI "\fBSourceMaterial\&.Row\fP \fBmatFloor\fP"
.br
.ti -1c
.RI "\fBSourceMaterial\&.Row\fP \fBmatBridge\fP"
.br
.ti -1c
.RI "float \fBblockLight\fP"
.br
.ti -1c
.RI "float \fBfloorLight\fP"
.br
.ti -1c
.RI "float \fBfloorLight2\fP"
.br
.ti -1c
.RI "float \fBlight\fP"
.br
.ti -1c
.RI "float \fBpcMaxLight\fP"
.br
.ti -1c
.RI "float \fBorgX\fP"
.br
.ti -1c
.RI "float \fBorgY\fP"
.br
.ti -1c
.RI "float \fBorgZ\fP"
.br
.ti -1c
.RI "float \fBroomHeight\fP"
.br
.ti -1c
.RI "float \fBmaxHeight\fP"
.br
.ti -1c
.RI "float \fBsnowLight\fP"
.br
.ti -1c
.RI "float \fBwaterAnimeTimer\fP"
.br
.ti -1c
.RI "float \fBfloatTimer\fP"
.br
.ti -1c
.RI "float \fBdestBrightness\fP"
.br
.ti -1c
.RI "float \fBlightLimit\fP"
.br
.ti -1c
.RI "float \fBmodSublight1\fP"
.br
.ti -1c
.RI "float \fBmodSublight2\fP"
.br
.ti -1c
.RI "float \fBshadowStrength\fP"
.br
.ti -1c
.RI "float \fB_shadowStrength\fP"
.br
.ti -1c
.RI "float \fBfogBrightness\fP"
.br
.ti -1c
.RI "float \fBdefaultBlockHeight\fP"
.br
.ti -1c
.RI "float \fBsnowLimit\fP"
.br
.ti -1c
.RI "float \fBsnowColor\fP"
.br
.ti -1c
.RI "float \fBsnowColor2\fP"
.br
.ti -1c
.RI "float \fBnightRatio\fP"
.br
.ti -1c
.RI "\fBRenderParam\fP \fBparam\fP = new \fBRenderParam\fP()"
.br
.ti -1c
.RI "\fBMeshBatch\fP \fBbatch\fP"
.br
.ti -1c
.RI "Vector3 \fB_actorPos\fP"
.br
.ti -1c
.RI "Vector3 \fBfreePos\fP"
.br
.ti -1c
.RI "int \fBtile\fP"
.br
.ti -1c
.RI "int \fBfloorMatColor\fP"
.br
.ti -1c
.RI "int \fBheight\fP"
.br
.ti -1c
.RI "int \fBcurrentHeight\fP"
.br
.ti -1c
.RI "int \fBpcX\fP"
.br
.ti -1c
.RI "int \fBpcZ\fP"
.br
.ti -1c
.RI "int \fBfloorDir\fP"
.br
.ti -1c
.RI "bool \fBroof\fP"
.br
.ti -1c
.RI "bool \fBisSeen\fP"
.br
.ti -1c
.RI "bool \fBshowAllCards\fP"
.br
.ti -1c
.RI "bool \fBfogBounds\fP"
.br
.ti -1c
.RI "bool \fBsnowed\fP"
.br
.ti -1c
.RI "bool \fBisSnowCovered\fP"
.br
.ti -1c
.RI "bool \fBhighlightCells\fP"
.br
.ti -1c
.RI "bool \fBcinemaMode\fP"
.br
.ti -1c
.RI "bool \fBalwaysLowblock\fP"
.br
.ti -1c
.RI "bool \fBshowBorder\fP"
.br
.ti -1c
.RI "Vector3 \fBthingPos\fP"
.br
.ti -1c
.RI "Vector3 \fBorgPos\fP"
.br
.ti -1c
.RI "\fBCell\fP \fBcell\fP"
.br
.ti -1c
.RI "\fBCellDetail\fP \fBdetail\fP"
.br
.ti -1c
.RI "\fBSourceBlock\&.Row\fP \fBsourceBlock\fP"
.br
.ti -1c
.RI "\fBSourceFloor\&.Row\fP \fBsourceFloor\fP"
.br
.ti -1c
.RI "\fBSourceFloor\&.Row\fP \fBsourceBridge\fP"
.br
.ti -1c
.RI "\fBRoom\fP \fBcurrentRoom\fP"
.br
.ti -1c
.RI "\fBRoom\fP \fBlastRoom\fP"
.br
.ti -1c
.RI "\fBRoom\fP \fBroom\fP"
.br
.ti -1c
.RI "\fBLot\fP \fBcurrentLot\fP"
.br
.ti -1c
.RI "\fBSourceBlock\&.Row\fP \fB_sourceBlock\fP"
.br
.ti -1c
.RI "\fBTileType\fP \fBtileType\fP"
.br
.ti -1c
.RI "\fBSceneLightProfile\fP \fBlightSetting\fP"
.br
.in -1c

Properties inherited from \fBBaseTileMap\fP
.in +1c
.ti -1c
.RI "\fBPoint\fP \fBHitPoint\fP\fR [get]\fP"
.br
.in -1c

Properties inherited from \fBEMono\fP
.in +1c
.ti -1c
.RI "static \fBGame\fP \fBgame\fP\fR [get]\fP"
.br
.ti -1c
.RI "static bool \fBAdvMode\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBPlayer\fP \fBplayer\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBChara\fP \fBpc\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBUI\fP \fBui\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBMap\fP \fB_map\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBZone\fP \fB_zone\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranchOrHomeBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFaction\fP \fBHome\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBScene\fP \fBscene\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBBaseGameScreen\fP \fBscreen\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameSetting\fP \fBsetting\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameData\fP \fBgamedata\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBColorProfile\fP \fBColors\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBWorld\fP \fBworld\fP\fR [get]\fP"
.br
.ti -1c
.RI "static SoundManager \fBSound\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBsources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBeditorSources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBCoreDebug\fP \fBdebug\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB4\fP of file \fBTileMap\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
