.TH "TraitMap" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TraitMap
.SH SYNOPSIS
.br
.PP
.PP
Inherits Dictionary< int, Trait >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBAdd\fP (\fBCard\fP c)"
.br
.ti -1c
.RI "void \fBRemove\fP (\fBCard\fP c)"
.br
.ti -1c
.RI "\fBCard\fP \fBGetRandom\fP ()"
.br
.ti -1c
.RI "\fBCard\fP \fBGetRandom\fP (Func< \fBTrait\fP, bool > func)"
.br
.ti -1c
.RI "\fBCard\fP \fBGetRandomInstalled\fP ()"
.br
.ti -1c
.RI "bool \fBContains\fP (\fBCard\fP c)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB6\fP of file \fBTraitMap\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void TraitMap\&.Add (\fBCard\fP c)"

.PP
Definition at line \fB9\fP of file \fBTraitMap\&.cs\fP\&.
.SS "bool TraitMap\&.Contains (\fBCard\fP c)"

.PP
Definition at line \fB64\fP of file \fBTraitMap\&.cs\fP\&.
.SS "\fBCard\fP TraitMap\&.GetRandom ()"

.PP
Definition at line \fB21\fP of file \fBTraitMap\&.cs\fP\&.
.SS "\fBCard\fP TraitMap\&.GetRandom (Func< \fBTrait\fP, bool > func)"

.PP
Definition at line \fB32\fP of file \fBTraitMap\&.cs\fP\&.
.SS "\fBCard\fP TraitMap\&.GetRandomInstalled ()"

.PP
Definition at line \fB47\fP of file \fBTraitMap\&.cs\fP\&.
.SS "void TraitMap\&.Remove (\fBCard\fP c)"

.PP
Definition at line \fB15\fP of file \fBTraitMap\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
