.TH "TraitManager" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TraitManager
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBEClass\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBOnAddCard\fP (\fBCard\fP c)"
.br
.ti -1c
.RI "void \fBOnRemoveCard\fP (\fBCard\fP c)"
.br
.ti -1c
.RI "\fBThing\fP \fBGetRandomThing< T >\fP ()"
.br
.ti -1c
.RI "List< T > \fBList< T >\fP (Func< T, bool > func=null)"
.br
.ti -1c
.RI "\fBTraitSet\fP \fBGetTraitSet< T >\fP ()"
.br
.ti -1c
.RI "\fBTraitSet\fP \fBGetTraitSet\fP (Type t)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Dictionary< Type, \fBTraitSet\fP > \fBtypeMap\fP = new Dictionary<Type, \fBTraitSet\fP>()"
.br
.ti -1c
.RI "\fBTraitMap\fP \fBaltars\fP = new \fBTraitMap\fP()"
.br
.ti -1c
.RI "\fBTraitMap\fP \fBrestSpots\fP = new \fBTraitMap\fP()"
.br
.ti -1c
.RI "\fBTraitMap\fP \fBchairs\fP = new \fBTraitMap\fP()"
.br
.ti -1c
.RI "\fBTraitMap\fP \fBsuns\fP = new \fBTraitMap\fP()"
.br
.in -1c
.SS "Additional Inherited Members"


Static Public Member Functions inherited from \fBEClass\fP
.in +1c
.ti -1c
.RI "static int \fBrnd\fP (int a)"
.br
.ti -1c
.RI "static int \fBcurve\fP (int a, int start, int step, int rate=75)"
.br
.ti -1c
.RI "static int \fBrndHalf\fP (int a)"
.br
.ti -1c
.RI "static float \fBrndf\fP (float a)"
.br
.ti -1c
.RI "static int \fBrndSqrt\fP (int a)"
.br
.ti -1c
.RI "static void \fBWait\fP (float a, \fBCard\fP c)"
.br
.ti -1c
.RI "static void \fBWait\fP (float a, \fBPoint\fP p)"
.br
.ti -1c
.RI "static int \fBBigger\fP (int a, int b)"
.br
.ti -1c
.RI "static int \fBSmaller\fP (int a, int b)"
.br
.in -1c

Static Public Attributes inherited from \fBEClass\fP
.in +1c
.ti -1c
.RI "static \fBCore\fP \fBcore\fP"
.br
.in -1c

Properties inherited from \fBEClass\fP
.in +1c
.ti -1c
.RI "static \fBGame\fP \fBgame\fP\fR [get]\fP"
.br
.ti -1c
.RI "static bool \fBAdvMode\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBPlayer\fP \fBplayer\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBChara\fP \fBpc\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBUI\fP \fBui\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBMap\fP \fB_map\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBZone\fP \fB_zone\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranchOrHomeBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFaction\fP \fBHome\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFaction\fP \fBWilds\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBScene\fP \fBscene\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBBaseGameScreen\fP \fBscreen\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameSetting\fP \fBsetting\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameData\fP \fBgamedata\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBColorProfile\fP \fBColors\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBWorld\fP \fBworld\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBsources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBeditorSources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static SoundManager \fBSound\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBCoreDebug\fP \fBdebug\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB5\fP of file \fBTraitManager\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBThing\fP TraitManager\&.GetRandomThing< T > ()"

.PP
\fBType Constraints\fP
.TP
\fIT\fP : \fI\fBTrait\fP\fP
.PP
Definition at line \fB54\fP of file \fBTraitManager\&.cs\fP\&.
.SS "\fBTraitSet\fP TraitManager\&.GetTraitSet (Type t)"

.PP
Definition at line \fB98\fP of file \fBTraitManager\&.cs\fP\&.
.SS "\fBTraitSet\fP TraitManager\&.GetTraitSet< T > ()"

.PP
\fBType Constraints\fP
.TP
\fIT\fP : \fI\fBTrait\fP\fP
.PP
Definition at line \fB92\fP of file \fBTraitManager\&.cs\fP\&.
.SS "List< T > TraitManager\&.List< T > (Func< T, bool > func = \fRnull\fP)"

.PP
\fBType Constraints\fP
.TP
\fIT\fP : \fI\fBTrait\fP\fP
.PP
Definition at line \fB65\fP of file \fBTraitManager\&.cs\fP\&.
.SS "void TraitManager\&.OnAddCard (\fBCard\fP c)"

.PP
Definition at line \fB8\fP of file \fBTraitManager\&.cs\fP\&.
.SS "void TraitManager\&.OnRemoveCard (\fBCard\fP c)"

.PP
Definition at line \fB31\fP of file \fBTraitManager\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBTraitMap\fP TraitManager\&.altars = new \fBTraitMap\fP()"

.PP
Definition at line \fB107\fP of file \fBTraitManager\&.cs\fP\&.
.SS "\fBTraitMap\fP TraitManager\&.chairs = new \fBTraitMap\fP()"

.PP
Definition at line \fB113\fP of file \fBTraitManager\&.cs\fP\&.
.SS "\fBTraitMap\fP TraitManager\&.restSpots = new \fBTraitMap\fP()"

.PP
Definition at line \fB110\fP of file \fBTraitManager\&.cs\fP\&.
.SS "\fBTraitMap\fP TraitManager\&.suns = new \fBTraitMap\fP()"

.PP
Definition at line \fB116\fP of file \fBTraitManager\&.cs\fP\&.
.SS "Dictionary<Type, \fBTraitSet\fP> TraitManager\&.typeMap = new Dictionary<Type, \fBTraitSet\fP>()"

.PP
Definition at line \fB104\fP of file \fBTraitManager\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
