.TH "TraitBigSister" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TraitBigSister
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBTraitUniqueChara\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override string \fBGetDramaText\fP ()"
.br
.in -1c

Public Member Functions inherited from \fBTraitChara\fP
.in +1c
.ti -1c
.RI "virtual bool \fBIdleAct\fP ()"
.br
.ti -1c
.RI "override int \fBGetValue\fP ()"
.br
.ti -1c
.RI "int \fBGetAdvRank\fP ()"
.br
.ti -1c
.RI "string \fBGetAdvRankText\fP ()"
.br
.in -1c

Public Member Functions inherited from \fBTrait\fP
.in +1c
.ti -1c
.RI "string \fBGetParam\fP (int i, string def=null)"
.br
.ti -1c
.RI "int \fBGetParamInt\fP (int i, int def)"
.br
.ti -1c
.RI "virtual bool \fBContains\fP (\fBRecipeSource\fP r)"
.br
.ti -1c
.RI "virtual bool \fBCanStackTo\fP (\fBThing\fP to)"
.br
.ti -1c
.RI "virtual string \fBGetHoverText\fP ()"
.br
.ti -1c
.RI "virtual Action \fBGetHealAction\fP (\fBChara\fP c)"
.br
.ti -1c
.RI "virtual bool \fBCanBlend\fP (\fBThing\fP t)"
.br
.ti -1c
.RI "virtual void \fBOnBlend\fP (\fBThing\fP t, \fBChara\fP c)"
.br
.ti -1c
.RI "virtual int \fBGetActDuration\fP (\fBChara\fP c)"
.br
.ti -1c
.RI "virtual \fBSourceElement\&.Row\fP \fBGetRefElement\fP ()"
.br
.ti -1c
.RI "virtual Sprite \fBGetRefSprite\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnRenderExtra\fP (\fBRenderParam\fP p)"
.br
.ti -1c
.RI "virtual Emo2 \fBGetHeldEmo\fP (\fBChara\fP c)"
.br
.ti -1c
.RI "virtual void \fBSetOwner\fP (\fBCard\fP _owner)"
.br
.ti -1c
.RI "virtual bool \fBIdleUse\fP (\fBChara\fP c, int dist)"
.br
.ti -1c
.RI "virtual void \fBOnSetOwner\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnImportMap\fP ()"
.br
.ti -1c
.RI "virtual void \fBSetParams\fP (params string[] s)"
.br
.ti -1c
.RI "virtual void \fBOnCrafted\fP (\fBRecipe\fP recipe)"
.br
.ti -1c
.RI "virtual void \fBOnCreate\fP (int lv)"
.br
.ti -1c
.RI "virtual void \fBOnChangePlaceState\fP (PlaceState state)"
.br
.ti -1c
.RI "virtual void \fBOnAddedToZone\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnRemovedFromZone\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnSimulateHour\fP (\fBVirtualDate\fP date)"
.br
.ti -1c
.RI "virtual string \fBGetName\fP ()"
.br
.ti -1c
.RI "virtual void \fBSetName\fP (ref string s)"
.br
.ti -1c
.RI "virtual unsafe void \fBOnRenderTile\fP (\fBPoint\fP point, HitResult result, int dir)"
.br
.ti -1c
.RI "virtual int \fBCompareTo\fP (\fBCard\fP b)"
.br
.ti -1c
.RI "virtual bool \fBCanBuiltAt\fP (\fBPoint\fP p)"
.br
.ti -1c
.RI "virtual void \fBUpdate\fP ()"
.br
.ti -1c
.RI "\fBPoint\fP \fBGetPoint\fP ()"
.br
.ti -1c
.RI "\fBPoint\fP \fBGetRandomPoint\fP (Func< \fBPoint\fP, bool > func=null)"
.br
.ti -1c
.RI "virtual List< \fBPoint\fP > \fBListPoints\fP (\fBPoint\fP center=null, bool onlyPassable=true)"
.br
.ti -1c
.RI "virtual \fBRecipe\fP \fBGetRecipe\fP ()"
.br
.ti -1c
.RI "virtual \fBRecipe\fP \fBGetBuildModeRecipe\fP ()"
.br
.ti -1c
.RI "virtual bool \fBCanCook\fP (\fBCard\fP c)"
.br
.ti -1c
.RI "void \fBCookProgress\fP ()"
.br
.ti -1c
.RI "virtual bool \fBCanOffer\fP (\fBCard\fP tg)"
.br
.ti -1c
.RI "void \fBOfferProcess\fP (\fBChara\fP cc)"
.br
.ti -1c
.RI "void \fBOffer\fP (\fBChara\fP cc)"
.br
.ti -1c
.RI "virtual bool \fBTryProgress\fP (\fBAIProgress\fP p)"
.br
.ti -1c
.RI "virtual LockOpenState \fBTryOpenLock\fP (\fBChara\fP cc, bool msgFail=true)"
.br
.ti -1c
.RI "virtual void \fBWriteNote\fP (UINote n, bool identified)"
.br
.ti -1c
.RI "int \fBGetSortVal\fP (UIList\&.SortMode m)"
.br
.ti -1c
.RI "virtual \fBHotItem\fP \fBGetHotItem\fP ()"
.br
.ti -1c
.RI "virtual bool \fBCanRead\fP (\fBChara\fP c)"
.br
.ti -1c
.RI "virtual void \fBOnRead\fP (\fBChara\fP c)"
.br
.ti -1c
.RI "virtual bool \fBCanEat\fP (\fBChara\fP c)"
.br
.ti -1c
.RI "virtual void \fBOnEat\fP (\fBChara\fP c)"
.br
.ti -1c
.RI "virtual bool \fBCanDrink\fP (\fBChara\fP c)"
.br
.ti -1c
.RI "virtual void \fBOnDrink\fP (\fBChara\fP c)"
.br
.ti -1c
.RI "virtual void \fBOnThrowGround\fP (\fBChara\fP c, \fBPoint\fP p)"
.br
.ti -1c
.RI "virtual bool \fBCanUse\fP (\fBChara\fP c)"
.br
.ti -1c
.RI "virtual bool \fBCanUse\fP (\fBChara\fP c, \fBCard\fP tg)"
.br
.ti -1c
.RI "virtual bool \fBCanUse\fP (\fBChara\fP c, \fBPoint\fP p)"
.br
.ti -1c
.RI "virtual bool \fBOnUse\fP (\fBChara\fP c)"
.br
.ti -1c
.RI "virtual bool \fBOnUse\fP (\fBChara\fP c, \fBCard\fP tg)"
.br
.ti -1c
.RI "virtual bool \fBOnUse\fP (\fBChara\fP c, \fBPoint\fP p)"
.br
.ti -1c
.RI "virtual void \fBTrySetAct\fP (\fBActPlan\fP p)"
.br
.ti -1c
.RI "virtual void \fBTrySetHeldAct\fP (\fBActPlan\fP p)"
.br
.ti -1c
.RI "virtual void \fBOnHeld\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnTickHeld\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnSetCurrentItem\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnUnsetCurrentItem\fP ()"
.br
.ti -1c
.RI "virtual bool \fBOnChildDecay\fP (\fBCard\fP c)"
.br
.ti -1c
.RI "virtual bool \fBCanChildDecay\fP (\fBCard\fP c)"
.br
.ti -1c
.RI "virtual void \fBOnSetCardGrid\fP (\fBButtonGrid\fP b)"
.br
.ti -1c
.RI "virtual void \fBOnStepped\fP (\fBChara\fP c)"
.br
.ti -1c
.RI "virtual void \fBOnSteppedOut\fP (\fBChara\fP c)"
.br
.ti -1c
.RI "virtual void \fBOnOpenDoor\fP (\fBChara\fP c)"
.br
.ti -1c
.RI "void \fBInstall\fP (bool byPlayer)"
.br
.ti -1c
.RI "void \fBUninstall\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnInstall\fP (bool byPlayer)"
.br
.ti -1c
.RI "virtual void \fBOnUninstall\fP ()"
.br
.ti -1c
.RI "virtual void \fBTryToggle\fP ()"
.br
.ti -1c
.RI "virtual void \fBToggle\fP (bool on, bool silent=false)"
.br
.ti -1c
.RI "virtual void \fBOnToggle\fP ()"
.br
.ti -1c
.RI "virtual void \fBTrySetToggleAct\fP (\fBActPlan\fP p)"
.br
.ti -1c
.RI "bool \fBIsFuelEnough\fP (int num=1, List< \fBThing\fP > excludes=null, bool tryRefuel=true)"
.br
.ti -1c
.RI "bool \fBIsFuel\fP (string s)"
.br
.ti -1c
.RI "bool \fBIsFuel\fP (\fBThing\fP t)"
.br
.ti -1c
.RI "int \fBGetFuelValue\fP (\fBThing\fP t)"
.br
.ti -1c
.RI "int \fBGetFuelValue\fP (string id)"
.br
.ti -1c
.RI "void \fBRefuel\fP (\fBThing\fP t)"
.br
.ti -1c
.RI "void \fBTryRefuel\fP (int dest, List< \fBThing\fP > excludes)"
.br
.ti -1c
.RI "virtual void \fBOnEnterScreen\fP ()"
.br
.ti -1c
.RI "virtual void \fBRefreshRenderer\fP ()"
.br
.ti -1c
.RI "virtual void \fBSetMainText\fP (UIText t, bool hotitem)"
.br
.ti -1c
.RI "virtual bool \fBCanCopy\fP (\fBThing\fP t)"
.br
.ti -1c
.RI "string \fBGetTextRestock\fP (string lang, bool pet)"
.br
.ti -1c
.RI "Emo2 \fBGetRestockedIcon\fP ()"
.br
.ti -1c
.RI "\fBThing\fP \fBFindShopChest\fP ()"
.br
.ti -1c
.RI "void \fBOnBarter\fP ()"
.br
.ti -1c
.RI "\fBThing\fP \fBCreateStock\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override ShopType \fBShopType\fP\fR [get]\fP"
.br
.ti -1c
.RI "override CurrencyType \fBCurrencyType\fP\fR [get]\fP"
.br
.ti -1c
.RI "override bool \fBCanInvite\fP\fR [get]\fP"
.br
.in -1c

Properties inherited from \fBTraitUniqueChara\fP
.in +1c
.ti -1c
.RI "override bool \fBIsUnique\fP\fR [get]\fP"
.br
.in -1c

Properties inherited from \fBTraitChara\fP
.in +1c
.ti -1c
.RI "new \fBChara\fP \fBowner\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual AI_Idle\&.Behaviour \fBIdleBehaviour\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBCanAutoRevive\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBIsCitizen\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBIsUnique\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBCanRevive\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBCanGuide\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBCanIdentify\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBCanPicklock\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBCanInvest\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual string \fBIDTrainer\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBCanJoinParty\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBCanJoinPartyResident\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBCanSellStolenGoods\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBCanBeBanished\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBCanInvite\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBCanInvestTown\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBCanSellPlan\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBCanHeal\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBCanWhore\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBCanServeFood\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBHaveNews\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBCanBout\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBUseGlobalGoal\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBShowAdvRank\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBUseRandomAbility\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual TraitChara\&.Adv_Type \fBAdvType\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBEnableTone\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBCanBeTamed\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBCanBePushed\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBCanGiveRandomQuest\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBUseRandomAlias\fP\fR [get]\fP"
.br
.ti -1c
.RI "override string \fBIDInvStyle\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual string \fBIDRumor\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual string \fBIdAmbience\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBCanFish\fP\fR [get]\fP"
.br
.in -1c

Properties inherited from \fBTrait\fP
.in +1c
.ti -1c
.RI "string[] \fBParams\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual byte \fBWeightMod\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual string \fBName\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual \fBTileType\fP \fBtileType\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual RefCardName \fBRefCardName\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBIsBlockPath\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBIsBlockSight\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBIsDoor\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBIsOpenSight\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBIsOpenPath\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBIsFloating\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBIsGround\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBInvertHeldSprite\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBIsChangeFloorHeight\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBShouldRefreshTile\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBShouldTryRefreshRoom\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBCanHarvest\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual int \fBradius\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBCanUseRoomRadius\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual int \fBGuidePriotiy\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual int \fBElectricity\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBIgnoreLastStackHeight\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual int \fBDecay\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual int \fBDecaySpeed\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual int \fBDecaySpeedChild\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBIsFridge\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual int \fBDefaultStock\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBHoldAsDefaultInteraction\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual int \fBCraftNum\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBShowOrbit\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBHaveUpdate\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBIsSpot\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBIsFactory\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBCanAutofire\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBCanName\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBCanPutAway\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBCanStack\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBCanCopyInBlueprint\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBCanBeAttacked\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBCanExtendBuild\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual string \fBlangNote\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual string \fBIDInvStyle\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual string \fBIDActorEx\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBMaskOnBuild\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBShowContextOnPick\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBIsThrowMainAction\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBLevelAsQuality\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBUseDummyTile\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBRequireFullStackCheck\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual InvGridSize \fBInvGridSize\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBIsContainer\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBCanOpenContainer\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBIsSpecialContainer\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual ContainerType \fBContainerType\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual ThrowType \fBThrowType\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual EffectDead \fBEffectDead\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBIsHomeItem\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBIsAltar\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBIsRestSpot\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBCanBeMasked\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBIsBlendBase\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBCanBeOnlyBuiltInHome\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBCanBuildInTown\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBCanBeHeld\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBCanBeStolen\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBCanOnlyCarry\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBCanBeDestroyed\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBCanBeHallucinated\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBCanSearchContents\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBCanBeDropped\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual string \fBReqHarvest\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBCanBeDisassembled\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBCanBeShipped\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBHasCharges\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBShowCharges\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBShowChildrenNumber\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBShowAsTool\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBCanBeHeldAsFurniture\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBHideInAdv\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBNoHeldDir\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBAlwaysHideOnLowWall\fP\fR [get]\fP"
.br
.ti -1c
.RI "bool \fBExistsOnMap\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBRenderExtra\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual float \fBDropChance\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual string \fBIdNoRestock\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual int \fBIdleUseChance\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual string \fBRecipeCat\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBIsTool\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual string \fBLangUse\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBIsOn\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBIsAnimeOn\fP\fR [get]\fP"
.br
.ti -1c
.RI "bool \fBIsToggle\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBAutoToggle\fP\fR [get]\fP"
.br
.ti -1c
.RI "bool \fBIsLighting\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBIsLightOn\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBIsNightOnlyLight\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual Trait\&.TileMode \fBtileMode\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBUseAltTiles\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBUseLowblock\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBUseExtra\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBUseLightColor\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual ? Color \fBColorExtra\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual int \fBMaxFuel\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual int \fBFuelCost\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBShowFuelWindow\fP\fR [get]\fP"
.br
.ti -1c
.RI "bool \fBIsRequireFuel\fP\fR [get]\fP"
.br
.ti -1c
.RI "string \fBIdToggleExtra\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual ToggleType \fBToggleType\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual int \fBShopLv\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual Trait\&.CopyShopType \fBCopyShop\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual int \fBNumCopyItem\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual ShopType \fBShopType\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual CurrencyType \fBCurrencyType\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual PriceType \fBPriceType\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBAllowSell\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual int \fBCostRerollShop\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBAllowCriminal\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual int \fBRestockDay\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual SlaverType \fBSlaverType\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual string \fBLangBarter\fP\fR [get]\fP"
.br
.ti -1c
.RI "string \fBTextNextRestock\fP\fR [get]\fP"
.br
.ti -1c
.RI "string \fBTextNextRestockPet\fP\fR [get]\fP"
.br
.in -1c

Properties inherited from \fBEClass\fP
.in +1c
.ti -1c
.RI "static \fBGame\fP \fBgame\fP\fR [get]\fP"
.br
.ti -1c
.RI "static bool \fBAdvMode\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBPlayer\fP \fBplayer\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBChara\fP \fBpc\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBUI\fP \fBui\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBMap\fP \fB_map\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBZone\fP \fB_zone\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranchOrHomeBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFaction\fP \fBHome\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFaction\fP \fBWilds\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBScene\fP \fBscene\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBBaseGameScreen\fP \fBscreen\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameSetting\fP \fBsetting\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameData\fP \fBgamedata\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBColorProfile\fP \fBColors\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBWorld\fP \fBworld\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBsources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBeditorSources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static SoundManager \fBSound\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBCoreDebug\fP \fBdebug\fP\fR [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Public Types inherited from \fBTraitChara\fP
.in +1c
.ti -1c
.RI "enum \fBAdv_Type\fP { \fBNone\fP, \fBAdv\fP, \fBAdv_Fairy\fP, \fBAdv_Backer\fP }"
.br
.in -1c

Public Types inherited from \fBTrait\fP
.in +1c
.ti -1c
.RI "enum \fBTileMode\fP { \fBDefault\fP, \fBDoor\fP, \fBIllumination\fP, \fBDefaultNoAnime\fP }"
.br
.ti -1c
.RI "enum \fBCopyShopType\fP { \fBNone\fP, \fBItem\fP, \fBSpellbook\fP }"
.br
.in -1c

Static Public Member Functions inherited from \fBEClass\fP
.in +1c
.ti -1c
.RI "static int \fBrnd\fP (int a)"
.br
.ti -1c
.RI "static int \fBcurve\fP (int a, int start, int step, int rate=75)"
.br
.ti -1c
.RI "static int \fBrndHalf\fP (int a)"
.br
.ti -1c
.RI "static float \fBrndf\fP (float a)"
.br
.ti -1c
.RI "static int \fBrndSqrt\fP (int a)"
.br
.ti -1c
.RI "static void \fBWait\fP (float a, \fBCard\fP c)"
.br
.ti -1c
.RI "static void \fBWait\fP (float a, \fBPoint\fP p)"
.br
.ti -1c
.RI "static int \fBBigger\fP (int a, int b)"
.br
.ti -1c
.RI "static int \fBSmaller\fP (int a, int b)"
.br
.in -1c

Public Attributes inherited from \fBTrait\fP
.in +1c
.ti -1c
.RI "\fBCard\fP \fBowner\fP"
.br
.in -1c

Static Public Attributes inherited from \fBTraitChara\fP
.in +1c
.ti -1c
.RI "static string[] \fBListRank\fP"
.br
.in -1c

Static Public Attributes inherited from \fBTrait\fP
.in +1c
.ti -1c
.RI "static \fBTraitSelfFactory\fP \fBSelfFactory\fP = new \fBTraitSelfFactory\fP()"
.br
.in -1c

Static Public Attributes inherited from \fBEClass\fP
.in +1c
.ti -1c
.RI "static \fBCore\fP \fBcore\fP"
.br
.in -1c

Static Protected Attributes inherited from \fBTrait\fP
.in +1c
.ti -1c
.RI "static List< \fBPoint\fP > \fBlistRadiusPoints\fP = new List<\fBPoint\fP>()"
.br
.in -1c

Static Package Functions inherited from \fBTrait\fP
.SH "Detailed Description"
.PP 
Definition at line \fB4\fP of file \fBTraitBigSister\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override string TraitBigSister\&.GetDramaText ()\fR [virtual]\fP"

.PP
Reimplemented from \fBTraitChara\fP\&.
.PP
Definition at line \fB7\fP of file \fBTraitBigSister\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "override bool TraitBigSister\&.CanInvite\fR [get]\fP"

.PP
Definition at line \fB34\fP of file \fBTraitBigSister\&.cs\fP\&.
.SS "override CurrencyType TraitBigSister\&.CurrencyType\fR [get]\fP"

.PP
Definition at line \fB24\fP of file \fBTraitBigSister\&.cs\fP\&.
.SS "override ShopType TraitBigSister\&.ShopType\fR [get]\fP"

.PP
Definition at line \fB14\fP of file \fBTraitBigSister\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
