.TH "TraitHouseBoard.Data" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TraitHouseBoard.Data
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBidRoofStyle\fP"
.br
.ti -1c
.RI "int \fBheight\fP"
.br
.ti -1c
.RI "int \fBidBGM\fP"
.br
.ti -1c
.RI "int \fBheightFix\fP"
.br
.ti -1c
.RI "int \fBidRoofTile\fP"
.br
.ti -1c
.RI "int \fBidBlock\fP = 30"
.br
.ti -1c
.RI "int \fBidRamp\fP"
.br
.ti -1c
.RI "int \fBidDeco\fP"
.br
.ti -1c
.RI "int \fBidDeco2\fP"
.br
.ti -1c
.RI "int \fBdecoFix\fP"
.br
.ti -1c
.RI "int \fBdecoFix2\fP"
.br
.ti -1c
.RI "int \fBcolRoof\fP"
.br
.ti -1c
.RI "int \fBcolBlock\fP"
.br
.ti -1c
.RI "int \fBcolDeco\fP"
.br
.ti -1c
.RI "int \fBcolDeco2\fP"
.br
.ti -1c
.RI "bool \fBreverse\fP"
.br
.ti -1c
.RI "bool \fBsnow\fP"
.br
.ti -1c
.RI "bool \fBaltRoof\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB138\fP of file \fBTraitHouseBoard\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "bool TraitHouseBoard\&.Data\&.altRoof"

.PP
Definition at line \fB210\fP of file \fBTraitHouseBoard\&.cs\fP\&.
.SS "int TraitHouseBoard\&.Data\&.colBlock"

.PP
Definition at line \fB190\fP of file \fBTraitHouseBoard\&.cs\fP\&.
.SS "int TraitHouseBoard\&.Data\&.colDeco"

.PP
Definition at line \fB194\fP of file \fBTraitHouseBoard\&.cs\fP\&.
.SS "int TraitHouseBoard\&.Data\&.colDeco2"

.PP
Definition at line \fB198\fP of file \fBTraitHouseBoard\&.cs\fP\&.
.SS "int TraitHouseBoard\&.Data\&.colRoof"

.PP
Definition at line \fB186\fP of file \fBTraitHouseBoard\&.cs\fP\&.
.SS "int TraitHouseBoard\&.Data\&.decoFix"

.PP
Definition at line \fB178\fP of file \fBTraitHouseBoard\&.cs\fP\&.
.SS "int TraitHouseBoard\&.Data\&.decoFix2"

.PP
Definition at line \fB182\fP of file \fBTraitHouseBoard\&.cs\fP\&.
.SS "int TraitHouseBoard\&.Data\&.height"

.PP
Definition at line \fB146\fP of file \fBTraitHouseBoard\&.cs\fP\&.
.SS "int TraitHouseBoard\&.Data\&.heightFix"

.PP
Definition at line \fB154\fP of file \fBTraitHouseBoard\&.cs\fP\&.
.SS "int TraitHouseBoard\&.Data\&.idBGM"

.PP
Definition at line \fB150\fP of file \fBTraitHouseBoard\&.cs\fP\&.
.SS "int TraitHouseBoard\&.Data\&.idBlock = 30"

.PP
Definition at line \fB162\fP of file \fBTraitHouseBoard\&.cs\fP\&.
.SS "int TraitHouseBoard\&.Data\&.idDeco"

.PP
Definition at line \fB170\fP of file \fBTraitHouseBoard\&.cs\fP\&.
.SS "int TraitHouseBoard\&.Data\&.idDeco2"

.PP
Definition at line \fB174\fP of file \fBTraitHouseBoard\&.cs\fP\&.
.SS "int TraitHouseBoard\&.Data\&.idRamp"

.PP
Definition at line \fB166\fP of file \fBTraitHouseBoard\&.cs\fP\&.
.SS "int TraitHouseBoard\&.Data\&.idRoofStyle"

.PP
Definition at line \fB142\fP of file \fBTraitHouseBoard\&.cs\fP\&.
.SS "int TraitHouseBoard\&.Data\&.idRoofTile"

.PP
Definition at line \fB158\fP of file \fBTraitHouseBoard\&.cs\fP\&.
.SS "bool TraitHouseBoard\&.Data\&.reverse"

.PP
Definition at line \fB202\fP of file \fBTraitHouseBoard\&.cs\fP\&.
.SS "bool TraitHouseBoard\&.Data\&.snow"

.PP
Definition at line \fB206\fP of file \fBTraitHouseBoard\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
