.TH "TraitSet" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TraitSet
.SH SYNOPSIS
.br
.PP
.PP
Inherits Dictionary< int, Card >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBAdd\fP (\fBCard\fP c)"
.br
.ti -1c
.RI "void \fBRemove\fP (\fBCard\fP c)"
.br
.ti -1c
.RI "\fBTrait\fP \fBGetRandom\fP ()"
.br
.ti -1c
.RI "\fBTrait\fP \fBGetRandom\fP (Func< \fBCard\fP, bool > func)"
.br
.ti -1c
.RI "bool \fBContains\fP (\fBCard\fP c)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB6\fP of file \fBTraitSet\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void TraitSet\&.Add (\fBCard\fP c)"

.PP
Definition at line \fB9\fP of file \fBTraitSet\&.cs\fP\&.
.SS "bool TraitSet\&.Contains (\fBCard\fP c)"

.PP
Definition at line \fB47\fP of file \fBTraitSet\&.cs\fP\&.
.SS "\fBTrait\fP TraitSet\&.GetRandom ()"

.PP
Definition at line \fB21\fP of file \fBTraitSet\&.cs\fP\&.
.SS "\fBTrait\fP TraitSet\&.GetRandom (Func< \fBCard\fP, bool > func)"

.PP
Definition at line \fB32\fP of file \fBTraitSet\&.cs\fP\&.
.SS "void TraitSet\&.Remove (\fBCard\fP c)"

.PP
Definition at line \fB15\fP of file \fBTraitSet\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
