.TH "TransAnimeData" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TransAnimeData
.SH SYNOPSIS
.br
.PP
.PP
Inherits ScriptableObject\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBAwake\fP ()"
.br
.ti -1c
.RI "void \fBGenerate\fP ()"
.br
.ti -1c
.RI "Vector3 \fBGetVector\fP (int frame)"
.br
.ti -1c
.RI "void \fBSwapXY\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBframes\fP"
.br
.ti -1c
.RI "int \fBcount\fP = 1"
.br
.ti -1c
.RI "float \fBinterval\fP"
.br
.ti -1c
.RI "float \fBmtp\fP"
.br
.ti -1c
.RI "float \fBrandomMtp\fP"
.br
.ti -1c
.RI "float \fBrandomDelay\fP"
.br
.ti -1c
.RI "bool \fBloop\fP"
.br
.ti -1c
.RI "bool \fBgenerate\fP"
.br
.ti -1c
.RI "bool \fBdirectional\fP"
.br
.ti -1c
.RI "bool \fBrealtimeGenerate\fP"
.br
.ti -1c
.RI "bool \fBrandomFlipX\fP"
.br
.ti -1c
.RI "Vector3 \fBoffset\fP"
.br
.ti -1c
.RI "Vector3[] \fBvectors\fP"
.br
.ti -1c
.RI "AnimationCurve \fBcurveX\fP"
.br
.ti -1c
.RI "AnimationCurve \fBcurveY\fP"
.br
.ti -1c
.RI "AnimationCurve \fBcurveZ\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBTotalFrame\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB5\fP of file \fBTransAnimeData\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void TransAnimeData\&.Awake ()"

.PP
Definition at line \fB18\fP of file \fBTransAnimeData\&.cs\fP\&.
.SS "void TransAnimeData\&.Generate ()"

.PP
Definition at line \fB27\fP of file \fBTransAnimeData\&.cs\fP\&.
.SS "Vector3 TransAnimeData\&.GetVector (int frame)"

.PP
Definition at line \fB42\fP of file \fBTransAnimeData\&.cs\fP\&.
.SS "void TransAnimeData\&.SwapXY ()"

.PP
Definition at line \fB57\fP of file \fBTransAnimeData\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int TransAnimeData\&.count = 1"

.PP
Definition at line \fB68\fP of file \fBTransAnimeData\&.cs\fP\&.
.SS "AnimationCurve TransAnimeData\&.curveX"

.PP
Definition at line \fB104\fP of file \fBTransAnimeData\&.cs\fP\&.
.SS "AnimationCurve TransAnimeData\&.curveY"

.PP
Definition at line \fB107\fP of file \fBTransAnimeData\&.cs\fP\&.
.SS "AnimationCurve TransAnimeData\&.curveZ"

.PP
Definition at line \fB110\fP of file \fBTransAnimeData\&.cs\fP\&.
.SS "bool TransAnimeData\&.directional"

.PP
Definition at line \fB89\fP of file \fBTransAnimeData\&.cs\fP\&.
.SS "int TransAnimeData\&.frames"

.PP
Definition at line \fB65\fP of file \fBTransAnimeData\&.cs\fP\&.
.SS "bool TransAnimeData\&.generate"

.PP
Definition at line \fB86\fP of file \fBTransAnimeData\&.cs\fP\&.
.SS "float TransAnimeData\&.interval"

.PP
Definition at line \fB71\fP of file \fBTransAnimeData\&.cs\fP\&.
.SS "bool TransAnimeData\&.loop"

.PP
Definition at line \fB83\fP of file \fBTransAnimeData\&.cs\fP\&.
.SS "float TransAnimeData\&.mtp"

.PP
Definition at line \fB74\fP of file \fBTransAnimeData\&.cs\fP\&.
.SS "Vector3 TransAnimeData\&.offset"

.PP
Definition at line \fB98\fP of file \fBTransAnimeData\&.cs\fP\&.
.SS "float TransAnimeData\&.randomDelay"

.PP
Definition at line \fB80\fP of file \fBTransAnimeData\&.cs\fP\&.
.SS "bool TransAnimeData\&.randomFlipX"

.PP
Definition at line \fB95\fP of file \fBTransAnimeData\&.cs\fP\&.
.SS "float TransAnimeData\&.randomMtp"

.PP
Definition at line \fB77\fP of file \fBTransAnimeData\&.cs\fP\&.
.SS "bool TransAnimeData\&.realtimeGenerate"

.PP
Definition at line \fB92\fP of file \fBTransAnimeData\&.cs\fP\&.
.SS "Vector3 [] TransAnimeData\&.vectors"

.PP
Definition at line \fB101\fP of file \fBTransAnimeData\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "int TransAnimeData\&.TotalFrame\fR [get]\fP"

.PP
Definition at line \fB9\fP of file \fBTransAnimeData\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
