.TH "TransAnime" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TransAnime
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTransAnime\fP \fBInit\fP ()"
.br
.ti -1c
.RI "bool \fBUpdate\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Vector3 \fBv\fP"
.br
.ti -1c
.RI "\fBPoint\fP \fBpoint\fP"
.br
.ti -1c
.RI "\fBCardRenderer\fP \fBrenderer\fP"
.br
.ti -1c
.RI "\fBTransAnimeData\fP \fBdata\fP"
.br
.ti -1c
.RI "int \fBframe\fP"
.br
.ti -1c
.RI "int \fBstartFrame\fP"
.br
.ti -1c
.RI "float \fBtimer\fP"
.br
.ti -1c
.RI "Vector3 \fBdest\fP"
.br
.ti -1c
.RI "bool \fBanimeBlock\fP"
.br
.ti -1c
.RI "bool \fBflipX\fP"
.br
.ti -1c
.RI "bool \fBdrawBlock\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB5\fP of file \fBTransAnime\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBTransAnime\fP TransAnime\&.Init ()"

.PP
Definition at line \fB8\fP of file \fBTransAnime\&.cs\fP\&.
.SS "bool TransAnime\&.Update ()"

.PP
Definition at line \fB22\fP of file \fBTransAnime\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "bool TransAnime\&.animeBlock"

.PP
Definition at line \fB96\fP of file \fBTransAnime\&.cs\fP\&.
.SS "\fBTransAnimeData\fP TransAnime\&.data"

.PP
Definition at line \fB81\fP of file \fBTransAnime\&.cs\fP\&.
.SS "Vector3 TransAnime\&.dest"

.PP
Definition at line \fB93\fP of file \fBTransAnime\&.cs\fP\&.
.SS "bool TransAnime\&.drawBlock"

.PP
Definition at line \fB102\fP of file \fBTransAnime\&.cs\fP\&.
.SS "bool TransAnime\&.flipX"

.PP
Definition at line \fB99\fP of file \fBTransAnime\&.cs\fP\&.
.SS "int TransAnime\&.frame"

.PP
Definition at line \fB84\fP of file \fBTransAnime\&.cs\fP\&.
.SS "\fBPoint\fP TransAnime\&.point"

.PP
Definition at line \fB75\fP of file \fBTransAnime\&.cs\fP\&.
.SS "\fBCardRenderer\fP TransAnime\&.renderer"

.PP
Definition at line \fB78\fP of file \fBTransAnime\&.cs\fP\&.
.SS "int TransAnime\&.startFrame"

.PP
Definition at line \fB87\fP of file \fBTransAnime\&.cs\fP\&.
.SS "float TransAnime\&.timer"

.PP
Definition at line \fB90\fP of file \fBTransAnime\&.cs\fP\&.
.SS "Vector3 TransAnime\&.v"

.PP
Definition at line \fB72\fP of file \fBTransAnime\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
