.TH "TwoDLaserPack.LineBasedLaser" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TwoDLaserPack.LineBasedLaser
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetLaserState\fP (bool enabledStatus)"
.br
.ti -1c
.RI "delegate void \fBLaserHitTriggerHandler\fP (RaycastHit2D hitInfo)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "LineRenderer \fBlaserLineRendererArc\fP"
.br
.ti -1c
.RI "LineRenderer \fBlaserLineRenderer\fP"
.br
.ti -1c
.RI "int \fBlaserArcSegments\fP = 20"
.br
.ti -1c
.RI "bool \fBlaserActive\fP"
.br
.ti -1c
.RI "bool \fBignoreCollisions\fP"
.br
.ti -1c
.RI "GameObject \fBtargetGo\fP"
.br
.ti -1c
.RI "float \fBlaserTexOffsetSpeed\fP = 1f"
.br
.ti -1c
.RI "ParticleSystem \fBhitSparkParticleSystem\fP"
.br
.ti -1c
.RI "float \fBlaserArcMaxYDown\fP"
.br
.ti -1c
.RI "float \fBlaserArcMaxYUp\fP"
.br
.ti -1c
.RI "float \fBmaxLaserRaycastDistance\fP = 20f"
.br
.ti -1c
.RI "bool \fBlaserRotationEnabled\fP"
.br
.ti -1c
.RI "bool \fBlerpLaserRotation\fP"
.br
.ti -1c
.RI "float \fBturningRate\fP = 3f"
.br
.ti -1c
.RI "float \fBcollisionTriggerInterval\fP = 0\&.25f"
.br
.ti -1c
.RI "LayerMask \fBmask\fP"
.br
.ti -1c
.RI "string \fBsortLayer\fP = 'Default'"
.br
.ti -1c
.RI "int \fBsortOrder\fP"
.br
.ti -1c
.RI "bool \fBuseArc\fP"
.br
.in -1c
.SS "Events"

.in +1c
.ti -1c
.RI "LineBasedLaser\&.LaserHitTriggerHandler \fBOnLaserHitTriggered\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB8\fP of file \fBLineBasedLaser\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void TwoDLaserPack\&.LineBasedLaser\&.SetLaserState (bool enabledStatus)"

.PP
Definition at line \fB115\fP of file \fBLineBasedLaser\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "float TwoDLaserPack\&.LineBasedLaser\&.collisionTriggerInterval = 0\&.25f"

.PP
Definition at line \fB251\fP of file \fBLineBasedLaser\&.cs\fP\&.
.SS "ParticleSystem TwoDLaserPack\&.LineBasedLaser\&.hitSparkParticleSystem"

.PP
Definition at line \fB230\fP of file \fBLineBasedLaser\&.cs\fP\&.
.SS "bool TwoDLaserPack\&.LineBasedLaser\&.ignoreCollisions"

.PP
Definition at line \fB221\fP of file \fBLineBasedLaser\&.cs\fP\&.
.SS "bool TwoDLaserPack\&.LineBasedLaser\&.laserActive"

.PP
Definition at line \fB218\fP of file \fBLineBasedLaser\&.cs\fP\&.
.SS "float TwoDLaserPack\&.LineBasedLaser\&.laserArcMaxYDown"

.PP
Definition at line \fB233\fP of file \fBLineBasedLaser\&.cs\fP\&.
.SS "float TwoDLaserPack\&.LineBasedLaser\&.laserArcMaxYUp"

.PP
Definition at line \fB236\fP of file \fBLineBasedLaser\&.cs\fP\&.
.SS "int TwoDLaserPack\&.LineBasedLaser\&.laserArcSegments = 20"

.PP
Definition at line \fB215\fP of file \fBLineBasedLaser\&.cs\fP\&.
.SS "LineRenderer TwoDLaserPack\&.LineBasedLaser\&.laserLineRenderer"

.PP
Definition at line \fB212\fP of file \fBLineBasedLaser\&.cs\fP\&.
.SS "LineRenderer TwoDLaserPack\&.LineBasedLaser\&.laserLineRendererArc"

.PP
Definition at line \fB209\fP of file \fBLineBasedLaser\&.cs\fP\&.
.SS "bool TwoDLaserPack\&.LineBasedLaser\&.laserRotationEnabled"

.PP
Definition at line \fB242\fP of file \fBLineBasedLaser\&.cs\fP\&.
.SS "float TwoDLaserPack\&.LineBasedLaser\&.laserTexOffsetSpeed = 1f"

.PP
Definition at line \fB227\fP of file \fBLineBasedLaser\&.cs\fP\&.
.SS "bool TwoDLaserPack\&.LineBasedLaser\&.lerpLaserRotation"

.PP
Definition at line \fB245\fP of file \fBLineBasedLaser\&.cs\fP\&.
.SS "LayerMask TwoDLaserPack\&.LineBasedLaser\&.mask"

.PP
Definition at line \fB254\fP of file \fBLineBasedLaser\&.cs\fP\&.
.SS "float TwoDLaserPack\&.LineBasedLaser\&.maxLaserRaycastDistance = 20f"

.PP
Definition at line \fB239\fP of file \fBLineBasedLaser\&.cs\fP\&.
.SS "string TwoDLaserPack\&.LineBasedLaser\&.sortLayer = 'Default'"

.PP
Definition at line \fB257\fP of file \fBLineBasedLaser\&.cs\fP\&.
.SS "int TwoDLaserPack\&.LineBasedLaser\&.sortOrder"

.PP
Definition at line \fB260\fP of file \fBLineBasedLaser\&.cs\fP\&.
.SS "GameObject TwoDLaserPack\&.LineBasedLaser\&.targetGo"

.PP
Definition at line \fB224\fP of file \fBLineBasedLaser\&.cs\fP\&.
.SS "float TwoDLaserPack\&.LineBasedLaser\&.turningRate = 3f"

.PP
Definition at line \fB248\fP of file \fBLineBasedLaser\&.cs\fP\&.
.SS "bool TwoDLaserPack\&.LineBasedLaser\&.useArc"

.PP
Definition at line \fB263\fP of file \fBLineBasedLaser\&.cs\fP\&.
.SH "Event Documentation"
.PP 
.SS "LineBasedLaser\&.LaserHitTriggerHandler TwoDLaserPack\&.LineBasedLaser\&.OnLaserHitTriggered"

.PP
Definition at line \fB13\fP of file \fBLineBasedLaser\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
