.TH "UD_String_EffectData" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UD_String_EffectData
.SH SYNOPSIS
.br
.PP
.PP
Inherits UDictionary< string, GameSetting\&.EffectData >\&.
.SH "Detailed Description"
.PP 
Definition at line \fB5\fP of file \fBUD_String_EffectData\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
