.TH "UI" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UI
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBELayer\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBOnCoreStart\fP ()"
.br
.ti -1c
.RI "void \fBOnActivateZone\fP ()"
.br
.ti -1c
.RI "void \fBShowFloats\fP ()"
.br
.ti -1c
.RI "void \fBHideFloats\fP ()"
.br
.ti -1c
.RI "void \fBOnKillGame\fP ()"
.br
.ti -1c
.RI "void \fBOnClickAction\fP (string _mode)"
.br
.ti -1c
.RI "void \fBRefreshActiveState\fP ()"
.br
.ti -1c
.RI "override void \fBOnChangeLayer\fP ()"
.br
.ti -1c
.RI "void \fBFlashCover\fP (float durationOut=1f, float duration=1f, float durationIn=1f, Action onFadeOut=null, Action onComplete=null, Color color=default(Color))"
.br
.ti -1c
.RI "void \fBShowCover\fP (float duration=0f, float dest=1f, Action onComplete=null, Color color=default(Color))"
.br
.ti -1c
.RI "void \fBHideCover\fP (float duration=0f, Action onComplete=null)"
.br
.ti -1c
.RI "bool \fBIsCovered\fP ()"
.br
.ti -1c
.RI "void \fBShowBalloon\fP (bool enable)"
.br
.ti -1c
.RI "void \fBShow\fP (float duration=1f)"
.br
.ti -1c
.RI "void \fBHide\fP (float duration=1f)"
.br
.ti -1c
.RI "void \fBOnUpdate\fP ()"
.br
.ti -1c
.RI "void \fBShowMouseHint\fP ()"
.br
.ti -1c
.RI "void \fBHideMouseHint\fP (float duration=0\&.2f)"
.br
.ti -1c
.RI "void \fBCheckWindowOrder\fP ()"
.br
.ti -1c
.RI "void \fBShowSceneSelector\fP ()"
.br
.ti -1c
.RI "void \fBShowLang\fP ()"
.br
.ti -1c
.RI "void \fBSetLight\fP (bool enable)"
.br
.ti -1c
.RI "UIContextMenu \fBCreateContextMenu\fP (string cid='ContextMenu')"
.br
.ti -1c
.RI "UIContextMenu \fBCreateContextMenuInteraction\fP ()"
.br
.ti -1c
.RI "void \fBSay\fP (string text, Sprite sprite=null)"
.br
.ti -1c
.RI "void \fBFreezeScreen\fP (float duration)"
.br
.ti -1c
.RI "void \fBUnfreezeScreen\fP ()"
.br
.ti -1c
.RI "void \fBToggleAbility\fP (bool delay=false)"
.br
.ti -1c
.RI "void \fBToggleInventory\fP (bool delay=false)"
.br
.ti -1c
.RI "void \fBOpenFloatInv\fP (bool ignoreSound=false)"
.br
.ti -1c
.RI "void \fBToggleFeedback\fP ()"
.br
.ti -1c
.RI "void \fBStartDrag\fP (\fBDragItem\fP item)"
.br
.ti -1c
.RI "void \fBOnDrag\fP ()"
.br
.ti -1c
.RI "void \fBEndDrag\fP (bool canceled=false)"
.br
.in -1c

Public Member Functions inherited from \fBELayer\fP
.in +1c
.ti -1c
.RI "override void \fBOnBeforeAddLayer\fP ()"
.br
.ti -1c
.RI "void \fBInitInspector\fP ()"
.br
.ti -1c
.RI "override void \fBInit\fP ()"
.br
.ti -1c
.RI "override void \fBOnAfterAddLayer\fP ()"
.br
.ti -1c
.RI "void \fBTryShowHelp\fP ()"
.br
.ti -1c
.RI "void \fBAddLayerToUI\fP (string id)"
.br
.ti -1c
.RI "void \fBTryShowHint\fP (string _langHint=null)"
.br
.ti -1c
.RI "void \fBTalkHomeMemeber\fP (string id)"
.br
.ti -1c
.RI "void \fBTalkMaid\fP (string id)"
.br
.ti -1c
.RI "override void \fBOnRightClick\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Canvas \fBcanvas\fP"
.br
.ti -1c
.RI "\fBHUD\fP \fBhud\fP"
.br
.ti -1c
.RI "\fBExtraHint\fP \fBextraHint\fP"
.br
.ti -1c
.RI "InputModuleEX \fBinputModule\fP"
.br
.ti -1c
.RI "UIContextMenuManager \fBcontextMenu\fP"
.br
.ti -1c
.RI "\fBWidgetManager\fP \fBwidgets\fP"
.br
.ti -1c
.RI "UIMouseInfo \fBmouseInfo\fP"
.br
.ti -1c
.RI "RectTransform \fBrectDynamic\fP"
.br
.ti -1c
.RI "RectTransform \fBrectDynamicEssential\fP"
.br
.ti -1c
.RI "RectTransform \fB_rectLayers\fP"
.br
.ti -1c
.RI "ReflexConsole \fBconsole\fP"
.br
.ti -1c
.RI "GameObject \fBblur\fP"
.br
.ti -1c
.RI "Material \fBmatBlur\fP"
.br
.ti -1c
.RI "LayoutGroup \fBlayoutLang\fP"
.br
.ti -1c
.RI "CanvasScaler \fBcanvasScaler\fP"
.br
.ti -1c
.RI "Image \fBlight\fP"
.br
.ti -1c
.RI "CanvasGroup \fBcg\fP"
.br
.ti -1c
.RI "int \fBminWidth\fP"
.br
.ti -1c
.RI "Layer \fBlayerFloat\fP"
.br
.ti -1c
.RI "\fBUIAutoTurn\fP \fBautoTurn\fP"
.br
.ti -1c
.RI "PopManager \fBpopGame\fP"
.br
.ti -1c
.RI "PopManager \fBpopSystem\fP"
.br
.ti -1c
.RI "float \fBblurSpeed\fP"
.br
.ti -1c
.RI "Texture2D \fBtexFreeze\fP"
.br
.ti -1c
.RI "RawImage \fBimageFreeze\fP"
.br
.ti -1c
.RI "\fBDragItem\fP \fBcurrentDrag\fP"
.br
.ti -1c
.RI "\fBDragItem\fP \fBnextDrag\fP"
.br
.ti -1c
.RI "float \fBlightContrast\fP"
.br
.ti -1c
.RI "float \fBdragDuration\fP"
.br
.ti -1c
.RI "bool \fBwasActive\fP"
.br
.ti -1c
.RI "bool \fBisPointerOverUI\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBAwake\fP ()"
.br
.in -1c

Protected Member Functions inherited from \fBELayer\fP
.in +1c
.ti -1c
.RI "override void \fB_Close\fP ()"
.br
.ti -1c
.RI "override void \fBKill\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "SkinManager \fBskins\fP\fR [get]\fP"
.br
.ti -1c
.RI "bool \fBIsActive\fP\fR [get]\fP"
.br
.ti -1c
.RI "bool \fBAllowInventoryInteractions\fP\fR [get]\fP"
.br
.ti -1c
.RI "bool \fBBlockActions\fP\fR [get]\fP"
.br
.ti -1c
.RI "bool \fBBlockMouseOverUpdate\fP\fR [get]\fP"
.br
.ti -1c
.RI "bool \fBBlockInput\fP\fR [get]\fP"
.br
.ti -1c
.RI "bool \fBIsPauseGame\fP\fR [get]\fP"
.br
.ti -1c
.RI "bool \fBIsInventoryOpen\fP\fR [get]\fP"
.br
.ti -1c
.RI "bool \fBIsAbilityOpen\fP\fR [get]\fP"
.br
.ti -1c
.RI "override bool \fBblockWidgetClick\fP\fR [get]\fP"
.br
.ti -1c
.RI "override RectTransform \fBrectLayers\fP\fR [get]\fP"
.br
.ti -1c
.RI "bool \fBIsDragging\fP\fR [get]\fP"
.br
.in -1c

Properties inherited from \fBELayer\fP
.in +1c
.ti -1c
.RI "static \fBCore\fP \fBcore\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGame\fP \fBgame\fP\fR [get]\fP"
.br
.ti -1c
.RI "static bool \fBAdvMode\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBPlayer\fP \fBplayer\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBChara\fP \fBpc\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFaction\fP \fBHome\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBUI\fP \fBui\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBMap\fP \fB_map\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBZone\fP \fB_zone\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBScene\fP \fBscene\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBBaseGameScreen\fP \fBscreen\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBCoreConfig\fP \fBconfig\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameSetting\fP \fBsetting\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBColorProfile\fP \fBColors\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBsources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBWorld\fP \fBworld\fP\fR [get]\fP"
.br
.ti -1c
.RI "static SoundManager \fBSound\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBCoreDebug\fP \fBdebug\fP\fR [get]\fP"
.br
.ti -1c
.RI "bool \fBIsFloat\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual string \fBIdHelp\fP\fR [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Static Public Member Functions inherited from \fBELayer\fP
.in +1c
.ti -1c
.RI "static int \fBrnd\fP (int a)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB11\fP of file \fBUI\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void UI\&.Awake ()\fR [protected]\fP"

.PP
Definition at line \fB134\fP of file \fBUI\&.cs\fP\&.
.SS "void UI\&.CheckWindowOrder ()"

.PP
Definition at line \fB449\fP of file \fBUI\&.cs\fP\&.
.SS "UIContextMenu UI\&.CreateContextMenu (string cid = \fR'ContextMenu'\fP)"

.PP
Definition at line \fB531\fP of file \fBUI\&.cs\fP\&.
.SS "UIContextMenu UI\&.CreateContextMenuInteraction ()"

.PP
Definition at line \fB537\fP of file \fBUI\&.cs\fP\&.
.SS "void UI\&.EndDrag (bool canceled = \fRfalse\fP)"

.PP
Definition at line \fB704\fP of file \fBUI\&.cs\fP\&.
.SS "void UI\&.FlashCover (float durationOut = \fR1f\fP, float duration = \fR1f\fP, float durationIn = \fR1f\fP, Action onFadeOut = \fRnull\fP, Action onComplete = \fRnull\fP, Color color = \fRdefault(Color)\fP)"

.PP
Definition at line \fB242\fP of file \fBUI\&.cs\fP\&.
.SS "void UI\&.FreezeScreen (float duration)"

.PP
Definition at line \fB550\fP of file \fBUI\&.cs\fP\&.
.SS "void UI\&.Hide (float duration = \fR1f\fP)"

.PP
Definition at line \fB322\fP of file \fBUI\&.cs\fP\&.
.SS "void UI\&.HideCover (float duration = \fR0f\fP, Action onComplete = \fRnull\fP)"

.PP
Definition at line \fB275\fP of file \fBUI\&.cs\fP\&.
.SS "void UI\&.HideFloats ()"

.PP
Definition at line \fB164\fP of file \fBUI\&.cs\fP\&.
.SS "void UI\&.HideMouseHint (float duration = \fR0::2f\fP)"

.PP
Definition at line \fB441\fP of file \fBUI\&.cs\fP\&.
.SS "bool UI\&.IsCovered ()"

.PP
Definition at line \fB296\fP of file \fBUI\&.cs\fP\&.
.SS "void UI\&.OnActivateZone ()"

.PP
Definition at line \fB147\fP of file \fBUI\&.cs\fP\&.
.SS "override void UI\&.OnChangeLayer ()"

.PP
Definition at line \fB205\fP of file \fBUI\&.cs\fP\&.
.SS "void UI\&.OnClickAction (string _mode)"

.PP
Definition at line \fB179\fP of file \fBUI\&.cs\fP\&.
.SS "void UI\&.OnCoreStart ()"

.PP
Definition at line \fB141\fP of file \fBUI\&.cs\fP\&.
.SS "void UI\&.OnDrag ()"

.PP
Definition at line \fB697\fP of file \fBUI\&.cs\fP\&.
.SS "void UI\&.OnKillGame ()"

.PP
Definition at line \fB170\fP of file \fBUI\&.cs\fP\&.
.SS "void UI\&.OnUpdate ()"

.PP
Definition at line \fB334\fP of file \fBUI\&.cs\fP\&.
.SS "void UI\&.OpenFloatInv (bool ignoreSound = \fRfalse\fP)"

.PP
Definition at line \fB642\fP of file \fBUI\&.cs\fP\&.
.SS "void UI\&.RefreshActiveState ()"

.PP
Definition at line \fB186\fP of file \fBUI\&.cs\fP\&.
.SS "void UI\&.Say (string text, Sprite sprite = \fRnull\fP)"

.PP
Definition at line \fB543\fP of file \fBUI\&.cs\fP\&.
.SS "void UI\&.SetLight (bool enable)"

.PP
Definition at line \fB526\fP of file \fBUI\&.cs\fP\&.
.SS "void UI\&.Show (float duration = \fR1f\fP)"

.PP
Definition at line \fB309\fP of file \fBUI\&.cs\fP\&.
.SS "void UI\&.ShowBalloon (bool enable)"

.PP
Definition at line \fB302\fP of file \fBUI\&.cs\fP\&.
.SS "void UI\&.ShowCover (float duration = \fR0f\fP, float dest = \fR1f\fP, Action onComplete = \fRnull\fP, Color color = \fRdefault(Color)\fP)"

.PP
Definition at line \fB256\fP of file \fBUI\&.cs\fP\&.
.SS "void UI\&.ShowFloats ()"

.PP
Definition at line \fB158\fP of file \fBUI\&.cs\fP\&.
.SS "void UI\&.ShowLang ()"

.PP
Definition at line \fB498\fP of file \fBUI\&.cs\fP\&.
.SS "void UI\&.ShowMouseHint ()"

.PP
Definition at line \fB388\fP of file \fBUI\&.cs\fP\&.
.SS "void UI\&.ShowSceneSelector ()"

.PP
Definition at line \fB474\fP of file \fBUI\&.cs\fP\&.
.SS "void UI\&.StartDrag (\fBDragItem\fP item)"

.PP
Definition at line \fB676\fP of file \fBUI\&.cs\fP\&.
.SS "void UI\&.ToggleAbility (bool delay = \fRfalse\fP)"

.PP
Definition at line \fB579\fP of file \fBUI\&.cs\fP\&.
.SS "void UI\&.ToggleFeedback ()"

.PP
Definition at line \fB663\fP of file \fBUI\&.cs\fP\&.
.SS "void UI\&.ToggleInventory (bool delay = \fRfalse\fP)"

.PP
Definition at line \fB606\fP of file \fBUI\&.cs\fP\&.
.SS "void UI\&.UnfreezeScreen ()"

.PP
Definition at line \fB569\fP of file \fBUI\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "RectTransform UI\&._rectLayers"

.PP
Definition at line \fB764\fP of file \fBUI\&.cs\fP\&.
.SS "\fBUIAutoTurn\fP UI\&.autoTurn"

.PP
Definition at line \fB794\fP of file \fBUI\&.cs\fP\&.
.SS "GameObject UI\&.blur"

.PP
Definition at line \fB770\fP of file \fBUI\&.cs\fP\&.
.SS "float UI\&.blurSpeed"

.PP
Definition at line \fB803\fP of file \fBUI\&.cs\fP\&.
.SS "Canvas UI\&.canvas"

.PP
Definition at line \fB737\fP of file \fBUI\&.cs\fP\&.
.SS "CanvasScaler UI\&.canvasScaler"

.PP
Definition at line \fB779\fP of file \fBUI\&.cs\fP\&.
.SS "CanvasGroup UI\&.cg"

.PP
Definition at line \fB785\fP of file \fBUI\&.cs\fP\&.
.SS "ReflexConsole UI\&.console"

.PP
Definition at line \fB767\fP of file \fBUI\&.cs\fP\&.
.SS "UIContextMenuManager UI\&.contextMenu"

.PP
Definition at line \fB749\fP of file \fBUI\&.cs\fP\&.
.SS "\fBDragItem\fP UI\&.currentDrag"

.PP
Definition at line \fB812\fP of file \fBUI\&.cs\fP\&.
.SS "float UI\&.dragDuration"

.PP
Definition at line \fB826\fP of file \fBUI\&.cs\fP\&.
.SS "\fBExtraHint\fP UI\&.extraHint"

.PP
Definition at line \fB743\fP of file \fBUI\&.cs\fP\&.
.SS "\fBHUD\fP UI\&.hud"

.PP
Definition at line \fB740\fP of file \fBUI\&.cs\fP\&.
.SS "RawImage UI\&.imageFreeze"

.PP
Definition at line \fB809\fP of file \fBUI\&.cs\fP\&.
.SS "InputModuleEX UI\&.inputModule"

.PP
Definition at line \fB746\fP of file \fBUI\&.cs\fP\&.
.SS "bool UI\&.isPointerOverUI"

.PP
Definition at line \fB837\fP of file \fBUI\&.cs\fP\&.
.SS "Layer UI\&.layerFloat"

.PP
Definition at line \fB791\fP of file \fBUI\&.cs\fP\&.
.SS "LayoutGroup UI\&.layoutLang"

.PP
Definition at line \fB776\fP of file \fBUI\&.cs\fP\&.
.SS "Image UI\&.light"

.PP
Definition at line \fB782\fP of file \fBUI\&.cs\fP\&.
.SS "float UI\&.lightContrast"

.PP
Definition at line \fB822\fP of file \fBUI\&.cs\fP\&.
.SS "Material UI\&.matBlur"

.PP
Definition at line \fB773\fP of file \fBUI\&.cs\fP\&.
.SS "int UI\&.minWidth"

.PP
Definition at line \fB788\fP of file \fBUI\&.cs\fP\&.
.SS "UIMouseInfo UI\&.mouseInfo"

.PP
Definition at line \fB755\fP of file \fBUI\&.cs\fP\&.
.SS "\fBDragItem\fP UI\&.nextDrag"

.PP
Definition at line \fB815\fP of file \fBUI\&.cs\fP\&.
.SS "PopManager UI\&.popGame"

.PP
Definition at line \fB797\fP of file \fBUI\&.cs\fP\&.
.SS "PopManager UI\&.popSystem"

.PP
Definition at line \fB800\fP of file \fBUI\&.cs\fP\&.
.SS "RectTransform UI\&.rectDynamic"

.PP
Definition at line \fB758\fP of file \fBUI\&.cs\fP\&.
.SS "RectTransform UI\&.rectDynamicEssential"

.PP
Definition at line \fB761\fP of file \fBUI\&.cs\fP\&.
.SS "Texture2D UI\&.texFreeze"

.PP
Definition at line \fB806\fP of file \fBUI\&.cs\fP\&.
.SS "bool UI\&.wasActive"

.PP
Definition at line \fB833\fP of file \fBUI\&.cs\fP\&.
.SS "\fBWidgetManager\fP UI\&.widgets"

.PP
Definition at line \fB752\fP of file \fBUI\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "bool UI\&.AllowInventoryInteractions\fR [get]\fP"

.PP
Definition at line \fB35\fP of file \fBUI\&.cs\fP\&.
.SS "bool UI\&.BlockActions\fR [get]\fP"

.PP
Definition at line \fB45\fP of file \fBUI\&.cs\fP\&.
.SS "bool UI\&.BlockInput\fR [get]\fP"

.PP
Definition at line \fB65\fP of file \fBUI\&.cs\fP\&.
.SS "bool UI\&.BlockMouseOverUpdate\fR [get]\fP"

.PP
Definition at line \fB55\fP of file \fBUI\&.cs\fP\&.
.SS "override bool UI\&.blockWidgetClick\fR [get]\fP"

.PP
Definition at line \fB105\fP of file \fBUI\&.cs\fP\&.
.SS "bool UI\&.IsAbilityOpen\fR [get]\fP"

.PP
Definition at line \fB95\fP of file \fBUI\&.cs\fP\&.
.SS "bool UI\&.IsActive\fR [get]\fP"

.PP
Definition at line \fB25\fP of file \fBUI\&.cs\fP\&.
.SS "bool UI\&.IsDragging\fR [get]\fP"

.PP
Definition at line \fB125\fP of file \fBUI\&.cs\fP\&.
.SS "bool UI\&.IsInventoryOpen\fR [get]\fP"

.PP
Definition at line \fB85\fP of file \fBUI\&.cs\fP\&.
.SS "bool UI\&.IsPauseGame\fR [get]\fP"

.PP
Definition at line \fB75\fP of file \fBUI\&.cs\fP\&.
.SS "override RectTransform UI\&.rectLayers\fR [get]\fP"

.PP
Definition at line \fB115\fP of file \fBUI\&.cs\fP\&.
.SS "SkinManager UI\&.skins\fR [get]\fP"

.PP
Definition at line \fB15\fP of file \fBUI\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
