.TH "UICardInfo" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UICardInfo
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBEMono\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetRenderer\fP (\fBIRenderer\fP _renderer, \fBRenderParam\fP p)"
.br
.ti -1c
.RI "void \fBUpdateImage\fP ()"
.br
.ti -1c
.RI "void \fBBuild\fP ()"
.br
.ti -1c
.RI "void \fBSetElement\fP (\fBElement\fP e)"
.br
.ti -1c
.RI "void \fBSetThing\fP (\fBThing\fP t)"
.br
.ti -1c
.RI "void \fBUpdateRecipe\fP (\fBRecipe\fP r)"
.br
.ti -1c
.RI "void \fBSetRecipe\fP (\fBRecipe\fP r)"
.br
.ti -1c
.RI "void \fBSetBlock\fP (\fBCell\fP cell)"
.br
.ti -1c
.RI "void \fBSetFloor\fP (\fBCell\fP cell)"
.br
.ti -1c
.RI "void \fBSetLiquid\fP (\fBCell\fP cell)"
.br
.ti -1c
.RI "void \fBSetObj\fP (\fBCell\fP cell)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "UINote \fBnote\fP"
.br
.ti -1c
.RI "\fBIRenderer\fP \fBrenderer\fP"
.br
.ti -1c
.RI "\fBRenderParam\fP \fBparam\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Static Public Member Functions inherited from \fBEMono\fP
.in +1c
.ti -1c
.RI "static int \fBrnd\fP (int a)"
.br
.in -1c

Static Public Attributes inherited from \fBEMono\fP
.in +1c
.ti -1c
.RI "static \fBCore\fP \fBcore\fP"
.br
.in -1c

Properties inherited from \fBEMono\fP
.in +1c
.ti -1c
.RI "static \fBGame\fP \fBgame\fP\fR [get]\fP"
.br
.ti -1c
.RI "static bool \fBAdvMode\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBPlayer\fP \fBplayer\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBChara\fP \fBpc\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBUI\fP \fBui\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBMap\fP \fB_map\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBZone\fP \fB_zone\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranchOrHomeBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFaction\fP \fBHome\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBScene\fP \fBscene\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBBaseGameScreen\fP \fBscreen\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameSetting\fP \fBsetting\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameData\fP \fBgamedata\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBColorProfile\fP \fBColors\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBWorld\fP \fBworld\fP\fR [get]\fP"
.br
.ti -1c
.RI "static SoundManager \fBSound\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBsources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBeditorSources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBCoreDebug\fP \fBdebug\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB4\fP of file \fBUICardInfo\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void UICardInfo\&.Build ()"

.PP
Definition at line \fB27\fP of file \fBUICardInfo\&.cs\fP\&.
.SS "void UICardInfo\&.SetBlock (\fBCell\fP cell)"

.PP
Definition at line \fB74\fP of file \fBUICardInfo\&.cs\fP\&.
.SS "void UICardInfo\&.SetElement (\fBElement\fP e)"

.PP
Definition at line \fB40\fP of file \fBUICardInfo\&.cs\fP\&.
.SS "void UICardInfo\&.SetFloor (\fBCell\fP cell)"

.PP
Definition at line \fB85\fP of file \fBUICardInfo\&.cs\fP\&.
.SS "void UICardInfo\&.SetLiquid (\fBCell\fP cell)"

.PP
Definition at line \fB96\fP of file \fBUICardInfo\&.cs\fP\&.
.SS "void UICardInfo\&.SetObj (\fBCell\fP cell)"

.PP
Definition at line \fB107\fP of file \fBUICardInfo\&.cs\fP\&.
.SS "void UICardInfo\&.SetRecipe (\fBRecipe\fP r)"

.PP
Definition at line \fB59\fP of file \fBUICardInfo\&.cs\fP\&.
.SS "void UICardInfo\&.SetRenderer (\fBIRenderer\fP _renderer, \fBRenderParam\fP p)"

.PP
Definition at line \fB7\fP of file \fBUICardInfo\&.cs\fP\&.
.SS "void UICardInfo\&.SetThing (\fBThing\fP t)"

.PP
Definition at line \fB46\fP of file \fBUICardInfo\&.cs\fP\&.
.SS "void UICardInfo\&.UpdateImage ()"

.PP
Definition at line \fB14\fP of file \fBUICardInfo\&.cs\fP\&.
.SS "void UICardInfo\&.UpdateRecipe (\fBRecipe\fP r)"

.PP
Definition at line \fB53\fP of file \fBUICardInfo\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "UINote UICardInfo\&.note"

.PP
Definition at line \fB118\fP of file \fBUICardInfo\&.cs\fP\&.
.SS "\fBRenderParam\fP UICardInfo\&.param"

.PP
Definition at line \fB124\fP of file \fBUICardInfo\&.cs\fP\&.
.SS "\fBIRenderer\fP UICardInfo\&.renderer"

.PP
Definition at line \fB121\fP of file \fBUICardInfo\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
