.TH "UICharaMaker" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UICharaMaker
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBEMono\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetChara\fP (\fBChara\fP c)"
.br
.ti -1c
.RI "void \fBBuildRaces\fP ()"
.br
.ti -1c
.RI "void \fBRefreshPortraitZoom\fP (bool force=false)"
.br
.ti -1c
.RI "void \fBRefresh\fP ()"
.br
.ti -1c
.RI "void \fBListModes\fP ()"
.br
.ti -1c
.RI "void \fBListDifficulties\fP ()"
.br
.ti -1c
.RI "void \fBRerollAlias\fP ()"
.br
.ti -1c
.RI "void \fBListAlias\fP ()"
.br
.ti -1c
.RI "void \fBRerollName\fP ()"
.br
.ti -1c
.RI "void \fBEditName\fP ()"
.br
.ti -1c
.RI "void \fBOnEndEditName\fP ()"
.br
.ti -1c
.RI "void \fBRerollRace\fP ()"
.br
.ti -1c
.RI "void \fBListRace\fP ()"
.br
.ti -1c
.RI "void \fBRerollJob\fP ()"
.br
.ti -1c
.RI "void \fBListJob\fP ()"
.br
.ti -1c
.RI "void \fBAddDomain\fP (UINote n, \fBElementContainer\fP domains, bool button)"
.br
.ti -1c
.RI "void \fBListGender\fP ()"
.br
.ti -1c
.RI "void \fBListAge\fP ()"
.br
.ti -1c
.RI "void \fBSetPortraitSlider\fP ()"
.br
.ti -1c
.RI "void \fBRerollPCC\fP ()"
.br
.ti -1c
.RI "void \fBRerollHair\fP ()"
.br
.ti -1c
.RI "void \fBRerollBio\fP ()"
.br
.ti -1c
.RI "void \fBRerollBio\fP (bool keepParent)"
.br
.ti -1c
.RI "void \fBEditPCC\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBChara\fP \fBchara\fP"
.br
.ti -1c
.RI "\fBPortrait\fP \fBportrait\fP"
.br
.ti -1c
.RI "\fBPortrait\fP \fBportraitZoom\fP"
.br
.ti -1c
.RI "InputField \fBinputName\fP"
.br
.ti -1c
.RI "InputField \fBinputAlias\fP"
.br
.ti -1c
.RI "InputField \fBinputJob\fP"
.br
.ti -1c
.RI "InputField \fBinputRace\fP"
.br
.ti -1c
.RI "InputField \fBinputGender\fP"
.br
.ti -1c
.RI "InputField \fBinputAge\fP"
.br
.ti -1c
.RI "UISlider \fBsliderPortrait\fP"
.br
.ti -1c
.RI "List< \fBSourceRace\&.Row\fP > \fBraces\fP = new List<\fBSourceRace\&.Row\fP>()"
.br
.ti -1c
.RI "List< \fBSourceJob\&.Row\fP > \fBjobs\fP = new List<\fBSourceJob\&.Row\fP>()"
.br
.ti -1c
.RI "UIButton \fBtoggleExtra\fP"
.br
.ti -1c
.RI "UIButton \fBtoggleParentLock\fP"
.br
.ti -1c
.RI "UINote \fBnote\fP"
.br
.ti -1c
.RI "UINote \fBnote2\fP"
.br
.ti -1c
.RI "UINote \fBnoteJob\fP"
.br
.ti -1c
.RI "UINote \fBnoteRace\fP"
.br
.ti -1c
.RI "bool \fBaddShadow\fP"
.br
.ti -1c
.RI "bool \fBextraRace\fP"
.br
.ti -1c
.RI "UIText \fBtextSign\fP"
.br
.ti -1c
.RI "UIText \fBtextMode\fP"
.br
.ti -1c
.RI "UIText \fBtextDifficulty\fP"
.br
.ti -1c
.RI "int \fBageIndex\fP"
.br
.ti -1c
.RI "Vector2 \fBposList\fP"
.br
.ti -1c
.RI "Vector2 \fBposList2\fP"
.br
.ti -1c
.RI "string[] \fBlistMode\fP"
.br
.ti -1c
.RI "string[] \fBlistDifficulties\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBBiography\fP \fBbio\fP\fR [get]\fP"
.br
.ti -1c
.RI "string \fBTextUnknown\fP\fR [get]\fP"
.br
.in -1c

Properties inherited from \fBEMono\fP
.in +1c
.ti -1c
.RI "static \fBGame\fP \fBgame\fP\fR [get]\fP"
.br
.ti -1c
.RI "static bool \fBAdvMode\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBPlayer\fP \fBplayer\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBChara\fP \fBpc\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBUI\fP \fBui\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBMap\fP \fB_map\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBZone\fP \fB_zone\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranchOrHomeBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFaction\fP \fBHome\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBScene\fP \fBscene\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBBaseGameScreen\fP \fBscreen\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameSetting\fP \fBsetting\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameData\fP \fBgamedata\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBColorProfile\fP \fBColors\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBWorld\fP \fBworld\fP\fR [get]\fP"
.br
.ti -1c
.RI "static SoundManager \fBSound\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBsources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBeditorSources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBCoreDebug\fP \fBdebug\fP\fR [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Static Public Member Functions inherited from \fBEMono\fP
.in +1c
.ti -1c
.RI "static int \fBrnd\fP (int a)"
.br
.in -1c

Static Public Attributes inherited from \fBEMono\fP
.in +1c
.ti -1c
.RI "static \fBCore\fP \fBcore\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB9\fP of file \fBUICharaMaker\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void UICharaMaker\&.AddDomain (UINote n, \fBElementContainer\fP domains, bool button)"

.PP
Definition at line \fB381\fP of file \fBUICharaMaker\&.cs\fP\&.
.SS "void UICharaMaker\&.BuildRaces ()"

.PP
Definition at line \fB51\fP of file \fBUICharaMaker\&.cs\fP\&.
.SS "void UICharaMaker\&.EditName ()"

.PP
Definition at line \fB251\fP of file \fBUICharaMaker\&.cs\fP\&.
.SS "void UICharaMaker\&.EditPCC ()"

.PP
Definition at line \fB474\fP of file \fBUICharaMaker\&.cs\fP\&.
.SS "void UICharaMaker\&.ListAge ()"

.PP
Definition at line \fB415\fP of file \fBUICharaMaker\&.cs\fP\&.
.SS "void UICharaMaker\&.ListAlias ()"

.PP
Definition at line \fB226\fP of file \fBUICharaMaker\&.cs\fP\&.
.SS "void UICharaMaker\&.ListDifficulties ()"

.PP
Definition at line \fB176\fP of file \fBUICharaMaker\&.cs\fP\&.
.SS "void UICharaMaker\&.ListGender ()"

.PP
Definition at line \fB398\fP of file \fBUICharaMaker\&.cs\fP\&.
.SS "void UICharaMaker\&.ListJob ()"

.PP
Definition at line \fB334\fP of file \fBUICharaMaker\&.cs\fP\&.
.SS "void UICharaMaker\&.ListModes ()"

.PP
Definition at line \fB160\fP of file \fBUICharaMaker\&.cs\fP\&.
.SS "void UICharaMaker\&.ListRace ()"

.PP
Definition at line \fB280\fP of file \fBUICharaMaker\&.cs\fP\&.
.SS "void UICharaMaker\&.OnEndEditName ()"

.PP
Definition at line \fB267\fP of file \fBUICharaMaker\&.cs\fP\&.
.SS "void UICharaMaker\&.Refresh ()"

.PP
Definition at line \fB104\fP of file \fBUICharaMaker\&.cs\fP\&.
.SS "void UICharaMaker\&.RefreshPortraitZoom (bool force = \fRfalse\fP)"

.PP
Definition at line \fB81\fP of file \fBUICharaMaker\&.cs\fP\&.
.SS "void UICharaMaker\&.RerollAlias ()"

.PP
Definition at line \fB219\fP of file \fBUICharaMaker\&.cs\fP\&.
.SS "void UICharaMaker\&.RerollBio ()"

.PP
Definition at line \fB461\fP of file \fBUICharaMaker\&.cs\fP\&.
.SS "void UICharaMaker\&.RerollBio (bool keepParent)"

.PP
Definition at line \fB467\fP of file \fBUICharaMaker\&.cs\fP\&.
.SS "void UICharaMaker\&.RerollHair ()"

.PP
Definition at line \fB453\fP of file \fBUICharaMaker\&.cs\fP\&.
.SS "void UICharaMaker\&.RerollJob ()"

.PP
Definition at line \fB326\fP of file \fBUICharaMaker\&.cs\fP\&.
.SS "void UICharaMaker\&.RerollName ()"

.PP
Definition at line \fB244\fP of file \fBUICharaMaker\&.cs\fP\&.
.SS "void UICharaMaker\&.RerollPCC ()"

.PP
Definition at line \fB445\fP of file \fBUICharaMaker\&.cs\fP\&.
.SS "void UICharaMaker\&.RerollRace ()"

.PP
Definition at line \fB273\fP of file \fBUICharaMaker\&.cs\fP\&.
.SS "void UICharaMaker\&.SetChara (\fBChara\fP c)"

.PP
Definition at line \fB32\fP of file \fBUICharaMaker\&.cs\fP\&.
.SS "void UICharaMaker\&.SetPortraitSlider ()"

.PP
Definition at line \fB429\fP of file \fBUICharaMaker\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "bool UICharaMaker\&.addShadow"

.PP
Definition at line \fB538\fP of file \fBUICharaMaker\&.cs\fP\&.
.SS "int UICharaMaker\&.ageIndex"

.PP
Definition at line \fB553\fP of file \fBUICharaMaker\&.cs\fP\&.
.SS "\fBChara\fP UICharaMaker\&.chara"

.PP
Definition at line \fB484\fP of file \fBUICharaMaker\&.cs\fP\&.
.SS "bool UICharaMaker\&.extraRace"

.PP
Definition at line \fB541\fP of file \fBUICharaMaker\&.cs\fP\&.
.SS "InputField UICharaMaker\&.inputAge"

.PP
Definition at line \fB508\fP of file \fBUICharaMaker\&.cs\fP\&.
.SS "InputField UICharaMaker\&.inputAlias"

.PP
Definition at line \fB496\fP of file \fBUICharaMaker\&.cs\fP\&.
.SS "InputField UICharaMaker\&.inputGender"

.PP
Definition at line \fB505\fP of file \fBUICharaMaker\&.cs\fP\&.
.SS "InputField UICharaMaker\&.inputJob"

.PP
Definition at line \fB499\fP of file \fBUICharaMaker\&.cs\fP\&.
.SS "InputField UICharaMaker\&.inputName"

.PP
Definition at line \fB493\fP of file \fBUICharaMaker\&.cs\fP\&.
.SS "InputField UICharaMaker\&.inputRace"

.PP
Definition at line \fB502\fP of file \fBUICharaMaker\&.cs\fP\&.
.SS "List<\fBSourceJob\&.Row\fP> UICharaMaker\&.jobs = new List<\fBSourceJob\&.Row\fP>()"

.PP
Definition at line \fB517\fP of file \fBUICharaMaker\&.cs\fP\&.
.SS "string [] UICharaMaker\&.listDifficulties"

.PP
Definition at line \fB567\fP of file \fBUICharaMaker\&.cs\fP\&.
.SS "string [] UICharaMaker\&.listMode"

.PP
Definition at line \fB563\fP of file \fBUICharaMaker\&.cs\fP\&.
.SS "UINote UICharaMaker\&.note"

.PP
Definition at line \fB526\fP of file \fBUICharaMaker\&.cs\fP\&.
.SS "UINote UICharaMaker\&.note2"

.PP
Definition at line \fB529\fP of file \fBUICharaMaker\&.cs\fP\&.
.SS "UINote UICharaMaker\&.noteJob"

.PP
Definition at line \fB532\fP of file \fBUICharaMaker\&.cs\fP\&.
.SS "UINote UICharaMaker\&.noteRace"

.PP
Definition at line \fB535\fP of file \fBUICharaMaker\&.cs\fP\&.
.SS "\fBPortrait\fP UICharaMaker\&.portrait"

.PP
Definition at line \fB487\fP of file \fBUICharaMaker\&.cs\fP\&.
.SS "\fBPortrait\fP UICharaMaker\&.portraitZoom"

.PP
Definition at line \fB490\fP of file \fBUICharaMaker\&.cs\fP\&.
.SS "Vector2 UICharaMaker\&.posList"

.PP
Definition at line \fB556\fP of file \fBUICharaMaker\&.cs\fP\&.
.SS "Vector2 UICharaMaker\&.posList2"

.PP
Definition at line \fB559\fP of file \fBUICharaMaker\&.cs\fP\&.
.SS "List<\fBSourceRace\&.Row\fP> UICharaMaker\&.races = new List<\fBSourceRace\&.Row\fP>()"

.PP
Definition at line \fB514\fP of file \fBUICharaMaker\&.cs\fP\&.
.SS "UISlider UICharaMaker\&.sliderPortrait"

.PP
Definition at line \fB511\fP of file \fBUICharaMaker\&.cs\fP\&.
.SS "UIText UICharaMaker\&.textDifficulty"

.PP
Definition at line \fB550\fP of file \fBUICharaMaker\&.cs\fP\&.
.SS "UIText UICharaMaker\&.textMode"

.PP
Definition at line \fB547\fP of file \fBUICharaMaker\&.cs\fP\&.
.SS "UIText UICharaMaker\&.textSign"

.PP
Definition at line \fB544\fP of file \fBUICharaMaker\&.cs\fP\&.
.SS "UIButton UICharaMaker\&.toggleExtra"

.PP
Definition at line \fB520\fP of file \fBUICharaMaker\&.cs\fP\&.
.SS "UIButton UICharaMaker\&.toggleParentLock"

.PP
Definition at line \fB523\fP of file \fBUICharaMaker\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "\fBBiography\fP UICharaMaker\&.bio\fR [get]\fP"

.PP
Definition at line \fB13\fP of file \fBUICharaMaker\&.cs\fP\&.
.SS "string UICharaMaker\&.TextUnknown\fR [get]\fP"

.PP
Definition at line \fB23\fP of file \fBUICharaMaker\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
