.TH "UICurrency.Options" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UICurrency.Options
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBmoney\fP"
.br
.ti -1c
.RI "bool \fBplat\fP"
.br
.ti -1c
.RI "bool \fBecopo\fP"
.br
.ti -1c
.RI "bool \fBknowledge\fP"
.br
.ti -1c
.RI "bool \fBinfluence\fP"
.br
.ti -1c
.RI "bool \fBmedal\fP"
.br
.ti -1c
.RI "bool \fBmoney2\fP"
.br
.ti -1c
.RI "bool \fBresources\fP"
.br
.ti -1c
.RI "bool \fBbranchMoney\fP"
.br
.ti -1c
.RI "bool \fBbranchFood\fP"
.br
.ti -1c
.RI "bool \fBbranchMaterial\fP"
.br
.ti -1c
.RI "bool \fBbranchKnowledge\fP"
.br
.ti -1c
.RI "bool \fBadmin\fP"
.br
.ti -1c
.RI "bool \fBcasino\fP"
.br
.ti -1c
.RI "bool \fBweight\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB164\fP of file \fBUICurrency\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "bool UICurrency\&.Options\&.admin"

.PP
Definition at line \fB203\fP of file \fBUICurrency\&.cs\fP\&.
.SS "bool UICurrency\&.Options\&.branchFood"

.PP
Definition at line \fB194\fP of file \fBUICurrency\&.cs\fP\&.
.SS "bool UICurrency\&.Options\&.branchKnowledge"

.PP
Definition at line \fB200\fP of file \fBUICurrency\&.cs\fP\&.
.SS "bool UICurrency\&.Options\&.branchMaterial"

.PP
Definition at line \fB197\fP of file \fBUICurrency\&.cs\fP\&.
.SS "bool UICurrency\&.Options\&.branchMoney"

.PP
Definition at line \fB191\fP of file \fBUICurrency\&.cs\fP\&.
.SS "bool UICurrency\&.Options\&.casino"

.PP
Definition at line \fB206\fP of file \fBUICurrency\&.cs\fP\&.
.SS "bool UICurrency\&.Options\&.ecopo"

.PP
Definition at line \fB173\fP of file \fBUICurrency\&.cs\fP\&.
.SS "bool UICurrency\&.Options\&.influence"

.PP
Definition at line \fB179\fP of file \fBUICurrency\&.cs\fP\&.
.SS "bool UICurrency\&.Options\&.knowledge"

.PP
Definition at line \fB176\fP of file \fBUICurrency\&.cs\fP\&.
.SS "bool UICurrency\&.Options\&.medal"

.PP
Definition at line \fB182\fP of file \fBUICurrency\&.cs\fP\&.
.SS "bool UICurrency\&.Options\&.money"

.PP
Definition at line \fB167\fP of file \fBUICurrency\&.cs\fP\&.
.SS "bool UICurrency\&.Options\&.money2"

.PP
Definition at line \fB185\fP of file \fBUICurrency\&.cs\fP\&.
.SS "bool UICurrency\&.Options\&.plat"

.PP
Definition at line \fB170\fP of file \fBUICurrency\&.cs\fP\&.
.SS "bool UICurrency\&.Options\&.resources"

.PP
Definition at line \fB188\fP of file \fBUICurrency\&.cs\fP\&.
.SS "bool UICurrency\&.Options\&.weight"

.PP
Definition at line \fB209\fP of file \fBUICurrency\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
