.TH "UICurrency.Item" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UICurrency.Item
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Func< string > \fBfunc\fP"
.br
.ti -1c
.RI "UIText \fBtext\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB213\fP of file \fBUICurrency\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "Func<string> UICurrency\&.Item\&.func"

.PP
Definition at line \fB216\fP of file \fBUICurrency\&.cs\fP\&.
.SS "UIText UICurrency\&.Item\&.text"

.PP
Definition at line \fB219\fP of file \fBUICurrency\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
