.TH "UIHomeInfo.ReportData" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UIHomeInfo.ReportData
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBReportType\fP { \fBDefault\fP, \fBWarning\fP, \fBCritical\fP, \fBGood\fP, \fBGreat\fP, \fBTrial\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "FontColor \fBGetFontColor\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "UIHomeInfo\&.ReportData\&.ReportType \fBtype\fP"
.br
.ti -1c
.RI "string \fBtext\fP"
.br
.ti -1c
.RI "Action \fBonClick\fP"
.br
.ti -1c
.RI "Action< UITooltip > \fBonShowTooltip\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB495\fP of file \fBUIHomeInfo\&.cs\fP\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "enum UIHomeInfo\&.ReportData\&.ReportType"

.PP
Definition at line \fB530\fP of file \fBUIHomeInfo\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "FontColor UIHomeInfo\&.ReportData\&.GetFontColor ()"

.PP
Definition at line \fB498\fP of file \fBUIHomeInfo\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "Action UIHomeInfo\&.ReportData\&.onClick"

.PP
Definition at line \fB524\fP of file \fBUIHomeInfo\&.cs\fP\&.
.SS "Action<UITooltip> UIHomeInfo\&.ReportData\&.onShowTooltip"

.PP
Definition at line \fB527\fP of file \fBUIHomeInfo\&.cs\fP\&.
.SS "string UIHomeInfo\&.ReportData\&.text"

.PP
Definition at line \fB521\fP of file \fBUIHomeInfo\&.cs\fP\&.
.SS "UIHomeInfo\&.ReportData\&.ReportType UIHomeInfo\&.ReportData\&.type"

.PP
Definition at line \fB518\fP of file \fBUIHomeInfo\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
