.TH "UIInspector" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UIInspector
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBELayer\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetVisible\fP (bool enable)"
.br
.ti -1c
.RI "void \fBHide\fP ()"
.br
.ti -1c
.RI "bool \fBInspectUnderMouse\fP ()"
.br
.ti -1c
.RI "void \fBInspect\fP (\fBIInspect\fP newTarget)"
.br
.ti -1c
.RI "void \fBInspect\fP (\fBInspectGroup\fP g)"
.br
.ti -1c
.RI "void \fBOnUpdate\fP ()"
.br
.ti -1c
.RI "void \fBRefresh\fP ()"
.br
.ti -1c
.RI "unsafe void \fBDrawHighlight\fP (\fBIInspect\fP i, bool selected=false)"
.br
.in -1c

Public Member Functions inherited from \fBELayer\fP
.in +1c
.ti -1c
.RI "override void \fBOnBeforeAddLayer\fP ()"
.br
.ti -1c
.RI "void \fBInitInspector\fP ()"
.br
.ti -1c
.RI "override void \fBInit\fP ()"
.br
.ti -1c
.RI "override void \fBOnAfterAddLayer\fP ()"
.br
.ti -1c
.RI "void \fBTryShowHelp\fP ()"
.br
.ti -1c
.RI "void \fBAddLayerToUI\fP (string id)"
.br
.ti -1c
.RI "void \fBTryShowHint\fP (string _langHint=null)"
.br
.ti -1c
.RI "void \fBTalkHomeMemeber\fP (string id)"
.br
.ti -1c
.RI "void \fBTalkMaid\fP (string id)"
.br
.ti -1c
.RI "override void \fBOnRightClick\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBInspectGroup\fP \fBgroup\fP"
.br
.ti -1c
.RI "LayoutGroup \fBlayoutBody\fP"
.br
.ti -1c
.RI "LayoutGroup \fBlayoutButtons\fP"
.br
.ti -1c
.RI "UIButton \fBmold\fP"
.br
.ti -1c
.RI "Vector3 \fBoffset\fP"
.br
.ti -1c
.RI "Vector3 \fBmodPos\fP"
.br
.ti -1c
.RI "SoundData \fBsoundPop\fP"
.br
.ti -1c
.RI "\fBWindowChara\fP \fBwindowChara\fP"
.br
.ti -1c
.RI "RectTransform \fBrectInfo\fP"
.br
.ti -1c
.RI "RectTransform \fBrectRoom\fP"
.br
.ti -1c
.RI "UINote \fBnote\fP"
.br
.ti -1c
.RI "UINote \fBnoteRoom\fP"
.br
.ti -1c
.RI "UIText \fBtextName\fP"
.br
.ti -1c
.RI "UIImage \fBbg\fP"
.br
.ti -1c
.RI "\fBPoint\fP \fBpoint\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "bool \fBIsActive\fP\fR [get]\fP"
.br
.in -1c

Properties inherited from \fBELayer\fP
.in +1c
.ti -1c
.RI "static \fBCore\fP \fBcore\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGame\fP \fBgame\fP\fR [get]\fP"
.br
.ti -1c
.RI "static bool \fBAdvMode\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBPlayer\fP \fBplayer\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBChara\fP \fBpc\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFaction\fP \fBHome\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBUI\fP \fBui\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBMap\fP \fB_map\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBZone\fP \fB_zone\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBScene\fP \fBscene\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBBaseGameScreen\fP \fBscreen\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBCoreConfig\fP \fBconfig\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameSetting\fP \fBsetting\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBColorProfile\fP \fBColors\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBsources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBWorld\fP \fBworld\fP\fR [get]\fP"
.br
.ti -1c
.RI "static SoundManager \fBSound\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBCoreDebug\fP \fBdebug\fP\fR [get]\fP"
.br
.ti -1c
.RI "bool \fBIsFloat\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual string \fBIdHelp\fP\fR [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Static Public Member Functions inherited from \fBELayer\fP
.in +1c
.ti -1c
.RI "static int \fBrnd\fP (int a)"
.br
.in -1c

Protected Member Functions inherited from \fBELayer\fP
.in +1c
.ti -1c
.RI "override void \fB_Close\fP ()"
.br
.ti -1c
.RI "override void \fBKill\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB7\fP of file \fBUIInspector\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "unsafe void UIInspector\&.DrawHighlight (\fBIInspect\fP i, bool selected = \fRfalse\fP)"

.PP
Definition at line \fB185\fP of file \fBUIInspector\&.cs\fP\&.
.SS "void UIInspector\&.Hide ()"

.PP
Definition at line \fB30\fP of file \fBUIInspector\&.cs\fP\&.
.SS "void UIInspector\&.Inspect (\fBIInspect\fP newTarget)"

.PP
Definition at line \fB53\fP of file \fBUIInspector\&.cs\fP\&.
.SS "void UIInspector\&.Inspect (\fBInspectGroup\fP g)"

.PP
Definition at line \fB64\fP of file \fBUIInspector\&.cs\fP\&.
.SS "bool UIInspector\&.InspectUnderMouse ()"

.PP
Definition at line \fB38\fP of file \fBUIInspector\&.cs\fP\&.
.SS "void UIInspector\&.OnUpdate ()"

.PP
Definition at line \fB85\fP of file \fBUIInspector\&.cs\fP\&.
.SS "void UIInspector\&.Refresh ()"

.PP
Definition at line \fB103\fP of file \fBUIInspector\&.cs\fP\&.
.SS "void UIInspector\&.SetVisible (bool enable)"

.PP
Definition at line \fB20\fP of file \fBUIInspector\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "UIImage UIInspector\&.bg"

.PP
Definition at line \fB288\fP of file \fBUIInspector\&.cs\fP\&.
.SS "\fBInspectGroup\fP UIInspector\&.group"

.PP
Definition at line \fB249\fP of file \fBUIInspector\&.cs\fP\&.
.SS "LayoutGroup UIInspector\&.layoutBody"

.PP
Definition at line \fB252\fP of file \fBUIInspector\&.cs\fP\&.
.SS "LayoutGroup UIInspector\&.layoutButtons"

.PP
Definition at line \fB255\fP of file \fBUIInspector\&.cs\fP\&.
.SS "Vector3 UIInspector\&.modPos"

.PP
Definition at line \fB264\fP of file \fBUIInspector\&.cs\fP\&.
.SS "UIButton UIInspector\&.mold"

.PP
Definition at line \fB258\fP of file \fBUIInspector\&.cs\fP\&.
.SS "UINote UIInspector\&.note"

.PP
Definition at line \fB279\fP of file \fBUIInspector\&.cs\fP\&.
.SS "UINote UIInspector\&.noteRoom"

.PP
Definition at line \fB282\fP of file \fBUIInspector\&.cs\fP\&.
.SS "Vector3 UIInspector\&.offset"

.PP
Definition at line \fB261\fP of file \fBUIInspector\&.cs\fP\&.
.SS "\fBPoint\fP UIInspector\&.point"

.PP
Definition at line \fB291\fP of file \fBUIInspector\&.cs\fP\&.
.SS "RectTransform UIInspector\&.rectInfo"

.PP
Definition at line \fB273\fP of file \fBUIInspector\&.cs\fP\&.
.SS "RectTransform UIInspector\&.rectRoom"

.PP
Definition at line \fB276\fP of file \fBUIInspector\&.cs\fP\&.
.SS "SoundData UIInspector\&.soundPop"

.PP
Definition at line \fB267\fP of file \fBUIInspector\&.cs\fP\&.
.SS "UIText UIInspector\&.textName"

.PP
Definition at line \fB285\fP of file \fBUIInspector\&.cs\fP\&.
.SS "\fBWindowChara\fP UIInspector\&.windowChara"

.PP
Definition at line \fB270\fP of file \fBUIInspector\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "bool UIInspector\&.IsActive\fR [get]\fP"

.PP
Definition at line \fB11\fP of file \fBUIInspector\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
