.TH "UIInventory.Tab" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UIInventory.Tab
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBCard\fP \fBdest\fP"
.br
.ti -1c
.RI "\fBInvOwner\fP \fBowner\fP"
.br
.ti -1c
.RI "UIInventory\&.Mode \fBmode\fP"
.br
.ti -1c
.RI "UIInventory\&.SubMode \fBsubMode\fP"
.br
.ti -1c
.RI "string \fBtextTab\fP"
.br
.ti -1c
.RI "bool \fBsmallTab\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB1576\fP of file \fBUIInventory\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBCard\fP UIInventory\&.Tab\&.dest"

.PP
Definition at line \fB1579\fP of file \fBUIInventory\&.cs\fP\&.
.SS "UIInventory\&.Mode UIInventory\&.Tab\&.mode"

.PP
Definition at line \fB1585\fP of file \fBUIInventory\&.cs\fP\&.
.SS "\fBInvOwner\fP UIInventory\&.Tab\&.owner"

.PP
Definition at line \fB1582\fP of file \fBUIInventory\&.cs\fP\&.
.SS "bool UIInventory\&.Tab\&.smallTab"

.PP
Definition at line \fB1594\fP of file \fBUIInventory\&.cs\fP\&.
.SS "UIInventory\&.SubMode UIInventory\&.Tab\&.subMode"

.PP
Definition at line \fB1588\fP of file \fBUIInventory\&.cs\fP\&.
.SS "string UIInventory\&.Tab\&.textTab"

.PP
Definition at line \fB1591\fP of file \fBUIInventory\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
