.TH "UIInventory.Transaction" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UIInventory.Transaction
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBThing\fP \fBthing\fP"
.br
.ti -1c
.RI "int \fBnum\fP"
.br
.ti -1c
.RI "int \fBprice\fP"
.br
.ti -1c
.RI "UIInventory\&.Mode \fBmode\fP"
.br
.ti -1c
.RI "\fBCard\fP \fBfrom\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB1480\fP of file \fBUIInventory\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBCard\fP UIInventory\&.Transaction\&.from"

.PP
Definition at line \fB1495\fP of file \fBUIInventory\&.cs\fP\&.
.SS "UIInventory\&.Mode UIInventory\&.Transaction\&.mode"

.PP
Definition at line \fB1492\fP of file \fBUIInventory\&.cs\fP\&.
.SS "int UIInventory\&.Transaction\&.num"

.PP
Definition at line \fB1486\fP of file \fBUIInventory\&.cs\fP\&.
.SS "int UIInventory\&.Transaction\&.price"

.PP
Definition at line \fB1489\fP of file \fBUIInventory\&.cs\fP\&.
.SS "\fBThing\fP UIInventory\&.Transaction\&.thing"

.PP
Definition at line \fB1483\fP of file \fBUIInventory\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
