.TH "UIMultiList" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UIMultiList
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBClear\fP ()"
.br
.ti -1c
.RI "void \fBAddOwner\fP (int i, \fBListOwner\fP o)"
.br
.ti -1c
.RI "void \fBBuild\fP (UIList\&.SortMode m=UIList\&.SortMode\&.ByNone)"
.br
.ti -1c
.RI "void \fBRefresh\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "List< \fBListOwner\fP > \fBowners\fP = new List<\fBListOwner\fP>()"
.br
.ti -1c
.RI "Layer \fBlayer\fP"
.br
.ti -1c
.RI "Window[] \fBwindows\fP"
.br
.ti -1c
.RI "UIList[] \fBlists\fP"
.br
.ti -1c
.RI "UIHeader[] \fBheaders\fP"
.br
.ti -1c
.RI "bool \fBDouble\fP"
.br
.ti -1c
.RI "bool \fBaddTab\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB6\fP of file \fBUIMultiList\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void UIMultiList\&.AddOwner (int i, \fBListOwner\fP o)"

.PP
Definition at line \fB15\fP of file \fBUIMultiList\&.cs\fP\&.
.SS "void UIMultiList\&.Build (UIList\&.SortMode m = \fRUIList::SortMode::ByNone\fP)"

.PP
Definition at line \fB32\fP of file \fBUIMultiList\&.cs\fP\&.
.SS "void UIMultiList\&.Clear ()"

.PP
Definition at line \fB9\fP of file \fBUIMultiList\&.cs\fP\&.
.SS "void UIMultiList\&.Refresh ()"

.PP
Definition at line \fB46\fP of file \fBUIMultiList\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "bool UIMultiList\&.addTab"

.PP
Definition at line \fB73\fP of file \fBUIMultiList\&.cs\fP\&.
.SS "bool UIMultiList\&.Double"

.PP
Definition at line \fB70\fP of file \fBUIMultiList\&.cs\fP\&.
.SS "UIHeader [] UIMultiList\&.headers"

.PP
Definition at line \fB67\fP of file \fBUIMultiList\&.cs\fP\&.
.SS "Layer UIMultiList\&.layer"

.PP
Definition at line \fB58\fP of file \fBUIMultiList\&.cs\fP\&.
.SS "UIList [] UIMultiList\&.lists"

.PP
Definition at line \fB64\fP of file \fBUIMultiList\&.cs\fP\&.
.SS "List<\fBListOwner\fP> UIMultiList\&.owners = new List<\fBListOwner\fP>()"

.PP
Definition at line \fB55\fP of file \fBUIMultiList\&.cs\fP\&.
.SS "Window [] UIMultiList\&.windows"

.PP
Definition at line \fB61\fP of file \fBUIMultiList\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
