.TH "UIResourceTrack" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UIResourceTrack
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBEMono\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBOnActivate\fP ()"
.br
.ti -1c
.RI "void \fBOnMoveZone\fP ()"
.br
.ti -1c
.RI "void \fB_Refresh\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBRefresh\fP ()"
.br
.in -1c

Static Public Member Functions inherited from \fBEMono\fP
.in +1c
.ti -1c
.RI "static int \fBrnd\fP (int a)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "LayoutGroup \fBlayout\fP"
.br
.ti -1c
.RI "\fBButtonResourceTrack\fP \fBmold\fP"
.br
.ti -1c
.RI "UIButton \fBbuttonAdd\fP"
.br
.ti -1c
.RI "Dictionary< string, \fBButtonResourceTrack\fP > \fBdictProp\fP = new Dictionary<string, \fBButtonResourceTrack\fP>()"
.br
.ti -1c
.RI "Dictionary< string, \fBButtonResourceTrack\fP > \fBdictCat\fP = new Dictionary<string, \fBButtonResourceTrack\fP>()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static \fBUIResourceTrack\fP \fBInstance\fP"
.br
.in -1c

Static Public Attributes inherited from \fBEMono\fP
.in +1c
.ti -1c
.RI "static \fBCore\fP \fBcore\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Properties inherited from \fBEMono\fP
.in +1c
.ti -1c
.RI "static \fBGame\fP \fBgame\fP\fR [get]\fP"
.br
.ti -1c
.RI "static bool \fBAdvMode\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBPlayer\fP \fBplayer\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBChara\fP \fBpc\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBUI\fP \fBui\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBMap\fP \fB_map\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBZone\fP \fB_zone\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranchOrHomeBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFaction\fP \fBHome\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBScene\fP \fBscene\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBBaseGameScreen\fP \fBscreen\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameSetting\fP \fBsetting\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameData\fP \fBgamedata\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBColorProfile\fP \fBColors\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBWorld\fP \fBworld\fP\fR [get]\fP"
.br
.ti -1c
.RI "static SoundManager \fBSound\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBsources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBeditorSources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBCoreDebug\fP \fBdebug\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB7\fP of file \fBUIResourceTrack\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void UIResourceTrack\&._Refresh ()"

.PP
Definition at line \fB43\fP of file \fBUIResourceTrack\&.cs\fP\&.
.SS "void UIResourceTrack\&.OnActivate ()"

.PP
Definition at line \fB19\fP of file \fBUIResourceTrack\&.cs\fP\&.
.SS "void UIResourceTrack\&.OnMoveZone ()"

.PP
Definition at line \fB34\fP of file \fBUIResourceTrack\&.cs\fP\&.
.SS "static void UIResourceTrack\&.Refresh ()\fR [static]\fP"

.PP
Definition at line \fB10\fP of file \fBUIResourceTrack\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "UIButton UIResourceTrack\&.buttonAdd"

.PP
Definition at line \fB121\fP of file \fBUIResourceTrack\&.cs\fP\&.
.SS "Dictionary<string, \fBButtonResourceTrack\fP> UIResourceTrack\&.dictCat = new Dictionary<string, \fBButtonResourceTrack\fP>()"

.PP
Definition at line \fB127\fP of file \fBUIResourceTrack\&.cs\fP\&.
.SS "Dictionary<string, \fBButtonResourceTrack\fP> UIResourceTrack\&.dictProp = new Dictionary<string, \fBButtonResourceTrack\fP>()"

.PP
Definition at line \fB124\fP of file \fBUIResourceTrack\&.cs\fP\&.
.SS "\fBUIResourceTrack\fP UIResourceTrack\&.Instance\fR [static]\fP"

.PP
Definition at line \fB112\fP of file \fBUIResourceTrack\&.cs\fP\&.
.SS "LayoutGroup UIResourceTrack\&.layout"

.PP
Definition at line \fB115\fP of file \fBUIResourceTrack\&.cs\fP\&.
.SS "\fBButtonResourceTrack\fP UIResourceTrack\&.mold"

.PP
Definition at line \fB118\fP of file \fBUIResourceTrack\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
