.TH "UIRecipeInfo.RecipeVariation" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UIRecipeInfo.RecipeVariation
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBRecipe\fP \fBrecipe\fP"
.br
.ti -1c
.RI "int \fBdir\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB569\fP of file \fBUIRecipeInfo\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int UIRecipeInfo\&.RecipeVariation\&.dir"

.PP
Definition at line \fB575\fP of file \fBUIRecipeInfo\&.cs\fP\&.
.SS "\fBRecipe\fP UIRecipeInfo\&.RecipeVariation\&.recipe"

.PP
Definition at line \fB572\fP of file \fBUIRecipeInfo\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
