.TH "UndoManager.Item" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UndoManager.Item
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "int \fBCount\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "List< \fBTask\fP > \fBlist\fP = new List<\fBTask\fP>()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBname\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB99\fP of file \fBUndoManager\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "int UndoManager\&.Item\&.Count ()"

.PP
Definition at line \fB116\fP of file \fBUndoManager\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "List<\fBTask\fP> UndoManager\&.Item\&.list = new List<\fBTask\fP>()"

.PP
Definition at line \fB133\fP of file \fBUndoManager\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "string UndoManager\&.Item\&.name\fR [get]\fP"

.PP
Definition at line \fB103\fP of file \fBUndoManager\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
