.TH "UndoManager" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UndoManager
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBItem\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBValidate\fP ()"
.br
.ti -1c
.RI "void \fBNewItem\fP ()"
.br
.ti -1c
.RI "void \fBAdd\fP (\fBTask\fP t)"
.br
.ti -1c
.RI "string \fBGetText\fP ()"
.br
.ti -1c
.RI "void \fBWriteNote\fP (UINote n)"
.br
.ti -1c
.RI "void \fBPerform\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "List< \fBUndoManager\&.Item\fP > \fBitems\fP = new List<\fBUndoManager\&.Item\fP>()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBUndoManager\&.Item\fP \fBlastItem\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB5\fP of file \fBUndoManager\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void UndoManager\&.Add (\fBTask\fP t)"

.PP
Definition at line \fB40\fP of file \fBUndoManager\&.cs\fP\&.
.SS "string UndoManager\&.GetText ()"

.PP
Definition at line \fB46\fP of file \fBUndoManager\&.cs\fP\&.
.SS "void UndoManager\&.NewItem ()"

.PP
Definition at line \fB30\fP of file \fBUndoManager\&.cs\fP\&.
.SS "void UndoManager\&.Perform ()"

.PP
Definition at line \fB79\fP of file \fBUndoManager\&.cs\fP\&.
.SS "void UndoManager\&.Validate ()"

.PP
Definition at line \fB18\fP of file \fBUndoManager\&.cs\fP\&.
.SS "void UndoManager\&.WriteNote (UINote n)"

.PP
Definition at line \fB61\fP of file \fBUndoManager\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "List<\fBUndoManager\&.Item\fP> UndoManager\&.items = new List<\fBUndoManager\&.Item\fP>()"

.PP
Definition at line \fB96\fP of file \fBUndoManager\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "\fBUndoManager\&.Item\fP UndoManager\&.lastItem\fR [get]\fP"

.PP
Definition at line \fB9\fP of file \fBUndoManager\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
