.TH "Wall" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Wall
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "byte \fBid\fP"
.br
.ti -1c
.RI "byte \fBidMat\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static \fBMap\fP \fBmap\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBSourceBlock\&.Row\fP \fBsource\fP\fR [get]\fP"
.br
.ti -1c
.RI "\fBSourceMaterial\&.Row\fP \fBmat\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB4\fP of file \fBWall\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "byte Wall\&.id"

.PP
Definition at line \fB30\fP of file \fBWall\&.cs\fP\&.
.SS "byte Wall\&.idMat"

.PP
Definition at line \fB33\fP of file \fBWall\&.cs\fP\&.
.SS "\fBMap\fP Wall\&.map\fR [static]\fP"

.PP
Definition at line \fB27\fP of file \fBWall\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "\fBSourceMaterial\&.Row\fP Wall\&.mat\fR [get]\fP"

.PP
Definition at line \fB18\fP of file \fBWall\&.cs\fP\&.
.SS "\fBSourceBlock\&.Row\fP Wall\&.source\fR [get]\fP"

.PP
Definition at line \fB8\fP of file \fBWall\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
