.TH "Weather.WeatherForecast" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Weather.WeatherForecast
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBAdd\fP (Weather\&.Condition con, int h)"
.br
.ti -1c
.RI "void \fBFinish\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBDate\fP \fBdate\fP"
.br
.ti -1c
.RI "Dictionary< Weather\&.Condition, int > \fBcons\fP = new Dictionary<Weather\&.Condition, int>()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB364\fP of file \fBWeather\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Weather\&.WeatherForecast\&.Add (Weather\&.Condition con, int h)"

.PP
Definition at line \fB367\fP of file \fBWeather\&.cs\fP\&.
.SS "void Weather\&.WeatherForecast\&.Finish ()"

.PP
Definition at line \fB379\fP of file \fBWeather\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "Dictionary<Weather\&.Condition, int> Weather\&.WeatherForecast\&.cons = new Dictionary<Weather\&.Condition, int>()"

.PP
Definition at line \fB399\fP of file \fBWeather\&.cs\fP\&.
.SS "\fBDate\fP Weather\&.WeatherForecast\&.date"

.PP
Definition at line \fB396\fP of file \fBWeather\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
