.TH "Weather.Forecast" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Weather.Forecast
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBduration\fP"
.br
.ti -1c
.RI "Weather\&.Condition \fBcondition\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB331\fP of file \fBWeather\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "Weather\&.Condition Weather\&.Forecast\&.condition"

.PP
Definition at line \fB337\fP of file \fBWeather\&.cs\fP\&.
.SS "int Weather\&.Forecast\&.duration"

.PP
Definition at line \fB334\fP of file \fBWeather\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
