.TH "WidgetManager" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WidgetManager
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBEMono\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSaveData\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBOnActivateZone\fP ()"
.br
.ti -1c
.RI "void \fBOnGameInstantiated\fP ()"
.br
.ti -1c
.RI "void \fBOnKillGame\fP ()"
.br
.ti -1c
.RI "void \fBOnChangeActionMode\fP ()"
.br
.ti -1c
.RI "void \fBUpdateConfigs\fP ()"
.br
.ti -1c
.RI "void \fBActivate\fP (string id)"
.br
.ti -1c
.RI "\fBWidget\fP \fBToggle\fP (string id)"
.br
.ti -1c
.RI "\fBWidget\fP \fBToggle\fP (\fBWidget\&.Config\fP c)"
.br
.ti -1c
.RI "void \fBToggleLock\fP (\fBWidget\&.Config\fP c)"
.br
.ti -1c
.RI "\fBWidget\fP \fBActivateWidget\fP (\fBWidget\&.Config\fP c)"
.br
.ti -1c
.RI "\fBWidget\fP \fBActivateWidget\fP (string id)"
.br
.ti -1c
.RI "void \fBRefreshWidget\fP (\fBWidget\&.Config\fP c)"
.br
.ti -1c
.RI "void \fBRefreshWidget\fP (\fBWidget\fP w)"
.br
.ti -1c
.RI "\fBWidget\fP \fBGetWidget\fP (string id)"
.br
.ti -1c
.RI "void \fBDeactivateWidget\fP (string id)"
.br
.ti -1c
.RI "void \fBDeactivateWidget\fP (\fBWidget\fP w)"
.br
.ti -1c
.RI "void \fBKillWidgets\fP ()"
.br
.ti -1c
.RI "void \fBShow\fP ()"
.br
.ti -1c
.RI "void \fBHide\fP ()"
.br
.ti -1c
.RI "void \fBReset\fP (bool toggleTheme)"
.br
.ti -1c
.RI "void \fBDialogSave\fP (Action onSave=null)"
.br
.ti -1c
.RI "void \fBDialogLoad\fP (Action onLoad=null)"
.br
.ti -1c
.RI "void \fBSave\fP (string path=null)"
.br
.ti -1c
.RI "void \fBLoad\fP (bool isSubTheme, string path=null)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Dictionary< string, \fBWidget\&.Meta\fP > \fBmetaMap\fP = new Dictionary<string, \fBWidget\&.Meta\fP>()"
.br
.ti -1c
.RI "string \fBcurrentPath\fP"
.br
.ti -1c
.RI "List< \fBWidget\fP > \fBlist\fP = new List<\fBWidget\fP>()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "List< \fBWidget\&.Meta\fP > \fBmetas\fP\fR [get]\fP"
.br
.ti -1c
.RI "Dictionary< string, \fBWidget\&.Config\fP > \fBconfigs\fP\fR [get]\fP"
.br
.in -1c

Properties inherited from \fBEMono\fP
.in +1c
.ti -1c
.RI "static \fBGame\fP \fBgame\fP\fR [get]\fP"
.br
.ti -1c
.RI "static bool \fBAdvMode\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBPlayer\fP \fBplayer\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBChara\fP \fBpc\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBUI\fP \fBui\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBMap\fP \fB_map\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBZone\fP \fB_zone\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranchOrHomeBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFaction\fP \fBHome\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBScene\fP \fBscene\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBBaseGameScreen\fP \fBscreen\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameSetting\fP \fBsetting\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameData\fP \fBgamedata\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBColorProfile\fP \fBColors\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBWorld\fP \fBworld\fP\fR [get]\fP"
.br
.ti -1c
.RI "static SoundManager \fBSound\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBsources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBeditorSources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBCoreDebug\fP \fBdebug\fP\fR [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Static Public Member Functions inherited from \fBEMono\fP
.in +1c
.ti -1c
.RI "static int \fBrnd\fP (int a)"
.br
.in -1c

Static Public Attributes inherited from \fBEMono\fP
.in +1c
.ti -1c
.RI "static \fBCore\fP \fBcore\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB9\fP of file \fBWidgetManager\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void WidgetManager\&.Activate (string id)"

.PP
Definition at line \fB154\fP of file \fBWidgetManager\&.cs\fP\&.
.SS "\fBWidget\fP WidgetManager\&.ActivateWidget (string id)"

.PP
Definition at line \fB200\fP of file \fBWidgetManager\&.cs\fP\&.
.SS "\fBWidget\fP WidgetManager\&.ActivateWidget (\fBWidget\&.Config\fP c)"

.PP
Definition at line \fB194\fP of file \fBWidgetManager\&.cs\fP\&.
.SS "void WidgetManager\&.DeactivateWidget (string id)"

.PP
Definition at line \fB271\fP of file \fBWidgetManager\&.cs\fP\&.
.SS "void WidgetManager\&.DeactivateWidget (\fBWidget\fP w)"

.PP
Definition at line \fB277\fP of file \fBWidgetManager\&.cs\fP\&.
.SS "void WidgetManager\&.DialogLoad (Action onLoad = \fRnull\fP)"

.PP
Definition at line \fB367\fP of file \fBWidgetManager\&.cs\fP\&.
.SS "void WidgetManager\&.DialogSave (Action onSave = \fRnull\fP)"

.PP
Definition at line \fB345\fP of file \fBWidgetManager\&.cs\fP\&.
.SS "\fBWidget\fP WidgetManager\&.GetWidget (string id)"

.PP
Definition at line \fB258\fP of file \fBWidgetManager\&.cs\fP\&.
.SS "void WidgetManager\&.Hide ()"

.PP
Definition at line \fB312\fP of file \fBWidgetManager\&.cs\fP\&.
.SS "void WidgetManager\&.KillWidgets ()"

.PP
Definition at line \fB292\fP of file \fBWidgetManager\&.cs\fP\&.
.SS "void WidgetManager\&.Load (bool isSubTheme, string path = \fRnull\fP)"

.PP
Definition at line \fB396\fP of file \fBWidgetManager\&.cs\fP\&.
.SS "void WidgetManager\&.OnActivateZone ()"

.PP
Definition at line \fB32\fP of file \fBWidgetManager\&.cs\fP\&.
.SS "void WidgetManager\&.OnChangeActionMode ()"

.PP
Definition at line \fB136\fP of file \fBWidgetManager\&.cs\fP\&.
.SS "void WidgetManager\&.OnGameInstantiated ()"

.PP
Definition at line \fB62\fP of file \fBWidgetManager\&.cs\fP\&.
.SS "void WidgetManager\&.OnKillGame ()"

.PP
Definition at line \fB130\fP of file \fBWidgetManager\&.cs\fP\&.
.SS "void WidgetManager\&.RefreshWidget (\fBWidget\fP w)"

.PP
Definition at line \fB248\fP of file \fBWidgetManager\&.cs\fP\&.
.SS "void WidgetManager\&.RefreshWidget (\fBWidget\&.Config\fP c)"

.PP
Definition at line \fB242\fP of file \fBWidgetManager\&.cs\fP\&.
.SS "void WidgetManager\&.Reset (bool toggleTheme)"

.PP
Definition at line \fB324\fP of file \fBWidgetManager\&.cs\fP\&.
.SS "void WidgetManager\&.Save (string path = \fRnull\fP)"

.PP
Definition at line \fB385\fP of file \fBWidgetManager\&.cs\fP\&.
.SS "void WidgetManager\&.Show ()"

.PP
Definition at line \fB300\fP of file \fBWidgetManager\&.cs\fP\&.
.SS "\fBWidget\fP WidgetManager\&.Toggle (string id)"

.PP
Definition at line \fB163\fP of file \fBWidgetManager\&.cs\fP\&.
.SS "\fBWidget\fP WidgetManager\&.Toggle (\fBWidget\&.Config\fP c)"

.PP
Definition at line \fB175\fP of file \fBWidgetManager\&.cs\fP\&.
.SS "void WidgetManager\&.ToggleLock (\fBWidget\&.Config\fP c)"

.PP
Definition at line \fB187\fP of file \fBWidgetManager\&.cs\fP\&.
.SS "void WidgetManager\&.UpdateConfigs ()"

.PP
Definition at line \fB145\fP of file \fBWidgetManager\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "string WidgetManager\&.currentPath"

.PP
Definition at line \fB418\fP of file \fBWidgetManager\&.cs\fP\&.
.SS "List<\fBWidget\fP> WidgetManager\&.list = new List<\fBWidget\fP>()"

.PP
Definition at line \fB422\fP of file \fBWidgetManager\&.cs\fP\&.
.SS "Dictionary<string, \fBWidget\&.Meta\fP> WidgetManager\&.metaMap = new Dictionary<string, \fBWidget\&.Meta\fP>()"

.PP
Definition at line \fB415\fP of file \fBWidgetManager\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "Dictionary<string, \fBWidget\&.Config\fP> WidgetManager\&.configs\fR [get]\fP"

.PP
Definition at line \fB23\fP of file \fBWidgetManager\&.cs\fP\&.
.SS "List<\fBWidget\&.Meta\fP> WidgetManager\&.metas\fR [get]\fP"

.PP
Definition at line \fB13\fP of file \fBWidgetManager\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
