.TH "Widget.Meta" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Widget.Meta
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override string \fBToString\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBid\fP"
.br
.ti -1c
.RI "bool \fBenabled\fP"
.br
.ti -1c
.RI "bool \fBlocked\fP"
.br
.ti -1c
.RI "bool \fBdebugOnly\fP"
.br
.ti -1c
.RI "bool \fBsystem\fP"
.br
.ti -1c
.RI "Widget\&.WidgetType \fBtype\fP"
.br
.ti -1c
.RI "GameMode \fBmode\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB731\fP of file \fBWidget\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override string Widget\&.Meta\&.ToString ()"

.PP
Definition at line \fB734\fP of file \fBWidget\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "bool Widget\&.Meta\&.debugOnly"

.PP
Definition at line \fB749\fP of file \fBWidget\&.cs\fP\&.
.SS "bool Widget\&.Meta\&.enabled"

.PP
Definition at line \fB743\fP of file \fBWidget\&.cs\fP\&.
.SS "string Widget\&.Meta\&.id"

.PP
Definition at line \fB740\fP of file \fBWidget\&.cs\fP\&.
.SS "bool Widget\&.Meta\&.locked"

.PP
Definition at line \fB746\fP of file \fBWidget\&.cs\fP\&.
.SS "GameMode Widget\&.Meta\&.mode"

.PP
Definition at line \fB758\fP of file \fBWidget\&.cs\fP\&.
.SS "bool Widget\&.Meta\&.system"

.PP
Definition at line \fB752\fP of file \fBWidget\&.cs\fP\&.
.SS "Widget\&.WidgetType Widget\&.Meta\&.type"

.PP
Definition at line \fB755\fP of file \fBWidget\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
