.TH "WidgetSticky.Extra" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WidgetSticky.Extra
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBshowDate\fP"
.br
.ti -1c
.RI "bool \fBshowText\fP"
.br
.ti -1c
.RI "bool \fBshowNerun\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB148\fP of file \fBWidgetSticky\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "bool WidgetSticky\&.Extra\&.showDate"

.PP
Definition at line \fB151\fP of file \fBWidgetSticky\&.cs\fP\&.
.SS "bool WidgetSticky\&.Extra\&.showNerun"

.PP
Definition at line \fB157\fP of file \fBWidgetSticky\&.cs\fP\&.
.SS "bool WidgetSticky\&.Extra\&.showText"

.PP
Definition at line \fB154\fP of file \fBWidgetSticky\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
