.TH "WidgetStats" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WidgetStats
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBBaseWidgetNotice\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fB_OnActivate\fP ()"
.br
.ti -1c
.RI "override void \fBOnRefresh\fP ()"
.br
.in -1c

Public Member Functions inherited from \fBBaseWidgetNotice\fP
.in +1c
.ti -1c
.RI "override void \fBOnActivate\fP ()"
.br
.ti -1c
.RI "void \fB_RefreshAll\fP ()"
.br
.ti -1c
.RI "\fBItemNotice\fP \fBAdd\fP (\fBBaseNotification\fP n, Transform parent=null)"
.br
.ti -1c
.RI "void \fBRemove\fP (\fBBaseNotification\fP n)"
.br
.ti -1c
.RI "override void \fBOnFlip\fP ()"
.br
.ti -1c
.RI "override void \fBOnSetContextMenu\fP (UIContextMenu m)"
.br
.ti -1c
.RI "void \fBRefreshLayout\fP ()"
.br
.ti -1c
.RI "override void \fBOnApplySkin\fP ()"
.br
.in -1c

Public Member Functions inherited from \fBWidget\fP
.in +1c
.ti -1c
.RI "void \fBTest\fP ()"
.br
.ti -1c
.RI "bool \fBIsInRightMode\fP ()"
.br
.ti -1c
.RI "void \fBActivate\fP ()"
.br
.ti -1c
.RI "virtual object \fBCreateExtra\fP ()"
.br
.ti -1c
.RI "void \fBDeactivate\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnDeactivate\fP ()"
.br
.ti -1c
.RI "void \fBClose\fP ()"
.br
.ti -1c
.RI "void \fBReactivate\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnManagerActivate\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnManagerDeactivate\fP ()"
.br
.ti -1c
.RI "void \fBSetAnchor\fP (RectPosition p)"
.br
.ti -1c
.RI "void \fBSetPivot\fP (RectPosition p)"
.br
.ti -1c
.RI "virtual void \fBOnChangePivot\fP ()"
.br
.ti -1c
.RI "void \fBUpdateConfig\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnUpdateConfig\fP ()"
.br
.ti -1c
.RI "void \fBClampToScreen\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnChangeResolution\fP ()"
.br
.ti -1c
.RI "void \fBOnChangePosition\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnChangeActionMode\fP ()"
.br
.ti -1c
.RI "bool \fBIsAlignTop\fP ()"
.br
.ti -1c
.RI "Layer \fBAddLayer\fP (Layer l, Transform trans)"
.br
.ti -1c
.RI "void \fBRefreshTipPivotPosition\fP ()"
.br
.ti -1c
.RI "SkinSet \fBGetSkin\fP ()"
.br
.ti -1c
.RI "SkinConfig \fBGetSkinConfig\fP ()"
.br
.ti -1c
.RI "void \fBSetSkin\fP (int id, int v=0)"
.br
.ti -1c
.RI "void \fBTestSkin\fP ()"
.br
.ti -1c
.RI "virtual void \fBApplySkin\fP ()"
.br
.ti -1c
.RI "void \fBInstantiateDeco\fP (SkinDeco deco)"
.br
.ti -1c
.RI "void \fBAddDeco\fP (SkinDeco deco)"
.br
.ti -1c
.RI "void \fBRemoveDeco\fP (SkinDeco deco)"
.br
.ti -1c
.RI "virtual bool \fBCanShowContextMenu\fP ()"
.br
.ti -1c
.RI "void \fBShowContextMenu\fP ()"
.br
.ti -1c
.RI "void \fBSetBaseContextMenu\fP (UIContextMenu m)"
.br
.ti -1c
.RI "void \fBSetGridContextMenu\fP (UIContextMenu m)"
.br
.ti -1c
.RI "void \fBSoundActivate\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBRefreshAll\fP ()"
.br
.in -1c

Static Public Member Functions inherited from \fBEMono\fP
.in +1c
.ti -1c
.RI "static int \fBrnd\fP (int a)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "List< \fBNotificationCondition\fP > \fBconditions\fP = new List<\fBNotificationCondition\fP>()"
.br
.ti -1c
.RI "\fBItemNotice\fP \fBmoldBuff\fP"
.br
.ti -1c
.RI "\fBItemNotice\fP \fBmoldStance\fP"
.br
.in -1c

Public Attributes inherited from \fBBaseWidgetNotice\fP
.in +1c
.ti -1c
.RI "Sprite[] \fBsprites\fP"
.br
.ti -1c
.RI "List< \fBBaseNotification\fP > \fBlist\fP = new List<\fBBaseNotification\fP>()"
.br
.ti -1c
.RI "VerticalLayoutGroup \fBlayout\fP"
.br
.ti -1c
.RI "VerticalLayoutGroup \fBlayout2\fP"
.br
.ti -1c
.RI "\fBItemNotice\fP \fBmold\fP"
.br
.in -1c

Public Attributes inherited from \fBWidget\fP
.in +1c
.ti -1c
.RI "Image \fBimageBG\fP"
.br
.ti -1c
.RI "SoundData \fBsoundActivate\fP"
.br
.ti -1c
.RI "UIDragPanel \fBdragPanel\fP"
.br
.ti -1c
.RI "RectTransform \fBtipPivotLeft\fP"
.br
.ti -1c
.RI "RectTransform \fBtipPivotRight\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static \fBWidgetStats\fP \fBInstance\fP"
.br
.in -1c

Static Public Attributes inherited from \fBEMono\fP
.in +1c
.ti -1c
.RI "static \fBCore\fP \fBcore\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Public Types inherited from \fBWidget\fP
.in +1c
.ti -1c
.RI "enum \fBWidgetType\fP { \fBDefault\fP, \fBZoomMenu\fP }"
.br
.ti -1c
.RI "enum \fBState\fP { \fBActive\fP, \fBInactive\fP }"
.br
.in -1c

Protected Member Functions inherited from \fBWidget\fP
.in +1c
.ti -1c
.RI "void \fBClampToScreenEnsured\fP (Component c, Vector2 anchoredPos)"
.br
.ti -1c
.RI "void \fBClampToScreen\fP (RectTransform rect, float margin=10f)"
.br
.in -1c

Protected Attributes inherited from \fBWidget\fP
.in +1c
.ti -1c
.RI "bool \fBflip\fP"
.br
.in -1c

Properties inherited from \fBWidget\fP
.in +1c
.ti -1c
.RI "string \fBID\fP\fR [get]\fP"
.br
.ti -1c
.RI "\fBWidget\&.Config\fP \fBconfig\fP\fR [get]\fP"
.br
.ti -1c
.RI "SkinRoot \fBskinRoot\fP\fR [get]\fP"
.br
.ti -1c
.RI "bool \fBIsSealed\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBShowStyleMenu\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBAlwaysTop\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBIsStaticPosition\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBAlwaysBottom\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual Type \fBSetSiblingAfter\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBShowInBuildMode\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBRightClickToClose\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBAllowRightClickToClose\fP\fR [get]\fP"
.br
.in -1c

Properties inherited from \fBEMono\fP
.in +1c
.ti -1c
.RI "static \fBGame\fP \fBgame\fP\fR [get]\fP"
.br
.ti -1c
.RI "static bool \fBAdvMode\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBPlayer\fP \fBplayer\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBChara\fP \fBpc\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBUI\fP \fBui\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBMap\fP \fB_map\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBZone\fP \fB_zone\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranchOrHomeBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFaction\fP \fBHome\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBScene\fP \fBscene\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBBaseGameScreen\fP \fBscreen\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameSetting\fP \fBsetting\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameData\fP \fBgamedata\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBColorProfile\fP \fBColors\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBWorld\fP \fBworld\fP\fR [get]\fP"
.br
.ti -1c
.RI "static SoundManager \fBSound\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBsources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBeditorSources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBCoreDebug\fP \fBdebug\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB5\fP of file \fBWidgetStats\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void WidgetStats\&._OnActivate ()\fR [virtual]\fP"

.PP
Reimplemented from \fBBaseWidgetNotice\fP\&.
.PP
Definition at line \fB18\fP of file \fBWidgetStats\&.cs\fP\&.
.SS "override void WidgetStats\&.OnRefresh ()\fR [virtual]\fP"

.PP
Reimplemented from \fBBaseWidgetNotice\fP\&.
.PP
Definition at line \fB46\fP of file \fBWidgetStats\&.cs\fP\&.
.SS "static void WidgetStats\&.RefreshAll ()\fR [static]\fP"

.PP
Definition at line \fB8\fP of file \fBWidgetStats\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "List<\fBNotificationCondition\fP> WidgetStats\&.conditions = new List<\fBNotificationCondition\fP>()"

.PP
Definition at line \fB86\fP of file \fBWidgetStats\&.cs\fP\&.
.SS "\fBWidgetStats\fP WidgetStats\&.Instance\fR [static]\fP"

.PP
Definition at line \fB83\fP of file \fBWidgetStats\&.cs\fP\&.
.SS "\fBItemNotice\fP WidgetStats\&.moldBuff"

.PP
Definition at line \fB89\fP of file \fBWidgetStats\&.cs\fP\&.
.SS "\fBItemNotice\fP WidgetStats\&.moldStance"

.PP
Definition at line \fB92\fP of file \fBWidgetStats\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
