.TH "WidgetExp.Extra" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WidgetExp.Extra
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBlv\fP"
.br
.ti -1c
.RI "bool \fBknowledge\fP"
.br
.ti -1c
.RI "bool \fBinfluence\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB78\fP of file \fBWidgetExp\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "bool WidgetExp\&.Extra\&.influence"

.PP
Definition at line \fB87\fP of file \fBWidgetExp\&.cs\fP\&.
.SS "bool WidgetExp\&.Extra\&.knowledge"

.PP
Definition at line \fB84\fP of file \fBWidgetExp\&.cs\fP\&.
.SS "bool WidgetExp\&.Extra\&.lv"

.PP
Definition at line \fB81\fP of file \fBWidgetExp\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
