.TH "WidgetRoster.Extra" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WidgetRoster.Extra
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBwidth\fP = 40"
.br
.ti -1c
.RI "int \fBmargin\fP"
.br
.ti -1c
.RI "bool \fBvertical\fP"
.br
.ti -1c
.RI "bool \fBpc\fP"
.br
.ti -1c
.RI "bool \fBportrait\fP"
.br
.ti -1c
.RI "bool \fBreverse\fP"
.br
.ti -1c
.RI "bool \fBonlyName\fP"
.br
.ti -1c
.RI "bool \fBshowHP\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB241\fP of file \fBWidgetRoster\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int WidgetRoster\&.Extra\&.margin"

.PP
Definition at line \fB249\fP of file \fBWidgetRoster\&.cs\fP\&.
.SS "bool WidgetRoster\&.Extra\&.onlyName"

.PP
Definition at line \fB269\fP of file \fBWidgetRoster\&.cs\fP\&.
.SS "bool WidgetRoster\&.Extra\&.pc"

.PP
Definition at line \fB257\fP of file \fBWidgetRoster\&.cs\fP\&.
.SS "bool WidgetRoster\&.Extra\&.portrait"

.PP
Definition at line \fB261\fP of file \fBWidgetRoster\&.cs\fP\&.
.SS "bool WidgetRoster\&.Extra\&.reverse"

.PP
Definition at line \fB265\fP of file \fBWidgetRoster\&.cs\fP\&.
.SS "bool WidgetRoster\&.Extra\&.showHP"

.PP
Definition at line \fB273\fP of file \fBWidgetRoster\&.cs\fP\&.
.SS "bool WidgetRoster\&.Extra\&.vertical"

.PP
Definition at line \fB253\fP of file \fBWidgetRoster\&.cs\fP\&.
.SS "int WidgetRoster\&.Extra\&.width = 40"

.PP
Definition at line \fB245\fP of file \fBWidgetRoster\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
