.TH "WidgetSideScreen.Extra" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WidgetSideScreen.Extra
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBwidth\fP"
.br
.ti -1c
.RI "int \fBheight\fP"
.br
.ti -1c
.RI "int \fBidImage\fP"
.br
.ti -1c
.RI "int \fBbgColor\fP"
.br
.ti -1c
.RI "bool \fBreverse\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB141\fP of file \fBWidgetSideScreen\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int WidgetSideScreen\&.Extra\&.bgColor"

.PP
Definition at line \fB153\fP of file \fBWidgetSideScreen\&.cs\fP\&.
.SS "int WidgetSideScreen\&.Extra\&.height"

.PP
Definition at line \fB147\fP of file \fBWidgetSideScreen\&.cs\fP\&.
.SS "int WidgetSideScreen\&.Extra\&.idImage"

.PP
Definition at line \fB150\fP of file \fBWidgetSideScreen\&.cs\fP\&.
.SS "bool WidgetSideScreen\&.Extra\&.reverse"

.PP
Definition at line \fB156\fP of file \fBWidgetSideScreen\&.cs\fP\&.
.SS "int WidgetSideScreen\&.Extra\&.width"

.PP
Definition at line \fB144\fP of file \fBWidgetSideScreen\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
