.TH "WidgetCurrentTool.Extra" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WidgetCurrentTool.Extra
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBiconSize\fP"
.br
.ti -1c
.RI "bool \fBshowShortcut\fP"
.br
.ti -1c
.RI "bool \fBtop\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB371\fP of file \fBWidgetCurrentTool\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int WidgetCurrentTool\&.Extra\&.iconSize"

.PP
Definition at line \fB374\fP of file \fBWidgetCurrentTool\&.cs\fP\&.
.SS "bool WidgetCurrentTool\&.Extra\&.showShortcut"

.PP
Definition at line \fB377\fP of file \fBWidgetCurrentTool\&.cs\fP\&.
.SS "bool WidgetCurrentTool\&.Extra\&.top"

.PP
Definition at line \fB380\fP of file \fBWidgetCurrentTool\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
