.TH "WidgetBottomBar.Extra" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WidgetBottomBar.Extra
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBwidth\fP"
.br
.ti -1c
.RI "int \fBheight\fP"
.br
.ti -1c
.RI "bool \fBsubBar\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB91\fP of file \fBWidgetBottomBar\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int WidgetBottomBar\&.Extra\&.height"

.PP
Definition at line \fB97\fP of file \fBWidgetBottomBar\&.cs\fP\&.
.SS "bool WidgetBottomBar\&.Extra\&.subBar"

.PP
Definition at line \fB100\fP of file \fBWidgetBottomBar\&.cs\fP\&.
.SS "int WidgetBottomBar\&.Extra\&.width"

.PP
Definition at line \fB94\fP of file \fBWidgetBottomBar\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
