.TH "WidgetManager.SaveData" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WidgetManager.SaveData
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Dictionary< string, \fBWidget\&.Config\fP > \fBdict\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB428\fP of file \fBWidgetManager\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "Dictionary<string, \fBWidget\&.Config\fP> WidgetManager\&.SaveData\&.dict"

.PP
Definition at line \fB431\fP of file \fBWidgetManager\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
