.TH "WidgetHP.Extra" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WidgetHP.Extra
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBlayout\fP"
.br
.ti -1c
.RI "bool \fBshowGauge\fP"
.br
.ti -1c
.RI "bool \fBshowMax\fP"
.br
.ti -1c
.RI "bool \fBstamina\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB134\fP of file \fBWidgetHP\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int WidgetHP\&.Extra\&.layout"

.PP
Definition at line \fB138\fP of file \fBWidgetHP\&.cs\fP\&.
.SS "bool WidgetHP\&.Extra\&.showGauge"

.PP
Definition at line \fB142\fP of file \fBWidgetHP\&.cs\fP\&.
.SS "bool WidgetHP\&.Extra\&.showMax"

.PP
Definition at line \fB146\fP of file \fBWidgetHP\&.cs\fP\&.
.SS "bool WidgetHP\&.Extra\&.stamina"

.PP
Definition at line \fB150\fP of file \fBWidgetHP\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
