.TH "WidgetHotbar.Extra" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WidgetHotbar.Extra
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBiconSize\fP = 2"
.br
.ti -1c
.RI "int \fBwidth\fP = 1"
.br
.ti -1c
.RI "int \fBrows\fP"
.br
.ti -1c
.RI "bool \fBshowShortcut\fP"
.br
.ti -1c
.RI "bool \fBvertical\fP"
.br
.ti -1c
.RI "bool \fBvisible\fP"
.br
.ti -1c
.RI "bool \fBalwaysShow\fP"
.br
.ti -1c
.RI "bool \fBreverse\fP"
.br
.ti -1c
.RI "bool \fBautoSize\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB772\fP of file \fBWidgetHotbar\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "bool WidgetHotbar\&.Extra\&.alwaysShow"

.PP
Definition at line \fB793\fP of file \fBWidgetHotbar\&.cs\fP\&.
.SS "bool WidgetHotbar\&.Extra\&.autoSize"

.PP
Definition at line \fB799\fP of file \fBWidgetHotbar\&.cs\fP\&.
.SS "int WidgetHotbar\&.Extra\&.iconSize = 2"

.PP
Definition at line \fB775\fP of file \fBWidgetHotbar\&.cs\fP\&.
.SS "bool WidgetHotbar\&.Extra\&.reverse"

.PP
Definition at line \fB796\fP of file \fBWidgetHotbar\&.cs\fP\&.
.SS "int WidgetHotbar\&.Extra\&.rows"

.PP
Definition at line \fB781\fP of file \fBWidgetHotbar\&.cs\fP\&.
.SS "bool WidgetHotbar\&.Extra\&.showShortcut"

.PP
Definition at line \fB784\fP of file \fBWidgetHotbar\&.cs\fP\&.
.SS "bool WidgetHotbar\&.Extra\&.vertical"

.PP
Definition at line \fB787\fP of file \fBWidgetHotbar\&.cs\fP\&.
.SS "bool WidgetHotbar\&.Extra\&.visible"

.PP
Definition at line \fB790\fP of file \fBWidgetHotbar\&.cs\fP\&.
.SS "int WidgetHotbar\&.Extra\&.width = 1"

.PP
Definition at line \fB778\fP of file \fBWidgetHotbar\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
