.TH "WidgetFeed.Extra" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WidgetFeed.Extra
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBshowChat\fP"
.br
.ti -1c
.RI "bool \fBintercept\fP"
.br
.ti -1c
.RI "int \fBstyle\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB145\fP of file \fBWidgetFeed\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "bool WidgetFeed\&.Extra\&.intercept"

.PP
Definition at line \fB151\fP of file \fBWidgetFeed\&.cs\fP\&.
.SS "bool WidgetFeed\&.Extra\&.showChat"

.PP
Definition at line \fB148\fP of file \fBWidgetFeed\&.cs\fP\&.
.SS "int WidgetFeed\&.Extra\&.style"

.PP
Definition at line \fB154\fP of file \fBWidgetFeed\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
