.TH "WidgetMinimap.Extra" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WidgetMinimap.Extra
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBrotate\fP"
.br
.ti -1c
.RI "bool \fBmonoColor\fP"
.br
.ti -1c
.RI "bool \fBlimitBounds\fP"
.br
.ti -1c
.RI "int \fBalpha\fP"
.br
.ti -1c
.RI "int \fBscale\fP"
.br
.ti -1c
.RI "int \fBwidth\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB319\fP of file \fBWidgetMinimap\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int WidgetMinimap\&.Extra\&.alpha"

.PP
Definition at line \fB331\fP of file \fBWidgetMinimap\&.cs\fP\&.
.SS "bool WidgetMinimap\&.Extra\&.limitBounds"

.PP
Definition at line \fB328\fP of file \fBWidgetMinimap\&.cs\fP\&.
.SS "bool WidgetMinimap\&.Extra\&.monoColor"

.PP
Definition at line \fB325\fP of file \fBWidgetMinimap\&.cs\fP\&.
.SS "bool WidgetMinimap\&.Extra\&.rotate"

.PP
Definition at line \fB322\fP of file \fBWidgetMinimap\&.cs\fP\&.
.SS "int WidgetMinimap\&.Extra\&.scale"

.PP
Definition at line \fB334\fP of file \fBWidgetMinimap\&.cs\fP\&.
.SS "int WidgetMinimap\&.Extra\&.width"

.PP
Definition at line \fB337\fP of file \fBWidgetMinimap\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
