.TH "WidgetStatsBar.Item" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WidgetStatsBar.Item
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "UIItem \fBcomponent\fP"
.br
.ti -1c
.RI "\fBElement\fP \fBele\fP"
.br
.ti -1c
.RI "string \fBid\fP"
.br
.ti -1c
.RI "Sprite \fBsprite\fP"
.br
.ti -1c
.RI "Func< string > \fBfunc\fP"
.br
.ti -1c
.RI "Func< FontColor > \fBfuncCol\fP"
.br
.ti -1c
.RI "Func< bool > \fBfuncShow\fP"
.br
.ti -1c
.RI "FontColor \fBlastColor\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB388\fP of file \fBWidgetStatsBar\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "UIItem WidgetStatsBar\&.Item\&.component"

.PP
Definition at line \fB391\fP of file \fBWidgetStatsBar\&.cs\fP\&.
.SS "\fBElement\fP WidgetStatsBar\&.Item\&.ele"

.PP
Definition at line \fB394\fP of file \fBWidgetStatsBar\&.cs\fP\&.
.SS "Func<string> WidgetStatsBar\&.Item\&.func"

.PP
Definition at line \fB403\fP of file \fBWidgetStatsBar\&.cs\fP\&.
.SS "Func<FontColor> WidgetStatsBar\&.Item\&.funcCol"

.PP
Definition at line \fB406\fP of file \fBWidgetStatsBar\&.cs\fP\&.
.SS "Func<bool> WidgetStatsBar\&.Item\&.funcShow"

.PP
Definition at line \fB409\fP of file \fBWidgetStatsBar\&.cs\fP\&.
.SS "string WidgetStatsBar\&.Item\&.id"

.PP
Definition at line \fB397\fP of file \fBWidgetStatsBar\&.cs\fP\&.
.SS "FontColor WidgetStatsBar\&.Item\&.lastColor"

.PP
Definition at line \fB412\fP of file \fBWidgetStatsBar\&.cs\fP\&.
.SS "Sprite WidgetStatsBar\&.Item\&.sprite"

.PP
Definition at line \fB400\fP of file \fBWidgetStatsBar\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
