.TH "WidgetStatsBar.Extra" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WidgetStatsBar.Extra
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBattributes\fP"
.br
.ti -1c
.RI "bool \fBmoney\fP"
.br
.ti -1c
.RI "bool \fBmoney2\fP"
.br
.ti -1c
.RI "bool \fBplat\fP"
.br
.ti -1c
.RI "bool \fBmedal\fP"
.br
.ti -1c
.RI "bool \fBkarma\fP"
.br
.ti -1c
.RI "bool \fBmood\fP"
.br
.ti -1c
.RI "bool \fBweight\fP"
.br
.ti -1c
.RI "bool \fBinfluence\fP"
.br
.ti -1c
.RI "bool \fBmaxAlly\fP"
.br
.ti -1c
.RI "bool \fBhearthLv\fP"
.br
.ti -1c
.RI "bool \fBtourism_value\fP"
.br
.ti -1c
.RI "bool \fBfame\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB416\fP of file \fBWidgetStatsBar\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "bool WidgetStatsBar\&.Extra\&.attributes"

.PP
Definition at line \fB419\fP of file \fBWidgetStatsBar\&.cs\fP\&.
.SS "bool WidgetStatsBar\&.Extra\&.fame"

.PP
Definition at line \fB455\fP of file \fBWidgetStatsBar\&.cs\fP\&.
.SS "bool WidgetStatsBar\&.Extra\&.hearthLv"

.PP
Definition at line \fB449\fP of file \fBWidgetStatsBar\&.cs\fP\&.
.SS "bool WidgetStatsBar\&.Extra\&.influence"

.PP
Definition at line \fB443\fP of file \fBWidgetStatsBar\&.cs\fP\&.
.SS "bool WidgetStatsBar\&.Extra\&.karma"

.PP
Definition at line \fB434\fP of file \fBWidgetStatsBar\&.cs\fP\&.
.SS "bool WidgetStatsBar\&.Extra\&.maxAlly"

.PP
Definition at line \fB446\fP of file \fBWidgetStatsBar\&.cs\fP\&.
.SS "bool WidgetStatsBar\&.Extra\&.medal"

.PP
Definition at line \fB431\fP of file \fBWidgetStatsBar\&.cs\fP\&.
.SS "bool WidgetStatsBar\&.Extra\&.money"

.PP
Definition at line \fB422\fP of file \fBWidgetStatsBar\&.cs\fP\&.
.SS "bool WidgetStatsBar\&.Extra\&.money2"

.PP
Definition at line \fB425\fP of file \fBWidgetStatsBar\&.cs\fP\&.
.SS "bool WidgetStatsBar\&.Extra\&.mood"

.PP
Definition at line \fB437\fP of file \fBWidgetStatsBar\&.cs\fP\&.
.SS "bool WidgetStatsBar\&.Extra\&.plat"

.PP
Definition at line \fB428\fP of file \fBWidgetStatsBar\&.cs\fP\&.
.SS "bool WidgetStatsBar\&.Extra\&.tourism_value"

.PP
Definition at line \fB452\fP of file \fBWidgetStatsBar\&.cs\fP\&.
.SS "bool WidgetStatsBar\&.Extra\&.weight"

.PP
Definition at line \fB440\fP of file \fBWidgetStatsBar\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
