.TH "WidgetDate.Extra" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WidgetDate.Extra
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBdate\fP"
.br
.ti -1c
.RI "bool \fBrealDate\fP"
.br
.ti -1c
.RI "bool \fBperiod\fP"
.br
.ti -1c
.RI "bool \fBroom\fP"
.br
.ti -1c
.RI "bool \fBclock\fP"
.br
.ti -1c
.RI "bool \fBloc\fP"
.br
.ti -1c
.RI "bool \fBweather\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB198\fP of file \fBWidgetDate\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "bool WidgetDate\&.Extra\&.clock"

.PP
Definition at line \fB213\fP of file \fBWidgetDate\&.cs\fP\&.
.SS "bool WidgetDate\&.Extra\&.date"

.PP
Definition at line \fB201\fP of file \fBWidgetDate\&.cs\fP\&.
.SS "bool WidgetDate\&.Extra\&.loc"

.PP
Definition at line \fB216\fP of file \fBWidgetDate\&.cs\fP\&.
.SS "bool WidgetDate\&.Extra\&.period"

.PP
Definition at line \fB207\fP of file \fBWidgetDate\&.cs\fP\&.
.SS "bool WidgetDate\&.Extra\&.realDate"

.PP
Definition at line \fB204\fP of file \fBWidgetDate\&.cs\fP\&.
.SS "bool WidgetDate\&.Extra\&.room"

.PP
Definition at line \fB210\fP of file \fBWidgetDate\&.cs\fP\&.
.SS "bool WidgetDate\&.Extra\&.weather"

.PP
Definition at line \fB219\fP of file \fBWidgetDate\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
