.TH "WidgetSearch" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WidgetSearch
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBWidgetCodex\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnActivate\fP ()"
.br
.ti -1c
.RI "override bool \fBCheckClose\fP ()"
.br
.ti -1c
.RI "override void \fBSearch\fP (string s)"
.br
.ti -1c
.RI "override void \fBRefreshList\fP ()"
.br
.ti -1c
.RI "override void \fBOnDeactivate\fP ()"
.br
.in -1c

Public Member Functions inherited from \fBWidgetCodex\fP
.in +1c
.ti -1c
.RI "void \fBClear\fP ()"
.br
.in -1c

Public Member Functions inherited from \fBWidget\fP
.in +1c
.ti -1c
.RI "void \fBTest\fP ()"
.br
.ti -1c
.RI "bool \fBIsInRightMode\fP ()"
.br
.ti -1c
.RI "void \fBActivate\fP ()"
.br
.ti -1c
.RI "virtual object \fBCreateExtra\fP ()"
.br
.ti -1c
.RI "void \fBDeactivate\fP ()"
.br
.ti -1c
.RI "void \fBClose\fP ()"
.br
.ti -1c
.RI "void \fBReactivate\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnManagerActivate\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnManagerDeactivate\fP ()"
.br
.ti -1c
.RI "void \fBSetAnchor\fP (RectPosition p)"
.br
.ti -1c
.RI "void \fBSetPivot\fP (RectPosition p)"
.br
.ti -1c
.RI "virtual void \fBOnChangePivot\fP ()"
.br
.ti -1c
.RI "void \fBUpdateConfig\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnUpdateConfig\fP ()"
.br
.ti -1c
.RI "void \fBClampToScreen\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnChangeResolution\fP ()"
.br
.ti -1c
.RI "void \fBOnChangePosition\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnChangeActionMode\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnFlip\fP ()"
.br
.ti -1c
.RI "bool \fBIsAlignTop\fP ()"
.br
.ti -1c
.RI "Layer \fBAddLayer\fP (Layer l, Transform trans)"
.br
.ti -1c
.RI "void \fBRefreshTipPivotPosition\fP ()"
.br
.ti -1c
.RI "SkinSet \fBGetSkin\fP ()"
.br
.ti -1c
.RI "SkinConfig \fBGetSkinConfig\fP ()"
.br
.ti -1c
.RI "void \fBSetSkin\fP (int id, int v=0)"
.br
.ti -1c
.RI "void \fBTestSkin\fP ()"
.br
.ti -1c
.RI "virtual void \fBApplySkin\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnApplySkin\fP ()"
.br
.ti -1c
.RI "void \fBInstantiateDeco\fP (SkinDeco deco)"
.br
.ti -1c
.RI "void \fBAddDeco\fP (SkinDeco deco)"
.br
.ti -1c
.RI "void \fBRemoveDeco\fP (SkinDeco deco)"
.br
.ti -1c
.RI "virtual bool \fBCanShowContextMenu\fP ()"
.br
.ti -1c
.RI "void \fBShowContextMenu\fP ()"
.br
.ti -1c
.RI "void \fBSetBaseContextMenu\fP (UIContextMenu m)"
.br
.ti -1c
.RI "virtual void \fBOnSetContextMenu\fP (UIContextMenu m)"
.br
.ti -1c
.RI "void \fBSetGridContextMenu\fP (UIContextMenu m)"
.br
.ti -1c
.RI "void \fBSoundActivate\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "HashSet< \fBCard\fP > \fBcards\fP = new HashSet<\fBCard\fP>()"
.br
.ti -1c
.RI "CanvasGroup \fBcgResult\fP"
.br
.in -1c

Public Attributes inherited from \fBWidgetCodex\fP
.in +1c
.ti -1c
.RI "InputField \fBfield\fP"
.br
.ti -1c
.RI "\fBWordSearch\fP \fBsearch\fP = new \fBWordSearch\fP()"
.br
.ti -1c
.RI "UIDynamicList \fBlist\fP"
.br
.ti -1c
.RI "HashSet< \fBRecipe\fP > \fBrecipes\fP = new HashSet<\fBRecipe\fP>()"
.br
.ti -1c
.RI "string \fBlastSearch\fP"
.br
.ti -1c
.RI "UIButton \fBbuttonClear\fP"
.br
.ti -1c
.RI "Transform \fBtransResult\fP"
.br
.in -1c

Public Attributes inherited from \fBWidget\fP
.in +1c
.ti -1c
.RI "Image \fBimageBG\fP"
.br
.ti -1c
.RI "SoundData \fBsoundActivate\fP"
.br
.ti -1c
.RI "UIDragPanel \fBdragPanel\fP"
.br
.ti -1c
.RI "RectTransform \fBtipPivotLeft\fP"
.br
.ti -1c
.RI "RectTransform \fBtipPivotRight\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static \fBWidgetSearch\fP \fBInstance\fP"
.br
.ti -1c
.RI "static \fBCard\fP \fBselected\fP"
.br
.in -1c

Static Public Attributes inherited from \fBEMono\fP
.in +1c
.ti -1c
.RI "static \fBCore\fP \fBcore\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override WidgetCodex\&.SearchType \fBtype\fP\fR [get]\fP"
.br
.in -1c

Properties inherited from \fBWidgetCodex\fP
.in +1c
.ti -1c
.RI "virtual WidgetCodex\&.SearchType \fBtype\fP\fR [get]\fP"
.br
.in -1c

Properties inherited from \fBWidget\fP
.in +1c
.ti -1c
.RI "string \fBID\fP\fR [get]\fP"
.br
.ti -1c
.RI "\fBWidget\&.Config\fP \fBconfig\fP\fR [get]\fP"
.br
.ti -1c
.RI "SkinRoot \fBskinRoot\fP\fR [get]\fP"
.br
.ti -1c
.RI "bool \fBIsSealed\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBShowStyleMenu\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBAlwaysTop\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBIsStaticPosition\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBAlwaysBottom\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual Type \fBSetSiblingAfter\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBShowInBuildMode\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBRightClickToClose\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBAllowRightClickToClose\fP\fR [get]\fP"
.br
.in -1c

Properties inherited from \fBEMono\fP
.in +1c
.ti -1c
.RI "static \fBGame\fP \fBgame\fP\fR [get]\fP"
.br
.ti -1c
.RI "static bool \fBAdvMode\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBPlayer\fP \fBplayer\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBChara\fP \fBpc\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBUI\fP \fBui\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBMap\fP \fB_map\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBZone\fP \fB_zone\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranchOrHomeBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFaction\fP \fBHome\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBScene\fP \fBscene\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBBaseGameScreen\fP \fBscreen\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameSetting\fP \fBsetting\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameData\fP \fBgamedata\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBColorProfile\fP \fBColors\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBWorld\fP \fBworld\fP\fR [get]\fP"
.br
.ti -1c
.RI "static SoundManager \fBSound\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBsources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBeditorSources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBCoreDebug\fP \fBdebug\fP\fR [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Public Types inherited from \fBWidgetCodex\fP
.in +1c
.ti -1c
.RI "enum \fBSearchType\fP { \fBCodex\fP, \fBSearch\fP }"
.br
.in -1c

Public Types inherited from \fBWidget\fP
.in +1c
.ti -1c
.RI "enum \fBWidgetType\fP { \fBDefault\fP, \fBZoomMenu\fP }"
.br
.ti -1c
.RI "enum \fBState\fP { \fBActive\fP, \fBInactive\fP }"
.br
.in -1c

Static Public Member Functions inherited from \fBEMono\fP
.in +1c
.ti -1c
.RI "static int \fBrnd\fP (int a)"
.br
.in -1c

Protected Member Functions inherited from \fBWidget\fP
.in +1c
.ti -1c
.RI "void \fBClampToScreenEnsured\fP (Component c, Vector2 anchoredPos)"
.br
.ti -1c
.RI "void \fBClampToScreen\fP (RectTransform rect, float margin=10f)"
.br
.in -1c

Protected Attributes inherited from \fBWidget\fP
.in +1c
.ti -1c
.RI "bool \fBflip\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB6\fP of file \fBWidgetSearch\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override bool WidgetSearch\&.CheckClose ()\fR [virtual]\fP"

.PP
Reimplemented from \fBWidgetCodex\fP\&.
.PP
Definition at line \fB28\fP of file \fBWidgetSearch\&.cs\fP\&.
.SS "override void WidgetSearch\&.OnActivate ()\fR [virtual]\fP"

.PP
Reimplemented from \fBWidgetCodex\fP\&.
.PP
Definition at line \fB19\fP of file \fBWidgetSearch\&.cs\fP\&.
.SS "override void WidgetSearch\&.OnDeactivate ()\fR [virtual]\fP"

.PP
Reimplemented from \fBWidget\fP\&.
.PP
Definition at line \fB161\fP of file \fBWidgetSearch\&.cs\fP\&.
.SS "override void WidgetSearch\&.RefreshList ()\fR [virtual]\fP"

.PP
Reimplemented from \fBWidgetCodex\fP\&.
.PP
Definition at line \fB111\fP of file \fBWidgetSearch\&.cs\fP\&.
.SS "override void WidgetSearch\&.Search (string s)\fR [virtual]\fP"

.PP
Reimplemented from \fBWidgetCodex\fP\&.
.PP
Definition at line \fB34\fP of file \fBWidgetSearch\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "HashSet<\fBCard\fP> WidgetSearch\&.cards = new HashSet<\fBCard\fP>()"

.PP
Definition at line \fB171\fP of file \fBWidgetSearch\&.cs\fP\&.
.SS "CanvasGroup WidgetSearch\&.cgResult"

.PP
Definition at line \fB177\fP of file \fBWidgetSearch\&.cs\fP\&.
.SS "\fBWidgetSearch\fP WidgetSearch\&.Instance\fR [static]\fP"

.PP
Definition at line \fB168\fP of file \fBWidgetSearch\&.cs\fP\&.
.SS "\fBCard\fP WidgetSearch\&.selected\fR [static]\fP"

.PP
Definition at line \fB174\fP of file \fBWidgetSearch\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "override WidgetCodex\&.SearchType WidgetSearch\&.type\fR [get]\fP"

.PP
Definition at line \fB10\fP of file \fBWidgetSearch\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
