.TH "WindowCharaMini" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WindowCharaMini
.SH SYNOPSIS
.br
.PP
.PP
Inherits WindowController\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetChara\fP (\fBChara\fP c)"
.br
.ti -1c
.RI "override void \fBOnSwitchContent\fP (Window window)"
.br
.ti -1c
.RI "void \fBRefresh\fP (int idTab)"
.br
.ti -1c
.RI "void \fBRefreshEquipment\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBChara\fP \fBchara\fP"
.br
.ti -1c
.RI "UIHeader \fBmoldHeader\fP"
.br
.ti -1c
.RI "UIHeader \fBmoldHeader2\fP"
.br
.ti -1c
.RI "UIText \fBtextName\fP"
.br
.ti -1c
.RI "UIText \fBtextInfo1\fP"
.br
.ti -1c
.RI "UIText \fBtextInfo2\fP"
.br
.ti -1c
.RI "UIList \fBmoldListResist\fP"
.br
.ti -1c
.RI "UIList \fBmoldListFeat\fP"
.br
.ti -1c
.RI "Transform \fBcontentList\fP"
.br
.ti -1c
.RI "UINote \fBnote\fP"
.br
.ti -1c
.RI "UIList \fBlistEq\fP"
.br
.ti -1c
.RI "Material \fBmatItem\fP"
.br
.ti -1c
.RI "Color \fBcolorUnequipped\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB7\fP of file \fBWindowCharaMini\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void WindowCharaMini\&.OnSwitchContent (Window window)"

.PP
Definition at line \fB17\fP of file \fBWindowCharaMini\&.cs\fP\&.
.SS "void WindowCharaMini\&.Refresh (int idTab)"

.PP
Definition at line \fB27\fP of file \fBWindowCharaMini\&.cs\fP\&.
.SS "void WindowCharaMini\&.RefreshEquipment ()"

.PP
Definition at line \fB264\fP of file \fBWindowCharaMini\&.cs\fP\&.
.SS "void WindowCharaMini\&.SetChara (\fBChara\fP c)"

.PP
Definition at line \fB10\fP of file \fBWindowCharaMini\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBChara\fP WindowCharaMini\&.chara"

.PP
Definition at line \fB325\fP of file \fBWindowCharaMini\&.cs\fP\&.
.SS "Color WindowCharaMini\&.colorUnequipped"

.PP
Definition at line \fB361\fP of file \fBWindowCharaMini\&.cs\fP\&.
.SS "Transform WindowCharaMini\&.contentList"

.PP
Definition at line \fB349\fP of file \fBWindowCharaMini\&.cs\fP\&.
.SS "UIList WindowCharaMini\&.listEq"

.PP
Definition at line \fB355\fP of file \fBWindowCharaMini\&.cs\fP\&.
.SS "Material WindowCharaMini\&.matItem"

.PP
Definition at line \fB358\fP of file \fBWindowCharaMini\&.cs\fP\&.
.SS "UIHeader WindowCharaMini\&.moldHeader"

.PP
Definition at line \fB328\fP of file \fBWindowCharaMini\&.cs\fP\&.
.SS "UIHeader WindowCharaMini\&.moldHeader2"

.PP
Definition at line \fB331\fP of file \fBWindowCharaMini\&.cs\fP\&.
.SS "UIList WindowCharaMini\&.moldListFeat"

.PP
Definition at line \fB346\fP of file \fBWindowCharaMini\&.cs\fP\&.
.SS "UIList WindowCharaMini\&.moldListResist"

.PP
Definition at line \fB343\fP of file \fBWindowCharaMini\&.cs\fP\&.
.SS "UINote WindowCharaMini\&.note"

.PP
Definition at line \fB352\fP of file \fBWindowCharaMini\&.cs\fP\&.
.SS "UIText WindowCharaMini\&.textInfo1"

.PP
Definition at line \fB337\fP of file \fBWindowCharaMini\&.cs\fP\&.
.SS "UIText WindowCharaMini\&.textInfo2"

.PP
Definition at line \fB340\fP of file \fBWindowCharaMini\&.cs\fP\&.
.SS "UIText WindowCharaMini\&.textName"

.PP
Definition at line \fB334\fP of file \fBWindowCharaMini\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
