.TH "WindowChara" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WindowChara
.SH SYNOPSIS
.br
.PP
.PP
Inherits WindowController\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetChara\fP (\fBChara\fP c)"
.br
.ti -1c
.RI "override void \fBOnSwitchContent\fP (Window window)"
.br
.ti -1c
.RI "void \fBSetPortraitBG\fP (int a)"
.br
.ti -1c
.RI "void \fBSetPortraitFrame\fP (int a)"
.br
.ti -1c
.RI "void \fBToggleFeatMode\fP ()"
.br
.ti -1c
.RI "void \fBRefreshFeatMode\fP ()"
.br
.ti -1c
.RI "void \fBRefresh\fP ()"
.br
.ti -1c
.RI "void \fBRefreshStatic\fP ()"
.br
.ti -1c
.RI "void \fBRefreshStatus\fP ()"
.br
.ti -1c
.RI "void \fBAddNeeds\fP (\fBStats\fP st)"
.br
.ti -1c
.RI "void \fBAddStatus\fP (\fBBaseStats\fP st)"
.br
.ti -1c
.RI "void \fBRefreshProfile\fP ()"
.br
.ti -1c
.RI "void \fBRefreshEquipment\fP (UIList list)"
.br
.ti -1c
.RI "void \fBRefreshInfo\fP ()"
.br
.ti -1c
.RI "void \fBOnClickPortrait\fP ()"
.br
.ti -1c
.RI "void \fBRefreshSkill\fP (int idTab)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBRefreshNote\fP (\fBChara\fP chara, UINote n, bool shortMode=false)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBChara\fP \fBchara\fP"
.br
.ti -1c
.RI "\fBPortrait\fP \fBportrait\fP"
.br
.ti -1c
.RI "UIText \fBtextMood\fP"
.br
.ti -1c
.RI "UIText \fBtextHealth\fP"
.br
.ti -1c
.RI "UIText \fBtextName\fP"
.br
.ti -1c
.RI "UIText \fBtextAlias\fP"
.br
.ti -1c
.RI "UIText \fBtextTitle\fP"
.br
.ti -1c
.RI "UIText \fBtextBio\fP"
.br
.ti -1c
.RI "UIText \fBtextBio2\fP"
.br
.ti -1c
.RI "UIText \fBtextBio3\fP"
.br
.ti -1c
.RI "UIText \fBtextBirthday\fP"
.br
.ti -1c
.RI "UIText \fBtextFaction\fP"
.br
.ti -1c
.RI "UIText \fBtextFaith\fP"
.br
.ti -1c
.RI "UIText \fBtextHome\fP"
.br
.ti -1c
.RI "UIText \fBtextMom\fP"
.br
.ti -1c
.RI "UIText \fBtextDad\fP"
.br
.ti -1c
.RI "UIText \fBtextBirthplace\fP"
.br
.ti -1c
.RI "UIText \fBtextLike\fP"
.br
.ti -1c
.RI "UIText \fBtextHobby\fP"
.br
.ti -1c
.RI "UIText \fBtextKarma\fP"
.br
.ti -1c
.RI "UIText \fBtextSAN\fP"
.br
.ti -1c
.RI "UIText \fBtextFame\fP"
.br
.ti -1c
.RI "UIText \fBtextMoney\fP"
.br
.ti -1c
.RI "UIText \fBtextTax\fP"
.br
.ti -1c
.RI "UIText \fBtextTerritory\fP"
.br
.ti -1c
.RI "UIText \fBtextIncome\fP"
.br
.ti -1c
.RI "UIText \fBtextAssets\fP"
.br
.ti -1c
.RI "UIText \fBtextDeposit\fP"
.br
.ti -1c
.RI "UIText \fBtextDeepest\fP"
.br
.ti -1c
.RI "UIText \fBtextCurrentZone\fP"
.br
.ti -1c
.RI "UIText \fBtextHomeZone\fP"
.br
.ti -1c
.RI "UIList \fBlistAttaribute\fP"
.br
.ti -1c
.RI "UIList \fBlistEquipment\fP"
.br
.ti -1c
.RI "UIList \fBlistEquipment2\fP"
.br
.ti -1c
.RI "UINote \fBnote\fP"
.br
.ti -1c
.RI "PUIExampleRPGStats \fBgraph\fP"
.br
.ti -1c
.RI "UIText \fBtextStability\fP"
.br
.ti -1c
.RI "UIText \fBtextLaw\fP"
.br
.ti -1c
.RI "UIText \fBtextAffection\fP"
.br
.ti -1c
.RI "UIText \fBtextDominance\fP"
.br
.ti -1c
.RI "UIText \fBtextExtroversion\fP"
.br
.ti -1c
.RI "UIText \fBtextFavArmor\fP"
.br
.ti -1c
.RI "UIText \fBtextDV\fP"
.br
.ti -1c
.RI "UIText \fBtextStyle\fP"
.br
.ti -1c
.RI "LayoutGroup \fBlayoutNeeds\fP"
.br
.ti -1c
.RI "LayoutGroup \fBlayoutStatus\fP"
.br
.ti -1c
.RI "GridLayoutGroup \fBgridEquip\fP"
.br
.ti -1c
.RI "UIScrollView \fBscrollSkill\fP"
.br
.ti -1c
.RI "\fBButtonElement\fP \fBbuttonMana\fP"
.br
.ti -1c
.RI "\fBButtonElement\fP \fBbuttonLife\fP"
.br
.ti -1c
.RI "\fBButtonElement\fP \fBbuttonVigor\fP"
.br
.ti -1c
.RI "\fBButtonElement\fP \fBbuttonSpeed\fP"
.br
.ti -1c
.RI "UIItem \fBmoldStats\fP"
.br
.ti -1c
.RI "UIItem \fBmoldNeeds\fP"
.br
.ti -1c
.RI "UIHeader \fBmoldHeader\fP"
.br
.ti -1c
.RI "UIHeader \fBmoldHeader2\fP"
.br
.ti -1c
.RI "UIHeader \fBheaderEquip\fP"
.br
.ti -1c
.RI "UIList \fBmoldListSkill\fP"
.br
.ti -1c
.RI "UIList \fBmoldListResist\fP"
.br
.ti -1c
.RI "UIList \fBmoldListFeat\fP"
.br
.ti -1c
.RI "UIList \fBmoldListFeatPurchase\fP"
.br
.ti -1c
.RI "Transform \fBcontentList\fP"
.br
.ti -1c
.RI "RectTransform \fBrectEquip\fP"
.br
.ti -1c
.RI "UIButton \fBbuttonFeatMode\fP"
.br
.ti -1c
.RI "Image \fBimageView\fP"
.br
.ti -1c
.RI "Sprite \fBmask\fP"
.br
.ti -1c
.RI "Sprite \fBmaskResist\fP"
.br
.ti -1c
.RI "Material \fBmatItem\fP"
.br
.ti -1c
.RI "Color \fBcolorUnequipped\fP"
.br
.ti -1c
.RI "Vector2 \fBequipPos\fP"
.br
.ti -1c
.RI "bool \fBfeatMode\fP"
.br
.ti -1c
.RI "float \fBbarColor1\fP"
.br
.ti -1c
.RI "float \fBbarColor2\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static \fBWindowChara\fP \fBInstance\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBBiography\fP \fBbio\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB10\fP of file \fBWindowChara\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void WindowChara\&.AddNeeds (\fBStats\fP st)"

.PP
Definition at line \fB187\fP of file \fBWindowChara\&.cs\fP\&.
.SS "void WindowChara\&.AddStatus (\fBBaseStats\fP st)"

.PP
Definition at line \fB205\fP of file \fBWindowChara\&.cs\fP\&.
.SS "void WindowChara\&.OnClickPortrait ()"

.PP
Definition at line \fB365\fP of file \fBWindowChara\&.cs\fP\&.
.SS "override void WindowChara\&.OnSwitchContent (Window window)"

.PP
Definition at line \fB46\fP of file \fBWindowChara\&.cs\fP\&.
.SS "void WindowChara\&.Refresh ()"

.PP
Definition at line \fB118\fP of file \fBWindowChara\&.cs\fP\&.
.SS "void WindowChara\&.RefreshEquipment (UIList list)"

.PP
Definition at line \fB273\fP of file \fBWindowChara\&.cs\fP\&.
.SS "void WindowChara\&.RefreshFeatMode ()"

.PP
Definition at line \fB109\fP of file \fBWindowChara\&.cs\fP\&.
.SS "void WindowChara\&.RefreshInfo ()"

.PP
Definition at line \fB352\fP of file \fBWindowChara\&.cs\fP\&.
.SS "static void WindowChara\&.RefreshNote (\fBChara\fP chara, UINote n, bool shortMode = \fRfalse\fP)\fR [static]\fP"

.PP
Definition at line \fB634\fP of file \fBWindowChara\&.cs\fP\&.
.SS "void WindowChara\&.RefreshProfile ()"

.PP
Definition at line \fB239\fP of file \fBWindowChara\&.cs\fP\&.
.SS "void WindowChara\&.RefreshSkill (int idTab)"

.PP
Definition at line \fB379\fP of file \fBWindowChara\&.cs\fP\&.
.SS "void WindowChara\&.RefreshStatic ()"

.PP
Definition at line \fB124\fP of file \fBWindowChara\&.cs\fP\&.
.SS "void WindowChara\&.RefreshStatus ()"

.PP
Definition at line \fB160\fP of file \fBWindowChara\&.cs\fP\&.
.SS "void WindowChara\&.SetChara (\fBChara\fP c)"

.PP
Definition at line \fB23\fP of file \fBWindowChara\&.cs\fP\&.
.SS "void WindowChara\&.SetPortraitBG (int a)"

.PP
Definition at line \fB76\fP of file \fBWindowChara\&.cs\fP\&.
.SS "void WindowChara\&.SetPortraitFrame (int a)"

.PP
Definition at line \fB89\fP of file \fBWindowChara\&.cs\fP\&.
.SS "void WindowChara\&.ToggleFeatMode ()"

.PP
Definition at line \fB102\fP of file \fBWindowChara\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "float WindowChara\&.barColor1"

.PP
Definition at line \fB953\fP of file \fBWindowChara\&.cs\fP\&.
.SS "float WindowChara\&.barColor2"

.PP
Definition at line \fB956\fP of file \fBWindowChara\&.cs\fP\&.
.SS "UIButton WindowChara\&.buttonFeatMode"

.PP
Definition at line \fB929\fP of file \fBWindowChara\&.cs\fP\&.
.SS "\fBButtonElement\fP WindowChara\&.buttonLife"

.PP
Definition at line \fB887\fP of file \fBWindowChara\&.cs\fP\&.
.SS "\fBButtonElement\fP WindowChara\&.buttonMana"

.PP
Definition at line \fB884\fP of file \fBWindowChara\&.cs\fP\&.
.SS "\fBButtonElement\fP WindowChara\&.buttonSpeed"

.PP
Definition at line \fB893\fP of file \fBWindowChara\&.cs\fP\&.
.SS "\fBButtonElement\fP WindowChara\&.buttonVigor"

.PP
Definition at line \fB890\fP of file \fBWindowChara\&.cs\fP\&.
.SS "\fBChara\fP WindowChara\&.chara"

.PP
Definition at line \fB740\fP of file \fBWindowChara\&.cs\fP\&.
.SS "Color WindowChara\&.colorUnequipped"

.PP
Definition at line \fB944\fP of file \fBWindowChara\&.cs\fP\&.
.SS "Transform WindowChara\&.contentList"

.PP
Definition at line \fB923\fP of file \fBWindowChara\&.cs\fP\&.
.SS "Vector2 WindowChara\&.equipPos"

.PP
Definition at line \fB947\fP of file \fBWindowChara\&.cs\fP\&.
.SS "bool WindowChara\&.featMode"

.PP
Definition at line \fB950\fP of file \fBWindowChara\&.cs\fP\&.
.SS "PUIExampleRPGStats WindowChara\&.graph"

.PP
Definition at line \fB845\fP of file \fBWindowChara\&.cs\fP\&.
.SS "GridLayoutGroup WindowChara\&.gridEquip"

.PP
Definition at line \fB878\fP of file \fBWindowChara\&.cs\fP\&.
.SS "UIHeader WindowChara\&.headerEquip"

.PP
Definition at line \fB908\fP of file \fBWindowChara\&.cs\fP\&.
.SS "Image WindowChara\&.imageView"

.PP
Definition at line \fB932\fP of file \fBWindowChara\&.cs\fP\&.
.SS "\fBWindowChara\fP WindowChara\&.Instance\fR [static]\fP"

.PP
Definition at line \fB737\fP of file \fBWindowChara\&.cs\fP\&.
.SS "LayoutGroup WindowChara\&.layoutNeeds"

.PP
Definition at line \fB872\fP of file \fBWindowChara\&.cs\fP\&.
.SS "LayoutGroup WindowChara\&.layoutStatus"

.PP
Definition at line \fB875\fP of file \fBWindowChara\&.cs\fP\&.
.SS "UIList WindowChara\&.listAttaribute"

.PP
Definition at line \fB833\fP of file \fBWindowChara\&.cs\fP\&.
.SS "UIList WindowChara\&.listEquipment"

.PP
Definition at line \fB836\fP of file \fBWindowChara\&.cs\fP\&.
.SS "UIList WindowChara\&.listEquipment2"

.PP
Definition at line \fB839\fP of file \fBWindowChara\&.cs\fP\&.
.SS "Sprite WindowChara\&.mask"

.PP
Definition at line \fB935\fP of file \fBWindowChara\&.cs\fP\&.
.SS "Sprite WindowChara\&.maskResist"

.PP
Definition at line \fB938\fP of file \fBWindowChara\&.cs\fP\&.
.SS "Material WindowChara\&.matItem"

.PP
Definition at line \fB941\fP of file \fBWindowChara\&.cs\fP\&.
.SS "UIHeader WindowChara\&.moldHeader"

.PP
Definition at line \fB902\fP of file \fBWindowChara\&.cs\fP\&.
.SS "UIHeader WindowChara\&.moldHeader2"

.PP
Definition at line \fB905\fP of file \fBWindowChara\&.cs\fP\&.
.SS "UIList WindowChara\&.moldListFeat"

.PP
Definition at line \fB917\fP of file \fBWindowChara\&.cs\fP\&.
.SS "UIList WindowChara\&.moldListFeatPurchase"

.PP
Definition at line \fB920\fP of file \fBWindowChara\&.cs\fP\&.
.SS "UIList WindowChara\&.moldListResist"

.PP
Definition at line \fB914\fP of file \fBWindowChara\&.cs\fP\&.
.SS "UIList WindowChara\&.moldListSkill"

.PP
Definition at line \fB911\fP of file \fBWindowChara\&.cs\fP\&.
.SS "UIItem WindowChara\&.moldNeeds"

.PP
Definition at line \fB899\fP of file \fBWindowChara\&.cs\fP\&.
.SS "UIItem WindowChara\&.moldStats"

.PP
Definition at line \fB896\fP of file \fBWindowChara\&.cs\fP\&.
.SS "UINote WindowChara\&.note"

.PP
Definition at line \fB842\fP of file \fBWindowChara\&.cs\fP\&.
.SS "\fBPortrait\fP WindowChara\&.portrait"

.PP
Definition at line \fB743\fP of file \fBWindowChara\&.cs\fP\&.
.SS "RectTransform WindowChara\&.rectEquip"

.PP
Definition at line \fB926\fP of file \fBWindowChara\&.cs\fP\&.
.SS "UIScrollView WindowChara\&.scrollSkill"

.PP
Definition at line \fB881\fP of file \fBWindowChara\&.cs\fP\&.
.SS "UIText WindowChara\&.textAffection"

.PP
Definition at line \fB854\fP of file \fBWindowChara\&.cs\fP\&.
.SS "UIText WindowChara\&.textAlias"

.PP
Definition at line \fB755\fP of file \fBWindowChara\&.cs\fP\&.
.SS "UIText WindowChara\&.textAssets"

.PP
Definition at line \fB818\fP of file \fBWindowChara\&.cs\fP\&.
.SS "UIText WindowChara\&.textBio"

.PP
Definition at line \fB761\fP of file \fBWindowChara\&.cs\fP\&.
.SS "UIText WindowChara\&.textBio2"

.PP
Definition at line \fB764\fP of file \fBWindowChara\&.cs\fP\&.
.SS "UIText WindowChara\&.textBio3"

.PP
Definition at line \fB767\fP of file \fBWindowChara\&.cs\fP\&.
.SS "UIText WindowChara\&.textBirthday"

.PP
Definition at line \fB770\fP of file \fBWindowChara\&.cs\fP\&.
.SS "UIText WindowChara\&.textBirthplace"

.PP
Definition at line \fB788\fP of file \fBWindowChara\&.cs\fP\&.
.SS "UIText WindowChara\&.textCurrentZone"

.PP
Definition at line \fB827\fP of file \fBWindowChara\&.cs\fP\&.
.SS "UIText WindowChara\&.textDad"

.PP
Definition at line \fB785\fP of file \fBWindowChara\&.cs\fP\&.
.SS "UIText WindowChara\&.textDeepest"

.PP
Definition at line \fB824\fP of file \fBWindowChara\&.cs\fP\&.
.SS "UIText WindowChara\&.textDeposit"

.PP
Definition at line \fB821\fP of file \fBWindowChara\&.cs\fP\&.
.SS "UIText WindowChara\&.textDominance"

.PP
Definition at line \fB857\fP of file \fBWindowChara\&.cs\fP\&.
.SS "UIText WindowChara\&.textDV"

.PP
Definition at line \fB866\fP of file \fBWindowChara\&.cs\fP\&.
.SS "UIText WindowChara\&.textExtroversion"

.PP
Definition at line \fB860\fP of file \fBWindowChara\&.cs\fP\&.
.SS "UIText WindowChara\&.textFaction"

.PP
Definition at line \fB773\fP of file \fBWindowChara\&.cs\fP\&.
.SS "UIText WindowChara\&.textFaith"

.PP
Definition at line \fB776\fP of file \fBWindowChara\&.cs\fP\&.
.SS "UIText WindowChara\&.textFame"

.PP
Definition at line \fB803\fP of file \fBWindowChara\&.cs\fP\&.
.SS "UIText WindowChara\&.textFavArmor"

.PP
Definition at line \fB863\fP of file \fBWindowChara\&.cs\fP\&.
.SS "UIText WindowChara\&.textHealth"

.PP
Definition at line \fB749\fP of file \fBWindowChara\&.cs\fP\&.
.SS "UIText WindowChara\&.textHobby"

.PP
Definition at line \fB794\fP of file \fBWindowChara\&.cs\fP\&.
.SS "UIText WindowChara\&.textHome"

.PP
Definition at line \fB779\fP of file \fBWindowChara\&.cs\fP\&.
.SS "UIText WindowChara\&.textHomeZone"

.PP
Definition at line \fB830\fP of file \fBWindowChara\&.cs\fP\&.
.SS "UIText WindowChara\&.textIncome"

.PP
Definition at line \fB815\fP of file \fBWindowChara\&.cs\fP\&.
.SS "UIText WindowChara\&.textKarma"

.PP
Definition at line \fB797\fP of file \fBWindowChara\&.cs\fP\&.
.SS "UIText WindowChara\&.textLaw"

.PP
Definition at line \fB851\fP of file \fBWindowChara\&.cs\fP\&.
.SS "UIText WindowChara\&.textLike"

.PP
Definition at line \fB791\fP of file \fBWindowChara\&.cs\fP\&.
.SS "UIText WindowChara\&.textMom"

.PP
Definition at line \fB782\fP of file \fBWindowChara\&.cs\fP\&.
.SS "UIText WindowChara\&.textMoney"

.PP
Definition at line \fB806\fP of file \fBWindowChara\&.cs\fP\&.
.SS "UIText WindowChara\&.textMood"

.PP
Definition at line \fB746\fP of file \fBWindowChara\&.cs\fP\&.
.SS "UIText WindowChara\&.textName"

.PP
Definition at line \fB752\fP of file \fBWindowChara\&.cs\fP\&.
.SS "UIText WindowChara\&.textSAN"

.PP
Definition at line \fB800\fP of file \fBWindowChara\&.cs\fP\&.
.SS "UIText WindowChara\&.textStability"

.PP
Definition at line \fB848\fP of file \fBWindowChara\&.cs\fP\&.
.SS "UIText WindowChara\&.textStyle"

.PP
Definition at line \fB869\fP of file \fBWindowChara\&.cs\fP\&.
.SS "UIText WindowChara\&.textTax"

.PP
Definition at line \fB809\fP of file \fBWindowChara\&.cs\fP\&.
.SS "UIText WindowChara\&.textTerritory"

.PP
Definition at line \fB812\fP of file \fBWindowChara\&.cs\fP\&.
.SS "UIText WindowChara\&.textTitle"

.PP
Definition at line \fB758\fP of file \fBWindowChara\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "\fBBiography\fP WindowChara\&.bio\fR [get]\fP"

.PP
Definition at line \fB14\fP of file \fBWindowChara\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
