.TH "World" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
World
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSpatial\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnCreate\fP ()"
.br
.ti -1c
.RI "void \fBCreateDayData\fP ()"
.br
.ti -1c
.RI "void \fBModEther\fP (int a=3)"
.br
.ti -1c
.RI "void \fBSendPackage\fP (\fBThing\fP p)"
.br
.in -1c

Public Member Functions inherited from \fBSpatial\fP
.in +1c
.ti -1c
.RI "int \fBGetInt\fP (int id, int? defaultInt=null)"
.br
.ti -1c
.RI "void \fBAddInt\fP (int id, int value)"
.br
.ti -1c
.RI "void \fBSetInt\fP (int id, int value=0)"
.br
.ti -1c
.RI "override string \fBToString\fP ()"
.br
.ti -1c
.RI "void \fBCreate\fP (string _id, int _x, int _y, int _icon)"
.br
.ti -1c
.RI "void \fBRegister\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnAfterCreate\fP ()"
.br
.ti -1c
.RI "virtual void \fBSetMainFaction\fP (\fBFaction\fP f)"
.br
.ti -1c
.RI "\fBZone\fP \fBGetFirstZone\fP ()"
.br
.ti -1c
.RI "void \fBOnBeforeSave\fP ()"
.br
.ti -1c
.RI "virtual void \fB_OnBeforeSave\fP ()"
.br
.ti -1c
.RI "void \fB_OnLoad\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnLoad\fP ()"
.br
.ti -1c
.RI "virtual void \fBDestroy\fP ()"
.br
.ti -1c
.RI "void \fBDeleteMapRecursive\fP ()"
.br
.ti -1c
.RI "virtual void \fBAddChild\fP (\fBSpatial\fP child)"
.br
.ti -1c
.RI "void \fBRemoveChild\fP (\fBSpatial\fP child)"
.br
.ti -1c
.RI "\fBZone\fP \fBFindDeepestZone\fP ()"
.br
.ti -1c
.RI "\fBZone\fP \fBFindZone\fP (int lv)"
.br
.ti -1c
.RI "\fBZone\fP \fBFindZone\fP (string _id)"
.br
.ti -1c
.RI "virtual bool \fBCanKill\fP ()"
.br
.ti -1c
.RI "int \fBDist\fP (\fBPoint\fP p)"
.br
.ti -1c
.RI "int \fBDist\fP (\fBSpatial\fP s)"
.br
.ti -1c
.RI "void \fBMakeGameObject\fP (GameObject parentGo)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBGameDate\fP \fBdate\fP = new \fBGameDate\fP()"
.br
.ti -1c
.RI "\fBSeason\fP \fBseason\fP = new \fBSeason\fP()"
.br
.ti -1c
.RI "\fBWeather\fP \fBweather\fP = new \fBWeather\fP()"
.br
.ti -1c
.RI "\fBSchedule\fP \fBschedule\fP = new \fBSchedule\fP()"
.br
.ti -1c
.RI "\fBDayData\fP \fBdayData\fP"
.br
.ti -1c
.RI "int \fBether\fP"
.br
.in -1c

Public Attributes inherited from \fBSpatial\fP
.in +1c
.ti -1c
.RI "\fBSpatial\fP \fBparent\fP"
.br
.ti -1c
.RI "string \fBid\fP"
.br
.ti -1c
.RI "string \fBidUser\fP"
.br
.ti -1c
.RI "string \fBname\fP"
.br
.ti -1c
.RI "string \fBidMainFaction\fP"
.br
.ti -1c
.RI "string \fBidProfile\fP"
.br
.ti -1c
.RI "string \fBidCurrentSubset\fP"
.br
.ti -1c
.RI "string \fBidHat\fP"
.br
.ti -1c
.RI "int[] \fB_ints\fP = new int[30]"
.br
.ti -1c
.RI "List< \fBSpatial\fP > \fBchildren\fP = new List<\fBSpatial\fP>()"
.br
.ti -1c
.RI "List< \fBSpatial\fP > \fBconnections\fP = new List<\fBSpatial\fP>()"
.br
.ti -1c
.RI "Dictionary< int, int > \fBmapInt\fP = new Dictionary<int, int>()"
.br
.ti -1c
.RI "bool \fBdestryoed\fP"
.br
.ti -1c
.RI "bool \fBisImported\fP"
.br
.ti -1c
.RI "BitArray32 \fBbits\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBRegion\fP \fBregion\fP\fR [get]\fP"
.br
.in -1c

Properties inherited from \fBSpatial\fP
.in +1c
.ti -1c
.RI "int \fB_bits\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "int \fBuid\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "int \fBicon\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "int \fBx\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "int \fBy\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "int \fBlastActive\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "int \fBidPrefix\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "int \fBlv\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "int \fBvisitCount\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "int \fBdateExpire\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "int \fBdateRevive\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "int \fB_dangerLv\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "int \fBdateRegenerate\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "int \fBinfluence\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "int \fBinvestment\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "int \fBdevelopment\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "int \fBelectricity\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "int \fBdateHat\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "int \fBuidBoss\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "int \fBdateQuest\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "int \fBversion\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "bool \fBisGenerated\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "bool \fBisShore\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "bool \fBisRandomSite\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "bool \fBisKnown\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "bool \fBisMapSaved\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "bool \fBisExternalZone\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "bool \fBisConquered\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "bool \fBisBeach\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "bool \fBisPeace\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "\fBFaction\fP \fBmainFaction\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "\fBSourceZone\&.Row\fP \fBsource\fP\fR [get]\fP"
.br
.ti -1c
.RI "bool \fBIsPlayerFaction\fP\fR [get]\fP"
.br
.ti -1c
.RI "bool \fBIsClosed\fP\fR [get]\fP"
.br
.ti -1c
.RI "int \fBmapX\fP\fR [get]\fP"
.br
.ti -1c
.RI "int \fBmapY\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual int \fBDangerLv\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual int \fBDangerLvFix\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual float \fBVolumeSea\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBShowDangerLv\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBCanSpawnAdv\fP\fR [get]\fP"
.br
.ti -1c
.RI "string \fBpathSave\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual string \fBName\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual string \fBNameSuffix\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBIsRegion\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBCanFastTravel\fP\fR [get]\fP"
.br
.ti -1c
.RI "\fBEloMap\&.TileInfo\fP \fBTile\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBIsSnowZone\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBIsSnowCovered\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual \fBPoint\fP \fBRegionPos\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBisClaimable\fP\fR [get]\fP"
.br
.ti -1c
.RI "int \fBSeed\fP\fR [get]\fP"
.br
.in -1c

Properties inherited from \fBEClass\fP
.in +1c
.ti -1c
.RI "static \fBGame\fP \fBgame\fP\fR [get]\fP"
.br
.ti -1c
.RI "static bool \fBAdvMode\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBPlayer\fP \fBplayer\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBChara\fP \fBpc\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBUI\fP \fBui\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBMap\fP \fB_map\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBZone\fP \fB_zone\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranchOrHomeBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFaction\fP \fBHome\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFaction\fP \fBWilds\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBScene\fP \fBscene\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBBaseGameScreen\fP \fBscreen\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameSetting\fP \fBsetting\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameData\fP \fBgamedata\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBColorProfile\fP \fBColors\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBWorld\fP \fBworld\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBsources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBeditorSources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static SoundManager \fBSound\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBCoreDebug\fP \fBdebug\fP\fR [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Static Public Member Functions inherited from \fBEClass\fP
.in +1c
.ti -1c
.RI "static int \fBrnd\fP (int a)"
.br
.ti -1c
.RI "static int \fBcurve\fP (int a, int start, int step, int rate=75)"
.br
.ti -1c
.RI "static int \fBrndHalf\fP (int a)"
.br
.ti -1c
.RI "static float \fBrndf\fP (float a)"
.br
.ti -1c
.RI "static int \fBrndSqrt\fP (int a)"
.br
.ti -1c
.RI "static void \fBWait\fP (float a, \fBCard\fP c)"
.br
.ti -1c
.RI "static void \fBWait\fP (float a, \fBPoint\fP p)"
.br
.ti -1c
.RI "static int \fBBigger\fP (int a, int b)"
.br
.ti -1c
.RI "static int \fBSmaller\fP (int a, int b)"
.br
.in -1c

Static Public Attributes inherited from \fBEClass\fP
.in +1c
.ti -1c
.RI "static \fBCore\fP \fBcore\fP"
.br
.in -1c

Protected Member Functions inherited from \fBSpatial\fP
.in +1c
.ti -1c
.RI "\fBZone\fP \fB_FindZone\fP (string _id)"
.br
.in -1c

Protected Attributes inherited from \fBSpatial\fP
.in +1c
.ti -1c
.RI "\fBPoint\fP \fB_regionPos\fP = new \fBPoint\fP()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB5\fP of file \fBWorld\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void World\&.CreateDayData ()"

.PP
Definition at line \fB37\fP of file \fBWorld\&.cs\fP\&.
.SS "void World\&.ModEther (int a = \fR3\fP)"

.PP
Definition at line \fB53\fP of file \fBWorld\&.cs\fP\&.
.SS "override void World\&.OnCreate ()\fR [virtual]\fP"

.PP
Reimplemented from \fBSpatial\fP\&.
.PP
Definition at line \fB18\fP of file \fBWorld\&.cs\fP\&.
.SS "void World\&.SendPackage (\fBThing\fP p)"

.PP
Definition at line \fB64\fP of file \fBWorld\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBGameDate\fP World\&.date = new \fBGameDate\fP()"

.PP
Definition at line \fB71\fP of file \fBWorld\&.cs\fP\&.
.SS "\fBDayData\fP World\&.dayData"

.PP
Definition at line \fB87\fP of file \fBWorld\&.cs\fP\&.
.SS "int World\&.ether"

.PP
Definition at line \fB91\fP of file \fBWorld\&.cs\fP\&.
.SS "\fBSchedule\fP World\&.schedule = new \fBSchedule\fP()"

.PP
Definition at line \fB83\fP of file \fBWorld\&.cs\fP\&.
.SS "\fBSeason\fP World\&.season = new \fBSeason\fP()"

.PP
Definition at line \fB75\fP of file \fBWorld\&.cs\fP\&.
.SS "\fBWeather\fP World\&.weather = new \fBWeather\fP()"

.PP
Definition at line \fB79\fP of file \fBWorld\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "\fBRegion\fP World\&.region\fR [get]\fP"

.PP
Definition at line \fB9\fP of file \fBWorld\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
