.TH "XY" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
XY
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBXY\fP (int _x, int _y)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBx\fP"
.br
.ti -1c
.RI "int \fBy\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB4\fP of file \fBXY\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "XY\&.XY (int _x, int _y)"

.PP
Definition at line \fB7\fP of file \fBXY\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int XY\&.x"

.PP
Definition at line \fB14\fP of file \fBXY\&.cs\fP\&.
.SS "int XY\&.y"

.PP
Definition at line \fB17\fP of file \fBXY\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
