.TH "ZINT" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ZINT
.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "const int \fBweight\fP = 1"
.br
.ti -1c
.RI "const int \fBdateClaim\fP = 2"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB4\fP of file \fBZINT\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "const int ZINT\&.dateClaim = 2\fR [static]\fP"

.PP
Definition at line \fB10\fP of file \fBZINT\&.cs\fP\&.
.SS "const int ZINT\&.weight = 1\fR [static]\fP"

.PP
Definition at line \fB7\fP of file \fBZINT\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
