.TH "ZoneUtil" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ZoneUtil
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBAddBandits\fP ()"
.br
.ti -1c
.RI "bool \fBAddMerchant\fP (string id)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBZone\fP \fBzone\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBMap\fP \fBmap\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB4\fP of file \fBZoneUtil\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "bool ZoneUtil\&.AddBandits ()"

.PP
Definition at line \fB17\fP of file \fBZoneUtil\&.cs\fP\&.
.SS "bool ZoneUtil\&.AddMerchant (string id)"

.PP
Definition at line \fB29\fP of file \fBZoneUtil\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBZone\fP ZoneUtil\&.zone"

.PP
Definition at line \fB38\fP of file \fBZoneUtil\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "\fBMap\fP ZoneUtil\&.map\fR [get]\fP"

.PP
Definition at line \fB8\fP of file \fBZoneUtil\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
