.TH "Zone.PortalReturnData" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Zone.PortalReturnData
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBuidZone\fP"
.br
.ti -1c
.RI "int \fBx\fP"
.br
.ti -1c
.RI "int \fBz\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB4106\fP of file \fBZone\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int Zone\&.PortalReturnData\&.uidZone"

.PP
Definition at line \fB4110\fP of file \fBZone\&.cs\fP\&.
.SS "int Zone\&.PortalReturnData\&.x"

.PP
Definition at line \fB4114\fP of file \fBZone\&.cs\fP\&.
.SS "int Zone\&.PortalReturnData\&.z"

.PP
Definition at line \fB4118\fP of file \fBZone\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
