.TH "ZoneBlueprint" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ZoneBlueprint
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBEClass\fP\&.
.PP
Inherited by \fBGameBlueprint\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBMapGenSetting\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBCreate\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnCreate\fP ()"
.br
.ti -1c
.RI "void \fBGenerateMap\fP (\fBZone\fP zone)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBMap\fP \fBmap\fP"
.br
.ti -1c
.RI "\fBZone\fP \fBzone\fP"
.br
.ti -1c
.RI "\fBZoneProfile\fP \fBzoneProfile\fP"
.br
.ti -1c
.RI "List< \fBChara\fP > \fBcharas\fP = new List<\fBChara\fP>()"
.br
.ti -1c
.RI "List< \fBThing\fP > \fBthings\fP = new List<\fBThing\fP>()"
.br
.ti -1c
.RI "\fBZoneBlueprint\&.MapGenSetting\fP \fBgenSetting\fP"
.br
.ti -1c
.RI "int \fBidDebug\fP"
.br
.ti -1c
.RI "\fBEloMap\&.TileInfo\fP[,] \fBsurrounding\fP"
.br
.ti -1c
.RI "bool \fBcustomMap\fP"
.br
.ti -1c
.RI "bool \fBignoreRoad\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static int \fBdebugCount\fP"
.br
.in -1c

Static Public Attributes inherited from \fBEClass\fP
.in +1c
.ti -1c
.RI "static \fBCore\fP \fBcore\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBEloMap\&.TileInfo\fP \fBtileCenter\fP\fR [get]\fP"
.br
.in -1c

Properties inherited from \fBEClass\fP
.in +1c
.ti -1c
.RI "static \fBGame\fP \fBgame\fP\fR [get]\fP"
.br
.ti -1c
.RI "static bool \fBAdvMode\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBPlayer\fP \fBplayer\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBChara\fP \fBpc\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBUI\fP \fBui\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBMap\fP \fB_map\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBZone\fP \fB_zone\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranchOrHomeBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFaction\fP \fBHome\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFaction\fP \fBWilds\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBScene\fP \fBscene\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBBaseGameScreen\fP \fBscreen\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameSetting\fP \fBsetting\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameData\fP \fBgamedata\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBColorProfile\fP \fBColors\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBWorld\fP \fBworld\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBsources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBeditorSources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static SoundManager \fBSound\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBCoreDebug\fP \fBdebug\fP\fR [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Static Public Member Functions inherited from \fBEClass\fP
.in +1c
.ti -1c
.RI "static int \fBrnd\fP (int a)"
.br
.ti -1c
.RI "static int \fBcurve\fP (int a, int start, int step, int rate=75)"
.br
.ti -1c
.RI "static int \fBrndHalf\fP (int a)"
.br
.ti -1c
.RI "static float \fBrndf\fP (float a)"
.br
.ti -1c
.RI "static int \fBrndSqrt\fP (int a)"
.br
.ti -1c
.RI "static void \fBWait\fP (float a, \fBCard\fP c)"
.br
.ti -1c
.RI "static void \fBWait\fP (float a, \fBPoint\fP p)"
.br
.ti -1c
.RI "static int \fBBigger\fP (int a, int b)"
.br
.ti -1c
.RI "static int \fBSmaller\fP (int a, int b)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB5\fP of file \fBZoneBlueprint\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void ZoneBlueprint\&.Create ()"

.PP
Definition at line \fB22\fP of file \fBZoneBlueprint\&.cs\fP\&.
.SS "void ZoneBlueprint\&.GenerateMap (\fBZone\fP zone)"

.PP
Definition at line \fB33\fP of file \fBZoneBlueprint\&.cs\fP\&.
.SS "virtual void ZoneBlueprint\&.OnCreate ()\fR [virtual]\fP"

.PP
Definition at line \fB28\fP of file \fBZoneBlueprint\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "List<\fBChara\fP> ZoneBlueprint\&.charas = new List<\fBChara\fP>()"

.PP
Definition at line \fB83\fP of file \fBZoneBlueprint\&.cs\fP\&.
.SS "bool ZoneBlueprint\&.customMap"

.PP
Definition at line \fB101\fP of file \fBZoneBlueprint\&.cs\fP\&.
.SS "int ZoneBlueprint\&.debugCount\fR [static]\fP"

.PP
Definition at line \fB98\fP of file \fBZoneBlueprint\&.cs\fP\&.
.SS "\fBZoneBlueprint\&.MapGenSetting\fP ZoneBlueprint\&.genSetting"

.PP
Definition at line \fB89\fP of file \fBZoneBlueprint\&.cs\fP\&.
.SS "int ZoneBlueprint\&.idDebug"

.PP
Definition at line \fB92\fP of file \fBZoneBlueprint\&.cs\fP\&.
.SS "bool ZoneBlueprint\&.ignoreRoad"

.PP
Definition at line \fB104\fP of file \fBZoneBlueprint\&.cs\fP\&.
.SS "\fBMap\fP ZoneBlueprint\&.map"

.PP
Definition at line \fB74\fP of file \fBZoneBlueprint\&.cs\fP\&.
.SS "\fBEloMap\&.TileInfo\fP [,] ZoneBlueprint\&.surrounding"

.PP
Definition at line \fB95\fP of file \fBZoneBlueprint\&.cs\fP\&.
.SS "List<\fBThing\fP> ZoneBlueprint\&.things = new List<\fBThing\fP>()"

.PP
Definition at line \fB86\fP of file \fBZoneBlueprint\&.cs\fP\&.
.SS "\fBZone\fP ZoneBlueprint\&.zone"

.PP
Definition at line \fB77\fP of file \fBZoneBlueprint\&.cs\fP\&.
.SS "\fBZoneProfile\fP ZoneBlueprint\&.zoneProfile"

.PP
Definition at line \fB80\fP of file \fBZoneBlueprint\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "\fBEloMap\&.TileInfo\fP ZoneBlueprint\&.tileCenter\fR [get]\fP"

.PP
Definition at line \fB9\fP of file \fBZoneBlueprint\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
