.TH "Zone" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Zone
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSpatial\fP, \fBICardParent\fP, and \fBIInspect\fP\&.
.PP
Inherited by \fBRegion\fP, \fBZone_Arena\fP, \fBZone_CaveElona\fP, \fBZone_Civilized\fP, \fBZone_Dungeon\fP, \fBZone_Field\fP, \fBZone_Hospital\fP, \fBZone_LumiestRuin\fP, \fBZone_Shelter\fP, \fBZone_SnowGrave\fP, \fBZone_StartCave\fP, \fBZone_StartSite\fP, \fBZone_Tent\fP, \fBZone_TestMap\fP, \fBZone_TestRoom\fP, \fBZone_TruceGround\fP, \fBZone_Underground\fP, \fBZone_User\fP, \fBZone_Wilds\fP, and \fBZone_WindRest\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPortalReturnData\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual string \fBGetDungenID\fP ()"
.br
.ti -1c
.RI "virtual string \fBGetNewZoneID\fP (int level)"
.br
.ti -1c
.RI "override string \fBToString\fP ()"
.br
.ti -1c
.RI "string \fBTextLevel\fP (int _lv)"
.br
.ti -1c
.RI "override void \fBOnCreate\fP ()"
.br
.ti -1c
.RI "override void \fBOnAfterCreate\fP ()"
.br
.ti -1c
.RI "void \fBActivate\fP ()"
.br
.ti -1c
.RI "void \fBRefreshHat\fP ()"
.br
.ti -1c
.RI "void \fBOnVisit\fP ()"
.br
.ti -1c
.RI "void \fBRevive\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnRegenerate\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnActivate\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnBeforeDeactivate\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnDeactivate\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnBeforeSimulate\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnVisitNewMapOrRegenerate\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnAfterSimulate\fP ()"
.br
.ti -1c
.RI "void \fBSimulate\fP ()"
.br
.ti -1c
.RI "\fBPoint\fP \fBGetSpawnPos\fP (\fBChara\fP c, ZoneTransition\&.EnterState destState=ZoneTransition\&.EnterState\&.Auto)"
.br
.ti -1c
.RI "\fBPoint\fP \fBGetRandomVisitPos\fP (\fBChara\fP c)"
.br
.ti -1c
.RI "void \fBAddGlobalCharasOnActivate\fP ()"
.br
.ti -1c
.RI "void \fBDeactivate\fP ()"
.br
.ti -1c
.RI "void \fBOnKillGame\fP ()"
.br
.ti -1c
.RI "void \fBUnloadMap\fP ()"
.br
.ti -1c
.RI "void \fBClaimZone\fP (bool debug=false)"
.br
.ti -1c
.RI "void \fBAbandonZone\fP ()"
.br
.ti -1c
.RI "bool \fBCanDestroy\fP ()"
.br
.ti -1c
.RI "override void \fB_OnBeforeSave\fP ()"
.br
.ti -1c
.RI "override void \fBOnLoad\fP ()"
.br
.ti -1c
.RI "override void \fBDestroy\fP ()"
.br
.ti -1c
.RI "void \fBClearZones\fP (\fBZone\fP current=null)"
.br
.ti -1c
.RI "void \fBOnChildNumChange\fP (\fBCard\fP c)"
.br
.ti -1c
.RI "\fBICardParent\fP \fBGetRoot\fP ()"
.br
.ti -1c
.RI "\fBZone\fP \fBGetTopZone\fP ()"
.br
.ti -1c
.RI "\fBCard\fP \fBAddCardSplinkle\fP (\fBCard\fP t, \fBPoint\fP center, int radius=4)"
.br
.ti -1c
.RI "\fBCard\fP \fBAddChara\fP (string id, int x, int z)"
.br
.ti -1c
.RI "\fBCard\fP \fBAddThing\fP (string id, int x, int z)"
.br
.ti -1c
.RI "\fBCard\fP \fBAddThing\fP (string id, \fBPoint\fP p)"
.br
.ti -1c
.RI "\fBCard\fP \fBAddCard\fP (\fBCard\fP t, \fBPoint\fP point)"
.br
.ti -1c
.RI "\fBCard\fP \fBAddCard\fP (\fBCard\fP t)"
.br
.ti -1c
.RI "\fBCard\fP \fBAddCard\fP (\fBCard\fP t, int x, int z)"
.br
.ti -1c
.RI "void \fBRemoveCard\fP (\fBCard\fP t)"
.br
.ti -1c
.RI "T \fBGetRandomSpot< T >\fP ()"
.br
.ti -1c
.RI "bool \fBTryAddThingInSpot< T >\fP (\fBThing\fP t, bool useContainer=true, bool putRandomPosIfNoSpot=true)"
.br
.ti -1c
.RI "List< \fBThing\fP > \fBTryListThingsInSpot< T >\fP (Func< \fBThing\fP, bool > func=null)"
.br
.ti -1c
.RI "bool \fBTryAddThingInSharedContainer\fP (\fBThing\fP t, List< \fBThing\fP > containers=null, bool add=true, bool msg=false, \fBChara\fP chara=null, bool sharedOnly=true)"
.br
.ti -1c
.RI "bool \fBTryAddThing\fP (\fBThing\fP target, \fBPoint\fP p, bool destroyIfFail=false)"
.br
.ti -1c
.RI "\fBThing\fP \fBTryGetThingFromSharedContainer\fP (Func< \fBThing\fP, bool > func)"
.br
.ti -1c
.RI "\fBThing\fP \fBTryGetRestock< T >\fP (string idCat)"
.br
.ti -1c
.RI "\fBZoneProfile\fP \fBGetProfile\fP ()"
.br
.ti -1c
.RI "void \fBCreateBP\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnCreateBP\fP ()"
.br
.ti -1c
.RI "void \fBGenerate\fP ()"
.br
.ti -1c
.RI "void \fBSpawnFollower\fP ()"
.br
.ti -1c
.RI "void \fBSpawnAltar\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnGenerateMap\fP ()"
.br
.ti -1c
.RI "void \fBTryGenerateOre\fP ()"
.br
.ti -1c
.RI "void \fBTryGenerateEvolved\fP (bool force=false)"
.br
.ti -1c
.RI "void \fBTryGenerateBigDaddy\fP ()"
.br
.ti -1c
.RI "void \fBTryGenerateShrine\fP ()"
.br
.ti -1c
.RI "void \fBResetHostility\fP ()"
.br
.ti -1c
.RI "virtual void \fBOnGenerateRooms\fP (\fBBaseMapGen\fP gen)"
.br
.ti -1c
.RI "\fBPoint\fP \fBGetSpawnPos\fP (SpawnPosition type, int tries=100)"
.br
.ti -1c
.RI "\fBChara\fP \fBSpawnMob\fP (\fBPoint\fP pos=null, \fBSpawnSetting\fP setting=null)"
.br
.ti -1c
.RI "void \fBRefreshElectricity\fP ()"
.br
.ti -1c
.RI "int \fBGetElectricity\fP (bool cost=false)"
.br
.ti -1c
.RI "void \fBSetBGM\fP (List< int > ids, bool refresh=true)"
.br
.ti -1c
.RI "void \fBSetBGM\fP (int id=\-1, bool refresh=true)"
.br
.ti -1c
.RI "void \fBRefreshPlaylist\fP ()"
.br
.ti -1c
.RI "void \fBRefreshBGM\fP ()"
.br
.ti -1c
.RI "Playlist \fBCreatePlaylist\fP (ref List< int > list, Playlist mold=null)"
.br
.ti -1c
.RI "\fBChara\fP \fBFindChara\fP (string id)"
.br
.ti -1c
.RI "\fBChara\fP \fBFindChara\fP (int uid)"
.br
.ti -1c
.RI "int \fBGetDeepestLv\fP ()"
.br
.ti -1c
.RI "int \fBGetDeepestLv\fP (ref int max)"
.br
.ti -1c
.RI "List< \fBElement\fP > \fBListLandFeats\fP ()"
.br
.ti -1c
.RI "\fBZoneExportData\fP \fBImport\fP (string path)"
.br
.ti -1c
.RI "void \fBExport\fP (string path, \fBPartialMap\fP partial=null, bool usermap=false)"
.br
.ti -1c
.RI "void \fBExportDialog\fP (string dir=null)"
.br
.ti -1c
.RI "void \fBImportDialog\fP (string dir=null)"
.br
.ti -1c
.RI "void \fBExport\fP ()"
.br
.ti -1c
.RI "void \fBWriteNote\fP (UINote n, Action< UINote > onWriteNote=null, IInspect\&.NoteMode mode=IInspect\&.NoteMode\&.Default, \fBRecipe\fP recipe=null)"
.br
.ti -1c
.RI "void \fBOnInspect\fP ()"
.br
.ti -1c
.RI "\fBChara\fP \fBAddRandomVisitor\fP (bool guest=false)"
.br
.ti -1c
.RI "void \fBOnSimulateHour\fP (\fBVirtualDate\fP date)"
.br
.ti -1c
.RI "void \fBOnSimulateDay\fP (\fBVirtualDate\fP date)"
.br
.ti -1c
.RI "void \fBOnSimulateMonth\fP (\fBVirtualDate\fP date)"
.br
.ti -1c
.RI "void \fBRainWater\fP ()"
.br
.ti -1c
.RI "void \fBGrowPlants\fP (\fBVirtualDate\fP date)"
.br
.ti -1c
.RI "\fBZone\fP \fBGetZoneAt\fP (int _x, int _y)"
.br
.ti -1c
.RI "bool \fBIsCrime\fP (\fBChara\fP c, \fBAct\fP act)"
.br
.ti -1c
.RI "void \fBRefreshCriminal\fP ()"
.br
.ti -1c
.RI "void \fBRefreshListCitizen\fP ()"
.br
.ti -1c
.RI "void \fBModInfluence\fP (int a)"
.br
.ti -1c
.RI "void \fBModDevelopment\fP (int a)"
.br
.ti -1c
.RI "void \fBUpdateQuests\fP (bool force=false)"
.br
.ti -1c
.RI "int \fBCountMinions\fP (\fBChara\fP c)"
.br
.ti -1c
.RI "int \fBGetSoilCost\fP ()"
.br
.ti -1c
.RI "void \fBSpawnLostItems\fP ()"
.br
.ti -1c
.RI "void \fBApplyBackerPet\fP ()"
.br
.in -1c

Public Member Functions inherited from \fBSpatial\fP
.in +1c
.ti -1c
.RI "int \fBGetInt\fP (int id, int? defaultInt=null)"
.br
.ti -1c
.RI "void \fBAddInt\fP (int id, int value)"
.br
.ti -1c
.RI "void \fBSetInt\fP (int id, int value=0)"
.br
.ti -1c
.RI "override string \fBToString\fP ()"
.br
.ti -1c
.RI "void \fBCreate\fP (string _id, int _x, int _y, int _icon)"
.br
.ti -1c
.RI "void \fBRegister\fP ()"
.br
.ti -1c
.RI "virtual void \fBSetMainFaction\fP (\fBFaction\fP f)"
.br
.ti -1c
.RI "\fBZone\fP \fBGetFirstZone\fP ()"
.br
.ti -1c
.RI "void \fBOnBeforeSave\fP ()"
.br
.ti -1c
.RI "void \fB_OnLoad\fP ()"
.br
.ti -1c
.RI "void \fBDeleteMapRecursive\fP ()"
.br
.ti -1c
.RI "virtual void \fBAddChild\fP (\fBSpatial\fP child)"
.br
.ti -1c
.RI "void \fBRemoveChild\fP (\fBSpatial\fP child)"
.br
.ti -1c
.RI "\fBZone\fP \fBFindDeepestZone\fP ()"
.br
.ti -1c
.RI "\fBZone\fP \fBFindZone\fP (int lv)"
.br
.ti -1c
.RI "\fBZone\fP \fBFindZone\fP (string _id)"
.br
.ti -1c
.RI "virtual bool \fBCanKill\fP ()"
.br
.ti -1c
.RI "int \fBDist\fP (\fBPoint\fP p)"
.br
.ti -1c
.RI "int \fBDist\fP (\fBSpatial\fP s)"
.br
.ti -1c
.RI "void \fBMakeGameObject\fP (GameObject parentGo)"
.br
.in -1c

Public Member Functions inherited from \fBICardParent\fP

Public Member Functions inherited from \fBIInspect\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBIsImportValid\fP (string path)"
.br
.in -1c

Static Public Member Functions inherited from \fBEClass\fP
.in +1c
.ti -1c
.RI "static int \fBrnd\fP (int a)"
.br
.ti -1c
.RI "static int \fBcurve\fP (int a, int start, int step, int rate=75)"
.br
.ti -1c
.RI "static int \fBrndHalf\fP (int a)"
.br
.ti -1c
.RI "static float \fBrndf\fP (float a)"
.br
.ti -1c
.RI "static int \fBrndSqrt\fP (int a)"
.br
.ti -1c
.RI "static void \fBWait\fP (float a, \fBCard\fP c)"
.br
.ti -1c
.RI "static void \fBWait\fP (float a, \fBPoint\fP p)"
.br
.ti -1c
.RI "static int \fBBigger\fP (int a, int b)"
.br
.ti -1c
.RI "static int \fBSmaller\fP (int a, int b)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBFactionBranch\fP \fBbranch\fP"
.br
.ti -1c
.RI "HashSet< int > \fBcompletedQuests\fP = new HashSet<int>()"
.br
.ti -1c
.RI "\fBZoneEventManager\fP \fBevents\fP = new \fBZoneEventManager\fP()"
.br
.ti -1c
.RI "\fBElementContainerZone\fP \fBelements\fP = new \fBElementContainerZone\fP()"
.br
.ti -1c
.RI "\fBMapBounds\fP \fBbounds\fP"
.br
.ti -1c
.RI "Dictionary< int, string > \fBdictCitizen\fP = new Dictionary<int, string>()"
.br
.ti -1c
.RI "\fBZoneInstance\fP \fBinstance\fP"
.br
.ti -1c
.RI "List< int > \fBlandFeats\fP"
.br
.ti -1c
.RI "\fBMap\fP \fBmap\fP"
.br
.ti -1c
.RI "\fBMapSubset\fP \fBsubset\fP"
.br
.ti -1c
.RI "\fBZoneBlueprint\fP \fBbp\fP"
.br
.ti -1c
.RI "int \fBfileVariation\fP"
.br
.ti -1c
.RI "bool \fBdirtyElectricity\fP"
.br
.ti -1c
.RI "bool \fBisStarted\fP"
.br
.ti -1c
.RI "bool \fBisSimulating\fP"
.br
.ti -1c
.RI "int \fBtempDist\fP"
.br
.ti -1c
.RI "\fBBiomeProfile\fP \fB_biome\fP"
.br
.in -1c

Public Attributes inherited from \fBSpatial\fP
.in +1c
.ti -1c
.RI "\fBSpatial\fP \fBparent\fP"
.br
.ti -1c
.RI "string \fBid\fP"
.br
.ti -1c
.RI "string \fBidUser\fP"
.br
.ti -1c
.RI "string \fBname\fP"
.br
.ti -1c
.RI "string \fBidMainFaction\fP"
.br
.ti -1c
.RI "string \fBidProfile\fP"
.br
.ti -1c
.RI "string \fBidCurrentSubset\fP"
.br
.ti -1c
.RI "string \fBidHat\fP"
.br
.ti -1c
.RI "int[] \fB_ints\fP = new int[30]"
.br
.ti -1c
.RI "List< \fBSpatial\fP > \fBchildren\fP = new List<\fBSpatial\fP>()"
.br
.ti -1c
.RI "List< \fBSpatial\fP > \fBconnections\fP = new List<\fBSpatial\fP>()"
.br
.ti -1c
.RI "Dictionary< int, int > \fBmapInt\fP = new Dictionary<int, int>()"
.br
.ti -1c
.RI "bool \fBdestryoed\fP"
.br
.ti -1c
.RI "bool \fBisImported\fP"
.br
.ti -1c
.RI "BitArray32 \fBbits\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static bool \fBforceRegenerate\fP"
.br
.ti -1c
.RI "static string \fBforceSubset\fP"
.br
.ti -1c
.RI "static \fBCardRow\fP \fBsourceHat\fP"
.br
.ti -1c
.RI "static int \fBokaerinko\fP = 0"
.br
.ti -1c
.RI "static bool \fBignoreSpawnAnime\fP"
.br
.ti -1c
.RI "static List< \fBThing\fP > \fBSuckers\fP = new List<\fBThing\fP>()"
.br
.in -1c

Static Public Attributes inherited from \fBEClass\fP
.in +1c
.ti -1c
.RI "static \fBCore\fP \fBcore\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBChara\fP \fBBoss\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "override int \fBDangerLv\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBDisableRooms\fP\fR [get]\fP"
.br
.ti -1c
.RI "int \fBHourSinceLastActive\fP\fR [get]\fP"
.br
.ti -1c
.RI "int \fBMinsSinceLastActive\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual string \fBpathExport\fP\fR [get]\fP"
.br
.ti -1c
.RI "\fBBiomeProfile\fP \fBbiome\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual string \fBIdBiome\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual string \fBIDGenerator\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual string \fBTextWidgetDate\fP\fR [get]\fP"
.br
.ti -1c
.RI "MapGenerator \fBGenerator\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual string \fBIdProfile\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual string \fBIDPlayList\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual string \fBIDPlaylistOverwrite\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual string \fBIDHat\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual string \fBIDBaseLandFeat\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual string \fBidExport\fP\fR [get]\fP"
.br
.ti -1c
.RI "string \fBpathTemp\fP\fR [get]\fP"
.br
.ti -1c
.RI "\fBRegion\fP \fBRegion\fP\fR [get]\fP"
.br
.ti -1c
.RI "\fBZone\fP \fBParentZone\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual \fBActionMode\fP \fBDefaultActionMode\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBBlockBorderExit\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual int \fBExpireDays\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual ZoneTransition\&.EnterState \fBRegionEnterState\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual ZoneFeatureType \fBFeatureType\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual string \fBIDAmbience\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual string \fBIDSceneTemplate\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBIsFestival\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual string \fBIDSubset\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBIsTown\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBCanBeDeliverDestination\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBCountDeepestLevel\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBHasLaw\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBMakeEnemiesNeutral\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBMakeTownProperties\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBAllowCriminal\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBAllowNewZone\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBWillAutoSave\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBRegenerateOnEnter\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBIsSkyLevel\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBIsUserZone\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBCanDigUnderground\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBLockExit\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBCanUnlockExit\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual int \fBMaxLv\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual int \fBMinLv\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBAddPrefix\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBIsNefia\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBPetFollow\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBRestrictBuild\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBKeepAllyDistance\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual int \fBMaxSpawn\fP\fR [get]\fP"
.br
.ti -1c
.RI "int \fBMaxRespawn\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual float \fBRuinChance\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual float \fBOreChance\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual float \fBBigDaddyChance\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual float \fBEvolvedChance\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual float \fBShrineChance\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual float \fBPrespawnRate\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual float \fBRespawnRate\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual int \fBRespawnPerHour\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual float \fBChanceSpawnNeutral\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBGrowPlant\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBGrowWeed\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBIsExplorable\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBIsReturnLocation\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBShouldMakeExit\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBShouldRegenerate\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBShouldAutoRevive\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBUseFog\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBRevealRoom\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBAlwaysLowblock\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBUseLight\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual int \fBStartLV\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBScaleMonsterLevel\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBHiddenInRegionMap\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual FlockController\&.SpawnType \fBFlockType\fP\fR [get]\fP"
.br
.ti -1c
.RI "override string \fBNameSuffix\fP\fR [get]\fP"
.br
.ti -1c
.RI "string \fBNameWithLevel\fP\fR [get]\fP"
.br
.ti -1c
.RI "string \fBTextDeepestLv\fP\fR [get]\fP"
.br
.ti -1c
.RI "bool \fBCanEnterBuildMode\fP\fR [get]\fP"
.br
.ti -1c
.RI "bool \fBCanEnterBuildModeAnywhere\fP\fR [get]\fP"
.br
.ti -1c
.RI "bool \fBIsPCFaction\fP\fR [get]\fP"
.br
.ti -1c
.RI "bool \fBIsStartZone\fP\fR [get]\fP"
.br
.ti -1c
.RI "bool \fBIsInstance\fP\fR [get]\fP"
.br
.ti -1c
.RI "bool \fBIsLoaded\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual int \fBBaseElectricity\fP\fR [get]\fP"
.br
.ti -1c
.RI "bool \fBIsActiveZone\fP\fR [get]\fP"
.br
.ti -1c
.RI "bool \fBCanInspect\fP\fR [get]\fP"
.br
.ti -1c
.RI "string \fBInspectName\fP\fR [get]\fP"
.br
.ti -1c
.RI "\fBPoint\fP \fBInspectPoint\fP\fR [get]\fP"
.br
.ti -1c
.RI "Vector3 \fBInspectPosition\fP\fR [get]\fP"
.br
.in -1c

Properties inherited from \fBSpatial\fP
.in +1c
.ti -1c
.RI "int \fB_bits\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "int \fBuid\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "int \fBicon\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "int \fBx\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "int \fBy\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "int \fBlastActive\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "int \fBidPrefix\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "int \fBlv\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "int \fBvisitCount\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "int \fBdateExpire\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "int \fBdateRevive\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "int \fB_dangerLv\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "int \fBdateRegenerate\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "int \fBinfluence\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "int \fBinvestment\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "int \fBdevelopment\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "int \fBelectricity\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "int \fBdateHat\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "int \fBuidBoss\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "int \fBdateQuest\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "int \fBversion\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "bool \fBisGenerated\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "bool \fBisShore\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "bool \fBisRandomSite\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "bool \fBisKnown\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "bool \fBisMapSaved\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "bool \fBisExternalZone\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "bool \fBisConquered\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "bool \fBisBeach\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "bool \fBisPeace\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "\fBFaction\fP \fBmainFaction\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "\fBSourceZone\&.Row\fP \fBsource\fP\fR [get]\fP"
.br
.ti -1c
.RI "bool \fBIsPlayerFaction\fP\fR [get]\fP"
.br
.ti -1c
.RI "bool \fBIsClosed\fP\fR [get]\fP"
.br
.ti -1c
.RI "int \fBmapX\fP\fR [get]\fP"
.br
.ti -1c
.RI "int \fBmapY\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual int \fBDangerLv\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual int \fBDangerLvFix\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual float \fBVolumeSea\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBShowDangerLv\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBCanSpawnAdv\fP\fR [get]\fP"
.br
.ti -1c
.RI "string \fBpathSave\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual string \fBName\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual string \fBNameSuffix\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBIsRegion\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBCanFastTravel\fP\fR [get]\fP"
.br
.ti -1c
.RI "\fBEloMap\&.TileInfo\fP \fBTile\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBIsSnowZone\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBIsSnowCovered\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual \fBPoint\fP \fBRegionPos\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual bool \fBisClaimable\fP\fR [get]\fP"
.br
.ti -1c
.RI "int \fBSeed\fP\fR [get]\fP"
.br
.in -1c

Properties inherited from \fBEClass\fP
.in +1c
.ti -1c
.RI "static \fBGame\fP \fBgame\fP\fR [get]\fP"
.br
.ti -1c
.RI "static bool \fBAdvMode\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBPlayer\fP \fBplayer\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBChara\fP \fBpc\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBUI\fP \fBui\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBMap\fP \fB_map\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBZone\fP \fB_zone\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFactionBranch\fP \fBBranchOrHomeBranch\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFaction\fP \fBHome\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBFaction\fP \fBWilds\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBScene\fP \fBscene\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBBaseGameScreen\fP \fBscreen\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameSetting\fP \fBsetting\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBGameData\fP \fBgamedata\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBColorProfile\fP \fBColors\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBWorld\fP \fBworld\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBsources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBSourceManager\fP \fBeditorSources\fP\fR [get]\fP"
.br
.ti -1c
.RI "static SoundManager \fBSound\fP\fR [get]\fP"
.br
.ti -1c
.RI "static \fBCoreDebug\fP \fBdebug\fP\fR [get]\fP"
.br
.in -1c

Properties inherited from \fBIInspect\fP
.SS "Additional Inherited Members"


Public Types inherited from \fBIInspect\fP
.in +1c
.ti -1c
.RI "enum \fBNoteMode\fP { \fBDefault\fP, \fBRecipe\fP, \fBProduct\fP, \fBInfo\fP }"
.br
.in -1c

Protected Member Functions inherited from \fBSpatial\fP
.in +1c
.ti -1c
.RI "\fBZone\fP \fB_FindZone\fP (string _id)"
.br
.in -1c

Protected Attributes inherited from \fBSpatial\fP
.in +1c
.ti -1c
.RI "\fBPoint\fP \fB_regionPos\fP = new \fBPoint\fP()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB13\fP of file \fBZone\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void Zone\&._OnBeforeSave ()\fR [virtual]\fP"

.PP
Reimplemented from \fBSpatial\fP\&.
.PP
Definition at line \fB2271\fP of file \fBZone\&.cs\fP\&.
.SS "void Zone\&.AbandonZone ()"

.PP
Definition at line \fB2235\fP of file \fBZone\&.cs\fP\&.
.SS "void Zone\&.Activate ()"

.PP
Definition at line \fB1048\fP of file \fBZone\&.cs\fP\&.
.SS "\fBCard\fP Zone\&.AddCard (\fBCard\fP t)"

.PP
Definition at line \fB2414\fP of file \fBZone\&.cs\fP\&.
.SS "\fBCard\fP Zone\&.AddCard (\fBCard\fP t, int x, int z)"

.PP
Definition at line \fB2420\fP of file \fBZone\&.cs\fP\&.
.SS "\fBCard\fP Zone\&.AddCard (\fBCard\fP t, \fBPoint\fP point)"

.PP
Definition at line \fB2408\fP of file \fBZone\&.cs\fP\&.
.SS "\fBCard\fP Zone\&.AddCardSplinkle (\fBCard\fP t, \fBPoint\fP center, int radius = \fR4\fP)"

.PP
Definition at line \fB2374\fP of file \fBZone\&.cs\fP\&.
.SS "\fBCard\fP Zone\&.AddChara (string id, int x, int z)"

.PP
Definition at line \fB2390\fP of file \fBZone\&.cs\fP\&.
.SS "void Zone\&.AddGlobalCharasOnActivate ()"

.PP
Definition at line \fB2058\fP of file \fBZone\&.cs\fP\&.
.SS "\fBChara\fP Zone\&.AddRandomVisitor (bool guest = \fRfalse\fP)"

.PP
Definition at line \fB3483\fP of file \fBZone\&.cs\fP\&.
.SS "\fBCard\fP Zone\&.AddThing (string id, int x, int z)"

.PP
Definition at line \fB2396\fP of file \fBZone\&.cs\fP\&.
.SS "\fBCard\fP Zone\&.AddThing (string id, \fBPoint\fP p)"

.PP
Definition at line \fB2402\fP of file \fBZone\&.cs\fP\&.
.SS "void Zone\&.ApplyBackerPet ()"

.PP
Definition at line \fB3896\fP of file \fBZone\&.cs\fP\&.
.SS "bool Zone\&.CanDestroy ()"

.PP
Definition at line \fB2252\fP of file \fBZone\&.cs\fP\&.
.SS "void Zone\&.ClaimZone (bool debug = \fRfalse\fP)"

.PP
Definition at line \fB2191\fP of file \fBZone\&.cs\fP\&.
.SS "void Zone\&.ClearZones (\fBZone\fP current = \fRnull\fP)"

.PP
Definition at line \fB2330\fP of file \fBZone\&.cs\fP\&.
.SS "int Zone\&.CountMinions (\fBChara\fP c)"

.PP
Definition at line \fB3837\fP of file \fBZone\&.cs\fP\&.
.SS "void Zone\&.CreateBP ()"

.PP
Definition at line \fB2732\fP of file \fBZone\&.cs\fP\&.
.SS "Playlist Zone\&.CreatePlaylist (ref List< int > list, Playlist mold = \fRnull\fP)"

.PP
Definition at line \fB3253\fP of file \fBZone\&.cs\fP\&.
.SS "void Zone\&.Deactivate ()"

.PP
Definition at line \fB2135\fP of file \fBZone\&.cs\fP\&.
.SS "override void Zone\&.Destroy ()\fR [virtual]\fP"

.PP
Reimplemented from \fBSpatial\fP\&.
.PP
Definition at line \fB2310\fP of file \fBZone\&.cs\fP\&.
.SS "void Zone\&.Export ()"

.PP
Definition at line \fB3463\fP of file \fBZone\&.cs\fP\&.
.SS "void Zone\&.Export (string path, \fBPartialMap\fP partial = \fRnull\fP, bool usermap = \fRfalse\fP)"

.PP
Definition at line \fB3372\fP of file \fBZone\&.cs\fP\&.
.SS "void Zone\&.ExportDialog (string dir = \fRnull\fP)"

.PP
Definition at line \fB3414\fP of file \fBZone\&.cs\fP\&.
.SS "\fBChara\fP Zone\&.FindChara (int uid)"

.PP
Definition at line \fB3281\fP of file \fBZone\&.cs\fP\&.
.SS "\fBChara\fP Zone\&.FindChara (string id)"

.PP
Definition at line \fB3275\fP of file \fBZone\&.cs\fP\&.
.SS "void Zone\&.Generate ()"

.PP
Definition at line \fB2746\fP of file \fBZone\&.cs\fP\&.
.SS "int Zone\&.GetDeepestLv ()"

.PP
Definition at line \fB3287\fP of file \fBZone\&.cs\fP\&.
.SS "int Zone\&.GetDeepestLv (ref int max)"

.PP
Definition at line \fB3294\fP of file \fBZone\&.cs\fP\&.
.SS "virtual string Zone\&.GetDungenID ()\fR [virtual]\fP"

.PP
Definition at line \fB110\fP of file \fBZone\&.cs\fP\&.
.SS "int Zone\&.GetElectricity (bool cost = \fRfalse\fP)"

.PP
Definition at line \fB3139\fP of file \fBZone\&.cs\fP\&.
.SS "virtual string Zone\&.GetNewZoneID (int level)\fR [virtual]\fP"

.PP
Definition at line \fB820\fP of file \fBZone\&.cs\fP\&.
.SS "\fBZoneProfile\fP Zone\&.GetProfile ()"

.PP
Definition at line \fB2691\fP of file \fBZone\&.cs\fP\&.
.SS "T Zone\&.GetRandomSpot< T > ()"

.PP
\fBType Constraints\fP
.TP
\fIT\fP : \fI\fBTrait\fP\fP
.PP
Definition at line \fB2468\fP of file \fBZone\&.cs\fP\&.
.SS "\fBPoint\fP Zone\&.GetRandomVisitPos (\fBChara\fP c)"

.PP
Definition at line \fB2033\fP of file \fBZone\&.cs\fP\&.
.SS "\fBICardParent\fP Zone\&.GetRoot ()"

.PP
Implements \fBICardParent\fP\&.
.PP
Definition at line \fB2358\fP of file \fBZone\&.cs\fP\&.
.SS "int Zone\&.GetSoilCost ()"

.PP
Definition at line \fB3851\fP of file \fBZone\&.cs\fP\&.
.SS "\fBPoint\fP Zone\&.GetSpawnPos (\fBChara\fP c, ZoneTransition\&.EnterState destState = \fRZoneTransition::EnterState::Auto\fP)"

.PP
Definition at line \fB1803\fP of file \fBZone\&.cs\fP\&.
.SS "\fBPoint\fP Zone\&.GetSpawnPos (SpawnPosition type, int tries = \fR100\fP)"

.PP
Definition at line \fB3005\fP of file \fBZone\&.cs\fP\&.
.SS "\fBZone\fP Zone\&.GetTopZone ()"

.PP
Definition at line \fB2364\fP of file \fBZone\&.cs\fP\&.
.SS "\fBZone\fP Zone\&.GetZoneAt (int _x, int _y)"

.PP
Definition at line \fB3651\fP of file \fBZone\&.cs\fP\&.
.SS "void Zone\&.GrowPlants (\fBVirtualDate\fP date)"

.PP
Definition at line \fB3610\fP of file \fBZone\&.cs\fP\&.
.SS "\fBZoneExportData\fP Zone\&.Import (string path)"

.PP
Definition at line \fB3362\fP of file \fBZone\&.cs\fP\&.
.SS "void Zone\&.ImportDialog (string dir = \fRnull\fP)"

.PP
Definition at line \fB3428\fP of file \fBZone\&.cs\fP\&.
.SS "bool Zone\&.IsCrime (\fBChara\fP c, \fBAct\fP act)"

.PP
Definition at line \fB3674\fP of file \fBZone\&.cs\fP\&.
.SS "static bool Zone\&.IsImportValid (string path)\fR [static]\fP"

.PP
Definition at line \fB3446\fP of file \fBZone\&.cs\fP\&.
.SS "List< \fBElement\fP > Zone\&.ListLandFeats ()"

.PP
Definition at line \fB3308\fP of file \fBZone\&.cs\fP\&.
.SS "void Zone\&.ModDevelopment (int a)"

.PP
Definition at line \fB3726\fP of file \fBZone\&.cs\fP\&.
.SS "void Zone\&.ModInfluence (int a)"

.PP
Definition at line \fB3715\fP of file \fBZone\&.cs\fP\&.
.SS "virtual void Zone\&.OnActivate ()\fR [virtual]\fP"

.PP
Definition at line \fB1619\fP of file \fBZone\&.cs\fP\&.
.SS "override void Zone\&.OnAfterCreate ()\fR [virtual]\fP"

.PP
Reimplemented from \fBSpatial\fP\&.
.PP
Definition at line \fB1034\fP of file \fBZone\&.cs\fP\&.
.SS "virtual void Zone\&.OnAfterSimulate ()\fR [virtual]\fP"

.PP
Definition at line \fB1644\fP of file \fBZone\&.cs\fP\&.
.SS "virtual void Zone\&.OnBeforeDeactivate ()\fR [virtual]\fP"

.PP
Definition at line \fB1624\fP of file \fBZone\&.cs\fP\&.
.SS "virtual void Zone\&.OnBeforeSimulate ()\fR [virtual]\fP"

.PP
Definition at line \fB1634\fP of file \fBZone\&.cs\fP\&.
.SS "void Zone\&.OnChildNumChange (\fBCard\fP c)"

.PP
Implements \fBICardParent\fP\&.
.PP
Definition at line \fB2353\fP of file \fBZone\&.cs\fP\&.
.SS "override void Zone\&.OnCreate ()\fR [virtual]\fP"

.PP
Reimplemented from \fBSpatial\fP\&.
.PP
Definition at line \fB1027\fP of file \fBZone\&.cs\fP\&.
.SS "virtual void Zone\&.OnCreateBP ()\fR [virtual]\fP"

.PP
Definition at line \fB2741\fP of file \fBZone\&.cs\fP\&.
.SS "virtual void Zone\&.OnDeactivate ()\fR [virtual]\fP"

.PP
Definition at line \fB1629\fP of file \fBZone\&.cs\fP\&.
.SS "virtual void Zone\&.OnGenerateMap ()\fR [virtual]\fP"

.PP
Definition at line \fB2858\fP of file \fBZone\&.cs\fP\&.
.SS "virtual void Zone\&.OnGenerateRooms (\fBBaseMapGen\fP gen)\fR [virtual]\fP"

.PP
Definition at line \fB3000\fP of file \fBZone\&.cs\fP\&.
.SS "void Zone\&.OnInspect ()"

.PP
Implements \fBIInspect\fP\&.
.PP
Definition at line \fB3478\fP of file \fBZone\&.cs\fP\&.
.SS "void Zone\&.OnKillGame ()"

.PP
Definition at line \fB2164\fP of file \fBZone\&.cs\fP\&.
.SS "override void Zone\&.OnLoad ()\fR [virtual]\fP"

.PP
Reimplemented from \fBSpatial\fP\&.
.PP
Definition at line \fB2300\fP of file \fBZone\&.cs\fP\&.
.SS "virtual void Zone\&.OnRegenerate ()\fR [virtual]\fP"

.PP
Definition at line \fB1614\fP of file \fBZone\&.cs\fP\&.
.SS "void Zone\&.OnSimulateDay (\fBVirtualDate\fP date)"

.PP
Definition at line \fB3572\fP of file \fBZone\&.cs\fP\&.
.SS "void Zone\&.OnSimulateHour (\fBVirtualDate\fP date)"

.PP
Definition at line \fB3513\fP of file \fBZone\&.cs\fP\&.
.SS "void Zone\&.OnSimulateMonth (\fBVirtualDate\fP date)"

.PP
Definition at line \fB3581\fP of file \fBZone\&.cs\fP\&.
.SS "void Zone\&.OnVisit ()"

.PP
Definition at line \fB1536\fP of file \fBZone\&.cs\fP\&.
.SS "virtual void Zone\&.OnVisitNewMapOrRegenerate ()\fR [virtual]\fP"

.PP
Definition at line \fB1639\fP of file \fBZone\&.cs\fP\&.
.SS "void Zone\&.RainWater ()"

.PP
Definition at line \fB3594\fP of file \fBZone\&.cs\fP\&.
.SS "void Zone\&.RefreshBGM ()"

.PP
Definition at line \fB3209\fP of file \fBZone\&.cs\fP\&.
.SS "void Zone\&.RefreshCriminal ()"

.PP
Definition at line \fB3680\fP of file \fBZone\&.cs\fP\&.
.SS "void Zone\&.RefreshElectricity ()"

.PP
Definition at line \fB3118\fP of file \fBZone\&.cs\fP\&.
.SS "void Zone\&.RefreshHat ()"

.PP
Definition at line \fB1525\fP of file \fBZone\&.cs\fP\&.
.SS "void Zone\&.RefreshListCitizen ()"

.PP
Definition at line \fB3698\fP of file \fBZone\&.cs\fP\&.
.SS "void Zone\&.RefreshPlaylist ()"

.PP
Definition at line \fB3200\fP of file \fBZone\&.cs\fP\&.
.SS "void Zone\&.RemoveCard (\fBCard\fP t)"

.PP
Implements \fBICardParent\fP\&.
.PP
Definition at line \fB2446\fP of file \fBZone\&.cs\fP\&.
.SS "void Zone\&.ResetHostility ()"

.PP
Definition at line \fB2987\fP of file \fBZone\&.cs\fP\&.
.SS "void Zone\&.Revive ()"

.PP
Definition at line \fB1579\fP of file \fBZone\&.cs\fP\&.
.SS "void Zone\&.SetBGM (int id = \fR\-1\fP, bool refresh = \fRtrue\fP)"

.PP
Definition at line \fB3191\fP of file \fBZone\&.cs\fP\&.
.SS "void Zone\&.SetBGM (List< int > ids, bool refresh = \fRtrue\fP)"

.PP
Definition at line \fB3167\fP of file \fBZone\&.cs\fP\&.
.SS "void Zone\&.Simulate ()"

.PP
Definition at line \fB1649\fP of file \fBZone\&.cs\fP\&.
.SS "void Zone\&.SpawnAltar ()"

.PP
Definition at line \fB2818\fP of file \fBZone\&.cs\fP\&.
.SS "void Zone\&.SpawnFollower ()"

.PP
Definition at line \fB2786\fP of file \fBZone\&.cs\fP\&.
.SS "void Zone\&.SpawnLostItems ()"

.PP
Definition at line \fB3862\fP of file \fBZone\&.cs\fP\&.
.SS "\fBChara\fP Zone\&.SpawnMob (\fBPoint\fP pos = \fRnull\fP, \fBSpawnSetting\fP setting = \fRnull\fP)"

.PP
Definition at line \fB3020\fP of file \fBZone\&.cs\fP\&.
.SS "string Zone\&.TextLevel (int _lv)"

.PP
Definition at line \fB879\fP of file \fBZone\&.cs\fP\&.
.SS "override string Zone\&.ToString ()"

.PP
Definition at line \fB836\fP of file \fBZone\&.cs\fP\&.
.SS "bool Zone\&.TryAddThing (\fBThing\fP target, \fBPoint\fP p, bool destroyIfFail = \fRfalse\fP)"

.PP
Definition at line \fB2598\fP of file \fBZone\&.cs\fP\&.
.SS "bool Zone\&.TryAddThingInSharedContainer (\fBThing\fP t, List< \fBThing\fP > containers = \fRnull\fP, bool add = \fRtrue\fP, bool msg = \fRfalse\fP, \fBChara\fP chara = \fRnull\fP, bool sharedOnly = \fRtrue\fP)"

.PP
Definition at line \fB2558\fP of file \fBZone\&.cs\fP\&.
.SS "bool Zone\&.TryAddThingInSpot< T > (\fBThing\fP t, bool useContainer = \fRtrue\fP, bool putRandomPosIfNoSpot = \fRtrue\fP)"

.PP
\fBType Constraints\fP
.TP
\fIT\fP : \fI\fBTrait\fP\fP
.PP
Definition at line \fB2474\fP of file \fBZone\&.cs\fP\&.
.SS "void Zone\&.TryGenerateBigDaddy ()"

.PP
Definition at line \fB2933\fP of file \fBZone\&.cs\fP\&.
.SS "void Zone\&.TryGenerateEvolved (bool force = \fRfalse\fP)"

.PP
Definition at line \fB2914\fP of file \fBZone\&.cs\fP\&.
.SS "void Zone\&.TryGenerateOre ()"

.PP
Definition at line \fB2884\fP of file \fBZone\&.cs\fP\&.
.SS "void Zone\&.TryGenerateShrine ()"

.PP
Definition at line \fB2953\fP of file \fBZone\&.cs\fP\&.
.SS "\fBThing\fP Zone\&.TryGetRestock< T > (string idCat)"

.PP
\fBType Constraints\fP
.TP
\fIT\fP : \fI\fBTraitSpot\fP\fP
.PP
Definition at line \fB2642\fP of file \fBZone\&.cs\fP\&.
.SS "\fBThing\fP Zone\&.TryGetThingFromSharedContainer (Func< \fBThing\fP, bool > func)"

.PP
Definition at line \fB2625\fP of file \fBZone\&.cs\fP\&.
.SS "List< \fBThing\fP > Zone\&.TryListThingsInSpot< T > (Func< \fBThing\fP, bool > func = \fRnull\fP)"

.PP
\fBType Constraints\fP
.TP
\fIT\fP : \fI\fBTraitSpot\fP\fP
.PP
Definition at line \fB2509\fP of file \fBZone\&.cs\fP\&.
.SS "void Zone\&.UnloadMap ()"

.PP
Definition at line \fB2176\fP of file \fBZone\&.cs\fP\&.
.SS "void Zone\&.UpdateQuests (bool force = \fRfalse\fP)"

.PP
Definition at line \fB3736\fP of file \fBZone\&.cs\fP\&.
.SS "void Zone\&.WriteNote (UINote n, Action< UINote > onWriteNote = \fRnull\fP, IInspect\&.NoteMode mode = \fRIInspect::NoteMode::Default\fP, \fBRecipe\fP recipe = \fRnull\fP)"

.PP
Implements \fBIInspect\fP\&.
.PP
Definition at line \fB3473\fP of file \fBZone\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBBiomeProfile\fP Zone\&._biome"

.PP
Definition at line \fB4097\fP of file \fBZone\&.cs\fP\&.
.SS "\fBMapBounds\fP Zone\&.bounds"

.PP
Definition at line \fB4058\fP of file \fBZone\&.cs\fP\&.
.SS "\fBZoneBlueprint\fP Zone\&.bp"

.PP
Definition at line \fB4079\fP of file \fBZone\&.cs\fP\&.
.SS "\fBFactionBranch\fP Zone\&.branch"

.PP
Definition at line \fB4042\fP of file \fBZone\&.cs\fP\&.
.SS "HashSet<int> Zone\&.completedQuests = new HashSet<int>()"

.PP
Definition at line \fB4046\fP of file \fBZone\&.cs\fP\&.
.SS "Dictionary<int, string> Zone\&.dictCitizen = new Dictionary<int, string>()"

.PP
Definition at line \fB4062\fP of file \fBZone\&.cs\fP\&.
.SS "bool Zone\&.dirtyElectricity"

.PP
Definition at line \fB4085\fP of file \fBZone\&.cs\fP\&.
.SS "\fBElementContainerZone\fP Zone\&.elements = new \fBElementContainerZone\fP()"

.PP
Definition at line \fB4054\fP of file \fBZone\&.cs\fP\&.
.SS "\fBZoneEventManager\fP Zone\&.events = new \fBZoneEventManager\fP()"

.PP
Definition at line \fB4050\fP of file \fBZone\&.cs\fP\&.
.SS "int Zone\&.fileVariation"

.PP
Definition at line \fB4082\fP of file \fBZone\&.cs\fP\&.
.SS "bool Zone\&.forceRegenerate\fR [static]\fP"

.PP
Definition at line \fB4029\fP of file \fBZone\&.cs\fP\&.
.SS "string Zone\&.forceSubset\fR [static]\fP"

.PP
Definition at line \fB4032\fP of file \fBZone\&.cs\fP\&.
.SS "bool Zone\&.ignoreSpawnAnime\fR [static]\fP"

.PP
Definition at line \fB4100\fP of file \fBZone\&.cs\fP\&.
.SS "\fBZoneInstance\fP Zone\&.instance"

.PP
Definition at line \fB4066\fP of file \fBZone\&.cs\fP\&.
.SS "bool Zone\&.isSimulating"

.PP
Definition at line \fB4091\fP of file \fBZone\&.cs\fP\&.
.SS "bool Zone\&.isStarted"

.PP
Definition at line \fB4088\fP of file \fBZone\&.cs\fP\&.
.SS "List<int> Zone\&.landFeats"

.PP
Definition at line \fB4070\fP of file \fBZone\&.cs\fP\&.
.SS "\fBMap\fP Zone\&.map"

.PP
Definition at line \fB4073\fP of file \fBZone\&.cs\fP\&.
.SS "int Zone\&.okaerinko = 0\fR [static]\fP"

.PP
Definition at line \fB4038\fP of file \fBZone\&.cs\fP\&.
.SS "\fBCardRow\fP Zone\&.sourceHat\fR [static]\fP"

.PP
Definition at line \fB4035\fP of file \fBZone\&.cs\fP\&.
.SS "\fBMapSubset\fP Zone\&.subset"

.PP
Definition at line \fB4076\fP of file \fBZone\&.cs\fP\&.
.SS "List<\fBThing\fP> Zone\&.Suckers = new List<\fBThing\fP>()\fR [static]\fP"

.PP
Definition at line \fB4103\fP of file \fBZone\&.cs\fP\&.
.SS "int Zone\&.tempDist"

.PP
Definition at line \fB4094\fP of file \fBZone\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "virtual bool Zone\&.AddPrefix\fR [get]\fP"

.PP
Definition at line \fB521\fP of file \fBZone\&.cs\fP\&.
.SS "virtual bool Zone\&.AllowCriminal\fR [get]\fP"

.PP
Definition at line \fB411\fP of file \fBZone\&.cs\fP\&.
.SS "virtual bool Zone\&.AllowNewZone\fR [get]\fP"

.PP
Definition at line \fB421\fP of file \fBZone\&.cs\fP\&.
.SS "virtual bool Zone\&.AlwaysLowblock\fR [get]\fP"

.PP
Definition at line \fB771\fP of file \fBZone\&.cs\fP\&.
.SS "virtual int Zone\&.BaseElectricity\fR [get]\fP"

.PP
Definition at line \fB968\fP of file \fBZone\&.cs\fP\&.
.SS "virtual float Zone\&.BigDaddyChance\fR [get]\fP"

.PP
Definition at line \fB611\fP of file \fBZone\&.cs\fP\&.
.SS "\fBBiomeProfile\fP Zone\&.biome\fR [get]\fP"

.PP
Definition at line \fB86\fP of file \fBZone\&.cs\fP\&.
.SS "virtual bool Zone\&.BlockBorderExit\fR [get]\fP"

.PP
Definition at line \fB251\fP of file \fBZone\&.cs\fP\&.
.SS "\fBChara\fP Zone\&.Boss\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB18\fP of file \fBZone\&.cs\fP\&.
.SS "virtual bool Zone\&.CanBeDeliverDestination\fR [get]\fP"

.PP
Definition at line \fB361\fP of file \fBZone\&.cs\fP\&.
.SS "virtual bool Zone\&.CanDigUnderground\fR [get]\fP"

.PP
Definition at line \fB471\fP of file \fBZone\&.cs\fP\&.
.SS "bool Zone\&.CanEnterBuildMode\fR [get]\fP"

.PP
Definition at line \fB908\fP of file \fBZone\&.cs\fP\&.
.SS "bool Zone\&.CanEnterBuildModeAnywhere\fR [get]\fP"

.PP
Definition at line \fB918\fP of file \fBZone\&.cs\fP\&.
.SS "bool Zone\&.CanInspect\fR [get]\fP"

.PP
Implements \fBIInspect\fP\&.
.PP
Definition at line \fB988\fP of file \fBZone\&.cs\fP\&.
.SS "virtual bool Zone\&.CanUnlockExit\fR [get]\fP"

.PP
Definition at line \fB491\fP of file \fBZone\&.cs\fP\&.
.SS "virtual float Zone\&.ChanceSpawnNeutral\fR [get]\fP"

.PP
Definition at line \fB671\fP of file \fBZone\&.cs\fP\&.
.SS "virtual bool Zone\&.CountDeepestLevel\fR [get]\fP"

.PP
Definition at line \fB371\fP of file \fBZone\&.cs\fP\&.
.SS "override int Zone\&.DangerLv\fR [get]\fP"

.PP
Definition at line \fB32\fP of file \fBZone\&.cs\fP\&.
.SS "virtual \fBActionMode\fP Zone\&.DefaultActionMode\fR [get]\fP"

.PP
Definition at line \fB241\fP of file \fBZone\&.cs\fP\&.
.SS "virtual bool Zone\&.DisableRooms\fR [get]\fP"

.PP
Definition at line \fB46\fP of file \fBZone\&.cs\fP\&.
.SS "virtual float Zone\&.EvolvedChance\fR [get]\fP"

.PP
Definition at line \fB621\fP of file \fBZone\&.cs\fP\&.
.SS "virtual int Zone\&.ExpireDays\fR [get]\fP"

.PP
Definition at line \fB261\fP of file \fBZone\&.cs\fP\&.
.SS "virtual ZoneFeatureType Zone\&.FeatureType\fR [get]\fP"

.PP
Definition at line \fB281\fP of file \fBZone\&.cs\fP\&.
.SS "virtual FlockController\&.SpawnType Zone\&.FlockType\fR [get]\fP"

.PP
Definition at line \fB827\fP of file \fBZone\&.cs\fP\&.
.SS "MapGenerator Zone\&.Generator\fR [get]\fP"

.PP
Definition at line \fB137\fP of file \fBZone\&.cs\fP\&.
.SS "virtual bool Zone\&.GrowPlant\fR [get]\fP"

.PP
Definition at line \fB681\fP of file \fBZone\&.cs\fP\&.
.SS "virtual bool Zone\&.GrowWeed\fR [get]\fP"

.PP
Definition at line \fB691\fP of file \fBZone\&.cs\fP\&.
.SS "virtual bool Zone\&.HasLaw\fR [get]\fP"

.PP
Definition at line \fB381\fP of file \fBZone\&.cs\fP\&.
.SS "virtual bool Zone\&.HiddenInRegionMap\fR [get]\fP"

.PP
Definition at line \fB811\fP of file \fBZone\&.cs\fP\&.
.SS "int Zone\&.HourSinceLastActive\fR [get]\fP"

.PP
Definition at line \fB56\fP of file \fBZone\&.cs\fP\&.
.SS "virtual string Zone\&.IDAmbience\fR [get]\fP"

.PP
Definition at line \fB291\fP of file \fBZone\&.cs\fP\&.
.SS "virtual string Zone\&.IDBaseLandFeat\fR [get]\fP"

.PP
Definition at line \fB187\fP of file \fBZone\&.cs\fP\&.
.SS "virtual string Zone\&.IdBiome\fR [get]\fP"

.PP
Definition at line \fB101\fP of file \fBZone\&.cs\fP\&.
.SS "virtual string Zone\&.idExport\fR [get]\fP"

.PP
Definition at line \fB197\fP of file \fBZone\&.cs\fP\&.
.SS "virtual string Zone\&.IDGenerator\fR [get]\fP"

.PP
Definition at line \fB117\fP of file \fBZone\&.cs\fP\&.
.SS "virtual string Zone\&.IDHat\fR [get]\fP"

.PP
Definition at line \fB177\fP of file \fBZone\&.cs\fP\&.
.SS "virtual string Zone\&.IDPlayList\fR [get]\fP"

.PP
Definition at line \fB157\fP of file \fBZone\&.cs\fP\&.
.SS "virtual string Zone\&.IDPlaylistOverwrite\fR [get]\fP"

.PP
Definition at line \fB167\fP of file \fBZone\&.cs\fP\&.
.SS "virtual string Zone\&.IdProfile\fR [get]\fP"

.PP
Definition at line \fB147\fP of file \fBZone\&.cs\fP\&.
.SS "virtual string Zone\&.IDSceneTemplate\fR [get]\fP"

.PP
Definition at line \fB309\fP of file \fBZone\&.cs\fP\&.
.SS "virtual string Zone\&.IDSubset\fR [get]\fP"

.PP
Definition at line \fB337\fP of file \fBZone\&.cs\fP\&.
.SS "string Zone\&.InspectName\fR [get]\fP"

.PP
Implements \fBIInspect\fP\&.
.PP
Definition at line \fB998\fP of file \fBZone\&.cs\fP\&.
.SS "\fBPoint\fP Zone\&.InspectPoint\fR [get]\fP"

.PP
Implements \fBIInspect\fP\&.
.PP
Definition at line \fB1008\fP of file \fBZone\&.cs\fP\&.
.SS "Vector3 Zone\&.InspectPosition\fR [get]\fP"

.PP
Implements \fBIInspect\fP\&.
.PP
Definition at line \fB1018\fP of file \fBZone\&.cs\fP\&.
.SS "bool Zone\&.IsActiveZone\fR [get]\fP"

.PP
Definition at line \fB978\fP of file \fBZone\&.cs\fP\&.
.SS "virtual bool Zone\&.IsExplorable\fR [get]\fP"

.PP
Definition at line \fB701\fP of file \fBZone\&.cs\fP\&.
.SS "virtual bool Zone\&.IsFestival\fR [get]\fP"

.PP
Definition at line \fB327\fP of file \fBZone\&.cs\fP\&.
.SS "bool Zone\&.IsInstance\fR [get]\fP"

.PP
Definition at line \fB948\fP of file \fBZone\&.cs\fP\&.
.SS "bool Zone\&.IsLoaded\fR [get]\fP"

.PP
Definition at line \fB958\fP of file \fBZone\&.cs\fP\&.
.SS "virtual bool Zone\&.IsNefia\fR [get]\fP"

.PP
Definition at line \fB531\fP of file \fBZone\&.cs\fP\&.
.SS "bool Zone\&.IsPCFaction\fR [get]\fP"

.PP
Definition at line \fB928\fP of file \fBZone\&.cs\fP\&.
.SS "virtual bool Zone\&.IsReturnLocation\fR [get]\fP"

.PP
Definition at line \fB711\fP of file \fBZone\&.cs\fP\&.
.SS "virtual bool Zone\&.IsSkyLevel\fR [get]\fP"

.PP
Definition at line \fB451\fP of file \fBZone\&.cs\fP\&.
.SS "bool Zone\&.IsStartZone\fR [get]\fP"

.PP
Definition at line \fB938\fP of file \fBZone\&.cs\fP\&.
.SS "virtual bool Zone\&.IsTown\fR [get]\fP"

.PP
Definition at line \fB351\fP of file \fBZone\&.cs\fP\&.
.SS "virtual bool Zone\&.IsUserZone\fR [get]\fP"

.PP
Definition at line \fB461\fP of file \fBZone\&.cs\fP\&.
.SS "virtual bool Zone\&.KeepAllyDistance\fR [get]\fP"

.PP
Definition at line \fB561\fP of file \fBZone\&.cs\fP\&.
.SS "virtual bool Zone\&.LockExit\fR [get]\fP"

.PP
Definition at line \fB481\fP of file \fBZone\&.cs\fP\&.
.SS "virtual bool Zone\&.MakeEnemiesNeutral\fR [get]\fP"

.PP
Definition at line \fB391\fP of file \fBZone\&.cs\fP\&.
.SS "virtual bool Zone\&.MakeTownProperties\fR [get]\fP"

.PP
Definition at line \fB401\fP of file \fBZone\&.cs\fP\&.
.SS "virtual int Zone\&.MaxLv\fR [get]\fP"

.PP
Definition at line \fB501\fP of file \fBZone\&.cs\fP\&.
.SS "int Zone\&.MaxRespawn\fR [get]\fP"

.PP
Definition at line \fB581\fP of file \fBZone\&.cs\fP\&.
.SS "virtual int Zone\&.MaxSpawn\fR [get]\fP"

.PP
Definition at line \fB571\fP of file \fBZone\&.cs\fP\&.
.SS "virtual int Zone\&.MinLv\fR [get]\fP"

.PP
Definition at line \fB511\fP of file \fBZone\&.cs\fP\&.
.SS "int Zone\&.MinsSinceLastActive\fR [get]\fP"

.PP
Definition at line \fB66\fP of file \fBZone\&.cs\fP\&.
.SS "override string Zone\&.NameSuffix\fR [get]\fP"

.PP
Definition at line \fB856\fP of file \fBZone\&.cs\fP\&.
.SS "string Zone\&.NameWithLevel\fR [get]\fP"

.PP
Definition at line \fB870\fP of file \fBZone\&.cs\fP\&.
.SS "virtual float Zone\&.OreChance\fR [get]\fP"

.PP
Definition at line \fB601\fP of file \fBZone\&.cs\fP\&.
.SS "\fBZone\fP Zone\&.ParentZone\fR [get]\fP"

.PP
Definition at line \fB231\fP of file \fBZone\&.cs\fP\&.
.SS "virtual string Zone\&.pathExport\fR [get]\fP"

.PP
Definition at line \fB76\fP of file \fBZone\&.cs\fP\&.
.SS "string Zone\&.pathTemp\fR [get]\fP"

.PP
Definition at line \fB211\fP of file \fBZone\&.cs\fP\&.
.SS "virtual bool Zone\&.PetFollow\fR [get]\fP"

.PP
Definition at line \fB541\fP of file \fBZone\&.cs\fP\&.
.SS "virtual float Zone\&.PrespawnRate\fR [get]\fP"

.PP
Definition at line \fB641\fP of file \fBZone\&.cs\fP\&.
.SS "virtual bool Zone\&.RegenerateOnEnter\fR [get]\fP"

.PP
Definition at line \fB441\fP of file \fBZone\&.cs\fP\&.
.SS "\fBRegion\fP Zone\&.Region\fR [get]\fP"

.PP
Definition at line \fB221\fP of file \fBZone\&.cs\fP\&.
.SS "virtual ZoneTransition\&.EnterState Zone\&.RegionEnterState\fR [get]\fP"

.PP
Definition at line \fB271\fP of file \fBZone\&.cs\fP\&.
.SS "virtual int Zone\&.RespawnPerHour\fR [get]\fP"

.PP
Definition at line \fB661\fP of file \fBZone\&.cs\fP\&.
.SS "virtual float Zone\&.RespawnRate\fR [get]\fP"

.PP
Definition at line \fB651\fP of file \fBZone\&.cs\fP\&.
.SS "virtual bool Zone\&.RestrictBuild\fR [get]\fP"

.PP
Definition at line \fB551\fP of file \fBZone\&.cs\fP\&.
.SS "virtual bool Zone\&.RevealRoom\fR [get]\fP"

.PP
Definition at line \fB761\fP of file \fBZone\&.cs\fP\&.
.SS "virtual float Zone\&.RuinChance\fR [get]\fP"

.PP
Definition at line \fB591\fP of file \fBZone\&.cs\fP\&.
.SS "virtual bool Zone\&.ScaleMonsterLevel\fR [get]\fP"

.PP
Definition at line \fB801\fP of file \fBZone\&.cs\fP\&.
.SS "virtual bool Zone\&.ShouldAutoRevive\fR [get]\fP"

.PP
Definition at line \fB741\fP of file \fBZone\&.cs\fP\&.
.SS "virtual bool Zone\&.ShouldMakeExit\fR [get]\fP"

.PP
Definition at line \fB721\fP of file \fBZone\&.cs\fP\&.
.SS "virtual bool Zone\&.ShouldRegenerate\fR [get]\fP"

.PP
Definition at line \fB731\fP of file \fBZone\&.cs\fP\&.
.SS "virtual float Zone\&.ShrineChance\fR [get]\fP"

.PP
Definition at line \fB631\fP of file \fBZone\&.cs\fP\&.
.SS "virtual int Zone\&.StartLV\fR [get]\fP"

.PP
Definition at line \fB791\fP of file \fBZone\&.cs\fP\&.
.SS "string Zone\&.TextDeepestLv\fR [get]\fP"

.PP
Definition at line \fB894\fP of file \fBZone\&.cs\fP\&.
.SS "virtual string Zone\&.TextWidgetDate\fR [get]\fP"

.PP
Definition at line \fB127\fP of file \fBZone\&.cs\fP\&.
.SS "virtual bool Zone\&.UseFog\fR [get]\fP"

.PP
Definition at line \fB751\fP of file \fBZone\&.cs\fP\&.
.SS "virtual bool Zone\&.UseLight\fR [get]\fP"

.PP
Definition at line \fB781\fP of file \fBZone\&.cs\fP\&.
.SS "virtual bool Zone\&.WillAutoSave\fR [get]\fP"

.PP
Definition at line \fB431\fP of file \fBZone\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
