.TH "ZoneProfile.Seeds" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ZoneProfile.Seeds
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBheight\fP"
.br
.ti -1c
.RI "int \fBpoi\fP"
.br
.ti -1c
.RI "int \fBbiome\fP"
.br
.ti -1c
.RI "int \fBbiomeSub\fP"
.br
.ti -1c
.RI "int \fBbush\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB127\fP of file \fBZoneProfile\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int ZoneProfile\&.Seeds\&.biome"

.PP
Definition at line \fB136\fP of file \fBZoneProfile\&.cs\fP\&.
.SS "int ZoneProfile\&.Seeds\&.biomeSub"

.PP
Definition at line \fB139\fP of file \fBZoneProfile\&.cs\fP\&.
.SS "int ZoneProfile\&.Seeds\&.bush"

.PP
Definition at line \fB142\fP of file \fBZoneProfile\&.cs\fP\&.
.SS "int ZoneProfile\&.Seeds\&.height"

.PP
Definition at line \fB130\fP of file \fBZoneProfile\&.cs\fP\&.
.SS "int ZoneProfile\&.Seeds\&.poi"

.PP
Definition at line \fB133\fP of file \fBZoneProfile\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
