.TH "ZoneInspector.ResizeUtil" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ZoneInspector.ResizeUtil
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBApply\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBnewSize\fP"
.br
.ti -1c
.RI "Vector2Int \fBoffset\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB209\fP of file \fBZoneInspector\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void ZoneInspector\&.ResizeUtil\&.Apply ()"

.PP
Definition at line \fB212\fP of file \fBZoneInspector\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int ZoneInspector\&.ResizeUtil\&.newSize"

.PP
Definition at line \fB225\fP of file \fBZoneInspector\&.cs\fP\&.
.SS "Vector2Int ZoneInspector\&.ResizeUtil\&.offset"

.PP
Definition at line \fB228\fP of file \fBZoneInspector\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
