.TH "ZoneBlueprint.MapGenSetting" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ZoneBlueprint.MapGenSetting
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBseed\fP"
.br
.ti -1c
.RI "\fBMapGenVariation\fP \fBvariation\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB107\fP of file \fBZoneBlueprint\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int ZoneBlueprint\&.MapGenSetting\&.seed"

.PP
Definition at line \fB110\fP of file \fBZoneBlueprint\&.cs\fP\&.
.SS "\fBMapGenVariation\fP ZoneBlueprint\&.MapGenSetting\&.variation"

.PP
Definition at line \fB113\fP of file \fBZoneBlueprint\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
