.TH "ZoneProfile" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ZoneProfile
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBEScriptable\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSeeds\fP"
.br
.in -1c
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBGenType\fP { \fBDefault\fP, \fBSky\fP, \fBUnderground\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBGenerate\fP ()"
.br
.ti -1c
.RI "void \fBRerollBiome\fP ()"
.br
.ti -1c
.RI "void \fBRerollBiomeSub\fP ()"
.br
.ti -1c
.RI "void \fBRerollBush\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBZoneProfile\fP \fBLoad\fP (string id)"
.br
.in -1c

Static Public Member Functions inherited from \fBEScriptable\fP
.in +1c
.ti -1c
.RI "static int \fBrnd\fP (int a)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBMapGenVariation\fP \fBvariation\fP"
.br
.ti -1c
.RI "\fBMapHeight\fP \fBheight\fP"
.br
.ti -1c
.RI "\fBZoneProfile\&.Seeds\fP \fBseeds\fP"
.br
.ti -1c
.RI "int \fBsize\fP = 200"
.br
.ti -1c
.RI "int \fBsizeBounds\fP"
.br
.ti -1c
.RI "int \fBoffsetX\fP"
.br
.ti -1c
.RI "int \fBoffsetZ\fP"
.br
.ti -1c
.RI "int \fBblockHeight\fP"
.br
.ti -1c
.RI "int \fBwater\fP"
.br
.ti -1c
.RI "int \fBbushMod\fP = 2"
.br
.ti -1c
.RI "int \fBextraShores\fP"
.br
.ti -1c
.RI "float \fBshoreHeight\fP"
.br
.ti -1c
.RI "float \fBbiomeSubScale\fP = 5f"
.br
.ti -1c
.RI "bool \fBisShore\fP"
.br
.ti -1c
.RI "bool \fBsetShore\fP = true"
.br
.ti -1c
.RI "bool \fBnoWater\fP"
.br
.ti -1c
.RI "bool \fBriver\fP = true"
.br
.ti -1c
.RI "bool \fBuseRootSize\fP"
.br
.ti -1c
.RI "bool \fBindoor\fP"
.br
.ti -1c
.RI "bool \fBclearEdge\fP"
.br
.ti -1c
.RI "string \fBidSceneProfile\fP"
.br
.ti -1c
.RI "ZoneProfile\&.GenType \fBgenType\fP"
.br
.ti -1c
.RI "MapBG \fBmapBG\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB5\fP of file \fBZoneProfile\&.cs\fP\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "enum ZoneProfile\&.GenType"

.PP
Definition at line \fB115\fP of file \fBZoneProfile\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void ZoneProfile\&.Generate ()"

.PP
Definition at line \fB14\fP of file \fBZoneProfile\&.cs\fP\&.
.SS "static \fBZoneProfile\fP ZoneProfile\&.Load (string id)\fR [static]\fP"

.PP
Definition at line \fB8\fP of file \fBZoneProfile\&.cs\fP\&.
.SS "void ZoneProfile\&.RerollBiome ()"

.PP
Definition at line \fB25\fP of file \fBZoneProfile\&.cs\fP\&.
.SS "void ZoneProfile\&.RerollBiomeSub ()"

.PP
Definition at line \fB32\fP of file \fBZoneProfile\&.cs\fP\&.
.SS "void ZoneProfile\&.RerollBush ()"

.PP
Definition at line \fB39\fP of file \fBZoneProfile\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "float ZoneProfile\&.biomeSubScale = 5f"

.PP
Definition at line \fB82\fP of file \fBZoneProfile\&.cs\fP\&.
.SS "int ZoneProfile\&.blockHeight"

.PP
Definition at line \fB67\fP of file \fBZoneProfile\&.cs\fP\&.
.SS "int ZoneProfile\&.bushMod = 2"

.PP
Definition at line \fB73\fP of file \fBZoneProfile\&.cs\fP\&.
.SS "bool ZoneProfile\&.clearEdge"

.PP
Definition at line \fB103\fP of file \fBZoneProfile\&.cs\fP\&.
.SS "int ZoneProfile\&.extraShores"

.PP
Definition at line \fB76\fP of file \fBZoneProfile\&.cs\fP\&.
.SS "ZoneProfile\&.GenType ZoneProfile\&.genType"

.PP
Definition at line \fB109\fP of file \fBZoneProfile\&.cs\fP\&.
.SS "\fBMapHeight\fP ZoneProfile\&.height"

.PP
Definition at line \fB49\fP of file \fBZoneProfile\&.cs\fP\&.
.SS "string ZoneProfile\&.idSceneProfile"

.PP
Definition at line \fB106\fP of file \fBZoneProfile\&.cs\fP\&.
.SS "bool ZoneProfile\&.indoor"

.PP
Definition at line \fB100\fP of file \fBZoneProfile\&.cs\fP\&.
.SS "bool ZoneProfile\&.isShore"

.PP
Definition at line \fB85\fP of file \fBZoneProfile\&.cs\fP\&.
.SS "MapBG ZoneProfile\&.mapBG"

.PP
Definition at line \fB112\fP of file \fBZoneProfile\&.cs\fP\&.
.SS "bool ZoneProfile\&.noWater"

.PP
Definition at line \fB91\fP of file \fBZoneProfile\&.cs\fP\&.
.SS "int ZoneProfile\&.offsetX"

.PP
Definition at line \fB61\fP of file \fBZoneProfile\&.cs\fP\&.
.SS "int ZoneProfile\&.offsetZ"

.PP
Definition at line \fB64\fP of file \fBZoneProfile\&.cs\fP\&.
.SS "bool ZoneProfile\&.river = true"

.PP
Definition at line \fB94\fP of file \fBZoneProfile\&.cs\fP\&.
.SS "\fBZoneProfile\&.Seeds\fP ZoneProfile\&.seeds"

.PP
Definition at line \fB52\fP of file \fBZoneProfile\&.cs\fP\&.
.SS "bool ZoneProfile\&.setShore = true"

.PP
Definition at line \fB88\fP of file \fBZoneProfile\&.cs\fP\&.
.SS "float ZoneProfile\&.shoreHeight"

.PP
Definition at line \fB79\fP of file \fBZoneProfile\&.cs\fP\&.
.SS "int ZoneProfile\&.size = 200"

.PP
Definition at line \fB55\fP of file \fBZoneProfile\&.cs\fP\&.
.SS "int ZoneProfile\&.sizeBounds"

.PP
Definition at line \fB58\fP of file \fBZoneProfile\&.cs\fP\&.
.SS "bool ZoneProfile\&.useRootSize"

.PP
Definition at line \fB97\fP of file \fBZoneProfile\&.cs\fP\&.
.SS "\fBMapGenVariation\fP ZoneProfile\&.variation"

.PP
Definition at line \fB46\fP of file \fBZoneProfile\&.cs\fP\&.
.SS "int ZoneProfile\&.water"

.PP
Definition at line \fB70\fP of file \fBZoneProfile\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
