.TH "ZoneInspector.FillUtil" 3 "Elin Modding Docs Doc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ZoneInspector.FillUtil
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBFlattenHeight\fP ()"
.br
.ti -1c
.RI "void \fBFillFloor\fP ()"
.br
.ti -1c
.RI "void \fBFillBlock\fP ()"
.br
.ti -1c
.RI "void \fBClearBlock\fP ()"
.br
.ti -1c
.RI "void \fBClearObj\fP ()"
.br
.ti -1c
.RI "void \fBClearBridge\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBflatHeight\fP"
.br
.ti -1c
.RI "int \fBfillFloor\fP = 5"
.br
.ti -1c
.RI "int \fBfillBlock\fP = 1"
.br
.ti -1c
.RI "bool \fBrandomFillDir\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB136\fP of file \fBZoneInspector\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void ZoneInspector\&.FillUtil\&.ClearBlock ()"

.PP
Definition at line \fB169\fP of file \fBZoneInspector\&.cs\fP\&.
.SS "void ZoneInspector\&.FillUtil\&.ClearBridge ()"

.PP
Definition at line \fB187\fP of file \fBZoneInspector\&.cs\fP\&.
.SS "void ZoneInspector\&.FillUtil\&.ClearObj ()"

.PP
Definition at line \fB178\fP of file \fBZoneInspector\&.cs\fP\&.
.SS "void ZoneInspector\&.FillUtil\&.FillBlock ()"

.PP
Definition at line \fB159\fP of file \fBZoneInspector\&.cs\fP\&.
.SS "void ZoneInspector\&.FillUtil\&.FillFloor ()"

.PP
Definition at line \fB149\fP of file \fBZoneInspector\&.cs\fP\&.
.SS "void ZoneInspector\&.FillUtil\&.FlattenHeight ()"

.PP
Definition at line \fB139\fP of file \fBZoneInspector\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int ZoneInspector\&.FillUtil\&.fillBlock = 1"

.PP
Definition at line \fB202\fP of file \fBZoneInspector\&.cs\fP\&.
.SS "int ZoneInspector\&.FillUtil\&.fillFloor = 5"

.PP
Definition at line \fB199\fP of file \fBZoneInspector\&.cs\fP\&.
.SS "int ZoneInspector\&.FillUtil\&.flatHeight"

.PP
Definition at line \fB196\fP of file \fBZoneInspector\&.cs\fP\&.
.SS "bool ZoneInspector\&.FillUtil\&.randomFillDir"

.PP
Definition at line \fB205\fP of file \fBZoneInspector\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Elin Modding Docs Doc from the source code\&.
